### ISSUE TITLE
Other languages beyond Polish -- with same surname tradition

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1000]
On Family trees preferences page in Surname tradition list I suggest "some Slavic" instead of "Polish".

As I see the same surname tradition is true in [Bulgarian](https://en.wikipedia.org/wiki/Bulgarian_name#Bulgarian_patronymics_and_family_names), [Czech](https://en.wikipedia.org/wiki/Czech_name#Female_surnames), [Eastern Slavic](https://en.wikipedia.org/wiki/Eastern_Slavic_naming_customs#Patronymic) (redirected from Russian), [Polish](https://en.wikipedia.org/wiki/Polish_name#Examples_of_feminine_and_neutral_forms), [Slovak](https://en.wikipedia.org/wiki/Slovak_name#Surnames), etc. languages (but, unfortunately there is nothing remarkable on [Croatian family names](https://en.wikipedia.org/wiki/Croatian_name#Croatian_family_names), [Serbian surnames](https://en.wikipedia.org/wiki/Serbian_names#Surnames), [Ukrainian surnames](https://en.wikipedia.org/wiki/Ukrainian_surnames), etc. Wikipedia pages and didn't found Slovene or Slovenian names, etc. on Wikipedia).

What do you think? I don't understand, why the affected users and/or developers said nothing... Or am I wrong?

**Comment by wooc** [comment]
As I know Polish is a little different than Russian and Slovak.

**Comment by tunandras** [comment]
> As I know Polish is a little different than Russian and Slovak.

Yes, you are right. Polish, Russian, Slovak, etc. languages are separate and independent languages. I agree.

But, as I read in the quoted articles, their surname tradition is similar: children inherit their father's surname, traditionally on marriage women gets their husband's surname, and the end of their surname is indicating their gender.

So, their surname tradition is similar. Is that true?

**Comment by wooc** [comment]
> But, as I read in the quoted articles, their surname tradition is similar: children inherit their father's 
>  surname,  traditionally on marriage women gets their husband's surname, and the end of their 
> surname is indicating their gender.
> So, their surname tradition is similar. Is that true?
It's true. The difference is the end of surname. Moreover, a lot of surnames in Polish surname tradition are identical in women and men version.
For example:
Surname Kostun in Slovakia is husband version and Kostunova is his wife version.
In Polish Kostun is for husband and and his wife.

**Comment by fisharebest** [comment]
The code for surname tradition is modular.
It is simple to add rules for other languages.

If somebody from Slovakia, Russia, etc. will provide the details for their language, then we will add them.

But we should not "guess" for another language.

**Comment by tunandras** [comment]
> But we should not "guess" for another language.

You are right. Sorry, it's my fault. I misunderstood the list. I should not have commented this...

**Comment by fisharebest** [comment]
> I should not have commented this...
