### ISSUE TITLE
Add source citation works not conform to gedcom structure (was #941)

### ISSUE THREAD

**Issue by mpwt** [fisharebest/webtrees#1002]
Sorry, but the edit_interface.php not works how we had discussed earlier. If I want to add a soure citation (with date of entry) webtrees 1.7.5 saves it as:
```
2 SOUR @S29@
3 PAGE (XXX)
4 DATE 06 JUN 2009
```
instead of
```
2 SOUR @S29@
3 PAGE (XXX)
3 DATA
4 DATE 06 JUN 2009
```

If I want to insert an aditional text of this source citation later webtrees save it as:
```
2 SOUR @S29@
3 PAGE (XXX)
4 TEXT test
4 DATE 06 JUN 2009
```
The edit interface looks strange after
![addsourcecitation](https://cloud.githubusercontent.com/assets/16311627/16154376/d20aaffc-34aa-11e6-9ea9-4f99e05ac9d6.png)
In the old issue the position of 3 DATA was saved wrong but now it is missing completely.

**Comment by tronsmit** [comment]
Seems related to editing new facts

Re-editing an existing source (formatted correctly) with at least a 3 DATA 4 TEXT preserves a new 4 DATE addition

However, creating a new fact with only a 3 DATA 4 TEXT (no 4 DATE) then re-editing, produces two TEXT fields in the edit interface for the same source

**Comment by fisharebest** [comment]
It is frustrating that this was not discovered before the 1.7.5 release :-(

**Comment by fisharebest** [comment]
This is a major bug.  I will create a new release of webtrees (1.7.6) tomorrow.

**Comment by mpwt** [comment]
Sorry. I found this problem few days earlier after checking a gedcom export with a validator. But I could not reproduce the error with a local dev-installation so I delete the written error message within the old issue #941. 

Otherwise I was surprised that you have published the new release on thursday ...
