### ISSUE TITLE
Entities in the upgrade wizard?

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1004]
Are there &amp;lt; and &amp;gt; entities instead of less-than signs and greater-than signs in the upgrade wizard? (today's snapshot...)

![in_upgrade_wizard_ _2016-06-17_12 58 02](https://cloud.githubusercontent.com/assets/15856891/16154579/ca6c287e-34ab-11e6-8f02-44cd6ae63360.png)

String: **"Download %s…"**
[admin_site_upgrade.php](https://github.com/fisharebest/webtrees/blob/master/admin_site_upgrade.php)   (in `filename($download_url)` function, in line 242)
Weblate: [#1012](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=9cf5a9130e6d311415b6a869a26938f0)

**Comment by fisharebest** [comment]
I don't see this...

![untitled](https://cloud.githubusercontent.com/assets/2306088/16179194/4e801174-3656-11e6-9f15-5c8831758672.png)

**Comment by tunandras** [comment]
Maybe it's because of the localization. Didn't you escape the posted characters?

![upgrade_wizard_ _2016-06-17_12 58 02](https://cloud.githubusercontent.com/assets/15856891/16179350/6de0b728-3663-11e6-9d06-5d1954efb372.png)

**Comment by tunandras** [comment]
Today it was okay. No less-than sign and no greater-than sign appeared... :-)

![upgrade_wizard_ _webtrees_-_2016-06-23_16 23 34](https://cloud.githubusercontent.com/assets/15856891/16307552/f3564a70-3961-11e6-8091-a60eb9a417a3.png)

But, I don't know why the upgrade message was in English (on the Hungarian page). I tried it twice: signed out and signed in again.

![message_in_english](https://cloud.githubusercontent.com/assets/15856891/16307653/5d2fcdd6-3962-11e6-8856-df747753d5be.png)

(I don't remember what happened last time.)

**Comment by fisharebest** [comment]
> Today it was okay.

I think this was a problem in an old version of webtrees, which is now fixed.

**Comment by tunandras** [comment]
>I think this was a problem in an old version of webtrees, which is now fixed.

Yes, I agree. You fixed it in webtrees 1.7.6.
