### ISSUE TITLE
Maybe something was wrong with committing a translation file

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1007]
I think something was wrong with committing [this translation](https://github.com/fisharebest/webtrees/commit/9dfb7c64c574e4fa04ce8492cdb76bd4a419c15f) with 7 additions and **6,780 deletions**. It's not shown because the diff is too large. I downloaded the `webtrees-webtrees-hu.po` original translation file and its size is now 435,295 bytes while the previous was 686,293 bytes. What happened? Is this normal? I'm so desperate. Please help!
This is the end of it:

```
#. I18N: Location of an LDS church temple
#: app/GedcomCode/GedcomCodeTemp.php:159
msgid "The Hague, Netherlands"
msgstr "Hága, Hollandia"

#. I18N: Help text for the “Show a download link in the media viewer” configuration setting
#: admin_trees_config.php:1052
msgid ""
msgstr ""
```

**Comment by fisharebest** [comment]
> What happened?

There was a merge conflict in the file.  This confused weblate, which ignored everything after the conflict.

All translations are kept in weblate - including old ones.
All versions of the .PO files are kept in GitHub.
It is impossible to lose work!

**Comment by fisharebest** [comment]
PS - it will take weblate 5-10 minutes to reload the updated translation files.

**Comment by tunandras** [comment]
> It is impossible to lose work!

I was scared. It's all right now. Thank you very much for repairing the translation files.
