### ISSUE TITLE
Chart blok - displaying next generations in compact mode

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1011]
In the block configuration panel when you set the 'show details' option to 'no', the pedigree starts correctly in compact mode, but as soon as you click on one of the arrows the next generation comes in in full mode which is not correct. The next generation should open in compact mode as well.

Also see: https://github.com/fisharebest/webtrees/issues/963

**Comment by fisharebest** [comment]
I think this issue has been overtaken by #1283
