### ISSUE TITLE
"Undo" didn't changed to "Reject"

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1012]
"Undo" and "Undo all changes" phrases remained in Hungarian translation.

The `undo -> reject` and `approve -> accept` changes was committed in Fix: #955 - [consistent English text](https://github.com/fisharebest/webtrees/commit/1f16f0e9c6a9a685fb29127b26997880b0ba6b14) at June 18, 5:19 PM.

At that time one quarter of the Hungarian Weblate file was missing. Probably that is the reason why only two items changed in it contrary to other languages--where four.

I think it is be because of the merge conflict which caused the horrible deletion commented in #1007.

1.) Please change "Undo" to "Reject" and "Undo all changes" to "Reject all changes" in the Hungarian Weblate file.
2.) The questions are: When the end of the Hungarian translation file deleted and what happened more while one quarter of the file was missing?

**Comment by fisharebest** [comment]
The updated .PO files are being sent to the weblate server now.  It will take about 1 hour to import them.

**Comment by tunandras** [comment]
Thank you very much! :-)
