### ISSUE TITLE
A minor change in Statistics, Own charts

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1013]
In Statistics > Own charts tab > chart types from "Age related to birth year" to "Number of children".

Is it possible to swap the word "over" and the last value--at the right end of the horizontal axis--if the selected language is Hungarian? The "over 100" is in Hungarian "100 felett".

The key is in file [statisticsplot.php](https://github.com/fisharebest/webtrees/blob/master/statisticsplot.php) (on line 788).

Here is (probably not the best, but working) solution: if these five lines

    if (WT_LOCALE !== 'hu') {
        $xdata[$xmax]        = I18N::translate('over') . ' ' . $hulpar[$i - 1];
    } else {
        $xdata[$xmax]        = $hulpar[$i - 1] . ' ' . I18N::translate('over');
    }
replace the original one:

        $xdata[$xmax]        = I18N::translate('over') . ' ' . $hulpar[$i - 1];

then the English (or any other language) AND Hungarian result is:

![over_to_felett](https://cloud.githubusercontent.com/assets/15856891/16179182/6e6938aa-365e-11e6-903a-8ad203ab0887.png)

In my opinion a bit better solution would be to change the code as the lines are handled in the chart's legend (as the GEDCOM date localization). There the words and values are combined in strings, and the translator can decide the order in Weblate--as "before %s", "after %s", and "between %s and %s" is--somehow like this:

        /* I18N: %s is the last value on the X axis */
        $xdata[$xmax]        = I18N::translate('over %s', $hulpar[$i - 1]);

Maybe there are other languages too, which also need the order change. What do you think?

**Comment by fisharebest** [comment]
The solution is to use a placeholder.  e.g. "over %s"
