### ISSUE TITLE
Google Maps Individual Tab pop display - invalid html

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#1015]
Under certain (as yet undetermined) circumstances the HTML generated for the info window is invalid (see attached image)
![screen dump](https://cloud.githubusercontent.com/assets/104515/16187637/60c4a71e-36c9-11e6-98b0-8455c3dece8f.jpg)

**Comment by ddrury** [comment]
GoogleMapsModule.php line 1912 `$name=` missing `>` after $parent->getHtmlUrl() - (doesn't fix problem tho')

**Comment by fisharebest** [comment]
I've fixed the missing `>`.

You're right about the suspicous looking `<div>` elements.
