### ISSUE TITLE
Suggestion to modify a Help text

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1018]
I think there are always some inexperienced administrators who are not familiar with all preferences pages and all preferences options that webtrees have (as I do). When they see the next Help text on family trees Preferences page

![help_text_to_supplement](https://cloud.githubusercontent.com/assets/15856891/16192117/bf1e5b0c-36e7-11e6-91bb-e82d4d81960f.png)

it would be good for them to know where they can find the **Allow users to select their own theme** option. So, I suggest to add `on the Website preferences page` string to the sentence. Moreover, it would be really fine to link the supplementation for example like this (however, the HTML code is not usual in Weblate strings):

"on the `<a href="admin_site_config.php?action=site" target="_blank">Website preferences page</a>`."

The affected areas:
[admin_trees_config.php](https://github.com/fisharebest/webtrees/blob/master/admin_trees_config.php) (line 967)
Weblate: [#1289](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=a7dd6c1e3af3e8680c045abb6ed52315)

This is the result on my family tree Preferences page:

![help_text_with_link](https://cloud.githubusercontent.com/assets/15856891/16192180/138f089e-36e8-11e6-95a2-437497923cc4.png)

And, when I wrote these sentences and accomplished the modification in the Hungarian translation, I started to think. There are two main levels of settings for webtrees to work: website preferences and family trees preferences. So, with this option you can distinguish family trees. While users can select their own theme in one family tree--in others not. That's fine.

But, why we have the opportunity for setting the same in website preferences too? Are there higher level administrators, who can handle website preferences while others not? No, I think there is no such distinction between administrators. Then why do not enough the setting in family trees preferences window? Isn't it redundant to set on both surfaces--especially on Website preferences page? Here it is:

![option_in_website_prefs](https://cloud.githubusercontent.com/assets/15856891/16192405/63d4d8e6-36e9-11e6-912b-9e59da09dcc7.png)

I can't imagine the reason... I guess, I'll suggest to remove it from Website preferences. Am I wrong? What is your opinion? (If I'm right, then I wrote the first part of this comment in vain.)

**Comment by fisharebest** [comment]
The text is confusing because the function is confusing ;-)

Each tree has the option to show the theme menu at the top of the page.
If the tree does not show the menu, then a user can still change theme using their account settings.

However, we can disable this globally in the site settings.

In #658, I suggested that we remove the ability for users to select themes.  It would become a setting for administrators only.

My only concern is that some users will choose a theme for accessibility.  For example, some themes are easier to use with poor-vision, colour-blindness, dyslexia, etc.

I guess that since many users already disable theme-changing, and many sites are used by only one or two people, then this isn't a major problem.  The solution is to improve the accessibility of **all** themes!

**Comment by tunandras** [comment]
So, there are two questions now: 
1.) What to write into the Help text?
2.) What to do with theme menus?

**What to write into the Help text?**

> If the tree does not show the menu, then a user can still change theme using their account settings.

Now I understand (I said I'm not familiar with all options that webtrees have :D). Then probably Help text on family trees preferences page has to contain that this option determines the appearance of the dropdown selector on every page on the top for users of this tree but, there is another opportunity for them to change theme in their account page.

While on website preferences page better to write that the option could disable both for the users--the option to change themes on their account page and the dropdown selector which appears on every page on the top.

And that means the first part of my suggestion was not in vain. It would be good to put the reference (possibly the link) to website preferences page into the Help text in family trees preferences.

**What to do with theme menus?**

> My only concern is that some users will choose a theme for accessibility. For example, some themes are easier to use with poor-vision, colour-blindness, dyslexia, etc.

I agree. I had not thought of that.

**Comment by makitso** [comment]
Personally, the option to select a theme is useful in testing changes.

**Comment by fisharebest** [comment]
This text has since been rewritten.
