### ISSUE TITLE
Delete data/cache with update routine

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1020]
When upgrading from 1.7.4 to 1.7.5 I got a lot of wrong translations displayed. Some users reported that they gone some hours after upgrading. I found out that deleting the content of cache/data helps to fix this.
I think it would be a great idea to do this at the end of the upgrade routine.

**Comment by fisharebest** [comment]
The fix will be included in 1.7.7.
So, you will not see the effect until you ugrade from 1.7.7. to 1.7.8
