### ISSUE TITLE
Nicer Pending changes window

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1024]
webtrees is so nice and so informative... and the Pending changes window is a little bit as a stepchild.

File: [edit_changes.php](https://github.com/fisharebest/webtrees/blob/master/edit_changes.php)

**The original layout**

![pending_changes_orig](https://cloud.githubusercontent.com/assets/15856891/16232217/f23b575a-37c9-11e6-8375-8694cc102cc1.png)

My changes (and/or hopes):
Links are bold--all other is normal.
GEDCOM names are not linked. They are behind the commands--to align the content better (in my opinion it's clearer this way); the separator is dash instead of hyphen.
In the user field there are only real names. (Is username important?)

Styles in every table cell:
padding: 3px;
text-align: center;
vertical-align: middle;
white-space: nowrap;

Vertical distance between changes: 3px.

**The improved window**

![pending_changes_new_eng_plus](https://cloud.githubusercontent.com/assets/15856891/16236305/310cad36-37d8-11e6-81c4-9ddce990fb9b.png)

**The Hungarian window is a bit wider**

![pending_changes_new_hun](https://cloud.githubusercontent.com/assets/15856891/16232732/03909f72-37cc-11e6-952a-3d5ea13d95d1.png)

But when you click on Pending changes link the window's width is not the desired:

![narrow_window](https://cloud.githubusercontent.com/assets/15856891/16232314/5142c33c-37ca-11e6-8ed0-194ed3d96cb9.png)

​It would be good to see everything after the window opens.

**Comment by tunandras** [comment]
Sorry, I forgot to mention in my style changes: I leaved Accept all changes and Reject all changes commands and individuals' name left aligned.

**Comment by HonkXL** [comment]
Good idea. And plese display dates and times in the regional date format. It is a bit hard to read if you are used to use other date-formats.

**Comment by fisharebest** [comment]
> plese display dates and times in the regional date format

See #812

**Comment by tunandras** [comment]
Thank you! I'm glad you liked it. :-)

**Comment by tunandras** [comment]
Sorry, I realized now that you ignored the supplement I made a bit later in the next comment:

>I leaved Accept all changes and Reject all changes commands and individuals' name left aligned.

Was it on purpose?

**Comment by makitso** [comment]
Greg and I discussed this change and decided to keep the existing alignment.

**Comment by tunandras** [comment]
It's all right, if you like this way better... :-)
