### ISSUE TITLE
Missing translations into pt.mo, and the webtrees is not loading the pt-BR.mo through index.php

### ISSUE THREAD

**Issue by carlluiz** [fisharebest/webtrees#1026]
I'm having this issue with some words and phrases that are not been translated, but when I look the source code index.php, I saw that pt-BR.mo file is not included to load automatically.
But pt.mo file is included and this is that being loaded in webtrees... ok... Here in Brazil the pt.mo is also useful, but the problem is when we changing the language for the pt-BR.mo, because the translations are working correctly in my language ( pt-BR.mo ) and the pt.mo from Portugual is not.
Is it possible, or permitted, myself to fix this issue... translating directly the "original" in english, or just modifying the PHP file, without having to wait for new updates?
Thanks.

**Comment by fisharebest** [comment]
All translations are managed at https://translate.webtrees.net
Anyone can register on the site and update the translations.
The updated translations are added to webtrees automatically.
Usually, this happens within 24 hours.

> I saw that pt-BR.mo file is not included to load automatically.

**All** languages are enabled automatically.  So, if your web-browser is set to prefer pt-BR, then webtrees will use pt-BR.

But only the most popular languages are shown in the menu.  It is not possible or desirable to list all languages here.
You can control this list of languages using `Control panel` -> `Langauges`

> Is it possible, or permited, myself to correct this problem without having to wait for updates?

Yes!
You can update the translations in https://translate.webtrees.net
You can download the latest .MO files and install them on your server.

**Comment by carlluiz** [comment]
Ok, thank you very much.
