### ISSUE TITLE
I still found capitalized button labels

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1027]
Shame on me. I can't get rid of them. I'm very sorry. :-(

**Upload**
without "#. I18N: A button label." introduction

[admin_media_upload.php](https://github.com/fisharebest/webtrees/blob/master/admin_media_upload.php) (line 263)
Control panel =&gt; Media =&gt; Upload media files
[GoogleMapsModule.php](https://github.com/fisharebest/webtrees/blob/master/app/Module/GoogleMapsModule.php) (line 4193)
Control panel =&gt; Module =&gt; Module administration =&gt; Google Maps™ =&gt; Geographic data =&gt; Upload geographic data
Weblate: [#2970](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=91412465ea9169dfd901dd5e7c96dd99)

And the next ones are mentioned in "Convert button labels to lower-case?" (closed) [issue #966](https://github.com/fisharebest/webtrees/issues/966)

**View**
with "#. I18N: Submit button, on a form" new introduction (on most of the charts' pages)

[ancestry.php](https://github.com/fisharebest/webtrees/blob/master/ancestry.php) (line 92)
[FunctionsPrintFacts.php](https://github.com/fisharebest/webtrees/blob/master/app/Functions/FunctionsPrintFacts.php) (line 1028, 1060) I think these are not button labels (in contrast to the state of PO file)
[GoogleMapsModule.php](https://github.com/fisharebest/webtrees/blob/master/app/Module/GoogleMapsModule.php) (line 766)
[branches.php](https://github.com/fisharebest/webtrees/blob/master/branches.php) (line 49)
[compact.php](https://github.com/fisharebest/webtrees/blob/master/compact.php) (line 54)
[descendancy.php](https://github.com/fisharebest/webtrees/blob/master/descendancy.php) (line 71)
[familybook.php](https://github.com/fisharebest/webtrees/blob/master/familybook.php) (line 61)
[fanchart.php](https://github.com/fisharebest/webtrees/blob/master/fanchart.php) (line 95)
[hourglass.php](https://github.com/fisharebest/webtrees/blob/master/hourglass.php) (line 62)
[pedigree.php](https://github.com/fisharebest/webtrees/blob/master/pedigree.php) (line 169)
[relationship.php](https://github.com/fisharebest/webtrees/blob/master/relationship.php) (line 85)

Weblate: [#3024](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=4351cfebe4b61d8aa5efa1d020710005)

**Add**
[timeline.php](https://github.com/fisharebest/webtrees/blob/master/timeline.php) (line 304)
Weblate : [#212](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=ec211f7c20af43e742bf2570c3cb84f9)

**Comment by fisharebest** [comment]
Thanks.  I missed these...

**Comment by tunandras** [comment]
You are welcome! :-)

I have some questions.

There was (and is) a "View" (#. I18N: Submit button, on a form) until now. This name appeared on charts' button. What is it's function now? If I see well, a new "view" came in and replaced it. That took it's function.

And there is a button with a very similar function. It's name is "show" in Lifespans chart. (The only one "show" button on charts' pages.) Don't you want to rename this last one to "view"?

**Comment by fisharebest** [comment]
I have written some scripts that allow me to update the .PO files.  For example, I can create a new translation that based on an existing transation, and mark it "for review".

This is how I update the English text, without losing all the translated text.

But these scripts do not remove old translations, and they do not insert the "I18N: comments".
To do that, I would need to rebuild all the .PO files, which requires a lot of server resources.
