### ISSUE TITLE
Date conversion

### ISSUE THREAD

**Issue by Shemwell** [fisharebest/webtrees#1029]
I've noticed in the last few versions that if you enter a date as "Jan. 18, 1957" it does not properly convert to "18 JAN 1957", it correctly displays the date on the page "18 January 1957, but it does not convert and incorrectly enters it in the gedcom as "2 DATE JAN. 18, 1957" instead of "2 DATE 18 JAN 1957". I tested it on the demo site with the same result.

**Comment by tronsmit** [comment]
Is it the period after Jan that causes this?

**Comment by fisharebest** [comment]
Probably.  I haven't had time to look at the code.  If so, it will be easy to ignore.  We have special code to re-write US-format dates.

**Comment by Shemwell** [comment]
There's probably a better way, but if I add this: 

(/(JAN.)/,"JAN ");s=s.replace(/(FEB.)/,"FEB ");s=s.replace(/(MAR.)/,"MAR ");s=s.replace(/(APR.)/,"APR ");s=s.replace(/(JUN.)/,"JUN ");s=s.replace(/(JUL.)/,"JUL ");s=s.replace(/(AUG.)/,"AUG ");s=s.replace(/(SEP.)/,"SEP ");s=s.replace(/(SEPT.)/,"SEP");s=s.replace(/(OCT.)/,"OCT ");s=s.replace(/(NOV.)/,"NOV ");s=s.replace(/(DEC.)/,"DEC ");s=s.replace

after (/(DECEMBER)/,"DEC");s=s.replace in webtrees.js, it works.
