### ISSUE TITLE
History facts 

### ISSUE THREAD

**Issue by Gustine** [fisharebest/webtrees#1031]
In app/Module/IndividualFactsTabModule.php
line 139 perhaps should be _input id="checkbox_histo"_...
instead of _input id="checkbox_rela_facts"_...

And it would be nice that the « unchecked » option (for both _histo_ and _relatives_)  is activated by default.

**Comment by tronsmit** [comment]
I agree with the default state being unchecked.

On my site running 1.7.6 it seems, that both are unchecked, and neither are sticky (i.e. if you change their state and go to another record, you go back to the default), while in the latest development code the changes to close_relatives checkbox state sticks, while historical facts is always selected again when viewing another record or refreshing the page.

Should they not behave similarly?

**Comment by Gustine** [comment]
Sorry but default state is still « checked ».
An ordinary visitor (no cookie, no session) sees all relatives and historical facts displayed. And he don't know anything about checkboxes that must be unticked to clean the page.

**Comment by fisharebest** [comment]
> And it would be nice that the « unchecked » option (for both histo and relatives) is activated by default.

If the site owner installs historical facts, I think it is reasonable to display them by default.

A visitor will only need to untick them once.

> don't know anything about checkboxes that must be unticked to clean the page

I guess the same user would not find the tickbox to **show** these facts.

**Comment by Gustine** [comment]
Until now, these indications — historical and relatives facts as well — were only optional. And it was a good thing.

**Comment by tronsmit** [comment]
I agree with Gustine, the only reason to keep it checked for first time visitors, would be if it was essential for the persistent logic to work (which I don't know if it matters). It really is a minor issue, but I would like a first time viewer to focus on the individual details, and later explore the additional information available.

**Comment by JustCarmen** [comment]
Me too. I totally agree with Gustine and tronsmit that the default state should be unchecked. When a user sees too much details at once it will scare him off. I have never turned this option on and I would really like to keep it that way.

**Comment by Gustine** [comment]
Perfect! Thanks a lot.
