### ISSUE TITLE
May I remove the logo?

### ISSUE THREAD

**Issue by carlluiz** [fisharebest/webtrees#1033]
Hi,
Is it possible, or permitted, remove the webtrees logo and other features that I do not need? I'm asking because I'm trying to build two family trees... one for my family and other for my wife...
That's because we just need a simple, less complex, family tree. And I would like to put the "home link" of our page, replacing the webtrees logo/link. So I will build a website without google index search and other online search engines finding our page.
Just for fun. Webtrees is great, very professional, but we would like to share our data only between the relatives... Without death things, etc.
Thanks.

**Comment by fisharebest** [comment]
> Is it possible, or permitted, remove the webtrees logo

Yes.  The [GPLv3 licence](https://www.gnu.org/licenses/gpl.txt) allows you to do this.

The licence only restricts how you can distribute (i.e. give/sell to other people) the software.

On your own server, you can modify the software as you choose.

**Comment by carlluiz** [comment]
Ok... But how to get the completed source code to install in my server?

**Comment by carlluiz** [comment]
Thank you
