### ISSUE TITLE
Default family tree

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1034]
If there are multiple family trees on a site, what determines which Home page will be downloaded if the web URL at its end contains only index.php (or without it--as Demo menu's items  are coded on [webtrees](https://www.webtrees.net/) page)?

If I visit the demo site with https://dev.webtrees.net/demo-dev/ URL then (mostly) the Royal Family family tree's Home page is downloaded. After that if I switch to Greek Mythology's family tree using Family trees menu and close the tab (without signing in), next time using the same URL the Greek Mythology's Home page is downloaded. (That is my experience.)

Wouldn't it be a good idea to let the administrator set on Website preferences page which family tree should be the default?

I wonder which Home page should appear if someone signs out from any of the family trees on a site. (As I see if I sign out from either Demo family tree, I get to the Royal Family's Home page.)

**Comment by fisharebest** [comment]
> Wouldn't it be a good idea to let the administrator set on Website preferences page which family tree should be the default?

Control panel -> Manage family trees -> Set as default 

;-)

**Comment by tunandras** [comment]
> Control panel -> Manage family trees -> Set as default

Thanks! I can only hope to get such answers in my remaining life. :-)

I don't understand what happened... Why didn't I found it? Maybe I was searching only in website and family tree's Preferences pages... or on the site where I have just one family tree... (but, it's reasonable to hide the option there).
