### ISSUE TITLE
Modify chart menu items

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1037]
I used to have a custom link on the pedigree chart in my own (personal) theme.php file because I like to have the chart open by default with different settings.

But calling the function 'menuChartPedigree' from the theme file doesn't do anything anymore. This function is no longer in use, though it still exists in the Abtract theme, like other similar chart menu functions ('menuChartAncestors', 'menuChartCompact' etc.). Testing this by removing all the chart related submenu functions from the Abstract theme doesn't give different results. All the menu items still appear as submenu of the chart main menu.

This is because the function 'menuChart' doesn't call the submenu items from the Abstract theme but directly from the module files. If a module exists the submenu item is shown with the default settings set in the module files, regardless of the settings used in the (Abstract) theme file. The chart related functions in the Abstract theme are not in use anymore. I get the feeling this is not the way it was meant to be.

**Comment by fisharebest** [comment]
This was PR #884 by ric2016.

> chart open by default with different settings

Which different settings?

**Comment by JustCarmen** [comment]
> Which different settings?

I used to have customized link on the submenu item, so the pedigree opened with a different layout.

My code looked like this:
```
protected function menuChartPedigree(Individual $individual) {
		return new Menu(I18N::translate('Pedigree'), 'pedigree.php?rootid=' . $individual->getXref() . '&amp;' . $this->tree_url . '&amp;orientation=2&show_full=0', 'menu-chart-pedigree', array('rel' => 'nofollow'));
	}
```

Which lead to this layout:

![27-6-2016 06-14-43](https://cloud.githubusercontent.com/assets/5641963/16368470/de066dba-3c2e-11e6-8b1c-af65d2552e54.jpg)

But that's not my point. My point is that in AbstractTheme the function 'menuChartPedigree' exists and in theory should be over-writeable but it isn't.

The new function in AbstractTheme looks like this:
```
protected function menuChartPedigreeMap(Individual $individual) {
		$chart = new GoogleMapsModule(WT_ROOT . WT_MODULES_DIR . 'googlemap');

		return $chart->getChartMenu($individual);
	}
```

Looking in the chart module I found this function:

```
public function getChartMenu(Individual $individual) {
		return new Menu(
			$this->getTitle(),
			'pedigree.php?rootid=' . $individual->getXref() . '&amp;ged=' . $individual->getTree()->getNameUrl(),
			'menu-chart-pedigree',
			array('rel' => 'nofollow')
		);
	}
```

Which is similar as the function in my theme.php file, so again it should be no problem to overwrite the link with the one in the theme.php file.

But the function 'menuChartPedigree' in AbstractTheme never get called. It is overwritten by the 'menuChart' function (also in AbstractTheme):

```
protected function menuChart(Individual $individual) {
		$submenus = array();
		foreach (Module::getActiveCharts($this->tree) as $chart) {
			$menu = $chart->getChartMenu($individual);
			if ($menu) {
				$submenus[] = $menu;
			}
		}

		if ($submenus) {
			usort($submenus, function (Menu $x, Menu $y) {
				return I18N::strcasecmp($x->getLabel(), $y->getLabel());
			});

			return new Menu(I18N::translate('Charts'), '#', 'menu-chart', array('rel' => 'nofollow'), $submenus);
		} else {
			return null;
		}
	}

```
The latter never calls one of the menuChart... functions from AbstractTheme. So the whole list of functions in AbstractTheme from 'menuChartAncestors' to 'menuChartTimeline' is worthless.

I use Netbeans for coding. In the Netbeans navigator these functions are strike through, which means they aren't in use.

**Comment by ric2016** [comment]
> So the whole list of functions in AbstractTheme from 'menuChartAncestors' to 'menuChartTimeline' is worthless.

I think we have just kept them for compatibility, e.g. in case some other custom module calls them directly. They are not meant to be overridden anymore.

What about adding the chart with different settings as a new custom chart? Or maybe it's also a good idea to make these settings configurable for this chart, via the module administration?

**Comment by JustCarmen** [comment]
> I think we have just kept them for compatibility, e.g. in case some other custom module calls them directly. They are not meant to be overridden anymore.

So, finally we have a simple fully customizable theme system and then if we want to change a menu-link with this awesome theme system, the answer is: 'they are not meant to be overridden anymore'.

Huh?? So if I simple want to change a (part of) a menu item I have to make a whole new custom module? That sounds crazy, since all other menu items are customizable through the theme system.

**Comment by JustCarmen** [comment]
> Or maybe it's also a good idea to make these settings configurable for this chart, via the module administration?

That could be a suitable alternative.

**Comment by ric2016** [comment]
> So if I simple want to change a (part of) a menu item I have to make a whole new custom module? That sounds crazy, since all other menu items are customizable through the theme system. 

In fact, it sounds more reasonable to me: In my opinion, all menu items should be configurable as modules, and not via themes. Per the webtrees wiki, themes are intended for controlling "the style or appearance of a web page - colour, font, icon size, and the like", so it's a bit dubious to have a theme use customized links to charts etc. anyway. But this should probably be discussed elsewehere ...

**Comment by JustCarmen** [comment]
> In fact, it sounds more reasonable to me: In my opinion, all menu items should be configurable as modules, and not via themes. Per the webtrees wiki, themes are intended for controlling "the style or appearance of a web page - colour, font, icon size, and the like", so it's a bit dubious to have a theme use customized links to charts etc. anyway.

Ok, I got it. I would never change this stuff in my public themes either for the same reasons. But in my own personal theme I was used to have this option and I am not very happy with the fact it suddenly stops working, because I want my users to see the chart at start with the options I've set, in stead of the default settings.So your suggestion of making this possible through the module configuration sounds reasonable. In the meantime I think I will solve this with some jQuery.

**Comment by ric2016** [comment]
> I am not very happy with the fact it suddenly stops working

I agree - that shouldn't happen. We just didn't consider that use case, otherwise there would have been a warning at least.

**Comment by fisharebest** [comment]
> Or maybe it's also a good idea to make these settings configurable for this chart, via the module administration?

The "relationship chart" module does this.

**Comment by fisharebest** [comment]
> all menu items should be configurable as modules, and not via themes

In the latest dev code, you can now change the default by creating a custom module containing just this:

```
return new class extends Fisharebest\Webtrees\Module\PedigreeChartModule
{
    protected const DEFAULT_ORIENTATION = self::OLDEST_AT_TOP;
};
```

I'm still working on this, so it might change slightly before the stable release...
