### ISSUE TITLE
No more « Date differences »

### ISSUE THREAD

**Issue by Gustine** [fisharebest/webtrees#1040]
Version 1.7.7-dev.
Manage family trees > Preferences > Individual pages
It looks like the option « Date differences » was erased.

**Comment by fisharebest** [comment]
> It looks like the option « Date differences » was erased.

Yes.  This is now a "persistant" user setting.

The following options all work the same way.

* Show historical facts
* Show events of close relatives
* Show date differences
* Show all notes
* Show all sources

**Comment by Gustine** [comment]
OK I didn't see the new tickbox.
