### ISSUE TITLE
English - quotation/emphasis when refering to other things

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#1041]
When we refer to other parts of the system, we use different styles:

>  You can view this on your "my page".
> 
>  You can view this on your _my page_.
> 
>  You can view this on your **my page**.

We should do this consistently.

**Comment by JustCarmen** [comment]
I prefer the first one. In that sentence It is most clear that "my page" is referring to a term..

**Comment by fisharebest** [comment]
> I prefer the first one. In that sentence It is most clear that "my page" is referring to a term..

I am most familiar with the first one.  But perhaps this is because I look at webtrees all the time!

According to my (very old) book of English grammar:

* italics are used for emphasis and titles.
* quotation marks are used to refer to the words,

> _my page_ contains customisable blocks.
> "my page" is spelt using six letters.

So, this says we should use `<em></em>` - which in English is italic.

I would be keen to hear other views.

**Comment by tunandras** [comment]
> According to my (very old) book of English grammar

To be honest, I love italics. It is so nice. Specially designed and drawn but, unfortunately only serif fonts have italics font types. In my opinion your very old English grammar book is talking about serif fonts on printed media.

Actually we use sans serif font families and its emphasized type is oblique (the value of slanting is determined in degrees). The sans serif fonts has an advantage. Their line width is constant. And I guess, that is why it is usable, more displayable on pixel-based surfaces.

Please look at your example with serif and sans serif font families.

![italics](https://cloud.githubusercontent.com/assets/15856891/16498788/b5070e98-3efd-11e6-8d8f-01384595b134.png)

You can differentiate italics easily from normal for serif font families (the first block). It's true for nearly all of the letters especially for instance letter "a" in the example.

Regarding sans serif font families (the second block) the oblique is very slightly recognizable. It looks nearly the same as the normal.

So, I prefer quotation marks, even though it gives more task--regarding the language-dependent variant.

Sorry for the very long explanation.

**Comment by tunandras** [comment]
Sorry, I forgot to mention yesterday evening the third option.
I don't prefer bold since it would be ambiguous--we started to use bold to draw the attention on links. (Otherwise I would like it too.)

**Comment by eric215** [comment]
I like the italic style too but it can be too subtle on many screens.  More and more I find I'm using bold or a color for emphasis and getting away from quotation marks.

**Comment by fisharebest** [comment]
I think most (all) of these texts have been updated since this issue was raised.
