### ISSUE TITLE
Assortment of Geographic areas

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1042]
**Geographic areas** are drop-down menu options in **Statistics** &gt; **Own charts** tab--if you choose any of the last four **Chart types**.

What was the point of view when you selected these areas? Don't you want to extend the set? I was thinking about North America, United States (itself), Caribbean (or Middle America), Australia (or Oceania), etc.

I agree with your conclusion in #1041 (this is a trial in this issue) and would prefer bold (if all themes would have a link color ![facebook-blush-emoticon](https://cloud.githubusercontent.com/assets/15856891/16446685/1b8dd1d0-3de9-11e6-9163-64a5cc7b8782.png))...

**Comment by fisharebest** [comment]
We can only use the options provided by GoogleCharts.

See the `chtm` parameter https://developers.google.com/chart/image/docs/gallery/map_charts

The only other option is "United States".  I have added this.

**Comment by tunandras** [comment]
>The only other option is "United States".

I didn't think that Google leaves out a continent from the listed zoom areas. That is sad...

>I have added this.

But, it's good to supplement with the US. It's better than nothing. Thank you very much.
