### ISSUE TITLE
Uniform title style in all of Own charts

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1044]
The title style of the last four **Chart types** in **Statistics** > **Own charts** tab is varying from other title styles.

I think it would be better to set the same font size and emphasizing for all titles.

**Comment by tunandras** [comment]
Bad luck this time... :-(

Now this is the style of last four **Chart types**:

![style_of_title_of_last_four_chart_types](https://cloud.githubusercontent.com/assets/15856891/16476408/86722624-3e87-11e6-8285-c60c0486ed42.png)

and the other titles look like this:

![other_title_style](https://cloud.githubusercontent.com/assets/15856891/16476416/9f05bb38-3e87-11e6-86cb-592e05a35c2c.png)

**Comment by makitso** [comment]
I am sorry but I fail to see your issue.

**Comment by tunandras** [comment]
> I am sorry but I fail to see your issue.

Please select **Own charts** tab on demo-dev **[Statistics](https://dev.webtrees.net/demo-dev/statistics.php?ged=demo)** page. There you can create charts with titles styled the same way.

Styles by the first ten option in the list differ from the last four.

**Comment by makitso** [comment]
I am sorry but again I fail to see your point.  Yes, the last four charts are different, they are maps as opposed to bar charts.

**Comment by fisharebest** [comment]
If I understand correctly, the maps have an HTML title above the graphics, but the barcharts have a bitmap title embedded into the graphics.

One solution would be to use HTML titles on all graphs.

However, we're using bitmap graphs for compatibility with IE <=8.
Google Charts can generate SVG graphs, which look much better, and can have nice clear HTML titles.
