### ISSUE TITLE
A couple of capitalized button labels more

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1047]
[admin_trees_manage.php](https://github.com/fisharebest/webtrees/blob/master/admin_trees_manage.php)
**Delete** line 429
Weblate: [#930](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=f2a6c498fb90ee345d997f888fce3b18)
**Set as default** line 452
Weblate: [#2305](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=ffee71a61dfb978efbca62128a312bc1)

[admin_site_upgrade.php](https://github.com/fisharebest/webtrees/blob/master/admin_site_upgrade.php)
**Disable these modules** line 136
Weblate: [#974](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=0f8bdef8b53a9a4858b1cfdce72fa995)
**Disable these themes** line 200
Weblate: [#975](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=53a98b9ff4c4be88eab941d14d5737c1)
**Pending changes** line 99
Weblate: [#1991](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=0f5d2860d318b99d28c2b98e7d3dc5e7)
**Upgrade anyway** line 137, 201
Weblate: [#2926](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=738abca23790fc6d53c4f285e2b47c96)

[UserMessagesModule.php](https://github.com/fisharebest/webtrees/blob/master/app/Module/UserMessagesModule.php)
**Delete** line 139 (this is an extremely long line!)
Weblate: [#930](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=f2a6c498fb90ee345d997f888fce3b18)
**Delete selected messages** line 142
Weblate: [#933](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=b111197f1583cd7a91c33f4e89dce93d)
**Reply** line 137
Weblate: [#2178](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=25d8df6e580905091a0d5ef5b9e05bf0)

And maybe the buttons (almost 30 pieces) in the found table's headings:
[FunctionsPrintLists.php](https://github.com/fisharebest/webtrees/blob/master/app/Functions/FunctionsPrintLists.php)

Individuals:
![individuals](https://cloud.githubusercontent.com/assets/15856891/16449437/d6fb7180-3df7-11e6-8770-b3b480f8ab04.png)

Families:
![families](https://cloud.githubusercontent.com/assets/15856891/16449449/e4d43026-3df7-11e6-912b-17d5a0dbc7a6.png)

**Comment by fisharebest** [comment]
Although the first list of items have `<button>` markup, they also have `btn-link` styling, which makes them look and behave like link elements.  These should stay as they are.

The second list are labels, rather than actions. As such, there is no need to change them.
