### ISSUE TITLE
HTML block content problems

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1049]
The **HTML — Preferences** doesn't remember the selected template in its drop-down menu.

Selecting different languages doesn't change the main content of **HTML block** either in CKEditor window or--after saving--on the page.

**Comment by fisharebest** [comment]
The template is used to create a new block.

It is expected that the user will edit the block.

If the "select template" field has a value, it will reset the block to the template. 
This is probably not what the user intends.

**Comment by tunandras** [comment]
>If the "select template" field has a value, it will reset the block to the template.
>This is probably not what the user intends.

I agree.

Possibly the problem (and my fault) is that I didn't see the last item of the form where the "Show this block for which languages" option is.

Sorry for that.

**Comment by fisharebest** [comment]
No problem!
