### ISSUE TITLE
After fixing the inconsistency in alignment of messages

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1050]
I was very pleased in sight of fixing the inconsistency in alignment of messages (#948) and saw that they are all centered.

Thanks a lot! :-)

But there were some new behaviors...

I found--when changing a fact of or deleting an individual--the message and options to accept or reject changes migrated from "Individual's page" to "Home page" and "Pending changes" window.

Accepting or rejecting command is accomplished

- on "Home page"--and webtrees confirmed on the same page;
- in "Pending changes" window--without confirmation.

Is that what you intended?

**Comment by fisharebest** [comment]
Fixed in #1055
