### ISSUE TITLE
McDonald, Mc Donald, Mac Donald, MacDonald still an issue

### ISSUE THREAD

**Issue by allendex** [fisharebest/webtrees#1052]
I have reported this once before and was told this was fixed in 1.7.5.  I have been in the hospital nd just loaded 1.7.7 on my site.  When I click on search by surname, or McDonald in the most popular surnames it does not display ANYTHING.  I've done everything I can think of to standardize my Mc Donalds.

I would like to see this feature work because I see great value in this as I also have LewALLEN LewELLYN LewELLEN's in my tree and it would be nice to lump them under the most common spelling.

Would like the McDonald to work but as we believe MC and MAC are two different clans we would like to be able to turn this off on their spelling.  I have altered many names on my tree in an attempt to standardize things which I will have to change back.  I don't know what more I can do.

I will gladly give you access to my cpanel and my password on my site http://mcdfamily.org in e-mail.

I also have Prunty's that are spelled as Prenty and Printy would like to lump them under Prunty.

This is a good feature but would like to see it a bit more customized... or at least FIXED for now that if we click MacDonald it will show all McDonalds for the time being.

I'm catching a lot of hell from my family that looks at this site and they want to see a listing of their family. As it is now I can't display a list of any McDonalds as it just shows the letters A B C D ... X Y Z and nothing listed in between. I was told by greg i't becuse I have too many McDonalds (How can you have too many when your site is mostly from that family)

**Comment by fisharebest** [comment]
>  When I click on search by surname, or McDonald in the most popular surnames it does not display ANYTHING. I've done everything I can think of to standardize my Mc Donalds.

When I click on the surname "McDonald" on your site, I get a list of McDonalds.  e.g.  [this](http://pagesfromourpast.com/indilist.php?surname=MACDONALD&ged=MAIN&falpha=D&ged=MAIN&falpha=R)

Can you be more precise in your description of what is not working...

**Comment by fisharebest** [comment]
Since this appears to be working OK on your site (and mine), I'll assume this is working for you.

If not, please open another ticket with more details.
