### ISSUE TITLE
Missing DOB/DOD causes endless loop

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#1053]
Scenario:
  Child Born 1816; died 1904
   Father - Name known & entered, DOB/DOD not known, no BIRT or DEAT fact created
   Mother - Name known & entered, DOB/DOD not known, no BIRT or DEAT fact created

Error:
Displaying the child or parents either directly, on interactive family tree or trying to SEARCH  for them results results in a time-exceeded error.

Looks like it is looping evaluating the Father and Mother.  I put some debug statements in and I see this sequence of repeated calls:

getTarget for the FAMS tag, 
canShow for Father, $ access_level = -1; no restrictions, must be public
getTarget for the FAMS tag, 
canShow for Mother, $ access_level = -1; no restrictions, must be public

I couldn't tell where the calls were coming from and couldn't determine which fact was being evaluated.

Workarounds:

Add DEAT = Y either the Mother or Father records
or
Show Private relationships: Show to Visitors

Privacy settings:
   Age at which to assume an individual is dead:  **120**
   Extend privacy to dead individuals born in last **0** years or died in last **20** years 
   Show names of Private individuals: Show to **members**
    Show private relationships:  Hide** from all **

Other Settings:
     Memory limit: 1024M
     PHP Time Limit:  60

**Comment by eric215** [comment]
I should clarify -- the issue above is experienced by the not-logged-in  **visitors** to the website.  Members/etc have no issue and see all results.

**Comment by fisharebest** [comment]
Confirmed

**Comment by fisharebest** [comment]
This bug was introduced in the fix for #876
