### ISSUE TITLE
Robots visit several times

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1054]
My site moved to a new server. Since then my bandwidth usage has grown a lot.

I see that 
Googlebot (for instance crawl-66-249-75-198.googlebot.com and crawl-66-249-66-154.googlebot.com)  and Yahoo Slurp (b110320.yse.yahoo.net) visit the indipage several times with different themecolor values.
for instance 
/webtrees/individual.php?pid=I1624&ged=gedcom.ged&themecolor=olivia
/webtrees/individual.php?pid=I1624&ged=gedcom.ged&themecolor=mercury
and with all the colors options
/webtrees/individual.php?pid=I11&ged=Gedcom.ged&themecolor=aquamarinea
/webtrees/individual.php?pid=I11&ged=Gedcom.ged&themecolor=tealtop

How can we avoid these unnecessary visits?

Meliza

**Comment by fisharebest** [comment]
In the short term, you can use google webmaster tools to tell it to ignore the `themecolor` parameter.

**Comment by melizaa** [comment]
Let's see that it works.

I do not see a similar solution for yahoo.

**Comment by wkitty42** [comment]
On 07/05/2016 12:39 PM, melizaa wrote:
> Let's see that it works.
>
> I do not see a similar solution for yahoo.


probably because yahoo! uses bing...

**Comment by eric215** [comment]
If you sign into the Microsoft web master tools [www.bing.com/toolbox/webmaster](url)  under "Dashboard" --> Configure My Site, there is an option to throttle the Bingbot.  You can control its activity by time of day.  I believe Google has something similar

**Comment by fisharebest** [comment]
Maybe we could replace
`<a href="...?palette=XXX">`
with
`<a onclick="document.location=...?palette=XXX">`
