### ISSUE TITLE
Show date in recent changes block to visitors

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1061]
When not logged in a visitor will see this in the recent changes block:
![12-7-2016 18-16-17](https://cloud.githubusercontent.com/assets/5641963/16774684/6cfd7fd8-485d-11e6-8eae-13f91da8266b.jpg)

The dates are missing.

**Comment by fisharebest** [comment]
I guess you added a privacy rule for "CHAN" records, to hide them from everybody.

If CHAN are hidden, what should we do with this block?

**Comment by JustCarmen** [comment]
O yes, you are right... completely forgot that. I have set them to show to members... Then it makes sense.  But as far as I can tell I've had this block on my homepage for a long time and I can't remember exactly what it looks like, but certainly not like this. I'm afraid I have to revert to a previous version to refresh my memory ;)

But in a case like this shouldn't the text 'Changed on' be removed? To just show the records with no additional information?

**Comment by JustCarmen** [comment]
Now I think about it... the reason I added that privacy restriction in the first place was the fact that I didn't want to show all names of members to random visitors. In the recent change block that is not an issue anymore since we now have the option to hide the name of the person who made the change. But there isn't such an option for all the other places the "CHAN" record is shown. Or is there?

**Comment by fisharebest** [comment]
> But there isn't such an option for all the other places the "CHAN" record is shown

The last change/user is shown on the changes report.
By default, the changes report is not shown to visitors.
