### ISSUE TITLE
GoogleMapsModule.php: no flags shown within selected state

### ISSUE THREAD

**Issue by joszon** [fisharebest/webtrees#1062]
In the select flag dialog, when the state is selected (last level), there are no flag images shown.
I think, this is caused in line 557 of GoogleMapsModule.php.
The backslash is missing after $stateSelected

`$files = glob(WT_ROOT . WT_MODULES_DIR . 'googlemap/places/' . $countrySelected . '/flags/' . $stateSelected . '*.png');`

solution 

`$files = glob(WT_ROOT . WT_MODULES_DIR . 'googlemap/places/' . $countrySelected . '/flags/' . $stateSelected . '/*.png');`

**Comment by fisharebest** [comment]
Thanks.

This was already fixed in https://github.com/fisharebest/webtrees/commit/95820a3a8880d5706012c4f6f9772e2dfecc073e

The fix will be included in the next release, in a few days time.
