### ISSUE TITLE
Send the file from the "Clippings Cart", as an email attachment (PHP code below)

### ISSUE THREAD

**Issue by carlluiz** [fisharebest/webtrees#1065]
It would be a good idea for all webtrees users, add to the option "Save Clippings," add an option like this: Instead of only download - to save the file into hard drive - we could send the file e-mail as an attachment (for any email address) directly through the Outlook, for example.
I'm not sure, but I think the code would be like this:

`if ($_FILES["file"]["error"] > 0) {
echo "Error: " . $_FILES["file"]["error"] . "<br>";
} else {

$temp = explode(".", $_FILES["file"]["name"]);
$extension = end($temp);
$newname= $_FILES["file"]["tmp_name"].".".$extension;
rename($_FILES["file"]["tmp_name"],$newname);
$attachments = array( $newname );

   wp_mail('emailto send', 'title', 'message','',$attachments );
}`

And if we would like to retain the original file name, Then We Could change ... rename as explained below:
`rename ($ _ FILES [ "file"] [ "name"], $ newname);`

**Comment by jpretired** [comment]
...Outlook?? What is this?

**Comment by carlluiz** [comment]
The attachment can be generated to open in a mail client, it can be anyone ... Microsoft Office Outlook, etc.

**Comment by carlluiz** [comment]
Ok
