### ISSUE TITLE
The "new version" notification is always in English

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1068]
I'm sorry saying just now: after signing in--the "new version" notification is untranslated (on "My page"). As I see it doesn't changes in any other language.

![upgrade_in_english](https://cloud.githubusercontent.com/assets/15856891/16959115/b9598d5a-4de3-11e6-99cd-436a15357b8c.png)

 The same happened last time but, I thought I made a mistake...

In the "Control panel" it's OK:

![upgrade_in_hungarian](https://cloud.githubusercontent.com/assets/15856891/16959135/c9dd060c-4de3-11e6-861f-95d0697d7fec.png)

**Comment by fisharebest** [comment]
This message is generated on one page, and displayed on the next page.

If you log in to an English page, webtrees will change to your prefered language on the next page.

I guess you logged in to an English page.  Therefore the English page generated the message.

What happens if you change to Hungarian before you log in?

**Comment by tunandras** [comment]
I'm sure you're right.

When I said: "As I see it doesn't changes in any other language." that meant, when I saw the problem, I selected Russian when I was signed in, then signed out (to the browser's default language--that is to English) and signed in again. This way I got the message in English using Russian language on "My page". (I tried this out in French too.)

I'm sorry, I can't repeat the process. I upgraded webtrees already to the new version. Next time I'll try it.

**Comment by HonkXL** [comment]
Maybe the text is not translated in your language? I use German translation and I am sure that this message was shown in German.

**Comment by fisharebest** [comment]
I'm pretty sure this happens when you log in to an English page, and your account is set to prefer another language.

The message is generated in the language of the login page - not the language of the next page, which might be different.

It should be possible to fix this.

**Comment by tunandras** [comment]
> Maybe the text is not translated in your language?

Thank you very much for thinking with me.

webtrees translates the message. It is shown by my comment's second image--made in the "Control panel".

> The message is generated in the language of the login page - not the language of the next page, which might be different.

Yes, I assume that the translation uses the language set in the browser instead of the settings in webtrees. That's what I decided to try next time...

**Comment by tunandras** [comment]
Sorry, the second half of my last comment was so stupid. I think it requires an explanation.

I referred to an earlier comment in issue #943:

>  webtrees chooses the language from the browser configuration.

That is--before signing in or selecting a language--webtrees uses the language set in the browser (the preferred language is English in my browser) and it takes this information to translate the message.

> The message is generated in the language of the login page - not the language of the next page, which might be different.

Absolutely. That is what happened.

> It should be possible to fix this.

It would be very nice (if it is not only my problem).
