### ISSUE TITLE
Apple iPad -changing blocks not possible

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1071]
I found no way to change the order of the blocks on my iPad (iOS 9.3.3)
See screenshot.

![image](https://cloud.githubusercontent.com/assets/16715040/16999635/38b4c084-4ebf-11e6-83fa-48e2bc7b69a8.jpeg)

**Comment by makitso** [comment]
This behavior also exists on the latest Android tablet.  Same behavior when trying to customize the home page.

**Comment by fisharebest** [comment]
I only use FF on my android tablet, so I guess this is the built-in browser / Safari.

There are some iPads in the cupboard at work, so I might see if I can borrow one.

Since we need to rewrite this, we may as well go for the full drag/drop...

**Comment by makitso** [comment]
I generally use Ghostery on my Nexus and occasionally Chrome, fails on both in either desktop or mobile mode.

**Comment by HonkXL** [comment]
Yes, I use Safari on iPad.
