### ISSUE TITLE
Fan chart with 6 or more generations looks wrong

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1072]
Fan chart with up to 5 generations is ok, but with more it looks wrong. I think it should be generated in a higher resolution with smaller text. Then zooming in would be possible.

Screenshot shows fan chart for 9 generations.

![image](https://cloud.githubusercontent.com/assets/16715040/17004223/54aef07e-4ed4-11e6-8bf4-2cbc2ea4c1f4.png)

**Comment by HonkXL** [comment]
I know that the zoom level can be set manually. Maybe a good idea to set this level according to the number of generations?

**Comment by fisharebest** [comment]
We use a bitmap for this chart because of old versions of Internet Explorer.

Now that IE8 is obsolete, we could rewrite this chart using SVG.

**Comment by bmhm** [comment]
I fiddled a bit with the D3 library. As a basis I used this blog post:
https://pankajkumar005.wordpress.com/2015/08/14/multilevel-pie-chart-using-d3/

What do you think of this? [http://codepen.io/anon/pen/YNzEmv](http://codepen.io/anon/pen/YNzEmv)

(Please mind the population item).

Greg, this would be a perfect application for a JSON-based Rest API.

**Comment by HonkXL** [comment]
Looks great :-)

**Comment by magicsunday** [comment]
Please take a look at this: https://github.com/magicsunday/ancestral-fan-chart

**Comment by fisharebest** [comment]
I will do (eventually), but I'm in the middle of some major updates at the moment.

**Comment by ekdahl** [comment]
@magicsunday's fan chart looks great. In my opinion it would be great to include that in webtrees releases and let that replace the now included fan chart.

**Comment by marku5** [comment]
@ekdahl, you are right: @magicsunday did a great job! Would be good to get it included as standard webtrees module.
Let's wait for Greg's (@fisharebest) opinion/response.

**Comment by HonkXL** [comment]
Looks great. Hope this will come to webtrees 1.x :-)

**Comment by marku5** [comment]
@HonkXL: Just install the module.
I assume Greg will not do this for 1.x...maybe in 2.x?!

**Comment by fisharebest** [comment]
New features will go in 2.0.

1.7 will get updates for issues that concern security or data-integrity.

**Comment by arbor95** [comment]
please close
