### ISSUE TITLE
Person twice in person list when more then one marriage-name existsts

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1075]
I have some female persons, that married more than one time. For every marriage I have a event "marriage" and to make sure that the person can be found, we have added the marriage-name to the person.
One example: Katharina Schmidt married Florian Nowintsch and Johann Mächtl. Now we added two marriage names: "Katharina Nowintsch" and "Katharina Mächtl"

When I do a search for "Katharina Schmidt", she is found one time with all Names (thats ok).
But when I go to the list of persons, there are two entries for the same person.

Here a screenshot of what I entered:
![duplicate0](https://cloud.githubusercontent.com/assets/16715040/17083725/1bb42a46-51a9-11e6-99f8-83a64df1a8b1.png)

And here a screenshot of the result in the persons-list:
![duplicate1](https://cloud.githubusercontent.com/assets/16715040/17083727/2428001c-51a9-11e6-9bef-77e3f1c7b4a4.png)

I think this person should be displayed only one times in the person-list.

**Comment by fisharebest** [comment]
> I think this person should be displayed only one times in the person-list.

Suppose Jane White marries twice, to John Black and Peter Brown.

Under the list of individuals with a surname beginning with "B", would we show her under "Jane Black" or "Jane Brown"?

**Comment by fisharebest** [comment]
The proposed change would not work, for the reason I gave above.

You you have other suggestions about this?

**Comment by fisharebest** [comment]
The code is woring as intended, and I do not think this proposal will work.

If you think of an answer to the question I asked on 2 Sep, then please create a new issue.
