### ISSUE TITLE
Improvement - setting to open pdf in new tab

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1076]
I have a lot of pdf-files in my tree. I dislike it, that they are opened in the same browser tab as webtrees. I would prefer to get them loaded with target="_blank" into a new browser tab or window.
Maybe it would be usefull to have this as an option.

![downloadmedia](https://cloud.githubusercontent.com/assets/16715040/17083919/f267d75e-51ae-11e6-9bc4-c40aa583ec1c.png)

**Comment by vytux-com** [comment]
Doesn't holding down Shift key open in new window and Control key new tab? It always had for me.

**Comment by HonkXL** [comment]
Yes, of course this works, but I have to press it every time and sometimes I forget. I think the best solution is a setting in the prefs for this , so everybody can decide.

On iPad I have to perform a long click to the link and touch to the right entry in the menu to get this. This is not so easy as on the Mac.

The advantage of having it in a new tab is, that you can now easily switch between the person datas and the PDFs file. I need this very often.
Sure that some users will not use this, but I think as option this would be great.

**Comment by fisharebest** [comment]
> I think as option this would be great

I disagree.

The current behaviour gives users the choice.  CLICK = same window.  CTRL-CLICK = new window.  Forcing new window takes away users choice, as they have no way to open the link in the same window.

Forcing a new window sucks on devices that do not have tabs or windows (e.g. tablets).

Many other reasons are listed here https://css-tricks.com/use-target_blank

If you want this on your own site, I wrote some Javascript that will do the job for you.

https://www.webtrees.net/index.php/en/forum/4-customising/31518-solved-vytux-menu2-open-link-in-new-tab

You'll need to modify the CSS selector to match URLs that end in `.pdf`.
