### ISSUE TITLE
Finding duplicates on media files - too much false positives

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1077]
When I got to "finding duplicates", I have a lot of duplicates on media files, but I see no reason for this! They have different file sizes and different names. Finding duplicates on media files should check file size at least.

Screenshot of checking duplicates and detailed screenshots of first two entries attached.

![image](https://cloud.githubusercontent.com/assets/16715040/17238046/9569181c-5558-11e6-8cf7-f4c394550dd2.png)
![image](https://cloud.githubusercontent.com/assets/16715040/17238047/958e44e8-5558-11e6-8735-5f7f182af23d.png)
![image](https://cloud.githubusercontent.com/assets/16715040/17238048/9590fe22-5558-11e6-8258-47517058b095.png)

**Comment by fisharebest** [comment]
This is working as designed.  IMHO, you need to give your media objects unique titles.

Instead of two media objects called "Indiana Evening Gazette", you could have

* "Indiana Evening Gazette - Obituary of Max Musterman"
* "Indiana Evening Gazette - Erika Musterman elected President"

**Comment by HonkXL** [comment]
Thank you, it worked with renaming. So it's no bug and I will close this!
