### ISSUE TITLE
Number of online users wrong when logged out

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1078]
Since 1.7.7 I have very often the problem that it shows me one or two logged in users when I am logged out (first screenshot). When I log in, I am the only user. When I log out again, there is still a user online, but who is it?
I am not sure if this came when installing 1.7.7 or since updating to PHP 7 & activating opcache.
I am sure that it does not depend on browser cache (already cleared)

I think this number is cached somewhere. Maybe this cache should be cleared more frequent?

![image](https://cloud.githubusercontent.com/assets/16715040/17238213/1cfea502-555a-11e6-9c5f-94b601a49e49.jpeg)
![image](https://cloud.githubusercontent.com/assets/16715040/17238214/1d216ba0-555a-11e6-876e-30342200aa2f.jpeg)

**Comment by HonkXL** [comment]
In the forum a other user reported the same problem. Think it does not depend to PHP version.

**Comment by fisharebest** [comment]
> I think this number is cached somewhere. 

You are almost correct.

Firstly, it is impossible to count logged-in users, or even to know who is logged in.

When you login, two things happen:
* a login session is created - which stores your identity
* a cookie is created - which identifies the login session

When you logout, both these things are destroyed.

The count of "logged in users" is simply a count of the login sessions (which webtrees stores in the database).

But if you simply close your browser, then the cookie will be destroyed but the login session will continue to exist.  webtrees cannot know that you have deleted the cookie.  It thinks you are still logged in.  So, you appear in the count of logged in users.

So, we must periodically delete any old sessions that have not been used for some time.  A typical value is 2 hours.  If we make it longer, people complain that the count of logged-in users is inaccurate.  If we make it shorter, people complain that they get logged out when they leave the computer to have dinner.

But PHP does not have a mechanism for doing such periodic jobs.  It can only do things when it is asked to display a page.

After each page is created, PHP will decide at random whether to clean up old sessions.

Typically, after 1 page in every 1000 (chosen at random), PHP will delete sessions that are older than 2 hours.

See `probability`, `divisor` and `lifetime` at http://php.net/manual/en/session.configuration.php 

Obviously, whether to choose 1 in 1000 or 1 in 100 depends on how busy your site is.  For total accuracy, you would need to do this on every page, but on a busy site, the database would be unable to keep up.  On a  really busy site, 1 in 10000 would be sufficient.

**Comment by Fa10175** [comment]
you say Greg:
> When you login, two things happen:
> 
>     a login session is created - which stores your identity
>     a cookie is created - which identifies the login session
> 
> When you logout, both these things are destroyed.

but I have : for each connection 2 occurrences add the "wt_session" table.
and on logout only one is deleted

**Comment by HonkXL** [comment]
I checked it again: when I log in, it says 1 user online. When I log out and reload the starage it says 1 user online, but I am logged out. It seems that here is something wrong.

**Comment by vytux-com** [comment]
Set your php settings to 1 out of 1 and you will always have accurate login count..... Your site might be very slow though unless you are the only one using it.

**Comment by Fa10175** [comment]
just a question see attach file about delete occurences on wt_table.
[test login with display table wt_session.pdf](https://github.com/fisharebest/webtrees/files/440546/test.login.with.display.table.wt_session.pdf)

**Comment by fisharebest** [comment]
> just a question see attach file about delete occurences on wt_table.

When you connect for the first time, PHP will create a session automatically.

When webtrees sees that a session has started, it ignores the first session, and creates a new one.

This is a security feature.  See https://en.wikipedia.org/wiki/Session_fixation

**Comment by Fa10175** [comment]
thanks for these informations

> When webtrees sees that a session has started, it ignores the first session, and creates a new one.

so webtrees ignore the first session and it should remove it inside wt_session

so like that on log off no one occurence from this user existe after.

**Comment by fisharebest** [comment]
> it should remove it inside wt_session

This is the responsibility of PHP.

webtrees does not update this table directly.  It only does it when PHP gives the instruction.

**Comment by HonkXL** [comment]
Now I had a look on this.
Today a user (Beàta) logged in and out. Then I logged in. I saw two online users. See screenshots. How can this happen? She was logged out.

![image](https://cloud.githubusercontent.com/assets/16715040/18093907/d32d3cc2-6ed1-11e6-94de-e987b1716ea9.jpeg)

![image](https://cloud.githubusercontent.com/assets/16715040/18093917/db788c56-6ed1-11e6-95a6-36522f92bdac.jpeg)
