### ISSUE TITLE
iPad: Editing fields with long data not possible

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1081]
Some fields like place of birth are very short on the editing screen. When you try to edit text with iPad that is right of the visible area, normal you hold your finger long on the text field, then you can set the cursor to the right. But on these fields, the text is not scrolling, so the text right of the visible area can not be edited.

Tested on iPad Air and iPad Mini, latest Safari version on iOS 9.3.3

![image](https://cloud.githubusercontent.com/assets/16715040/17277402/4368e4f2-5742-11e6-9bf9-ca0245bf2626.jpeg)

**Comment by makitso** [comment]
I am not sure we can address the specific iPAD issue but can make the window larger.  Try adding this to the end of the style.css file in themes/colors/css-1.7.5/  and see if it helps.

#edit_interface-page input[type="text"][id*="_PLAC"] {
	width: 330px;
}

**Comment by HonkXL** [comment]
No, it is no general iPad problem! In other fields (not in Webtrees) it works fine. Just hold your finger a bitlonger, then got to right and the text starts to scroll. Only in Webtrees this fields have a different behaviour on the iPad.

**Comment by makitso** [comment]
This scrolling left and right does work on my Android tablet but not on the iPAD.  Can you give me a link to a non-webtrees site that I can test with?

**Comment by HonkXL** [comment]
uups. I just created a testcase on https://weiland.space/ipad-text.html and found out, that it is not working in iOS 9.3.3. Seems to be a Safari-Bug. I will file a bug report at Apple.com ;-)
