### ISSUE TITLE
show INDI and FAMS numbers - for tablet users

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1084]
In the last few weeks I used Webtrees from my iPad most times. A lot of things works fine with iPad, but sometimes, for example when merging duplicated persons it is very usefull to see the INIDE or FAM numbers somewhere.

On the desktop computer this information is always visible in the address bar of the browser, but on the iPad it only shows the hostname. The details are only shown when I click on the address bar, but then the virtual keyboard is coming up and this is not very good to handle.

So I have the suggestion to display these informations in the page, maybe in the right area. At moment the only reason to use my desktop are actions like merging, because I am never sure which person I am looking at. Most times I work with more than one browser tabs and this makes it hard without the information about which person is displayed at them moment.

**Comment by eric215** [comment]
This has been discussed many times in the webtrees forum.  See also the FAQ in the wiki [here](https://wiki.webtrees.net/en/Frequently_Asked_Questions).  The FAQ document some of the many difficulties in displaying these numbers on larger screens that are available to desktop users.  

Perhaps merging individuals is a task best left to a desktop/laptop where multiple monitors can be used?

**Comment by HonkXL** [comment]
I read the FAQ and can understand it. And I agree: it is a good idea to make it on the desktop. But most time I am working on iPad ;-)
I don't want to have the numbers everywhere and not behind the names like it was written in the FAQ. It would be enough to see the I and F of the actual displayed person or family somewhere. Maybe in the right bar as a plugin or something like this?

**Comment by HonkXL** [comment]
Maybe it's a good idea to close this issue. I think everything was told about this. Thank you for the answer!
