### ISSUE TITLE
Cannot continue after fatal import error

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1085]
It is not possible to import an GEDCOM-file that is ANSEL coded. This brings up an error.
After showing this error, it is no longer possible to use Webtrees. I have first log out, then login again. Then the only solution was to delete the tree, because every call of the tree bings the error message up and then the message will never disappear.
I know that ANSEL is not very common, but I got 2 GEDCOMs with this coding.

Most GEDCOMs I have seen in ANSEL are from Brothers keeper software.

**Comment by fisharebest** [comment]
FYI, I have written a library to convert ANSEL into UTF8, but it requires PHP7.0 and so I cannot include it in webtrees :-(

This is a more general problem.  After any fatal error, it  is not possible to delete or re-import.

**Comment by HonkXL** [comment]
I think it would be helpful to have a possibility to reimport in case of error.

**Comment by fisharebest** [comment]
> After showing this error, it is no longer possible to use Webtrees.

I tried to import a GEDCOM file in ANSEL format.  This is what happens

![screenshot at 2016-08-29 15 47 11](https://cloud.githubusercontent.com/assets/2306088/18055496/fbe587dc-6dff-11e6-87e7-c7a3811d30e5.png)

I can continue by deleting the tree or importing another GEDCOM file.

What do you mean by "no longer possible to use webtrees"?

**Comment by HonkXL** [comment]
I will test this and write here about it!

**Comment by fisharebest** [comment]
Have you been able to reproduce the problem?

**Comment by HonkXL** [comment]
Yes, I was able to reproduce. When upload fails, I am not able to do anything else then deleting the tree. Then my settings are lost. :-(

Attached ZIP contains a video of my import and you see that I can not do anything else then delete the tree.

[Webtrees-ANSEL.m4v.zip](https://github.com/fisharebest/webtrees/files/477122/Webtrees-ANSEL.m4v.zip)

**Comment by fisharebest** [comment]
>  I am not able to do anything else then deleting the tree

See my screenshot above.  When the import fails, all the options are available.  Therefore I can import a new file.

You say that you have the "delete" option but nothing else?  Show me a screenshot.

**Comment by HonkXL** [comment]
Import may work, but when I have a GEDCOM file that can not be imported, it is very unlikely that I have a corrected GEDCOM file a few minutes later! If import is not possible, I think I should be able to leave the import dialog and go to one of the other (working) trees. But this is not possible (see video).

**Comment by fisharebest** [comment]
> I think I should be able to leave the import dialog and go to one of the other (working) trees

You can.

The link "Stammbaum" is a link to the tree.  It will work.

The "My page" link is failing, because it is trying to connect to the **current** tree.  The current tree is not accessible.  Hence you are redirected back to this page to import it.

**Comment by HonkXL** [comment]
OK. I did not know this. Maybe a message in the text "import failed" would help to make this clearer?
