### ISSUE TITLE
Missing source fields 

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1086]
When you create a source  you have these fields; Title, Abbreviation, Author, Publication, Repository and Call Number.  
However, if you do not add a field during the initial create, say Title, it is not possible to add it later on the sources display.

**Comment by HonkXL** [comment]
I can confirm this. I already had this problem, but I thought I did something wrong. But it seems to bee a bug...

**Comment by fisharebest** [comment]
> it is not possible to add it later on the sources display

On the edit-source page, there is a drop-down list of "facts" that can be added.  This includes "title" and "abbreviation".

This is set in the "Unique source facts" setting in the family-tree preferences.

Do you have `TITL` and `ABBR` in this setting?

**Comment by fisharebest** [comment]
> it is not possible to add it later

It is?  See above.

If you are having some other problem, please provide details in a new issue.
