### ISSUE TITLE
merging persons - entering in lowercase can be a problem

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1087]
I merged two persons and entered the INDI-numbers to the merge window. On the first number I entered i242 insted of I242.

Merging worked fine, but in the family there was a CHIL to i242 instead of I242. In the error checker I got this message (sorry that it is in German):

"AM F708 hat einen CHIL Verweis auf i242. i242 gibt es nicht. Ist vielleicht I242 gemeint?"
This means F708 has a CHIL link to i242. i242 is not existing. Maybe you mean I242?"

Yes, of course I mean I242. But I think the merging tool should check and correct this and make the I or F uppercase.

**Comment by eric215** [comment]
Are you asking for the merge tool to assume that upper case "I" and lower case "i" are the same and to automatically assume you meant to merge the records?

Have you considered a situation where  there are records brought in from different sources over time (perhaps originally created using many different software tools), where some records may use the lower case "i" or "f" and other records use the upper case"I" or "F"?  In that scenario, they may very well represent two different individuals or families.

In the Gedcom standard, the characters in the XREF field are case-sensitive. so software is supposed to treat "I203" and "i203" as two separate records.

Not saying it is impossible, just trying to make sure that we're thinking everything through carefully and accounting for the many situations which could come up

**Comment by fisharebest** [comment]
> In the Gedcom standard, the characters in the XREF field are case-sensitive. so software is supposed to treat "I203" and "i203" as two separate records.

The GEDCOM standard doesn't say whether these are case-sensitive or case-insentitive.

Most software is case-insensitive, and so webtrees does the same.

BUT - webtrees uses the database to manage this.  You can (in theory!) change to case-sensitive by changing the collation of the relevant database columns.

In this case, I agree its a bug.  You searched for `i242`.  webtrees found `I242`.  Therefore it should use `I242` when creating links.

**Comment by eric215** [comment]
Greg- thanks for the clarification, I thought I was reading the spec   correctly but clearly not.
