### ISSUE TITLE
Accessing Webtrees not possible on plain IP v6 connections

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1088]
Today I had to use a plain IP v6 connection to my Webtrees installation. So no IP v4 is available on the client side. Accessing my Webtrees installation was not possible.

I use PHP 7.0.9, mySQL 5.6 and Apache 2.4 on a Debian 7 Server. Client side is Firefox 48 on Ubuntu Linux.

/var/www/vhosts/weiland24.de/httpdocs/webtrees/app/Statement.php:82 SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'ip_address' at row 1 #0 /app/Statement.php:82 PDOException("SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'ip_address' at row 1") #1 /includes/session.php:369 execute([array]) #2 unknown:unknown Fisharebest\Webtrees\{closure}('q7oo5fdipmpd8a01h3j8214vd7', '') #3 /app/Session.php:107 session_regenerate_id(false) #4 /includes/session.php:394 regenerate(false) #5 /index.php:31 require('/var/www/vhosts/weiland24.de/h…')

**Comment by HonkXL** [comment]
The IP of my client was:#
2001:470:1f15:6d9:213:ceff:fe37:faec

**Comment by fisharebest** [comment]
See also #1023.

As a temporary workaround, you could disable "strict mode" on your database

**Comment by HonkXL** [comment]
I set from
sqlmode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
to
sqlmode=NO_ENGINE_SUBSTITUTION
and now it works.

This is not the recommended MySQL configuration for mySQL 5.6.
But as workaround it is ok. Thank you.
