### ISSUE TITLE
wrong box layout on media screen

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1090]
The last days I changed a lot of names of media files. When I have media files assigned to families, the layout of the boxes is overlapping (see screenshot). Browser is the latest Firefox.

![changing-media](https://cloud.githubusercontent.com/assets/16715040/17789865/50b5a388-6594-11e6-8c57-4075059d2a85.png)

**Comment by ddrury** [comment]
Missed updating the folder version for the _administration theme

**Comment by fisharebest** [comment]
I only update the folder name (i.e. the URL) when something changes, and in this case, nothing has changed in the CSS for the admin theme.

**Comment by ddrury** [comment]
In which case I don't think you should have changed `app/Theme/AdministrationTheme.php line 47
`

**Comment by makitso** [comment]
There is no easy fix to this issue.  A slight improvement might be to set the % width from 80 to 95.
