### ISSUE TITLE
Individual Family tab shows the data wrong - github code

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1094]
I see for some parents their marriage and divorce in wrong sequence and children with wrong time differences. 
1. In the sample family record the parents' divorce is recorded before the marriage.
This causes us to see the Divorce before the Marriage in the Family tab and this causes us to see the first child with a negative time difference (divorce date - birth date).
2. In the sample family record the younger child is recorded before the elder one.
This causes us to see the younger one before the elder one and the elder with a negative time difference.

![familytab](https://cloud.githubusercontent.com/assets/5202996/18353787/10f7aae4-75ec-11e6-89b9-c81631c39378.jpg)

We should print the family facts in date sequence and the children in birth date sequence.

On the demo site I do not see the time differences. On my site I see them. Where can i define not to show them on the family tab?

**Comment by fisharebest** [comment]
> Where can i define not to show them on the family tab? 

There is a checkbox at the top of the family tab "Date differences".  (This setting is remembered next time you visit the page).

**Comment by melizaa** [comment]
1. Does every user have to change the checkbox value?
2. What about visitors? 
3. Do we have to change the value for each family?

**Comment by fisharebest** [comment]
1) Every user can set this for themself.

2) It does not matter if you are logged in.  The setting is stored in the browser

3) The setting applies to all families.
