### ISSUE TITLE
A php error message on "Geographic data" page

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1099]
A php error message generated on _Geographic data_ page after clicking **continue** (button) on "Upload geographic data" page if no file is selected on Control panel &gt; Modules/Module administration &gt; Google Maps™ &gt; Geographic data &gt; **upload** (button) &gt; _Upload geographic data_ page. Probably a human information would be better instead.

**Comment by HonkXL** [comment]
I can confirm this - I will get this message:

`/var/www/vhosts/weiland24.de/httpdocs/webtrees/includes/session.php:193 /var/www/vhosts/weiland24.de/httpdocs/webtrees/app/Module/GoogleMapsModule.php:3737 asort() expects parameter 1 to be array, null given #0 unknown:unknown ErrorException("/var/www/vhosts/weiland24.de/httpdocs/webtrees/app/Module/GoogleMapsModule.php:3737 asort() expects parameter 1 to be array, null given") #1 /app/Module/GoogleMapsModule.php:3737 asort([NULL]) #2 /app/Module/GoogleMapsModule.php:103 adminPlaces() #3 /module.php:26 modAction('admin_places')`
