### ISSUE TITLE
Maybe they are redundant menu options

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1101]
Is there a reason to show certain menu items on their page or are they redundant options in "My pages" menu? If you agree and if it is possible please remove "My page" menu item in "My pages" pull-down menu when that page is shown (as the "Customize this page" menu item disappears after selecting it).

![is_redundant_my_page_menu_item](https://cloud.githubusercontent.com/assets/15856891/18607548/e824e998-7ccf-11e6-8754-30ed1cfd5e7d.png)

Please do the same with "My account" menu item when its page is shown.

![is_redundant_my_account_menu_item](https://cloud.githubusercontent.com/assets/15856891/18607550/fa1b6a46-7ccf-11e6-9fc3-949fc7c223ca.png)

In my opinion the occurrence of the already chosen menu options in "Theme" and "Language" pull-down menus are all right (they aren't written on pages).

**Comment by fisharebest** [comment]
"Customize this page" only appears on two pages:

* The family tree home page
* My page

These are the only two pages that can (currently) be customized.

**Comment by tunandras** [comment]
>These are the only two pages that can (currently) be customized.

Yes, you are absolutely right.

Sorry, I think I was wrong. I mentioned the "Customize this page" phrase just for one reason: after selecting it in the menu and the change blocks page downloaded, the "Customize this page" menu item disappears from the "My pages" pull-down menu.

I tried to suggest the same behavior for "My page" and "My account" menu items too.

**Comment by fisharebest** [comment]
I don't think we should hide/disable these.

They menus still work - they load the page again.  Maybe this is what the user wants.

The "customise" menus are here because there is nowhere better to put them.
They are used infrequently, and the alternative is to have a button/link on the page itself - which looks untidy.

**Comment by tunandras** [comment]
It's all right. I understand you. :-)
