### ISSUE TITLE
The individual's name in the confirmation

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1103]
Let's say, the family tree includes an individual named John Smith, whose given name is really Alexander so, a manager replaces John to Alexander. After accepting the changes, a message informs the manager that "The changes to “John Smith” have been accepted."

Wouldn't it be better if the individual's new (changed) name would be in the message instead of their former, already non-existent (wrong) name?

**Comment by fisharebest** [comment]
There are problems with both approaches.

Suppose an individual is edited, and the name is deleted.  Now, there is no "new name" to show.

> "The changes to “John Smith” have been accepted."

You could argue that the changes were made to the **old** record, and hence we should show the **old** name!

I think I prefer the existing logic.
