### ISSUE TITLE
Alignment of "close" button on auxiliary pages

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1104]
Since the **close** button is consistently _right aligned and_ it is _at the very bottom on_ creating and editing _pages_ I would suggest to do the same on page "Link to an existing media object" too--even though there is no "save" button on the left (as it is on "Pending changes" window).

I would do the same on "Find..." pages too. See for example "Relationships" &gt; "Find an individual" or "Family tree clippings cart" &gt; "Find an individual", "Find a family", and "Find a source" pages.

**Comment by fisharebest** [comment]
These pages have been rewritten in the latest code
