### ISSUE TITLE
Observations on the Make process

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#1109]
I've recently installed [_Bash on Ubuntu on windows_](https://msdn.microsoft.com/en-gb/commandline/wsl/about) and thought I'd give it a go by 'make'ing webtrees. First thing I realised was that the java compiler doesn't work (some people say it does but not for me) so it was necessary to run in interpreted mode which makes things slooow (about an hour to make webtrees) but a couple of things came to light. 

- The make ignores custom themes (.gitignore in the themes directory) - any reason why? custom modules **are** made
- line 60 in the Makefile refers to` /library/Zend/*` which no longer exists

**Comment by fisharebest** [comment]
The minification process is slow.  It isn't run very often, so it's not a priority to update it.

`.gitignore` in `themes/` exists because I frequently have custom themes in my working code.  You are right that we need on in `modules_v3/'.  Added.
