### ISSUE TITLE
Visibility of "Google Street View™"

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1117]
In "Place hierarchy" it would be better to show automatically "Google Street View™" only if it makes sense--that is only at bottom level Map View (assuming that places are well structured in the GEDCOM). I think for example to show streets of a county is meaningless so, in this case in my opinion it is better to hide the right (empty) frame.
![place_hierarchy](https://cloud.githubusercontent.com/assets/15856891/19184890/84d46f34-8c7f-11e6-94dd-0a82adb09fa1.png)
Or, as an alternative solution it would be great to provide the opportunity to set its visibility in preferences.

**Comment by JustCarmen** [comment]
>> Or, as an alternative solution it would be great to provide the opportunity to set its visibility in preferences.

You can enable of disable the street view in the Google Map Preferences (Module configuration page)

**Comment by tunandras** [comment]
Thank you very much for your answer.

>You can enable or disable the street view in the Google Map Preferences (Module configuration page)

Yes, you are absolutely right. I'm sorry it is my fault because I wasn't clear enough.

I thought it would be good to set the visibility of "Google Street View™" for higher levels separately. (You know, in a county for example there are multiple cities so, it doesn't make sense to show streets--like when you choose top level.)

**Comment by fisharebest** [comment]
> I think for example to show streets of a county is meaningless

I did not write this module, but I think the intention is that you choose a streetview that represents the country.

For France, you could use a view of the Eifel Tower.

I do not like the StreetView feature for many reasons.

* Genealogy is about the world many years ago.  The view of a street today will have little in common with the view in 1700.
* A streetview is for an address `ADDR`, but we are using it for a place `PLAC`.
* It only works with Google Maps.  Therefore we cannot change to other map providers, such as OpenStreetMap.

> I thought it would be good to set the visibility of "Google Street View™" for higher levels separately.

Different countries, and different regions have different hierarchies.  For example, some US states have counties, but others do not.

My prefered option would be to remove StreetView, and allow users to choose different maps.  There are some great mapping libaries that we can use, such as `leaflet`.

Also, there is (was?) a project to create a historic world map using OpenStreetMap.  If this ever happens, we could use that with no work at all.

**Comment by tunandras** [comment]
>I do not like the StreetView feature for many reasons.

I agree with your considerations--mostly with the first. I had not thought of them.

>Different countries, and different regions have different hierarchies.

That's true. My proposal was just my point of view. I'm sorry, and suppose it would be too difficult to set the visibility for every place however, if there would be a default setting the manager would have to change only the exceptions--until OpenStreetMap or another map is not usable...

**Comment by fisharebest** [comment]
Streetview has been removed.

1) This is a modern view of places, and we are dealing with historic data.
2) It prevents us from using other mapping providers (e.g. openstreetmap)
