### ISSUE TITLE
Help text of "Pending changes"

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1118]
The help text: "Pending changes are only shown when your account has permission to edit. When you sign out, you will no longer be able to see them. Also, pending changes are only shown on certain pages. For example, they are not shown in lists, reports, or search results."

As I see the pending changes link is shown in the top menu on list and search result pages too.

**Comment by fisharebest** [comment]
This help text refers to the changes to the genealogy data.
Pending changes to the genealogy data are usually shown with blue/red borders.

The menu item to accept/reject these changes is shown on all pages.

This is working as intended.
