### ISSUE TITLE
place list is not updated in some cases

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1121]
In the last weeks I had very often a problem with the place list. Now I was able to see how this problem happens:
1. we started with a small tree. It was imported from a gedcom file.
2. user A added a person, born in "Hoffen".
3. user B accepted this change.
4. user A changed the birthplace from "Hoffen" to "Hoffen, unbekannt, Deutschland".
5. user B accpeted this change.

Now there should be a entry "Deutschland" in the place list. But there isn't.
In the places hierarchy there is only "Ungarn", but no Hoffen or Deutschland.
![places3](https://cloud.githubusercontent.com/assets/16715040/19246432/a08f7bd4-8f26-11e6-952e-5418355d9191.png)

When showing all places, there is "Hoffen", but no word of "Deutschland". Where is it? Why is Hoffen displayed here, but not in the hierarchy?

![cities2](https://cloud.githubusercontent.com/assets/16715040/19246458/c1fcd65e-8f26-11e6-953f-67d7d741df18.png)

And this is a screenshot of the person:
![cities1](https://cloud.githubusercontent.com/assets/16715040/19246473/d0ff6388-8f26-11e6-94c8-4f9a07ae18dc.png)

I had this problem very often in the past in all of my webtrees installations, but I was never able to see how it could happen, because too many people did changes. Now it was simple, because in this tree we only had 2 users.

**Comment by fisharebest** [comment]
I am unable to reproduce this.

**Comment by HonkXL** [comment]
At moment I can not reproduce this, too. I would recommend to close this bug-report and if I will notice this problem again, I will open a new one with more details and logs.
