### ISSUE TITLE
Facebook Integration Error

### ISSUE THREAD

**Issue by nmella** [fisharebest/webtrees#1125]
Hi There,

I know the Facebook module is not part of webtrees, buy maybe it is a simple fix. I am not a developer ...

I have a Webtrees install 1.7.8 on a Linux server with PHP7. After installing the Facebook Integration module version v1.0-beta.7, I get the following error when trying to enable the module in Adminstration => Modules:

PHP Fatal error:  Class 'WT_Module' not found in /home/petacl/mella.cl/modules_v3/facebook/module.php on line 31

Any solution around this ? 

Thanks,

Nicolás

**Comment by fisharebest** [comment]
The error means that this module was written for a much earlier (1.6?) version of webtrees.

There is nothing that I can do to help.  You'll need to contact the author of the module and ask them to update it.

**Comment by nmella** [comment]
OK, thanks.
