### ISSUE TITLE
Godparents - improve this window

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1127]
I tried to add godparents in my tree. There I found some points to be improved:

1. It is not possible to add more than one godparent at a time. If the first is added, I have to close the window, then I can add the next.

2. I associated a person, but I forgot to fill the field "relationship". Later it was not possible to add "godmother" to this, because the relationship field was no longer visible. I edited the GEDCOM to add this...

3. Maybe it would be a idea to make it possible to add new person inside the windows where I can choose the godparents, because if they don't exists in the tree, I first have to add them manually in the control panel and then I have to go back to the person where I want to add them as godparent.

**Comment by mpwt** [comment]
4. A automatic backlink to the original person -> godparent - godchild. When I add a associate to a person and it exists a revers association than this should added automatically.

**Comment by fisharebest** [comment]
It is best to have just one item in each issue.  Otherwise it gets difficult to manage.

> It is not possible to add more than one godparent at a time.

Yes it is?  If you add a christening (`CHR`), there are two associate fields, for two godparents.

**Comment by fisharebest** [comment]
> A automatic backlink to the original person -> godparent - godchild. When I add a associate to a person and it exists a revers association than this should added automatically.

The reverse links are calculated dynamically, and shown when you select "show events of close relatives".

On the demo site, visit one of the godparents of Queen Elizabeth, enable "Events of close relatives", and you will see the christening.

**Comment by mpwt** [comment]
> The reverse links are calculated dynamically, and shown when you select "show events of close relatives".

I mean a different thing (ASSO instead of EVEN) and will open a separate issue. Thanks.

**Comment by wkitty42** [comment]
i know of numerous children with godparents that were never christened... christening is a religious "procedure" and not everyone belongs to that particular branch of religion but they do appreciate the concept of have other selected adults to watch over their children, help raise them and take them in if something untoward happens to the birth parents...

i suggest that keeping this linked with christening is a good thing but it should also be available separately without requiring christening...

**Comment by ric2016** [comment]
> Yes it is? If you add a christening (CHR), there are two associate fields, for two godparents.

For Baptisms (BAPM), there is only one initial associate field. Is that intentional?

**Comment by fisharebest** [comment]
> Is that intentional?

No.  The feature was originally added to CHR and MARR events.  It is easy to add it to others.

**Comment by fisharebest** [comment]
> i know of numerous children with godparents that were never christened

Then you can add an individual assocation `1 ASSO` link for these.

This issue (AFAICT) is about the fact associations `1 BAPM /2 _ASSO`

**Comment by wkitty42** [comment]
On 12/01/2016 09:02 AM, Greg Roach wrote:
>     i know of numerous children with godparents that were never christened
>
> Then you can add an individual assocation |1 ASSO| link for these.

i would never thing to look for or do that... i and others who have worked with 
my trees always look for something like godmother and godfather to add...

> This issue (AFAICT) is about the fact associations |1 BAPM /2 _ASSO|

my bad if i hijacked... i saw it simply as dealing with godparents in general... 
sorry...

**Comment by fisharebest** [comment]
If you have no BAPP/CHR, where *would* you you (or your users) expect to find the ability to link godparents.

**Comment by wkitty42** [comment]
in the record along with mother and father? not real sure... just seems kinda natural from a generic view point... the problem comes from godparents seemingly always associated with religious activities... suppose that is to be expected with "god" in their name... what else would they be known as?
