### ISSUE TITLE
Feature request: automatic revers link for associates (was part of #1127)

### ISSUE THREAD

**Issue by mpwt** [fisharebest/webtrees#1130]
A automatic revers link to the original person -> godparent - godchild. When I add a associate (ASSO) to a person as godparent than a revers link at the target person as godchild should added automatically or about a checkbox.

![reverslink](https://cloud.githubusercontent.com/assets/16311627/20111931/708769a8-a5ea-11e6-8395-a83aa1d74279.png)

**Comment by fisharebest** [comment]
There *are* automatic reverse links.

Go to the demo site, and view the page for Queen Elizabeth.
Scroll down to her christening.
Click on one of the godparents.
At the page of the godparent, select the "events of close relatives" option.
Scroll down - you can see the christening.

**Comment by fisharebest** [comment]
Also, what do you want the reverse link to look like?

In the original record, we have

```
0 @i1@
1 CHR
2 ASSO @i2@
3 RELA godparent
```

What do you want in the godparent's record?

```
0 @i2@
1 CHR <----- this is NOT a christening of i2, so this is wrong!
2 ASSO @i2@
3 RELA godchild
```

**Comment by mpwt** [comment]
Well. I am looking for a possibility to insert two ASSO-tags in one step: F.i. I have a christening and the child has godparents than I can add links/tags to this child with the relationship of godparent. Otherwise I have the individuals of godparent where I have to add the link/tag as godchild manually. For this case I looking for a automatically added ASSO-tag (reverse link or is this the wrong word).

0 @I1@
1 ASSO @I2@
2 RELA godparent

and back

0 @I2@
1 ASSO @I1@
2 RELA godchild

An 2 ASSO tag below an Event is not allowed in Gedcom 5.5.1. It have to saved as 2 _ASSO. Theefore I use it only as 1 ASSO.

**Comment by fisharebest** [comment]
> When I add a associate (ASSO) to a person as godparent than a revers link at the target person as godchild should added automatically

Some associations are obvious pairs.  Buyer/seller.  Godparent/godchild. Friend/friend.

Others are not.  There is no opposite to Priest, Witness, etc.

**Comment by mpwt** [comment]
Now I have tried to understand the different associations of GedcomCodeRela.php and to find the possible pairs. I think some of the existing associates are very special and others often used I am missing.

Pairs are: employee/employer, ward/guardian, godchild/godparent, friend/friend, buyer/seller, foster child/foster parents (and maybe owner/slave). At least for this should it be possible to insert the revers link automatically, f.i. as a case sensitive function.

For all others the revers link could be "... of". But for an associated person this person has to exist in the DB. For what it is worth to have persons in the DB they are not related to anyone (only associated). In case someone wants to insert them a possibillity to insert another word by hand would be very helpful.

The meaning of the following words I do not understand well: attending, attendant, bridesmaid (or better maid of honor as female part of best man), nurse and lodger. A german translation exists but I do not know if it is well translated.

I miss f.i. midwife, Witness_of_Birth, Witness_of_Death, Witness_of_Marriage, Witness_of_Civil_Marriage, Witness_of_Religious_Marriage, person reporting the birth, person reporting the death. A possibillity to insert another word would be helpful. The translation can added in a custom language file.



Could you insert foster parents, foster son and foster daughter too (it is the same like godchild and godparents)? And for witness exists a different male/female translation at least for german (male Zeuge, female Zeugin).

**Comment by fisharebest** [comment]
> I miss f.i. midwife, Witness_of_Birth, Witness_of_Death, Witness_of_Marriage, Witness_of_Civil_Marriage, Witness_of_Religious_Marriage, person reporting the birth, person reporting the death.

Why add these to the *individual*?  It would be simpler to add them to the *event*.
e.g. instead of this:

```
0 @xxx@ INDI
1 ASSO @yyy@
2 RELA witness_of_birth
1 ASSO @zzz@
2 RELA registered_the_birth
```

use this:

```
0 @xxx@ INDI
1 BIRT
2 _ASSO @yyy@
3 RELA witness
2 _ASSO @zzz@
3 RELA registrant
```

**Comment by arkodonti** [comment]
> There _are_ automatic reverse links.
> 
> Go to the demo site, and view the page for Queen Elizabeth.
> Scroll down to her christening.
> Click on one of the godparents.
> At the page of the godparent, select the "events of close relatives" option.
> Scroll down - you can see the christening.

The automatic reverse link, as you describe, works for the first godparent only, not the second one. This can be verified on the demo site, page for Queen Elizabeth. Is this a bug ?
