### ISSUE TITLE
Report - Ancestors does not show any children

### ISSUE THREAD

**Issue by arjanvs** [fisharebest/webtrees#1139]
Unfortunately, this report does not show the children with the checkerbox enabled.

Can this feature be enabled? Perhaps, similar as from @JustCarmen hers FancyTreeview?

Thank you!

**Comment by bmhm** [comment]
A bug in: `modules_v3/ahnentafel_report`.

I can confirm this bug.

**Comment by arjanvs** [comment]
I would like to help to solve it, but I have no clue how to debug in PHP

**Comment by arjanvs** [comment]
@bmhm @fisharebest  I tested the new report.xml, but appearently it does not work for 1.3.9 Still no children. Do need to update more, than just the report.xml?

**Comment by fisharebest** [comment]
> Do need to update more, than just the report.xml?

Yes.

But I don't think you can just take certain files.  There are too many dependencies.
