### ISSUE TITLE
Support for PHP 7.1

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1140]
I just activated PHP 7.1 for one of my webtree-installations.

On the startpage I see this message on top of page below the menus:

`/var/www/vhosts/weiland24.de/httpdocs/webtrees2/app/Stats.php:646 [] operator not supported for strings #0 /app/Module/FamilyTreeStatisticsModule.php:112 Error("[] operator not supported for strings") #1 /index.php:70 getBlock(23) `

I don't know if there are other things not working with PHP 7.1

**Comment by fisharebest** [comment]
Already fixed by https://github.com/fisharebest/webtrees/pull/1134 ??

**Comment by mpwt** [comment]
I have test it on my site and it seems to work. The error message disappears. Thanks.

**Comment by HonkXL** [comment]
Works fine. Thank you.
