### ISSUE TITLE
Translation of the RELA description

### ISSUE THREAD

**Issue by mpwt** [fisharebest/webtrees#1144]
Why it is not possible to use another text within RELA and translate this text with a separate language file? It seems that the text have to be one of the drop down menu. Own word are not translateble.

**Comment by fisharebest** [comment]
1) Yes this is possible

2) Are you thinking of a specific relationship?  If it could be useful to others, then perhaps we should include it in the core code?

**Comment by mpwt** [comment]
Wow! Superfast answer. Thank you.

1. Ok, it is possible. I had tested it. But it was/is not possible to translate it. Example: https://ffp.bauschaffen.de/individual.php?pid=I39&ged=Pannier. A separate de.mo exist in dta/language/.

2. No, what I want to use is to specific. Some suggestions I made within #1130.
