### ISSUE TITLE
Useless « yes » in occupation

### ISSUE THREAD

**Issue by Gustine** [fisharebest/webtrees#1145]
When an occupation tag is used without date nor location, webtrees 1.7.9 adds a useless « yes ».
![occupation-yes](https://cloud.githubusercontent.com/assets/5450774/21455052/9306734c-c91d-11e6-971f-666fed27bba3.png)

**Comment by mpwt** [comment]
This [change](https://github.com/fisharebest/webtrees/commit/603c4534a5f9f71b89e8f3f89f43de4ee4469deb) introduce the new behaviour. I think a case sensitive function for Death and Marriage events is missing there.

**Comment by HonkXL** [comment]
Same behaviour inside other fields like in sources or in archives.
When the entered data is in more than one line, it is displayed in one line!

In this example I entered

`Schneider Druck GmbH
Erlbacher Str. 102-104
91541 Rothenburg`

And this is, what there is displayed:

<img width="321" alt="webtrees-sources" src="https://cloud.githubusercontent.com/assets/16715040/21463352/61af3aa4-c968-11e6-9476-00e94b055c98.png">

**Comment by mpwt** [comment]
> When the entered data is in more than one line, it is displayed in one line!
This is not new in 1.7.9! In 1.7.8. it is the same for addresses.

**Comment by fisharebest** [comment]
I think we should only show "yes" for events that are listed in `Config::emptyFacts()`

**Comment by Gustine** [comment]
It sounds like a good idea.

**Comment by wt-enigma** [comment]
This fix is ​​in the next release, Can I change something at this time?

**Comment by mpwt** [comment]
download the webtrees-1.7-master.zip and upload the file FunctionsPrint.php in the same subfolder in your installation. done.

**Comment by wt-enigma** [comment]
Solved
Thanks
