### ISSUE TITLE
Privacy suggestions

### ISSUE THREAD

**Issue by arjanvs** [fisharebest/webtrees#1146]
Add option, show to administrators.

Show private relationships: I cannot select members, but perhaps I do not understand the feature well. So I need perhaps some additional documentation.

**Comment by fisharebest** [comment]
This is a "yes" / "no" question.  The options "show to visitors" and "hide from everybody" are used for consistency.

* "Show to visitors" = "yes"
* "Hide from everybody" = "no"

When we show private relationships, we show the structure of the tree, but no names/details.

So, if a (public) individual had a (private) wife, son, and daughter, then charts would show empty boxes for the wife, son and daughter.

**Comment by fisharebest** [comment]
Also, it would really be very useful.

"Show to members" would mean that if an individual was marked as "show to administrators", then a member would be able to see an empty box for the person.

If an indiviudual is sufficiently private that your members cannot see it, then it is unlikely that you would want your members to know it exists.

**Comment by arjanvs** [comment]
After reading your comments here it is clear to me. But wouldn't it be a benifit if one could read it in the adjoining "documentation/explanation"?
