### ISSUE TITLE
Untranslatable string

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1147]
You have added a new option to the tree configuration: "Find unrelated individuals"

I can't find this string in weblate to translate. Are the language files updated to includes this one?

**Comment by mpwt** [comment]
I don't know if 'Find any relationship' and 'Find relationships via ancestors' from RelationshipsChartModule.php (line 134 and 135) is missing too?

**Comment by fisharebest** [comment]
FYI, I have created a second project on the translation server for the webtrees-1.7 branch.

The two projects are linked, so adding a translation to one project will automatically add it to the other.

**Comment by JustCarmen** [comment]
That's good to know. Thank you Greg.
