### ISSUE TITLE
suppress .htaccess as unused object in media manager

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1148]
In the media manager the .htaccess is displayed as not linked media file. The user can delete it here.
It would be a good idea to suppress this file from the frontend. A user should not be able to delete the .htaccess file from the webinterface. It makes no sense to display the .htaccess here.

<img width="241" alt="webtrees-media" src="https://cloud.githubusercontent.com/assets/16715040/21463326/d7a94d4a-c967-11e6-920f-60379f290424.png">

**Comment by mpwt** [comment]
For what do you have the .htaccess inside the folder /media? Normally it is in /data.

**Comment by HonkXL** [comment]
You are right. Maybe this an relict is from an older version of webtrees?

**Comment by JustCarmen** [comment]
I even think it is an inheritance of an old PGV installation... given the text at the top of this file:
`# $Id: .htaccess,v 1.1.2.1 2004/12/08 23:32:51 yalnifj Exp $`

I've removed it.

**Comment by fisharebest** [comment]
Since `/media` is a user folder, I don't think we can easily know if the .htaccess file should be there or not.

This would normally be used as a "public" media folder, for images on the home page, etc.  As such, it would not need a `.htaccess` file.

If we hid this filename, then you wouldn't have found it and deleted it!

The current behaviour would seem to be the better option.

**Comment by wkitty42** [comment]
On 12/26/2016 10:59 AM, Greg Roach wrote:
> Since |/media| is a user folder, I don't think we can easily know if the
> .htaccess file should be there or not.
>
> This would normally be used as a "public" media folder, for images on the home
> page, etc. As such, it would not need a |.htaccess| file.
>
> If we hid this filename, then you wouldn't have found it and deleted it!
>
> The current behaviour would seem to be the better option.

my understanding is that leading-dot filenames are hidden... at least on *nix 
systems... i have to take special steps to see them... none of my FTP servers 
show them and neither do my web servers (on OS/2 or *nix)... i don't run 
winwhatever so i don't know what FTP or HTTP servers show for them on that OS...


-- 
  NOTE: No off-list assistance is given without prior approval.
        *Please keep mailing list traffic on the list* unless
        private contact is specifically requested and granted.

**Comment by fisharebest** [comment]
> my understanding is that leading-dot filenames are hidden

They are hidden by the application-level code, not the operating systm.

Each application makes its own decisions.  IMHO, webtrees should show them here - as we are not expecting them.

**Comment by wkitty42** [comment]
On 12/27/2016 04:00 AM, Greg Roach wrote:
>     my understanding is that leading-dot filenames are hidden
>
> They are hidden by the application-level code, not the operating systm.

ahhh... and i guess that sh, bash, zsh and other shells are applications?

> Each application makes its own decisions. IMHO, webtrees should show them
> here - as we are not expecting them.

i'm trying to correlate this with the above... oh, wait... applications can hide 
them... ok, so why not do just that? or make it an option in the config?

i'm not sure what i'm missing here :(

**Comment by fisharebest** [comment]
> i'm not sure what i'm missing here :(

It is most likely that any `.htaccess` file in the media folder is erroneous.  (As in this case).  

Therefore the best course of action is to show them, so that they can be identified and removed.

In other words, the current behaviour is (IMHO) prefered.
