### ISSUE TITLE
Next version 1.8?

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#1149]
Greg,

Based on your recent forum post re ver 1.7.9 and your recent commits shouldn't the next version be bumped to 1.8 ?

**Comment by wkitty42** [comment]
why can't there be a version 1.7.10? :wink:

**Comment by fisharebest** [comment]
> why can't there be a version 1.7.10

There will be!

The next release on the 1.7 branch will be 1.7.10 (which will run on PHP 5.3-7.1)

The next release on the "master" branch will be 1.8.0 (which will run on PHP 5.6-7.1)

In fact, I found a bug in 1.7.9 (which only affects PHP 5.3 users), so the 1.7.10 release will be fairly soon.

**Comment by Amgine0** [comment]
New features which are backwards-compatible.

[major].[minor].[maintenance[.build]]
