### ISSUE TITLE
find unlinked individuals does not care about godparents

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1156]
I used the "find unliked individuals" feature to finde unlinked individuals. I got a large list of persons, some are really unlinked, but most of them are godparents, not related to the familys blood lines, but godparent for a person.
If I click to this persons in the list, I don't see that they are set as godparents. If I delete them, I see in the "find errors" list, that I deleted a linked person.

Can you extend the find unlinked individuals list to take care about godparents?

**Comment by fisharebest** [comment]
>  you extend the find unlinked individuals list to take care about godparents?

Yes and no.

We can easily extend it to include *associates*.  All associates (witness, etc.), not just godparents.

I guess this is probably the desired behaviour.

**Comment by vytux-com** [comment]
Well that depends on whether this is supposed to find unlinked or unrelated individuals. I think I would find it more useful if it found unrelated ones, but that may just be me

**Comment by fisharebest** [comment]
It would be simple to make this an option.

**Comment by Amgine0** [comment]
Yes, please.
