### ISSUE TITLE
Remove Google Street View

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#1158]
There are many criticisms of the Street View module.

* It shows the current view of the world, whereas genealogy is concerned with the historic view.  The current view often bears no relation to the historic view.
* Each time Google update their images, it invalidates existing coordinates/angles/elevations
* It ties us into Google Maps, and prevents us using other mapping providers, such as Open Street Map.
* The user interface is not intuitive, and the code behind it is convoluted and difficult to maintain.

I propose to remove StreetView for the 1.8.0 release

**Comment by HonkXL** [comment]
In my opinion this is a good idea. I don't know any person using Street View here (but maybe they exist). Supporting Open Street Map would be great!
