### ISSUE TITLE
Batch update - last change information - wrong values

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1165]
The option 'keep the existing last change information' in Batch Update doesn't work correctly anymore.

Choosing 'no' does _not_ update the last change information
Choosing 'yes' _does_ update the last change information

This should be the other way around.

And shouldn't the default value be 'yes'?

**Comment by fisharebest** [comment]
> And shouldn't the default value be 'yes'?

The default is set (should be set!) in the family tree preferences - "Keep the existing ‘last change’ information"

**Comment by JustCarmen** [comment]
> The default is set (should be set!) in the family tree preferences - "Keep the existing ‘last change’ information"

That doesn't matter. If I set the default to 'yes' in the family tree preferences the default value in the batch update section stays 'no'.

But should this value be linked to the value in the family tree preferences? Most of the time when you are updating records one by one it is okay to update the last change information, but most of the time when you are doing a batch update it is to correct things and then it is preferable to keep the last change information. Therefore I think the default value should be 'yes' (keep the existing last change information). And if I recall correctly this was the case in the past.

But apart from this, my main concern was the fact the values don't act the way they should:
> Choosing 'no' does _not_ update the last change information
Choosing 'yes' _does_ update the last change information

> This should be the other way around.

**Comment by mpwt** [comment]
I found this issue too (and Carmen was faster to send it). Thanks. 

I think the checkbox description is wrong. The default is set to 'yes' ("Keep the existing ‘last change’ information" - first checkbox) but the checkbox description is 'no'.

**Comment by mpwt** [comment]
Here is the code from BatchUpdateSearchReplacePlugin.php - line 172:

`FunctionsEdit::radioButtons('case', array('I' => I18N::translate('no'), 'i' => I18N::translate('yes')), ($this->case ? 'i' : 'I'), 'class="radio-inline" onchange="this.form.submit();"') .`

When I select the first checkbox (no) the last change date is keeping. When I select the second (yes) the process changes the last change date.

**Comment by fisharebest** [comment]
The code is in `BatchUpdateBasePlugin.php` (not `BatchUpdateSearchReplacePlugin.php`)

The internal option is a boolean "Update CHAN".
The "on screen" option is a yes/no "Keep CHAN".

So, the "Keep CHAN" = "yes" option needs to set the flag to `false`....

Perhaps we should have called this option "Update the last change".

**Comment by JustCarmen** [comment]
> Perhaps we should have called this option "Update the last change".

It doesn't matter how we call it as long as the terms match. The way it is now with opposite terms is confusing and can easily lead to (coding) mistakes.
