### ISSUE TITLE
PHP 7.1 fix advice please

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#1167]
app/GoogleMapsModule.php function buildIndividualMap() has the following code starting at line 1779

```
$facts = array_values(array_filter($facts, function (Fact $item) {
	// remove null facts (child without birth event) and facts without places
	return $item !== null && !$item->getPlace()->isEmpty();
}));
```

php 7.1 throws an error if $item is null when it is typehinted as Fact. The error can be fixed by 

- removing the typehint, or
- add default value of null to $item

Please advise if you know a better way or your preferred solution

**Comment by bmhm** [comment]
I'd say solution #2 works, but I'd also check why the `$facts` array contains null elements in the first place.

**Comment by fisharebest** [comment]
A cleaner fix is to filter the facts in the preceding loop.
