### ISSUE TITLE
Link to Existing Media Field very small

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#1169]
Tried to find the style that was controlling this, but no luck.

Individual --> Families Tab --> View this family --> Family Group Information block --> link to an existing media

The input field is so small (narrow) that it is difficult to type in a name and see what you've entered. 

This is a low priority as the popup list of existing media is shown sized correctly, or the media could be added via the Marriage Event attached to one of the Individuals.

Raises a broader question - is there a way to reduce complexity and use the same edit block in both places (Marriage event attached to the Individual and the Family Group Information Block?)  Seems like extra effort to have such similar but still different blocks.

Example:

![add media to family](https://cloud.githubusercontent.com/assets/13973937/21631760/46e92eac-d20d-11e6-95d6-28f7af4e6097.PNG)

Linked from here:

![family group info](https://cloud.githubusercontent.com/assets/13973937/21631777/6fc6a8b8-d20d-11e6-98fc-41d1ceab1036.PNG)

**Comment by mpwt** [comment]
It is a fielf for a xref_ID like 'M1' only. For what do you need more space?

**Comment by eric215** [comment]
My understanding was that we had moved away from using  identifiers to using the full title/name of the object.  This field is larger in all other locations that I've come across, so at a minimum, there should be some consistency in which CSS element is used to identify it.

**Comment by fisharebest** [comment]
The plan is to replace the current autocomplete/xref-lookup with https://select2.github.io/examples.html

**Comment by mpwt** [comment]
The value is a xref_ID, but with the camera symbol you can looking for the real name.

The code you can find here -> inverselink.php:
```
		echo I18N::translate('Link to an existing media object');
		echo '</td></tr><tr><td class="descriptionbox width20 wrap">', I18N::translate('Media'), '</td>';
		echo '<td class="optionbox wrap">';
		if (!empty($mediaid)) {
			//-- Get the title of this existing Media item
			$title =
				Database::prepare("SELECT m_titl FROM `##media` where m_id=? AND m_file=?")
				->execute(array($mediaid, $WT_TREE->getTreeId()))
				->fetchOne();
			if ($title) {
				echo '<b>', Filter::escapeHtml($title), '</b>';
			} else {
				echo '<b>', $mediaid, '</b>';
			}
		} else {
			echo '<input data-autocomplete-type="OBJE" type="text" name="mediaid" id="mediaid" size="5">';
			echo ' ', FunctionsPrint::printFindMediaLink('mediaid', '1media');
			echo '</td></tr>';
		}
```

**Comment by mpwt** [comment]
With the Justlight theme I havn't this problem ...
![medialink](https://cloud.githubusercontent.com/assets/16311627/21722045/3c3e7d84-d42b-11e6-8b42-aef5329c228a.png)

Now I have tested too that I can looking for the media title directly from this field. It is sufficient to insert the first characters to find the right media file.

**Comment by fisharebest** [comment]
> The plan is to replace the current autocomplete/xref-lookup

This change is mostly complete.

It's in the `develop` branch on github.
