### ISSUE TITLE
Set TMP folder for swiftmailer

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#1171]
Some servers are configured to use a system temp folder that is outside the open-basedir-restriction.  /SIGH

We can work around this by creating our own temporary folder, and instruction swiftmailer to use it.

```
\Swift_Preferences::getInstance()->setTempDir($tmpDir)
```

**Comment by wkitty42** [comment]
please see also issue #1154 for updated info... i don't know how to reopen an issue so it is visible again but when i saw this it reminded me about that issue...

**Comment by fisharebest** [comment]
> i don't know how to reopen an issue

Just create a new one!

**Comment by wkitty42** [comment]
On 01/06/2017 06:02 AM, Greg Roach wrote:
>     i don't know how to reopen an issue
>
> Just create a new one!

:lol: i didn't think about that :lol:

**Comment by melizaa** [comment]
Where should we add 
\Swift_Preferences::getInstance()->setTempDir($tmpDir) ?

**Comment by fisharebest** [comment]
https://github.com/fisharebest/webtrees/commit/7577aecd6925e461ab43f99cfd372eb40b265e64
