### ISSUE TITLE
Make PclZip requirement optional by using PHP ZipArchive extension

### ISSUE THREAD

**Issue by robert-scheck** [fisharebest/webtrees#1172]
Since PHP >= 5.2.0, there is http://php.net/manual/en/class.ziparchive.php / http://php.net/manual/en/book.zip.php which provides a built-in PHP Zip/ZipArchive extension/module that should be faster compared to a pure PHP implementation. If not mistaken, the zip functionality is only used in

 * admin_site_upgrade.php
 * admin_trees_download.php
 * app/Module/ClippingsCart/ClippingsCartController.php

This request is to make PclZip optional in case some webhosting providers do not offer the PHP Zip/ZipArchive extension/module, while I think the built-in PHP variant should be preferred over a library that has seen to update for 7+ years.

**Comment by JustCarmen** [comment]
It is already on the to do list to replace PclZip https://github.com/fisharebest/webtrees/issues/279

**Comment by fisharebest** [comment]
> It is already on the to do list to replace PclZip #279

Now that we have dropped support for old versions of PHP, we can use https://flysystem.thephpleague.com for all our filesystem interaction.

Flysystem contains a wrapper for PHP/Ziparchive.
