### ISSUE TITLE
Missing support for German genealogical generation names

### ISSUE THREAD

**Issue by robert-scheck** [fisharebest/webtrees#1173]
As of writing, webtrees does not support German genealogical (professional) generation names as mentioned at https://de.wikipedia.org/wiki/Generationsbezeichnungen – which means that e.g. `great ×22 grandparent` has its own German name (`Erzahnenurgroßeltern`), not just the German translation (`Ur( × 22)großeltern`). There is some rough idea in webtrees, but only up to `great ×7 grandparent`, which is generation 9, while the German naming schema covers up to generation 24.

As the mentioned Wikipedia page unfortunately has no English translation: The generation names apply only to mother, father and both (as parents) in a straight direction of ancestors.

Oh, as per http://www.baar-online.de/inhalte/genealogie.html there are even three more generations with own German names, however about the last three I'm not sure, even my family tree goes still further.

Maybe we can extend at first from generation 9 to (well known) generation 24 for the German translation?

**Comment by JustCarmen** [comment]
I think this is related to this https://github.com/fisharebest/webtrees/pull/928

**Comment by robert-scheck** [comment]
@JustCarmen, from my point of view the pull request is not related. The pull request only refers to cousins, niece/nephew, aunt/uncle about different generations/degrees. My request is about parents or their parents (up to 24 generations back). Or am I wrong?

**Comment by JustCarmen** [comment]
> @JustCarmen, from my point of view the pull request is not related. The pull request only refers to cousins, niece/nephew, aunt/uncle about different generations/degrees. My request is about parents or their parents (up to 24 generations back). Or am I wrong?

I don't think you are wrong. However the pull request is handling a part of the problem regarding the translation of relationship names in different languages and your question is related to this problem, hence why I want to point this out to you.

In Dutch we have the same problem, the English/American way of handling relationships is not the way we should do it. According to this wikipedia page we even have 65 named generations:

https://nl.wikipedia.org/wiki/Lijst_van_benamingen_voor_generaties

Many of us would never reach number 65 in their tree, but about 20/25 named relations would be great. So I follow these discussions with attention.

Another related discussion is this one: https://github.com/fisharebest/webtrees/issues/947. Here Greg says this has his attention but a fix for this will have to wait until the 1.8 release.

**Comment by mikejpr** [comment]
I agree with @mpwt this names are only a suggestion and aren't standard. Also I think that the most users aren't expert and know that "Stammurgroßeltern" means "Ur( × 10)großeltern", the last one is more expressive and understandable.

**Comment by mpwt** [comment]
There was a longer discussion in the forum few months ago. Please look [here](https://www.webtrees.net/index.php/en/forum/8-translation/31084-translating-relationships-into-german).

**Comment by robert-scheck** [comment]
While I agree that people might have different views about what they treat more expressive, more readable or more understandable, webtrees should from my point of view still at least technically support the alternatives. That would allow own/customized/alternative translations, which currently does not work at all.

**Comment by fisharebest** [comment]
Support for this is now planned for version 2.1 - #2331
