### ISSUE TITLE
Some strange German translations

### ISSUE THREAD

**Issue by robert-scheck** [fisharebest/webtrees#1174]
#: app/Functions/Functions.php:1360
    msgctxt "son’s wife’s father"
    msgid "daughter-in-law’s father"
    msgstr "Schwiegertochters Vater"
    
    #: app/Functions/Functions.php:1362
    msgctxt "son’s wife’s mother"
    msgid "daughter-in-law’s mother"
    msgstr "Schwiegertochters Mutter"
    
    #: app/Functions/Functions.php:1364
    msgctxt "son’s wife’s parent"
    msgid "daughter-in-law’s parent"
    msgstr "Schwiegertochters Vater/Mutter"

I would suggest (from the perspective of a German native speaker) instead:

  * Vater der Schwiegertochter
  * Mutter der Schwiegertochter
  * Eltern der Schwiegertochter

**Comment by robert-scheck** [comment]
#: app/Functions/Functions.php:1072
    msgctxt "daughter’s husband’s father"
    msgid "son-in-law’s father"
    msgstr "Schwiegersohns Vater"
    
    #: app/Functions/Functions.php:1074
    msgctxt "daughter’s husband’s mother"
    msgid "son-in-law’s mother"
    msgstr "Schwiegersohns Mutter"
    
    #: app/Functions/Functions.php:1076
    msgctxt "daughter’s husband’s parent"
    msgid "son-in-law’s parent"
    msgstr "Schwiegersohns Vater/Mutter"

And of course:

  * Vater des Schwiegersohns
  * Mutter des Schwiegersohns
  * Eltern des Schwiegersohns

**Comment by JustCarmen** [comment]
Hi, you can change these translations yourself at the webtrees translation server:

https://translate.webtrees.net/projects/webtrees/webtrees/de/

You can suggest a new translation or update a  translation (requires registration).
Changes are pushed to this repository on a regular bases and will be added to the next release of webtrees.

**Comment by fisharebest** [comment]
The relationship translation must include a translation for every relationship that has a name in any language.

FYI, these relationships have specific names in Spanish.

As @JustCarmen says, you can update the translations at https://translate.webtrees.net

**Comment by robert-scheck** [comment]
Thanks, I suggested the translations above.
