### ISSUE TITLE
Link from Add Media Object to Source too small

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#1178]
This is a low priority, more of a nuisance,  Ver 1.7.9, but existed in prior versions too.

Edit any event --> Add a media object (create media object) --> Add a Source citation.

The field for the source name is extremely small.  The pop-up list of matching sources IS full width and can be used to select the right source, it's just a usability issue, can't really see what you've typed in.

![create media - source](https://cloud.githubusercontent.com/assets/13973937/21707798/5e83196c-d3a0-11e6-8c6e-96b05dcb703e.PNG)

**Comment by mpwt** [comment]
It is a fielf for a xref_ID like 'S1' only. For what do you need more space?

**Comment by eric215** [comment]
My understanding was that we had moved away from using  identifiers to using the full title/name of the object.  This field is larger in all other locations that I've come across, so at a minimum, there should be some consistency in which CSS element is used to identify it.

**Comment by fisharebest** [comment]
This has been fixed in the `develop` branch.  XREFs are no longer used.
