### ISSUE TITLE
Link from Add Media Object to Shared Note too small

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#1179]
This is a low priority, more of a nuisance,  Ver 1.7.9, but existed in prior versions too.

Edit any event --> Add a media object (create media object) --> Add a Shared Note.

The field for the Shared Note Name is extremely small.  The pop-up list of matching notes IS full width and can be used to select the right source, it's just a usability issue, can't really see what you've typed in.

![create media - shared note](https://cloud.githubusercontent.com/assets/13973937/21707824/af06f41c-d3a0-11e6-99e1-0c7ec17ef46f.PNG)

**Comment by mpwt** [comment]
It is a fielf for a xref_ID like 'N1' only. For what do you need more space?

**Comment by eric215** [comment]
My understanding was that we had moved away from using  identifiers to using the full title/name of the object.  This field is larger in all other locations that I've come across, so at a minimum, there should be some consistency in which CSS element is used to identify it.

**Comment by fisharebest** [comment]
This has been fixed in the `develop` branch.  XREFs are no longer used.
