### ISSUE TITLE
Fatal error: Class 'Collator' not found

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1180]
Using the latest code I get a fatal error:

Fatal error: Class 'Collator' not found in C:\xampp\htdocs\webtrees\app\I18N.php on line 442

I think this commit is responsible for this failure: https://github.com/fisharebest/webtrees/commit/991b93ddf82ec1af763df7d5e82b5c7c43ed1347

**Comment by fisharebest** [comment]
Can you tell me the PHP version?

**Comment by JustCarmen** [comment]
php 5.6.23

**Comment by fisharebest** [comment]
OK. 5.6 doesn't allow you to catch these errors.

I will need to check for the class explicitly.

**Comment by magicsunday** [comment]
I got the same error. I needed to install the missing PHP module `intl`.

`apt-get install php5-intl`
