### ISSUE TITLE
[RFE] Option to reverse tree view

### ISSUE THREAD

**Issue by bmhm** [fisharebest/webtrees#1182]
It has come to my attention, that someone wishes to reverse the pedigree view from ltr to rtl.

Currently: Youngest generation on the left side (either Landscape or Portrait mode).
Feature request: Youngest generation on the right side.

Or in other words: Reverse Portrait & reverse Landscape or just Right-To-Left.

Source: [https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-9/31813-direction-of-the-family-tree](https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-9/31813-direction-of-the-family-tree)

**Comment by fisharebest** [comment]
This is implemented in e759aebbec359cf7148227a725fea81907659ae8

e.g. https://dev.webtrees.net/demo-dev/index.php?route=module&module=pedigree_chart&action=Chart&ged=demo&xref=i1&generations=4&orientation=left
