### ISSUE TITLE
Fatal error: Arrays are not allowed in class constants in /webtrees/app/I18N.php on line 48

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#1183]
The webtrees.net page states the following: webtrees 1.7.x requires PHP5.3 or later.

Arrays in class constants are gets available in PHP5.6

**Comment by fisharebest** [comment]
Which version of webtrees are you using?

**Comment by magicsunday** [comment]
Github master-Branch

**Comment by fisharebest** [comment]
Look at the webtrees version (shown in admin.php) or the definition in includes/session.php.

You have 1.8.0-dev

The 1.7.x development is now on the branch 1.7

**Comment by magicsunday** [comment]
It shows webtrees 1.7.10-dev

**Comment by magicsunday** [comment]
After upgrading PHP to version 5.6 it runs fine again.
