### ISSUE TITLE
Value objects, testability

### ISSUE THREAD

**Issue by bmhm** [fisharebest/webtrees#1184]
This is a TODO / _for the record_ issue. Should be assigned to the second laravel release (e.g. `v2.1.0` or so).

There are currently no [value objects](https://dzone.com/articles/practical-php-patterns/basic/practical-php-patterns-value) in webtrees. A value objects consists only of a constructor and values, getters (java user here `;-)`) and simple conversion functions. Perhaps a static method for constructing such an object, if desireable. Additionally, a `check()` method at the end of a constructor is a good idea, to check for illegal states.

Mixing value objects with database code will make testing more difficult. Consider my very simple method [`personHasTombstone($person);`](https://github.com/bmhm/webtrees-missingtombstones/blob/master/src/missingtombstones/TombstoneSearch.php#L56). I can write a test for `null` easily, but it is somewhat hard to create an `Fisharebest\Webtrees\Individual` instance without a database. Individual holds values (model) and logic (controller, parts of the view).

This issue shall track those classes, which needs refactoring to be a value object only.

Benefits:

- Comparing objects can be done using `==` (which compares all fields).
- Easier testing, less mocking.
- Defined states.
- Logic can be tracked separately
- View can be created separately.

- [ ] `Fisharebest\Webtrees\Individual` (`app/Individual.php`)
- [ ] …

**Comment by fisharebest** [comment]
> it is somewhat hard to create an `Fisharebest\Webtrees\Individual` instance without a database.

This can already be achieved by creating "mock" objects.  Here's an example:

https://github.com/fisharebest/webtrees/blob/master/tests/app/Census/CensusColumnAgeMaleTest.php

> Comparing objects can be done using `==` (which compares all fields).

We use a "singleton" pattern for GEDCOM records - see `GedcomRecord::getInstance()`.  Therefore we can use `===`, which is much faster.

> View can be created separately.

We now have a system of views (`/resources/views`) and most code uses it.  The rest is being converted).

**Comment by fisharebest** [comment]
The business logic is now being moved into "services" `\app\Services\`

Services are stateless and contain just business logic.  This means they can be tested without needing to simulate an HTTP request.

Services are injected into the controllers.  This means they can be easily mocked, allowing the controllers to be tested.

I'm going to close this issue now because making the code more testable is happening as part of the 2.0.0 rewrite.
