### ISSUE TITLE
'Events of close relatives' only listed for first associate

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#1192]
This bug has been discussed as while ago in [https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-4/31323-how-to-add-other-kind-of-related-person](url), but apparently not reported here:

On the 'Facts and Events' tab, in the list of 'Events of close relatives' of an Individual _Ix_, an associate event is only displayed if _Ix_ is listed as the first associate of the respective event (e.g. as the first godparent).

This is because `associateFacts` in `IndividualFactsTabModule.php` only checks for the first attribute (`$fact->getAttribute('_ASSO')`/`$fact->getAttribute('ASSO')`). Here, all ASSO/_ASSO attributes should be used instead, e.g. via a new function in `Fact.php`:

```
public function getAttributes($tag) {
	preg_match_all('/\n2 (?:' . $tag . ') ?(.*(?:(?:\n3 CONT ?.*)*)*)/', $this->gedcom, $matches);
	$attributes = array();
	foreach ($matches[1] as $match) {
		$attributes[] = preg_replace("/\n3 CONT ?/", "\n", $match);
	}
	return $attributes;
}

**Comment by apberger** [comment]
Is there any idea, when this issue will be solved?

**Comment by Joppla** [comment]
This item is closed, but the bug is not solved in v 1.7.11

**Comment by ric2016** [comment]
Where do you see that this issue is closed?

**Comment by fisharebest** [comment]
> This item is closed

This issue is not closed.  Issue #1267 is closed, and #1267 has a reference to this issue.

**Comment by Joppla** [comment]
misunderstanding, sorry, in the title I saw "close" and here also: 
![afbeelding](https://user-images.githubusercontent.com/25467829/45555146-4a5ba700-b838-11e8-80fd-3b649f6be94d.png)
But now I understand that it is a link to the other item. 

Any idea when the item will be solved?

**Comment by AndreasRauhut** [comment]
Me too, I would like that somebody will do the neccessary to solve the bug and close the issue.
Unfortunately I'm not the right person to do it.

**Comment by AndreasRauhut** [comment]
Please explain me, why I can't see a change in the behavior of my database. I understood that you changed the code and closed the issue, but I see only one chagement.
When I place relationships in webtrees, the system creates an _ASSO tag instead of an ASSO tag.

But nevetheless only the first relative of a person will show the relationship to this person.
Does I need to change some code or wait for the next release ?
Please give me a hint.

**Comment by fisharebest** [comment]
You asked the same question on the fourm.
I gave examples showing that the code is now fixed.

> Please give me a hint.

You must give me a hint.
Show me an example where it is not working.
Perhaps you have a different problem.
