### ISSUE TITLE
Gedcom FORM tag

### ISSUE THREAD

**Issue by arjanvs** [fisharebest/webtrees#1193]
The gedcom file created after an export contains following line "2 FORM Lineage-Linked"

Shouldn't it be "2 FORM LINEAGE-LINKED" according to the "standard"?

[ged551-5](http://phpgedview.sourceforge.net/ged551-5.pdf)

**Comment by fisharebest** [comment]
On page 50 of the specification, it uses upper-case:

```
GEDCOM_FORM := {Size=14:20}
[ LINEAGE-LINKED ]
```

On page 74 of the specification, it uses initial capitals:

```
0 HEAD
1 SOUR PAF
2 VERS 2.1
1 DEST ANSTFILE
1 SUBM @5@
1 SUBN @8@
1 GEDC
2 VERS 5.4
2 FORM Lineage-Linked
1 CHAR ANSEL
```

And on page 21 , it says that upper/lower case are considered the same:

> All controlled line_value choices should be considered as case insensitive.
This means that the values should be converted to all uppercase or all lowercase prior to
comparing.

In summary, it doesn't matter.  Upper/lower case are equally valid.

Unless this is causing a problem somewhere, I suggest we leave it as it is.

**Comment by arjanvs** [comment]
If that is the case, we should!
