### ISSUE TITLE
Marriage type gedcom tag

### ISSUE THREAD

**Issue by arjanvs** [fisharebest/webtrees#1194]
Add marriage to couple, in popup window change marriage in Religious from the drop down.

Gedcom Type shows: Religious

Add religious marriage from event list

Gedcom Type shows: RELIGIOUS

When are capitals used and when not?

**Comment by fisharebest** [comment]
In your first example, you are creating

```
1 MARR
2 TYPE religious
```

In your second example, you are creating

```
1 MARR_RELIGIOUS
```

This is a custom tag which is created by a desktop application.  webtrees will try to display this by converting `1 MARR_XXXXX` to `1 MARR/2 TYPE XXXX`.

Upper/lower case shouldn't make a difference (see my comment on your other issue).
IIRC webtrees converts to lower case before translating the type.

I recommend that you do not use MARR_RELIGIOUS.

**Comment by arjanvs** [comment]
Greg

Sorry to say this, but it is not after an import.

If I am in a family and use "fact or event".

The path add "normal" marriage, then change it to religious type. The type is Religious.

OR

Add event from drop down menu religious marriage, the type is RELIGIOUS.

**Comment by fisharebest** [comment]
I am guessing at your data.  Can you post the GEDCOM data for these records.

**Comment by fisharebest** [comment]
> I am guessing at your data. Can you post the GEDCOM data for these records.

**Comment by arjanvs** [comment]
Sorry took a while, I was a bit distracted:

0 HEAD
1 SOUR webtrees
2 NAME webtrees
2 VERS 1.7.9
1 DEST DISKETTE
1 DATE 04 NOV 2017
2 TIME 20:49:41
1 GEDC
2 VERS 5.5.1
2 FORM Lineage-Linked
1 CHAR UTF-8
1 FILE zzzz
1 PLAC
2 FORM City, County, State/Province, Country
1 SUBM @SUBM@
0 @SUBM@ SUBM
0 @I1@ INDI
1 NAME Jan /JANSEN/
1 SEX M
1 BIRT
2 DATE 01 JAN 1850
2 NOTE Wijzig deze persoon en vervang de details door uw eigen.
2 SOUR @S128@
3 PAGE asdfgh cit
3 DATA
4 TEXT Blabla
4 DATE 02 DEC 2016
3 QUAY 2
1 FAMS @F37@
1 CHAN
2 DATE 26 DEC 2016
3 TIME 12:22:00
0 @I137@ INDI
1 NAME Bob /JANSEN/
2 GIVN Bob
2 SURN JANSEN
1 SEX M
1 FAMC @F37@
2 PEDI birth
1 DEAT
2 DATE 12 APR 1925
2 AGE 26
1 BIRT Y
1 CHAN
2 DATE 17 DEC 2016
3 TIME 13:30:11
0 @I164@ INDI
1 NAME /Male1/
2 SURN Male1
1 SEX M
1 CHAN
2 DATE 04 NOV 2017
3 TIME 20:45:58
1 FAMS @F42@
0 @I165@ INDI
1 NAME /Male2/
2 SURN Male2
1 SEX M
1 CHAN
2 DATE 04 NOV 2017
3 TIME 20:47:37
1 FAMS @F43@
0 @I166@ INDI
1 NAME /Female1/
2 SURN Female1
1 SEX F
1 CHAN
2 DATE 04 NOV 2017
3 TIME 20:45:58
1 FAMS @F42@
0 @I167@ INDI
1 NAME /Female2/
2 SURN Female2
1 SEX F
1 CHAN
2 DATE 04 NOV 2017
3 TIME 20:47:38
1 FAMS @F43@
0 @F37@ FAM
1 HUSB @I1@
1 CHAN
2 DATE 17 DEC 2016
3 TIME 13:25:52
1 CHIL @I137@
0 @F42@ FAM
1 HUSB @I164@
1 WIFE @I166@
1 MARR
2 DATE 01 APR 2017
2 PLAC Somewhere
2 TYPE Religious
1 CHAN
2 DATE 04 NOV 2017
3 TIME 20:48:59
0 @F43@ FAM
1 HUSB @I165@
1 WIFE @I167@
1 MARR Y
1 CHAN
2 DATE 04 NOV 2017
3 TIME 20:48:05
1 MARR
2 TYPE RELIGIOUS
2 DATE 02 APR 2017
2 PLAC Church
0 @S128@ SOUR
1 TITL addg
1 CHAN
2 DATE 26 DEC 2016
3 TIME 10:01:56
0 TRLR
