### ISSUE TITLE
PLAC.NOTE tag, shared note does not display for visitor

### ISSUE THREAD

**Issue by NorwegianSardines** [fisharebest/webtrees#1195]
Adding a "shared note" under a place tag does not expand with note text for visitors, but displays fine for signed on Moderator.  Example Code:

1 BIRT
2 PLAC ...
3 NOTE @n1@

For visitor the "n1" is displayed as a "note" while a signed on moderator shows "shared note: text of note.

**Comment by fisharebest** [comment]
I just created this on the demo site:

https://dev.webtrees.net/demo-dev/individual.php?pid=i1&ged=demo

(This example is valid until 03:00 tomorrow).

I see the shared note as a visitor.

Any more clues to help me reproduce this?

**Comment by NorwegianSardines** [comment]
Sorry I did not get back to your issue fast enough.  I added my issue to the same person.   As a visitor the "shared note" only shows the note xref, while as the moderator it shows as the text of the shared note.

**Comment by fisharebest** [comment]
What privacy applies to this note?

e.g. I presume that the moderator has permission to see it, but the visitor does not?

**Comment by NorwegianSardines** [comment]
i added the note new to the system, so I guess it is the same as the person, the individual is alive but set to "show to visitors" I can see the birth detail, so I would expect the note to follow and be seen as well.  I think I understand.    The note was not excepted, so to the visitor the note only showed the xref but to the moderator who entered the note it showed because he entered it.

**Comment by fisharebest** [comment]
Visitors do not see pending changes.

If I understand correctly, the changes to the note were not accepted, but the changes to the individual were accepted.  Thus the individual had a link to note that does not (yet) exist.

In this case, this is working as designed.
