### ISSUE TITLE
messages & mails not sent - github be5f0ef

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1196]
Mails are not sent using swiftmailer.

I see in the error log messages
"Unable to send a message. FROM:admin TO:admin (failed to send)"
and
"Mail: .../webtrees/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/MailTransport.php:45 The Swift_Transport_MailTransport class is deprecated since version 5.4.5 and will be removed in 6.0. Use the Sendmail or SMTP transport instead."

I see the messages on the webtrees site.

See for instance
http://stackoverflow.com/questions/41426486/the-swift-transport-mailtransport-class-is-deprecated-since-version-5-4-5-and-wi

**Comment by fisharebest** [comment]
Oops.  wrong issue number in commit.

**Comment by fisharebest** [comment]
You are using the "PHP mail" option.

Our mail library has decided that this option is unreliable, and will be removed in future.

I have added a third option.  "sendmail".

Like PHP mail, it will only work if your server is configured to use it.

Try it.  If this fails, you will need to use SMTP mail.

**Comment by melizaa** [comment]
I see now with sendmail in the Website log error

Mail: .../webtrees/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:295 Undefined variable: pipes

**Comment by fisharebest** [comment]
I'm guessing your server has disabled `proc_open()`.

This is understandable.  I do this on my own server.

It is likely that this will be disabled on 99% of servers.

You should set up and use an SMTP server.

**Comment by fisharebest** [comment]
In session.php, you can tell webtrees to ignore these warnings, by removing `E_DEPRECATED` in the call to `error_reporting()`.

**Comment by melizaa** [comment]
If I tell webtrees to ignore the warning/error, will I receive the mail. Today neither users nor I receive any mails from webtrees.

**Comment by fisharebest** [comment]
>If I tell webtrees to ignore the warning/error, will I receive the mail.

Yes.  For stable releases, we ignore all deprecation warnings.

You only see them because you are using development code (which enables them).

**Comment by melizaa** [comment]
I made the change to session.php. It did not help.

So I started to make changes to the Sending email definitions.
I received different error messaged.
I saw that I have to use SMTP.
Most of my SMTP definitions were outdated, because I have used PHP mail to send mails.
At the end I managed to get a mail from webtrees.

Thanks for the support.  

Meliza

Mail: Failed to authenticate on SMTP server with username "m@a.com" using 2 possible authenticators

webtrees/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/MailTransport.php:45 The Swift_Transport_MailTransport class is deprecated since version 5.4.5 and will be removed in 6.0. Use the Sendmail or SMTP transport instead.

webtrees/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:267 stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

**Comment by fisharebest** [comment]
> I made the change to session.php. It did not help.

Do you mean that

1) you changed `session.php` so that it does not report deprecation notices.
2) you still see deprecation notices in your error log when you send mail

**Comment by melizaa** [comment]
I created an error situation by using a wrong SMTP mail server password.
The session.php was the old one that used to work on my site at 20:42 and without E_DEPRECATED,
if (WT_DEBUG) {
//@@	error_reporting(E_ALL | E_STRICT | E_NOTICE | E_DEPRECATED);	
	error_reporting(E_ALL | E_STRICT | E_NOTICE);	//@@
} else {
	error_reporting(E_ALL);
},
at 20:48.
In both cases I did not receive any email and in both cases I see the same error message.

I have for a long time the following code after the above error
if ($_SERVER['REMOTE_ADDR']=="5.29.20.216" && !ini_get('display_errors')) //@@ show errors on webpages for my IP address
{ //@@
  ini_set('display_errors','1'); //@@ does not have any effect on fatal errors!!
} //@@

I see that WT_DEBUG is 1.

Meliza

![image](https://cloud.githubusercontent.com/assets/5202996/22629917/b2dfe272-ebf8-11e6-8841-636117cd1687.png)

**Comment by fisharebest** [comment]
Try

```
error_reporting((E_ALL | E_STRICT | E_NOTICE ) & ~E_USER_DEPRECATED )
```

> ini_set('display_errors','1'); //@@ does not have any effect on fatal errors!!

In PHP 5.6, you cannot catch fatal errors.
In PHP 7.0, you can catch them.

**Comment by melizaa** [comment]
Greg,

 

I do not understand what you suggest that I do?

 

Is this what I should test?
if (WT_DEBUG) {

               error_reporting((E_ALL | E_STRICT | E_NOTICE ) & ~E_USER_DEPRECATED )

} else {

               error_reporting(E_ALL);

}

 


This gives
The amitys.com page isn’t working


amitys.com is currently unable to handle this request.

HTTP ERROR 500

 

 

Meliza

**Comment by fisharebest** [comment]
I think this issue is out of date.
