### ISSUE TITLE
Document getting a development environment setup

### ISSUE THREAD

**Issue by mnoorenberghe** [fisharebest/webtrees#1197]
It would help contributors if the process for getting a development site setup from GIt was documented in the README (or another repo file at the top-level) and/or on https://wiki.webtrees.net/en/Category:Development_Guidelines

The main thing that's not clear is the Makefile targets.

**Comment by mnoorenberghe** [comment]
Instructions for using vagrant would also be good if that's what is preferred.

**Comment by fisharebest** [comment]
> The main thing that's not clear is the Makefile targets.

See https://wiki.webtrees.net/en/How_to_create_a_webtrees_release

**Comment by fisharebest** [comment]
Vagrant was used to create a PHP 5.3 environment for testing.
We no longer support this version of PHP.
I no longer use Vagrant, and am unable to support it.

Personally, I now use [Laravel Valet](https://laravel.com/docs/5.5/valet)

**Comment by mnoorenberghe** [comment]
It would be great to have instructions for setting up a dev environment… every time I want to contribute I have to fiddle to get everything working again. Unfortunately the README is only targeted at users, not devs.
