### ISSUE TITLE
Header line for a family is missing when name type is set to married

### ISSUE THREAD

**Issue by ccprog** [fisharebest/webtrees#1202]
If you open a family page where at least one of the parents has a name entry like
```
1 NAME Walter /Smith/
2 TYPE married
2 GIVN Walter
2 SURN Smith
```
where `TYPE married` is set, the header line (**Walter Smith + Barbara Adams**) is missing. Same for the entry in the calendar view; the only thing you see looks like this, without a link to anything:
+  
    Marriage — June 3 1956

In the right column Family list, after expanding a name, only the year fo marriage is shown (and is a link)

After removing the `TYPE` line for both partners, or setting one or both to `birth`, the header line comes back.

Version 1.7.9, lighttpd/1.4.35, MySQL 5.7.17, PHP 5.6.29

**Comment by vytux-com** [comment]
That is almost what I would expect as that is not the person's birth name... 

Actually I would expect the system to show unknown unknown rather than blank.

If you do not know the proper birth name an only married name you should still enter at least the first name with the surname unknown for the actual person's name

**Comment by ccprog** [comment]
Well, what I would expect is a proper explanation in the program how to use fields.

Point is, if I know both the birth name and the married name, and if I want to display the married name, who tells me that I should not use the type field to indicate which of the two it is?

And what you expect is certainly not what should be shown to end users. Either the usage of a field is  erroneous, and should be prevented/an error mesage shown, or it is legit, and should end with a sensible and error-free view.

**Comment by vytux-com** [comment]
If you enter both birth and married name it will work properly as the system is designed to handle multiple names.

**Comment by ccprog** [comment]
Just to make it totally clear: I am not posting here to ask for support. There is a forum for that. 

**This is a bug report.** It stays one even if you think I am using the program wrong.

**Comment by fisharebest** [comment]
When both spouses only have married names, then no name gets generated.  Fixed.

**Comment by ccprog** [comment]
If one parent is completely unknown, your fix unfortunately generates a fatal error:
```
PHP Fatal error:  Call to a member function getAllNames() on null in /home/claus/webworking/webtrees/app/Family.php on line 347
```
and trying to go to that individuals page crashes during page generation.

**Comment by fisharebest** [comment]
In my own tree, I always create two parents - even if one is unknown.

**Comment by ccprog** [comment]
I'm importing data here. 100+ Error log entries were generated for, as far as I have found, one instance like this in 300 individuals. Import completed without visible error; only afterwards the page crash appeared.

**Comment by wkitty42** [comment]
On 02/05/2017 12:52 PM, Greg Roach wrote:
> In my own tree, I always create two parents - even if one is unknown.

we never do... if only one parent is known, that is the only one we create... if 
the other parent is discovered, then we create that record at that time... 
otherwise we have numerous children with only one parent as well as marriages 
with only one person... we find this to be ""better"" in a manner of sorts than 
to have a bunch of "unknown" listed...

2 centavos, FWTW...

**Comment by fisharebest** [comment]
> If one parent is completely unknown, your fix unfortunately generates a fatal error:

Not in my testing.

Your error is on line 347, yet `->getAllNames()` exists on line 346.

Which version of the code are you using?  Do you have any local modfiications?
Are you able to reproduce the problem on the demo server?

**Comment by ccprog** [comment]
You are right, my bad. I had applied the patch manually on top of 1.7.9. The reported error is invalid.
