### ISSUE TITLE
Webtrees logs 127.0.0.1 instead of client IPv6 address

### ISSUE THREAD

**Issue by kohtala** [fisharebest/webtrees#1203]
The issue #1023 is still not fixed in 1.7.9. Database seems to have wider ip_address fields as result of #1088.

If the client came through proxy that set stored the client IPv6 address in the Client-IP or X-Forwarded-For headers, Webtrees now logs the IPv6 address.

If the client reached server directly using IPv6 and Webtrees sees IPv6 address in REMOTE_ADDR, it still logs 127.0.0.1 instead of the IPv6 address.

I would expect to see the IPv6 address in the log.

**Comment by Joppla** [comment]
Greg wrote me on the forum:

```
>But are IPv6 addresses shown in webtrees?

The "access rules" logic was added a long time ago - before IPv6 was widely used.

It simply ignores IPv6.

The site-access-rules was added because we must prevent search engines from visiting some pages (e.g. calendar.php). There are better solutions to this problem. The site-access-rules will be removed in a future release of webtrees. 
```
