### ISSUE TITLE
List of individuals "strangly" sorted

### ISSUE THREAD

**Issue by marku5** [fisharebest/webtrees#1204]
wt 1.7.9
Settings > Preferences
If setting "Lists > Surname list style" is set to "list" or "tag cloud" the the order of names in Lists>Individuals seems to be random!? Maybe I do not get the scheme...
When set to "table" order of names is according ASCII-code.

I assume/suggest that it's always sorted A-Z or according number of occurrences.

**Comment by fisharebest** [comment]
I can't reproduce this.

Which (exact) version of MySQL (or MariaDB) are you using?

**Comment by marku5** [comment]
Hi Greg,
I'm using 5.5.53-MariaDB and PHP 7.0.15.

**Comment by marku5** [comment]
I'll try.

At least one other user (see [here](https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-9/31920-solved-control-panel-f-trees-manage-ft-pref-lists)) has same issue.

**Comment by fisharebest** [comment]
> I'll try the ex-/import procedure.

Did this help?

Can you give *full* details of the problem, and maybe a link to your site?

The other user reported that only the letter M was unsorted.  Is your problem also with just one letter?

It's hard to guess what might be causing this, and there's very little information to go on.

**Comment by marku5** [comment]
Yes, ex- and importing solved this. Now the list and tag cloud are sorted alphabetically; the table always has been correct. How could this happen?

The separete letter filters ("e.g. "M") always have been properly sorted.

> If so, export to GEDCOM and import will recreate the sort/search indexes.

Is there any other way (than ex-/import) to reset the indexes? Probably yes...but what to change in db?

**Comment by fisharebest** [comment]
> Is there any other way (than ex-/import) to reset the indexes?

No.

We must decode each gedcom record, identify name parts, places, dates, links, etc.  We then store these in the name/place/date/link tables.

This is a complex PHP script.

**Comment by marku5** [comment]
Ok, thanks for your explanation.
