### ISSUE TITLE
More specific error message in addmedia.php

### ISSUE THREAD

**Issue by marku5** [fisharebest/webtrees#1205]
My PHP-server had setting `upload_max_filesize=32M`.

When trying to upload larger files I get message "`.../webtrees/addmedia.php:410 Bad $action () in addmedia.php`"

Even with setting `upload_max_filesize` to a larger value I keep getting this error!?

Suggestion is to fill variable `$action` to get a more specific output for `too` large files (if this applies here):
`default:
	throw new \Exception('Bad $action (' . $action . ') in addmedia.php');`

**Comment by fisharebest** [comment]
addmedia.php has been removed in the latest develoment code.
