### ISSUE TITLE
individual.php divorce display issue.

### ISSUE THREAD

**Issue by muadhh** [fisharebest/webtrees#1206]
woman1 marries man1
woman1 divorces man1

woman1 marries man2

now in each of their individual.php page this is what shows:
===================
man1:

man2 + woman1 -veiw this family
wife's husband man2  ===> should be ex-wife's husband.
ex-wife woman1
Marriage:-
====================
man2:

man1 + woman1 -veiw this family
wife's husband man1 ===> should be wife's ex-husband.
wife woman1
Divorce:-
======================
woman1:

shows correctly.

**Comment by fisharebest** [comment]
For the names of immediate relatives, we check for "modifiers".  e.g twin brother, older sister, ex-wife, etc.

For relationships with two or more steps (e.g. father's brother), we have only one translation.  This code cannot apply the "modifiers".

**Comment by muadhh** [comment]
It has nothing to do with translation, it is showing an ex-wife as a current wife and an ex-husband as a current husband.

**Comment by muadhh** [comment]
![image](https://cloud.githubusercontent.com/assets/25746751/22939935/5c91893e-f2f1-11e6-83e5-804237a6af94.png)
![image](https://cloud.githubusercontent.com/assets/25746751/22939995/837770f4-f2f1-11e6-8395-924b6bf0f7f8.png)
![image](https://cloud.githubusercontent.com/assets/25746751/22940024/9471da52-f2f1-11e6-8a82-a6533f2124b3.png)
