### ISSUE TITLE
Default language: is it possible to stick it?

### ISSUE THREAD

**Issue by Assisto** [fisharebest/webtrees#1208]
Hi, 

Is it possible to stick **default language** irrespective to browser?
I know it can be done through hooking **function languagetag**, but is there another way to do so? 

thanks

**Comment by fisharebest** [comment]
If a visitor only speaks Polish, and sets their browser to Polish, you want to force them to use another language?

Why?

**Comment by Assisto** [comment]
My logic is: I want to minimize users' frustrations from many options -> and remove language from menu. As many relatives not so friendly with computer... Unfortunatelly, not all users understand browser issues...
And when users visit from other language browser - English language appears...

**Comment by fisharebest** [comment]
> and remove language from menu (as well many other options)

You can remove languages from the menu.  Control panel -> Website > Languages.

But this only removes them from the menu.  They are always available using browser-negotiation.

> And when users visit from other language browser - English language appears...

Can you give an example of this?

For visitors, webtrees should *always* use the language from the browser.

**Comment by Assisto** [comment]
For example, when default language is polish, users, who don't care about browser settings (in my case couple of Android/iPhone phones) - will always see English.
 
> For visitors, webtrees should always use the language from the browser.
Exactly, but I want to change this behaviour to default language.

**Comment by vytux-com** [comment]
So you are saying that a user that can understand enough English to be able to use the browser in that language and therefore not bother to change the language will be confused by the login page being in English?

**Comment by fisharebest** [comment]
> For example, when default language is polish, users, who don't care about browser settings (in my case couple of Android/iPhone phones) - will always see English.

Are you saying that

1) The phone is configured for Polish
2) The user visits your site for the first time (no cookies)
3) They see the page in English

**Comment by Assisto** [comment]
I have checked... 
If the phone configured for Polish -> webtrees is Polish,
but if phone is English (more often then I think) -> webtrees is English - which is not convinient sometimes. 

As I understand correctly -> Is that case, the only solution - hook languagetag function

**Comment by fisharebest** [comment]
> but if phone is English (more often then I think) -> webtrees is English

When you setup a new phone, it asks you to choose a language.

If **everything** on the phone is English, then either

1) the person understands English
2) the person will get help to convert the phone to Polish.

I think you are trying to fix a problem that does not exist.
Your change will break things for poeple who have set their phones with the correct language.

But if you really want to do this, edit the file app/Init.php and change `function httpAcceptLanguage()` to return and instance of `new LocalePl`.

**Comment by Assisto** [comment]
Indeed, may be I am exaggerating that problem, as statitically not enough data - only few users... 
Anyway, thank you very much for discussion and ideas.
