### ISSUE TITLE
starred name span off by one with nicknames

### ISSUE THREAD

**Issue by LarsEighner** [fisharebest/webtrees#1209]
When a nickname is starred, it is rendered in the full name with the opening quote underlined but the closing quote not.  Either both quotes should go in the span (preferred for typography) or neither should. This problem is observed in ltr. Situation in rtl is not known to me.

ex: &lt;span class="starredname"&gt;“Lars&lt;/span&gt;” 
should be: &lt;span class="starredname"&gt;“Lars"&lt;/span&gt;
or: "&lt;span class="starredname"&gt;Lars&lt;/span&gt;”

**Comment by fisharebest** [comment]
What is the GEDCOM behind this name?

**Comment by LarsEighner** [comment]
1 NAME Laurence Vail /Eighner/
2 GIVN Laurence Vail
2 SURN Eighner
2 NICK Lars*
2 NOTE [FamiliesWiki](http://families.larseighner.com/index.php/Main/LaurenceVailEighner)

**Comment by LarsEighner** [comment]
// A suffix of “*” indicates a preferred name
`$full` = preg_replace('/([^ >]*)\*/', '<span class="starredname">\\1</span>', $full);`
