### ISSUE TITLE
GEDCOM Export and then Import does not work - Github code

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1210]
I wanted to upload my production Gedcom file to my test system in order to find some odd behavior.

I exported the file from the production system and imported the exported file to the test system from my local computer. Something worked for a while. After this I saw that the Gedcom data was not updated. 

I tried to do this a couple of times to confirm that I had done what I expected to do and that it did not work.

I then uploaded the exported file to the server and imported it. After importing the file I see that the statistics counters in the test system are identical to the counters in the production system and I managed to detect the problematic record and to correct it in the production system.

We should remove the Gedcom import from the local machine (your computer) option as long as it does not work.

**Comment by fisharebest** [comment]
How big was the GEDCOM file?

What are you PHP limits for uploading files? (PHP settings `upload_max_filesize` and `post_max_size`)

My guess is that your server is blocking large file uploads.

**Comment by melizaa** [comment]
Yes the file is pretty big. It is a little over 17MB, some 28 thousand individuals...
upload_max_filesize - 60M.
post_max_size - 8M.
max_execution_time 500.
Some 27 thousand individuals were uploaded by export & import.

But why does it work as expected from the server?

Meliza

**Comment by fisharebest** [comment]
> But why does it work as expected from the server?

The limit `post_max_size` is a limit on *file uploads*.

The option to load files from the server exists for people who cannot alter `post_max_size` and `uplad_max_filesize` on their server.

These users need to copy the file to the server using FTP/SFTP.

If you cannot change these server settings, then you cannot upload files larger than 8MB.  There is nothing webtrees can do.
