### ISSUE TITLE
Find unrelated individuals - 500 - server configuration error - 1.8.0-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1211]
I get the error in the test and prod systems, for small test files and for the big production file.

What do I need to change in the configuration?

Meliza

**Comment by fisharebest** [comment]
https://webtrees.github.io/faq/500

**Comment by melizaa** [comment]
I get the error also for the small Duck file.

I do not see new errors in the webtrees error logs.
In the cPanel Errors I see 2 types of errors.
several times [access_compat:error] [pid nnnnn] [client ip address:nnnn] AH01797: client denied by server configuration: .../webtrees/individual.php or .../webtrees/indilist.php
(also some for .../phpGedView that I no longer redirect to webtrees)

and some  
[:error][pid nnnnn] [client ip address:nnnnn] SoftException in Application.cpp:256: File ".../admin_trees_unconnected.php" is writeable by group, referer: .../admin_trees_manage.php 

What do I need to do?

Meliza

I hope that I copied the texts correctly.

**Comment by fisharebest** [comment]
> is writeable by group

Your file has "group write" permission.  e.g. `rwxrwxr-x` or `775`.
Your server is configured to prevent these being executed as PHP scripts.

> What do I need to do?

Remove the execute permission.  e.g. `rw-r--r--` or `644`.

**Comment by melizaa** [comment]
Thanks! Works!

I do not need to update the write permissions of any other program files. Why these?

**Comment by melizaa** [comment]
They were 664.

**Comment by fisharebest** [comment]
> Why these?

Perhaps these are files you edited/uploaded separately?
