### ISSUE TITLE
Wrong Icons in Color Thema

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#1213]
See attached screenshot. The icons in the 'personal facts edit menu' are mixed up.

 
![coloredit](https://cloud.githubusercontent.com/assets/25879600/23102011/4e42fb52-f6a1-11e6-9f46-badbcd482ccd.jpg)

**Comment by HonkXL** [comment]
I can confirm this!

**Comment by makitso** [comment]
Let me take a look at that.

**Comment by fisharebest** [comment]
@makitso - can you commit any changes to the `1.7` branch only.

(any changes to the `master` branch would cause conflicts with a major rewrite that is currently happening on the `develop` branch.)
