### ISSUE TITLE
Can't create reports

### ISSUE THREAD

**Issue by gnilebein** [fisharebest/webtrees#1215]
I can't create any type of report. I can not select a person and webtrees show me only the string "undefined" (Screenshot: http://imgur.com/a/w3mKD:

My Setup:
Webserver: Nginx
PHP: 7.0 via Fastcgi

No errors in PHP or Webserver Error log.

**Comment by fisharebest** [comment]
Did this stop working, or has this never worked?

Did you, perhaps, upgrade PHP?

**Comment by gnilebein** [comment]
I never used this feature befor. I did an upgrade from Ubuntu 14.04 to 16.04 a few weeks ago. But i didn't used it under 14.04.

**Comment by fisharebest** [comment]
My guess is that you have upgraded PHP, and failed to install some PHP libraries that were present in your previous version.

webtrees checks these during installation, but obviously not when you upgrade the server.

Perhaps try installing a new/clean version of webtrees in a temp folder, and seeing if you get any warnings on the first two pages.

**Comment by gnilebein** [comment]
PHP libs are ok. Ich tried it with webtrees standard Themen and it works. The issue only occour with justlight theme.

**Comment by fisharebest** [comment]
> The issue only occour with justlight theme.

Then you should report the issue at https://github.com/JustCarmen/justlight/issues
