### ISSUE TITLE
extra gender possibility

### ISSUE THREAD

**Issue by Joppla** [fisharebest/webtrees#1216]
Hello,

In my tree I have a transgender. Shouldn't it be nice to add an extra symbol for transgenders? Because "gender unknown" you use for people from who you the sex don't know. Or does GEDCOM standard give this option not?

Thanks

**Comment by fisharebest** [comment]
The GEDCOM standard provides only three options `M`, `F` and `U`.  I don't know if it would possible to extend this.

Also, transgender is one of many categories that do not fit into M/F/U.  Do we want to (need to) classify people's sex/gender exactly?

I would simply record the person using their new/chosen gender.

You could create a custom event to document the transition, or you could add a note to the name record.

```
1 EVEN
2 TYPE Gender reassignment
```

**Comment by Joppla** [comment]
If the gedcom gives only this 3 I think we have to accept this fact.

**Comment by Amgine0** [comment]
http://onlinelibrary.wiley.com/doi/10.1111/nin.12184/full

Note especially the comments on prevalence: more common than either red hair or AB- bloodtype.
