### ISSUE TITLE
B.C and A.C mixed in homepage statics block

### ISSUE THREAD

**Issue by marku5** [fisharebest/webtrees#1220]
When browsing the showcase trees I found this tree: [Our Family Jiapu](https://joeclan.net/webtrees/index.php?ctype=gedcom&ged=joeclan.ged).

Please check stats block
Earliest birth year | AD 202 (202) | Emperor Wen of Han, Birth  202 BC (-202), Death  157 BC (-157) (Age 45 years)

The rightmost columns shows that this indi lived B.C, whereas the middle column shows A.D.
Same for "Earliest death year"

Likely related to #1219, where I do see an empty col!?

**Comment by BertKoor** [comment]
Since the fix is in the v2 branch only, could this be patched in the v1.7 branch as well?

**Comment by fisharebest** [comment]
> could this be patched in the v1.7 branch as well?

Yes, it could.  This one is looks easy to back-port.

However, I don't have time to back-port **every** fix.  If I start doing some of them, there will be pressure to do all the others.

If someone has the time and inclination to create/test any back-ports, then I'd be happy to review/accept them.
