### ISSUE TITLE
SQL password exposed when PDO driver is missing

### ISSUE THREAD

**Issue by jviksell** [fisharebest/webtrees#1221]
After upgrading my lab server something broke and I stumbled onto this error:
```
/var/www/webtrees/app/Database.php:98 could not find driver
#0 /app/Database.php:98 PDOException("could not find driver")
#1 /includes/session.php:274 createInstance('localhost', '3306', 'webtrees', 'webtrees', 'PASSWORD')
#2 /individual.php:31 require('/var/www/webtrees/includes/ses…')
```

The version is webtrees-1.7.9.

**Comment by jviksell** [comment]
#1222

**Comment by fisharebest** [comment]
Just trying to reproduce this so I can test the PR.

Where do you see the error?

**Comment by fisharebest** [comment]
Also which version of PHP?

**Comment by jviksell** [comment]
It looks like the upgrade removed php5-mysql and that's the problem. This was after a do-release-upgrade on Ubuntu...
I saw it viewing /webtrees/individual.php?pid=I1&ged=tree1
PHP/5.5.9-1ubuntu4.21

**Comment by jviksell** [comment]
Just to be clear, I used:
curl -i  'http://192.168.56.101/webtrees/individual.php?pid=I1&ged=tree1'
In a browser the redirect is followed and nothing is shown.

It looks like the set_exception_handler in session.php will ouput stack traces for all exceptions.

**Comment by fisharebest** [comment]
Merged.
Thanks.
