### ISSUE TITLE
screen "edit changes" is to small

### ISSUE THREAD

**Issue by Joppla** [fisharebest/webtrees#1223]
For pending changes is opening a new screen, but the screen is opening to small in my opinion, lot of info is behind the scroll bars. See screenshot: ...
![screenshot](https://cloud.githubusercontent.com/assets/25467829/23438494/5c7d1fae-fe12-11e6-9520-2069a7b11025.png)

**Comment by Joppla** [comment]
![Uploading Screenshot - 28-02-17 - 21:31:14.png…]()

**Comment by fisharebest** [comment]
In webtrees 1.8, all popup windows will be removed.
The "Pending changes" page is now full-screen.

You can see this here: https://dev.webtrees.net/demo-future/

So, this has already been fixed - but the changes are not yet ready to merge into the main code.

**Comment by Joppla** [comment]
Geat!

I should like to see it, but to test I need an inlog to the Demo I presume ...

**Comment by fisharebest** [comment]
The demo sites all use the same database and same logins.  They are listed on the home page.

**Comment by Joppla** [comment]
Hi Greg,
Thanks! 
I have looked for it. I have a few comments about it if I may:

- The editing window is opening in the same window. At one site nice and faster, but ... I work general on 2 screens and it is always nice to have the main few open to see what is in the original few, or during editing to look for other information.
- The editing window is very much designed for tablets and phones, very well, but now for the desktop it is looking terrible (to big font, to wide screen) in my opinion and I have to scroll a lot to come to the save/cancel buttons. Shouldn't it be nicer to have for wider screens the lay-out in two columns and to have the save/cancel button on more places?

Hopefully helps this comment to get webtrees better :-)
Succes

**Comment by marku5** [comment]
Hello Joppla,
you may be interested in [this thread](https://www.webtrees.net/index.php/en/forum/2-open-discussion/31969-solved-future-design-of-wt), where I commented similar topics...
BR /Markus

**Comment by Joppla** [comment]
Hi Markus,
Thanks! What I see in the link you gave, they still work on it? Or is status today more or less definitive?

**Comment by marku5** [comment]
Hello Joppla,
From my understanding Greg and Rob clearly stated that they concentrate first on functionality, then on form/layout.
So I will be patiently waiting for their results...lot of things will change, especially on layout findings.
BR /Markus

**Comment by Joppla** [comment]
I too :)

**Comment by fisharebest** [comment]
These changes have now been merged.
