### ISSUE TITLE
Copy Media Objects to clipboard and add the copied objects to individuals or families.

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1225]
We can copy media objects on the Media tab.
Are they added to the clipboard?
Where can we use the copies?

It would be nice if we could add them to individuals in the individual Facts and events and the Media tab and in the family page.

**Comment by fisharebest** [comment]
> Where can we use the copies?

They appear in the list of facts/events to paste - same as other copied facts/events.

> It would be nice if we could add them to individuals in the individual Facts and events and the Media tab and in the family page.

You can.

**Comment by melizaa** [comment]
In demo-dev I see that I can add from the clipboard media to individuals on the Facts and events tab and to the family. 

I do not see an option to add from the clipboard media on the individual Media tab. This would be useful when I want to link a media object to several individuals and need 1st to make sure that it is not yet linked to the current individual.

**Comment by melizaa** [comment]
btw, we should in a similar way be able to add from the clipboard notes and shared notes in the Notes tab, sources in the Sources tab and media in the Album tab.
