### ISSUE TITLE
After name updating I see the nickname more than once - latest GITHUB code

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1226]
When I add a nickname to an existing name, it is added twice, once between the given name and the surname and the second time at the end of the name. 
If I add an aka-name or a married name to a name that has a nick-name, an additional nick-name is added. 

How can I detect these errors in order to correct them?
To search for such names in the changes log takes a lot of time.
I do not know how to search for such names in QMF, because I have in many cases two 1 NAME records, one for the Latin name and the second for the Hebrew name.

I see that the duplicate nicknames were added on my site at least from February 18.

**Comment by melizaa** [comment]
I have NICK in the family tree Advanced fact preferences in Advanced name facts.

**Comment by melizaa** [comment]
I have
1 NAME Aron /Kuha/
2 GIVN Aron
2 SURN Kuha

I add a nick-name and I get
1 NAME Aron /Kuha/
2 GIVN Aron
2 NICK Arele
2 SURN Kuha
2 NICK Arele

**Comment by melizaa** [comment]
The nickname is added both in
	$newged = '';
	if (!empty($_POST['NAME'])) {
		$newged .= "\n1 NAME " . $_POST['NAME'];
		$name_facts = ['TYPE', 'NPFX', 'GIVN', 'NICK', 'SPFX', 'SURN', 'NSFX'];
		foreach ($name_facts as $name_fact) {
			if (!empty($_POST[$name_fact])) {
				$newged .= "\n2 " . $name_fact . ' ' . $_POST[$name_fact];
			}
		}
	}

and in

	// Add new names after existing names
	if (!empty($_POST['NAME'])) {
		preg_match_all('/[_0-9A-Z]+/', $WT_TREE->getPreference('ADVANCED_NAME_FACTS'), $match);
		$name_facts = array_unique(array_merge(['_MARNM'], $match[0]));
		foreach ($name_facts as $name_fact) {
			if (!empty($_POST[$name_fact])) {
				$newged .= "\n2 " . $name_fact . ' ' . $_POST[$name_fact];
			}
		}
	}

If I do not add NICK in the additional facts, I do not see the nick-name field in the name form.

**Comment by fisharebest** [comment]
Some parts of the code treat `NICK` as a standard name fact.
Some parts of the code treat `NICK` as an "advanced" name fact.

GEDCOM 5.5.1 says this is a standard tag.  We should do this.
