### ISSUE TITLE
After updating individual data the sequence of the data changes - github code

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1227]
When I update a name or a date, it is not written at the same place in the individual or family record as it used to be.

This causes the Gregorian birth, death, marriage, etc. data to be written after the Hebrew data in the database and I see on the individual page, in the charts, in lists and in reports, a mixture of dates instead of the first Gregorian birth and death dates. 

I want to see the Latin name before the Hebrew name in lists and charts.
When I run QMF queries on the individual data I want to see the name at the top of the individual data.
If the name is updated it is moved away from the top and the Hebrew name will appear before the Latin name in the individual record.

I need to try to verify that the dates and names are in correct sequence and places in the individual and family records before I approve changes. I need periodically to run QMF queries that highlight the individuals and families with sequence issues and I need to use raw-editing to correct the sequence. This requires a lot of unnecessary time and effort. 

If we cannot write the updated data in its original place in the record, then we should sort the updated record before it is written to the DB.

**Comment by fisharebest** [comment]
> When I update a name or a date, it is not written at the same place in the individual or family record as it used to be.

Can you give an example of

1) what happens
2) what you expect to happen.

Facts/events are sorted when we display them, so the order in which they are stored should not matter at all.

**Comment by melizaa** [comment]
A sample from 2017-06-09 from the change log

0 @I1238@ INDI
1 NAME Abraham /Levit/
2 GIVN Abraham
2 SURN Levit
2 _HEB אברהם /לויט/
2 _AKA Abram Shlomo /Levith/
2 _AKA Meyer /Levith/
2 _AKA Abraham Shlomo /Levite/
2 _AKA אברהם שלמה /לויטה/
1 SEX M
1 BIRT **[deleted]**
2 DATE 06 DEC 1841 **[deleted]**
2 PLAC Nowogrod, Lomza, Poland **[deleted]**
2 NOTE or about 1838 **[deleted]**
1 DEAT
2 DATE CAL 07 OCT 1917
2 PLAC Helsinki, Finland **[added]**
1 BURI
2 PLAC Helsinki, Finland
1 FAMS @F726@
1 OBJE @M6221@
1 BIRT
2 DATE @#DHEBREW@ 5599
1 OBJE @M1244@
1 SOUR @S766@
1 FAMC @F727@
1 COMM Bikur Cholim founding member
1 OBJE @M95@
1 DEAT
2 DATE @#DHEBREW@ 21 TSH 5678
2 NOTE Hoshana Raba
1 _TODO Is he
2 DATE 02 JAN 2012
2 ASSO @I9036@
1 OCCU Butcher shop
1 CAST Levi
1 COMM Permission to remain after military service
2 DATE 29 MAR 1889
2 PLAC Helsinki, Finland
1 RESI Kampinkatu
2 DATE 1898
2 PLAC Helsinki, Finland
1 _MILT Soldier in local commando on furlough
2 PLAC Helsinki, Finland
2 DATE BEF 1880
1 NOTE Born 1839 or 1841
2 CONT 38 in 1880
2 CONT
2 CONT Registered in Novogrudska? (Nowogród?), Lomza, Poland
2 CONT (son - Tradesman (Burgher) in Danilov)
1 SOUR @S7@
2 PAGE 207
1 SOUR @S6@
2 PAGE 781
1 RESI
2 DATE FROM 1865
2 PLAC Helsinki, Finland
1 SOUR @S153@
2 PAGE 1890 Helsinki Census
1 RESI Fredrikinkatu 63
2 DATE FROM 1 JUN 1886
2 PLAC Helsinki, Finland
2 NOTE 1 room and a kitchen, 1 window to the garden, 2 windows to the street.
1 SOUR @S165@
2 DATA
3 TEXT Was another daughter (Xuna?) born 1865
1 RESI Lapinlahdenkatu 5
2 DATE 1880
2 AGE 38y
2 PLAC Helsinki, Finland
1 COMM Registered into Congregation
2 DATE 04 MAR 1875
2 PLAC Helsinki, Finland
2 NOTE On 4 March or on 24 May
1 SOUR @S2@
2 DATA
3 TEXT Old book page 36
1 SOUR @S168@
2 DATA
3 TEXT Bikur Cholim list - no. 8
1 SOUR @S247@
1 OBJE @M6222@
1 BIRT **[Added]**
2 DATE 06 DEC 1841 **[Added]**
2 PLAC Nowogrod, Lomza, Poland **[Added]**
2 NOTE or about 1838 **[Added]**
1 SOUR @S1085@
2 DATA
3 TEXT VeSA 5628:953, 5730 s. 67, 7562:4, KS 1895 s. 3; SSiv; MG
2 NOTE Levita/Levit, Abraham/Abram-Šlomo Itskovitš (s. 6.12.1841 – k. 7.10.1917? H:ki), Łomżan kuv. Nowo¬gród; palv. 1865; rvm, 92.Petšoran JR, H:ki; HSS 1870; > aseett. palv. Suomen sot.piirin pääll. käyttöön 1870; H:gin PaikKK 1871; lihakauppias, H:ki 1888/1915. (VeSA 5628:953, 5730 s. 67, 7562:4, KS 1895 s. 3; SSiv; MG)
1 CHAN
2 DATE 10 JUN 2017
3 TIME 00:17:37 **[Deleted]**
3 TIME 00:18:09 **[Added]**
2 _WT_USER admin

Before the change I saw the Gregorian birth year on the indi-page. After the change I see the Hebrew year. On my site I should see in the indi page name row the Gregorian or Julian years. 

I see after the update a mixture of dates
![image](https://user-images.githubusercontent.com/5202996/27453752-291aa946-57a0-11e7-87ef-c8a094cd1b6a.png)

**Comment by melizaa** [comment]
It seems that not all the Birth/Death/Marriage changes cause the changed record to be written after the Hebrew date one.

**Comment by melizaa** [comment]
Names
According to the 5.5.1 standard, the name structure should exist after the indi level 0 record and before the SEX tag.  This is how webtrees creates new individuals. When the Latin name is updated, it is moved to the end of the indi record.
It seems that webtrees prints the name as expected. 
My problem is when I run queries in SQL. To make it easier to read the query results, I should see the name at the top.

Meliza

**Comment by fisharebest** [comment]
I am unable to reproduce this with the latest code.

If I edit a fact or a name, the updated fact is in the same position in the GEDCOM data.

Do you still have the problem?

**Comment by melizaa** [comment]
I tried to carry out 2 tests tests in demo-dev. I did not see the issue.
On my site I show either a Gregorian, Julian or Hebrew date, not a translated date.

My site is not ready for testing. I do not now have time to prepare my site for testing.
I will carry out testing on my site as soon as I can update the code. 

Meliza

**Comment by fisharebest** [comment]
If the problem can be reproduced, please create a new issue.
