### ISSUE TITLE
PHP7.1 problem with indilist.php and famlist.php

### ISSUE THREAD

**Issue by mpwt** [fisharebest/webtrees#1229]
I use webtrees 1.7.9 with some code additions from the 1.7.10-dev. I have two trees, one semi-open and one closed for visitors. My provider offers PHP up to 7.1.

With the semi-open tree I havn't any problems with PHP 7.1 but within the closed tree I found a strange error now on indilist.php:

`/home/bauschaf/webtrees_ffp/includes/session.php:193 /home/bauschaf/webtrees_ffp/app/Functions/FunctionsPrintLists.php:150 A non-numeric value encountered #0 /app/Functions/FunctionsPrintLists.php:150 ErrorException("/home/bauschaf/webtrees_ffp/app/Functions/FunctionsPrintLists.php:150 A non-numeric value encountered") #1 /indilist.php:261 individualTable([array])
`

and famlist.php:

`/home/bauschaf/webtrees_ffp/includes/session.php:193 /home/bauschaf/webtrees_ffp/app/Functions/FunctionsPrintLists.php:589 A non-numeric value encountered #0 /app/Functions/FunctionsPrintLists.php:589 ErrorException("/home/bauschaf/webtrees_ffp/app/Functions/FunctionsPrintLists.php:589 A non-numeric value encountered") #1 /famlist.php:261 familyTable([array])
`

when I clicked on a surname. All works well if I use PHP 7.0. 

Why I found this error only in one tree and not in the other too? Twice are hosted at the same hoster, same webtrees installation and same database.

The tree "OFBRadis" is a test for a heritage book starting in 1652. All persons are born after this starting date or are parents. But I didn't enter a 1 DEAT Y for all persons at the moment.

**Comment by fisharebest** [comment]
`Stats::longlifeQuery()` is returning a I18N formatted string.  e.g. `1,234`.
`max()` is rejecting this non-numeric value.
