### ISSUE TITLE
PGW Wizard: language mo file not found

### ISSUE THREAD

**Issue by jerry1970** [fisharebest/webtrees#1232]
During the PGV wizard I got an error that the nl.mo file was not found. In git there is only a nl.po file so I copied that but that didn't help. I then made a copy of the only mo file I found: en-US.mo to nl.mo and then it worked. Where is the nl.mo file? Shouldn't the wizard switch to a default language whent he PGV lagnuage is not found?

**Comment by fisharebest** [comment]
> I got an error that the nl.mo file was not found

Do you have the *exact* error message?

**Comment by jerry1970** [comment]
No sorry, I should have copied the text but forgot and now it's working. But I remember it was an error on `fopen()` when searching for the `nl.mo` file. My PGV was set to NL but my installation of Webtrees only had en-US.

**Comment by fisharebest** [comment]
> but my installation of Webtrees only had en-US.

That is because you have just copied the source code from github.

You should have downloaded the release package, which contains these files.
