### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by kabe95** [fisharebest/webtrees#1237]
I have just installed webtrees and after the installation I come to the login page, but whenever I try to login, I get the message: You can't log in, because your browser doesn't support cookies.

I'm using Safari 10.1 on a Mac, and cookies should be allowed for all websites.

**Comment by fisharebest** [comment]
Post the URL of your site.

**Comment by kabe95** [comment]
kasperbergholt.dk/slaegt

**Comment by fisharebest** [comment]
I get "404 not found" at that address.

**Comment by wkitty42** [comment]
i get a login screen with some grey box over the name and password fields saying that it is not a secure connection...

**Comment by fisharebest** [comment]
@wkitty - yours is a completely different issue.  Most modern browsers will complain if you have a password field on an HTTP (not HTTPS) connection.  To fix this, upgrade your server to use HTTPS.

**Comment by wkitty42** [comment]
On 04/16/2017 05:26 PM, Greg Roach wrote:
> @wkitty <https://github.com/wkitty> - yours is a completely different issue.
> Most modern browsers will complain if you have a password field on an HTTP (not
> HTTPS) connection. To fix this, upgrade your server to use HTTPS.

not my server, greg... i tried the url given above that you reported 404 on... i 
got a logon page there at that same url...


i know the browsers are playing games and warning about insecure servers ;)


-- 
  NOTE: No off-list assistance is given without prior approval.
        *Please keep mailing list traffic on the list* unless
        private contact is specifically requested and granted.

**Comment by kabe95** [comment]
I don't know, why you get 404, it works fine for me. I have just re-installed it, and now when I log in, it redirects to "http://www.kasperbergholt.dk/slægt/login.php?url=index.php%3F", which is the same page.

**Comment by fisharebest** [comment]
@kabe95.

If you rename the folder from slægt to slaegt, does it help?

**Comment by fisharebest** [comment]
If this does help, can you edit includes/session.php and change

```
	'cookie_path'    => parse_url(WT_BASE_URL, PHP_URL_PATH),
```

to

```
	'cookie_path'    => rawurlencode(parse_url(WT_BASE_URL, PHP_URL_PATH)),
```

**Comment by kabe95** [comment]
It worked when I renamed it. Thank you very much!

**Comment by fisharebest** [comment]
Can you try the change above (using slægt)

**Comment by kabe95** [comment]
Looks like that also works

**Comment by kabe95** [comment]
No, wait. When it's called slægt I can't log in, not even if I change that line. But it works when it's called slaegt.

**Comment by fisharebest** [comment]
On my development server, if I change the folder name to slægt then it stops working.
If I also make the change to `cookie-path`, then it works OK.

According to several articles on the web, this is the correct solution for the problem.

>No, wait. When it's called slægt I can't log in, not even if I change that line. But it works when it's called slaegt.

Can you check again.

**Comment by magicsunday** [comment]
Your change in https://github.com/fisharebest/webtrees/commit/e934f1277463c621bd9d93e2716e97dbd2844e4a also fails for me, if I try to use my pages together with an iPad. In my windows 10 firefox all works fine, but safari on iPad fails to load the page. Instead i renders the error message "You cannot sign in because your browser does not accept cookies" as $_COOKIE is always empty.

**Comment by fisharebest** [comment]
> Your change in e934f12 also fails for me

Does this mean that

1) it worked before the change, but it does not work after the change
2) It didn't work before the change, and still does not work after the change.

On my development server, I was able to reproduce the problem (UTF8 characters in cookie path) and was able to fix it by url-encoding the cookie path.

You will need to provide more details that might help me reproduce your problem.  What cookies are set?  What paths are set for them?  etc.

**Comment by magicsunday** [comment]
1. yes, if I revert the change it works again

rawurlencode encodes the cookie path "/" to "%2F". This fails for the "cookie-path".

**Comment by magicsunday** [comment]
👍
