### ISSUE TITLE
Support for DKIM signing for the mails

### ISSUE THREAD

**Issue by anmol26s** [fisharebest/webtrees#1238]
Can you please impliement the DKIM signing in Mail.php so that the emails can have better delivery to other providers.

Demo code for swiftmailer: [http://www.martyhermsen.nl/2015/08/12/php-swiftmailer-version-5-supports-dkim-signing/](http://www.martyhermsen.nl/2015/08/12/php-swiftmailer-version-5-supports-dkim-signing/)

Thanks

**Comment by dverdin** [comment]
Alternatively, you can use tools like [Rspamd](https://www.rspamd.com/doc/modules/dkim_signing.html) to make your outgoing MTA sign messages.
that's what I did for my own Webtrees instance and it works like a charm.
Cheers!

David

**Comment by fisharebest** [comment]
The link no longer works.

There is no documentation for `Swift_Signers_DKIMSigner` in the Swiftmailer documentation - and very little online.

According to this page, it won't work with multi-part mail.  (webtrees uses mult-part mail).
https://stackoverflow.com/questions/31591078/swiftmailer-dkim-fails-only-with-multipart-email

**Comment by fisharebest** [comment]
I get the same problem that was reported in the stackoverflow article, the body hash fails for multipart/alternative messages.

So, I only attach the HTML part when DKIM is used.

I don't use DKIM.  I used on online testing tool.

I would appreciate any feedback and/testing.
