### ISSUE TITLE
RecentChangesModule (v 1.8dev)

### ISSUE THREAD

**Issue by Gustine** [fisharebest/webtrees#1239]
Hello,
Since last change of RecentChangesModule.php on April 25, I get this error :
Fatal error: Call to a member function canShow() on null in /home/.../app/Module/RecentChangesModule.php on line 215

**Comment by Gustine** [comment]
Sorry, error is still present.

**Comment by fisharebest** [comment]
Line 215 is this.

```
if ($record->canShow()) {
```

Change to

```
if ($record === null) var_dump($xref);
if ($record->canShow()) {
```

This will tell you the XREF of the record that is causing the problem.

Now investigate this record in the table wt_change.

What data do you see?

**Comment by Gustine** [comment]
string(4) "R103"
Fatal error: Call to a member function canShow() on null in 
/home/gustine/wt3/app/Module/RecentChangesModule.php on line 216

Oups. Very specific problem : I renamed (with phpmyadmin) R103 in R49A 
probably when creating S3664 
<https://gustine.eu/wt3/source.php?sid=S3664&ged=Riviere-LeDu> when 
editing I3993. But R103 is no more present in the gedcom.

**Comment by fisharebest** [comment]
> I renamed (with phpmyadmin) R103

If you do this, you should rename ***every** reference to R103.  This includes the tables `wt_change`, `wt_link`, `wt_name`, `wt_default_resn`, etc., etc.,

**Comment by Gustine** [comment]
OK I'll just wait for a few days so that the problem disappears.
(but with 1.7.9 and the same database, there is no error)

**Comment by fisharebest** [comment]
> but with 1.7.9 and the same database, there is no error

1.7.9 only shows changes in individual and family records.
1.8.0 will show changes in all types of record.

**Comment by Gustine** [comment]
Thank you for these explanations. Now I understood everything :-)

**Comment by Gustine** [comment]
Same problem when deleting a _recently changed_ item.

**Comment by Shemwell** [comment]
I get the same error every time I delete an individual.
