### ISSUE TITLE
Report Menu - Undefined function

### ISSUE THREAD

**Issue by rchampagneca** [fisharebest/webtrees#1241]
Any item under the reports menu is producing the following message:

`/var/www/webtrees/app/Report/ReportParserBase.php:36 Call to undefined function Fisharebest\Webtrees\Report\xml_parser_create() #0 /reportengine.php:136 Error("Call to undefined function Fisharebest\Webtrees\Report\xml_parser_create()")`
 
---

Server: PHP Version 7.0.15-0 - Ubuntu0.16.04.4
Webtrees release: 1.7.9

**Comment by fisharebest** [comment]
Your server does not have the PHP libraries `php-xml` and `php-simple-xml`.

webtrees checks for necessary PHP libraries during installation.
If you tried to install webtrees now, you would see an error message.

I guess that you upgraded PHP on your server, but did not install the same libraries.

Install these, and it will work.

**Comment by rchampagneca** [comment]
Thank you. Installed as you had suggested php-xml. Regards. Roger.
