### ISSUE TITLE
Censuses of Czech Republic

### ISSUE THREAD

**Issue by jpretired** [fisharebest/webtrees#1243]
I would like to add/replace the following modified and added census files (into app/Census):
CensusOfCzechRepublic.php
CensusOfCzechRepublic1880.php
CensusOfCzechRepublic1890.php
CensusOfCzechRepublic1900.php
CensusOfCzechRepublic1910.php
CensusOfCzechRepublic1921.php

Zip file appended.
[CensusOfCzechRepublic.zip](https://github.com/fisharebest/webtrees/files/981710/CensusOfCzechRepublic.zip)

**Comment by jpretired** [comment]
Is this the right way to supply modified/new php scripts to be included into webtrees?

**Comment by fisharebest** [comment]
This is fine.

I will hopefully add them to the next release.

I have been very busy recently.
