### ISSUE TITLE
Incorrect date comparing?

### ISSUE THREAD

**Issue by AppChecker** [fisharebest/webtrees#1244]
Hi!

Please, look [code in compare function](https://github.com/fisharebest/webtrees/blob/d09b5ef1f1f6fb27bc5d182e072c66ef08770e71/app/Date/CalendarDate.php#L410-L413):
```
		if ($d1->maxJD < $d2->minJD) {
			return -1;
		} elseif ($d2->minJD > $d1->maxJD) {
			return 1;
		} 
```
Condition in if and in elseif are equivalents.

May be it should be:
```
		if ($d1->maxJD < $d2->minJD) {
			return -1;
		} elseif ($d2->minJD < $d1->maxJD) {
			return 1;
		} 
```

This possible defect found by [AppChecker](https://npo-echelon.ru/en/solutions/appchecker.php)

**Comment by fisharebest** [comment]
Surprised that this hasn't been noticed before.  I guess it depends on the sort algorithm which calls it.

Fixed. in 1.7, master and develop.
