### ISSUE TITLE
Auto-check PHP dependencies after server migration (or PHP upgrade)

### ISSUE THREAD

**Issue by BertKoor** [fisharebest/webtrees#1246]
A couple of times per month I read in the forum a user has migrated a webtrees instance to another hosting provider (or upgraded the server's PHP config) to discover some core libraries are missing. The initial setup script does perform some preliminary checks on dependencies, so the logic is already there.

How hard would it be for webtrees to detect somehow it has been migrated (or PHP version has changed) and then perform the same check on dependencies it would do on a fresh install?

I think this will save some headaches in hunting down illusive bugs, giving the admin clear messages of what exactly is lacking in the new config.

**Comment by fisharebest** [comment]
I have added all the "installation" checks to the control panel.

Note that this won't catch everything, as some features are required before we get to the control panel (e.g. database drivers).

**Comment by BertKoor** [comment]
Nice!
Thank you!
