### ISSUE TITLE
Error when removing a source

### ISSUE THREAD

**Issue by Bonbadil** [fisharebest/webtrees#1248]
Hello,

I'm using the develop branch from today.
I want to remove a source from an event. The only way I see is by using the little cross at the end of the source selector. When I try to save, I get:
```
/[...]/webtrees-git/includes/session.php:155 /[...]/webtrees-git/app/Functions/FunctionsEdit.php:1382 Undefined offset: 29
#0 /app/Functions/FunctionsEdit.php:1382 ErrorException("/[...]/webtrees-git/app/Functions/FunctionsEdit.php:1382 Undefined offset: 29")
#1 /edit_interface.php:445 handleUpdates('')
```
As a workaround, I delete the line from GEDCOM tags.

**Comment by fisharebest** [comment]
We use the "select2" module for this input control.

The "clear" button selects *nothing*.  Therefore the value is not submitted with the form.

Instead, it should select an empty string - which will be submitted.
