### ISSUE TITLE
Forced logout

### ISSUE THREAD

**Issue by peterkromanpeter** [fisharebest/webtrees#1249]
Hi, 
Is it possible for admin to perform a forced logout of a user? And if so, how to do :) 
Regards Peter

**Comment by fisharebest** [comment]
There is no way to do this using the web interface.

You could delete their sessions (which would log them out) from the database:

`DELETE FROM wt_session WHERE user_id= ...`

**Comment by peterkromanpeter** [comment]
Thanks Greg, 
Just needed to know :)
