### ISSUE TITLE
Array was modified by the user comparison function (v1.8dev June 17)

### ISSUE THREAD

**Issue by Gustine** [fisharebest/webtrees#1250]
Asking for List of branches, I get this error :
 /home/…/includes/session.php:154 /home/…/app/Controller/BranchesController.php:133 usort(): Array was modified by the user comparison function #0 unknown:unknown ErrorException("/home/…/app/Controller/BranchesController.php:133 usort(): Array was modified by the user comparison function") #1 /app/Controller/BranchesController.php:133 usort([array], '\\Fisharebest\\Webtrees\\Individu…') #2 /app/Controller/BranchesController.php:59 loadIndividuals() #3 /branches.php:25 __construct()

**Comment by fisharebest** [comment]
What version of PHP?

**Comment by Gustine** [comment]
php 5.6.30

**Comment by fisharebest** [comment]
This seems to be https://bugs.php.net/bug.php?id=71238 although I'm not sure why we are only just seeing this.  The code has not changed in a long time.

Have you used development versions of webtrees before?

Development versions trap every warning and notice.
Stable releases only trap serious errors.

Does the error go away if you edit includes/session.php and change WT_DEBUG to false.

**Comment by Gustine** [comment]
My main site is running a 1.8dev version built on April 27. No problem.
My test site (same gedcom) ran into error on June 17.

**Comment by HRN-webtrees** [comment]
On this day and Upcoming events:
The error message appeared after going from 1.7 to 1.8 dev, and at the same time upgrading wampserver (now using php 5.6.25)
There is error when changing sort order from "sort by name" to "sort by date" in the two blocks.
Editing includes/session.php does not change anything.

**Comment by Gustine** [comment]
Perhaps a clue :
Statistics > Longevity versus time gets « use bootstrap modal » with webtrees June 17 but runs correctly with webtrees April 27.

**Comment by fisharebest** [comment]
> use bootstrap modal

This was just a "to do" comment.  It has since been removed.

I tried installing PHP 5.6, but did not manage to reproduce the problem.

**Comment by HRN-webtrees** [comment]
Using php 7.0.10, I no longer have this error

**Comment by Gustine** [comment]
Yes !
Thanks a lot.

**Comment by Gustine** [comment]
Hum... not sure it's the same bug.
When logged on, all lists of branches are correctly displayed.
When logged off, some branches get errors, for example http://gustine.eu/wt3/branches.php?ged=Riviere-LeDu3&surname=Bouvet (no living individual yet) 
/home/…/includes/session.php:137 /home/…/app/Controller/BranchesController.php:241 usort(): Array was modified by the user comparison function #0 unknown:unknown ErrorException("/home/…/app/Controller/BranchesController.php:241 usort(): Array was modified by the user comparison function") 
#1 /app/Controller/BranchesController.php:241 usort([array], '\\Fisharebest\\Webtrees\\Family::…') 
#2 /app/Controller/BranchesController.php:269 getDescendantsHtml([Individual I1526@2], [Family F725@2]) 
#3 /app/Controller/BranchesController.php:269 getDescendantsHtml([Individual I1831@2], [Family F1115@2]) 
#4 /app/Controller/BranchesController.php:174 getDescendantsHtml([Individual I2723@2]) 
#5 /branches.php:66 getPatriarchsHtml()
