### ISSUE TITLE
Not possible to add existing parents to child (1.8-dev)

### ISSUE THREAD

**Issue by HelmutL** [fisharebest/webtrees#1256]
hlein's Avatar
    Online
    New
    Posts: 97

	
In the develop version it seems not to be possibkle to link an individual as a child to an existing family. The family cannot be searched (how to find the familiy id?)
![link_child](https://user-images.githubusercontent.com/17042607/27394751-95cf6e3a-56ad-11e7-8001-ff1a5a993512.jpg)

**Comment by fisharebest** [comment]
Fixed
