### ISSUE TITLE
On this day and Upcoming events

### ISSUE THREAD

**Issue by HRN-webtrees** [fisharebest/webtrees#1257]
On my front page, I get following error messages when not logged in:

C:\wamp\www\webtrees\includes\session.php:154 C:\wamp\www\webtrees\app\Functions\FunctionsPrintLists.php:1644 uasort(): Array was modified by the user comparison function #0 unknown:unknown ErrorException("C:\wamp\www\webtrees\app\Functions\FunctionsPrintLists.php:1644 uasort(): Array was modified by the user comparison function") #1 \app\Functions\FunctionsPrintLists.php:1644 uasort([array], [Closure]) #2 \app\Module\OnThisDayModule.php:82 eventsList(2457926, 2457926, 'BIRT MARR DEAT', '0', 'alpha') #3 \index.php:65 getBlock(137)

C:\wamp\www\webtrees\includes\session.php:154 C:\wamp\www\webtrees\app\Functions\FunctionsPrintLists.php:1644 uasort(): Array was modified by the user comparison function #0 unknown:unknown ErrorException("C:\wamp\www\webtrees\app\Functions\FunctionsPrintLists.php:1644 uasort(): Array was modified by the user comparison function") #1 \app\Functions\FunctionsPrintLists.php:1644 uasort([array], [Closure]) #2 \app\Module\UpcomingAnniversariesModule.php:89 eventsList(2457927, 2457933, '', '0', 'alpha') #3 \index.php:65 getBlock(138)

**Comment by fisharebest** [comment]
Same problem as #1250
