### ISSUE TITLE
Cemetery report not showing info correctly

### ISSUE THREAD

**Issue by Ziris85** [fisharebest/webtrees#1263]
This is similar to issue #616 (maybe), but I'm noticing that when I try to generate a list of cemeteries, it seems that the cemetery name is put in the "Place" column (which I imagine is supposed to show the address of said cemetery), and the actual "Cemetery" column is just blank for everything:

![screenshot from 2017-06-24 23-32-51](https://user-images.githubusercontent.com/14392979/27513486-91283fe4-5935-11e7-9d8f-67f23890a30f.png)

Taking a look at the raw GEDCOM for these, it looks like the actual name of the cemetery is being placed with the **PLAC** tag, and the location/address of the cemetery with the **ADDR** tag. For fun (and science!) I tried editing the raw GEDCOM to have the **BURI** tag have the cemetery name, but it didn't seem to change anything with respect to the report.

If I understand how this report is organizing its data, then it seems that the "Cemetery" column should be drawing info from the **PLAC** tag, and the "Place" column drawing from the **ADDR** tag?

**Comment by fisharebest** [comment]
Older versions of the GEDCOM specification used a `CEME` tag, subordinate to the `BURI` tag.  e.g.

```
1 BURI
2 CEME Highgate Cemetery
2 PLAC Highgate, London, England
```

However, this tag is deprecated, and you should now use

```
1 BURI
2 PLAC Highgate Cemetery, Highgate, London, England
```

The "Cemetery" column exists to show the legacy `CEME` tag.  We ought to remove it, and prepend the value to the place column.
