### ISSUE TITLE
dev - Individuals list has extra code.

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1265]
Greg,
On the List Individules, when you have a lot of people, there is some garbage on the screen.

![individuals](https://user-images.githubusercontent.com/5147603/27650372-5c1c1290-5bfa-11e7-9160-00ba476b83da.png)

**Comment by fisharebest** [comment]
Was fixed in 64eef06468ef3defb9436dd1373c5fdcaedc7a58
