### ISSUE TITLE
Interactive tree runs and runs - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1269]
https://dev.webtrees.net/demo-dev/module.php?mod=tree&mod_action=treeview&rootid=i1&ged=demo

**Comment by fisharebest** [comment]
The interactive tree used the jQuery-UI "draggable" support.
We no longer use jQuery-UI.
We need to rewrite this using native HTML5 (or some lightweight draggable library).

**Comment by makitso** [comment]
I believe this was fixed by #1264.
