### ISSUE TITLE
pdf thumbnails return a 500 error

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1270]
I have always used custom thumbnails for my pdf's. Uploaded with the extension pdf to match the main file. After the recent changes in the media area this no longer works. The thumbnails are not recognized anymore and return a 500 error.

**Comment by fisharebest** [comment]
Hi Carmen,

I am working on two features to help this.

1) Automatically creating .JPEG files from the first page of a .PDF document.
This requires that the server has the php-imagick extension loaded.

2) Implement the GEDCOM feature that allows a media object to contain many media files.  For example, a media object could contain an audio file (an interview), a text file (a transcript of the interview) and an image (picture of the interviewee).

A "batch update" can easily be written for (2) which adds existing thumbnails linked to non-image files.

**Comment by JustCarmen** [comment]
Ok, fine this sounds really good. The new features are certainly very welcome. And it is no problem to do a batch update on existing thumbnails.

**Comment by fisharebest** [comment]
It is possible to create thumbnails from PDF files - but it requires the php-imagick library.

**Comment by JustCarmen** [comment]
> A "batch update" can easily be written for (2) which adds existing thumbnails linked to non-image files.

Could you please explain this in more detail. I tried to rename a pdf thumbnail (which really is a jpeg image, but formerly needed to have the extension pdf to serve as a thumbnail for a pdf document) in the thumbs folder to 'jpg' but that doesn't work.

**Comment by fisharebest** [comment]
> It is possible to create thumbnails from PDF files - but it requires the php-imagick library.

php-imagick also requires that `gs` is installed on the server, and that PHP has permission to execute processes on the server.  So, it won't work on >99% of servers.

**Comment by fisharebest** [comment]
> I have always used custom thumbnails for my pdf's. Uploaded with the extension pdf to match the main file.

Can you tell me exactly what you did here?

e.g. if you have a file `xxx.pdf`, then what is your thumbnail called?

* `xxx.jpg` ?
* `xxx.pdf.jpg` ?
* `../thumbs/xxx.pdf.jpg` ?
???

**Comment by JustCarmen** [comment]
> Can you tell me exactly what you did here?
e.g. if you have a file xxx.pdf, then what is your thumbnail called?

The thumbnail is called xxx.pdf while it is actually a jpg file. So the extension has been changed. These thumbnails are saved in the thumbs folder: .../thumbs/xxx.pdf

This is not something I've made up. This is the default webtrees way to handle thumbnails with pdf files.

**Comment by fisharebest** [comment]
The latest code contains a feature to detect custom thumbnails - Control panel, Media, Import custom thumbnails

The code to import these thumbnails will come soon.

**Comment by fisharebest** [comment]
The latest code can now import custom thumbnails.

The result is a media object that contains two media files - the PDF and the JPEG.

When webtrees needs to display a thumbnail for the media object, it will use the first image file.
