### ISSUE TITLE
Select2 bootstrap style

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1275]
Greg as discussed.

Maybe this will help to fulfill the task as mentioned in #1273 

- [ ] Get the select2-bootstrap-theme to work

I was playing around with this issue in a few of my modules where I have a select2 selectbox.

This css works in my case. Don't know if it works in all cases but it's worth trying:

```
.select2-selection--single, 
.select2-selection--single .select2-selection__rendered, 
.select2-selection--single .select2-selection__arrow {
  height: calc(2.25rem + 2px);
  line-height: 2.25;
}

 .input-group .select2-selection--single {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}
```
And in case you are using Sass you could make a mixin of it (that's what I did).

```
@mixin select2() {
  $select: "select2-selection--single";
  .#{$select} {
    &,
    & .select2-selection__rendered,
    & .select2-selection__arrow {
      height: calc(2.25rem + 2px);
      line-height: 2.25;
    }
  }

  .input-group .#{$select} {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
  }
}
```

**Comment by fisharebest** [comment]
See #1290 - we may be switching from "select2" to "chosen".

**Comment by fisharebest** [comment]
The select2/bootstrap styling seems OK now.

I recently fixed the layouts when the select was initially hidden, and the heights adjust to contain images, etc.

If there is something specific, please open another issue for it.
