### ISSUE TITLE
Use of undefined constant WT_AUTOCOMPLETE_JS_URL

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#1278]
Whats happened in the current master to WT_AUTOCOMPLETE_JS_URL. How to implement autoload of individual search know?

**Comment by JustCarmen** [comment]
This library is replaced by Select2

To add a form field to search  for an individual for example now use FunctionsEdit::formControlIndividual
In the FunctionsEdit class you find more examples.
