### ISSUE TITLE
dev - Add or link to media object fails

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1281]
Both the Add a media object and Link to an existing media object do nothing when clicked.
![images](https://user-images.githubusercontent.com/5147603/28094482-7d45ae50-6662-11e7-8b54-cb84701db355.png)

**Comment by Fa10175** [comment]
for each media, i have this message : `This image failed to load.`
If i try to download i have :  

> D:\Genealogie\xampp 7.1.1\xampp\htdocs\webtrees\addmedia.php:230 Bad $action () in addmedia.php

or 

> D:\Genealogie\xampp 7.1.1\xampp\htdocs\webtrees\vendor\league\flysystem\src\Util.php:111 Path is outside of the defined root, path: [../firewallmedia/...x.jpg] #0 \vendor\league\flysystem\src\Util.php:84 LogicException("Path is outside of the defined root, path: [../firewallmedia/...x.jpg]") #1 \vendor\league\flysystem\src\Filesystem.php:55 normalizePath('../firewallmedia/...') #2 \vendor\league\glide\src\Server.php:164 has('../firewallmedia/…') #3 \vendor\league\glide\src\Server.php:498 sourceFileExists('medias/…') #4 \vendor\league\glide\src\Server.php:465 makeImage('medias/…', [array]) #5 \mediafirewall.php:79 outputImage('medias/…', [array])

**Comment by fisharebest** [comment]
@Fa10175 - I think you have a completely different issue.  Do you have `../` in the setting for the media directory?  It could be difficult to support this.  FYI, you can move the entire `/data` folder (excluding `config.ini.php`).

**Comment by Fa10175** [comment]
In 1.7.9 
![dir](https://user-images.githubusercontent.com/10681601/28122212-d263c938-671d-11e7-8607-e38e075868c4.JPG)
and of course ../firewallmedia
it's working so like that all my personnal media are outside data (this is  done a longtime ago all previous release).

In 1.8.0- Dev
It's true if i move this directory under data it's good (working) but less secure and less helpfull for me (backup, number directory level , size character for the name of file, ...) . 
to do this change should also make some over change in personal html code.

Thanks to find a good solution.

**Comment by fisharebest** [comment]
I think we can use `sha1($folder)` instead of `$folder`.

**Comment by fisharebest** [comment]
The add/link media functions are now available.
