### ISSUE TITLE
Dev - Show details option in charts

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1283]
Please bring back the 'show details option' in the (pedigree) charts.

I had it set to 'no' for display on the homepage, where compact blocks are nicer, but even more important, my default setup for the pedigree page was the compact version (show details set to 'no') and oldest at top, which gives a very nice layout. 

See: https://wijzijnfamilie.nl/pedigree.php?ged=knegt&show_full=0&rootid=I14&PEDIGREE_GENERATIONS=3&orientation=2&show_full=0

As far as I know this compact layout isn't possible anymore in the dev-version or do I miss something?

**Comment by fisharebest** [comment]
This is being moved from a server-side function to a client-side function.

The intention is for a show/hide details button which will add/remove a class from the chart container.

This class will control what details are shown in the chart, the size of the chart, etc.

**Comment by fisharebest** [comment]
All chart boxes now have exactly the same HTML.  CSS is used to control the size and content.

For example,
* the compact chart shows variable-sized boxes with just the name and lifespan
* the ancestry chart shows wide boxes with name, facts and zoom/link menus

This gives us much more control over the layout.  For example, we can use media-queries to show less information on small screens.

We could also switch between compact/full views using javascript to add/remove CSS classes.  This would allow us to change the layout without re-loading the page.   It would work the same as the "show events of close relatives" option on the individual page.

**Comment by fisharebest** [comment]
e759aebbec359cf7148227a725fea81907659ae8 introduces more changes for pedigree charts.

Each generation and orientation can be styled separately.

You can now use CSS to achieve the layout that you desire.
