### ISSUE TITLE
Errors in demo-dev for media

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1294]
In https://dev.webtrees.net/demo-dev/addmedia.php?action=editmedia&pid=m113 I see
/home/webtrees/dev.webtrees.net/demo-dev/addmedia.php:230 Bad $action () in addmedia.php

In the Album tab I see twice Add media object and Link toan existing media object.

I see for adding a media object in Album in https://dev.webtrees.net/demo-dev/addmedia.php?action=showmediaform&linktoid=i220
error /home/webtrees/dev.webtrees.net/demo-dev/addmedia.php:230 Bad $action () in addmedia.php

I see for linking an existing media object in Album in https://dev.webtrees.net/demo-dev/inverselink.php?linktoid=i220&linkto=person error /home/webtrees/dev.webtrees.net/demo-dev/inverselink.php:25 Class 'Fisharebest\Webtrees\Controller\SimpleController' not found

Meliza

**Comment by fisharebest** [comment]
The demo site was failing to update from github.
Should be working now.
