### ISSUE TITLE
demo-dev media errors 404, 500, etc.

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1295]
The following are not found

i176 - Countess Augusta Reuss of Ebersdorf (1757-1831), duchess of Saxe-Coburg-Saalfeld - Augusta_di_Reuss-Ebersdorf,_duchessa_di_Sassonia-Coburgo-Saalfeld.jpg

i7 - Duke of York at Montreal and Quebec, 1901 - Video downloaded from Wikipedia on 25th May 2012

i201 - Elisabeth Sophie of Mecklenburg - Elisabeth_Sophie_of_Mecklenburg.jpg

i1 - European monarchs family tree - Document

i1 - Location of Buckingham Palace - "The Google Maps Embed API must be used in an iframe."

i1 - Queen Elizabeth II’s christmas message 2011 - Audio

i1 - Royal Coat of Arma of the United Kingdom - Coat of arms - also spelling

**Comment by fisharebest** [comment]
See #1270
