### ISSUE TITLE
dev - xref prefixes

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#1297]
As version 2 is getting rid of a lot of ancient baggage how about getting rid of the XREF prefix options.

Persons who raise queries in the forums to make the xrefs visible are being steered towards using unique identifiers or to look  at the URL so I can't see any use for these options now.

**Comment by fisharebest** [comment]
I guess there are various options.

* Always use the (current) default prefixes.
* Always use the same prefix for all record types.  e.g. `X`
* Abandon the prefix/sequence system in favour of something else.

**Comment by ddrury** [comment]
I seem to remember a discussion a while back (don't remember the context) where you proposed using a UUID. This seems like a good idea although regardless of new format I can see implementation problems -

- possibly need schema change to accommodate longer xrefs
- would you leave existing xref "as is" or migrate to new format
- notwithstanding what I mentioned originally, I can see complaints in the forums about invisible/unreadable xrefs

**Comment by fisharebest** [comment]
XREFs are still used in a few places:

* [ ] Control panel, Manage family trees, Merge records
* [ ] Control panel, Manage family trees, Privacy
* [ ] Control panel, User administration, Edit the user
* [ ] Control panel, Module administration, Stories, Add a story

These need removing before we can proceed with this.

**Comment by fisharebest** [comment]
XREF sequences used to be per-type/tree.  Hence the `wt_next_id` table has `record_type` and `gedcom_id` columns.

However, for a while now, the code ignores the `gedcom_id` column, and generates sequences per-type.  i.e. we can generate both `F1234` and `R1234`.

If we decide to use the same prefix for all records (I like `X`), then this table becomes entirely redundant, and the `next_id` setting would become a site setting.

**Comment by someone-somenet-org** [comment]
A little late to the show, but please consider migrating to UUIDs again.

Enumerable site-wide IDs are pretty uncool and the argument about unreadability is already there and while the gedcom 5.5.1 document does not require it, they do put a lot of effort into having easily distinguishable xref_ids for the diffrent record types. 
So when you ignore their effort to having xrefs obviously show what they reference, they could just be UUIDs too. :)
