### ISSUE TITLE
error in lifespanchart

### ISSUE THREAD

**Issue by Joppla** [fisharebest/webtrees#1301]
If I fill in in the lifespanchart a place:
![afbeelding](https://user-images.githubusercontent.com/25467829/28926445-167d0dc2-7868-11e7-9fe2-0cf7d94cf0ae.png)
I got the following error:
`/home/deb72249/domains/planje.info/public_html/webtree/app/Controller/LifespanController.php:481 Argument 1 passed to Fisharebest\Webtrees\Controller\LifespanController::checkFact() must be an instance of Fisharebest\Webtrees\Fact, null given, called in /home/deb72249/domains/planje.info/public_html/webtree/app/Controller/LifespanController.php on line 218 #0 /app/Controller/LifespanController.php:218 TypeError("Argument 1 passed to Fisharebest\Webtrees\Controller\LifespanController::checkFact() must be an instance of Fisharebest\Webtrees\Fact, null given, called in /home/deb72249/domains/planje.info/public_html/webtree/app/Controller/LifespanController.php on line 218") #1 /lifespan.php:26 __construct() `

**Comment by Joppla** [comment]
hi Greg,
Is the fix also for version 1.7.9 and can I exchange/replace the file? Or is it done for the new version?

**Comment by fisharebest** [comment]
I committed two versions of the fix.  One in the 1.7 branch (for 1.7.9).  One in the master branch (for 2.0.0).
