### ISSUE TITLE
Not all PLAC in Place hierarchy

### ISSUE THREAD

**Issue by luca74** [fisharebest/webtrees#1306]
Like illustrated in Forum

dev.webtrees.net/demo-stable/individual.php?pid=i242&ged=demo#

1 RESI
2 DATE FROM 10 AUG 2016
2 PLAC La luna

and

1 RESI
2 DATE TO 10 AUG 2016
2 PLAC La Terra

dev.webtrees.net/demo-stable/placelist.php?display=list you can see "La Terra" but non "La luna"

**Comment by HonkXL** [comment]
Hi,
I already had such a problem, but I was never able to reproduce it....

**Comment by HonkXL** [comment]
Today I exported my trees as GEDCOM. This was the place hierarchy on the old version of webtrees:

![hierar-alt](https://user-images.githubusercontent.com/16715040/29552528-0fc5fe9e-8718-11e7-8858-729d88394592.png)

Then I imported the same GEDCOM (without changing it) to a test system with the latest master and I got much more places!

![hierar-neu](https://user-images.githubusercontent.com/16715040/29552664-8df66b3c-8718-11e7-80d7-8f683c3c3cc9.png)

**Comment by fisharebest** [comment]
I am still unable to reproduce this problem.

If I add "La luna" an d"La terra", I see both in the place hierarchy.

**Comment by fisharebest** [comment]
Places are only added to the place hierachy when you accept the change.
If you add a new place, and it is still "pending", then it will not be shown.

The only way I can reproduce this issue is:

1) add "La luna"
2) accept the change
3) add "La terra"
4) visit the place hierarchy
5) Only "La luna" is shown

The same behaviour also applies to dates.

**Comment by fisharebest** [comment]
I can't reproduce this, and I'm pretty sure it is caused by not accepting a pending change.

I've also rewritten much of the place handling code.

If you can still reproduce the issue on the 2.0 code, please open another issue.

**Comment by fisharebest** [comment]
The code to read/create place hierarchies has been rewritten.

This should have fixed the issue
