### ISSUE TITLE
Media error - Path is outside of the defined root

### ISSUE THREAD

**Issue by vytux-com** [fisharebest/webtrees#1311]
I have a setup where the media files are shared between the dev site and the main site and as such they are outside the site folder. This setup has worked well for a long time, however 2.0.0 dev breaks this and I get the following error:
`/var/www/webtrees/webtrees-dev/vendor/league/flysystem/src/Util.php:111 Path is outside of the defined root, path: [thumbnail-cache/../../media/Kilmes_Medis/personal/portraits/6fea2f29328ed1bb2d55f47546442ddc.jpg/f26551ec22b651ba8dd093dd6950d8df] #0 /vendor/league/flysystem/src/Util.php:84 LogicException("Path is outside of the defined root, path: [thumbnail-cache/../../media/Kilmes_Medis/personal/portraits/6fea2f29328ed1bb2d55f47546442ddc.jpg/f26551ec22b651ba8dd093dd6950d8df]") #1 /vendor/league/flysystem/src/Filesystem.php:55 normalizePath('thumbnail-cache/../../media/Ki…') #2 /vendor/league/glide/src/Server.php:301 has('thumbnail-cache/../../media/Ki…') #3 /vendor/league/glide/src/Server.php:494 cacheFileExists('personal/portraits/6fea2f29328…', [array]) #4 /vendor/league/glide/src/Server.php:465 makeImage('personal/portraits/6fea2f29328…', [array]) #5 /mediafirewall.php:79 outputImage('personal/portraits/6fea2f29328…', [array])`

Anything I can do to get this to work again or will I need to redesign my site setups.

**Comment by fisharebest** [comment]
I think that restricting the use of `../` in media paths is a wise security precaution.

It prevents a malicious script from accessing files elsewhere on the server.

I guess there are two options.

1) Your two site can share a a data folder.  The two demo sites (dev/stable) share the same media folder using this technique.

2) You can use symbolic links.  e.g. in your data folder, you have a symlink `media` which points to `../../media/location/`

**Comment by ddrury** [comment]
Using symlinks on a windows system with the current code results in random failures to find the media item (I did submit a pull request - subsequently withdrawn - as a solution) it will be interesting to see if the use of Glide works reliably in this situation.

Anyhow I think that sharing the data folder is a much cleaner solution
