### ISSUE TITLE
Indi page - Facts and events tab - Events of close relatives selection does not work - GitHub code

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1312]
I see the same close relatives data when I select or unselect the Events of close relatives box.

**Comment by melizaa** [comment]
See for instance https://dev.webtrees.net/demo-dev/individual.php?pid=i223&ged=demo

**Comment by HonkXL** [comment]
Same here and same problem with history-events! They are always shown.

**Comment by melizaa** [comment]
This makes testing the GitHub code take much longer than if we could manage if we will show or do not show the events of close relatives.

**Comment by melizaa** [comment]
Is the issue similar to #1397 - The family book "Show spouse" selection does not work - demo_dev?

**Comment by melizaa** [comment]
Same as https://github.com/fisharebest/webtrees/issues/1408
May be closed
