### ISSUE TITLE
I see facts without places in Indi Google Maps right hand fact list on my site - GitHub code

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1313]
I do not see the divorce of f3 on demo-dev in the indi Googe maps.
On my site I see facts without places in the list. They include divorce, name, sex, family as spouse, husband, child, media objects, sources, last change, etc.

I have this issue on my production site with old code and on my build test site with latest GitHub code.
What is wrong on my site?

The list of I269:

Birth | Helsinki, Finland28 December 1886
-- | --
Education | Helsinki, Finlandfrom 1894 to 1900
Education | IV classfrom September 1900to May 1906
Graduation | Fil.KandDecember 1913
Graduation | Fil.Mag. in Germanic philologyHelsinki, Finland1914
Marriage | Vera RosenthalHelsinki, Finland30 May 1915
Birth of a child | … Rubinstein20 November 1915
Birth of a daughter | Gigi S RubinsteinStockholm, Sweden4 April 1917
Birth of a son | Nathan Rubinstein"Nattis"Copenhagen, Denmark14 September 1918
Occupation | Teacher, Business, Esperanto, Zionist Congress, Jewish choir
Occupation | Chairman of the committee that handled Jewish refugees during WWIIHelsinki, Finland
Occupation | Manager
Residence | Copenhagen, Denmarkabout 1918
Naturalisation | Finland21 May 1920
Residence | Vera RosenthalHelsinki, Finland10 June 1920
Name | Samuel /Rubinstein/
Sex | M
Family as a spouse | @F68@
Family as a child | @F165@
Husband | @I269@Vera Rosenthal
Wife | @I270@Vera Rosenthal
Child | @I21989@Vera Rosenthal
Child | @I310@Vera Rosenthal
Child | @I86@Vera Rosenthal
Child | @I311@Vera Rosenthal
Comment | Applied for a certificate of non-impediment (esteettömyystodistus) for a five year passport.Vera Rosenthal10 June 1920
Birth of a son | Herbert RubinsteinHelsinki, Finland6 April 1922
Occupation | Teacher of German at the Helsinki Jewish Schoolfrom 1920 to 1922
Residence | Helsinki, Finland1930
Comment | Helsinki Jewish School directorate memberbetween 1931 and 1934
Occupation | Helsinki Jewish Congregation chairmanbetween 1940 and 1941
Death | Stockholm, Sweden9 March 1952
Death | 12 Adar 5712
Burial | Helsinki, Finland12 March 1952
Caste | Levi
Media object | @M416@
Media object | @M417@
Media object | @M418@
Media object | @M419@
Media object | @M327@
Media object | @M18@
Media object | @M167@
Media object | @M420@
Media object | @M421@
Media object | @M422@
Media object | @M423@
Media object | @M424@
Media object | @M425@
Media object | @M426@
Media object | @M2563@
Media object | @M2577@
Media object | @M2982@
Media object | @M3037@
Media object | @M3474@
Media object | @M3892@
Media object | @M5@
Media object | @M924@
Media object | @M8@
Media object | @M1569@Vera Rosenthal
Media object | @M440@Vera Rosenthal
Media object | @M1570@Vera Rosenthal
Media object | @M530@Vera Rosenthal
Media object | @M531@Vera Rosenthal
Media object | @M4@Vera Rosenthal
Media object | @M2831@Vera Rosenthal
Media object | @M2575@Vera Rosenthal
Note | One of the Helsinki Jewish Choir "Hazamir" founders and conductors Prepared music for the choir Honorary chairman of the Jewish choir in Helsinki 4-10 October 1906 - Active in the Russian Zionist Congress in Helsinki Born: 16 Oct 1886 or 23 Dec 1886 Julian 16 December 1886 would give Gregorian 28 December 1886
Source | @S15@
Source | @S6@
Source | @S16@
Source | @S7@
Source | @S2@
Source | @S17@
Source | @S3@
Source | @S77@
Source | @S167@
Source | @S250@
Source | @S247@
Source | @S956@
Source | @S968@
Source | @S67@
Last change | Vera Rosenthal2 December 2013
Last change | 26 September 2015
Research task | Married 15 Jun 1914 (7209) or 30 JunVera Rosenthal

**Comment by melizaa** [comment]
I have today tried again to debug I22522.

She has 1 NAME and 2 GIVN and 2 SURN, 1 SEX F, 1 FAMC and 1 SOUR @S...@ 2 DATA 3 TEXT Turku 1870 census and a 1 CHAN record
She was born 1869 in Turku, Finland.
She has a death record 1 DEAT Y .

I see all the above facts on her individual page Google Maps's right hand list of Facts and Events.
As far as I understand, I should only see in the lists only the facts with a place, (olny her birth data). 

In GoogleMapsModule.php, function buildIndividualMap I see all her data in $facts.

if (!empty($place_data)) - $place_data is not empty
if (!empty($events)) { - is not empty
all the facts/events are filled to $event
I see <span dir="auto"></span> for the event place.

Where should webtrees filter our the facts without places?
As a workaround I would ask after >foreach ($events as $event) {<  if $event["place"] has only the above span text, but I do not know how to do it.

![2018-01-27_19-24-09](https://user-images.githubusercontent.com/5202996/35474500-b172589a-0397-11e8-892a-328fed6ab964.jpg)

I print in the future test system the $event values. 


Array
(
    [class] => 
    [fact_label] => Birth
    [date] => 1869
    [info] => 
    [name] => 
    [place] => Turku, Finland
    [placeid] => IDN60.44E22.27
)

event
Array
(
    [class] => 
    [fact_label] => Name
    [date] => 
    [info] => Rolla /Gumpler/
    [name] => 
    [place] => 
    [placeid] => IDN0E0

etc.

**Comment by fisharebest** [comment]
You have created a place name "Unknown", with co-ordinates 0,0.

The googlemap module uses "Unknown" for places with no name.

I think it is matching your place "Unkown" with a missing place.

If you rename this place in your googlemap data, does the problem disappear?

**Comment by melizaa** [comment]
I no longer see the facts without places.

**Comment by fisharebest** [comment]
This issue is fixed in 2.0.0, which is now released.
