### ISSUE TITLE
New themes / layout takes too much space, especially on tablets

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1314]
As far as I know, the new layout and themes should be optimized for tablets. I installed the latest master parallel to my productive webtrees and tested it with an Apple iPad.

First problem is, that the boxes of the statistics are no longer in two columns. Look to boxes-new.JPG for the new layout and boxes-old.JPG shows the same view in 1.8

Second problem is, that more than 50% of the screen is showing the name and the sex of the displayed person. See layout-new.JPG
In 1.8 (layout-old.JPG) the same part of the person took only 20% of the screen. This was much more efficient.

Maybe a bit fine-tuning of sizes and font sizes would be required?

![boxes-new](https://user-images.githubusercontent.com/16715040/29550559-b17d27c6-870e-11e7-8f1f-7014950ee0ed.JPG)

![boxes-old](https://user-images.githubusercontent.com/16715040/29550562-b693f15e-870e-11e7-869b-98d6ad9a5dff.JPG)

![layout-new](https://user-images.githubusercontent.com/16715040/29550570-bbf6254a-870e-11e7-9be8-6c7df784329a.JPG)

![layout-old](https://user-images.githubusercontent.com/16715040/29550587-c843949a-870e-11e7-80da-0f9d91e4b02b.JPG)

**Comment by makitso** [comment]
So, I tested the 2.0 system with two tablets and colors theme, an iPad with 1024 x 678 resolution and an Pixel C with 1280 x 765.  Both display reasonable well in portrait and landscape mode.  However, my tests were done in English.  If I change the language to German then the iPad does have the problem you referenced above.  I will take a look to see if there is an easy fix.

**Comment by makitso** [comment]
This issue is a bit more complex now that we use bootstrap.  I have submitted some test code for the colors theme to dev.  Please give it a try and provide feedback.

**Comment by HonkXL** [comment]
Great - I will test it. On the "normal" iPad it looks much better now. I will test it on my iPad Mini later and notify you.
