### ISSUE TITLE
Mouse over chart Individual name wrong - Demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1316]
I see for instance for i1 the following:
![image](https://user-images.githubusercontent.com/5202996/29555148-60f321b8-872a-11e7-91ea-2864bf74e2ca.png)

**Comment by melizaa** [comment]
I see the same or similar mouse over text in the ancestors and the compact charts when I move the mouse over arrows.

**Comment by fisharebest** [comment]
This is part of the `select2` library.  In #1369 we are planning to replace it.

**Comment by melizaa** [comment]
Also the report root persons have this issue/

The issue is solved for the ancestor and compact chart arrows.

**Comment by fisharebest** [comment]
This is a bug in the "select2" library.

We don't need this "tooltip" text, but there is no option to set or disable it.

Possible workarounds in https://stackoverflow.com/questions/35500508/how-to-disable-the-title-in-select2
