### ISSUE TITLE
Statistics - Families -  Number of families without children - we do not see the counter of the tallest column in big trees - GitHub

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1319]
We see the totals as expected in demo-dev.

In my GitHub build system I do not see for my big file the highest counter
![image](https://user-images.githubusercontent.com/5202996/29581516-39cf42bc-8782-11e7-8eed-a709747203fc.png)

and in the Glück tree I see the total on the bar data, not above it
![image](https://user-images.githubusercontent.com/5202996/29581564-6d038e04-8782-11e7-8dd5-adbd777b629a.png)

We should not use as a rule $max + 1 in app/Stats.php.
$max * 1.05 +1 is much better for my data, but I do not know how to make the y-axes taller.

Meliza

**Comment by melizaa** [comment]
I see now also the total of the big file in the bar.

**Comment by melizaa** [comment]
But, it is printed as black on blue, and it is hard to read it.

**Comment by fisharebest** [comment]
The charts have been rewritten by @magicsunday and this issue no longer exists
