### ISSUE TITLE
In the index Home page and MyPage blocks show too much data. GitHub code.

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1320]
I miss the boxes with scroll bars that we used to have. Now I scroll and scroll the page in order to see any data. I do not see where one block ends and another starts.

The blocks with much data are research tasks, upcoming events, yahrzeiten, messages and even on this day.

**Comment by melizaa** [comment]
You may see the issue in demo-dev by adding the upcoming events to the index page and showing all events of dead people.

**Comment by melizaa** [comment]
See Upcoming events #1300

**Comment by fisharebest** [comment]
They were removed intentionally.  See #773

**Comment by melizaa** [comment]
Perhaps we should have different handling of the blocks for handhelds and for computer screens?

**Comment by melizaa** [comment]
This issue is a main showstopper on my site to install wt2.0.

**Comment by melizaa** [comment]
I have changed this locally in my future test site.
