### ISSUE TITLE
Branches errors - GitHub code

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1322]
On my test sites I get

/home/meliza/public_html/build/webtrees/includes/session.php:137 /home/meliza/public_html/build/webtrees/app/Controller/BranchesController.php:134 usort(): Array was modified by the user comparison function #0 unknown:unknown ErrorException("/home/meliza/public_html/build/webtrees/app/Controller/BranchesController.php:134 usort(): Array was modified by the user comparison function") #1 /app/Controller/BranchesController.php:134 usort([array], '\\Fisharebest\\Webtrees\\Individu…') #2 /app/Controller/BranchesController.php:60 loadIndividuals() #3 /branches.php:25 __construct()

What could cause the issue?

I see results in demo-dev.

**Comment by fisharebest** [comment]
Which exact version of PHP?

**Comment by fisharebest** [comment]
See #1250

**Comment by melizaa** [comment]
PHP version 5.6.31

**Comment by fisharebest** [comment]
Closed via #1250
