### ISSUE TITLE
Index page Charts issues - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1324]
The descendants, hourglass and pedigree charts do not have scrollbars in the minimal theme. They print outside the block borders.

In the other themes there are scrollbars, but the chart selection icons print in fixed positions (even outside the block) and do not move with the chart when it is scrolled.

**Comment by makitso** [comment]
I can't duplicate these issues.  Perhaps a screen shot?

**Comment by fisharebest** [comment]
![screen shot 2017-08-24 at 19 07 34](https://user-images.githubusercontent.com/2306088/29681234-029c0f18-88ff-11e7-8ba0-48ee73bc1874.png)

**Comment by makitso** [comment]
Ok, I will fix it in the morning.

**Comment by melizaa** [comment]
And the icons in other themes
![image](https://user-images.githubusercontent.com/5202996/29700563-613059de-896e-11e7-828a-1e5092ad46a3.png)

**Comment by makitso** [comment]
Melizaa, fixed the block overflow problem for the minimal theme.  However, I am stumped on the icon problem.  Typically, a position of relative at the parent level solves this.  However, then the popup zoom fails.  Greg, suggestions?

**Comment by makitso** [comment]
You know, when  you add position: relative to .wt-block-content, the icons and popups are restricted to the parent block.  However, you can scroll down on the icon, which might be ok???

**Comment by makitso** [comment]
Just installed 1.7.9 and it looks like this is the same behavior.  So, I will commit the patch.

**Comment by melizaa** [comment]
In my productin 1.8.0-dev installation the fact icons move with the hourglass chart.
There was no need for a scrollbar for the descendants and the pedigree charts.

**Comment by makitso** [comment]
Original issues listed above have been resolved.
