### ISSUE TITLE
I do not see all the defined individual tabs - GitHub

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1328]
Before the leftnav is added I see all the expected tabs
![image](https://user-images.githubusercontent.com/5202996/29633680-bbaa2b30-884f-11e7-8fbb-c4a781b7be95.png)

After the leftnav is added I no longer see all the expected tabs
![image](https://user-images.githubusercontent.com/5202996/29633156-04747868-884e-11e7-8e15-92b21837f439.png)

It seems to me that the page marigins are too big.

Also the Stories tab has vanished. Why?

**Comment by fisharebest** [comment]
Fixed in #1326
