### ISSUE TITLE
The birth fact box of a child or a grandchild is too tall - GitHub

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1330]
Would it be possible to print the child and grandchild sequence number higher up in the Birth of a daughter/son or Birth of a granddaughter/grandson? (For instance after the texts Birth of a daughter/son or Birth of a granddaughter/grandson or with less space after the edit etc. icons.)
I fill normally source data only for individuals, not for facts/events.
The sequence numbers cause too tall, half empty fact/event boxes to be printed and require unnecessary scrolling on the individual pages.

![image](https://user-images.githubusercontent.com/5202996/29639359-2a9f65d8-8863-11e7-9449-44cd4cbe0451.png)

**Comment by fisharebest** [comment]
Are these numbers useful?  Do we need them?
