### ISSUE TITLE
Request a new user account on startpage cut off in German

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1332]
When I switch to German language, the Icon "Request a new user account" on top right is not displayed.

See screenshot of English and German version.
In 1.7.x this was no problem.

![german](https://user-images.githubusercontent.com/16715040/29662448-abbd7ede-88c7-11e7-81af-f84c1293b0df.jpg)

![english](https://user-images.githubusercontent.com/16715040/29662442-a566a60a-88c7-11e7-8111-03ab25b626b1.jpg)

**Comment by makitso** [comment]
Are you sure your on the latest dev update?  Here is what I see:

![image](https://user-images.githubusercontent.com/5147603/29670560-de0cc60a-889b-11e7-830c-e052ce139e6e.png)

**Comment by fisharebest** [comment]
I see the same as makitso.

@HonkXL - do you have a URL where we can see this?

**Comment by HonkXL** [comment]
Hi,
URL is https://genesis.weiland24.de/webtrees/index.php?ctype=gedcom&ged=Weiland
But I think I know the reason:

In Firefox it looks fine, but in Safari it is displayed wrong. Safari is my default browser.

See screenshot - the first is Safari, the second Firefox.

<img width="715" alt="safari-firefox" src="https://user-images.githubusercontent.com/16715040/29744913-b63f14b0-8aae-11e7-9397-5cc7fe40390a.png">

**Comment by fisharebest** [comment]
According to http://caniuse.com/#feat=flexbox this should work with Safari versions 10 or later.

Which version of Safari do you use?

**Comment by makitso** [comment]
I tried his site using my iPad tablet and Safari.  It failed when I
switched to the German language.

**Comment by fisharebest** [comment]
> I tried his site using my iPad tablet and Safari

Which version of Safari?  This layout uses "flexbox", which requires Safari 10 or higher.

**Comment by makitso** [comment]
Version 10.1 
There appears to be a bug in the latest versions of Safari with .col support and wrap 
https://github.com/twbs/bootstrap/issues/23193

**Comment by fisharebest** [comment]
There's a new versions of Bootstrap out, so that may fix it.  Their policy is to support at least latest/previous versions of major browsers, which for safari is 10 + 11.

**Comment by HonkXL** [comment]
Hi,
my Safari is 10.1.2. This is the latest version for MacOS Sierra (10.12.6). I think Safari 11 will be shipped with High Sierra, which will maybe released in September.

I will update my installation on Tuesday and test again ;-)

**Comment by HonkXL** [comment]
I just tested it with my iPad with latest iOS 10.3.3. There is the same problem! Screenshot:

![img_0764](https://user-images.githubusercontent.com/16715040/29761814-65df921a-8bcb-11e7-9bcb-dbee6c0dd187.PNG)

**Comment by makitso** [comment]
Well, I can get it to wrap.  However, the word-break seems to be failing :-(

![image](https://user-images.githubusercontent.com/5147603/29787321-555fb880-8be3-11e7-80a7-e0bcfb5fef3f.png)

**Comment by HonkXL** [comment]
Hi,
I just tested it with the latest build here from Github. Now it looks much better, but still not perfect.

<img width="712" alt="safari-screensh-next" src="https://user-images.githubusercontent.com/16715040/29793164-36dc3c5c-8c43-11e7-885e-c377e65d1368.png">

And in this build there seems to be a problem with the tables on the start screen. Scroll a bit down in the screenshot and look to the "Forschungsaufgaben" on the right side. This looks exactly the same in English (only the text is here "research")...

<img width="690" alt="safari-next2" src="https://user-images.githubusercontent.com/16715040/29793224-66cfe99a-8c43-11e7-892c-7c301a2bea20.png">

**Comment by makitso** [comment]
I am giving up on this.  The only Safari product I have is on an iPad and that gives inconsistent results.

**Comment by Amgine0** [comment]
[Mac boxen](https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=&q=Mac) in Vagrant.

**Comment by fisharebest** [comment]
I have a selection of mac that I can use.

**Comment by fisharebest** [comment]
@HonkXL 

In German, is it conventional to use hyphens to split long words across lines.  e.g.

```
standarddiagram
```

```
standard-
diagram
```

If so, then we could update the translation to `standard&shy;diagram`.

The `&shy;` means "soft hyphen", and is used to tell the brower where a hyphen can be added.  It is only used when the word does not fit in the available space.
