### ISSUE TITLE
Census Assistant US Census 1910 + 1920 converts McNaughton to MacNaughton

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#1333]
Family members all have surname McNaughton.   For the census years 1910 + 1920, the Census Assistant converts the surname  to M**a**cNaughton when building the shared note.

Ignore the middle initials -- I added some as I filled in the shared note from the census image, then went back later and added them to the individual records.

Webtrees Ver 1.7.9
Php 7.0.12
MySQL 5.6.32-78.1 

![one](https://user-images.githubusercontent.com/13973937/29686864-80aff444-88e8-11e7-9ba0-1f62a6bfe76e.PNG)

![two](https://user-images.githubusercontent.com/13973937/29686885-87d9ff08-88e8-11e7-95a3-58e9abc10ec7.PNG)

**Comment by fisharebest** [comment]
It's probably picking up the internal sorting version of the name, rather than the actual surname
