### ISSUE TITLE
I would like the moderator and the administrator to see the latest commit number for instance in the MyPage

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1336]
To see the last commit number is important when one tests the site behavior.

**Comment by fisharebest** [comment]
This is possible through a (very popular) library https://github.com/sebastianbergmann/version

But, it requires that PHP can execute commands on the server (`git`).  This is blocked on most servers for security reasons.

We can add it, but it will likely not work for many people...

**Comment by melizaa** [comment]
Would it work in demo-dev?

**Comment by fisharebest** [comment]
As far as I can tell, this can only work if the server permits PHP to execute server processes.

This permission should not generally be enabled on production servers, due to security risks.

It would only likely be available on development servers - which already have access to this information.
