### ISSUE TITLE
Visitor Edit Capability

### ISSUE THREAD

**Issue by imskriaz** [fisharebest/webtrees#1339]
Since Webtrees have fantastic review system by approving changes feel allowing edit by visitor will not be issue. Is there any option to allow visitor to allow edit or record edit proposal to moderator (like wiki)

Thanking developers for so hard works for this CMS.

**Comment by fisharebest** [comment]
I think this would cause too many problems.

1) A visitor cannot view living individuals.  If a visitor added a living individual, they would not be able to see the record that they just created.

2) Any website that allows visitors to add content will be abused by spammers.

3) With anonymous contributions, you cannot ask the author for more information, sources, etc.

4) Each page has a "Send message" link, which allows visitors to make comments about a record.
