### ISSUE TITLE
Selection buttons are printed on text on rtl pages - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1341]
At least in the relationships/ancestors/lifespan/hourglass/descendancy/familybook/statistics-own righthand selections in charts and the branches lists, selection buttons are printed on text.
The search buttons print OK on rtl pages.

See for instance https://dev.webtrees.net/demo-dev/ancestry.php?rootid=i1&ged=demo and
https://dev.webtrees.net/demo-dev/relationship.php?pid1=i1&ged=demo

**Comment by makitso** [comment]
Something happened to the hidden-print selector, it no longer seems to be working.
