### ISSUE TITLE
Research tasks - table displayed wrong

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1343]
The table of the research tasks is displayed in a wrong way, when attached to the right bar.

See screenshot. Screenshot taken with Safari 10, but can be reproduced on Firefox 55, too.

<img width="690" alt="safari-next2" src="https://user-images.githubusercontent.com/16715040/29793463-3734caec-8c44-11e7-8663-4df9d055f934.png">

**Comment by HonkXL** [comment]
And it can be reproduced in English, too. Problem is not language-specific!

**Comment by fisharebest** [comment]
FYI, I'm just about to upgrade bootstrap 4.0-alpha6 to 4.0-beta.

This may well fix many layout issues.  I would suggest leaving these until after the bootstrap upgrade.

**Comment by makitso** [comment]
Git is already on 4.0-beta right?

**Comment by fisharebest** [comment]
Oops - I think I may have pushed the commit that updated the library before I had updated the corresponding markup.

**Comment by makitso** [comment]
LOL, yes a few are needed.
