### ISSUE TITLE
Use of undefined constant WT_POPPER_JS_URL

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#1345]
Latest master.

Fatal error: Uncaught exception 'ErrorException' with message '/webtrees/app/Controller/PageController.php:104 Use of undefined constant WT_POPPER_JS_URL - assumed 'WT_POPPER_JS_URL'' in /webtrees/includes/session.php on line 138

**Comment by fisharebest** [comment]
Should be fixed now
