### ISSUE TITLE
Welcome text on login page not visible

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1350]
The welcome text on the login page is only visible when the first (default) text option is set. The other three options are not shown. I think this line in login.php is responsible:

`switch (Site::getPreference('WELCOME_TEXT_AUTH_MODE') === '1')`

Looks like it always using option 1, but I am not sure if this is used to set option 1 as default or something.

**Comment by fisharebest** [comment]
I think that a series of `if` `elseif` was converted to a `switch` incorrectly...
