### ISSUE TITLE
Individual page carrousel

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1354]
Referring to: https://github.com/fisharebest/webtrees/issues/1310

> But I agree with you that images from facts are rarely good examples for a "portrait" image.

This is exactly what is happening now with the recent changes. I have a lot of individuals with documents but without portraits The first thing you now see when entering an individuals page is a death notice or even worse, a picture of a graveyard. I am sure some visitors won't really appreciate this. And to be frankly I don't either.

So I hope this new feature will be optional and we will get the opportunity to use the old silhouettes in case we don't have good pictures to show as the main image. We also have two tabs with images, where people can see all the pictures and documents. I don't need these as main image too.

Another point are the links below the carousel. This may look good in English with its short sentences, but in Dutch the text is spread across 4 lines which makes the whole page looks very crowdy. Is it possible to use only an edit link (with the word 'edit') or a pencil icon?

![9-9-2017 23-24-10](https://user-images.githubusercontent.com/5641963/30244014-1a1699ce-95b6-11e7-9dcd-b8c5db79f169.jpg)![9-9-2017 23-23-44](https://user-images.githubusercontent.com/5641963/30244016-203155c4-95b6-11e7-9fe3-e6f2cdcc41b0.jpg)

**Comment by fisharebest** [comment]
> This is exactly what is happening now with the recent changes.

This must be a bug.  I thought I had changed it to look only for media attached to the individual (not to facts/source citations).

**Comment by fisharebest** [comment]
>  I have a lot of individuals with documents but without portraits The first thing you now see when entering an individuals page is a death notice or even worse, a picture of a graveyard. I am sure some visitors won't really appreciate this. And to be frankly I don't either.

For clarification:

I assume you have attached the death notice to the `DEAT` event and the graveyard photo to the `BURI` event?

**Comment by JustCarmen** [comment]
I see what is happening. For example the death notice above is attached to the death event of the individual. In this example "Jan Knegt". On his page this notice is _not_ visible in the carousel. But it is also linked to all people (his wife and children), who are mentioned in the death notice.

On their pages the death notice is in the carrousel.

I think that is an unwanted side effect.

**Comment by JustCarmen** [comment]
There are also individuals without any media items. Now you just see a link to add a new media item. And a regular visitor (not logged in) just sees an empty spot. Imho it is much nicer to show the old silhouettes there instead of an empty spot.

**Comment by fisharebest** [comment]
> much nicer to show the old silhouettes

I want the silhoutte to resize automatically - the same as the real images.

This is easy with a `<img>` tag.  It is harder with a CSS.

**Comment by JustCarmen** [comment]
> I want the silhoutte to resize automatically - the same as the real images.

A few years back when developing my justlight theme I've turned the silhouettes into font icons. With the bootstrap responsive utilities these could then  be easily resized according to the screen size.

If you are interested I can sent you the fonts. I generated them with [Icomoon](https://icomoon.io/).

**Comment by JustCarmen** [comment]
In fact I've turned a few more images into icons. This is the whole package I use:

![10-9-2017 10-12-05](https://user-images.githubusercontent.com/5641963/30247267-b33e312a-9610-11e7-8705-f850947c2b68.jpg)

**Comment by fisharebest** [comment]
I have added the silhouettes.  The size is fixed.  I will try to fix the auto-resize later.

**Comment by JustCarmen** [comment]
> I have added the silhouettes. The size is fixed. I will try to fix the auto-resize later.

That's fine.

But there is another thing that just occurred to me. I am not sure if I should made a new issue for this because it is very much related.

You have removed the primary tag. This means all individuals where an image was set as primary do not have it anymore.  The image that shows up as the first image in the carousel could be another (first level) image. I've used the sort order feature rarely so this means I have to manually check all individuals to see if the correct image shows up as the first image in the carrousel....

**Comment by fisharebest** [comment]
I hope you will agree that it is better to use standard GEDCOM conventions than custom tags.

The logic for `_PRIM` is not clear, not documented, and I think rarely used.

> I have to manually check all individuals

You can identifiy individuals using a query like this one

```
SELECT l_file, l_from
FROM wt_link
JOIN wt_media ON m_file=l_file AND m_id = l_to
JOIN wt_individuals ON i_file = l_file AND i_id = l_from 
WHERE m_gedcom LIKE '% _PRIM %'
-- Linked at level 1
AND i_gedcom LIKE CONCAT('%1 OBJE @', l_to, '@%')
-- More than one image link
AND LOCATE('1 OBJE @', i_gedcom, 1 + LOCATE('1 OBJE @', i_gedcom)) > 0;
```

Does this help?

**Comment by JustCarmen** [comment]
> I hope you will agree that it is better to use standard GEDCOM conventions than custom tags.
Yes, agreed.

> I think rarely used
I was one of those rare persons who was using this feature regularly to set a highlighted image.

> You can identifiy individuals using a query like this one
Thanks, this certainly helps. I will try it tomorrow.
