### ISSUE TITLE
Import gedcom

### ISSUE THREAD

**Issue by Fa10175** [fisharebest/webtrees#1355]
download of the 10 sept 2017
the site has several trees. if I want to import a gedcom on the second tree, it tries to do it on the first

**Comment by fisharebest** [comment]
I just tried this:

1) create two trees
2) import a GEDCOM into the second tree
3) import a GEDCOM into the first tree
4) both trees now contain the expected GEDCOM data.

Can you give more details to help me reproduce the problem?

**Comment by Fa10175** [comment]
I did not try to import this second tree because the title in the page that asks me the name of the file gave me the name of the first tree and below (I had not seen it) and in small the name of the second tree.
I think it's just a display problem
