### ISSUE TITLE
/webtrees/addmedia.php:230 Bad $action () in addmedia.php 

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#1357]
- Open https://dev.webtrees.net/demo-dev/individual.php?pid=i1&ged=demo#media
- Klick an Edit-Button of an image
- Error /home/webtrees/dev.webtrees.net/demo-dev/addmedia.php:230 Bad $action () in addmedia.php is shown

**Comment by fisharebest** [comment]
I don't think we need an edit link here.  What are we editing?

It we want to edit the image properties, we should visit the image's page and edit it there...
