### ISSUE TITLE
Admin - Error message in privacy settings

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1359]
![10-9-2017 14-39-12](https://user-images.githubusercontent.com/5641963/30249160-0da424ba-9636-11e7-9f9d-b7a9e6bd032e.jpg)

**Comment by fisharebest** [comment]
I see a privacy restriction in each column.

Can you examine the HTML?

**Comment by JustCarmen** [comment]
Sorry my mistake. In order to solve the issue with the sidebar I needed to cover up another error to quickly set some trees as private. Afterwards I thought I had put everything back in the original state and couldn't find the original error anymore but saw the empty column. Apparently forgot to save... Short memory or something....

The original error is this one:

`C:\xampp\htdocs\webtrees\includes\session.php:137 C:\xampp\htdocs\webtrees\admin_trees_config.php:528 Undefined index: hidden #0 \admin_trees_config.php:528 ErrorException("C:\xampp\htdocs\webtrees\admin_trees_config.php:528 Undefined index: hidden")`

The original setting was 'hide from everyone'. A state that doesn't exist anymore?

**Comment by fisharebest** [comment]
I had used the wrong list of options in the `<select>`
