### ISSUE TITLE
/jquery-ui-1.11.4/js/jquery-ui.min.js not autoloaded

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#1360]
Is there any reason why jquery-ui (packages/jquery-ui-1.11.4/js/jquery-ui.min.js) is not included by default in the page? Will this present in the next version of webtrees or will it be removed, so I have to provide it with my module?

**Comment by fisharebest** [comment]
jQuery-UI has been removed.

We no longer use/need any of the features that it provies.

**Comment by fisharebest** [comment]
> I have to provide it with my module?

Yes.
