### ISSUE TITLE
Time to load page with several thumbnail is long

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#1361]
I noticed that pages containing several thumbnail images can take very long to load. 

For instance the page: [https://dev.webtrees.net/demo-dev/medialist.php?action=submit&ged=demo&folder=&subdirs=&filter=&form_type=&max=20&page=1](https://dev.webtrees.net/demo-dev/medialist.php?action=submit&ged=demo&folder=&subdirs=&filter=&form_type=&max=20&page=1) Took the first time almost 30 seconds to load! 

Like me, most users of Webtrees are most probable using a shared server. I am afraid that loading times on these servers will even be longer (or even impossible). Since I am using quite a lot of images on all my pages I am afraid that I cannot use the 2.0 version of Webtrees.

Could you please comment on this issue? Is this just temporary and will the loading time improve when version 2 has developed further?

**Comment by JustCarmen** [comment]
> ook the first time almost 30 seconds to load!
Are you sure you don't have problems with your internet connection? The indicated page took me 1,5sec. to load.

![image](https://user-images.githubusercontent.com/5641963/30292451-7d41e568-9736-11e7-8b73-4719d91f1e71.png)

**Comment by SnarfW** [comment]
I am quite sure it was not a slow internet connection. The first time it took very long the second time it was much faster. I understand that thumbnails are automatically generated, and not stored in the data folder. Are the generated thumbnails perhaps stored in a cache on the server? This could explain the observed behaviour.
I also noticed that other pages containing images that I visit for the first time can take quite long to load (or should I say calculate). 

First visit:
![first](https://user-images.githubusercontent.com/25879600/30334927-4e98feee-97e1-11e7-9df3-0318b0c7fd39.jpg)

Second visit:
![second](https://user-images.githubusercontent.com/25879600/30334928-4f4983d6-97e1-11e7-92da-dcd0c0951399.jpg)

**Comment by fisharebest** [comment]
> The first time it took very long the second time it was much faster.

The first request causes the thumbnails to be generated.

The second request uses the thumbnails that were created earlier.

Creating thumbnails is a CPU-intensive operation.

On the demo server, the data folder (including thumbnails) is reset every night.  Normal sites will not have this issue.

**Comment by SnarfW** [comment]
Clear, thanks for the explanation. I will close this issue
