### ISSUE TITLE
Horizontal scroll bars on all themes except clouds, all browsers except FF

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1362]
This is a bootstrap issue and I am stumped.  Colors and xenea have a horizontal scroll bar on the home page.  It appears correctly in Firefox.  However, Chrome, IE, and Edge on windows all show the same problem.

![image](https://user-images.githubusercontent.com/5147603/30294916-abc4c290-96f3-11e7-9d39-605421318a2d.png)

![image](https://user-images.githubusercontent.com/5147603/30294967-d4a7d94a-96f3-11e7-9920-092d9c0cd6d0.png)

**Comment by JustCarmen** [comment]
I think this is the problem:

https://codepen.io/tigt/post/bust-elements-out-of-containers-with-one-line-of-css
https://cloudfour.com/thinks/breaking-out-with-viewport-units-and-calc/

This code is used on the margins of the primary and secondary navigation in the xenea theme and the primary menu (ul) in the colors theme:
`margin 0 calc(50% - 50vw)` 

The other themes don't use this construction.

So you could set an "overflow: hidden" on the html element or reorganize the html.

**Comment by fisharebest** [comment]
Without seeing more of the page, that could be the correct/intended layout.

The header background needs to expand out of the header to reach the full width of the screen.

**Comment by makitso** [comment]
Looked at both breakout articles, but nothing works -- stumped.

**Comment by makitso** [comment]
Looks like Chrome doesnt support viewport units (vw, vh)  in CSS transforms.
https://bugs.webkit.org/show_bug.cgi?id=91554

**Comment by fisharebest** [comment]
We're not using CSS transforms?

**Comment by makitso** [comment]
So, the problem appears to be with calc, the vw in that the scroll bars are part of the calculation.

**Comment by fisharebest** [comment]
One possible solution could be to disable horizontal scrollbars using CSS.

**Comment by makitso** [comment]
Yes, I tried that.  But, it prevents seeing the entire Hourglass chart, at least for desktop systems.  Touch devices work fine.

**Comment by makitso** [comment]
I have managed to fix the scroll problem by adding a container around primary menu, see changes to abstractTheme.php below.  I also need to make a change to the XeneaTheme.php as well as some style tweeks.  Greg, what do you think, should I update git?

/**
	 * Add markup to the primary menu.
	 *
	 * @param Menu[] $menus
	 *
	 * @return string
	 */
	protected function primaryMenuContainer(array $menus) {
		return '</div></div></div><div class="wt-primary-container"><nav class="container wt-primary-navigation"><ul class="nav wt-primary-menu">' . $this->primaryMenuContent($menus) . '</ul></nav></div><div><div>';
	}

**Comment by fisharebest** [comment]
Ideally, I would like all themes to use the same HTML, and do all styling in CSS.

**Comment by makitso** [comment]
That would be great but no styling solution that I have found fixes the calc vw problem.  However, its your call.

**Comment by fisharebest** [comment]
This seems to be a browser bug,
https://bugs.webkit.org/show_bug.cgi?id=133271
https://bugs.chromium.org/p/chromium/issues/detail?id=377331

A quick test suggests that `body { overflow-x: hidden; }` provides a reasonable workaround for this.

But as you say:

> it prevents seeing the entire Hourglass chart, at least for desktop systems. Touch devices work fine.

There are several "wide" charts that require horizontal scrolling (ancestry, hourglass).

Scrolling left/right to see the full chart will also scroll the header/footer.  If the chart itself had `overflow-x: scroll`, then you'd still be able to scroll to see the entire chart, but the chart options and header/footer would remain in place.

This would provide a nicer "screen" environment, but would prevent printing.  So, maybe the `body { overflow-x: hidden; }` should exclude print media types.

**Comment by makitso** [comment]
OK, everything looks OK except there is a phanton horizontal scroll bar at the bottom of all charts.  

![image](https://user-images.githubusercontent.com/5147603/30783971-4137473c-a101-11e7-9d29-ed2aa7d2a8b7.png)

`
body {
	overflow-x: hidden; /* clips left and right */
}

.wt-ancestors-chart,
.wt-compact-chart,
.wt-descendants-chart,
.wt-family-book-chart,
.wt-fan-chart,
.wt-hourglass-chart,
.wt-lifespans-chart,
.wt-pedigree-chart,
.wt-relationships-chart,
.wt-statistics-chart
{
	overflow-x: scroll; /* clips left and right */
	overflow-y: hidden; /* clips top and bottom */
}


@media print
{    
    body,
	.wt-ancestors-chart,
	.wt-compact-chart,
	.wt-descendants-chart,
	.wt-family-book-chart,
	.wt-fan-chart,
	.wt-hourglass-chart,
	.wt-lifespans-chart,
	.wt-pedigree-chart,
	.wt-relationships-chart,
	.wt-statistics-chart
    {
        overflow-x: initial;
        overflow-y: initial;
    }
}`

**Comment by makitso** [comment]
Greg,  You don’t suppose that it might be easier to reset the viewpoint width vw, for browsers with the Chrome user agent?  Could this be down in JS?

**Comment by makitso** [comment]
Just found out that the new Firefox version 57 has the same problem as Chrome.

**Comment by makitso** [comment]
I am impressed!   Everything seems to work except for HTML Reports, there is no scroll bar.

**Comment by makitso** [comment]
I am going to close this issue out. Reports work well on touch devices and larger screens. If it's a problem let someone open a new issue.
