### ISSUE TITLE
Top 10 Surnames and Given names do not have row sort option or Odd/Even coloring

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1366]
![image](https://user-images.githubusercontent.com/5147603/30548830-0f596dac-9c48-11e7-9fb3-8a7561d8f59c.png)

**Comment by makitso** [comment]
I think I am loosing my mind, there is something really strange going on.  There are times when the Top 10 blocks show the sort arrows and odd/even coloring.  And, then at times they do not.  It appears to happen on a theme change not not all the time.  Here are two screen shots a few minutes apart to prove I am not nuts.
file:///home/rob/Desktop/Selection_046.jpg

file:///home/rob/Desktop/Selection_047.jpg

**Comment by fisharebest** [comment]
The lack of arrows indicates that the dataTables initialisation code wasn't called - which probably means that there was a Javascript error somewhere.

Anything in the browser/js error log?

**Comment by makitso** [comment]
Looked at webtrees log and Apache log, nothing.  Tried to get it to fail with Firebug running but couldn't.

**Comment by makitso** [comment]
Doing a Ctl+Sh+J to see the browser console shows nothing.
For what its worth, on Win10, using Edge, it always shows the sort arrows.
