### ISSUE TITLE
Highlighted image - preferred media object

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1370]
This issue is related to the following issues but since it is not quite the same I thought I make a new one.

https://github.com/fisharebest/webtrees/issues/1354
https://github.com/fisharebest/webtrees/issues/1310

Formerly the highlighted image was the one set as primary image with the _PRIM tag. This tag is removed. As highlighted image we now use the first level 1 media object for an individual. By changing the sort order it is still possible to set the prefered image as highlighted image. This image is used in several places like charts, the individual page and also in some custom modules like the Fancy Treeview page. Currently I am working on [the Fancy Treeview module to implement the new media url's](https://github.com/JustCarmen/fancy_treeview/issues/56) and I stumbled accross this issue.

In this case I have an individual to whom I have attached several level 1 media objects. But none of them are portrait pictures. So I rather do not want one of these documents to show up as the highlighted image. In charts I would like to see the silhouette instead as well as on the individual page and in other places where a highlighted image is used.

I think this could be solved by adding the media type to the function. Only mages marked in the Gedcom with the type 'photo' should be used. Al other images (documents, newspapers, gravestones etc) should be left out.

I hope this could be implemented, because this is really a big issue. I've hundreds of media objects attached to persons who don't have a portrait picture among them.

In the example below the birth certificate of the son of this individual is attached to his record. It is very common to link media objects to other persons. These objects are automatically attached as level 1 objects.

Below a few examples of what I mean:

![image](https://user-images.githubusercontent.com/5641963/30828544-489ee2f8-a23e-11e7-9fe6-4544efd41511.png)

![image](https://user-images.githubusercontent.com/5641963/30828571-5ab40c8e-a23e-11e7-949f-dad07e7346c6.png)

**Comment by HRN-webtrees** [comment]
Removing the _PRIM tag has left my site in "chaos". Having more than 5000 indis and 8400 media objects, there will be a lot of sorting. Also, for many individuals, I have level 1 media objects (type photo) that I do NOT want highlighted. I do understand that _PRIM is not standard GEDCOM, but do we really have to remove it?

**Comment by JustCarmen** [comment]
> I have level 1 media objects (type photo) that I do NOT want highlighted. 

That is exactly my point. I only proposed to use the photo type to get rid of most of the chaos, but there will still be many leftovers to cope with.

I hope there is a better alternative. For me this might be a real showstopper, because it forces me to rearrange the way I do my genealogical research. If nothing changes it means you cannot link documents to other persons anymore because these will immediately show up as highlighted image. It also means that all current level 1 documents and unwanted photos should be placed elsewhere. Because I have a lot of individuals with linked media objects where I do NOT want any of these highlighted. I can't imagine this is intended.

**Comment by HonkXL** [comment]
For me this is a reason for not updating to 2.0 :-(
I have a lot of media files in my trees. Photos showing persons are marked as photos, others as documents and so on. The portrait photo is any of the photo, not always the first one.

It is totally sill to show other photos like documents or newspapers in the trees!

Yes, I understand that it is a good idea to support GEDCOM in a strict way. But maybe there is a more clever way to handle this:
Show only images of the photo type here.
When updating from 1.9.x to 2.0 set the image that has the tag "show" to the first photo. Only if there is none tagged or more then one, leave it as it is.

I know: not easy to implement, but I am sure that there will be a lot of angry requests from users after updating to 2.0 if there is no change in this point.

**Comment by UksusoFF** [comment]
@fisharebest any news here? 

I'm very confused after update to 2.0 :)

**Comment by UksusoFF** [comment]
UPD: Found answer in https://webtrees.github.io/upgrade/#primary-photo
