### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#1372]
In the "month" view, I see for instance all the birth dates of each person in the tree. 

https://dev.webtrees.net/demo-stable/calendar.php?cal=&day=27&month=SEP&year=2017&filterev=BIRT&filterof=all&filtersx=&view=month

If I change to "day" or "year" view I only see persons born on this day or in this year.

Seems like a bug for me that other events of the persons are not shown in day/year view?

**Comment by fisharebest** [comment]
> In the "month" view, I see for instance all the birth dates of each person in the tree.

If I follow the link, I see:

* Sep 1-8 empty
* Sep 9 contains one person, born on Sep 9
* Sep 10 contains one person, born on Sep 10
* Sep 11 contains two people, born on Sep 11

I do not see (or understand) the problem.

**Comment by magicsunday** [comment]
Ok all fine. My fault. I finally discovered the possibility to use ranges in the year selector.
