### ISSUE TITLE
Favicon not recognized

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1378]
In abstract theme the favicon is referenced to 'SELF::ASSET_DIR. This leads to the _common theme. In the common theme there are no favicons. Each theme holds its own set. 

I don't know what is intended. Or the favicons should be placed in the common theme and removed from the other themes or SELF::ASSET_DIR should be replaced with STATIC::ASSET_DIR

**Comment by fisharebest** [comment]
I guess that the icons should be moved to `_common`.

This way, all themes can share the default icon, but and also provide their own.
