### ISSUE TITLE
Place check (google maps module)

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1383]
What happened to the place check in the google maps module???

I can't find it anymore. Looks like it has been removed. Why??? How do we look up new coördinates and enter new places into the database now?

**Comment by JustCarmen** [comment]
Never mind. Found it. You need to use the import button to import new places from a gedcom and then you are able to locate the places without coördinates and lookup their coördinates in the map.

**Comment by fisharebest** [comment]
The place check has been combined into the list of geographic data.

Each place shows a count of the number of lower-level places that do not have co-ordinates.

Many people (me included) found it confusing to have two hierarchy lists.

**Comment by JustCarmen** [comment]
The disadvantage of this new system is that you can't get all the places without coördinates in one overview. You need to click through all lower level places to find the one without the coördinates. Fill it, save it. Then click your way back up (or use the breadcrumb) to go to the next upper level place. Click down again to all lower levels to find the next place without coördinates and so on.

In my opinion this is much more confusing and time consuming than how it was before.... But I think this could be easily overcome by adding an option to show only places without coördinates. That shouldn't be hard to implement. Maybe I should open this issue again and make it a feature request....
