### ISSUE TITLE
colorbox/wheelzoom - zooming should expand to fill window

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#1384]
The problem is shown in here: https://github.com/jackmoore/wheelzoom/issues/3

A user-submitted patch existing for older versions of colorbox/wheelzoom to fix this.

https://github.com/fisharebest/webtrees/tree/1.7/assets/js-1.7.9

We need to create similar patches that work with the latest code.

**Comment by makitso** [comment]
Do you want me to keep this issue open or will #1384 be enough?

**Comment by fisharebest** [comment]
Keep them both open.  They will probably get fixed separately.

**Comment by CharlesNepote** [comment]
I'm interested by this patch. I don't know how to fix that but I'm able to help to test. A live example: http://rn7.net/histoire/20.sources/10.Dauphine/ADIs/20171003.1006.4E80.215.Bois.de.Montbuffet/slide_IMG_5661.html

**Comment by ddrury** [comment]
This is a nice lightbox with all the facilities inbuilt. http://sachinchoolur.github.io/lightGallery/
