### ISSUE TITLE
Error when try to create a clipping file in GitHub test system

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1385]
I try to create a clipping file in my GitHub test system and I get:
/home/amitys/test.amitys.com/includes/session.php:137 /home/amitys/test.amitys.com/app/Module/ClippingsCart/ClippingsCartController.php:164 tempnam(): open_basedir restriction in effect. File() is not within the allowed path(s): (/home/amitys/) #0 unknown:unknown ErrorException("/home/amitys/test.amitys.com/app/Module/ClippingsCart/ClippingsCartController.php:164 tempnam(): open_basedir restriction in effect. File() is not within the allowed path(s): (/home/amitys/)") #1 /app/Module/ClippingsCart/ClippingsCartController.php:164 tempnam('', 'webtrees-zip-') #2 /app/Module/ClippingsCartModule.php:75 __construct() #3 /module.php:25 modAction('index')

**Comment by fisharebest** [comment]
The clippings cart is still using the old .ZIP library - which does not work with modern versions of PHP.

We have a new library, but we have not updated all the code to use it.
