### ISSUE TITLE
Highlighted thumbnail pictures

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1386]
I do not see my thumbnail pictures in the GitHub test site.
I see thumbnail pictures that seem to be created by webtrees.

On my production site (older code) that uses the same media files as the test system, I see the main 100x120 thumbnails created by me.

On the production site I do not see as main pictures pictures with Highlighted image No. In the GitHub test site I see them.

Samples are for instance pictures of 
I23918, I7561 and I7546

**Comment by fisharebest** [comment]
> I do not see my thumbnail pictures in the GitHub test site.

In webtrees 1.x, there was only one thumbnail image for each full-size image.  This one thumbnail was used everywhere.

In webtrees 2.x, we create different thumbnails for each context.  For example, we generate smaller thumbnails for person-boxes and larger thumbanails for the primary image on the individual page.  Some images are cropped to a fixed aspect ratio, others are scaled to fit a maximum height or width.

See also https://github.com/fisharebest/webtrees/issues/1271

> with Highlighted image No

The "highlighted image" tag is non-standard, and also relies on having the value "N".  GEDCOM says that tags should only ever have the value "Y".

So, this tag has been removed.  We now show the first image as the highlighted image.  This follows the GEDCOM standard that when there are multiple copies of data, the first one takes precedence.  There is a "sort media objects" link underneath the primary image.

The issue https://github.com/fisharebest/webtrees/issues/1370 has been raised by Carmen, who used `1 _PRIM N` extensively.

**Comment by melizaa** [comment]
Perhaps we could create a smaller image from the thumbnail one instead of from the full picture.

As Carmen writes, the first or only image is not in many cases a picture we should use as the highlighted image.
I do not want to see for instance group photos, building photos, grave pictures or document pictures as highlighted images.

I have some 4000 individuals and 370 families with "1 OBJE"s.

**Comment by JustCarmen** [comment]
> So, this tag has been removed. We now show the first image as the highlighted image. This follows the GEDCOM standard that when there are multiple copies of data, the first one takes precedence. There is a "sort media objects" link underneath the primary image.

The "sort media objects" function only has the desired effect if there IS an image that we want to show as highlighted image. Most of the time NONE of the images attached to an individual should be highlighted! There should be an option to use the silhouette instead.

**Comment by fisharebest** [comment]
> I only want to use pictures of people as highlighted image and nothing else.

I understand this.

Personally, I disagree.  Images help you to recognise the same person as you navigate around the site.  A photograph of a gravestone, coat-of-arms, building, etc., does this as well as a photograph of the individual.

Are these "undesirable" images

*  media objects that **should** really be linked to facts/events or source citations (e.g. documents or photographs of places, buildings, gravestones, etc.)
* something else

**Comment by melizaa** [comment]
It should be possible to carry out, but it will take a lot of time to check my 4000 individuals with level 1 media.

**Comment by HRN-webtrees** [comment]
With more than 5000 individuals and 10000 media files, I see alot of work coming up :(

**Comment by fisharebest** [comment]
> With more than 5000 individuals and 10000 media files, I see alot of work coming up :(

webtrees has a tool to help: Control panel -> Media -> Link media objects to facts and events

It will list all your media that is linked to an individual, and give you a one-click option to move them to an appropriate fact/event.

<img width="739" alt="screen shot 2019-02-16 at 16 22 48" src="https://user-images.githubusercontent.com/2306088/52902345-509ae880-3207-11e9-91a6-f3539bc7e803.png">
