### ISSUE TITLE
righ/left arrows wrong in fab and minimal rtl pages - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1394]
right/left arrows point to wrong direction on rtl pages in fab and minimal themes
I see the issue at least on the following pages: family, compact tree, hourglass, pedigree, relationship
![image](https://user-images.githubusercontent.com/5202996/31483734-46723f66-af36-11e7-91f0-cdf32998496d.png)

**Comment by fisharebest** [comment]
We were using an out-of-date version of the `fisharebest/font-awesome-rtl` library.

You may need to clear your browser cache to see the fix.
