### ISSUE TITLE
RTL pages - the texts should print adjusted right - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1399]
RTL pages (יידיש, עברית, العربية) need to be mirror images of the LTR pages.

The RTL texts and media should print adjusted right. Now most texts are printed adjusted left, as on LTR pages.

I speak for instance of: page titles, names and icons, fact/event titles and texts, selection boxes, buttons and menus and their texts.

Latin only data like URLs, time zones or directories could print LTR.

Special characters like ? ) “ , !, numbers, etc. on RTL pages at the end of LTR texts should print to the right of the text, not to the left. Samples: "Congo (Democratic Republic)", "genealogy brick walls." and "admin/". 

[Special characters on LTR pages at the end of RTL texts should print to the left of the text.]

**Comment by melizaa** [comment]
I have not created issues for all the RTL issues that I have seen. I will do this after the existing issues are solved.

**Comment by melizaa** [comment]
LTR texts on RTL page News block, Journals block, Research tasks block, Individual Notes and Shared Notes, Shared notes list, Source titles, and Source Author, Repository list, Media titles

**Comment by melizaa** [comment]
I have looked at the research tasks in the block. My site has only 5 tasks written in rtl texts, all the others are ltr. In pre 2.0.0 I used to see these texts adjusted left also on rtl pages. Now they are adjuster right on rtl pages, although the code of research-tasks.phtml is 
                <td dir="auto">
                    <?= e($task->value()) ?>
                </td>
I tried also dir="ltr". It did not print the text adjusted left.

How can I change the code to print this text adjusted left?

pre 2.0.0
![2019-03-01_20-40-47](https://user-images.githubusercontent.com/5202996/53658780-75a94580-3c62-11e9-8791-53c0ec51c1e7.jpg)

2.0.0
![2019-03-01_20-26-10](https://user-images.githubusercontent.com/5202996/53658030-632e0c80-3c60-11e9-9876-09210b4cb4b5.jpg)

**Comment by melizaa** [comment]
the code is (I added some spaces)
< td dir="auto" >
                    < ?= e($task->value()) ? >
                < /td >

**Comment by melizaa** [comment]
The ltr column data prints adjusted right on the rtl page because of  the vendor.min.css body definition text-align: right;
and rtl data on the ltr page prints adjusted left because of text-align: left.
If I unselect the vendor.min.css body text-align: right; and the text-align: left; in chrome inspect, I see the texts adjusted as expected. 

How can I get rid of the vendor.min.css definition for the column data?
Is the body definition used only for table data?

Perhaps we can replace the text-align by dir="auto" and remove the dir="auto" from the tabular resources/modules/xxxx/yyyy.phtml etc. files? (for instance research-tasks.phtml)

Now we adjust rtl data on ltr pages left and ltr data on rtl pages right.
It is correct to adjust the page texts this way. It is not OK to adjust the site data this way.

**Comment by melizaa** [comment]
I do not know how to print on rtl research task pages ltr records (for instance John Doe) adjusted left and rtl records adjusted right.

**Comment by melizaa** [comment]
also, I have added in pre 2.0.0 to several Hebrew texts <span dir="ltr">Latin text</span>. This does no longer work. We see the <span ...>. I will try to remove one of text with the spans. Let's see if we will see the texts as expected.

**Comment by melizaa** [comment]
For instance, the Research Tasks block prints still the texts aligned by the page language rules, not by the data text rules.
As I wrote, in Pre 2.0.0 I added dir="auto" where the common code did not print the texts as expected. Now, this does no longer work. 
The common code has dir="auto" for the research task text. It does neither work.

**Comment by melizaa** [comment]
See for instance <https://www.w3.org/International/tutorials/bidi-xhtml/>

**Comment by melizaa** [comment]
Also messages, news, and headers. Latin names and places in lists, etc.

**Comment by melizaa** [comment]
The Mirroring in the following document shows how the text language, not the page language, should define how the text is adjusted.

<https://material.io/design/usability/bidirectionality.html#mirroring-elements>

**Comment by fisharebest** [comment]
> I have not created issues for all the RTL issues that I have seen. I will do this after the existing issues are solved.

All existing RTL issues should now be fixed.  Please create a new issue for each problem.  Thanks!
