### ISSUE TITLE
RTL pages selection-boxes and -buttons - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1402]
On RTL pages selection-boxes and -buttons and their texts should print adjusted right and not one on top of the other

Some samples are 
Lifespans, Descendants, Ancestors, Family book, Relationships, Hourglass, Own statistics  charts
Branches list
admin_site_config

**Comment by fisharebest** [comment]
This is the `select2` library.

We are planning to replace this with another library (`chosen`) in #1369 

Need to review rtl / css as part of that.

**Comment by melizaa** [comment]
Also medialist, search, phonetic search, search and replace and several admin pages.

Search
![selection1](https://user-images.githubusercontent.com/5202996/32163500-2874db6c-bd65-11e7-96d8-8b6853e495bd.jpg)

Relationships
![selection2](https://user-images.githubusercontent.com/5202996/32163607-80a19da2-bd65-11e7-9a87-70238d13edf2.jpg)

**Comment by melizaa** [comment]
looks OK
