### ISSUE TITLE
The shared notes list is empty - Shared notes are defined - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1403]
I see no shared notes in the list. 
The theme or lanfguage changes do not work from the list page.N1 

I have in the GEDCOM for instance N1 and N2.

**Comment by JustCarmen** [comment]
I can confirm this. It is caused by a Javascript error in the datatable function. That's also why the language changes do not work.

Not sure where it is located but the dev console shows this error:
`Uncaught TypeError: Cannot set property '_DT_CellIndex' of undefined`
