### ISSUE TITLE
RTL - top submenu texts cut - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1405]
RTL page top selection submenu texts are cut. The texts are as expected adjusted right. The texts print fully on LTR pages.

Language - American English
Family trees
Clippings cart - Add to the clippings cart
Edit - Edit the raw GEDCOM
Family tree overview (Fancy Tree View)
etc.

**Comment by fisharebest** [comment]
bootstrap.js sets `left: 0` on dropdowns which causes this effect.

Removing this (default is `left: auto`) which appears to give the correct layout.

**Comment by fisharebest** [comment]
There are several bootstrap-4 RTL libraries.  e.g.

https://github.com/parsmizban/Bootstrap-RTL
https://github.com/mmdsharifi/Bootstrap4-RTL
https://github.com/GhalamborM/bootstrap4-rtl

These only support bootstrap4.alpha6.
Hopefully they will soon be updated to use bootstrap4.beta

**Comment by melizaa** [comment]
I added Charles William Frederick Cavendish-Bentinck as a favorite in demo-dev.
His name is cut in the rtl top Favourites menu.
![2017-11-18_09-58-43](https://user-images.githubusercontent.com/5202996/32978261-1e4f43de-cc47-11e7-931b-8da725643080.jpg)

**Comment by melizaa** [comment]
Should https://github.com/MahdiMajidzadeh/bootstrap-v4-rtl or some other package correct our remaining rtl issues?

RTL
Index pagw - block titles, texts and submenu texts print adjusted left.

Individual page - Facts, names, right/left hand side titles and list data print adjusted left. Not OK for rtl texts.
Family/Source/Media/Cousins tab data printed adjusted left.

Family page - titles, add child, father/mother, etc., fact data printed adjusted left

Individual , Google map, Media, Branches list texts and end of text special characters
Source, Repository page/list titles, texts and dates

Calendar - day/month/year and data

Search - option texts and data

Clippings

Fancy Treeview

Texts print on selection boxes/buttons, sosa numbers in branches list

etc.

**Comment by melizaa** [comment]
The top drop down menu texts are adjusted left.

**Comment by melizaa** [comment]
Does a good rtl bootstrap4.beta library exist already?

If not, perhaps we should solve the adjust right issue in webtrees?

**Comment by fisharebest** [comment]
There are several bootstrap-rtl packages available.

The one you mentioned above seems to be the first to support the latest bootstrap version (bootstrap4-beta.2).

I haven't had time to try it out.  I expect to have some time between christmas and the new year.

**Comment by melizaa** [comment]
The American English text is still cut on the Hebrew pages in F.A.B., minimal, webtrees and xenea.

**Comment by fisharebest** [comment]
Seems OK now.

<img width="448" alt="Screen Shot 2019-08-11 at 18 52 13" src="https://user-images.githubusercontent.com/2306088/62837602-351a1300-bc69-11e9-9c15-e8567449edce.png">
<img width="256" alt="Screen Shot 2019-08-11 at 18 52 07" src="https://user-images.githubusercontent.com/2306088/62837603-364b4000-bc69-11e9-96bc-a063f7ff2802.png">
<img width="434" alt="Screen Shot 2019-08-11 at 18 53 46" src="https://user-images.githubusercontent.com/2306088/62837622-5ed33a00-bc69-11e9-8adc-fcf9583f7dca.png">

**Comment by melizaa** [comment]
I see
![image](https://user-images.githubusercontent.com/5202996/62838843-14ae8080-bc8a-11e9-9d32-b1a786543c85.png)

**Comment by fisharebest** [comment]
I tried in firefox, chrome and safari.  All work OK.

Which browsers did you try?

**Comment by melizaa** [comment]
Seems that you have defined less languages. 
I use chrome.

**Comment by vytux-com** [comment]
I have seen this on charts menu in chrome too on my site, but I think mine was after I added a custom chart module.

Do you maybe have a custom language module?

**Comment by melizaa** [comment]
My test test system is only GITHUB code.

**Comment by melizaa** [comment]
I see the languages OK in LTR languages.

**Comment by melizaa** [comment]
Perhaps we use multi bytes to calculate the menu width although the text is Latin, not multi bytes? 

My site has the same issue on the other RTL language (Yiddish and Arabic) pages.

**Comment by melizaa** [comment]
I see the issue also in demo-dev.

**Comment by melizaa** [comment]
Greg, which theme did you use?

**Comment by fisharebest** [comment]
This is from your test site:

<img width="318" alt="Screen Shot 2019-08-11 at 22 36 18" src="https://user-images.githubusercontent.com/2306088/62839833-84237080-bc88-11e9-99ba-34b0f4c65409.png">

This is from the demo site:

<img width="234" alt="Screen Shot 2019-08-11 at 22 37 35" src="https://user-images.githubusercontent.com/2306088/62839845-a5845c80-bc88-11e9-98f3-5b12c51e55bd.png">

Where can I see the problem?

**Comment by melizaa** [comment]
Which theme do you use. Perhaps the issue occurs only for certain (most)
themes.

**Comment by fisharebest** [comment]
> Which theme do you use

It works with all of them...

**Comment by melizaa** [comment]
I see the text American English on my Windows 10 client on RTL pages of demo-dev
OK - in Microsoft Edge (44.17763.1.0) and in Microsoft Internet Explorer (11.615.17763.0)
not OK - in Avast (75.1.1528.101), Google Chrome (76.0.3809), Mozilla Firefox (68.0.1), Opera (60-R3), Safari (5.1.7) and Vivaldi (2.6)
I do not (yet?) manage to reach demo-dev using a new installation of the Tor Browser (8.5.4).

I do see the full text at least in Google Chrome and almost the full text in Avast on the demo-dev RTL page in the clouds and colours themes. I have not looked at this in the other browsers.
