### ISSUE TITLE
Entering Date - DEV 2.0.0

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#1410]
I noticed that entering a date for a fact or event has changed considerable. At the moment I find the behaviour quite annoying. Some examples:

Eg I want to enter 1 dec 1900:

-) when I want to enter this like 1-12-1900: after the first '-' it is immediately is changed into a "FROM" date
-) when I want to enter this like 1.12.1900: is automatically changed into 2001 after typing the first digit of the year.
-) same with 12/1/1900. 

Is this behaviour intended??

**Comment by fisharebest** [comment]
The "date shortcuts" were being applied on the wrong event.
