### ISSUE TITLE
Add a child - DEV 2.0.0

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#1411]
I just tried to add a child to a family. It seems that this form is not finished yet. I am not sure whether you want me to submit these type of issues already or not.

Some issue on the add a child form:

-) Some unknown fields like "type". 
-) Missing tick boxs next to Birth/Death/Burrial
-) Help info on date shown in form
-) No fill in fields with the Map items (even not sure what should be filled)
-) Would it be be possible to have some "collapse" options (eg source, note etc) in here like in the current release?  Currently I have to scroll down five pages to find the save button.

**Comment by fisharebest** [comment]
> I am not sure whether you want me to submit these type of issues already or not.

Yes please

>Some issue on the add a child form:

Thanks!.  Next time, could you create a separate entry for each issue.  It makes managing them so much easier.

**Comment by fisharebest** [comment]
Name type fixed in 94d1540

**Comment by fisharebest** [comment]
Empty `MAP` tag should be hidden - fixed in fcd076d

**Comment by fisharebest** [comment]
Date help was already raised in #1346
