### ISSUE TITLE
Edit media object: missing delete/edit gedcom - DEV 2.0.0

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#1413]
When you edit a media object the option to edit the raw gedcom, manage the links or to delete the mediaobject is missing

**Comment by fisharebest** [comment]
I still see the "edit raw gedcom" and "delete" links in the main menu.

I intend to move the "link" functions to the tabs.  e.g. you would add a link to a source on the sources tab.

FYI, I intend to remove the "edit" menu entirely.  The rest of the menu is for navigation and users frequently fail to find this option.  The functions will be moved closer to the things they edit.

**Comment by SnarfW** [comment]
I am using the colors theme with ash pallet. In this view the Edit symbol is not visible in the menu...

By the way:  I cannot change the theme when you have opened a media object. Will create a new issue..

**Comment by makitso** [comment]
The edit icon is visible on the Facts and Events tab but missing from the Media tab in all themes.
