### ISSUE TITLE
Edit media object: error with change filename - DEV2.0.0

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#1414]
When you change the filename of a document, and error is obtained: 

/home/webtrees/dev.webtrees.net/demo-dev/includes/session.php:137 /home/webtrees/dev.webtrees.net/demo-dev/edit_interface.php:811 sha1_file(/home/webtrees/webtrees-data/media/royals/Charlotte_Amalie_of_Hesse-Philippsthal.JPG): failed to open stream: No such file or directory #0 unknown:unknown ErrorException("/home/webtrees/dev.webtrees.net/demo-dev/edit_interface.php:811 sha1_file(/home/webtrees/webtrees-data/media/royals/Charlotte_Amalie_of_Hesse-Philippsthal.JPG): failed to open stream: No such file or directory") #1 /edit_interface.php:811 sha1_file('/home/webtrees/webtrees-data/m…')

**Comment by fisharebest** [comment]
This is related to #1270 and #1271.

The code it trying to find and rename a corresponding thumbnail.  But we have changed the thumbnail system, and this file won't exist.

**Comment by fisharebest** [comment]
Fixed in d6641c5850084ed75baaa5bc5b2d3d714e604881
