### ISSUE TITLE
Default media type - DEV 2.0.0

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#1415]
When you create a new media object the default type is "audio".  Another default type would be useful.
Would it be possible to set the default type in the control panel?

**Comment by fisharebest** [comment]
There is no default media type.

Is your web browser auto-completing the form?

Can you give exact steps to reproduce?

**Comment by SnarfW** [comment]
Correct when you create a new media object it does not auto-complete the form. But when you edit an object without type it does auto-complete and changes to Audio.
