### ISSUE TITLE
Edit media object: thumbnail - DEV2.0.0 

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#1416]
In the Edit media object menu still the option to upload a thumbnail is shown. I am not sure, but I think this option is not needed any more. (or will it be used for PDF/video files?)

**Comment by fisharebest** [comment]
It's possible that the thumbnail changes may be deferred until 2.1.0, so I left some of the code there in case I need to roll back a little.

**Comment by fisharebest** [comment]
The "edit media object" page has now gone.

We now allow multiple media files per media object, and this functionality is now on the "edit media file" page.
