### ISSUE TITLE
Mediaobject: Image Dimension & Filesize not shown

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#1417]
Mediaobject: Image Dimension & File size not shown

**Comment by fisharebest** [comment]
They are shown when you are logged in with "editor" role or higher.

Visit https://dev.webtrees.net/demo-dev/mediaviewer.php?mid=m32&ged=demo
Log in with editor/editor
Size is shown

**Comment by SnarfW** [comment]
You are right. Not sure why I did not see this. I will close this issue
