### ISSUE TITLE
Create Mediaobject: options missing - DEV2.0.0

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#1418]
In the create media object menu, the option to add a source citation, shared note or to add a restriction is missing

**Comment by fisharebest** [comment]
In webtrees 1.7, we used popup windows to create new objects.
Popup windows could open other popup windows which could open other windows...
You could have 5 or 6 windows stacked up.

Tablets and phones do not have windows, and this mechanism does not work.

In webtrees 2.0, we only create one object at a time.  We use modal dialogs in some places, but these cannot be nested.

The "new media form"  is a modal dialog, and hence we can't open any more windows to create child objects.  These need to be added afterwards.

(Although the GEDCOM specification allows you to add sources to media objects, this is IMHO backwards.  You would link a media object to a source record, not the other way around.).

**Comment by SnarfW** [comment]
I feel that options that were possible in webtrees 1.7 should also be possible in webtrees 2.0. 

I have been using sources (especially for pictures received from others) and also restrictions to media-objects and would like to continue doing so... In the current 2.0 version I do not know how I should do this.

**Comment by fisharebest** [comment]
These options are now available on the media page.
