### ISSUE TITLE
v2.0 Notes tab

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#1427]
Wide notes (eg Markdown formatted census records) project beyond the RHS margin and are overlaid by the sidebar. (All themes)

Need overflow-x: scroll somewhere?

**Comment by ddrury** [comment]
Scope is wider than just the notes tab, it also occurs in the facts and events tab

**Comment by fisharebest** [comment]
> Need overflow-x: scroll somewhere?

Adding this doesn't seem to help.  Any ideas?

**Comment by ddrury** [comment]
I'll have play

**Comment by ddrury** [comment]
Well, I have a solution but I can't say it fills me with delight.

for every occurence of wt-facts-table add 
```
<colgroup>
    <col width="20%">
</colgroup>
```
to the HTML and add the following CSS
```
.wt-facts-table {
	table-layout: fixed;
}
```
Is a better solution to replace the tables altogether with a more bootstrap type of solution (a lot more work I suspect)

**Comment by fisharebest** [comment]
> I can't say it fills me with delight.

Agreed

> replace the tables altogether with a more bootstrap type of solution

That's almost certainly the way to go

**Comment by ddrury** [comment]
> a more bootstrap type of solution 

I think that's way beyond me at the moment so over to you - sorry

**Comment by ddrury** [comment]
Greg,
I think I have a solution for this. Maybe temporary but at least it'll help getting V2 out of the door.
First in FunctionsPrintFacts() immediately after line 1045 add` echo '<div class="note-details">';` and add the closing `</div>` immediately before the `</td>` i.e enclose all the content of the `<td>` with the `<div>`

Then add `note-details: {display: grid;}` to the css.

The markup on the individual facts already includes the necessary `<div class="note-details">` so the css fixes that as well.

Tested on firefox, chrome & edge on desktop & chrome on Android tablet.

**Comment by ddrury** [comment]
Just re-read this and it sounds like I'm teaching grany to suck eggs - sorry.

To sumarise, need to add `display:grid` to class note-details and add a wrapping `<div class="note-details">` for the notes tab

**Comment by fisharebest** [comment]
I was actually looking at this again last night.

I can either

a) prevent the table breaking out of the layout and add responsive horizontal scrolling to the table

b) set nice column widths for the two columns (labels/values) in the notes tab

but not both at the same time ;-)

I'll have a look at your suggestion later.

**Comment by ddrury** [comment]
In addition to above, adding `overflow-y: hidden` to markdown class prevents flash of vertical scroll bar when expanding a note, but I'm not sure of the wider impact of this

**Comment by ddrury** [comment]
For what it's worth, I've put the following in the CSS/JS module, maybe not the proper solution but a sticking plaster in the interim
```
<style>
  .wt-grid {display:grid}
</style>

<script>
  $('.markdown').wrap('<div class="wt-grid"></div>');
</script>
```

**Comment by fisharebest** [comment]
This seems to be working in the latest code. 

Maybe it was fixed by https://github.com/fisharebest/webtrees/commit/c1f982bd447ec3287562442cfee7e98387f793b9
