### ISSUE TITLE
v2.0 bug in commit 01cf285 (Use markdown for censuses)

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#1429]
Empty fields are overwritten by shifting leftwards fields to the right of the empty field.

Caveat - I'd already converted all my census notes to Markdown format and had rewritten function formatCensusNote to suit so it may be me at fault

**Comment by ddrury** [comment]
Just created new shared note and problem still exists so my caveat doesn't apply

**Comment by fisharebest** [comment]
> Empty fields are overwritten by shifting leftwards fields to the right of the empty field.

Is this in the data-entry grid for the census fields?

I don't see this.

Can you give me some exact steps to reproduce this?

**Comment by ddrury** [comment]
It's a display issue, I created a new note using the census assistant and the following was produced
```
Name|Relation|Condition|AgeM|AgeF|Occupation|Birthplace|Infirm
-----|-----|-----|-----|-----|-----|-----|-----
Henry Drury|head||11|||Ashton Under Lyne, Lancashire|
```
but the image below shows the corresponding display (events tab, notes tab are both the same)

![census](https://user-images.githubusercontent.com/104515/31707674-e84b0d56-b3e4-11e7-866d-05d89ce3626e.png)

**Comment by ddrury** [comment]
If I replace the empty fields with a space then it displays ok

**Comment by fisharebest** [comment]
Maybe the markdown/table syntax requires some content between the pipes....

I should have been less diligent filling in the forms when testing ;-)

**Comment by mpwt** [comment]
The markdown code from above works as simple shared note within 1.7.9. The table is shown correct. 

With the dev version it works not. The code is misinterpreted.

**Comment by fisharebest** [comment]
I have looked at the code in the markdown table library - https://github.com/webuni/commonmark-table-extension/blob/master/src/TableParser.php

It does not support empty table cells.

**Comment by ddrury** [comment]
Surely that's a bug isn't it? In any case is the solution to insert spaces?

BTW I noticed that when I put spaces in the markdown, the rendered output was an empty `<td></td>`

**Comment by fisharebest** [comment]
> Surely that's a bug isn't it?

There is no "official standard" for table markup, so the package is free to define its own.  We say "bug", the package owner might say "feature" ;-)

> In any case is the solution to insert spaces?

Or, it might be possible to write our own parser that handles the `.b....|` format directly.
(Similar to the parser I wrote for expanding XREFs into links)
Just looking at this now.

**Comment by Amgine0** [comment]
There's no "official standard" for extended Markdown, but [Michel Fortin's discussion](https://michelf.ca/projects/php-markdown/extra/) is usually considered strong guidance.

Is there a reason for not using the most-popular markdown library on packagist?

**Comment by fisharebest** [comment]
0a016d046f63b3b1ece7ec913216782c17f0cbad adds a markdown extension which formats the existing format notes.

@Amgine0 - I like the commonmark standard and library for many reasons.  It is designed to be extended, and I have created two extensions for it - these tables and XREF links.

**Comment by Amgine0** [comment]
That is a good reason. When I just searched I did not find user documentation for

* table MarkDown
* XREF links

on stable or beta demo, in the wiki, or in the forum, but perhaps I am not looking well.

**Comment by ddrury** [comment]
Neat solution, however I thought the idea was to not need to populate empty cells,
I note that you're now adding a space to front and back of the cell content so empty cells get two spaces, Removing them results in the original problem.

**Comment by fisharebest** [comment]
> I note that you're now adding a space to front and back of the cell content

That's because the census-assistant is now generating markdown, instead of the custom `.b.///` format.

> I thought the idea was to not need to populate empty cells,

That wasn't actually the intention.

I've just read the documentation for the first two pages of the google search results for `markdown` `tables`).  They all show spaces around the cell content.

In some markdown-table implementations, consecutive `|` characters are used to indicate `colspan`.

**Comment by ddrury** [comment]
Fair enough

> I've just read the documentation for the first two pages of the google search results for ...

Rather you than me :-(
