### ISSUE TITLE
Copy protection images - DEV2.0.0

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#1430]
In the current development version it seems possible for visitors to download (some) images without watermark by simple removing the part describing the watermark from the links shown on the site.
For instance: [https://dev.webtrees.net/demo-dev/mediaviewer.php?mid=m1&ged=demo](url) downloads the original.

**Comment by fisharebest** [comment]
The URL contains a signature to prevent this from happening.

Perhaps the signature is not being verified?

**Comment by SnarfW** [comment]
Not sure whether it is related: currently all thumbnails/images give a 403 not allowed error on the development demo-site
