### ISSUE TITLE
Watermark on thumbnails

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1433]
All thumbnails are having a watermark now while the option to use watermark on thumbnails is set to 'No'.

**Comment by fisharebest** [comment]
Previously, we had two image sizes: thumbnails (100px wide) and full-size.
The text watermark was difficult to add in 100px.

Now, we generate images with the exact size for each requirement.
We have an image watermark that can be used on any size.

I think this configuration option is not needed any more.

Unless there are strong objections, I shall remove it.

**Comment by JustCarmen** [comment]
No I think you are right. With the different sizes of thumbs it doesn't make sense anymore. 

I would rather see the option to add a watermark to certain types of images. I would like to watermark my photos, but I don't need a watermark on documents and newspaper artikels which are freely available elsewhere on the internet anyway.

**Comment by fisharebest** [comment]
It seems that simple watermarks can now be easily removed.

https://research.googleblog.com/2017/08/making-visible-watermarks-more-effective.html

> I would like to watermark my photos, but I don't need a watermark on documents and newspaper artikels

Perhaps create an issue for this?
