### ISSUE TITLE
FR: Watermark based on image type

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1436]
Now thumbnails are automatically watermarked (if the option to use watermarks is set to yes), it is all or nothing. Or you use the watermark on all images, thumbnails included or you don't use watermarks at all.

The reason to remove the distinguish between images and thumbnails is clear. Earlier discussed here: https://github.com/fisharebest/webtrees/issues/1433

I would rather see the option to add a watermark to certain types of images. I would like to watermark my photos, but I don't need a watermark on documents and newspaper articles which are freely available elsewhere on the internet anyway.

**Comment by fisharebest** [comment]
See 6577bfc3111b4789852b83f46e19d92c9b59921c and #3305 

There are now "hooks" available, to allow you to implement your own logic.
