### ISSUE TITLE
Links to (disabled) modules in dashboard

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1437]
Nice to have links to the configuration page of modules inside the dashboard. Very handy!

But if a module is disabled the configuration page is not accessible. I think in such a case the link should be grayed out or in some way be marked as disabled.

**Comment by fisharebest** [comment]
I am thinking of removing the top menu/navigation, and putting all the links on the "dashboard" page.

What do you think?

**Comment by JustCarmen** [comment]
Not sure. It is convenient to have all the configurable modules together in the dashboard, mainly because it gives a nice summary and it is not a very long list. Putting all links in the dashboard means a lot of scrolling (at least for me and other old fashioned laptop users without a touch screen). I am not very fond of scrolling through long lists.  Maybe you then should make the cards [collapsible](https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example) or use another way to get a quick overview of the content of the page.
