### ISSUE TITLE
Hide Entries

### ISSUE THREAD

**Issue by Gunnar-GO** [fisharebest/webtrees#1438]
It would be nice to have a option to hide some part of the trees for some users. Work together on a familytree, specially divorced families could benefit from such an option.

**Comment by fisharebest** [comment]
I don't think this is ever going to be possible.

> divorced families could benefit from such an option

Complications include:

* Other connections between the ex-spouses.  For example,  common ancestors, children, marriage of cousins.
* Performance relationship checks are very time consuming on large trees. Many sites struggle to calculate the relationship between two individuals.  We would need to calculate it for every record in every search request.

The only available options are:

* split the tree into two parts
* use the "relationship privacy" option.
