### ISSUE TITLE
Interactive chart on index page main part - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1440]
interactive chart block shows initially the chart too high up in the block for instance for Charles I, Landgrave of Hesse-Philippsthal. 
![interactive](https://user-images.githubusercontent.com/5202996/32036965-900d3edc-ba2b-11e7-9ce2-ea15eba089e3.jpg)

**Comment by magicsunday** [comment]
I guess you mean this page? https://dev.webtrees.net/demo-dev/module.php?mod=tree&mod_action=treeview&ged=demo&rootid=i239

**Comment by melizaa** [comment]
Yes.
