### ISSUE TITLE
The new individual date help text takes up unnecessary space on the form demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1442]
New individual - we should use the date help link from the icons next to dates to link to the date help text as for existing individuals and for families. Now the help icon of the new individual birth data links to the name help text.

After the date help text in the "Add new individual" form, the form data is printed on a very wide page, not under the data above the help text. This will probably not be an issue after we remove the date help text from the "Add new individual" form.
Top part of of the form
![add_new_indi_top](https://user-images.githubusercontent.com/5202996/32042670-0344ecf0-ba41-11e7-9c61-d89d33b829e3.jpg)
Bottom part of the form
![add_new_indi_bottom](https://user-images.githubusercontent.com/5202996/32042768-55818f14-ba41-11e7-82cd-9d92685c648b.jpg)

The admins should be able to select which types of dates are relevant for their tree and we should show only the help text of these date types.

**Comment by fisharebest** [comment]
Already reported in #1346
