### ISSUE TITLE
Wrong help text for individual and family places and restrictions - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1443]
Help links next to place or restricion data take us to the date or name help box instead of a box that explains how to fill places or restrictions.  

**Add individual** on individual page or on family page
We see the Name help data for places and for restrictions

**Edit individual** event data
**Add/Edit family** event data
We see the Date help text for places and for restrictions

**Comment by fisharebest** [comment]
Fixed as part of #1346
