### ISSUE TITLE
Edit person data: Some inputfields too narrow

### ISSUE THREAD

**Issue by marku5** [fisharebest/webtrees#1444]
Latest beta: Person edit form: Fields shall be aligned; here have same width as other elements.
![grafik](https://user-images.githubusercontent.com/5243414/32051272-4b52ef8e-ba54-11e7-8f9a-30d019ac9fa6.png)

**Comment by fisharebest** [comment]
I do not see this.

How do I reproduce the problem?

**Comment by marku5** [comment]
Royal Family demo tree, edit birth or death data of any person
Switch to german (or català) => effect as in screenshot. Other languages work ok.

**Comment by fisharebest** [comment]
The German translation contains some invalid HTML.

`<b>Orte suchen</ b>`

An extra space between `/` and `b`.

I have updated the text on the translation server.  It may take 24 hours before it appears on the demo server.
