### ISSUE TITLE
Config.ini.php

### ISSUE THREAD

**Issue by rrosancrans** [fisharebest/webtrees#1445]
So i found this webtree for geology i downloaded xampp to test the site but it keeps telling me to make sure i configure the config.ini.php now i am rather new to php not realy sure what to do but config.ini.php is pointing to the data folder can anyone assist me on correcting the issue thanks

**Comment by fisharebest** [comment]
When you first start webtrees, the file `data/config.ini.php` will not exist.

webtrees will redirect to the setup wizard.  This will create `data/config.ini.php`.

When the file `data/config.ini.php` exists, webtrees will run normally.

> it keeps telling me to make sure i configure the config.ini.php

What exactly did you do, and what exactly is the *exact* error message that you see?

**Comment by rrosancrans** [comment]
Ill post it tonight im on my way to work

**Comment by rrosancrans** [comment]
so after doing the setup wizard i get 
Warning: parse_ini_file(data/config.ini.php): failed to open stream: No such file or directory in C:\xampp\htdocs\webtrees-master\site-unavailable.php on line 45

**Comment by rrosancrans** [comment]
ok i was able to finally get the config.ini.php to gen
