### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by rrosancrans** [fisharebest/webtrees#1446]
when i upload a fresh webtrees files to my hosting i get this "SQLSTATE[HY000] [2002] No such file or directory" does the hosting not support SQL or do i have to put something in the directory for the SQL to work

and i also downloaded xampp to start a tree n localhost can i just upload the the local files or does have to be a fresh webtrees not setup?

**Comment by fisharebest** [comment]
This error can indicate that you have set the database server to "127.0.0.1" instead of "localhost" (or vice versa).

**Comment by fisharebest** [comment]
NOTE:  the file `data/config.ini.php` simple contains the connection details for your database.

These connection details are different on every webserver.  The settings on your local machine (XAMPP) will be different to the settings on your webhost.

**Comment by rrosancrans** [comment]
Ok thank you i have it working now side question how do i configure "sending emails" page i put in my server user pass port info but when i try "send broadcast message" i get an error

**Comment by fisharebest** [comment]
> how do i configure "sending emails" page

The simplest opiton is to configure an SMTP server.

If your webhost provides one, then they will give you the settings.

Alternatively, just use a GMAIL account.  There are instructions on the page.  Don't forget to enable SMTP ("less secure applications") in your google account.
