### ISSUE TITLE
Zend

### ISSUE THREAD

**Issue by gbon** [fisharebest/webtrees#1450]
After an accidental upgrade of my webtrees-site to 1.7.9 the website rendered in faults. I decided to recopy all files of webtrees 1.4.6 and keeping the mysql-database as is. I saved the data-directory with database-connection. After this the site functioned but with a few errors in the Zend-module. These 3 errors are enclosed below. What can I do to correct them? Thanks in advance!!

Gerrit.

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /home/bonbonbon/domains/bonbonbon.net/public_html/webtrees/includes/functions/functions_date.php on line 62

Deprecated: iconv_set_encoding(): Use of iconv.internal_encoding is deprecated in /home/bonbonbon/domains/bonbonbon.net/public_html/webtrees/library/Zend/Locale/Format.php on line 313

Deprecated: iconv_set_encoding(): Use of iconv.internal_encoding is deprecated in /home/bonbonbon/domains/bonbonbon.net/public_html/webtrees/library/Zend/Locale/Format.php on line 474

**Comment by fisharebest** [comment]
I think you are using an incompatible combination of PHP / webtrees.

You will need to use a newer version of webtrees or an older version of PHP.

You might be able to modify webtrees to ignore these warnings.   In includes/session.php, you could try to change

`error_reporting(E_ALL | E_STRICT);`

to

`error_reporting(E_NONE);`

**Comment by gbon** [comment]
Thanks for your reply Greg! I'll try this!



2017-10-29 20:08 GMT+01:00 Greg Roach <notifications@github.com>:

**Comment by gbon** [comment]
Hi Greg et all,

Most errors have gone, but one. Now the system says: 
Notice: Use of undefined constant E_NONE - assumed 'E_NONE' in /home/bonbonbon/domains/bonbonbon.net/public_html/webtrees/includes/session.php on line 136

Should I declare E_NONE in the header somewhere?

TIA, Gerrit.

**Comment by fisharebest** [comment]
My mistake.  Use `0` instead of `E_NONE`.

**Comment by gbon** [comment]
The 0 solved it! Thanks and greetings from Holland.
