### ISSUE TITLE
Coding style question

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#1453]
What kind of coding style is used for webtrees? Seems not PSR (http://www.php-fig.org/psr/)?

**Comment by fisharebest** [comment]
https://wiki.webtrees.net/en/Coding_Standards

**Comment by fisharebest** [comment]
There is a `.php-cs.php` config file, but it is very out of date.

Mosty, I just use the auto-formatting in PhpStorm.

**Comment by magicsunday** [comment]
Ok thanks

**Comment by fisharebest** [comment]
I'm just updating `.php_cs` now.

I'll push it to the repo later today.
