### ISSUE TITLE
Fatal error generated on non existent module

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#1455]
The following error is generated
`Fatal error: Fisharebest\Webtrees\Module::loadModule(): Failed opening required '<path>\modules_v3/myModule/module.php' (include_path='.;C:\php\pear') in <path>\app\Module.php on line 48`

This is generated when (in the above example) the module 'myModule' is not on the disk but is enabled within the database. Caused when switching branches within Git so maybe not a common situation
Using php 7.1.9

**Comment by fisharebest** [comment]
I'd switched `include` with `require`.

For a non-existant file, the former throws an exception (which we catch), whereas the latter halts with a fatal error.
