### ISSUE TITLE
sending a message in account page

### ISSUE THREAD

**Issue by rrosancrans** [fisharebest/webtrees#1456]
hi guys im having an issue with "My Page" in the messages tab when i click send it doesnt do anything dont load nothing any way to fix in order to send a message to a user thats offline
![screenshot-2017-11-4 my page family tree](https://user-images.githubusercontent.com/33152115/32405028-8b34fec2-c133-11e7-9fdb-4e12c8ed86d2.png)

**Comment by fisharebest** [comment]
I guess webtrees 1.7.9.

Have you set your browser to block popup windows?
Are there any messages in your web browser's error console?

**Comment by rrosancrans** [comment]
yes i get this error message 
index.php?ctype=user&ged=Reader-Rosancrans:6 Uncaught ReferenceError: mesg_window_specs is not defined
    at message (webtrees.js:642)
    at HTMLInputElement.onclick (index.php?ctype=user&ged=Reader-Rosancrans:6)

**Comment by magicsunday** [comment]
This is caused due the removal off the javascript popup windows in webtrees.js:

If I readd the following line, the popup window is opened again:

var mesg_window_specs = 'width=620,height=600,left=75,top=50,resizable=1,scrollbars=1'; // message.php

**Comment by fisharebest** [comment]
All popup windows have been removed.

This is because popup windows do not work on mobile devices.

There is now a "full page" view for sending mail.  We need to modify this code to use it.
