### ISSUE TITLE
Image files slow to load

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1457]
Using Slide show on the home page, if I click on the image it can take from 5-30 seconds to load.  However, if I log on then the image appears in less than a second. Using Chrome 62.0.3202.75 for my testing.  However, FF is the same.

**Comment by fisharebest** [comment]
Is this simply a case that thumbnails are slow the **first** time they are viewed?

Since we generate them on demand, I would expect first-time use of all images to be slow(er).

**Comment by makitso** [comment]
You know, it's only Chrome that does it. It's almost like chrome is intentionally causing the delay, kind of like sound on some video files.

**Comment by makitso** [comment]
OK, gave it another go today to test the latest git with Chrome and a browser cache flush.  If I click on the image in the slideshow block, it waits and waits and times out.  If I clean everything and log in and do the same thing the image appears immediately.

**Comment by fisharebest** [comment]
What settings do you have for watermarks?

Perhaps it is slow for visitors because it must add the watermark?

**Comment by makitso** [comment]
Yes, by removing watermarks from visitors that solved the problem.  However, that begs the question, why are watermarks a problem for Chrome and not the other browsers?

**Comment by wkitty42** [comment]
On 11/24/2017 09:43 AM, Rob Peters wrote:
> Yes, by removing watermarks from visitors that solved the problem. However,
> that begs the question, why are watermarks a problem for Chrome and not the
> other browsers?

is chrome perhaps trying to prefetch the images to make their loading appear 
faster? when it prefetches, it doesn't get anything because the watermark work 
is going on?

**Comment by makitso** [comment]
> is chrome perhaps trying to prefetch the images

Except, my public site is webtrees 2 from a git release around Nov 1, and there is no delay with watermark'ed images.  Something happened since then to cause this problem -- for all browsers on linux and windows.

**Comment by maekclena** [comment]
Currently, images above ~500kb fail to load on demo-dev with some variation of the following message:
```
Fatal error: Maximum execution time of 30 seconds exceeded in /home/webtrees/dev.webtrees.net/demo-dev/vendor/intervention/image/src/Intervention/Image/*.php line *
```
[Example](https://dev.webtrees.net/demo-dev/index.php?route=media-thumbnail&xref=m88&ged=demo&fact_id=a7599fb25915be548be1bd1137b8ed67&w=0&h=0&fit=contain&mark=watermark.png&markh=100h&markw=100w&markalpha=25&or=0&s=82377efdd30a7e40e24e911d7e342e4c)

**Comment by makitso** [comment]
No longer a problem
