### ISSUE TITLE
Individual record 

### ISSUE THREAD

**Issue by rrosancrans** [fisharebest/webtrees#1458]
not really an issue but more of a question
the Individual record under My Account page is grayed out disabled is this where the user would choose their family tree place-holder so they could edit their own info?
![screenshot-2017-11-4 my account family tree](https://user-images.githubusercontent.com/33152115/32411010-763b4ecc-c1a6-11e7-869f-553510de8ad3.png)

and can we create a new block(ie on this day, messages. favorites... ) and if so where could i find the file to create one

**Comment by fisharebest** [comment]
Please, only one issue at a time.

The privacy rules allow a user to see all the information about their own individual record.

If a user could select any individual, they would be able to bypass all privacy rules and view all details of all records.

The administrator can set this in the control panel.

You can add blocks by using the "My pages, customise this page" link at the top of the page.

**Comment by rrosancrans** [comment]
thanks for the info for the new blocks i mean to create a a block thats not listed in the customise this page

**Comment by fisharebest** [comment]
> create a a block thats not listed

You mean create a new, custom, block.

If you are a PHP programmer, then you should be able to base your code on one of the existing blocks.

**Comment by rrosancrans** [comment]
were might one find the code for the existing blocks.

**Comment by fisharebest** [comment]
The blocks (and all other modules) are in `/app/Modules/`
