### ISSUE TITLE
php-cs-fixer

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#1463]
Disclaimer - I probably don't know what I'm talking about!

I've just installed php-cs-fixer and have it working as an external tool within phpstorm. It is using .php_cs in the webtrees root directory for it's config but when I run it I get the following

before
```
		$sortStyle = $this->getBlockSetting($block_id, 'sortStyle', 'alpha');

		?>
		<div class="form-group row">
```
after
```
		$sortStyle = $this->getBlockSetting($block_id, 'sortStyle', 'alpha'); ?>
		<div class="form-group row">
```
i.e. it shifts the php end tag onto the end of the last line of php code and removes the blank line
I've looked through the documentation but can't find a command to change this

**Comment by fisharebest** [comment]
> but can't find a command to change this

I don't think there is one.

PHP-CS-FIXER is a useful tool, but it is far from perfect.

I already found/reported a bug that corrupts the actual code.

Do not submit any changes that it makes without reviewing them first...

BTW - you may have noticed that we're moving to a template system (`resource/views/...`), and this "mixed" template and logic should disappear over time.

**Comment by ddrury** [comment]
OK thanks
