### ISSUE TITLE
RTL - User Latin name with a trailing special character like ) not correct on the User Welcome block - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1467]
In the UserWelcomeModule.php we should see the users name exactly as in LoggedInUsersModule.php

Some of my site users have written their name with () when they registered to my site.

On the Hebrew page I do not see
Lisa Mayer (Smith) שלום
I see
(Lisa Mayer (Smith שלום

**Comment by fisharebest** [comment]
This seems OK on firefox, but not on chrome.

**Comment by melizaa** [comment]
I removed the translated text שלום for Welcome in the Hebrew translation.
Now I see the user is as expected.

**Comment by melizaa** [comment]
I see a similar issue on ltr pages for users who are defined in rtl and who have a special character at the end. There I have not removed the text Welcome or it's translation to the page language.

**Comment by melizaa** [comment]
I have added back the Hebrew translation for Welcome.

**Comment by melizaa** [comment]
Perhaps we should add the dir="auto" to 
public function contactWebmaster()
and
public function contactGedcom()

**Comment by melizaa** [comment]
and also for latestUserFullName()
like for userFullName()
