### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by timmarchant** [fisharebest/webtrees#1468]
Hi

On one of my trees I have this error:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5-M52' for key 'PRIMARY'

I had updated an individual and no cannot access that tree, others seem fine. I searched the database for the entry but couldn't find it. Next steps? Suggestions please>

**Comment by timmarchant** [comment]
Hi

This occurs when I attempt to view the tree (not during an import, so no Gedcom is involved).

i.e. The link /webtrees/index.php?ctype=gedcom&ged=tim-marchant-2017 
redirects to /webtrees/admin_trees_manage.php where the error is displayed below the Tree name.

I have searched in the web interface on the name of the individual I had edited and I can see that the entry is showing as blank - so I assume this record is where the issue lies. However, I don't know which tables are most likely to contain the data which needs repair.

**Comment by fisharebest** [comment]
> The link /webtrees/index.php?ctype=gedcom&ged=tim-marchant-2017
redirects to /webtrees/admin_trees_manage.php

If you start to import a GEDCOM file, you cannot visit any other page until the import is complete.  It does not make sense to browse an incomplete tree, so you will always be redirected back to this page to complete the import.

You need to fix your GEDCOM file (remove the duplicate) and then re-import it.

**Comment by fisharebest** [comment]
> As I said, this did not occur during an import.

You said:

> The link /webtrees/index.php?ctype=gedcom&ged=tim-marchant-2017
redirects to /webtrees/admin_trees_manage.php where the error is displayed below the Tree name.

The only code in webtrees that would redirect to this page is when webtrees detects that there is an incomplete import.  When it reaching this page, it attempts to resume the import.

The only time I have ever seen this error message (and it would be expected here) is when you are importing a GEDCOM file with duplicate IDs.

So, all the evidence suggests that webtrees thinks it is in the middle of importing a GEDCOM file.

Go to your database and look in the table `wt_gedcom`.  Find the `gedcom_id` for this tree.

Next, go to your database and look in the table `wt_gedcom_setting` for entries for with the same `gedcom_id` and a `setting_name='imported'`.

What do you have in `setting_value`?
What value(s) do you see here?

**Comment by fisharebest** [comment]
If you'd like me to help, I'll need some more information to help work out what is happening on your system.

**Comment by UksusoFF** [comment]
@fisharebest can reproduce this error on import with checked option "Keep media objects".
As described here this is probably normal behavior: https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-9/32281-edit-interface-message#65651
But maybe need show something understandably message?
