### ISSUE TITLE
Safari 11.0.1 shows thumbnails for favorites only when reloading page

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1469]
I use Safari 11.0.1 on Mac OS High Sierra for Webtrees (1.7.9). Images are not displayed public for my tree. After logging in, the thumbnails for the person images in the favorites-block are not displayed. See screenshot. After reloading the page it works fine.
Works well with other browsers on MacOS, so I think it's related with Safari. I first noticed this problem after the upgrade from Sierra to High Sierra.

<img width="79" alt="webtrees-images-notshown" src="https://user-images.githubusercontent.com/16715040/32748830-ada4b38a-c8bd-11e7-8ade-7fb08f0de49b.png">

**Comment by fisharebest** [comment]
Is this just a problem with Safari - or do you see the same problem with other browsers?

Do you see this problem on the demo site?

**Comment by fisharebest** [comment]
I can't reproduce this, and the code has been rewritten significantly since the issue was raised.

If you can reproduce the problem with webtrees 2.0, please open a new issue.
