### ISSUE TITLE
box "research tasks" wrong formatted - 2.0.0

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1470]
In latest 2.0.0 build the box "research tasks" is wrong formatted.
See screenshot.

<img width="390" alt="webtrees-research-tasks" src="https://user-images.githubusercontent.com/16715040/32749071-6fb43c34-c8be-11e7-9997-30ba95323e62.png">

**Comment by makitso** [comment]
IMHO, bootstrap seems to be oriented toward mobile devices.  You can add this to colors style.css or the common style.css and it will help a bit.

@media (min-width: 1200px) {
	.container {
		max-width: 95%;
 	}
}
