### ISSUE TITLE
sorting arrows are to near to the text in some cases - 2.0.0

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1471]
In the latest 2.0.0 the sorting arrows are to near to the text / or over the text in some cases.

<img width="186" alt="webtrees-sort" src="https://user-images.githubusercontent.com/16715040/32749146-b2e16478-c8be-11e7-8f4c-341f2483c9bf.png">

**Comment by fisharebest** [comment]
The `datatables-bootstrap` library only supports `bootstrap4.alpha-6`.  We are using `bootstrap4.beta-2`.

I guess this issue will be fixed when this library is updated.
