### ISSUE TITLE
MEDIA FIXUP media 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1472]
I see in MEDIA FIXUP only Media objects of individual I1 of my big GEDCOM.
I do not see the first Media object of I1. This is the Media object that we see in the individual page, in charts, in the branche's list and in reports. 

How will I see Media objects of the other individuals?

I would prefer to see only the first level 1 main media objects of each individual in the FIXUP page.
Should this be an option?

**Comment by fisharebest** [comment]
Perhaps there is an error on the page?
Perhaps there is an error in the webtrees error log?

This page shows *all* level-0 images of *all* individuals.

**Comment by melizaa** [comment]
I see no errors on the page.

There are empty error log files for future.

There are access- and error-log files for tree.

There are  error-log files that it seems contain both production, test and future data..

I see for instance
2017/11/17 12:02:06 [error] 3379#3379: *3143047 open() "/home/amitys/www.amitys.com/test/packages/popper-1.11.0/popper.min.js.map" failed (2: No such file or directory), client: 5.29.205.7, server: www.amitys.com, request: "GET /test/packages/popper-1.11.0/popper.min.js.map HTTP/2.0", host: "www.amitys.com".

**Comment by fisharebest** [comment]
This was fixed.
