### ISSUE TITLE
Shows non highlighted images instead of the grey heads - 2.0.0

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1473]
In the latest 2.0.0 non highlighted images are displayed in the trees or on overview pages. In 1.7.9 here was the grey head visible, if no highlighted images was available.

**Comment by fisharebest** [comment]
webtrees no longer looks at the custom `_PRIM` tag.

We criticise other applications for creating and depending on custom tags.
We should not do this ourselves.

See #1370 for an ongoing discussion on this.
