### ISSUE TITLE
I see error in addmedia - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1477]
When I try to add a media in Manage family trees - Add unlinked records - Media object, I see the error 
/home/amitys/test.amitys.com/addmedia.php:230 Bad $action () in addmedia.php

The link is to addmedia.php?action=showmediaform

I see the form, if I change in addmedia.php line 34
from 
$action      = Filter::post('action');
to
$action = Filter::post('action', null, Filter::get('action'));

**Comment by fisharebest** [comment]
`addmedia.php` has been replaced with a new edit window.

8655ee667c2b46241ee8df824001f8f663b7d61e
