### ISSUE TITLE
Vital records report - html - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1480]
There are unnecessary empty lines between individual data and the line between individuals
![2017-11-16_14-05-26](https://user-images.githubusercontent.com/5202996/32890386-3dc188f6-cad7-11e7-8dc9-c6df1dacfa36.jpg)

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
