### ISSUE TITLE
English page Vital records report - PDF - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1481]
An individual with a Hebrew nick-name causes the following data to be printed adjusted right.
![2017-11-16_14-09-29](https://user-images.githubusercontent.com/5202996/32890579-08af445e-cad8-11e7-97b9-42285e165f31.jpg)

Rubinstein

All the list reports have this issue.

**Comment by melizaa** [comment]
This happens after a person with a Hebrew nick-name

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
