### ISSUE TITLE
Hebrew Sources report - pdf - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1482]
Hebrew nick-names print on Hebrew names
![2017-11-16_14-39-46](https://user-images.githubusercontent.com/5202996/32891683-4376888c-cadc-11e7-89db-15f49e78e84d.jpg)

**Comment by melizaa** [comment]
The Latin nick-name prints to the left of the Latin name

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
