### ISSUE TITLE
English Sources report - pdf - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1483]
A person with a Hebrew name causes the following data to be printed adjusted right.
![2017-11-16_14-44-31](https://user-images.githubusercontent.com/5202996/32891861-f2115930-cadc-11e7-8311-eb00a3705fe4.jpg)

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
