### ISSUE TITLE
Sources report Citation details - records - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1484]
I run a report for a certain source. The Citation details in the report are from the 1st source of the individual, not for the reported source.

Sample source - Helsinki Jewish School 1921-22 - Hirsch Rung - text should be "Lower school class 3"

See attachment of #1483

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
