### ISSUE TITLE
Related individuals - relative_ext_report - html - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1485]
Many of my site individuals are defined with Latin and Hebrew names.

The day of marriage or the year (if only the year is defined), are printed between the spouse's Latin and Hebrew names.
![2017-11-16_15-07-47](https://user-images.githubusercontent.com/5202996/32892808-1b808b80-cae0-11e7-9669-131a37af7685.jpg)

The nickname's trailing "prints in a wrong place.
![2017-11-16_15-10-35](https://user-images.githubusercontent.com/5202996/32892916-6fc41b26-cae0-11e7-8a8d-221ae778f66a.jpg)

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
