### ISSUE TITLE
English Related individuals - relative_ext_report - pdf - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1486]
The names of the person, parents, children, spouses do not print correctly - one on top of the other, on several lines, without spaces between names .
The spouse's and children's titles should be adjusted left.

Data printed with wrong adjustment after a Hebrew nickname

![2017-11-16_15-16-09](https://user-images.githubusercontent.com/5202996/32893149-2282f64c-cae1-11e7-9fea-197bbd0b97fc.jpg)

Compare with the html report

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
