### ISSUE TITLE
Hebrew Related individuals - relative_ext_report - pdf - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1487]
The names of the person, parents, children, spouses do not print correctly - one on top of the other, on several lines, without spaces between names.
The data is printed adjusted left after a child's nickname.

Compare with the html report

![2017-11-16_15-22-13](https://user-images.githubusercontent.com/5202996/32893404-fc761cd0-cae1-11e7-9dc9-a8d29461a4ba.jpg)

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
