### ISSUE TITLE
Hebrew Ancestors report of I659 - html - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1488]
Marriage day or year printed between spouse's Latin and Hebrew name

**Comment by melizaa** [comment]
Same issue in the English LTR HTML report

**Comment by melizaa** [comment]
In the Hebrew report the trailing Latin nickname " should print to the right of the Latin nickname, it prints to the left of the Latin given name.
![2018-10-20_20-03-40](https://user-images.githubusercontent.com/5202996/47258451-f3cf3180-d4a3-11e8-9a00-b0b600aa9925.jpg)

In the English report the trailing Hebrew nickname " should print to the left of the nickname, it prints to the right of the given name.
![2018-10-20_20-10-29](https://user-images.githubusercontent.com/5202996/47258474-6b9d5c00-d4a4-11e8-9984-ebb04dc6e5f5.jpg)

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
