### ISSUE TITLE
English Ancestors report of I659 - pdf - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1489]
Names one on top of the other, birth data wrong for people with Hebrew names and nick-names.
Report adjusted left after a Hebrew nick-name.
The report title is cut and we do not see the Hebrew nick-name

![2017-11-16_15-55-51](https://user-images.githubusercontent.com/5202996/32894873-d50e09aa-cae6-11e7-8e2d-47989b65bf06.jpg)

**Comment by melizaa** [comment]
The names do no longer print one on the other.

In the title and for individuals, the Hebrew nickname should print to the left of the Hebrew given-name and surname. It prints now to the right.

We miss a space between the individual source numbers and the text "was born." It seem that it is printed to the left of the source numbers instead of to the right of them.

We see a space between the marriage year and the full stop.

![2018-10-20_19-05-31](https://user-images.githubusercontent.com/5202996/47257882-591f2480-d49c-11e8-81dc-0922302f9168.jpg)

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
