### ISSUE TITLE
Hebrew Ancestors report of I659 - pdf - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1490]
Spaces and special end characters (., ") in wrong places, texts on text. Odd line breaks
I see the Hebrew word for He (הוא) in odd places to the right of the country of a previous Latin place.
the burial data of individual 1 prints below the title Generation 2. 

Marriage day/year of 1. between spouse's Latin and Hebrew names.

![2017-11-16_16-01-32](https://user-images.githubusercontent.com/5202996/32895097-97f3fd4e-cae7-11e7-95dc-ca40988f16d7.jpg)

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
