### ISSUE TITLE
RTL Place hierarchy - places print outside the column and bullets have a right margin - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1491]
RTL Place hierarchy - bullets print far from the right border and texts pass the left border

In inspect of the rtl page I see an orange border to the right and to the left.
In the ltr pages I see in ul the margin only to the right, not to the left

I changed in _common/style.css "#place_hierarchy ul { margin-right" to "[dir=ltr] #place_hierarchy ul {"
This removed the right margin.

Texts pass still the left border.
![2017-11-18_10-13-57](https://user-images.githubusercontent.com/5202996/32978354-43137efe-cc49-11e7-90fb-74c7b803fcec.jpg)

Is this a similar issue as #1405

**Comment by fisharebest** [comment]
There is an updated bootstrap-rtl libary.  Fixed in 8910e2b9560aa9767ec21191dc203385b6946d6d ???

**Comment by melizaa** [comment]
This is not OK. Please reopen the issue.

**Comment by fisharebest** [comment]
The new place-hierarchy module does not use bullet points.
