### ISSUE TITLE
Branches list should print the names of both spouses in the same language - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1493]
Now the couple's names are in different languages. The spouse's name is in the page language (if it is defined).
![2017-11-18_10-33-09](https://user-images.githubusercontent.com/5202996/32978527-8dc424c8-cc4c-11e7-8d13-9dcda6d5ee1a.jpg)
![2017-11-18_10-34-59](https://user-images.githubusercontent.com/5202996/32978528-94440d5e-cc4c-11e7-8463-2f293fc689bb.jpg)

In order to at least print the Sosa numbers of the spouses in the same format, I have added dir="auto" after rel="nofollow" to printing of the $sosa in BranchesController.php.

**Comment by melizaa** [comment]
With 2 Latin names on the rtl page the 2 Sosa numbers are in different directions.
![2017-11-18_12-07-35](https://user-images.githubusercontent.com/5202996/32979195-4d8cc2a4-cc59-11e7-8628-8abf1e389fe5.jpg)

**Comment by melizaa** [comment]
I soundex search a rtl name on the rtl page, The results show the Latin name of the person and the rtl name of the spouse.
![2018-03-23_14-28-05](https://user-images.githubusercontent.com/5202996/37827035-dafc25ee-2ea6-11e8-9574-65e9315510d0.jpg)

 I should see the rtl soundex name also for the person like what I see in not soundex search. 
![2018-03-23_14-57-02](https://user-images.githubusercontent.com/5202996/37827948-7d818720-2eaa-11e8-8244-dbbd93977704.jpg)

**Comment by fisharebest** [comment]
We only match the names/scripts of spouses when we generate the name of a family record.

Here, we are showing individuals.

Also, when an individual has two spouses, we would need to match it to two difference spouses.  If we did this, we would show two different names for the same individual, which would be confusing.

Individual + Spouse 1 (latin only)
Individual + Spouse 2 (hebrew only)

I think we should leave this as it is.

**Comment by melizaa** [comment]
I still think that we should return both spouse's names in the branches list in the language of the searched name if this name exists on the site.
