### ISSUE TITLE
Individual and Related families pdf reports - 2.0.0 & demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1494]
English page 
Hebtrew nicknames cause data to print on other data and to continue in the middle of the next row and a box to be too long.
![2017-11-18_10-56-06](https://user-images.githubusercontent.com/5202996/32978689-ed94df48-cc4f-11e7-9b25-4bea0f9ab1f0.jpg)

Hebrew page
Parent's and siblings' data prints on other data
The trailing ( of birth and death data prints as )
Father, Mother, Husband, Wife, Son, Daughter and their Hebrew name print without a space between them. Also the Latin birth place and the word Death of relatives print without a space.
![2017-11-18_10-52-33](https://user-images.githubusercontent.com/5202996/32978687-e6e6a244-cc4f-11e7-88bb-0c4c130615ec.jpg)
![2017-11-18_10-58-20](https://user-images.githubusercontent.com/5202996/32978668-a33249ae-cc4f-11e7-9470-13927cae98b9.jpg)

See my site I269.

**Comment by melizaa** [comment]
I added today a nickname and a Hebrew name to Sarah Ferguson in demo-dev.
I look at the Hebrew Individual PDF report of Prince Andrew.
1. The picture is printed under the data
2. The family members' data ends by ). It should end by (.
3. The spouse's Latin and Hebrew nicknames print on top of each other
4. The nickname '' or "" are not printed.
5. The Latin source data prints without a space between the source title and the source details and we should see the details on the ltr pages to the right of the title, like we see in the HTML report.

![image](https://user-images.githubusercontent.com/5202996/76700240-5854e700-66be-11ea-95ca-f272344fdb71.png)

**Comment by melizaa** [comment]
In the English PDF report I see the Hebrew nickname without a space to the right of the name. I should see it to the left of the name.

![image](https://user-images.githubusercontent.com/5202996/76700482-be426e00-66c0-11ea-8202-bfa2dea42480.png)

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
