### ISSUE TITLE
Pedigree report - 2.0.0 and demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1495]
Long names are shortened in a way that makes the individuals unrecognizible
Parts of names print on the next or previous row's data - see i1
![2017-11-18_11-30-52](https://user-images.githubusercontent.com/5202996/32978952-c5e75b10-cc54-11e7-8341-5a92ac854474.jpg)
![2017-11-18_11-34-59](https://user-images.githubusercontent.com/5202996/32978962-dd135a1e-cc54-11e7-9916-75f5d5c82b94.jpg)

Hebrew pdf report - I do not see the names of all the individuals who have a Hebrew name - 2, 3, 7, 14 and also a child of the root person - see I269
![2017-11-18_11-40-05](https://user-images.githubusercontent.com/5202996/32978997-9a6a8ef2-cc55-11e7-83fb-e6f503a4e751.jpg)

The html report shows the names
![2017-11-18_11-41-47](https://user-images.githubusercontent.com/5202996/32978994-939d2f30-cc55-11e7-8e85-a6df3789e204.jpg)

**Comment by fisharebest** [comment]
There are three separate issues here:

* [ ] Long names converted to initial letters
* [ ] Long names overlap b/m/d details
* [ ] Latin names not shown on Hebrew pages

**Comment by melizaa** [comment]
The 3rd point is that some longer Hebrew names do not show on Hebrew pages.
