### ISSUE TITLE
Modification Bloc Html not possible

### ISSUE THREAD

**Issue by Fa10175** [fisharebest/webtrees#1497]
After install files from 19-11
they are a mix on one a my tree (default)
on my page some blocs disapear same page link of the tree.
I correct it by a new selection of bloc.
but the Html bock is not modifiy

**Comment by fisharebest** [comment]
Is it possible to reproduce the problem?

I have not seen any blocks disappear.

**Comment by Fa10175** [comment]
I do not know how the blocks disappeared. But the fact that the html block is no longer editable is important because I will have to modify this block because the area to be displayed is smaller in 2.0
