### ISSUE TITLE
Birth report -2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1498]
I run the report on my test site on Jerusalem

Hebrew - html
on line 2, the trailing Latin nickname "prints to the left of the Latin name instead of to the right of the nickname 

Hebrew - pdf
Hebrew nicknames print on Hebrew names or next to them without a space. 
The "-s that should print before and after the nickname, print as "" between the Hebrew and the Latin names
The Latin nicknames print to the left of the names - should print to the right
Unnecessary new lines start in the middle of lines.

English - pdf
The direction of the data starts to be wrong after the 1st person with a nickname - Rachela
Hebrew nicknames print on Hebrew names.
We see the nickname '' to the left of the Hebrew name

**Comment by melizaa** [comment]
English - pdf - Hebrew nicknames print to the right of the Hebrew name

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
