### ISSUE TITLE
Cemeteries report - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1499]
I run the report on my test site for Jerusalem

English - html
'' of the end of Hebrew nickname prints to the right of the Hebrew name 

English - pdf
Hebrew nickname causes data to print in wrong sequence 
3 last individuals are missing in the report

Hebrew -html
'' of the end of a Latin nickname prints to the left of the Latin name 

Hebrew pdf
Hebrew nickname prints on the Hebrew name
Menachem Nuchem* prints without a space between the names

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
