### ISSUE TITLE
Family report pdf - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1501]
Hebrew nicknames print on Hebrew names. 
The "-s that should print before and after the nickname, print as "" between the Hebrew and the Latin 
names and between names and (Birth - Death)

Spouse's father's and Mother's Latin and Hebrew names printed without a space 

Data printed on next fact line under it's data

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
