### ISSUE TITLE
RTL Texts - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1504]
Texts on rtl pages are again adjusted left - titles, menus, blocks, facts, charts, selection boxes, …

**Comment by fisharebest** [comment]
The bootstrap-rtl-library does this:

https://github.com/MahdiMajidzadeh/bootstrap-v4-rtl/issues/8

**Comment by melizaa** [comment]
Is the
.dropdown-menu
OK?

**Comment by fisharebest** [comment]
While we wait for a working bootstrap-rtl library, I have manually created a bootstrap-rtl.css file using https://cssjanus.github.io

I guess there is also some ltr/rtl logic in bootstrap.js.

I hope the CSS file will "mostly" work.

**Comment by melizaa** [comment]
A great improvement!

I see some issues, like the top menu placements in all the themes, except in webtrees and xenea. 
I need still to continue with my testing of the reports and the admin pages.
