### ISSUE TITLE
Index page charts - vertical lines - demo-dev & 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1505]
I see again too short vertical lines in the index page pedigree, descendants, hourglass charts

**Comment by makitso** [comment]
The inline style="height'xx" is no longer being generated on the img tag.

**Comment by makitso** [comment]
Looks like the setupJavascript code in the HourglassControler.php is not running for these scripts.

**Comment by fisharebest** [comment]
We currently use the controller to inject javascript into the responses.

This is the wrong way to do it, so I am moving this to the views.

The embedded charts use the "old" system, whereas the home page uses the "new" system.

This problem should fix itself as soon as the charts move to the new style of controllers.
