### ISSUE TITLE
Texts translated to Hebrew that include Latin letters - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1506]
Hebrew module administration - Module name CKEditor tm printed with <"
CKEditor™ is translated in Hebrew to <span dir="ltr">CKEditor™</span>. How should we translate it to print the TM to the right also on the Hebrew page?

I have included <span dir=''ltr> also at least to "Hello %s…", "Hello %sThe folder can be specified in full (e.g. /hom…<br>Thank you for your registration. ...", "The media file %s does not exist.", "The thumbnail file %s does not exist.", "... <b>197?</b> for all events from 1970 to 1979 or <b>16??</b> for all events from 1600 to 1699 ...", "We will now send a confirmation email to the address <b>%s</b>.  ...", "You may enter a URL, beginning with “http://”. I have not now tested if they still work as before 2.0.0.

**Comment by fisharebest** [comment]
> Hebrew module administration - Module name CKEditor tm printed with <"

This is caused by the unexpected HTML markup in the translation:

```
msgid "CKEditor™"
msgstr "<span dir=\"ltr\">CKEditor™</span>"
```

> How should we translate it to print the TM to the right also on the Hebrew page?

Add `dir="auto"` in the code.  Done.

**Comment by fisharebest** [comment]
I see that for the Google™ Maps mdoule, you have simply moved the ™ to the start of the word.

This may be a better solution.

**Comment by melizaa** [comment]
Greg, should the Hebrew language file be updated and the HTML markups removed? I doubt that I will be able to do it before miid-January. Meliza

**Comment by fisharebest** [comment]
Leave it with me.  I will try out a few options, and update the language file if necessary
