### ISSUE TITLE
Occupations report - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1507]
Same issues as other list reports.

**Comment by magicsunday** [comment]
It would be much easier to understand the errors if you would please provide appropriate links in all your issues (you may use: https://dev.webtrees.net/demo-dev/index.php?route=tree-page&ged=demo). So no one has to look around for the right page.

**Comment by melizaa** [comment]
Thanks for your comment.

My test site is https://www.amitys.com/test/index.php
I have Latin and Hebrew data on the site.

I use demo-dev only to test issues that do not require Hebrew, admin rights or other features like names with an apostrophe or ()-s .

Meliza

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
