### ISSUE TITLE
Descendants report in pdf - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1509]
See 4 of I1.

English and Hebrew 
Place Be'er Ya'akov prints as Be&apos;er Ya&apos;akov

Hebrew
End of sentence . printed to the right on Hebrew page.
Spaces in wrong places. No space between date and place or between 2 sentances, for instance, 4 was born and 4 married.
Nicknames on data  - 4's in-laws. 
Nicknames cause wrong text sequences and data printing at the middle of a new line

**Comment by fisharebest** [comment]
The HTML-escaped apostrophe was fixed earlier.

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
