### ISSUE TITLE
Mails with an apostrophe print &apos; - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1510]
Pending changes mail site title's apostrophe wrong. My site title is "Meliza's Genealogy" 

Apostrophe in the mail text is wrong.

Similar to #1478

**Comment by fisharebest** [comment]
I created a tree with special characters in the title.

This is the email I receive for pending notifications.

The special characters look OK.

![screen shot 2017-11-22 at 16 05 28](https://user-images.githubusercontent.com/2306088/33137127-fe2357f2-cf9e-11e7-986c-4b8d6ef176d5.png)

What exactly do you see?

**Comment by melizaa** [comment]
I sent a mail.

**Comment by fisharebest** [comment]
Fixed by #1478
