### ISSUE TITLE
dev - Media Firewall - IE and Edge browser display white

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1513]
All browsers tested center image with black background.  However, on Win10, using either Edge or IE, the image is left justified on the screen with a white background.

**Comment by fisharebest** [comment]
It's not clear especially what you mean here - especially as I don't have easy access to MS Windows.
Can you provide steps to reproduce and/or screen shots?

**Comment by makitso** [comment]
Edge on Win10
![image](https://user-images.githubusercontent.com/5147603/33519516-42f1d5c0-d765-11e7-9299-30a7bef33776.png)

Chrome on Win10
![image](https://user-images.githubusercontent.com/5147603/33519518-6afe90f8-d765-11e7-933f-d88ccb647cc6.png)

**Comment by makitso** [comment]
The background being black or white is no big deal.  However, on Windows the picture is pined to the top left corner not centered.

**Comment by fisharebest** [comment]
This looks like the "colorbox" viewer isn't activating.  Without it, the browser falls back to displaying the raw .JPEG file, and this looks like the default way the browser displays images.

Any errors in the Javascript error console?

**Comment by makitso** [comment]
Nope:
![image](https://user-images.githubusercontent.com/5147603/33519638-1cd3a686-d768-11e7-92bf-a49579b6abbf.png)

**Comment by fisharebest** [comment]
The URL shows that you are just looking at the raw JPEG image (not the viewer).

This is the fallback behaviour if the photobox plugin fails to load/activate.

Effectively, we have

```
<a onclick="activate colorbox"><img src="..."></a>
```

You are just seeing the raw image - hence colorbox is not activating.

Is this for every image - or just ones in certain places.

**Comment by makitso** [comment]
Looks like it only happens on the Slide Show on the home page.  Media objects and individual images are ok.

**Comment by fisharebest** [comment]
I think, perhaps, that `activate_colorbox()` isn't being called.
