### ISSUE TITLE
dev - SQL queries not updated

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1514]
Latest git, SQL queries value is not being updated.

**Comment by fisharebest** [comment]
You mean the XML comments at the end of the page?

I've replaced our custom logging with maximebf/php-debugbar

To see it, you need to install the PHP dev dependencies using:

`php composer.php install --dev`.

You should now see a debugging toolbar.  I've just installed this on the demo-dev server.

It also includes info for AJAX requests, so on the home page, you'll see info for the blocks as well.

Not all pages/requests are currently linked to this system.

It provides a useful replacement to `var_dump()`, as debug data can be sent directly to the toolbar.

**Comment by ddrury** [comment]
Can I suggest a .gitignore file is put in the vendor subdirectory to exclude from git all the extra stuff installed by the above command

**Comment by fisharebest** [comment]
We should add a `.gitignore` for *everything* under `/vendor`....

**Comment by fisharebest** [comment]
....and we will do once 2.0 is released.
