### ISSUE TITLE
Resources/views

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1516]
I am using a few 'views' inside my themes because in some cases I prefer a slightly different layout.

Recently the views I've added stopped working. Found out this is caused by the fact they are no longer loaded since the lines that supposed to redirect to the themes specific views are commented out. May I assume this is just temporary?

**Comment by fisharebest** [comment]
Yes, I plan to keep this feature.

I also expect that many of the functions from AbstractTheme can be replaced with views.

**Comment by fisharebest** [comment]
FYI, the long-term plan is to migrate the code to Laravel.
You will notice that the folder/code structure is change to match the laravel structure.

Laravel allows third-party packages to [override views](https://laravel.com/docs/5.5/packages#views)

I need to choose a system that will be compatible with the laravel approach.

**Comment by JustCarmen** [comment]
Thanks, good to know.

**Comment by fisharebest** [comment]
The reason they are commented out is that I want to be certain that it will still be possible for a custom view to load a core view.

For example, if the `views/core.php` contains:

```<p>Hello world</p>```

and `custom-views/core.php` wants to center this text, it would use

```<div class="center"><?= view('core.js') ?></div>```

However, this would just result in recursion.  The custom view cannot load the core view.

I think we can fix this using a namespace for the view name.  e.g.

```<div class="center"><?= view('::core.js') ?></div>```

But I haven't had the time to test this.
