### ISSUE TITLE
2.0 - Renumber Family Tree generates error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1518]
/var/www/app/Statement.php:82 SQLSTATE[HY000]: General error: 1100 Table 'wt_site_setting' was not locked with LOCK TABLES #0 /app/Statement.php:82 PDOException("SQLSTATE[HY000]: General error: 1100 Table 'wt_site_setting' was not locked with LOCK TABLES") #1 /app/Tree.php:665 execute([array]) #2 /admin_trees_renumber.php:82 getNewXref('INDI')

**Comment by makitso** [comment]
After the fix one of the trees was renumbered.  However, there is no action available on the Renumber page.  So, using the link ontrol panel/Manage family trees/Merge family trees and again selecting the two trees resulted in this error:

var/www/app/Statement.php:82 SQLSTATE[HY000]: General error: 1100 Table 'wt_media_file' was not locked with LOCK TABLES #0 /app/Statement.php:82 PDOException("SQLSTATE[HY000]: General error: 1100 Table 'wt_media_file' was not locked with LOCK TABLES") #1 /admin_trees_merge.php:149 execute([array])

**Comment by fisharebest** [comment]
`admin_trees_merge.php:149` does not reference `wt_media_file`, which is locked on line 71.

Quick sanity check - are you sure you have the latest code, no modifications, etc.?

**Comment by makitso** [comment]
> are you sure you have the latest code

Yes, meld says match between git and my dev environment.

Reran test.  
Selected family tree to merge into another.  
Display: The two family trees have 168 records which use the same “XREF”.
You must renumber the records in one of the trees before you can merge them.
- Renumber family tree — Leonard
- Renumber family tree — Peters Genealogy
Selected Leonard and the system did the renumbering of Leonard.
I then selected Merge family trees from the Control Panel Family trees dropdown
Re selected the two trees to merge and received this error

/var/www/app/Statement.php:82 SQLSTATE[HY000]: General error: 1100 Table 'wt_media_file' was not locked with LOCK TABLES #0 /app/Statement.php:82 PDOException("SQLSTATE[HY000]: General error: 1100 Table 'wt_media_file' was not locked with LOCK TABLES") #1 /admin_trees_merge.php:149 execute([array])

**Comment by fisharebest** [comment]
The first error was in *renumbering* trees.
The second error was in *merging* trees.

I didn't notice this, and assumed we were still talking about renumbering.

Fixed...
