### ISSUE TITLE
dev - Slideshow on home page broken

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1522]
![image](https://user-images.githubusercontent.com/5147603/33519478-9814bf82-d764-11e7-9a17-d436901c5f4d.png)

**Comment by fisharebest** [comment]
I think this was fixed about 15 minutes ago....

Can you check again?

**Comment by makitso** [comment]
It works on my dev system but not the webtrees dev demo -- which I suspect has not been updated yet.

**Comment by fisharebest** [comment]
> I suspect has not been updated yet.

Quite likely.  I've been pushing changes for a couple of hours, and the demo server gets updated hourly.
