### ISSUE TITLE
PHP 7.2 - relationship to me - no longer working because of deprecated functions

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1529]
With PHP 7.2 the relationship to me is no longer working:

each() function is deprecated:

`/var/www/vhosts/weiland24.de/httpdocs/webtrees/includes/session.php:193 /var/www/vhosts/weiland24.de/httpdocs/webtrees/vendor/fisharebest/algorithm/src/Dijkstra.php:84 The each() function is deprecated. This message will be suppressed on further calls #0 unknown:unknown ErrorException("/var/www/vhosts/weiland24.de/httpdocs/webtrees/vendor/fisharebest/algorithm/src/Dijkstra.php:84 The each() function is deprecated. This message will be suppressed on further calls") #1 /vendor/fisharebest/algorithm/src/Dijkstra.php:84 each([array]) #2 /vendor/fisharebest/algorithm/src/Dijkstra.php:130 extractPaths('I88') #3 /app/Controller/RelationshipController.php:67 shortestPaths('I111', 'I88') #4 /relationship.php:56 calculateRelationships([Individual I111@1], [Individual I88@1], 0, false)`

**Comment by fisharebest** [comment]
This has already been fixed.

See the package https://github.com/fisharebest/algorithm

The fix will be included in webtrees 2.0.

**Comment by johnds123** [comment]
Well it doesn't seem to work for me on 1.7.10. All I get is a page without any relationship information but with the normal Webtrees header and footer.

**Comment by fisharebest** [comment]
@johnds123 - this error report was that the `each()` function is deprecated in PHP7.2

The code has been rewriten to avoid this function.  I guess you have a different problem...

Can you provide any other info?  e.g. error message from either the webtrees error log or the apache error log?  If so, create a new issue with all the details.  Thanks.
