### ISSUE TITLE
Login to webtrees home-page - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1538]
I show news on my site's homepage.
I want all my users to see the news when they login.

I have users who do not login from my webtrees home page.

Now my users are moved to their My Page after they login.
I see that other sites want their users to see their My Page after login.

Please make the page that users will see after they login an option that the administrators can define.

**Comment by fisharebest** [comment]
> Now my users are moved to their My Page after they login.

Only if they were previously on the home page.
This means they would already have seen your home page and the news.

The only way a user can avoid visiting the home page is to

a) bookmark another page (e.g. their individual page)
b) visit that page
c) log in (and remain on that page).

**Comment by melizaa** [comment]
Greg,

 

I have users who have bookmarked the sign-in page.

They can then login from the sign-in page and they will not see the news. 

 

Meliza
