### ISSUE TITLE
I do not see pictures in individual boxes - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1540]
I do not see all the pictures for instance in the family tab and in chart individual boxes.
I work on a slow internet connection.
See family tab of test/individual.php?pid=I299&ged=Gedcom.ged
![2017-12-14_09-35-54](https://user-images.githubusercontent.com/5202996/33997412-4f714438-e0b2-11e7-9517-7514a7dcf6dd.jpg)

I see the pictures on my production site.

**Comment by fisharebest** [comment]
I see the images on this page.
![screen shot 2017-12-14 at 14 43 04](https://user-images.githubusercontent.com/2306088/33997694-213a5688-e0dd-11e7-89cd-6ab41d8b6fe2.png)

Which browser?

**Comment by melizaa** [comment]
Chrome

I think it has to with the slow internet connection.

**Comment by melizaa** [comment]
Now I have a fast connection to the web and I see the pictures.

Not all my users have fast connections.

**Comment by fisharebest** [comment]
I don't think there is anything we can do about this.
