### ISSUE TITLE
Home page modules edit error

### ISSUE THREAD

**Issue by curtisdelicata** [fisharebest/webtrees#1541]
Error on bottom of page when editing boxes. This is using the minimal theme.

/home/curtis/public_html/app/Module/RecentChangesModule.php:163 Return value of Fisharebest\Webtrees\Module\RecentChangesModule::configureBlock() must be an instance of Fisharebest\Webtrees\Module\void, none returned #0 /block_edit.php:84 TypeError("Return value of Fisharebest\Webtrees\Module\RecentChangesModule::configureBlock() must be an instance of Fisharebest\Webtrees\Module\void, none returned")

**Comment by fisharebest** [comment]
`: void` is PHP 7.1 so we can't use it.

**Comment by curtisdelicata** [comment]
ok. I don't remember the error before so it must of happened when I swapped servers to 7.0 instead of 7.1

**Comment by curtisdelicata** [comment]
Tested on PHP 7.1 and there are no errors shown.

**Comment by fisharebest** [comment]
We need to support 7.0
