### ISSUE TITLE
Text reports descendants

### ISSUE THREAD

**Issue by curtisdelicata** [fisharebest/webtrees#1542]
Can there be different text reports? d'Aboville System is the one I'm most interested for descendants

https://en.wikipedia.org/wiki/Genealogical_numbering_systems

**Comment by curtisdelicata** [comment]
I found this.

https://github.com/BlasiusSecundus/descendant_numbering/tree/development

**Comment by fisharebest** [comment]
@curtisdelicata - can you clarify exactly what you want?

The descendants chart shows d'aboville numbers.
