### ISSUE TITLE
Import custom thumbnails from webtrees version 1 - table is empty

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1545]
When clicking on the link I get an empty table.

Could that be because my media is organized in subfolders? And hence in wt-1 my thumbs were automatically divided into subfolders too.

**Comment by melizaa** [comment]
My media is also organized in subfolders.
I have the same issue in the test system.

In future I see 6 pictures of one family branch.

Where should I see the thumbs?

**Comment by fisharebest** [comment]
I was looking for

`.../media/subfolder/thumbs/photo.jpeg`

instead of

`.../media/thumbs/subfolder/photo.jpeg`

**Comment by melizaa** [comment]
I do not yet see the media and thumb files even with the latest code.

I have for most pictures
.../media/thumbs/subfolder1/subfolder2/photo.jpeg

**Comment by fisharebest** [comment]
@melizaa - I see the problem.  Your `media` folder is a symbolic link.

By default, PHP does not follow symbolic links when scanning directories.

I can change this.
