### ISSUE TITLE
Relationships chart scroll bar does not move the Link to charts icon does not move - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1548]
When I use the Relationships chart scroll bar, the chart individual box Link to charts icons remain in their original places. The scroll bar was added in "Missing scrollbar in wide charts - 2.0.0 (#1539)"
![2017-12-16_08-07-05](https://user-images.githubusercontent.com/5202996/34072226-2e1e91e6-e238-11e7-9717-4f06e79e0120.jpg)

In the Hourglass chart the icons move as expected with the chart when I use the scroll bar.

**Comment by melizaa** [comment]
For instance test/relationship.php?ged=Gedcom.ged&pid1=I1&pid2=I486&ancestors=0&recursion=2

**Comment by fisharebest** [comment]
This will probably be fixed when we replace the "hover" menu in the individual boxes with a bootstrap dropdown.

**Comment by melizaa** [comment]
I see the same behavior of the submenu icons on a not full screen window in the person boxes of the Ancestors booklet with show cousins selected, the Descendants booklet and in the family book.

The pedigree chart and the hourglass charts are OK.

**Comment by makitso** [comment]
Does this issue still exist?

**Comment by fisharebest** [comment]
It still exists for me.  Create a relationship chart wider than the screen (or reduce the screen width!), and scroll.

I was going to replace this drowndown menu with a bootstrap menu, which should fix the problem.

**Comment by melizaa** [comment]
I see also still the issue.

**Comment by fisharebest** [comment]
The menus have now been replaced with bootstrap drop-downs, and the problem appears fixed.
