### ISSUE TITLE
Restrict user to individual record

### ISSUE THREAD

**Issue by curtisdelicata** [fisharebest/webtrees#1550]
The search does not find anyone so I cannot link a new user?

**Comment by fisharebest** [comment]
Works for me.
![screen shot 2017-12-18 at 16 33 35](https://user-images.githubusercontent.com/2306088/34116713-47d643f6-e411-11e7-9390-a1ab22e1aca0.png)

Do you actually have any users in the tree?

Are there any errors in the webtrees error log?

Are there any errors in the webserver error log?

Do you know how to check the XHR responses in the chrome/firefox developer tools and see if there are any errors there?

**Comment by curtisdelicata** [comment]
Yes there are individuals in the tree.

Apache log  - [Mon Dec 18 17:36:40.928037 2017] [core:error] [pid 15337] [client 148.252.128.54:24686] End of script output before headers: action.php, referer: /admin_users.php?action=edit&user_id=4

/public_html/app/Statement.php:82 SQLSTATE[HY000]: General error: 3 Error writing file '/tmp/MYVVngr7' (Errcode: 28 - No space left on device)
#0 /app/Statement.php:82 PDOException("SQLSTATE[HY000]: General error: 3 Error writing file '/tmp/MYVVngr7' (Errcode: 28 - No space left on device)")
#1 /app/Select2.php:224 execute([array])
#2 /action.php:284 individualSearch([Tree], 0, '')

I'll check but seeing the above makes me think it is the mounting and not webtrees. (the / mount is 78% full but no /tmp) the virtual server was set to higher than the usage of the website but the above errors.

Turned out the database I was using, I forgot was on a different virtual account.

Now it loads but is all privatised so I cannot pick the right one?

**Comment by curtisdelicata** [comment]
... ..., -

I see hundreds of them which must be living ones when I search? but it isn't showing any deceased either.

**Comment by fisharebest** [comment]
> /public_html/app/Statement.php:82 SQLSTATE[HY000]: General error: 3 Error writing file '/tmp/MYVVngr7' (Errcode: 28 - No space left on device)

This is your problem.

MySQL needs disk space to process queries., and your disk is full.

**Comment by fisharebest** [comment]
> I see hundreds of them which must be living ones when I search

You are logged in as an administrator, so privacy filtering does not apply.

I guess that these individual records do not actually contain a name, date of birth or date of death.

The individual list should be able to confirm this, as you can use it to select individuals with an unknown surname.

**Comment by curtisdelicata** [comment]
It is possible that it is showing corrupted data first? Is it showing any spouses that got imported with no name?

Does it need time to find the full 25,000 records to cache? Isn't it cached already?

**Comment by curtisdelicata** [comment]
I've got no gedcom errors and don't remember any no names though before I imported. I let it scroll to the bottom and it showed no names at all.

This is PHP 7.1 if it matters. I'll test PHP 7.0

**Comment by fisharebest** [comment]
> It is possible that it is showing corrupted data first?

Individuals with no name sort first.

You are typing your search terms into the box, aren't you?

**Comment by curtisdelicata** [comment]
Yes I am typing search terms.

**Comment by curtisdelicata** [comment]
I created a test tree and it shows Joe Bloggs as an option. Even after typing a name?

How can I debug why it it does not filter?

**Comment by curtisdelicata** [comment]
I changed select2 how much it is limiting by and it shows more people now just does not filter.

**Comment by fisharebest** [comment]
You did not answer my comment about disk space.

The queries used by the search/autocomplete can require large temporary tables.  If you have no disk space, then these will fail.

It would explain why you can do simple activities (create new trees), but not complex ones (queries).

You said "/ is 78% full" and "there is no moutpoint for /tmp".

78% of what?  The `/` filesystem can often be tiny.

**Comment by curtisdelicata** [comment]
2.2GB available.

Virtualhost set to unlimited quota.

**Comment by curtisdelicata** [comment]
No apache errors or webtrees errors.

**Comment by curtisdelicata** [comment]
I'm reading https://select2.org/searching now and will let you know if I find a fix

**Comment by curtisdelicata** [comment]
Tested on fresh clone with same database.

Same issues

**Comment by curtisdelicata** [comment]
I got it working by modifying the line. Not sure if this is a good idea but it let me quickly set one of the users restricted.

                                                <?= FunctionsEdit::formControlIndividual(Individual::getInstance($tree->getUserPreference($user, 'gedcomid'), $tree), ['id' => 'gedcomid' .
 $tree->getTreeId(), 'name' => 'gedcomid' . $tree->getTreeId() ]) ?>

**Comment by curtisdelicata** [comment]
Any update on if the change I done was correct?

**Comment by fisharebest** [comment]
> Any update on if the change I done was correct?

I'm not entirely clear what you actually did - but I'm guessing you disabled the auto-complete / search on this field.

So, you are simply ingoring the code that is triggering the error.

You originally reported an error message that MySQL could not write to `/tmp` because the partition was full.

I asked about this.  You replied "2.2GB available out of 9.7GB" which does not tell me that you addressed the problem.  It is quite possible for there to be lots of free space on the **disk** but not enough space in the **partition**.

So, on the basis of information provided, your problem is still that your database server is failing to run large queries because it is getting "disk full" errors from the operating system when it tries to create temporary files in /tmp..

**Comment by curtisdelicata** [comment]
I understand about partition, thank you for checking.

It is fine on space. /var/lib/mysql is on the main / partition.

The database is 305M on the /var/lib/mysql

I removed part of the array. Changing the line to read as it does on the previous comment.

**Comment by wkitty42** [comment]
On 12/22/2017 02:36 PM, Curtis Delicata wrote:
> I understand about partition, thank you for checking.
> 
> It is fine on space.


you keep pointing to this but the mysql error log you posted specifically said 
that it was out of drive space for your search... it is easily possible for a 
search to require at least as drive space as the database, itself... maybe more 
depending on the indexes needed/created...

one way to test this is to put the line back like you had it and try the query 
again... if there really is enough drive space available in /tmp, then the query 
should work this time...


-- 
  NOTE: No off-list assistance is given without prior approval.
        *Please keep mailing list traffic on the list unless*
        *a signed and pre-paid contract is in effect with us.*

**Comment by curtisdelicata** [comment]
I was getting the SQL disk space error for lots of different things when it was full. I think I confused things by this.

Now it is it 3GB available and no errors at all. It is searching still as it finds the records if they match name I enter.

This is a small VPS. Does it really need more than 3GB to search a 305MB database? Is there an estimated ratio? I might upgrade the VPS anyway.

**Comment by wkitty42** [comment]
On 12/22/2017 02:54 PM, Curtis Delicata wrote:
> I was getting the SQL disk space error for lots of different things when it was 
> full. I think I confused things by this.


:thumbsup:


> Now it is it 3GB available and no errors at all. It is searching still as it 
> finds the records if they match name I enter.


excellent!


> This is a small VPS. Does it really need more than 3GB to search a 305MB 
> database? Is there an estimated ratio? I might upgrade the VPS anyway.


i don't know your database or your searches but consider if you have ten folks 
on your system at once... all doing some sort of searches... consider that if 
all their searches resulted in a temp database of 305MB, that's 10*305 MB your 
system might need on disk... considering that these temp result databases are in 
/tmp... just to toss some brain work out there ;)


-- 
  NOTE: No off-list assistance is given without prior approval.
        *Please keep mailing list traffic on the list unless*
        *a signed and pre-paid contract is in effect with us.*

**Comment by fisharebest** [comment]
> Is there an estimated ratio?

It depends on the size of your database, the distribution of data, etc.
It may be possible to calculate the requirements, but I don't know how.

MySQL needs to join several tables to create a search query and store the intermediate results somewhere.  For complex queries, this can be large.

Glad you got it working
