### ISSUE TITLE
Dev - Undefined offset

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1553]
I was adding some media to this individuals wife and child and now on the individual page I get a 
/var/www/includes/session.php:151 /var/www/individual.php:145 Undefined offset: 0 #0 /individual.php:145 ErrorException("/var/www/individual.php:145 Undefined offset: 0") 

Browser error TypeError: $(...).sortable is not a function

I checked the gedcom and there are no errors.  

0 @I0217@ INDI
1 NAME Gijs John /Peters/
2 GIVN Gijs John
2 NICK Guy
2 SURN Peters
1 SEX M
1 BIRT
2 DATE 28 JUL 1870
2 PLAC Het Loo, Gelderland, Netherlands
1 DEAT
2 DATE 6 FEB 1959
2 PLAC Grass Valley, Nevada Co, California, USA
2 CAUS Heart attack
1 FAMC @F001@
1 FAMS @F143@
1 OBJE @M69@
1 NOTE Dutch pronunciation of Gjis is Gish.
2 CONT The 1910 census lists Guy as living in Chester Township, Dodge Co, occupation as farmer.
2 CONT Guy will move to Twin Falls  summer of 1910.
2 CONT Guy was the builder who build most of Amsterdam.
2 CONT Guy and Louise moved to CA before 1914.
2 CONT 1920 census lists Guy living in Oakland township, occupation carpenter.
2 CONT 1930 census lists Guy as living at San Mateo, renting next door to Delmar and Dorothy Peters, occupation carpenter.
2 CONT After 1930 lived at 1154 College Avenue, Palo Alto.
1 BURI
2 CEME Greenwood Memorial Gardens
2 PLAC Grass Valley, Nevada Co, California, USA
1 SOUR @S20@
2 DATA
3 TEXT Family pictures received from Linda Peters.
1 CHAN
2 DATE 08 OCT 2015
3 TIME 20:06:53
2 _WT_USER petersra
1 OBJE @M386@

**Comment by makitso** [comment]
Ok, the problem was the media object for this individual, added a long time ago, had a .mpg extension instead of a .jpg extension.  I fixed this in the gedcom and the problem went away

**Comment by makitso** [comment]
Not a bug but an unfriendly error.

**Comment by fisharebest** [comment]
We shouldn't display JS/PHP errors - whatever data is found.

**Comment by fisharebest** [comment]
I can't manage to reproduce it.  I tried creating a media object `photo.mpg`.
