### ISSUE TITLE
Google maps

### ISSUE THREAD

**Issue by curtisdelicata** [fisharebest/webtrees#1554]
I turned on Google Maps and enabled the API key.

It finds locations but does not save to database.

Is it also supposed to find locations for all places?

Entered places. Clicked searched globally (or locally, both worked). It displayed the place but didn't update the latitude and longitude displayed.

**Comment by curtisdelicata** [comment]
There was an error about missing flags directory but creating this still doesn't save the latitude and longitude found.

**Comment by fisharebest** [comment]
> Entered places. Clicked searched globally (or locally, both worked). It displayed the place but didn't update the latitude and longitude displayed.

The search will display one or more markers on the map.  Click the one you want to select the co-ordinates.

**Comment by curtisdelicata** [comment]
I clicked on the selected one and it opened a dialog then redirected to home page after clicking ok button.

However if I click a few pixels away it successfully saved. Thank you.
