### ISSUE TITLE
I see part of top icon texts in clouds and colors after I login - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1557]
Before I login
![cloudsbef2017-12-23_17-15-50](https://user-images.githubusercontent.com/5202996/34323591-5d175d84-e805-11e7-89c9-43a1d7ee0a5f.jpg)

After I login
![clouds2017-12-23_17-14-50](https://user-images.githubusercontent.com/5202996/34323592-6f867a68-e805-11e7-88d0-c5347f7eed04.jpg)

and
![colors2017-12-23_17-14-11](https://user-images.githubusercontent.com/5202996/34323593-790aa014-e805-11e7-9f38-bc6c21f440e6.jpg)

This happens both in the test and the future test systems, at least in chrome and in edge.

**Comment by fisharebest** [comment]
This appears to be caused by the fancy-tree-view module.
If you disable the module, the problem disappears.
