### ISSUE TITLE
Note markups do no longer work - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1559]
I use for instance in Shared Note N172
#Russian Military
and
####Military Units - work in progress (by Meliza)

Now I see the #-s.

Also for instance media notes have the same issue.
"####In the picture" in M8041
See S296

**Comment by fisharebest** [comment]
Do you have a space after the `#`s ?

In webtrees 2.0.0, we changed to a new markdown library, which is very strict about following the markdown specification.

The old library may have allowed headings without spaces.  The official standard requires them

http://spec.commonmark.org/0.27/#atx-heading

**Comment by melizaa** [comment]
Thanks! That solves the issue.
