### ISSUE TITLE
getLifeSpan

### ISSUE THREAD

**Issue by curtisdelicata** [fisharebest/webtrees#1560]
/public_html/app/Controller/IndividualController.php:54 Call to undefined method Fisharebest\Webtrees\Family::getLifeSpan() #0 /individual.php:33 Error("Call to undefined method Fisharebest\Webtrees\Family::getLifeSpan()") 

Tested on an user that is restricted to manager  - not sure if that affects anything. I think it was also because of a same sex marriage created by mistake.

**Comment by fisharebest** [comment]
Same-sex relationships work fine in webtrees.

The error message suggests that you've passed the ID of a family record to the individual page.

Were you following a link from another page in webtrees?  If so, can you provide more details.

If you generated this link yourself, then perhaps we need to trap this and provide a more helpful error message.

**Comment by curtisdelicata** [comment]
It was when saving a new record.

I only posted this as grep couldn't find the function in any place.

This may be caused by changes to the code I made for clean urls. I thought I had it working for individual.php

**Comment by curtisdelicata** [comment]
Sorry, to clarify I meant. I added a same sex relationship to an existing relationship. It showed as two marriages. I understand that the code seems to work fine.

**Comment by curtisdelicata** [comment]
Fresh install does not have this error. I must of been redirecting to individual/ instead of family/
