### ISSUE TITLE
How can I delete from the server a media file? - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1563]
The file is not linked.

**Comment by fisharebest** [comment]
Control panel -> Manage media -> Unused files

You should see a "delete" link.

**Comment by melizaa** [comment]
I see the option for unused files.

What about a media object file that was created, in Manage family trees > Add unlinked media object, but not linked? I see that I can delete it in the mediaviewer.

**Comment by melizaa** [comment]
I do not see how it can be deleted on the admin pages.

**Comment by melizaa** [comment]
Sorry, I see that it can be deleted using the top Edit icon.
