### ISSUE TITLE
Approve user and it wipes password - 2.0.0

### ISSUE THREAD

**Issue by curtisdelicata** [fisharebest/webtrees#1564]
When you approve a user it changes the password and they can't login it appears?

**Comment by fisharebest** [comment]
I've never seen this.

> it appears?

You don't sound certain?  Are you able to reproduce this?

**Comment by curtisdelicata** [comment]
It happened to every new registration.

They registered, approved their email. I set their account to approved but then it says password incorrect. They reset their password and it lets them login.

**Comment by wkitty42** [comment]
On 12/26/2017 05:14 AM, Curtis Delicata wrote:
> It happened to every new registration.
> 
> They registered, approved their email. I set their account to approved but then 
> it says password incorrect. They reset their password and it lets them login.


1. do you have your browser saving form data and autofilling it?
2. is there a password field on the screen where the account is set to approved?

if i were a betting man, i'd bet the answer to both questions is "yes" which 
means that your browser is changing their password to yours when you save the 
page with their "approved" status...


-- 
  NOTE: No off-list assistance is given without prior approval.
        *Please keep mailing list traffic on the list unless*
        *a signed and pre-paid contract is in effect with us.*

**Comment by curtisdelicata** [comment]
My administrative password is saved on the site but only auto fills when I'm editing cdelicata

Maybe the browser is doing it

**Comment by wkitty42** [comment]
@curtisdelicata you either missed my post or misread it... i did say that my thought was the browser was doing it from it's autofill form data :smiley_cat: 

the real question is if it is your browser doing it when you set the user's account to approved, what password is it putting in if not yours used on the same site in the same forms?

**Comment by curtisdelicata** [comment]
Sorry. I meant that I was agreeing with you that the browser could be changing the password.

It doesn't show any data as auto filled though, just blank and a green tick icon on password boxes.

**Comment by wkitty42** [comment]
ahhh... ok... if the browser isn't autofilling it, it shouldn't be changing it... sounds like something else is going on... good thing i'm not a betting man :laughing: 

too bad there's no easy way to see what the passwords get changed to... i mean, easy as in looking at the raw database... if we're salting, even the same password would be different in what we can see...

anyway, i'm out... it was an idea that has bitten us in the past when managing user accounts on various forums...

**Comment by fisharebest** [comment]
> if the browser isn't autofilling it, it shouldn't be changing it

I think the point is that it is setting **your** password for the other user.

This should be easily testable.  Approve them and see if you can log in to their account with your password.

**Comment by wkitty42** [comment]
On 12/26/2017 03:25 PM, Greg Roach wrote:
>     if the browser isn't autofilling it, it shouldn't be changing it
> 
> I think the point is that it is setting *your* password for the other user.


that is what i was originally saying...


> This should be easily testable. Approve them and see if you can log in to their 
> account with your password.


exactly... the only reason i wrote the above was because the OP said there was 
no autofilling going on so maybe i wasn't clear or something??? :shrug:


-- 
  NOTE: No off-list assistance is given without prior approval.
        *Please keep mailing list traffic on the list unless*
        *a signed and pre-paid contract is in effect with us.*

**Comment by fisharebest** [comment]
I've added some markup (which is not supported by all browsers) which tells the browser not to auto-fill password fields for other user accounts.

If, as we suspect, your browser is doing this, then this change is about all we can do.

**Comment by curtisdelicata** [comment]
Thank you. I will test.

**Comment by curtisdelicata** [comment]
Works great. Thank you again.
