### ISSUE TITLE
Relationship chart individual 2 - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1567]
In the relationship chart, searching for Individual 2 does not work

**Comment by melizaa** [comment]
I can neither replace the default root person in the charts and reports.

**Comment by melizaa** [comment]
Same issue when I create a story

**Comment by fisharebest** [comment]
All the "select2" inputs seem to have broken.

**Comment by fisharebest** [comment]
This broke in 27c4cda0cb98970e86f55c22a8248833b6cf40d9 - which is where we changed the way we load our javascript files.

**Comment by fisharebest** [comment]
There is a problem with the latest version of the select2 library.  So, I have downgraded to the last one that worked.
