### ISSUE TITLE
Place hierarchy place names print on the left column border - rtl - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1569]
In rtl, the place hierarchy place bullets are too far from the column right border. 
Place names print on the left box border.
![2018-01-05_11-23-25](https://user-images.githubusercontent.com/5202996/34624735-2c33d570-f20b-11e7-88dc-1fd8ab97aa15.jpg)

**Comment by fisharebest** [comment]
The bullets have been removed - to provide more space on small screens.
