### ISSUE TITLE
The admin modules column-widths are wrong - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1570]
In the admin modules (Menus, Tabs, Blocks, etc.) Description and Access level columns are too narrow and the 1st column is too wide.

![2018-01-05_16-37-31](https://user-images.githubusercontent.com/5202996/34634260-18262d4a-f237-11e7-8f59-4708c6ab357d.jpg)

**Comment by makitso** [comment]
Interesting, FF 57.0.4 displays correctly and Chrome 63.0.3239.132 does not.

**Comment by makitso** [comment]
There is an HTML error in module-components.php line 15, second class statement.  Not sure what the intent was.

<table class="table table-bordered" class="row">

**Comment by fisharebest** [comment]
> FF 57.0.4 displays correctly and Chrome 63.0.3239.132 does not

I use FF, which is why I couldn't see the problem.

**Comment by makitso** [comment]
There is an HTML error in module-components.php line 15, second class statement. Not sure what the intent was.

<table class="table table-bordered" class="row">
