### ISSUE TITLE
RTL Top 10 given name block table sizes - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1572]
In the rtl Top 10 given-name blocks the male and female tables have different sizes. This does not look good on the Right section blocks, where the female and male data prints one above the other.

![2018-01-05_19-31-58](https://user-images.githubusercontent.com/5202996/34636099-2a0cbb7e-f24f-11e7-9f49-6c24eb75895c.jpg)

**Comment by fisharebest** [comment]
The layout of these has been improved.  On narrow screens (and on the right-hand side), the two tables are centered vertically.  Otherwise they are centered horizontally.
