### ISSUE TITLE
The text "first" at the bottom of lists wrong in some languages - 2.0.0 and before

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1574]
At least in the lists and in the admin_media list the bottom text "first" is gramatically incorrect in Finnish and Hebrew. Where is the text defined?

We print - ensimmäisellä    Should print - ensimmäinen     
We print - ראשונה   Should print - ראשון

**Comment by fisharebest** [comment]
> Where is the text defined?

https://translate.webtrees.net/translate/webtrees/webtrees/fi/?q=first&search=exact&source=on&target=on&type=all&ignored=False

https://translate.webtrees.net/translate/webtrees/webtrees/he/?q=first&search=exact&source=on&target=on&type=all&ignored=False

**Comment by melizaa** [comment]
The text is correct in the webtrees language files.

I do not see the language file text, even after I uploaded the new media files and cleaned the webtrees cache.

**Comment by melizaa** [comment]
This text has not been updated for a long time. I see the same wrong texts with my pre 2.0.0 code.

**Comment by fisharebest** [comment]
If the text is correct in the .PO files, but you are seeing the wrong text on screen, then perhaps your .MO files are outdated?

**Comment by melizaa** [comment]
Yes, the text is correct in the .po files.
And the downloaded .mo files include the new texts.

But I keep seeing the wrong translations for 'first'.

I cannot find 'ensimmäisellä' in the webtrees files on my client machine that I use to update my server site. 

I have cleaned the cache both using webtrees and using Filezilla.
I have created .mo files using POEDIT.

I continue to get the wrong translation fort this text both in my test and in my future test sites.
I added some debugging to see what translate("first") would print. It printed the wrong ensimmäisellä.

I see that new language files have been created today in data/cache/.

I see the same wrong text when I look at the test site on my smartphone.

I removed the fi language file and the fi cache file from the test system.
I did no longer see Finnish among the site files.
I added the fi language back to the test language folder.
I see again Finnish/Suomi and I see the wrong text ensimmäisellä.

The Finnish production language file was created 25/2/2017.
On 18.6.2017 I see for first - ensimmäinen.
On 14.2.2017, 13.2.2017 I do not see first
On  11.2.2017 I see ensimmäinen ...

What else can I do? Where could this ensimmäisellä come from?
Do any of our vendor files define the text on their servers?

**Comment by melizaa** [comment]
I have compared the language/fi.po file to the data/cache/language-fi-cache.php files of my test and future test systems.
The fi.po has 
twice 
msgid "first"
msgstr "ensimmäinen"
and for instance the new
msgid "Add a media file"
msgstr "Lisää mediatiedosto"

The cache files have
once
  'first' => 'Ensimmäisellä',
and the new
'Add a media file' => 'Lisää mediatiedosto',

Why do I keep seeing the wrong uppercase translation for 'first'?

Greg, please send me the fi.mo file that you use in demo-dev.
Let's see if that will solve this issue.

**Comment by melizaa** [comment]
I figured this out finally.
The wrong text for 'first' comes in app/I18N.php from the FancyTreeview module.

I do not think that we should use in webtrees texts defined in language directories of our modules.

**Comment by melizaa** [comment]
Actually we should use longer, unique English texts.
In FanveTreeview we speak of "The first time he married".
In admin_trees_config we speak of "Show the first/last n parts of a place name."
In the lists we speak of the "first page".
The words "first"should have different translations.

**Comment by melizaa** [comment]
I see only one translation in the cache file.

**Comment by magicsunday** [comment]
I created a new fi.mo file from the fi.po using poedit (https://poedit.net/), after copying the updated mo-file to the language folder and switching to "suomi", the word "first" is correctly translated to "ensimmäinen".

After installing the modules "fancy_treeview" (https://github.com/JustCarmen/fancy_treeview) and generating the mo-file for fi.po the translation in the admin module is indeed again "ensimmäisellä".

**Comment by fisharebest** [comment]
The [fancy tree view module](https://github.com/JustCarmen/fancy_treeview) is for webtrees 1 only.

So this issue won't affect webtrees 2.

In any case, the module is constructing sentences by inserting words.

e.g. `The %s time, he married %s`, where the first placeholder is `first`, `second`, `third`, etc.

Constructing sentences like this is always problematic.

The module should define texts as
The first time, he married %s`
The second time, he married %s`
The third time, he married %s`
etc.
