### ISSUE TITLE
Make language files build broke - no .bak file

### ISSUE THREAD

**Issue by curtisdelicata** [fisharebest/webtrees#1575]
When I run make I get:

rm -Rf build language/webtrees.pot
find language -name "*.mo" -not -path "language/en-US.mo" -delete
# Modify the .XML report files so that xgettext can scan them
find modules*/ -name "*.xml" -exec cp -p {} {}.bak \;
sed -i .bak -e 's~\(I18N::[^)]*[)]\)~<?= \1 ?>~g' modules*/*/*.xml
sed: can't read .bak: No such file or directory
Makefile:58: recipe for target 'language/webtrees.pot' failed
make: *** [language/webtrees.pot] Error 2

If I run, touch .bak first to create an empty file then make works fine it builds the language files.

**Comment by fisharebest** [comment]
`sed` has several different versions.

In some, the `-i` option requires a manadatory extension to be used for temporary files.

In others, the `-i` option does not take a parameter.

I guess you have a different version of `sed` to me.  Just remove the `.bak`

**Comment by curtisdelicata** [comment]
Thank you for prompt response.
