### ISSUE TITLE
Workflow for custom themes and modules

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1576]
Until now I was using bootstrap - sass - grunt for developing my themes in wt 2.0. I had a package.json file and node_modules (npm) in the root of webtrees to use it across multiple themes and modules. 

But recently this is changed. Webtrees also uses npm now and webpack in stead of grunt. The problem is I lost my custom package.json file (which got overwritten by the webtrees version) . So I know I need to move things to the theme/modules folders. But it bothers me to have multiple instances of the node_modules folder which would blow up the size of webtrees (on my local machine).

I was using grunt to compile the sass files and fulfilling some other automated tasks. Moving to webpack doesn't seem necessary but then I still need my own version of the package.json file and I will end up with multiple instances of the node_modules folder (is there a better way???). If I move to webpack I also need my own version of webpack-mix.js inside each custom themes folder, because I don't want to compile the default version of bootstrap but I still need the other vendor.css files. 
Before I simply removed the default bootstrap file from the styles array (leaving the other files as is), but that is not possible anymore since they are all compiled into one css file.

I am using a custom set of bootstrap variables (variables.scss) to easily change things like colors etc. and compile my own version with grunt and sass (see: [https://getbootstrap.com/docs/4.0/getting-started/theming/](https://getbootstrap.com/docs/4.0/getting-started/theming/)

So I am a bit lost. What should be the best workflow for developing custom themes and modules according to webtrees with the Laravel workflow in mind?

**Comment by fisharebest** [comment]
Hi Carmen,

A good question.  I have little experience with these Javascript build tools, so I am open to suggestions.

> What should be the best workflow for developing custom themes and modules according to webtrees with the Laravel workflow in mind?

Laravel packages would be completely independent.  They would have their own `package.json` file.  Building the `.css/.js` files for the core application would be separate from building them for the package.  So, you would have two copies of `node_modules`, etc.

Two related thoughts

1) I still want to combine themes and modules.

2) I wonder if all the theme functions can be replaced with custom views? (see #1516).

**Comment by JustCarmen** [comment]
> I have little experience with these Javascript build tools

Me either :)

> I still want to combine themes and modules.

Themes and modules needs a different approach I think. A theme is used for changing layout, while a module is used for changing functionality. Wouldn't combining them make things just more complex?

> I wonder if all the theme functions can be replaced with custom views? 

Mostly yes. But a custom theme still needs a place to hold the assets and a configuration or theme file I think

There are some theme packages for Laravel that might come in handy. This one looks promising: 
https://github.com/karlomikus/theme

**Comment by fisharebest** [comment]
Issue #2120 replaces this one.
