### ISSUE TITLE
Re-ordering media/families/children does not work

### ISSUE THREAD

**Issue by jorgenvvv** [fisharebest/webtrees#1577]
When trying to re-order media/families/children on the demo server then there is an error in javascript console:

```javascript
Uncaught ReferenceError: Sortable is not defined
    at edit_interface.php?action=reorder-media&ged=Sugupuu&xref=I12:formatted:334
```
[https://dev.webtrees.net/demo-dev/edit_interface.php?action=reorder-media&ged=demo&xref=i1](https://dev.webtrees.net/demo-dev/edit_interface.php?action=reorder-media&ged=demo&xref=i1)

**Comment by fisharebest** [comment]
Still need to convert edit_interface.php to use views to use the sortablejs library.
