### ISSUE TITLE
Bootstrap datetimepicker

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1580]
For your information:

https://tempusdominus.github.io/bootstrap-4/

This is the successor of https://github.com/Eonasdan/bootstrap-datetimepicker

**Comment by fisharebest** [comment]
Thanks.  I'll look at this.

**Comment by fisharebest** [comment]
Now that modern browsers support `<input type="date" min="..." max="...>`, I am not sure we need this library at all.

**Comment by fisharebest** [comment]
We are only using this for the changes log and the webtrees log.

I have replaced these with HTML5 `<input type="date">` fields.

The `datetimepicker` is nicer on desktop views.
However, the native input is nicer on mobile devices.
