### ISSUE TITLE
Relationship to me - route changes

### ISSUE THREAD

**Issue by curtisdelicata** [fisharebest/webtrees#1587]
When the route changes happened the related to me doesn't auto calculate based on the last viewed individual like it used to do?

**Comment by fisharebest** [comment]
This affects all the header / menu items.

There are some other changes I need to make before I can fix this one.

**Comment by curtisdelicata** [comment]
Thank you for reply.

**Comment by melizaa** [comment]
Is this why I do not see any rlationship reports. The program just runs and runs. Also in demo-dev.

**Comment by fisharebest** [comment]
> The program just runs and runs.

That's a different issue - which I've just fixed.

**Comment by fisharebest** [comment]
This is a duplicate of #1608
