### ISSUE TITLE
rtl indi page - edit dropdown menu next to the name should print as a mirror to the ltr pages - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1598]
The individual name edit dropdown menu should print as a mirror to the ltr pages, more to the right of the title 'button'.
![2018-01-27_18-54-56](https://user-images.githubusercontent.com/5202996/35474191-a137304e-0393-11e8-95f6-e191b0fd27bb.jpg)

Also the last rtl dropdown menu text is cut in a similar way to the rtl texts of other drop down menus.

**Comment by melizaa** [comment]
See #1400

**Comment by fisharebest** [comment]
This appears to be fixed in the latest code, which uses the mirrored bootstrap4 files
