### ISSUE TITLE
Dev - Arrow down take you to family.

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1599]
If you click on the right arrow, it should take you to family 29.  Instead you go to the home page.

![image](https://user-images.githubusercontent.com/5147603/35475509-eb9e1666-035c-11e8-8bff-78be39ca26eb.png)

**Comment by makitso** [comment]
Get this error in the logs when selecting the arrow
Error: Class 'Fisharebest\Webtrees\Functions\FunctionsDB' not found in file /app/Module/OnThisDayModule.php on line 120
Stack trace:
  1. Error->() /app/Module/OnThisDayModule.php:120
  2. Fisharebest\Webtrees\Module\OnThisDayModule->getBlock() /app/Http/Controllers/HomePageController.php:261
  3. Fisharebest\Webtrees\Http\Controllers\HomePageController->treePageBlock() /index.php:92
  4. call_user_func() /index.php:92
  5. Fisharebest\Webtrees\{closure}() /index.php:95
  6. call_user_func() /index.php:95

**Comment by fisharebest** [comment]
The second error would appear to be unrelated.

There's nothing obviously wrong here (works for me!).  The error suggests perhaps you are missing the FunctionsDB file/class.

Can you double-check you have all the latest files from github and create a new issue if you can reproduce this.  Thanks.
