### ISSUE TITLE
dev - admin/Website Logs not working

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1601]
I have 833 rows in wt_log, the oldest entry is 2017-10-26 and the newest is 2017-01-27

I want to delete all rows so I enter 2017-10-21 into the From field.  If I put the cursor into the To  field the Form date reverts back to todays date.

I want to delete all rows so I enter 2017-10-21 into the From field and then select search and no rows are selected.

I blank out the From field and then select search and 883  rows are selected.  If I then hit the delete no rows are deleted.  

I blank out the From field and then select search and 883  rows are selected.  If I clear the from field and then select delete all 883 rows are deleted.

**Comment by fisharebest** [comment]
We need to update the date-time-picker (see #1580), so will look at this issue then.
