### ISSUE TITLE
Descendants chart - List - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1604]
2 marriage dates should print on a row under another (like in the Ancestors report) - now they print on the same row.

Descendants
![descendants_2018-02-08_10-22-40](https://user-images.githubusercontent.com/5202996/35962519-67a71256-0cba-11e8-9cd5-b855ac47a7ff.jpg)

Ancestors
![ancestors_2018-02-08_10-23-53](https://user-images.githubusercontent.com/5202996/35962531-72d79bd2-0cba-11e8-9a7c-abf78b00bdbe.jpg)

**Comment by makitso** [comment]
I can't reproduce this with the data I have.  Can you provide a link un/pw if applicable?

**Comment by fisharebest** [comment]
If we show the marriage(s) on the same line as the [+] then it is always shown.

If we show the marraige(s) underneath, on separate lines, then they will only be shown when we expand the [+]

Perhaps we should show them above the [+] ?

**Comment by makitso** [comment]
Greg,  looks like when a person has two marriages to the same person, e.g. one a civil marriage and one a religious?? that the condition happens.

![image](https://user-images.githubusercontent.com/5147603/36030330-fcc8c862-0d63-11e8-8372-626c8f29d691.png)

**Comment by melizaa** [comment]
Looks good

**Comment by fisharebest** [comment]
The ancestors and descendants charts have been rewritten.

Multiple marriages (and divorces) are now shown in one line.
