### ISSUE TITLE
Stats - totals counts inconsistent for placelist.php using Googlemaps

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#1610]
Easiest way to demonstrate: on demo - latest beta. Lists  - Place hierarchy.
At top level click on icon for Scotland.
Popup show 5 individual & 2 families. Now Select Scotland to display its children and click on each of the icons in turn.
Aberdeen returns 0 individual, 1 Family
Angus returns 5 individual, 0 Family
Edinburgh returns 0 individual, 1 Family
Inveresk returns 1 individual, 0 Family
Total therefore come to 6 individuals & 2 families which doesn't match Scotland's totals. On my data I get significant differences in some cases
I can see a reason why the parent level can have a higher count than the sum of it's children - A fact may be assigned to the parent so won't appear in the sum of the children, but I can't see a reason for the children to total more than the parent

**Comment by fisharebest** [comment]
Presumably your new code fixes this.
If not, open a new issue.
