### ISSUE TITLE
Dev - Report throws exception error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1611]
Family, Individuals and Pedigree reports using the display defaults produce this error.  Git and dev are equal.  However,  I can't reproduce this on the webtrees demo machine so it must be data dependent.  If I select an individual then there is no error.

ErrorException: /app/Report/ReportParserGenerate.php:618 A non-numeric value encountered in file /includes/session.php on line 127
Stack trace:
  1. ErrorException->() /includes/session.php:127

**Comment by makitso** [comment]
It appears that it is phone version dependent.  My device system is running 7.1.1 and my prod system, that I can't reproduce the error on is 7.0.27.

**Comment by fisharebest** [comment]
Thanks.  My dev system is currently 7.2, so I'll install 7.1.1 and see what happens.

**Comment by fisharebest** [comment]
> so it must be data dependent

> ReportParserGenerate.php:618 A non-numeric value encountered 

Lines 617-618 are

```
$temp      = explode(' ', trim($tgedrec));
$level     = $temp[0] + 1;
```

This suggests that the first field in a GEDCOM line is not a numeric string.  e.g. "2DATE" instead of "2 DATE".

Are you still able to reproduce this error?
Are you able to add any debug here?

**Comment by makitso** [comment]
Well, I tried three different trees, with the same results.  I looked at the raw gedcom file and there are no 2DATE entries.  However, if you select the Individual report and do not select anyone then what gedcom record is it looking at?  On my prod system the report is generated but with no content. So, what is the contents of $tgedrec?

**Comment by fisharebest** [comment]
> using the display defaults produce this error

Maybe I misunderstood.  Due to #1608, the report options do not include a default individual.

Are you submitting the report *without* choosing an individual?

**Comment by fisharebest** [comment]
Yes - I can reproduce it now.

This bug will disappear as soon as #1608 is fixed.
