### ISSUE TITLE
Too much space needed for individual and home pages (2.0)

### ISSUE THREAD

**Issue by HelmutL** [fisharebest/webtrees#1613]
individual pages and "My Page" wastes too much space by larger font and large empty left and right margins. This implies that you have to to more scrolling and don't have an easy overview.

As an example attach screenshots of webtrees 1.7.9 and 2.0, showing the same data (it was imported from the same GEDCOM file, same system, same settings in webtrees).

![facts_2_2 0](https://user-images.githubusercontent.com/17042607/36353841-df04113c-14cb-11e8-82fc-b03fff8e66b1.jpg)
![facts_2_1 7 9](https://user-images.githubusercontent.com/17042607/36353842-df1eebe2-14cb-11e8-9990-009169c499be.jpg)
![facts_1_2 0](https://user-images.githubusercontent.com/17042607/36353843-df36c0f0-14cb-11e8-98a0-b80abd41fe1d.jpg)
![facts_1_1 7 9](https://user-images.githubusercontent.com/17042607/36353844-df544ce2-14cb-11e8-94c5-3c3b22b36c9f.jpg)
![mypage_2 0](https://user-images.githubusercontent.com/17042607/36353845-df6e47f0-14cb-11e8-963c-20f6d619f1ec.jpg)
![mypage_1 7 9](https://user-images.githubusercontent.com/17042607/36353846-df9b42be-14cb-11e8-8639-3f3f1865ab35.jpg)

**Comment by fisharebest** [comment]
The pages in 1.7 also have lots of space - but in the *middle* of the page.

Long lines are difficult to read.

If you want webtrees to completely fill the page, you can do it using the control panel.

Modules -> CSS and JS -> head

```
<style>
.container { max-width: 100% }
</style>
```
