### ISSUE TITLE
Catch encoding errors during import

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#1617]
A GEDCOM file that contains invalid UTF8 sequences will cause an error such as

```
SQLSTATE[HY000]: General error: 1366 Incorrect string value:
```

Can we catch this and give a more helpful error message?

**Comment by fisharebest** [comment]
The fix for #2265 will show the GEDCOM record being processed, which should provide enough info.

**Comment by sridharb1** [comment]
Hi,

I am moving from PGV 4.3 to webtrees.

I see that the v2 doesn't have the migration wizard. Ok, I switched to the latest of the 1.7 branch.

I run into this error, but it doesn't show any detail as is mentioned above.

What I get is the following:

SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xB0 50' ...' for column 'i_gedcom' at row 1

Could you please help?

Thanks,
Sridhar

**Comment by fisharebest** [comment]
> I run into this error

The error means that you data claims to be encoded using UTF-8 and it contains a byte-sequence that is not valid UTF-8.

> but it doesn't show any detail as is mentioned above.

That is because the fix was added to the 2.0 code, and you are using 1.7

One way to find this is to use an advanced text edit.

In `vim`, you could:

* enable hex mode, by pressing `[ESCAPE]` and then typing `:%!xxd`
* search for this character by typing `\b0`

Alternatively:
* create a temporary webtrees 2 installation
* use it to import the GEDCOM file
* find the error(s) and fix it in PhpGedView
* run the import wizard with webtrees 1.7
* upgrade webtrees 1.7 to webtrees 2.0

**Comment by sridharb1** [comment]
Thank you for the prompt response.

I tried your alternate method. However, the gedcom imports successfully into a v2 installation without errors.

I guess, I have to look at \b0 and see what could be causing it to fail in v1.7

**Comment by fisharebest** [comment]
If it imported OK into webtres, try importing the same file back into PGV?

I've not looked at the PGV code for many years, but I seem to recall some sort of conversion happens on export/import, so that may have cleaned up the problem for you.

**Comment by sridharb1** [comment]
I looked for all the \b0 and I found four instances of the degree sign and changed them to lowercase o.

I ran the import wizard and it had the same error as above. I cannot find any other b0 at the beginning or end of a 4-character block.

**Comment by sridharb1** [comment]
Sorry, but I am a little stuck in the sense that I have only php7 and thus cannot use PGV.

**Comment by fisharebest** [comment]
Well, you have the GEDCOM file (and presumably a backup of the database).

You could:

* delete all the rows from the pgv_individuals / pgv_families / pgv_sources / pgv_media / pgv_other tables.
* run the import wizard with webtrees 1.7
* upgrade to webtrees 2.0
* import the GEDCCOM file

This should migrate all your user accounts and setting, and also keep the genealogy data.

**Comment by sridharb1** [comment]
Thank you. This worked.

I need to migrate the media. I will look at the documentation to see how this can be done.
