### ISSUE TITLE
Document Page Size defaults to A4 on Reports

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1620]
Any way to set Page Size to Letter for US English sites?

**Comment by fisharebest** [comment]
The page size parameter is coded the same as other report parameters - so the default is hard-coded into the report.XML.

The [localisation library](https://github.com/fisharebest/localization) includes support for default paper sizes, so we know to use Letter for en-US.

I think we'll need to refactor the page size out of the report.xml, and into the report engine.  After all, it only applies to PDF.
