### ISSUE TITLE
Size of dropdown boxes (2.0.0)

### ISSUE THREAD

**Issue by HelmutL** [fisharebest/webtrees#1623]
The width of several dropdown boxes (e.g. adding media, sources etc. to facts) is too small.

![addmedia](https://user-images.githubusercontent.com/17042607/36413724-ecef79c6-161f-11e8-91ca-bfe6c28c12cf.jpg)

**Comment by fisharebest** [comment]
The drop-down boxes are provided by the "select2" library.

I plan to replace this library. See #1369 

I will look at these styling problems after #1369 is complete.

**Comment by fisharebest** [comment]
I've added a temporary fix until I have time to replace the select2 library
