### ISSUE TITLE
Dev - Individual page, sidebar link bug

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#1628]
See attached,

Clicking on any of the 'links' in the relationship boxes has no effect. I seem to remember these items were not proper anchors for validation reasons and required a bit of javascript to work.

![sidebar bug](https://user-images.githubusercontent.com/104515/36482297-be5c90ee-170a-11e8-9a19-849327d5520e.jpg)

**Comment by fisharebest** [comment]
The entire popup is an `<a>`, which is why it cannot contain links.

Should be simple to replace with boostrap dropdowns.
