### ISSUE TITLE
initial Setup of 2.0 doesn't create tables

### ISSUE THREAD

**Issue by DaniHaag** [fisharebest/webtrees#1629]
The step after connecting to the database fails. You can enter the data for the administrator account but as soon as you submit it complains about the table not existing: 
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.wt_gedcom' doesn't exist

when I connect to the database I don't see any tables created.

**Comment by fisharebest** [comment]
I just tried this, and it worked OK.

Was the file data/config.ini.php created?

**Comment by fisharebest** [comment]
Are you able to reproduce this problem?

**Comment by fisharebest** [comment]
I guess there is some error with your server.
Without more information, we cannot help you.

If the problem happens again, please open a new issue with all the details.  Thanks.
