### ISSUE TITLE
Forum hides reply #26 (first of page 2)

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#1631]
I got an email about an reply to an topic in the forum (https://www.webtrees.net/index.php/en/forum). It contains a link to the forum topic:

https://www.webtrees.net/index.php/en/forum/4-customising/31882-module-ancestral-fan-chart-using-d3-js/66712

If you click the link you won't see the reply. The current topic contains 25 replys after that a second page will be appended. The new topic is on page two. If you add another reply the above one will be shown.

**Comment by makitso** [comment]
Post #28 was deleted, I presume by you.

**Comment by magicsunday** [comment]
Why close? I'm still not able to see the post. I just added one (#27) to test and deleted it afterwards.

**Comment by magicsunday** [comment]
Seems a bug in the forum software.

**Comment by makitso** [comment]
Once you delete the post its gone, you can't see it -- its working as designed.

**Comment by magicsunday** [comment]
You don't understand, The user "gustine" wrote a new post:

A new reply has been posted on the webtrees
Message Subject : Module - Ancestral fan chart using d3.js
Category : Customising
Posted by : Gustine

URL : https://www.webtrees.net/index.php/en/forum/4-customising/31882-module-ancestral-fan-chart-using-d3-js/66712

This post is number 26. I'm not able to see his post. Only if I add another post to the topic I see it.

**Comment by makitso** [comment]
Rico,  It's possible there is a bug in the Kunena forum software.  You might want to check their forum to see if its a known problem.  However, www.webtrees.net uses a version of kunena software that is no longer supported.  On a hunch, I changed the number of posts displayed to 20 and now on page 2 the post is visible.

**Comment by magicsunday** [comment]
Thanks. The bug seems to be fixed: https://github.com/Kunena/Kunena-Forum/issues/5543

Maybe the forum could be updated some day.

**Comment by makitso** [comment]
I turned over the support of the www.webtrees.net web site to Greg as of the first of the year.  I believe his intention is to migrate the forum to another product.

**Comment by fisharebest** [comment]
We are using version 4 of the forum software.
The current version is 5.

A long time ago, I was told there was a reason we can't upgrade, but cannot remember the details.

I guess I can make a server backup - then upgrade and see what breaks...

**Comment by makitso** [comment]
The Kunena form software is a very important part of the www.webrees.net site.  At the present time the site uses Kunena version 4 and the Blue Eagle template, which has been heavenly modified for webtrees.

Version 5 of Kunena dropped the Blue Eagle template (although recently it became available from a third party) and went to a responsive design that changed the MVC structure.  Quite frankly, it would have been a lot of work to convert to Version 5 with any of the supported templates.  In addition, the forum software has always been a very trick part of the webtrees web site.  By this I mean, there are a lot of extensions in use, and each release brings it normal share of problems.

**Comment by fisharebest** [comment]
Thanks Rob - I remember now.

**Comment by fisharebest** [comment]
The forum software has been updated.
