### ISSUE TITLE
Dev Html validation issue

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#1632]
The following code snippet is used in many places
```
<fieldset class="form-group">
    <div class="row">
        <legend ...
```

and this fails validation as a legend should be the first (immediate) child of a fieldset. I tried swapping the legend and the div but this breaks the display and the only way I could fix it with css was by floating the legend - not very satisfactory. I found a simpler solution was to replace the legend (in it's current location) with a label (or span). A label seems to me to be a bit more semantically correct. However, perhaps someone with better css skills than me could come up with the 'proper' solution.

**Comment by fisharebest** [comment]
I raised this with the bootstrap team a while back.

https://github.com/twbs/bootstrap/issues/21666

Their recommendation was the extra `<div>`.

> A label seems to me to be a bit more semantically correct

A `<label>` identifies an individual radio button.
A `<legend>` describes/groups a number of radio buttons.

**Comment by ddrury** [comment]
> A <label> identifies an individual radio button.
> A <legend> describes/groups a number of radio buttons.

Yeah, I realise it isn't really correct but I thought it closer than a span. Recommending something that is invalid doesn't seem to me to be the way forward but what do I know

**Comment by fisharebest** [comment]
> Recommending something that is invalid doesn't seem to me to be the way forward

I'm kinda with you on this one - which is why I raised the issue with bootstrap last year.  But this is their area of expertise, so I'll defer to them on this one.

**Comment by ddrury** [comment]
May as well close this
