### ISSUE TITLE
Send mail with smtp and gmail

### ISSUE THREAD

**Issue by Jean-Mercier** [fisharebest/webtrees#1648]
Hello i'm not sure it's an issue or a problem from my side but i need help
I try to configure mail to be send via gmail smtp

but i have this error message

> /webtrees/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:95 stream_socket_enable_crypto(): this stream does not support SSL/crypto 

is there a workarround ?

**Comment by fisharebest** [comment]
This error message often means that your insallation of PHP does not have the `openssl` library.

**Comment by Jean-Mercier** [comment]
Thanks  i activate open ssl so it's ok now
