### ISSUE TITLE
The Hebrew nickname apostrophies on ltr pages are wrong - 2.0.0 

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1650]
The apostrophies around the Hebrew nicknames in charts print out and down from the name. ‘Freddie’  and 
![freddie_2018-03-17_20-38-31](https://user-images.githubusercontent.com/5202996/37559324-79b58452-2a2c-11e8-9b64-d14042453be9.jpg) in Hebrew.

They should print from outside towards the names or as in pre 2.0.0 straight. "Freddie" in Latin and "פרדי".

Sample person on my site I2103

**Comment by fisharebest** [comment]
The quotation characters are a translation string: `“%s”`.

According to https://en.wikipedia.org/wiki/Hebrew_punctuation#Quotation_marks Hebrew uses straight quotation marks.

You can change it on the translation server:

https://translate.webtrees.net/translate/webtrees/webtrees/he/?q=%E2%80%9C%25s%E2%80%9D&search=exact&source=on&target=on&type=all&ignored=False

**Comment by fisharebest** [comment]
It looks like this change has been made
