### ISSUE TITLE
Chart person boxes - my site needs 6 full rows - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1651]
I have Latin and Hebrew names on my site. They are printed in the charts on 2 rows.
The birth and death data is printed on 2 rows each.

This means that my site needs 6 rows in the chart individual boxes.
We should print a small bottom margin under the 6th row.

Now I see that the individual boxes are 260pc x 85px in clouds, colors and fab themes and 250px x 80px in minimal, webtrees and xenea themes.
In clouds, colors and fab themes we see the upper part of the last row. We do not see a bottom margin.
In minimal, webtrees and xenea themes we do not see the 6th row or a bottom margin.

Attached a prinout of the individual box of my 2.0.0 test site I2103 in fab and minimal themes. 
![fabpersonbox_2018-03-17_19-49-33](https://user-images.githubusercontent.com/5202996/37559353-138a6c0a-2a2d-11e8-95b9-ba641e4ad194.jpg)
![minimalpersonbox_2018-03-17_19-51-14](https://user-images.githubusercontent.com/5202996/37559354-1909efb6-2a2d-11e8-94c4-740209e6e12f.jpg)

Where in the wt code can we try to enlarge the boxes?

The boxes on my pre 2.0.0 production site with my local changes. 
![oldfabbox_2018-03-17_20-02-47](https://user-images.githubusercontent.com/5202996/37559361-2fea75de-2a2d-11e8-877e-9b08fc454317.jpg)
![oldminimalbox_2018-03-17_20-00-48](https://user-images.githubusercontent.com/5202996/37559363-37696180-2a2d-11e8-9f66-62dc671d0ad3.jpg)

**Comment by makitso** [comment]
Look at
https://github.com/fisharebest/webtrees/commit/bfe5986f294cd25d56c970a3cdd238e451ae4386#diff-2c8e5f5180a49e322fca5862781b5fdb

**Comment by melizaa** [comment]
Thanks!

**Comment by melizaa** [comment]
I have updated the files of all the themes except for colors.
Where should I update colors?

**Comment by melizaa** [comment]
Colors looks also OK.

**Comment by fisharebest** [comment]
The person boxes will soon be updated to use separate views (templates), so it should be easier to modify them in the future.

**Comment by melizaa** [comment]
The chart person boxes look now much better on my test sites, Thanks makitso!
