### ISSUE TITLE
Fan chart parents' Hebrew name not centered - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1652]
The Hebrew names of the parents are not centered on ltr and on rtl pages.

See 2.0.0
![latest_2018-03-17_22-21-32](https://user-images.githubusercontent.com/5202996/37559662-82f40362-2a32-11e8-9c86-6a3e9f884d0d.jpg)

See pre 2.0.0
![old_2018-03-17_22-23-04](https://user-images.githubusercontent.com/5202996/37559663-8a529344-2a32-11e8-92ab-5db7a059244c.jpg)

**Comment by magicsunday** [comment]
Hi, could you please try the following module as an replacement for the fan chart?
    https://github.com/magicsunday/ancestral-fan-chart

I would like to know if it could handle your hebrew names the way you need.

**Comment by magicsunday** [comment]
Are you sure you closed the right issue? #1653 seems right.

**Comment by melizaa** [comment]
Rico,

1. Pre 2.0.0 - see my site - www.amitys.com/webtrees/module.php?ged=Gedcom.ged&mod=ancestral-fan-chart&rootid=I86&generations=4&fanDegree=180&fontScale=100&showColorGradients=0&showEmptySegments=1&showEmptySegments-GUI-ONLY=1

- On the Latin LTR pages I see Latin LTR names in a very nice presentation. In the old fan chart I see also the person's Hebrew name.

- On Hebrew RTL pages I see Hebrew names. The root person's name is printed correctly. The names of the other individuals should also print from the right. They print from the left to right. We see the root person's mother as הרו לטנזור. We should see her as ורה רוזנטל. Mouse over her name prints the name as expected.
I think that we had similar problems originally also in the old chart and in other graphic pages. 

2. In my 2.0.0 test site https://www.amitys.com/future/ I get errors.

Fatal error: Uncaught ErrorException: /home/amitys/future.amitys.com/modules_v3/ancestral-fan-chart/src/Module.php:96 Use of undefined constant WT_STATIC_URL - assumed 'WT_STATIC_URL' in /home/amitys/future.amitys.com/includes/session.php:139 Stack trace: #0 /home/amitys/future.amitys.com/modules_v3/ancestral-fan-chart/src/Module.php(96): Fisharebest\Webtrees\{closure}(8, 'Use of undefine...', '/home/amitys/fu...', 96, Array) #1 /home/amitys/future.amitys.com/modules_v3/ancestral-fan-chart/src/Module.php(190): RSO\WebtreesModule\AncestralFanChart\Module->getModuleUrlPath() #2 /home/amitys/future.amitys.com/module.php(25): RSO\WebtreesModule\AncestralFanChart\Module->modAction('') #3 {main} thrown in /home/amitys/future.amitys.com/includes/session.php on line 139

After I replace WT_STATIC_URL by WT_ROOT I get the following error.

Fatal error: Uncaught ErrorException: /home/amitys/future.amitys.com/modules_v3/ancestral-fan-chart/src/Module.php:196 Use of undefined constant WT_AUTOCOMPLETE_JS_URL - assumed 'WT_AUTOCOMPLETE_JS_URL' in /home/amitys/future.amitys.com/includes/session.php:139 Stack trace: #0 /home/amitys/future.amitys.com/modules_v3/ancestral-fan-chart/src/Module.php(196): Fisharebest\Webtrees\{closure}(8, 'Use of undefine...', '/home/amitys/fu...', 196, Array) #1 /home/amitys/future.amitys.com/module.php(25): RSO\WebtreesModule\AncestralFanChart\Module->modAction('') #2 {main} thrown in /home/amitys/future.amitys.com/includes/session.php on line 139

I do not know what we should use instead of WT_AUTOCOMPLETE_JS_URL.

3. In English, as far as I know, one should write 180 degrees, etc., not 180 degree

Meliza

**Comment by fisharebest** [comment]
> After I replace WT_STATIC_URL by WT_ROOT I get the following error.

`WT_STATIC_URL` should be replaced with `WT_BASE_URL`.

**Comment by melizaa** [comment]
Rick,

Another issue.

On the Hebrew page we see people with a birth and a death year 1821-1886. A birth only year prints as if it is a death date -1824 and a death only date as if it is a berth date 1831-
just a birth date are

**Comment by melizaa** [comment]
Greg,

With what should we replace WT_AUTOCOMPLETE_JS_URL?

**Comment by fisharebest** [comment]
Not a simple change.

We have replaced the old autocomplete (which returned an XREF) with a new "select" interface which selects individuals/families.etc.

**Comment by magicsunday** [comment]
Hi, please use the code from the 2.0 branch (https://github.com/magicsunday/ancestral-fan-chart/tree/2.0) on your webtrees 2.0 installation. Direct download: https://github.com/magicsunday/ancestral-fan-chart/archive/2.0.zip

**Comment by melizaa** [comment]
This issue was not solved. Please reopen it.
