### ISSUE TITLE
Dropdown menu cropped in Hourglass chart

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1661]
Index page Hourglass chart - I see only a part of the drop down menu of family members when I hit the down arrow.
![2018-03-24_00-52-39](https://user-images.githubusercontent.com/5202996/37854865-c871cb3e-2efd-11e8-843f-7b97d5d3f6da.jpg)

**Comment by fisharebest** [comment]
This also affects the full-size hourglass chart.

**Comment by makitso** [comment]
Fixed with patch 5318773

**Comment by melizaa** [comment]
The dropdown menu is still cropped in the charts block.

**Comment by makitso** [comment]
Please provide an screen shot.

**Comment by fisharebest** [comment]
This was a CSS change, so you will need to clear your browser cache or do a full page reload (e.g. CTRL-F5)

**Comment by melizaa** [comment]
In my test system as a user

I see the full drop down menu in Edge and in FireFox.

In Chrome I have removed cache and cookies a few times, hit CTL-5 several times, lofgged off and on and I do not see the vertical scroll bar. I see the block as it was originally with a scrollbar only at the bottom.

**Comment by makitso** [comment]
Yes, it appears that Chrome does not work.  But, perhaps the next version of Chrome will help?

**Comment by makitso** [comment]
Ok, just submitted a patch that "should" solve it.
