### ISSUE TITLE
Links on fan chart no longer work

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1667]
![image](https://user-images.githubusercontent.com/5147603/37916091-d9408cec-30cf-11e8-9c7f-ffdf1aaed2e2.png)

**Comment by magicsunday** [comment]
Time to replace it with: https://github.com/magicsunday/ancestral-fan-chart

🙄 😁

**Comment by fisharebest** [comment]
Menus are back (missing javascript).

They still need converting to bootstrap dropdowns, as used elsewhere on the site.

**Comment by fisharebest** [comment]
Seems to be working now.
