### ISSUE TITLE
GED: non-standard date in TMG import interpreted as French Republican Calendar

### ISSUE THREAD

**Issue by Amgine0** [fisharebest/webtrees#1668]
The Master Genealogist output can include "EITHER [date] OR [date]" formats. This is amusingly misinterpreted as Thermidor, with years being ~= [year] + 1792 (beginning of the French Republican Calendar) and displayed in Roman numerals.
e.g.
```
1 BIRT
2 DATE EITHER 1731 OR 1734
2 PLAC Caroline County, Virginia
```
becomes
```
Thermidor MDCCXXXI (August 3523) 
Caroline County, Virginia
```

A proposed solution "EITHER [date] OR [date]" becomes "[date] - [date]". TMG appears to order the either-or dates ascending.

**Comment by fisharebest** [comment]
When the date is invalid, webtrees searches for a valid date anywhere in the text.

Here it is matching `THER 1731`.

> "EITHER [date] OR [date]" becomes "[date] - [date]"

Or we could treat it the same as `BET x AND y`.

**Comment by Amgine0** [comment]
My personal suggestion would be to treat it the same as BET x AND y.

**Comment by fisharebest** [comment]
We could convert `EITHER x OR y` to `BET x AND y` automatically during import.

We fix a small number of similar non-standard GEDCOM issues.  e.g. we convert `RESN invisible` to `RESN confidential`.

Should we do this here?

**Comment by fisharebest** [comment]
For dates, we already convert many other formats to valid GEDCOM.  e.g.

* `APX x` -> `ABT x`
* `CIR x` -> `ABT x`
* `BET x - y` -> `BET x AND y`

etc.
