### ISSUE TITLE
HTML reports change the page font size - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1673]
The HTML report changes the page fonts to very small.

In Colors I see texts under the icons.

Minimal theme before HTML report
![2018-04-07_18-02-42](https://user-images.githubusercontent.com/5202996/38456522-3ea248b0-3a8e-11e8-9303-712b87b8e6b1.jpg)

Minimal theme with HTML report 
![2018-04-07_18-03-53](https://user-images.githubusercontent.com/5202996/38456525-45ef138c-3a8e-11e8-9d37-3fb238b2b4cd.jpg)

**Comment by makitso** [comment]
Looks like d-print-non is not being honored for the header.

**Comment by melizaa** [comment]
I see this in Chrome in any themes and reports that I have looked at..

**Comment by melizaa** [comment]
In colours I do not see a full text. Any report page.

**Comment by makitso** [comment]
> In colours I do not see a full text. Any report page.
I am sorry but I can't reproduce this on W10 and Chrome.

**Comment by melizaa** [comment]
This is a sample colours theme report
![2018-04-07_20-03-02](https://user-images.githubusercontent.com/5202996/38457916-5f4107f8-3a9f-11e8-86b7-f6ff5361b915.jpg)

**Comment by melizaa** [comment]
I see the same in demo-dev in colours theme.

**Comment by melizaa** [comment]
I think that this is one issue.

**Comment by fisharebest** [comment]
The HTML reports set the global font size to 10px in `ReportHtml::run()`.

It should just set it for the report content.

**Comment by makitso** [comment]
Greg's patch fixed the names appearing under the primary Icons for Colors and Clouds.
