### ISSUE TITLE
Media file with %20 shows error 404 in 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1675]
I have media files like Amalia%20Wagenheim%20017[1].JPG. 

I see them correctly in pre 2.0.0 webtrees.
In 2.0.0 I see 404 instead of the media.

**Comment by fisharebest** [comment]
This appears to be a bug in the `phpleague/glide` library.  I've raised it on their [issue tracker](https://github.com/thephpleague/glide/issues/227).

I can code around it, but I'll wait for their response first.

**Comment by fisharebest** [comment]
We use few features from `glide`.  It might be simpler to write our own wrapper around `intervention`

**Comment by fisharebest** [comment]
The `glide` project hasn't responded, so we'll need to deal with this locally.
