### ISSUE TITLE
Select2 feedback messages are always in English

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1676]
When I make a mistake with or search for the root person on non English pages, I see English messages, for instance “The results could not be loaded”, “Searching...”, “No results found”, “Loading more results”.

I filled in the field in my test site I111111, nothing or IA and I scrolled to the bottom, etc.

We should print the messages in the page language.

![2018-04-07_20-05-01](https://user-images.githubusercontent.com/5202996/38457879-fcb64314-3a9e-11e8-9941-7cac53da34c9.jpg)

**Comment by fisharebest** [comment]
This is the "select2" plugin.

It is the "least bad" plugin that provides this service.

I am still not sure whether to include it in the 2.0 release.  It may be better to use a simpler plugin with fewer features.

**Comment by fisharebest** [comment]
This one was fixed a while ago...
