### ISSUE TITLE
All the site messages should print in the page language, not in English. - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1677]
If I try to login to a non English page and I do not fill a password, I see a message in English "Please fill out this field." 

Messages should print in the page language.
![2018-04-07_20-23-43](https://user-images.githubusercontent.com/5202996/38458050-9e258014-3aa1-11e8-804d-1b2efff39bfe.jpg)

**Comment by fisharebest** [comment]
This message is generated by the web-browser (for a required field), and is shown in the browser's language.

There is nothing we can do to influence this.

**Comment by fisharebest** [comment]
Other similar messages about invalid input and file uploads are also generated by the browser.

There appear to be plans by the web-standards group to support localisation of forms in the future.

https://www.w3.org/International/wiki/Locale-based_forms
