### ISSUE TITLE
Error when I try to update media directory of 404 file in test system to an updated media directory - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1678]
I share the media folders between 4 URLs.

A mediafile is moved to another folder in another URL. I see the media as 404.
I try to update the directory of the missing media object in media to the new directory by using the Media file edit icon. 

I get error
ErrorException: /app/Http/Controllers/EditMediaController.php:232  sha1_file(/home/amitys/test.amitys.com/data/media/19755854_10212744543350739_737519293_n.jpg): failed to open stream: No such file or directory in file /includes/session.php on line 127
Stack trace:
  1. ErrorException->() /includes/session.php:127

or for another file "The file 'xxxx.jpg' does not exist."

I can update the directory using The Filename editor or the edit menu raw editing. 
I can update existing files in the Media file, the Filename and in the top edit menu raw editing.

The Media file editor is the most user-friendly. It helps find the required folder.
I should not get errors when I try to use it.

Why do we show the file name and enable the editing both in the Media file and in the Filename?

**Comment by fisharebest** [comment]
This issue is fixed in 2.0.0, which is now released.
