### ISSUE TITLE
New Install has two issues

### ISSUE THREAD

**Issue by kristophr** [fisharebest/webtrees#1682]
I'm using the latest version - on my own server (webtrees.kristophr.com) - when I try to upload a picture/media object to a family - I get an error:

/var/www/webtrees.kristophr.com/addmedia.php:410 Bad $action () in addmedia.php

This seems to be only for Family's - uploading media for individuals works just fine.

Unrelated - but when I also pull up an individual list and click on a name I get this error:

/var/www/webtrees.kristophr.com/includes/session.php:193 /var/www/webtrees.kristophr.com/app/Functions/FunctionsPrintLists.php:150 A non-numeric value encountered #0 /app/Functions/FunctionsPrintLists.php:150 ErrorException("/var/www/webtrees.kristophr.com/app/Functions/FunctionsPrintLists.php:150 A non-numeric value encountered") #1 /indilist.php:261 individualTable([array])

**Comment by fisharebest** [comment]
Please only create one at at time.  With two issues, we cannot assign a status/priority and we cannot mark part of it as solved.  It costs nothing to create issues.  You can create as many as required!

2) short answer - you are using PHP 7.1 or later.  webtrees 1.7 was developed/tested on PHP 5.3->7.0.
You also posted this question on the fourm.  If I remember correctly, solutions have been posted on the forum.

**Comment by fisharebest** [comment]
1. I am unable to reproduce this issue, and it has not been reported before.

All families or just some families?

Is the specific image causing the problem?  Can you add this image to individuals?

What are the exact steps you take to reproduce the error?

**Comment by kristophr** [comment]
> Is the specific image causing the problem? Can you add this image to individuals?

Actually does seem to be image specific - I will rescan and see it the new image works.  I used a random image off the internet and that took just fine.  Trying to upload my scanned image didn't work on any of the ways to upload images.   Not sure why - but like i said - I'll rescan and try a different method.

**Comment by kristophr** [comment]
> short answer - you are using PHP 7.1 or later. webtrees 1.7 was developed/tested on PHP 5.3->7.0.
> You also posted this question on the fourm. If I remember correctly, solutions have been posted on the forum.

I am on 7.2 of PHP - however - reading the forums I didn't see any answers other than "wait for 2.0"  But since it is php versioning - I'll mark this as closed and wait for 2.0
