### ISSUE TITLE
Media List - Repeated Entries

### ISSUE THREAD

**Issue by maekclena** [fisharebest/webtrees#1698]
In demo-dev, each media object is listed 144 times.
[Link for reference.](https://dev.webtrees.net/demo-dev/index.php?ged=demo&route=media-list&action=1&search=yes&folder=&subdirs=1&max=20&form_type=&filter=&action=1)

**Comment by fisharebest** [comment]
Do you see this on your own site, or just on the demo site?

**Comment by maekclena** [comment]
Just the demo site, I don't have an instance of the beta.

**Comment by fisharebest** [comment]
Thanks.  It isn't happening on my development server, so I wanted to understand the priority.

**Comment by fisharebest** [comment]
I've re-imported the GEDCOM file and the problem has disappeared.

No idea what caused it.  Perhaps an earlier bug created duplicates?

If the problem doesn't reappear in the next few days, I'll close this issue.

**Comment by fisharebest** [comment]
I see that the duplicates have reappeared.  We now have 3 of each image.

I also not that it is 3 days since I re-imported the data.

Perhaps the demo-server's overnight refresh script is at fault?

**Comment by fisharebest** [comment]
It is now 19 days, and there are 19 copies of the image.

**Comment by maekclena** [comment]
About a week ago I noticed the duplicates were gone. Since then none reappeared so I guess the issue is solved.

**Comment by fisharebest** [comment]
I couldn't find the problem, so if it no longer happening, I'm happy to close it.
