### ISSUE TITLE
Census Shared note on individual census line - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1701]
In pre 2.0.0 census N125 and N126 shared notes are printed as expected. In 2.0.0 we do not print the row of the 1st person, we do not print all the columns and we print control texts before and/or after the census table ".end_formatted_area."

**N125 in pre 2.0.0**
![2018-04-16_01-19-13](https://user-images.githubusercontent.com/5202996/38784031-3d545aa2-4114-11e8-8bd2-80fc7c390248.jpg)

**N125 in 2.0.0**
![2018-04-16_01-20-20](https://user-images.githubusercontent.com/5202996/38784051-7db3d820-4114-11e8-8fdd-6c40e92f64d3.jpg)

**N126 in pre 2.0.0**
![2018-04-16_01-24-15](https://user-images.githubusercontent.com/5202996/38784064-f66c53e6-4114-11e8-98d1-5259e0f28826.jpg)

**N126 in 2.0.0**
![2018-04-16_01-25-42](https://user-images.githubusercontent.com/5202996/38784075-253c14e0-4115-11e8-9589-11d884c49ae4.jpg)

**Comment by fisharebest** [comment]
This is implemented using a "markdown plugin".  Perhaps this is caused by an update to the markdown library?

**Comment by melizaa** [comment]
I have today looked at N125, N126, N134, N142, N150.
As we can see in the above sample, N126 prints also b. before the column titles.

**Comment by sleebooth** [comment]
The minus/hyphen occurs often in my Census Shared Notes and Certificate tables.

Batch Update: Search for |-| and Replace with |−| for these instances corrects them. It seems like a temporary fix though.

I haven't come across any cases (including 1910 USA Censuses) of the first line of the table being omitted in rendering

**Comment by melizaa** [comment]
The shared notes look OK in the latest code.
