### ISSUE TITLE
rtl - edit raw record - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1705]
level 0 prints 0 and @ after it to the right instead of to the left - the data is adjusted right.
The other facts print adjusted left.

![2018-04-17_12-14-19](https://user-images.githubusercontent.com/5202996/38860516-0b96709c-4239-11e8-9347-80a08a2c296e.jpg)

**Comment by fisharebest** [comment]
Fixed in https://github.com/fisharebest/webtrees/commit/cd32eb608fb47f7b9bf703226b2a1074d16a0009
