### ISSUE TITLE
Editing event with @#xxxxx@ in rtl - @# print to the right - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1706]
Editing an event defined with a Julian (or Hebrew) date in prod I see also on the rtl page as expected @#DJULIAN@ 25 DEC 1871. 

Editing the events in the test systems in rtl prints DJULIAN@ 25 DEC 1871#@

![2018-04-17_12-28-45](https://user-images.githubusercontent.com/5202996/38861467-4ea66f84-423b-11e8-80b3-0a2a56250e1e.jpg)

**Comment by fisharebest** [comment]
Reopen - wrong issue number in commit message
