### ISSUE TITLE
Descendants list - Expanding in new page

### ISSUE THREAD

**Issue by maekclena** [fisharebest/webtrees#1708]
In demo-dev, clicking on the descendants list of an individual to expand/collapse an item displays the results in a new page.

**Comment by fisharebest** [comment]
This is working for me.  I assume you mean the [+] and [-] icons.

Can you clear your browser cache and try again?

**Comment by maekclena** [comment]
Disabling cache doesn't fix it.
Maybe I wasn't clear when I said the descendant list. I meant the list in the sidebar on an individual's page.

**Comment by fisharebest** [comment]
> I meant the list in the sidebar on an individual's page.

Ah!  I was looking at the list-view of the descendants chart (which also has +/- links).
