### ISSUE TITLE
Descendants sidebar - Wrong behavior

### ISSUE THREAD

**Issue by maekclena** [fisharebest/webtrees#1709]
In the sidebar descendants list, clicking twice on the very last entry creates an embedded copy of the current individual's page.

It seems like the last link defaults to the current page and, when triggering the expansion, is interpreted as a query.

The bug appears in both demo-dev and demo-stable. It does not occur if the last entry has the indication "no children".

**Comment by fisharebest** [comment]
I am surprised nobody has reported this before.

I guess that very few people use this feature...

**Comment by makitso** [comment]
There is also no indentation.  Any objections to a little padding:
![image](https://user-images.githubusercontent.com/5147603/39667298-c6789dd6-5067-11e8-86b3-2f0fb693d62e.png)

**Comment by fisharebest** [comment]
> Any objections to a little padding, say 5px?

I'd probably keep the indentation as small as possible.  If there are lots of generations, we'll run out of space.

**Comment by fisharebest** [comment]
I guess I must have been able to reproduce this bug once, but I can't reproduce it now.

**Comment by maekclena** [comment]
I can still reproduce the issue on demo-dev and demo-stable:
1. Expand the "Descendants" tree on an individual's page sidebar until you find a leaf node
2. Collapse the leaf node by clicking on the minus sign (which has no effect since there is nothing to collapse)
3. Expand the leaf node by clicking on the plus sign

Note that it doesn't work if the mention "no children" appears ([example](https://dev.webtrees.net/demo-dev/index.php?route=individual&xref=i105&ged=demo)) or if the tree is seemingly too small ([example](https://dev.webtrees.net/demo-dev/index.php?route=individual&xref=i12&ged=demo)).

**Comment by fisharebest** [comment]
Can you give an exact URL and example?

I've tried many different individuals on the demo site, and cannot find one with the problem.

**Comment by ric2016** [comment]
The problem occurs for spouses with children, where these children aren't shown due to privacy restrictions, as in the example (but 'no children' isn't shown either, so the respective html block is empty).

In this case, an ajax request attempts to load html for further descendants, but uses the wrong url, leading to the entire individual page getting displayed in the sidebar.

See PR for a fix.
