### ISSUE TITLE
Interactive Tree - Repeated event handlers

### ISSUE THREAD

**Issue by maekclena** [fisharebest/webtrees#1710]
In demo-dev, each time the interactive tree is updated, the events `mouseup` and `mousemove` are registered again. This causes queries to be sent multiple times.

**Comment by fisharebest** [comment]
I do not see the events being registered multiple times.

Can you give me any more information to help reproduce the problem?  Thanks.

**Comment by maekclena** [comment]
Every time the interactive tree is dragged, line 53 in treeview.js is executed and adds new event listeners to the document's root.

The bug is not visible in Safari, probably because it detects duplicates, but it is visible using Firefox, IE11 or Edge.
