### ISSUE TITLE
New user registration form failed to display

### ISSUE THREAD

**Issue by nejman** [fisharebest/webtrees#1712]
URL: index.php?route=register

`Error: Call to a member function getTitle() on null in file /app/Http/Controllers/Auth/RegisterController.php on line 124
Stack trace:
  1. Error->() /app/Http/Controllers/Auth/RegisterController.php:124
  2. Fisharebest\Webtrees\Http\Controllers\Auth\RegisterController->registerAction() /index.php:93
  3. call_user_func() /index.php:93
  4. Fisharebest\Webtrees\{closure}() /app/Http/Middleware/UseTransaction.php:43
  5. Fisharebest\Webtrees\Http\Middleware\UseTransaction->handle() /index.php:89
  6. Fisharebest\Webtrees\{closure}() /app/Http/Middleware/CheckCsrf.php:46
  7. Fisharebest\Webtrees\Http\Middleware\CheckCsrf->handle() /index.php:89
  8. Fisharebest\Webtrees\{closure}() /index.php:96
  9. call_user_func() /index.php:96`

**Comment by fisharebest** [comment]
On your site, are all the trees private?

**Comment by makitso** [comment]
My trees are not private - registration gets:
ErrorException: /resources/views/layouts/default.php:15 Undefined variable: tree in file /includes/session.php on line 118 Stack trace: 1. ErrorException->() /includes/session.php:118

**Comment by fisharebest** [comment]
I fixed the "undefined variable: tree" error just before I posted.
Are you still seeing it with the very latest code?

**Comment by makitso** [comment]
Yes

**Comment by makitso** [comment]
Same problem with "Forgot password"

**Comment by nejman** [comment]
At this moment I§m getting the following exception (WT revision 976923d44):

ErrorException: /resources/views/layouts/default.php:15 Undefined variable: tree in file /includes/session.php on line 118 Stack trace: 1. ErrorException->() /includes/session.php:118

**Comment by fisharebest** [comment]
The "undefined tree" errors should be fixed.

The tree variable was changed from a global to a parameter, and I missed a few...

**Comment by nejman** [comment]
OK, I can confirm it, it is working now. Thank you.

**Comment by makitso** [comment]
Latest github, register a user throws this error.
Error: Call to a member function getTitle() on null in file /app/Http/Controllers/Auth/RegisterController.php on line 124
Stack trace:
  1. Error->() /app/Http/Controllers/Auth/RegisterController.php:124
  2. Fisharebest\Webtrees\Http\Controllers\Auth\RegisterController->registerAction() /index.php:96
  3. call_user_func() /index.php:96
  4. Fisharebest\Webtrees\{closure}() /app/Http/Middleware/CheckForMaintenanceMode.php:46
  5. Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->handle() /index.php:92
  6. Fisharebest\Webtrees\{closure}() /app/Http/Middleware/UseTransaction.php:43
  7. Fisharebest\Webtrees\Http\Middleware\UseTransaction->handle() /index.php:92
  8. Fisharebest\Webtrees\{closure}() /app/Http/Middleware/CheckCsrf.php:46
  9. Fisharebest\Webtrees\Http\Middleware\CheckCsrf->handle() /index.php:92
 10. Fisharebest\Webtrees\{closure}() /index.php:99
 11. call_user_func() /index.php:99

**Comment by fisharebest** [comment]
As well as the missing `tree` parameter, there was also an error where a missing contact in the tree configuration would cause an error.
