### ISSUE TITLE
[HTTPS] Port number added to URL which causes problems

### ISSUE THREAD

**Issue by econo202** [fisharebest/webtrees#1718]
# Problem
I'm running webtrees 1.7.9 and I want to enable HTTPS connection.

No matter if I do it with the Control Panel options or with .htaccess, when opening the site `mydomain.com/webtrees` the address changes to `http://mydomain.com:443/login.php?url=index.php%3F` and returns an error. I have to manually cut `:443` and then the HTTPS version of the login screen appears.

The .htaccess rules I use are:
```
RewriteEngine on
RewriteCond %{HTTPS} !=on
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```

# Partial solution and doubts
I think that the problem might lie in `/includes/session.php`, where I've tried to comment the lines:

```
$port = Filter::server('SERVER_PORT', null, '80');
$port = Filter::server('HTTP_X_FORWARDED_PORT', '80|443', $port);

// Ignore the default port.
if ($protocol === 'http' && $port === '80' || $protocol === 'https' && $port === '443') {
	$port = '';
} else {
	$port = ':' . $port;
}
```

Unfortunately this solution works only partially. The site loads over HTTPS correctly, but the browser reports that the connection is not secure.

**Question 1:** How to permanently get rid of port number being added to the URL?

**Question 2:** Is the information about the insecure connection misleading? If it's really insecure, what information gets encrypted and what's transferred in plaintext?

**Comment by econo202** [comment]
I don't see the `$_SERVER` section in webtrees, but I can list them manually.

Tell me which variables are important in this case, and I'll paste them here.

**Comment by fisharebest** [comment]
> Tell me which variables are important in this case

The ones referenced in this block of code

https://github.com/fisharebest/webtrees/blob/1.7.9/includes/session.php#L166-L189

**Comment by fisharebest** [comment]
BTW - in webtrees 2.0, this logic is replaced by an external library, which can detect a wider range of server configurations.

You might want to create a test installation of 2.0 on this server, to see if this works.

**Comment by fisharebest** [comment]
The original error suggests that webtrees has detected the port (443), but has mis-detected the protocol as http rather than https.

Reading through the logic, you have the right config, so it should work.

Have you set the "SERVER_URL" setting?  (In the database, table wt_site_setting).  If so, try deleting it.

**Comment by econo202** [comment]
`SERVER_URL` does not exist in the table `wt_site_setting`, and if I set it to `https://domain/webtrees_directory` there's an error due to redirect loop.

**Comment by LotekHeavy** [comment]
I do have the same trouble, that when I open my webtrees with https://www.domain.example I always got an port :80. I'm behind a reverse proxy and my server variable are:

```
HTTPS => on 
HTTP_HOST => www.domain.example
HTTP_X_FORWARDED_HOST => www.domain.example 
HTTP_X_FORWARDED_SERVER => www.domain.example 
HTTP_X_FORWARDED_FOR => 111.111.111.111 
HTTP_FORWARDED_REQUEST_URI => /index_test.php 
HTTP_HTTPS => on 
HTTP_X_FORWARDED_PROTO => https 
HTTP_X_FORWARDED_SSL => on 
SERVER_NAME => www.domain.example
SERVER_ADDR => 127.0.0.1 
SERVER_PORT => 80 
REMOTE_ADDR => 111.111.111.111
```

Other PHP application (like drupal 8) can find automatic the correct domain. 

My ugly solution is in the session.php to set the port to "" ($port = '';) and then switch in the Website URL to the https://www.domain.example.

**Comment by norpan** [comment]
I have the same or a similar problem with the 2.0.0 beta 3 release. I have https enabled on familjen.eu hosted at one.com. It works when not logged in, but when logging in it redirects to https://familjen.eu:80/... which of course does not work. When I remove the :80 from the redirected page everything works again. It's just the login redirect that adds the :80.

**Comment by fisharebest** [comment]
> 2.0.0 beta 3 release

You might want to update.

The latest code (a) has improvements here and (b) lets you specify your base URL in data/config.ini.php
