### ISSUE TITLE
[webtrees 2.0 Dev] All update / edit / management functions are broken

### ISSUE THREAD

**Issue by HelmutL** [fisharebest/webtrees#1721]
I downloaded from github on May 11, 2018, and extracted the zip file over an existing installation of webtrees 2.0, dated from February.

--> Existing trees and data may be visualised but any function to either edit existing data or doing adminstration tasks like view site logs, tree administration, site settings, ... show only an empty screen.

**Comment by fisharebest** [comment]
It may take many days to fix all of these.

I am migrating the final few functions from the old code structure to the new code structure.
