### ISSUE TITLE
Individual Selection - Bad title attribute

### ISSUE THREAD

**Issue by maekclena** [fisharebest/webtrees#1726]
In every individual's chart, the individual selection drop list shows a malformed tool tip when hovered.

For example, in the [default chart of demo-dev](https://dev.webtrees.net/demo-dev/index.php?route=pedigree&xref=i1&ged=demo), the element with ID `select2-xref-container` has a `title` attribute set to `'<a class="gallery" type="image/jpeg" href="https://dev.webtrees.net/demo-dev/index.php?route=media-thumbnail [...] </span>'`.

**Comment by fisharebest** [comment]
This is a duplicate of #1586

The "select2" library has many faults, and I think we will need to replace it before the 2.0 release.

See also #1369 and #1623
