### ISSUE TITLE
Update use of count() to satisfy PHP 7.2

### ISSUE THREAD

**Issue by mestaritonttu** [fisharebest/webtrees#1731]
See this forum post: https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-9/32481-compatible-with-php-7-2-2#67353

> Solved the above problem by changing the line https://github.com/fisharebest/webtrees/blob/1.7/app/GedcomRecord.php#L641 to
> 
> if ($this->getAllNames() && count($this->getAllNames()) > 1) { 

Obviously there are more uses of count() that need to be updated to not throw a warning.

**Comment by mestaritonttu** [comment]
Wow, so I noticed it does not throw the warning with all surnames, but only certain ones (picked from Lists - Families)! Using 1.7.9.

I used a simple var_dump($this->getAllNames()); to get the output for both the unchanged and the changed scenario. Obvious the full output dumps include a lot of names that I cannot publish. Could I skip the sanitising and email the outputs to you? Or do you have other debugging tips to suggest?

**Comment by fisharebest** [comment]
> Could I skip the sanitising and email the outputs to you?

Please do.  fisharebest@gmail.com

**Comment by fisharebest** [comment]
Is this a family where one of the spouses only has a married name (and no birth name)?

**Comment by mestaritonttu** [comment]
I sent the email back in Saturday. Was it caught in spam filter or...?

**Comment by fisharebest** [comment]
Sorry - yes I got the email.  It suggested the same cause (individual with married name but no birth name) as #1202 - which has already been fixed.  Hence my follow-up question.

If you've found/fixed the name in your data and you are still seeing an error then either:

1) you have other individuals with the same name issue
2) it's a different bug - in which case more info is needed.

**Comment by mestaritonttu** [comment]
Ah, indeed: I manually patched my app/Family.php with your fix for 1202 and I no longer get the warning with the original app/GedcomRecord.php! Thanks.
