### ISSUE TITLE
General search from Place hierarchy display results in 

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1734]
Doing search for an unknown name from top menu leaves user at General search page with the message "no results found."

However, if one does a top menu search of an unknown name from the Lists/Place hierarchy display, no results are displayed and instead of the General search page the user is left in the Place hierarchy.

**Comment by fisharebest** [comment]
That's because the the place-hierarchy page isn't using the new routing system.

There are only a few of these left to update: some edit pages, some admin pages, some module pages and this one.

**Comment by fisharebest** [comment]
All pages now use the new routing system.
