### ISSUE TITLE
Custom modules and views

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1737]
What is the best way to implement (custom) views inside custom modules?

I have seen views being implemented inside standard modules by using the views in the standard views folder. Custom modules can't use this approach. Are there any plans to make views available in custom modules like the way they are implemented in custom themes?

**Comment by fisharebest** [comment]
> Are there any plans to make views available in custom modules like the way they are implemented in custom themes?

Yes, and I think the best way to do it might be to combine themes and modules into a general "plugin".0

**Comment by JustCarmen** [comment]
> Yes, and I think the best way to do it might be to combine themes and modules into a general "plugin".

This would certainly make things less complicated. Do you think this will be implemented before the 2.0-alpha release?

**Comment by fisharebest** [comment]
> Do you think this will be implemented before the 2.0-alpha release?

Unlikely.  Maybe for 2.0-beta.

**Comment by curtisdelicata** [comment]
Is there a roadmap?

**Comment by curtisdelicata** [comment]
Sounds good.

**Comment by fisharebest** [comment]
Themes and modules are now included in the view search path.

Just create `/modules_v3/MODULE_NAME/resources/views/....` or `/themes/THEME_NAME/resources/views/...'.

You can use your own views, or overwrite core views.
