### ISSUE TITLE
Places & Placelocation tables move to comma separated place

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#1743]
Hi Greg,

You mentioned you were considering this a month or so ago rather than the linked list which we currently have (and I was all in favour), however I can't find that conversation now!

It's dawned on me that we can't do this for the placelocation table as each part of the comma separated place will require it's own set of co-ordinates and if the places table does switch to comma separated then we can't have a link table either

**Comment by fisharebest** [comment]
> each part of the comma separated place will require it's own set of co-ordinates

You mean like this?

| Place  | Lat | Long |
| ------------- | ------------- | ------------- |
| England  | 52 | -1 |
| England, London  | 50 | 0 |
| England, London, Westminster  | 50.1 | 0.3 |

**Comment by ddrury** [comment]
Yeah, I see what you're getting at but by doing it like that means (potentially) an awful lot of duplication

**Comment by Amgine0** [comment]
Place | Lat | Lon | Period
------ | ----- | ----- | -----
United Kingdom | 55 | 3 | 1922-present
England, United Kingdom | 51.5 | -0.116667 | 1707-present 
London, England, United Kingdom | 51.507222 | -0.1275 | 2000-present
Greater London, England, United Kingdom | 51.5 | -0.083333 | 1965-present
City of Westminster, Greater London, England, United Kingdom | 51.5 | -0.133333 | 1965-present
City of London, England, United Kingdom | 51.516 | -0.092 | ~886-present
Lundenburh | 51.502786 | 0.087762 | 886-1016
Lundenwic | 51.5132 | 0.1167 | ~600-886
Londinium, Brittania Prima, Western Rome | 51.5125 | -0.0906 | 47-306

There is a benefit to using csv titles if we can add time periods, or just a starting point. But there are complications, like City of London being a county within the region of Greater London, but not a part of the (administrative region) county of Greater London. (Coordinates, dates abstracted from en.WP)

**Comment by fisharebest** [comment]
I have recently tidied up the `Place` and `Location` classes to make it much easier to use them without repeated DB queries.

e.g. this will create "England" (if it doesn't exist) and then create "London, England" (if it doesn't exist).

`$location = new Location('London, England');`

Previous DB queries are cached for efficiency, and there are functions to fetch parents, children, etc.

I don't plan any significant changes in the immediate future.
