### ISSUE TITLE
Feature Request: Add include file for site-specific text e.g. copyright

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1745]
For my personal site I add a copyright statement to the bottom of each page. I do this by making a change to the AbstractTheme.php file.  

It would be nice if there was an include in AbstractTheme.php that references a local file e.g. local.html that a site owner could change with as they see fit.

**Comment by fisharebest** [comment]
This sort of function is already planned.

Most of the theme functions will be replaced with views (PHP templates), which can be overridden by themes.

We are also going to need a privacy-policy page for GDPR reasons, so maybe we can add something to this.

**Comment by makitso** [comment]
>  ...which can be overridden by themes.

IMHO, seems like a lot of work to go through to add a simple copyright to a site.

**Comment by fisharebest** [comment]
> seems like a lot of work

Not really.  There will be a few empty views (e.g. in `<head>`, `<footer>`, etc. which have no content in the core code.

Adding content in these locations will be a simple case of creating a file in a theme (or module?) with your desired content - and this file will not be overwritten during upgrades.

So, all you'd need to do is create a file in a specific location containing your content (even in an existing theme), and that's it.

**Comment by johnds123** [comment]
GDPR is now in full effect. When will the needed module be available?
I am on 1.7.10.
Thanks

**Comment by fisharebest** [comment]
678a16c4e adds an example footer module which does this.

It contains a footer with a link to a page of information.
