### ISSUE TITLE
Dev 2.0 - Clouds and Colors have icon on dropdown top row

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1748]
![image](https://user-images.githubusercontent.com/5147603/40580055-7551dcda-60eb-11e8-82f1-c71d60095e72.png)

The dropdown header should not have an icon.

**Comment by melizaa** [comment]
This is not a header, it is the first menu line. The header is missing.

I see this only as a visitor.
Logged-in users see the menu as expected.

**Comment by melizaa** [comment]
I see sometimes this issue also when I log-in.

**Comment by fisharebest** [comment]
The menus are in the middle of being converted from PHP functions into views.

So, the code that adds the first line is (temporarily) not being called.
