### ISSUE TITLE
A query about queries

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#1749]
Greg,
As you probably know I've recently been looking at the indexes on the placelocation table and when testing a new index on phpMyAdmin I made a fundamental error - I omitted COLLATE from the ORDER BY clause; without it the new index worked, with it the query reverted to using filesort.

Thinking about it I can see why that happens, but what then surprised me was if the table, and the fields involved both had the same collation as that specified in the ORDER BY clause, the index was still ignored.

Not knowing enough about the inner workings of this sort (grin) of thing, by specifying a UTF8 collation  when creating the table does that not allow for correct sorting of different locales? - in other words is COLLATE in an ORDER BY clause really necessary?

BTW don't suppose it makes a difference but I'm using MariaDB 10.2

**Comment by fisharebest** [comment]
I'd really need to see the exact queries and table definitions to be able to look at this.

> specifying a UTF8 collation when creating the table does that not allow for correct sorting of different locales?

It depends.  MySQL can often use the index to get the column values, rather than use the table.

The `EXPLAIN PLAN` will tell you.

> is COLLATE in an ORDER BY clause really necessary?

This is necessary so that we sort according to the rules of the current language.  The default collation `utf8_unicode_ci` is good for most languages, but not all.

**Comment by ddrury** [comment]
Table & query follows, the index that does/doesn't work is ix1. $id is the parent_id of a place in the placelocation table, $p_id is the parent_id of the same place in the places table. (0 & 0 work for the top level places)

```
CREATE TABLE IF NOT EXISTS `##placelocation` (
  `pl_id` int(11) NOT NULL,
  `pl_parent_id` int(11) DEFAULT NULL,
  `pl_level` int(11) DEFAULT NULL,
  `pl_place` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pl_long` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pl_lati` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pl_zoom` int(11) DEFAULT NULL,
  `pl_icon` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`pl_id`),
  UNIQUE KEY `ix1` (`pl_parent_id`,`pl_place`) USING BTREE,
  KEY `ix2` (`pl_parent_id`),
  KEY `ix3` (`pl_place`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


$rows = Database::prepare(
"SELECT SQL_CACHE pl_id, pl_parent_id, pl_place, pl_lati, pl_long, pl_zoom, pl_icon," .
" (t1.p_place IS NULL) AS inactive" .
" FROM `##placelocation`" .
" LEFT JOIN (SELECT p_place" .
 " FROM `##places`" .
 " WHERE p_parent_id = :p_id) AS t1 ON pl_place = t1.p_place" .
" WHERE pl_parent_id=:id" .
" ORDER BY pl_place COLLATE :collation"
)
->execute([
	'id'        => $id,
	'p_id'    => $place_id,
	'collation' => I18N::collation(),
])->fetchAll(\PDO::FETCH_ASSOC);
```

**Comment by ddrury** [comment]
Would changing the collation to utf8mb4_unicode_ci solve things?

**Comment by fisharebest** [comment]
Old versions of MySQL do not support mb4, so we can't use it.

Besides, it is the same collation sequence - just with support for 4-byte encoded characters.

**Comment by fisharebest** [comment]
In a MySQL explain plan `filesort` simply means that the data could not be sorted by the index, and was sorted by the code.

(Note, it doesn't mean that anything was written to a file.  I think this is just the name of a very early implementation of the sort algorithm.  Most likely, all sorting is done in memory).

 I suspect that the query optimiser isn't smart enough to realise that specifying the same collation sequence as used in the column/index means that the index can be used.  Instead, I guess that all collation-specific sort orders will be done in memory, after the results are fetched from the database.

However, the in-memory sort is helped when the data is already "mostly sorted".  In this case, we're fetching data using an index on this column, so for utf8_unicode_ci, it will already be correct, and the sort algorithm will have nothing to do.
