### ISSUE TITLE
Journal and News texts - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1752]
In pre 2.0.0 my site News and Journal entries look in the Source as: 
`<p dir="LTR"><strong>Time for a family tree</strong></p>`

`<p dir="LTR">An article was published on phpGedView, webtrees, this site and me in the 10 January 2014 Jerusalem Post Metro pages 10-11 by Patricia Carmel.</p>`

`<p dir="LTR"><a href="http://www.jpost.com/In-Jerusalem/Arts-And-Culture/Time-for-a-family-tree-337581?prmusr=3gNYpIOU9X3nV5oTj1XHn%2fy7xDph%2fA7phkK05UgAgYR6WJGRNeIqvFuZMeE84zjw">A link to the article</a></p>`

In 2.0.0 I see on the index pages the source text with the `<p>`-s and the `<a>`-s.

**Comment by melizaa** [comment]
The pre 2.0.0 source text that I see in 2.0.0
![2018-05-27_22-37-03](https://user-images.githubusercontent.com/5202996/40599260-2f60e574-6201-11e8-989c-3cb0e7c17c59.jpg)

**Comment by melizaa** [comment]
In 2.0.0 How can I print the following text correctly also on RTL pages?

Given Name Surname (Maiden name)

**Comment by melizaa** [comment]
How can I define ordered or unordered lists in 2.0.0?

**Comment by fisharebest** [comment]
This change is intentional and temporary.

Previously, a malicious user could add scripts to the HTML, which could have security implications.

So, HTML is temporalily disabled until we have a fix for this.

**Comment by fisharebest** [comment]
This also affects the FAQ module

**Comment by Amgine0** [comment]
Markdown-only?

**Comment by melizaa** [comment]
How can we add URL links to the texts?  - from #1751

**Comment by melizaa** [comment]
Latin texts on RTL pages print special trailing charscters [for instance ) . ,] to the right of the page  - from #1751

**Comment by melizaa** [comment]
Almost perfect.

I see "empty lines" between data.
![image](https://user-images.githubusercontent.com/5202996/57604794-c0eaa900-756d-11e9-9968-51660887ba8f.png)

The data looks as expected in the Edit form.
![image](https://user-images.githubusercontent.com/5202996/57604949-23dc4000-756e-11e9-8b3c-331a8ea1f4b3.png)

**Comment by melizaa** [comment]
Adding  style="text-align:left;" to <p> and <li> causes ltr texts too print adjusted left also on rtl pages.

I do not yet know how to print

- end of line/paragraph special characters as expected to the right of the ltr text on rtl pages

- bullets/numbers to the left of ltr text on rtl pages

- ordered/bulleted lists with less empty lines (see also this issue)

I see the parallel issues for rtl texts on ltr pages.

**Comment by melizaa** [comment]
1. The "empty" lines are still a problem.
Why do we see them?

2. I can solve the other issues by using the edit page text direction and align right/left selections and adding to the text lines style="text-align:left;" or right;

3. I need to add to the titles <p dir="ltr" style="text-align:left;"> and </p> or "rtl" and right.
It would be great if the edit form would help me in adding this also to the Title, and not only to the Content.

**Comment by melizaa** [comment]
I need to add to the titles "<p dir="rtl" style="text-align:right;">"and "</p>"

" and "</p>"

**Comment by melizaa** [comment]
I need to add to the titles < p dir="rtl" style="text-align:right;" > and < /p >

**Comment by melizaa** [comment]
I do not think that administrators should have to add to news and journal block titles < p dir="rtl" style="text-align:right;" > and < /p > and to bulletted or numbered lists or texts style="text-align:left;" or right;
The wt code should handle this besed on the direction of the following text.
