### ISSUE TITLE
dev - Lists showing defined surname

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1756]
Test system is exact match with github.

I have two trees in both my configuration.  With the default tree (peters) if I select lists and then mouse over Families, the link at the bottom contains a surname=Peters see below.

![image](https://user-images.githubusercontent.com/5147603/41298920-2aa08df6-6e17-11e8-82b6-1ad7fdd9bc80.png)
If I switch to the second tree Johannsen and do the same Families mouse over I still have the surname=Peters see below
![image](https://user-images.githubusercontent.com/5147603/41299029-6522d812-6e17-11e8-8c3d-5fb1303d4188.png)

**Comment by fisharebest** [comment]
Since you are not looking at an individual details/chart/report, then the surname used in the URL should that of the default individual for the user/tree.

Assuming you are in both trees, and you have set yourself as your default individual, then this behaviour is probably normal.
