### ISSUE TITLE
dev - Stories module generates error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1758]
ErrorException: Undefined property: stdClass::$language in file /app/Module/StoriesModule.php on line 340
Stack trace:
  1. ErrorException->() /app/Module/StoriesModule.php:340
  2. Fisharebest\Webtrees\{closure}() /app/Module/StoriesModule.php:340
  3. Fisharebest\Webtrees\Module\StoriesModule->Fisharebest\Webtrees\Module\{closure}() [internal]:0
  4. array_filter() /app/Module/StoriesModule.php:341
  5. Fisharebest\Webtrees\Module\StoriesModule->getShowListAction() /app/Http/Controllers/ModuleController.php:61
  6. Fisharebest\Webtrees\Http\Controllers\ModuleController->action() /index.php:93
  7. call_user_func() /index.php:93
  8. Fisharebest\Webtrees\{closure}() /app/Http/Middleware/CheckForMaintenanceMode.php:46
  9. Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->handle() /index.php:89
 10. Fisharebest\Webtrees\{closure}() /index.php:96
 11. call_user_func() /index.php:96

**Comment by fisharebest** [comment]
I can't reproduce this, but I think I see the problem.
