### ISSUE TITLE
Empty screen at any function ?

### ISSUE THREAD

**Issue by HelmutL** [fisharebest/webtrees#1765]
I downloaded webtrees dev on June 18 and extracted the zip fiole, overwriting a version of May 2018. Whenever I want to launch webtrees (index.php, login.php ...) I only get an empty screen.

running index.php from the comand line shows the following:
> php index.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url=http://:index.php?route=tree-page&amp;ged=Leininger" />

        <title>Redirecting to http://:index.php?route=tree-page&amp;ged=Leininger</title>
    </head>
    <body>
        Redirecting to <a href="http://:index.php?route=tree-page&amp;ged=Leininger">http://:index.php?route=tree-page&amp;ged=Leininger</a>.
    </body>
</html>PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'ip_address' cannot be null in /var/www/html/webtrees/app/Statement.php:82
Stack trace:
#0 /var/www/html/webtrees/app/Statement.php(82): PDOStatement->execute()
#1 /var/www/html/webtrees/app/Session.php(234): Fisharebest\Webtrees\Statement->execute(Array)
#2 /var/www/html/webtrees/app/Session.php(132): Fisharebest\Webtrees\Session::write('ov4ffu8f4g0tnf8...', 'initiated|b:1;l...')
#3 [internal function]: Fisharebest\Webtrees\Session::Fisharebest\Webtrees\{closure}('ov4ffu8f4g0tnf8...', 'initiated|b:1;l...')
#4 [internal function]: session_write_close()
#5 {main}
  thrown in /var/www/html/webtrees/app/Statement.php on line 82

**Comment by HelmutL** [comment]
Works after a clean install.

BUT

only American English is available (other lnguages have disappeared.

**Comment by fisharebest** [comment]
> running index.php from the comand line shows the following:

This looks normal.  It is redirecting to the default tree.

Also, the error is because webtrees expects requests to come from the web, and expects requests to have an IP address.

> Works after a clean install.

OK!
