### ISSUE TITLE
 Zoom is at maximum level when there is only 1 place for an individual

### ISSUE THREAD

**Issue by bxbroze** [fisharebest/webtrees#1767]
For an individual with only  1 place, the zoom level is always maximum, no matter what is in the configuration.
This is observed on my sites and also the demo sites.

What I found out is that it seems to be due to a change in the google maps API, somewhere in February.
Here is a link on a post desribing the issue on a wordpress plugin:
http://forums.artbees.net/t/advanced-google-maps-not-working-properly-with-6-1-1/12172

**Comment by fisharebest** [comment]
The latest code does not use Google Maps and does not have this problem.

Also, Google Maps now requires an API key *and* a credit card.
I guess few people will be using it.

**Comment by bxbroze** [comment]
It seems the problem is now gone, without any change to my webtree site.
So I guess the google API was updated to fix this.
As you say it is of low importance since next version will be without google maps, but so the information is up to date.
Thanks for the answer.
