### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Fa10175** [fisharebest/webtrees#1774]
I start 1.7.9
i download the last zip today 2018 juil 06
and when i start webtrees i have this error
message:

> _Fatal error: Declaration of Fisharebest\Webtrees\Module\PageMenuModule::getMenu() must be compatible with Fisharebest\Webtrees\Module\ModuleMenuInterface::getMenu(Fisharebest\Webtrees\Tree $tree) in .....\xampp 7.2.2\xampp\htdocs\webtrees\app\Module\PageMenuModule.php on line 25_

thanks to tell me what is the problem

**Comment by fisharebest** [comment]
Which version of PHP are you using?

**Comment by Fa10175** [comment]
Version PHP : 7.2.2

**Comment by fisharebest** [comment]
The error message suggests that you have:

`Module\PageMenuModule.php` from webtrees 1.7
`Module\ModuleMenuInterface.php` from webtrees 2.0

Can you check you have installed the correct files.

**Comment by Fa10175** [comment]
I have on this directorie both files.
so i remove 

> \PageMenuModule.php

and it's ok
this is done because the all old files are don't delete yet
thanks

**Comment by Fa10175** [comment]
they are several file that they should be delete

**Comment by Fa10175** [comment]
after i have

> Fatal error: Uncaught Error: Class 'Fisharebest\Webtrees\Module\PageMenuModule' not found in xampp 7.2.2\xampp\htdocs\webtrees\modules_v3\page_menu\module.php:20 Stack trace: #0 xampp 7.2.2\xampp\htdocs\webtrees\app\Module.php(122): include() #1 xampp 7.2.2\xampp\htdocs\webtrees\app\Module.php(153): Fisharebest\Webtrees\Module::loadModule('...') #2 \xampp 7.2.2\xampp\htdocs\webtrees\app\Module.php(372): Fisharebest\Webtrees\Module::getActiveModules() #3 xampp 7.2.2\xampp\htdocs\webtrees\app\Module.php(241): Fisharebest\Webtrees\Module::getModuleByName('ahnentafel_repo...') #4 xampp 7.2.2\xampp\htdocs\webtrees\app\Http\Controllers\HomePageController.php(628): Fisharebest\Webtrees\Module::getAllModulesByComponent('block') #5 xampp 7.2.2\xampp\htdocs\webtrees\app\Http\Controllers\HomePageController.php(676): Fisharebest\Webtrees\Http\Controlle in xampp 7.2.2\xampp\htdocs\webtrees\modules_v3\page_menu\module.php on line 20

so i try to delete some old files before to put zip files

**Comment by Fa10175** [comment]
If i delete maximum of old files it's ok
