### ISSUE TITLE
I see a fatal error on the individual pages in my test systems - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1782]
Fatal error: Uncaught TypeError: Argument 1 passed to Fisharebest\Webtrees\Functions\FunctionsPrint::printAddNewFact() must be an instance of Fisharebest\Webtrees\GedcomRecord, string given, called in .../resources/views/modules/personal_facts/tab.php on line 37 and defined in .../app/Functions/FunctionsPrint.php:460 

Visitors and members do not see the error.

**Comment by fisharebest** [comment]
I think this error was fixed in a recent commit - 911f5683b68340b4bad2bbca6e1ab7a3a15f46a7
Do you still see the problem?

**Comment by melizaa** [comment]
my test sites are fdf03do, unless I have made an error.

**Comment by melizaa** [comment]
I transfered the files resources/views/modules/personal_facts/tabs.php to the test server. 
Now the issue is solved.
