### ISSUE TITLE
No Timezone in last changes block (1.7.9)

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1783]
I am in the timezone GMT +2. All times in Webtrees are showing the correct times. On the start page I have an block "last change". Inside this blocks all times are 2 hours past, so I think the timezone is not working here.

I use 1.7.9 final.

**Comment by HonkXL** [comment]
Same problem for the tie stamp „last mail sent“ on the block „pending changes“

**Comment by fisharebest** [comment]
I've fixed various timestamps which did not include the timezone.

However, the "recent changes" block displays the `CHAN` record from the database.

This value was (potentially) read from a GEDCOM file and we do not know the timezone.

Therefore we cannot convert the timezone.

**Comment by HonkXL** [comment]
I do not agree. Each user has a timezone in his settings. When I make a change to the database, the timezone of my user has to be used. When I make this change at 15:00 MEST, this value has to be translated to UTC and this value should be written to database. When any user displays this data, it has to be calculated back to the timezone in the user-settings.

Of couse I agree, when I import a GEDCOM file with CHAN-records, it is hard to find the correct timezone for this import.

But here I am just talking abount modifications done inside webtrees, without any export or import!
