### ISSUE TITLE
Page blocks return error 502

### ISSUE THREAD

**Issue by maekclena** [fisharebest/webtrees#1787]
In demo-dev, requests to route `tree-page-block` return an error 502 (bad gateway). [Example](https://dev.webtrees.net/demo-dev/index.php?route=tree-page-block&ged=demo&block_id=16) from [the main page](https://dev.webtrees.net/demo-dev/index.php?route=tree-page&ged=demo).

**Comment by fisharebest** [comment]
The developer tools were enabled.  These need additional resources from the webserver.  I've disabled them.  They should only be used on local development machines.
