### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Fa10175** [fisharebest/webtrees#1789]
I start from 2.0.0  of the 2018 juil 6
i download the last zip today 2018 juil 16
and when i to go to admin-control-panel i have this error
message:

> Fatal error: Uncaught Error: Class 'Fisharebest\Webtrees\Module\FamiliesSidebarModule' not found in \xampp 7.2.2\xampp\htdocs\webtrees\modules_v3\families\module.php:20 Stack trace: #0 \xampp 7.2.2\xampp\htdocs\webtrees\app\Module.php(123): include() #1 \xampp 7.2.2\xampp\htdocs\webtrees\app\Module.php(493): Fisharebest\Webtrees\Module::loadModule('...') #2 \xampp 7.2.2\xampp\htdocs\webtrees\app\Http\Controllers\AdminController.php(591): Fisharebest\Webtrees\Module::getInstalledModules('disabled') #3 [internal function]: Fisharebest\Webtrees\Http\Controllers\AdminController->controlPanel(Object(Symfony\Component\HttpFoundation\Request)) #4 \xampp 7.2.2\xampp\htdocs\webtrees\index.php(319): call_user_func(Array, Object(Symfony\Component\HttpFoundation\Request)) #5 \xampp 7.2.2\xampp\htdocs\webtrees\app\Http\Middleware\CheckForMaintenanceMode.php(48): Fisharebest\Webtree in \xampp 7.2.2\xampp\htdocs\webtrees\modules_v3\families\module.php on line 20

Thanks to tell me, want i should do.

**Comment by Fa10175** [comment]
Nota : before to go to admin-control-panel i can navigate but since i have always the error above.

**Comment by fisharebest** [comment]
You should delete these folders:

modules_v3/families
modules_v3/individuals
modules_v3/page_menu

**Comment by makitso** [comment]
FWIW, whenever there are modules/folders that are deleted from the modules_v3 folder, there is a greater potential for a http 500 error. Many people simply untar a release in a webtrees directory thinking that files are being updated. As a result, an orphaned module hangs the system with no error message -- very untidy.  It would be nice if webtrees could be a bit more helpful and advise that an unknown module was encountered.

**Comment by fisharebest** [comment]
When we do the 2.0 release, the folder modules_v3 will be renamed modules_v4.

This will effectively "delete" the old modules.

The difficulty here is that the missing class triggers a fatal PHP error - which we cannot catch.

I guess one solution is for `module.php` to return the name of a class, instead of an instance of the class.  This way, the core code can run something like

```
$class_name = include 'modules/foobar/module.php';
if (class_exists($class_name)) {
    $module = new $class_name;
} else {
    throw new Exception('Bad module');
}
```

**Comment by fisharebest** [comment]
However, this would still give a fatal error if we cannot instantiate the class - perhaps because it doesn't implement all the functions specified in the interface, etc.

**Comment by Fa10175** [comment]
Thank you for your time
I try from time to time a new master download, to help because I know it's hard to test everything and I understand that there are gaps and imperfections
