### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by Art4** [fisharebest/webtrees#1794]
I would like to contribute to webtrees to help this project moving forward. Unfortunly I have trouble to find a starting point. 

I've read the [Development Guidelines](https://wiki.webtrees.net/en/Category:Development_Guidelines) and the [README](https://github.com/fisharebest/webtrees#building-and-developing). I've also read the discussion in #345, but there are many things unclear to me. 

To make it easier for developers I would like to create a CONTRIBUTING.md file as a starting point where the main questions I have are answered:

1) How to setup the Environment? What is required?
2) How to running the tests?
3) Which Coding Standards or other Conventions should I follow?
4) How to submit a patch? Which branch should I use?
5) Is there a roadmap?

**Comment by Art4** [comment]
This is a first preview for the CONTIBUTING.md. I think it would be best having two different files in each branch (`master` and `1.7`).

# How to contribute

Thanks for taking the time to contribute!

The following is a set of guidelines for contributing to Webtrees. These are mostly guidelines, not rules. Use your best judgment, and feel free to propose changes to this document in a pull request.

## How to submit a patch or feature

If you want to submit a patch or feature, please create a pull request on Github. There are different branches for different versions of webtrees:

- For webtrees 2.0, use the `master` branch
- For the latest webtrees 1.7.*, use the `1.7` branch

Before submitting a pull request make sure you have [tested the code](#how-to-test) and [followed the coding conventions](#coding-conventions).

Please read more about [setting up your environment](#how-to-setup-the-environment) for development.

## How to start

You can start contributing by

- submitting patches or features
- writing tests to [increase the test coverage](https://coveralls.io/github/fisharebest/webtrees?branch=master)

## How to setup the environment

You need

- PHP >=7.1.3 (for webtrees 2.0; or PHP >=5.3.9 for webtrees 1.7)
- MySQL 5
- git
- composer

1. Fork and clone the repository
2. Run `php -S localhost:8080` and open your browser at [localhost:8080](http://localhost:8080)
3. Go through the install process

## How to test

Install PHPUnit by running `composer install`

Then run the tests with `vendor/bin/phpunit`

## Coding conventions

Your code should follow the [PSR-12](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md) Extended coding style guide.

**Comment by fisharebest** [comment]
We also need instructions on using `npm` to build the CSS and JS files.

**Comment by fisharebest** [comment]
Contributing to translations

**Comment by Art4** [comment]
Thank you 👍
