### ISSUE TITLE
Invisible button in interactive tree

### ISSUE THREAD

**Issue by maekclena** [fisharebest/webtrees#1795]
In the [interactive tree](https://dev.webtrees.net/demo-dev/index.php?route=module&module=tree&action=Treeview&xref=i1&ged=demo) chart of demo-dev, when clicking on a box to show details, the button `a.icon-button_indi.tv_link.tv_treelink` next to the individual's name is invisible. The image `indi.png` set as background [returns an error 404](https://dev.webtrees.net/demo-dev/themes/webtrees/css-2.0.0/images/buttons/indi.png).

**Comment by ungeahnt** [comment]
unresolved problem:
> In the interactive tree chart of demo-dev, when clicking on a box to show details, the button a.icon-button_indi.tv_link.tv_treelink next to the individual's name is invisible.
