### ISSUE TITLE
In charts and reports, the individual selection box is not tall enough - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1796]
In charts and reports.the individual selection box is too low.

I saw a correct height before I logged in.
After that I see a height that prints the individual picture outside the box.
![2018-07-19_09-27-57](https://user-images.githubusercontent.com/5202996/42925226-1c91f0c4-8b36-11e8-8d2b-862d14968560.jpg)

**Comment by makitso** [comment]
I error-ed in fixing the wrong problem as defined by this issue.  However, since thumbnails are no longer shown in the individual box its moot.  Anyway the patch needed to be done to give the webtrees theme a bit more room for primary menu dropdowns, e.g. Charts.

**Comment by fisharebest** [comment]
Your change arrived while I was creating the 2.0.0-alpha.1 release, so it went in.

Re-opening just so I can review this when I get some time,.

**Comment by fisharebest** [comment]
This issue was fixed some time ago.  Closing.
