### ISSUE TITLE
The countries are printed a number of times in the Geographic data AdminPlaces - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1798]
I see countries a number of times in the Places list -> Geographic data -  Contro panel / Module administration / Open Street Maps (Geographic data) - Module configuration.
What should I do?

Sample:
/index.php?route=admin-module&module=openstreetmap&action=AdminPlaces&inactive=0
![2018-07-19_10-26-47](https://user-images.githubusercontent.com/5202996/42927819-4ee32b6c-8b3e-11e8-9800-69df6a3dee14.jpg)

**Comment by fisharebest** [comment]
I've also seen this.  I think the code is fetching each place from each tree.
