### ISSUE TITLE
The links Map module preferences and Geographic data give "Module not found" - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1801]
The links "Map module preferences" and "Geographic data" give "Module not found" for index.php?route=admin-module&module=**pedigree-map**&action=AdminPlaces in Pedigree map and index.php?route=admin-module&module=**places**&action=AdminPlaces in the indi Places tab. The link modules are wrong.

The link works from the Place hierarchy Places to index.php?route=admin-module&module=**openstreetmap**&action=AdminPlaces

**Comment by fisharebest** [comment]
The openstreetmap module was written by Dave Drury, and I'm in the middle of moving parts of it to the core code.

These are dummy placeholders until the code is moved.

**Comment by fisharebest** [comment]
These have been fixed
