### ISSUE TITLE
Openstreetmap difference display counter

### ISSUE THREAD

**Issue by Fa10175** [fisharebest/webtrees#1802]
I know it's a new module to replace googlemap but we can see differences in the counters see below

![openstreetmap-counter](https://user-images.githubusercontent.com/10681601/42986676-c54b083e-8bf6-11e8-99e2-67dda428e8b0.jpg)

**Comment by fisharebest** [comment]
The count on the right is taken from the database and ignores privacy.

The table on the bottom shows details of individuals, and includes privacy.

We cannot do privacy checks on all individuals in large trees.  So, perhaps we should not show the total on the right?
