### ISSUE TITLE
Individual Places map markers - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1805]
How can one show a death/burial marker that does not look like a cross? 
For instance a grave without a cross:
![2018-07-22_23-51-34](https://user-images.githubusercontent.com/5202996/43050004-3f74b76c-8e0a-11e8-966f-dd7708aff156.jpg)

**Comment by ddrury** [comment]
The marker icons are taken from the Font Awesome collection, if you can find anything [here](https://fontawesome.com/icons?d=gallery&m=free) that is more appropriate then let us know and we'll probably use it.

**Comment by melizaa** [comment]
How can I replace Font Awesome icons by own icons?

**Comment by ddrury** [comment]
Not easy at the moment! The fontawesome icon is defined in app/factlocation.php::getIconDetails and the markup is created in javascript but I don't know where that is to be found since Greg's restructure. 
Perhaps we could create the icons in views - Greg, what do you think?

**Comment by ddrury** [comment]
How about the fontawesome icon for either Church or Monument (my preference) - I realise that neither are ideal but maybe better than the current choice

**Comment by fisharebest** [comment]
...or maybe just lose the beautifymarker/font-awesome icons, and use the default leafletjs map markers?

**Comment by fisharebest** [comment]
There are some fairly "standard" symbols used in genealogy.

See:
https://www.tamurajones.net/GenealogySymbols.xhtml
http://wiki-en.genealogy.net/Symbols_and_Signs
https://www.geni.com/projects/Abbreviations-Acronyms-for-Genealogy-The-Accepted/3096

Birth: asterisk - `*`
Baptism: tilde - `~`
Death: plus or dagger `+` or `†`
Burial: square brackets -`[]`

I'm going to put this issue on hold for a while and come back to it later.

**Comment by fisharebest** [comment]
I have updated the icons with more neutral options.  e.g.

* death - a diagonal cross (as used for "close") elsewhere on the site.
* marriage - a double-circle, instead of male+female symbol.

They are defined in `app/Module/PlacesModule.php`.

To suggest an new / different icon/color, raise another issue.
