### ISSUE TITLE
Media uploaded to sub folder loses file name

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1810]
Create folder under media e.g. living
Upload of a image file, via the individual/media page, results in file name being lost and system generated name used even though not checked.

For what its worth, uploading on the admin page and then linking seems to work ok.

**Comment by fisharebest** [comment]
If you try to upload a file with the same folder/name as an existing file, then rather than overwrite it, webtrees will create a unique name.

Are you sure the folder/filename you chose was not already in use?

**Comment by makitso** [comment]
Possibly, I will clean the system up and try again.

**Comment by makitso** [comment]
Problem went away on clean install
