### ISSUE TITLE
Can not load media to sub folders

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1811]
Have sub folder in Media.  Trying to load media, from the individual/media page, into that sub folder fails, it is loaded instead into the Media folder.

**Comment by fisharebest** [comment]
I just tried this, and it worked OK.

* Individual page, click the "Add a media object" link.
* On the "add media object" page, clicked the "+" to upload a new media object.
* A modal dialog appears.  In the section "filename on server", I typed a foldername into the "folder" field and left the filename field empty (i.e. "same as uploaded file").

The result is a new media object, with its original filename, in the new folder that I entered.

**Comment by wkitty42** [comment]
On 08/09/2018 04:12 AM, Greg Roach wrote:
> I just tried this, and it worked OK.
> 
>   * Individual page, click the "Add a media object" link.
>   * On the "add media object" page, clicked the "+" to upload a new media object.
>   * A modal dialog appears. In the section "filename on server", I typed a
>     foldername into the "folder" field and left the filename field empty (i.e.
>     "same as uploaded file").
> 
> The result is a new media object, with its original filename, in the new folder 
> that I entered.


just asking for clarity: did you enter a folder name that already existed or did 
webtrees create the folder for you because it did not exist?

**Comment by makitso** [comment]
@wkitty42  - I had an existing folder media/living.

**Comment by wkitty42** [comment]
right, i was checking with @fisharebest to see what his test had...

**Comment by makitso** [comment]
OK, did a clean install, cleaned out the data folder and now it works.  
Question:  Is it advisable to delete the thumbnail-cache folder?

**Comment by fisharebest** [comment]
>  Is it advisable to delete the thumbnail-cache folder?

In theory, it shouldn't matter.
If you delete it, then it will be recreated next time it is needed.

I plan a small housekeeping job that periodically scans this folder and deletes old files.

**Comment by makitso** [comment]
I went to my production site and looked at the thumbnail-cache folder.  It was huge, over 300MB.  I have deleted it and there appears to be no negative side effect.
