### ISSUE TITLE
Media question - Dev version

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1812]
Although I use one media subfolder /media/living for media for living people.  However, I am not sure how this all works.

If you create a sub folder e.g. /media/living should you also create a separate thumbnail folder e.g. /media/thumbnail/living?

When you upload a median item, via the individual\media page, and want it to go to the subfolder, will webtrees create a thumbnail file and if so where?

**Comment by fisharebest** [comment]
"Thumbnail" can mean different things.

1) A replacement image for a non-image.  e.g. a photo to represent and audio file.
2) A smaller version of a larger image.

For (1), we now support the GEDCOM system of having a media object that contains multiple media files.  When displaying a media object, webtrees will use the first media file that contains an image.

For (2), we generate many different scaled images at different sizes.  So, the image in a chart-box will be a smaller version than the main image on an individual page.

(2) is entirely internal to webtrees, and users are not expected to get involved with it.  Currently, they are stored in the folder /data/thumbnail-cache, but this may change.
