### ISSUE TITLE
Managing media files is very difficult and time consuming

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1817]
1.On the Admin/Manage media page you can select a Media object
       That brings up the page to manage this object.
3.If one selects edit and uses the Delete option the object is or should be deleted.
       However, if one then looks at the Manage media Unused files, the deleted file still exists.
4.If one then deletes the specific filename webtrees says its deleted.  However, if one looks in the thumbnail-cache the files are still there.

**Comment by fisharebest** [comment]
3) Is this the same issue as #1815?  (i.e. deleting a media object/media file only deletes the GEDCOM data - it does not remove the corresponding file from the filesystem.)

4) Ignore the thumbnail-cache folder.  This is for internal use only.

**Comment by makitso** [comment]
#3 is different than #1815.  While not a bug it nevertheless is time consuming and requires multiple steps to fully delete the media object and file.
#4 This is for internal use only.....     However, if one delete the "object" and "file" and then tries to add a media object, webtrees still remembers the deleted file name and thus assigns a system generated file name. sigh!

**Comment by fisharebest** [comment]
> However, if one delete the "object" and "file" and then tries to add a media object, webtrees still remembers the deleted file name and thus assigns a system generated file name. sigh!

I can't reproduce this.

I deleted a media object.
I deleted the media file (from the control panel, unused media list).

I created a new media object using a file with the same name.  The file was created with the specified name.
