### ISSUE TITLE
housekeeping.php throws error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1823]
Working on media items and noticed this error in the log. 

RuntimeException: SplFileInfo::getType(): Lstat failed for /data/thumbnail-cache/3a96fede85e109e0a3d5bc4a65651700/Riggi-Judy.jpg in file /vendor/league/flysystem/src/Adapter/Local.php on line 494 Stack trace: 1. RuntimeException->() /vendor/league/flysystem/src/Adapter/Local.php:494 2. SplFileInfo->getType() /vendor/league/flysystem/src/Adapter/Local.php:494 3. League\Flysystem\Adapter\Local->mapFileInfo() /vendor/league/flysystem/src/Adapter/Local.php:437 4. League\Flysystem\Adapter\Local->normalizeFileInfo() /vendor/league/flysystem/src/Adapter/Local.php:288 5. League\Flysystem\Adapter\Local->listContents() /vendor/league/flysystem/src/Filesystem.php:271 6. League\Flysystem\Filesystem->listContents() /app/Services/HousekeepingService.php:543 7. Fisharebest\Webtrees\Services\HousekeepingService->deleteOldCacheFiles() /app/Http/Middleware/Housekeeping.php:91 8. Fisharebest\Webtrees\Http\Middleware\Housekeeping->runHousekeeping() /app/Http/Middleware/Housekeeping.php:76 9. Fisharebest\Webtrees\Http\Middleware\Housekeeping->handle() /index.php:316 10. Fisharebest\Webtrees\{closure}() /index.php:324 11. call_user_func() /index.php:324

**Comment by fisharebest** [comment]
This could be a race condition.  i.e. two scripts try to delete old files.  Both find the same file.  Only one will be able to delete it.
