### ISSUE TITLE
French text with a space - &nbsp;

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1825]
In French I see the block text "Who is online" text as "Qui est en ligne`&nbsp;`?"
I see on the site also "Voulez-vous vraiment supprimer cet élément`&nbsp;`?" and "SDJ`&nbsp;`: date du scellement de l’enfant"

Other texts have the same issue.

**Comment by melizaa** [comment]
![french2018-08-13_20-27-29](https://user-images.githubusercontent.com/5202996/44049697-7eae3554-9f3d-11e8-8560-4bec58b1893d.jpg)

**Comment by melizaa** [comment]
The &nbsp; text is not printed in my issue text - I see it on the webtrees pages.

**Comment by melizaa** [comment]
**Please re-open**

I see still in French "Voulez-vous vraiment supprimer cet élément&nbsp;?" for "Are you sure you want to delete this fact?" when I try to delete a fact.

**Comment by melizaa** [comment]
I see it with entity "& and nbsp and ;"

**Comment by fisharebest** [comment]
This will get fixed when we replace `class FontAwesome` with views.

**Comment by fisharebest** [comment]
This will get fixed when we replace `class FontAwesome` with views.

**Comment by fisharebest** [comment]
This
