### ISSUE TITLE
Blocks print outside the page - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1826]
At least in Finnish, Estonian, French, Greek and Catalia the On this day and Upcoming events right hand side blocks print outside the page. In Spanish the right side margin is too narrow.

In čeština the Yahrzeiten right hand side block prints outside the page.

In Spanish the main messages block prints outside the page.

etc.

![2018-08-13_20-26-37](https://user-images.githubusercontent.com/5202996/44049654-5ecdc542-9f3d-11e8-9d4e-f22eb7de676d.jpg)

**Comment by makitso** [comment]
Unfortunately, this happens on several right section blocks with different languages.  The vendor framework has the .container max width set at 1140px for large screens.

There are several css ways to deal with this by adding code to the common style.css to override the vendor.css defaults:

1.  Set .container’s max width to 1200 over
2.  Reduce the left and right padding on the col* from 15px to 5px
3.  Modify each small block to either have a horizontal scroll bar or hide the overflow.

**Comment by fisharebest** [comment]
Or show fewer details.
Or not use a tabular layout
...

**Comment by makitso** [comment]
> Or show...
True, but that would require some redesign and were now in alpha mode.

**Comment by makitso** [comment]
Do you want me to submit a change to add horizontal scroll bars to each of these small block displays?

**Comment by fisharebest** [comment]
Since i plan to review amd update the module interface we can add a param to tell the block whete it is beimg drawn so it can show teduced conyent pr a different layout
