### ISSUE TITLE
Critical - Today's github pull results in home page not loading

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1827]
[Mon Aug 13 15:54:07.120415 2018] [php7:error] [pid 16609] [client 127.0.0.1:47064] PHP Fatal error:  Uncaught TypeError: Return value of Fisharebest\\Webtrees\\Http\\Controllers\\HomePageController::Fisharebest\\Webtrees\\Http\\Controllers\\{closure}() must be of the type boolean, object returned in /var/www/app/Http/Controllers/HomePageController.php:699\nStack trace:\n#0 [internal function]: Fisharebest\\Webtrees\\Http\\Controllers\\HomePageController->Fisharebest\\Webtrees\\Http\\Controllers\\{closure}('html')\n#1 /var/www/app/Http/Controllers/HomePageController.php(700): array_map(Object(Closure), Array)\n#2 /var/www/app/Http/Controllers/HomePageController.php(652): Fisharebest\\Webtrees\\Http\\Controllers\\HomePageController->filterActiveBlocks(Array, Array)\n#3 /var/www/app/Http/Controllers/HomePageController.php(207): Fisharebest\\Webtrees\\Http\\Controllers\\HomePageController->getBlocksForTreePage(1, 2, 'main')\n#4 [internal function]: Fisharebest\\Webtrees\\Http\\Controllers\\HomePageController->treePage(Object(Fisharebest\\Webtrees\\Tree))\n#5 /var/www/app/Resolver.php(83): ReflectionMethod->invoke(Object(Fisharebest\\Webtrees\\Http\\Co in /var/www/app/Http/Controllers/HomePageController.php on line 699

**Comment by fisharebest** [comment]
Fixed in  5d42b1a52
