### ISSUE TITLE
Fatal Error when editing name of persons on tree

### ISSUE THREAD

**Issue by foxandfigs** [fisharebest/webtrees#1834]
> Fatal error: Uncaught ArgumentCountError: Too few arguments to function Fisharebest\Webtrees\Http\Controllers\EditGedcomRecordController::updateFact(), 1 passed in /Users/username/Sites/webtrees/app/Http/Controllers/EditIndividualController.php on line 622 and exactly 2 expected in /Users/username/Sites/webtrees/app/Http/Controllers/EditGedcomRecordController.php:390 Stack trace: #0 /Users/username/Sites/webtrees/app/Http/Controllers/EditIndividualController.php(622): Fisharebest\Webtrees\Http\Controllers\EditGedcomRecordController->updateFact(Object(Symfony\Component\HttpFoundation\Request)) #1 [internal function]: Fisharebest\Webtrees\Http\Controllers\EditIndividualController->editNameAction(Object(Symfony\Component\HttpFoundation\Request)) #2 /Users/username/Sites/webtrees/app/Resolver.php(83): ReflectionMethod->invoke(Object(Fisharebest\Webtrees\Http\Controllers\EditIndividualController), Object(Symfony\Component\HttpFoundation\Request)) #3 /Users/username/Sites/webtrees/index.php(321): Fisharebest\Webtrees\Resolver-> in /Users/username/Sites/webtrees/app/Http/Controllers/EditGedcomRecordController.php on line 390

I'm probably missing something obvious. How do I fix this?

**Comment by makitso** [comment]
I think I saw that Greg was going on holiday so it might be a bit before he can look at this.  If it's critical you can carefully edit the gedcom

**Comment by fisharebest** [comment]
I've got very limited internet access.  The phone signal comes and goes with the weather...

**Comment by foxandfigs** [comment]
Ack, I know what that's like! No worries, shall have a plod around and see what I can do then, it's nothing critical.

**Comment by fisharebest** [comment]
Just update to the latest dev code.

FYI, the auto-upgrade is broken in alpha.1, but will work in alpha.2

**Comment by foxandfigs** [comment]
Thank you!
