### ISSUE TITLE
2.0 - Internet Explorer V11 has poor support for flex this displays wrong

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1839]
There are still a lot of people using IE 11 especially since Edge is not available on Windows 7.  IE11 has spotty support for flex blocks.  As such, the  main-container is not positioned correctly - see below.  This hack seems to fix this and does not impact MS Edge:

/*  Hack to allow IE11 to work with a bit better with flex  */
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
    .wt-main-container {padding-top: 4em;}
}

![image](https://user-images.githubusercontent.com/5147603/44371906-25bd1b00-a496-11e8-9f89-5498220ef81a.png)

**Comment by makitso** [comment]
As I said, I carry the local mod on my production site. 
I still see a lot of Win7 on my client PC's.  And with older folks, they often use the default browser 😕

So, what do you want to do with the issue -- close it?

**Comment by fisharebest** [comment]
I need to find out how to get webpack and babel working.

I spent most of yesterday working on it.  It should be possible.  This is what these tools are designed to do.  I can get it to apply the polyfills, or merge the libraries, but not both at the same time.

**Comment by fisharebest** [comment]
This (and any other) IE hacks now have a home in `/resources/css/_base.css`
