### ISSUE TITLE
Stable Release update

### ISSUE THREAD

**Issue by boydhako** [fisharebest/webtrees#1840]
Anybody know if there's a more recent stable release out? The most recent one I'm seeing is version 1.7.9, released 23 December 2016.

If not, any song and dance I gotta do to get it working in a sub-directory? I keep getting a 500 error when I git clone it and input the index.php url.

**Comment by fisharebest** [comment]
1.7.10 was released last week.  It contains some compatibility fixes for MySQL 8.
It also contains some updates for PHP 7.1 and 7.2.

> to get it working in a sub-directory? 

Nothing special is required.  The demo server runs webtrees in a subdirectory.

> I keep getting a 500 error

See https://webtrees.github.io/faq/500

> git clone it

Start with getting a stable release (1.7.9 or 1.7.10) release working first.  Then think about using the development code.

**Comment by boydhako** [comment]
What's the URL? The site needs to be updated.



Domo,

Boyd H. Ako


boyd.hanalei.ako@gmail.com
(424) 244-9653
https://www.boydhanaleiako.me

“Coming together is a beginning. Keeping together is progress. Working together is success.” -Henry Ford

PGP/GPG Public Key: https://sks-keyservers.net/pks/lookup?op=get&search=0xC58073B21618F134

**Comment by fisharebest** [comment]
> The site needs to be updated.

I know.  I've looked at the site a couple of times (it runs Joomla) and can't work out how to edit the home page.  It's been a while since I needed to update it, and I forget how to do it...

**Comment by makitso** [comment]
Would you like some help?

**Comment by fisharebest** [comment]
Yes please.

I've looked all over the admin pages, but can't find the way to edit this.

**Comment by makitso** [comment]
Have you changed the un/PW to the back end joomla system?  If so, email me login info.

**Comment by fisharebest** [comment]
I just visit https://www.webtrees.net/administrator/ with my usual site username/password.

According to the users page, you are a "super user".

**Comment by boydhako** [comment]
Just do the release on github via the read me. Aside from the demo, you can put everything in github.



Domo,

Boyd H. Ako


boyd.hanalei.ako@gmail.com
(424) 244-9653
https://www.boydhanaleiako.me

“Coming together is a beginning. Keeping together is progress. Working together is success.” -Henry Ford

PGP/GPG Public Key: https://sks-keyservers.net/pks/lookup?op=get&search=0xC58073B21618F134

**Comment by boydhako** [comment]
@fisharebest 
> See https://webtrees.github.io/faq/500
>     git clone it
```
[22-Aug-2018 05:06:05 America/Denver] PHP Warning:  Unsupported declare 'strict_types' in /home2/boydhana/public_html/kaupu/webtrees/index.php on line 16
[22-Aug-2018 05:06:05 America/Denver] PHP Parse error:  syntax error, unexpected '?' in /home2/boydhana/public_html/kaupu/webtrees/index.php on line 234
[22-Aug-2018 05:06:22 America/Denver] PHP Warning:  Unsupported declare 'strict_types' in /home2/boydhana/public_html/kaupu/webtrees/index.php on line 16
[22-Aug-2018 05:06:22 America/Denver] PHP Parse error:  syntax error, unexpected '?' in /home2/boydhana/public_html/kaupu/webtrees/index.php on line 234
```
> Start with getting a stable release (1.7.9 or 1.7.10) release working first. Then think about using the development code.

I tried the release on the site; before the site was updated. and that worked fine.

**Comment by fisharebest** [comment]
@boydhako - These error messages suggest that you are using PHP 5.x

webtrees 2.0 requires PHP 7.0 - PHP 7.2.
Also, it is still only an alpha release.

webtrees 1.7.9 was written for PHP 5.3 - PHP 7.0.

1.7.10 fixed *some* of the compatibility issues with PHP 7.1 and PHP 7.2
1.7.11 (when it is released) will fix some more.

Since you are using PHP 5, just install webtrees 1.7.10.

**Comment by boydhako** [comment]
@fisharebest That is correct... Apparently Bluehost see's PHP 7 as a "Beta". No eye deer why.

**Comment by fisharebest** [comment]
The site has been updated, and a new release has been issued.
