### ISSUE TITLE
2.0 - Family Report - PDF generates error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1841]
Family report.  First select HTML output, everything looks good. Then select PDF output and this error.

** Update ** This may be data driven since I can't reproduce it on the demo web site.  However, on my Git dev site I get the error if there is nothing entered in the form and then select PDF as output.

ErrorException: A non-numeric value encountered in file /app/Report/ReportParserGenerate.php on line 636
Stack trace:
  1. ErrorException->() /app/Report/ReportParserGenerate.php:636
  2. Fisharebest\Webtrees\{closure}() /app/Report/ReportParserGenerate.php:636
  3. Fisharebest\Webtrees\Report\ReportParserGenerate->gedcomStartHandler() /app/Report/ReportParserGenerate.php:172
  4. Fisharebest\Webtrees\Report\ReportParserGenerate->startElement() [internal]:0
  5. xml_parse() /app/Report/ReportParserBase.php:57
  6. Fisharebest\Webtrees\Report\ReportParserBase->__construct() /app/Report/ReportParserGenerate.php:143
  7. Fisharebest\Webtrees\Report\ReportParserGenerate->__construct() /app/Http/Controllers/ReportEngineController.php:262
  8. Fisharebest\Webtrees\Http\Controllers\ReportEngineController->reportRun() [internal]:0
  9. ReflectionMethod->invoke() /app/Resolver.php:85
 10. Fisharebest\Webtrees\Resolver->dispatch() /index.php:322
 11. Fisharebest\Webtrees\{closure}() /app/Http/Middleware/CheckForMaintenanceMode.php:48
 12. Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->handle() /index.php:317
 13. Fisharebest\Webtrees\{closure}() /app/Http/Middleware/PageHitCounter.php:107
 14. Fisharebest\Webtrees\Http\Middleware\PageHitCounter->handle() /index.php:317
 15. Fisharebest\Webtrees\{closure}() /app/Http/Middleware/Housekeeping.php:72
 16. Fisharebest\Webtrees\Http\Middleware\Housekeeping->handle() /index.php:317
 17. Fisharebest\Webtrees\{closure}() /index.php:325
 18. call_user_func() /index.php:325

**Comment by fisharebest** [comment]
I can reproduce the error if I try to run the report without specifying a family.

In this case, an empty GEDCOM is being passed to some code, which isn't expecting an empty string.

Are you running the report for an existing family, or are you leaving the family field empty?

**Comment by makitso** [comment]
Blank
