### ISSUE TITLE
relationship generates an empty page

### ISSUE THREAD

**Issue by johnds123** [fisharebest/webtrees#1845]
I just installed 1.7.10 in order to get rid of the problem related to the each() function and PHP 7.2.

Now instead of getting PHP errors I get a blank page with just the normal header and footer.
The Apache logs has no errors. I don't see any erros on the page itself either.
Please provide some guidance for what to look for.

Well I actually have these three errors:

Loading failed for the <script> with source “blob:http://<my webserver's hostname>/85c8237e-5cf8-49c3-8776-a9f5d3a037fe”. relationship.php:1
Loading failed for the <script> with source “blob:http://<my webserver's hostname>/3f455b5a-0474-4ad8-b93e-5cab27caca2a”. relationship.php:1
Loading failed for the <script> with source “http://<my webserver's hostname>/packages/jquery-2.2.1/jquery.min.js”. relationship.php:1 

Error loading this URI: Could not load the source for blob:http://<my webserver's hostname>/1dbc7040-8afa-4416-8072-af60dc1c9242.
[Exception... "Failed to open input source 'file:////<my webserver's hostname>/1dbc7040-8afa-4416-8072-af60dc1c9242'"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://devtools/shared/base-loader.js -> resource://devtools/shared/DevToolsUtils.js :: mainThreadFetch :: line 645"  data: yes]
Stack: mainThreadFetch@resource://devtools/shared/base-loader.js -> resource://devtools/shared/DevToolsUtils.js:645:5
_getSourceText/<@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/source.js:410:27
Line: 645, column: 0

Error loading this URI: Could not load the source for blob:<my webserver's hostname>/2c1579a1-cc4c-457e-93b7-5af4246e5f74.
[Exception... "Failed to open input source 'file:////<my webserver's hostname>/2c1579a1-cc4c-457e-93b7-5af4246e5f74'"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://devtools/shared/base-loader.js -> resource://devtools/shared/DevToolsUtils.js :: mainThreadFetch :: line 645"  data: yes]
Stack: mainThreadFetch@resource://devtools/shared/base-loader.js -> resource://devtools/shared/DevToolsUtils.js:645:5
_getSourceText/<@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/source.js:410:27
Line: 645, column: 0

**Comment by fisharebest** [comment]
> Please provide some guidance for what to look for.

Can you post the URL of your site?

**Comment by johnds123** [comment]
I was warned not to do so.
Here it is in pieces
gedview
hovedpuden
dk

**Comment by fisharebest** [comment]
Are there any error messages in the webtrees error log?

Control panel -> Website -> Website logs -> type="error" -> Search

**Comment by johnds123** [comment]
Thanks for pointnig to this error log. There is of course an error relating to each().

/var/www/html/webtrees/app/Controller/RelationshipController.php:77 The each() function is deprecated. This message will be suppressed on further calls
#0 unknown:unknown ErrorException("The each() function is deprecated. This message will be suppressed on further calls")
#1 /app/Controller/RelationshipController.php:77 each([array])
#2 /relationship.php:56 calculateRelationships([Individual I121@1], [Individual I1@1], 0, false)

**Comment by fisharebest** [comment]
OK.  This bug has already been fixed.

Wait for the next release - or change this one line:

https://github.com/fisharebest/webtrees/commit/23cbb7db2c340c86173433f532c198b47d63e6ab#diff-196d75d0e9ec4887a1dd92a002530a1b

**Comment by johnds123** [comment]
Thanks for your support. Now it works again.
