### ISSUE TITLE
How to add a route of a new module?

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#1846]
How to add a route of a new module? It seems only possible to use route=module? But no chance to set up a individual controller?

**Comment by fisharebest** [comment]
Eventually, I want modules to be able to register global routes (and hence replace core functions).

Until then, all module routes go through `route=module`.

Choose a route name - e.g. 'MyRoute', and create a function to receive it.

For HTTP `GET` requests, create `MyModule::getMyRouteAction()`.
For HTTP `POST` requests, create `MyModule::postMyRouteAction()`.

Generate a URL for this route using `route('module', ['module' => 'my_module', 'action' => 'MyRoute'])`

These functions are called using the dependency injection system, so you can specify parameters such as Request, Tree, User, etc.

**Comment by magicsunday** [comment]
Thanks
