### ISSUE TITLE
Upgrade 1.7.09 -> 1.7.10: A non well formed numeric value…

### ISSUE THREAD

**Issue by Amgine0** [fisharebest/webtrees#1867]
In vendor/pclzip/:

* Download https://github.com/fisharebest/webtrees/releases/download/1.7.10/webtrees-1.7.10.zip…
31,793 KB were downloaded in 6.56 seconds.
* Unzip webtrees-1.7.10.zip to a temporary folder…/raid/www/webtrees/includes/session.php:193 /raid/www/webtrees/vendor/pclzip/pclzip/pclzip.lib.php:1797 A non well formed numeric value encountered #0 /vendor/pclzip/pclzip/pclzip.lib.php:1797 ErrorException("/raid/www/webtrees/vendor/pclzip/pclzip/pclzip.lib.php:1797 A non well formed numeric value encountered") #1 /vendor/pclzip/pclzip/pclzip.lib.php:783 privOptionDefaultThreshold([array]) #2 /admin_site_upgrade.php:296 extract(77001, '/raid/www/webtrees/data/webtre…', 77003, 'webtrees', 77016)

**Comment by fisharebest** [comment]
This is a known bug.  It has been reported (and answered) many times on the forum.

It will be fixed in 1.7.11

If you use the option "convert to French calendar", then I recommend that you wait for 1.7.11.

**Comment by Amgine0** [comment]
Did not see it as an open issue here. Did not look there.

**Comment by mpwt** [comment]
Switch for the automatic update to PHP 7.0 than it should work as aspected. It seems that you use PHP 7.1 or higher. 
For use of PCLZIP with 1.7.10 and PHP 7.1 or 7.2 look at the changes since 12.08.2018 on https://github.com/fisharebest/webtrees/tree/1.7. There are to fixes for zip and to others ...

**Comment by fisharebest** [comment]
webtrees-1.7.11 contains a fix for this issue.

I have also written an FAQ article: https://webtrees.github.io/faq/upgrade-numeric

**Comment by Amgine0** [comment]
* Unzip webtrees-1.7.11.zip to a temporary folder…/raid/www/webtrees/includes/session.php:193 /raid/www/webtrees/vendor/pclzip/pclzip/pclzip.lib.php:1797 A non well formed numeric value encountered #0 /vendor/pclzip/pclzip/pclzip.lib.php:1797 ErrorException("/raid/www/webtrees/vendor/pclzip/pclzip/pclzip.lib.php:1797 A non well formed numeric value encountered") #1 /vendor/pclzip/pclzip/pclzip.lib.php:783 privOptionDefaultThreshold([array]) #2 /admin_site_upgrade.php:296 extract(77001, '/raid/www/webtrees/data/webtre…', 77003, 'webtrees', 77016)

**Comment by mpwt** [comment]
Why do you not read the FAQ article or my post above? The automatic update not work with PHP >=7.1 and webtrees 1.7.10.

**Comment by Amgine0** [comment]
I **can** fix it for my own installation. This does not fix this bug. Furthermore, although a bug fix was applied for 1.7.11, it appears to not resolve the bug.

It is important for the developer to know if the issue is actually resolved.

**Comment by fisharebest** [comment]
> although a bug fix was applied for 1.7.11, it appears to not resolve the bug.

When we upgrade from `1.7.10` to `1.7.11`, we use the code from `1.7.10` (which has the problem).

There is nothing I can do to fix this automatically :-(

So, the users must fix the problem themselves.  There are 3 options.  These are on the FAQ.

**Comment by Amgine0** [comment]
Ah, I misunderstood your comment "webtrees-1.7.11 contains a fix for this issue."

**Comment by fisharebest** [comment]
Sorry if I wasn't clear.

Once you have `1.7.11`, the upgrade will start working.

**Comment by Amgine0** [comment]
No, it was clear. I was just self-focused, not thinking through what it meant in practice.
