### ISSUE TITLE
Sundanese language

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#1883]
There is a request to add definitions for the Sundanese language - `su`.

This language is not included in our localization library, so it needs to be added there.

See https://github.com/fisharebest/localization/issues/4

First, we need answers to some questions;

1) what are the plural rules?
2) what is the default script? (Latin or Sundanese characters)

**Comment by fisharebest** [comment]
The original requester hasn't replied to several emails, so I'll close this.

**Comment by nugeo** [comment]
Thank you for responding my request, I hope the Sundanese language can be added to webtrees, you can see the Sundanese character in here : 
https://konversiaksarasunda.blogspot.com
https://drive.google.com/file/d/0B4MDqeuIhvKdb2dtdzRTdm9xcEE/view

**Comment by fisharebest** [comment]
Sundandese and Javanese have both been added to webtrees.

You can add translations at https://translate.webtrees.net/projects/webtrees/webtrees/
