### ISSUE TITLE
2.0 - Download gedcom after adding to clippings cart is not working

### ISSUE THREAD

**Issue by Tanhueco** [fisharebest/webtrees#1884]
I tried this on 2 fresh installs.  After adding an individual and descendants to the clipping cart and downloading the gedcom file using any of the available privacy options and UTF conversion, it takes me to a dead page "The page isn't working - unable to handle this request" in Chrome browser.

**Comment by fisharebest** [comment]
@Tanhueco I cannot reproduce this error, and nobody else has reported it.

I cannot fix this without more information.

Can you provide the error logs?

**Comment by fisharebest** [comment]
Without more information, I am unable to help.

If you are still having this problem, please open another issue.
