### ISSUE TITLE
2.0 - Wrong family tree deleted

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1891]
Have two trees.  Go to Manage family trees and select the top tree for deleting.  After delete the second tree was deleted (tree2).  If you mouse over the delete link for the Johannsen tree,  the actual link is for  tree2.  

![image](https://user-images.githubusercontent.com/5147603/45160528-8c347f80-b19e-11e8-845e-26cea582cf73.png)

**Comment by fisharebest** [comment]
The "mouseover" is a red-herring - This is a JS onclick event, and all show the current URL.  You can see this on some of the "add unlinked ..." links.

But you're right about the page deleting the wrong tree.  I'll post a fix asap.
