### ISSUE TITLE
2.0 The server’s time limit has been reached on renumbering

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1892]
Have 132 individuals in the duck database.  Went to renumber on the admin page and got this error.

**Comment by fisharebest** [comment]
This is not really an error.

The process can take a long time.  If we are approaching the the time limit, we return this message, and the user is expected to click the "continue" button to process the remaining records.

The number of records should go down each time.  On my dev system, I had approx 2000, then 1500, then 1000, then 500, then 0.

OR - are you saying that even when you do this, there are always 132 records still to be processed.

**Comment by makitso** [comment]
As soon as I press continue the error pops up immediately -- and I suspect processing stops.  I have waited and there is no other action.

**Comment by fisharebest** [comment]
What do you have for your PHP time limit?  Zero?

**Comment by makitso** [comment]
PHP version 7.2.7

; Maximum execution time of each script, in seconds
; http://php.net/max-execution-time
; Note: This directive is hardcoded to 0 for the CLI SAPI
max_execution_time = 30

**Comment by fisharebest** [comment]
OK- that's the PHP default.

But it is possible to override this in the webtrees control panel (and elsewhere).

i.e. you could have set it to zero in Control panel, Website preferences, PHP time limit

Can you check/confirm the value that you see in Control panel -> Server information

**Comment by makitso** [comment]
if I run phpinfo on the site it says:

![image](https://user-images.githubusercontent.com/5147603/45223854-42ff3100-b26d-11e8-88fb-e8fbf6e6ce4b.png)

However, if use webtrees and Server information is says:
![image](https://user-images.githubusercontent.com/5147603/45223943-8f4a7100-b26d-11e8-97fd-b53c6d887e76.png)

So, why or how might the value of zero be changed?

**Comment by makitso** [comment]
OK, in the website preferences it was set to 0.  I can't recall changing this :-(
