### ISSUE TITLE
2.0.0 Alpha

### ISSUE THREAD

**Issue by meljturner** [fisharebest/webtrees#1895]
In testing the Alpha release I get errors like the one below when updating an individual record, usually when I am not updating every field. This is repeatable; 

Edit Individual record-> change one field -> click save

PHP: 7.2.9 Apache 2.4.34 MacOS 10.13.6 Safari 11.1.2

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Fisharebest\Webtrees\Http\Controllers\EditGedcomRecordController::updateFact(), 1 passed in /Library/WebServer/Documents/webtrees2/app/Http/Controllers/EditIndividualController.php on line 622 and exactly 2 expected in /Library/WebServer/Documents/webtrees2/app/Http/Controllers/EditGedcomRecordController.php:390 Stack trace: #0 /Library/WebServer/Documents/webtrees2/app/Http/Controllers/EditIndividualController.php(622): Fisharebest\Webtrees\Http\Controllers\EditGedcomRecordController->updateFact(Object(Symfony\Component\HttpFoundation\Request)) #1 [internal function]: Fisharebest\Webtrees\Http\Controllers\EditIndividualController->editNameAction(Object(Symfony\Component\HttpFoundation\Request)) #2 /Library/WebServer/Documents/webtrees2/app/Resolver.php(83): ReflectionMethod->invoke(Object(Fisharebest\Webtrees\Http\Controllers\EditIndividualController), Object(Symfony\Component\HttpFoundation\Request)) #3 /Library/WebServer/Documents/webtrees2/index.p in /Library/WebServer/Documents/webtrees2/app/Http/Controllers/EditGedcomRecordController.php on line 390
--

**Comment by fisharebest** [comment]
The error message suggests that your upgrade was incomplete, and that you are still using an older version of one of the files.

BTW, the `alpha.2` release now supports automatic updates, so you'll be able to upgrade to the next alpha/beta version automatically.

**Comment by fisharebest** [comment]
> 1 passed in /Library/WebServer/Documents/webtrees2/app/Http/Controllers/EditIndividualController.php on line 622

alpha.1, line 622:

`return (new EditGedcomRecordController)->updateFact($request);`

alpha.2, lines 621-622:

`return (new EditGedcomRecordController())->updateFact($request, $tree);`
`}`

Yup - you definitely still have at least one file from alpha.1.  Upload the files again.
