### ISSUE TITLE
2.0: Placename/Coordinate Import Errors

### ISSUE THREAD

**Issue by dbq-andersons** [fisharebest/webtrees#1896]
Trying to import the same placename/coordinate file I imported on 1.7.10 (ALLUSA_deci.txt).  Uploads fine and then this error pops a few seconds after upload is complete.

ErrorException: Undefined offset: -2 in file /app/Http/Controllers/AdminLocationController.php on line 383
Stack trace:
  1. ErrorException->() /app/Http/Controllers/AdminLocationController.php:383
  2. Fisharebest\Webtrees\{closure}() /app/Http/Controllers/AdminLocationController.php:383
  3. Fisharebest\Webtrees\Http\Controllers\AdminLocationController->importLocationsAction() [internal]:0
  4. ReflectionMethod->invoke() /app/Resolver.php:85
  5. Fisharebest\Webtrees\Resolver->dispatch() /index.php:324
  6. Fisharebest\Webtrees\{closure}() /app/Http/Middleware/CheckForMaintenanceMode.php:48
  7. Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->handle() /index.php:319
  8. Fisharebest\Webtrees\{closure}() /app/Http/Middleware/UseTransaction.php:46
  9. Fisharebest\Webtrees\Http\Middleware\UseTransaction->handle() /index.php:319
 10. Fisharebest\Webtrees\{closure}() /app/Http/Middleware/CheckCsrf.php:48
 11. Fisharebest\Webtrees\Http\Middleware\CheckCsrf->handle() /index.php:319
 12. Fisharebest\Webtrees\{closure}() /index.php:327
 13. call_user_func() /index.php:327

Thanks,

Bill Anderson

**Comment by fisharebest** [comment]
Can you give a link to this file?

**Comment by dbq-andersons** [comment]
Here's a link to where I got it.

https://www.webtrees.net/index.php/en/add-ons/download/5-gm-files/65-usa-places-all-in-one-large-file

I've attached the .zip file as well.

[allusa.zip](https://github.com/fisharebest/webtrees/files/2373158/allusa.zip)

Thanks,

Bill

**Comment by fisharebest** [comment]
I've fixed the code.  (It was looking for comma-separated values, not semicolon-separated values).

However, note that his file (all USA) is huge, and I had to set many of my PHP and MySQL settings to very high values in order to load it.

You may need to split this into smaller files (e.g. per state) and load them separately.

**Comment by dbq-andersons** [comment]
Gotcha.  Thanks for the advice and the support.

Cheers!

Bill
