### ISSUE TITLE
"Restrict to immediate family" not saved if individual is selected

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#1902]
Control panel =>  User administration => Edit the user => Restrict to immediate family 

I created a test user and assigned an existing individual to him. Now I tried to restrict his access according "Restrict to immediate family" but this seems never be saved. It remains on "no".

**Comment by fisharebest** [comment]
Is this condition backwards?

https://github.com/fisharebest/webtrees/blob/master/app/Http/Controllers/AdminUsersController.php#L423
