### ISSUE TITLE
2.0 - Default install sets Default theme as clouds

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1905]
Shouldn't the default theme be set to webtrees?

**Comment by fisharebest** [comment]
It should be webtrees.  Here's the line that sets it.

https://github.com/fisharebest/webtrees/blob/master/index.php#L282

I just tested a clean install, and the default theme was indeed webtrees.

Are you able to reproduce this issue?

**Comment by makitso** [comment]
Perhaps it's a display problem.  Clean install but no family tree created, display Website preferences:

![image](https://user-images.githubusercontent.com/5147603/45596598-04572e00-b973-11e8-97f5-f60af3ad73d9.png)

And, the site settings does not include the default theme:

![image](https://user-images.githubusercontent.com/5147603/45596608-2486ed00-b973-11e8-9753-683adb51ace8.png)

**Comment by fisharebest** [comment]
Thanks.  I see what you mean.
