### ISSUE TITLE
2.0 Admin Control panel throws error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1909]
This is kind of an obscure issue but....
Create new installation of webtrees
Sign on via Welcome to this website page
Do not create a tree but instead Go to Control panel:

![image](https://user-images.githubusercontent.com/5147603/45597012-77b06e00-b97a-11e8-94ed-20f8850e58f4.png)

Display is bad:
![image](https://user-images.githubusercontent.com/5147603/45597017-931b7900-b97a-11e8-89ca-03685b7297f8.png)

Apache Error Log:

![image](https://user-images.githubusercontent.com/5147603/45597022-9f9fd180-b97a-11e8-8d08-ebf819361668.png)

**Comment by fisharebest** [comment]
Can you confirm you have the latest code.

Line 243 of `admin/control-panel` is just `</a>`

**Comment by makitso** [comment]
> Line 243 of admin/control-panel is just </a>

Yes it is.  However, I was running this test in a VM with xubuntu 18.10 it is using PHP version 7.27 if that makes a difference.

**Comment by fisharebest** [comment]
OK, I can reproduce this - but get a different line number.

Lots of admin functions require a tree.  We shouldn't be able to use the control panel until we have created one.

**Comment by makitso** [comment]
agreed.

**Comment by fisharebest** [comment]
> Lots of admin functions require a tree

It seems that only a few functions require a tree.

* Stories/faq/batch-update modules
* Manage media

However, it is probably a good thing to keep the user on this page until they have created a tree.
