### ISSUE TITLE
Error while merging two trees

### ISSUE THREAD

**Issue by Art4** [fisharebest/webtrees#1912]
I'm using webtrees 1.7.11 with PHP 7.1 and have two trees. 
Tree A has 939 individuals.
Tree B has 2210 individuals.
I'm want to copy all individuals from tree A to tree B. Before starting I had to renumbering the individuals in tree A. That works find.
Next I tried to copy the individuals, so I chose "copy all individuals from tree A to tree 2". After clicking the button I got this error:

`[...]/app/Statement.php:82 SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'HEAD-3-0' for key 'PRIMARY' #0 /app/Statement.php:82 PDOException("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'HEAD-3-0' for key 'PRIMARY'") #1 /admin_trees_merge.php:160 execute([array]) `

What can I do to debug and find the reason?

**Comment by fisharebest** [comment]
1) Can you show me the contents of the GEDCOM `HEAD` record for each tree.

Tip: type "HEAD" in the search box at the top of the page.

2) Can you run the following SQL query

`SELECT * FROM wt_name WHERE n_id = 'HEAD';`

**Comment by Art4** [comment]
> Can you show me the contents of the GEDCOM HEAD record for each tree.

HEAD of tree A:

```
0 HEAD
1 SOUR webtrees
2 NAME webtrees
2 VERS 1.7.9
1 DEST DISKETTE
1 DATE 16 SEP 2018
2 TIME 22:44:29
1 GEDC
2 VERS 5.5.1
2 FORM Lineage-Linked
1 CHAR UTF-8
1 FILE kosmann
1 PLAC
2 FORM City, County, State/Province, Country
1 SUBM @SUBM@
```

HEAD of tree B:

```
0 HEAD
1 SOUR webtrees
2 NAME webtrees
2 VERS 1.7.9
1 DEST DISKETTE
1 DATE 16 SEP 2018
2 TIME 22:44:29
1 GEDC
2 VERS 5.5.1
2 FORM Lineage-Linked
1 CHAR UTF-8
1 FILE main
1 PLAC
2 FORM City, County, State/Province, Country
1 SUBM @SUBM@
```
> Can you run the following SQL query

Sure. For clarification:

- n_file:6 is tree A.
- n_file:3 is tree B.
- n_file:7 is another tree.

```
mysql> SELECT * FROM wt_name WHERE n_id = 'HEAD';
+--------+------+-------+--------+--------+--------+-----------+--------+--------+--------------------+--------------------+-------------------+-------------------+
| n_file | n_id | n_num | n_type | n_sort | n_full | n_surname | n_surn | n_givn | n_soundex_givn_std | n_soundex_surn_std | n_soundex_givn_dm | n_soundex_surn_dm |
+--------+------+-------+--------+--------+--------+-----------+--------+--------+--------------------+--------------------+-------------------+-------------------+
|      3 | HEAD |     0 | HEAD   |        |        | NULL      | NULL   | NULL   | NULL               | NULL               | NULL              | NULL              |
|      6 | HEAD |     0 | HEAD   |        |        | NULL      | NULL   | NULL   | NULL               | NULL               | NULL              | NULL              |
|      7 | HEAD |     0 | HEAD   |        |        | NULL      | NULL   | NULL   | NULL               | NULL               | NULL              | NULL              |
+--------+------+-------+--------+--------+--------+-----------+--------+--------+--------------------+--------------------+-------------------+-------------------+
3 rows in set (0.00 sec)

```

**Comment by Art4** [comment]
> The problem is caused by the HEAD records in the wt_name table. They should not exist.
> 
> You should be able to fix your problem by deleting these records - or by exporting/importing your data to a GEDCOM file.

I will try to delete these 3 records. Thank you.


> I cannot think how these records were created.
> 
> Do you know (approximately) the last time you imported these GEDCOM files?
> Perhaps these were created by a bug an an old version of webtrees?

The first changes in both trees were made at 2013-10-16. This should be the date I imported the files first time to webtrees. This must be webtrees 1.4.3.

**Comment by Art4** [comment]
I've deleted the 3 records and webtrees found ~1200 records where the x_ref ID must be renamed. I renamed all individuals and famalies again and started the next try to merge the trees. Now this error appears:

`[...]/app/Statement.php:82 SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'TRLR-3-0' for key 'PRIMARY' #0 /app/Statement.php:82 PDOException("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'TRLR-3-0' for key 'PRIMARY'") #1 /admin_trees_merge.php:160 execute([array]) `

**Comment by fisharebest** [comment]
> I assume I can delete these 3 records in table wt_name too?

Correct.

**Comment by Art4** [comment]
I deleted the 3 records with `TRLR` and webtrees again wanted to renumbering all indidivuals. I've done this again (now the 3rd time) and tried again to merge the trees.

Now it worked! :tada: The tree were merged.

But now I noticed that every individual from tree A is present three times in tree B. I think this must be a sideeffect of the errors shown above, when the individuals were copied, but then the error occurred and webtrees renumbered all individuals.

I will restore my database and will delete the `HEAD` and `TRLR` records in the database before trying to merge and renumbering the trees.

**Comment by Art4** [comment]
> I will restore my database and will delete the HEAD and TRLR records in the database before trying to merge and renumbering the trees.

This worked fine. I could safely delete the records and then the merge works without errors. I don't know where this entries came from, but I think it would be helpful to add a check and remove for this records on a merge.

Thank you for your help. :+1:

**Comment by fisharebest** [comment]
Re-open, as we will need some code changes to ignore/delete these records for other people.
