### ISSUE TITLE
I see "Mohyliv Podil&#039;s&#039;kyi" in wt 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1915]
When I move the mouse over places or years with places, that have an apostroph (for instance Mohyliv, Podil's'kyi) in the Compact tree, the Place hierarchy and Interactive tree, I see &#039; instead of the apostrophe. 
![2018-09-20_00-28-28](https://user-images.githubusercontent.com/5202996/45782634-323abc00-bc6c-11e8-8f2f-4980cfec4fd4.jpg)

I see the same in the chart or report root person's name when the mouse goes over the name. 

Mouse over the Pedigree map marker shows the place correctly.

I tested for instance the birth of I33987 in my test test site.

**Comment by melizaa** [comment]
Why was this closed? **Please re-open it.**

Mouse over the place in the Place hierarchy shows
![place2018-10-14_15-08-00](https://user-images.githubusercontent.com/5202996/46916405-025cab00-cfc3-11e8-9e21-1e00eca4d445.jpg)

In the Compact tree and Interactive tree when I move the mouse over the death year 1942 of Haim Faust, I see still the &#039;-s.
![compact2018-10-14_15-03-28](https://user-images.githubusercontent.com/5202996/46916382-721e6600-cfc2-11e8-93d9-f9afce57f6aa.jpg)

![interactive2018-10-14_15-00-44](https://user-images.githubusercontent.com/5202996/46916360-063bfd80-cfc2-11e8-9ece-08f276a346b3.jpg)



I see the same error in the chart or report root person's name when the mouse goes over the name.
Chart
![chart2018-10-14_15-30-31](https://user-images.githubusercontent.com/5202996/46916691-aac03e80-cfc6-11e8-81a6-b8827e894b79.jpg)

Report
![report2018-10-14_15-31-44](https://user-images.githubusercontent.com/5202996/46916695-b14eb600-cfc6-11e8-921a-5678555177cc.jpg)

**Comment by fisharebest** [comment]
> Why was this closed

Because the reported problem (HTML entities on maps) was fixed.

This happens automatically.

When a git commit message contains the issue number in the description, then github closes the issue.

Here, there are several separate bugs.

**Comment by melizaa** [comment]
Are the mouse over date in Compact tree and Interactive tree and mouse over place on Place hierarchy one bug? 
Are the report issues a second bug?

I  just do not know how many issues I should create.
