### ISSUE TITLE
2.0 Latest update throws error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1917]
Two trees, One no longer shows statistics on home page.  The other tree shows the statistics block

**Comment by fisharebest** [comment]
This error message (which I can reproduce) is triggered when you select "All" on the "Logs" page of the control panel.

But it's not the one that affecting the stats block on the home page.
Can you check to see if there's another error message?  Thanks.

**Comment by makitso** [comment]
There is nothing that I can see either in the apache logs or webtrees.  Tried adding statistics to My Page and did not work.  Will continue to investigate,

**Comment by fisharebest** [comment]
The statistics block is loaded using an AJAX request.

Can you look at the response using your browser dev tools.  Does it contain an error?

**Comment by makitso** [comment]
I am not sure what is going on.  After this mornings github update the problem has gone away.
