### ISSUE TITLE
2.0 - Selecting Preferences gives 500 error 

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1919]
Selecting Preferences for a specific family tree throws 500 Error:

[Sat Sep 22 16:46:09.047345 2018] [php7:error] [pid 27713] [client ::1:43092] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Fisharebest\\Webtrees\\GedcomRecord::getInstance() must be of the type string, null given, called in /var/www/app/Http/Controllers/AdminTreesController.php on line 936 and defined in /var/www/app/GedcomRecord.php:143\nStack trace:\n#0 /var/www/app/Http/Controllers/AdminTreesController.php(936): Fisharebest\\Webtrees\\GedcomRecord::getInstance(NULL, Object(Fisharebest\\Webtrees\\Tree))\n#1 [internal function]: Fisharebest\\Webtrees\\Http\\Controllers\\AdminTreesController->preferences(Object(Fisharebest\\Webtrees\\Tree))\n#2 /var/www/app/Resolver.php(85): ReflectionMethod->invoke(Object(Fisharebest\\Webtrees\\Http\\Controllers\\AdminTreesController), Object(Fisharebest\\Webtrees\\Tree))\n#3 /var/www/index.php(321): Fisharebest\\Webtrees\\Resolver->dispatch(Object(Fisharebest\\Webtrees\\Http\\Controllers\\AdminTreesController), 'preferences')\n#4 /var/www/app/Http/Middleware/CheckForMaintenanceMode.php(48): Fisharebest\\Webtrees\\{closure}(Object(Symfony\\Component\\HttpFoundation\\Request))\n#5 /var/www/i in /var/www/app/GedcomRecord.php on line 143

**Comment by fisharebest** [comment]
Fixed in 355841967

My development environment (PhpStorm) has an annoying bug that when you search for something and it is low on memory, it shows "no results", rather than an error.

Thus you think you've updated everything when you haven't....

**Comment by makitso** [comment]
Problem still exists after this mornings update.
