### ISSUE TITLE
2.0 - No places listed in Control Panel / Geographical Data

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1921]
Lots of places in the Lists / Place Hierarchy but noting on the  Control Panel page.

![image](https://user-images.githubusercontent.com/5147603/45928886-39c5c380-beff-11e8-8d6d-6e18edf818be.png)

**Comment by fisharebest** [comment]
Perhaps it is empty, because you have no geographic data?

Try importing place names from your tree, or importing locations from  a CSV file.

**Comment by makitso** [comment]
Interesting.  Today I exported my tree, from my public site (2.0 but back a few days of updates).  I then recreated the tree on my dev system (2.0 current) and imported the .ged file.  However, If I use phpmyadmin to look at wt_placelocation the table is empty even though the same table has 776 rows on my public site.

So, the question is; it looks like the gedcom export does not include place locations?

**Comment by makitso** [comment]
Now that I think about it, I bet your going to say that place locations are not in the gedcom spec and as such are not included on a webtrees export.

**Comment by fisharebest** [comment]
> I bet your going to say that place locations are not in the gedcom spec and as such are not included on a webtrees export.

You win the bet! ;-)

If you use the "import places from tree" option, then webtrees will create the 776 blank entries in the place-locations table, and webtrees will give you the option to locate them on a map.
