### ISSUE TITLE
1.7.11 & 2.0 Missing punctuation and space

### ISSUE THREAD

**Issue by HRN-webtrees** [fisharebest/webtrees#1928]
Missing punctuation and space after tags in Facts and events, when language set to nynorsk (nn)
![nn](https://user-images.githubusercontent.com/7372415/45931518-66192880-bf6f-11e8-82ee-f23a7a90b843.jpg)

![en](https://user-images.githubusercontent.com/7372415/45931519-6ca7a000-bf6f-11e8-9366-d43804a44c74.jpg)

**Comment by fisharebest** [comment]
There is a translation string `<span class="label">%1$s:</span> <span class="field" dir="auto">%2$s</span>` which is used for labels/values.

The `nn` translation does not have the colon.

https://translate.webtrees.net/translate/webtrees/webtrees/nn/?q=%3Cspan+class%3D%22label%22%3E%251%24s%3A%3C%2Fspan%3E+%3Cspan+class%3D%22field%22+dir%3D%22auto%22%3E%252%24s%3C%2Fspan%3E&search=substring&source=on&target=on&type=all&ignored=False

You should update the translation here.

**Comment by HRN-webtrees** [comment]
Thank you. Translation updated
