### ISSUE TITLE
webtrees 1.7.11 - FunctionsPrintLists.php:150 A non-numeric value encountered

### ISSUE THREAD

**Issue by mpwt** [fisharebest/webtrees#1932]
> https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-10-11/32856-solved-source-object-without-link-to-persons

I use webtrees 1.7.11 with PHP 7.2. I have two trees, one semi-open and one closed for visitors. With the semi-open tree I havn't any problem. But within the closed tree I found a strange error on indilist.php:

`/home/bauschaf/webtrees_ffp/includes/session.php:193 /home/bauschaf/webtrees_ffp/app/Functions/FunctionsPrintLists.php:150 A non-numeric value encountered #0 /app/Functions/FunctionsPrintLists.php:150 ErrorException("/home/bauschaf/webtrees_ffp/app/Functions/FunctionsPrintLists.php:150 A non-numeric value encountered") #1 /indilist.php:261 individualTable([array])`

and famlist.php:

`/home/bauschaf/webtrees_ffp/includes/session.php:193 /home/bauschaf/webtrees_ffp/app/Functions/FunctionsPrintLists.php:589 A non-numeric value encountered #0 /app/Functions/FunctionsPrintLists.php:589 ErrorException("/home/bauschaf/webtrees_ffp/app/Functions/FunctionsPrintLists.php:589 A non-numeric value encountered") #1 /famlist.php:261 familyTable([array])`

when I click on a surname. 

It is the same as here: https://github.com/fisharebest/webtrees/issues/1229 and the fix https://github.com/fisharebest/webtrees/commit/ca0f261d4c4a3ab3984a1fa52e0a57180321d660 helps. Please change it for webtrees 1.7.X too.

**Comment by luenissla** [comment]
I had the same problem to look to a source-object. If I now show the object "Source" and click on "People", then an error message appears in both files:
` 
> /www/htdocs/w01813e8/PoolWT/app/Functions/FunctionsPrintLists.php:150 A non-numeric value encountered
> #0 /app/Functions/FunctionsPrintLists.php:150 ErrorException("A non-numeric value encountered")
> #1 /source.php:181 individualTable([array])`

The Fix for 2.0.0 alpha works: Fix [#1229](https://github.com/fisharebest/webtrees/commit/ca0f261d4c4a3ab3984a1fa52e0a57180321d660) - maximum age in indi/fam list charts.
