### ISSUE TITLE
language files

### ISSUE THREAD

**Issue by Salokyn** [fisharebest/webtrees#1933]
Hello,

Could you include .mo files in the release package or explain how to make them from the .po files ?

Thank you

**Comment by fisharebest** [comment]
A `.MO` file is a compressed version of a `.PO` file.

You can download `.MO` files individually from the [translation server](https://translate.webtrees.net/projects/webtrees/).  Navigate to the specific translation, and then choose "Files", "Download" from the menu.

You can also create them using various GUI tools, such as [PoEdit](https://poedit.net/).

I use a command-line tool `msgfmt` (part of the [gettext](https://www.gnu.org/software/gettext/) suite of tools).  webtrees source code contains a script to generate all of the `.MO` files.  You'd run it by:

1. install [composer](https://getcomposer.org/)
2. install `gettext`.  For linux, you'd use something like `sudo apt-get install gettext`.  On mac, you'd use something like `brew install gettext` and on windows, you'd need to install the [cygwin](http://www.cygwin.com/) shell and select it from the list of packages.
3. run `composer webtrees-mo`

**Comment by Salokyn** [comment]
Thank you
