### ISSUE TITLE
Fatal error in reports

### ISSUE THREAD

**Issue by maekclena** [fisharebest/webtrees#1934]
In demo-dev, the [Ancestors](https://dev.webtrees.net/demo-dev/index.php?route=report-setup&ged=demo&report=ahnentafel_report), [Descendants](https://dev.webtrees.net/demo-dev/index.php?route=report-setup&ged=demo&report=descendancy_report), [Family](https://dev.webtrees.net/demo-dev/index.php?route=report-setup&ged=demo&report=family_group_report), [Individual](https://dev.webtrees.net/demo-dev/index.php?route=report-setup&ged=demo&report=individual_report), [Pedigree](https://dev.webtrees.net/demo-dev/index.php?route=report-setup&ged=demo&report=pedigree_report) and [Related individuals](https://dev.webtrees.net/demo-dev/index.php?route=report-setup&ged=demo&report=relative_ext_report) reports return a fatal error:

```
Fatal error:
Uncaught TypeError: Argument 1 passed to Fisharebest\Webtrees\Individual::getInstance() must be of the type string, null given, called in /home/webtrees/dev.webtrees.net/demo-dev/app/Http/Controllers/ReportEngineController.php on line 105 and defined in /home/webtrees/dev.webtrees.net/demo-dev/app/Individual.php:51
Stack trace:
#0 /home/webtrees/dev.webtrees.net/demo-dev/app/Http/Controllers/ReportEngineController.php(105): Fisharebest\Webtrees\Individual::getInstance(NULL, Object(Fisharebest\Webtrees\Tree))
#1 [internal function]: Fisharebest\Webtrees\Http\Controllers\ReportEngineController->reportSetup(Object(Symfony\Component\HttpFoundation\Request), Object(Fisharebest\Webtrees\Tree))
#2 /home/webtrees/dev.webtrees.net/demo-dev/app/Resolver.php(85): ReflectionMethod->invoke(Object(Fisharebest\Webtrees\Http\Controllers\ReportEngineController), Object(Symfony\Component\HttpFoundation\Request), Object(Fisharebest\Webtrees\Tree))
#3 /home/webtrees/dev.webtrees.net/demo-dev/index.php(321): Fisharebest\Webtrees\ in /home/webtrees/dev.webtrees.net/demo-dev/app/Individual.php on line 51
```

**Comment by makitso** [comment]
Still throws error on either pdf or html reports

[Sun Feb 24 09:48:52.138614 2019] [php7:error] [pid 17290] [client ::1:41738] PHP Fatal error:  Uncaught TypeError: Argument 4 passed to Fisharebest\\Webtrees\\Report\\ReportParserGenerate::addAncestors() must be of the type integer, string given, called in /home/rob/www/app/Report/ReportParserGenerate.php on line 2428 and defined in /home/rob/www/app/Report/ReportParserGenerate.php:2769\nStack trace:\n#0 /home/rob/www/app/Report/ReportParserGenerate.php(2428): Fisharebest\\Webtrees\\Report\\ReportParserGenerate->addAncestors(Array, 'I0015', false, '3')\n#1 /home/rob/www/app/Report/ReportParserGenerate.php(182): Fisharebest\\Webtrees\\Report\\ReportParserGenerate->relativesStartHandler(Array)\n#2 /home/rob/www/app/Report/ReportParserBase.php(50): Fisharebest\\Webtrees\\Report\\ReportParserGenerate->startElement(Resource id #5, 'Relatives', Array)\n#3 [internal function]: Fisharebest\\Webtrees\\Report\\ReportParserBase->Fisharebest\\Webtrees\\Report\\{closure}(Resource id #5, 'Relatives', Array)\n#4 /home/rob/www/app/Report/ReportParserBase.php(71): xml_parse(Resource id #5, '<?xml version="...', false)\n#5 /home/rob/www/app/Rep in /home/rob/www/app/Report/ReportParserGenerate.php on line 2769, referer: http://localhost/index.php?route=report-setup&xref=I0015&ged=peters.ged&report=ahnentafel_report

**Comment by fisharebest** [comment]
I think this is an unrelated error.  Should be fixed now.
