### ISSUE TITLE
2.0 - Flags missing from Places

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1936]
I am a bit frustrated with google maps on the Places hierarchy.  Specifically, can’t seem to get flags to show.  Everything was good on 1.7.x but on 2.0 I am at a loss.  

My first issue has to do with where the flags should reside in the webtrees folder.   In the  Geographical Data section if I edit USA, I can see the flag at why under googlemaps in the modules_v2 folder.  Is this correct?

![image](https://user-images.githubusercontent.com/5147603/46179451-2ce30000-c270-11e8-8c13-f46d826994bc.png)

The second issue is not seeing any flags on Graphical Data top page and thus nothing shows up on the Places Hierarchy chart.

![image](https://user-images.githubusercontent.com/5147603/46179455-3704fe80-c270-11e8-96d1-65800cc722f1.png)

Suggestions?

**Comment by fisharebest** [comment]
The flag code is still "in progress".

The code is (I think) still looking in the openstreetmap module folder, which no longer exists.

**Comment by makitso** [comment]
I figured as much.  No hurry on my part, should I close this issue?

**Comment by fisharebest** [comment]
Leave it open.  Otherwise, I'll forget about it (again!).

**Comment by fisharebest** [comment]
There is already an open issue for this - #1797
