### ISSUE TITLE
2.0 - Latest github give error on home page

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1937]
[Fri Sep 28 10:16:15.287816 2018] [php7:warn] [pid 8190] [client 127.0.0.1:56592] PHP Warning:  require(/var/www/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /var/www/vendor/composer/autoload_real.php on line 66
[Fri Sep 28 10:16:15.287846 2018] [php7:error] [pid 8190] [client 127.0.0.1:56592] PHP Fatal error:  require(): Failed opening required '/var/www/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/usr/share/php') in /var/www/vendor/composer/autoload_real.php on line 66

**Comment by fisharebest** [comment]
/dang

Same old problem again.  Projects really should *not* include the contents of the `vendor` directory.  Other people's libraries do not belong in our source repository.
