### ISSUE TITLE
2.0 - Text input box not suitable for touch devices

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1938]
The little control in the lower right corner is good for expanding text boxes for mouse users.  However, for touch devices you can't use it.

![image](https://user-images.githubusercontent.com/5147603/46301490-51362980-c55b-11e8-8819-1a270328bd2c.png)

I can fix this with this code added to common but wonder if you have a better solution?

@media (max-width: 1280px) {
#note,
#source-text,
*[id^='TEXT'],
*[id^='NOTE'] {
	min-height: 200px;
 }
}

**Comment by fisharebest** [comment]
It seems that mobile devices do not support the css `resize` property.

The default vertical size for `textarea` elements appears to be 2 rows (based on the limited range browsers I currently have available).

We could explicitly add `rows="4"` to all of our`<textarea>` controls to provide an initial value...

Desktop users could resize (as at present).
Mobile users would get some more space.  I don't think we should go too high, as when the keyboard is open, there's very little screen available, and I wouldn't want the control to be larger than that.

**Comment by fisharebest** [comment]
I have added an initial size to all `textarea` elements.  Typically `rows="5"`, but sometimes more or less, depending on the context.

How does this work for you?

**Comment by makitso** [comment]
Yes thanks, that is much better.
