### ISSUE TITLE
2.0 - Add father to family gives 500 error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1939]
Fatal error: Uncaught TypeError: Argument 1 passed to Fisharebest\Webtrees\GedcomRecord::updateFact() must be of the type string, null given, called in /var/www/app/GedcomRecord.php on line 1216 and defined in /var/www/app/GedcomRecord.php:1242 Stack trace: #0 /var/www/app/GedcomRecord.php(1216): Fisharebest\Webtrees\GedcomRecord->updateFact(NULL, '1 FAMC @X973@', true) #1 /var/www/app/Http/Controllers/EditIndividualController.php(372): Fisharebest\Webtrees\GedcomRecord->createFact('1 FAMC @X973@', true) #2 [internal function]: Fisharebest\Webtrees\Http\Controllers\EditIndividualController->addParentAction(Object(Symfony\Component\HttpFoundation\Request), Object(Fisharebest\Webtrees\Tree)) #3 /var/www/app/Resolver.php(85): ReflectionMethod->invoke(Object(Fisharebest\Webtrees\Http\Controllers\EditIndividualController), Object(Symfony\Component\HttpFoundation\Request), Object(Fisharebest\Webtrees\Tree)) #4 /var/www/index.php(323): Fisharebest\Webtrees\Resolver->dispatch(Object(Fisharebest\Webtrees\Http\Controllers\EditIndiv in /var/www/app/GedcomRecord.php on line 1242

**Comment by makitso** [comment]
Greg,  if you happen to have time, this one is a pain, waiting to add a bunch of people :-)

**Comment by fisharebest** [comment]
Feel free to nudge me on any other issues, if you think their priority needs bumping up.

**Comment by makitso** [comment]
Thanks Greg, no biggies at this moment
