### ISSUE TITLE
2.0 - Latest update results in error from Place hierarchy

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1944]
Fatal error
: Uncaught TypeError: rawurlencode() expects parameter 1 to be string, integer given in /var/www/app/Functions/Functions.php:2407 Stack trace: #0 /var/www/app/Functions/Functions.php(2407): rawurlencode(0) #1 /var/www/app/Theme/ColorsTheme.php(151): Fisharebest\Webtrees\Functions\Functions::getQueryUrl(Array, '&') #2 /var/www/app/Theme/ColorsTheme.php(127): Fisharebest\Webtrees\Theme\ColorsTheme->menuPalette() #3 /var/www/resources/views/layouts/default.php(81): Fisharebest\Webtrees\Theme\ColorsTheme->secondaryMenu() #4 /var/www/app/View.php(130): include('/var/www/resour...') #5 /var/www/app/View.php(170): Fisharebest\Webtrees\View->render() #6 /var/www/app/Helpers/functions.php(84): Fisharebest\Webtrees\View::make('layouts/default', Array) #7 /var/www/app/Http/Controllers/AbstractBaseController.php(202): view('layouts/default', Array) #8 /var/www/app/Http/Controllers/PlaceHierarchyController.php(102): Fisharebest\Webtrees\Http\Controllers\AbstractBaseController->viewResponse('places-page', Array) #9 [internal in
/var/www/app/Functions/Functions.php
on line
2407

**Comment by fisharebest** [comment]
I've just enabled `strict_types` globally - so there may well be a few more errors like this one.  They should all be trivial to fix....
