### ISSUE TITLE
Replace genealogy contacts with administrators

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#1945]
webtrees was created from PhpGedView - which was written in a time when it was difficult and expensive to run a webserver.

The design assumes you will have a site administrator who will manage the site/users and many independent trees - each with their own manager.

The result is that emails to users (regisration, password reset, etc.) get sent from a *tree* or its genealogy contact.

This causes a number of issues.

* Registration is impossible when all trees are private.
* Password reset is impossible when all trees are private.
* If there is no genealogy contact, then new registration details do not get sent.

For 2.0 we should simplify this.

* The sender-name in emails should be the site name (url?), rather than the tree name.
* Registration requests should be sent to all administrators (there can be more than one), rather than the tree's genealogy contact.
* The two contact names in the footer (tech/genealogy) should be combined into a single (genealogy) setting.

**Comment by dverdin** [comment]
A solution could be to default to site admin whan no tree admin is available, be it becaus there is no tree admin or all trees are private.

That's what we do in Sympa and it works fairly well. As webtrees seems to be intended for hosting, it could be an interesting mechanism to develop: always try to use the closer contact to the tree but keep the possibility to default to a broader contact if needed.

For example, if a tree is private ot without contact, send a mail to all administrators.

Thanks for making this great software!

David
