### ISSUE TITLE
Login Problem with Cloudflare SSL

### ISSUE THREAD

**Issue by b202i** [fisharebest/webtrees#1951]
This problem is with Webtrees 1.7.11 running on Ubuntu 18.04.1 and Python 2.7.15rc1.

Login fails when Cloudflare SSL is enabled. When a page rule "Always Use HTTPS" is disabled, login works fine and all pages appear to work fine. When the page rule is enabled, the login dialog seems to refresh but there is no error message displayed or any error message in the log file. If the page rule is disabled for login, then enabled, all of the pages appear to work fine with SSL. It seems that only the login page has issues.

Website Preference, Website URL is unchanged, default blank.
Website Sign-in Registration, Sign-in URL is unchanged, default blank.

I've reviewed the login.php code, and I am not a PHP programmer, but I don't see anything obviously wrong:

```        echo '<form id="login-form" name="login-form" method="post" action="', WT_LOGIN_URL, '">
                <input type="hidden" name="action" value="login">
                <input type="hidden" name="url" value="', Filter::escapeHtml($url), '">';
                echo '<div>
                        <label for="username">', I18N::translate('Username'),
                        '<input type="text" id="username" name="username" value="', Filter::escapeHtml($username), '" class="formField" autofocus>
                        </label>
                </div>
                <div>
                        <label for="password">', I18N::translate('Password'),
                                '<input type="password" id="password" name="password" class="formField">
                        </label>
                </div>
                <div>
                        <input type="submit" value="', /* I18N: A button label. */ I18N::translate('sign in'), '">
                </div>
                ';```

**Comment by b202i** [comment]
I've tried changing the Control panel, Sign-in and Registration, Sign-in URL.

The documentation reads:
> You only need to enter a Sign-in URL if you want to redirect to a different website or location when your users sign in. This is very useful if you need to switch from http to https when your users sign in. Include the full URL to login.php. For example, https://www.yourserver.com/webtrees/login.php 

The base URL is myancestry.club, this puts you in the /webtrees folder. I have tried two different values without any luck:
    https://www.myancestry.club/login.php 
    https://www.myancestry.club/webtrees/login.php 

When using the Safari browser this warning is shown:

> This is a non-secure form.

> This form will be sent in a way that is not secure. Are you sure you want to send it?

I am guessing the post method is trying to submit the login request to http insted of https. I have been searching through the code but don't know where the default is set.

Suggestions appreciated

**Comment by fisharebest** [comment]
> I am guessing the post method is trying to submit the login request to http insted of https

Yes.  You can see this if you view the page source of your login page.

IIRC, with cloudflare, you have two options.

1) Cloudflare uses HTTP to connect to your site, and serves HTTPS to your visitors

2) Cloudflare uses HTTPS to connect to your site, and serves HTTPS to your visitors.

With both options, your visitors see HTTPS.  But with option 1, your webserver sees an HTTP request.

(This is from memory.  We use cloudflare at work, but I can't access it from home, so can't log in to check this)

Now, because webtrees is sees a connection on HTTP, it generates URLs with HTTP.  (How would it know to do otherwise).

> You only need to enter a Sign-in URL if you want to redirect to a different website or location when your users sign in.

I'd recommend leaving this option empty.  It was added to PGV (our predecessor project) to allow one of the developers to integrate the sign-on with the rest of his site.  The option is removed in the next version of webtrees.

Maybe set up a SSL cert on your site (e.g. using letsencrypt), and then tell cloudflare to connect to your server using HTTPS.

**Comment by fisharebest** [comment]
...alternatively, modify your webserver config to tell webtrees that the request was on HTTPS, even when it wasn't.  e.g. with apache, set `HTTPS=on`

**Comment by b202i** [comment]
Digging into this a bit more with the Sign-in URL blank, the sequence of server requests is not consistently https.

1. Request URL: https://myancestry.club/
2. Request URL: http://myancestry.club/login.php?url=index.php%3F
3. Request URL: https://myancestry.club/login.php?url=index.php%3F
4. Request URL: https://myancestry.club/themes/clouds/jquery-ui-1.11.2/jquery-ui.css
5. Request URL: https://myancestry.club/themes/clouds/css-1.7.8/style.css
6. Request URL: https://myancestry.club/packages/jquery-2.2.1/jquery.min.js
7. Request URL: https://myancestry.club/packages/jquery-ui-1.11.4/js/jquery-ui.min.js
8. Request URL: https://myancestry.club/assets/js-1.7.9/webtrees.js
9. Request URL: https://myancestry.club/assets/js-1.7.9/jquery.colorbox-1.5.14.js
10. Request URL: https://myancestry.club/assets/js-1.7.9/jquery.wheelzoom-2.0.0.js
11. Request URL: https://myancestry.club/themes/clouds/css-1.7.8/images/background.png
12. Request URL: https://myancestry.club/themes/clouds/css-1.7.8/images/powered-by-webtrees.png
13. Request URL: https://myancestry.club/themes/clouds/css-1.7.8/images/clouds.png
14. Request URL: https://myancestry.club/themes/clouds/css-1.7.8/favicon192.png

All requests use GET method. Cloudflare makes the initial request with https.

I find it interesting the first request for login.php is http and the second is https. Not sure why there are two requests for login.php. All following requests are https.

When I hit the "sign in" button, it repeats the sequence from number 2 except the first login.php request is with http and POST method.

Initial https://myancestry.club Request Headers
```:authority: myancestry.club
:method: GET
:path: /
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: no-cache
cookie: __cfduid=d2a1d24ffba4cc70e45cec299303cfab61538579609; compact=false; allPartners=false; WT_SESSION=4chrteksdlflj34clnohncidkp
dnt: 1
pragma: no-cache
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36```

It seems we need to figure out why it is making two GET requests to login.php and the first http requests needs to be eliminated.

**Comment by fisharebest** [comment]
If I visit your login page https://myancestry.club/login.php and examine the HTML source, I see that the login form's URL is set to http://myancestry.club/login.php

This URL is generated by webtrees, and is based on the incoming request.

I guess you are using Cloudflare's "Flexible SSL" option.
See https://support.cloudflare.com/hc/en-us/articles/200170416 for an explanation.

So, my browser is making an HTTPS connection to Cloudflare.
Cloudflare is then making an HTTP connection to your webserver.
webtrees sees that it has received an HTTP request, and generates an HTTP URL.

One possible option for you is to enable Cloudflare's "Automatic HTTPS Rewrites" option.
This will rewrite all HTTP URLs in the page to HTTPS.

**Comment by b202i** [comment]
Automatic HTTPS Rewrites seems to have solved the problem. It works although for the first page-load I still see http and https GET requests for login.php and index.php, i.e., pairs of GET requests one http followed by one https. After that all requests are https and even refreshing the page generates 100% https. So it works and I am happy only that I don't understand the double-request behavior.  Thanks again for your help.
