### ISSUE TITLE
2.0 - Error when trying to add media object to individual

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1953]
Current github:

[Tue Oct 09 07:44:03.349469 2018] [php7:error] [pid 10778] [client ::1:38798] PHP Fatal error:  Uncaught Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException: The file "/tmp/phpQHtbr5" does not exist in /var/www/vendor/symfony/http-foundation/File/File.php:37\nStack trace:\n#0 /var/www/vendor/symfony/http-foundation/File/UploadedFile.php(66): Symfony\\Component\\HttpFoundation\\File\\File->__construct('/tmp/phpQHtbr5', true)\n#1 /var/www/vendor/symfony/http-foundation/FileBag.php(87): Symfony\\Component\\HttpFoundation\\File\\UploadedFile->__construct('/tmp/phpQHtbr5', '1_003.jpg', 'image/jpeg', 266546, 0)\n#2 /var/www/vendor/symfony/http-foundation/FileBag.php(52): Symfony\\Component\\HttpFoundation\\FileBag->convertFileInformation(Array)\n#3 /var/www/vendor/symfony/http-foundation/FileBag.php(61): Symfony\\Component\\HttpFoundation\\FileBag->set('file', Array)\n#4 /var/www/vendor/symfony/http-foundation/FileBag.php(40): Symfony\\Component\\HttpFoundation\\FileBag->add(Array)\n#5 /var/www/vendor/symfony/http-foundation/FileBag.php(31): Symfony\\Component\\HttpFoundation\\FileBag->replace(Array)\n#6 /var/www/vendo in /var/www/vendor/symfony/http-foundation/File/File.php on line 37, referer: http://localhost/index.php?route=add-fact&ged=peters.ged&xref=I0065&fact=OBJ

**Comment by makitso** [comment]
On my production side I get this message:

[Tue Oct 09 07:03:43.192028 2018] [fcgid:warn] [pid 12511:tid 3775757120] [host www.skatekey.net] [client 67.128.192.90:41876] #2 /var/www/html/sk/skatekey.net/vendor/symfony/http-foundation/FileBag.php(52): Symfony\\Component\\HttpFoundation\\FileBag->convertFileInformation(Array), referer: https://www.skatekey.net/index.php?route=add-fact&ged=peters.ged&xref=I0065&fact=OBJE

**Comment by fisharebest** [comment]
I can't reproduce this.
To be certain I'm looking at the right thing, can you give me the exact steps you take.
Thanks,

**Comment by makitso** [comment]
This is still a big pain in the tush, can not upload a media object, can not link an existing media object.

[Tue Oct 23 16:03:06.810032 2018] [fcgid:warn] [pid 6283:tid 3792296768] [host www.skatekey.net] [client 67.128.192.90:49126] #4 /var/www/html/sk/skatekey.net/vendor/symfony/http-foundation/FileBag.php(40): Symfony\\Component\\HttpFoundation\\FileBag->add(Array) in /var/www/html/sk/skatekey.net/vendor/symfony/http-foundation/File/File.php on line 37, referer: https://www.skatekey.net/index.php?route=edit-fact&xref=I0024&fact_id=ce0173856da1c320d343ce34f1597c18&ged=peters.ged

**Comment by fisharebest** [comment]
It's really difficult to investigate this when I can't reproduce it.

Google suggests this can be caused by PHP configuration issues.  i.e. you are uploading a file larger than the limits set in PHP.INI or the temp upload folder is not writable, etc.

**Comment by makitso** [comment]
The file is 216K jpeg.  
The data/tmp has 755 permissions. And, in fact there are files in data/tmp that have dates as new as 31/Oct/2018

My php.ini has been static for a long time.
date.timezone="America/Chicago"
memory_limit = 512M
post_max_size = 128M
upload_max_filesize = 128M
default_charset = "utf-8"
error_reporting = 1

**Comment by makitso** [comment]
BTY, I can go into Admin/Media and do an Upload Media File.  Then I find the image in Manage media and create a Media object for correct tree.  And last, I then go to edit and Link it to an Individual. 
SO, if it works in multiple steps why not in add a media object to an individual?

I removed the error reporting and did the add media again:  Lots more information including a fatal error at the end:

[Wed Oct 24 13:59:16.928766 2018] [fcgid:warn] [pid 25233:tid 3757509440] [host www.skatekey.net] [client 67.128.192.90:53866] 
#6 /var/www/html/sk/skatekey.net/index.php(3 in /var/www/html/sk/skatekey.net/resources/views/selects/media.phtml on line 1, referer: https://www.skatekey.net/index.php?route=add-fact&ged=Johannsen&xref=I446&fact=OBJE
[Wed Oct 24 13:59:16.928756 2018] [fcgid:warn] [pid 25233:tid 3757509440] [host www.skatekey.net] [client 67.128.192.90:53866] 
#5 /var/www/html/sk/skatekey.net/app/Resolver.php(87): ReflectionMethod->invoke(Object(Fisharebest\\Webtrees\\Http\\Controllers\\EditMediaController), Object(Symfony\\Component\\HttpFoundation\\Request), Object(Fisharebest\\Webtrees\\Tree)), referer: https://www.skatekey.net/index.php?route=add-fact&ged=Johannsen&xref=I446&fact=OBJE
[Wed Oct 24 13:59:16.928746 2018] [fcgid:warn] [pid 25233:tid 3757509440] [host www.skatekey.net] [client 67.128.192.90:53866] 
#4 [internal function]: Fisharebest\\Webtrees\\Http\\Controllers\\EditMediaController->createMediaObjectAction(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Fisharebest\\Webtrees\\Tree)), referer: https://www.skatekey.net/index.php?route=add-fact&ged=Johannsen&xref=I446&fact=OBJE
[Wed Oct 24 13:59:16.928736 2018] [fcgid:warn] [pid 25233:tid 3757509440] [host www.skatekey.net] [client 67.128.192.90:53866] 
#3 /var/www/html/sk/skatekey.net/app/Http/Controllers/EditMediaController.php(382): view('selects/media', Array), referer: https://www.skatekey.net/index.php?route=add-fact&ged=Johannsen&xref=I446&fact=OBJE
[Wed Oct 24 13:59:16.928727 2018] [fcgid:warn] [pid 25233:tid 3757509440] [host www.skatekey.net] [client 67.128.192.90:53866] 
#2 /var/www/html/sk/skatekey.net/app/Helpers/functions.php(84): Fisharebest\\Webtrees\\View::make('selects/media', Array), referer: https://www.skatekey.net/index.php?route=add-fact&ged=Johannsen&xref=I446&fact=OBJE
[Wed Oct 24 13:59:16.928717 2018] [fcgid:warn] [pid 25233:tid 3757509440] [host www.skatekey.net] [client 67.128.192.90:53866] 
#1 /var/www/html/sk/skatekey.net/app/View.php(184): Fisharebest\\Webtrees\\View->render(), referer: https://www.skatekey.net/index.php?route=add-fact&ged=Johannsen&xref=I446&fact=OBJE
[Wed Oct 24 13:59:16.928708 2018] [fcgid:warn] [pid 25233:tid 3757509440] [host www.skatekey.net] [client 67.128.192.90:53866] 
#0 /var/www/html/sk/skatekey.net/app/View.php(140): include(), referer: https://www.skatekey.net/index.php?route=add-fact&ged=Johannsen&xref=I446&fact=OBJE
[Wed Oct 24 13:59:16.928696 2018] [fcgid:warn] [pid 25233:tid 3757509440] [host www.skatekey.net] [client 67.128.192.90:53866] 
Stack trace:, referer: https://www.skatekey.net/index.php?route=add-fact&ged=Johannsen&xref=I446&fact=OBJE
[Wed Oct 24 13:59:16.928630 2018] [fcgid:warn] [pid 25233:tid 3757509440] [host www.skatekey.net] [client 67.128.192.90:53866] PHP Fatal error: Uncaught Error: Call to undefined method Fisharebest\\Webtrees\\GedcomRecord::mediaFiles() in /var/www/html/sk/skatekey.net/resources/views/selects/media.phtml:1, referer: https://www.skatekey.net/index.php?route=add-fact&ged=Johannsen&xref=I446&fact=OBJE

**Comment by makitso** [comment]
> It's really difficult to investigate this when I can't reproduce it.
I understand.  With three different systems I get slightly different results.  So, I have focused on my laptop where I have both 2.0 and 1.7.11 installed.  With 1.7.11 I get no error in webrees log or apache error report.   
However, with 2.0 synced to gethub, I get the error in the apache log even when the add media object at the individual level succeeds e.g. save works correctly.

**Comment by makitso** [comment]
I have reverted to the Alpha-1 release and the problem has gone away.

**Comment by fisharebest** [comment]
The error in the stack-trace (Oct 24) was fixed in 313e72b (Oct 28).

> I have reverted to the Alpha-1 release and the problem has gone away.

Are you able to use [git bisect](https://git-scm.com/docs/git-bisect)?

If you have a known good / bad commits, then this tool will help you find the commit that introduced the problem.

**Comment by makitso** [comment]
> Are you able to use git bisect?

**Comment by makitso** [comment]
> Are you able to use git bisect?

Thanks, I will look it up.  I just installed Alpha 1 and then added some patches.

> The error in the stack-trace (Oct 24) was fixed in 313e72b (Oct 28).

I had three systems on the latest GitHub and all failed.  It's quite confusing to me and difficult to describe.

**Comment by makitso** [comment]
Maybe I should close this issue out and start a new one?

**Comment by makitso** [comment]
One last shot:  Test gedcom "duck".  I went to individual page and selected "Add media object."  The process did complete correctly.  However, there was an error in the Apache log as follows:

[Tue Nov 20 06:10:07.145267 2018] [php7:error] [pid 19357] [client ::1:56404] PHP Fatal error:  Uncaught Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException: The file "/tmp/php3UHqgl" does not exist in /var/www/vendor/symfony/http-foundation/File/File.php:37\nStack trace:\n#0 /var/www/vendor/symfony/http-foundation/File/UploadedFile.php(66): Symfony\\Component\\HttpFoundation\\File\\File->__construct('/tmp/php3UHqgl', true)\n#1 /var/www/vendor/symfony/http-foundation/FileBag.php(87): Symfony\\Component\\HttpFoundation\\File\\UploadedFile->__construct('/tmp/php3UHqgl', 'Moon.jpg', 'image/jpeg', 12474, 0)\n#2 /var/www/vendor/symfony/http-foundation/FileBag.php(52): Symfony\\Component\\HttpFoundation\\FileBag->convertFileInformation(Array)\n#3 /var/www/vendor/symfony/http-foundation/FileBag.php(61): Symfony\\Component\\HttpFoundation\\FileBag->set('file', Array)\n#4 /var/www/vendor/symfony/http-foundation/FileBag.php(40): Symfony\\Component\\HttpFoundation\\FileBag->add(Array)\n#5 /var/www/vendor/symfony/http-foundation/FileBag.php(31): Symfony\\Component\\HttpFoundation\\FileBag->replace(Array)\n#6 /var/www/vendor/ in /var/www/vendor/symfony/http-foundation/File/File.php on line 37, referer: http://localhost/index.php?route=add-fact&ged=Duck&xref=I74&fact=OBJE

**Comment by fisharebest** [comment]
This error seems to be happening in the call to `Request::createFromGlobals()`.

This is pretty much the first line of code in `index.php`, and it reads the request parameters from the PHP globals; `$_POST`, `$_GET`, `$_COOKIES`, etc., and most significantly, [`$_FILES`](http://php.net/manual/en/reserved.variables.files.php)

Maybe you could add some debugging code here (immediately above the call to `createFromGlobals()`) which checks that the temp-file actually exists.

You might also want to check the errors for this upload - see http://php.net/manual/en/features.file-upload.errors.php

**Comment by makitso** [comment]
Greg, the problem is with vendor/symfony/http-foundation/Request.php.  By reverting the changes made on Sept 14 - patch f5666b2 the problem goes away.

**Comment by fisharebest** [comment]
I've looked at the changes in http-foundation between 3.4.14 and 3.4.15.

As far as I can tell, then only changes are to the way it handles trusted headers (i.e. which may have been set by proxy servers).

Maybe there is a side-effect in one of the other changed libraries?

Is there a server which is (a) having the problem, and (b) I could access via FTP?

**Comment by makitso** [comment]
Resolved with patch   117c5bd
