### ISSUE TITLE
2.0: GEDCOM Import Page Warns of Different File Name when Same File is Used

### ISSUE THREAD

**Issue by dbq-andersons** [fisharebest/webtrees#1956]
Good Day,

When importing a GEDCOM from a file on my server, the GEDCOM Import page warns me that I'm about to import a file with a different name even though I use the same file for all my imports into a given tree (full-tree_webtrees.ged in this case).

![image](https://user-images.githubusercontent.com/43183321/46682731-fa140280-cbb3-11e8-902d-b346ec6ca5e3.png)

Warning only appears when I use "A file on the server".  When I import from "A file on your computer" 
 and use a local copy of the above-mentioned GEDCOM, the warning is not displayed, as expected.

Thanks,

Bill Anderson

**Comment by fisharebest** [comment]
Can you look in your database, and tell me the result of

```sql
SELECT setting_value FROM `wt_gedcom_setting` WHERE setting_name='gedcom_filename';
```

**Comment by dbq-andersons** [comment]
```
mysql> SELECT setting_value FROM `wt2_gedcom_setting` WHERE setting_name='gedcom_filename';
+-----------------------------+
| setting_value               |
+-----------------------------+
| scrubbed-tree_webtrees.ged  |
| sanitized-tree_webtrees.ged |
+-----------------------------+
2 rows in set (0.00 sec)

mysql>
```

Those are the filenames of the gedcoms I import for the trees on this site.

Thanks for the help.

Bill
