### ISSUE TITLE
2.0: 

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#1963]
Auto Upgrade from alpha.2 to alpha.3 gives an error: 
Client error: `GET https://github.com/fisharebest/webtrees/releases/download/2.0.0-alpha.3/webtrees-2.0.0-alpha.3.zip` resulted in a `404 Not Found

**Comment by fisharebest** [comment]
I noticed this yesterday, and couldn't work out what was wrong.

Now, with fresh eyes, I see that the upload file was called `.alpha-3.zip` instead of `-alpha.3.zip`.

I have now renamed the file.
