### ISSUE TITLE
webtrees 1.7.11 does not work under PHP 7.2 (javascript related)

### ISSUE THREAD

**Issue by abalage** [fisharebest/webtrees#1967]
Hello,

I tried to use 1.7.11 with PHP 7.2. Although with 7.1 it works in 7.2 it does not, I only presented with a blank page.

I managed to track down to the issue to PageController->pageHeader --> escapeJs
While I am on 7.1 I can see in the web site logs error messages  like this:

```
/var/www/csaladfa/app/Filter.php:72 iconv(): Wrong charset, conversion from `UTF-8' to `UTF-16BE' is not allowed
#0 unknown:unknown ErrorException("iconv(): Wrong charset, conversion from `UTF-8' to `UTF-16BE' is not allowed")
#1 /app/Filter.php:72 iconv('UTF-8', 'UTF-16BE', 'ó')
#2 unknown:unknown Fisharebest\Webtrees\{closure}([array])
#3 /app/Filter.php:78 preg_replace_callback('/[^A-Za-z0-9,. _]/Su', [Closure], 'Kiss János családfája')
#4 /admin_trees_manage.php:417 escapeJs('Kiss János családfája')
```

The Hungarian text says, "Pedigree of Little John" with accented letters.

On 7.2 I cannot check the web site as I presented with a blank page (not html, nothing, I got http 200 only). If I manually edit the code I got to that escapeJs part, anything written to the code _before_ escapeJs gets printed, nothing after.

On 7.2 I tried to rename the pedigree to not to use accented letters, and this made the main part of the site rendered, but most of the site is still missing.

Going back to 7.1 and checking the errors I don't see that particular error but I see others. Like this.

```
 /var/www/csaladfa/app/Filter.php:72 iconv(): Wrong charset, conversion from `UTF-8' to `UTF-16BE' is not allowed
#0 unknown:unknown ErrorException("iconv(): Wrong charset, conversion from `UTF-8' to `UTF-16BE' is not allowed")
#1 /app/Filter.php:72 iconv('UTF-8', 'UTF-16BE', 'Ú')
#2 unknown:unknown Fisharebest\Webtrees\{closure}([array])
#3 /app/Filter.php:78 preg_replace_callback('/[^A-Za-z0-9,. _]/Su', [Closure], 'Re: Új regisztráció a(z) ht…')
#4 /app/Module/UserMessagesModule.php:137 escapeJs('Re: Új regisztráció a(z) ht…')
#5 /index.php:110 getBlock(32)
```

The Hungarian text "Re: Új regisztráció a(z) ht" comes from news page mentioning that a new registration has been made. If I delete those news items, almost everything gets rendered correctly... except Control panel -> Web server logs.

PHP 7.1 is based on official Docker image (iconv is installed btw)
PHP 7.2 is based on OpenSUSE Leap 15 docker image (iconv is also installed).
Browser: Firefox 60 ESR, no JS blocking addon is in place

The two environments I admit are quite different. Let me know what information do you need.

**Comment by abalage** [comment]
Checking individuals I got very similar to this: #650

**Comment by fisharebest** [comment]
> PHP 7.2 is based on OpenSUSE Leap 15 docker image (iconv is also installed).

What encoding does your iconv library support?  Type `iconv -l` at the command line.
Does the output include `UTF-16BE`.

On 

```
$ iconv -l | grep UTF
UTF-8 UTF8
UTF-8-MAC UTF8-MAC
UTF-16
UTF-16BE
UTF-16LE
UTF-32
UTF-32BE
UTF-32LE
UNICODE-1-1-UTF-7 UTF-7 CSUNICODE11UTF7
```

**Comment by abalage** [comment]
Hm does not look like it is there.

PHP 7.1
```
root@acf5656bdfc0:/run# iconv -l | grep UTF
ISO-10646/UTF-8/
ISO-10646/UTF8/
UTF-7//
UTF-8//
UTF-16//
UTF-16BE//
UTF-16LE//
UTF-32//
UTF-32BE//
UTF-32LE//
UTF7//
UTF8//
UTF16//
UTF16BE//
UTF16LE//
UTF32//
UTF32BE//
UTF32LE//
root@acf5656bdfc0:/run# php -v
PHP 7.1.22 (cli) (built: Sep 15 2018 03:39:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.22, Copyright (c) 1999-2018, by Zend Technologies
```

PHP 7.2
```
c732ddf02cdb:/var/www # iconv -l | grep UTF
ISO-10646/UTF-8/
ISO-10646/UTF8/
UTF-8//
UTF8//
c732ddf02cdb:/var/www # php -v
PHP 7.2.5 (cli) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.5, Copyright (c) 1999-2018, by Zend Technologies
```

Do you have any idea how can I add them? As far as I know iconv is part of glibc, which is installed of course. The only thing I can think of is that they removed it during creation of Docker image to reduce the size of the final image.

**Comment by fisharebest** [comment]
I have no experience of docker, but a quick search finds the following issue, which may be relevant to you.

https://github.com/docker-library/php/issues/240

Another suggestion would be to start using the webtrees 2.0.0 (alpha.3) release.  The 2.0.0 code removes the dependency on iconv/UTF16

**Comment by abalage** [comment]
I found out that glibc-local package provides those missing encodings. After I installed it, it looks to be working, though the error message remains.

I am not planning to upgrade to 2.0.0 before it reaches RC, but thanks for the help and the advice. This case can be closed.
