### ISSUE TITLE
Admin - Clean-up Data Folder gives error - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1974]
League\Flysystem\NotSupportedException: Links are not supported,  encountered link at /data/media in file  /vendor/league/flysystem/src/NotSupportedException.php on line 21

**Comment by fisharebest** [comment]
Symbolic links are not supported by the filesystem abstraction layer: https://github.com/thephpleague/flysystem/issues/599

**Comment by melizaa** [comment]
What should I do?

**Comment by fisharebest** [comment]
It would be easier to answer a specific question.

What do you want to acheive?  Share all your media folders between all your webtrees installations?

**Comment by melizaa** [comment]
Yes, I use the same media folders for all my installations.

**Comment by melizaa** [comment]
I had an media folder in the data folder. I removed it and the error vanished.

**Comment by melizaa** [comment]
Now I do no longer see the media in the test systems. The media is shared with my production system.

**Comment by melizaa** [comment]
I added one media file to the future test system.
The data/media/ folder was created.

How do I share media between two wt 2.0.0. installations?

How do I share media from my production pre wt2.0.0 to my test wt2.0.0 installation? I assume that the link that I had and that worked, caused this issue and error message.

**Comment by melizaa** [comment]
#2418
