### ISSUE TITLE
Admin - Manage family trees - Family tree - Privacy - gives error - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1975]
ErrorException: Undefined property: stdClass::$tag_label in file   /app/Http/Controllers/AdminController.php on line 1516

**Comment by melizaa** [comment]
I do no longer see the error.

**Comment by fisharebest** [comment]
I think this is still an issue.  The error only occurs for certain combinations of data.

Re-opening until I can check this.

**Comment by fisharebest** [comment]
I think this is now fixed
