### ISSUE TITLE
"Mohyliv Podil&#039;s&#039;kyi" for report root persons - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1981]
When I move the mouse over the report root person's date or name and this person has an apostrophe in the place, for instance Mohyliv Podil's'kyi, I see & and #039; instead of the apostrophe.          

See Haim Faust and Lippa Rosenzweig in my test system big tree          

See #1915

![2018-10-17_14-16-04](https://user-images.githubusercontent.com/5202996/47082756-5b248180-d217-11e8-957a-c72c5b442007.jpg)

**Comment by fisharebest** [comment]
Should be fixed in e842485be

**Comment by melizaa** [comment]
I do not see it correctly

**Comment by fisharebest** [comment]
Fixed in 2d4c1bed2
