### ISSUE TITLE
"Mitel&#039;man" for chart root person - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1982]
When I move the mouse over the chart root person's name and this person has an apostrophe in the name, for instance Mitel'man, I see & and #039; instead of the apostrophe.           

See Meir Mitel'man in my test system big tree          

See #1915

![chartname46916691-aac03e80-cfc6-11e8-81a6-b8827e894b79](https://user-images.githubusercontent.com/5202996/47082926-e00f9b00-d217-11e8-8333-2e38db2573f8.jpg)

**Comment by fisharebest** [comment]
Should be fixed in e842485be

**Comment by melizaa** [comment]
I do no longer see anything when I move the mouse over the root person's name
