### ISSUE TITLE
"Mitel&#039;man" for report root person - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1983]
When I move the mouse over the report root person's name and this person has an apostrophe in the name, for instance Mitel'man, I see & and #039; instead of the apostrophe.           

See Meir Mitel'man in my test system big tree          

See #1915

![reportname46916695-b14eb600-cfc6-11e8-921a-5678555177cc](https://user-images.githubusercontent.com/5202996/47083075-498fa980-d218-11e8-844e-cf0f6723dd1d.jpg)

**Comment by fisharebest** [comment]
Should be fixed in e842485be

**Comment by melizaa** [comment]
I do no longer see anything when I move the mouse over the root person's name
