### ISSUE TITLE
The rtl edit drop down menu - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1984]
We should see the menu on rtl pages from the leftmost border of the edit icon to the right. Now it prints to the very left or left from almost the middle of the edit icon.          

Individuals, families, shared notes, media objects, sources, repositories

![rtl2018-10-17_15-08-10](https://user-images.githubusercontent.com/5202996/47085445-51068100-d21f-11e8-9751-36185e66ef01.jpg)

![rtl2018-10-17_15-09-16](https://user-images.githubusercontent.com/5202996/47085450-5663cb80-d21f-11e8-85fa-2317b652ff64.jpg)

![2018-10-17_15-16-01](https://user-images.githubusercontent.com/5202996/47085552-9f1b8480-d21f-11e8-89e0-6ddad244597f.jpg)

**Comment by fisharebest** [comment]
There is an open issue for this on the bootstrap-rtl library:
https://github.com/MahdiMajidzadeh/bootstrap-v4-rtl/issues/26

**Comment by melizaa** [comment]
Now I see
![2019-03-06_12-51-41](https://user-images.githubusercontent.com/5202996/53876293-258a0480-400f-11e9-8f0d-e6e467c656dd.jpg)

**Comment by fisharebest** [comment]
We now use our own "mirror-css" version of bootstrap, which fixes most of there.

There is still a smaller issue with some javascript positioning, which is covered by #2315
