### ISSUE TITLE
Importing a Gedcom file gives error - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1987]
I decided to import my big Gedcom file again to the test system.     
I exported it from the pre 2.0.0 production site.         

I get error     
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry   'I2823-2' for key 'PRIMARY'

**Comment by fisharebest** [comment]
Can you confirm that the GEDCOM file does not contain two copies of individual `@I2823@`.

Is this error reproducable?  What happens if you try to import the GEDCOM file again?

**Comment by melizaa** [comment]
I tried to import again. The same error.

I edited the Gedcom file and saw the individual ID only once. I see also 
indies I28280-I28289 with a few missing.
I do not see in another Gedcom a I2828.

Is it possibile that some data was not deleted before the importing?

Do you know which data is duplicate?

The indi has one 1 NAME with a 2 _HEB name and one birth and one death record.

Should I try to look at the DB tables? I have not done that.

On October 18, 2018 17:05:05 Greg Roach <notifications@github.com> wrote:
> Can you confirm that the GEDCOM file does not contain two copies of 
> individual @I2823@.
> Is this error reproducable? What happens if you try to import the GEDCOM 
> file again?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


Sent with AquaMail for Android
https://www.mobisystems.com/aqua-mail

**Comment by fisharebest** [comment]
When I looked at your site, I could see that `I2823` was already imported into the wt_individuals table, and it was also the next record to be imported from the wt_gedcom_chunk table.

When we get these database errors, we do not see which code was being executed - or any other useful imformation.  I will see if I can improve this.

**Comment by melizaa** [comment]
Ups! - I looked for I2828.
I2823 has one 1 NAME, 2 times 1 DEAT, 2 times 1 BIRT

I imported again. I get as the 1st time
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '46320-I2828-2' for key 'PRIMARY'

**Comment by fisharebest** [comment]
OK - this is a slightly different error.  Can you email me the GEDCOM file?

**Comment by melizaa** [comment]
Yes

**Comment by fisharebest** [comment]
I see the problem.

This record contains the same place name twice - once with accented-letters and once without.

PHP sees these as different text, and tries to create both entries in the database.

MySQL sees these as the same text, and complains at the duplicate.

**Comment by melizaa** [comment]
The place exists only once with a 2 PLAC. The second time is a 2 NOTE that should not update the places table.

I have used this way to record places for a long time. It works in pre 2.0.0.

Please re-open this.

**Comment by melizaa** [comment]
Thanks!

I updated the Death place and I imported the Gedcom file.

I do still not see the data for instance of I63. I see it only in Edit the raw GEDCOM.
https://github.com/fisharebest/webtrees/issues/1986
