### ISSUE TITLE
I need a way to verify that all the data is shown on the site as expected. 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1990]
I need some utility (for instance the admin - manage family trees - genealogy data - check for errors) to verify if there are any additional records whose data is not shown fully on my test site although I see the data in GEDCOM raw editing. 

I would like to see at least the record ID. 

See #1986

**Comment by fisharebest** [comment]
I do not really understand what you are asking for?

#1986 looks like a fatal error that prevented the tab from displaying.

**Comment by fisharebest** [comment]
I am not sure that this is possible.

Any such tool would use the same underlying code.

If there was a problem with the code, then the tool would also have the same problem.
