### ISSUE TITLE
Changes report range does not work as expected - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1992]
I run the report with dates 21 Sep 2018 and 21 Oct 2018.

The report shows changes since 1 Jan 2018.

**Comment by fisharebest** [comment]
The report shows recent (accepted) changes for a given date range.

It also has an option to show all pending changes.

> The report shows changes since 1 Jan 2018.

Do you see pending changes or recent changes?

**Comment by melizaa** [comment]
I do not have any pending changes.
I see only recent changes.

I see in the report dates 2018 - 2018 although I selected today 22 Sep 2018 and 22 Oct 2018
![2018-10-22_22-11-02](https://user-images.githubusercontent.com/5202996/47313669-30d42900-d648-11e8-985d-e434bd6b8905.jpg)
.

**Comment by melizaa** [comment]
Works now as expected.
