### ISSUE TITLE
2.0: GEDCOM Import Not Populating Some Media Information

### ISSUE THREAD

**Issue by dbq-andersons** [fisharebest/webtrees#1995]
When importing a GEDCOM exported from RootsMagic 7 (sample attached), the descriptive_title and source_media_type fields in ##media_file are not being populated (table attached).  This, in turn, causes issues with record duplication in that table if an image is referenced multiple times in that export as well as the descriptive_title being missing from several places around the site (slide-show screenshot attached).

![image](https://user-images.githubusercontent.com/43183321/47364868-eb434a80-d69f-11e8-85fb-c3dbd67c2b48.png)

![image](https://user-images.githubusercontent.com/43183321/47364448-f21d8d80-d69e-11e8-811f-c5e44f5b9b53.png)

[hans-anderson.ged.txt](https://github.com/fisharebest/webtrees/files/2506310/hans-anderson.ged.txt)

**Comment by dbq-andersons** [comment]
I fixed the issue for me by adding these lines to app/Functions/FunctionsImport.php

```
1123             // Fix RM7 GEDCOMS
1124             $gedrec = preg_replace('/\n1 FILE (.+)\n1 FORM (.+)\n1 TITL (.+)/', "\n1 FILE $1\n2 FORM $2\n2 TITL $3", $gedrec);
```

descriptive_title now imports properly and over 3K images per tree are down to the expected 841.

Assuming you don't think this will break anything (I'm pretty sure it won't, but as I've said here before, you guys know the code better than I do), please add those lines to app/Functions/FunctionsImport.php so it gets included in future releases.

**Comment by fisharebest** [comment]
Can you provide a sample GEDCOM produced by Roots Magic that I can use for testing?

**Comment by dbq-andersons** [comment]
I thought I attached one when I opened the issue, but I may have forgotten.  Here is a GEDCOM with only my great-grandfather (deceased).  It contains several image references; it is the one I was testing with.

[hans-anderson.ged.txt](https://github.com/fisharebest/webtrees/files/2510369/hans-anderson.ged.txt)
