### ISSUE TITLE
I do not see Statistics - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2003]
I see error for:
Month of birth - date periods 
Month of death - date periods
Month of marriage - date periods

Month of first marriage

I  do not (yet?) see anything in the Website Log

**Comment by melizaa** [comment]
After  37ff053 I still see that the month of firts marriage for the date period runs and runs still.
This chart is not yet solved. I see still the word "error".

**Comment by melizaa** [comment]
After a longish time I see the charts.

Sorry!

**Comment by fisharebest** [comment]
The reported error was a bug that prevented these charts from being created.
This was fixed.

> This chart is not yet solved. I see still the word "error" on the chart form.

The chart is taking longer than 60 seconds to generate, and so the webserver is giving a timeout error.

So, this is a different issue.
