### ISSUE TITLE
Privacy page 'Show private relationships' wrong text - 2.0.0 & 1.7.11

### ISSUE THREAD

**Issue by liegebe** [fisharebest/webtrees#2006]
Hi,
On the page  Control panel > Manage family trees > Privacy (index.php?route=tree-privacy&ged=tree1), at 'Show private relationships' (at the bottom of the page) there is 2 options: 'Show to visitors' and 'Hide from everyone'. When choosing 'Show to visitors', it selects 'members' on the right (visitor block is grey and members block is green). I guess the text there should be 'Show to members'.
This is in 1.7.11 as well as the 2.0.0-alpha.3.

**Comment by fisharebest** [comment]
> When choosing 'Show to visitors', it selects 'members' on the right (visitor block is grey and members block is green)

Does it?

If I select "show to visitors", then both blocks are green.
If I select "hide from everyone", then both blocks are grey.

If you have one block green and one block grey, then can you post a screendump showing this?

**Comment by fisharebest** [comment]
I cannot reproduce this issue.  Can you provide more information (screenshots, etc.?)

**Comment by liegebe** [comment]
When selecting 'Show to members' for 'Show the family tree' at the top of the page, then all the 'visitors' blocks below are becoming grey - which makes sense. Then when selecting 'Show to visitors' in any menu below, the visitor block stays grey.

The thing which was confusing me is, in this particular case when the tree has to be shown to members only, that you have to select 'Shows to visitors' when you want to 'Show to members'. The colour of the block is correct, but the text is confusing. I understand the logic behind it and why it was made like this, though.

Please see a screenshot here : https://i.postimg.cc/yY08BGd5/webtrees.jpg

When the visitors block are all becoming grey after selecting show to members only in the first menu, maybe the text below should become "members" instead of "visitors" also. Up to you, this is not really a bug, this is even not very important and maybe no one else but me is confusing with it.

**Comment by fisharebest** [comment]
> maybe no one else but me is confusing with it.

Nobody else has reported this issue, so perhaps yes ;-)
