### ISSUE TITLE
Homepage 'Link below' text even if no link - 2.0.0

### ISSUE THREAD

**Issue by liegebe** [fisharebest/webtrees#2007]
On the default homepage you have the following text 'Welcome to this genealogy website. Anyone with a user account can access this website. **You can apply for an account using the link below**.'
This is written even if the option of allowing user to apply is deactivated, without any link following.

**Comment by fisharebest** [comment]
The text is a configuration option:
Control panel -> Sign-in and registration -> Welcome text on sign-in page.

It is possible to select "Do not allow users to request an account" at the same time as selecting the text "Visitors can request an account".

**Comment by liegebe** [comment]
Alright, thank you for the answer!
