### ISSUE TITLE
Index length

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#2009]
InnoDB servers have a maximum index length of 767 or 3072 bytes.

The `wt_media_file` table requires more than 767.

We need to detect this limitation.

Options are:

* use a partial/prefix index
* do not use an index

**Comment by ungeahnt** [comment]
**Enclosed the response from hoster Strato regarding the error message "SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes."**

 (original text in german below):
1) assumption: webtrees tries to create at least one table with a large index via MyISAM. However MyISAM  is no longer supported by Strato and the table is created with InnoDB-Engine instead.
2) By default Strato uses InnoDB with an ROW_FORMAT that allows no large index (presumable:  COMPACT). Therefore it is neccessary to change the ROW_FORMAT to DYNAMIC by oneself. Afterwards the use of indices > 767 Bytes should be possible.

------- original german text : ----------------------------------
> Offenbar möchte webtrees mindestens eine Tabelle, die einen großen Index benötigt, mit der Datenbank-Engine MyISAM anlegen. Diese wird in den STRATO Hosting-Paketen jedoch nicht länger unterstützt. Entsprechende Tabellen werden automatisch stattdessen mit der InnoDB-Engine angelegt.
> 
> Die InnoDB-Engine nutzt 4 unterschiedliche Zeilenformate ("ROW_FORMAT"), von denen zwei einen großen Index erlauben, die anderen beiden nicht. Standardmäßig verwenden unsere Datenbankserver ein ROW_FORMAT, das keinen großen Index erlaubt. Es ist daher notwendig, das ROW_FORMAT explizit selbst auf DYNAMIC einzustellen. Dann können auch Indizes mit mehr als 767 Bytes verwendet werden.
> 
> Bitte haben Sie Verständnis dafür, dass ich Ihnen nicht mitteilen kann, wo genau in den Installationsdaten von webtrees diese Anpassung vorgenommen werden kann. Hier können Ihnen die Entwickler der Software sicherlich weiterhelfen.
>

**Comment by fisharebest** [comment]
> Therefore it is neccessary to change the ROW_FORMAT to DYNAMIC

This should be possible.

**Comment by fisharebest** [comment]
Alternatively, we could just index the first 255 characters of the field

**Comment by SunsetGolfer** [comment]
This website is temporarily unavailable
An unexpected database error occurred.

    SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.
The webtrees developers would be very interested to learn about this error. If you contact them, they will help you resolve the problem.


Strato again ;-)

Can I change the ROW_FORMAT myself, or will a "fixed" version be available shortly?

**Comment by fisharebest** [comment]
Sorry for the delay in fixing this.  I have been on a dive boat in the Red Sea, with no phone/internet signal ;-)

I plan to release a fix when I return at the weekend.

**Comment by SunsetGolfer** [comment]
Well deserved hollidays - safe trip home!

Looking forward to test the fix.....

Kind regards
Jörg
