### ISSUE TITLE
html reports with LTR and RTL names and a marriage date - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2012]
Ancestors (ahnentafel) report
![2018-11-03_22-03-00](https://user-images.githubusercontent.com/5202996/47956863-8ac3df80-dfb4-11e8-931b-7ce448fc45c8.jpg)
and
![2018-11-03_22-15-47](https://user-images.githubusercontent.com/5202996/47956952-31f54680-dfb6-11e8-817d-30e6a5689214.jpg)

Related individuals (relative_ext_report)          
![2018-11-03_22-06-55](https://user-images.githubusercontent.com/5202996/47956884-f4dc8480-dfb4-11e8-920b-d1d77cbabdde.jpg)

The marriage day or year (only) print between the two names of the spouse,  instead of after the two names. 

The marriage date prints correctly after the parent's names in the   Descendants (descendancy_report)
![2018-11-03_22-22-42](https://user-images.githubusercontent.com/5202996/47957011-19396080-dfb7-11e8-88b0-c3d7d49c32c7.jpg)

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.

**Comment by melizaa** [comment]
When do you plan that the reports will work as expected?

**Comment by fisharebest** [comment]
If the TCPDF library doesn't understand UTF8 directional codes/overrides, then there is nothing we can do.

We will need to completely replace the reporting library.  This will be several months full-time work.

In terms of priorities, I need to look at GEDCOM 7.0 support first, which will include a more structured database.
