### ISSUE TITLE
LTR (English, ...) html reports - RTL nicknames - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2013]
In the LTR html reports, the RTL nickname end "prints to the right of the RTL name
![2018-11-03_22-34-32](https://user-images.githubusercontent.com/5202996/47957209-56532200-dfba-11e8-8546-65b934d02a1d.jpg)
![2018-11-03_22-37-46](https://user-images.githubusercontent.com/5202996/47957211-5d7a3000-dfba-11e8-90c0-ee1efb73a759.jpg)
![2018-11-03_22-43-07](https://user-images.githubusercontent.com/5202996/47957212-610db700-dfba-11e8-878a-64309b890b67.jpg)

See also for instance #1485 and #1488

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
