### ISSUE TITLE
RTL (Hebrew, ...) html reports - LTR nicknames - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2014]
In the RTL html reports, the LTR nickname end " prints to the left of the LTR name
![2018-11-03_22-54-58](https://user-images.githubusercontent.com/5202996/47957400-b26b7580-dfbd-11e8-83c3-19d58ef3543f.jpg)

![2018-11-03_23-08-46](https://user-images.githubusercontent.com/5202996/47957402-b6979300-dfbd-11e8-961a-b9d16629c909.jpg)

See also for instance #1485 and #1488

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
