### ISSUE TITLE
LTR (English, ...) PDF reports - RTL nicknames - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2015]
In the LTR pdf reports, the RTL nickname prints to the right of the RTL name. It should print to the left of the RTL name, in the same way as in the wt pages.
![2018-11-03_23-29-14](https://user-images.githubusercontent.com/5202996/47957550-80a7de00-dfc0-11e8-9145-7bbb611d1667.jpg)
![2018-11-03_23-32-57](https://user-images.githubusercontent.com/5202996/47957566-d8dee000-dfc0-11e8-9c53-4086719362b5.jpg)

See also for instance #1486

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
