### ISSUE TITLE
RTL (Hebrew, ...) PDF reports - LTR nicknames - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2016]
In the RTL pdf reports, the LTR nickname prints to the left of the LTR name or the RTL and LTR names print on two rows partially overlaping, the LTR nickname prints to the left and the RTL nickname looks wrong.
![2018-11-03_23-41-38](https://user-images.githubusercontent.com/5202996/47957682-5ad00880-dfc3-11e8-8fff-1320880003f9.jpg)

![2018-11-03_23-44-30](https://user-images.githubusercontent.com/5202996/47957683-5f94bc80-dfc3-11e8-9b10-61a4771381e3.jpg)

![2018-11-03_23-52-47](https://user-images.githubusercontent.com/5202996/47957708-a84c7580-dfc3-11e8-87c9-b38fbc3a827e.jpg)

The LTR nickname should print to the right of the LTR name, in the same way as in the wt pages.  

See also for instance #1487

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
