### ISSUE TITLE
Fresh Install Problem - the site doesnt render properly

### ISSUE THREAD

**Issue by ghanjiboy** [fisharebest/webtrees#2018]
Hi, On Windows, I have nginx, php 7 and MariaDB.  THe setup wizard came up fine, but as soon as its done, the site thats rendered looks like it has no styling.

![image](https://user-images.githubusercontent.com/1289510/47965155-998caf80-e011-11e8-8a68-c7c93ee777f6.png)

**Comment by fisharebest** [comment]
It is hard to know what is happening from the screendump.

Could be an error causing the page to terminated early.
Could be a failure to detect the site URL.

Do you know how to view the page source in your browser (typically CTRL-U) and look for errors?

Do you know how to use the developer tools (typically CTRL-SHIFT-I) to look at the loading tab and see what resources are failing to load?

**Comment by ghanjiboy** [comment]
Thanks for your response.  Yep, I did that, nothing in the console nor the network - everything seems to load OK.   I checked the nginx log files as well and theres nothing there either.  Is there some skin or ui library that needs to be loaded?

________________________________

**Comment by fisharebest** [comment]
Instead of a screendump, post the actual page.

Use your browser's "file, save" function to save the file to your disk, and then attach it here.

**Comment by ghanjiboy** [comment]
Please see files attached.
________________________________

**Comment by fisharebest** [comment]
You'll need to log in to github and attach it here.

Replying to emails does not work with attachments.

**Comment by fisharebest** [comment]
Ping @ghanjiboy

**Comment by ghanjiboy** [comment]
Thanks  for following up, I found another solution and move on.  Have a good holiday.
