### ISSUE TITLE
2.0 - Error in log file

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2022]
ErrorException: Undefined index: I0001 in file /resources/views/timeline-page.phtml on line 60 Stack trace: 1. ErrorException->() /resources/views/timeline-page.phtml:60 2. {closure}() /resources/views/timeline-page.phtml:60 3. include() /app/View.php:140 4. Fisharebest\Webtrees\View->render() /app/View.php:184 5. Fisharebest\Webtrees\View->make() /app/Helpers/functions.php:84 6. view() /app/Http/Controllers/AbstractBaseController.php:199 7. Fisharebest\Webtrees\Http\Controllers\AbstractBaseController->viewResponse() /app/Http/Controllers/TimelineChartController.php:121 8. Fisharebest\Webtrees\Http\Controllers\TimelineChartController->page() [internal]:0 9. ReflectionMethod->invoke() /app/Resolver.php:87 10. Fisharebest\Webtrees\Resolver->dispatch() /index.php:326 11. {closure}() /app/Http/Middleware/CheckForMaintenanceMode.php:48 12. Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->handle() /index.php:321 13. {closure}() /app/Http/Middleware/PageHitCounter.php:106 14. Fisharebest\Webtrees\Http\Middleware\PageHitCounter->handle() /index.php:321 15. {closure}() /app/Http/Middleware/Housekeeping.php:70 16. Fisharebest\Webtrees\Http\Middleware\Housekeeping->handle() /index.php:321 17. {closure}() /index.php:329

**Comment by fisharebest** [comment]
Hmmm.  It's hard to see what might have caused this.

We have two arrays that are generated from the same list.
The error says that an array key was found in one, but not the other.

What was the timestamp of the error?   Was it generated by the latest code or is this an old error?

**Comment by fisharebest** [comment]
I've managed to reproduce this by specifying an XREF in the URL which is an upper/lower case mismatch for an existing record.  i.e. creating a url with `&xref[]=i123` when the actual xref is `I123`.
