### ISSUE TITLE
Alternative Traking Engines

### ISSUE THREAD

**Issue by legle** [fisharebest/webtrees#2024]
Mautic is a CRM for digital marketing automation and has a tracking engine similar to google Analitics, but the webtrees control panel does not have a field where I can paste the maltic tracking javascript code.

is it possible to implement this functionality in the Webtrees control panel?

**Comment by fisharebest** [comment]
I've spent 10 minutes looking at the mautic website, and cannot find

1) a description of what it does.
2) the tracking javascript.

It appears to be very specialised, and unrelated to webtrees or genealogy.
So, I am not persuaded to add support to webtrees.

There is a plugin for webtrees called "custom javascript", which allows you to add your own javascript to every webtrees page.   I recommend that you use this module on your site.

**Comment by legle** [comment]
Mautic is a digital marketing manager.

The tracking feature has the same goal as google analytics.

It is not necessary to add a specific functionality to Mautic, but there should be a native functionality to include custom Javascript code.

I found the plugin but did not find the button to download.
