### ISSUE TITLE
2.0 - Add Media from Server misses some items

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2025]
Individual, add media object, Media file, File on Server.  Autofill list does not match list of media files in database table wt_media_file.

![image](https://user-images.githubusercontent.com/5147603/48662454-58e45b80-ea3f-11e8-999f-41a905a21716.png)

![image](https://user-images.githubusercontent.com/5147603/48662455-5f72d300-ea3f-11e8-9b37-a6a9307ae7ed.png)

**Comment by makitso** [comment]
The problem is that variable m_file is not set to the correct tree.  In the case above m_file is set to 3 when it should be set to 1.

**Comment by makitso** [comment]
> When you create a media object from a file on the server, the list of files in the dropdown should only include "unused" files.
Yes, unused files but filtered on m_file.

As the code now stands, if you have multiple trees, the list of Unused files is based  upon the last tree not the tree in use.  I have two tree with an m_file of 1 and 3.  One is the tree where I am doing the add.  but, m_file has a value of 3.

**Comment by makitso** [comment]
Actually, I am confused by this whole approach.  On my prod system I have no unused files.  So, the dropdown should be empty.  As it stands the dropdown has "all" the file shown for the wrong gedcom tree.

**Comment by fisharebest** [comment]
The system is (for me), working as designed.

Is this still an issue for you?

**Comment by makitso** [comment]
Have not tried this in a while so lets close it.
