### ISSUE TITLE
Re-use age, work, etc. data from census assistant shared note

### ISSUE THREAD

**Issue by Bonbadil** [fisharebest/webtrees#2027]
Hello,

I use webtrees master branch (updated today) in French version and when I submit a census assistant with age or work data, this age is not reused in the census event created for all the individual linked.
I'm new to this, but I think the event should be filled with all the data available from the census.

**Comment by Bonbadil** [comment]
I've filled more census assistants, and when the age is reused in the census event it's only one's of the family's chef, the first individual of the list, which is affected to all people.

**Comment by fisharebest** [comment]
Can you give an example?

I do not use the census-assistant, and I do not understand the problem.

> when I submit a census assistant with age

There is an "age" field in each row of the table.
There is an "age" field for the entire census event.

**Comment by Bonbadil** [comment]
Yes, sorry, I was not very clear, even for me. :)

When I fill the census assistant's table with a whole family, and fill the age field for each member on each row, every member get in their automatically generated census event the age of the first row (or of the family head, the first row was always the family head for me).
So I have to edit each census event to put the right age, except the family head's one of course.

**Comment by Bonbadil** [comment]
I will try to be more clear: :)

### What I did:
I've added 2 test census in the English Royal Family.
One in 1871 with the age field of the event (not the census table) leaved empty:
![census without age](https://user-images.githubusercontent.com/833234/49331876-1aed4880-f5a4-11e8-8f71-3b799f299048.png)
One in 1881 with the age field of the event filled:
![census with age](https://user-images.githubusercontent.com/833234/49331879-3b1d0780-f5a4-11e8-83cd-ecd484f4cb0b.png)

### What I get:
For the father:
![result on father](https://user-images.githubusercontent.com/833234/49331885-699ae280-f5a4-11e8-8cb4-c6bc495781f1.png)
For the son:
![result on son](https://user-images.githubusercontent.com/833234/49331886-6f90c380-f5a4-11e8-861e-7e6803429d6e.png)
The age field of the census event are copied in the census event of everyone.

### What I expected:
The age field of the census table for each person is copied in the the age field of the census event created by the census assistant for this person.
So in the Facts and events list, after the first test, the father should have get "2 April 1871 (Age 29 years) Age: 29" in his event, his wife "2 April 1871 (Age 26 years) Age: 26" and their son "2 April 1871 (Age 5 years) Age: 5".

**Comment by fisharebest** [comment]
OK - now I understand.

The census-assistant creates a GEDCOM `CENS` event - with a transcript of the census.

It then copies this event to all individuals in the transcript.

If you add other attributes to the event (e.g. `SOUR`, `OBJE`, etc.) then these are also copied to all individuals.

If you add an `AGE` attribute to a `CENS`, then this is also copied to all individuals - which is incorrect.

The simple solution is to remove the `AGE` before copying to all individuals.

A more complex solution is to ignore the `AGE` attribute, and generate it automatically from the transcript.  This is difficult, because once we have created the transcript (in the browser), the server does not know the meaning of each column.  It does not even know that the transcript is a table.  It is treated simply as text.

**Comment by Bonbadil** [comment]
The `AGE` should at least be removed when copied to all individuals. Because now the census assistant actually add false informations. In my example it's obvious, but in real case it take me time to spot and understand the error.

About the complex solution: I'm concerned about the age, because census is one of the few source I dispose to estimate birth years (or even decade) and then find birth acts. But other users could be more interested in work occupation, residence, marital status, etc.
Even for the age, there could be several column about it. These columns change between country and date of census...
To be more universal, in the census shared note view maybe it could be very useful to have the transcript viewable above the linked individual list, with links to add/edit birth, death (> date of census), marriage (Y, < date of census), occupation or residence events.
![image](https://user-images.githubusercontent.com/833234/49341678-5003a480-f651-11e8-8632-e640b4f9dbc0.png)
This way, users can decipher the handwritten census into the census assistant, and when it's recorded they have a synthetic view of it above one of the censused individuals and quick links to add usable information.
Do you think it could be a good compromise?
