### ISSUE TITLE
Places redesign

### ISSUE THREAD

**Issue by dkniffin** [fisharebest/webtrees#203]
I think the whole system of places in webtrees could use a major redesign. 

Major changes to be made:
- Remove reliance on Google Maps module
- Allow users to manage places at input-time (vs post-input in admin interface). This should reduce a lot of issues
- Implement hooks in various places to allow modules to interface with eg: input fields
- Clean up database schema
- Improve efficiency

If anyone can think of other major changes they'd like to see made to places, post a comment, and I'll consider adding it to the list.

**Comment by loudubewe** [comment]
Yes, there is a lot of problems whit places.

First of all, it is a gedcom problem. The details about a place should be in a '0 @P1234@ PLAC' record, containing all general common informations about a place so that this record could be referenced many times with an XREF (e.g. 'n PLAC @1234@', followed at 'n+1' by details about the place in the context of the specific event).
<a href="http://www.beholdgenealogy.com/blog/?p=899">An interesting comment on this subject</a>.

In WT, long fully qualified place names create some messy reports. That's because the treatment of the 'truncate' propriety in these 'report.xml' files is not (yet?) implemented in the 'gedcomValueStartHandler' function (in 'Base.php').

Sorry if this comment is not very helpful but I really don't know where to begin with that issue.

**Comment by fisharebest** [comment]
> <a href="http://www.beholdgenealogy.com/blog/?p=899">An interesting comment on this subject</a>

This raises an interesting question.

Are place records global (shared by all trees) or local (each tree has its own copy).

Intuitivley, they are global.  This is how the googlemaps module works.

But it means that when we import two trees containing place recrods, then one will overwrite the other...

**Comment by Amgine0** [comment]
On 2015-01-18 10:12 AM, Greg Roach wrote:
> An interesting comment on this subject 
> <http://www.beholdgenealogy.com/blog/?p=899>
> 
> This raises an interesting question.
> 
> Are place records global (shared by all trees) or local (each tree
> has its own copy).
> 
> Intuitivley, they are global. This is how the googlemaps module
> works.
> 
> But it means that when we import two trees containing place
> recrods, then one will overwrite the other...


Or a conflict report is generated for manual harmonization.

**Comment by loudubewe** [comment]
Yes, for sure, importing and merging trees is a challenging task. Nevertheless, merging places seems easier than merging individuals or families, not speaking of sources or objects.
Many years ago, I was very impressed by the merging tool of the Legacy software. From time to time, it helped me to merge unnoticed (and hard to notice) duplicate individuals!
In our case, for place records, I would suggest an (optional) automatic merge when the 2 records are exactly the same and a suggested manual merge in case of important similarities, as proposed by Amgine0.
As noted by ddury, there often are multiple names for the same place, for historical or political reasons.
There would be no real inconvenient to have 2 records for the same place, with different names (e.g. Léopoldville and Kinshasa). It would be a little more difficult to conceive a place record with multiple names.
Finally, gedcom standard compatibility is an important issue. What do 'webtrees' think about the <a href="https://github.com/FamilySearch/gedcomx">gedcomx</a> project?

**Comment by fisharebest** [comment]
> What do 'webtrees' think about the <a href="https://github.com/FamilySearch/gedcomx">gedcomx</a> project?

I have never seen it before.  I looked quickly.  The first thing I saw was:

> Dates MUST be specified using the proleptic Gregorian calendar.

There can be two different recorded dates that are the same in the proleptic Gregorian calendar.

e.g. `@#DJULIAN@ 23 FEB 1732/33` and `@#DJULIAN@ 23 FEB 1733`
e.g. `29 FEB 1879` and `01 MAR 1879`

So, if you store the converted date, you lose your original data.  This sucks.

**Comment by fisharebest** [comment]
> Remove reliance on Google Maps module

Done.  We now use OpenStreetMap as our default map provider.

> Improve efficiency

Done.  Low-level caching has been added, and each place / location is only queried once.

> Implement hooks in various places to allow modules to interface with eg: input fields

Done - the 2.0 module system allows modules to modify pretty much anything.

-----

I'm going to close this issue now.  It is a little vague/general in scope, and we have addressed much of it.  If you have any specific requests/suggestions, please create a separate issue for each of them.
