### ISSUE TITLE
Emails with 2-Step Gmail Authentification - How? - 2.0 and Pre 2.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2044]
I have secured my Gmail account with 2-Step Authentification.
Since then no mails are sent from my wt sites.
How should I configure the Sending email and the Application password in Gmail?

**Comment by melizaa** [comment]
I defined the sending the way that it is defined in /index.php?route=admin-site-mail and my Gmail account received the mail.

I will do the same on my other wt sites.

**Comment by fisharebest** [comment]
According to this link, you can create a separate "app password" for using SMTP, which means you won't need to use your google password in webtrees.

**Comment by melizaa** [comment]
What should I write in the app?
Should I have different application passwords for each wt site?

**Comment by melizaa** [comment]
I tried to send a visitor message to the pgv-dev administrator. Did it work?

**Comment by melizaa** [comment]
The admin gets now mails from test visitors.
