### ISSUE TITLE
Edit the user - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2046]
The admin does not see user Roles and cannot update the Roles.

**Comment by fisharebest** [comment]
This is working for me.  Can you give more details?

**Comment by melizaa** [comment]
This is what I see
![2018-11-29_22-43-05](https://user-images.githubusercontent.com/5202996/49250765-624eca00-f428-11e8-8d13-5e1d3f4e436a.jpg)

I cannot see any role.
