### ISSUE TITLE
Age hidden with DEAT Y but not with DEAT

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#2052]
Noticed in versions 1.7.11 and 1.7.12.

When I import individuals with 1 DEAT and then view the individual page, it shows me their 'age' in the name banner.  However, if I add a death event, which is saved as 1 DEAT Y, then the age is not displayed.

This bug does not seem to affect the statistics reports, for example oldest people still alive.

**Comment by fisharebest** [comment]
When you say "individuals with 1 DEAT",

I guess you mean just this:

```
1 DEAT
```

According to the GEDCOM standard, this does *not* indicate that a death occured.
You need either

* a date
* a place
* a `Y`

So, this would appear to be working correctly.

When an individual is living, we show their age in the header.
When an individual is dead, we show their date of death in the header.

**Comment by miqrogroove** [comment]
I need to check if my software FTB 7 is doing this to all records during export, or only to old records.  I have been seeing this inconsistent behavior with individuals and statistics but perhaps it is all in the import.  I will let you know.

**Comment by miqrogroove** [comment]
I was just able to look at this again.

FTB 7 exports all deceased individuals as "1 DEAT".  The optional "2 DATE" and "2 PLAC" are exported only when specified by the user.

If there is no way to handle this in webtrees then I will have to transform my import files on my own.

**Comment by fisharebest** [comment]
The GEDCOM spec is quite explicit.  From page 21:

> All GEDCOM lines have either a value or a pointer unless the line contains subordinate GEDCOM lines. In other words the presence of a level number and a tag alone should not be used to assert data (i.e. 1 DEAT Y should be used to imply a death known to have happened but date and place are unknown, not 1 DEAT ).

> FTB 7

The latest version of FTB seems to be version 8. (https://www.myheritage.com/family-tree-builder)

Does this version produce better GEDCOM exports?

**Comment by miqrogroove** [comment]
I've been afraid to try it.  Maybe next year I will have some free time to experiment.

**Comment by fisharebest** [comment]
You could use the search/replace option of the batch-update.

Search type regular-expression
Search for `\n1 DEAT\n`
Replace with `\n1 DEAT Y\n`

**Comment by miqrogroove** [comment]
I will make it work on my end.
