### ISSUE TITLE
Two Text Boxes When Editing Any Source

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#2053]
This is a very old bug still found in latest version 1.7.12.

After adding a source to any individual with some text in the text box, any attempt to later edit that text displays two text boxes instead of one.  This is very awkward and confusing.

**Comment by miqrogroove** [comment]
I always see this problem.  All versions and all browsers.

Here is a screencast https://youtu.be/6QjX5xwpVPA

**Comment by fisharebest** [comment]
OK, I believe you.  But I cannot reproduce the problem.

Have you modified your webtrees installation?

**Comment by miqrogroove** [comment]
I have a few very minor changes in PHP files.  Already confirmed same bug with original files.  This is not related to modifications.

**Comment by miqrogroove** [comment]
If I try to save text in both boxes it gives me something like this:

1 SOUR @S1@
2 DATA
3 TEXT Whatnow.
2 PAGE 2
3 TEXT This is another test.2
2 QUAY 3

**Comment by miqrogroove** [comment]
It really looks like webtrees never adds the  DATA tag when importing or creating new citations.  It only shows up after editing an existing source, and then it is  crazy sensitive to the tag order.

**Comment by magicsunday** [comment]
Same here 
- go to an individual 
- Go to tab sources 
- Click „add a source citation“
- enter Source, Details and Text and Save
- Now click on edit of the newly created citation 
- Text Input is duplicate

**Comment by fisharebest** [comment]
OK, this only applies when adding sources directly to individuals - not when adding sources to facts and events.

(I've never done this - IMHO, it makes no sense - but that is a different discussion)
