### ISSUE TITLE
Refactoring Stats.php

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#2059]
Is it okay for you if I will refactor the Stats.php file (splitting it up in separate sub elements, using views, some modern UI, ...) or do you have any other plans with it?

**Comment by fisharebest** [comment]
It certainly needs some tidying up!

I really don't like the functions that return different things (raw data, HTML, charts, lists, etc.) depending on the parameters.

**Comment by fisharebest** [comment]
I don't know if you have started, or where you plan to start, but I am replacing all the webtrees database queries/connections with the [laravel/database](https://github.com/illuminate/database) package.

Documentation at https://laravel.com/docs/5.7/queries

Both the current (`Database::`) and the new (`DB::`) connections will be available while I migrate all the code.

`Stats.php` has lots of dynamic SQL statements, which would be easier to write using this package.

The main reason for this change is that we will be able to support many different databases (sqlite, mysql, postgres, mssql).  In particular, the ability to support sqlite will mean that we will be able to write test scripts for much more of the code.

**Comment by magicsunday** [comment]
Yes, I already started working on it. See branch 2059 in my fork.

**Comment by fisharebest** [comment]
> I also was trying the dB component a while ago.

;-)

I have almost finished converting the migrations.  When they are complete, I'll merge it into master before I continue with the other queries.

**Comment by fisharebest** [comment]
How is the refactoring going?

I have converted all the code (except `Stats.php`) to use `illuminate/database`.

Once your changes are merged in, I'll be able to remove the old `Database` class.

**Comment by fisharebest** [comment]
@magicsunday Any update?

**Comment by magicsunday** [comment]
I'm still on it. I hadn't much time the last week. I hope I will get any progress in the next days. With some minor changes it already works but is not in the final state, which I thought of. Maybe you may take a look at it (https://github.com/magicsunday/webtrees/tree/2059)?

**Comment by fisharebest** [comment]
> Maybe you may take a look at it

If you create a pull-request from your fork, I will be able to add comments, make changes, merge some of the changes, etc.

**Comment by fisharebest** [comment]
Merged.  Thanks!
