### ISSUE TITLE
Relationship to myself is not working in PHP 7.3

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#2063]
I updated from PHP 7.1 to PHP 7.3. In general it seems to work, but the relationship to myself displays a wrong result in PHP 7.3

See the screenshots - this is exactly the same chart, one in PHP 7.1 and the other in PHP 7.3.
Running webtrees 1.7.11

PHP 7.1:
![php71](https://user-images.githubusercontent.com/16715040/50137491-95ec7980-029b-11e9-90b0-2662334d2305.png)

PHP 7.3:
![php73](https://user-images.githubusercontent.com/16715040/50137500-a13fa500-029b-11e9-8f33-d7836bc9d7e0.png)

**Comment by fisharebest** [comment]
This affects 2.0 as well as 1.7

**Comment by fisharebest** [comment]
The `each()` function was deprecated in PHP 7.2 and a workaround was added, using the related functions `current()`, `next()` and `key()`.

However, the workaround seems unreliable in PHP 7.3.

I'm pretty sure this is a bug in PHP, but I can't extract a simple test case to use in a bug report.

So, I've rewritten the code using a different approach.
