### ISSUE TITLE
V2 bug when data directory is relocated

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2066]
Last commit loaded is c7d640a222ebe69e8a63d531427b9957e0efd659 (Fix: #2063, update vendor dependencies).

When the data directory is changed from `data/` in the website preferences and en-GB (and apparently only en-GB!) is the selected language then the individual page (and apparently only the individual page) doesn't render - the `<head></head>` section is empty. When the data directory **is** ` data/` the the page renders correctly although of course no media loads as it's in the wrong place

I have recently had to reload webtrees from scratch so there is no historical baggage, the database is also new. There are no errors in the browser console, and the webtrees and server logs are empty.

**Comment by fisharebest** [comment]
The demo sites, and also my local development server all use en-GB and a non-default data folder.

Are you seeing any error messages anywhere?
Do you have write permission to your data folder?
Are you using symbolic links?

**Comment by ddrury** [comment]
Server is on a windows 10 system

> Are you seeing any error messages anywhere? **NO** (webtrees, server, windows event log)
> Do you have write permission to your data folder? **YES**
> Are you using symbolic links? **NO**

I'm getting lost in the code path with the request/response logic. I've noticed that the call to
http://webtrees-development/index.php?route=individual&xref=I270&ged=drury returns a 403 status. If I disable the "facts and events" tab then the page renders ok.

I notice that I have language cache files in the relocated data folder but also an en-US cache file in the original data folder.

I've raised a couple of new issues that I've found whilst trying to figure out whats going on here

**Comment by fisharebest** [comment]
Is this on a public site where I can see it?

**Comment by ddrury** [comment]
Unfortunately not. BTW how can I turn on the DebugBar output?

**Comment by fisharebest** [comment]
> how can I turn on the DebugBar output?

The code detects whether the "development dependencies" are installed.

To install them, use [composer](https://getcomposer.org/), and run `composer install`

**Comment by ddrury** [comment]
Was using a history file which had the following at the top
```
if (!defined('WT_WEBTREES')) {
	header('HTTP/1.0 403 Forbidden');
	exit;
}
```
Removing that cured things
