### ISSUE TITLE
Incompatible change in I18N - 2.0.0

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#2074]
In 2.0.0, strings to be translated/ translated strings must not contain single literal '%' characters, apparently because `sprintf` is now used directly? Is this intentional - It would require adjusting I18N strings (using '%%' works).

Example:
`I18N::translate('This used to work 100% in webtrees 1.7');`
Doesn't work in 2.0.0.

1.7 had a comment in I18N stating:
> This also allows us to have translated strings that contain "%" characters, which can't be passed to sprintf.

**Comment by fisharebest** [comment]
This is intentional.

If you need to show a percentage, use the `I18N::percent()` function.

This takes care of localising the output.  Latin scripts use `%`.  Other scripts (e.g. arabic) have their own symbols.

**Comment by ric2016** [comment]
Ok, that makes sense.

For future reference, it's actually
`I18N::percentage(float $n, int $precision = 0)`
