### ISSUE TITLE
Style inconsistencies

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2090]
Please see attached image relating to modules on "My Page" - applies to all themes

![style errors](https://user-images.githubusercontent.com/104515/50642250-7a06fa00-0f62-11e9-8e12-6388acafc5c7.jpg)

**Comment by fisharebest** [comment]
Two issues in one....

The icons are centre-aligned with their corresponding text.  How else would you want to align them?

**Comment by ddrury** [comment]
On 1.7 the icons are on a single row (which to my mind is tidier)

**Comment by fisharebest** [comment]
This change was made in response to a bug report that some languages use long words in each of the labels - which don't fit in one row.

**Comment by ddrury** [comment]
Good point
