### ISSUE TITLE
Number of individuals/surnames - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2093]
I try to compare the number of individuals who have surname   "Loon" in the Duck tree.          

1. **Top Surnames block** - I   see 6 Loon individuals - there are only 5, one of them with **2 names**.     
2. **Individuals list**  for surname - I see 5 individuals. Brother Loon is counted **twice. I do not see Lulubelle Loon "Lulu" in the list.** I would like to also see a **counter of the number of individuals.**      
3. Search - I search for Loon and see 8 individuals. 2 have "Loon" in a note and one has "saloon" in a note.     
4. Phonetic search - I search for Loon and see, as expected, 5 individuals. 

We should show the same individual count in 1., 2. and 4.          

I will attach an updated Gedcom file after I can export it from my test system.          

One of my production site users complained about the counters that show different numbers of individuals.

**Comment by melizaa** [comment]
Duck Gedcom file
[duck.ged.zip](https://github.com/fisharebest/webtrees/files/2727708/duck.ged.zip)

**Comment by melizaa** [comment]
I updated the name of Lulubelle Loon "Lulu", and now I see also her in the test Individual list of Loon.

**Comment by fisharebest** [comment]
The "individual" list actually shows "individual names".

In the attached file, individual `I133` has two names (with the same surname) - "Veli /Loon/" and "Brother /Loon/".

So, they are shown twice - once sorted under "B" and once sorted under "V".

(We show both name in both sort positions).

This is working as intended.
