### ISSUE TITLE
Deletion of an individual with no surname and no firstname require an additionnal step - 1.7.12

### ISSUE THREAD

**Issue by liegebe** [fisharebest/webtrees#2096]
Accidentally I created a new guy with no names and deciding to delete it. It did not work as expected. Not sure if it is intentional, so I am mentioning it here.

Deleting an individual with no surname and no first name is resulting into a linked element that stay there (for the individual to be removed, you have to delete it twice, one with the red cross icon and one with Edit > delete). I think it is confusing.

How to reproduce the issue:

- Go to a family with parents.
- Click on 'Add a brother or sister'
- Hit 'save' without writing anything. You have now a new child with no first name and the family surname of its father.
- Look at the top right. You can edit or delete this new child.
- Edit this child again, delete the surname (let it blank).
- Hit 'save'.
- Look at the top right. You can still edit or delete this new child.
- On the top right, click on the red cross icon for deletion.
- The child is not deleted (still listed in the family)
- Look at the top right. You can not edit nor delete this new child anymore because there is no red cross icon.
- However, if you click on this child, you still go to 'Edit', and do 'delete' once again (to delete a link apparently), then it works.
- The message that you see then is similar to (I changed the names): '_The link from “Donald Trump + Hillary Clinton” to “… …” has been deleted.
This individual does not exist or you do not have permission to view it._'

**Comment by fisharebest** [comment]
> On the top right, click on the red cross icon for deletion.
> The child is not deleted (still listed in the family)

This action will just delete the name, not the individual.

You had an individual with an empty/blank name.  e.g. this:

```
0 @I1@@INDI
1 NAME //
```

The "red cross" deletes this name record, to give

```
0 @I1@@INDI
```

> you still go to 'Edit', and do 'delete' once again (to delete a link apparently), then it works.

You could have done this immediately.  You did not need to delete the name first.
