### ISSUE TITLE
Style inconsistencies, part 2

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#2100]
Not the same, but related to: https://github.com/fisharebest/webtrees/issues/2090

![image](https://user-images.githubusercontent.com/5641963/50736227-1b888880-11bb-11e9-93fa-3f02de1e3a13.png)

**Comment by fisharebest** [comment]
It looks like the latest version of bootstrap has changed the mark for `<legend>` elements (again).

I'll take a look
