### ISSUE TITLE
Translation of Gedcom Tag 'MAP'

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#2102]
In `GedcomTag::getLabel`, the Tag 'MAP' is translated as
`/* I18N: gedcom tag MAP */
return I18N::translate('Map');`

This is a bit confusing or at least unclear, as this tag actually contains map coordinates, namely LATI and LONG, under PLAC:

> +1 MAP
> +2 LATI <PLACE_LATITUDE>
> +2 LONG <PLACE_LONGITUDE>

The Gedcom spec inconsistently uses the terms 'map coordinates' and 'measurements', as in:

> MAP {MAP}:=
> Pertains to a representation of measurements usually presented in a graphical form.

Note also that this tag is probably not actually translated anywhere in webtrees itself, as MAP.LATI and MAP.LONG are generally displayed/edited directly (I came across this only when using the tag in a custom module).

Anyway I propose changing the translation to something like
`I18N::translate('Map coordinates');`

**Comment by ric2016** [comment]
In any case, the gedcom tag 'MAP' is not the same thing as the media object type 'map' (which refers to an actual map) translated in `GedcomTag::getFileFormTypeValue`:

`/* I18N: Type of media object */
return I18N::translate('Map');`

and therefore should use a different translation key.

**Comment by fisharebest** [comment]
I have changed this to "Location".

We already use this term in the contol panel for lat/long
