### ISSUE TITLE
Bug in index.php - 2.0.0

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#2115]
The latest change in index.php regarding the initialization of `$tree` doesn't work in cases where there is no tree with gedcom_id 0 in the database (or is there always supposed to be such a tree now?).

This is in line 188:

`$tree = Tree::findByName(Site::getPreference('DEFAULT_GEDCOM')) ?? Tree::getAll()[0] ?? null;`

Solution that works for me (using, as before, `array_values`):

`$tree = Tree::findByName(Site::getPreference('DEFAULT_GEDCOM')) ?? array_values(Tree::getAll())[0] ?? null;`

**Comment by fisharebest** [comment]
Oops.  Thanks.  I hadn't thought this change through.
