### ISSUE TITLE
Module system in 2.x

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#2120]
Following the suggestion in #1950, this ticket collects some high-level aspects to consider for the module system in webtrees 2.x.

* Installation

Are modules to be installed in the same way as before, i.e. simply by dropping a directory in the proper location, or is something else preferable? The current approach is probably fine.

* Themes vs modules
 
Is it a good idea to merge these? The functionality seems rather different usually, what are the benefits of having these two concepts integrated? On the other hand, a module provides all kinds of different functionality already (tab, block, chart ...), so a theme can be seen as just one more of these.

* Protection against errors

Should we attempt to catch exceptions and fatal errors (which is apparently possible in php 7) from modules in order to present a page that is not completely broken in these cases? If this is easily possible, it seems like a good idea, but ultimately the site admin has to handle these cases anyway. Note that we probably cannot keep a module from displaying errors or stack traces within its own output area (such as a tab) anyway.

* Separation of modules

Is it important to enforce a unique internal module name? Should activated duplicated modules work independently? I cannot think of a use case where it makes sense to have the same module more than once, other than for testing purposes. Still, it seems like a good idea to use unique names. The easiest way to achieve this is probably to manage them outside of the module (e.g. use the directory name and pass it to the module as a variable), rather than to have the module implement a `getName` method (in which case we'd have to reject modules with non-unique names).

* Naming

A module should be able to name all of its parts independently. Currently the name of a module's tab cannot be different from the module's (displayed) name itself, this restriction seems unnecessary. It may also make sense to make all names configurable in general (tab name, chart name etc), so that a system with two independent modules which happen to use the same name e.g. for a tab can disambiguate these.

* Hooks

Should we additionally provide some kind of hook system, where modules can provide smaller UI parts or other functionality - E.g. not a complete tab or chart, but some additional output in a facts & events block? I'm currently using this approach to integrate several of my own custom modules. As long as this is just about additional content to display, it can probably be handled already by extending the respective view (once views are used everywhere, and sufficiently broken down).

* Lists

This is the only remaining main hierarchy where it's currently not possible to add entries via custom modules. We should allow this, similar to charts, reports etc, and consequently turn the existing lists into modules.

To be continued - We may have to split this up into multiple tickets though.

**Comment by fisharebest** [comment]
> Are modules to be installed in the same way as before, i.e. simply by dropping a directory in the proper location, or is something else preferable? The current approach is probably fine.

The current installation process has two steps. 

* Copy the module to the modules folder
* Enable it in the control panel.

This second step is not obvious, and causes many problems.

webtrees tries to load all the modules that are enabled in the database, rather than those it finds on disk.  If the module has been deleted from disk, we need to catch the error and disable it in the database.

Perhaps we should simply load all the modules that we find on disk?

Of course, we need a way to disable unwanted core modules.  We already have an access-level system on charts, reports, etc.  We could extend this to all modules.

**Comment by ric2016** [comment]
> If the module has been deleted from disk, we need to catch the error and disable it in the database.
> 
> Perhaps we should simply load all the modules that we find on disk?

Wouldn't we still have to do some cleanup in case a module is deleted? Its preferences shouldn't remain in the database. I don't see how this approach would be significantly simpler overall. But I agree, we could at least enable new modules by default, so that the site administrator wouldn't have to carry out this second step explicitly.

**Comment by fisharebest** [comment]
> I don't see how this approach would be significantly simpler overall

At present, when we detect a new module, we create all the database config for it.  When we create a new tree, we create database config for each module.  There is lots of code to synchronise the modules on disk with the `wt_modules*` tables.

When we install webtrees, the setup script must manually enable all the default modules. Otherwise all modules would be disabled by default.

I've simplied this so that we now use all the modules found on disk, with whatever config exists in the database.  Things such as access levels are checked as late as possible, rather than as early as possible.

The resulting code is much simpler.

> Protection against errors

If we can catch errors during module creation, they are now shown at the top of the page.

> Separation of modules

I have removed the `__DIR__` parameter to the constructor.  The name is now injected into the module.  If we have two copies of the same module, they should both work.  (i.e. two tabs, two menus, etc.).

**Comment by ric2016** [comment]
> I have removed the `__DIR__` parameter to the constructor. The name is now injected into the module. 

The module can still return something else via `getName`. Admittedly that wouldn't make much sense, and we probably shouldn't protect against misbehaving modules everywhere, but wouldn't it be easier for the module implementors not to have to deal with aspects that are managed elsewhere anyway? Aspects such as name, status (enabled/disabled), and maybe access level - these could be handled outside the actual custom module code, e.g. by using a small wrapper class around the actual module class.

 > If we have two copies of the same module, they should both work.

Note (not relevant for the main architecture, and not very important): Existing modules will have to be slightly adjusted for this - currently, multiple facts and events tabs e.g. share their persistent toggle state.

**Comment by fisharebest** [comment]
> The module can still return something else via getName.

I guess we could mark the function with `final` to prevent this.

> Aspects such as name, status (enabled/disabled), and maybe access level - 

At present, the module needs to call `getName()` because the name is needed in URLs.

(Eventually, modules should be able to register their own routes - and maybe even replace routes in the core code.)

> these could be handled outside the actual custom module code

You mean something like: replace `$module->isEnabled()` with `Module::isEnabled($module)`.

**Comment by ric2016** [comment]
> > The module can still return something else via getName.
> 
> I guess we could mark the function with `final` to prevent this.

I don't think that would help - the module could implement `ModuleInterface` without using `AbtractModule`.

> At present, the module needs to call `getName()` because the name is needed in URLs.

Yes, but it could retrieve the name in a different way. Or we could inject it as a variable (which is actually already done) in `Module.php`:

`$module_name = basename(dirname($filename));
$module      = include $filename;`

In the specific included `module.php`, the variable `$module_name` is already available.
(note that at this point, the included code may also modify `$module_name`, which is also problematic)

> > these could be handled outside the actual custom module code
> 
> You mean something like: replace `$module->isEnabled()` with `Module::isEnabled($module)`.

That's one solution, it wouldn't even have to be a static method.

**Comment by magicsunday** [comment]
Are the old modules still working with modules_v3 directory or is modules_v4 now the only supported module-directory?

**Comment by fisharebest** [comment]
modules_v4 is the only supported directory.

**Comment by ric2016** [comment]
> > Protection against errors
> 
> If we can catch errors during module creation, they are now shown at the top of the page.

Do we want to catch fatal errors as well? In that case, we'll have to extend try-catch blocks in various places with `catch (Error $ex)`, mainly the one around

`$module = self::load($filename);`

but also elsewhere, e.g. when rendering the modules.phtml view via View.php (because it calls `ModuleConfigInterface.getConfigLink()`) - basically everywhere a custom module interface method is called.

**Comment by fisharebest** [comment]
Fatal errors cannot be caught in a `catch {}` block.  They cause the script to terminate immediately.

However, we can create a shudown handler - which can check the error status, and may also have access to the stack-trace, etc.

Many hosts are configured with `display_errors = Off`, and fatal errors just leave a blank page.

So, we could display an error message - which would be more useful than a blank page...

> but also elsewhere

All requests run in a `try {} catch {}` block in `index.php`.  This will already catch errors and display them appropriately.  See `app/Exceptions/Handler.php`.

We *could* try to catch errors closer to where they occur - but only if there is something useful we could do.

**Comment by ric2016** [comment]
It's possible to catch fatal errors in php 7, see e.g. [here](https://www.aurigait.com/blog/fatal-error-handling-in-php-7/).

**Comment by ric2016** [comment]
>    Hooks

> Should we additionally provide some kind of hook system, where modules can provide smaller UI parts or other functionality

In fact we already have this mechanism: There are several module providing functionality to other modules e.g. via implementing specific interfaces, e.g. `ModuleAnalyticsInterface`. Should we make the mechanism more explicit by introducing a superinterface `ModuleHookInterface`? This would allow us to show an additional column in the module administration (in addition to Menus, Tabs, etc.), so that the function of the respective modules would be more clear (currently, modules such as Bing™ webmaster tools only have empty entries in all columns, which may be confusing as it isn't immediately obvious what the module actually does). We could even introduce a separate category and then configure access levels for these hooks, as for other components.

**Comment by fisharebest** [comment]
I have added a column to the module list for analytics.

> Should we make the mechanism more explicit by introducing a superinterface `ModuleHookInterface`?

"Hooks" are *how* a module works, not *what* it does.  The current interfaces all define features that the user can see.

The next feature to be converted will be "footers".  We already have several footers:

* hit counter
* contact links
* webtrees link

There are also feature requests for other footers

* copyright message #1745 
* imprints #920
* the widely used "custom javascript" module which simply adds some JS to every page.

**Comment by fisharebest** [comment]
Page footers and historic events are now both implemented as modules.

**Comment by fisharebest** [comment]
Now that code/custom modules are stored in separate locations, perhaps we could move the `/modules_v4/` folder to `/data/modules/`.

Since this is the only folder to which we have read/write access, it would allow webtrees to install/uninstall modules via the control panel.

**Comment by ric2016** [comment]
> Page footers and historic events are now both implemented as modules.

Modularizing as much as possible seems very reasonable. Having additional columns in the module administration for each kind of hook may become a bit unmanageable though. On the other hand, I'd like these columns (and the list in the main view) to be dynamically extensible, so that new hook kinds defined in custom modules (to be implemented in further custom modules) could show up in these places as additional columns and entries.

**Comment by ric2016** [comment]
>     * Naming
> 
> 
> A module should be able to name all of its parts independently. 

I have created a pull request for this.

> It may also make sense to make all names configurable in general (tab name, chart name etc)

This would be problematic with regard to I18N (the adjusted name would have no translations) - I don't think we should support this option.

**Comment by ric2016** [comment]
>     * Lists
> 
> We should [...] turn the existing lists into modules.

Any thoughts about this? I started to implement it and it seems rather straightforward. A few places will have to use dynamic urls to link to the respective list (including an access check, similar to how the relationship chart is linked to). I can finish this and submit a pull request, if there isn't anything else to consider.

**Comment by fisharebest** [comment]
> Any thoughts about this?

Go ahead!

**Comment by fisharebest** [comment]
I am thinking of moving `modules_v4` to `data/modules`.

*.All user-data and customisations will be in one place.  Easier backups.
* webtrees can write to this folder.  We willl be able to install/remove/upgrade modules using the control panel.

**Comment by fisharebest** [comment]
Still needed before 2.0.0-beta

* A way to access resource files (CSS, JS, etc.)
* A way to provide translations
* Anything else???

**Comment by ric2016** [comment]
I don't have anything major that's still missing, and I think we have addressed all original points from my list.

> A way to access resource files (CSS, JS, etc.) 
> A way to provide translations

I use both successfully in my custom modules (migrated to the current master), i.e. I18N via a `language` folder in the custom module, and links to resource files via html code. Is that not how it's supposed to work in the future?

> I am thinking of moving `modules_v4` to `data/modules`.

The data folder currently is compatible between major webtrees versions (I think?). This would change with this approach. Therefore maybe rather use `data/modules_v4`?
(On that occasion, maybe also align the `_v4` with the webtrees major version, i.e. use `data/modules_2` ?) 

One goal here is to install/update modules via the control panel - by uploading a zip file in the browser? Or do you envision some kind of central registry from where to install custom modules?

**Comment by fisharebest** [comment]
> I use both successfully in my custom modules (migrated to the current master), i.e. I18N via a language folder in the custom module,

This loads all the translations for all modules - even ones that are disabled.

We probably need the module to provide the translations via an API call.

> and links to resource files via html code. Is that not how it's supposed to work in the future?

When we add URL rewriting and "pretty URLs", the `/public/` folder will become the web root.

Therefore you won't be able to access `/modules_v4/...` directly via the browser - and we don't want to put the modules folder in `/public/`.

So it will work now, but maybe not in the future.

**Comment by ric2016** [comment]
I see - we could provide those resource files via `index.php?route=module`... then? I'm using this for ajax requests within custom modules already. The problem is that it's not that efficient because of unnecessary initialization (session/middleware/all other modules are loaded etc. - some of this may still be required though?), so we may need a different 'faster' path here after all?

**Comment by fisharebest** [comment]
> The problem is that it's not that efficient because of unnecessary initialization (session/middleware/all other modules are loaded etc.

Performance is one issue.  But we can set HTTP cache headers.

A bigger problem is CSS files that reference images.

```css
.some-class {
    background-image: url(background.gif);
}
```

**Comment by ric2016** [comment]
Well, it's already possible (just tested it, this works if the css file itself is also retrieved via `index.php?route=module`) like this:

```
.some-class {
    background-image: url(index.php?route=module&module=_the_custom_module_&action=BackgroundGif);
}
```

As the internal name of the module ("`_the_custom_module_`") isn't static (the module may be copied to a different folder), we'd have to generate the css file though (instead of using a static file), so that we can use something like

```
.some-class {
    background-image: url(<?= route('module', [
        'module' => $module->name(),
        'action' => 'BackgroundGif'
    ]); =>);
}
```

Not sure that's the best solution.

**Comment by ric2016** [comment]
> > I use both successfully in my custom modules (migrated to the current master), i.e. I18N via a language folder in the custom module,
> 
> This loads all the translations for all modules - even ones that are disabled.

Anyway this already doesn't work anymore (`init` in I18N doesn't check custom modules) - not sure why I thought otherwise. 

Wouldn't the easiest solution be this: Load translations of enabled modules only, via specific folders? Loading them via API calls would strictly also require checking the update times (as for the main files), in order to determine whether to rebuild the cache.

Or prehaps use a different `I18N::translate` within custom modules, which additionally loads files from that specific custom module only? 

In general, should custom modules be able to override main translations?

**Comment by fisharebest** [comment]
Support for custom translations was added in d37db671e2f4b9f27d817b54a435ecf154a67a6b and there is some [example code](https://github.com/fisharebest/webtrees/blob/master/modules_v4/example.disable/module.php).

> whether to rebuild the cache.

I'm not sure if caching is needed for these.  Modules typically have a very small number of translations.  Perhaps 10-50.

> In general, should custom modules be able to override main translations?

Yes.  For example, there are modules for horse pedigrees that replace "father/mother" with "sire/dam" etc.

**Comment by fisharebest** [comment]
I think this is done.  Can we close this issue now?

**Comment by ric2016** [comment]
What about the resource files? Is the solution I described earlier the way to go?

**Comment by fisharebest** [comment]
> I see - we could provide those resource files via index.php?route=module... then?

Yes.  I agree that's our best approach.  I added an example implementation here:

https://github.com/fisharebest/webtrees/blob/master/modules_v4/example-theme.disable/module.php#L73-L148

It needs to be moved to somewhere else.  Probably `ModuleConfigTrait`.

**Comment by ric2016** [comment]
I think we're done here then. Yay!
