### ISSUE TITLE
2.0 - Menu layout changed after update

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2130]
![image](https://user-images.githubusercontent.com/5147603/51545848-131d8800-1e20-11e9-9a22-1f1de3c913d7.png)

**Comment by fisharebest** [comment]
See #2129

Previously, we could just choose the order of menus created by modules (e.g. faq/stories/clippings).

Now, we can enable/disable and change the order of all menus.

Until the UI to re-order menus is updated, you're stuck.

You could run this SQL command to reset the order to a sensible default:

```sql
UPDATE wt_module SET menu_order = NULL;
```

**Comment by makitso** [comment]
Optional menu items use to be on the right side of the menu.  Now, there 

![image](https://user-images.githubusercontent.com/5147603/51548014-a22c9f00-1e24-11e9-9f4a-2cc9b632719d.png)

Now they are intermixed

![image](https://user-images.githubusercontent.com/5147603/51548076-cbe5c600-1e24-11e9-8ba9-a36d5303d71a.png)

**Comment by fisharebest** [comment]
All modules are now optional.

I guess you previously had the stories module in position 3.

So, it has changed from being the 3rd optional module to being the 3rd overall module.

**Comment by makitso** [comment]
?  so before all the default modules were shown in the list first with optional modules at end -- right.
Now the clipping and stores icons are mixed with the default ones.  So, how can I change this?

**Comment by fisharebest** [comment]
You would use the "re-order menus" function - which is temporarily broken.  See #2129.  Give me a day or two.

Didn't the SQL statement work?  That should have reset everything to defaults, and the default position for the stories module is 7.

**Comment by fisharebest** [comment]
The re-order function exists again.  Control panel -> Modules -> Menus
