### ISSUE TITLE
2.0 - Mouse over of primary menu fails to display drop down or alt for colors and clouds themes

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2131]
Not sure when the was removed.  However, now one needs to click on the primary menu icon to see the dropdown, whereas, a mouse over was sufficient to see the sub menu.  For those primary menu icons such  as stories, there is no alt text.

**Comment by fisharebest** [comment]
Replacing "hover menus" with "click menus" was a deliberate change some time ago.

Hover actions cause problems for touch-screens and accessibility software.

I've found a plugin for bootstrap 3 which seems to combine hover and click.

https://cameronspear.com/demos/bootstrap-hover-dropdown/ 

Not sure if it works with bootstrap 4.  I'll need to take a look.

**Comment by fisharebest** [comment]
webtrees now has a module "CSS and JS", which allows you to add these to all your pages.

The module is disabled by default.  Enable it, and add the following content to the `body` option. 

```
<script>
$(".wt-theme-colors .wt-genealogy-menu, .wt-theme-clouds .wt-genealogy-menu").on("mouseenter mouseleave", ".dropdown", function (e) {
    var dropdown = $(e.target).closest(".dropdown");
    var menu = $(".dropdown-menu", dropdown);
    dropdown.addClass("show");
    menu.addClass("show");
    setTimeout(function () {
        dropdown[dropdown.is(":hover") ? "addClass" : "removeClass"]("show");
        menu[dropdown.is(":hover") ? "addClass" : "removeClass"]("show");
    }, 20);
});
</script>
```

Does this give you what you want?

**Comment by makitso** [comment]
Yes, that works much better than css code.
