### ISSUE TITLE
Uncaught TypeError: Return value of callBlock must be of the type string

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#2133]
- Open https://dev.webtrees.net/demo-dev/index.php?route=tree-page&ged=demo
- Login as moderator
- Go to user page (https://dev.webtrees.net/demo-dev/index.php?route=user-page&ged=demo)
- If you add HTML block element to page with option "Keyword examples" the method "callBlock" fails now

Fatal error: Uncaught TypeError: Return value of Fisharebest\Webtrees\Stats::callBlock() must be of the type string, null returned in /home/webtrees/dev.webtrees.net/demo-dev/app/Stats.php:6726 

Stack trace: 

    #0 /home/webtrees/dev.webtrees.net/demo-dev/app/Stats.php(107): Fisharebest\Webtrees\Stats->callBlock() 
    #1 /home/webtrees/dev.webtrees.net/demo-dev/app/Stats.php(158): Fisharebest\Webtrees\Stats->getAllTagsTable() 
    #2 /home/webtrees/dev.webtrees.net/demo-dev/app/Stats.php(175): Fisharebest\Webtrees\Stats->getTags('#getAllTagsTabl...') 
    #3 /home/webtrees/dev.webtrees.net/demo-dev/app/Module/HtmlBlockModule.php(84): Fisharebest\Webtrees\Stats->embedTags('#getAllTagsTabl...') 
    #4 /home/webtrees/dev.webtrees.net/demo-dev/resources/views/user-page-block.phtml(5): Fisharebest\Webtrees\Module\HtmlBlockModule->getBlock(Object(Fisharebest\Webtrees\Tree), 84, 'user') 
    #5 /home/webtrees/dev.webtrees.net/demo-dev/app/View.php(140): include('/home/webtrees/...') 
    #6 /home/webtrees/dev.webtrees.net/demo-dev/app/View.php(184): Fisharebest in /home/webtrees/dev.webtrees.net/demo-dev/app/Stats.php on line 6726

**Comment by fisharebest** [comment]
This is because `Stats.php` is behind the rest of the code.

Need to fix #2059 first.

**Comment by fisharebest** [comment]
fixed in c50ff97d2
