### ISSUE TITLE
Place changes aren't handled recursively

### ISSUE THREAD

**Issue by Bonbadil** [fisharebest/webtrees#2134]
Hello,

**Step to reproduce:**
I add a new event, with a wrong place, for example "Mayfair, London" in place of "Mayfair, London, England".
![image](https://user-images.githubusercontent.com/833234/51766584-36c02700-20db-11e9-95f0-f749fb0b794b.png)
I now find a new "London" country in the place hierarchy, with only "Mayfair" in it.
I then correct my error, by changing to "Mayfair, London, England".

**What I get:**
The "Mayfair" in "World - London" place is deleted, but the "World - London" place still exist, with nothing in it and no event associated.
![image](https://user-images.githubusercontent.com/833234/51766804-ca91f300-20db-11e9-867d-640ca008a0e9.png)

**What I think should be:**
The "World - London - Mayfair" and the "World - London" places are both deleted.

**Comment by fisharebest** [comment]
Possibly related to #1306

**Comment by Bonbadil** [comment]
I don't know, I never had the #1306 problem. It seems to be about places not always added.
This one is about the "parent places" (ie. all the place upper in the place hierarchy) never deleted when a place is deleted and that the parents are no used any more. And this one is easily reproducible on the online demo. :-)
