### ISSUE TITLE
Burial returns an empty report for any place - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2137]
I fill Windsor in the burial place and see no individuals in the report. King Edward VII is buried in Windsor, Berkshire, England.

**Comment by fisharebest** [comment]
Interesting.  It works OK on my dev server, but not on demo server.

Let me check the demo server is up to date...

**Comment by fisharebest** [comment]
Interesting.  It just seems to be a problem on the demo site.

I imported the GEDCOM file into another site on the same server, and it runs OK.

Debug shows that it is running the expected query:

```
select distinct `i_id` as `xref`, `i_gedcom` as `gedcom` from `wtsvn_individuals`
 inner join `wtsvn_places` as `wtsvn_filter1a` on `p_file` = `i_file`
 inner join `wtsvn_placelinks` as `wtsvn_filter1b` on `wtsvn_filter1b`.`pl_file` = `wtsvn_filter1a`.`p_file` and `wtsvn_filter1b`.`pl_p_id` = `wtsvn_filter1a`.`p_id`
 where `i_file` = ?
 and `wtsvn_filter1a`.`p_place` LIKE ?
 and `i_gedcom` REGEXP ?
```

with these parameters

```
array(3) {
  [0]=>  int(1)
  [1]=>  string(9) "%windsor%"
  [2]=>  string(8) "\n1 BURI"
```

The query gives the expected results when run directly in MySQL, but gives zero rows when run from webtrees...

**Comment by fisharebest** [comment]
It's working fine on my local machine and on my live site.
Just not the demo site.  I'm not sure why...

> How can I activate on my test system the maps?

Control panel - Map provider

**Comment by melizaa** [comment]
I see now the maps in my test Control Panel -> Map ->  Geographic data and in the Place hierarchy.

I do not yet see for instance individual places or the Burials report data.

**Comment by fisharebest** [comment]
I've rewritten this to use `LIKE` instead of `REGEXP` (to support other databases), and this fixes the problem.
