### ISSUE TITLE
Occupations report is empty - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2140]
I added to i1 an occupation and tried to see it in the Occupations report.
I see an empty report.

**Comment by fisharebest** [comment]
I've rewritten this to use `LIKE` instead of `REGEXP` (to support other databases), and this fixes the problem.

**Comment by melizaa** [comment]
I get still an empty report in demo-dev for i1 and on my site.

**Comment by fisharebest** [comment]
> I get still an empty report in demo-dev for i1

I add an occupation to I1 - and it appears in the report...

https://dev.webtrees.net/demo-dev/index.php?route=report-run&ged=demo&report=occupation_report&varnames%5B%5D=occupation&vars%5Boccupation%5D=&varnames%5B%5D=sortby&vars%5Bsortby%5D=NAME&varnames%5B%5D=pageSize&vars%5BpageSize%5D=A4&output=HTML

**Comment by fisharebest** [comment]
I just logged in as moderator, and then ran the report.  Worked OK...

**Comment by melizaa** [comment]
This url does not show i1. It is a little different from your url. Why? I
used chrome or avaste.

https://dev.webtrees.net/demo-dev/index.php?route=report-run&ged=demo&report=occupation_report&varnames%5B%5D=occupation&vars%5Boccupation%5D=Queen&varnames%5B%5D=sortby&vars%5Bsortby%5D=NAME&varnames%5B%5D=pageSize&vars%5BpageSize%5D=A4&output=HTML

**Comment by melizaa** [comment]
I see i1, if I do not fill any occupation.
I do not see her if I fill i2's occupation in the input form.
