### ISSUE TITLE
Ä, Ö and Å in the Finnish individual- and family -lists - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2153]
In the Finnish language lists I see surnames starting by Ä and Å under the top letter A and surnames starting by Ö under the top letter O.

On the Swedish, Norwegian and Danish listst these names are printed as expect under the special letters after letter Z.

This is also how we should see the Finnish lists.

![2019-01-29_14-00-02](https://user-images.githubusercontent.com/5202996/51906994-3de28000-23ce-11e9-901b-0003c3bef843.jpg)

**Comment by melizaa** [comment]
The name Aalto has to print under A as in Swedish, not under Å as in Danish and Norwegian.

**Comment by melizaa** [comment]
I see now on the Finnish lists the letters Å, Ä and Ö.

On the Finnish page I see all the names that start by A, Å or Ä (or Æ) under the the 3 top letters A, Å and Ä and the names that start by O or Ö (or Ø) under both letters O and Ö. I should see each surname only under one top letter in the same way that I see on the Swedish pages.

**Comment by fisharebest** [comment]
The rules for swedish and finnish got lost when this code was rewritten.

**Comment by melizaa** [comment]
I see still on the Finnish page O and Ö names under both top letters and A, Ä/, Å and Æ names under top letters A, Å and Ä.

**Comment by fisharebest** [comment]
I found the problem.  Finnish should use the Swedish collation.

The problem is in a third-party library.  I'll get this updated.
