### ISSUE TITLE
Missing top letters in the individual- and family-list - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2154]
I have defined site individuals with Latin names. Many individuals have also Hebrew names and some have Cyrillic or Thai names.

In wt pre 2.0 I see on the on the Latin lists the Latin top letters and the letters in the other languages, if there are surnames that start with that letter. On the Hebrew lists I see the Hebrew top letters and the letters in the other languages, if there are surnames that start with that letter.
![2019-01-29_14-14-25](https://user-images.githubusercontent.com/5202996/51907829-afbbc900-23d0-11e9-8bd6-fc1adad61c8f.jpg)
![2019-01-29_14-15-15](https://user-images.githubusercontent.com/5202996/51907836-b4807d00-23d0-11e9-96da-6c57c47b9fd1.jpg)

In 2.0.0 I see only Latin letters on the Latin pages and only Hebrew letters on Hebrew pages (and Greek letters on the Greek list, etc.)
![2019-01-29_14-12-07](https://user-images.githubusercontent.com/5202996/51907859-c530f300-23d0-11e9-99a5-48c150c771a6.jpg)
![2019-01-29_14-13-02](https://user-images.githubusercontent.com/5202996/51907864-ca8e3d80-23d0-11e9-9911-cdd0bcc8b33c.jpg)

This means that the users and admins will have to select the All names option in order to see names that are not in the page language. This is unacceptable.

**Comment by fisharebest** [comment]
PHP counts things from zero.
MySQL counts things from one.

The initial character was being ignored...
