### ISSUE TITLE
Add Individual Sources from Clipboard in Sources tab - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2159]
I have requested this before.
The option does not yet exist.

Now I have to look for each individual to whom I need to add the source in the sources tab if the source exists already and then go to the facts and events tab to add the source.

See 
#1224

**Comment by fisharebest** [comment]
This is part of a larger problem:

We have modules that are responsible for certain GEDCOM facts.

* "Sources" tab for `SOUR`
* "Notes" tab for `NOTE`
* "Media" tab for `OBJE`
* Extra information sidebar for `RESN`, `AFN`, `CHAN`, `_UID`, etc.

When these modules are disabled, the "Facts and events" tab should display them.
When these modules are enabled, the "Facts and events" tab should not display them.

We have special code for the "Extra information" sidebar, but not for other modules.

We need to make this logic more general purpose.  Each module should identify the facts for which it is responsible.

The "paste-from-clipboard" functions would then be able to know which facts to list for which module.

**Comment by melizaa** [comment]
Sources work now. Thanks! This is what I had in mind.

I can now not copy to the clipboard and add to individuals or families
notes, shared notes or media.

**Comment by melizaa** [comment]
Should I create new issues for clipboard and individual media, notes and shared notes?

**Comment by fisharebest** [comment]
> Should I create new issues for clipboard and individual media, notes and shared notes?

Please do.
