### ISSUE TITLE
Bottom contact text wrong in demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2161]
I see "For technical support and information contact ' Greg Roach ."

**Comment by fisharebest** [comment]
The apostrophe and extra spaces come from the template that is used by `->copntactLInk()` to create the link.

**Comment by makitso** [comment]
What about the "." After the %s ?

**Comment by fisharebest** [comment]
> What about the "." After the %s ?

It is a sentence.  It has a period at the end.  I don't understand the point you are making?

The errors that I see are the apostrophe before the name and the spaces around it.

**Comment by makitso** [comment]
Sorry, you are correct - my bad

**Comment by melizaa** [comment]
While we touch this, could we add dir="auto" around the %s, for ltr real names with trailing special characters on rtl pages. We should ensure that the names will print correctly in the site message pages and in the messages.
