### ISSUE TITLE
Not picking up HTTPS behind reverse proxy

### ISSUE THREAD

**Issue by bygri** [fisharebest/webtrees#2166]
I'm running Webtrees 1.7.11 on Apache/PHP 7.2, behind an nginx reverse proxy which handles HTTPS.

When forwarding, nginx sets the header `X-Forwarded-Proto: https` which arrives in PHP as `$_SERVER['HTTP_X_FORWARDED_PROTO']` but Webtrees [(via Symfony?)](https://github.com/fisharebest/webtrees/blob/c6bb1f942429fae64a0fcbe4a879f5ccb6a8127d/includes/session.php#L169) is unaware, and produces http:// redirect links, causing an endless redirect loop.

I haven't touched PHP since PHP3, but is this something Webtrees can easily solve?

**Comment by fisharebest** [comment]
The Symfony HTTP-Foundation classes ignore the `X-Forwarded-` headers unless they come from a trusted proxy server, as these can easily be spoofed by a malicious client.

Therefore you would need to provide a list of "trusted" proxy servers to Symfony.

As present, there is no config option to do this.  It's tricky with the current architecture, as we store config in the database, but would need it before we can establish a database connection.

I'm looking at a `dotenv` based system for server configuration issues, but it is a long way off.

Meanwhile, are you able to set the header `HTTPS: On`?

This isn't subject to the trusted-proxy checks, and is the one Apache would set if it were handling SSL itself.

**Comment by bygri** [comment]
This makes perfect sense, thank you.

Yes, I can set `proxy_set_header HTTPS On;`, but it doesn't appear to make it into Symfony. I notice that on the Server Information page, under Apache Environment, it's coming through as the variable `HTTP_HTTPS`.

**Comment by fisharebest** [comment]
There's a PHP.INI option [`auto_prepend_file`](http://php.net/manual/en/ini.core.php#ini.auto-prepend-file).  You could use it to execute the following script....

```php
$_SERVER['HTTPS'] = 'On';
```

A bit of a dirty hack, but might help you temporarily...

**Comment by fisharebest** [comment]
...or write a script that makes a call to `Request::setTrustedProxies(['12.34.56.78']);`

**Comment by bygri** [comment]
`auto_prepend_file` worked just fine. Thanks so much for your help.
