### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1055 'wt_individuals.i_rin' isn't in GROUP BY 

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#2171]
Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1055 'webtrees-2.0.wt_individuals.i_rin' isn't in GROUP BY 

(SQL: select `wt_individuals`.*, MAX(wt_death.d_julianday2 - wt_birth.d_julianday1) AS days from `wt_individuals` inner join `wt_dates` as `wt_birth` on `wt_birth`.`d_file` = `i_file` and `wt_birth`.`d_gid` = `i_id` inner join `wt_dates` as `wt_death` on `wt_death`.`d_file` = `i_file` and `wt_death`.`d_gid` = `i_id` where `i_file` = 5 and `wt_birth`.`d_fact` = BIRT and `wt_death`.`d_fact` = DEAT and `wt_death`.`d_julianday1` >= `wt_birth`.`d_julianday2` and `wt_birth`.`d_julianday2` <> 0 and `i_sex` = M group by `i_id`, `i_file` order by `days` desc limit 10) 

in file /vendor/illuminate/database/Connection.php on line 664 

Stack trace: 
1. Illuminate\Database\QueryException->() /vendor/illuminate/database/Connection.php:664 
2. Fisharebest\Webtrees\Module\StatisticsChartModule->getIndividualsAction() [internal]:0
3. Fisharebest\Webtrees\Http\Controllers\ModuleController->action() [internal]:0 
4. Doctrine\DBAL\Driver\PDOException->() /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63 
5. Fisharebest\Webtrees\Module\StatisticsChartModule->getIndividualsAction() [internal]:0 
6. Fisharebest\Webtrees\Http\Controllers\ModuleController->action() [internal]:0 
7. PDOException->() /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61 
8. PDO->prepare() /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61 
9. Doctrine\DBAL\Driver\PDOConnection->prepare() /vendor/illuminate/database/Connection.php:326 
10. Illuminate\Database\Connection->Illuminate\Database\{closure}() /vendor/illuminate/database/Connection.php:657 
11. Illuminate\Database\Connection->runQueryCallback() /vendor/illuminate/database/Connection.php:624 
12. Illuminate\Database\Connection->run() /vendor/illuminate/database/Connection.php:333 
13. Illuminate\Database\Connection->select() /vendor/illuminate/database/Query/Builder.php:2095 
14. Illuminate\Database\Query\Builder->runSelect() /vendor/illuminate/database/Query/Builder.php:2083 
15. Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}() /vendor/illuminate/database/Query/Builder.php:2569 
16. Illuminate\Database\Query\Builder->onceWithColumns() /vendor/illuminate/database/Query/Builder.php:2084 
17. Illuminate\Database\Query\Builder->get() /app/Statistics/Repository/IndividualRepository.php:962 
18. Fisharebest\Webtrees\Statistics\Repository\IndividualRepository->topTenOldestQuery() /app/Statistics/Repository/IndividualRepository.php:1084 
19. Fisharebest\Webtrees\Statistics\Repository\IndividualRepository->topTenOldestMaleList() /app/Statistics.php:1221 
20. Fisharebest\Webtrees\Statistics->topTenOldestMaleList() /resources/views/statistics/individuals/greatest-age.phtml:20 
21. include() /app/View.php:141 
22. Fisharebest\Webtrees\View->render() /app/View.php:185 
23. Fisharebest\Webtrees\View->make() /app/Helpers/functions.php:88 
24. view() /resources/views/modules/statistics-chart/individuals.phtml:11 
25. include() /app/View.php:141 
26. Fisharebest\Webtrees\View->render() /app/View.php:185 
27. Fisharebest\Webtrees\View->make() /app/Helpers/functions.php:88 
28. view() /app/Module/StatisticsChartModule.php:170 
29. Fisharebest\Webtrees\Module\StatisticsChartModule->getIndividualsAction() [internal]:0 
30. ReflectionMethod->invoke() /app/Application.php:44 
31. Fisharebest\Webtrees\Application->dispatch() /app/Http/Controllers/ModuleController.php:82 
32. Fisharebest\Webtrees\Http\Controllers\ModuleController->action() [internal]:0 
33. ReflectionMethod->invoke() /app/Application.php:44 
34. Fisharebest\Webtrees\Application->dispatch() /index.php:291 
35. {closure}() /app/Http/Middleware/CheckForMaintenanceMode.php:48 
36. Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->handle() /index.php:288 
37. {closure}() /app/Http/Middleware/DebugBarData.php:39 
38. Fisharebest\Webtrees\Http\Middleware\DebugBarData->handle() /index.php:288 
39. {closure}() /app/Http/Middleware/Housekeeping.php:74 
40. Fisharebest\Webtrees\Http\Middleware\Housekeeping->handle() /index.php:288 
41. {closure}() /index.php:294

**Comment by fisharebest** [comment]
What database/version are you using?

What `SQL_MODE` are you using?

I can guess what change to make, but I can't reproduce the error, as the query runs OK for me...

**Comment by magicsunday** [comment]
I only updated my master to the latest version.

Dont know if this is right:

:~# mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 377
Server version: 10.1.37-MariaDB-0+deb9u1 Debian 9.6

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> SELECT @@GLOBAL.sql_mode;
+--------------------------------------------+
| @@GLOBAL.sql_mode                          |
+--------------------------------------------+
| NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+--------------------------------------------+
1 row in set (0.00 sec)

MariaDB [(none)]> SELECT @@SESSION.sql_mode;
+--------------------------------------------+
| @@SESSION.sql_mode                         |
+--------------------------------------------+
| NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+--------------------------------------------+
1 row in set (0.00 sec)

**Comment by fisharebest** [comment]
Does your `wt_individuals` table have the primary key on `i_id` and `i_file` (in that order)?

(There should also be a unique index on the columns in the other order...)

**Comment by fisharebest** [comment]
> The query in "topTenOldestQuery" now requests all columns of the table "individuals". Before (44cdc21#diff-2f01feee91f535005801261013f67b12R957) not.

This is a recent change.  Are you saying that this change
* fixed the problem
* created the problem

**Comment by magicsunday** [comment]
The change created the problem. Before was everything fine.

**Comment by fisharebest** [comment]
The database connection was specifying `SQL_MODE = ONLY_FULL_GROUP_BY`.

The effect depends on whether your underlying database supports the SQL99 standard (implicit group by on functionally dependent columns), or the earlier SQL92 standard.

I guess that my version of MySQL (8.0) supports the 99 standard, and your version of MariaDB (10.1.37) does not.

I can remove this option from the SQL_MODE.
