### ISSUE TITLE
2.0 - Change user email address to existing email address throws error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2174]
Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'makitso@gmail.com' for key 'ux2' (SQL: update `wt_user` set `email` = makitso@gmail.com where `user_id` = 15) in file /vendor/illuminate/database/Connection.php on line 664
Stack trace:
  1. Illuminate\Database\QueryException->() /vendor/illuminate/database/Connection.php:664
  2. Fisharebest\Webtrees\Http\Controllers\AdminUsersController->update() [internal]:0
  3. Doctrine\DBAL\Driver\PDOException->() /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119
  4. Fisharebest\Webtrees\Http\Controllers\AdminUsersController->update() [internal]:0
  5. PDOException->() /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
  6. PDOStatement->execute() /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
  7. Doctrine\DBAL\Driver\PDOStatement->execute() /vendor/illuminate/database/Connection.php:483
  8. Illuminate\Database\Connection->Illuminate\Database\{closure}() /vendor/illuminate/database/Connection.php:657
  9. Illuminate\Database\Connection->runQueryCallback() /vendor/illuminate/database/Connection.php:624
 10. Illuminate\Database\Connection->run() /vendor/illuminate/database/Connection.php:490
 11. Illuminate\Database\Connection->affectingStatement() /vendor/illuminate/database/Connection.php:423
 12. Illuminate\Database\Connection->update() /vendor/illuminate/database/Query/Builder.php:2659
 13. Illuminate\Database\Query\Builder->update() /app/User.php:524
 14. Fisharebest\Webtrees\User->setEmail() /app/Http/Controllers/AdminUsersController.php:390
 15. Fisharebest\Webtrees\Http\Controllers\AdminUsersController->update() [internal]:0
 16. ReflectionMethod->invoke() /app/Application.php:44
 17. Fisharebest\Webtrees\Application->dispatch() /index.php:282
 18. {closure}() /app/Http/Middleware/CheckForMaintenanceMode.php:48
 19. Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->handle() /index.php:279
 20. {closure}() /app/Http/Middleware/DebugBarData.php:40
 21. Fisharebest\Webtrees\Http\Middleware\DebugBarData->handle() /index.php:279
 22. {closure}() /app/Http/Middleware/UseTransaction.php:43
 23. Fisharebest\Webtrees\Http\Middleware\UseTransaction->handle() /index.php:279
 24. {closure}() /app/Http/Middleware/CheckCsrf.php:48
 25. Fisharebest\Webtrees\Http\Middleware\CheckCsrf->handle() /index.php:279
 26. {closure}() /index.php:285

**Comment by fisharebest** [comment]
I can reproduce this.  Re-opening
