### ISSUE TITLE
Individual Places map wrong - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2181]
The individual Places markers are shown in wrong places on the map. See i1 and others.

I see for i1
![2019-02-05_13-58-24](https://user-images.githubusercontent.com/5202996/52272058-35e68b00-294e-11e9-8aec-73a6c4b3e61a.jpg)

and for i9
![2019-02-05_14-00-58](https://user-images.githubusercontent.com/5202996/52272164-92e24100-294e-11e9-8bbc-bc32c094931e.jpg)

**Comment by melizaa** [comment]
Same issue in the rtl Place hierarchy list map in my test system.

**Comment by HRN-webtrees** [comment]
In Places tab, it looks like lat, long has been inversed (long,lat).
In other maps the places are correctly displayed

**Comment by fisharebest** [comment]
> In Places tab, it looks like lat, long has been inversed (long,lat).

You're right.  Thanks.

One half of my brain uses land maps (long/lat) and the other half uses nautical maps (lat/long).  Sometime I get confused...
