### ISSUE TITLE
2.0 Color theme not honoring palette

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2194]
After moving the themes to public the color theme is no longer honoring the palette for the dir wt-header-wrapper.

![image](https://user-images.githubusercontent.com/5147603/52483010-06af6400-2b70-11e9-86eb-3618c681b6e2.png)

**Comment by fisharebest** [comment]
I saw that happen before, and already fixed it once ;-)

Since colors extends clouds, it needs to reset the background.

I'll take another look...

**Comment by makitso** [comment]
Its not the only problem, lots of palette colors being ignored.

**Comment by makitso** [comment]
Even though the link to the palette style sheet appears after the color.min.css, the palette style is being superseded the color.min.css style.

**Comment by fisharebest** [comment]
> Its not the only problem, lots of palette colors being ignored.

The CSS-RTL plugin was making some of the rules more specific (`[dir=rtl] .foo` instead of `.foo`), and so the palette rules were no longer overriding the code rules.

The fix is to run palette CSS files through the same tools.
