### ISSUE TITLE
Relatinship runs and runs - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2199]
Relatinship between Queen Elisabeth II and her father King   George VI runs and runs

**Comment by magicsunday** [comment]
ErrorException: Undefined index: image-vline in file /app/Module/WebtreesTheme.php on line 80 

Stack trace: 
1. ErrorException->() /app/Module/WebtreesTheme.php:80 
2. Fisharebest\Webtrees\Webtrees->Fisharebest\Webtrees\{closure}() /app/Module/WebtreesTheme.php:80 
3. Fisharebest\Webtrees\Module\WebtreesTheme->parameter() /app/Module/RelationshipsChartModule.php:333 
4. Fisharebest\Webtrees\Module\RelationshipsChartModule->chart() /app/Module/RelationshipsChartModule.php:231 
5. Fisharebest\Webtrees\Module\RelationshipsChartModule->getChartAction() [internal]:0 
6. ReflectionMethod->invoke() /app/Application.php:44 
7. Fisharebest\Webtrees\Application->dispatch() /app/Http/Controllers/ModuleController.php:82 
8. Fisharebest\Webtrees\Http\Controllers\ModuleController->action() [internal]:0 
9. ReflectionMethod->invoke() /app/Application.php:44 
10. Fisharebest\Webtrees\Application->dispatch() /index.php:285 
11. {closure}() /app/Http/Middleware/CheckForMaintenanceMode.php:48 
12. Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->handle() /index.php:282 
13. {closure}() /app/Http/Middleware/DebugBarData.php:39 
14. Fisharebest\Webtrees\Http\Middleware\DebugBarData->handle() /index.php:282 
15. {closure}() /app/Http/Middleware/Housekeeping.php:74 
16. Fisharebest\Webtrees\Http\Middleware\Housekeeping->handle() /index.php:282 
17. {closure}() /index.php:288
