### ISSUE TITLE
Greek mythology gedcom

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#2205]
Where did you get greek myth gedcom from? 

There seems to be some more problems on the statistics page with it.

**Comment by fisharebest** [comment]
I created it from wikipedia.  Started with Zeus and added all the relatives I could find.

It's a useful test, as gods tend to marry their sons/daughters, have thousands of children, etc.

**Comment by magicsunday** [comment]
Could you please add the gedcom? I only found this one right now http://genealogyoflife.com/tng/gedcom/GreekGods.ged (on the page http://famousfamilytrees.blogspot.com/2008/07/links-to-religious-system-ged-file.html) and dont have the time to create my own version.

**Comment by magicsunday** [comment]
The one http://genealogyoflife.com/tng/gedcom/GreekGods.ged seems ok. Same stats keeps empty.

**Comment by fisharebest** [comment]
> The one http://genealogyoflife.com/tng/gedcom/GreekGods.ged seems ok.

I guess you now have something suitable...
