### ISSUE TITLE
2.0 - Charts Statistics spin icon

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2206]
[Tue Feb 12 06:48:54.631886 2019] [php7:error] [pid 12613] [client ::1:46352] PHP Fatal error:  Uncaught Error: Class 'NumberFormatter' not found in /home/rob/www/app/Statistics/Helper/Century.php:41\nStack trace:\n#0 /home/rob/www/app/Statistics/Google/ChartBirth.php(92): Fisharebest\\Webtrees\\Statistics\\Helper\\Century->centuryName(16)\n#1 /home/rob/www/app/Statistics/Repository/IndividualRepository.php(687): Fisharebest\\Webtrees\\Statistics\\Google\\ChartBirth->chartBirth('ffffff', '95b8e0')\n#2 /home/rob/www/app/Statistics.php(1002): Fisharebest\\Webtrees\\Statistics\\Repository\\IndividualRepository->statsBirth(NULL, NULL)\n#3 /home/rob/www/resources/views/statistics/individuals/total-events.phtml(32): Fisharebest\\Webtrees\\Statistics->statsBirth()\n#4 /home/rob/www/app/View.php(144): include('/home/rob/www/r...')\n#5 /home/rob/www/app/View.php(188): Fisharebest\\Webtrees\\View->render()\n#6 /home/rob/www/app/Helpers/functions.php(108): Fisharebest\\Webtrees\\View::make('statistics/indi...', Array)\n#7 /home/rob/www/resources/views/modules/statistics-chart/individuals.phtml(7): view('statistics/indi...', Array)\n#8 /home/ in /home/rob/www/app/Statistics/Helper/Century.php on line 41, referer: http://localhost/index.php?route=module&module=statistics_chart&action=Chart&ged=Johannsen

**Comment by fisharebest** [comment]
The `NumberFormatter` class is part of the `PHP intl` extension.

We probably should not be using it.

We did have our own version - which appears to have gotten lost during the recent refactoring...
