### ISSUE TITLE
2.0 - Footer center problem with colors theme

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2207]
![image](https://user-images.githubusercontent.com/5147603/52640692-476eec00-2e94-11e9-8c3e-37daf99bb529.png)

**Comment by fisharebest** [comment]
We're using `text-center` to center the footers - and this isn't text...

**Comment by makitso** [comment]
.wt-footer-powered-by {
	display: block;
	margin: 0 auto;
}

**Comment by fisharebest** [comment]
Interestly, it works for clouds (and other themes) so should be the same...

**Comment by makitso** [comment]
only colors has its own image.

**Comment by fisharebest** [comment]
I've got it.  The custom image is replacing the parent div, not the text.
