### ISSUE TITLE
2.0 - Style problem on individual page

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2208]
![image](https://user-images.githubusercontent.com/5147603/52640802-9583ef80-2e94-11e9-98d8-b72f39c66425.png)

**Comment by fisharebest** [comment]
Many of the charts have a problem with the position of this icon.

I need to replace this "hover" menu with a the bootstrap menus, so will look at this then.

**Comment by fisharebest** [comment]
The chart-boxes have been replaced, and this icon is now back where it should be.
