### ISSUE TITLE
2.0 On this day and Upcoming events

### ISSUE THREAD

**Issue by HRN-webtrees** [fisharebest/webtrees#2209]
Not sure if this is same as https://github.com/fisharebest/webtrees/issues/1250

Blocks On this day and Upcoming events are fine when presented as table.
If presented as list, I get following error:

Uncaught TypeError: intdiv() expects parameter 1 to be integer, float given in
C:\xampp\htdocs\webtrees\app\I18N.php:764 Stack trace: #0 
C:\xampp\htdocs\webtrees\app\I18N.php(764): intdiv(2270592000, 31536000) #1 
C:\xampp\htdocs\webtrees\resources\views\modules\upcoming_events\list.phtml(14): 
Fisharebest\Webtrees\I18N::timeAgo(2270592000) #2 
C:\xampp\htdocs\webtrees\app\View.php(144): 
include('C:\\xampp\\htdocs...') #3 C:\xampp\htdocs\webtrees\app\View.php(188): 
Fisharebest\Webtrees\View->render() #4 C:\xampp\htdocs\webtrees\app\Helpers\functions.php(108): 
Fisharebest\Webtrees\View::make('modules/upcomin...', Array) #5 
C:\xampp\htdocs\webtrees\app\Module\UpcomingAnniversariesModule.php(157): 
view('modules/upcomin...', Array) #6 
C:\xampp\htdocs\webtrees\app\Http\Controllers\HomePageController.php(320): 
Fisharebest\Webtrees\Module\UpcomingAnniversariesModule-
>getBlock(Object(Fisharebest\Webtrees\Tree), 356, 'gedcom') #7 [internal function]: 
Fisharebest\Webtrees\Http\Controllers\HomePageController->treePageBlock in 
C:\xampp\htdocs\webtrees\app\I18N.php on line 764

**Comment by fisharebest** [comment]
Which version of webtrees is this?

**Comment by HRN-webtrees** [comment]
2.0 dev downloaded yesterday.
php 7.2.12

**Comment by fisharebest** [comment]
> Uncaught TypeError: intdiv() expects parameter 1 to be integer, float given

This value is computed by subtracting two integers, so I'm not sure how it can be a float.

Is there any other information you can give that might help me reproduce this?

**Comment by HRN-webtrees** [comment]
Just downloaded latest dev, and tested again.
Added both blocks to index page, and they both work fine initally.
When changing Presentation style from table to list I get the same error for the Upcoming events.
On this day now works fine with both settings!

**Comment by HRN-webtrees** [comment]
I'm not able to reproduce this on demo site

**Comment by fisharebest** [comment]
Do you have any local modifications to your code?

**Comment by HRN-webtrees** [comment]
No modifications.

**Comment by HRN-webtrees** [comment]
On this day also throw the error message when "Show only events of living individuals" is set to "no"
Works fine when set to "yes"

**Comment by fisharebest** [comment]
It sounds like you have one (or more) particular records that is triggering this.

Do you have any unusual dates.  e.g. dates `B.C.`, etc.

**Comment by fisharebest** [comment]
The error is in line 14 of `resources\views\modules\upcoming_events\list.phtml`, which is this

`<?= ' (' . I18N::timeAgo($fact->anniv * 365 * 24 * 60 * 60) . ')'; ?>`

Temporarily replace this line with

`<?php var_dump($fact->anniv) ?>`

Your upcoming event list should now contain lots of things like `int(1234)`, and presumably one or more like `float(1234.0)`.

Anything suspicious with the `float` ones?

**Comment by HRN-webtrees** [comment]
No unusual dates

Here is the list:

Nora Alvilde Adolfsen  
Død — 20. februar 1993 int(26) — Andenes, Andøy, Nordland, Norge
Anne Andersdotter  
Død — 14. februar 1839 int(180) — Espenakken, Volda, Møre og Romsdal, Norge
Kanutte Marte Andersdotter  
Fødsel — 17. februar 1826 int(193) — Eidset, Volda, Møre og Romsdal, Norge
Mette Andersdotter  
Død — før 14. februar 1724 int(295) — Lianes, Ørsta, Møre og Romsdal, Norge
Arne Andersen  
Død — 19. februar 1818 int(201) — Runde, Herøy, Møre og Romsdal, Norge
Alvilde Helene Kristine Andreasdatter  
Fødsel — 17. februar 1887 int(132) — Lovika, Dverberg, Nordland, Norge
Knut Aslakson  
Fødsel — 17. februar 1848 int(171) — Rød, Nesset, Møre og Romsdal, Norge
Ole Aslakson  
Fødsel — 14. februar 1851 int(168) — Rød, Nesset, Møre og Romsdal, Norge
Gjertrud Torbjørnsdotter Brænde  
Fødsel — 16. februar 1900 int(119) — Folkestad, Volda, Møre og Romsdal, Norge
Esther Victoria Callsen  
Død — 20. februar 1967 int(52) — Aberdeen, Brown County, South Dakota, USA
Johan Fredrik Klemetsen  
Død — 14. februar 1910 int(109) — Lovika, Dverberg, Nordland, Norge
Kristoffer Colbanussen  
Fødsel — 15. februar 1800 int(219) — Viken, Frosta, Nord-Trøndelag, Norge
Ruby Lanora Dawson  
Død — 16. februar 1986 int(33) — Riverside County, California, USA
Enok Jentoft Edvardsen  
Fødsel — 19. februar 1859 int(160) — Steiro, Sortland, Nordland, Norge
Karen Ellingsdotter  
Fødsel — før 15. februar 1756 int(263) — Ulvestad, Volda, Møre og Romsdal, Norge
Gunnar Ellingson + Brite Olsdotter
Vielse — 20. februar 1718 int(301) — Volda, Møre og Romsdal, Norge
Ole Elias Eriksen  
Fødsel — 17. februar 1881 int(138) — Rød, Aukra, Møre og Romsdal, Norge
Jens Bech Gøttsche  
Død — 19. februar 1806 int(213) — Herefoss, Birkenes, Aust-Agder, Norge
Jens Bech Gøttsche  
Fødsel — før 17. februar 1768 int(251) — Fredriksborg Amt, Danmark
Aagot Holmsen  
Død — 14. februar 1953 int(66) — Stadsbygd, Sør-Trøndelag, Norge
Cato Andreas Christian Holmsen  
Fødsel — 14. februar 1843 int(176) — Ørland, Sør-Trøndelag, Norge
Fridthjof Hans Gøttsche Holmsen  
Fødsel — 18. februar 1861 int(158) — Kvarberg, Ringsaker, Hedmark, Norge
Ole Andreas Ingebrigtson + Anna Karoline Olsdatter
Vielse — 17. februar 1914 int(105) — Bellingham, Whatcom County, Washington, USA
Ane Margrethe Isaksdatter  
Død — 18. februar 1866 int(153) — Faksfjord, Dyrøy, Troms, Norge
Isak Rasofiel Isaksen  
Fødsel — 15. februar 1881 int(138) — Igesund, Herøy, Møre og Romsdal, Norge
Ingeborg Maria Jakobsdotter  
Fødsel — 18. februar 1816 int(203) — Bjørkedal Søre, Volda, Møre og Romsdal, Norge
Kari Jakobsdotter  
Død — før 20. februar 1803 int(216) — Kornberg, Volda, Møre og Romsdal, Norge
Oline Jakobsdotter  
Fødsel — 16. februar 1819 int(200) — Nautvika Ytre, Volda, Møre og Romsdal, Norge
Ole Jakobsson  
Fødsel — før 20. februar 1763 int(256) — Mårstøyl, Volda, Møre og Romsdal, Norge
Peder Andreas Johanneson  
Død — 17. februar 1975 int(44) — Volda, Møre og Romsdal, Norge
Sæmund Martinus Andreas Johanneson 
Fødsel — 18. februar 1868 int(151) — Nautøy, Herøy, Møre og Romsdal, Norge
Jon Jonsson  
Fødsel — før 16. februar 1766 int(253) — Ulvestad, Volda, Møre og Romsdal, Norge
Pernille Kanutte Karlsdotter  
Død — 18. februar 1916 int(103) — Dalslisjebøen, Volda, Møre og Romsdal, Norge
Toralf Sigvart Klev  
Fødsel — 20. februar 1909 int(110) — Klev, Snåsa, Nord-Trøndelag, Norge
Brite Knutsdotter  
Død — før 16. februar 1749 int(270) — Eidset, Volda, Møre og Romsdal, Norge
Mette Knutsdotter  
Død — før 15. februar 1761 int(258) — Brekke, Ørsta, Møre og Romsdal, Norge
Johan Andreas Knutson  
Død — 15. februar 1895 int(124) — Marburg, KwaZulu-Natal, Sør-Afrika
Daniel Jakobus Knutsson  
Fødsel — 15. februar 1881 int(138) — Velle, Ørsta, Møre og Romsdal, Norge
Ingeborg Larsdatter  
Fødsel — 16. februar 1817 int(202) — Jørstad, Snåsa, Nord-Trøndelag, Norge
Peder Larsen  
Fødsel — 14. februar 1810 int(209) — Jørstad, Snåsa, Nord-Trøndelag, Norge
Beret Anna Lassesdotter  
Fødsel — 20. februar 1841 int(178) — Hatlen, Bolsøy, Møre og Romsdal, Norge
Nils Odin Lillebø  
Fødsel — 14. februar 1895 int(124) — Halkjelsvik, Volda, Møre og Romsdal, Norge
Andrew Lind  
Fødsel — 18. februar 1901 int(118) — Port Shepstone, KwaZulu-Natal, Sør-Afrika
Frida Lindeblad  
Fødsel — 17. februar 1882 int(137) — Skållerud, Mellerud, Dalsland, Västra Götaland, Sverige
Torborg Lindeblad  
Fødsel — 19. februar 1876 int(143) — Tisselskog, Dalsland, Västra Götaland, Sverige
Theodor Normann Lorentsen  
Fødsel — 20. februar 1885 int(134) — Berg, Kvæfjord, Troms, Norge
Lisa Cajsa Löfberg  
Død — 14. februar 1886 int(133) — Oslo, Norge
Asseline Moritsdotter  
Fødsel — 20. februar 1629 int(390) — Rygg, Gloppen, Sogn og Fjordane, Norge
Ingeborg Moritsdotter  
Fødsel — 19. februar 1719 int(300) — Bjørkedal Søre, Volda, Møre og Romsdal, Norge
Marta Nilsdatter  
Død — før 18. februar 1812 int(207) — Åse, Dverberg, Nordland, Norge
Andreas Pauli Nilsen  
Død — 15. februar 1932 int(87) — Lovika, Dverberg, Nordland, Norge
Anna Nilsen  
Fødsel — 17. februar 1907 int(112) — Volda, Møre og Romsdal, Norge
Ingemann Arliot Nilsen  
Fødsel — 14. februar 1898 int(121) — Andenes, Dverberg, Nordland, Norge
Iris Lynne Nilsen  
Fødsel — 15. februar 1932 int(87) — Hermosa Beach, Los Angeles, California, USA
Marta Olsdotter  
Død — før 15. februar 1750 int(269) — Straume, Volda, Møre og Romsdal, Norge
Gullik Olsson  
Fødsel — 20. februar 1718 int(301) — Høydalsdalen, Volda, Møre og Romsdal, Norge
Jakob Olsson + Malene Knutsdotter
Vielse — 17. februar 1743 int(276) — Volda, Møre og Romsdal, Norge
Jon Olsson  
Fødsel — før 16. februar 1800 int(219) — Bjørkedal Nøre, Volda, Møre og Romsdal, Norge
Knut Olsson  
Død — 19. februar 1825 int(194) — Flovikholm, Veøy, Møre og Romsdal, Norge
Ole Olsson  
Død — før 19. februar 1769 int(250) — Åmelfotdalen, Volda, Møre og Romsdal, Norge
Ole Olsson  
Fødsel — før 15. februar 1773 int(246) — Sør Nesje, Veøy, Møre og Romsdal, Norge
Lena Catharina Paludan  
Død — 17. februar 1806 int(213) — Oddernes, Kristiansand, Vest-Agder, Norge
Bersvend Paulsen  
Fødsel — før 16. februar 1800 int(219) — Kaldalbakken, Beitstad, Nord-Trøndelag, Norge
Cathinka Johanne Paus  
Fødsel — 17. februar 1874 int(145) — Oslo, Norge
Johanne Caroline Paus  
Fødsel — 16. februar 1813 int(206) — Rising, Gjerpen, Skien, Telemark, Norge
Anne Lisbet Pedersdotter  
Fødsel — før 19. februar 1764 int(255) — Kile, Volda, Møre og Romsdal, Norge
Siri Pedersdotter  
Fødsel — 19. februar 1826 int(193) — Skinnvika, Volda, Møre og Romsdal, Norge
Alfred Lawrence Prevost  
Død — 15. februar 1976 int(43) — Portland, Multnomah County, Oregon, USA
Marit Rasmusdatter  
Død — 18. februar 1888 int(131) — Nerem, Vestnes, Møre og Romsdal, Norge
Niels Rasmussen  
Død — 16. februar 1862 int(157) — Bø, Dverberg, Nordland, Norge
Petra Rebbestad  
Fødsel — 19. februar 1907 int(112) — Ørstavik, Ørsta, Møre og Romsdal, Norge
Per Olai Olsson Riste  
Fødsel — 20. februar 1846 int(173) — Riste, Sande, Møre og Romsdal, Norge
Edward Joseph Roe  
Fødsel — 19. februar 1924 int(95) — Brooklyn, Kings County, New York, USA
Jon Frederick Roe  
Fødsel — 18. februar 1937 int(82) — New York, USA
Knut Pederson Rød  
Fødsel — 19. februar 1865 int(154) — Rød, Nesset, Møre og Romsdal, Norge
Sigrid Pedersdotter Rød  
Død — 17. februar 1945 int(74) — Høvik, Nesset, Møre og Romsdal, Norge
Jenny Marie Rødseth  
Fødsel — 18. februar 1902 int(117) — Volda, Møre og Romsdal, Norge
Inger Else Røed  
Fødsel — 17. februar 1945 int(74) — Ørsta, Møre og Romsdal, Norge
Antonette Birgithe Olufine Samuelsdatter 
Fødsel — 16. februar 1877 int(142) — Aune indre, Trondenes, Troms, Norge
Johanna Berntine Samuelsdatter  
Fødsel — 17. februar 1873 int(146) — Aune indre, Trondenes, Troms, Norge
Earl Harold Sande + Marion Gascoyne
Vielse — 18. februar 1932 int(87)
Sigvart Christian Sandness  
Fødsel — 18. februar 1901 int(118) — Barnes County, North Dakota, USA
Floyd Hamilton Sayers  
Død — 14. februar 1939 int(80) — Yonkers, Westchester County, New York, USA
Ola Sjurson  
Død — 17. februar 1867 int(152) — Leikongsætra, Herøy, Møre og Romsdal, Norge
Clarence Ralph Snowberg  
Død — 17. februar 2003 int(16) — Minneapolis, Hennepin County, Minnesota, USA
Barbro Solmundsdotter  
Død — 16. februar 1848 int(171) — Velle, Ørsta, Møre og Romsdal, Norge
Ole Stenersen  
Fødsel — før 18. februar 1798 int(221) — Ovre, Gausdal, Oppland, Norge
Luther O. Strommen  
Fødsel — 15. februar 1917 int(102) — North Dakota, USA
Johannes Eriksson Söderström  
Fødsel — 17. februar 1823 int(196) — Sunnerud, Svanskog, Värmland, Sverige
Erik Taraldsen  
Død — 20. februar 1866 int(153) — Gran, Snåsa, Nord-Trøndelag, Norge
Robert Thomas  
Fødsel — 14. februar 1926 int(93) — Indianapolis, Marion County, Indiana, USA
Ingrid Larsdatter Tvete  
Død — 18. februar 1992 int(27) — Vågen, Frosta, Nord-Trøndelag, Norge
Jarle Larsen Tvete  
Fødsel — 17. februar 1915 int(104) — Vågen, Frosta, Nord-Trøndelag, Norge
Lars Larsen Tvete  
Død — 15. februar 1969 int(50) — Frosta, Nord-Trøndelag, Norge
Odd Tvete  
Fødsel — 20. februar 1916 int(103) — Aspgutu, Frosta, Nord-Trøndelag, Norge
Anna Margrethe Marie Wangensteen  
Død — 14. februar 1879 int(140) — Asak, Halden, Østfold, Norge

**Comment by magicsunday** [comment]
The problem seems to be, that you are running a 32-Bit system, The largest available integer will be 2147483647. So 2270592000 will be converted, as values outside of these ranges are represented by floating point values.

**Comment by HRN-webtrees** [comment]
Thank you magicsunday!
Tested on WAMP64 php 7.2.14, and can confirm the problem is gone.

**Comment by fisharebest** [comment]
I think there may be some other places that use seconds for time-differences.  I'll need to rewrite these to avoid 32 bit overflow.
