### ISSUE TITLE
2.0 - Compact tree, links take to home page

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2213]
Any link on this page returns the user to the home page.

![image](https://user-images.githubusercontent.com/5147603/52715665-40121600-2f5a-11e9-99a8-20d04923643f.png)

**Comment by fisharebest** [comment]
It is using the "old" URL - before the chart was converted into a module.

It needs updating to use the new module-generated URL.

**Comment by fisharebest** [comment]
I've fixed this, but can't push the changes until I have completed some other work.

**Comment by fisharebest** [comment]
Fixed.

**Comment by makitso** [comment]
I was not aware you were closing issues without pushing something to github?

**Comment by makitso** [comment]
I assume the code in part of "Refactoring themes and chart boxes" push you just did.  However, its difficult to track problems to updates without some identifier.

**Comment by fisharebest** [comment]
The fix was in the middle of about 100 local commits.

I squashed these 100 commits into 1 before pushing to github.  So, the fix for this issue got merged into the big commit.

I could have left it until later and fixed it in isolation, but I was editing that exact file when I saw the issue arrive.

**Comment by makitso** [comment]
I understand that a large commit can fix several bugs.  It would be helpful if when you close the issue(s) to note what title or number was of the commit.

**Comment by makitso** [comment]
Chis issue is fixed and included in commit "Refactoring themes and chart boxes" - 242a786
