### ISSUE TITLE
2.0 - Family book shows living people

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2214]
Not signed in yet shows names of living people.

![image](https://user-images.githubusercontent.com/5147603/52715993-ffff6300-2f5a-11e9-895e-8c337d7fdb25.png)

**Comment by fisharebest** [comment]
The demo site has the config option "Names of living individuals: show to visitors", so I would expect this.

This is on the basis that all the individuals are well-known public figures, and it makes the tree more interesting to visitors....
