### ISSUE TITLE
2.0 - Advanced Search failing

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2215]
Advanced search on Royal Family fails to return results.  If I search on Queen Victoria's Exact birth date of May 24, 1819 or 24 May 1819 I get no hits. 

![image](https://user-images.githubusercontent.com/5147603/52716992-49e94880-2f5d-11e9-831e-21795689adcf.png)

**Comment by fisharebest** [comment]
The input form is expecting a date in GEDCOM format.

i.e. it works for `14 MAY 1819`.

I guess this field is missing the javascript "fixer" that we have on the edit-date fields.

**Comment by makitso** [comment]
The date of May 24, 1819 fails, the date of MAY 25, 1819 succeeds.

**Comment by fisharebest** [comment]
> the date of MAY 25, 1819 succeeds.

You mean that `MAY 25, 1819` (with exact date) will find Queen Victoria?
