### ISSUE TITLE
Chart right and left arrows and Slide show arrows in the wrong direction on rtl pages - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2222]
![2019-02-16_23-54-31](https://user-images.githubusercontent.com/5202996/52905691-4e0bb380-3246-11e9-89d8-ccaab5c214b6.jpg)

**Comment by fisharebest** [comment]
The rule to reverse certain icons on RTL pages seems to have been lost.

I've added it back in.  This should fix RTL icons in all pages.

**Comment by melizaa** [comment]
The arrows point now in the wrong direction on the ltr pages.

**Comment by fisharebest** [comment]
> The arrows point now in the wrong direction on the ltr pages.

Which arrows?

Slide-show icons and compact-chart arrows look OK for me on both LTR and RTL.

**Comment by melizaa** [comment]
Let me double check my sites.
