### ISSUE TITLE
Individual box sizes - demo-dev & local 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2228]
The individual boxes have different sizes on different pages and even on the same page, for instance the family page and relationships.

This causes the pages to look unclean.

The boxes arre too small for my site (Samuel, Jakob, Racki and Freddie Young) and even for the demo-dev Royal Family data.
We do not see fully the last row, we do not see death data, we do not see the death place or fully the death place, ...

Family page (also the titles are not above the data)
![image](https://user-images.githubusercontent.com/5202996/52911320-d91e9500-32aa-11e9-8efb-bcd9cd493d3b.png)

Pedigree
![image](https://user-images.githubusercontent.com/5202996/52911360-7aa5e680-32ab-11e9-8bb6-abda212cfd54.png)

![image](https://user-images.githubusercontent.com/5202996/52911419-39620680-32ac-11e9-81f1-af74d69bef68.png)

**Comment by melizaa** [comment]
Relationship chart -  the boxes are narrower and narrower and we do not even see the birth and death years.
![image](https://user-images.githubusercontent.com/5202996/52911548-04ef4a00-32ae-11e9-8222-9eb598a2e75b.png)

**Comment by fisharebest** [comment]
> The individual boxes have different sizes on different pages and even on the same page

The new design for chart boxes allows them to have different sizes and different content in different places.  This gives a lot of flexibility.  For example, we could do things like show smaller boxes with less detail on the last row of pedigree charts.

I have only looked at the compact/pedigree charts so far.  I'm working on the others next.

**Comment by fisharebest** [comment]
The ancestors and descendant charts (list view) have now been updated.

I am working on the others.

**Comment by fisharebest** [comment]
More charts have been updated.

Still outstanding are

* Hourglass
* Ancestors (booklet view)
* Descendants (booklet view)

**Comment by fisharebest** [comment]
Box widths should now be set for all charts
