### ISSUE TITLE
General and Phonetic Search special characters - 2.0.0.

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2229]
I do not see for instance Ä/ä, Ü/ü and the lower case only German sharp s, ß, in the search list of special Latin characters. They are needed at least for Finnish, Swedish, German.
I think that I see twice У in the Cyrillic letters. I do not see B there.
I do not see for instance all the the Viatnamese special letters.     

Are all the special letters of the wt languages covered?

**Comment by fisharebest** [comment]
> I do not see for instance Ä/ä, Ü/ü

Fixed.

> and the lower case only German sharp s, ß

Both upper and lower case esszet are already included:

<img width="354" alt="screen shot 2019-02-17 at 14 37 00" src="https://user-images.githubusercontent.com/2306088/52914691-67067a00-32c3-11e9-9a43-ac54d421d5e3.png">

> I think that I see twice У in the Cyrillic letters. I do not see B there.

Fixed.

> I do not see for instance all the the Viatnamese special letters.

If I understand correctly, vietnamese can have many diacritic symbols on each letter.  I cannot find an on-line resource, and so I would need a vietnamese speaker to provide a list.

> Are all the special letters of the wt languages covered?

I don't know!  I included all the common ones.
