### ISSUE TITLE
Some ideas for version 2.0

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2232]
1、Parent information is displayed by default in search and search results
At present, I find that there is a very inconvenient place in the process of use. In the browse chart, select the root personnel ID to find the filter. If there are many people with the same name, you don't know which one to choose. How can I show individual parents in the search filter results? I look forward to your help. Thank you.

2、I hope to add custom pseudo-static function in version 2.0.
Using pseudo-static, not only is more friendly to search engines, but can also use CDN for caching, improving website speed.
E.g:
Use pseudo-static for the ‘individual.php’ and ‘family.php’ pages, and change the url from ‘/individual.php?pid=I1111&ged=aaa’ to ‘/aaa/person/I111.html’, change the url from ‘family.php?famid= F1111&ged=aaa’ to ‘/aaa/family/F1111.html’

3、Increase Chinese Lunar Support
There is no support for the Chinese Lunar Calendar in the current code. I hope to increase support for the Chinese Lunar Date. Or integrate the code below.
https://github.com/guojikai/plunar

**Comment by fisharebest** [comment]
> 1. How can I show individual parents in the search filter results?

There is a button "show parents" at the bottom of the list.

> 2. and 3.

Please create one issue for one item.

It is impossible to manage requests that contain lists of unrelated items.
