### ISSUE TITLE
Missing map markers - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2237]
I do not see map place markers in Control Panel -> Map -> Geographic data -  map-data-edit
![2019-02-19_21-27-28](https://user-images.githubusercontent.com/5202996/53041756-720d0600-348d-11e9-855c-f6ebfcd7c755.jpg)

**Comment by TheRealJPS** [comment]
Same here with 2.0.0-beta.3

**Comment by fisharebest** [comment]
This was fixed in 75e7614a3c4ae5641ce6af45e2bb8ce501918735
