### ISSUE TITLE
Radiobutton-Labels not working in modules

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#2244]
See https://dev.webtrees.net/demo-dev/index.php?route=module&module=pedigree_chart&action=Chart&xref=i1&ged=demo for example.

If the view components/radio.phtml is used the radio button labels are not clickable.

**Comment by magicsunday** [comment]
#2245 allows adding an "id" attribute. Its fixed for the map provider list in admin but needs to be fixed too in all affected places.

**Comment by fisharebest** [comment]
The bootstrap4 markup does not allow us to put the control inside the label - `<label><input></label>`.

See https://getbootstrap.com/docs/4.0/components/forms/#checkboxes-and-radios

Therefore we must use an `id`.

Perhaps in the view: `$id = $id ?? Uuid::uuid4()->toString()`.

HOWEVER -  In Laravel Blade templates, variables are automatically passed from parent-view to child-view.  With this logic, the child-view would break if the parent-view already used `$id`.

Can we do this in a way that will no break if we replace our PHP templates with Blade templages?
OR - can we implement the inheritence feature?  Perhaps inheritance now would be better?

**Comment by fisharebest** [comment]
We have new templates for radio buttons and checkboxes.  These use (or create) `id` attributes.

Although the templates currently use bootstrap, they are just called "components", to allow a different CSS framework to be used easily.
