### ISSUE TITLE
2.0 – Custom Modules: ModuleCustomInterface methods never called

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#2257]
The methods from ModuleCustomInterface are currently not evaluated, in particular
`customModuleAuthorName()`
`customModuleVersion()`

They were probably intended to replace
`$module::CUSTOM_VERSION`
etc in modules.phtml?

Also the methods 
`customModuleLatestVersionUrl()`
`customModuleSupportUrl()`
seem to overlap with ModuleExternalUrlIInterface?

**Comment by fisharebest** [comment]
> seem to overlap with ModuleExternalUrlIInterface?

The "analytics" modules have external URLs, which point to the information page for the service.

A custom analytics module would need a link to this page, and also a link to the module home page.

**Comment by fisharebest** [comment]
These need to be added to `resources/views/admin/custom-module-info.phtml`
