### ISSUE TITLE
Rejecting records on import

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#2259]
![igf](https://user-images.githubusercontent.com/5910274/53293468-fced4980-3788-11e9-8227-a404a4ef8bf7.jpg)
Exported entire DB without privacy=None
Added several new records in valid format.
On import, several records are alleged invalid format, but the messages vanish too fast to read.  After a few attempts, grabbed the attached screen shot.  Some individuals that are in the import (but not in the screenshot) cannot be found in the DB.  I see no errors in the format of the records displayed.

**Comment by WGroleau** [comment]
After flashing the invalid format claim, it appears to continue importing, and error check finds no errors.

**Comment by fisharebest** [comment]
> Added several new records in valid format.

I don't think they are valid.

`0 INDI @BMV@` should be `0 @BVM@ INDI`

**Comment by WGroleau** [comment]
Of course, you are correct and I should have known better!
