### ISSUE TITLE
2.0 - lifespan

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2264]
Is there a configuration option to not display lifespan in charts?

**Comment by fisharebest** [comment]
All chartboxes contain all the content.

Displaying/hiding is down to each chart/theme - using CSS.

This lets us do things such as

* show reduced content and smaller boxes on the older generations of a pedigree tree.
* toggle compact/full views using a checkbox/javascript to add/remove CSS.

So, I have created a system that allows flexibility and configuration, but I haven't yet written anything to take advantage of it.

**Comment by makitso** [comment]
Just seems superfluous to me since there is the Birth and Death facts.

**Comment by fisharebest** [comment]
Both need to be present - so that one can be hidden.

If there's a chart showing both, then it probably means I haven't had a chance to look at the styling for it yet.

Which chart are you refering to?

**Comment by makitso** [comment]
Family book of Queen Elizabeth II,  Relationships Elizabeth 1 - King Edward VII, Individual page (Famlies) King Edward VII, Relationships with spouse, Compact Charts Queen Elizabeth.
