### ISSUE TITLE
Errors announced too fast to read

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#2265]
When an imported GEDCOM contains records starting with
`0 INDI @ID#@`
The invalid records are displayed, but not long enough to examine.  (See 
https://github.com/fisharebest/webtrees/issues/2259).  Then the import continues with the valid records.

I think the error message should remain until the user clicks a button to either cancel import or continue with whatever valid records are in the file.

**Comment by fisharebest** [comment]
Import now stops at the error.

The error message includes the GEDCOM record being processed at the time.
