### ISSUE TITLE
Add husband serves wife form

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#2274]
1.7.12 — "Add a husband using an existing individual" and "Add a wife using an existing individual" both bring up the form to add a wife.

**Comment by magicsunday** [comment]
Seems fine to me: https://dev.webtrees.net/demo-stable/individual.php?pid=i1&ged=demo

**Comment by fisharebest** [comment]
If the individual is male, we get an "add wife using existing individual" link and an "add wife" form.

If the individual is female, we get an "add husband using existing individual" link and "add husband" form.

But if the individual has no sex, then we get a slightly different error in 1.7 and 2.0

In 1.7, we get both links - but both give the same "add wife" form.

In 2.0, we only get the "add wife" and "add wife using existing individual" links.

Perhaps the solution is to replace the link(s) with "add spouse" and "add spouse using existing individual".

**Comment by WGroleau** [comment]
"Add spouse" sounds good to me, with the added person tagged HUSB or WIFE according to gender.  But if the added spouse is 'U', then what?
