### ISSUE TITLE
Use the chrome browser to select the wrong language file

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2275]
My operating system is Simplified Chinese and the browser language is also Simplified Chinese.
When I use Google Chrome to access https://dev.webtrees.net/demo-dev/, the default is English language, which is wrong.
When I use the Edge browser to access https://dev.webtrees.net/demo-dev/, the default is Simplified Chinese, which is correct.

Both 2.0 and 1.7 have this problem.

I looked at the differences between chrome and edge language code.
Chrome: zh-CN, zh; q=0.9, en-US; q=0.8, en; q=0.7, zh-TW; q=0.6
IE/Edge: zh-Hans-CN, zh-Hans; q=0.5

**Comment by fisharebest** [comment]
webtrees has two Chinese translations:

* `zh-Hans` - Chinese written in simplified script
* `zh-Hant` - Chinese written in traditional script

> My operating system is Simplified Chinese and the browser language is also Simplified Chinese.

It looks like the chrome browser is lying or broken.  I see the following options:

<img width="558" alt="screenshot 2019-02-26 at 08 52 06" src="https://user-images.githubusercontent.com/2306088/53400038-f1766a00-39a4-11e9-8ff7-6c718a6e9774.png">

These four options request these four langauge codes:

* Chinese `zh`
* Chinese (Hong Kong) `zh-HK`
* Chinese (Simplifed) `zh-CN`
* Chinese (Traditional) `zh-TW`

For once, it seems that Microsoft is following the correct standards ;-)

**Comment by xmlf** [comment]
Yes. However, there are a lot of users who use chrome.
Therefore, you should also join zh-CN when judging.

**Comment by fisharebest** [comment]
Here are two links from the web standards organisation which says that `zh-Hant` and `zh-Hans` is correct.

https://www.w3.org/International/questions/qa-css-lang#bytheway
https://www.w3.org/International/articles/language-tags/

**Comment by xmlf** [comment]
> Here are two links from the web standards organisation which says that `zh-Hant` and `zh-Hans` is correct.
> 
> https://www.w3.org/International/questions/qa-css-lang#bytheway
> https://www.w3.org/International/articles/language-tags/

In addition, I found that firefox is also zh-cn

**Comment by fisharebest** [comment]
One solution might be to add the following mappings:

`zh` => `zh-Hans-CN`
`zh-CN` => `zh-Hans-CN`
`zh-SG` => `zh-Hans-SG`
`zh-HK` => `zh-Hant-HK`
`zh-TW` => `zh-Hant-TW`
`zh-MO` => `zh-Hant-MO`

However, this is not part of webtrees.  It is part of another package (which I also wrote) -  [fisharebest/localization](https://github.com/fisharebest/localization)

**Comment by xmlf** [comment]
HI @fisharebest ，
The problem still exists and is not resolved.

**Comment by fisharebest** [comment]
I think that in Chrome, you have selected both `zh-CN` **and** `en-US`.

When we look for alternatives (i.e. `zh-Hans` instead of `zh-CN`), these are added to the end of your list.

So, webtrees searches the list: `zh-CN`, `en-US` and `zh-Hans`.

It will match `en-US` *before* it matches `zh-Hans`.

You are telling chrome that you want English - and so you get English.

Remove `en-US` in chrome, and it will work.

**Comment by xmlf** [comment]
Thank you very much! I removed en-us and the problem was solved.
