### ISSUE TITLE
Name record does not follow Gedcom5.5.1 standard.

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2279]
Previously, I have been using the PGV program to maintain my family tree online and use Gramps to organize my genealogy data.
There is no problem in importing data between **Gramps** and **PGV**.
Now, when I try Webtrees 2.0, I import the Gramps or PGV data into webtrees and find that Surname and Given name are wrong, and I can't set the surname to be displayed in the family tree.
Later, I looked at the Gedcom record and found that the Gedcom Name record in webtrees is:
**1 NAME surname / given name /**

I found out that webtrees did not comply with the Gedcom standard by reviewing the Gedcom 5.5.1 standard (https://wiki.webtrees.net/w/images-en/Ged551-5.pdf, pp. 54-55).
![default](https://user-images.githubusercontent.com/26761596/53534067-45fe1e80-3b38-11e9-9c31-668044ff8e51.JPG)

Gramps, PGV, and other programs follow the Gedcom 5.5.1 standard.
**1 NAME Given name/ Surname  /**

**This will make maintenance between different programs very difficult.**

Hopefully webtrees 2.0 will comply with the Gedcom 5.5.1 standard and provide the "surname shown in front" option in the control panel.

Thank you very much for your hard work and dedication.

**Comment by magicsunday** [comment]
I could not reproduce this with my tree (non chinese). My webtrees exports are as expected. 

GRAMPS is not fully 5.5.1 compatible (https://www.gramps-project.org/wiki/index.php?title=Features:  Extensive support for the defacto industry standard GEDCOM version 5.5.1 so you can exchange Gramps information to and from users of most other genealogy programs.).
- Reports "FORM" error which is not present
- Does not handle RELI, ASSO, RELA, SOUR, ...

But let's not stick to trivialities. 😄

**Comment by xmlf** [comment]
> I could not reproduce this with my tree (non chinese). My webtrees imports/exports are as expected.
> 
> GRAMPS is not fully 5.5.1 compatible (https://www.gramps-project.org/wiki/index.php?title=Features: Extensive support for the defacto industry standard GEDCOM version 5.5.1 so you can exchange Gramps information to and from users of most other genealogy programs.).
> 
> * Reports "FORM" error which is not present
> * Does not handle RELI, ASSO, RELA, SOUR, ...
> 
> But let's not stick to trivialities. 😄

When I use My Family Tree, GRAMPS or PGV for maintenance. Gedcom is recorded as 1 NAME Given name /surname /.
And you can set the display "last name in front".

When I will maintain good data in these programs, the display is wrong when importing webtrees. Because it is impossible to control the display "last name is in front".

Webtrees stores the record form in English language is correct.
  1 NAME Given name /surname /

In Chinese language, storage does not follow the gedcom standard. it is

  1 NAME surname /Given name /

**Comment by fisharebest** [comment]
> I import the Gramps or PGV data into webtrees and find that Surname and Given name are wrong

> Later, I looked at the Gedcom record and found that the Gedcom Name record in webtrees is:
**1 NAME surname / given name /**

This is because the names are wrong in PGV!

Surname-first names should be stored surname first.
Surname-last names should be stored surname last.

webtrees can create both names.

If you set your language to Chinese (or Hungarian or ...), then webtrees will create surname-first names.

If you set your langauge to other languages, then webtrees will create surname-last names.

If the default order is wrong, click the edit link by the name, and you will be able to change the order.  This is also useful for names that are do not have the standard format.  e.g.

1 NAME Queen Elizabeth
2 GIVN Elizabeth, Alexandra, Mary

**Comment by fisharebest** [comment]
> When I use My Family Tree, GRAMPS or PGV for maintenance. Gedcom is recorded as 1 NAME Given name /surname /.

This is bad logic.

The GEDCOM standard says that:

> The name value is formed in the manner the name is normally spoken, with the given name and family name (surname) separated by slashes (/).

So, if a name is normally spoken surname-first, then it should be stored surname-first.

> And you can set the display "last name in front".

The order of names is not a *display* issue.

My name is `Greg /Roach/`.  If I visit China, my name is still "Greg Roach".  It does not become "Roach Greg".

If a `/Ban/ Ki-Moon` visits England, we still call him "Ban Ki-Moon".  We do not call him "Ki-Moon Ban".

PGV is wrong.  This was a deliberate change in webtrees.

**Comment by xmlf** [comment]
> > When I use My Family Tree, GRAMPS or PGV for maintenance. Gedcom is recorded as 1 NAME Given name /surname /.
> 
> This is bad logic.
> 
I very much agree with what you said. According to Chinese habits, the surname is completely correct in front.
However, this will result in inability to share data with other software. Because, in other software, the display is wrong.
Or, can  provide options and convert when webtrees import and export data?

**Comment by fisharebest** [comment]
> > The surname of an individual, if known, is enclosed between two slash (/) characters
>
> What does it mean?

The `1  NAME` is used to create the display name.
The `2 GIVN` and `2 SURN` are only used for sorting, searching, etc.

You should put a `/` before and after the surname.  e.g.

```
1 NAME Greg /Roach/
2 GIVN Greg
2 SURN Roach
```

``
1 NAME /周/朝佐
2 GIVN 朝佐
2 SURN 周
``

If an individual has two surnames, put a slash around each one.

```
1 NAME Jose /Sanchez/ /Cervantes/
```

If the surname is unknown, use empty slashes

```
1 NAME John //
```

If the individual has no surname (e.g. in Iceland), do not use slashes

```
1 NAME Eric Godwinson
```

**Comment by xmlf** [comment]
Thank you very much for your answer. I understand the mistake.
Webtrees are compliant with the gedcom5.5.1 standard.
It is only in the display order that the adjustment is more in line with the usage habits.
thanks again!
