### ISSUE TITLE
Add individual page label sorting

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2280]
When my language selection is English, the display order is as follows：
Album，Facts and events，Families，Interactive tree，Media，Notes，Places，Sources

![inditab](https://user-images.githubusercontent.com/26761596/53534948-d25e1080-3b3b-11e9-9106-4be40eef7ae6.JPG)

When my language selection is Chinese, the display order is as follows
Places，Notes，Families，Interactive tree，Media，Facts and events，Album，Sources

![inditab2](https://user-images.githubusercontent.com/26761596/53534950-d427d400-3b3b-11e9-95b2-c3f534b5f7c5.JPG)

It is desirable to increase the label display order control, or displayed in a fixed order in English

**Comment by fisharebest** [comment]
1) You can change the order in the control panel.

2) The default order is correct when you use MySQL.  The default order is wrong for SQLite.

**Comment by xmlf** [comment]
> 1. You can change the order in the control panel.
> 2. The default order is correct when you use MySQL.  The default order is wrong for SQLite.

YES！I  can change the order in the control panel.
Thank you!
