### ISSUE TITLE
F.A.B sex icons in the indi- & family-list not readable on the dark zebra lines - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2284]
![2019-02-28_22-50-39](https://user-images.githubusercontent.com/5202996/53597679-7206b780-3bab-11e9-8810-f93330a582a1.jpg)

**Comment by fisharebest** [comment]
What do you prefer?

Darker icons?
Lighter backgrounds?
White background on the icon?

**Comment by melizaa** [comment]
I think it would be better to have darker icons and if still required, a little lighter background.

**Comment by melizaa** [comment]
The F.A.B. sex icons can also not be seen for instance in the pedigree chart individual boxes.

**Comment by Amgine0** [comment]
Everything I needed to know about color contrasts is summed up by [@accessibleColors@botsin.space]( https://botsin.space/@accessibleColors "Mastodon Bot")  (Nutshell: [Web Contrast Accessibility Guidelines](https://www.w3.org/TR/2008/REC-WCAG20-20081211/) are cryptic, but useful, yet you still need a few humans to test.)
