### ISSUE TITLE
After I change an indi and do not approve the change and go to the home page or to the my page, I get an error - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2285]
I do not see the error in demo-dev.
I see it in both my test systems.

Fatal error: Uncaught Error: Call to a member function canShow() on null in /home/amitys/test.amitys.com/app/Module/ReviewChangesModule.php:153 Stack trace: #0 /home/amitys/test.amitys.com/resources/views/tree-page-block.phtml(5): Fisharebest\Webtrees\Module\ReviewChangesModule->getBlock(Object(Fisharebest\Webtrees\Tree), 433, 'gedcom') #1 /home/amitys/test.amitys.com/app/View.php(143): include('/home/amitys/te...') #2 /home/amitys/test.amitys.com/app/View.php(187): Fisharebest\Webtrees\View->render() #3 /home/amitys/test.amitys.com/app/Helpers/functions.php(108): Fisharebest\Webtrees\View::make('tree-page-block', Array) #4 /home/amitys/test.amitys.com/resources/views/tree-page.phtml(16): view('tree-page-block', Array) #5 /home/amitys/test.amitys.com/app/View.php(143): include('/home/amitys/te...') #6 /home/amitys/test.amitys.com/app/View.php(187): Fisharebest\Webtrees\View->render() #7 /home/amitys/test.amitys.com/app/Helpers/functions.php(108): Fisharebest\Webtrees\View::make('tree-page', Array) #8 /home/amitys/test.ami in /home/amitys/test.amitys.com/app/Module/ReviewChangesModule.php on line 153

**Comment by xmlf** [comment]
#2282
