### ISSUE TITLE
2.0 - Choose to use English language, add name, switch to Chinese language, can't edit name

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2289]
When I add a name in the  language  of English, the format is
/surname/givn name
After saving.
Then, I switched the language to the Chinese state and could not edit the name.
Similarly, I can't edit all the names added in the Chinese language when I switch languages to English.

After troubleshooting, I found that there is a problem with the js code in resources/views/edit/new-individual.phtml.
Starting from line 399

```
 if (locale === "vi" || locale === "hu") {
            // Default format: /SURN/ GIVN
         return trim(npfx + " /" + trim(spfx + " " + surn).replace(/ *, */g, " ") + "/ " + givn.replace(/ *, */g, " ") + " " + nsfx); // not executed correctly.
        } else if (locale === "zh-Hans" || locale === "zh-Hant") {
            // Default format: /SURN/GIVN
        return npfx + "/" + spfx + surn + "/" + givn + nsfx; // not executed correctly.
	}

```

` return trim(npfx + " /" + trim(spfx + " " + surn).replace(/ *, */g, " ") + "/ " + givn.replace(/ *, */g, " ") + " " + nsfx);` 
And
`return npfx + "/" + spfx + surn + "/" + givn + nsfx;`
The code is not executed correctly.

**Comment by fisharebest** [comment]
This is working as designed.

webtrees can calculate the `NAME` automatically.  It is correct for 99% of names - but all.
This is why we have the "edit" icon - so you can edit the `NAME` independently.

When you edit an *existing* name, webtrees will only update the `NAME` automatically if it can be generated automatically from the `GIVN`, 'SURN`, etc.

When you change from English to Chinese, you change the rule for automatically generating `NAME`.  Therefore it is now "unlinked" and you must edit it manually.

> Similarly, I can't edit all the names added in the Chinese language when I switch languages to English

You *can* edit them manually.
They are not updated automatically.

**Comment by xmlf** [comment]
However, I added the name in the Chinese language. Still in the Chinese language, the editor still can't automatically generate the name.

![editerror](https://user-images.githubusercontent.com/26761596/53631536-b5b1fd80-3c4d-11e9-8b01-273a1813c95a.gif)

Under the chrome browser, the **Name** field is blank.
Under the Edge browser, the **Name** field display can be displayed.

**Comment by xmlf** [comment]
I suddenly thought that if Chinese people living in the United States (such as the joytree of the webtrees forum), he would only speak English and would not speak Chinese.
When he processes family tree data, everyone has a Chinese name and an English name, so everyone can't automatically generate a name.
It will cause a lot of trouble for his use.
