### ISSUE TITLE
Statistics - Number of children - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2295]
I do not understand the number of children 0-1, 1-2, 2-3, etc. In the custom statistics.
Do we see families with 1 child both in 0-1 and in 1-2?

**Comment by magicsunday** [comment]
Seems to be an error, compared with the 1.7 branch.

https://dev.webtrees.net/demo-dev/index.php?route=module&module=statistics_chart&action=Chart&ged=demo#tab-tab-9a4e800b7ff81308b463956d1a0a66d3

https://dev.webtrees.net/demo-stable/statistics.php?ged=demo

**Comment by fisharebest** [comment]
This is the `axisNumbers()` function.  There is the same issue on other charts such as age at first marriage...
