### ISSUE TITLE
2.0 Surname missing link on families list

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2297]
![image](https://user-images.githubusercontent.com/5147603/53700468-de520880-3daf-11e9-93a9-333d6b81e03f.png)

**Comment by fisharebest** [comment]
I think this was fixed earlier today in 47a36b2f839776f94c9d5b28dc1df294b452d820

Are you using the latest code?

**Comment by makitso** [comment]
You have been busy.  But no, still a problem.

**Comment by fisharebest** [comment]
Have you disabled the individual or family list modules?

**Comment by makitso** [comment]
> Have you disabled the individual or family list modules?

No.  There is no link in the code.  

Here is what the demo site shows
![image](https://user-images.githubusercontent.com/5147603/53701282-87046600-3db8-11e9-912d-53554f0d0ae4.png)
