### ISSUE TITLE
Where do language .mo files go?

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2298]
With the new refactoring of the language files to use laravel structure, where do we put our old .mo files?
If I have a German de.mo file to I rename it and put it somewhere?

**Comment by xmlf** [comment]
put it here:
resources/lang/de/messages.mo

**Comment by fisharebest** [comment]
@makitso - if you install a bash shell (e.g. https://www.cygwin.com), then you can run the commands to update/compile the .PO files - as mentioned in #2305

**Comment by makitso** [comment]
> update/compile the .PO files
I simply copied the .mo file from the old structure to the new structure and renamed it as messages.mo
This seems to work right?

**Comment by fisharebest** [comment]
> This seems to work right?

Yup - that's fine.
