### ISSUE TITLE
Admin: Module configuration shows message about preferences, which can't be removed.

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#2300]
The module configuration (index.php?route=modules). prints messages about existing preferences for the modules which are no longer present.

Preferences exist for the module “british-monarchs”, but this module no longer exists.
Preferences exist for the module “british-prime-ministers”, but this module no longer exists.
Preferences exist for the module “british-social-history”, but this module no longer exists.
Preferences exist for the module “us-presidents”, but this module no longer exists. 

If I click on "Delete ..." it displays a success messsage "The preferences for the module “british-monarchs” have been deleted." but the warning still persists.

**Comment by xmlf** [comment]
Yes. This problem does exist.
