### ISSUE TITLE
webtrees demo site throws error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2305]
ErrorException: filemtime(): stat failed for /resources/lang/en-GB/messages.mo in file /app/I18N.php on line 420
Stack trace:
  1. ErrorException->() /app/I18N.php:420
  2. filemtime() /app/I18N.php:420
  3. Fisharebest\Webtrees\I18N->init() /app/Http/Middleware/UseLocale.php:47
  4. Fisharebest\Webtrees\Http\Middleware\UseLocale->handle() /index.php:139
  5. {closure}() /app/Http/Middleware/UseTree.php:58
  6. Fisharebest\Webtrees\Http\Middleware\UseTree->handle() /index.php:139
  7. {closure}() /app/Http/Middleware/UseSession.php:59
  8. Fisharebest\Webtrees\Http\Middleware\UseSession->handle() /index.php:139
  9. {closure}() /app/Http/Middleware/UseFilesystem.php:50
 10. Fisharebest\Webtrees\Http\Middleware\UseFilesystem->handle() /index.php:139
 11. {closure}() /app/Http/Middleware/SetPhpLimits.php:54
 12. Fisharebest\Webtrees\Http\Middleware\SetPhpLimits->handle() /index.php:139
 13. {closure}() /app/Http/Middleware/CheckForMaintenanceMode.php:48
 14. Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->handle() /index.php:139
 15. {closure}() /index.php:156

**Comment by magicsunday** [comment]
Seems like that all the *.mo files in the new language directories are missing and required to be created.

**Comment by makitso** [comment]
Yes, they need to be copied from the old /language folder  and renamed to messages.mo.

**Comment by fisharebest** [comment]
I have rebuilt the language files.

Assuming you have `composer` and the `gettext` command line tools installed, the command to do this is

`composer webtrees:mo`
