### ISSUE TITLE
2.0 - Languages do not show up in Control Pannel / Languages

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2307]
![image](https://user-images.githubusercontent.com/5147603/53824937-5e07e080-3f32-11e9-8485-e47e3f3a8387.png)

Recompiling languages makes no difference  composer webtrees:mo

**Comment by goon818** [comment]
I miss the other languages too.
The folder language was deleted automaticaly on the host, if i go to the language setting in the control panel.
