### ISSUE TITLE
How to add logo into the header of fab theme

### ISSUE THREAD

**Issue by uocepek** [fisharebest/webtrees#2311]
Hi, I'd like to upgrade the "fab" theme for Webtrees. I want to add a clickable logo instead of the name of the family tree in the header. I have already checked some .php and .css files, but I have not found any solution, yet? Is there any easy way to do that?

**Comment by fisharebest** [comment]
Are you talking about 2.0 or 1.7 ?

**Comment by uocepek** [comment]
I'm using webtrees 1.7

**Comment by fisharebest** [comment]
That content is generated by this function:

https://github.com/fisharebest/webtrees/blob/1.7.12/app/Theme/AbstractTheme.php#L562-L574

Ideally, you would create a new theme (which extends the "fab" theme).
You then provide your own version of this function in your new theme.

**Comment by uocepek** [comment]
Thank you very much! It works great!
