### ISSUE TITLE
2.0 - Primary menu dropdown display problem for rtl 

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2315]
Problem is most noticeable on Family Tree
![image](https://user-images.githubusercontent.com/5147603/54072518-f656db80-4238-11e9-88dc-3ab40e6cc6c5.png)

For rtl, shouldn't the left: 0px be changed to right: 0px?

![image](https://user-images.githubusercontent.com/5147603/54072523-0a024200-4239-11e9-9a15-cf82d480b10d.png)

**Comment by fisharebest** [comment]
Bootstrap is a mix of CSS and JS.  We have created a mirror of the CSS - which works very well.

AFAICT, the position of the dropdowns is set using JS in the library `popper.js`.

**Comment by makitso** [comment]
I don't use rtl myself.  The problem can be fixed with:

[dir=rtl] .dropdown-menu[x-placement^=bottom] {
	left: auto!important;
}

**Comment by fisharebest** [comment]
Thanks.  I guess the !important overrides the inline style set by JS.

I'm not 100% certain this will fix *every* problem, but it may well fix enough of them...

**Comment by makitso** [comment]
I updated the fix listed above to reduce the scope of the change.

**Comment by melizaa** [comment]
The gedcom titles in demo-dev are now OK on rtl pages.
My test site two last titles are not yet OK.
![2019-03-10_11-24-32](https://user-images.githubusercontent.com/5202996/54083143-a5beab80-4328-11e9-9127-b5628fae4929.jpg)

I miss also in demo-dev and on my test site the last word in the Hebrew home page and my page "my pages" menu.
![2019-03-10_11-28-20](https://user-images.githubusercontent.com/5202996/54083193-1cf43f80-4329-11e9-91d1-930d8d97f296.jpg)

**Comment by fisharebest** [comment]
Thanks for the fix.
