### ISSUE TITLE
Lists - shared notes datatables display

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2317]
V2.0 See attached image. The display count is overlayed with something. In addition the overall layout of the datatables fields (pager, filter, display etc.) is different on this page to others.

![demo](https://user-images.githubusercontent.com/104515/54077197-3c4d8700-42ad-11e9-9188-5183e66a8df8.jpg)

**Comment by fisharebest** [comment]
Same problem with source and repository lists
