### ISSUE TITLE
2.0 – Notes on repository names

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#2321]
In `edit-facts.phtml`:

`// REPO:NAME facts may take a NOTE (but the REPO record may not).`

Doesn't seem right. The spec says:

> REPOSITORY_RECORD:=
> n @<XREF:REPO>@ REPO
> +1 NAME <NAME_OF_REPOSITORY>
> +1 <<ADDRESS_STRUCTURE>>
> +1 <<NOTE_STRUCTURE>>

I.e. the note is on the record itself, not on its name.

**Comment by fisharebest** [comment]
It looks like someone (probably me!) misread the spec.
