### ISSUE TITLE
How to implement a new theme (from alpha-5)

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#2322]
Since alpha-5 the theme interface is moved to modules, but I can't figure out how to add a new theme.

I followed the example given [here](https://github.com/fisharebest/webtrees/tree/master/modules_v4) for the pedigree chart. That works. But if I want to do the same thing with a theme it doesn't work at all. I can't get my theme to show up in the module directory or in the theme selector. Can you please give a basic example how to add a custom theme? In my case I want to extend the minimal theme.

**Comment by fisharebest** [comment]
Hi Carmen - the module/theme interface is the last to be updated, and I only started today.

I have just pushed some sample code to `modules_v4/example-theme.disable/`.

It demonstrates adding a CSS file to an existing theme, and replacing one of the views.

It is a first draft and needs tidying up.  Some of the functions (e.g. `getAssetAction()` and `assetUrl()` ) will be moved to one of the core classes.  But I haven't decided which one.

**Comment by xmlf** [comment]
If the added css style is the same as the css style name in the existing theme, is the CSS style of the existing theme overwritten with the added css style?

**Comment by JustCarmen** [comment]
Thanks. I've tried the example and it works. I was assuming the theme implementation in the module section was in test phase with the release of alpha-5, but it is now clear to me it was not. No hurries, I'll wait :).

**Comment by fisharebest** [comment]
With the latest code, modules can now:

* provide translations
* replace views
* add CSS and JS.

That should be everything you need for a theme.

If you have any questions or problems, please open a new issue for them.
