### ISSUE TITLE
2.0 - vertical line are incorrect on several charts

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2323]
The vertical lines used in the chart displays assumes a box height of 85px.  However, the use of 
box-sizing: border-box; distorts the dislayed box height which results in vertical lines being incorrect.
Suggest the use of content-box in replace of border-box.

![image](https://user-images.githubusercontent.com/5147603/54088111-79e6fa00-4317-11e9-82ce-719dd70b1804.png)

**Comment by fisharebest** [comment]
I have updated the family book chart to use the new "css border" lines.

Still outstanding are the hourglass chart and the booklet views of the ancestors and descendants charts.

**Comment by fisharebest** [comment]
Hourglass should now be OK.

**Comment by makitso** [comment]
Looks wonderful.  Don't forget the Booklet views for Ancestor and Descendants :-)

**Comment by makitso** [comment]
You know I am a cosmetics guy so I am picky :-)  The links to the blocks are positioned a bit low due to the use of the  <div>&nbsp;</div> at line 38 in children.phtml.  Any chance of removing it?
With:
![image](https://user-images.githubusercontent.com/5147603/56432958-28218000-6284-11e9-8d0a-0bf57097861a.png)

Without:
![image](https://user-images.githubusercontent.com/5147603/56432977-3b345000-6284-11e9-95d6-c07f0ca51824.png)

**Comment by fisharebest** [comment]
The space should only be there when there are spouses.
Otherwise you get a continuous block of children/spouses.

I've moved the space inside the `if`, where it should be.

I'll admit it is a bit hacky (and the spacing it too much), but I am keen to get the rest of the charts converted.

I can review the details later.

**Comment by makitso** [comment]
That's better.  You know, I never noticed it before, Show spouses on the Family book chart only is only for the root person whereas on Hourglass chart it shows spouses for root and descendants.

**Comment by fisharebest** [comment]
All the old chart line code as been replaced
