### ISSUE TITLE
2.0.0-alpha.5 Control panel - clean up data folder results in ...

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2326]
Illuminate\Contracts\Container\BindingResolutionException: Target [League\Flysystem\AdapterInterface] is not instantiable while building [League\Flysystem\Filesystem]. in file /vendor\illuminate\container\Container.php on line 962
Stack trace:
  1. Illuminate\Contracts\Container\BindingResolutionException->() /vendor\illuminate\container\Container.php:962
  2. Illuminate\Container\Container->notInstantiable() /vendor\illuminate\container\Container.php:800
  3. Illuminate\Container\Container->build() /vendor\illuminate\container\Container.php:671
  4. Illuminate\Container\Container->resolve() /vendor\illuminate\container\Container.php:619
  5. Illuminate\Container\Container->make() /vendor\illuminate\container\Container.php:929
  6. Illuminate\Container\Container->resolveClass() /vendor\illuminate\container\Container.php:857
  7. Illuminate\Container\Container->resolveDependencies() /vendor\illuminate\container\Container.php:822
  8. Illuminate\Container\Container->build() /vendor\illuminate\container\Container.php:671
  9. Illuminate\Container\Container->resolve() /vendor\illuminate\container\Container.php:619
 10. Illuminate\Container\Container->make() /app\Application.php:59
 11. Fisharebest\Webtrees\Application->Fisharebest\Webtrees\{closure}() [internal]:0
 12. array_map() /app\Application.php:67
 13. Fisharebest\Webtrees\Application->makeParameters() /app\Application.php:43
 14. Fisharebest\Webtrees\Application->dispatch() /index.php:153
 15. {closure}() /app\Module\HitCountFooterModule.php:185
 16. Fisharebest\Webtrees\Module\HitCountFooterModule->handle() /index.php:139
 17. {closure}() /app\Http\Middleware\Housekeeping.php:75
 18. Fisharebest\Webtrees\Http\Middleware\Housekeeping->handle() /index.php:139
 19. {closure}() /app\Http\Middleware\DebugBarData.php:41
 20. Fisharebest\Webtrees\Http\Middleware\DebugBarData->handle() /index.php:139
 21. {closure}() /app\Http\Middleware\BootModules.php:59
 22. Fisharebest\Webtrees\Http\Middleware\BootModules->handle() /index.php:139
 23. {closure}() /app\Http\Middleware\UseTheme.php:71
 24. Fisharebest\Webtrees\Http\Middleware\UseTheme->handle() /index.php:139
 25. {closure}() /app\Http\Middleware\UseLocale.php:52
 26. Fisharebest\Webtrees\Http\Middleware\UseLocale->handle() /index.php:139
 27. {closure}() /app\Http\Middleware\UseTree.php:58
 28. Fisharebest\Webtrees\Http\Middleware\UseTree->handle() /index.php:139
 29. {closure}() /app\Http\Middleware\UseSession.php:59
 30. Fisharebest\Webtrees\Http\Middleware\UseSession->handle() /index.php:139
 31. {closure}() /app\Http\Middleware\UseFilesystem.php:50
 32. Fisharebest\Webtrees\Http\Middleware\UseFilesystem->handle() /index.php:139
 33. {closure}() /app\Http\Middleware\CheckForMaintenanceMode.php:48
 34. Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->handle() /index.php:139
 35. {closure}() /index.php:156

**Comment by augur11** [comment]
Seeing the exact same behavior.
