### ISSUE TITLE
2.0.0-alpha.5 Pedigree report

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2333]
On both HTML and PDF formats, when a person has sufficient data, the contents overlay that of the person immediately below. In the image below see persons 8 & 9
![demo](https://user-images.githubusercontent.com/104515/54473530-e60ea580-47d0-11e9-83de-d95de9975e6f.jpg)

**Comment by fisharebest** [comment]
The report framework does not allow you to truncate text to a box.
You can only truncate to a number of characters.

If your text contains lots of wide characters such as W then you may still see the problem occaisionally.

**Comment by ddrury** [comment]
Looks like a bit of css needs tweaking now
![demo](https://user-images.githubusercontent.com/104515/54488064-0ef86e80-4895-11e9-8814-123a24a48b2b.jpg)

**Comment by fisharebest** [comment]
Dang - I added borders to the boxes to help with debugging...

I've been looking at them for so long that I forgot they were there!
