### ISSUE TITLE
Can't hide media objects with v2.0.0-alpha5

### ISSUE THREAD

**Issue by Gustine** [fisharebest/webtrees#2337]
I've set privacy restrictions for media objets to « Show to members »  (Control panel > Family tree > Privacy).
However, the thumbnails are visible as well as some (cached ?) images ; others are processing, processing, processing.

**Comment by fisharebest** [comment]
The code was setting the `xref` and `tag_type` columns to empty strings (not nulls).

I have fixed the code, but you will still have the errors in your database.

You will need to delete this rule and add it again.

**Comment by Gustine** [comment]
It works. Thanks.
