### ISSUE TITLE
Text on text in Find unrelated individuals - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2341]
Control panel -> Manage family trees -> Find unrelated individuals in the test system - texts print on texts

![image](https://user-images.githubusercontent.com/5202996/54497041-a8a83600-48fe-11e9-927f-89a08ea6f57c.png)

**Comment by fisharebest** [comment]
I do not see this.

Do you see it on all trees?
Do you see it on all browsers?

**Comment by xmlf** [comment]
Yes！
There is this problem.
I am chrome 72.
![捕获](https://user-images.githubusercontent.com/26761596/54515580-70086b00-4997-11e9-9ba2-054b931d8bb4.JPG)

**Comment by melizaa** [comment]
I have the issue in chrome and avast in both test systems for all the familytrees.
IE, FF and Edge are OK.

**Comment by fisharebest** [comment]
I don't see this on

* Chrome 72
* Chrome 74
* Firefox 67

I tried, English, Hebrew and Chinese.

**Comment by melizaa** [comment]
I see the overlapping texts in Chrome 72 - 64 bit and in avast 72.0.1174.122 - 32 bit.
I do not see the overlapping texts in Chrome 73 - 64 bit.

**Comment by melizaa** [comment]
I see texts too close in windows opera browser version 58.0.3135.107

**Comment by melizaa** [comment]
I do not manage to reach my server using Edge for Windows.

**Comment by fisharebest** [comment]
Chrome is now up to 74.  Do people still see the problem?

**Comment by melizaa** [comment]
My Opera version is 60, my Chrome is 73 and my Avast is 73.
I do not see the issue in these browsers.
