### ISSUE TITLE
The font of "Add a favorite" in the block is odd. 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2342]
The "Add a favorite" font in the block is odd. It is even odder on the Hebrew page.
![2019-03-18_14-11-56](https://user-images.githubusercontent.com/5202996/54529348-527fd500-4988-11e9-858f-6afa0825aa8f.jpg)
![2019-03-18_14-11-17](https://user-images.githubusercontent.com/5202996/54529368-61668780-4988-11e9-9c3d-cbb151a76995.jpg)

The Journal news article addition text font looks good.
![2019-03-18_13-46-36](https://user-images.githubusercontent.com/5202996/54529324-485dd680-4988-11e9-9996-964d7279c16e.jpg)

**Comment by melizaa** [comment]
I would not print the link text in bold and I would use the same Calibri font on the Hebrew page as on the English page.

**Comment by fisharebest** [comment]
I'm not seeing this.  There is no font specified.

However, the font-weight was set to "extra-bold", and this may just be the way your browser renders extra-bold.

I've removed the bold text.  Can you check again?  Thanks.

**Comment by melizaa** [comment]
Now the text is not printed with the same colour/text size as for instance the favorites block link text.
