### ISSUE TITLE
Descendants Individual and Family lists show the same individual or family more than once - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2346]
Descendants Individual and Family lists show the same individual or family more than once, if the two individuals are related through more than one path 

My big file.
The Descendants list of 6 generations of I1418.
We see for instance I1162, I6263 and F411 twice (dead)
We see I6360 4 times and F389 4 times. (alive)

**Comment by fisharebest** [comment]
This was fixed in 9bbda1e6be2ef66109d81aba7b0e242a0f110846
