### ISSUE TITLE
tests/coverage commited

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#2353]
It seems like you accidentally committed the test coverage files?

**Comment by fisharebest** [comment]
Dang :-(

That's a lot of data to add to the repository.

I know it is "bad practice" to rewrite GIT history.  But I could easily remove that commit and force-push.

It shouldn't (!) cause any conflicts, as I doubt anyone would have edited those files...

**Comment by fisharebest** [comment]
I've removed those files from the commit, and force-pushed.

Apologies if this causes anyone extra effort merging their branches.
