### ISSUE TITLE
2.0.0-alpha.5 lifespan chart

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2357]
Overlapping individuals, see below
![demo](https://user-images.githubusercontent.com/104515/55066571-fbf45400-5075-11e9-8b33-118b94407076.jpg)

**Comment by fisharebest** [comment]
I can't reproduce this.

Any other info that might be relevant?

**Comment by ddrury** [comment]
Image shows 1.7 chart (the red 'dot' to the left of Henry Drury the elder is Margery)

Only other thing is that neither have Birth/Baptism info, only burial dates

![demo](https://user-images.githubusercontent.com/104515/55143788-60c3b300-5137-11e9-855f-e62c01bbe940.jpg)

**Comment by ddrury** [comment]
I seem to remember that I rewrote a lot of the 1.7 code (gulp) and I *think*  that where only a death date was present I calculated a birth based of the "assumed life span" option (probably not worded that correctly)
but why Margery ends up as a dot I don't know off hand

**Comment by ddrury** [comment]
In v2 the div element of the bar for Margery has a negative width (which being invalid is ignored)

**Comment by fisharebest** [comment]
Even with the clippings.ged that you sent me, I still cannot reproduce this.

The Margery in your file died in 1624.  The one in the screenshot was born in 1626

**Comment by ddrury** [comment]
I'm a bit tied up at the moment - I'll have another look as soon as I 
can

Regards David

------ Original Message ------

**Comment by ddrury** [comment]
Well!
There are two problems.
First my data. Margery's father (Edmund)  would have been 12 when she died.
Second, given that unlikely event, In this instance (no mother or husband recorded) )Individual->getEstimatedBirthDate can only use Edmund's birth date in the calculation and that returns a date two years after Margery's death!

**Comment by fisharebest** [comment]
Thanks - I can reproduce the problem by creating an individual with a death date before the birth date.

Not sure the best way to handle this.

I'll just set the death year to be the same as the birth year...
