### ISSUE TITLE
2.0.0-alpha.5 slideshow block text alignment

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2365]
Links should be left aligned (see red block in attached)

![demo](https://user-images.githubusercontent.com/104515/55614985-32248880-5786-11e9-99af-67d55afd1d61.jpg)

**Comment by fisharebest** [comment]
Given the lack of space, I think I'll remove the "Record type" (e.g. "Individual", "Family", etc.) as well.
