### ISSUE TITLE
Using keywords in HTML, date display problem

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2367]
When I use the keyword tag to call the data. E.g
#firstDeathYear#
The result in English is: **2017**
In the Chinese state, the display is: **2017年 月 日**. It’s wrong to have more 

> 年 月 日

 in the back.

**Comment by fisharebest** [comment]
Which is correct: `2017年` or `2017`

**Comment by xmlf** [comment]
> Which is correct: `2017年` or `2017`

2017 is correct.
Displayed in English，it's correct!
![en](https://user-images.githubusercontent.com/26761596/56260981-df46bb80-610b-11e9-81d3-fb43b1f7e12e.JPG)

Displayed in Chinese,there are more '年 月 日' behind, which is wrong.
![chinese](https://user-images.githubusercontent.com/26761596/56260975-dc4bcb00-610b-11e9-9dec-64df58eb315e.JPG)
