### ISSUE TITLE
Replace symfony httpfoundation with psr-7 and psr-15

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#2368]
Currently we use [Symfony HttpFoundation](https://github.com/symfony/http-foundation) for our request and response objects.

We should convert to [PSR-7](https://www.php-fig.org/psr/psr-7/) requests and responses, and [PSR-15](https://www.php-fig.org/psr/psr-15/) middleware

We would then be compatible with almost every other major framework.

The [symfony psr7 bridge](https://github.com/symfony/psr-http-message-bridge) means that we would still be compatible with symfony-based systems such as laravel.

**Comment by fisharebest** [comment]
All the "heavy-lifting" is done, in the `develop` branch.

A little more testing required before merging.

**Comment by magicsunday** [comment]
Theme switching fails now.

**Comment by fisharebest** [comment]
I see it.  The `route` parameter needs to be part of the URL.  This is to support routing (a.k.a. pretty URLs).

The "change language" and "change theme" requests are sending this parameter as a `POST` variable.  There might be some other instances of this...
