### ISSUE TITLE
After upgrading to webtrees 2, the old website links are still accessible.

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2369]
I have switched from phpgedview to webtrees 2. The URL structure of webtrees and phpgedview is different.
I checked that the default setting for webtrees is that it can still be accessed using the old URL of phpgedview.
This can result in a lot of duplicate content appearing on two different URLs. This is very unfriendly to search engines.

**Comment by xmlf** [comment]
I think this problem also exists from webtrees 1 update to webtrees 2.

**Comment by fisharebest** [comment]
Needs to wait for #2368
