### ISSUE TITLE
Smtp sendmail error fix

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2370]
When the SMTP parameters are configured in the control panel, it is not possible to successfully send mail.
I tested two mail providers and prompted the error as follows:
Yandex:
> Mail: Expected response code 250 but got code "553", with message "553 5.7.1 Sender address rejected: not owned by auth user. "

Tencent:
> Mail: Expected response code 250 but got code "501", with message "501 mail from address must be same as authorization user "

And, there are many such mistakes on the Internet. The cause of this error is that the send from address must be the same as the smtp authentication user address.
The solution is:
https://github.com/fisharebest/webtrees/blob/4f194b97d4dda944b41f9edd5e8f7da11656c545/app/Mail.php#L54
change:
`$from->email()`
to
`Site::getPreference('SMTP_AUTH_USER')
`

**Comment by wkitty42** [comment]
On 4/7/19 12:03 AM, xmlf wrote:
> And, there are many such mistakes on the Internet. The cause of this error is 
> that the send from address must be the same as the smtp authentication user address.
> The solution is:
> https://github.com/fisharebest/webtrees/blob/8b04670a78742b3f7e8852b5533a6c5e1d47dd73/app/Mail.php#L59
> change:
> |$from->email()|
> to
> |SMTP_AUTH_USER|

while that may work for you, it does/will not work for everyone... in our case, 
once we're authed, i can send mail from any name/email address we choose... our 
provider does not restrict us from forwarding or relaying email for others...

it was problems like this that lead me to add the more advanced email capability 
to phpGedView years back... that after that project would not accept the basic 
email capabilities offered by using the email code from phpBB forums which i 
originally offered...

IF this is changed, it should be an additional option in the settings... not 
something hard coded as you present...

**Comment by xmlf** [comment]
As far as I know, many large service providers are currently making such restrictions.Ex:zoho,yandex
It is to prevent abuse.
Yes, it can be used as an option, preferably as a default option.

**Comment by fisharebest** [comment]
> change:
> $from->email()
> to
> Site::getPreference('SMTP_AUTH_USER') 

> Yes, it can be used as an option, preferably as a default option.

It is already an option!  See the family tree preferences.

<img width="723" alt="Screen Shot 2019-04-07 at 16 51 35" src="https://user-images.githubusercontent.com/2306088/55686143-7b770280-5955-11e9-8e75-524fdc8a4d30.png">

You can find the code here: https://github.com/fisharebest/webtrees/blob/master/app/TreeUser.php#L59

-------

Mail sent from the site already uses the `SMTP_AUTH_USER` setting.
See https://github.com/fisharebest/webtrees/blob/master/app/SiteUser.php#L44

**Comment by xmlf** [comment]
It‘s great!
