### ISSUE TITLE
Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Psr\Http\Message\ServerRequestInterface] is not instantiable

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#2375]
I'm trying to update my modules to use the new PSR-7 and PSR-15 request/response structure.

How to I now get the current request object in method boot() or __construct? It fails now with:

Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Psr\Http\Message\ServerRequestInterface] is not instantiable. in /vendor/illuminate/container/Container.php on line 962

    ```
/**
     * Bootstrap.
     *
     * @param Config $config
     * @param ModuleThemeInterface $theme
     * @param ServerRequestInterface $request
     */
    public function boot(Config $config, ModuleThemeInterface $theme, ServerRequestInterface $request): void
    {
        $this->config = $config;
        $this->theme  = $theme;

        // Here is also a good place to register any views (templates) used by the module.
        // This command allows the module to use: view($this->name() . '::', 'fish')
        // to access the file ./resources/views/fish.phtml
        View::registerNamespace($this->name(), $this->resourcesFolder() . 'views/');
    }
```

**Comment by fisharebest** [comment]
> How to I now get the current request object in method boot() or __construct?

Definitely not in `__construct()` - we create the modules before we create the request.

Probably not `boot()` - although the request exists, it can still be modified by other middleware/modules, and you might have an out-of-date version.

Once we start processing the request (e.g. via a controller-action), the final version of the request is available, and it is stored in the "dependency-injection container".  You can then get it using:

`$request = app(ServerReqeustInterface::class);`

In what sort of module do you need it?  It might be better if we add the request to other parts of the module API.

**Comment by fisharebest** [comment]
Update: with the middleware system, I am no longer certain that `boot()` is helpful or useful.  I need to review this.

**Comment by magicsunday** [comment]
I need the request to access the form values submitted by the user.

**Comment by fisharebest** [comment]
If you are processing a form-submission, then I guess your module is using

* `function getMyFormAction()` to display the form
* `function postMyFormAction()` to process the results

You can typehint any object types for this functions.  e.g.

```
public function postMyFormAction(ServerRequestInterface $request): ResponseInterface {
    /* do something with */ $request->getParsedBody();
    return redirect(/* URL */);
}
```

**Comment by magicsunday** [comment]
Is there a method that is called before the get/post Actions are called which contains the complete/final request?

**Comment by fisharebest** [comment]
> Is there a method that is called before the get/post Actions

No.

Another middleware could do something like convert all XREF parameters to upper case.

> I dont want to instantiate the Config class in each Action method of my module

To avoid repetition?
To avoid overhead?

Perhaps use lazy evaluation in your config class?

```
$config = $this->myConfigObject->mergeDefaultsWithReqeust($request);
```

**Comment by fisharebest** [comment]
Aha.

Your config class could have a dependency on the request.

```
class Config {
    __construct(ServerRequestInterface $request) {}
}
```

Your action could have a dependency of the Config object (and optionally the request).

```
    public function getSomeAction(ServerRequestInterface, Config $config) {
        $config->.....
    }
```

Now, your config object will be constructed from the request object when your action is called.

**Comment by magicsunday** [comment]
This does not work, as I extend the FanChartModule, I have to use the getChartAction method.
