### ISSUE TITLE
Entering Nickname results in 2 Nickname entries

### ISSUE THREAD

**Issue by sleebooth** [fisharebest/webtrees#2382]
Edit the Name
Insert Nickname
Save

results in 2 Nickname entries - one (NICK) before the surname, one (NICK) after the Surname

**Comment by fisharebest** [comment]
Which version of webtrees?

**Comment by fisharebest** [comment]
I can't reproduce this behaviour.  Can you give the exact steps to reproduce it?  Thanks!

**Comment by fisharebest** [comment]
If you can reproduce this problem in the latest code, please open another issue for it.
