### ISSUE TITLE
Can't Login behind Reverse Proxy

### ISSUE THREAD

**Issue by begleysm** [fisharebest/webtrees#2383]
I've got webtrees setup on a LXC container.  I'm able to fully access the site and login when I go to http://ctwebtrees/webtrees (direct access from my LAN).

I've got a Reverse Proxy setup on an Apache server so that when I got to https://steamforge.net/webtrees it points to the local http://ctwebtrees/webtrees.

/etc/apache2/sites-enabled/000-default-ssl.conf (on the reverse proxy machine) has this section for webtrees
```#webtrees
                <Location /webtrees>
                        ProxyPreserveHost On
                        ProxyPass http://ctwebtrees/webtrees
                        ProxyPassReverse http://ctwebtrees/webtrees
                </Location>
```
which came from here: https://wiki.webtrees.net/en/Apache_Configuration

I've got various Reverse Proxy functions working for a number of other services setup in a similar way so I know the general concept is working.

I appear to have full functionality/control of the webtrees site (from the external address) except I can't login.

When I go to the login page, type in my username and password, and hit "sign in" it just reloads the login page as if nothing ever happened.

As an aside Firefox gives me a little warning on the password field telling me that the connection is not secure which is odd (wrong?) because the data is all being transferred to steamforge.net over a valid HTTPS connection.  This makes me wonder if the "sign in" function is trying to send the data to the wrong address or is not using HTTPS.

Perhaps it is related to #2166?  I tried the "auto_prepend_file" fix (on the ctwebtrees' config, not the reverse proxy) from #2166 but it caused me to get a blank screen for both http://ctwebtrees/webtrees and https://steamforge.net/webtrees.  I think this is because ctwebtrees SHOULD be delivering content as HTTP, not HTTPS.  I tried it on the Reverse Proxy server's config and nothing seemed to change.

Looks like I might be in the same boat as the guy from #328.  That's a pretty old issue.  Any changes in how to address the problem since then?  @wkitty42 are you still using webtrees behind an apache2 reverse proxy?  If so, how are you dealing with this now?  Btw, I'm find with only being able to log in over the WAN if that's what it takes.

**Comment by fisharebest** [comment]
webtrees is failing to detect the request URL.  It does this from the information provided in the `$_SERVER` parameters.

It would be helpful if you could create a `phpinfo()` page and post the contents of `$_SERVER` section.

Also - which version of webtrees?

**Comment by begleysm** [comment]
I'm running the latest stable version from the release section which is 1.7.13.

Here is the PHP Variables section of the webtrees container's server.
```
$_SERVER['HTTP_HOST'] | ctwebtrees
$_SERVER['HTTP_USER_AGENT'] | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
$_SERVER['HTTP_ACCEPT'] | text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
$_SERVER['HTTP_ACCEPT_LANGUAGE'] | en-US,en;q=0.5
$_SERVER['HTTP_ACCEPT_ENCODING'] | gzip, deflate
$_SERVER['HTTP_CONNECTION'] | keep-alive
$_SERVER['HTTP_UPGRADE_INSECURE_REQUESTS'] | 1
$_SERVER['PATH'] | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$_SERVER['SERVER_SIGNATURE'] | <address>Apache/2.4.25 (Debian) Server at ctwebtrees Port 80</address>
$_SERVER['SERVER_SOFTWARE'] | Apache/2.4.25 (Debian)
$_SERVER['SERVER_NAME'] | ctwebtrees
$_SERVER['SERVER_ADDR'] | 172.27.2.119
$_SERVER['SERVER_PORT'] | 80
$_SERVER['REMOTE_ADDR'] | 172.27.2.100
$_SERVER['DOCUMENT_ROOT'] | /var/www/html
$_SERVER['REQUEST_SCHEME'] | http
$_SERVER['CONTEXT_PREFIX'] | no value
$_SERVER['CONTEXT_DOCUMENT_ROOT'] | /var/www/html
$_SERVER['SERVER_ADMIN'] | webmaster@localhost
$_SERVER['SCRIPT_FILENAME'] | /var/www/html/info.php
$_SERVER['REMOTE_PORT'] | 46050
$_SERVER['GATEWAY_INTERFACE'] | CGI/1.1
$_SERVER['SERVER_PROTOCOL'] | HTTP/1.1
$_SERVER['REQUEST_METHOD'] | GET
$_SERVER['QUERY_STRING'] | no value
$_SERVER['REQUEST_URI'] | /info.php
$_SERVER['SCRIPT_NAME'] | /info.php
$_SERVER['PHP_SELF'] | /info.php
$_SERVER['REQUEST_TIME_FLOAT'] | 1555276093.426
$_SERVER['REQUEST_TIME'] | 1555276093
```
And here is the PHP Variables section of the reverse proxy server
```
$_COOKIE['steamwikiUserName'] | Sean
$_COOKIE['_pk_id_1_76b5'] | 445d9c67f406a1f1.1553302444.7.1555208280.1555208276.
$_COOKIE['_pk_id_2_76b5'] | a03e889fc99ee904.1553431604.1.1553431604.1553431604.
$_SERVER['SCRIPT_URL'] | /info.php
$_SERVER['SCRIPT_URI'] | https://steamforge.net/info.php
$_SERVER['HTTPS'] | on
$_SERVER['SSL_TLS_SNI'] | steamforge.net
$_SERVER['SSL_SERVER_S_DN_CN'] | steamforge.net
$_SERVER['SSL_SERVER_I_DN_C'] | US
$_SERVER['SSL_SERVER_I_DN_O'] | Let's Encrypt
$_SERVER['SSL_SERVER_I_DN_CN'] | Let's Encrypt Authority X3
$_SERVER['SSL_SERVER_SAN_DNS_0'] | steamforge.net
$_SERVER['SSL_SERVER_SAN_DNS_1'] | www.steamforge.net
$_SERVER['SSL_VERSION_INTERFACE'] | mod_ssl/2.4.25
$_SERVER['SSL_VERSION_LIBRARY'] | OpenSSL/1.0.2l
$_SERVER['SSL_PROTOCOL'] | TLSv1.2
$_SERVER['SSL_SECURE_RENEG'] | true
$_SERVER['SSL_COMPRESS_METHOD'] | NULL
$_SERVER['SSL_CIPHER'] | ECDHE-RSA-AES128-GCM-SHA256
$_SERVER['SSL_CIPHER_EXPORT'] | false
$_SERVER['SSL_CIPHER_USEKEYSIZE'] | 128
$_SERVER['SSL_CIPHER_ALGKEYSIZE'] | 128
$_SERVER['SSL_CLIENT_VERIFY'] | NONE
$_SERVER['SSL_SERVER_M_VERSION'] | 3
$_SERVER['SSL_SERVER_M_SERIAL'] | 04662DDB535C4886ED754EE3D2B5820C2561
$_SERVER['SSL_SERVER_V_START'] | Mar 24 11:37:22 2019 GMT
$_SERVER['SSL_SERVER_V_END'] | Jun 22 11:37:22 2019 GMT
$_SERVER['SSL_SERVER_S_DN'] | CN=steamforge.net
$_SERVER['SSL_SERVER_I_DN'] | CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
$_SERVER['SSL_SERVER_A_KEY'] | rsaEncryption
$_SERVER['SSL_SERVER_A_SIG'] | sha256WithRSAEncryption
$_SERVER['SSL_SESSION_RESUMED'] | Initial
$_SERVER['HTTP_HOST'] | steamforge.net
$_SERVER['HTTP_USER_AGENT'] | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
$_SERVER['HTTP_ACCEPT'] | text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
$_SERVER['HTTP_ACCEPT_LANGUAGE'] | en-US,en;q=0.5
$_SERVER['HTTP_ACCEPT_ENCODING'] | gzip, deflate, br
$_SERVER['HTTP_CONNECTION'] | keep-alive
$_SERVER['HTTP_COOKIE'] | steamwikiUserName=Sean;  _pk_id.1.76b5=445d9c67f406a1f1.1553302444.7.1555208280.1555208276.;  _pk_id.2.76b5=a03e889fc99ee904.1553431604.1.1553431604.1553431604.
$_SERVER['HTTP_UPGRADE_INSECURE_REQUESTS'] | 1
$_SERVER['PATH'] | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$_SERVER['SERVER_SIGNATURE'] | <address>Apache/2.4.25 (Debian) Server at steamforge.net Port 443</address>
$_SERVER['SERVER_SOFTWARE'] | Apache/2.4.25 (Debian)
$_SERVER['SERVER_NAME'] | steamforge.net
$_SERVER['SERVER_ADDR'] | 172.27.2.108
$_SERVER['SERVER_PORT'] | 443
$_SERVER['REMOTE_ADDR'] | 47.24.192.249
$_SERVER['DOCUMENT_ROOT'] | /var/www/html
$_SERVER['REQUEST_SCHEME'] | https
$_SERVER['CONTEXT_PREFIX'] | no value
$_SERVER['CONTEXT_DOCUMENT_ROOT'] | /var/www/html
$_SERVER['SERVER_ADMIN'] | steamforge.net@gmail.com
$_SERVER['SCRIPT_FILENAME'] | /var/www/html/info.php
$_SERVER['REMOTE_PORT'] | 37904
$_SERVER['GATEWAY_INTERFACE'] | CGI/1.1
$_SERVER['SERVER_PROTOCOL'] | HTTP/1.1
$_SERVER['REQUEST_METHOD'] | GET
$_SERVER['QUERY_STRING'] | no value
$_SERVER['REQUEST_URI'] | /info.php
$_SERVER['SCRIPT_NAME'] | /info.php
$_SERVER['PHP_SELF'] | /info.php
$_SERVER['REQUEST_TIME_FLOAT'] | 1555276297.005
$_SERVER['REQUEST_TIME'] | 1555276297
```

**Comment by fisharebest** [comment]
webtrees needs to generate absolute URLs.

It only has the information in these variables.

The general solution is to (a) configure the proxy to set headers `X-Forwarded-For`, `X-Forwarded-Port`, etc. and then (b) configure webtrees to use/trust these headers.

While code for (b) exists (in the symfony http/foundation library), it is not exposed in webtrees.  In general, one should not trust these headers, as they could be set maliciously by a client.  Each site needs to confirm that the headers were set by a trusted proxy.

Furthermore, in 2.0.0, the code is being rewritten, and we'll probably pick up the external URL from an environment variable or similar.

The quick and dirty solution is to edit this line, and hard-code your external URL.
https://github.com/fisharebest/webtrees/blob/1.7.13/includes/session.php#L173

**Comment by begleysm** [comment]
Thanks!  Hopefully this will be a cleaner solution come 2.0.0 but until then I'd like to implement your suggestion.

I'm maybe not getting the syntax or content quite right.

Original
`define('WT_BASE_URL', $base_uri);`

I've tried the following and always get a blank white return
`define('WT_BASE_URL', 'https://steamforge.net/webtrees/');`
`define('WT_BASE_URL', 'https://steamforge.net/webtrees');`
`define('WT_BASE_URL', 'https://steamforge.net/');`
`define('WT_BASE_URL', 'https://steamforge.net');`

Can you point me toward the correct syntax/content?

**Comment by fisharebest** [comment]
> I've tried the following and always get a blank white return

Blank page probably means (a) fatal error and (b) your server is configured with `display_errors=0`

Can you find the error?  Perhaps in your apache logs?

**Comment by begleysm** [comment]
Ya I had mistake in my syntax.

I had written (extra semicolon after WT_BASE_URL
`define('WT_BASE_URL;', 'https://steamforge.net/webtrees/');`

After getting rid of that it worked! Thanks!

For those following along (or more likely finding this thread in the future) the final fix was to modify line 173 of /var/www/html/webtrees/include/sessions.php to look like this
`define('WT_BASE_URL', 'https://steamforge.net/webtrees/');`

Thanks @fisharebest.  I'll be looking forward to checking out release 2.0.0.

**Comment by begleysm** [comment]
In case it helps anyone browsing this topic, I've written a step by step guide on settings up webtrees on Debian 9 in an LXC Container under Proxmox and using a Reverse Proxy to make it accessible over the web.

The specific instructions on making the necessary modification to the pre 2.0.0 software can be found here: https://steamforge.net/wiki/index.php/How_to_setup_a_webtrees_server_on_a_Debian_9_Proxmox_container#Setup_the_Reverse_Proxy
