### ISSUE TITLE
Browse button lockups up Firefox when behind Reverse Proxy

### ISSUE THREAD

**Issue by begleysm** [fisharebest/webtrees#2384]
I have my webtrees (v1.7.13) server behind a Reverse Proxy.  As per #2383 I have modified https://github.com/fisharebest/webtrees/blob/1.7.13/includes/session.php#L173 to look like
`define('WT_BASE_URL', 'https://steamforge.net/webtrees/');`

When I am VPN'd into my local network (and I assume when I'm physically located on my local network) where the webtrees server is I can successfully import a GEDCOM file by going to Control Panel -> Family trees -> Manage family trees -> GEDCOM file -> Import and clicking on the "Browse..." button (when "A file on your computer" is selected.  I'm using Firefox 66.0.2 on Linux Mint 18.3.
![browse](https://user-images.githubusercontent.com/1275999/56102379-c1563c80-5efa-11e9-8c84-b828634d33fc.png)

However when I perform the same action externally (not being on the local network / VPN) Firefox locks up after hitting the "Browse..." button.

Since Importing GEDCOM files isn't something I have to do frequently this isn't a huge impediment but I wonder if the root cause has other impacts that are more impactful.

**Comment by fisharebest** [comment]
It is difficult to imagine how anything on the server could cause the browser to hang like this?

It *smells* like the browser it trying (and failing) to access a network drive.

Can you try other browsers and other computers?

**Comment by begleysm** [comment]
I'm on vacation right now but I'll experiment a bit and see if I can narrow it down.

**Comment by begleysm** [comment]
You're absolutely right.  Red Herring.  Nothing to do with webtrees.  I had a problem with a local network drive that was mapped while on the VPN not being accessible while off the VPN.  Thank you for the lead.
