### ISSUE TITLE
Family Trees menu is blank (with 2 trees)

### ISSUE THREAD

**Issue by begleysm** [fisharebest/webtrees#2385]
The demo site for webtrees contains two family trees and when the "Family tree" button is moused-over both trees are shown and are clickable.
![right](https://user-images.githubusercontent.com/1275999/56102721-c4522c80-5efc-11e9-9fd5-a01f64af6325.png)

On my installation of webtrees (v1.7.13) no family trees are shown when the "Family tree" button is moused-over.  As a result, the only way I can change family trees that I'm looking at is to modify the URL in the browser.
![wrong](https://user-images.githubusercontent.com/1275999/56102748-05e2d780-5efd-11e9-9fe6-e0ceeffd433b.png)

**Comment by fisharebest** [comment]
There is a configuration setting "allow users to change family trees" (or similar).

If you disabled this option, then the menu would be empty.

**Comment by begleysm** [comment]
Thank you.  Now that you mention it, I remember setting that to "no" during initial setup (never expecting to have more than 1 family tree).  Then almost right away I found out about another GEDCOM worth importing and all of a sudden had two.

Thanks!
