### ISSUE TITLE
Github - visitor sees add and reorder children on Family page

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2386]
![image](https://user-images.githubusercontent.com/5147603/56142837-330ea480-5f54-11e9-9184-b0009a105178.png)

**Comment by fisharebest** [comment]
... and presumably "add father/mother" as well...

**Comment by makitso** [comment]
Perhaps I was not clear, visitors who are not logged in see this.

**Comment by fisharebest** [comment]
Perhaps I was not clear also ;-)

There are some new links on this page - to add missing parents and grandparents.

Visitors will also (wrongly) see these.

A fix is incoming....
