### ISSUE TITLE
Inconsistent values used for chart box calculations

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2387]
Currently, chart box dimension are defined in each of the theme.php files as:
         'chart-box-x'                    => 260,
         'chart-box-y'                    => 85,

These values are used in FamilyBookChartModule.php and HourglassChartModule.php controllers
for horizontal and vertical line position calculation.  

In files _chart-family-book.css and _chart-hourglass.css 
	.wt-chart-box width is set to 20rem; [320px]
In each of the individual theme .css files 
	.wt-chart-box height is set to 5 rem [80px]
These values are used for chart box view display sizes.

This inconsistency in box dimensions results in horizontal and vertical line 
display problems in Family book chart.  The problem also exists in Hourglass chart 
but is corrected with javascript.

This is somewhat of a duplicate of issue #2323.

**Comment by fisharebest** [comment]
Family book chart now uses the new method for drawing lines.

The 'parameters' section of the theme will be removed once the remaining charts are updated.

**Comment by makitso** [comment]
First of all let me say that I am impressed, I thought removing tables and going to css borders would not have worked for the Family book chart.
I am curious about the change you made to each theme, changing the width from 20rem to 15rem.  The Ancestors, Descendants, Hourglass have a width of 20rem whereas Familybook and Pedigree as a rem of 15rem.  Perhaps removing the width from the _chart- *.css files and allowing the theme .css files to define the width?

**Comment by fisharebest** [comment]
> I thought removing tables and going to css borders would not have worked for the Family book chart.

:innocent: -  CSS `flexbox` is your friend ;-)

> I am curious about the change you made to each theme, changing the width from 20rem to 15rem.

I figured that the charts with lots of horizontal relationships would benefit from narrower boxes.

I have no stong views on the exact numbers.

> Perhaps removing the width from the _chart- *.css files and allowing the theme .css files to define the width.

Themes can still set widths.  But they need to do it for each chart.

I like CSS variables.  I will probably put the charts widths/heights into CSS variables.

Maybe have two standard withs - a narrower one for vertical charts (e.g. descendants) and a wider one for horizontal charts (e.g. familybook)?  Then the theme will only need to specify two widths.

**Comment by makitso** [comment]
> Maybe have two standard widths - a narrower one for vertical charts (e.g. descendants) and a wider one for horizontal charts (e.g. familybook?

Either works for me.  Personally, on my public site, I set the 	width: 254px and height: 79px.  But, I also use box-sizing: content-box, gives a bit more consistency.

**Comment by makitso** [comment]
> Personally, on my public site, I set the width: 254px and height: 79px
I think the real issue is that I was too lazy get it to work as border-box.  I have fixed that.
