### ISSUE TITLE
2.0.0-alpha.5 Timeline chart zoom in/out

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2388]
when clicking on the zoom in/out icons, the result is not always what is expected. ie sometimes zoom in when zoom out is clicked or visa versa but can't determine a pattern

**Comment by fisharebest** [comment]
I have not seen this.

If you can reproduce, can you:

1) check the `scale` parameter in the browser's URL bar.
2) check the `scale` parameter on the link you clicked.  Zoom in should be a bigger number, zoom out should be a smaller number.

Then post the sequence of events, with the history of the `scale` parameter and what you see/click on screen.

**Comment by ddrury** [comment]
The scale parameter does change as you mentioned - although not in linear steps
I misunderstood what the zoom buttons do. I was looking at the line spacing of the years on the chart (not the actual year) and that does change as I mentioned above.

I assumed that by increasing the zoom, events that were (perhaps partially) hidden, would be revealed - this isn't always the case.

See two examples below. Top shows spacing as entered from menu (no scale parameter on URL), bottom shows after zoom in clicked (scale parameter 13)

![demo](https://user-images.githubusercontent.com/104515/56641066-5defab80-666c-11e9-8978-d21ba9e1de09.jpg)

**Comment by fisharebest** [comment]
Zooming changes the scale to allow more/fewer facts to fit on the screen.

Is this still a bug?  If so, what changes do you want?

**Comment by ddrury** [comment]
It's not a chart I normally use myself and don't know how popular it is, but I wouldn't cry into my beer if it was removed, however assuming it is to stay then I would say that having events overlap thus making them potentially unreadable is a bug and should be fixed either by removing them from the chart or shifting their position to make them visible

**Comment by fisharebest** [comment]
> having events overlap thus making them potentially unreadable is a bug and should be fixed either by removing them from the chart or shifting their position to make them visible

I'm not sure that selectively removing events is a good idea.  At present, you can see that they are there - even if they are behind other events.

I can't imagine how to reposition them either.  If we zoom out, such that there is insufficient space for all of them, then repositioning cannot help...

> It's not a chart I normally use myself and don't know how popular it is

Likewise.  So unless a regular user of it has a concrete proposal, it is probably best to leave it as it is.
