### ISSUE TITLE
Unable to choose parental relationship in editing family members

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2394]
When I want to modify family members, I can't choose to adopt, birth.
Must be manually modify gedcom record.
This is very cumbersome.

**Comment by fisharebest** [comment]
You can do this be re-creating the lin.

For example, if X is a child of Y+Z

1) visit the individual page of X, and select the families tab.
2) choose "Link to existing family as a child"
3) select birth/adoption/etc.

This will update the existing relationship.  It will let you change birth to adoptions, etc.

**Comment by xmlf** [comment]
Yes, I know this method.The main reason why I don’t use this method at present is mainly：
1,My family data currently has more than 40,000 people, and each name has a re-name of 50 More. In this way, I am not sure which one is the family I am looking for.
2，When x is already a family member, the relationship is birth, I want to change to adoption,I can't change the relationship between existing family members and parents.

**Comment by fisharebest** [comment]
> 2. When x is already a family member, the relationship is birth, I want to change to adoption,I can't change the relationship

Yes you can.  The method I described above will do this.

**Comment by wkitty42** [comment]
On 4/29/19 3:49 PM, Greg Roach wrote:
>      2. When x is already a family member, the relationship is birth, I want to
>         change to adoption,I can't change the relationship
> 
> Yes you can. The method I described above will do this.

the way i read his #1 bullet is that there are so many to try to pick from in 
the list that it is near impossible to find the right ones to set to adopted... 
i may be misunderstanding the OP, though...

**Comment by xmlf** [comment]
> > 1. When x is already a family member, the relationship is birth, I want to change to adoption,I can't change the relationship
> 
> Yes you can. The method I described above will do this.

Yes, this is ok. But when there are a lot of search results lists, you can't find the right family. I still want to show my parents by default and I can find them by `xref`.

**Comment by xmlf** [comment]
I also found that if it is a single-parent family (only father), this single-parent family cannot be found through  "Link to existing family as a child".
