### ISSUE TITLE
2.0-Unable to open pending changes page

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2398]
Just yesterday, I was dealing with family relationships and deleting some individuals. Then I can't open the pending changes page for approval.
![err](https://user-images.githubusercontent.com/26761596/56950793-e5f01c80-6b68-11e9-885b-db57c2ed4ee8.JPG)

`Undefined offset: 1
#0 …/app/Http/Controllers/PendingChangesController.php(269): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(8, 'Undefined offse...', '/home/wwwroot/j...', 269, Array)
#1 [internal function]: Fisharebest\Webtrees\Http\Controllers\PendingChangesController->showChanges(Object(Fisharebest\Webtrees\Http\Request), Object(Fisharebest\Webtrees\Tree))
#2 …/app/Application.php(45): ReflectionMethod->invoke(Object(Fisharebest\Webtrees\Http\Controllers\PendingChangesController), Object(Fisharebest\Webtrees\Http\Request), Object(Fisharebest\Webtrees\Tree))
#3 …/app/Http/Middleware/RequestRouter.php(68): Fisharebest\Webtrees\Application->dispatch(Object(Fisharebest\Webtrees\Http\Controllers\PendingChangesController), 'showChanges')
#4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestRouter->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#5 …/app/Module/HitCountFooterModule.php(141): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#6 …/app/Http/Middleware/ModuleMiddleware.php(70): Fisharebest\Webtrees\Module\HitCountFooterModule->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#7 …/modules_v4/default-lang/module.php(70): class@anonymous->handle(Object(Fisharebest\Webtrees\Http\Request))
#8 …/app/Http/Middleware/ModuleMiddleware.php(70): class@anonymous->process(Object(Fisharebest\Webtrees\Http\Request), Object(class@anonymous))
#9 …/app/Http/Middleware/ModuleMiddleware.php(75): class@anonymous->handle(Object(Fisharebest\Webtrees\Http\Request))
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ModuleMiddleware->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#11 …/app/Http/Middleware/BootModules.php(58): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#13 …/app/Http/Middleware/UseTransaction.php(44): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#15 …/app/Http/Middleware/CheckCsrf.php(63): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#17 …/app/Http/Middleware/DoHousekeeping.php(76): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#19 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#21 …/app/Http/Middleware/UseLocale.php(51): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLocale->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#23 …/app/Http/Middleware/UseTree.php(59): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTree->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#25 …/app/Http/Middleware/UseSession.php(58): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#27 …/app/Http/Middleware/UseFilesystem.php(49): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseFilesystem->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#29 …/app/Http/Middleware/UseCache.php(44): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#31 …/app/Http/Middleware/UpdateDatabaseSchema.php(56): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#33 …/app/Http/Middleware/UseDebugbar.php(64): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#35 …/app/Http/Middleware/UseDatabase.php(85): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#37 …/app/Http/Middleware/ReadConfigIni.php(62): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#39 …/app/Http/Middleware/CheckForMaintenanceMode.php(49): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#41 …/app/Http/Middleware/HandleExceptions.php(54): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#43 …/app/Http/Middleware/EmitResponse.php(52): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#45 …/app/Http/Middleware/PhpEnvironment.php(46): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#46 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#48 …/index.php(44): Middleland\Dispatcher->dispatch(Object(Fisharebest\Webtrees\Http\Request))
#49 {main}`

**Comment by fisharebest** [comment]
This error message suggests that there is an invalid GEDCOM record on the `wt_change` table.

There are two columns: `old_gedcom` and `new_gedcom`.

Either:

* `old_gedcom` should start `0 @XXX@ YYY` 
* `old_gedcom` should be empty and `new_gedcom` should start `0 @XXX@ YYY`

Can you look for records with `status` = `pending` and the old/new columns are not valid?

**Comment by xmlf** [comment]
Yes! I found old_gedcom is empty and new_gedcom also is empty!

**Comment by fisharebest** [comment]
OK - this row is causing the problem.

You can delete it.

Perhaps it was created by an earlier error?

**Comment by xmlf** [comment]
Yes, I found that two records are Invalid.After the delete, the problem is solved!
