### ISSUE TITLE
webtrees 2.0 beta-1 language files broken

### ISSUE THREAD

**Issue by HelmutL** [fisharebest/webtrees#2399]
wbtrees in German language. I updated from webtrees 2.0.0 alpha-5 to beta-1. Now the language appears to be mixed German and English. The same problem of mixed languages appears when language is set to French ....
![webtrees-beta-1-Window](https://user-images.githubusercontent.com/17042607/56961294-b84ca880-6b53-11e9-9d54-6a3305400277.jpg)
![webtrees-beta-1-Window](https://user-images.githubusercontent.com/17042607/56961311-c6022e00-6b53-11e9-8b73-8a0189ffa7e5.jpg)
![webtrees-beta-1-Window](https://user-images.githubusercontent.com/17042607/56961318-cac6e200-6b53-11e9-9f07-21c0332f4a15.jpg)

**Comment by HelmutL** [comment]
sorry for attaching the same picture three times.

**Comment by xmlf** [comment]
#2397 
it's same.

**Comment by fisharebest** [comment]
The build script missed only included the `.php` and `.xml` files.
It did not include the `.phtml` files.

I have fixed the build script and re-created the `.PO` files.

The updated `.MO` files will be included in the next release.

Until then, please copy the `.MO` files from the alpha.5 release.
