### ISSUE TITLE
2.0beta-Link to existing family as a child will have duplicate records

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2400]
X no parents, I want to link X to existing family as a child
I do this：
1.visit the individual page of X
2.select the families tab.
3.choose "Link to existing family as a child"
4.select family Y+Z
5.select birth.
A “Father’s family with an unknown individual” family record will appear. That should not exist..
As shown in the figure below, the red border identification area is an extra record, which is an error and should not exist.
![error](https://user-images.githubusercontent.com/26761596/56968817-6c6f2300-6b96-11e9-92b8-3735e76726bf.JPG)

**Comment by fisharebest** [comment]
The red box indicates a "pending change".

If you accept the pending changes, the extra family and box will disappear.
