### ISSUE TITLE
2.0-Search results in the chart are incomplete

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2403]
I have found this problem many times.
Some people's names can be searched in the general search, but the search in the search box in the chart does not find.
For example, I searched “秉伟” on the general search page, and I can find a lot of results.
But I typed “王秉伟” or “秉伟” search in the search box on the chart page, just found a part, not showing it completely.
I only have to enter “王 伟” to find the person I am looking for.
I checked the database records and found no difference.

**Comment by fisharebest** [comment]
> the search in the search box in the chart does not find.

This search searches the names table in the database: `wt_names.n_full`.

Does the name that you type appear in this table?

**Comment by xmlf** [comment]
> > the search in the search box in the chart does not find.
> 
> This search searches the names table in the database: `wt_names.n_full`.
> 
> Does the name that you type appear in this table?

YES! I'm sure!The name in this table wt_names.n_full.
I have found this problem more than once.
![aaa](https://user-images.githubusercontent.com/26761596/57225091-dd528700-703d-11e9-957a-0fbb3499485f.JPG)

**Comment by fisharebest** [comment]
Does `n_full` contain *exactly* the name you typed?

Are there any non-printing characters, etc.

**Comment by xmlf** [comment]
> Does `n_full` contain _exactly_ the name you typed?
> 
> Are there any non-printing characters, etc.

YES, the `n_full` contain exactly the name.
And I checked it and didn't include other characters.

**Comment by fisharebest** [comment]
I need to reproduce the problem on my development system.

Are you able to create a GEDCOM file that has the problem?

You can email it to me at fisharebest@gmail.com

**Comment by xmlf** [comment]
> I need to reproduce the problem on my development system.
> 
> Are you able to create a GEDCOM file that has the problem?
> 
> You can email it to me at [fisharebest@gmail.com](mailto:fisharebest@gmail.com)

Because my entire family tree GEDCOM file is relatively large. I want to send it to you through the collection box download.
However, I found that the size of the .zip file downloaded through the collection box is 0 and cannot be opened.

**Comment by xmlf** [comment]
I have already sent it to you by email.

**Comment by fisharebest** [comment]
Thanks.  I see the problem.
