### ISSUE TITLE
2.0beta-Individual chart box border color error after changing family members

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2404]
When editing a family member and deleting a family member, 
In individual pages and family page, the individual chart box border is blue(style is wt-new), which is error. It should be red(style is wt-old).
This can be misleading to the editor.

**Comment by fisharebest** [comment]
There are lots of places that we use the red/blue boxes.

Which one exactly is wrong?

**Comment by xmlf** [comment]
For example
Https://dev.webtrees.net/demo-dev/index.php?route=family&xref=f2&ged=demo
Edit the family, change family members, and delete a child.
Then the border displayed by this child is blue, it should be red.

**Comment by fisharebest** [comment]
The child record has been updated (to remove the FAMC link).
The child has not been deleted.  Just unlinked.
Therefore it has a blue border.

If the child was deleted, it would have a red border.

In this example:

* Andrew is deleted (red border)
* Edward is unlinked (blue border)

<img width="481" alt="Screen Shot 2019-05-04 at 10 46 57" src="https://user-images.githubusercontent.com/2306088/57177205-fa2e6500-6e59-11e9-82f9-7a29042f93b7.png">

**Comment by xmlf** [comment]
I understand！Thank you!
This place, marking the removal of family links as blue, is prone to misunderstanding.
