### ISSUE TITLE
Wrong events order

### ISSUE THREAD

**Issue by maekclena** [fisharebest/webtrees#2405]
In demo-dev, the events in the families tab of an individual are not ordered by date.
For example in [George VI's page](https://dev.webtrees.net/demo-dev/index.php?route=individual&xref=i34&ged=demo#tab-relatives), his birth is displayed after his younger sister, resulting in a negative date difference.

**Comment by fisharebest** [comment]
> are not ordered by date

You are right.  They are shown in the order that they exist in the family GEDCOM record.

Underneath (if you are logged in), you'll see a link to "re-order" the children - which updates the GEDCOM record.  The re-order page also has a "sort by birth date" option.

Basically, we have two choices.  Either sort automatically, or allow the genealogist to control the order.

If all dates are known (and accurate!), then automatic sorting is fine.  But there are too many cases when automatic sorting won't work.  For example

* unknown dates
* identical dates (twins)
* conflicting data (i.e. one source says that child X is older than child Y, but a less reliable source gives the birth date of Y before X

As a general policy, webtrees doesn't update data without direct instruction from the user.

**Comment by maekclena** [comment]
Thank you for the explanation, that makes sense. Feel free to close this issue.
