### ISSUE TITLE
PHP Email Issues since May

### ISSUE THREAD

**Issue by KosherJava** [fisharebest/webtrees#241]
A number of months ago email from my webtrees install stopped making it through. I tried both SMPT and PHP mail (changing back and forth logs Site setting "SMTP_ACTIVE" set to "internal"/Site setting "SMTP_ACTIVE" set to "external"). I see no errors in the regular logs. family/admin_site_logs.php shows the following:

Unable to send message. FROM:aaa@gmail.com TO:AAA(failed to send)
Mail: Unable to send mail.
Incidentally the errors started at the end of May, and may be related to this checkin:
https://github.com/fisharebest/webtrees/commit/9291dbb7f8cb7ad4593eb38957766250afa2ce0a

I do see the flowing in the server logs, but I think it is unrelated

[Fri Aug 08 16:09:33 2014] [error] [client 123.12.123.123] ModSecurity: Rule 7f0049143c88 [id "340145"][file "/etc/httpd/modsecurity.d/10_asl_rules.conf"][line "337"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "www.example.com"] [uri "/wt/admin_users.php"] [unique_id "U@VKnUKT9F8AACdfhvIAAAMH"]

Any suggestions would be welcome.

**Comment by Birdie777** [comment]
The posting from "KosherJava" is interesting. I have the same issue. I agree with "fisharebest" that a flicke issues. Fact is that it only affects "Webtrees" at my server. Squirrelmail works fine on my Postfix server. Both SMTP/PHP Mail don't work. Both my Postfix server and GMail SMTP don't sent any mail (not even to my own server). The last mail sent was 3 days ago about "Pending Changes" (what I recently have changed to "Automatically approve changes made by this user". I didn't change anything on Linux level in meantime. Till now to put "permit_mynetworks" on top in the /etc/postfix/main.cf

smtpd_recipient_restrictions =
        permit_mynetworks,
        permit_sasl_authenticated,
        reject_unauth_destination
smtpd_helo_required = yes
smtpd_helo_restrictions =
        permit_mynetworks,
        permit_sasl_authenticated,
        reject_invalid_helo_hostname,
        reject_non_fqdn_helo_hostname,
        reject_unknown_helo_hostname

But it not works!
My last mail

Return-Path: <www-data@domain.com>
X-Original-To: webmaster@domain.com
Delivered-To: webmaster@domain.com
Received: by vogels.org (Postfix, from userid 33)
    	id 9D5534037D; Sun, 19 Apr 2015 14:25:18 +0200 (CEST)
To: webmaster <webmaster@domain.com>
Subject: Pending changes
X-PHP-Originating-Script: 0:Sendmail.php

**Comment by fisharebest** [comment]
> Both my Postfix server and GMail SMTP don't sent any mail

GMAIL changed recently.  You must now enable "allow insecure applications to send mail" in your google preferences.

**Comment by Birdie777** [comment]
Despite of GMAIL,  "PHP Mail" should still work, but it doesn't anymore.
How can that be?

TEST->Successful:
I downloaded from an external site (see below) a "PHP Mail" script and it run successful on my server, it send mail to both external email addresses and those that are hosted on the Raspberry itself. 

Source from used script.
http://www.htmlgoodies.com/img/2009/12/Form.zip 
change in "form_mailer.php"
$mailto = 'webmaster@domain.com';

QUESTION: How can it be that PHP mail from my Webtrees stopped working/ or does not work anymore? Where I can check more? I think I can assume all the files in the webroot are stable (corruption excluded), only the MySQL database and /webroot/data contain dynamic data.
