### ISSUE TITLE
Improve the way to find individuals in general search

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2411]
Currently, There are two ways to find an individual by entering a name.
One is to only enter the given name(excluding surname) in the general search.
The other is to search by entering the full name or the given name in the chart.
Finding an individual is very unfriendly to the user experience in two ways.
I recommend a unified input method. In the general search, you can also enter the full name to search.

**Comment by kexuebin** [comment]
Chinese users search 100% of all names
