### ISSUE TITLE
Local translation files - wt 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2416]
I have for instance added a local fact, Mother tongue (_MTNG), to my site. 
In wt pre-2.0 I have added local .mo files to the data/languages folder. Where should I put them in wt 2.0.0?

**Comment by melizaa** [comment]
I tried to add to the data fiolder a lang folder with he, fi, etc. folders and in them message.mo files. This did not work.

I tried then to add to the data folder a resources folder and in it the lang folder. This does neither work.

**Comment by fisharebest** [comment]
In webtrees 2, you add custom translations in modules.

There are custom translations in one of the example modules:
https://github.com/fisharebest/webtrees/blob/master/modules_v4/example.disable/module.php

You would add translations for all your langauges in the same module.

**Comment by melizaa** [comment]
I have tried to create a module by using the example module.
I see errors for the namespace and for Translation.

Where/how should I add the local texts in the module to the regular, translated texts?

**Comment by melizaa** [comment]
and where should I use the local module?

**Comment by melizaa** [comment]
and I try to use the old local .mo files from webtrees-data/languages/.

**Comment by fisharebest** [comment]
You seem to have this set up OK.
