### ISSUE TITLE
Share media - wt 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2418]
How do I share media between two wt 2.0.0. installations?

How do I share media from my production pre wt2.0.0 to my test wt2.0.0 installation?
The link that I had and that worked, and that I removed today, caused errors in Cleanup data.

See #1974

**Comment by melizaa** [comment]
I see the media and the #1974 issue in the future test.

I do not see media or issues in the test test.

**Comment by fisharebest** [comment]
The sites can share a `data` folder.

You have a folder `webtrees-data` in your home folder.  You could use this folder.

For each site, go to "Control panel", "Website preferences" and set "Data folder" to `../webtrees-data/` or `../../webtrees-data/`.

Move the folder `www.amitys.com/webtrees/data/media` to `webtrees-data/media`.

All your sites will then share this same folder.

**Comment by fisharebest** [comment]
I can do this for you, but it is important that we are not both working on your site at the same time.  I do not want to be moving media files at the same time as you are uploading/editing them.

**Comment by melizaa** [comment]
Greg, please do it.

**Comment by fisharebest** [comment]
I've done this.

1) Please check that this is working as expected
2) You have lots of GEDCOM and other files in your old `data` folders.  You should move these to the new `webtrees-data` folder.  (Some have the same name).
