### ISSUE TITLE
Modify the date of birth, not modify, edit, equal to a new line

### ISSUE THREAD

**Issue by kexuebin** [fisharebest/webtrees#2421]
Modify the date of birth, not modify, edit, equal to a new line？

**Comment by fisharebest** [comment]
Like this?

<img width="515" alt="Screen Shot 2019-05-11 at 09 42 38" src="https://user-images.githubusercontent.com/2306088/57567445-235a7280-73d1-11e9-86b9-66aed99bb242.png">

You need to confirm the edit:

<img width="740" alt="Screen Shot 2019-05-11 at 09 43 38" src="https://user-images.githubusercontent.com/2306088/57567464-906e0800-73d1-11e9-993a-126bc964e5f3.png">

If you want edits be be confirmed automatically, there is an option in the control panel (user administration, edit user)

**Comment by kexuebin** [comment]
Click on the change at the top, the problem still exists, add a new line.
Question 2: After clicking “Continue” to jump to the home page, click on the alpha version to continue back to the original edit.
