### ISSUE TITLE
github - Media throws error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2423]
Undefined index: xref …/app/Http/Controllers/MediaFileController.php:106 #0 …/app/Http/Controllers/MediaFileController.php(106): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(8, 'Undefined index...', '/var/www/html/s...', 106, Array) #1 [internal function]: Fisharebest\Webtrees\Http\Controllers\MediaFileController->mediaThumbnail(Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Tree)) #2 …/app/Application.php(45): ReflectionMethod->invoke(Object(Fisharebest\Webtrees\Http\Controllers\MediaFileController), Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Tree)) #3 …/app/Http/Middleware/RequestRouter.php(68): Fisharebest\Webtrees\Application->dispatch(Object(Fisharebest\Webtrees\Http\Controllers\MediaFileController), 'mediaThumbnail') #4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestRouter->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #5 …/app/Http/Middleware/ModuleMiddleware.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ModuleMiddleware->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #7 …/app/Http/Middleware/BootModules.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #9 …/app/Http/Middleware/UseTransaction.php(44): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #11 …/app/Http/Middleware/CheckCsrf.php(63): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #13 …/app/Http/Middleware/DoHousekeeping.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #15 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #17 …/app/Http/Middleware/CheckForMaintenanceMode.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #19 …/app/Http/Middleware/UseLocale.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLocale->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #21 …/app/Http/Middleware/UseTree.php(59): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTree->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #23 …/app/Http/Middleware/UseSession.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #25 …/app/Http/Middleware/UseFilesystem.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseFilesystem->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #27 …/app/Http/Middleware/UseCache.php(44): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #29 …/app/Http/Middleware/UpdateDatabaseSchema.php(56): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #31 …/app/Http/Middleware/UseDebugbar.php(64): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #33 …/app/Http/Middleware/UseDatabase.php(85): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #35 …/app/Http/Middleware/ReadConfigIni.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #37 …/app/Http/Middleware/HandleExceptions.php(54): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #39 …/app/Http/Middleware/EmitResponse.php(52): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #41 …/app/Http/Middleware/PhpEnvironment.php(46): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #43 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #44 …/index.php(44): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #45 {main}

**Comment by fisharebest** [comment]
Can you reproduce this error?  If so, how?

**Comment by makitso** [comment]
Nope, found it in my wt log generated by visitor.

**Comment by fisharebest** [comment]
There is only one place in the code that generates URLs to this function - and it includes the xref.

Are you able to cross reference the timestamp in your webserver logs to find the corresponding URL?

**Comment by makitso** [comment]
Sorry, I deleted the wt logs that contained the time stamps.

**Comment by makitso** [comment]
This command throws error.  
/index.php?route=media-thumbnail&amp;xref=m175&amp;ged=peters.ged&amp;fact_id=b5e6a5456df08aecd7e8cac1be96f21f&amp;w=0&amp;h=0&amp;fit=contain&amp;mark=watermark.png&amp;markh=100h&amp;markw=100w&amp;markalpha=25&amp;or=0&amp;s=03464bc4a037fd677d4874c58f5d42df

**Comment by fisharebest** [comment]
The errors says that the query string does not contain an `xref` parameter - which clearly it does.

Is this reproduceable?

**Comment by makitso** [comment]
I looked at the sequence of queries done by this guy and it does not make any sense to me.  

62.210.201.91 - - [11/May/2019:02:07:04 -0700] "GET /index.php?route=calendar&amp;view=year&amp;ged=peters.ged HTTP/1.1" 200 12224 "-" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/6.0;)"
62.210.201.91 - - [11/May/2019:02:07:05 -0700] "GET /index.php?route=report-setup&amp;xref=i0001&amp;ged=peters.ged&amp;report=birth_report HTTP/1.1" 200 10485 "-" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/6.0;)"

62.210.201.91 - - [11/May/2019:02:07:05 -0700] "GET /index.php?route=media-thumbnail&amp;xref=m175&amp;ged=peters.ged&amp;fact_id=b5e6a5456df08aecd7e8cac1be96f21f&amp;w=0&amp;h=0&amp;fit=contain&amp;mark=watermark.png&amp;markh=100h&amp;markw=100w&amp;markalpha=25&amp;or=0&amp;s=03464bc4a037fd677d4874c58f5d42df HTTP/1.1" 301 1078 "-" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/6.0;)"

62.210.201.91 - - [11/May/2019:02:07:06 -0700] "GET /index.php?route=media-thumbnail&amp;xref=m175&amp;ged=peters.ged&amp;fact_id=b5e6a5456df08aecd7e8cac1be96f21f&amp;w=0&amp;h=0&amp;fit=contain&amp;mark=watermark.png&amp;markh=100h&amp;markw=100w&amp;markalpha=25&amp;or=0&amp;s=03464bc4a037fd677d4874c58f5d42df HTTP/1.1" 500 41407 "http://www.skatekey.net/index.php?route=media-thumbnail&amp;xref=m175&amp;ged=peters.ged&amp;fact_id=b5e6a5456df08aecd7e8cac1be96f21f&amp;w=0&amp;h=0&amp;fit=contain&amp;mark=watermark.png&amp;markh=100h&amp;markw=100w&amp;markalpha=25&amp;or=0&amp;s=03464bc4a037fd677d4874c58f5d42df" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/6.0;)"

**Comment by fisharebest** [comment]
That IP address belongs to a hosting company, so this is more likely to be a robot than a human.

According to https://developers.whatismybrowser.com/useragents/parse/
the user-agent string suggests IE10 running in compatibility mode (to emulate IE 7) on Windows Server.

The "referer" URL in the logs is double-encoded.  The `&` are `&amp;`.

My guess is that this error was caused by a robot generating an invalid URL.
