### ISSUE TITLE
2.0 - toggleable events buggy in Firefox

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#2424]
On the Facts and Events tab, if historical events are enabled, we have two checkboxes
"Events of close relatives" and "Historical facts".

Checking these and reloading the page in Firefox (66.0.5) doesn't consistently display the checkbox states correctly: Sometimes they are displayed unchecked even though the persistent toggle is 'on'.
In Chrome, this works correctly. 

I cannot reproduce this on the demo server, because historical facts are apparently not enabled there (A single checkbox also seems to work correctly in Firefox).

The issue may be caused by Firefox not handling `.click()` correctly (used in webtrees.js for the `persistent_toggle` function), there are several (mostly older though) StackOverflow entries describing similar problems.

**Comment by fisharebest** [comment]
I have just spend several minutes selecting/unselecting/reloading using Firefox (version 67,  Mac).

It worked every time.

What version of Firefox do you use?

Does anybody else see this problem?

**Comment by ric2016** [comment]
I had a feeling this could be tricky to reproduce - 
I observed it with Firefox (66.0.5) on Windows 7.

Can you enable one of the historical data modules on the demo server, so that I can make sure this doesn't only occur on my local system?

**Comment by fisharebest** [comment]
> Can you enable one of the historical data modules on the demo server

Done.

Remember that the database on the demo server is reset every night.

**Comment by fisharebest** [comment]
Were you able to test this?

**Comment by ric2016** [comment]
Yes, and I cannot reproduce this on the demo server either.
It could be caused by the page loading more slowly in my local version, or some other obscure reason. I guess we can close this issue for now.

**Comment by fisharebest** [comment]
OK.  If you can find a reproducable test case, then create a new issue.
