### ISSUE TITLE
Translation for string not used

### ISSUE THREAD

**Issue by marku5** [fisharebest/webtrees#2425]
Latest dev-Version: https://dev.webtrees.net/demo-dev/index.php?route=source&xref=s1&ged=Demo

If german language is selected:
The first  statistics diagram shows on x-axis „Century” instead of “Jahrhunderts”. String is correct in translation project (https://weblate.iet.open.ac.uk/translate/webtrees/webtrees/de/?sid=1908b3e8-7424-11e9-a785-005056945943&offset=3), just not used here!? The other diagrams are ok.

**Comment by fisharebest** [comment]
The language files on the dev/demo site need to be re-compiled manually.

I have just done this.

This translation is now being used.


<img width="314" alt="Screen Shot 2019-05-11 at 21 24 18" src="https://user-images.githubusercontent.com/2306088/57574554-28500e00-7433-11e9-9725-658620cbf9ac.png">

**Comment by marku5** [comment]
Thanks Greg!
