### ISSUE TITLE
https://dev.webtrees.net/ansel/ broken

### ISSUE THREAD

**Issue by lochiiconnectivity** [fisharebest/webtrees#2427]
https://dev.webtrees.net/ansel/ is broken, all that is seen is the code, not the form

**Comment by fisharebest** [comment]
Thanks for letting me know.  It's working now.

BTW, there is a bug in PHP 7.2 and 7.3 - which I found and reported 7 months ago...

https://bugs.php.net/bug.php?id=77069

A consequence of the bug is that the last line of the GEDCOM file (`0 TRLR`) might be missing from the output file :-(
