### ISSUE TITLE
Text Other is not translated in the statistics individual page - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2431]
In individual statistics Births by century and Death by century the word Other is not translated.
![image](https://user-images.githubusercontent.com/5202996/57653127-c4b41500-75d9-11e9-93bc-2386847b44a5.png)

![image](https://user-images.githubusercontent.com/5202996/57653186-e6ad9780-75d9-11e9-9b83-2c4b5f504511.png)

Text Other is translated on the same page in the Tps surnames and Top given names pie charts.

**Comment by fisharebest** [comment]
How do you get "Other"?

**Comment by melizaa** [comment]
I look at the big file and see 19th-21st centuries and Other.
In pre 2.0.0 production I see 16th-21st centuries.

btw.
In most common surnames I see in pre 2.0.0 10 surnames and Other, and in
2.0.0 I see only 2 names and Other, and most common given names I see 7 and
Other and in 2.0.0 only 2 names and Other  The 2.0.0 pie chart shows more
than 3 slices, most without names.

Also the Other page Media objects pie chart prints an Other total.

Meliza

**Comment by melizaa** [comment]
The Other of the names is translated to languages.

The Other of media is also not translated.

**Comment by melizaa** [comment]
The Other counter of names in pre 2.0.0 production is bigger than the Other total in the 2.0.0 test system, although I see less specific names with totals in the 2.0.0 test system.

**Comment by melizaa** [comment]
The birth Other 20 individuals were born: 18 in the 17th century and 2 in the 16th century.
The death Other individuals died in the 17th and 16th centuries.

**Comment by fisharebest** [comment]
"Other" is created automatically by GoogleCharts when there are values that are too small to display.

By default, it uses the browser language.  We can override this.
