### ISSUE TITLE
I see wrong ages in family statistics - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2432]
I see unacceptable youngest/oldest father and mother in family statistics.
Also the youngest/oldest male/female at marriage are unacceptable.
I would like not to show these values on my site as long as my site has such data.
Please enable me to remove them.

The youngest parents are shown with negative thousands of days.
On the Hebrew page the negative sign is printed to the right of the number of days. It should print to the left as on ltr pages.
The negative age is caused by the fact that the parent is recorded as born before the child.

I would like to see these cases in the error page.

**Comment by wkitty42** [comment]
On 5/13/19 5:30 PM, melizaa wrote:
> The negative age is caused by the fact that the parent is recorded as born 
> before the child.

somehow, i think you meant to write something else here... maybe "after" instead 
of "before"??

**Comment by melizaa** [comment]
You are right, I should have written 
The negative age is caused by the fact that the parent is recorded as born after the child.

**Comment by fisharebest** [comment]
> I would like not to show these values on my site as long as my site has such data.

You can change the access level for the statistics chart in the control panel.  This would let you show it to admins only.

**Comment by melizaa** [comment]
I want to show the statistics on my site, but not these negative ages.

**Comment by t-karcher** [comment]
Not sure whether this issue is still relevant, but just in case: Negative parent ages could be correct in rare circumstances, e.g. for adopted childs. If you have serious doubts about the correctness of a certain date and don't want it to be regarded in statistics etc., you could just remove the respective fact from the individual and re-add the information as a note in a new research task, preventing it from showing up anywhere as the basis for calculations.

**Comment by fisharebest** [comment]
> The negative age is caused by the fact that the parent is recorded as born after the child.

I think that most people use the blocks to help *find* errors like this.

> Please enable me to remove them.

Add a privacy restriction to the family?

**Comment by melizaa** [comment]
I will close this
