### ISSUE TITLE
2 Beta3 Openstreetmap error when using flags

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2436]
If we have flags stored at `Modules_v4/openstreetmap/places` then they are not displayed on the Places Hierarchy page (assuming Maps are used). I think the solution is to change line 274 of PlaceHierarchyController from `Webtrees::MODULES_DIR . 'openstreetmap/';` to `Webtrees::MODULES_PATH. '/openstreetmap/';`

However now that openstreetmaps is no longer a module wouldn't it make more sense to store the flags somewhere else (resources?)

**Comment by fisharebest** [comment]
The only folder to which we can/should write is `/data`

Not only is the `modules_v4` folder not guaranteed to be writable, all assets (css, js, png, etc.) need to be in `/public`, as this will be the base-url when we move to "pretty URLs".

Storing flags in the database might be an option - and then embedding them as `data:` URLs in the page.

See  #1797

**Comment by fisharebest** [comment]
Closed in favour of #3698
