### ISSUE TITLE
Sign up for Account to webtrees doesn't accept the scrambled letters.  

### ISSUE THREAD

**Issue by KenJames0322** [fisharebest/webtrees#2440]
Trying to set up an account in Webtree and it doesn't accept my response to the scrambled letters.  I have tried numerous times and keep getting rejected.  Is it broken?
As an aside, at 76 years old I hate these )&)^^))^_) things.  Who designs this crap?

**Comment by fisharebest** [comment]
>  Is it broken?

Several people have signed up today, so I guess it is working.

> keep getting rejected

It is case-sensitive.  If you see `R`, then you must type `R` and not `r`.

> at 76 years old I hate these )&)^^))^_) things

Everybody hates them!  I hate them.
But without them, the forum would be full of automated accounts posting spam.

Like everything in life, it is a trade-off.

Try again?

**Comment by KenJames0322** [comment]
Thanks for the response. I will keep trying.
