### ISSUE TITLE
2.0beta-My website database is inserted into illegal code

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2441]
Today, when I checked my geographic data(/index.php?route=map-data), I found that there are many shell commands. As shown below:
![捕获](https://user-images.githubusercontent.com/26761596/57900937-716deb00-7895-11e9-8432-97077016d268.JPG)

Then I analyzed my database binary log, my database was inserted at 7:39 am on 05 03, 2019.
Currently my server has failed2ban installed, and only open ssh and web ports, and only installed webtrees.
I checked the system log, which is definitely not caused by the Linux system being compromised.
I checked the website access log, but the website access log on May 3, 2019 was automatically overwritten by my own shell code.
So at the moment I can't know which file was illegally operated.
I hope that I can pay attention and check if there is an unsafe code. Thank you!

**Comment by fisharebest** [comment]
> I checked the website access log, but the website access log on May 3, 2019 was automatically overwritten by my own shell code.

This is unfortunate.

Perhaps you should inlcude the webserver logs in your backup.

> So at the moment I can't know which file was illegally operated.

webtrees can import data from files `data/*.csv` into this database table.

Do you have any `.csv` files?  Did you examine them?

**Comment by fisharebest** [comment]
A google search reveals that very many sites have had the same content inserted.

None of these are webtrees sites.

This suggests that the attackers are using a "general" vulnerability - not a "webtrees" vulnerability.

**Comment by xmlf** [comment]
I can be very sure that there are no csv files under the `data` folder.
And I take great care of the security of the server, I use Debian 9, automatically update the security patch every day. 
And use fail2ban to analyze the log and automatically block some IP.(including multiple logins to webtrees).
Yes, I also use GOOGLE search to find that there are many websites with this problem.
The most confusing thing about me is why I inserted this data into the` wt_placelocation`  table  instead of the other data tables.

**Comment by fisharebest** [comment]
Did you find the cause of this, or any other information?

This does not seem to be a problem with webtrees

I will close this issue, as there is nothing we can do in webtrees to help.
