### ISSUE TITLE
Complete Privacy

### ISSUE THREAD

**Issue by adelatour11** [fisharebest/webtrees#2445]
Hello
I tried to configure my tree so that not any personal info is shared publicly, no even family names. 
I've noticed that visitors can access to the lists menu and view family names.

Is it possible to remove Lists / Calendar / Search from the visitors menu ? or is it possible to prevent visitors to view names ?

Thanks

**Comment by fisharebest** [comment]
This is not possible in webtrees 1.7.

It *is* possible in webtrees 2.0.0, which is currently in "beta" release.  (beta.3 will be released today or tomorrow).

(Actually, it *is* possible in 1.7, but would require you to create your own custom theme).

**Comment by fisharebest** [comment]
Oops - I forgot the obvious answer to this question.  In the privacy settings, you can set it so that the entire tree is hidden until you log in.

This has some other consequences such as disabling the "new user registration" system - as new users register with a tree rather than the site.

**Comment by adelatour11** [comment]
thanks for your quickfeedback, 
very good work you did on webtrees!
