### ISSUE TITLE
2.0-The login form is automatically completed, making it impossible to switch accounts

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2450]
I am often troubled by this problem in use.
Now on the login page, the default is to automatically populate my username and password.

If I have multiple accounts and want to switch accounts, I often encounter cases where the input box cannot be clicked.
I hope to change the autocomplete feature to manual complete.

login-page.phtml 27 line
`<input class="form-control" type="text" id="username" name="username" required value="<?= e($username) ?>" autocomplete="username">`

changed to

  `<input class="form-control" type="text" id="username" name="username" required value="<?= e($username) ?>" autocomplete="off" onfocus="this.type='username'">`

**Comment by fisharebest** [comment]
The markup is correct.  See documentation at https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands

> onfocus="this.type='username'"

`type="username"` is not valid?  DId you mean `this.autocomplete`?

> If I have multiple accounts and want to switch accounts

Autocomplete is handled by your browser or password manager.

I do not understand what problems you have.
I have more than one login on the same site, and my password manager has no problems.

> I hope to change the autocomplete feature to manual complete.

If you want to customise this on your own site, you can do so easily using a module.

The example at https://github.com/fisharebest/webtrees/blob/master/modules_v4/example-theme.disable/module.php shows how to replace one of the HTML templates.

You simply need to replace the files
* `resources/views/login-page.phtml`
* `resources/views//modules/login_block/sign-in.phtml`

**Comment by xmlf** [comment]
When I have multiple accounts, For example a and b. Google Chrome has saved the username and password. When I open the login page, Google Chrome automatically fills in the a account. I want to log in with the b account, but the username and password input boxes are not clickable, so I can't switch to log in with the b account.
 I am currently solving this problem by changing the login-page with a custom theme. However, there may be other people who have the same problem.

**Comment by fisharebest** [comment]
Are you using the "auto sign-in" feature in Chrome?

**Comment by xmlf** [comment]
Yes!
I logged in on other websites and never encountered this problem.Logging in on the mobile phone, switching accounts is also normal.I only encountered this issue on the desktop version of Google Chrome.

**Comment by fisharebest** [comment]
This works for me.

I create three accounts, and I allow Chrome to store them.

I visit the webtrees login page.

Chrome will auto-complete the username/password (using the most-recently used account).

> but the username and password input field are not clickable

I can click on the username field to choose a different account.

**Comment by fisharebest** [comment]
Any more information?

I cannot reproduce this problem, and I think it is caused by the web-browser, not webtrees.
