### ISSUE TITLE
2.0-Tabs does not work for visitor display

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2451]
In the control panel, the tab settings in the module, setting the display to the visitor does not work. Visitors still can't see the tab.

**Comment by fisharebest** [comment]
Which tab?

Tabs are only shown when there is something to display.

For example, if there are no notes, then the notes tab is not displayed.

**Comment by xmlf** [comment]
> Which tab?
> 
> Tabs are only shown when there is something to display.
> 
> For example, if there are no notes, then the notes tab is not displayed.
Sources tab. All individual source tags contain content, but are not displayed for visitors.

**Comment by fisharebest** [comment]
Are the sources visible?

By default, sources are not shown to visitors - so there will be nothing in the tab.

Control panel -> Family tree -> Privacy -> Privacy rules

**Comment by xmlf** [comment]
Thanks!
The problem is solved.
