### ISSUE TITLE
2.0-The error message in the website log, the ip address is 127.0.0.1

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2452]
What does the IP address mean for 127.0.0.1? Why are there so many error logs?
![error](https://user-images.githubusercontent.com/26761596/58363849-75c18600-7edd-11e9-9773-86c2962bd291.JPG)
![2](https://user-images.githubusercontent.com/26761596/58363850-7823e000-7edd-11e9-9ca3-475d4bd24094.JPG)
![3](https://user-images.githubusercontent.com/26761596/58363852-79eda380-7edd-11e9-915d-442659f177d2.JPG)
![4](https://user-images.githubusercontent.com/26761596/58363853-7bb76700-7edd-11e9-824f-214c429439f7.JPG)

**Comment by xmlf** [comment]
In addition, the website log does not recognize the real IP address of the user after using the proxy.

**Comment by fisharebest** [comment]
The error message suggests that there is a problem when creating the cache files.

Perhaps there was an error when they were created.  Disk full, etc.

> In addition, the website log does not recognize the real IP address of the user after using the proxy.

Support for this is planned for the future.
