### ISSUE TITLE
Translate File Title - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2453]
In PhpGedView I used the local language files to translate my GEDCOM file title to languages.

How can I do it in webtrees 2.0.0?

**Comment by fisharebest** [comment]
In file `app\Tree.php`, there is a function `title()`.

You could translate the title there.

**Comment by melizaa** [comment]
I did not manage to translate the title.
Perhaps this is because I updated .po files and my Gedcom title includes "Meliza's"?

**Comment by melizaa** [comment]
actually, if I remember correctly, I tried to add the translation to the modules_v4/local_language/module.php.

There the original and the translated text are surrounded by single quotes.

**Comment by melizaa** [comment]
In app/Tree.php I added

// @@ local  =>      
       if ($name === 'GedcomFuture.ged') 
                 $this->title               = I18N::translate($title); 
      else	       
        	$this->title               = $title;
// @@ <=
