### ISSUE TITLE
webtrees 2.0.0beta3: user administration and log forms don't work with https

### ISSUE THREAD

**Issue by HelmutL** [fisharebest/webtrees#2454]
Some administration forms don't work. E.g. calling user administration (to show / modify defined users) show empty data because of:
`vendor.min.js?v=1557830439:1 Mixed Content: The page at 'https://www.familie-leininger.at/wt-test/index.php?route=admin-users' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.familie-leininger.at:443/wt-test/index.php?route=admin-users-data&draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%...name%5D=&columns%5B10%5D%5Bsearchable%5D=true&columns%5B10%5D%5Borderable%5D=true&columns%5B10%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B10%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B11%5D%5Bdata%5D=11&columns%5B11%5D%5Bname%5D=&columns%5B11%5D%5Bsearchable%5D=true&columns%5B11%5D%5Borderable%5D=true&columns%5B11%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B11%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=2&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1557926813859'. This request has been blocked; the content must be served over HTTPS.
send @ vendor.min.js?v=1557830439:1
ajax @ vendor.min.js?v=1557830439:1
ht @ vendor.min.js?v=1557830439:1
ft @ vendor.min.js?v=1557830439:1
at @ vendor.min.js?v=1557830439:1
lt @ vendor.min.js?v=1557830439:1
At @ vendor.min.js?v=1557830439:1
j @ vendor.min.js?v=1557830439:1
l @ vendor.min.js?v=1557830439:1
re @ vendor.min.js?v=1557830439:1
(anonymous) @ vendor.min.js?v=1557830439:1
each @ vendor.min.js?v=1557830439:1
each @ vendor.min.js?v=1557830439:1
l @ vendor.min.js?v=1557830439:1
(anonymous) @ index.php?route=admin-users:127
vendor.min.js?v=1557830439:1 Mixed Content: The page at 'https://www.familie-leininger.at/wt-test/index.php?route=admin-users' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.familie-leininger.at:443/wt-test/index.php?route=admin-users-data&draw=2&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%...name%5D=&columns%5B10%5D%5Bsearchable%5D=true&columns%5B10%5D%5Borderable%5D=true&columns%5B10%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B10%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B11%5D%5Bdata%5D=11&columns%5B11%5D%5Bname%5D=&columns%5B11%5D%5Bsearchable%5D=true&columns%5B11%5D%5Borderable%5D=true&columns%5B11%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B11%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=2&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1557926813860'. This request has been blocked; the content must be served over HTTPS.
send @ vendor.min.js?v=1557830439:1
ajax @ vendor.min.js?v=1557830439:1
ht @ vendor.min.js?v=1557830439:1
ft @ vendor.min.js?v=1557830439:1
at @ vendor.min.js?v=1557830439:1
lt @ vendor.min.js?v=1557830439:1
(anonymous) @ vendor.min.js?v=1557830439:1
iterator @ vendor.min.js?v=1557830439:1
(anonymous) @ vendor.min.js?v=1557830439:1
(anonymous) @ vendor.min.js?v=1557830439:1
fnFilter @ vendor.min.js?v=1557830439:1
(anonymous) @ index.php?route=admin-users:149
`
The same problem occurs when trying to show / filter log data: -> empty data.

A similar problem occurs for login:
`https://www.familie-leininger.at/wt-test/index.php?route=login&url=http%3A%2F%2Fwww.familie-leininger.at%3A443%2Fwt-test%2Findex.php%3Froute%3Duser-page%26ged%3DLeininger-Test`

The login works, but data are transferred unencrypted.

The attachment shows the defined subdomains.

![subdomains](https://user-images.githubusercontent.com/17042607/58560161-d544cc00-8224-11e9-9be2-fe98fa56aebd.jpg)

Note: 
The behaviour is the same wether redirection is set to "Permanent Redirection (308)" or "Moved Permanently (301)".

**Comment by fisharebest** [comment]
Does it help if you add this line to the file `data/config.ini.php`?

`base_url=https://www.familie-leininger.at/wt-test/`

**Comment by HelmutL** [comment]
Unfortunately not. Same behaviour.

**Comment by HelmutL** [comment]
I have to correct my last answer.

To be sure, I cleaned all directories with the exception of data today. Then unzipped webtrees-2.0.0beta.3 again. After adding base_url to data/config.ini.php it started to work.

**Comment by fisharebest** [comment]
Thanks - good to hear it is now working for you
