### ISSUE TITLE
Out of place entry in sorted table

### ISSUE THREAD

**Issue by maekclena** [fisharebest/webtrees#2457]
In result tables, some individuals without events are placed in the middle after sorting by date.

For example in [this table](https://dev.webtrees.net/demo-dev/index.php?route=search-general&ged=demo&query=King&search_individuals=on&search_trees%5B%5D=demo), when sorting by either "Birth", "Death" or "Anniversary", Claude Bowes-Lyon is placed in the middle rather than at the end despite having no corresponding dated events.

**Comment by fisharebest** [comment]
When an individual has no birth/death date, an estimated date is used.

For Claude Bowes-Lyon, the dates are "EST 1823" and "BEF 1943".

Whether the estimated dates are displayed or not is a config option - which isn't working right now.  I'll post a fix shortly.
