### ISSUE TITLE
JavaScript TypeError when clearing individual selection

### ISSUE THREAD

**Issue by maekclena** [fisharebest/webtrees#2463]
The "Remove all items" button to clear an individual selection in charts fails with this JavaScript error:

```js
TypeError: this.placeholder is undefined
```

**Comment by fisharebest** [comment]
Which chart?  The text "Remove all items" doesn't exist in any of the webtrees code...

**Comment by maekclena** [comment]
I'm talking about the individual selection box in the Ancestors chart, for example. I think it's from the Select2 module.
