### ISSUE TITLE
2.0-Short_open_tag default value causes sitemap error

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2464]
In php, short_open_tag is enabled by default. 
The code `<?xml version="1.0" encoding="UTF-8"?> `in the sitemap module's sitemap-index.xml.phtml and sitemap-file.xml.phtml file causes a `syntax error, unexpected 'version' (T_STRING)" error.`
It is recommended to `<?xml version="1.0" encoding="UTF-8"?>`
change to
`<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>`

**Comment by fisharebest** [comment]
Short open tags will be deprecated in PHP 7.4 and will be removed in PHP 8.0. [link](https://wiki.php.net/rfc/deprecate_php_short_tags)

**Comment by xmlf** [comment]
However, in versions prior to php 7.4, an error occurred. Suggested amendment.
