### ISSUE TITLE
SSL hindered

### ISSUE THREAD

**Issue by janlimpens** [fisharebest/webtrees#2469]
I installed beta 3 on a ssl enabled website and it went almost ok. Only on the last page, I had to change the form target from http:// to https:// and the tree was generated, however, now, whatever link I click, http seems to be the hard coded protocol. This is pretty unusual for software written in 2019, IMHO.

**Comment by fisharebest** [comment]
Depending on your webserver configuration, it is not always possible for PHP to detect the URL.

Add the following line to the file `data/config.ini.php`:

```
base_url=https://your.site/
```

**Comment by janlimpens** [comment]
Thanks, that worked!

--
jan

https://jan.limpens.com
