### ISSUE TITLE
V2 Add Source to Event error

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2470]
When adding a source to an event, the source over-writes any existing source rather than adding and the display after saving includes markup - see image

![Add source error](https://user-images.githubusercontent.com/104515/60087882-b9eeb300-9735-11e9-9207-9e217b342db4.jpg)

**Comment by fisharebest** [comment]
It looks like you are editing an existing source citation, not adding a new one.

The "+" icon creates a new source, but for the existing citation.

To add a new source citation, expand the "source" panel.

This looks OK to me.

The displayed HTML is already covered by an existing issue.

**Comment by ddrury** [comment]
OK I see what you mean - it's not the most intuitive workflow but it works
