### ISSUE TITLE
Relationship to me runs in endless loop for "find other relationship" in some cases

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#2471]
I found some persones, where the function "find other relationship" of the relationship to me runs in an endless loop.
Below the error log of the webserver. I set the timeout/runtime of scripts to 600 seconds, but this did not change the behaviour. PHP memory is set to 1024 MB.

I have this problems in all PHP versions. I tested it with 5.6, 7.1 and 7.3 with the same result. Log is from 5.6.

The problem is only with some persons, while other persons are working.

I tested the same request with the extended relationship module from cissee.de without any problem, so I think the problem are not my data but the original relationship module.

```
[Tue Jun 25 14:13:03.907364 2019] [cgi:warn] [pid 18879] [client xx.xx.218.215:50199] AH01220: Timeout waiting for output from CGI script /home/cgi-bin/php5.6.cgi, referer: https://webtrees.xxx.de/relationship.php?pid1=I111&pid2=I1864&ged=Weiland
[Tue Jun 25 14:13:03.907426 2019] [core:error] [pid 18879] (70007)The timeout specified has expired: [client xx.xx.218.215:50199] AH00574: ap_content_length_filter: apr_bucket_read() failed, referer: https://webtrees.xxx.de/relationship.php?pid1=I111&pid2=I1864&ged=Weiland
```

Some parts of the log have been masked with xxx (-> this is not a bug) ;-)

**Comment by fisharebest** [comment]
You don't say whether this is 1.7 or 2.0.

Different code is used in both.

**Comment by HonkXL** [comment]
I am using 1.7.14.

**Comment by fisharebest** [comment]
I think this was answered in #2849
