### ISSUE TITLE
777 Permissions not workingI'm struggling to get past this screen...

### ISSUE THREAD

**Issue by umfundise** [fisharebest/webtrees#2475]
I'm struggling to get past this screen
"Setup wizard for webtrees
/var/www...../data

Oops! webtrees was unable to create files in this folder.

I have set the .../data/ directory to 777 bit still it  says I need to set these permissions.  The owner of the directory structure is apache:apache

Help please

**Comment by fisharebest** [comment]
webtrees needs permission to write files to this directory.

The setup wizard attempts to create a file data/test.txt

If this fails, you will get the message that you "probably need to make the folder world-writable" - i.e. 777).

But it can be non-writable for other reasons.

SE-Linux - or some other access control.
open-basedir-restriction in PHP.
etc.

There is no exhaustive list of reasons.  Is this your own server (which OS?) or a commercial web-host?

Perhaps create a test file something like this:

```php
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
file_put_contents('data/test', 'test');
```

Does it display an error?  Does an error get written to your webserver error log?

**Comment by fisharebest** [comment]
The lack of write-permission is most likely to be a server configuration issue, and not anything that can be fixed in the code.

If you are still having problems, you should ask on the forum at www.webtrees.net, giving as much detail as possible about your server configuration.
