### ISSUE TITLE
2.0.0-beta.3 - Hide Theme function is not working

### ISSUE THREAD

**Issue by TheRealJPS** [fisharebest/webtrees#2482]
Theme selection button appears although "hide" is activated in "Control panel | Manage family trees | Preferences | User preferences | Theme menu".

**Comment by fisharebest** [comment]
The logic for this has changed.

The themes menu is shown when more than one theme is enabled.

To disable the theme menu, you should disable all themes (except one!).

**Comment by TheRealJPS** [comment]
A simple solution that works, thanks!
