### ISSUE TITLE
RTL Media list, media item's bottom arrows have wrong direction - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2492]
The arrows are directed towards each other, they should point outwards.
Also the filename's lefthand part 1670_ prints to the right. 

![image](https://user-images.githubusercontent.com/5202996/61181796-79e36780-a633-11e9-8cee-a5a44da22c10.png)

**Comment by melizaa** [comment]
The **Hebrew page** should in my opinion be a mirror to the English page, except that the Play triangle should point to the right. Next and previous icons should not print towards each other. 
![image](https://user-images.githubusercontent.com/5202996/70847413-d1992f80-1e6c-11ea-9768-4a6c08928056.png)

The **English page**
![image](https://user-images.githubusercontent.com/5202996/70847351-78310080-1e6c-11ea-8653-d1c1fc46b8f6.png)

**Comment by fisharebest** [comment]
I think this is fixed in the latest code.

We now use the directional arrows (which get mirrored), instead of the media-fwd/back icons (which do not).
