### ISSUE TITLE
Texts cannot translate - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2493]
There are texts that are not translated.

Samples
Drag the blocks to change their position.
Add more blocks from the following list.

Choose File
No file chosen
Show

**Comment by fisharebest** [comment]
The .PO files have been updated with the latest source code.

Note that some of the text (choose file, no file chosen) are created by the browser, and will use the browser's setting, not the page setting.  There is nothing we can do about this.
