### ISSUE TITLE
Customise page: HTML blocks with ID (or similar) for a clear distinction

### ISSUE THREAD

**Issue by ungeahnt** [fisharebest/webtrees#2494]
To distinguish individual HTML blocks:
Every HTML-block has a own ID which is visible in the URL when the block is edited on the "start page" (e.g. .../block_edit.php?block_id=194).
Please make this block-Id in any manner visible to the corresponding HTML block in the table of "customise this page" .

see:
- [https://www.webtrees.net/index.php/en/forum/9-request-for-new-feature/33421-customize-page-html-blocks-with-id-or-similar](https://www.webtrees.net/index.php/en/forum/9-request-for-new-feature/33421-customize-page-html-blocks-with-id-or-similar)
and 
- [https://www.webtrees.net/index.php/en/forum/4-customising/31002-html-blocks-customize-this-page](https://www.webtrees.net/index.php/en/forum/4-customising/31002-html-blocks-customize-this-page)

**Comment by fisharebest** [comment]
> Please make this block-Id in any manner visible

The block ID is shown if you hover your mouse over the block.

<img width="230" alt="Screen Shot 2019-08-16 at 20 10 00" src="https://user-images.githubusercontent.com/2306088/63192102-27e29700-c062-11e9-80df-fe81419b0347.png">
