### ISSUE TITLE
The biography disappeared inexplicably

### ISSUE THREAD

**Issue by kexuebin** [fisharebest/webtrees#2496]
It's weird, and the biography disappears (for the second time disappeared). In recent days, there has been no access to the website server and control panel, and a lot of biographical data has disappeared.How can I restore biographical data?

**Comment by fisharebest** [comment]
It is difficult to imagine a bug that would delete just this data, without any user activity.

I have not seen this before.

If I cannot reproduce an error, I will not be able to fix it.

It is not helpful to have discussion in two places.  I will continue on the forum.

https://www.webtrees.net/index.php/en/forum/3-help-for-2-0-beta/33426-the-biography-disappeared-inexplicably
