### ISSUE TITLE
Error when xrefs are numbers in relationship search (2.0.0 beta 3)

### ISSUE THREAD

**Issue by norpan** [fisharebest/webtrees#2499]
I have some imported individuals in my tree and they have numerical ids. Webtrees creates ids starting with "I", but keeps the imported ids.

So, in this case, I get the following error when trying to show the relationship between one of these individuals and another individual.

> Argument 1 passed to Fisharebest\Webtrees\Family::getInstance() must be of the type string, int given, called in …/app/Module/RelationshipsChartModule.php on line 574 …/app/Family.php:104

My tree is public: http://familjen.eu/webtrees/index.php?route=module&module=relationships_chart&action=Chart&ged=Olivers&xref=13&xref2=I116&ancestors=0&recursion=0

(as you can see, the first person there has xref=13)

**Comment by fisharebest** [comment]
There is an annoying "feature" in PHP that will convert array keys from strings to numbers, if they look "numeric".

So, we create a string, then PHP converts it to a number and complains that it is not a string ;-)

There are probably other places in the code where similar errors occur.

**Comment by norpan** [comment]
Thanks! I'll report any more places I find.
