### ISSUE TITLE
Family report pictures one on the other - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2500]
In the Family report, Individual pictures are printed on family pictures.

Family Report
![2019-07-18_19-33-14](https://user-images.githubusercontent.com/5202996/61475372-51d96880-a993-11e9-87b2-3b7a9aad0316.jpg)

Family
![2019-07-18_19-34-12](https://user-images.githubusercontent.com/5202996/61475388-59990d00-a993-11e9-90d6-ec3aa8745515.jpg)

**Comment by melizaa** [comment]
I see this in the html report

**Comment by fisharebest** [comment]
Where can I see this error?

I do not see it on the demo site - 

https://dev.webtrees.net/demo-dev/index.php?route=report-run&ged=demo&report=family_group_report&varnames%5B%5D=famid&vars%5Bfamid%5D=f1&varnames%5B%5D=sources&vars%5Bsources%5D=on&varnames%5B%5D=notes&vars%5Bnotes%5D=on&varnames%5B%5D=photos&vars%5Bphotos%5D=on&varnames%5B%5D=blanks&varnames%5B%5D=pageSize&vars%5BpageSize%5D=A4&varnames%5B%5D=colors&vars%5Bcolors%5D=on&output=HTML

<img width="227" alt="Screen Shot 2019-08-16 at 20 05 08" src="https://user-images.githubusercontent.com/2306088/63191735-2b295300-c061-11e9-809c-41e53c9cd705.png">

**Comment by melizaa** [comment]
See for instance
(https://www.amitys.com/test/index.php?route=report-run&ged=Gedcom.ged&report=family_group_report&varnames%5B%5D=famid&vars%5Bfamid%5D=F68&varnames%5B%5D=sources&vars%5Bsources%5D=on&varnames%5B%5D=notes&vars%5Bnotes%5D=on&varnames%5B%5D=photos&vars%5Bphotos%5D=on&varnames%5B%5D=blanks&varnames%5B%5D=pageSize&vars%5BpageSize%5D=A4&varnames%5B%5D=colors&vars%5Bcolors%5D=on&output=HTML) after you sign-in.

Your sample seems to have only one media for each family individual.

**Comment by fisharebest** [comment]
The report is displaying the "family images" in the same location as the husband/father's image.

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
