### ISSUE TITLE
Layout of source with media and notes corrupted (2.0.0. beta 3)

### ISSUE THREAD

**Issue by jpretired** [fisharebest/webtrees#2502]
**2.0.0. beta 3**
On a page of individual, Facts and Events, if an event e.g. Birth contains a source with media and one or more notes, the alignment is corrupted.
See attached screenshots.
pic-1 -> all collapsed
pic-2 -> source expanded
pic-3 -> first note expanded
pic-4 -> all expanded

pic-1:
![image](https://user-images.githubusercontent.com/350656/61478499-e773f880-a991-11e9-984f-fb1d000af8fc.png)
pic-2:
![image](https://user-images.githubusercontent.com/350656/61478579-10948900-a992-11e9-9880-7b1346976396.png)
pic-3:
![image](https://user-images.githubusercontent.com/350656/61478619-2609b300-a992-11e9-87f1-7d8e67570a62.png)
pic-4:
![image](https://user-images.githubusercontent.com/350656/61478667-3de13700-a992-11e9-8363-647b9da3cfef.png)

**Comment by jpretired** [comment]
Hi Greg, I will keep your admin account to my family tree so that you can see the above issue e.g. at the individual https://test.jprodina.cz/index.php?route=individual&xref=I267&ged=tree1.
See Facts and events -> Birth
There you can also see the issue I described at webtrees forum i.e. https://www.webtrees.net/index.php/en/forum/3-help-for-2-0-beta/33451-markdown-formatting-fails

**Comment by dbq-andersons** [comment]
Looks like #1907 that I reported last year; we can close that one and continue off this one.
