### ISSUE TITLE
Calendar year selection and help - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2507]
I do no longer see the help text to the calendar year selection options and only the specific year option seems to work.

**Comment by fisharebest** [comment]
The year range functions were removed.

They were confusing, and didn't work very well.

**Comment by melizaa** [comment]
I use the year range selection in pre 2.0.0.
It enables me to select a group of people in one try.

Do we have some other option in webtrees to select all the people who were born for instance in 17xx or 1910-1915?

**Comment by fisharebest** [comment]
> Do we have some other option in webtrees to select all the people who were born for instance in 17xx or 1910-1915?

The advanced search can find people born in a year, +/- 2, 5, 10 years

**Comment by fisharebest** [comment]
> The advanced search can find people born in a year, +/- 2, 5, 10 years

I have added more range options to the advanced search: ±1, 2, 5, 10, 20 years

This should give you the function you requested.
