### ISSUE TITLE
Relationships "relationship recursion" - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2510]
Does the Chart preferences - Relationships "relationship recursion" change work? 

What should it do?

I select a value and save and I do not see the selected value.
Also, I see the same relationships after I change the selection values.

**Comment by melizaa** [comment]
I see in the log
Tree preference "RELATIONSHIP_RECURSION" set to ""

**Comment by fisharebest** [comment]
> What should it do?

First, we calculate the shortest path(s).

Then, (1st level of recursion), we eliminate each family in the path in turn - and see if further paths can be found that do not use this family.

Then, (2nd level of recursion), we do the same for the new paths found above.

When a tree has many loops, then it may not be possible to find *every* path.  So, for these complex trees, you can limit the recursion.

For simple trees (with no loops), then this setting makes no difference.
