### ISSUE TITLE
End of line special characters print on the wrong side of the line - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2514]
End of line special characters print on rtl pages to the wrong side of the text.

Samples:
- Indi/family edit page in Chrom, FF, IE - Place help text - two lines have the end of the line " to the right of the Hebrew text.
- Korea (North) - End ) printed to the left of K in the rtl Control Panel Map Geographic data - same for other places with special characters

I do not think that the solution to these cases is to update the language records by moving the ", ) or full stops (etc.) to the beginning of the line, instead of to the end of the line.

**Comment by fisharebest** [comment]
> Indi/family edit page in Chrom, FF, IE - Place help text

This is a very text, and the error is not obvious to me.

Perhaps it is better to re-write the help text.  We should not encourage empty place names: `village, , , country`.

They are only necessary if you are using structured place hierarchies (with the `PLAC\FORM` tag).
To my knowledge, no genealogy application uses `FORM`.

> Korea (North) 

Are there any place names that officially end with a parenthesis?

The official name is "North Korea" or "Democratic People's Republic of Korea".
