### ISSUE TITLE
RTL new user request - wrong message language - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2516]
New rtl page user request - the online message that the user sees is in English.

**Comment by fisharebest** [comment]
I changed the language to French.
I registered a new user.
The new user received an email in French.

How do I reproduce the problem?

**Comment by melizaa** [comment]
A new user request was created on the Hebrew page.
The user sees the following after the action
![image](https://user-images.githubusercontent.com/5202996/63089102-7a875a80-bf5f-11e9-9ae4-a39d0b1d037d.png)

**Comment by melizaa** [comment]
also, text "Duplicate username. A user with that username already exists. Please choose another username" is printed in English for the Hebrew user request.
