### ISSUE TITLE
The change report in the report has an error

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2518]
`Call to a member function facts() on null …/app/Report/ReportParserGenerate.php:1310
#0 …/app/Report/ReportParserGenerate.php(183): Fisharebest\Webtrees\Report\ReportParserGenerate->factsStartHandler(Array)
#1 …/app/Report/ReportParserGenerate.php(2298): Fisharebest\Webtrees\Report\ReportParserGenerate->startElement(Resource id #468, 'Facts', Array)
#2 [internal function]: Fisharebest\Webtrees\Report\ReportParserGenerate->Fisharebest\Webtrees\Report\{closure}(Resource id #468, 'Facts', Array)
#3 …/app/Report/ReportParserGenerate.php(2312): xml_parse(Resource id #468, '<tempdoc>\n\t\t\t\t\t...', true)
#4 …/app/Report/ReportParserGenerate.php(206): Fisharebest\Webtrees\Report\ReportParserGenerate->listEndHandler()
#5 …/app/Report/ReportParserBase.php(53): Fisharebest\Webtrees\Report\ReportParserGenerate->endElement(Resource id #424, 'List')
#6 [internal function]: Fisharebest\Webtrees\Report\ReportParserBase->Fisharebest\Webtrees\Report\{closure}(Resource id #424, 'List')
#7 …/app/Report/ReportParserBase.php(71): xml_parse(Resource id #424, 'tBox height="12...', true)
#8 …/app/Report/ReportParserGenerate.php(151): Fisharebest\Webtrees\Report\ReportParserBase->__construct('/home/wwwroot/j...')
#9 …/app/Http/Controllers/ReportEngineController.php(243): Fisharebest\Webtrees\Report\ReportParserGenerate->__construct('/home/wwwroot/j...', Object(Fisharebest\Webtrees\Report\ReportHtml), Array, Object(Fisharebest\Webtrees\Tree))
#10 [internal function]: Fisharebest\Webtrees\Http\Controllers\ReportEngineController->reportRun(Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Tree))
#11 …/app/Application.php(45): ReflectionMethod->invoke(Object(Fisharebest\Webtrees\Http\Controllers\ReportEngineController), Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Tree))
#12 …/app/Http/Middleware/RequestRouter.php(73): Fisharebest\Webtrees\Application->dispatch(Object(Fisharebest\Webtrees\Http\Controllers\ReportEngineController), 'reportRun')
#13 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestRouter->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#14 …/app/Http/Middleware/ModuleMiddleware.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ModuleMiddleware->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#16 …/app/Http/Middleware/BootModules.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#18 …/app/Http/Middleware/UseTransaction.php(44): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#20 …/app/Http/Middleware/CheckCsrf.php(63): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#22 …/app/Http/Middleware/DoHousekeeping.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))`

**Comment by fisharebest** [comment]
I guess that this error is caused by corrupt data.

I guess that you have a link to a record that does not exist.

If you use the "check for errors" function in the control panel, does it find any broken links?

**Comment by fisharebest** [comment]
Did you find any corrupt data?

What was it?

**Comment by xmlf** [comment]
Yes.Errors are caused by #2530.
