### ISSUE TITLE
0 _TODO Record Blocks Imports

### ISSUE THREAD

**Issue by samiona2** [fisharebest/webtrees#2520]
A zero level _TODO tag will block a GEDCOM import on 2.0 b3. The same GEDCOM will import without issues in the 1.7.8 branch. While it may be invalid (I am not sure of this, but the 1.7 code seems to ignore this record, or at least not display it in the Research Tasks block), it should not block the import. Here is the record that blocks the import.
```
0 _TODO
1 DESC Email John Smith about Joe's Family
1 DATE 11 Apr 2004
1 STAT Open
1 TYPE 0
1 PRTY 8
1 REPO @R0@
1 NOTE Email John Smith about Joe's Family.
2 CONT example@example.com
```

**Comment by fisharebest** [comment]
Can you post the *full* record.

I guess the problem is in the `0` line - which you do not include.

**Comment by samiona2** [comment]
@fisharebest  I updated the above. The 0 row was there and it was actually a markdown "issue" that hid it. It would be nice if the Research Task would show such general TODO notes if they are not really invalid.

**Comment by fisharebest** [comment]
Records need an identifier.  e.g.

```
0 @x1234@ _TODO
```

At present, invalid records can break the import.  We should simply ignore them.

**Comment by fisharebest** [comment]
This is the same bug as #2480
