### ISSUE TITLE
Use silhouettes = no Setting Ignored in 2.0 b3

### ISSUE THREAD

**Issue by samiona2** [fisharebest/webtrees#2521]
Setting "Use silhouettes" to No in the settings are ignored by 2.0 b3, and the silhouettes continue to display.

**Comment by fisharebest** [comment]
Works for me.  Here are screenshots from the demo site, with/without silhouettes:

<img width="663" alt="Screenshot 2019-08-09 at 15 54 07" src="https://user-images.githubusercontent.com/2306088/62788075-162b4d80-babe-11e9-8517-6e2efc9b8aec.png">
<img width="743" alt="Screenshot 2019-08-09 at 15 55 00" src="https://user-images.githubusercontent.com/2306088/62788080-162b4d80-babe-11e9-9eb6-dc5a66b9f107.png">

**Comment by samiona2** [comment]
@fisharebest  Sorry for the delay in responding. I thought that this would impact the silhouettes on the individual page when there is no photo. Is there any reason that is not controlled from this setting?

**Comment by fisharebest** [comment]
> Is there any reason that is not controlled from this setting?

The link to add a new image is underneath the silhoutte.

If we did not show the silhouette on the individual page, there would just be a gap.
