### ISSUE TITLE
Restrict Social Security Number to Members 2.0 - How To?

### ISSUE THREAD

**Issue by samiona2** [fisharebest/webtrees#2522]
By default Social Security Numbers are shown only to managers. I deleted this record in an attempt to set it to members, but there seems to be no way to add such a record in the UI in 2.0 b3.
While I can add a note restriction to a specific note, I can't add a global note restriction to members.

**Comment by samiona2** [comment]
I figured it out. It is far from intuitive (to me), but I will close this. I guess that I figured out the identical process in 1.7.8 in the past, but forgot.

**Comment by fisharebest** [comment]
> It is far from intuitive

Did you not find the privacy page?
Did you find the page, but not understand how the restrictions work?

What would make it "more intuitive"?
