### ISSUE TITLE
Show More Information in Research Tasks Block for Legacy _TODO

### ISSUE THREAD

**Issue by samiona2** [fisharebest/webtrees#2523]
My _TODO records may be odd (thank you Legacy Family Tree for probably exporting things in an odd format), and this results in the Research Task not showing any text besides the linked name. In 1.7.8 the date shows up, and in 2.0 b3 only the name appears (there is no date column, at least in the narrow view). The actual research task remains blank. Shouldn't the DESC text or even the NOTE show up?
Thanks

```
1 _TODO
2 DESC Verify 1936 - 1939 Residence at 123 Main St.
2 DATE 23 Mar 2012
2 _RDATE 23 Apr 2012
2 STAT Open
2 TYPE 0
2 PRTY 8
2 NOTE They had a neighbor Edward and Sylvia Smith with a Daugh
3 CONC ter Jane. Check the 1940 census in case they were there i
3 CONC n ...
```

**Comment by fisharebest** [comment]
I have never seen this format before.

webtrees uses the following format.  I *think* it was created by Family Tree Maker.  I *think* that other applications also use this format.

```
1 _TODO description of task
2 DATE 23 JUL 2019
```

webtrees also adds `2 _WT_USER xxxx` to this - to assign tasks to users.

**Comment by samiona2** [comment]
Thank you. It would be a nice enhancement (for me at least :) ), but with 201 other open tickets, this is probably a very low priority. Thanks for all you do for the project.

**Comment by Gunnar-GO** [comment]
since this works

> 1 _TODO description of task
> 2 DATE 23 JUL 2019

Could be the DATE optional?

**Comment by fisharebest** [comment]
> Could be the DATE optional?

Not easily.

webtrees stores data as GEDCOM records.

To find records, we have indexes of dates, places and links.

We use the index of dates to find the _TODO records.

Without a date, it is difficult (i.e. slow/ineffecient) to find them.

**Comment by fisharebest** [comment]
These tags are now supported by the "Legacy Custom Tags" module.
