### ISSUE TITLE
Bulletted or Numbered lists in the News and Journal blocks, print empty lines - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2525]
I see empty lines between text groups. The text looks OK on the edit form.
Removing the /li-s removes one empty line, one unnecessary empty line remains.
Editing the entry adds all the /li-s.

It seems that in wt2.0.0 (CKEditor 4.11.2) li and /li add an unnecessary empty line.
Pre 2.0.0 (CKEditor 4.5.2) did not add these lines.
I do not see these empty lines in CKEditor 4 samples.

**Comment by fisharebest** [comment]
It is not clear what you mean by "unnecessary empty line"?

Block-level elements (paragraph, list, etc.) all have spaces between them.

The spacing in CKEditor should be the same as the spacing in the rest of the application.

**Comment by melizaa** [comment]
Please look at the News of my test-test system, even without logging in.
Is this how wt prints lists? I do not think it is. When I look at the Pending changes, Top surnames or given-names lists, there are no empty lines.
Where else can I see bulleted or numbered lists?

I tried to add to the demo-dev moderator's page my news/journal text.
I do not see where I can edit the text or define the bullets/numbers.

**Comment by melizaa** [comment]
I added the bulleted/numbered text to an html block (under the Statistics block).
It looks great, without the added empty lines.

**Comment by fisharebest** [comment]
> Please look at the News of my test-test system, even without logging in.

I am not an admin on this site.  I cannot see the HTML content of this block.

I see the blank lines, but perhaps the HTML contains blank lines?

**Comment by fisharebest** [comment]
The HTML block has `style="whitespace: pre-wrap"`.

Need to check why this is there.

**Comment by melizaa** [comment]
Why did you close this?
I see still the 'empty' lines.
The html block looks as expected. 

I tried to add to the News block <div style="whitespace: pre-wrap">.
It did not solve the issue.
When I look at the source after I saved the above, I see only <div>

**Comment by fisharebest** [comment]
> Why did you close this?

Because it is now fixed?

<img width="348" alt="Screen Shot 2019-08-11 at 09 10 55" src="https://user-images.githubusercontent.com/2306088/62831483-fad45580-bc17-11e9-965e-ced1d2796270.png">

**Comment by melizaa** [comment]
I see it now on my test test site OK in the Journal block.
The News block is not yet OK.

I will test later in the future test site.

**Comment by melizaa** [comment]
I think that news uses resources/views/modules/gedcom_news/list.phtml.

Also future test has the issue.

**Comment by melizaa** [comment]
I changed this file locally. It solves the issue of the news.
