### ISSUE TITLE
Message for deletion of media files does not display special chars correctly

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#2526]
I created a media file called ZZZ-TEST.JPG and deleted this in the Control-Panel / Media / Manage Media later.

Then I get a message "Are you sureyou want to delete "ZZZ\x2DTEST.JPG"?
So I get \x2D instead of -

See screenshot:

![delete-media2](https://user-images.githubusercontent.com/16715040/62194906-15d2da00-b37b-11e9-9779-8247a3984f9d.jpg)

**Comment by fisharebest** [comment]
This has already been fixed in the 2.0 code

**Comment by fisharebest** [comment]
This issue is fixed in 2.0.0, which is now released.
