### ISSUE TITLE
Daily or Monthly calendar - same birth and death day and month - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2527]
If a person was born and died on the same day&month - we should see the earlier birth data before the later death data.

![image](https://user-images.githubusercontent.com/5202996/62311963-a30a5180-b495-11e9-8f8c-69743b9b42ff.png)

**Comment by melizaa** [comment]
I see still the following
![image](https://user-images.githubusercontent.com/5202996/62830877-b7c9b080-bc1e-11e9-9ec4-d46b87776540.png)
The death is recorded in the Gedcom file before the birth.

**Comment by fisharebest** [comment]
The facts are now sorted by date.

If the events were in different years, then no problem.

We can't sort by event-type using a database query.
