### ISSUE TITLE
Improve source statistics query and module permission settings

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2529]
There are thousands of pieces of data in a single source or individual list on my site, which can be slow to open and run out of server resources.
I think this is very unreasonable.
Although I set the permissions of the background module to "Show to members", the input url is still accessible without logging in.
suggestions below:
1. Improve data query methods in source statistics.
2. When the module permission is set to "Show to member", the visitor should display "no access" or 403

**Comment by fisharebest** [comment]
A source will be private if it is linked to any private records.

If a source is linked to 1000 individuals, then webtrees must check the privacy of 1000 individuals to calculate the privacy of the source.

But if the source has a privacy restriction (e.g. `0 @x123@ SOUR / 1 RESN privacy`), then webtrees can calculate the privacy immediately.

So, for sources that are linked to many records, you can improve performance by adding a privacy restriction.  e.g. "Show to public" or "Show to members".

**Comment by fisharebest** [comment]
> Although I set the permissions of the background module to "Show to members", the input url is still accessible without logging in.

Which module?
Which URL?

**Comment by xmlf** [comment]
1. Individual data in genealogy are derived from many books. If there are 5,000 individuals on a book, then by source statistics, opening this source can be very slow and exhausts server resources.
2, Not just the source, the list - this is also the case in the individual list. If a surname or a name contains a lot of individuals, it will also exhaust the server resources.

This problem exists in the modules in the list. If "Show to member" is set in the control panel, the user who is not logged in can not see it, but can still access it by directly inputting the url.
For example: set the display to members in the control panel, list, and individual list. Unlogged in users can still enter https://dev.webtrees.net/demo-dev/index.php?route=module&module=individual_list&action=List&ged=demo
access.

**Comment by xmlf** [comment]
In addition, the pending change page suggestions can also be paged.
Currently I have more than 5,000 pending change records, and opening the pending changes page is very slow.

**Comment by fisharebest** [comment]
> 1...
> 2...

Please create only one issue for each problem.

The source list is slow because we cannot use pagination on data that requires privacy checks.
e.g. we cannot know how many sources to show in the list unless we check all of them.

You can improve performance by adding a privacy restriction (1 RESN ...) to sources that are linked to many records.

This allows us to know the privacy instantly.
Otherwise, we must check the privacy of every linked record.
