### ISSUE TITLE
2.0 GEDCOM record from clippings cart incomplete

### ISSUE THREAD

**Issue by jpretired** [fisharebest/webtrees#2531]
Display an individual to be added to clippings cart:
![image](https://user-images.githubusercontent.com/350656/62422737-8188b000-b6b7-11e9-8db9-9255e29fac7c.png)
Add it to clippings cart:
![image](https://user-images.githubusercontent.com/350656/62422744-95ccad00-b6b7-11e9-80bf-43427aa1f846.png)
Download the clippings cart:
![image](https://user-images.githubusercontent.com/350656/62422755-b5fc6c00-b6b7-11e9-95de-1639fabac43d.png)
 The GEDCOM record so generated is incomplete. All links to spouses, children, sources etc. are missing. The choice of option for adding makes no difference.

**Comment by fisharebest** [comment]
I cannot reproduce this.  It works OK for me.

> All links to spouses, children, sources etc. are missing.

So, the GEDCOM file contains only the one individual, matous spunda?

(stupid question).  Does matous have children, sources, etc.?

**Comment by jpretired** [comment]
The demo site latest beta does not allow me to work with clippings cart so I could not try to reproduce the issue with it.
My family tree site (webtrees version 2.0 beta.3) is https://test.jprodina.cz/index.php?route=tree-page&ged=tree1
There are two trees: "Naše rodina (test wt v2)" and "Small family".
The individual Matouš Špunda mentioned above is https://test.jprodina.cz/index.php?route=individual&xref=I267&ged=tree1
The original GEDCOM record of this individual is:
`@I267@ INDI
1 NAME Matouš /Špunda/
2 GIVN Matouš
2 SURN Špunda
1 SEX M
1 BIRT
2 DATE 30 JAN 1856
2 PLAC Lutín, Olomoucký, Česko
2 ADDR Lutín č. 9
2 SOUR @S23@
3 PAGE snímek http://digi.archives.cz/da/permalink?xid=be96ed78-f13c-102f-8255-0050568c0263&scan=251
3 DATA
4 TEXT (1856 Lutín)
5 CONT 30. ledna v č. 9 narozen, 31. pokřtěn Matouš, manželský syn.
5 CONT (Připsáno: Sezd. 10/11/1879 s Filomenou Bernátovou. † 17/11/1942.)
5 CONT Otec: Matouš Špunda, sedlák v Lutíně, syn Ignáce Špundy, sedláka v Lutíně, a jeho manželky Rozálie, dcery Bartoloměje Procházky, sedláka v Luběnicích.
5 CONT Matka: Anna, dcera Tomáše Dočkala, sedláka ve Slatinicích, a jeho manželky Mariany, dcery Františka Ošťádala, sedláka ve Slatinicích.
5 CONT Kmotři: Šebestián Liška, sedlák v Lutíně, Františka, jeho manželka.
3 QUAY 3
3 OBJE @M1198@
2 SOUR @S103@
3 QUAY 0
3 OBJE @M1663@
2 NOTE @X3@
1 DEAT
2 DATE 17 NOV 1942
2 PLAC Lutín, Olomoucký, Česko
2 ADDR Lutín č. 45
2 SOUR @S126@
3 PAGE snímek http://digi.archives.cz/da/permalink?xid=be96e9f4-f13c-102f-8255-0050568c0263&scan=254
3 DATA
4 TEXT Špunda Matouš 17/11/1942 Lutín č. 45, str. 110
2 NOTE Datum úmrtí také podle matriky N.
1 OCCU rolník
1 FAMS @F21@
1 FAMC @F19@
1 OBJE @M278@
1 OBJE @M49@
1 CENS
2 DATE 31 DEC 1880
2 PLAC Lutín, Olomoucký, Česko
2 SOUR @S82@
3 DATA
4 TEXT "Czech Republic Censuses, 1800-1945," images, <i>FamilySearch</i> (https://familysearch.org/pal:/MM9.3.1/TH-1951-39274-1192-49?cc=1930345 : accessed 14 March 2016), Olomouc &gt; Lutín &gt; 1880 &gt; 227102010-000567-001317-000081-000081-01-OL0447
5 CONC  &gt; image 26 of 141; Moravský Zemský Archiv, Brně (Moravian Land Archives, Brno).
3 PAGE snímek https://familysearch.org/ark:/61903/3:1:3QS7-996K-Q9CG
3 OBJE @M153@
2 NOTE @N4@
1 _WT_OBJE_SORT @M278@
1 _WT_OBJE_SORT @M49@
1 _WT_OBJE_SORT @M153@
1 _WT_OBJE_SORT @M325@
1 _WT_OBJE_SORT @M529@
1 _WT_OBJE_SORT @M518@
1 _WT_OBJE_SORT @M519@
1 CENS
2 DATE 15 FEB 1921
2 PLAC Lutín, Olomoucký, Česko
2 ADDR Lutín č. 45
2 SOUR @S83@
3 QUAY 0
3 PAGE snímek https://familysearch.org/ark:/61903/3:1:3QS7-L96Q-1QQ9
3 DATA
4 TEXT "Czech Republic Censuses and Inhabitant Registers, 1800-1990," images, FamilySearch (https://familysearch.org/ark:/61903/3:1:3QS7-L96Q-1QQ9?cc=1930345&wc=Q67Z-FBX%3A226978201%2C1291677704%2C226974303%2C1291677703 : 25 July 2014), Olomouc > Lutín
5 CONC  > 1921 > image 196 of 373; Moravský Zemský Archiv, Brně (Moravian Land Archives, Brno).
3 OBJE @M2378@
2 NOTE @N48@
2 NOTE @X3@
1 CHAN
2 DATE 29 JUL 2019
3 TIME 15:28:12
2 _WT_USER admin`

The GEDCOM record downloaded from clippings cart is:
`0 @I267@ INDI
1 NAME Matouš /Špunda/
2 GIVN Matouš
2 SURN Špunda
1 SEX M
1 BIRT
2 DATE 30 JAN 1856
2 PLAC Lutín, Olomoucký, Česko
2 ADDR Lutín č. 9
1 DEAT
2 DATE 17 NOV 1942
2 PLAC Lutín, Olomoucký, Česko
2 ADDR Lutín č. 45
2 NOTE Datum úmrtí také podle matriky N.
1 OCCU rolník
1 CENS
2 DATE 31 DEC 1880
2 PLAC Lutín, Olomoucký, Česko
1 CENS
2 DATE 15 FEB 1921
2 PLAC Lutín, Olomoucký, Česko
2 ADDR Lutín č. 45
1 CHAN
2 DATE 29 JUL 2019
3 TIME 15:28:12
2 _WT_USER admin
1 SOUR @WEBTREES@
2 PAGE https://test.jprodina.cz/index.php?route=individual&xref=I267&ged=tree1`

I set an administration user for you so that you can try the issue with my family test website. I am sending an e-mail to you with the information.

**Comment by xmlf** [comment]
Yes. Clippings cart is problematic, the downloaded record is incomplete, such as missing family records.

**Comment by fisharebest** [comment]
> I set an administration user for you so that you can try the issue with my family test website. I am sending an e-mail to you with the information.

Thanks.  The clippings cart contains families, sources, individuals, etc.
I still cannot see what exactly is missing.

**Comment by xmlf** [comment]
> > I set an administration user for you so that you can try the issue with my family test website. I am sending an e-mail to you with the information.
> 
> Thanks. The clippings cart contains families, sources, individuals, etc.
> I still cannot see what exactly is missing.
Have you tried importing the clippings cart file into a new family tree?
Family relationships have all been lost.

**Comment by jpretired** [comment]
>  Family relationships have all been lost.
Not only, also sources, media objects etc. were lost.

**Comment by fisharebest** [comment]
Thanks - I see it now.
