### ISSUE TITLE
1.7.14 On this day module error

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2532]
Sort by Date doesn't work properly, the problem is that FunctionsDB::getEventsList isn't actually returning an array sorted in date order

**Comment by fisharebest** [comment]
This seems to work OK for me.

Are you using the list view or the table view?

With tables, the user can change the order by clicking in the headers - and their selection will be remembered by the browser.

**Comment by ddrury** [comment]
List,, and I think it happens when there is a mix of individual & family events

**Comment by fisharebest** [comment]
Just noticed that you are refering to wt 1.7.

I can't reproduce this on 1.7 either.

**Comment by ddrury** [comment]
Hm,
I'll investigate further but as you don't see it and it is on 1.7, I'll close this
