### ISSUE TITLE
2.0-A lot of error logs, what is the reason?

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2534]
`Return value of Fisharebest\Webtrees\Family::Fisharebest\Webtrees\{closure}() must be an instance of Fisharebest\Webtrees\Family, null returned …/app/Family.php:75 #0 [internal function]: Fisharebest\Webtrees\Family::Fisharebest\Webtrees\{closure}(Object(stdClass), 576) #1 …/vendor/illuminate/support/Collection.php(1120): array_map(Object(Closure), Array, Array) #2 …/app/Http/Controllers/AutocompleteController.php(140): Illuminate\Support\Collection->map(Object(Closure)) #3 [internal function]: Fisharebest\Webtrees\Http\Controllers\AutocompleteController->page(Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Tree)) #4 …/app/Application.php(45): ReflectionMethod->invoke(Object(Fisharebest\Webtrees\Http\Controllers\AutocompleteController), Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Tree)) #5 …/app/Http/Middleware/RequestRouter.php(73): Fisharebest\Webtrees\Application->dispatch(Object(Fisharebest\Webtrees\Http\Controllers\AutocompleteController), 'page') #6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestRouter->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #7 …/app/Http/Middleware/ModuleMiddleware.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ModuleMiddleware->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #9 …/app/Http/Middleware/BootModules.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #11 …/app/Http/Middleware/UseTransaction.php(44): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #13 …/app/Http/Middleware/CheckCsrf.php(63): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #15 …/app/Http/Middleware/DoHousekeeping.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #17 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #19 …/app/Http/Middleware/CheckForMaintenanceMode.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #21 …/app/Http/Middleware/UseLocale.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLocale->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #23 …/app/Http/Middleware/UseTree.php(59): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTree->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #25 …/app/Http/Middleware/UseSession.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #27 …/app/Http/Middleware/UseFilesystem.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseFilesystem->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #29 …/app/Http/Middleware/UseCache.php(44): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #31 …/app/Http/Middleware/UpdateDatabaseSchema.php(56): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #33 …/app/Http/Middleware/UseDebugbar.php(64): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #35 …/app/Http/Middleware/UseDatabase.php(85): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #37 …/app/Http/Middleware/ReadConfigIni.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #39 …/app/Http/Middleware/HandleExceptions.php(54): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #41 …/app/Http/Middleware/EmitResponse.php(52): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #43 …/app/Http/Middleware/PhpEnvironment.php(46): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #45 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #46 …/index.php(40): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #47 {main}`

**Comment by fisharebest** [comment]
This error suggests that you have a row in the database table wt_families, which does not contain a valid family record (`0 FAM @xxxx@`).

**Comment by xmlf** [comment]
I checked all the records, the all record  contain vaild format is
'0 @XXXX@ FAM'

**Comment by fisharebest** [comment]
This error is in the autocomplete for a source-citation (GEDCOM `PAGE`)

We fetch a row from the wt_families table in the database.
We merge pending changes.
We check the record.  It is not a family record.

**Comment by xmlf** [comment]
Thank you for your help.
I think I might find the cause of the error.
X9917 exists in both wt_families and wt_individuals tables.
![1](https://user-images.githubusercontent.com/26761596/62863461-6fec7b80-bd3b-11e9-930b-67deaa630f3f.PNG)
![2](https://user-images.githubusercontent.com/26761596/62863465-71b63f00-bd3b-11e9-8bd3-7b0512346ac1.PNG)

The reason for this error, I think it is the same as this.
One is adding one family and the other is adding one individual.
When two people submit data in the same second, it will cause data confusion.
I hope that the family xref can start with F (Fxxxx),the individual starts with I (Ixxxx), the media starts with M (Mxxx). This can be consistent with other genealogy software.

**Comment by fisharebest** [comment]
> X9917 exists in both wt_families and wt_individuals tables.

This will explain the error.

> When two people submit data in the same second, it will cause data confusion.

This should not be possible.

The sequence number is stored in the table `wt_site_setting` (`next_xref`).
We update it inside a transaction, using a database lock.
https://github.com/fisharebest/webtrees/blob/master/app/Tree.php#L736

Have you modified your MySQL server configuration?
Perhaps the "transaction isolation level"?
https://dev.mysql.com/doc/refman/8.0/en/innodb-transaction-isolation-levels.html

**Comment by xmlf** [comment]
#2533 Explain in detail under what circumstances this error will occur.If the database lock is working, then x9917 should not appear in both the family and individual tables.For example, the value of next_xref is now 1.
When two people save the added individuals I1 and I2 in the same family for F1 and F2, I1 and I2 will only save one success, the other will be lost, and I1 may be added. F2 family.

**Comment by fisharebest** [comment]
Testing:

Session 1 takes a lock.

```
mysql> START TRANSACTION;
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT * FROM wt_site_setting WHERE setting_name='next_xref' FOR UPDATE;
+--------------+---------------+
| setting_name | setting_value |
+--------------+---------------+
| next_xref    | 3826          |
+--------------+---------------+
1 row in set (0.00 sec)
```

Session 2 waits, because session 1 has a lock.

```
mysql> START TRANSACTION;
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT * FROM wt_site_setting WHERE setting_name='next_xref' FOR UPDATE;
```

Session 1 commits the transaction and releases the lock.

```
mysql> UPDATE wt_site_setting SET setting_value=3827 WHERE setting_name='next_xref';
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> COMMIT;
Query OK, 0 rows affected (0.00 sec)
```

Session 2 can now continue.

```
+--------------+---------------+
| setting_name | setting_value |
+--------------+---------------+
| next_xref    | 3827          |
+--------------+---------------+
1 row in set (23.08 sec)
```

What database engine do you use (e.g. InnoDB)?
You can see this if you run the command `SHOW CREATE TABLE wt_site_setting;`.

What transaction isolation level do you use?
You can see this if you run the command `SHOW VARIABLES LIKE 'transaction_isolation';`

**Comment by xmlf** [comment]
I have done tests before, before I used MYISAM, and later changed to Innodb. 
This problem is true whether the database engine is myisam or Innodb.

SHOW VARIABLES LIKE 'transaction_isolation'; 
The result is null.

select @@tx_isolation;
The result is:
REPEATABLE-READ

**Comment by fisharebest** [comment]
> This problem is true whether the database engine is myisam or Innodb.

MyISAM does not support transactions.
The code relies on transactions.
I would expect the code to fail with MyISAM.

webtrees specifies InnoDB in the database connection:
https://github.com/fisharebest/webtrees/blob/master/app/Http/Middleware/UseDatabase.php#L65
https://github.com/fisharebest/webtrees/blob/master/app/Http/Controllers/SetupController.php#L460

> From the binary log file, it can be seen that next_xref is not updated in some cases.

I see it.

We need to understand how this is happening.

What version of MySQL (or MariaDB)?

**Comment by xmlf** [comment]
5.5.62-MariaDB

**Comment by xmlf** [comment]
When you open two new add individual pages, enter the information and save it in the same second, you should reproduce this error.

**Comment by fisharebest** [comment]
> save it in the same second

This will require two computers.

I am on vacation, and only have one computer with me.

**Comment by xmlf** [comment]
Recently I upgraded mariab to version 10.2.
When operating at the same time, the following error message appears, need to return and resubmit before it can succeed.
`SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction (SQL: delete `wt_places` from `wt_places` left join `wt_placelinks` on `p_id` = `pl_p_id` and `p_file` = `pl_file` where `pl_p_id` is null) …/vendor/illuminate/database/Connection.php:664 #0 …/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('delete `wt_plac...', Array, Object(Closure)) #1 …/vendor/illuminate/database/Connection.php(490): Illuminate\Database\Connection->run('delete `wt_plac...', Array, Object(Closure)) #2 …/vendor/illuminate/database/Connection.php(435): Illuminate\Database\Connection->affectingStatement('delete `wt_plac...', Array) #3 …/vendor/illuminate/database/Query/Builder.php(2771): Illuminate\Database\Connection->delete('delete `wt_plac...', Array) #4 …/app/Functions/FunctionsImport.php(1146): Illuminate\Database\Query\Builder->delete() #5 …/app/Functions/FunctionsImport.php(1097): Fisharebest\Webtrees\Functions\FunctionsImport::updateRecord('0 @I43058@ INDI...', Object(Fisharebest\Webtrees\Tree), false) #6 …/app/GedcomRecord.php(1215): Fisharebest\Webtrees\Functions\FunctionsImport::acceptAllChanges('I43058', Object(Fisharebest\Webtrees\Tree)) #7 …/app/Http/Controllers/EditGedcomRecordController.php(459): Fisharebest\Webtrees\GedcomRecord->updateFact('NOT A VALID FAC...', '1 RESI\n2 PLAC \xE7...', true) #8 [internal function]: Fisharebest\Webtrees\Http\Controllers\EditGedcomRecordController->updateFact(Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Tree)) #9 …/app/Application.php(45): ReflectionMethod->invoke(Object(Fisharebest\Webtrees\Http\Controllers\EditGedcomRecordController), Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Tree)) #10 …/app/Http/Middleware/RequestRouter.php(73): Fisharebest\Webtrees\Application->dispatch(Object(Fisharebest\Webtrees\Http\Controllers\EditGedcomRecordController), 'updateFact') #11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestRouter->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #12 …/app/Http/Middleware/ModuleMiddleware.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #13 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ModuleMiddleware->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #14 …/app/Http/Middleware/BootModules.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #16 …/app/Http/Middleware/UseTransaction.php(44): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #18 …/app/Http/Middleware/CheckCsrf.php(63): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #20 …/app/Http/Middleware/DoHousekeeping.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #22 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #24 …/app/Http/Middleware/CheckForMaintenanceMode.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #26 …/app/Http/Middleware/UseLocale.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLocale->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #28 …/app/Http/Middleware/UseTree.php(59): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTree->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #30 …/app/Http/Middleware/UseSession.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #32 …/app/Http/Middleware/UseFilesystem.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseFilesystem->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #34 …/app/Http/Middleware/UseCache.php(44): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #36 …/app/Http/Middleware/UpdateDatabaseSchema.php(56): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #38 …/app/Http/Middleware/UseDebugbar.php(64): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #40 …/app/Http/Middleware/UseDatabase.php(85): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #42 …/app/Http/Middleware/ReadConfigIni.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #44 …/app/Http/Middleware/HandleExceptions.php(54): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #46 …/app/Http/Middleware/EmitResponse.php(52): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #48 …/app/Http/Middleware/PhpEnvironment.php(46): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #50 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #51 …/index.php(40): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #52 {main}`
