### ISSUE TITLE
1.7.14 On this day & Upcoming events sort

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2536]
Further to #2532.

I attach an image from the upcoming events module as it's easier to demonstrate the problem (uses same code as on this day - FunctionsPrintLists::getEventsList())

```
        for ($jd = $jd1; $jd <= $jd2; ++$jd) {
            $found_facts = array_merge($found_facts, self::getAnniversaryEvents($jd, $events, $tree));
        }
```

The problem is that in the above loop $found_facts grows for each iteration through the loop and as the keys of this array are numeric they get added to the end each time through the loop.

This is fine but you'll see in the attached image although the day and month are sequential the years are all over the place - surely they should be taken into account too given that the option is "Sort by date"?

![demo](https://user-images.githubusercontent.com/104515/62870283-4f0f3080-bd11-11e9-9231-464b5ad532cf.jpg)

**Comment by fisharebest** [comment]
This issue is fixed in 2.0.0, which is now released.
