### ISSUE TITLE
2.0 : Add register link when all trees private

### ISSUE THREAD

**Issue by dverdin** [fisharebest/webtrees#2539]
Dear all,

I have a site with a single family tree, that I would like to save for my family because it contains a lot of private data.

When I made everything reserved to registered members, it works as expected : anyone not authenticated is redirected to the login page.

However, there is no link to the register page, making it impossible for my family members to create an account.

Reading the code, I found the following comment in login-page.phtml :

```
            <!--
            Emails are sent from a TREE, not from a SITE. Therefore if there is no
            tree available (initial setup or all trees private), then we can't send email.
            -->
```
Though I understand the application logic, it makes my own setup unfeasable.
I had a workaround by making a dummy empty tree which lets people access the normal login page containing the register link.

I don't understand why it does not seem possible to have only private trees and still let people register new accounts, as long as they are moderated by the tree owner?

Please, shed some light on my ignorance. :wink: 

Regards,

David

**Comment by fisharebest** [comment]
It's because the registration emails are sent to the tree's genealogy contact.

There is already an open issue for this - See #1945 for a lengthy explantion.  Feel free to add to the discussion there.

There is another option.  You can set the privacy rules so that all individuals (living and dead) are shown only to members only.  You can do the same with sources, media, etc.

**Comment by dverdin** [comment]
Oh yes that's perfect !
I did not notice that you could access the tree but still keep individuals informations private.

This way, it is indeed way more user friendly.

I'll add a suggestion to the other issue.

Thank you very much!

Regards,

David
