### ISSUE TITLE
Following email confirmation link gives error message - v2.0.0 beta 3

### ISSUE THREAD

**Issue by cricktor** [fisharebest/webtrees#2544]
I have setup webtrees v2.0.0b3 running on PHP 7.3 and forced https (option on my webhoster's domain setup).

No issues with setup of webtrees so far. Import of a GEDCOM that I initially started to create on my mobile with FamilyGTG (Android) failed, but I didn't bother to dig into it and recreated my family tree from scratch in webtrees. Again no real issues with that again.

Created a test account with a different email address than my admin account; email was sent; followed the provided link to verify the test account's email address:
webtrees tells that there is an error and the user should either try again or contact the administrator.
BUT there is no issue with that account visible for the administrator, the email address is confirmed so the administrator can approve the new account and activate it.

That some error occurred may scare off users, especially the older family members.

I can't see an apparent error with the link or in the email address confirmation request email:
Subject line states "Your registration at https://{my site}/"
The correct site address and registration email address is again repeated correctly in the first sentence (I currently don't want to show my site's address in the public until I have checked the configuration completely).
The confirmation link looks fine, too:
https://{my site}/index.php?route=verify&username=testuser1&token={token gibberish}&ged={my tree id}

If you need any logs or if I missed to provide some vital details, I'll happily amend those (but I may need some additional help where and how to create those further details; I'm a bit "rusty" in this coding stuff...).

I hope I didn't miss something in the so far published issues as I couldn't find this topic in the open issues.

**Comment by fisharebest** [comment]
> webtrees tells that there is an error and the user should either try again or contact the administrator.

The registration code is single-use.

Are you sure that you haven't tried following the link twice in your testing? 

> webtrees tells that there is an error and the user should either try again or contact the administrator.
> I'm a bit "rusty" in this coding stuff...

The code is pretty simple to follow:
https://github.com/fisharebest/webtrees/blob/master/app/Http/Controllers/Auth/VerifyEmailController.php#L46

Either the username does not correspond to an actual user account, or the token in the email doesn't match the one in the database.

Perhaps compare the token in the email with the value in the database before you click on the URL? (Tables `wt_user` and `wt_user_setting`)

**Comment by cricktor** [comment]
I'm pretty sure I tried only once, but, oh well...

Tried again with another test account and checked first in the wt_user_setting table: hashcodes in table and email confirmation request email both match.

Using the provided link for the first time gives no issue, but expected success notification came up just fine. (Maybe it's because I used my mobile phone for testing and when screen orientation changes, the page request might be repeated which then fails (also if you change the language from the menue you will get the error message "Could not verify the information you entered. ..."

As it's one-time only, then the text "Please try again ..." won't help, but nevermind.
In my opinion we can close herewith.
