### ISSUE TITLE
Translations - better via the website or github?

### ISSUE THREAD

**Issue by serl** [fisharebest/webtrees#2546]
Hello,
I edited a couple of Italian translations, both for master and 1.7 branch, using the website ([this one](https://weblate.iet.open.ac.uk/projects/webtrees)). But I see no related commit in this repository.

Was this the supposed workflow? Or do you prefer better a direct good old PR?
BTW I see there are things to translate to Italian. I can help.

Thanks!

**Comment by fisharebest** [comment]
> I edited a couple of Italian translations, both for master and 1.7 branch, using the website

Thanks!

> But I see no related commit in this repository.

The translation server does not push commits automatically.  I need to do this manually.

> Was this the supposed workflow?

Yes.

> BTW I see there are things to translate to Italian. I can help.

Thanks!

**Comment by serl** [comment]
Perfect, so I'll loop over the missing ones as I have spare time!

Should I notify you for new data or it is automatic?

**Comment by fisharebest** [comment]
> Should I notify you for new data or it is automatic?

I synchronise the website every week (approx).
