### ISSUE TITLE
Feature Request: Healthcheck

### ISSUE THREAD

**Issue by Cutyno** [fisharebest/webtrees#2549]
A command line based health check for automatic informing of problems or overloads. The check should test the database, the consistency of the data and the Internet interface.

**Comment by fisharebest** [comment]
I don't think a command-line utility will be of much use.

1) Most users cannot run command-line tools.
2) CLI scripts run with a different PHP configuration to web requests.  The CLI script may have all the correct configuration, but the web request may not.
3) CLI scripts may not be able to make a web-request.  Some sites may use proxy servers, port-forwarding, etc.

We already have a number of "healthcheck" tools built in to webtrees:

* There are checks for errors in GEDCOM data.

* The control panel will show warnings if any libraries are missing, or PHP configuration is incorrect.
See https://github.com/fisharebest/webtrees/blob/master/app/Services/ServerCheckService.php for details of the checks.

If you can think of any specific checks that we can add here, then we can add them.

**Comment by Cutyno** [comment]
I've been thinking about a command target based solution for 3rd party apps. The user does not necessarily have to use it. However, this way, enclosing apps can inform the user at regular intervals that the website is still working properly or can take countermeasures if this is no longer the case.
Now in hindsight, after looking further into your code, maybe a php file that outputs a JSON object, XML document or any other machine-readable file format would be better. In this file should be listed tests of all functional parts of the program. 
In the referenced link only basic requirements are checked. This can also be included in the file, but should only be used afterwards on a functioning system.

Translated with www.DeepL.com/Translator

**Comment by xmlf** [comment]
Let me say that I have some improvements to my website:
1. Customize the user registration page and ask the user to enter their grandparent information and his mobile number.
2. I can verify the user quickly and conveniently in the background according to the ancestral information filled in by the user when registering. When I verify the user, the user's phone will receive a text message notification.
3. I use a third-party program to monitor my website for normal access every 5 minutes. If it is not available, my wechat or telegram will receive a notification message.

**Comment by fisharebest** [comment]
> In this file should be listed tests of all functional parts of the program.

I do not think that these details should be publicly available.

All our checks are built into the `ServerCheckService` class.

These are currently shown on the admin and setup pages.

We could show a simple status, (`OK`, `WARNING`, `ERROR`), via a URL.

e.g. `index.php?route=ping`
