### ISSUE TITLE
Local change - LTR data on RTL pages and RTL data on LTR pages - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2550]
I have started to 'play' with the Research Tasks block.

If I change < td dir="auto" > to < td dir="ltr" style="text-align: left" >, all my task texts print adjusted left also on rtl pages. Almost all my tasks are ltr.

I want to add an if and else to resources/views/modules/todo/research-tasks.phtml.
Can I write 
< ?php if ... ? >
    <td ....>
< ?php else: ? >
    <td ...>
< ?php endif; ? >

Which function can check if the e($task->value()), e($task->attribute('_WT_USER')) and the $task->record()->fullName() are RTL?

**Comment by fisharebest** [comment]
`$script = I18N::textScript($text)` will identify the script - for most characters in common scripts.

`$dir = I18N::scriptDirection($script)` will return `ltr` or `rtl`.

**Comment by melizaa** [comment]
Thanks! Will try to use this.

**Comment by melizaa** [comment]
So far my testing does not work.

**Comment by melizaa** [comment]
Now it works! Thanks!

**Comment by melizaa** [comment]
Shouldn't we add she bidi support to the wt code?
