### ISSUE TITLE
2.0 Fatal log errors

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2557]
Here is the site logs around the time of the error:
66.249.79.157 - - [23/Aug/2019:00:32:54 -0700] "GET /individual.php?pid=I0015&ged=peters.ged HTTP/1.1" 301 6029 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.79.159 - - [23/Aug/2019:00:32:55 -0700] "GET /index.php?pid=I0015&ged=peters.ged&xref=I0015&route=individual HTTP/1.1" 200 28900 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.66.44 - - [23/Aug/2019:00:42:22 -0700] "GET /index.php?route=media&xref=M49&ged=peters.ged HTTP/1.1" 200 16061 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"

Here is the output from the webtrees log
2019-08-23 00:45:50

SQLSTATE[HY000]: General error: 144 Table './webtrees@002dprod/wt_session' is marked as crashed and last (automatic?) repair failed (SQL: select `session_data` from `wt_session` where `session_id` = csrqm865tbauc6g805glu663n7 limit 1) …/vendor/illuminate/database/Connection.php:664 #0 …/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select `session...', Array, Object(Closure)) #1 …/vendor/illuminate/database/Connection.php(333): Illuminate\Database\Connection->run('select `session...', Array, Object(Closure)) #2 …/vendor/illuminate/database/Query/Builder.php(2130): Illuminate\Database\Connection->select('select `session...', Array, true) #3 …/vendor/illuminate/database/Query/Builder.php(2118): Illuminate\Database\Query\Builder->runSelect() #4 …/vendor/illuminate/database/Query/Builder.php(2604): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}() #5 …/vendor/illuminate/database/Query/Builder.php(2119): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure)) #6 …/vendor/illuminate/database/Concerns/BuildsQueries.php(77): Illuminate\Database\Query\Builder->get(Array) #7 …/vendor/illuminate/database/Query/Builder.php(2104): Illuminate\Database\Query\Builder->first(Array) #8 …/app/SessionDatabaseHandler.php(65): Illuminate\Database\Query\Builder->value('session_data') #9 [internal function]: Fisharebest\Webtrees\SessionDatabaseHandler->read('csrqm865tbauc6g...') #10 …/app/Session.php(66): session_start() #11 …/app/Http/Middleware/UseSession.php(43): Fisharebest\Webtrees\Session::start(Object(Nyholm\Psr7\ServerRequest)) #12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #13 …/app/Http/Middleware/UseFilesystem.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseFilesystem->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #15 …/app/Http/Middleware/UseCache.php(44): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #17 …/app/Http/Middleware/UpdateDatabaseSchema.php(56): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #19 …/app/Http/Middleware/UseDebugbar.php(64): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #21 …/app/Http/Middleware/UseDatabase.php(85): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #23 …/app/Http/Middleware/WebEnvironment.php(78): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WebEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #25 …/app/Http/Middleware/ReadConfigIni.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #27 …/app/Http/Middleware/HandleExceptions.php(54): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #29 …/app/Http/Middleware/EmitResponse.php(52): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #31 …/app/Http/Middleware/PhpEnvironment.php(46): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #33 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #34 …/index.php(40): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #35 {main}

**Comment by fisharebest** [comment]
The table is corrupt.  This could be a sign of problems on the server.   Now might be a good time for a backup.

Fortunately, the data in this table is not important (it is just a record of the current sessions), and can be safely deleted.

You could try `TRUNCATE TABLE `wt_session`;`.

If this fails, you could try to drop and recreate the table

```
DROP TABLE `wt_session`;
CREATE TABLE `wt_session` (
  `session_id` char(128) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `session_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` int(11) NOT NULL,
  `ip_address` varchar(45) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `session_data` longblob NOT NULL,
  PRIMARY KEY (`session_id`),
  KEY `ix1` (`session_time`),
  KEY `ix2` (`user_id`,`ip_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

You might want to re-create each of your tables, using `OPTIMIZE TABLE wt_xxxxx;`.

**Comment by makitso** [comment]
OK, deleted all rows in wt_session, will keep an eye on it.

**Comment by makitso** [comment]
Turns out my hosting company (and yours for webtrees.net) had a DOS attach late on 8/22.  When they recovered they noted the corrupt session table and reloaded from the night earlier.
