### ISSUE TITLE
2.0.0 beta 4: Upgrade problems

### ISSUE THREAD

**Issue by dverdin** [fisharebest/webtrees#2558]
Dear all,

I just ran the upgrade wizard from the web interface to switch to beta 4. thanks a lot for your efforts in developing this great software!

I have two problems:
1- Webtrees does not have the translations anymore. All the character strings in the web interface are now in English. I cleaned the data cache. Then went to resources/lang and found out that there is no file at all in any directory.
2- Though the upgrade process seemingly completed without error, Webtrees still asks for an upgrade from beta 3 to beta 4. Indeed, the files in the app folder are all from the 18th of May. So I think that the software did not actually upgrade but still cleaned out the old translations.

Any input about how to fix this?

thanks!

David

**Comment by dverdin** [comment]
Two small precisions:

1- I ran the wizard two times for the same result,
2- I did not find any error in the Apache and Webtrees logs.

Regards,

**Comment by dverdin** [comment]
And another side effect: Some individuals page are displayed without any CSS. Just the raw HTML.
Most of the individuals are displayed, though. I don't find any rationale behind this display discrepancy.

**Comment by fisharebest** [comment]
I did see this problem once (on my own site) but could not reproduce it.

Since the upgrade is run using the *old* code, I figured it was an issue with the old code, and did a manual upgrade.  i.e. just download the zip, unpack it and copy to server.

I suggest you do the same.

The translation files are definitely included in the release.  (We use .PHP files now.  Previously we used .MO files).  I guess a manual upgrade will fix it.

**Comment by dverdin** [comment]
Thanks for your answer, @fisharebest !
Indeed, running the manual upgrade worked perfectly.
For the record, my server was a fresh install of Webtres 2.0.0 beta 3. So the problem might be in more recent code.

Anyway, my problem is fixed now, so feel free to close this issue!

Thanks a lot for your quick answer and for pouring energy in developing Webtrees!

**Comment by fisharebest** [comment]
I have found the problem.  It also exists in the beta.4 code - which means that you will have the same problem next time.

Or you could apply the patch.

**Comment by dverdin** [comment]
Thanks!
I'm quite busy this week but will do my best to apply the patch before the next upgrade. I'll keep you informed if it works out well.
Cheers, 
David
