### ISSUE TITLE
German language lost after automatic update from 2.0.0.b3 to 2.0.0.b4

### ISSUE THREAD

**Issue by HelmutL** [fisharebest/webtrees#2564]
After automatic update from beta3 to beta4 it seems that national languages are lost (although they show up in the language dropdown menu).
After a manual update (i.e. download of 2.0.0-beta.4 and unzip) the languages are back again,

**Comment by fisharebest** [comment]
This is a consequence of #2558

beta.3 uses `messages.mo` files.
beta.4 uses `messages.php` files.

The upgrade installs all the new files, and then deletes old files.

The install fails (#2558), but the delete works.

So, you stay at beta.3, but are missing some files :-(

The same bug exists in beta.4.

So, you will also need to manually upgrade to the next release.
