### ISSUE TITLE
Manager role can't manage tree, beta-4

### ISSUE THREAD

**Issue by Ziris85** [fisharebest/webtrees#2567]
Hello! I was just testing 2.0.0-beta.4 of webtrees and user management when I noticed that, in my environment, a user given the Manager role to a tree couldn't actually gain access to said tree's management interface. Specifically, I do get a "Control Panel" link that takes me to a page that shows the tree with a wrench next to it:
![image](https://user-images.githubusercontent.com/14392979/64186507-f24cf480-ce3c-11e9-8dd6-65efe1c8fd9e.png)
However, when clicking on the wrench, instead of getting the actual Management interface for the tree, I instead just get routed back to the main tree page:
![image](https://user-images.githubusercontent.com/14392979/64186602-1dcfdf00-ce3d-11e9-8b27-437422debcec.png)
I don't believe this is related to any caching or such.

**Comment by fisharebest** [comment]
Fixed in a2a24e20da9f20295005e2bd13644c6fa2f64c4c
