### ISSUE TITLE
Individual list - age at death sorting

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#2573]
If an individual died aged more than 1000 years, the age `1,000` is sorted as `1`, not `1000`

**Comment by bmhm** [comment]
Related commit: 4e96702fabf715ae955aafd54002fb5c57a109cf
 => Fix: individuals older than 1000 years break statistics chart in individual list
and refined in 57ab22314b2599feb432b1a1ed71643cfc2f0452 (code cleanup).

**Comment by bmhm** [comment]
@fisharebest  we are talking about humans here, right? 
Unless we are showing non-gregorian-years, this is an issue which no one will ever see with valid data. So maybe labeling as low-priority?

For anyone interested, this is the list: Go to individuals -> all -> show list of all individuals.

![sort_ascending](https://user-images.githubusercontent.com/1413391/66922379-41369e00-f027-11e9-8ff0-8c51d53e10ec.png)
![sort_descending](https://user-images.githubusercontent.com/1413391/66922380-41cf3480-f027-11e9-8673-b99114842268.png)

**Comment by fisharebest** [comment]
> So maybe labeling as low-priority?

Yeah - it is a low priority.  It came from a reported problem on the forum.

The solution is (probably!) to create an `Age` entity (from two dates) with methods for `days()`, `years()`, etc.

**Comment by fisharebest** [comment]
> The solution is (probably!) to create an Age entity (from two dates) with methods for days(), years(), etc.

This was implemented in a recent commit.
