### ISSUE TITLE
2.0 - Search have problems?

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2574]
On the webtrees latest beta demo, if I do a general search for the word of Duchess I get 5 hits.  Why is Queen Victoria in the list?  She has a source with the word "Duchess" in it but the search only is for Individuals??

![image](https://user-images.githubusercontent.com/5147603/64495561-8f9a9500-d250-11e9-8572-7a4ffedf3ef3.png)

**Comment by makitso** [comment]
As a side bar, on the Current Release the search term is highlighted.

**Comment by xmlf** [comment]
This is no problem. As long as it is the facts or events contained in the individual, you can search by entering keywords here.

**Comment by fisharebest** [comment]
This is a full-text search. 

The word "duchess" appears in Victoria's birth record - as part of the source citation.
