### ISSUE TITLE
2.0-b4: Image Path/File Appears with Title

### ISSUE THREAD

**Issue by dbq-andersons** [fisharebest/webtrees#2576]
Not sure if this a bug or as designed, but in Media object table fields (both on the individual Media tab and on the family page), the object's path and file appear below the title/caption; both are part of the link to the object.

![image](https://user-images.githubusercontent.com/43183321/64886218-402adf00-d62b-11e9-8930-95d063e478f2.png)

Might be just me, but it looks a little messy.  Perhaps it'd be better to show the path/file only if there is no caption? If there is a caption, show it by itself.

Cheers,

Bill

**Comment by fisharebest** [comment]
We should only show the filename if the title is not present.
