### ISSUE TITLE
wiki.webtrees.net outdated?

### ISSUE THREAD

**Issue by meulie** [fisharebest/webtrees#2581]
It mentions 1.7.13 as newest version and displays 'Parameter 1 to GadgetHooks::registerModules() expected to be a reference, value given in <b>/home/webtrees/wiki.webtrees.net/mediawiki-1.26.2/includes/Hooks.php' as error above all pages...

**Comment by fisharebest** [comment]
The MediaWiki software has been upgrade to the latest LTS release.
