### ISSUE TITLE
Undefined offset after adding image (2.0.0. beta 4)

### ISSUE THREAD

**Issue by c-prompt** [fisharebest/webtrees#2586]
After adding an image to a person, I received the following error:

> Undefined offset: 0 …/resources/views/individual-page.phtml:43

I printed `$individual_media` on line 43:

`<?= $individual_media[0]->displayImage(200, 260, 'crop', ['class' => 'img-thumbnail img-fluid w-100']) ?>`

and found that time image is in [3] - not [0]. Thus, changing it to 3 fixes the error.

**Comment by fisharebest** [comment]
This was fixed earlier today in 8e64ca84598f5d9d6117c0702ba09635c2c8f23d

We now use `$individual_media->first()` instead of `$individual_media[0]`.
