### ISSUE TITLE
date entry

### ISSUE THREAD

**Issue by guidovanharten** [fisharebest/webtrees#2591]
In the hints for entry dates I see the format how to entry dates. Today, September 28, e.g. can be entered as: 28-09-18.
I prefer also another entry format, which is not available now: 28092018 (without dashes, dots, spaces, etc.).
My current (offline) family tree application uses these option and I like it very much.
(see also the discussion at [https://www.webtrees.net/index.php/en/forum/3-help-for-2-0-beta/33593-entry-dates-additional-appreciated-option](url)

**Comment by fisharebest** [comment]
YYYYMMDD and DDMMYYYY are unambiguous for the year 1300 onwards.
