### ISSUE TITLE
Connecting lines in charts are in wrong direction on RTL pages - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2596]
Ancestors, descendants, family book, hourglass chart,  pedigree

Sample from the pedigree
![image](https://user-images.githubusercontent.com/5202996/65860660-64005b80-e373-11e9-8ebe-755a3cc0822a.png)

**Comment by fisharebest** [comment]
This broke in b60877d9de903a8f4c698c6a4ab3b88a86ebf4b5
