### ISSUE TITLE
How can I imbed a site media object in a note or shared note? - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2599]
In pre 2.0.0 I used mediafirewall.php. See for instance N74.

**Comment by fisharebest** [comment]
You can copy the URL from the image.

In firefox, right-click and select "copy image location".

For example, here is the URL for one of the thumbnail images.

https://dev.webtrees.net/demo-dev/index.php?route=media-thumbnail&xref=m1&ged=demo&fact_id=a11b92ed7e364dae58b1870a1c2818e4&w=200&h=200&fit=contain&mark=watermark.png&markh=100h&markw=100w&markalpha=25&or=0&s=b57c0b32cd48823cab7af9e866903bd0

Here is an image that uses that URL.

![Image](https://dev.webtrees.net/demo-dev/index.php?route=media-thumbnail&xref=m1&ged=demo&fact_id=a11b92ed7e364dae58b1870a1c2818e4&w=200&h=200&fit=contain&mark=watermark.png&markh=100h&markw=100w&markalpha=25&or=0&s=b57c0b32cd48823cab7af9e866903bd0)

Note that this URL format *might* change before 2.0.0 final is released.

**Comment by melizaa** [comment]
Thanks.

I managed to add a media-thumb URL using a markdown sample to my shared note N74.
