### ISSUE TITLE
Shared note heading markups printed in note title - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2600]
In pre 2.0.0 I used to fill shared note titles by adding markup ** or ##, etc. I used to see the shared note titles in the note page and in the Shared notes list without the markup ** or ##,  etc.

In 2.0.0 I see the note title with the ** or ##, etc.

Shared notes list:
![image](https://user-images.githubusercontent.com/5202996/65907734-93dc4d00-e3cd-11e9-94e6-d87aed9c982b.png)

and note:
![image](https://user-images.githubusercontent.com/5202996/65908482-35b06980-e3cf-11e9-9aaf-3261cff2c7e9.png)

is now printed
![image](https://user-images.githubusercontent.com/5202996/65908374-fd109000-e3ce-11e9-8bf5-19adda6ad334.png)

**Comment by fisharebest** [comment]
This was changed to fix #2588 ...

**Comment by melizaa** [comment]
How can we remove the markups from the titles?

**Comment by fisharebest** [comment]
I don't know.  I'll probably need to find another fix for #2588
