### ISSUE TITLE
How to customize url format？

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2611]
The current rewrite url format is
https://dev.webtrees.net/tree/demo/individual/i47/alexandra-of-denmark
If I want to shorten the URL length, modify it to:
https://dev.webtrees.net/demo/indi/i47.html
or
https://dev.webtrees.net/indi/i47
How should I do it?

**Comment by fisharebest** [comment]
This is new code.  It is changing every day.



You can change the URL format here

https://github.com/fisharebest/webtrees/blob/cf7dfd3d9dd62946c6388b91f0f7ec936ed997b9/routes/web.php#L305

If you do not use the `{slug}` part, then you must also remove the redirect from here

https://github.com/fisharebest/webtrees/blob/cf7dfd3d9dd62946c6388b91f0f7ec936ed997b9/app/Http/Controllers/IndividualController.php#L99

**Comment by xmlf** [comment]
> This is new code. It is changing every day.
> 
> You can change the URL format here
> 
> https://github.com/fisharebest/webtrees/blob/cf7dfd3d9dd62946c6388b91f0f7ec936ed997b9/routes/web.php#L305
> 
> If you do not use the `{slug}` part, then you must also remove the redirect from here
> 
> https://github.com/fisharebest/webtrees/blob/cf7dfd3d9dd62946c6388b91f0f7ec936ed997b9/app/Http/Controllers/IndividualController.php#L99

How do I remove  `slug` now?

**Comment by fisharebest** [comment]
Does it work if you change `slug()`

to  `return '';`

https://github.com/fisharebest/webtrees/blob/2.0.0/app/GedcomRecord.php#L353

**Comment by xmlf** [comment]
I have changed `slug() `to return '';
This still does not work.
The url is:
xxx.com/tree/demo/individual/I3869**/**
And redirect to` My pages`
