### ISSUE TITLE
Routing problem

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2614]
I realise you're still working on this and my problem may be a server configuration error (but I can't see what) but if I just enter webtrees in the url, eg.

`http://webtrees/` then I get this `http://webtrees///tree-page?ged=drury` with a 404 response.

This has only started since you've been making routing changes

**Comment by fisharebest** [comment]
Maybe you enabled URL-rewrites without setting the correct base_url?

What did you put in config.ini.php?

**Comment by ddrury** [comment]
Reinstall of server fixed something but config files are identical. ho hum
