### ISSUE TITLE
MiddlewareInterface::process does not parse $individual

### ISSUE THREAD

**Issue by bmhm** [fisharebest/webtrees#2615]
Hi,

for my plugin I saw that there is a new method `MiddlewareInterface::process`.
Sadly it is the interface of the underlying http library, which has two drawbacks:

1. it exposes an implementation choice. If you ever want to change the implementation, all modules will fail.
2. It does not give access to the individual. 

Thus, I'd have to call `Individual::getInstance($xref, $tree);`. For this, I'd have to parse the request, which duplicates functionality of both `IndividualController` and `routes/web.php`:

```php
        $tree = app(Tree::class);
        $xref = $request->getQueryParams()['xref'];
        $individual = Individual::getInstance($xref, $tree);
```

I know this might be asking for a lot, but is there a chance to have an `ModuleIndividualInterceptor` interface? Would be the same as the process method, but the `Individual $individual` added as 3rd argument.

I wouldn't deal with 1. at the moment, since there is no risk in leaving this implementation exposed at the moment.

**Comment by fisharebest** [comment]
We code against the [PSR-7](https://www.php-fig.org/psr/psr-7) interfaces for requests and responses.
We code against the [PSR-11](https://www.php-fig.org/psr/psr-11) interface for middleware.
We code against the [PSR-15](https://www.php-fig.org/psr/psr-15) interface for request handlers.

> If you ever want to change the implementation, all modules will fail.

If we migrate to a framework that does not use the PSR interfaces (e.g. Symfony or Laravel), then we would use an adapter - and all our code will still work without changes.

> which duplicates functionality of both IndividualController

Duplicates 4 lines?

This is already duplicated in every handler that processes an individual.

So, your module is (approximately) this:

```
public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    if ($request->getAttribute('route')) === 'individual' && $request->getHeaderLine('Accept') matches application/ld+json) {
            $tree       = $request->getAttribute('tree');
            $xref       = $request->getAttribute('xref');
            $individual = Individual::getInstance($xref, $tree);
            Auth::checkIndividualAccess($individual);

            $data = json_encode(....);

            return response($data, 200, ['Content-type' => 'application/ld+json']);
    }

    return $handler($request);
}
```

**Comment by bmhm** [comment]
Oh that is a PSR? Sigh.

Thanks. I'll close it then.
