### ISSUE TITLE
Todays github sync causes login to fail

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2616]
From landing page, select login, and get this error:
The requested URL /tree/peters/tree-page was not found on this server.

Logs
::1 - - [11/Oct/2019:08:30:51 -0700] "POST /index.php?route=%2Flogin HTTP/1.1" 302 493 "http://localhost/index.php?route=%2Flogin&url=http%3A%2F%2Flocalhost%2Ftree%2Fjohannsen%2Ftree-page%3Froute%3D%252Ftree%252Fjohannsen%252Ftree-page" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
::1 - - [11/Oct/2019:08:30:51 -0700] "GET /tree/johannsen/tree-page?route=%2Ftree%2Fjohannsen%2Ftree-page HTTP/1.1" 404 513 "http://localhost/index.php?route=%2Flogin&url=http%3A%2F%2Flocalhost%2Ftree%2Fjohannsen%2Ftree-page%3Froute%3D%252Ftree%252Fjohannsen%252Ftree-page" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"

**Comment by fisharebest** [comment]
In `config.ini.php`, what values do you use for `base_url` and `rewrite_urls`?

**Comment by makitso** [comment]
; <?php return; ?> DO NOT DELETE THIS LINE
dbtype="mysql"
dbhost="localhost"
dbport="3306"
dbuser="makitso"
dbpass="xxxxxx"
dbname="webtrees_dev"
tblpfx="wt_"
base_url="http://localhost"

**Comment by fisharebest** [comment]
It is redirecting to a "pretty" URL - but you haven't enabled URL rewriting...

What URL were you on before logging in?

**Comment by makitso** [comment]
Landing page: https://www.webtrees.net/index.php/en/
Select Login: https://www.webtrees.net/index.php/en/login-en

**Comment by fisharebest** [comment]
Um - that's the URL for the project website.

Aren't we talking about your local webtrees site?

**Comment by makitso** [comment]
Sorry;

Landing page: http://localhost/index.php?route=%2Ftree%2Fpeters%2Ftree-page
select login
http://localhost/index.php?route=%2Flogin&url=http%3A%2F%2Flocalhost%2Ftree%2Fpeters%2Ftree-page%3Froute%3D%252Ftree%252Fpeters%252Ftree-page

**Comment by fisharebest** [comment]
...and after you login, you are redirected to  http://localhost/tree/johannsen/tree-page ??

**Comment by makitso** [comment]
I have two trees on this system:
After login:
http://localhost/login?route=%2Flogin&url=http%3A%2F%2Flocalhost%2Ftree%2Fpeters%2Ftree-page%3Froute%3D%252Ftree%252Fpeters%252Ftree-page

**Comment by fisharebest** [comment]
Previously, you said

> From landing page, select login, and get this error:
> The requested URL /tree/peters/tree-page was not found on this server.

I'm confused.  After login, which URL do you get?

**Comment by makitso** [comment]
> It is redirecting to a "pretty" URL - but you haven't enabled URL rewriting...

I am not using a .htaccess file for my apache configuration.

> I'm confused. After login, which URL do you get?

Select login from peters landing page
log:
::1 - - [11/Oct/2019:08:50:46 -0700] "GET /index.php?route=%2Flogin&url=http%3A%2F%2Flocalhost%2Ftree%2Fpeters%2Ftree-page%3Froute%3D%252Ftree%252Fpeters%252Ftree-page HTTP/1.1" 200 4922 "http://localhost/index.php?route=%2Ftree%2Fpeters%2Ftree-page" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"

Enter un/pw and select sign in:

log:
::1 - - [11/Oct/2019:08:52:03 -0700] "POST /index.php?route=%2Flogin HTTP/1.1" 302 488 "http://localhost/index.php?route=%2Flogin&url=http%3A%2F%2Flocalhost%2Ftree%2Fpeters%2Ftree-page%3Froute%3D%252Ftree%252Fpeters%252Ftree-page" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
::1 - - [11/Oct/2019:08:52:03 -0700] "GET /tree/peters/tree-page?route=%2Ftree%2Fpeters%2Ftree-page HTTP/1.1" 404 510 "http://localhost/index.php?route=%2Flogin&url=http%3A%2F%2Flocalhost%2Ftree%2Fpeters%2Ftree-page%3Froute%3D%252Ftree%252Fpeters%252Ftree-page" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"

**Comment by fisharebest** [comment]
I've just re-written the logic for detecting base URL and request URL.

Can you tell me if it fixes the problem?

**Comment by makitso** [comment]
I am sorry but it did not.  Sync'ed to git and cleared cache of pages.
On login page:
logs:
::1 - - [12/Oct/2019:11:34:36 -0700] "GET /index.php?route=%2Flogin&url=http%3A%2F%2Flocalhost%2Ftree%2Fpeters%2Ftree-page HTTP/1.1" 200 4893 "http://localhost/index.php?route=%2Ftree%2Fpeters%2Ftree-page" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"

Select sign in:
logs:
::1 - - [12/Oct/2019:11:35:59 -0700] "POST /index.php?route=%2Flogin HTTP/1.1" 302 453 "http://localhost/index.php?route=%2Flogin&url=http%3A%2F%2Flocalhost%2Ftree%2Fpeters%2Ftree-page" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [12/Oct/2019:11:35:59 -0700] "GET /tree/peters/tree-page HTTP/1.1" 404 510 "http://localhost/index.php?route=%2Flogin&url=http%3A%2F%2Flocalhost%2Ftree%2Fpeters%2Ftree-page" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
