### ISSUE TITLE
Another routing issue

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2617]
Not sure if this is related to #2616 , I can sign in but when I click on "My page" from the control panel I get an invalid url
`http://localhost/webtrees//index.php?route=%2Fwebtrees%2F%2Ftree%2F%7Btree%7D%2Fmy-page`

whereas clicking on "My page" from the "My pages" menu gives

`http://localhost/webtrees//index.php?route=%2Fwebtrees%2F%2Ftree%2Fdrury%2Fmy-page
`
which works

**Comment by fisharebest** [comment]
I've just re-written the logic for detecting base URL and request URL.

Can you tell me if it fixes the problem?

**Comment by ddrury** [comment]
Get the following error

```
session_set_cookie_params() expects parameter 3 to be string, null given …\app\Session.php:67
#0 …\app\Session.php(67): session_set_cookie_params(0, '/', NULL, false, true)
+ lots of middleware lines
```

Cleared all cookies but still get error

**Comment by ddrury** [comment]
BTW in the other issue you asked what was in my config.ini.php - it hasn't changed from 1.7.14 so just DB access stuff

**Comment by ddrury** [comment]
Replaced line 59 of session.php with `$domain = parse_url($url, PHP_URL_HOST) ?? '';` got rid of the error but didn't fix problem

**Comment by ddrury** [comment]
Added base_url to config.ini.php - no change

**Comment by ddrury** [comment]
Is this any use? here are var_dumpd of $uri, $params, $url_route, $uri after line 72 of middleware/router.php

After calling my page from My pages menu item
```
…\app\Http\Middleware\Router.php:73:
object(Nyholm\Psr7\Uri)[534]
  private 'scheme' => string 'http' (length=4)
  private 'userInfo' => string '' (length=0)
  private 'host' => string 'webtrees.local' (length=14)
  private 'port' => null
  private 'path' => string '/tree/%7Btree%7D/my-page' (length=24)
  private 'query' => string 'route=%2Ftree%2F%7Btree%7D%2Fmy-page' (length=36)
  private 'fragment' => string '' (length=0)
…\app\Http\Middleware\Router.php:73:
array (size=1)
  'route' => string '/tree/{tree}/my-page' (length=20)
…\app\Http\Middleware\Router.php:73:string '/tree/{tree}/my-page' (length=20)
…\app\Http\Middleware\Router.php:73:
object(Nyholm\Psr7\Uri)[534]
  private 'scheme' => string 'http' (length=4)
  private 'userInfo' => string '' (length=0)
  private 'host' => string 'webtrees.local' (length=14)
  private 'port' => null
  private 'path' => string '/tree/%7Btree%7D/my-page' (length=24)
  private 'query' => string 'route=%2Ftree%2F%7Btree%7D%2Fmy-page' (length=36)
  private 'fragment' => string '' (length=0)
```

After calling My page from control panel
```
 …\app\Http\Middleware\Router.php:73:
object(Nyholm\Psr7\Uri)[534]
  private 'scheme' => string 'http' (length=4)
  private 'userInfo' => string '' (length=0)
  private 'host' => string 'webtrees.local' (length=14)
  private 'port' => null
  private 'path' => string '/tree/%7Btree%7D/my-page' (length=24)
  private 'query' => string 'route=%2Ftree%2F%7Btree%7D%2Fmy-page' (length=36)
  private 'fragment' => string '' (length=0)
…\app\Http\Middleware\Router.php:73:
array (size=1)
  'route' => string '/tree/{tree}/my-page' (length=20)
…\app\Http\Middleware\Router.php:73:string '/tree/{tree}/my-page' (length=20)
…\app\Http\Middleware\Router.php:73:
object(Nyholm\Psr7\Uri)[534]
  private 'scheme' => string 'http' (length=4)
  private 'userInfo' => string '' (length=0)
  private 'host' => string 'webtrees.local' (length=14)
  private 'port' => null
  private 'path' => string '/tree/%7Btree%7D/my-page' (length=24)
  private 'query' => string 'route=%2Ftree%2F%7Btree%7D%2Fmy-page' (length=36)
  private 'fragment' => string '' (length=0)
```

**Comment by ddrury** [comment]
The attached differences file generated by`var_dump($uri, $params, $url_route, $uri);` 
[differences.pdf](https://github.com/fisharebest/webtrees/files/3721044/differences.pdf)

new1.txt (left) is from calling My page from My pages menu, new2.txt (right) from calling My page from control panel

**Comment by ddrury** [comment]
looks like the query parameter get a bit of extra escaping somewhere so the tree name isn't substituted

**Comment by fisharebest** [comment]
Try the latest code.

I think it covers all the options...

* root folder / subfolder
* pretty urls / ugly urls
* explicit base_url / automatic base_url

**Comment by ddrury** [comment]
Nope sorry - no change

**Comment by fisharebest** [comment]
> Not fixed for the call to my page from the control panel.

That's a different (and known) problem.

The new routing logic makes it explicit that "my-page" requires a tree.  In the control panel, we don't have a "current tree".  In fact, there may not be any tree at all - and so there would not be a "my-page".

There are a few other similar cases where we want to redirect to my-page, but don't have a current tree.

I'm working through them...

> Other stuff seems better

In that case, I'll close this issue.
