### ISSUE TITLE
Family relationship records were not deleted when the spouse was deleted

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2623]
When I want to delete all the members of a family, I first delete his wife and the deletion is successful.  Then I will delete the husband. I cannot delete him.  Through the control panel check error, found that the family record still exists, so cannot delete the husband.  It should be correct that when the wife is deleted, the family should also be deleted.

**Comment by abeger** [comment]
Ran into the same problem twice today. I deleted the individual but IND record is still referenced in the GEDCOM fragment on the family record.

**Comment by fisharebest** [comment]
> When I want to delete all the members of a family

Are you trying to

1) delete the family group and keep all the individuals
2) delete the family group and delete all the individuals

> I first delete his wife and the deletion is successful

What are you doing here?

1) Individual -> Edit/Delete
2) Family -> Change family members -> wife -> delete

**Comment by xmlf** [comment]
delete the family group and delete all the individuals

Individual -> Edit/Delete
