### ISSUE TITLE
github - Create Family Tree does not complete

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2625]
In Admin, when you go to create a family tree, enter data and then select Create it leaves the tree in an unknown state -- hung at 0%
![image](https://user-images.githubusercontent.com/5147603/66720255-47224a00-edaf-11e9-853a-434a2703a1b5.png)

**Comment by fisharebest** [comment]
Should be fixed in latest code

**Comment by makitso** [comment]
Yes, this fixed this.  However, can't import gedcom #2624
