### ISSUE TITLE
Customize whether the {slug} is enabled

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2626]
At present, in the pretty url function, individuals、families、 sources and media all use {slug} parameters.  It is very friendly to use English.
However, when using Chinese, Japanese, Korean and other languages, will {slug} be urlencode?
If {slug} is encoded by a url, the url will become very, very lengthy and no longer pretty.
It is hoped that whether the  {slug}  is used can be set in the control panel or the custom module.

**Comment by xmlf** [comment]
Of course, it would be better if you could use slug that supports Chinese.
https://github.com/overxue/slug
https://github.com/JellyBool/translug
https://github.com/senlin/pinyin-slugs

**Comment by fisharebest** [comment]
> use slug that supports Chinese.

This is the better option.

**Comment by xmlf** [comment]
> This is the better option.

Yes, it is more friendly to search engines.

**Comment by fisharebest** [comment]
The problem was comparing `null` with an empty string.

I will look at better slug algorithms later.

**Comment by xmlf** [comment]
If the administrator can enable or disable the slug parameter by configuring slug="1" or "0 "in the config.ini.php file, it will be a better choice for non-English alphabet languages.

**Comment by fisharebest** [comment]
It looks OK to me.

<img width="526" alt="Screen Shot 2019-11-07 at 10 18 40" src="https://user-images.githubusercontent.com/2306088/68380575-061c1c00-0148-11ea-84ee-3233c4455c27.png">
<img width="427" alt="Screen Shot 2019-11-07 at 10 20 18" src="https://user-images.githubusercontent.com/2306088/68380682-38c61480-0148-11ea-8571-0ae23e670472.png">

What is the problem?

**Comment by xmlf** [comment]
> It looks OK to me.
> 
> <img alt="Screen Shot 2019-11-07 at 10 18 40" width="526" src="https://user-images.githubusercontent.com/2306088/68380575-061c1c00-0148-11ea-84ee-3233c4455c27.png">
> 
> <img alt="Screen Shot 2019-11-07 at 10 20 18" width="427" src="https://user-images.githubusercontent.com/2306088/68380682-38c61480-0148-11ea-8571-0ae23e670472.png">
> 
> What is the problem?

The search engine is unable to display the url as Chinese, or some browsers will urlencode Chinese, which is very ugly.
