### ISSUE TITLE
github - Multiple trees, switching from one to another broken

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2627]
See demo site.  If you select the Greek Mythology tree the results are not correct.

**Comment by makitso** [comment]
When you switch from the default tree to another tree, the default tree data is still shown on the home page, e.g. Surnames, Statistics, etc.

**Comment by bmhm** [comment]
I cannot reproduce this. I am constantly switching between:

* https://dev.webtrees.net/demo-dev/tree/mythology/
* https://dev.webtrees.net/demo-dev/tree/demo/

Both pages look fine to me. Do I need to log in? Or is there another page which you mean by "home page"?

**Comment by fisharebest** [comment]
I think this was fixed in last night's update.
