### ISSUE TITLE
"My Page" and "Add Father" will redirect to control panel

### ISSUE THREAD

**Issue by bmhm** [fisharebest/webtrees#2629]
Hi Greg,

## Steps to reproduce

Reproducible: always.

* Install webtrees, current git version.
* login
* Click on my page -- redirected to control panel.
* Click on new individual and save -- redirected to contrl panel, no new individual added.
* Navigate to 1st individual John Briggs, open the Family Tab and click on "add father". You'll be redirected to the control panal again.

## Expected behaviour

* Individual added from control panel step
* Father individual input opens when clicking on "add father".

## actual behaviour

* Redirections to Control Panel

## Things I tried:
Setting my user (administrator) to "moderator" in the tree's user  settings. No change.

## Things I haven't tried
Setting pretty URLs. Although I added a `.htaccess` file and looked for an option to enable pretty URLs.

**Comment by fisharebest** [comment]
The `ged` parameter needs to be renamed to `tree` in all (most) of the code.

I've just pushed a quick search/replace.   It fixes the immediate problem, but may cause others.

I'll pick these up as I work through all the routing issues.

**Comment by bmhm** [comment]
@fisharebest 
https://github.com/fisharebest/webtrees/commit/9022ab6638958a155b6ee7c99b822adbb3eaa2f6#r35503016

I think that was not intended.

But I'll test the current status. If it works, I think I can finally create some pull requests.

**Comment by bmhm** [comment]
POST to index.php?route=/tree/{tree}/add-parent-to-individual
I guess a `$` is missing somewhere.
See also the comment from above where you accidently added a bit too much.

**Comment by fisharebest** [comment]
This seems to be working now.  Can you confirm?

**Comment by ungeahnt** [comment]
> 
> 
> This seems to be working now. Can you confirm?

6h ago I've tried to "add a son" on webtrees/demo-dev and this failed. Now it's working. Was this the same problem? If yes, than it's ok now ;)

**Comment by fisharebest** [comment]
Thanks
