### ISSUE TITLE
Routing issue

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2630]
After https://github.com/fisharebest/webtrees/commit/5377b74d62e86ce15153fe4c9d3199a28e3b394f Nothing on the lists menu works, all fail with an error message starting with
`Argument 3 passed to Fisharebest\Webtrees\Auth::checkComponentAccess() must be an instance of Fisharebest\Webtrees\Tree, null given`

**Comment by fisharebest** [comment]
Previously, some of our variables were a bit "promiscuous", and got stored in various global (or global-like) storage.

e.g. if you added a `ged=XYZ` query parameter, it would magically end up everywhere.

The default route for modules does not include a `{tree}` parameter.  It's easy to add one (which will fix the problem), but it will also break any module routes that are not tree specific (e.g. pages).

So, I'll need to create two module routes - one for tree-pages and one for admin-pages.

We already have this sort of distinction, based on module `action` names.  Those beginning `Admin` are admin routes.

**Comment by fisharebest** [comment]
Actually, I think this is much easier than I thought.

Just create two routes - one for admin pages and one for tree pages.

**Comment by ddrury** [comment]
As you're doing so much work on routing at the moment would you rather we hang fire on reporting stuff until things stabilise ?

**Comment by ddrury** [comment]
No problem to me, thought it was wasting your time, anyway I'll keep 
poking!

------ Original Message ------
