### ISSUE TITLE
V2 Name accordion not collapsible

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2636]
See [The Queen mother](https://dev.webtrees.net/demo-dev/tree/demo/individual/i35/Elizabeth%20Angela%20Marguerite%20Bowes-Lyon) on the demo site

**Comment by fisharebest** [comment]
Um - it collapses nicely for me.  Both/either/neither name.

Do you have any JS errors in your console?

**Comment by ddrury** [comment]
I got this on 1st entering webtrees.net
`JQMIGRATE: Migrate failed to load (this from memory but the gist is right)` after refresh I get
`JQMIGRATE: Migrate is installed, version 1.4.1`   but still can't collapse the names

Tried with chrome, firefox & edge

**Comment by ddrury** [comment]
BTW also get this on github but I guess you can't do much about that :-(
`index-es.js:141 GET https://github.com/fisharebest/webtrees/used_by_count net::ERR_ABORTED 406 (Not Acceptable)`

**Comment by fisharebest** [comment]
> Tried with chrome, firefox & edge

Hmm.  Works for me on chrome and firefox (on two different machines)

**Comment by ddrury** [comment]
I'll fire up my laptop in a bit and try on that

**Comment by ddrury** [comment]
Tried on two windows machines and an android tablet over wifi and an android phone over 4g and can't collapse on any of them

**Comment by ungeahnt** [comment]
It works for me too (firefox + chrome). When I deactivate JS (via uBlock browser-addon), folding stops and the view below the tabs disappear.

**Comment by ddrury** [comment]
Doh, I'm an idiot. I thought there used to be a drop down icon right aligned on the panel that you clicked on. Clicking on the name does of course roll the panel up/down

Sorry!
