### ISSUE TITLE
Control panel manage media error

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2642]
Selecting "External files" or "Unused files" or "Exclude subfolders" returns to My page

**Comment by fisharebest** [comment]
This seems to be working in the latest code.  Can you confirm?

**Comment by ddrury** [comment]
No, still going straight to my page. Looking at the console I see the following 3 urls when I select any of the radio buttons (the files parameter in the url obviously changes). The 2nd one looks suspect doesn't it?
```

http://webtrees.home.lan/index.php?route=admin-media&files=external&media_folder=&subfolders=include
http://webtrees.home.lan/index.php?route=%2F
http://webtrees.home.lan/index.php?route=%2Ftree%2Fdrury%2Fmy-page
```

**Comment by ddrury** [comment]
BTW last commit was https://github.com/fisharebest/webtrees/issues/2648

**Comment by ddrury** [comment]
Greg,
As far as I can see, looking at the first url above, route admin-media is directed to `Admin\MediaController::index` but if I do a var_dump of $request in the index function, the only item in  queryParams is the route.

**Comment by ddrury** [comment]
In addition to all the above, the first two urls return a status of 302.

I'm competely lost in trying to follow the routing logic!!!

**Comment by fisharebest** [comment]
Ah,

> index.php?route=admin-media

The route parameter should include the leading slash.

Without it, you get a "not found" errror, which redirects to "/", which in turn redirects to my-page or a tree-page.

**Comment by fisharebest** [comment]
I can reproduce this - by removing the definition of `base_url` in `config.ini.php`.

**Comment by ddrury** [comment]
Hm,
I didn't have that entry, but inserting it makes no difference

**Comment by ddrury** [comment]
I can fix it by changing the 2nd line of the form in /resources/views/admin/media.phtml to
`<input type="hidden" name="route" value="<?=e('/admin/admin-media')?>">`
but not sure if this is the correct method!

**Comment by fisharebest** [comment]
The hidden `route` input only works for "ugly" URLs.

To work with both ugly and pretty URLs, we need to change the form method to `POST`, and then redirect to an updated URL.

There are currently 11 occurrences of this in the code.  I'm working through them...
