### ISSUE TITLE
github - today's update throws error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2645]
[Thu Oct 17 09:44:18.820416 2019] [php7:warn] [pid 1476] [client ::1:32786] PHP Warning:  require(/home/rob/www/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /home/rob/www/vendor/composer/autoload_real.php on line 66
[Thu Oct 17 09:44:18.820450 2019] [php7:error] [pid 1476] [client ::1:32786] PHP Fatal error:  require(): Failed opening required '/home/rob/www/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/usr/share/php') in /home/rob/www/vendor/composer/autoload_real.php on line 66

**Comment by fisharebest** [comment]
Fixed.

The dev version of the autoload files got committed by mistake.
