### ISSUE TITLE
Not possible to extend existing modules?

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#2651]
Due the latest changes, my modules stop working. I extended the fan chart module. Is this not possible any longer?

I get some nothing saying error messages:

fan-chart …/vendor/aura/router/src/Map.php:134
#0 …/vendor/aura/router/src/Map.php(177): Aura\Router\Map->addRoute(Object(Aura\Router\Route))
#1 …/vendor/aura/router/src/Map.php(196): Aura\Router\Map->route('fan-chart', '/tree/{tree}/fa...', 'MagicSunday\\Web...')
#2 …/modules_v4/webtrees-fan-chart/src/Module.php(90): Aura\Router\Map->get('fan-chart', '/tree/{tree}/fa...', 'MagicSunday\\Web...')

**Comment by magicsunday** [comment]
So I cannot overwrite an existing route any longer?

**Comment by magicsunday** [comment]
I changed the ROUTE_NAME and ROUTE_URL values. The error has gone. But my module is not loaded. Instead I see twice the same link to the default fan-chart module.

**Comment by fisharebest** [comment]
Can you post a link to your git repository?

**Comment by magicsunday** [comment]
The repo you will find here: index.php?route=%2Ftree%2FDuck%2Ffan-chart-3-4-100%2FI1
But this does not contain the changes I currently did.

I am now one step further. My module is now called. I removed the dependency to the default fan chart module. An other question. On the demo site the url to the fan-chart is demo-dev/tree/demo/fan-chart-3-3-100/i1. On my site it is index.php?route=/tree/Duck/fan-chart-3-4-100/I1. How do I get rid of the index.php?route part?

**Comment by fisharebest** [comment]
> But this does not contain the changes I currently did.

OK.  Maybe create a new branch with your changes.

If I can see what you are doing, I can (a) suggest alterntives or (b) modify webtrees to assist your module.

> How do I get rid of the index.php?route part?

1) configure URL rewriting on your server.  i.e. URL that does not correspond to a file should be handled by index.php

2) add two lines to `data/config.ini`

```
base_url="https://webtrees.test"
rewrite_urls="1"
```

The URL can include a path - but most not include the trailing slash.

**Comment by magicsunday** [comment]
I committed my changes to a test branch: https://github.com/magicsunday/webtrees-fan-chart/tree/test
Please have a look at it.

**Comment by fisharebest** [comment]
Your module and the core module seem to have very little in common - so it's not clear why you are extending the core module.

Here are a few comments that might help:

We no longer use `__DIR__` in the constructor.  Just use `__DIR__ . '/../../resources/'` in the function `resourcesFolder()`.

I don't think your constructor is needed.

When you extend a function that is part of the interface (e.g. `boot()`), it needs to be compatible with the base class.
This means that you can add *optional* parameters, but you cannot change existing parameters.  e.g.

```
    public function boot(RouterContainer $router_container, ModuleThemeInterface $theme = null): void
    {
        parent::boot($router_container);
        ....
        // do something with $theme.
    }
```

You cannot reference CSS and JS scripts by using the URL `modules_v4/..../`.

All assets need to be in the public folder, or created using a script.
For custom modules, this means they must be created using a script.  e.g. something like this:

```
function getJsAction() : ResponseInterface
{
    return response(
        file_get_contents($this->resourcesFolder() . 'js/xxx.js'), 
        200,
        ['Content-type' => 'application/javascript']
    );
}
```

```
<script src=<?= e(route('module', ['module' => $this->name(), 'action' => 'Js'])) ?></script?
```

**Comment by magicsunday** [comment]
Thank you for your support. 

If I assign $theme inside boot() to a class member var, it is not available afterwards in any method of the class (its null). Also $this->name() is an empty string in methode `handle`. $this->name() is `_modulename_` in method boot().

**Comment by fisharebest** [comment]
> If I assign $theme inside boot() to a class member var, it is not available afterwards in any method 

I discovered this too.

While I was looking at your module, I tried to modify both your theme and the core theme to make them more similar.

I spent a couple of hours investigating, but could not find the cause.

**Comment by magicsunday** [comment]
My module gets initialized in app/Services/ModuleService.php:568 during processing of \Fisharebest\Webtrees\Http\Middleware\UseLocale (in call to I18N::init). Here the $name is correctly set (line 573) to the underscore + module name value. The last middleware that is called is \Fisharebest\Webtrees\Http\Middleware\WrapHandler. This ends up somewhere in vendor/illuminate/container/Container.php:644 where it builds a new instance of the module by using `ReflectionClass `. The class is created and used inside the method `handle` but the $name property is not set in this new class instance.

This happens also to core modules which uses `$this->name()` the method `handle`. But this seems not affect anything as the assigned var is nowhere used.

**Comment by fisharebest** [comment]
Thanks for analysing this.

I guessed it was something to do with a new instance being created, but couldn't find it.

The `WrapHandler` was a bit of a kludge, but it allowed me to move past a problem.

I'll see if I can find a better way to implement this.

**Comment by fisharebest** [comment]
We can now use `$this` in route definitions, instead of `self::class`.

This allows us to use the current module, rather than a new (unbooted) instance of it.
