### ISSUE TITLE
Adoptive relationship, the chart should show adoptive parents

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2653]
If individual A is adopted from family B to family C.
At present, the chart of A (hourglass chart, genealogy tree, interaction tree, ancestor tree, etc.) only shows A's parents and family B, which is unreasonable.  
After adoption, priority should be given to showing that A's parents' family is C.

**Comment by fisharebest** [comment]
When there are two "parent families", we currently choose the birth family.

The GEDCOM standard says that when there are two versions of a fact (e.g. birth-date, name, etc.), then the prefered one is stored first.

We could replace the current logic with "use the first family record", and add the ability to re-order the parent families.

This would allow the user to choose which parents will be used on charts.  For some individuals, this might be the adopted parents.  For other individuals, this might be the birth parents.

**Comment by xmlf** [comment]
If the user can choose, that is great!

**Comment by fisharebest** [comment]
Individual -> Edit -> Re-order families -> Parents
