### ISSUE TITLE
Fail to upload large document

### ISSUE THREAD

**Issue by mirono** [fisharebest/webtrees#2655]
I'm trying to add a pdf document (size 81 MB) to an event as a media object.
The upload counter reaches 38-40%, then zeros out and start again. It will again reach 38-40%. And will zero again. Thirs time it will bring an error page in the "add media" screen.

Version is 1.7.10

Thanks,
Miron

**Comment by fisharebest** [comment]
This is (almost certainly) a limitation of your server.

Go to the control panel, server information, and tell me what values you have for

* `upload_max_filesize`
* `post_max_size`

Both these must be larger than the size of your file.

There can also be limits imposed by your webserver.  For example, nginx has a parameter `client_max_body_size` and apache has a parameter `LimitRequestBody`.

**Comment by fisharebest** [comment]
As a workaround, you can copy the file to your server (using FTP), and then create a media object for this media file.

**Comment by bmhm** [comment]
We could check for the value of `$_FILES['upfile']['error']`, specifically those: https://www.php.net/manual/en/features.file-upload.errors.php

* UPLOAD_ERR_INI_SIZE
Value: 1; The uploaded file exceeds the upload_max_filesize directive in php.ini.

* UPLOAD_ERR_FORM_SIZE
Value: 2; The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form.

Maybe this could go into webtrees 2.1.0? I don't think it is _needed_ for 2.0.0. Altough showing the user what went wrong is always a good idea, 2.0.0 should probably just be a rewrite of existing functionality (mostly).

**Comment by mirono** [comment]
Yes, the settings file are weirdly too small. I remember setting php.ini correctly. but this may have been reset by a php version update on the server.
Thank you all for your help.

**Comment by bmhm** [comment]
@fisharebest either tag this as a question and let me create a new issue as enhancement, or just reopen this one too track my proposal?

**Comment by fisharebest** [comment]
FYI - There is already some code to check the error code and display a helpful message.

Search for `fileUploadErrorText()`
