### ISSUE TITLE
github - Bad routing on Reports / Ancestors / html and PDF

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2664]

**Comment by fisharebest** [comment]
@makitso - are you still seeing this error?  If so, can you post any errors/details.

**Comment by makitso** [comment]
Yes, still have the error:
Select Report / Ancestors

::1 - - [22/Oct/2019:16:29:37 -0700] "GET /public/favicon-32.png?v=1549812510 HTTP/1.1" 200 2003 "http://localhost/index.php?route=%2Ftree%2Ftree1%2Freport-setup&xref=I0001&report=ahnentafel_report" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"

Select continue

:1 - - [22/Oct/2019:16:29:45 -0700] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.41 (Ubuntu) (internal dummy connection)"
::1 - - [22/Oct/2019:16:30:02 -0700] "GET /index.php?route=report-run&tree=tree1&report=ahnentafel_report&varnames%5B%5D=pid&vars%5Bpid%5D=I0001&varnames%5B%5D=maxgen&vars%5Bmaxgen%5D=3&varnames%5B%5D=sources&vars%5Bsources%5D=on&varnames%5B%5D=notes&varnames%5B%5D=occu&varnames%5B%5D=resi&varnames%5B%5D=children&varnames%5B%5D=pageSize&vars%5BpageSize%5D=US-Letter&output=HTML HTTP/1.1" 302 348 "http://localhost/index.php?route=%2Ftree%2Ftree1%2Freport-setup&xref=I0001&report=ahnentafel_report" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
::1 - - [22/Oct/2019:16:30:02 -0700] "GET /index.php?route=%2F HTTP/1.1" 302 362 "http://localhost/index.php?route=%2Ftree%2Ftree1%2Freport-setup&xref=I0001&report=ahnentafel_report" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
::1 - - [22/Oct/2019:16:30:03 -0700] "GET /index.php?route=%2Ftree%2Ftree1%2F HTTP/1.1" 200 6043 "http://localhost/index.php?route=%2Ftree%2Ftree1%2Freport-setup&xref=I0001&report=ahnentafel_report" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
::1 - - [22/Oct/2019:16:30:03 -0700] "GET /index.php?route=%2Ftree%2Ftree1%2Ftree-page-block&block_id=43 HTTP/1.1" 200 1576 "http://localhost/index.php?route=%2Ftree%2Ftree1%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
::1 - - [22/Oct/2019:16:30:03 -0700] "GET /index.php?route=%2Ftree%2Ftree1%2Ftree-page-block&block_id=44 HTTP/1.1" 200 539 "http://localhost/index.php?route=%2Ftree%2Ftree1%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
::1 - - [22/Oct/2019:16:30:03 -0700] "GET /index.php?route=%2Ftree%2Ftree1%2Fmedia-thumbnail&s=bb7bfa117a625bba9dd9249770364dd9&xref=M298&fact_id=9ab77894e3693906b96c10bbd0055b62&w=200&h=200&fit=&mark=watermark.png&markh=100h&markw=100w&markalpha=25&or=0 HTTP/1.1" 200 12333 "http://localhost/index.php?route=%2Ftree%2Ftree1%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
::1 - - [22/Oct/2019:16:30:03 -0700] "GET /index.php?route=%2Ftree%2Ftree1%2Ftree-page-block&block_id=38 HTTP/1.1" 200 1826 "http://localhost/index.php?route=%2Ftree%2Ftree1%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"

**Comment by fisharebest** [comment]
OK - thanks.  I see the problem now.

**Comment by fisharebest** [comment]
Fixed in 1cfe16bdd395d38c2ee606c52e494d06879ce80a
