### ISSUE TITLE
github - bad routing on Manage media

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2671]
Control panel / Manage media, select of external or Unused files route incorrect.

**Comment by fisharebest** [comment]
I'm not seeing any errors here (nor on many of your other similar issues).

I've tried various combinations (pretty/ugly URLs, root/sub folder).

Can you give any more info?

What is the URL of the page you are viewing.
What URL gives the error?

**Comment by makitso** [comment]
Login, go to Control panel / Manage media

Logs:
::1 - - [21/Oct/2019:06:30:03 -0700] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.41 (Ubuntu) (internal dummy connection)"

Select External files:

::1 - - [21/Oct/2019:06:30:50 -0700] "GET /index.php?route=admin-media&files=external&media_folder=media%2F&subfolders=include HTTP/1.1" 302 348 "http://localhost/index.php?route=%2Fadmin%2Fadmin-media" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
::1 - - [21/Oct/2019:06:30:50 -0700] "GET /index.php?route=%2F HTTP/1.1" 302 369 "http://localhost/index.php?route=%2Fadmin%2Fadmin-media" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
::1 - - [21/Oct/2019:06:30:50 -0700] "GET /index.php?route=%2Ftree%2Ftree1%2Fmy-page HTTP/1.1" 200 7064 "http://localhost/index.php?route=%2Fadmin%2Fadmin-media" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
::1 - - [21/Oct/2019:06:30:50 -0700] "GET /index.php?route=%2Ftree%2Ftree1%2Fmy-page-block&block_id=12 HTTP/1.1" 200 1617 "http://localhost/index.php?route=%2Ftree%2Ftree1%2Fmy-page" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
::1 - - [21/Oct/2019:06:30:50 -0700] "GET /index.php?route=%2Ftree%2Ftree1%2Fmy-page-block&block_id=8 HTTP/1.1" 200 1311 "http://localhost/index.php?route=%2Ftree%2Ftree1%2Fmy-page" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
::1 - - [21/Oct/2019:06:30:50 -0700] "GET /index.php?route=%2Ftree%2Ftree1%2Fmedia-thumbnail&s=6d87d255e7bd7d54ea531f7532fda676&xref=M165&fact_id=92b8db42277da6cea9c6c8fa3c910154&w=200&h=200&fit=&mark=&markh=100h&markw=100w&markalpha=25&or=0 HTTP/1.1" 200 15365 "http://localhost/index.php?route=%2Ftree%2Ftree1%2Fmy-page" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
::1 - - [21/Oct/2019:06:30:50 -0700] "GET /index.php?route=%2Ftree%2Ftree1%2Fmy-page-block&block_id=13 HTTP/1.1" 200 1765 "http://localhost/index.php?route=%2Ftree%2Ftree1%2Fmy-page" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"

**Comment by fisharebest** [comment]
Thanks.  This looks to be the same as #2642
