### ISSUE TITLE
Height of interactive tree 

### ISSUE THREAD

**Issue by Elmahmoudy** [fisharebest/webtrees#2674]
Hello Sir

I may suggest the following feature:
While using the interactive tree, the height of output frame is fixed, we may modify the of the view area containing data to be adjusted in height automatically to fit the output illustrated date for the whole requested tree.
this will enable us to print the whole tree and save it as JPG by using google Full screen capture extension.

BR and good luck

**Comment by fisharebest** [comment]
This seems to be asking for the same as #1067

**Comment by fisharebest** [comment]
Closing, as duplicate.
