### ISSUE TITLE
Git - Pedigree Map cannot change individual

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2682]
Not sure if this is a knock-on from https://github.com/fisharebest/webtrees/commit/353080f8c238896c32674e7f73a3448a714cb0ac but changing the individual on the form and clicking view shows the original person.

**Comment by ddrury** [comment]
Shouldn't the form in pedigree-map/page.phtml have an action?

**Comment by fisharebest** [comment]
> Shouldn't the form in pedigree-map/page.phtml have an action?

We POST back to the same URL.

This post request then generates an updated URL and redirects back to it.

In the "old webtrees" style, we could just use GET with lots of hidden `<input>`s.

With pretty URLs, we can't, as we need to update the URL, not the query parameters.
