### ISSUE TITLE
Exception while catching module's errors

### ISSUE THREAD

**Issue by bmhm** [fisharebest/webtrees#2685]
I18N seems unavailable when catching the error.

Introduced by my PR. :(

![2019-10-23T163641-Bildschirmfoto](https://user-images.githubusercontent.com/1413391/67405101-96892700-f5b4-11e9-856b-742a2acb1bf3.png)

**Comment by fisharebest** [comment]
Ah.  Catch 22!

Translations are modules.

Modules can't access other modules during their initialisation.

This error will have to be in English.

**Comment by bmhm** [comment]
I'll put this in the PHPDoc. The PR will reference this issue to close it.

**Comment by fisharebest** [comment]
I updated the comments in the example module.

**Comment by fisharebest** [comment]
The latest code handles these errors much better.
