### ISSUE TITLE
github: sign-in routes to pretty URL even if not configured

### ISSUE THREAD

**Issue by dbq-andersons** [fisharebest/webtrees#2696]
I have not configured anything with the new pretty URLs feature, but it seems to be bleeding in any way.  Not sure I know how to yet even if I wanted to.

When I'm sitting at an individual's page (`http://www.dbq-andersons.com/genealogy/webtrees2-test/index.php?route=%2Fgenealogy%2Fwebtrees2-test%2Ftree%2Fscrubbed-tree%2Findividual%2FI10%2FDavid%2520Barry%2520Anderson`) as a visitor and then sign in, I am routed to a non-existent page (`http://www.dbq-andersons.com/genealogy/webtrees2-test/tree/scrubbed-tree/individual/I10/David%20Barry%20Anderson`).  I get similar behavior with family pages.

Thanks,

Bill

**Comment by fisharebest** [comment]
The URL is generated in`ModuleThemeTrait::menuLogin()`.

We use "pretty URLs" internally.  Requests with "ugly" URLs get converted on arrival.

So, when the code looks for the "current URL" (to redirect after login), it gets the pretty version.

There are several other places where we store the current URL, to return to later.
For example, pending changes.

I guess we need to store the original URL somewhere.
