### ISSUE TITLE
github - Batch update has no effect

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2701]
Trying to use batch update to change a Media number (@X777@ to @M777@) item.  When you select the old and new and then select Update nothing happens and the raw Gedcom element is not changed.

**Comment by fisharebest** [comment]
I can't reproduce this.

I just changed an ID from `@i1@` to `@z1@` - and back again.

Do you still see it?

**Comment by makitso** [comment]
I can still get it to fail.  But, it looks like the Update fails whereas the Update all works.

**Comment by fisharebest** [comment]
Both "update" and "update all" are working for me.

I tried with both pretty/ugly URLs.
I tried different batch-update plugins.

**Comment by makitso** [comment]
OK, will close issue.
