### ISSUE TITLE
Git - Individual tab - Browser display difference

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2703]
See icon positioning on attached. All themes, any browser width 

![demo](https://user-images.githubusercontent.com/104515/67668948-d3646d80-f968-11e9-87d6-dec066a20138.jpg)

**Comment by fisharebest** [comment]
This is a table.  We don't set the width of the columns.  We let the browser choose how much space to give to each column.

I guess chrome/firefox have different algorithms to choose the weighting.

On a mobile display, they give about 50/50.
On a desktop display, they give most to the details.

This tends to work better than explicitly choosing percentages or pixel widths.

Perhaps we just need to add `nowrap` to the icons?
