### ISSUE TITLE
Github - Individual facts tab, Source citation display issue

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2704]
See attached. Two source citations, first has image attached, When displayed, 2nd citation slides up the side of the first.
![demo](https://user-images.githubusercontent.com/104515/67676792-3ad6e900-f97a-11e9-8ab7-846075104484.jpg)

**Comment by fisharebest** [comment]
Same as #2502?

**Comment by ddrury** [comment]
Sorry yes - I'll close this
