### ISSUE TITLE
Github - Control panel - Manage media - default thumbnail

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2707]
No thumbnail for media types that are not images

**Comment by ddrury** [comment]
Need `@import "_mime-type-icons.css";` in administration.css. but as I don't know what tools you use to produce the minified  files, I'll leave it up to you!

**Comment by fisharebest** [comment]
The distribution `min.css` and `min.js` files are created/updated using [npm](https://www.npmjs.com/get-npm).

There are two steps:

* `npm install`
* `npm run production`
