### ISSUE TITLE
My future test system error - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2711]
Greg,

I have some local changes in the future test system.
One change is in app/Date/AbstractCalendarDate.php for Finnish and Hebrew dates.
I use still WT_LOCALE to know the language. It seems no longer to work.
I have from line 563
/* @@ is locally @@ */
		if ($this->day && preg_match('/%[djlDNSwz]/', $format)) {
			// If we have a day-number *and* we are being asked to display it, then genitive
			$case = 'GENITIVE';
			//Should use in Finnish 'PARTITIVE' @@
		} else {
			//Hebrew rules @@
			if (WT_LOCALE == 'he')
				$case = 'NOMINATIVE';
			//Finnish rules @@
			else if (WT_LOCALE == 'fi')
				switch ($qualifier) {
					case '':
					case 'INT':
					case 'EST':
					case 'CAL':
					case 'ABT':
						$case = 'LOCATIVE';
						break; //'INESSIVE'
					case 'BEF':
						$case = 'GENITIVE';
						break; //'PARTITIVE'
					case 'AFT':
					case 'BET':
					case 'AND':
						$case = 'INSTRUMENTAL';
etc. etc.
Now I see an error when I try to look at the future test system.
How can I correct the code to work in wt 2.0.0?

![image](https://user-images.githubusercontent.com/5202996/67787274-f2eabb80-fa78-11e9-8f3d-2e25f6aefb4b.png)

**Comment by fisharebest** [comment]
The code is getting rid of global variables (and global constants, and other global "state").

The language is part of the request (i.e. get me this page in english/hebrew/etc.).
So, we now store the langauge in the request object.

(At some point, we will create a "date formatting service", to keep this logic away from the date calculations and other logic.).

Until then, this should probably work:

1) add this import statement at the top of the file
`use Psr\Http\Message\ServerRequestInterface;`

2) get the langauge code using
`$language = app(ServerRequestInterface::class)->getAttribute('locale')->languageTag();`

**Comment by melizaa** [comment]
Great! Thanks! 
Works better than the wt 2.0.0 code in the test test system.
