### ISSUE TITLE
Production site does no longer send messages - 1.8.0-dev 

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2717]
I see in the log
Mail: Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 37sm10841002wrc.96 - gsmtp
"

I use SMTP to send messages
Sender name is my gmail aliasl
Server name smtp.gmail.com
Port number 587
Use password yes
Username is my gmail
Password is empty
Secure connection is tls
Sending server name smtp.gmail.com

**Comment by fisharebest** [comment]
You have successfully established a connection with google's mail server.

It is rejecting your credentials.

If you haven't changed anything, then there is likely to be a change with google.

Have you enabled 2-factor authentication?

**Comment by fisharebest** [comment]
I have updated the mail-preferences page to give additional instructions for two-factor authentication.
