### ISSUE TITLE
Test sites do no longer send mails - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2718]
I see in the log
MailService: Failed to authenticate on SMTP server with username "ALIAS mail" using 3 possible authenticators. Authenticator LOGIN returned Expected response code 235 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8 https://support.google.com/mail/?p=BadCredentials n17sm441500wmc.34 - gsmtp ". Authenticator PLAIN returned Expected response code 235 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8 https://support.google.com/mail/?p=BadCredentials n17sm441500wmc.34 - gsmtp ". Authenticator XOAUTH2 returned Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8 https://support.google.com/mail/?p=BadCredentials n17sm441500wmc.34 - gsmtp ".

I use SMTP to send messages
Sender name is my gmail
Server name smtp.gmail.com
Port number 587
Use password yes
Username is my gmail
Use password yes
Username gmail alias
Password empty
Secure connection is tls
Sending server name smtp.gmail.com
DKIM digital signature 3 empty fields

**Comment by fisharebest** [comment]
This will be the same as #2717
