### ISSUE TITLE
Github - Control panel - Stories module error

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2733]
When selecting a person who has a media object attached then the Xref of the media object is returned otherwise nothing seems to be selected.

After editing the Xref in phpMyAdmin, the details appear correct in the control panel , but the stories Tab on the individual page is disabled

**Comment by fisharebest** [comment]
Can you give a bit more information.

Maybe a screenshot of what you see?

> After editing the Xref in phpMyAdmin

Editing?  Changing what to what?

**Comment by ddrury** [comment]
Try this
![demo](https://user-images.githubusercontent.com/104515/68071775-c33bfc00-fd75-11e9-86d9-d4d06c1f085c.jpg)

**Comment by fisharebest** [comment]
Oops - the "individual select control" was fetching media objects, and was broken across the site!

**Comment by ddrury** [comment]
Can happen to anyone!, however even after creating a "proper" story the stories tab isn't enabled

**Comment by ddrury** [comment]
Nor is the menu

**Comment by fisharebest** [comment]
There is no menu for the stories module - just the tab.

The default permissions for stories is to hide.  I guess you just need to edit the permissions.

The permissions are a bit hidden.  It's designed that way so it works on sites with tens of trees.

I'll see if I can expose it a bit better.

**Comment by ddrury** [comment]
There is a getMenu function in the module!

**Comment by ddrury** [comment]
As always you're right I had it set to hide from everyone!

**Comment by fisharebest** [comment]
> There is a getMenu function in the module!

So there is.

It has its own access levels.
