### ISSUE TITLE
github - Manage media / Unused files fails

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2737]
This is an old issue that has been around a long time but will bring it up again.

New install, create one tree, added one individual, added one media object. 
I then manually place two .jpg files to /data/media for testing.

On the Manage media page (default with include subfolders) I see only one Media file with the correct link to the individual.  This is good.

1. If I select to exclude subfolder I see nothing.

2.  Now, if I select Unused files I see every file in the /data folder -- config.ini.php and all the three files in the /data/media folder, the good file linked to the individual and the two unused .jpg files.

So my question is, the path that the default Manage media uses, shouldn't that be /data/media?
Selecting Unused should not display correctly used linked media objects.

**Comment by makitso** [comment]
There is no /media referenced on the page
![image](https://user-images.githubusercontent.com/5147603/68093097-3feed900-fe4f-11e9-9e50-4041c72efcdd.png)

**Comment by fisharebest** [comment]
I've already coded a fix for this (and for #2479).

It's part of a bigger change, which I am currently testing.

**Comment by makitso** [comment]
Ok, I will wait for that release.

**Comment by makitso** [comment]
Today's git push did not fix these issues so I am reopening.

**Comment by fisharebest** [comment]
> Now, if I select Unused files I see every file in the /data folder -- config.ini.php and all

I saw that before the recent change.
I do not see it now.

...Copying ddrury's comments on the commit (or they will get lost).
> include or exclude subfolders makes no difference.

I put files in a subfolder.  Include shows them.  Exclude hides them.

I'm sure we are looking at the same page and seeing different things....

**Comment by makitso** [comment]
Not sure what is going on.  Using Ubuntu and Chrome browser, cleared cache.
Here is what is in /data/media
![image](https://user-images.githubusercontent.com/5147603/68153907-a6353380-ff03-11e9-8b68-684db273686e.png)
Here is what is in /data
![image](https://user-images.githubusercontent.com/5147603/68153961-c1a03e80-ff03-11e9-8f02-53ea1000548f.png)
Here is a search for unused files.
![image](https://user-images.githubusercontent.com/5147603/68154169-2491d580-ff04-11e9-8066-fbb8353bce0c.png)

**Comment by makitso** [comment]
OK, will give this one last shot.
Clean install of github
Clean installation of webtrees
Create one tree
Add Media object to John Doe tree.gif
/data/media has three files, 
![image](https://user-images.githubusercontent.com/5147603/68155312-b3075680-ff06-11e9-8217-db5129fe6240.png)
Go to Control Panel / Manage media -- shows one file tree.gif
Select unused files -- now shows 21 files, the two unused files, the tree.gif, and 18 files from the thumbnail cache
![image](https://user-images.githubusercontent.com/5147603/68155661-59535c00-ff07-11e9-9bf2-c7bc0fce5dbb.png)

**Comment by makitso** [comment]
Yup, that fixed it -- Thanks!!
