### ISSUE TITLE
Not able to remove elements from multiple selection in preferences form (wt 2.0.0.b4)

### ISSUE THREAD

**Issue by t-karcher** [fisharebest/webtrees#2738]
When I try to remove any element from any of the multiple selection form field in the tree preferences form (... /index.php?route=admin-trees-preferences&ged=test - see screenshots below), all elements are removed and cannot be added again (the list becomes empty). This happens regardless of whether I remove the element by clicking on the "x" or by deselecting it in the dropdown menu. (Tested with Firefox and IE) Adding additional elements works without problems.

Not sure whether this is an issue with Select2, Webtrees, or the combination of both.

Before:
![Screenshot_2019-11-04 Preferences — test](https://user-images.githubusercontent.com/22897030/68117756-7d5e6f80-fefe-11e9-936e-707d8073598c.png)

After:
![Screenshot_2019-11-04 Preferences — test(1)](https://user-images.githubusercontent.com/22897030/68118206-b0553300-feff-11e9-8827-03b7ca479186.png)

**Comment by fisharebest** [comment]
This was caused by the fix for #2548
