### ISSUE TITLE
Where should I place media files (like a Happy new Year file) that are used in html blocks? - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2742]
In pre 2.0.0 they were in themes/pictures.
In early 2.0.0 they were in a directory in data.

**Comment by fisharebest** [comment]
These can be stored in the `public` folder.

e.g. `/public/happy-new-year.mp3`.

To keep your local modifications separate from the core files, you might want to create a subfolder.

e.g. `/public/meliza/happy-new-year.mp3`.
