### ISSUE TITLE
Position of bootstrap popovers can be incorrect on first use

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2743]
On the families tab, the first click on the details icon (magnifying glass with a plus sign in it) results in the detail popup being placed in an indeterminate position on the screen. 2nd and subsequent clicks are ok.

Tested on Edge, Chrome & Firefox

Actually seems to be any person box - i.e favourites on the home page as well

**Comment by fisharebest** [comment]
Interesting.  I've never seen anything like this.

Can you post a screenshot?

**Comment by ddrury** [comment]
Two images showing first & (second & subsequent) location of the popup after clicking on Annie Drury - 
![first](https://user-images.githubusercontent.com/104515/68340267-fff15580-00dd-11ea-9749-7539d7c2e4f0.jpg)

![second](https://user-images.githubusercontent.com/104515/68340271-0253af80-00de-11ea-87ab-b8f4f8a650c1.jpg)

**Comment by ddrury** [comment]
Also happens on demo - check out HM QE2.

**Comment by fisharebest** [comment]
I've just tried it on my work desktop machine, and see the problem there.

The difference seems to be whether or not you scroll first.

My laptop has a small screen, so I was always scrolling down first.

On my desktop, I don't need to scroll - and see the problem.
But if I do scroll first, I don't.

Can you confirm if this is the same behaviour that you see?

**Comment by ddrury** [comment]
Scrolling doesn't seem to make any difference for me, however where I said position is indeterminate above, it's not really. For any individual the position of the popup on the first click is always the same - just different to second and subsequent - unfortunately I've noticed in the past it can sometime be partially off the screen, although I can't find an example at the moment

**Comment by fisharebest** [comment]
Maybe this: https://stackoverflow.com/questions/46476857/popper-js-wrong-initial-position-of-dropdown-tooltip

**Comment by ddrury** [comment]
Looks like it doesn't it

**Comment by fisharebest** [comment]
Hmm.  Not just scrolling.   It's the initial position.

Initial page load. wrong position
Scroll down a few millimetres.  Refresh. Wrong position.
Scroll down a few millimetres.  Refresh. Wrong position.
Scroll down a few millimetres.  Refresh. Wrong position.
Scroll down a few millimetres.  Refresh. Right position.

**Comment by fisharebest** [comment]
Maybe it is to do with the `position` attribute of the parent element.

https://stackoverflow.com/questions/41602487/bootstrap-tooltip-in-wrong-position-on-initial-hover-then-in-correct-position

**Comment by ddrury** [comment]
Interestingly, the boxes on charts don't exhibit this behaviour

**Comment by fisharebest** [comment]
Position of popups is controlled by the "popper" library.

I have just upgraded bootstrap from v4 to v5 (and hence popper from v1 to v2).

I can no longer reproduce the issue.
