### ISSUE TITLE
github-Install error

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2745]
Chinese is selected for installation and cannot be installed.

Fatal error: Uncaught ErrorException: sprintf(): Too few arguments in /home/wwwroot/app/I18N.php:415 Stack trace: #0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(2, 'sprintf(): Too ...', '/home/wwwroot/j...', 415, Array) #1 /home/wwwroot/app/I18N.php(415): sprintf('webtrees\xE9\x9C\x80\xE8\xA6\x81\xE4...') #2 /home/wwwroot/resources/views/setup/step-3-database-type.phtml(25): Fisharebest\Webtrees\I18N::translate('webtrees\xE9\x9C\x80\xE8\xA6\x81\xE4...') #3 /home/wwwroot/app/View.php(186): include('/home/wwwroot/j...') #4 /home/wwwroot/app/View.php(282): Fisharebest\Webtrees\View->render() #5 /home/wwwroot/app/Helpers/functions.php(217): Fisharebest\Webtrees\View::make('setup/step-3-da...', Array) #6 /home/wwwroot/app/Http/ViewResponseTrait.php(51): view('setup/step-3-da...', Array) #7 /home/wwwroot/app/Http/Controllers/SetupController.php(295): Fisharebest\Webtrees\Http\Controllers\Abstrac in /home/wwwroot/app/I18N.php on line 415

**Comment by fisharebest** [comment]
This is an error in the translation file.

> webtrees needs a database to store your genealogy data.

> webtrees需要一个MySQL数据库，版本%s或更高版本。

The translation has a placeholder (%s) that does not appear in the English text.

**Comment by xmlf** [comment]
I haved update translate file.
Thanks!
