### ISSUE TITLE
User message to bottom contact links transfers the user out of the wt site - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2754]
I added app passwords to the test systems.
Messages are now sent. Thanks!

But, after a user sends a message to the bottom contact person, he is transferred out of the test site to amitys.com.

Sending a message from the messages block returns the user to the My page.

see #2718

**Comment by melizaa** [comment]
In demo-dev I am thrown out to https://dev.webtrees.net/

**Comment by fisharebest** [comment]
I tried this, and I am returned back to the original page.

**Comment by melizaa** [comment]
In demo-dev when I send a message using the bottom link from the user moderator, I am transferred out of demo-dev.
I can return to demo-dev by going back in the browser.

After I sign-in to my test system and send a message using a site user, I see the same behavior.

**Comment by fisharebest** [comment]
The demo server (and your server) set a header `Referrer-Policy: strict-origin`.

This means that it does not send the full URL of the current page to the next page.

It's a privacy feature, and makes it harder for sites to track you.

However, it's breaking this functionality, as webtrees doesn't know which URL to return to after sending the message.

We'll need to pass it in explicitly.
