### ISSUE TITLE
github - contact user, send mail fails from home page

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2762]
In Control panel / Sending email, when I select the "Send a test email using these settings" and then save, the system sends me a "test" email.

However, I use the "For technical support or genealogy questions contact Rob Peters." option to "Send a message"  I get the message
"The message was successfully sent to Rob Peters." but nothing is received.
Unfortunately, nothing shows up in the log.

**Comment by fisharebest** [comment]
> "The message was successfully sent to Rob Peters." but nothing is received.

What is the "contact method" setting for your account?
If it is set to "internal messaging only", then you would not get an email.

**Comment by makitso** [comment]
Yes, you are correct, my oversight.
