### ISSUE TITLE
Add paging for batch updates

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2766]
At present, in the batch update module, if processing a large amount of data, it needs to wait for a long time and is prone to timeout errors.
Can paging be added to batch updates?  
For example, you can return the total number to be processed first, and manually set the number of updating  once. After updating once.
 Click "Continue" to continue updating the set number until all updating  are completed.

**Comment by fisharebest** [comment]
IMPORTANT - this fix relies on proper server conguration.

The PHP time limit (`max_execution_time`) must be **less** than the webserver timeout (e.g. `fastcgi_read_timeout` on NGINX).

**Comment by xmlf** [comment]
I am all server configuration is no problem.  
When I batch update-search and replace-regular expression, when there are more than 10000 pieces of updated data, it cannot be successful.

**Comment by fisharebest** [comment]
> When I batch update-search and replace-regular expression, when there are more than 5000 pieces of updated data, it cannot be successful.

WIth the new code, webtrees will stop when there are 3 seconds remaining.

On my server, `php.ini:max_execution_time` is 60 seconds.
So, the batch update will run for 57 seconds.
It will then stop, and display a message saying "time limit reaced".
The user can select "update all" again, to continue processing.

> how many updates can be set each time, these problems will not exist.

We do not set a maximum **number** of updates.
We set a maximum amount of **time**.
