### ISSUE TITLE
Github - Recent changes module - an observation

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2767]
In 1.7 this module showed changes to individuals & families, in 2.0 it seems to include a wider scope e.g changes to shared notes, is this intentional?

**Comment by fisharebest** [comment]
I didn't realise that 1.7 only showed INDI/FAM records.

Is there a reason why we wouldn't show changes to other record types?

**Comment by ddrury** [comment]
I don't have a preference one way or the other and I suspect for everyone who expresses an opinion one way someone else will have the opposite view, so I suggest it be called a feature and leave well alone!
