### ISSUE TITLE
Beta4 is manually upgraded to beta5,WebSite URL

### ISSUE THREAD

**Issue by kexuebin** [fisharebest/webtrees#2769]
Beta4 is manually upgraded to beta5,url:/ index.PHP? Route =% 2ftree% 2fdemo. The latest demo site address of webtrees.net is... / demo dev / trees / demo. What's wrong with me?

**Comment by fisharebest** [comment]
To use these "pretty" URLs, you must do two things:

1) update your webserver configuration to redirect all unknown requests onto `index.php`.

2) add `rewrite_urls="1"` to the file `data/config.ini.php`.
