### ISSUE TITLE
Touch/mobile-friendly theme? (Feature discussion/request)

### ISSUE THREAD

**Issue by Ziris85** [fisharebest/webtrees#2770]
Hello! I was just wondering if anyone knew of any touch- or mobile-friendly themes for webtrees? I've been trying to set it up using an 8" touchscreen for a project of mine, but it's really hard to navigate around since everything is so small (links, drop-downs, etc).

**Comment by Ziris85** [comment]
Also, if there's a more appropriate place for general discussion like this instead of opening issues, please let me know and I'll redirect accordingly :smile:

**Comment by xmlf** [comment]
2.0 is responsive.
https://dev.webtrees.net/demo-dev/tree/demo

**Comment by fisharebest** [comment]
As @xmlf says, webtrees 2.0 is mobile friendly by default.

If there are specific issues with 2.0, then please create separate issues for them.

**Comment by UksusoFF** [comment]
@fisharebest 
In some places webtrees really not mobile friendly:
media page:
![image](https://user-images.githubusercontent.com/1931442/71488596-d2ea3500-283a-11ea-8112-af43f9982bd7.png)
header: 
![image](https://user-images.githubusercontent.com/1931442/71488660-2eb4be00-283b-11ea-89d5-1f4612e8ef98.png)
person title:
![image](https://user-images.githubusercontent.com/1931442/71488677-412ef780-283b-11ea-899b-e9b9cf088469.png)
facts tab:
![image](https://user-images.githubusercontent.com/1931442/71488693-5d329900-283b-11ea-9956-8c2baebe0067.png)
