### ISSUE TITLE
Restore password reset by username

### ISSUE THREAD

**Issue by DaPoHou** [fisharebest/webtrees#2771]
https://dev.webtrees.net/demo-dev/password-request
At present, the password can only be reset via Email address.
This is very inconvenient for many elderly people who forget or have no Email address.
Please resume the password reset function using user name or Email.

In the process of user registration or password reset, the elderly population without Email address should be considered as much as possible, which is a phenomenon in many countries.
And for genealogy research, more of these elderly people participate.
We need to consider carefully how to facilitate these people to register.

At present, I use SMS to send reset password.
Use SMS verification code to register login, reset password, and notify SMS after pending changes are accepted, hoping to integrate functions into the program.

**Comment by fisharebest** [comment]
> At present, the password can only be reset via Email address.

There was a reason for this change...

There are no restrictions on username.  A user could change their username to be the same as somebody else's email.

If I request a password for my username (same as your email), then which one is matched?

So, we will need the user to select email or username.


PS - For a future release, I plan to split the `wt_user` table into two parts - account (username) and identity (email).  This will allow a user to have multiple identities (emails, social-media accounts, SMS, etc.)

**Comment by xmlf** [comment]
> PS - For a future release, I plan to split the `wt_user` table into two parts - account (username) and identity (email). This will allow a user to have multiple identities (emails, social-media accounts, SMS, etc.)

That's great.  The multi-step registration form is recommended.
At present, the information provided by users after registration is too little to link well with individuals in the family tree.
So I changed the registration page and incorporated the added field contents into the comment field.  This will enable me to link users with individuals in the family tree more quickly.
After split the `wt_user` table，hope to consider adding to the release.
