### ISSUE TITLE
Associate dropdown broken in baptism dialogue (2.0.0.b5)

### ISSUE THREAD

**Issue by t-karcher** [fisharebest/webtrees#2772]
This associate dropdown field in the baptism dialogue looked fine in Beta 4 but is broken (=extremely narrow) now:

![Baptism_Associate](https://user-images.githubusercontent.com/22897030/68800723-ed859780-065a-11ea-9050-80e7c174cdaf.PNG)

**Comment by t-karcher** [comment]
Also (related?): The Indi-ID of these associates is saved without "@" and not shown anymore on the individual page since b5:

**Beta 4:**
2 _ASSO @X50@
3 RELA godmother

**Beta 5:**
2 _ASSO X417
3 RELA godmother

**Comment by t-karcher** [comment]
@fisharebest : Thanks! Does this also fix the missing "@" (see second comment), or should I open a separate issue for that?

**Comment by fisharebest** [comment]
It is always better to create separate issues, rather than add extra comments to existing issues.

Trying to combine two issues in one just leads to confusion over statuses, etc.
