### ISSUE TITLE
"Reorder media objects" link missing on individual page (2.0.0.b5)

### ISSUE THREAD

**Issue by t-karcher** [fisharebest/webtrees#2775]
In 2.0.0.b4 there was a link "Reorder media objects" next to the "Add media object" link below the profile picture on the individual page which allowed you to define the picture to be shown as primary profile picture. This link is gone now. :-( Is it hidden somewhere else, or is this a bug?

**Comment by t-karcher** [comment]
Oh - I just found the link in the "edit" drop down menu. So I can still reorder the pictures. If this was done intentionally, this issue can be closed: I don't care where to find this option as long as I can find it.

**Comment by fisharebest** [comment]
This was done intentionally - but I'm not a UX expert, and am happy to accept feedback and consider changes.

The only time I learn that people have problems finding things is when they report issues.

**Comment by t-karcher** [comment]
I'm not an UX expert either, so take this with a grain of salt, but I would move both links (add new media + reorder existing media) in the multimedia tab. And I'm not even sure whether a complex "reorder" feature is really needed: For me, a simple "favourite"/"primary" flag (which would move the selected object up and make it the profile picture) would be sufficient.

**Comment by fisharebest** [comment]
> For me, a simple "favourite"/"primary" flag (which would move the selected object up and make it the profile picture) would be sufficient.

Previously, we had a `1 _PRIMARY Y` flag to indicate the prefered image.  It was a custom tag, and I want to reduce dependence on custom tags.

The 're-order' approach is consistent with other related objects  where we need to show just one item.  (1st name is used, 1st parents are used, 1st birth event is used, etc.).

It is also consistent with the GEDCOM spec, which says that "prefered" things should be placed ahead of others.

So, I want to keep this logic.

**Comment by t-karcher** [comment]
I wasn't talking about the GEDCOM code, but about the user interface: Flagging an image as "preferred" would not necessarly mean to add a custom tag to the code: You could still reorder the objects in the background like you do now. It would just be a more intuitive way to select the default profile picture, e.g. by clicking a star in the media tab:

![grafik](https://user-images.githubusercontent.com/22897030/69387450-198dc200-0cc6-11ea-85e3-a9ee6f3f51f1.png)

Currently, I doubt that any new user could update the profile picture without consulting the documentation.

**Comment by johnds123** [comment]
What can be done to avoid the first image to be the profile image?
I have very few media objects that can be classified as profile image, but a lot of general media objects that should never be used as profile image. See this example with a death certificate displayed as the profile image. Looks quite silly to me.
![image](https://user-images.githubusercontent.com/12587955/70573172-ad55fe00-1ba1-11ea-991f-83c2eb84168d.png)

**Comment by fisharebest** [comment]
You can attach media objects to either individuals or to facts.

In general, you'd add photographs, coats-of-arms, etc. to the individual, and you'd add scans of death certificates to the death event.

You probably want to move this media link from the individual to the death event.

Try:

Control panel -> Media -> Link media objects to facts and events

This lets you scan through all your media, and move media to the correct location with a single click.
