### ISSUE TITLE
unwarranted gender icon

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#2779]
Just upgraded to 1.7.15

Went to edit an individual who did not have a SEX tag.  He did have the generic circle icon in some places, but in the birth fact, between the year and the computed age was a male icon.

**Comment by fisharebest** [comment]
> in the birth fact, between the year and the computed age was a male icon.

You mean like this:

<img width="446" alt="Screen Shot 2019-11-18 at 07 27 51" src="https://user-images.githubusercontent.com/2306088/69032684-fd8fd500-09d4-11ea-8902-6e0e3fb34b5e.png">

The male icon indicates that this is the age of the father at this event.

**Comment by WGroleau** [comment]
Did not see a tooltip, but perhaps it takes a while to appear.
