### ISSUE TITLE
Manager cannot manage the registered users of their genealogy

### ISSUE THREAD

**Issue by DaPoHou** [fisharebest/webtrees#2781]
When a website has multiple genealogies and is assigned to different users for management.
As genealogy managers, they cannot manage the registered users of their genealogy, which is very inconvenient.
When a new user is registered, the manager cannot verify it in time, and must wait for the website administrator to verify it. However, the website administrator does not know about this family tree and knows little about the real information of the registered user, so it is impossible to determine whether it passes the verification.  Only the genealogy manager can determine whether to pass the user registration verification.

It is urgently hoped that each family tree manager can manage the registered users of his own family tree.

**Comment by fisharebest** [comment]
The access roles and permissions have been established for many years.

If we changed them now, it would cause many problems for existing users.

Even if this is a good idea, we cannot change it.

**Comment by DaPoHou** [comment]
At present, it is only necessary to add user management functions to the role of family tree managers, who can edit and verify users.
Or we can add an option, whether it has user management rights.
It is very necessary and reasonable to grant user management authority to every family tree manager.

If the website has multiple genealogical trees, it can be judged according to the $tree->name parameters at the time of registration.
