### ISSUE TITLE
Duplicate families on sidebar 1.7 & 2.0

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2782]
After recent commit to allow reordering of parent families, I decided to check it out and noticed the following behaviour (1.7 & 2.0). I attach a couple of images although most is redacted as living people are involved, however in summary, Iris had relationships with three men, Barry was fathered by Albert and later adopted by David. You will see in the sidebar that Iris's family with Ernest is duplicated. 

If necessary I can copy a gedcom to you
![demo](https://user-images.githubusercontent.com/104515/69043464-ff649300-09ea-11ea-8bde-2611cf6a5de6.jpg)
![demo2](https://user-images.githubusercontent.com/104515/69043470-01c6ed00-09eb-11ea-8671-130cccd1f5a2.jpg)

**Comment by fisharebest** [comment]
To find step-families, the code iterates over all the parent families, and then looks for other spouse-families for each parent.

Your individual has two parent families (birth and adopted).

The mother appears in *both* families, and hence gets counted twice when searching for step-families.

It should be pretty simple to add a "unique" filter to the find-step-family logic.
