### ISSUE TITLE
Github - Reorder families

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2784]
Maybe I'm misunderstanding something here, but for the family I mentioned in issue #2782 and fixed in https://github.com/fisharebest/webtrees/commit/ed5b62270655a3f02d5bf16bc0787babe8bc6d90, the reorder families menu item is greyed out.

**Comment by fisharebest** [comment]
The option should be enabled if *either* more than one spouse-family *or* more than one child-family.

My test data had multiples of both, so perhaps I forgot to update the hide/show logic.

I'll check later.
