### ISSUE TITLE
Github - duplicated or redundant code?

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2785]
Caveat - I'm not sure what I'm doing !!

Class IndividualPage::constructor has the comment IndividualController constructor, and there is an awful lot of duplicated code in the two classes

**Comment by fisharebest** [comment]
The "Controllers" are being migrated into "RequestHandlers".

(A request handler is simply a controller with only one action.  This style of coding forces you to move business logic into separate classes - services)

I guess I did a copy/paste and forgot to delete afterwards.
