### ISSUE TITLE
v1.7 WT_LOGIN_URL looses https scheme when undified

### ISSUE THREAD

**Issue by Salokyn** [fisharebest/webtrees#2788]
Hello,

I'm working at making webtrees 1.7.15 run from a docker stack. (I may post a MR to share it once it runs smoothly)

I acces to my webtrees container through nginx as a https reverse proxy.

![diagram](http://www.plantuml.com/plantuml/png/HOv12i8m44NtSuf_WLx0LHTkbQAubcaojCMObCbK1F7kncgK4FZp7xoPDXkhBTT0x2mfJbcKL9nn78BWA7eJnODYyeBzCCNx-T2H2sdns2PtMI7mntNenhb4pyOzPy6ETMBVqxEyzmuqFnis6CtcJBMex0i-FPfLMNv9rTPAzENs5m00)

The problem is when I go to https://webtrees.url/login.php, the login form action is http://webtrees.url/login.php (without the `s`).

Could `WT_LOGIN_URL` keep the URL scheme by default (when not specified in site_setting table)?
Or maybe we could specify it in config.ini.php like `base-url`?

**Comment by fisharebest** [comment]
In webtrees 2.0, the base URL is set in `config.ini.php`.

In webtrees 1.7, the base URL is autodetected from the request headers.

Can you set add something like `proxy_set_header HTTPS on;` in your NGINX config?

NOTE: webtrees 2.0.0 will be released in a few weeks.  Unless you have a specific reason for working with 1.7, I would recommend you work with 2.0.

**Comment by Salokyn** [comment]
Ok thanks,

In RP config I added:
```
proxy_set_header X-Forwarded-Https $https;
```

And in nginx container config I added in the php part:
```
fastcgi_param HTTPS $http_x_forwarded_https;
```

Don't know if that's clean but that works !
