### ISSUE TITLE
Add media list directories

### ISSUE THREAD

**Issue by Fa10175** [fisharebest/webtrees#2789]
when you try to add media inside special directorie, the list of all directories is displayed

![CreateMedia2 0](https://user-images.githubusercontent.com/10681601/69476084-7c21b380-0dd5-11ea-93f8-a6fc0c911861.jpg)
it display 5 lines and no scroll for the other lines

![CreateMedia1 7](https://user-images.githubusercontent.com/10681601/69476089-82b02b00-0dd5-11ea-8a49-e8ba5e9b07f5.jpg)

**Comment by fisharebest** [comment]
This is the design of the autocomplete library.

e.g. visit https://typeahead.js.org/examples/ and type `a` in the search box.

Only the first 5 results are shown. (The limit can be changed.)

It is not designed to scroll.  You are expected to keep typing...

Perhaps I need to investigate other libraries.

**Comment by Fa10175** [comment]
when i try to write the begining for the directory the list is updating but not right .
why it shows me thumb... ?
![CreateMedia2 0-1](https://user-images.githubusercontent.com/10681601/70308370-6667b180-180b-11ea-810c-057405994c4d.jpg)
