### ISSUE TITLE
Replace PCLZIP

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#279]
The PCLZIP library is no longer compatible with all modern PHP builds.

It needs replacing - perhaps with the native PHP/ZIP library?

**Comment by fisharebest** [comment]
Like a growing number of libraries, Flysystem requires PHP5.4

37% of webtrees sites are hosted on PHP5.3 servers (and 4% on PHP5.2!)
https://dev.webtrees.net/statistics.html

:-(

**Comment by bmhm** [comment]
You can stick to flysystem 0.4: https://github.com/thephpleague/flysystem/issues/23#issuecomment-50155015
Same goes for laravel. If you need to support PHP 5.3, go for an old version: http://dor.ky/install-old-version-of-laravel-4-1-x-for-php-5-3-servers-using-composer/

Suggestions:
1. Use an older laravel and flysystem for the upcoming webtrees 1.7 so it will be compatible with PHP 5.3. 
2. Create a 1.8 version with PHP 5.4-compatibilty and upgrade flysystem and laravel.
3. Recommend more modern hosters, like dreamhost, uberspace, etc.

**Comment by fisharebest** [comment]
webtrees 1.8 (laravel based) will require PHP5.4, but will take some time to write.

I am planning to create 1.8 as a new/clean project, with 1.7 as a dependency to allow code reuse.  This is why I am busy converting all the code to use PSR4 autoloading.

webtrees 1.7 will be released soon - no new features, just refactoring and bugfixing.  It will need to be supported for some time (a year?).

**Comment by bmhm** [comment]
Are results in for the new version? I saw it contains a php version warning.

**Comment by bmhm** [comment]
About the statistics:

> Ihave more than one installation of webtrees on the same server. How is this counted?
> This will only get counted as one server.

Is this an issue on shared hosting? On Uberspace, each customer can choose his php version and create his own php.ini file.

**Comment by MetalMatze** [comment]
Hey, I would not hesitate to go forward with at least PHP 5.5. PHP 5.3 isn't even supported by PHP anymore. Which version of laravel do you plan on using?
I'd suggest to use laravel 5.1 because it's the first [LTS](https://laravel-news.com/2015/05/laravel-announces-v5-1-will-be-lts/) with 3 years of bug fixes. But laravel 5.1 requires PHP >= 5.5.9.

Having developed for Android in the past I know the struggle of supporting older Android versions. But are those people who are running Android 2.x nowadays, the ones your new version will be for?

Are the users running PHP < 5.4 even upgrading to a new version? I doubt it. So don't build for them, build for the people wanting a new webtrees!

**Comment by bmhm** [comment]
PHP 5.5.9 was released on 06 Feb 2014. So it is quite new. If not PHP 5.5, I'd love to see webtrees 1.8 being the first version to require 5.4 and the last version to support 5.4.

By the way, this issue is tagged with PHP 5.5 @MetalMatze. ;-)

**Comment by fisharebest** [comment]
> Are the users running PHP < 5.4 even upgrading to a new version? I doubt it.

If we look at people who are using webtrees 1.7 (i.e. people who have upgraded in the last 6 months), we can see that almost half of them run on servers  with obsolete versions of PHP.

See https://dev.webtrees.net/statistics.html

**Comment by bmhm** [comment]
@fisharebest it might be that those ppl have 5.5 or 5.6 available, but just need to change a single config item in their hosters config panel. Like uberspace, where I forgot to change my php.config file. It was just changing one number. The warning you implemented in admin area was really helpful.

So it might not be too big of a problem to require 5.5.

**Comment by Amgine0** [comment]
Yes, it would be a big problem. My stock Debian is running php 5.4.44-0+deb7ul. That's a very large server base. You would need to support too many OSes with "how to upgrade/how to use unstable/how to..." imo.

**Comment by Amgine0** [comment]
On a related note: zip span is not base supported on android 5.x. (This pisses me off no end with ownCloud.)

**Comment by bmhm** [comment]
That would be Debian wheezy.
LTS: Debian 7 “Wheezy” from February 2016 to May 2018

Still, you can upgrade. If my Hoster has only PHP 5.4, I'd already be miles away. That's not very nice for customers to offer. PHP is a very modern and dynamic language. 

https://www.dotdeb.org/instructions/

**Comment by Amgine0** [comment]
For that machine, I am my hoster. But this issue is about the archiving library.

**Comment by bmhm** [comment]
which we can't use because of PHP restrictions.

**Comment by Amgine0** [comment]
php/zip uses zlib, compatible with 5.2+ I believe. (That is, the native php library works.)

**Comment by bmhm** [comment]
Flysystem requires PHP 5.4. 
I'd still like to see wt 1.8 to be the first and last version which supports php5.4 and then go for a more current laravel version. Php 5.5 will be some years old by then.

**Comment by HonkXL** [comment]
Is this the reason for this error when downloading a zip compressed tree on PHP 7.1?

`
/var/www/vhosts/weiland24.de/httpdocs/webtrees/includes/session.php:193 /var/www/vhosts/weiland24.de/httpdocs/webtrees/vendor/pclzip/pclzip/pclzip.lib.php:1797 A non well formed numeric value encountered #0 /vendor/pclzip/pclzip/pclzip.lib.php:1797 ErrorException("/var/www/vhosts/weiland24.de/httpdocs/webtrees/vendor/pclzip/pclzip/pclzip.lib.php:1797 A non well formed numeric value encountered") #1 /vendor/pclzip/pclzip/pclzip.lib.php:513 privOptionDefaultThreshold([array]) #2 /admin_trees_download.php:75 add('/var/www/vhosts/weiland24.de/h…', 77012, 'Created by webtrees 1.7.8 on W…', 77003, '/var/www/vhosts/weiland24.de/h…')
`

**Comment by fisharebest** [comment]
Probably not.  From the code, it most likely looks like an improper value of `memory_limit` in `php.ini`.

**Comment by HonkXL** [comment]
Memory Limit is 760M - this value is displayed in "server informations" inside webtrees, too.

**Comment by fisharebest** [comment]
I looked again.  The PCLZIP code is not compatible with PHP 7.1

**Comment by fisharebest** [comment]
Try replacing `760M` with `796917760`

**Comment by fisharebest** [comment]
The PCLZip library has not been updated for 3 years, and is not compatible with PHP 7.1

**Comment by HonkXL** [comment]
Yes, thats true. But replacing it with ZipArchive as mentioned by JustCarmen would be the solution.

http://php.net/manual/en/class.ziparchive.php

**Comment by bmhm** [comment]
@fisharebest now there is the option to NOT support current releases, but legacy releases (which are out of support) or current releases and not so old releases.

From what I know from our previous discussion, you'd like to keep support for older PHP versions, which are still used (see statistics). Is this still true?

**Comment by fisharebest** [comment]
The next release will be 2.0.0.  It will support PHP 5.6 -> 7.1

The previous release (1.7.x) will support PHP 5.3 -> 7.0.  It will only receive updates for secuirty and major bugs.

**Comment by fisharebest** [comment]
`PclZip` has been replaced with `flysystem/ziparchive`

**Comment by Art4** [comment]
Is there a plan to get this fix into webtrees 1.7.10?

**Comment by furlongm** [comment]
Seeing this error when upgrading to 1.7.10 via web interface:

Unzip webtrees-1.7.10.zip to a temporary folder…/var/www/webtrees/includes/session.php:193 /var/www/webtrees/vendor/pclzip/pclzip/pclzip.lib.php:1797 A non well formed numeric value encountered #0 /vendor/pclzip/pclzip/pclzip.lib.php:1797 ErrorException("/var/www/webtrees/vendor/pclzip/pclzip/pclzip.lib.php:1797 A non well formed numeric value encountered") #1 /vendor/pclzip/pclzip/pclzip.lib.php:783 privOptionDefaultThreshold([array]) #2 /admin_site_upgrade.php:296 extract(77001, '/var/www/webtrees…', 77003, 'webtrees', 77016)

**Comment by furlongm** [comment]
Same error upgrading 1.7.11 via web interface

**Comment by fisharebest** [comment]
https://webtrees.github.io/faq/upgrade-numeric

**Comment by bmhm** [comment]
This should be linked on the update page (perhaps only if the user is running php7).

RFE hereby submitted. ;-)

Thanks for the helpful link!
