### ISSUE TITLE
V2 suggestion - control panel - manage family trees - check for duplicates

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2791]
For media objects, include the filename in the compare function

**Comment by fisharebest** [comment]
Wouldn't this just ensure that there are never any duplicates?

The whole purpose of this check is to ensure that media objects have unique titles.
The title is used as an `alt` tag for the image.

**Comment by ddrury** [comment]
It clearly depends on what you class as duplicates - it would still find two identical media objects, but the reason I suggested this is that I have a large number of photos when I know the person(s) involved but not the date, place or any other details so I just end up titling them Fred & Maisie Bloggs, I accept that I could say the obvious (Fred & Maisie on the beach) or Fred & Maisie 1, 2 etc.
but that really doesn't add any real benefit to the picture itself.
