### ISSUE TITLE
Github - Maps - Leaflet.BeautifyMarker does not support FontAwesome v5

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2794]
fa-globe - the icon for the place markers

**Comment by fisharebest** [comment]
I can't find `fa-globe` in the code.

I guess it needs to be changed to either the map icon or the location icon.

**Comment by ddrury** [comment]
Either would suit wouldn't it

**Comment by fisharebest** [comment]
I don't know where it is used.  I can't find `fa-globe` anywhere.

**Comment by ddrury** [comment]
Ah .. wionderful L.BeautifyIcon!!
PlaceHierarchyController line 310 and then loaded in map-place view line 123+

**Comment by ddrury** [comment]
There is a pull request on the BeautifyIcon github site for FontAwesome 5 that has been there since Oct 2018

**Comment by fisharebest** [comment]
`globe` on its own doesn't really work...

With FA-5, you need to specify the icon set - either `far fa-globe` or `fas fa-globe`.

**Comment by ddrury** [comment]
Yeah, BeautifyIcon supplies the prefixes but for FontAwesome 5 they have changed, I've just commented out all the icon code to make it use the default and that doesn't work either. I'll have a look tomorrow to see if the pull request fixes it, other wise I guess it's a different icon library

**Comment by ddrury** [comment]
Guess it shouldn't come as a surprise but all the maps have the same problem!

**Comment by ddrury** [comment]
I'm trying to use a different library, I've changed `"beautifymarker": "^1.0.7", ` to `"leaflet-extra-markers": "^1.1.0",` in package.json, and tried to run npm install and npm run production but am having problems (see attached), 
I've set an environment variable NODE_ENV=production
and if I look at the log mentioned I see the following lines
```
9 verbose lifecycle @~production: CWD: D:\Server\nginx\html\sites\webtrees-2.0
10 silly lifecycle @~production: Args: [ '/d /s /c',
10 silly lifecycle   'NODE_ENV=production node_modules/webpack/bin/webpack.js --config=node_modules/laravel-mix/setup/webpack.config.js' ]
11 silly lifecycle @~production: Returned: code: 1  signal: null
12 info lifecycle @~production: Failed to exec production script
```
I have files webpack, webpack.cmd, webpack-cli, webpack-cli.cmd, webpack-dev-server and webpack-dev-server.cmd but no webpack.js in the path mentioned above

HELP!
BTW on a windows 10 machine

![dump](https://user-images.githubusercontent.com/104515/69713820-1dbe4300-10fd-11ea-8992-5bffa0f84ac0.jpg)

**Comment by ddrury** [comment]
correction, I do have webpack.js

**Comment by fisharebest** [comment]
I think you are running a linux script at a windows prompt.

Do you have `bash` (or any other shell) available?  I seem to remember reading that Windows now ships with a bash shell.

IIRC, it is possible to write that script to run on either linux/windows.

**Comment by ddrury** [comment]
Doh, wish I was clever

**Comment by ddrury** [comment]
I can now run` npm install` and` npm  run production/development ` the js is compiled but I'm missing the css and the associated images. Any suggestions?

**Comment by fisharebest** [comment]
What do you mean by "missing"?  Not created?  Not updated?

Here's the output from `npm run production` on my server

```
> @ production /Users/gr4376/Projects/webtrees
> NODE_ENV=production node_modules/webpack/bin/webpack.js --config=node_modules/laravel-mix/setup/webpack.config.js



 DONE  Compiled successfully in 16792ms                                                                                           16:29:08

                               Asset       Size  Chunks                          Chunk Names
         /css/administration.min.css    173 KiB       0  [emitted]               /js/vendor.min
                 /css/clouds.min.css    145 KiB       0  [emitted]               /js/vendor.min
                 /css/colors.min.css    195 KiB       0  [emitted]               /js/vendor.min
      /css/colors/aquamarine.min.css   1.19 KiB       0  [emitted]               /js/vendor.min
             /css/colors/ash.min.css   1.19 KiB       0  [emitted]               /js/vendor.min
/css/colors/belgianchocolate.min.css   1.19 KiB       0  [emitted]               /js/vendor.min
      /css/colors/bluelagoon.min.css   1.19 KiB       0  [emitted]               /js/vendor.min
      /css/colors/bluemarine.min.css   1.19 KiB       0  [emitted]               /js/vendor.min
  /css/colors/coffeeandcream.min.css   1.19 KiB       0  [emitted]               /js/vendor.min
         /css/colors/coldday.min.css   1.19 KiB       0  [emitted]               /js/vendor.min
       /css/colors/greenbeam.min.css   1.19 KiB       0  [emitted]               /js/vendor.min
    /css/colors/mediterranio.min.css   1.19 KiB       0  [emitted]               /js/vendor.min
         /css/colors/mercury.min.css   1.18 KiB       0  [emitted]               /js/vendor.min
       /css/colors/nocturnal.min.css   1.19 KiB       0  [emitted]               /js/vendor.min
          /css/colors/olivia.min.css   1.19 KiB       0  [emitted]               /js/vendor.min
     /css/colors/pinkplastic.min.css   1.19 KiB       0  [emitted]               /js/vendor.min
            /css/colors/sage.min.css   1.17 KiB       0  [emitted]               /js/vendor.min
     /css/colors/shinytomato.min.css   1.19 KiB       0  [emitted]               /js/vendor.min
         /css/colors/tealtop.min.css   1.19 KiB       0  [emitted]               /js/vendor.min
                    /css/fab.min.css   75.1 KiB       0  [emitted]               /js/vendor.min
           /css/images/layers-2x.png   1.23 KiB          [emitted]               
              /css/images/layers.png  696 bytes          [emitted]               
      /css/images/marker-icon-2x.png   2.41 KiB          [emitted]               
         /css/images/marker-icon.png   1.43 KiB          [emitted]               
       /css/images/marker-shadow.png  618 bytes          [emitted]               
                /css/minimal.min.css   65.7 KiB       0  [emitted]               /js/vendor.min
                     /css/vendor.css    195 KiB          [emitted]               
                 /css/vendor.min.css    282 KiB       0  [emitted]        [big]  /js/vendor.min
               /css/webtrees.min.css    181 KiB       0  [emitted]               /js/vendor.min
                  /css/xenea.min.css    205 KiB       0  [emitted]               /js/vendor.min
                   /js/vendor.min.js   1.01 MiB       0  [emitted]        [big]  /js/vendor.min
               /js/vendor.min.js.map   4.73 MiB       0  [emitted] [dev]         /js/vendor.min
                 /js/webtrees.min.js   20.8 KiB          [emitted]               
     /resources/fonts/DejaVuSans.ttf    739 KiB          [emitted]               
```

**Comment by ddrury** [comment]
My output is more or less the same, every line is there and allowing for differences in file systems the file sizes are pretty close, however whilst the extra-markers script is included in` vendor.min.js` the css isn't in `vendor.min.css`. If I manually append it to `vendor.min.css` and copy the images into a new folder under public then everything works.

If I understand things correctly when the css is compiled the relative paths of images are corrected - is that correct? if so the only problem is the fact that somehow the css is being skipped.

**Comment by ddrury** [comment]
Well, apart from the CSS problem, I've updated the views and Controller/Modules to use Extra-Markers successfully

**Comment by fisharebest** [comment]
> the css isn't in vendor.min.css

Did you include it in `webpack.mix.js`?

**Comment by ddrury** [comment]
No,
Would you like to give me a clue?
The locations are
src/assets/css/leaflet.extra-markers.css
src/assets/img/*.*
dist/css/leaflet.extra-markers.min.css
dist/img/*.*

**Comment by fisharebest** [comment]
https://github.com/fisharebest/webtrees/blob/baef639bc75c0933c577b8512ecd71c3e626999d/webpack.mix.js#L31

**Comment by ddrury** [comment]
I was looking in the wrong place: `node_modules\laravel-mix\setup\webpack.mix.js` - got it working now. A bit of tidying then I'll do a pull req

**Comment by ddrury** [comment]
Ho-hum, spoke too soon, js & css going into the correct vendor files and the images going to public/css/images but I can't get the urls in the css updated (either fixing the path or converting to inline) - I think it seemed to work earlier because of browser caching

**Comment by fisharebest** [comment]
> but I can't get the urls in the css updated

This should be automatic.  URLs are resolved and converted to inline data.

If the package offers both src and dist folders, the dist one is probably the one you want, as it will usually have the correct relative URLs.

**Comment by ddrury** [comment]
That's what I thought, the urls in `dist/css/leaflet.extra-markers.min.css` are of the form` ../img/markers_shadow.png` and the bits of webpack.mix.js I've changed are here

```
mix.styles([
    "node_modules/bootstrap/dist/css/bootstrap.min.css",
    "node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css",
    "resources/css/begin-ignore-rtl.css",
    "node_modules/select2/dist/css/select2.min.css",
    "resources/css/end-ignore-rtl.css",
    "node_modules/typeahead.js-bootstrap4-css/typeaheadjs.css",
    "node_modules/leaflet/dist/leaflet.css",
    "node_modules/leaflet-geosearch/dist/style.css",
    "node_modules/leaflet.markercluster/dist/MarkerCluster.Default.css",
    "node_modules/leaflet.markercluster/dist/MarkerCluster.css",
    "node_modules/leaflet-extra-markers/dist/css/leaflet.extra-markers.min.css",
], "public/css/vendor.css");

mix
    .autoload({
        jquery: ["$", "jQuery"],
    })
    .setPublicPath('./public')
    .sourceMaps()
    .js("resources/js/vendor.js", "public/js/vendor.min.js")
    .babel(["resources/js/webtrees.js", "resources/js/statistics.js", "resources/js/treeview.js"], "public/js/webtrees.min.js")
    .copy("node_modules/leaflet/dist/images/*", "public/css/images/")
    .copy("node_modules/leaflet-extra-markers/dist/img/*", "public/css/images/")
    .copy("node_modules/dejavu-fonts-ttf/ttf/DejaVuSans.ttf", "resources/fonts/")
```

**Comment by fisharebest** [comment]
You shouldn't need to copy the images to the public folder, as the images should be embedded in `vendor.min.css`.

**Comment by ddrury** [comment]
removed the copy line but no change

**Comment by ddrury** [comment]
Just noticed something, the marker images are a sprite - does that make a difference?
![markers_default](https://user-images.githubusercontent.com/104515/69865161-665e3380-1298-11ea-8da3-5ba0761f5cb5.png)

**Comment by ddrury** [comment]
BTW Just shoved up a pull request that makes use of leaflet-extra-markers - it works as long as you put the images in public/img.

There look like a lot of changes but really they just simplify the script in the views, change the icon library and fix the place hierarchy bug that placed invisible markers on the map

**Comment by fisharebest** [comment]
The solution is to add the category to the icon name.

e.g. `$icon = 'university fas'`
