### ISSUE TITLE
display in French last change on left

### ISSUE THREAD

**Issue by Fa10175** [fisharebest/webtrees#2796]
just for information:

![image](https://user-images.githubusercontent.com/10681601/69564458-5eaa4080-0fb3-11ea-8ed3-49f5ce1a1676.png)

**Comment by fisharebest** [comment]
I have:

* enabled word-wrap in the titles
* removed the first column for blocks on the right
* enabled horizontal scrolling for the table.

There is one more thing that can be done.

In the translation, you can add "soft hyphens".
These allow words to wrap when there is insufficient space.

e.g. `Dernière modification` => `Dernière modifi&shy;cation`

**Comment by fisharebest** [comment]
<img width="970" alt="Screen Shot 2019-11-26 at 17 06 12" src="https://user-images.githubusercontent.com/2306088/69655720-13556800-106f-11ea-891d-39bef3dbd152.png">
