### ISSUE TITLE
Support for MacFamilyTree Custom GEDCOM

### ISSUE THREAD

**Issue by bkintanar** [fisharebest/webtrees#2797]
I imported my family tree from Mac Family Tree 9 and it seems that they are including some custom GEDCOM tags as seen below.

Is there a plan to support such custom GEDCOM? If not, can webtrees ignore custom unsupported GEDCOM tags upon importing?

![image](https://user-images.githubusercontent.com/685928/69730563-424d0600-1163-11ea-86f9-200fcf4f52eb.png)

**Comment by fisharebest** [comment]
Which version of webtrees are you using?

**Comment by fisharebest** [comment]
There is a configuration option in the family tree preferences: "Show GEDCOM errors".

Change this to suppress the invalid/custom GEDCOM tags.

(The HTML errors for these tags is fixed in bf9caab)
