### ISSUE TITLE
gedcom - Adoption fact has unneeded <br> tag

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2800]
![image](https://user-images.githubusercontent.com/5147603/69828899-ea51e600-11da-11ea-913f-58c925f4b938.png)

![image](https://user-images.githubusercontent.com/5147603/69828812-9e9f3c80-11da-11ea-8988-b17ffa234eaf.png)

**Comment by makitso** [comment]
Perhaps deleting lines 339 and 340 of FunctionsPrintFacts.php might do the trick?

**Comment by fisharebest** [comment]
340 gives the spacing between the date/place and the other attributes.

I think the layout is better *with* this space.

So we need to supress it when there is no date/place
