### ISSUE TITLE
github - Routing problem on display of media

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2805]
Demo site:  When your looking at an individual "Elizabeth Angela Marguerite Bowes-Lyon" and you click on the media object in the Death fact the media object is displayed.  
1. There is no close icon.  
2. If you choose the browser (FF) back option you're directed to the home page suggesting a routing problem.

**Comment by fisharebest** [comment]
Was this fixed by #2804 ?

If not, can you post a screenshot showing "There is no close icon".

**Comment by makitso** [comment]
Fixed
