### ISSUE TITLE
Frozen map of interactive tree

### ISSUE THREAD

**Issue by mrqd9** [fisharebest/webtrees#2810]
Interacrive tree is frozen (unable to move) on my mobile phone screen.

**Comment by oniox** [comment]
Please is there an ETA for this fix by any chance? 
Many thanks for your assistance.

**Comment by mrqd9** [comment]
> Please is there an ETA for this fix by any chance?
> Many thanks for your assistance.

This can be a temporary solution until an official fix found, I added this style to custom "CSS and JS" module:
`<style>.tv_in{position:relative; height:100%;overflow:scroll;}</style>`

**Comment by fisharebest** [comment]
Unfortunately, that CSS does not allow the tree to expand when you scroll past the edge, and it breaks on non-mobile devices.

I guess that we need to respond to touch events as well as mouse events.

**Comment by fisharebest** [comment]
Issue #1710 is in the same block of code, and should probably be fixed at the same time.

**Comment by oniox** [comment]
Wow. 
Thanks a million @fisharebest !

**Comment by mrqd9** [comment]
>Fix:42584a2
Tree movement and expansion is ok now, but individual boxes in tree are not getting enlarged on touch, as earlier. (experienced @ phone screen)
