### ISSUE TITLE
github - Lifespans does not show default person

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2812]
Not sure if this is a bug or not.  With 1.7, the Lifespans chart show default person whereas beta does not.

![image](https://user-images.githubusercontent.com/5147603/69966898-8c701780-14d4-11ea-85db-3da2dec530ae.png)

**Comment by fisharebest** [comment]
The same applies to the timelines chart.

The reason for removing it is that on the other charts, you simply need to select a different individual.

On timeline/lifespans, you need to actively remove the intial person as well.

So it was a guess on whether people would more often visit these charts from the desired individual, or visit them from some other page.

I guess it's probably better to keep the original behaviour.  Nobody complained about it!
