### ISSUE TITLE
wheelzoom

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#2816]
Could we have the wheelzoom function added to colorbox to allow images to expand when zooming?

**Comment by fisharebest** [comment]
It works for me...

Can you give any more information about what you are doing or how I might reproduce this?

**Comment by HRN65** [comment]
In 2.0 the image will only expand within the original frame. 

![2_0](https://user-images.githubusercontent.com/55854079/70027934-9dd42500-15a3-11ea-97b6-f10990fdef75.jpg)
![1_7](https://user-images.githubusercontent.com/55854079/70027942-a4629c80-15a3-11ea-8d26-a5a2b6dc8d3b.jpg)

**Comment by fisharebest** [comment]
There was a patch available for the old version of wheelzoom to do this.

Then the library was updated, and the patch no longer worked.

I raised this with the author of the package https://github.com/jackmoore/wheelzoom/issues/3

I guess we need to find a replacement for the colorbox/wheelzoom packages.

**Comment by fisharebest** [comment]
I guess this duplicates #1384
