### ISSUE TITLE
Hindi translation - relationship names

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#2822]
> Translation for Hindi strings(836-841) needs (-1) one number less value for %s. 
> (as "great 5× uncle" is "पर 4× दादा") if %s is 5, translation needs 4.
> https://weblate.iet.open.ac.uk/translate/webtrees/webtrees/hi/?checksum=a35b8ff082b358c8
>
> Same again strings(878-889) great nephew is grandson. 
> Needs -1 value of %s.

**Comment by mrqd9** [comment]
Is it done?

**Comment by fisharebest** [comment]
Yes.  Here is the code change:

https://github.com/fisharebest/webtrees/commit/0b35263af65d2bb8a86d2ae2ccd9939e5b24a91c

**Comment by fisharebest** [comment]
https://dev.webtrees.net/demo-dev/tree/demo/relationships-0-99/i10/i22

<img width="713" alt="Screen Shot 2019-12-05 at 20 55 50" src="https://user-images.githubusercontent.com/2306088/70273270-a7c37700-17a1-11ea-8613-eef5e237e1d9.png">
<img width="738" alt="Screen Shot 2019-12-05 at 20 55 35" src="https://user-images.githubusercontent.com/2306088/70273276-aa25d100-17a1-11ea-990e-025b1b419cb7.png">
