### ISSUE TITLE
Improvement: editor for SUBM-Tag

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#2823]
In my GEDCOMs there is the part below. This is great if you send GEDCOM files to other persons. But there is no possibility to edit this in webtrees.

I think a editor for the Submitter Tag would be fine.

```
0 @SUBM@ SUBM
1 NAME Thomas Weiland
1 ADDR My address
2 CONT zip city
2 CONT Germany
2 CONT Homepage: www....
2 CONT E-Mail: mymail@dfasfd.sadfsdfsdf
0 TRLR
```

**Comment by fisharebest** [comment]
This already exists...

Here's a screenshot from the demo site:

<img width="1176" alt="Screen Shot 2019-12-06 at 10 59 47" src="https://user-images.githubusercontent.com/2306088/70318266-9026d580-1817-11ea-8309-8287bba71bc8.png">

This also works for other special record types, such as `SUBN` and `HEAD`.

**Comment by mpwt** [comment]
But the Submitter Tag doesn't exist automatically and then it is not possible to change them.

I have six trees ([my homepage](https://ffp.bauschaffen.de)), but only three have this tag in the database:
[1](https://ffp.bauschaffen.de/index.php?ctype=gedcom&ged=Pannier) from TNG imported -> 0 @ SUB1 @ SUBM
not visible - created with webtrees 1.7.9 (Mar 2017) -> 0 @ SUBM @ SUBM
[3](https://ffp.bauschaffen.de/index.php?ctype=gedcom&ged=Kuhne-Gollmenz) from Legacy imported -> 0 @ S0 @ SUBM

There I can search for SUB1, SUBM or S0 and see a search result.

All other tree were create with webtrees (Aug 2017, Oct 2017, Nov 2018). However, when I look into the exported Gedcom files, I find a Submitter tag in the other trees as well.

How can I add and extend this tag?

**Comment by fisharebest** [comment]
> But the Submitter Tag doesn't exist automatically and then it is not possible to change them.

`SUBM` can be used in three places: `INDI`, `FAM`, `HEAD`.

You can add easily add submitters to `INDI` and `FAM`:

* Control panel -> Family tree preferences -> Individuals facts -> Add "Submitter"
* Individual -> Add fact -> Submitter
* Create a new submitter or link to an existing one.

For the `HEAD` record, you can use the "Edit raw GEDCOM" option to add a link to an existing submitter.

What is missing:
* `1 SUBM @XXX@` is not linked to `XXX`
* The page for a submitter does not show the linked individuals/families.

Perhaps we could use `SUBM` records to indicate who has edited the record - instead of `1 CHAN/2 _WT_USER`?

**Comment by mpwt** [comment]
> For the HEAD record, you can use the "Edit raw GEDCOM" option to add a link to an existing submitter.

v1.7 -> Where I can edit `SUBM` if it doesn't exist? Where I can add it in a tree created in webtrees?

In FunctionsExport.php (line 111) the SUBM tag is only added during the export.

**Comment by fisharebest** [comment]
> v1.7 -> Where I can edit SUBM if it doesn't exist? Where I can add it in a tree created in webtrees?

You can now edit the `HEAD` record.  (Type "HEAD" in the search box).
There is an option to add/create a submitter.

**Comment by mpwt** [comment]
Will you make the fix also available for v1.7 too? It is currently only available in the branch "develop".

_Thanks a lot for your work. Have a nice second Advent._

**Comment by fisharebest** [comment]
> Will you make the fix also available for v1.7 too?

No.  1.7 only gets fixes for translations, security and major bugs.

The changes will be merged into the master branch (2.0) soon.

**Comment by mpwt** [comment]
Ok, if there is no Submitter tag available, the easiest way for version 1.7 will be to export a gedcom file, make the changes or additions there, and import them back into webtrees. This requires a minimum of Gedcom knowledge. The tag can then be found using the search function and then processed further.

With version 2 I will have to wait until certain add-ons have been updated.

**Comment by fisharebest** [comment]
> With version 2 I will have to wait until certain add-ons have been updated.

I've written the code for SUBM support.  I haven't had time to test it.

This is why it is in the `develop` branch.

I don't want to push untested code to the `master` branch right now, in case someone reports a major problem with 2.0.0 and I have to release 2.0.1 urgently.

Can you wait a few days?

**Comment by mpwt** [comment]
> Can you wait a few days?

Thank you for your work. You have all the time you need. The submitter tag is not so important. :)

_What I wrote about v2 was that I will not update until some add-ons are available for v2 (f.i. custom themes, fan chart etc.). For testing I'm already using v2 locally._

**Comment by fisharebest** [comment]
Submitters now exist as "first-class" obejcts.

There are submitter lists.
You can edit/create/delete submitters.
You can link submitters to `INDI`/`FAM`/`HEAD` records.

Please create a new issue for any problems.
