### ISSUE TITLE
Relationships - names of relationship in Hindi

### ISSUE THREAD

**Issue by mrqd9** [fisharebest/webtrees#2824]
For "Great ×## grandfather" 
Translation needs two variations, "maternal grandfather" or "paternal grandfather"
(and great grandmother, great aunt/uncle, great niece/nephew or grandson/daughter, etc. also) 

Most relationship names translated from English are not so perfect for Hindi, but somehow Hindi speakers are also influenced by English, so these translations may work for the time. 

Extremely waiting for upcoming new relationship system.

**Comment by fisharebest** [comment]
Please add any comments to #2331 so that all the information is in one place.  Thanks!
