### ISSUE TITLE
Editing SOUR link - no CALN field available

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#2826]
The CALN field is only available when creating new REPO links.

A workaround is to delete the existing REPO link, and create it again (with the CALN).

**Comment by wsb56** [comment]
Or edit the source by "GEDCOM Rohdaten bearbeiten" and add the CALN. This will preserve the data.

**Comment by fisharebest** [comment]
This fix has been merged into the main branch, and will be included in 2.1.0.
