### ISSUE TITLE
AFN links to familysearch.org no longer work

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#2829]
FamilySearch no longer allow direct links to AFN pages.

We should probably remove the links.

**Comment by gregkuhnert** [comment]
I checked again, and there are two options to fix this within app/Functions/FunctionsPrintFacts.php: Both are listed below, and work fine. My earlier testing indicated one option was not working, but I re-tested and they both work fine. The first option is a native search form, which is pre-populated with the AFN. The second option below takes you direct to a detail page for the individual. Both options require the user to be logged into FamilySearch, which is acceptable. Even after going to one of these links, it is possible to login and still get to the data without needing to start again. NOTE: Login details can be cached for up to 14 days, so not a big issue.

Which of the options below to use is a matter of preference and taste - they both work.
 ```
          case 'AFN':
                echo '<div class="field"><a href="https://www.familysearch.org/tree/find/id?search=1&id=', rawurlencode($fact->value()), '">', e($fact->value()), '</a></div>';
                echo '<div class="field"><a href="https://www.familysearch.org/tree/person/details/', rawurlencode($fact->value()), '">', e($fact->value()), '</a></div>';
                break;

```

**Comment by rsbarreiro** [comment]
I generated my GEDECOM by importing the familySearch tree with the RootsMagic software. He created "_FSFTID" tags on my GEDECOM ... I modified the files of the vesta_personal_facts module to look like this (open in new window)
![falquer_familisearch](https://user-images.githubusercontent.com/25822701/81016003-0c106280-8e36-11ea-9a6b-76f304c588dc.png)
:
