### ISSUE TITLE
Stories somehow disappeared (not reproducible) 2.0.0.b5

### ISSUE THREAD

**Issue by t-karcher** [fisharebest/webtrees#2841]
**UPDATE: The GEDCOM (re)import was not the cause for this loss! (see last comments)**

<strike>I learned the hard way that exporting and importing the same GEDCOM file to the same family tree will delete all stories (added via the stories module) previously linked to this family tree. While I was able to restore them from backups, I still wish there was a more convenient way to re-import a tree without losing those stories. Could you please add an option (similar to the "keep media" option) to keep them? Thanks!

(An alternative could be an option to save stories as media objects, which could then be included in the GEDCOM export, but this would probably require major changes in the stories module...)</strike>

**Comment by fisharebest** [comment]
> I learned the hard way that exporting and importing the same GEDCOM file to the same family tree will delete all stories 

I can't reproduce this.

I created a tree.
I created a story.
I exported/imported the tree.
The story still exists.

The system is designed to keep all this data (module settings).

Did you import the GEDCOM file into the *EXACT SAME* tree, or into a different tree with the same name?

**Comment by t-karcher** [comment]
Oh. Interesting. I checked more backups, and you're right: The stories were still there after the reimport, but got lost some time after that (approx. four weeks ago). Unfortunately, there's not much I can say about the circumstances. All I remember is I upgraded from 2.0.0.b4 to 2.0.0.b5 at that time (which didn't cause any issues I'm aware of). Now I see the IDs previously used for these stories in the database are missing both in wt_block and wt_block_settings. I'll try to investigate further, but I currently don't know what else to check.

**Comment by t-karcher** [comment]
After some more research it seems like there's at least one other user affected by this strange bug: https://www.webtrees.net/index.php/en/forum/help-for-2-0/33426-the-biography-disappeared-inexplicably 
I tried hard to find any trigger for this, but failed so far: 
- I changed from PHP 7.1 to 7.3 a couple of days ago, but when I switched back and forth again today nothing was lost.
- I tried restricting stories to certain languages and removing those restrictions again. Worked as expected and nothing was lost.
- I did not do anything directly on database level in the last four weeks, so this also cannot be the reason for the loss.

I'll rename this issue and keep it open for some days - maybe someone has another idea what to try / look for?

**Comment by t-karcher** [comment]
Still no idea what caused the loss, but after restoring my stories from backups I didn't face any problems with the current release, so I'll close this issue for now.

**Comment by fisharebest** [comment]
OK - if it happens again, create a new issue.

**Comment by kexuebin** [comment]
My story disappeared strangely again
