### ISSUE TITLE
2.0.0 text in the boxes on family book is cut off

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#2848]
Displaying a family-book with more than 2 generations: text in the boxes is cut off. - see screenshot.
When only 2 generations are displayed, the space between the boxes is too small.

<img width="537" alt="familybook" src="https://user-images.githubusercontent.com/16715040/70476491-1290ed00-1ad7-11ea-875e-c3962383ff34.png">

**Comment by fisharebest** [comment]
The male/female icons are larger than the text.  This prevents us from showing 4 lines of details.
