### ISSUE TITLE
2.0.0 occupation report  - gateway timout

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#2850]
The occupation timout in 2.0.0 brings up an gateway timeout. Running the same report with the same tree on the same server in 1.7.x tooks around 10-15 seconds.

```
Gateway Timeout
The gateway did not receive a timely response from the upstream server or application.
```

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
