### ISSUE TITLE
2.0.0 namesearch boxes shows same entry more than 1 time

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#2851]
In some cases the searchbox shows a name two times. This can be reproduced for some searches, but I don't know when.

Here a screenshot of the search:

<img width="892" alt="searchbox1" src="https://user-images.githubusercontent.com/16715040/70478300-09098400-1adb-11ea-9166-1610995a132f.png">

This person (Gabriele) only exists one times in the tree.

Here the entry in the search result:

<img width="750" alt="searchbox2" src="https://user-images.githubusercontent.com/16715040/70478317-1a529080-1adb-11ea-899a-8e7b3c8845a9.png">

**Comment by vytux-com** [comment]
Looks like she has 2 names, but I think a bug is showing name 1 both times

**Comment by HonkXL** [comment]
Yes - one name before and one after marriage. It would be ok to see both names, but not the same 2 times.
