### ISSUE TITLE
2.0.0 html source in search results

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#2852]
In some cases I see HTML source code inside of the search results.

<img width="793" alt="html-source-in-search-result" src="https://user-images.githubusercontent.com/16715040/70478635-cac09480-1adb-11ea-88b6-d70b5c7cea95.png">

The only special for this person is, that there came a unknown GEDCOM Tag "_RUFNAME" while importing this file from an third party application.

**Comment by fisharebest** [comment]
Can you post the GEDCOM for the `NAME` record of this individual?
