### ISSUE TITLE
Cannot login after logout - send password does not work either

### ISSUE THREAD

**Issue by johnds123** [fisharebest/webtrees#2854]
I just logged out of my webtrees 2.0 site and now I am not able to login again.
The reset password function does not send new password either.
I get no errors

**Comment by fisharebest** [comment]
Same as #2844 ?

Delete your browser cookies ?

**Comment by johnds123** [comment]
Yes, of course. I should have found it myself
A restart of the browser was also needed.

**Comment by fisharebest** [comment]
No problem.  Glad you got it sorted.
