### ISSUE TITLE
Why ModuleCustomInterface implemented modules prefixed with underscore?

### ISSUE THREAD

**Issue by UksusoFF** [fisharebest/webtrees#2855]
I found this code:
```
                    if ($module instanceof ModuleCustomInterface) {
                        $module_name = '_' . basename(dirname($filename)) . '_';
                        $module->setName($module_name);
                    } else {
                        return null;
                    }
```
https://github.com/fisharebest/webtrees/blob/master/app/Services/ModuleService.php#L593

And can't understand why? Why not just folder name? Without underscore. 

I'm trying update module from 1.7 version and now can't access to old preferences because it without underscores.

**Comment by vytux-com** [comment]
The module designer should have code to convert the old settings to new ones on upgrade if they are needed

**Comment by fisharebest** [comment]
> Why not just folder name? Without underscore.

The core modules do not use underscores.

So, the underscores prevent custom modules from conflicting with core modules.

> The module designer should have code to convert the old settings to new ones on upgrade if they are needed

If I had this feedback before the 2.0.0 release, I would have included it.

**Comment by vytux-com** [comment]
I think it was mentioned during one of our chats, but I understood that to be the job of the module creator

**Comment by UksusoFF** [comment]
I think module creator mustn't do anything in core tables bypassing public interfaces such as getPreference/setPreference.

**Comment by fisharebest** [comment]
> I think module creator mustn't do anything in core tables bypassing public interfaces such as getPreference/setPreference.

Agreed.

I can easily create a new migration script that does this automatically...
