### ISSUE TITLE
V2.1 Control panel - Link media objects to facts and events

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2859]
Following the fix to issue https://github.com/fisharebest/webtrees/issues/2845, the filter works but duplicates are appearing see attached (BTW the filter text was 'Eric' and I haven't shown the other duplicates - there are 4 people attached to this image and each appears more than once)
![demo](https://user-images.githubusercontent.com/104515/70526474-9253a180-1b41-11ea-9884-e1d00d91321b.jpg)

**Comment by fisharebest** [comment]
I can't reproduce this.

I linka  media object to three individuals - I see three rows with the media object - and a different individual in each one.

I tried creating multiple links, etc.

**Comment by ddrury** [comment]
Hm, I can't see any obvious problems. I'll send you my gedcom. BTW the gedcom is pretty much a 1.7 version and media still has the `1 _THUM  & 1 _PRIM` fields but deleting them made no difference (and v2.0 still provides the ability to edit them)

**Comment by fisharebest** [comment]
It's caused by the`_WT_SORT @xxx@` records.

These also need to be ignored in the list of facts in the right-hand column
