### ISSUE TITLE
2.0.0 Image zoom in

### ISSUE THREAD

**Issue by jpretired** [fisharebest/webtrees#2867]
Image zooming in in 2.0 uses only part of the frame.
Sample image taken at https://dev.webtrees.net/demo-stable/individual.php?pid=i1&ged=demo.
I believe that the 1.7 way is more suitable.

Image zoom in in 1.7:
![zoom-in-1 7](https://user-images.githubusercontent.com/350656/70637836-33248880-1c38-11ea-90f6-16480e8bbd3c.jpg)

The same image zoom in 2.0:
![zoom-in-2 0](https://user-images.githubusercontent.com/350656/70637909-4e8f9380-1c38-11ea-9f27-9184b79aa305.jpg)

**Comment by fisharebest** [comment]
There is already an open issue for this - #1384

There is also a possible solution - #2864
