### ISSUE TITLE
2.0 Send mail error

### ISSUE THREAD

**Issue by t-karcher** [fisharebest/webtrees#2868]
Mails were being sent without problems until 2.0.0.b4, but I just noticed that for some weeks now (possibly with the update to b5?) sending fails with the following error in the log:

<pre>MailService: failed loading cafile stream: `/usr/local/etc/pki/cacert.pem [pcntl] 
extension=pcntl.so [PDF] extension=php_pdflib.so [pspell] extension=pspell.so [shmop] 
extension=shmop.so [soap] extension=soap.so [sockets] extension=sockets.so [tidy] 
extension=tidy.so [xmlrpc] extension=xmlrpc.so [xsl] extension=xsl.so [wddx] extension=wddx.so [zip] 
extension=zip.so [zlib] extension=zlib.so [Zend] zend_extension=/usr/local/phpfarm/inst/php-
7.3.9/lib/php/extensions/no-debug-non-zts-20180731/ioncube.so zend_extension=/usr/local
/phpfarm/inst/php-7.3.9/lib/php/extensions/no-debug-non-zts-20180731/opcache.so'</pre>

I did not change any settings in webtrees, gmail or my webserver (mails were successfully being sent with SMTP via gmail). Not sure whether this is even caused by webtrees, but maybe someone can point me in the right direction how to fix it?

**Comment by fisharebest** [comment]
`/usr/local/etc/pki/cacert.pem` is a system file that contains trusted "root certificates", and are essential for making secure SSL connections.

This post seems to cover installations for windows, mac and linux...

https://stackoverflow.com/questions/55526568/failed-loading-cafile-stream-in-file-get-contents

**Comment by t-karcher** [comment]
Thanks for the quick feedback! Looks like this would need to be fixed by my hosting provider then. So my problem is not solved yet, but I'll close this issue anyway, because it's obviously not related to Webtrees.

**Comment by t-karcher** [comment]
In case anyone is reading this looking for a solution: My issue was caused by a bug in the Zend Engine for PHP 7.3. Switching back to PHP 7.2 solved the problem.
