### ISSUE TITLE
Registering new members / Registration email and link provided

### ISSUE THREAD

**Issue by allan-wtf** [fisharebest/webtrees#2870]
Greg
Further to the suggested bug report - on Registering new members 
I have completed a clean install of v.2.0 - and I am running it on a local webserver (not my public one). 
The request is made and appears in the pending category.
The registration email is sent to the new registrant
Pls see the attached email and link generated.

[Yourregistrationathttp_192.168.100.1928922_webtrees-2.txt](https://github.com/fisharebest/webtrees/files/3952977/Yourregistrationathttp_192.168.100.1928922_webtrees-2.txt)

**Comment by fisharebest** [comment]
This was fixed a few hours ago in 256b18b914992685964d90e10ae11a8693496234
