### ISSUE TITLE
CSS compilation problem

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2871]
As mentioned in Pull request https://github.com/fisharebest/webtrees/pull/2864.

When compiling css as part of command `npm run production`, any css files that are merged into the file `public/css/vendor.css` are not parsed by the script `postcss_image_inliner` as it's configuration option `assetPaths `is set to "resources/css"

**Comment by ddrury** [comment]
A "solution" to this is to add the node module path to `postcss_image_inliner`
```
const postcss_image_inliner = require("postcss-image-inliner")({
    assetPaths: ["resources/css", "node_modules/lightGallery/dist/css"],
    maxFileSize: 0,
});
```
I was worried that this would alter the css in the node module itself but it doesn't, however `vendor.min.css` grows alarmingly (just for lightgallery which only has 5 images, the size grows from 365k to 437k) and if we went this way should all the other node module paths be added too?

**Comment by ddrury** [comment]
Actually, I've just had a look through all the other modules and there is nothing else that needs including

**Comment by ddrury** [comment]
I thought a better way to go would be to directly compile the lightgallery scss files so I included the following line in webpack.mix.js `mix.sass('resources/sass/lightgallery.scss', 'resources/css');` (I created the lightgallery.scss file just including the relevant scss files from lightgallery) but when I run `npm run production` I get this error
 error  in ./resources/sass/lightgallery.scss
```
Syntax Error: ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError
(7:4) Unknown word
  5 | $lg-theme: #0D0A0A !default;
  6 |
> 7 | // basic icon colours
    |    ^
  8 | $lg-icon-bg: rgba(0, 0, 0, 0.45) !default;
  9 | $lg-icon-color: #999 !default;
```
It seems that postcss-loader is getting hold of the file somehow and treating it as native css, but at this point I'm stumped - any suggestions?

**Comment by fisharebest** [comment]
...I have a week off at christmas.  I'll take a look then.

**Comment by ddrury** [comment]
Don't you like Christmas then? 😀 
Have a good one

**Comment by ddrury** [comment]
WARNING - long rambling post

Sorted it - mostly

If I'd looked very closely at the error message above it'd given me a steer! The Sass group are proposing to remove `@import` from the language in the future as it is confused with the css equivalent, however, whilst they haven't formally deprecated it they are strongly recommending the use of `@use` as a replacement. node-sass (which I was using for documentation) accepts this, however mix.sass uses the Dart implementation which doesn't (I've since found with a parameter change you can use the node-sass implementation but I've not tried it) BUT although `@use url(..) `and `@import url(...) `are not interpreted correctly they are passed though unchanged to the compiled css file and when mix styles grabs it, it sees "valid" css but baulks when it sees double slash comments and fails hence the error message above. Using plain `@import "path/to/file"` works and compilation works.

Another thing that got me was all the paths have to be relative to /public (although I suspect more accurately to whatever is set in mix.setPublicPath), weirdly when I set path to "resources/css" the file actually ended up in "public/resources/css" but when I set it to "public/css" that wasn't changed! so its necessary to set the output path to "../resources/css".

There are two things I've not cracked yet:

- It seems that sometimes I have to run "npm run production" twice, I suspect on the first run the wt-lightgallery css file doesn't exist and is picked up on the second run
- The image (only one now) isn't being inlined (but I wonder if it really matters)

I have a feeling that these are both dependent on the sequencing of the mix commands and I don't really know what that is.

And finally, I've created "resources/sass" for the scss files which then compile down to "resources/css/wt-lightgallery.css" are they the correct locations for the files?

I'll incorporate these changes in the pull request so you can see what I've done so far and I suspect we can close this issue

**Comment by ddrury** [comment]
I think I've fixed the need to run` npm run production ` twice by shifting the position of the sass line in webpack.mix.js

**Comment by ddrury** [comment]
BTW Wouldn't it make more sense to put vendor.js in resources and then minify it to public and/or set the postcss_image_inliner path to public therefore leaving the css in resources untouched but all the stuff in public is compressed and has all it's images inlined (I've tried it and it works)
