### ISSUE TITLE
2.0.0-Redirection problem

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2872]
[https://dev.webtrees.net/demo-dev/index.php?route=individual&xref=I1&ged=demo](https://dev.webtrees.net/demo-dev/index.php?route=individual&xref=I1&ged=demo)
Unable to redirect to
[https://dev.webtrees.net/demo-dev/tree/demo/individual/i1/Queen%20Elizabeth%20II](https://dev.webtrees.net/demo-dev/tree/demo/individual/i1/Queen%20Elizabeth%20II)

**Comment by fisharebest** [comment]
> https://dev.webtrees.net/demo-dev/index.php?route=individual&xref=I1&ged=demo

This is not a valid URL.

Where do you see it?

**Comment by xmlf** [comment]
when rewrite_urls is not used.The URLs is this.

**Comment by fisharebest** [comment]
The URL `index.php?route=individual&xref=I1&ged=demo` was not created by an official webtrees release (1.7 or 2.0).

It was created by development code (e.g. 2.0.0-alpha).

> Search engines have included many of these URLs for my site.

Invalid URLs are redirected (302) to the home page.

Instead, we could show a 404 page.

This would be better for search engines - but worse for humans?

**Comment by xmlf** [comment]
I have already used the nginx rewrite rule, thank you!
```
if ($query_string ~ "route=(.*)ged=wang$" ){
rewrite ^/index.php /tree/wang/$arg_route/$arg_xref? permanent;
}
```
