### ISSUE TITLE
Relationship chart options - 2.0.1

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2877]
I see in the form in

**demo-dev**
Find the closest relationships
Find all possible relationships

**my test system
F**ind the closest relationships
Find other relationships

**my future test system**
Find the closest relationships

What causes the different options and texts? I do not remember how I have decided what to show.

**Comment by fisharebest** [comment]
In the module preferences, there is an option "how much recursion to use".

1 => find the closest paths only
small number => find other paths
unlimited => find all paths

On trees with many loops, there can easily be thousands of paths, and it is not practical to find them all.

So you would choose a value depending on the size/complexity of your tree.

**Comment by melizaa** [comment]
I do not see a preference option for the Relationships in 2.0.1.
I see it in pre 2.0.0.
