### ISSUE TITLE
RTL chart horizontal arrows are in the wrong direction in minimal & F.A.B. themes - demo-dev2.0.1

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2878]
I see the issue in the compact tree, hourglass, pedigree and relationships 
Also the block charts have the issue.

![image](https://user-images.githubusercontent.com/5202996/70826275-2c8c4180-1def-11ea-8560-346d2efd86f2.png)

see #2222

**Comment by fisharebest** [comment]
This broke in b60877d9de903a8f4c698c6a4ab3b88a86ebf4b5
