### ISSUE TITLE
The RTL slideshow icons should be mirror images to the LTR icons - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2879]
The icon arrow triangles point to the same direction as on the LTR pages. 

Hebrew page
![image](https://user-images.githubusercontent.com/5202996/70827094-3020c800-1df1-11ea-8571-6bbebbcb65a8.png)

English page
![image](https://user-images.githubusercontent.com/5202996/70827179-5d6d7600-1df1-11ea-9850-0d058971b6d7.png)

see #2225

**Comment by fisharebest** [comment]
This is correct?

Media icons are not supposed to be reversed on RTL pages.

**Comment by ungeahnt** [comment]
Hi, in the link below Google explains its own point of view (material design):
https://material.io/design/usability/bidirectionality.html#mirroring-elements

See "Passage the time" -> first caption
> Since media playback buttons and the progress indicator reflect the direction of the **tape**, they are not mirrored. 

TAPE! ... pretty funny people on Google. Would like to know when they last listened to a piece of music from a tape! ;)

**Comment by vytux-com** [comment]
Yes, but tape was also the last medium to have a 'direction' of play.... So those icons make sense for current digital area it would have to be a 0 and 1 arrange somehow?

Having said that media files are read from start to end and not in reverse even if the song (or whatever) is in Hebrew

**Comment by ungeahnt** [comment]
Good morning, not turning the icon seems to be the standard (that's why I referred to the link).

I was only amused by the 'ancient' example. Intuitively I would have also rotated the button for RTL, since I interpret an audio file (meanwhile) rather in the temporal context. But I would have been wrong.

**Comment by melizaa** [comment]
Yes, sorry. I was wrong.
