### ISSUE TITLE
2.0.0-How to fetch real IP using proxy pass

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2882]

**Comment by fisharebest** [comment]
You must put the IP address of your proxy and the name of the header in data/config.ini.php.

https://github.com/fisharebest/webtrees/blob/master/app/Http/Middleware/ClientIp.php#L41-L45

**Comment by xmlf** [comment]
Can you provide an example? It didn't take effect after I configured.

**Comment by fisharebest** [comment]
`trusted_headers="X-Forwarded-For,X_REAL_IP"`

**Comment by xmlf** [comment]
> `trusted_headers="X-Forwarded-For,X_REAL_IP"`

I have already set this up, but IP is still 127.0.0.1

**Comment by xmlf** [comment]
I have found the problem：
https://github.com/fisharebest/webtrees/blob/4874f72da8279544d9c0a459e2920a9986acfaa0/vendor/middlewares/client-ip/src/ClientIp.php#L240
`FILTER_FLAG_NO_RES_RANGE` was not included, so 127.0.0.1 was returned.
This is bug.

`trusted_proxies="127.0.0.1" `must be set in config.ini.php at the same time.

**Comment by fisharebest** [comment]
`127.0.0.1` is valid.

```
php > var_dump(filter_var('127.0.0.1', FILTER_VALIDATE_IP, FILTER_FLAG_IPV4 | FILTER_FLAG_IPV6) !== false);
bool(true)
```

`FILTER_FLAG_NO_RES_RANGE` would mean that you could not use `127.0.0.1` as a proxy.

**Comment by xmlf** [comment]
https://github.com/fisharebest/webtrees/blob/4874f72da8279544d9c0a459e2920a9986acfaa0/vendor/middlewares/client-ip/src/ClientIp.php#L229
127.0.0.1 is valid, so it eventually returned client-ip is 127.0.0.1

**Comment by fisharebest** [comment]
This works for me.

For testing, I add this to index.php

```
$request = $request->withHeader('X-Forwarded-For', '49.11.11.10,127.0.0.1');
```

In config.ini.php, I add

```
trusted_proxies="127.0.0.1"
trusted_headers="X-Forwarded-For"
```

Now, I see `49.11.11.10` in the webtrees logs.

**Comment by xmlf** [comment]
Yes! 

> trusted_proxies="127.0.0.1" must be set in config.ini.php at the same time.

If not set, the IP is 127.0.0.1
