### ISSUE TITLE
Ability to translate the names

### ISSUE THREAD

**Issue by mrqd9** [fisharebest/webtrees#2885]
Please make it possible to translate all name field inputs.
Example: When we switch the language, Givens, Surnames, Nicknames etc. Should be translated or transcripted for that language if the translation data exits somewhere for that name (e.g. "John";"जॉन" , "DOE";"डो". for Hindi). 

It's needed in the regions that having multiple primary languages

**Comment by fisharebest** [comment]
Normally, you would enter two versions of the name. One in latin text and one in hindi text.

webtrees will select the name that matches the current langauge.

Suppose you have an individual with these two names.

```
1 NAME जॉन /डो/
1 NAME John /DOE/
```

If you visit the site using Hindi, then then name "जॉन डो" will be used.
If you visit the site using a latin language, then the name "John DOE" will be used.

If you visit the site using a language with another script (Cyrillic, Hebrew, Greek, etc.), then the first name will be used.

Here is a site which uses this - https://www.amitys.com/webtrees/individual.php?pid=I1&ged=Gedcom.ged

Change from English to Hebrew, and you will see the name change.

**Comment by mrqd9** [comment]
It need to add names for each individual separately,
Now "Surname list" showing two different versions of the nam,
It will be better if all "John" replaced with "जॉन" by translating a single word, except the adding multiple names to the gedcom file

**Comment by mrqd9** [comment]
Is there any option to translate non `I18N` text?

**Comment by fisharebest** [comment]
> Is there any option to translate non I18N text?

1) No.  We do not do this sort of thing anywhere in webtrees.

2) The translation functions are always *from* English *to* other langauges.  So it is not possible to use them to translate from Hindi to English.

I don't think your request is possible.  Sorry.

**Comment by mrqd9** [comment]
Is it possible to translate roman names to another language/script?

**Comment by fisharebest** [comment]
I do not think so.

Names are stored in the database, and are used for searching/sorting/etc.

If you do not have the NAME records, then you cannot search them, list them, etc.

It may be possible to modify the "display a name" function, but too many things will not work.

Again, I don't think your request is possible. Sorry.

**Comment by mrqd9** [comment]
I understood that.. Thanks
