### ISSUE TITLE
package.json - change

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2889]
I think the following entry `"beautifymarker": "^1.0.7"`, needs to be changed to `"leaflet.beautifymarker": "^1.1.1", `

... and of course vendor.js

**Comment by fisharebest** [comment]
Hmmm....

npmjs.com shows two packages - [beautifymarker](https://www.npmjs.com/package/beautifymarker) and [leaflet.beautifymarker](https://www.npmjs.com/package/leaflet.beautifymarker).

The [github repo)(https://github.com/marslan390/BeautifyMarker) contains `1.0.7` in its package.json, and says:

> Current version of L.BeautyMarker is 1.0

I looked through the revision history of package.json, and it has never inlcuded a version higher than 1.0.x

The package `leaflet.beautifymarker` was updated 3 years ago, whereas `beautifymarker` was updated 1 year ago.

`beautifymarker` is released under the MIT licence, so we are OK to include it.
`leaflet.beautifymarker` is released under the MAS licence, which I've never heard of (and nor has google).

I'm not convinced that the package `leaflet.beautifymarker` is legitimate...

**Comment by fisharebest** [comment]
I've just run a diff on the two packages.

The one we're using looks like it has newer code.

**Comment by ddrury** [comment]
I've just looked at the package.json on his github site - it says version 1.0.7 at the top and 1.1.1 near the bottom!!

**Comment by fisharebest** [comment]
Maybe open an issue on his site and ask him to clean it up?
