### ISSUE TITLE
ModuleCustomInterface not allowed on admin layout?

### ISSUE THREAD

**Issue by UksusoFF** [fisharebest/webtrees#2890]
According to [this](https://github.com/fisharebest/webtrees/blob/master/resources/views/layouts/administration.phtml#L90) code:
```php
        <?= app(ModuleService::class)->findByInterface(ModuleGlobalInterface::class)->map(static function (ModuleGlobalInterface $module): string {
    return $module instanceof ModuleCustomInterface || $module instanceof CustomCssJsModule ? '' : $module->bodyContent();
        })->implode('') ?>
```
Is this right behaviour? Any solution for extend admin layout and add some content?

**Comment by fisharebest** [comment]
This was intentional.  I did not want modules to allow modules to break the admin page.

What sort of content do you want to add?

**Comment by UksusoFF** [comment]
Okay. Understand.
I want create settings page for my module and attach some javascript/styles on page. 
Seems I must connect it directly in view().

**Comment by fisharebest** [comment]
> I want create settings page for my module and attach some javascript/styles on page.

The admin pages **can** contain javascript.

See this page for an example:

https://github.com/fisharebest/webtrees/blob/master/resources/views/admin/media.phtml

**Comment by UksusoFF** [comment]
Yep. Already done it via push. Just confused - ModuleGlobalInterface expected as really global.

**Comment by fisharebest** [comment]
> ModuleGlobalInterface expected as really global.

OK - I understand.  But this is just for genealogy pages.

Perhaps I should have used a better name!
