### ISSUE TITLE
github - CSS and JS module fails with Pretty URL's

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2892]
I have the following entry for my CSS and JS module.  It works on normal URLs  has no effect on Pretty URLs.  By this I mean the  link is in the code but the contents of common.css have no effect.

![image](https://user-images.githubusercontent.com/5147603/71000508-ac890480-2098-11ea-9d34-020ff9e5be2c.png)

**Comment by fisharebest** [comment]
We don't use relative URLs anywhere in webtrees (absolute URLs only) for exactly this reason.

I tried adding a `<base>` element to the `<head>`, but IIRC this breaks in-page links (e.g. `<a href="#xxx">`), which now point to a different page.

The only answer I can think of is for you to use an absolute URL.

**Comment by makitso** [comment]
With normal URLs, the link address is https://skatekey.net/public/css/common.css
With pretty URLs, the link address is https://skatekey.net/tree/public/css/common.css

**Comment by makitso** [comment]
> The only answer I can think of is for you to use an absolute URL.

Not that I am aware of.

**Comment by makitso** [comment]
If I change
Old
<link rel="stylesheet" href="public/css/common.css">
New
<link rel="stylesheet" href="https://skatekey.net/public/css/common.css">

**Comment by makitso** [comment]
OK, I misunderstood your comment about relative and absolute.  I changed the link to absolute and it fixed the problem.
