### ISSUE TITLE
My story disappeared strangely again

### ISSUE THREAD

**Issue by kexuebin** [fisharebest/webtrees#2894]
My story disappeared strangely again, and it disappeared five times in memory. I don't know why, The server is not set (the server is set to release memory at 1 o'clock every day), and the control panel was never set. wt2.0,centos6.5, php7.3, nginx1.8.1, mysql5.5.57. Greg, ask for help and analyze why.

**Comment by t-karcher** [comment]
For everyone not following the previous discussions: This is basically a follow up of #2841 

My stories were mysteriously gone as well a couple of weeks ago, but I was never able to reproduce this problem: When I last saw them, I was running WT2.0.0.b5 with PHP7.1. A while later, they were gone and I had to recreate them from a backup.

**Comment by kexuebin** [comment]
> For everyone not following the previous discussions: This is basically a follow up of #2841
> 
> My stories were mysteriously gone as well a couple of weeks ago, but I was never able to reproduce this problem: When I last saw them, I was running WT2.0.0.b5 with PHP7.1. A while later, they were gone and I had to recreate them from a backup.

I was very depressed. I lost the hard-written story five times. Haha, I couldn't find any cause, it was weird and suddenly, it disappeared somehow.

**Comment by fisharebest** [comment]
Do you have full control over your MySQL database?

Can you enable "binary logging" (a log of all SQL update/insert/delete statements)?

When it happens again, we will know the SQL statement that deleted the data.
We will also know the date/time it happened.
We can use the date/time to find the apache/nginx request that caused it.
