### ISSUE TITLE
Haha, Columbus discovered the New （BUG）.

### ISSUE THREAD

**Issue by kexuebin** [fisharebest/webtrees#2895]
There were five times when the story was lost strangely. After searching for a long time, no reason was found, and somehow it was gone. After testing for a long time today, I finally found the source of the problem: Originally click on the family tree homepage, customize this page, add or delete HTML, and the story will somehow be cleared (deleted).

**Comment by fisharebest** [comment]
Thanks!

The problem is now obvious!
