### ISSUE TITLE
A question related to lightgallery optimisation

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2896]
Lightgallery has a rotating gear wheel image "loading.gif". webtrees has the same thing called "loading-32x32.gif" which is a tad smaller. I can't change the name of the lightgallery image but I could the webtrees one, it would save a little bit of duplication and I could lose a line in webpack.min.js.

Also font "DejaVuSans.ttf" is copied to resources/fonts and is referenced by the fanchart module, currently I'm putting lightgallery's fonts in public/fonts should I relocate them?

What do you think

**Comment by fisharebest** [comment]
Apart from 20 seconds looking at the demo on their website, I haven't had any time to look at lightgallery.

Whatever we do, I'd like to make this as "modular" as possible, to make it easy/possible to switch different providers.
