### ISSUE TITLE
github - Contact me email does not include senders email address

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2899]
![image](https://user-images.githubusercontent.com/5147603/71265437-78fde280-2303-11ea-9bcf-61e6c80da040.png)

**Comment by fisharebest** [comment]
There are two different contact forms.

* Visitors - this should include the email address
* Registered users - this should not

The reasoning was that it allowed registered to communicate via webtrees without having to disclose their email addresses.

**Comment by makitso** [comment]
This is a visitor

**Comment by fisharebest** [comment]
Ok - I saw "test user" in the screenshot, and jumped to conclusions.

**Comment by fisharebest** [comment]
The sender's email address is set in the "Reply-to" header, so you'll see it if you reply to the email.

But we should probably show it in the body as well.
