### ISSUE TITLE
New user registration issues

### ISSUE THREAD

**Issue by kexuebin** [fisharebest/webtrees#2900]
New user registration, click on the email verification address to jump to the homepage of the website, the email address is:is:https://www.website.com/verify/yaoxingling//ke

With beautiful URLs enabled, NGINX rules are as follows:
    # Static files have versions in their URLs, and can be cached indefinitely.
location /public {
    expires 365d;
    access_log off;
}

# GIT config files can contain credentials or other sensitive data.
location /.git {
    deny all;
}

# User data is stored here by default.
location /data {
    deny all;
}

# Nothing sensitive here, but there is no need to publish it.
location /app {
    deny all;
}
location /modules {
    deny all;
}
location /resources {
    deny all;
}
location /vendor {
    deny all;
}

# Rewrite all other requests onto the webtrees front-controller.
location / {
    rewrite ^ /index.php last;
}

# webtrees runs from this one script.
location = /index.php {
    include fastcgi.conf;
    fastcgi_pass unix:/tmp/php-cgi-73.sock;
}

**Comment by kexuebin** [comment]
Test closed beautiful URL, click verification email still invalid

**Comment by fisharebest** [comment]
This has already been fixed

https://github.com/fisharebest/webtrees/commit/256b18b914992685964d90e10ae11a8693496234
