### ISSUE TITLE
Deter SPAM registrations and messages

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#2901]
Some sites are having problems with spam user registrations and messages.

There may be some easy things we can do with CSS and JS to help...

**Comment by makitso** [comment]
Going to add this to Contact "Send message " ?  😃

**Comment by fisharebest** [comment]
It's on both the registration and the contact page.

**Comment by makitso** [comment]
I just tried it and see no captcha on Send message.  Do you turn it on somehow in the control panel?

**Comment by fisharebest** [comment]
It is totally invisible to the user.

If you want to see it, use the browser dev tools and look for the hidden fields and javascript at the top of the form.

If it proves to be ineffective, I can add something more intrusive.
