### ISSUE TITLE
2.0-$from->realName error in sending mail.

### ISSUE THREAD

**Issue by DaPoHou** [fisharebest/webtrees#2902]
https://github.com/fisharebest/webtrees/blob/d44668f6cee02a5ac8030fd9e0fe2e7fdf2217ce/app/Services/EmailService.php#L79
At present, I have many family trees.
According to the code, `$from->realName()` should be the name of the family tree.
But now they all become "webtrees."

```
    public function realName(): string
    {
        return $this->tree->title();
    }
```

**Comment by fisharebest** [comment]
There are many types of email.

Which one?

**Comment by xmlf** [comment]
All type email.
Contact message,register notice,etc .

**Comment by ekremparlak** [comment]
With version 2.0.1 register notice and register confirm notice;
```
From: webtrees <mail@mydomain.com>
Reply-To: webtrees <no-reply@localhost>
To: Ekrem Parlak <ekremparlak@mydomain.com>
```
With version 1.7 register notice;
```
From: Family Tree Name <mail@mydomain.com>
Reply-To: Registered User Name <example@hotmail.com>
To: Ekrem Parlak <ekremparlak@mydomain.com>

```
register confirm notice;
```
From:  Family Tree Name <mail@mydomain.com>
Reply-To: "webtrees-noreply@mydomain.com"
 <webtrees-noreply@mydomain.com>
To: Ekrem Parlak <ekremparlak@mydomain.com>
```

**Comment by fisharebest** [comment]
In 2.1, it is possible to set the reply-to name in the control panel.
