### ISSUE TITLE
session_set_cookie_params() expects parameter 3 to be string, null given

### ISSUE THREAD

**Issue by RAlfoeldi** [fisharebest/webtrees#2903]
As requested I am attaching the stacktrace. 

I saw Issue #2617 but don't have the impression this is the same thing.

Error occurred after setting admin account on a new installation.

Setup wizard for webtrees

An unexpected database error occurred.

session_set_cookie_params() expects parameter 3 to be string, null given
#0 /mnt/disks/mort-1/var/www/webtrees/app/Session.php(68): session_set_cookie_params(0, '/', NULL, false, true)
#1 /mnt/disks/mort-1/var/www/webtrees/app/Http/Controllers/SetupController.php(414): Fisharebest\Webtrees\Session::start(Object(Nyholm\Psr7\ServerRequest))
#2 /mnt/disks/mort-1/var/www/webtrees/app/Http/Controllers/SetupController.php(343): Fisharebest\Webtrees\Http\Controllers\SetupController->createConfigFile(Array)
#3 /mnt/disks/mort-1/var/www/webtrees/app/Http/Controllers/SetupController.php(175): Fisharebest\Webtrees\Http\Controllers\SetupController->step6Install(Array)
#4 /mnt/disks/mort-1/var/www/webtrees/app/Http/Middleware/ReadConfigIni.php(69): Fisharebest\Webtrees\Http\Controllers\SetupController->setup(Object(Nyholm\Psr7\ServerRequest))
#5 /mnt/disks/mort-1/var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#6 /mnt/disks/mort-1/var/www/webtrees/app/Http/Middleware/EmitResponse.php(56): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#7 /mnt/disks/mort-1/var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#8 /mnt/disks/mort-1/var/www/webtrees/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#9 /mnt/disks/mort-1/var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#10 /mnt/disks/mort-1/var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#11 /mnt/disks/mort-1/var/www/webtrees/index.php(55): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#12 {main}
The webtrees developers would be very interested to learn about this error. If you contact them, they will help you resolve the problem.

**Comment by fisharebest** [comment]
> session_set_cookie_params() expects parameter 3 to be string, null given

Parameter 3 is the domain name.

This is copied from the URL in your browser.

1) what URL do you see in your browser during the setup wizard?  A valid domain? A local/test domain?  An IP address?  A "file:" URL?  Something else?

2) if the file `data/config.ini.php` exists, what does it contain for `base_url`?

**Comment by RAlfoeldi** [comment]
Thanks for the quick response.

webtrees is behind an nginx reverse proxy with an url of https://stammbaum.xxx.ch.

nginx config (reduced version of my wordpress configs.)

	server {
		listen 443 ssl http2;
		server_name stammbaum.xxx.ch;	

		client_max_body_size 20M;

		include ssl.conf;

        	ssl_certificate /etc/letsencrypt/live/stammbaum.xxx.ch/fullchain.pem; # managed by Certbot
        	ssl_certificate_key /etc/letsencrypt/live/stammbaum.xxx.ch/privkey.pem; # managed by Certbot

		include csp-header-webtrees.conf;	
		include security-headers.conf;

		root /var/www/webtrees;

		location = /robots.txt {
			try_files /robots-no-se.txt =404;
		}

        	index index.php index.html index.htm;

        	location = /favicon.ico {
			log_not_found off;
			access_log off;
		}

		# Deny public access to wp-config.php
			location /data {
				deny all;
			}

		location = /index.php {
			include fastcgi.conf;
			include fastcgi_cache.conf;
		}
	}

PHP Serverinfo indicates, that the relevant environment vars are set correctly:

	$_SERVER['HTTP_HOST'] | stammbaum.xxx.ch
	...
	$_SERVER['SERVER_NAME'] | stammbaum.xxx.ch

config.ini.php:
	base_url=""

Everything works fine - now. But the setup dialog was stuck in a loop. After the final step I got the NPE, deleting config.ini.php got me back to the start of the setup dialog, do the setup dialog, get the NPE, repeat.

**Comment by fisharebest** [comment]
> config.ini.php:
> base_url=""

This is the problem.  `base_url` should contain the URL of your site (no trailing slash).

During setup, we copy this from the URL bar in your browser, and look for everything to the left of `/index.php`.

My guess is that you already had URL rewriting enabled for the path used by webtrees, and that the URL didn't contain `index.php`.

**Comment by RAlfoeldi** [comment]
Yeah... But if I leave base_url empty, I can use the same config for more than one url, e.g. stammbaum.familyone.ch and stammbaum.familytwo.ch. (tried it, works). The problem only came up during setup and I got around it by explicitly calling index.php (url rewriting was active yet). Closing issue as it works for me. Just thought you would want to know about NPEs.
