### ISSUE TITLE
Invalid code in input string …/app/Module/FanChartModule.php (2.0.0)

### ISSUE THREAD

**Issue by t-karcher** [fisharebest/webtrees#2906]
The fan chart module isn't working in 2.0.0:

https://familie-dohl.de/index.php?route=%2Ftree%2Ftest%2Ffan-chart-3-4-100%2FX1

<pre>
imagettftext(): any2eucjp(): invalid code in input string …/app/Module/FanChartModule.php:397
#0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(2, 'imagettftext():...', '/data/web/1/000...', 397, Array)
#1 …/app/Module/FanChartModule.php(397): imagettftext(Resource id #454, 7, 16.875, 155, 69, 1, '/data/web/1/000...', '            Uro...')
#2 …/app/Module/FanChartModule.php(225): Fisharebest\Webtrees\Module\FanChartModule->chart(Object(Fisharebest\Webtrees\Individual), '3', 100, 4)
#3 …/app/Http/Middleware/WrapHandler.php(66): Fisharebest\Webtrees\Module\FanChartModule->handle(Object(Nyholm\Psr7\ServerRequest))
#4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#5 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#6 …/app/Http/Middleware/Router.php(121): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
...
</pre>

**Comment by fisharebest** [comment]
Your server is configured with a "japanese font override", meaning that functions which are documented to accept UTF8 characters now expect a japanese encoding instead.

We already have a fix: acd78f726d6605c5b80bd6bfddc79eb43d197413
