### ISSUE TITLE
Uncaught TypeError: Cannot read property 'checked' of null

### ISSUE THREAD

**Issue by UksusoFF** [fisharebest/webtrees#2907]
This error show on console on media pages eg: https://dev.webtrees.net/demo-dev/tree/demo/media/m23/Portrait%20of%20Queen%20Elizabeth%20The%20Queen%20Mother%2C%20by%20Richard%20Stone%2C%201986

**Comment by fisharebest** [comment]
This error is in the bootstrap library - the "toggle buttons" at the bottom of the individual/family lists.

I'm pretty sure I'm using it correctly...

**Comment by UksusoFF** [comment]
Seems error was fixed
