### ISSUE TITLE
2.0.0 - upgrade is not working when large trees exists

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#2910]
I use webtrees 2.0.0 with 12 trees and a total of around 170.000 persons in them. Upgrades in 1.x versions was never a problem. Now I tried to upgrade from 2.0.0 to 2.0.1 by using the web-upgrader.

It tried to export the trees and then there came this error on the 3rd tree:

Gateway Timeout
The gateway did not receive a timely response from the upstream server or application.

This tree has around 55k persons and 22k families. Exporting in earlier versions was never a problem.
Execution limits in php were set to 180 seconds and I tried to change them to 240 withound any change.

**Comment by fisharebest** [comment]
In webtrees 1.x, all the upgrade steps were performed in a single request - meaning that they all needed to run within 30 / 60 / whatever seconds.

Now, each separate task runs in its own request, so it seems odd that it can't export one tree.

What happens if you try to export that tree via the control panel?  How long does it take?

**Comment by fisharebest** [comment]
> Gateway Timeout

Ah.

I guess that you have a proxy server with a lower timeout than your PHP execution time.

In other words, your scripts may continue to run (high PHP time limit), but your webserver would not wait for them (lower proxy time limit).

Previously, your upgrade would have run for (say) 5 minutes.  The proxy would have timed out after 1 minute - but the job would continue to run in the background.

Is this your server?  What is the proxy timeout?  60 seconds is a common default.

**Comment by HonkXL** [comment]
Yes, it's my server. Value was set to 30 seconds :-( I now set it to 600 seconds, but the same problem still exists. Doing a manual export of this tree tooks around 15 seconds.

**Comment by HonkXL** [comment]
BTW: Apache is configured to use PHP 7.3 with CGI Wrapper. Is this a problem for Webtrees? In 1.7 I had never any issue with this.

**Comment by fisharebest** [comment]
When you say "but the same problem still exists", do you mean the exact same error message - or do you simply mean that it still does not work?

After how many seconds (approximately) do you get the "gateway timeout" error?

**Comment by HonkXL** [comment]
I just stopped the time: The upgrade process starts end exports the first 2 trees in 3 seconds. Then after 1 minute 50 seconds it brings up the error message:

Gateway Timeout
The gateway did not receive a timely response from the upstream server or application.

**Comment by HonkXL** [comment]
I just changed Apache to use FPM. Here it exports 7 trees and then I get this error message:

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by HonkXL** [comment]
FCGId did not work, too. And I changed from PHP 7.3 to 7.2 -> same result, no change. And I was not able to get any PHP error message. The only errors I have seen sayed "time out".

**Comment by vytux-com** [comment]
I'm not certain about Apache but under nginx FPM version of PHP certainly runs under a 'gateway' and has a separate timeout setting.

**Comment by fisharebest** [comment]
The "export to server" process sorts the records "numerically". `I1`, `I2`, `I3`....

Removing this sort makes a significant different to the performance.

On my own site, (10000 individuals), the export time is reduced from 3.3 seconds to 0.3 seconds.
