### ISSUE TITLE
2.0.1-The records of the wife and husband are wrong.

### ISSUE THREAD

**Issue by DaPoHou** [fisharebest/webtrees#2911]
When a family has only one wife and no husband.
After I change the family members or add an existing person as his wife, the wife is ranked above the husband in the family page and cannot be changed.
XREF=15062 for wife
XREF=I8775 for husband

Then I edited the original GEDCOM records and found that the records of the husband and wife were wrong. The wife became the husband and the husband became the wife.
1 HUSB @I15062@
1 WIFE @I8775@

**Comment by fisharebest** [comment]
I cannot reproduce this.

> the wife is ranked above the husband in the family page and cannot be changed.

This sounds like you have a pending edit.  You will see the old and new data together, and you cannot edit the old data.

If you can still see the problem, and you can provide exact steps to reproduce it, then please create a new issue.
