### ISSUE TITLE
2.0.1- Control Panel Still Shows 2.0.0

### ISSUE THREAD

**Issue by dbq-andersons** [fisharebest/webtrees#2913]
After a successful upgrade to version 2.0.1, the control panel wants to do it again, saying I'm still on 2.0.0.  Line 96 of app/Webtrees.php still shows 2.0.0 out of the zip file.  

` 96     public const VERSION = '2.0.0' . (self::STABILITY === '' ? '' : '-') . s    elf::STABILITY;`

Once I updated it, the control panel shows the correct version.

 `96     public const VERSION = '2.0.1' . (self::STABILITY === '' ? '' : '-') . s    elf::STABILITY;`

Cheers,

Bill

**Comment by fisharebest** [comment]
Dang.  How did I miss that :-(

The only manual step in the release process is to edit the version number in that file...

**Comment by fisharebest** [comment]
I'll update the .ZIP file.
