### ISSUE TITLE
2.0.0 pedigree chart boxes are too small

### ISSUE THREAD

**Issue by mpaluchowski** [fisharebest/webtrees#2915]
As shown in the screenshot. The content gets clipped because it doesn't fit into the box. The 1.x version boxes were considerably larger. You can see an example [in my tree](https://genealogy.paluchowski.com/tree/paluchowski/pedigree-right-4/I0812).

![Screenshot from 2019-12-27 07-23-14](https://user-images.githubusercontent.com/727642/71504487-e5d02a00-2879-11ea-9ab4-0e5258a737f2.png)

**Comment by fisharebest** [comment]
The text is variable length.  Boxes can never be large enough to show **all** content at **all** times.

Also, taller boxes mean that fewer are displayed.  It's a compromise.

This is why we have the (+) icon in the top right.

Boxes are `5rem` tall be default.  You can change this in the control panel.  Enable the module "CSS and JS".  Add this to the `<head>` option.

```
<style>
.wt-chart-box { height: 8rem; }
</style>
```

**Comment by mpaluchowski** [comment]
I see where you're going. In that case, wouldn't it be better to show _less_ information by default and once the (+) is clicked, expand the box and show more? Ie. the default would be to show the photo, full name and years of birth and death. These should fit in most cases.

Right now there's a lot of information displayed and with the size you have chosen, it won't fit in 99% of cases.

**Comment by fisharebest** [comment]
>  it won't fit in 99% of cases.

On my own pedigree chart, I can see *all* the details for me, my parents, my grandparents and my great-grandparents.

> Ie. the default would be to show the photo, full name and years of birth and death.

You mean like the "Compact chart"?

You can switch to this layout using CSS.

e.g. something like this:

```
.wt-chart-pedigree .wt-chart-box-lifespan {
    display: block;
}
.wt-chart-pedigree .wt-chart-box-facts {
    display: none;
}
```

Alternatively, you can add

```
.wt-chart-box { font-size: 75%; }
```

**Comment by fisharebest** [comment]
Annother option is to show abbreviated place names in charts.  e.g. just "Krakow" instead of "Krakow, Krakow malopolski, Poland".

This is configured in the control panel

**Comment by otmarmayr** [comment]
With click on a photo, a huge window opens. How can I make the window smaller?

**Comment by fisharebest** [comment]
> a huge window opens

I guess you mean the 'colorbox image viewer".

The image size is set in CSS.

You can see the default settings and some documentation here:
https://github.com/fisharebest/webtrees/blob/master/resources/css/_colorbox.css

The colorbox library also has documentation - https://www.jacklmoore.com/colorbox

However, be aware that there are plans to replace colorbox with another library.
https://github.com/fisharebest/webtrees/pull/2864
