### ISSUE TITLE
2.0.1 - error in top surnames block

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#2919]
After upgrading to 2.0.1 I encounter the following error when entering the homepage:

Argument 1 passed to Fisharebest\Webtrees\I18N::number() must be of the type float, string given, called in …/app/Functions/FunctionsPrintLists.php on line 70 …/app/I18N.php:385
#0 …/app/Functions/FunctionsPrintLists.php(70): Fisharebest\Webtrees\I18N::number('39')
#1 …/app/Module/TopSurnamesModule.php(129): Fisharebest\Webtrees\Functions\FunctionsPrintLists::surnameTagCloud(Array, Object(Fisharebest\Webtrees\Module\IndividualListModule), true, Object(Fisharebest\Webtrees\Tree))
etc. etc.

When I disable the top surnames block the error disappears.

**Comment by fisharebest** [comment]
I can't reproduce this.

This is the "tag cloud" view of the top surnames block.

What version of PHP?

**Comment by JustCarmen** [comment]
Php 7.3.1

**Comment by fisharebest** [comment]
Can you add some debug for me?

In `TopSurnamesModule.php`, at line 117, add this;

```
            $all_surnames[$top_surname] = $variants;
            var_dump($variants);
        }
```

I see values such as this - surnames and integers.

```
array (size=2)
  'Williams' => int 231
  'Monte-Williams' => int 1
```

Do you see integers, or strings?

**Comment by JustCarmen** [comment]
Hi Greg,

This is really a strange problem. I thought I had checked it, but I can't reproduce this either in my localhost, same webtrees state, same php version.

So this problem only occurs online on the server of the hosting provider. I have setup webtrees2 in a subdomain of my main site.

Var_dump gives this result: array(2) { ["Knegt"]=> string(3) "338" ["de Knegt"]=> string(1) "3" }
Strings indeed, but the array should also contain more names.

Here you can view the error: [https://webtrees2.wijzijnfamilie.nl/tree/knegt](https://webtrees2.wijzijnfamilie.nl/tree/knegt)
I've removed the var_dump because I had to force an exit right after the statement to output anything.

But I just got a thought. Could it be a database problem? I see that the server uses an old phpmyadmin version  4.4.15.10. I was searching for the mysql version but I can't find this information. However, in the webtrees server information I've found a Mysqli version number 10.2.19, but no information about Mysql.

What are the minimum requirements for the Mysql database? Could this be the problem?

**Comment by fisharebest** [comment]
It seems to be caused by the database driver.  The `mysqlnd` driver returns columns with the correct type.  The `mysql` driver returns everything as strings.

However, other drivers (e.g. SQLite) always return everything as  a string.

It seems that for every query, we must manually cast numeric columns to int/float.
