### ISSUE TITLE
admin, media, create, glitch,

### ISSUE THREAD

**Issue by alvin101** [fisharebest/webtrees#292]
In Administration, Media files, Media Folders,  unused files clicked, Include subfolders clicked, and sub folder drop down set to a sub folder.

When you click Create, you get the popup but when in this sub folder state, the popup does not auto enter the (Folder name on server) in the box.  If you are not in a sub folder (folder drop down set to a sub folder) this does not happen, it will auto set.

A minor problem,

**Comment by bmhm** [comment]
This actually creates a glitch of more concern. If you select another folder (where the file is NOT located), you have an image object in your database with a broken filesystem link.
If you try to move the object to another folder, you will get a PHP error instead of a webtrees error.

**Comment by fisharebest** [comment]
This code no longer exists, and is being rewritten for 2.0.0
