### ISSUE TITLE
translate.webtrees.net-Unable to receive mail

### ISSUE THREAD

**Issue by DaPoHou** [fisharebest/webtrees#2921]
Unable to receive mail (reset password or register).

**Comment by fisharebest** [comment]
The translation server runs at my employer (a University).

Mail is sent by the University's mail-server.

I control the translation server.  I do not control the mail server.

Some users can recevie mail.  Some cannot.  I do not know why.

It may be several weeks before I can work on the translation server.

If you need a password reset, etc., then contact me direclty.

**Comment by xmlf** [comment]
I suggest that you can change the mail server, you can use many free mail servers. For example yandex.com, I am currently using it to send mail.
