### ISSUE TITLE
2.0.1-Date input problem

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2924]
Input `1965 1 14 `  can be changed to `14 JAN 1965` .There is no problem.

But, input `1965 2 12 `  cannot be changed to `12 FEB 1965`.

**Comment by wkitty42** [comment]
On 12/29/19 7:11 AM, xmlf wrote:
> Input |1965 1 23 | can be changed to |14 JAN 1965| .There is no problem.


i think you have a typo above... how does 23 become 14? ;)


> But, input |1965 2 12 | cannot be changed to |12 FEB 1965|.


could the date format conversions be based on your locale's date format? i don't 
recall...


-- 
  NOTE: No off-list assistance is given without prior approval.
        *Please keep mailing list traffic on the list unless*
        *a signed and pre-paid contract is in effect with us.*

**Comment by fisharebest** [comment]
> could the date format conversions be based on your locale's date format

It is - but it did not detect `%n`
