### ISSUE TITLE
1.7.x - open changes mail shows wrong tree

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#2928]
When a user makes changes to my second tree, I always receive a mail that there are open changes for moderation in my first tree (the URL in the mail is wrong).

I think it would be correct if the links refers to the affected tree.

**Comment by HonkXL** [comment]
correct: the first user edits one tree (say number 2). An other user logs in on tree number 5. Then the link in the pending changes mail refers to tree 5, but the changes are in tree 2.

**Comment by fisharebest** [comment]
I'm afraid that 1.7 is only getting fixes for security and data-integrity issues.

There aren't enough resources available to fix minor bugs.  Sorry.
