### ISSUE TITLE
2.0.1 Create New Source: No dropdown for Repository

### ISSUE THREAD

**Issue by sleebooth** [fisharebest/webtrees#2935]
Open Create a Source.
Dropdown menu for repository does not display.
Save new source.
Displays Source Reference (e.g. X67) instead of Source Name.
Trying to select a Source by typing in characters displays &lt;span dir="auto"&gt;Source Name&lt;/span&gt; for each suggested Source

**Comment by fisharebest** [comment]
I cannot reproduce this.

Both behaviours suggest that there is an earlier Javascript error that is preventing later scripts from running.

Do you see any errors messages in your browser's error console?

**Comment by sleebooth** [comment]
[Violation] 'setTimeout' handler took 54ms
DevTools failed to parse SourceMap: http://sleebooth.co.uk/public/js/vendor.min.js.map
vendor.min.js?v=2.0.1:2 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ vendor.min.js?v=2.0.1:2
ajax @ vendor.min.js?v=2.0.1:2
(anonymous) @ VM8394:9
[Violation] 'submit' handler took 786ms

**Comment by fisharebest** [comment]
Nothing relevant there.

Which browser?  Try another?

**Comment by sleebooth** [comment]
Error was with Google Chrome. - which did not allow me to enter anything in the Repository field.

Microsoft Edge allows a Repository to be chosen (but not every time - I get a blue band sometimes, as in Chrome, but can't repeat to order) but still returns the source ref rather than the source Title.

Console Log:
HTML1300: Navigation occurred.
Arthur%20FORD (1,1)

5HTML1423: Malformed start tag. Attributes should be separated by whitespace.
Arthur%20FORD (237,40)

HTML1300: Navigation occurred.
SOUR (1,1)

HTML1512: Unmatched end tag.
SOUR (280,45)

SCRIPT7016: SCRIPT7016: Use of XMLHttpRequest with the synchronous flag set to true is deprecated due to its impact on user-perceived site performance.

HTML1300: Navigation occurred.
I1466 (1,1)

0: Unable to get property 'SavePersonalAndPaymentData' of undefined or null reference
Autoformfill_ContentScript.js (1,20660)

**Comment by sleebooth** [comment]
Tried with Firefox. Same symptoms as Chrome. On Save of new Source, message is:
Source map error: Error: JSON.parse: unexpected character at line 2 column 1 of the JSON data
Resource URL: http://sleebooth.co.uk/public/js/vendor.min.js?v=2.0.1
Source Map URL: vendor.min.js.map

**Comment by sleebooth** [comment]
Just to clarify. I can add a Repository to a Source by editing a Source and adding a Repository Fact. The Repository dropdown works fine in that scenario.

**Comment by fisharebest** [comment]
Do you see the problem on the demo site, or just on your own?

Here's what I am doing:

* Log in to the demo-dev site, and visit https://dev.webtrees.net/demo-dev/tree/demo/individual/i1
* Switch to the sources tab
* Click "Add a source citation"
* Click the "+" to create a new source
* Click into the repository field
* Type "NA" - and select "National Archives"

**Comment by sleebooth** [comment]
You have correctly repeated my actions.
The problem is similar on the Demo site when using Chrome Browser Version 79.0.3945.88 (Official Build) (64-bit) or Firefox 71.0 (64-bit)
i.e. The Repository Dropdown is inaccessible with a Blue strip below the Repository field on select, BUT when I save the Source it correctly shows the Source Title not the Source reference, but with no Repository shown.

However, when I use Microsoft Edge build 18362 there is no error - I see the expected result

**Comment by fisharebest** [comment]
> The problem is similar on the Demo site when using Chrome Browser Version 79.0.3945.88 (Official Build) (64-bit) or Firefox 71.0 (64-bit)

I have Firefox 72 (my default browser) - which works fine.

I have Chromium 79 (which I use very infrequently) - which showed the problem once.  I refreshed the page, and cannot now reproduce it.

Does clearing your cache / refreshing the page make a difference for you?

**Comment by sleebooth** [comment]
No. I have tried both!

**Comment by Salokyn** [comment]
Same problem for me on Firefox 70.0.1.

I initiated my tree on Webtrees 2.0 from a GEDCOM file exported from Webtrees 1.7. I used a fresh database.

![image](https://user-images.githubusercontent.com/11018648/71887643-d46f0380-313e-11ea-9165-1702d6cb8ec8.png)

The dropdown box is empty wereas I have several repository in database.

Here are the messages from the console (in french sorry)

```
Erreur d’analyse de la valeur pour « -webkit-text-size-adjust ».  Déclaration abandonnée. vendor.min.css:6:829
Pseudo-classe ou pseudo-élément « focus-visible » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:1325
Pseudo-classe ou pseudo-élément « -ms-expand » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:33433
Pseudo-classe ou pseudo-élément « -ms-input-placeholder » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:33882
Pseudo-classe ou pseudo-élément « -ms-input-placeholder » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:33942
Pseudo-classe ou pseudo-élément « -ms-value » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:34207
Pseudo-classe ou pseudo-élément « -ms-value » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:34264
Pseudo-classe ou pseudo-élément « -ms-value » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:93264
Pseudo-classe ou pseudo-élément « -ms-value » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:93316
Pseudo-classe ou pseudo-élément « -ms-expand » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:93832
Pseudo-classe ou pseudo-élément « -ms-thumb » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:96258
Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:97103
Pseudo-classe ou pseudo-élément « -ms-thumb » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:98140
Pseudo-classe ou pseudo-élément « -ms-thumb » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:98420
Pseudo-classe ou pseudo-élément « -ms-thumb » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:98521
Pseudo-classe ou pseudo-élément « -ms-thumb » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:98657
Pseudo-classe ou pseudo-élément « -ms-thumb » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:98725
Pseudo-classe ou pseudo-élément « -ms-track » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:98782
Pseudo-classe ou pseudo-élément « -ms-track » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:98855
Pseudo-classe ou pseudo-élément « -ms-fill-lower » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:98974
Pseudo-classe ou pseudo-élément « -ms-fill-upper » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:99094
Pseudo-classe ou pseudo-élément « -ms-fill-upper » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:99152
Pseudo-classe ou pseudo-élément « -ms-thumb » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. vendor.min.css:6:99499
Propriété « orphans » inconnue.  Déclaration abandonnée. vendor.min.css:6:117685
Propriété « widows » inconnue.  Déclaration abandonnée. vendor.min.css:6:117694
Propriété « backdrop-filter » inconnue.  Déclaration abandonnée. vendor.min.css:6:142078
Propriété « orphans » inconnue.  Déclaration abandonnée. vendor.min.css:6:227164
Propriété « widows » inconnue.  Déclaration abandonnée. vendor.min.css:6:227173
Propriété « size » inconnue.  Déclaration abandonnée. vendor.min.css:6:227215
Erreur d’analyse de la valeur pour « image-rendering ».  Déclaration abandonnée. vendor.min.css:6:255431
Propriété « behavior » inconnue.  Déclaration abandonnée. vendor.min.css:6:256967
Propriété « zoom » inconnue.  Déclaration abandonnée. vendor.min.css:6:271116
Nom de fonctionnalité média attendue, mais « -ms-high-contrast » trouvé. fab.min.css:1:428
Nom de fonctionnalité média attendue, mais « -ms-high-contrast » trouvé. fab.min.css:1:455
XHRGEThttps://genealogie.xxxxxxxxx.fr/index.php?route=%2Ftree%2Fgif-fino%2Fcreate-source
[HTTP/2.0 200 OK 109ms]

Erreur d’analyse de la valeur pour « transform ».  Déclaration abandonnée. index.php:3:25
```

**Comment by Salokyn** [comment]
Well, on another computer (Ubuntu 18.04) it works on FF 71.0 ...

**Comment by eric215** [comment]
This fails for me also on my own site with ver 2.0.3 and Firefox 74.0.1;   The current-version demo site + beta site both work OK for me when I use editor/editor or moderator/moderator

![Console](https://user-images.githubusercontent.com/13973937/78949990-628abb00-7a9b-11ea-8834-4c26492cd73a.png)
![network](https://user-images.githubusercontent.com/13973937/78949995-6585ab80-7a9b-11ea-9103-20f4fb5f9891.png)

**Comment by fisharebest** [comment]
>This fails for me also on my own site with ver 2.0.3 and Firefox 74.0.1

@eric215 - can you give me access to your site so I can see the problem?

Perhaps create a new/test tree - with enough data to demonstrate the problem...

**Comment by ro-la** [comment]
The bug described in the first posts seems to be the same behavior as in this forum post: https://www.webtrees.net/index.php/en/forum/help-for-2-0/33915-link-media-to-an-individual-cannot-chose-an-indi

@fisharebest cann I send you user/password to my tree?

**Comment by fisharebest** [comment]
> @fisharebest cann I send you user/password to my tree?

Sure - greg@subaqua.co.uk

**Comment by ro-la** [comment]
Sent😉
-------- Pôvodná správa --------Od: Greg Roach <notifications@github.com> Dátum: 10. 4. 2020  12:27  (GMT+01:00) Komu: fisharebest/webtrees <webtrees@noreply.github.com> Kópia: ro-la <lacoros@gmail.com>, Comment <comment@noreply.github.com> Predmet: Re: [fisharebest/webtrees] 2.0.1 Create New Source: No dropdown for Repository & corrupt response (#2935) 

@fisharebest cann I send you user/password to my tree?

Sure - greg@subaqua.co.uk

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/fisharebest/webtrees/issues/2935#issuecomment-611975485",
"url": "https://github.com/fisharebest/webtrees/issues/2935#issuecomment-611975485",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by fisharebest** [comment]
On my sites, when I click the [+] button to open the "new source" window, the window appears immediately.

On your site, there is a delay of approximtely 1 second.
Do you see this delay when opening?

[delay.zip](https://github.com/fisharebest/webtrees/files/4461376/delay.zip)

I think this delay is causing the problem.  When the window opens, we activate the edit controls.  But they do not exists for one more second - so they are not activated.

I tried disabling all the custom modules - but this did not help.

Do you have any other modifications or customisations?

**Comment by ro-la** [comment]
Hm - I see this delay, and I dont see it on demo. 

My only modification is the hotfix for "Shared palce modul", I removed it. No change, the delay remains.

This instalation is quite out of box, no pretty URLs, no SSL. 
Is there something in "Server information"?

Ladislav

**Comment by fisharebest** [comment]
Can you try something for me.

In the file `resources/views/modals/ajax.phtml` can you change line 2.

From: `class="modal fade"`

To: class="modal"

Does this make a difference?

**Comment by eric215** [comment]
Greg - I set you up as administrator on my site, user name is   GRoach  site is behunt.net/ft/
I emailed a password to you separately

Gave you access to the tree since it seems to fail for any person.  I also notice a delay opening the source window on my site but not the demo, I will try your test above

**Comment by eric215** [comment]
Change had no impact

**Comment by ro-la** [comment]
No change

**Comment by fisharebest** [comment]
@eric215 - did you look at the two videos?  Do you also see the same delay?

**Comment by eric215** [comment]
yes --similar delay

**Comment by fisharebest** [comment]
Perhaps this is a timing issue.

I note that ro-la's server is very slow.  Simple responses (e.g. switching language) take over 1 second.

We load the modal contents using an HTTP request.

We activate the modal contents using a "modal loaded" event.

But perhaps the event is triggered before the content is loaded?

**Comment by fisharebest** [comment]
I think this is it.  If I add delays to my dev site, then I can reproduce the problem.
