### ISSUE TITLE
Redirection problem after login (2.0.1)

### ISSUE THREAD

**Issue by t-karcher** [fisharebest/webtrees#2939]
This one is bugging me for some weeks now, and my hope that this problem would be gone with 2.0.1 (which fixed different redirection problems) was unfortunately not fulfilled:

I have a rewrite rule in my .htaccess file to take the "webtrees" subfolder out of the URL, making it the default folder for my whole domain:

<pre>
RewriteEngine on

# redirect root to index.php
RewriteCond %{HTTP_HOST} ^(www.)?familie-dohl.de$
RewriteRule ^(/)?$ index.php

# redirect all requests to non-existing files and folders to the "webtrees" subfolder
RewriteCond %{HTTP_HOST} ^(www.)?familie-dohl.de$
RewriteCond %{REQUEST_URI} !^/webtrees/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /webtrees/$1 [L]
</pre>

This works like a charm for almost all parts of the site:
https://familie-dohl.de/index.php?route=%2Ftree%2Ftest%2Findividual%2FX1%2FKarl%2520MUSTERMANN

There's one problem, though: If you hover over the "Login" ("Anmelden") link on the top right corner, you'll notice that the URL parameter is showing <code>https://familie-dohl.de?route=...</code> (without the /index.php part), which is leading to a redirection error after the login. This only occurs when logging in from an individual or family page. Logging in from the homepage directly works as expected.

Why is "/index.php" left out in this case? Can this be fixed in the code, or do you have a clever idea how to rewrite my .htaccess rules to cope with that?

**Comment by fisharebest** [comment]
Do you have the correct `base_url` setting in `/data/config.ini.php`?

**Comment by t-karcher** [comment]
Oh - good point! I never touched this file after the initial installation, and there was no entry for base_url in there. I now added <code>base_url="https://familie-dohl.de"</code> and it works! Thanks!
