### ISSUE TITLE
Route will not be cleared

### ISSUE THREAD

**Issue by Gunnar-GO** [fisharebest/webtrees#2945]
If you follow the link after all open changes are permitted (in german the button is named "weiter")
the side will break with 

ERR_TOO_MANY_REDIRECTS

the generated weblink is: http://XXXXXXX.de/webtrees/?route=%2Fwebtrees%2Ftree%2Fstammbaum%2Fmy-page/index.php?route=%2Fwebtrees%2F%2F

Since route is doubled, i assume that is the faulty behavior?

There was also another links with this behavior, sadly i didn't wrote down, if i find some i will add this here.

**Comment by fisharebest** [comment]
In the file `/data/config.ini.php`, what do you have for `base_url`?

**Comment by Gunnar-GO** [comment]
interesting, theres no base_url defined, only the database information are stored.

i will add this and check

**Comment by Gunnar-GO** [comment]
there are some if parallel new changes will be open. errors like

`syntax error, unexpected '}', expecting end of file …/vendor/swiftmailer/swiftmailer/lib/classes/Swift/DependencyContainer.php:374
#0 [internal function]: Swift::autoload('Swift_Dependenc...')
#1 …/vendor/swiftmailer/swiftmailer/lib/dependency_maps/cache_deps.php(3): spl_autoload_call('Swift_Dependenc...')
#2 …/vendor/swiftmailer/swiftmailer/lib/swift_required.php(15): require('/data/web/1/000...')
#3 …/vendor/swiftmailer/swiftmailer/lib/classes/Swift.php(59): {closure}()
#4 [internal function]: Swift::autoload('Swift_Mime_Char...')
#5 …/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(16): spl_autoload_call('Swift_Mime_Char...')
#6 …/vendor/swiftmailer/swiftmailer/lib/classes/Swift.php(54): require('/data/web/1/000...')
#7 [internal function]: Swift::autoload('Swift_Mime_Simp...')
#8 …/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/MimePart.php(16): spl_autoload_call('Swift_Mime_Simp...')
#9 …/vendor/swiftmailer/swiftmailer/lib/classes/Swift.php(54): require('/data/web/1/000...')
#10 [internal function]: Swift::autoload('Swift_Mime_Mime...')
#11 …/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(16): spl_autoload_call('Swift_Mime_Mime...')
#12 …/vendor/swiftmailer/swiftmailer/lib/classes/Swift.php(54): require('/data/web/1/000...')
#13 [internal function]: Swift::autoload('Swift_Mime_Simp...')
#14 …/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Message.php(16): spl_autoload_call('Swift_Mime_Simp...')
#15 …/vendor/swiftmailer/swiftmailer/lib/classes/Swift.php(54): require('/data/web/1/000...')
#16 [internal function]: Swift::autoload('Swift_Message')
#17 …/app/Services/EmailService.php(76): spl_autoload_call('Swift_Message')
#18 …/app/Module/ReviewChangesModule.php(141): Fisharebest\Webtrees\Services\EmailService->send(Object(Fisharebest\Webtrees\SiteUser), Object(Fisharebest\Webtrees\User), Object(Fisharebest\Webtrees\TreeUser), 'Ausstehende \xC3\x84n...', '\r\nHallo Detlef ...', '<div dir="ltr" ...')
#19 …/resources/views/user-page-block.phtml(11): Fisharebest\Webtrees\Module\ReviewChangesModule->getBlock(Object(Fisharebest\Webtrees\Tree), 62, 'user')
#20 …/app/View.php(186): include('/data/web/1/000...')
#21 …/app/View.php(282): Fisharebest\Webtrees\View->render()
#22 …/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make('user-page-block', Array)
#23 …/resources/views/user-page.phtml(15): view('user-page-block', Array)
#24 …/app/View.php(186): include('/data/web/1/000...')
#25 …/app/View.php(282): Fisharebest\Webtrees\View->render()
#26 …/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make('user-page', Array)
#27 …/app/Http/ViewResponseTrait.php(51): view('user-page', Array)
#28 …/app/Http/RequestHandlers/UserPage.php(89): Fisharebest\Webtrees\Http\RequestHandlers\UserPage->viewResponse('user-page', Array)
#29 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\UserPage->handle(Object(Nyholm\Psr7\ServerRequest))
#30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#31 …/app/Http/Middleware/AuthMember.php(60): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthMember->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#33 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#35 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#36 …/app/Http/Middleware/Router.php(121): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#38 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#40 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#42 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#43 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#44 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction(Object(Closure), 3)
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#46 …/app/Http/Middleware/DoHousekeeping.php(80): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#48 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#50 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#52 …/app/Http/Middleware/UseLanguage.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#54 …/app/Http/Middleware/UseSession.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#56 …/app/Http/Middleware/UseFilesystem.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseFilesystem->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#58 …/app/Http/Middleware/UseCache.php(74): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#59 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#60 …/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#61 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#62 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#63 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#64 …/app/Http/Middleware/UseDatabase.php(90): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#65 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#66 …/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#67 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#68 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#69 …/app/Http/Middleware/HandleExceptions.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#70 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#71 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#72 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#73 …/app/Http/Middleware/ReadConfigIni.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#74 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#75 …/app/Http/Middleware/EmitResponse.php(56): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#76 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#77 …/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#78 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#79 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#80 …/index.php(55): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#81 {main}
`

but if directly used it works actually

**Comment by fisharebest** [comment]
Add a line to config.ini.php:

```
base_url="http://XXXXXXX.de/webtrees"
```

**Comment by fisharebest** [comment]
> syntax error, unexpected '}', expecting end of file …/vendor/swiftmailer/swiftmailer/lib/classes/Swift/DependencyContainer.php:374

Perhaps this file is corrupt?

Copy the files from webtrees-2.x.x.zip to your server again?

**Comment by fisharebest** [comment]
The original issue (redirects) is fixed.

If you still have the second problem, please open a separate issue for it.
