### ISSUE TITLE
search lists last editor

### ISSUE THREAD

**Issue by Gunnar-GO** [fisharebest/webtrees#2947]
The search bar has a nice feature: if only one entry exist with the search term the person will be opened.

most webtrees are edited by few, so search for one of these users will return all edits. it isn't helpfull in general, for check sure, but in general :S
 
Sadly it isn't editable, so all terms will searched. maybe an option would be nice?

**Comment by fisharebest** [comment]
I think this is the same issue as #2809

**Comment by fisharebest** [comment]
Fixed
