### ISSUE TITLE
Changed death behavior

### ISSUE THREAD

**Issue by Gunnar-GO** [fisharebest/webtrees#2949]
The old behavior was to assume, that persons over x years is death.

the new behavior is if not tag 1 DEAT Y is set person is living. Now on statistics i have living people with age of 500+ years. i can clear that with simple add death by person, even without a date.

I'm fine with, but it would be much more userfriendly if age of maybe 150+ the deathtag will be automaticly set by input? 

If i generate a new entry i set name and a birth date. if i don't have a death date i can't setting anything in the box to make clear person is death. So it would be a nice addition to set it automatically.

**Comment by fisharebest** [comment]
> If i generate a new entry i set name and a birth date. if i don't have a death date i can't setting anything in the box to make clear person is death

This option existed previously
There was a recent request to remove this.
We should add it back.
