### ISSUE TITLE
Last Changes on Main Page

### ISSUE THREAD

**Issue by Gunnar-GO** [fisharebest/webtrees#2954]
At main page (Family tree) the **last changes** can be shown. It is configureable for 1 between 90 days.

Actually it doesn't stopps. for me it shows several hundreds entries (632 to be exact). A limiter to break at 20, 50 would be nice.

**Comment by fisharebest** [comment]
Perhaps it would be better to show

* last N changes

instead of

* changes in the last N days

**Comment by Gunnar-GO** [comment]
Jepp, that's what i meant with limit. 

Maybe both or a mix is interesting, but "last N changes" will be the better way, least in my opinion.
