### ISSUE TITLE
"On this Day" Block does not seem to use User Timezone

### ISSUE THREAD

**Issue by GreggShimokura** [fisharebest/webtrees#2961]
When I was trying to get my father to use Webtrees, he was bothered by the fact that events shown in the "On this Day" block were 'wrong' because it was one day ahead. 

We are in UTC-8 (Vancouver, Canada) and we ere viewing Webtrees after 4PM local time (so it was one day later at UTC-0).

A trial to change the server TZ to UTC-8 using .user.ini did not have the desired effect and I don't think is a generic approach that would work for users in all TZ.

We also tried:
http://xxx.com/admin/admin-site-preferences
Server Setting is UTC-5
My pages/My account
User Account is UTC-8
-> Did not change anything.

Changing
http://xxx.com/admin/admin-site-preferences
to UTC-8
-> Did not change anything.

Our physical server is located and needs to run at UTC-5 for other services.

I guess that the code for the "On this Day" block could be a starting point to check that the User TZ is used to calculate/display events.

It is a cosmetic issue but avoids giving new users doubts about the integrity of the data .

Thank you

**Comment by fisharebest** [comment]
This was working previously, but the local-time conversion seems to have been missed in a recent update.
