### ISSUE TITLE
Page layout breaking @Mobile view

### ISSUE THREAD

**Issue by mrqd9** [fisharebest/webtrees#2965]
Secondary-menu is breaking page layout @ mobile screen. 

![Screenshot_20200111-193839_Chrome](https://user-images.githubusercontent.com/56225476/72205620-49c63580-34ab-11ea-93e4-0c5e970afe62.jpg)

**Comment by UksusoFF** [comment]
Mobile layout also breaking here: https://github.com/fisharebest/webtrees/issues/2770#issuecomment-569124165

**Comment by mrqd9** [comment]
Adding `select{width:100%}` CSS, worked.
