### ISSUE TITLE
Edits Causing Traceback Error

### ISSUE THREAD

**Issue by GreggShimokura** [fisharebest/webtrees#2966]
Hi,

We are experiencing a new unexpected error after some days with a working site.

### Error Condition: 
After making a edit to the birthday of a family member, the home page shows a sever error.  From the log: 
Snippet Only:
`Address in mailbox given [xxx.xx.xxx.xxx] does not comply with RFC 2822, 3.6.2. …/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:355 #0 …/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(272): Swift_Mime_Headers_MailboxHeader-&gt;assertValidAddress(&#039;206.47.13.58&#039;) #1 …/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(117): Swift_Mime_Headers_MailboxHeader-&gt;normalizeMailboxes(Array) #2 …/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(74): 
....`

### Work Around:  
Backing out of the edit (going ahead and NOT approving the Pending Change) returns the Home Page back to normal.

It is repeatable, in that I can make the edit, revert and toggle between good and bad states.

### Other Info:
In the error condition, I tried opening the control panel as I am an administrator and clicking on `Sending e-mail` and I get a different error thrown:
Snippet:
`substr() expects parameter 1 to be string, boolean given …/app/Services/EmailService.php:199 #0 …/app/Services/EmailService.php(199): substr(false, 1) #1 …/app/Http/RequestHandlers/EmailPreferencesPage.php(78): Fisharebest\Webtrees\Services\EmailService-&gt;isValidEmail(&#039;206.47.13.58&#039;) #2 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\EmailPreferencesPage-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #3 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #4 …/app/Module/HitCountFooterModule.php(149): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #5 
....`

Has anyone else seen this behaviour and could suggest a way forward?

Thank you,

Gregg

**Comment by fisharebest** [comment]
It's a known issue, and has already been fixed.

Does this help:

https://www.webtrees.net/index.php/en/forum/help-for-2-0/33941-solved-how-to-change-smtp-paramters#74220

**Comment by GreggShimokura** [comment]
Yes, I got it working.

Although I did not find the `phpstan-baseline.neon` file in my installation.

Thank you,

Gregg

**Comment by fisharebest** [comment]
> Although I did not find the phpstan-baseline.neon file in my installation.

That's part of the build/test tools.  It is not part of the distributed code.
