### ISSUE TITLE
Changes report user - 2.0.2

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2970]
Last change in Hebrew PDF - Latin user ID prints without a space or - attached to the time. the - prints to the left of the ID

We see:
![image](https://user-images.githubusercontent.com/5202996/72258441-c6295780-3616-11ea-9931-b5b7792b6832.png)

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
