### ISSUE TITLE
Changes report nicknames - 2.0.2

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2971]
HTML
On the Hebrew page a Latin name with a nick-name prints as "Given Surname "Nickname - 
"Itzhak Feder "Zooki "יצחק פדר "צוקי
On the English page a Hebrew name with a nickname prints with the trailing ' or " to the right instead of to the left - Izhak Feder ‘Zooki’ יצחק פדר ‘צוקי’

PDF
On the Hebrew page a Latin name with a nick-name prints as "Nickname"Given Surname -
 "Zooki"Izhak Feder "יצחק פדר "צוקי 
On the English page a Hebrew name with a nickname - Text on text - the report of the next changes print right justified ...
![2020-01-13_14-49-36](https://user-images.githubusercontent.com/5202996/72258631-3c2dbe80-3617-11ea-8852-dfc80b22e9aa.jpg)

There are similar issues in other reports.

**Comment by melizaa** [comment]
Could we start from this changes report to adjust the wt reports to again work with Latin and Hebrew texts?

**Comment by melizaa** [comment]
See #2013 - #2016

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
