### ISSUE TITLE
Facts and Events Table Format Change - 2.0.2

### ISSUE THREAD

**Issue by dbq-andersons** [fisharebest/webtrees#2972]
In the Facts and Events table (both individual and family), would like to see the blank line feed between the place name and the source placed after the Address: (if there is one).

![image](https://user-images.githubusercontent.com/43183321/72261684-e509f880-35da-11ea-9b77-348886664762.png)

Thinking something like this might look better especially in cases where I strip out the source detail.

![image](https://user-images.githubusercontent.com/43183321/72264493-7465da80-35e0-11ea-819a-b374c3c46406.png)

Cheers,

Bill Anderson

**Comment by dbq-andersons** [comment]
So, I finally looked over the code in FunctionsPrintFacts.php and I have duplicated how I want things to look by commenting out line 352 . . .

```
 351         // A blank line between the primary attributes (value, date, place)      and the secondary ones
 352         #echo '<br>';
 353
```
and inserting a duplicate after line 492.

```
 490                     break;
 491             }
 492         }
 493         echo '<br>';
 494         echo self::printFactSources($tree, $fact->gedcom(), 2);
 495         echo FunctionsPrint::printFactNotes($tree, $fact->gedcom(), 2);
```

While it seems simple to me as a UNIX/scripting jockey, I do not know enough about the overall code base to have a guess as to what this might break for other people.  All I do know is that it works for me with no side effects.

Let me know if this change will be coded in, or I can just make it a customization on my part.

Cheers,

Bill

**Comment by fisharebest** [comment]
What we probably need is to wrap the various sections in `<div>`s, so that we can set vertical padding using CSS.
