### ISSUE TITLE
HTTPS not working

### ISSUE THREAD

**Issue by StefOfficiel** [fisharebest/webtrees#2973]
FR : Il y a une erreur en HTTPS, la page s'affiche sans feuilles de style, est-ce une erreur connu (je n'ai pas vu dans les issues) ? [version 2.0.1]
Merci !

EN : There is an error in HTTPS, the page is displayed without stylesheets, is this a known error ? (I have not seen in the issues) [version 2.0.1]
Thank !

**Comment by fisharebest** [comment]
In the file `data/config.ini.php`, what value do you have for `base_url`?

If this is correct, can you provide the URL of your site so that I can take a look?

**Comment by StefOfficiel** [comment]
FR : Parfait, c'était bien ça, "url" dans le "config.ini.php" était sur "http://", j'ai changé pour "https://" et ça fonctionne, merci !

EN : Perfect, that was it, "url" in "config.ini.php" was on "http://", I changed to "https://" and it works, thanks!

**Comment by StefOfficiel** [comment]
FR : Petit tips, j'ai testé, chez moi ça fonctionne, remplacer le "http://" ou le "https://" par "//". Exemple : "base_url="http://mytree.tld"" => "base_url="//mytree.tld"" ce qui le rend compatible HTTP&HTTPS !
A vérifier que mon raisonnement soit bon !

EN : Little tips, I tested, at home it works, replace the "http: //" or the "https: //" with "//". Example: "base_url =" http: //mytree.tld "" => "base_url =" // mytree.tld "" which makes it HTTP & HTTPS compatible!
To verify that my reasoning is good!

**Comment by fisharebest** [comment]
> replace the "http://" or the "https://" with "//"

Do not do this.

URLs are also included in emails, robots.txt, sitemaps, etc.

These require `https:` or `http:`.

**Comment by StefOfficiel** [comment]
Ok, thank !
