### ISSUE TITLE
Errors when attempting to install

### ISSUE THREAD

**Issue by nextgeninternet** [fisharebest/webtrees#2974]
After uploading all the files and navigating to index.php there several error displayed in the browser (Opera)

Fatal error: Uncaught Illuminate\Container\EntryNotFoundException: Fisharebest\Webtrees\Http\Middleware\ReadConfigIni in /srv/disk18/user/www/example.com/ws/vendor/illuminate/container/Container.php:630 Stack trace:
#0 /srv/disk18/user/www/example.com/ws/vendor/oscarotero/middleland/src/Dispatcher.php(97): Illuminate\Container\Container->get('Fisharebest\\Web...') 
#1 /srv/disk18/user/www/example.com.am/ws/vendor/oscarotero/middleland/src/Dispatcher.php(126): Middleland\Dispatcher->get(Object(Nyholm\Psr7\ServerRequest)) 
#2 /srv/disk18/user/www/example.com/ws/app/Http/Middleware/EmitResponse.php(56): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#3 /srv/disk18/user/www/example.com/ws/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))

#4 /srv/disk18/user/www/example.com/ws/app/Http/Middleware/PhpEnvironment.php(49): Middlela in /srv/disk18/user/www/example.com/ws/vendor/illuminate/container/Container.php on line 630

**Comment by fisharebest** [comment]
It hard to guess what might have happened.

Are you 100% certain that all the files were copied completely?

What sort of server is this?  Anything unusual?  What version of PHP?

Does the folder /data have write permission?

**Comment by nextgeninternet** [comment]
I reloaded them twice. It is shard server hosting. PHP version 7.4.1

**Comment by nextgeninternet** [comment]
I just tried switching to PHP 7.2.26 and uploaded allthe files again. NOW

Fatal error: Uncaught ReflectionException: Class Fisharebest\Webtrees\Module\YahrzeitModule does not exist in /srv/disk18/3286846/www/newmanfamily.dx.am/ws/vendor/illuminate/container/Container.php:788 Stack trace: #0 /srv/disk18/3286846/www/newmanfamily.dx.am/ws/vendor/illuminate/container/Container.php(788): ReflectionClass->__construct('Fisharebest\\Web...') #1 /srv/disk18/3286846/www/newmanfamily.dx.am/ws/vendor/illuminate/container/Container.php(667): Illuminate\Container\Container->build('Fisharebest\\Web...') #2 /srv/disk18/3286846/www/newmanfamily.dx.am/ws/vendor/illuminate/container/Container.php(615): Illuminate\Container\Container->resolve('Fisharebest\\Web...', Array) #3 /srv/disk18/3286846/www/newmanfamily.dx.am/ws/app/Helpers/functions.php(45): Illuminate\Container\Container->make('Fisharebest\\Web...') #4 /srv/disk18/3286846/www/newmanfamily.dx.am/ws/app/Services/ModuleService.php(564): app('Fisharebest\\Web...') #5 [internal function]: Fisharebest\Webtrees\Services\ModuleService::Fisharebest\Webtrees\Servi in /srv/disk18/3286846/www/newmanfamily.dx.am/ws/vendor/illuminate/container/Container.php on line 788

**Comment by fisharebest** [comment]
> Fatal error: Uncaught ReflectionException: Class Fisharebest\Webtrees\Module\YahrzeitModule does not exist

This is the file app/Module/YahrzeitModule.php

If you are missing this file, then others may be missing or incomplete.

> Are you 100% certain that all the files were copied completely?

Try copying all the files to the server again...

**Comment by nextgeninternet** [comment]
I have FTPed all the files again.
`app/Module/YahrzeitModule.php` does exit
I tried removing the file and the error are the same.

**Comment by nextgeninternet** [comment]
I finally got it fixed. I added a .htaccess file to every file directory. I am not sure why this made a difference but it fixed it.
