### ISSUE TITLE
Convert CEME tags to burial places

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#2983]
**Gedcom 5.3 used the CEME tag like this:**

```
1 BURI
2 PLAC
3 CEME
4 PLOT
```

> Used only when cemetery information is managed separately from the burial place name.  It is      permissible to include the cemetery name as the low level locality name; for example,      Richmond Cemetery, Richmond, Cache, Utah, USA.

So, we should be able to convert this

```
1 BURI
2 PLAC Richmond, Cache, Utah, USA
3 CEME Richmond Cemetery
4 PLOT abc123
```

into this

```
1 BURI
2 PLAC abc123, Richmond Cemetery, Richmond, Cache, Utah, USA
```

or

```
1 BURI
2 PLAC Richmond, Cache, Utah, USA
2 ADDR abc123, Richmond Cemetery
```

**Other applications  used CEME like this:**

```
1 BURI
2 PLAC
2 CEME
```

This can be converted in the same way.

Are there any other structures that use `CEME`?

**Comment by hartenthaler** [comment]
When I use the function "preview" of the CEME batch conversion, there is an error. The "update" button does not work (without any error message).
![Screenshot (50)](https://user-images.githubusercontent.com/6324175/76462883-16405280-63eb-11ea-9e4a-d9c6f5c6d2f8.png)
