### ISSUE TITLE
Custom module based on existing one

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#2985]
I'm trying to slightly edit an existing core module by using the example given in this [README ](https://github.com/fisharebest/webtrees/tree/master/modules_v4#how-to-extendmodify-an-existing-modules)file, but it simply doesn't work.

Here is my code:
```
<?php
declare(strict_types=1);

namespace JustCarmen\Webtrees\Module;

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Module\ModuleCustomTrait;
use Fisharebest\Webtrees\Module\PedigreeChartModule;
use Fisharebest\Webtrees\Module\ModuleCustomInterface;
/**
 * Creating an anoymous class will prevent conflicts with other custom modules.
 */
return new class extends PedigreeChartModule implements ModuleCustomInterface {
    use ModuleCustomTrait;

     /**
     * Constructor.  The constructor is called on *all* modules, even ones that are disabled.
     * This is a good place to load business logic ("services").  Type-hint the parameters and
     * they will be injected automatically.
     */
    public function __construct()
    {
        // NOTE:  If your module is dependent on any of the business logic ("services"),
        // then you would type-hint them in the constructor and let webtrees inject them
        // for you.  However, we can't use dependency injection on anonymous classes like
        // this one. For an example of this, see the example-server-configuration module.
    }

    /**
     * Bootstrap.  This function is called on *enabled* modules.
     * It is a good place to register routes and views.
     *
     * @return void
     */
    public function boot(): void
    {
    }

    /**
     * @return string
     */
    public function title(): string
    {
        return I18N::translate('Pedigree');
    }

    /**
     * @return string
     */
    public function description(): string
    {
        return 'A modified version of the pedigree chart';
    }

    // Change the default layout...
    public const DEFAULT_STYLE = self::STYLE_DOWN;
};
```
What am I doing wrong?

**Comment by fisharebest** [comment]
There are a few things that I need to change in the core code

* some `private` must become `protected`
* some `self::` must become `static::`

The only thing you were missing is the parameter (`ChartService`) for the constructor.

When this is done, your custom module becomes this

```
return new class(app(ChartService::class)) extends PedigreeChartModule implements ModuleCustomInterface {
    use ModuleCustomTrait;

    protected const DEFAULT_STYLE       = self::STYLE_DOWN;
    protected const DEFAULT_PARAMETERS  = [
        'generations' => parent::DEFAULT_GENERATIONS,
        'style'       => self::STYLE_DOWN,
    ];
};
```

----------


I need to review the code, and make these `private`/`protected` changes to all the charts and modules

**Comment by fisharebest** [comment]
PS.  This code will use the same URL as the existing chart.

This means that you must disable the existing chart - only one will match.

If you want to have both charts together, then your module will also need to define `ROUTE_URL`.

**Comment by fisharebest** [comment]
OK - done.  The example code above now works.

**Comment by JustCarmen** [comment]
Thanks for the clarification and the fix.

**Comment by JustCarmen** [comment]
I was in the assumption this should be easy after the fix, but alas...

I've followed your instructions and added the code as described above. Furthermore I disabled the existing pedigree chart module to prevent URL conflicts. But that wasn't enough. Next step was to  add the ROUTE_URL constant to my code with a slightly different URL, but that wasn't enough either. I still got errors. Eventually I copied the boot function ($router_container->getMap()) from the original module to the boot function in my own module. That did the trick, but I don't think that step should be necessary.

So I finally end up at the module page but unfortunately the page itself also gives an error:

_Call to a member function sosaStradonitzAncestors() on null …\app\Module\PedigreeChartModule.php:224_

And now I am stuck at that point. What next?

**Comment by fisharebest** [comment]
> I still got errors

It would be helpful to know the errors ;-)

> And now I am stuck at that point. What next?

Can you post your code, or put it in a github repository?

**Comment by JustCarmen** [comment]
Hi Greg, here my code so far. 
```
<?php
declare(strict_types=1);

namespace JustCarmen\Webtrees\Module;

use Fisharebest\Webtrees\I18N;
use Aura\Router\RouterContainer;
use Fig\Http\Message\RequestMethodInterface;
use Illuminate\Database\Capsule\Manager as DB;
use Fisharebest\Webtrees\Services\ChartService;
use Fisharebest\Webtrees\Module\ModuleCustomTrait;
use Fisharebest\Webtrees\Module\PedigreeChartModule;
use Fisharebest\Webtrees\Module\ModuleCustomInterface;
/**
 * Creating an anoymous class will prevent conflicts with other custom modules.
 */
return new class (app(ChartService::class)) extends PedigreeChartModule implements ModuleCustomInterface {
    use ModuleCustomTrait;

    protected const ROUTE_URL  = '/tree/{tree}/_pedigree-{style}-{generations}/{xref}';

     /**
     * Constructor.  The constructor is called on *all* modules, even ones that are disabled.
     * This is a good place to load business logic ("services").  Type-hint the parameters and
     * they will be injected automatically.
     */
    public function __construct()
    {
        // NOTE:  If your module is dependent on any of the business logic ("services"),
        // then you would type-hint them in the constructor and let webtrees inject them
        // for you.  However, we can't use dependency injection on anonymous classes like
        // this one. For an example of this, see the example-server-configuration module.
    }

    /**
     * Bootstrap.  This function is called on *enabled* modules.
     * It is a good place to register routes and views.
     *
     * @return void
     */
    public function boot(): void
    {
          // Disable the default pedigree_chart module. It is replaced by this module.
         DB::table('module')
         ->where('module_name', '=', 'pedigree_chart')
         ->update([
             'status' => 'disabled',
         ]);

        $router_container = app(RouterContainer::class);
        assert($router_container instanceof RouterContainer);

        $router_container->getMap()
            ->get(static::class, static::ROUTE_URL, $this)
            ->allows(RequestMethodInterface::METHOD_POST)
            ->tokens([
                'generations' => '\d+',
                'style'       => implode('|', array_keys($this->styles())),
            ]);
    }

    /**
     * @return string
     */
    public function title(): string
    {
        return I18N::translate('Pedigree');
    }

    /**
     * @return string
     */
    public function description(): string
    {
        return 'A modified version of the pedigree chart';
    }

    // Change the default layout
    protected const DEFAULT_PARAMETERS  = [
        'generations' => self::DEFAULT_GENERATIONS,
        'style'       => self::STYLE_DOWN,
    ];
};
```
As said above I first only disabled the original module. But that gives me this error: 

> class@anonymous…\modules_v4\my-pedigree-chart\module.php0000014A56980B11 …\vendor\aura\router\src\Map.php:152
#0 …\app\Helpers\functions.php(169): Aura\Router\Map->getRoute('class@anonymous...')
etc

Then I added the ROUTE_URL constant to the code:

`protected const ROUTE_URL  = '/tree/{tree}/_pedigree-{style}-{generations}/{xref}';`

But that didn't solve the issue. Same error.

Eventually I copied the whole code blok from the boot function of the original module to the boot function of my module:
 ```
$router_container = app(RouterContainer::class);
        assert($router_container instanceof RouterContainer);

        $router_container->getMap()
            ->get(static::class, static::ROUTE_URL, $this)
            ->allows(RequestMethodInterface::METHOD_POST)
            ->tokens([
                'generations' => '\d+',
                'style'       => implode('|', array_keys($this->styles())),
            ]);
```

That works. Now at least the top block of pedigree page is visible. But below this error message appears:
`Call to a member function sosaStradonitzAncestors() on null …\app\Module\PedigreeChartModule.php:224`

**Comment by fisharebest** [comment]
You are extending the class `PedigreeChartModule`.

This class has a constructor.

Your module contains an empty constructor.

This prevents the constructor in `PedigreeChartModule` from being called.

If you do not plan to modify the constructor, then you should delete yours.

If you do plan to modify it, then it should take `ChartService $chart_service` as a parameter, and call `parent::__construct($chart_service)`.

**Comment by fisharebest** [comment]
I see that you disable the existing `PedigreeChartModule` with a database call.

Database writes are slow, and will block other read requests.

If you must do this, then you should do a read first (which is quicker), and only update if necessary.

Alternatively, you might be able to do something like in the boot method.

```
$module = $module_service->findByName('pedigree_chart');
if ($module !== null) {
    $module->setEnabled(false);
}
```

This will avoid any database call.

Also, it will not save the enabled/disabled status to the database.

So if your module is disabled/removed, then the original module will return.

This code requires the `ModuleService` object.

You will need to add it to your constructor (and also call the parent constructor).

**Comment by JustCarmen** [comment]
> If you do not plan to modify the constructor, then you should delete yours.

This helps. The page displays without errors now, but I don't think the code for the Route_URL in the boot function should be necessary or am I wrong? As soon as I remove it the error returns. 

By the way, this is a 500 internal server error. This wasn't clear (for me) from the error output on the page (class@anonymous…\modules_v4\my-pedigree-chart\module.php0000014A56980B11 …\vendor\aura\router\src\Map.php:152 etc.) but this comes from the console log.

> Alternatively, you might be able to do something like in the boot method.
> 
> $module = $module_service->findByName('pedigree_chart');
> if ($module !== null) {
>     $module->setEnabled(false);
> }
> This will avoid any database call.
....
> This code requires the ModuleService object.
> 
> You will need to add it to your constructor (and also call the parent constructor).
> 
Thanks, this is much better but I use a slightly different approach. Calling the ModuleService in the constructor didn't work because the parent is the ChartService and not the ModuleService. And I think this is even more convenient.

Here my (working) code.
```
<?php
declare(strict_types=1);

namespace JustCarmen\Webtrees\Module;

use Fisharebest\Webtrees\I18N;
use Aura\Router\RouterContainer;
use Fig\Http\Message\RequestMethodInterface;
use Fisharebest\Webtrees\Services\ChartService;
use Fisharebest\Webtrees\Module\ModuleCustomTrait;
use Fisharebest\Webtrees\Module\PedigreeChartModule;
use Fisharebest\Webtrees\Module\ModuleCustomInterface;
use Fisharebest\Webtrees\Module\ModuleInterface;
use Fisharebest\Webtrees\Services\ModuleService;

/**
 * Creating an anoymous class will prevent conflicts with other custom modules.
 */
return new class (app(ChartService::class)) extends PedigreeChartModule implements ModuleCustomInterface, ModuleInterface {
    use ModuleCustomTrait;

    protected const ROUTE_URL  = '/tree/{tree}/_pedigree-{style}-{generations}/{xref}';

    /**
     * Bootstrap.  This function is called on *enabled* modules.
     * It is a good place to register routes and views.
     *
     * @return void
     */
    public function boot(): void
    {
        // Disable the default pedigree_chart module. It is replaced by this module.
        $module = app(ModuleService::class)->findByName('pedigree_chart');
        if ($module !== null) {
            $module->setEnabled(false);
        }

        $router_container = app(RouterContainer::class);
        assert($router_container instanceof RouterContainer);

        $router_container->getMap()
            ->get(static::class, static::ROUTE_URL, $this)
            ->allows(RequestMethodInterface::METHOD_POST)
            ->tokens([
                'generations' => '\d+',
                'style'       => implode('|', array_keys($this->styles())),
            ]);
    }

    /**
     * @return string
     */
    public function title(): string
    {
        return I18N::translate('Pedigree');
    }

    /**
     * @return string
     */
    public function description(): string
    {
        return 'A modified version of the pedigree chart';
    }

    // Change the default layout
    protected const DEFAULT_PARAMETERS  = [
        'generations' => self::DEFAULT_GENERATIONS,
        'style'       => self::STYLE_DOWN,
    ];
};
```
