### ISSUE TITLE
Changing part of a view

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#2986]
Suppose I want to change a little area of the individual page within a custom module. Should I always take over the whole view (with the drawback of missing important core changes later) or can I just overwrite one or more of the variables?

This is just an example. But suppose I want to change the title of the individual page. Should I make a copy of the view individual-page.phtml into my own module view folder and change the title in there? Or could I just overwrite the variable and leave the original view as is?

The individual-page view is called from app\Http\RequestHandlers\IndividualPage.php. The variables used in the view are declared there:

```
         return $this->viewResponse('individual-page', [
            'age'              => $age,
            'clipboard_facts'  => $this->clipboard_service->pastableFacts($individual, new Collection()),
            'count_media'      => $this->countFacts($individual, ['OBJE']),
            'count_names'      => $this->countFacts($individual, ['NAME']),
            'count_sex'        => $this->countFacts($individual, ['SEX']),
            'individual'       => $individual,
            'individual_media' => $individual_media,
            'meta_robots'      => 'index,follow',
            'name_records'     => $name_records,
            'sex_records'      => $sex_records,
            'sidebars'         => $this->getSidebars($individual),
            'tabs'             => $this->getTabs($individual),
            'significant'      => $this->significant($individual),
            'title'            => $individual->fullName() . ' ' . $individual->lifespan(),
            'tree'             => $tree,
            'user_link'        => $user_link,
        ]);
```
If I only want to change the title I would like to have something like this additional stuff in my module:
```
        return $this->viewResponse('individual-page', [           
            'title'            => 'blablabla',
        ]);
```
rather then a copy of the view.

Is that possible and if so, how?

**Comment by fisharebest** [comment]
> But suppose I want to change the title of the individual page.

This should be easy. You create your own view `my-module::individual-page`, which contains this:

```
<?= view('::individual-page', ['title' => 'MY TITLE'] + get_defined_vars())
```

Note the `::` in the view name.  This means use the original view.  Otherwise, there would be an infinite loop.

This will add your modified title to the original variables, and then use the original view.

> Suppose I want to change a little area of the individual page within a custom module. Should I always take over the whole view (with the drawback of missing important core changes later)

You have two options.  

1) replace the whole view
2) fetch the existing view and modify it.  e.g.

```
<?=
$v = view('::individual-page', get_defined_vars());
$v = preg_replace('~<title>.*</title>~', ..., $view);
echo $v;
```

Of course, both these may have problems if there are changes in the original view...

For large/complex pages, I am happy to split the view into smaller views.  For the individual page, we could split it into

1) layout
2) profile image
3) names
4) tabs
5) sidebars

Just post an issue to discuss the details.

**Comment by JustCarmen** [comment]
Thanks Greg for the explanation. Both options work.

> For large/complex pages, I am happy to split the view into smaller views. For the individual page, 
>
> we could split it into
> 
> layout
> profile image
> names
> tabs
> sidebars

That would be very helpful when customizing a theme. Smaller views are easier to maintain.

> Just post an issue to discuss the details.

I've not a real issue right now, it was just a question to understand how this works. But there might pop up one later.

**Comment by fisharebest** [comment]
OK.  Just create a new issue when you need a change.
