### ISSUE TITLE
V2 new data fixes - add missing death records

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2987]
The selection for this is too wide, for example I have someone born in 1973 (but with no other data) being presented as needing a death record!

And the  "Age at which to assume an individual is dead" option is set at 120

**Comment by fisharebest** [comment]
> presented as needing a death record

Are you sure?

Are you seeing this in the table?
Does it have a preview/update button?

If not, then it will not be updated.

The table of results shows things that **might** need processing.
It is based on a quick/easy filter of the database using SQL.

For this data-fix, it just searches for records without `1 DEAT`

If you page through the data, you should see entries with this button.

I suspect you won't be the first to point this out, so perhaps we need a big banner with words to the effect:

"This is a list of records that have been selected for further analysis.  Rows here might not need updating."

**Comment by ddrury** [comment]
Ah Ok, so the Data fix column will have a button rather than a dash?

I agree that further information would be helpful and having the page size selector at the top of the table would help as well

**Comment by fisharebest** [comment]
BTW - even if we *could* use SQL to accurately find records to change, we cannot use SQL for pending records (as the linked places/names/dates tables won't have been updated).  So pending records are always included in the list.
