### ISSUE TITLE
Custom Css/Js module

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#2988]
I prefer a smaller font-size in the admin trees manage section (with a multiple tree site the current size is too big to my taste), so I thought that could be easily done using the Custom CSS/JS Module to add some additional styling.

But that doesn't work in the admin section. The style tags are only implemented in the head tags of the frontsite. Why? Aren't we supposed to change anything in the backend? There is no AdminTheme module either.

Or is there another way to achieve what I want?

**Comment by fisharebest** [comment]
I decided that modules should not run on the control panel, because it would be too easy for a bad module to break the control panel - and prevent the module being removed.

> the current size is too big to my taste

Size of text or size of `<h1> <h2> <h3>`?

The bootstrap defaults are

h1 - 2.5 rem
h2 - 2 rem
h3 - 1.75 rem
h4 - 1.5 rem

Perhaps change these to: 2 / 1.75 / 1.5 / 1.25

**Comment by ddrury** [comment]
If you look at my pull request to replace colorbox https://github.com/fisharebest/webtrees/pull/2864 you'll notice that I've changed the way vendor.css is built by compiling scss files where possible (including bootstrap) and a load of variables are included in `bootstrap/scss/_variables.scss` therefore over-riding the default values would be trivial

**Comment by JustCarmen** [comment]
> Perhaps change these to: 2 / 1.75 / 1.5 / 1.25

Yes, that would be much better. It is just because all panels are collapsed by default, and having a text in the H2 font size at 2 rem looks very restless in this area.

> If you look at my pull request to replace colorbox #2864 you'll notice that I've changed the way vendor.css is built by compiling scss files where possible (including bootstrap) and a load of variables are included in bootstrap/scss/_variables.scss therefore over-riding the default values would be trivial

Yes, that is an option but a bit too much for a simple change like this. I was just playing around to see what can and what can't be done with little effort.
