### ISSUE TITLE
V2 Query on vendor.css

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2991]
When working on Lightgallery, I thought that some of the fonts were looking a bit "anaemic" so switching back to master and looking at vendor.css, I found that the body styling in bootstrap was being over-ridden by style.css in leaflet-geosearch (line 127).

Shouldn't bootstrap be the last file in the webpack.mix.js merge process so it's not over-ridden?

**Comment by fisharebest** [comment]
IMHO, leaflet-geosearch certainly shouldn't be styling the `<body>` element.

However, the pinned issue at https://github.com/smeijer/leaflet-geosearch/issues
suggests that there is little point creating an issue.

> Shouldn't bootstrap be the last file in the webpack.mix.js merge process so it's not over-ridden?

Bootstrap may need to come before datatables-bs4 and typeahead-bs4.
But moving this package first might be an option.

Maybe there's alternative package that it still supported/maintained?

**Comment by ddrury** [comment]
I've checked all the other files that comprise vendor.css and there is nothing else that interferes with bootstrap. There are a whole load of alternatives on the leaflet plugins page - I'll have a rummage

**Comment by ddrury** [comment]
This looks like the best bet https://github.com/perliedman/leaflet-control-geocoder
