### ISSUE TITLE
HTML validation - tabs on indi page

### ISSUE THREAD

**Issue by ljm42** [fisharebest/webtrees#2995]
This line:
https://github.com/fisharebest/webtrees/blob/7bb122d69bf8a45328cbee345e6744a32e16a8b0/resources/views/individual-page.phtml#L107
needs to have `role="tablist"`:
 `<ul class="nav nav-tabs flex-wrap" role="tablist">`

Because it contains a list of items with `role="tab"`:
```
  <ul role="tablist">
     <li><a role="tab"></a></li>
     <li><a role="tab"></a></li>
     <li><a role="tab"></a></li>
  </ul>
```

It looks like the other pages with the "nav-tabs" class already have this role, it was just missed on the indi page.

**Comment by fisharebest** [comment]
`role="tab"` probably ought to be on the `<li>`, rather than the `<a>`.

**Comment by fisharebest** [comment]
We also need `aria-controls="..."`

**Comment by fisharebest** [comment]
This appears to be the reference implementation

http://a11yideas.com/testcode/tabs/tabs_with_ARIA.html
