### ISSUE TITLE
Media List issue when multiple files in Media Object

### ISSUE THREAD

**Issue by ljm42** [fisharebest/webtrees#3011]
webtrees 2 allows multiple Media Files to be added to a single Media Object. But when browsing the Media List, the full Media Object is displayed for each Media File that is found.

So if you add 5 files to a Media Object, that full Media Object containing all 5 files will be displayed 5 separate times in the Media List instead of just once.

The code is searching Media Files, but should be grouping by Media Objects.

**Comment by t-karcher** [comment]
This seems to be fixed since 2.0.8: Thanks to the rewritten MediaListModule, results are grouped by media objects now as expected. I was able to reproduce it until 2.0.7, but not anymore.
