### ISSUE TITLE
Routing error at login when on Individuum page V2.0.1

### ISSUE THREAD

**Issue by Man-fred** [fisharebest/webtrees#3013]
1. After a correct login on a public individuum page i get a routing error (in german Firefox: "Umleitungsfehler"). The url is shown as below:
https://www.bielemeier.de/gedview/?route=%2Fgedview%2Ftree%2Fb1%2Findividual%2FX2832%2FJohann%2520Heinrich%2520Funnek%25C3%25B6tter/index.php?route=%2Fgedview%2F%2F

2. After login on the homepage i get a correct login with the url:
https://www.bielemeier.de/gedview/index.php?route=%2Fgedview%2Ftree%2Fb1%2Fmy-page
and there is no error.

Probable solution:
In the first url "index.php" is missing after the first .../gedwiew/... and "/index.php?route=%2Fgedview%2F%2F" should not be appended. Or, if the landing page shoud be the homepage, then the original route has to be deleted.

**Comment by fisharebest** [comment]
do you have the correct url for your site in the file data/config.ini php.  e.g.

base_url="https://www.bielemeier.de/gedview"

**Comment by Man-fred** [comment]
That line was missing. I inserted it and that solves the problem.
Thank you.
