### ISSUE TITLE
Inline Source Citations (V1.7.16)

### ISSUE THREAD

**Issue by webtrees-pesz** [fisharebest/webtrees#3014]
1 BIRT
2 DATE 01 MAR 1880
2 PLAC sample village
2 SOUR inline source

When a GEDCOM file is imported with an inline source at an event (e.g., birth), the source text is displayed normally in the Source field of the event.
If the Birth event is edited and saved, then an XREF ID is created from the source text, without the associated record. The source text is now displayed in red color as erroneous.

Raw GEDCOM after update:
1 BIRT
2 DATE 01 MAR 1880
2 PLAC sample village
2 SOUR @inline source@

If webtrees does not support inline sources, then an inline source should be converted to a corresponding source record during import.

**Comment by fisharebest** [comment]
This cannot easily be fixed in 1.7.

The edit interface code has too many hard-coded assumptions about the structure of source citations.

The code is being redesigned for 2.1, and will be fixed there.
