### ISSUE TITLE
Inline Source Citations (V2.0.1)

### ISSUE THREAD

**Issue by webtrees-pesz** [fisharebest/webtrees#3015]
1 BIRT
2 DATE 01 MAR 1880
2 PLAC sample village
2 SOUR inline source

After importing, the source text in the raw GEDCOM is displayed normally, but the "Source" field in the Birth view is empty. When the Birth event is edited and saved, the SOUR tag disappears from the raw GEDCOM.

Raw GEDCOM after update:
1 BIRT
2 DATE 01 MAR 1880
2 PLAC sample village

If webtrees does not support inline sources, then an inline source should be converted to a corresponding source record during import.

**Comment by fisharebest** [comment]
> an inline source should be converted to a corresponding source record during import.

This would be the best approach - especially since GEDCOM 7 no longer supports inline sources.

**Comment by webtrees-pesz** [comment]
Hi Greg,
you removed that issue from the 2.1.0 milestone. What does it mean? In version 2.1.0, are the inline sources always converted into source records during import?

**Comment by fisharebest** [comment]
It means that this fix will be delayed.

**Comment by fisharebest** [comment]
This is fixed in the 2.1 dev code.
