### ISSUE TITLE
sitemap should run as unprivileged user

### ISSUE THREAD

**Issue by ljm42** [fisharebest/webtrees#3019]
The 2.0.1 sitemap has a confusing behavior - if you look at the sitemap while logged in, you will see references to private people. The good news is that when unprivileged users (such as search engines) view it, the private people are not included.

There is no expectation that a sitemap would be based on the current user's privs, the expectation is that it contains only what we want a search engine to see.

Would it be possible to force the sitemap to only show data that an unprivileged user can see, regardless of the current user's privs?

Thanks for considering it!

**Comment by ljm42** [comment]
Thanks! This should eliminate any confusion when a logged in user views the sitemap

**Comment by fisharebest** [comment]
Bear in mind that the sitemap files are cached for 14 days - so you may have cached versions that contain links to private records.

**Comment by ljm42** [comment]
Thanks for the reminder :) That leads to something else I've been thinking about: https://github.com/fisharebest/webtrees/issues/3022
