### ISSUE TITLE
option to clear Sitemap cache

### ISSUE THREAD

**Issue by ljm42** [fisharebest/webtrees#3022]
The sitemap files are cached for 14 days, but after making a lot of changes I'd like to encourage search engines to visit sooner. Perhaps it would make sense to add a "Clear Sitemap Cache" button to the Sitemap module page so the files can be regenerated?

**Comment by fisharebest** [comment]
We have a new cache library.

The sitemap module needs to use it, instead of the module-settings table.

The file-cache is stored in `/data/cache`, and can be deleted using the "clean data folder" option in the control panel

**Comment by fisharebest** [comment]
Last time I looked, google wouldn't re-query a sitemap file more frequently than 14 days.

This is why the files are cached for 14 days.

**Comment by ljm42** [comment]
Oh I wondered where the two week cache came from :) I'll keep an eye on the Google Search Console to see when they come next. Currently it says:

```
/module/sitemap/File?file=1-i-0	Jan 27, 2020	Success	167
/module/sitemap/File?file=1-m-0	Jan 27, 2020	Success	9
/module/sitemap/File?file=1-r-0	Jan 24, 2020	1 error	0
/module/sitemap/File?file=1-s-0	Jan 23, 2020	Success	2
```

**Comment by fisharebest** [comment]
That reminds me - we need pretty URLs for these.

**Comment by fisharebest** [comment]
Note: changing the URLs means that existing URLs will become invalid.

Google will eventually pick up the new URLs from `robots.txt`.

If you are impatient, you can submit the new URL - `/sitemap.xml`

**Comment by ljm42** [comment]
It took some minor changes to get it to work with 2.0.1 ($route->name changes to $route), but it is working ;) 

Wow! This is very nice! There are no more empty sitemaps, no more private records, the pretty urls are great, and I *really* like the stylesheet

I see how to delete the cache too. It feels a little heavy-handed to delete all cache entries for this, but if you think it is ok then I'm sure it is :) 

Google parsed the main file and the 5 sub files:
```
/sitemap-WEBSITE.GED-INDI-0.xml	Jan 27, 2020	Success	167
/sitemap-WEBSITE.GED-NOTE-0.xml	Jan 27, 2020	Success	1
/sitemap-WEBSITE.GED-OBJE-0.xml	Jan 27, 2020	Success	9
/sitemap-WEBSITE.GED-REPO-0.xml	Jan 27, 2020	Success	1
/sitemap-WEBSITE.GED-SOUR-0.xml	Jan 27, 2020	Success	2
```

This is really cool, thanks!
