### ISSUE TITLE
suppress empty sitemaps

### ISSUE THREAD

**Issue by ljm42** [fisharebest/webtrees#3023]
Some of my sitemaps are empty due to privacy restrictions (notes and repos):

```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
</urlset>
```
which the Google Search Console reports as an error. Can we prevent the main sitemap file from linking to empty sitemaps? Probably not critical.

**Comment by fisharebest** [comment]
We cannot know in advance that a sitemap file will be empty.

Previously, empty sitemap files were given a link to the home page - to prevent this error.

This step must have been omitted during the rewrite.

Simple to fix.
