### ISSUE TITLE
Spaces in Pretty URLs

### ISSUE THREAD

**Issue by ljm42** [fisharebest/webtrees#3024]
I am very happy to have Pretty URLs, but I have a request... can we change spaces from %20 to a hyphen?

So instead of:
  https://dev.webtrees.net/demo-dev/tree/demo/individual/i1/Queen%20Elizabeth%20II
the url would be much more readable:
  https://dev.webtrees.net/demo-dev/tree/demo/individual/i1/Queen-Elizabeth-II

This page:
  https://www.commonplaces.com/blog/how-to-create-seo-friendly-urls/
describes an idea that is on a lot of the SEO sites:

> Using hyphens to separate words in URL phrases is important to both user readability and search engine optimization. Google recommends using hyphens (-) instead of underscores (_) in URLs because hyphens are treated as spaces between words, while words connected by underscores are viewed as one word

Here is the Google page they seem to be referring to:
  https://support.google.com/webmasters/answer/76329?hl=en

---
Oh... maybe this function:
  https://github.com/fisharebest/webtrees/blob/master/app/GedcomRecord.php#L368
could call this one?
  https://github.com/fisharebest/webtrees/blob/master/vendor/illuminate/support/Str.php#L456

**Comment by xmlf** [comment]
So, I have modified it:
https://github.com/fisharebest/webtrees/issues/2611#issuecomment-565663632

**Comment by fisharebest** [comment]
@ljm42 - we originally used the `Str::slug()` function - but it breaks with non-latin characters.

So it was taken out while I find another solution.  I'd prefer to use a 3rd party library, but I may have to write my own.

**Comment by fisharebest** [comment]
@xmlf - can you test the latest code.

`王秀英` becomes `wang-xiu-ying`

**Comment by xmlf** [comment]
Class 'Transliterator' not found …/app/GedcomRecord.php:371

**Comment by fisharebest** [comment]
This requires the PHP library `intl`.

**Comment by fisharebest** [comment]
I have added a test for this.

**Comment by xmlf** [comment]
Intl extension is not a common extension. I cannot install it at present, so I cannot test it. I am very sorry.
Hope to be able to add the option to close `slug `. Not very friendly to CJK.

**Comment by fisharebest** [comment]
This is now on the demo server.

https://dev.webtrees.net/demo-dev/tree/demo/individual/X242/wang-xiu-ying

**Comment by ljm42** [comment]
Now these are pretty urls :)

Would you mind clearing the sitemap cache on the demo-dev server so we can see it with the new slug?
  https://dev.webtrees.net/demo-dev/sitemap-demo-INDI-0.xml

Also, the robots.txt in the root is out of date:
  https://dev.webtrees.net/robots.txt

**Comment by fisharebest** [comment]
> Would you mind clearing the sitemap cache
> robots.txt in the root is out of date

done

**Comment by xmlf** [comment]
> This requires the PHP library `intl`.

I haved install PHP library `intl`.
But it show:
`Call to a member function transliterate() on null`

`print_r(get_defined_functions());` show:
`transliterator_create [1288] => transliterator_create_from_rules [1289] => transliterator_list_ids [1290] => transliterator_create_inverse [1291] => transliterator_transliterate [1292] => transliterator_get_error_code [1293] => transliterator_get_error_message`
