### ISSUE TITLE
QUAY field display

### ISSUE THREAD

**Issue by ljm42** [fisharebest/webtrees#3026]
When adding/editing a fact on an individual, the "Quality of data" field contains a dropdown with several options:
- primary evidence
- secondary evidence
- questionable evidence
- unreliable evidence

However, when viewing the fact on an individual record, it displays a number:
- Quality of data: 3

This discepancy between what you choose in the input box and what is displayed is confusing. Can we have it display the meaning rather than the number?

**Comment by fisharebest** [comment]
<img width="497" alt="Screenshot 2021-02-11 at 14 36 56" src="https://user-images.githubusercontent.com/2306088/107650649-9ebc1880-6c76-11eb-9580-d06f6c945ced.png">

Was fixed in a recent change.
