### ISSUE TITLE
ERR after modifying foldername of data-folder

### ISSUE THREAD

**Issue by AndreasRauhut** [fisharebest/webtrees#3029]
SQLSTATE[42000]:  Syntax error or access violation: 1203 User rauhutbase already has more  than &#039;max_user_connections&#039; active connections  …/vendor/illuminate/database/Concerns/ManagesTransactions.php:109 #0 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(109):  PDO-&gt;beginTransaction() #1 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(93):  Illuminate\Database\Connection-&gt;createTransaction() #2 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(23):  Illuminate\Database\Connection-&gt;beginTransaction() #3 …/app/Http/Middleware/UseTransaction.php(46):  Illuminate\Database\Connection-&gt;transaction(Object(Closure), 3) #4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #5 …/app/Http/Middleware/DoHousekeeping.php(80):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #7 …/app/Http/Middleware/UseTheme.php(70):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #9 …/app/Http/Middleware/CheckForMaintenanceMode.php(51):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #11 …/app/Http/Middleware/UseLanguage.php(73):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #13 …/app/Http/Middleware/UseSession.php(73):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #15 …/app/Http/Middleware/UseFilesystem.php(58):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\UseFilesystem-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #17 …/app/Http/Middleware/UseCache.php(74):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\UseCache-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #19 …/app/Http/Middleware/UpdateDatabaseSchema.php(58):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #21 …/app/Http/Middleware/UseDebugbar.php(67):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\UseDebugbar-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #23 …/app/Http/Middleware/UseDatabase.php(90):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #25 …/vendor/middlewares/client-ip/src/ClientIp.php(81):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #26 …/app/Http/Middleware/ClientIp.php(47):  Middlewares\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #28 …/app/Http/Middleware/HandleExceptions.php(75):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #30 …/app/Http/Middleware/BaseUrl.php(77):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #32 …/app/Http/Middleware/ReadConfigIni.php(65):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #34 …/app/Http/Middleware/EmitResponse.php(56):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #36 …/app/Http/Middleware/PhpEnvironment.php(49):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\PhpEnvironment-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #38 …/vendor/oscarotero/middleland/src/Dispatcher.php(118):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #39 …/index.php(55):  Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest)) #40 {main}

**Comment by fisharebest** [comment]
This is a limitation of your server.

MySQL can set a maximum number of simultaneous connections for each account.

You have reached this limit.


I will see if we can catch this error, and display a more friendly message.

**Comment by AndreasRauhut** [comment]
Yes, a friendly message would be fine, even to the user who is waiting for a result.

But it is surprising me, that I find it more than one time  in the ERR logs.
