### ISSUE TITLE
Cannot create thumbnail Impossible to create the root directory

### ISSUE THREAD

**Issue by AndreasRauhut** [fisharebest/webtrees#3031]
This error persists. Even after replacing the media folder from **../data/** to **../wt-media/** .

`2020-01-29 12:07:22 | error | Cannot  create thumbnail Impossible to create the root directory  "../wt-media/thumbnail-cache/d770f5edbe667c6393ae8668d0af297e/Rauhut/Rauhut  Marie-Delphine2004.jpg". | 87.123.198.186 | Andreas | <none>
-- | -- | -- | -- | -- | --
2020-01-29 12:04:02 | config | Site preference "INDEX_DIRECTORY" set to "../wt-media/" | 87.123.198.186 | Andreas | <none>
2020-01-29 11:56:44 | error | Cannot  create thumbnail Impossible to create the root directory  "../data/thumbnail-cache/67f237e858ca81a8d9d757087a62437d/2015-10-01 fb  Robinson Maupiler.jpg". | 87.123.198.186 | Andreas | <none>
2020-01-29 11:54:04 | edit | Update: INDI 26912I | 87.123.198.186 | Andreas | GAC.ged`

**Comment by fisharebest** [comment]
> Even after replacing the media folder from ../data/ to ../wt-media/ .

The media folder must exist **inside** the data folder.
Therefore it cannot start with `../`
That would put it **outside** the data folder.

Your error "Impossible to create the root directory" is caused when you try to access files outsdie the data folder.

----------

If you want to share a media folder between two webtrees sites, then both sites must have:

* the same data folder - e.g. `../webtrees-data/` (this **can** include `..`)
* the same media folder - e.g.`media/` (this **cannot** include `..`)

Each site will keep have its original `/data` which contains `config.ini.php` and system files such as `cache`, `tmp`, `thumbnail-cache`.

But they will both share the same folder for user data (media files, GEDCOM files, etc.)

**Comment by AndreasRauhut** [comment]
I have taken this into account. 
My data folder is placed at the same level parallel to my webtrees folders root.
The media folder exist inside this data folder.
In the webtrees folder there's still a data folder for the config.ini.php

here two screenshots with the Website preferences
![folder-media](https://user-images.githubusercontent.com/14984533/73368613-94b8b900-42b1-11ea-91cf-2fb939835b71.jpg)

The gedcom preferences
![folder-data](https://user-images.githubusercontent.com/14984533/73368614-94b8b900-42b1-11ea-9360-b7d3b429940d.jpg)

and a part of my servers folders from FileZilla
![ftp-webtrees + media](https://user-images.githubusercontent.com/14984533/73368615-95514f80-42b1-11ea-9a08-8f1d2637a32f.jpg)

**Comment by AndreasRauhut** [comment]
in the tree view wt201 is the home folder of webtrees v2.0.1

wt-media/Ahnen the media folder that I share between the v1.7.16 and v2.0.1 release of webtrees.

www is the folder of my personal homepage

**Comment by AndreasRauhut** [comment]
has been repaired in v2.0.2 . Thanks
