### ISSUE TITLE
Markdown formatting

### ISSUE THREAD

**Issue by Bogiegit** [fisharebest/webtrees#3038]
here is the issue regarding Markdown differences in TEXT and and NOTE.

>I think the difference is source-record versus source-citation.
>If we do it in the citation, we should also do it in the record.

**Comment by ljm42** [comment]
Some more detail: if you add this markdown:
```
|Field|Value|
|---|---|
|Age|79|
|Given Name|Alice|
```
To both the NOTE and TEXT fields of a SOUR, the NOTE will render the markdown properly as a table but the TEXT field does not

https://dev.webtrees.net/demo-dev/tree/demo/source/X243/markdown-test

![image](https://user-images.githubusercontent.com/5751849/73576691-eb4c0180-442f-11ea-9893-310ee7e4c611.png)
