### ISSUE TITLE
Pending changes and search results page is not convenient to use

### ISSUE THREAD

**Issue by DaPoHou** [fisharebest/webtrees#3040]
When I have many pending changes, I click on a record to see the detailed changes. This will leave the pending changes page, and if I want to process other pending changes, I have to cycle: open the pending changes page, leave the pending changes page, and then open the pending changes page.When I have dozens of pending changes, the operation is very tedious and time consuming.

Similarly, on the search results page, when I find someone, there are many similar results, and I need to view them one by one. This will cause me to repeat the search many times, not only wasting server resources but also time. Inconvenient to operate.

So hopefully the links in the above two pages change to open in new window.
(target=_blank)

**Comment by vytux-com** [comment]
Doesn't holding down Shift key when click the link do that?

**Comment by xmlf** [comment]
Of course I know this can be done. However, you cannot ask all users to do this, especially the elderly. Why not open it in a new window instead?

**Comment by wkitty42** [comment]
On 1/31/20 10:31 PM, xmlf wrote:
> When I have many pending changes, I click on a record to see the detailed 
> changes. This will leave the pending changes page, and if I want to process 
> other pending changes, I have to cycle: open the pending changes page, leave the 
> pending changes page, and then open the pending changes page.When I have dozens 
> of pending changes, the operation is very tedious and time consuming.


why not just use the back button to return to the previous page?


-- 
  NOTE: No off-list assistance is given without prior approval.
        *Please keep mailing list traffic on the list unless*
        *a signed and pre-paid contract is in effect with us.*

**Comment by xmlf** [comment]
> On 1/31/20 10:31 PM, xmlf wrote: When I have many pending changes, I click on a record to see the detailed changes. This will leave the pending changes page, and if I want to process other pending changes, I have to cycle: open the pending changes page, leave the pending changes page, and then open the pending changes page.When I have dozens of pending changes, the operation is very tedious and time consuming.
> why not just use the back button to return to the previous page?
> […](#)
> -- NOTE: No off-list assistance is given without prior approval. *Please keep mailing list traffic on the list unless* *a signed and pre-paid contract is in effect with us.*

When viewing a change message on the pending changes page, I sometimes click multiple times on the new page.This is more likely to happen on search results pages, and when I want to determine if an individual is what I'm looking for, I look at his ancestor and offspring information.When more than 5 steps, clicking the back button is not a good idea!

**Comment by vytux-com** [comment]
There are tons of reasons why this new behaviour would be bad... Just google why _blank links are bad. Here is just one site with an explanation https://medium.com/the-metric/links-should-open-in-the-same-window-447da3ae59ba

**Comment by xmlf** [comment]
Website design must first consider user convenience. Think about users' feelings because they are the end users.A user searches individual, and there are more than 20 records on the search results page. What should he do when he wants to click to see the details of each individual in turn?Is it necessary to repeat the search more than 20 times? I don't think any user is willing to do this!

**Comment by vytux-com** [comment]
But webtrees is thinking of the user. Normal user is quite capable of pressing shift while clicking.

Using _blank target disadvantages vision impaired users a lot.

**Comment by xmlf** [comment]
First of all, many users who are not familiar with computer operation do not know how to open a new window at all.
In addition,mobile device users, how do I open a new window? Moreover, mobile device traffic currently accounts for the vast majority.

**Comment by vytux-com** [comment]
Mobile - long click then select new tab etc

Users can be trained very easily, vision impaired users cannot

**Comment by xmlf** [comment]
Any product should be as user-friendly as possible.
If you process more than 20 pending changes on your mobile device in a row, and browse through each individual's information carefully. Or, if there are more than 20 similar results on the search results page, you need to view each individual and their parents and grandfather information one by one.You will understand how inconvenient it is!
Difficult to register users , this is not a good idea.

**Comment by wkitty42** [comment]
On 2/1/20 5:55 AM, xmlf wrote:
> If you process more than 20 pending changes on your mobile device in a row,


personally speaking, i would never attempt that... IMHO, tasks like this are 
much better suited to be done from a real computer on a desk top and not a 
mobile device but that's my 30+ years of network and security administration 
speaking ;)

**Comment by xmlf** [comment]
In fact, more people now use mobile devices to access it. Especially in China, not every home has a desktop computer, but everyone has a smartphone.

**Comment by fisharebest** [comment]
I cannot think of any website that forces links to open in a new tab.

In my opinion, this would be a very bad user experience.


If you want to do this on your own site, you can use code similar to this.
It shows how to open external links in new windows.

https://www.webtrees.net/index.php/en/forum/4-customising/31518-solved-vytux-menu2-open-link-in-new-tab#73761

You could modify the logic so that it matches links in the changes-page, or whatever you choose.

You would add this code to the "CSS and JS" module.
