### ISSUE TITLE
Import custom thumbnails - add wt 2.0.2 to the output table - 2.0.2

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3042]
Import custom thumbnails from webtrees version 1

I would like to see in the table in addition to the current Thumbnail image and the Media file, the thumbnail that we see in wt 2.0.2. The ones for which I need to add the version 1 thumbnail are the ones where the thumbnail is created by wt from the Media file and the thumbnail created by wt cuts the face. Sample: I2843 

![image](https://user-images.githubusercontent.com/5202996/73611618-475b8500-45ec-11ea-930f-4a9d90f43659.png)

**Comment by fisharebest** [comment]
> I need to add the version 1 thumbnail

This table already shows the V1 thumbnail, in the first column…

If the comparison is 98-100%, then it is almost certainly a system-generated thumbnail - which should be deleted.

If it is less, then it is almost certainly a user-generated thumbnail.  You must decide if you want to keep it.
