### ISSUE TITLE
Import custom thumbnails - 404 - 2.0.2

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3045]
Import custom thumbnails from webtrees version 1

I see 404 or 500 for some Media files of Media objects (sample: page 1 - perhaps the file was deleted and the thumbnail has remained in the wt version 1 directories?) and 404 both for the Thumbnail and the Media files for other Media objects (Sample pages: 8 and 9 for 50 items - so far I see that these are for media files that exist for facts, not for individuals or families).

**Comment by fisharebest** [comment]
> perhaps the file was deleted and the thumbnail has remained in the wt version 1 directories?

Yes.  This is what has happened.

You probably want to delete these.
