### ISSUE TITLE
Import custom thumbnails - question - 2.0.2

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3046]
Import custom thumbnails from webtrees version 1

I use the same mail and thumbnail directories and files for two pre wt 2.0.0 production sites and for two wt 2.0.2 test sites.
Suppose I will delete a thumbnail image in a test system. Will the image still exist in the production systems and in the other test system?

**Comment by melizaa** [comment]
I see that the production thumbnails that were added to the test system, have vanished.
I will add them back.

**Comment by fisharebest** [comment]
> Suppose I will delete a thumbnail image in a test system. Will the image still exist in the production systems and in the other test system?

You have one data folder (`/webtrees-data`) which is shared by several sites.

So if you delete an old thumbnail on one site, it will also be deleted on the other.
