### ISSUE TITLE
Multiple media objects in the Favorites do not align to the left

### ISSUE THREAD

**Issue by harrywesterman** [fisharebest/webtrees#3047]
I like to add a couple of pictures (Media Objects) to my Favorites block on the frontpage. But after a picture there is a missing <CRLF>, so the next favorite is not aligned to the left on the next line.
![image](https://user-images.githubusercontent.com/5954481/73613957-1040a000-45fb-11ea-847a-0fba945b1d22.png)

**Comment by fisharebest** [comment]
I think this is fixed in the lastest code.
