### ISSUE TITLE
Include family records in sitemap?

### ISSUE THREAD

**Issue by ljm42** [fisharebest/webtrees#3050]
I see that family pages such as:
https://dev.webtrees.net/demo-dev/tree/demo/family/f29/Prince-Albert-of-Saxe-Coburg-and-Gotha-Queen-Victoria
Have a robots metatags that permits indexing:
`<meta name="robots" content="index,follow">`

Can we add them to the sitemap to help with this?

They could potentially be given a lower priority:
`  <priority>0.3</priority>`
to encourage search engines to focus on individual pages (which have a default priority of 0.5)

**Comment by ljm42** [comment]
Actually, all the tree homepages should probably be listed in the sitemap too

**Comment by fisharebest** [comment]
It seemed unnecessary to add families to the sitemap.

Search engines should be able to find all public family records from the included individuals.

All other record types can exist without being linked to another record.

**Comment by ljm42** [comment]
Oh I always thought the goal was for all valid urls to be in the sitemap?

In the "Google Search Console" they put those in an "Indexed, not submitted in sitemap" category, which seems a bit like saying "tsk tsk" :) 

If you feel strongly it isn't needed (or isn't worth the time to address) then that is fine.

**Comment by fisharebest** [comment]
It is probably quicker to add families than to discuss reasons why they should/not be included...

**Comment by ljm42** [comment]
This is very nice. I was hung up on how to pass in the record priority, this makes total sense. Thanks!
