### ISSUE TITLE
Translations missing in 2.0.2?

### ISSUE THREAD

**Issue by t-karcher** [fisharebest/webtrees#3056]
I was surprised to find some English strings on my otherwise German page after upgrading to 2.0.2. According to https://weblate.iet.open.ac.uk/projects/webtrees/webtrees/de/ , all strings should be translated, but I see "Add a brother", "Add a sister", "Add a sibling", "Add a son" and "Add a daughter" on the relatives tab of the invididual page:

https://familie-dohl.de/index.php?route=%2Ftree%2Ftest%2Findividual%2FX1%2FKarl-MUSTERMANN#tab-relatives

**Comment by fisharebest** [comment]
Already reported (and fixed) earlier today.  #3041

These new texts are now available in the translation server.
