### ISSUE TITLE
FAM record strange behavior

### ISSUE THREAD

**Issue by sevtor** [fisharebest/webtrees#3062]
I have been using pdpGedView earlier and converted to webtrees some years ago. Now I observed something strange in version 2.0.2 but version 1.7.16 has the same behavior. 
It can be seen in the enclosed gedcom file (GFD-mini.ged) where there are two persons and one family with the two persons as husband and wife but no wedding date. If I look at the family in webtrees it looks normal, see gfd-marr-1.png. (The next image shows the raw gedcom of this family, gfd-marr-before.png. ) If I try to add a marriage date the wife is removed from the header but is still mentioned in the raw gedcom, see gfd-marr-error.png. 
![gfd-marr-1](https://user-images.githubusercontent.com/60674592/73872749-96095900-4850-11ea-9429-88704534de3f.png)
![gfd-marr-before](https://user-images.githubusercontent.com/60674592/73872752-96a1ef80-4850-11ea-9c94-13a9b0c67f63.png)
![gfd-marr-error](https://user-images.githubusercontent.com/60674592/73872753-973a8600-4850-11ea-9ca4-9abba4e1fa11.png)
[GFD-mini.zip](https://github.com/fisharebest/webtrees/files/4161485/GFD-mini.zip)

The only difference in GFD-mini-OK.ged in the zip file is that the gedcom for the family has a source added (lines 18-19). 
Any attempt to add a note or a media or a source will have the same result.

**Comment by sevtor** [comment]
I did not dare to accept the change in my original tree but now I tested on the mini-tree. After acceptance the family looks normal again so the error is "only" in the presentation not in the database. 

If the file GFD-mini-OK.ged is used the presentation is correct.

**Comment by sevtor** [comment]
I have several families in my family tree that have ONLY two lines, husband and wife:
0 @X1@
1 HUSB @X2@
1 WIFE @X3@

All changes to such families trigger this problem.
When I add a third line with anything (CHIL, NOTE, CHAN, ...) the behavior is normal

**Comment by fisharebest** [comment]
This bug will have been present for many years.
I am surprised it was not noticed before.

It only affects the display of data.  There is no corruption.

Simple to fix...

**Comment by sevtor** [comment]
I have always accepted my own changes directly earlier. Then the error never pops up.
