### ISSUE TITLE
Sitemap.xml throws an error

### ISSUE THREAD

**Issue by harrywesterman** [fisharebest/webtrees#3065]
I'm using v2.0.2, but my sitemap.xml link just gives an error:
https://www.stamboomwesterman.net/index.php?route=%2Fsitemap.xml

syntax error, unexpected 'type' (T_STRING) …/resources/views/modules/sitemap/sitemap-index-xml.phtml:16
#0 …/app/View.php(282): Fisharebest\Webtrees\View->render()
#1 …/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make('modules/sitemap...', Array)
#2 …/app/Module/SiteMapModule.php(271): view('modules/sitemap...', Array)
#3 …/app/Cache.php(59): Fisharebest\Webtrees\Module\SiteMapModule->Fisharebest\Webtrees\Module\{closure}()
#4 …/vendor/symfony/cache/LockRegistry.php(99): Fisharebest\Webtrees\Cache::Fisharebest\Webtrees\{closure}(Object(Symfony\Component\Cache\CacheItem), true)
#5 …/vendor/symfony/cache/Traits/ContractsTrait.php(88): Symfony\Component\Cache\LockRegistry::compute(Object(Closure), Object(Symfony\Component\Cache\CacheItem), true, Object(Symfony\Component\Cache\Adapter\FilesystemAdapter), Object(Closure), NULL)
#6 …/vendor/symfony/cache-contracts/CacheTrait.php(68): Symfony\Component\Cache\Adapter\AbstractAdapter->Symfony\Component\Cache\Traits\{closure}(Object(Symfony\Component\Cache\CacheItem), true)
#7 …/vendor/symfony/cache/Traits/ContractsTrait.php(95): Symfony\Component\Cache\Adapter\AbstractAdapter->doGet(Object(Symfony\Component\Cache\Adapter\FilesystemAdapter), '5d33eb6e08d0e90...', Object(Closure), 1, Array, NULL)
#8 …/vendor/symfony/cache-contracts/CacheTrait.php(30): Symfony\Component\Cache\Adapter\AbstractAdapter->doGet(Object(Symfony\Component\Cache\Adapter\FilesystemAdapter), '5d33eb6e08d0e90...', Object(Closure), 1, Array)
#9 …/app/Cache.php(60): Symfony\Component\Cache\Adapter\AbstractAdapter->get('5d33eb6e08d0e90...', Object(Closure))
#10 …/app/Module/SiteMapModule.php(273): Fisharebest\Webtrees\Cache->remember('sitemap.xml', Object(Closure), 209600)

**Comment by fisharebest** [comment]
This issue has already been fixed.  Here are the code changes.

0800f024dcbfd93c798d3e6b5c48d18f68e79593
a9b216cea106cf1196df0c1c08a9fa5bd71780c2

It is caused by the PHP setting `short_open_tag`.

This setting is deprecated, and will be removed in a future version of PHP.

Unless it is needed for another website on your server, you are advised to disable it.
