### ISSUE TITLE
Question re resources folder

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3069]
When producing a release, why are the folders `resources/css` & `resources/js` included when everything in there is compiled and placed in the public folder from which it is accessed?

**Comment by fisharebest** [comment]
You are right.  We don't need these.  I'll remove them from the build process.

**Comment by fisharebest** [comment]
There is also `public/css/vendor.css` that needs removing...

**Comment by ddrury** [comment]
I know I keep banging on about this, but if you use sass to combine all the components that make up vendor.css you can junp straight to the minified version therefore vendor.css is never created.

**Comment by fisharebest** [comment]
When I get time to read up on sass, I'm sure I'll make the switch.
