### ISSUE TITLE
Individuals list privacy problem

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3072]
Individuals are being shown on the list of individuals when privacy dictates they shouldn't be.

E.G One person exists in the database named Jones who is still living, but even when logged out, Jones appears on the 'J' list

**Comment by fisharebest** [comment]
This is already known, and can't realistically be solved.

The same applies to place names.

If you had 10000 private joneses, then we'd need to make 10,000 privacy calculations - which would make the page unusable.


I have looked at caching the privacy calculations.  However, the relationship privacy feature makes the cache invalidation logic so time-consuming that it becomes slower than not having a cache.
