### ISSUE TITLE
Notes associated with a related person not showing

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#3074]
When adding a related person to for instance a PROP tag, a note can be added but the person’s page does not show this note.

Sample GEDCOM:
`1 PROP Schoorl D 1251
2 DATE FROM ABT 1955 TO ABT 1961
2 PLAC Schoorl, Noord-Holland, Nederland
2 ADDR Postweg 2
2 SOUR @S277@
3 DATA
4 TEXT Legger SCH01 art.3038
2 _ASSO @I5@
3 RELA buyer
3 NOTE Verenigd met D695`

(moved from https://github.com/webtrees/webtrees.github.io/issues/13)

**Comment by godzil3** [comment]
Same issue occur with media object, note is visible in database but is omitted in view and gedcom editor

**Comment by fisharebest** [comment]
> Same issue occur with media object

`ASSO` links are permitted to contain notes.

<img width="620" alt="Screen Shot 2020-02-11 at 08 03 46" src="https://user-images.githubusercontent.com/2306088/74219559-0d057e00-4ca5-11ea-997e-d5e3de4c1da8.png">


`OBJE` links are not permitted to contain notes.

<img width="613" alt="Screen Shot 2020-02-11 at 08 03 14" src="https://user-images.githubusercontent.com/2306088/74219535-fb23db00-4ca4-11ea-911f-69a541eea725.png">

**Comment by godzil3** [comment]
Got it, but i can add a note, and can't only edit them. I use note fild for all my medias, what about them? should i move them somwhere?

**Comment by mpwt** [comment]
hi godzil3, but you can add notes to the multimedia record (not to the multimedia link):

MULTIMEDIA_RECORD:= 
n @XREF:OBJE@ OBJE

   +1 FILE <MULTIMEDIA_FILE_REFN> 
      +2 FORM <MULTIMEDIA_FORMAT> 
         +3 TYPE <SOURCE_MEDIA_TYPE> 
      +2 TITL <DESCRIPTIVE_TITLE> 
   +1 REFN <USER_REFERENCE_NUMBER>
      +2 TYPE <USER_REFERENCE_TYPE> 
   +1 RIN <AUTOMATED_RECORD_ID> 
   **+1 <<NOTE_STRUCTURE>>** 
   +1 <<SOURCE_CITATION>> 
   +1 <<CHANGE_DATE>>

**Comment by godzil3** [comment]
i think i'm not explained what i mean

When i create new fact and there create media object, i enter text in Note field. once i accept the changes i can see this note in fact frame
![obraz](https://user-images.githubusercontent.com/45084859/74747347-bb3d9480-525e-11ea-9cc7-cd57773de46f.png)

When i go to this media object site (../tree/drzewo/media/X16/..) there is no field where i can edit them
![obraz](https://user-images.githubusercontent.com/45084859/74747553-0657a780-525f-11ea-9454-2e306969196a.png)
In edit the raw GEDCOM i also don't see notes
![obraz](https://user-images.githubusercontent.com/45084859/74747654-2e470b00-525f-11ea-8494-a5d680d198a8.png)

I can see this note in database in wt_media table and related entry
![obraz](https://user-images.githubusercontent.com/45084859/74748048-ccd36c00-525f-11ea-918d-ee9b7da23c3a.png)

How i can edit this note?

**Comment by fisharebest** [comment]
This is a duplicate of #1284
