### ISSUE TITLE
Place hierarchy - Events occuring in 

### ISSUE THREAD

**Issue by ro-la** [fisharebest/webtrees#3076]
After clicking on "View table of events occurring in Berkshire, England" you are redirected to the most top level with a message "No results found". You cann se it on the demo site: https://dev.webtrees.net/demo-dev/module/places_list/List/demo?place_id=719

I have changed the place in the birth record in https://dev.webtrees.net/demo-dev/tree/demo/individual/i30/Catherine-Elizabeth-Middleton#tab-personal_facts to "Berkshire, England" so there should be listed this one record. When there is no record linked to this level, then it should stay on this level and report "No entries"

I think the best way would be when entering a level where thera are events exactly on this level this records should be displayed automaticaly (now works only for the lowest level) and the button should display the list like in 1.7.16. (all records with this level AND all with lower levels)

I have started this discussion here https://www.webtrees.net/index.php/en/forum/help-for-2-0/34079-behavior-of-view-table-of-events-occurring-in and I know Gregs answer (and I disagree because there are so many other possibilities to generate big lists in webtrees). So this is my second (and last) attempt on this. For me it would be very helpful also a hint, where and what to change in source to have back the functionality from 1.7.16. so I cann add it to my own upgrade list.

**Comment by fisharebest** [comment]
> I know Gregs answer

That was just my first guess.  I had not looked at the code.

This is not a change in behaviour.  It is just a bug.
