### ISSUE TITLE
Searching fails on certain privacy settings

### ISSUE THREAD

**Issue by mirono** [fisharebest/webtrees#3077]
Version: 1.7.16
An individual and his family are set in privacy settings as "All facts and events" and "Name" defined as "Show to users".
In the general search page search for the surname and check "Individuals" and "Families".
The search returns a blank page, and the logs show:

2020-02-11 20:02:26 error /var/www/tree.ophir.org.il/html/app/Individual.php:1157 Trying to access array offset on value of type null
#0 /app/Individual.php:1157 ErrorException("Trying to access array offset on value of type null")
#1 /app/GedcomRecord.php:633 addName()
#2 /app/Family.php:367 getAllNames()
#3 /app/GedcomRecord.php:764 getAllNames()
#4 /app/Functions/FunctionsDb.php:477 getFullName()
#5 unknown:unknown Fisharebest\Webtrees\Functions\{closure}()
#6 /app/Functions/FunctionsDb.php:485 array_filter()
#7 /app/Controller/SearchController.php:252 searchFamilyNames()
#8 /app/Controller/SearchController.php:195 generalSearch()
#9 /search.php:24 __construct()
77.137.114.80 <none> The Ophir Family
2020-02-11 20:02:26 search Type: General
Query: abourmad 77.137.114.80 <none> The Ophir Family

**Comment by fisharebest** [comment]
Are there any pending changes?  Does it help if you accept them?
Have you used the "check for errors" option in the control panel?

This error suggests corrupt, invalid (or unexpected) GEDCOM data somewhere.

**Comment by fisharebest** [comment]
@mirono - did you see my previous comment?

I will need your assistance to identify the problem.
