### ISSUE TITLE
Pedigree Map not obeying "Do not use maps" option

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3080]
Control panel - Map - Map provider can set an option "Do not use maps" but the Pedigree map module has no code to take account of it.

(The place hierarchy & places tab do obey it)

Would it be better to give the place hierarchy module it's own local option and leave the others permanently enabled?

**Comment by fisharebest** [comment]
Perhaps there is a more general solution...?

Many modules have certain requirements.  For example, the reports require the `php-xml` library, the fanchart requires the `php-gd` library.

So, if the module interface included a function along the lines of `areRequirementsMet()`, then we could suppress ones that won't work.

The pedigree map would then need to declare a dependency on there being a mapping provider.

**Comment by ddrury** [comment]
> function along the lines of areRequirementsMet()

Sounds like a good idea, however, if the place hierarchy is to retain it's current functionality then it would still need an option to enable/disable map usage

**Comment by fisharebest** [comment]
> If the place hierarchy is to retain it's current functionality then it would still need an option to enable/disable map usage

You mean this?

https://github.com/fisharebest/webtrees/blob/2.0.2/app/Http/Controllers/PlaceHierarchyController.php#L89

Or is there something else?

**Comment by ddrury** [comment]
Yep, that's what I meant

**Comment by ddrury** [comment]
BTW, I've implemented a method of providing different map providers using modules, but I don't want to create a pull request yet, particularly if you fundamentally disagree with the way I've gone about things, howabout I give a summary of what I've done on slack and we could go from there?

**Comment by fisharebest** [comment]
Fixed by  #4166
