### ISSUE TITLE
function app() and the IoC container

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#3085]
in functions.php, `app()` is documented as "Get the IoC container, or fetch something from it."

I find it a bit surprising that using app e.g.

`$factories = app(GedcomRecordFactories::class);`

does not return a singleton instance from the container, but instead creates a new object every time, which is often not helpful. Is that intentional? Singletons have to be created explicitly via
```
if (!Application::getInstance()->bound(GedcomRecordFactories::class)) {
  Application::getInstance()->singleton(GedcomRecordFactories::class);
} 
```

Should this perhaps be the default logic when using `app()` (without additional parameters)?

**Comment by fisharebest** [comment]
> Is that intentional?

We are using the laravel container - and this is how is works.

>  Singletons have to be created explicitly via

There is  a simpler syntax to create a singleton

```
app()->instance(GedcomRecordFactoryInterface::class, new MyGedcomRecordFactory())
```

Factories are not usually singletons - because they have no state or resources.

You'd generally use bind your implementation to an interface.  e.g.

```
app()->bind(GedcomRecordFactoryInterface::class, `MyGedcomRecordFactory`.::class)
```

Now, when a method type-hints `GedcomRecordFactoryInterface`, the container will create a `MyGedcomRecordFactory`.

**Comment by ric2016** [comment]
> We are using the laravel container - and this is how is works.

But we could implement app() in functions.php differently, or at least have another method there which returns singletons. I guess my question is, is there at all some use of app() within the code where we actually must not obtain a singleton?

A factory may not have been the best example (but why shouldn't a factory have state? In my case, it does - for caching). Using another example, `app(Statistics::class)`: What is the point of not using a singleton Statistics here? Every call constructs a new Statistics object, which seems like unnecessary overhead.

**Comment by fisharebest** [comment]
> Every call constructs a new Statistics object, which seems like unnecessary overhead.

Creating objects in PHP is very fast.  My guess is that this overhead is so small, you can not measure it reliably.

> but why shouldn't a factory have state?

Global state is generally bad.  It means the output of a function depends on not
just the inputs to the function, but also *every previous call to the package*.

Stateless classes are easier to refactor, easier to test, easier to debug.

> In my case, it does - for caching

Caching should be done using the cache object.  (Most of the similar "caches" have already been converted).

It makes testing easier.  I can set up a "null" cache.

**Comment by ric2016** [comment]
> Global state is generally bad.

Except when it's explicitly required.
When we register a custom view from a custom module, we want to change the global state. In my original example, I want to register a custom GedcomRecordFactory so that calls to GedcomRecord::getInstance elsewhere (there are several of these) return the proper object. So I explicitly need to have state here. And so on ...

> Caching should be done using the cache object.

ok, but we have to be aware that in several cases, caching isn't optional! I.e. it won't work with a "null" cache. We had this issue in #2830 and we also have this in GedcomRecord: Disabling the internal caching there leads to "Fatal error: Nesting level too deep - recursive dependency?" errors, because records are initialized in an endless loop (from INDI to FAM to INDI ...) Just something to keep in mind when this is refactored.

**Comment by fisharebest** [comment]
The pattern I imagine is this.

We have a new middleware `RegisterFactories`, which sets the default factories.

```
app()->bind(FooFactoryInterface::class, FooFactory::class);
app()->bind(BarFactoryInterface::class, BarFactory::class);
...
app()->bind(GedcomRecordFactoryInterface::class, GedcomRecordFactory::class);
```

The code would type-hint the interface, and the container would provide the concrete object.

--------

Then, in your module, you would simply replace the binding with your own singleton 

```
function boot() {
  app()->instance(GedcomRecordFactoryInterface::class, new MyGedcomRecordFactory());
}
```

There is no need to change `app()`.  You just tell it how to create a `GedcomRecordFactoryInterface` object.

**Comment by ric2016** [comment]
(note: further discussion in #3091, should probably be continued here)

**Comment by ric2016** [comment]
How do we want to continue here?

You suggested to create gedcom records via all custom modules, like this

```
foreach ($modules as $module) {
    $record = $module->createRecord($record);
}
```

This would require the GedcomRecordFactory to access all enabled modules. This dependency cannot be injected when constructing the GedcomRecordFactory, unless the modules are initialized earlier. So the GedcomRecordFactory has to obtain the list of modules via the Service Locator pattern (e.g. from the container). I don't see how this is fundamentally different from obtaining the actual factories themselves, as currently implemented in the 'development' branch.

Ultimately, as long as the modules are initialized after other components, while at the same time affecting those other components in some way, I don't think there is a way around the Service Locator pattern - we just cannot inject all (final) dependencies in the constructors of the components.

**Comment by fisharebest** [comment]
> I don't think there is a way around the Service Locator pattern

I think you are right.

I have created a simple "Factory Service Locator" class - `app/Factory.php`.

Factories are registered with `Factory::individual($factory)`,
and used  as `Factory::individual()->...`

Are you happy with this approach?  Is there a better way?

**Comment by ric2016** [comment]
This works for me. There is no longer a way to register a custom factory apparently (a SharedPlaceFactory in my case), but I can work around that.

I think it's good to have the "Factory Service Locator" separate from the app container, that makes things clearer. We should probably clean up remaining service-locator-like uses of the app container, but that isn't urgent.

I would be happy to use this in the next release!

**Comment by fisharebest** [comment]
> I would be happy to use this in the next release!

OK.  I will update the master branch to use the new factories and run some more tests.

**Comment by fisharebest** [comment]
FYI, the develop branch has now been merged into master.

Question:

webtrees has support for obscure record types that are not used.  e.g. `SUBN`.

It would be trivial (copy/paste) to add similar support for `_LOC`.

These would be treated the same as any other unknown record type.

Then, your modules would extend/replace this type, and also its factory.

I will need to do this at some point in time.  Doing it now seems preferable.

The only difficult part is choosing a name for the class.  `Location` is already used, and I do not like `Shared...`

Your thoughts?

**Comment by fisharebest** [comment]
PS - I am happy to rename the existing `Location` class - but I would need a name for it ;-)

**Comment by ric2016** [comment]
I had the same difficulty, that's why I ended up with 'Shared Place'.
Maybe rename the existing `Location` to `PlaceLocation`, which is already the name of the respective table?

Basic support for _LOC as described would be great - If you don't mind that it's a custom tag?

**Comment by fisharebest** [comment]
> If you don't mind that it's a custom tag?

webtrees recognises (rather than supports) many of the frequently-used custom tags.

This is no different.

PS - It would be really helpful if you have a GEDCOM file containing some _LOC records that you can share with me for testing...
