### ISSUE TITLE
Search engine crawl language error

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#3089]
The family tree preferences have been set to Simplified Chinese, but Google Spider still crawls in English.

**Comment by xmlf** [comment]
https://github.com/fisharebest/webtrees/blob/f307429b21f5956fe3c70f5afdc20e1394d89e56/app/Http/Middleware/UseLanguage.php#L100
https://github.com/fisharebest/webtrees/blob/50b23b0d007a750c2e92c88071f2224cb81db10e/vendor/fisharebest/localization/src/Locale.php#L110

**Comment by fisharebest** [comment]
We have a language setting per tree.

In webtrees 1, we identified the tree first, and so could select the language.

In webtrees 2, we select the language before we know the tree.

Perhaps we should change this from a tree-setting to a site-setting.

**Comment by xmlf** [comment]
> We have a language setting per tree.
> 
> In webtrees 1, we identified the tree first, and so could select the language.
> 
> In webtrees 2, we select the language before we know the tree.
> 
> Perhaps we should change this from a tree-setting to a site-setting.

If so, there is no flexibility in setting the language for each tree. Assume that there are two trees a and b, and you want to set the default language to Chinese and English, respectively.
