### ISSUE TITLE
Commits to .css not involved in webtrees-master

### ISSUE THREAD

**Issue by jpretired** [fisharebest/webtrees#3090]
Some commits apply also to .css files but these are not involved in webtrees-master.zip.

**Comment by fisharebest** [comment]
Which one?

**Comment by jpretired** [comment]
I meant Fix #1209 which applied also to resources/css/_base.css.

**Comment by fisharebest** [comment]
That should have gone in.

In any case, I just made another update, which should have re-built all the CSS files.
