### ISSUE TITLE
v2 Fatal error

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3092]
I guess since recent language change

XHR response received in Control panel - user administration.

Fatal error: Class fisharebest\localization\language\languagedv wasn't preloaded in /mnt/d/Server/html/webtrees-2.0/vendor/fisharebest/localization/src/Language/LanguageDv.php on line 16

**Comment by fisharebest** [comment]
I have no problems selecting / using Divehi (dv).

Does the file `LanguageDv.php` look OK?  Not corrupt/empty/missing?

The only place I can find this error message in in the PHP source code,
so no clues as to what might cause it.
https://github.com/php/php-src/blob/master/Zend/zend_compile.c#L1130

**Comment by ddrury** [comment]
Hm,
restarting php74-fpm fixed it!!
