### ISSUE TITLE
option to define another basefolder

### ISSUE THREAD

**Issue by Gunnar-GO** [fisharebest/webtrees#3095]
Is it possible to use another basefolder for 

/data
/media
?

So an pure upgrade/intall would be only extract the files and moving the config file.
Also it would be more secure, since ged-files will be saved with name-date. So they can set out of reach from web.

**Comment by fisharebest** [comment]
This already exists?

Control panel -> Website preferences

![Screenshot 2020-02-27 at 19 49 53](https://user-images.githubusercontent.com/2306088/75481151-7d491a80-599a-11ea-8b38-7aa5f8009c79.png)
