### ISSUE TITLE
I see 1 Adar data more than once in the Calendar and in the Yahrzeiten and Upcoming events blocks. wt 2.0.2

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3097]
see for instance I7623. I see her Hebrew death data several times for 1 Adar 5683. In the Yahrzeiten block, the Yahrzeit date is 28 February 2020-8 March 2020 for the same Hebrew date. I show data of 10 days.

![BlockMultiples](https://user-images.githubusercontent.com/5202996/75544564-ef6a3f80-5a2c-11ea-8600-8c325dbb6eff.jpg)

**Comment by melizaa** [comment]
I see Rachel Lea also in the daily calendars of 29/2/2020 - 24/3/2020.
I see her also on several days in the Hebrew calendar.

I do not see the person who died on 4 ADR 5678 in the daily calendar of 4 ADR 5679, 5680, etc.

**Comment by fisharebest** [comment]
See #3406
