### ISSUE TITLE
Time of birth (minutes)

### ISSUE THREAD

**Issue by kexuebin** [fisharebest/webtrees#3098]
Chinese people divide a day into 12 Chinese zodiac (时辰), each 时辰 is 2 hours. Chinese genealogy records a person's birth such as: 子时, my question:Webtrees don't control the number of minutes of birth. Is that ok? Let me input Chinese characters 子时.

**Comment by xmlf** [comment]
Time input format, allowing time periods to be entered. E.g. 23: 00-01: 00, 05: 00-07: 00

**Comment by fisharebest** [comment]
The `TIME` field is specified on page 63 of the GEDCOM specification.

> TIME_V ALUE:= [ hh:mm:ss.fs ]
> The time of a specific event, usually a computer-timed event, where: hh = hours on a 24-hour clock
> mm = minutes
> ss = seconds (optional)
> fs = decimal fraction of a second (optional)

webtrees enforces the format here:
https://github.com/fisharebest/webtrees/blob/2.0.2/app/Functions/FunctionsEdit.php#L582

You could change this - but in my opinion it is wrong to use the `TIME` field for something that is not a time.

**Comment by fisharebest** [comment]
Also - it is wrong to add `TIME` to `BIRT:DATE`.

webtrees supports it because some other applications create this data.
