### ISSUE TITLE
Replace "add a child" by "add a boy"& "add a girl"

### ISSUE THREAD

**Issue by sleebooth** [fisharebest/webtrees#3103]
Webtrees V2.0.2 Enhancement

In the process of creating a new individual from the Family Navigator's link to the family display's green "add a child", it is easy to overlook setting the individual's sex in v2. The line for Sex with the buttons just doesn't stand out. So I end up having to edit the Sex after creating the individual, if I notice he/she is sex-less.

I suggest replacing "add a child" by "add a boy"& "add a girl" or maybe offering child, boy & girl to incorporate an individual of unknown sex.

**Comment by sleebooth** [comment]
But how would you then cope with either "unknown" or non-binary?

**Comment by vytux-com** [comment]
The valid options would be male / female / unknown as those are the only options available in the spec

**Comment by fisharebest** [comment]
At present, there are three options `U`/`M`/`F` - `U` is selected by default.

If you forget to select `M` or `F`, you will get `U`.

A simple change to to leave all options unselected.

If you forget to select a sex, the browser will not let you submit the form.

**Comment by sleebooth** [comment]
Maybe a solution is to move the Sex line to the top, immediately after "Relationship to Parents"?
