### ISSUE TITLE
Census assitant - clicking on head clears data

### ISSUE THREAD

**Issue by ro-la** [fisharebest/webtrees#3106]
Clicking on the "head" icon deletes every row, but the selected individual.

When this is realy "working as designed", then please add a warning. Something like this: "Do you realy wont to clear all data from the note?" In v 1 it didnt work this way, so at least a warning would be great.

A second issue - adding an empty row is realy not very intuitive. In pervious version there was an special button for it.

Thanks 

Ladislav

**Comment by fisharebest** [comment]
Perhaps we do not need this button?

It is simple to start again by deleting all the rows.

The first row is automatically the "head of household".
