### ISSUE TITLE
develop-Branch: Factories do not handle pending changes correctly

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#3111]
In the [develop](https://github.com/fisharebest/webtrees/tree/develop) branch, the new factories (FamilyFactoryInterface etc) do not handle pending changes correctly. This leads to confusing messages such as "The changes to “… … + … …” have been accepted.", e.g. after accepting a changed fact of an individual.

The reason for this message is that a family record is created for (in this case) an individual xref, because:

1. the main gedcom record factory tries all factories in turn, until a non-null rcord is returned (GedcomRecordFactory line 65) (this should maybe be handled differently anyway?).
2. First, an attempt is made to create a family record, via FamilyFactoryInterface. This succeeds in case of pending changes _for any xref type_, because FamilyFactory never returns null for an xref with pending changes (the other factories are implemented similarly).

One solution would be to have each factory check the type of the pending change, and return null unless it's the type actually handled by the respective factory.

**Comment by fisharebest** [comment]
> have each factory check the type of the pending change

This is necessary, but it is not sufficient.

The code in `GedcomRecordFactory::make()` should also check `$gedcom`.

If this is not null, then we must select the correct factory.

At present, it will create a Family record using GEDCOM for a different type of record.

----------

Also, I have some other ideas to allow modules to register Factory objects.

**Comment by ric2016** [comment]
Will work on the develop-branch be continued, or is it effectively a dead branch? I know there are a lot of other issues, but I think we'll have to address the open issues for developers of custom modules at some point.

**Comment by fisharebest** [comment]
Paused, rather than suspended.

In some places, we use dependency injection for the factory objects.

In other places, we use get them from the laravel container (`app(Factory::class)`) - effectively global variables...

I am not 100% comfortable with the second of these.

**Comment by ric2016** [comment]
I agree - I don't quite like the second case either, anyway not as it currently is handled. For future reference, some thoughts about this here: https://github.com/fisharebest/webtrees/pull/3091#issuecomment-592987669.

**Comment by fisharebest** [comment]
> The code in GedcomRecordFactory::make() should also check $gedcom.
> If this is not null, then we must select the correct factory.

Looking through the code, this situation does not actually occur.  To have $gedcom, we would need to be querying the `wt_changes` table directly, and we only do that for the recent changes module, which looks for accepted changes.
