### ISSUE TITLE
Suggestions for first names and surnames 

### ISSUE THREAD

**Issue by AndreasRauhut** [fisharebest/webtrees#3113]
When entering firstnames and surnames I miss the opportunity to choose from a list of suggestions.

![new_child_wt2](https://user-images.githubusercontent.com/14984533/76257958-f413cc80-6252-11ea-9152-4a1751418021.jpg)

In v1.7.16 I saw which names already were used in the database and the right orthography. Additionnally this prevents me often to enter double individuals.

![new_child_wt1](https://user-images.githubusercontent.com/14984533/76257961-f4ac6300-6252-11ea-97d6-dd49262109eb.jpg)

Would this need to make a great modification to the code ? (btw. I can choose when entering places)

**Comment by fisharebest** [comment]
This was removed for privacy reasons.

The list in 1.7 includes names for private individuals.

**Comment by AndreasRauhut** [comment]
Ok, I understand. An individual may be private. The private information consists of the unique combination of firstname and lastname together. This might to have been hidden of curious eyes.

But the firstnames in question in the lists are showing only either firstname or surname. In this form they are totally anonymized.

A name is used many times for private and for non private individuals.

**Comment by fisharebest** [comment]
> A name is used many times for private and for non private individuals.

Or it may be used only once...

My father's has an unusual given name - and with an unusual spelling.
I believe he is the only person with this given name in the world.
If it appeared in a list of given names, it would uniquely identify him.

If the autocomplete just worked for one name (e.g. "André", instead of "André Anonciade René"), then it would be OK.

But would this be useful?

**Comment by AndreasRauhut** [comment]
Yes, of course you're right. 

 I didn't think that this (General Data Protection Regulation <GDPR>) one day will even enter in leasure activity as genealogy.

The live before this extreme reglemantation of privacy was easier for all of us.

**Comment by hartenthaler** [comment]
would it be possible to reactivate the old behavior if the user has admin rights? In this case privacy shouldn't be a problem.

**Comment by AndreasRauhut** [comment]
Thank you!
