### ISSUE TITLE
Suggestions for media folder names 

### ISSUE THREAD

**Issue by AndreasRauhut** [fisharebest/webtrees#3114]
I regret the loss of history when selecting the folder by adding / uploading new media.
In V2.0.2 it is only a changeless list.

In V1.7.16 the most often used media folders are up in the list and the user quickly can reuse it.

Please give me hope, that this functionality will be reastablished in a later version of v2.0.x

**Comment by fisharebest** [comment]
It is not helpful to say "like webtrees 1.7" or "like some other application".

I haven't used webtrees 1.7 for years.
On my own site, I keep all my media in one folder.

It is better to describe what you actually want.

> In V1.7.16 the most often used media folders are up in the list

How does this work, exactly?
Are the folders sorted by timestamp instead of alphabetically?

**Comment by AndreasRauhut** [comment]
Let me try to describe it in an other way.
I'm classifying my media by place in structured folders and subfolders. One reason is the time to look up for too much files in a single folder. I made bad experiance by storing too much drawings in one single folder. Another thing is the ability to easily extract files by their name and foldername.

Sorry but I still use v1.7.16 and I found it genious and self-explaining how foldernames were presented in a way which is very useful for daily use. I agree that my way of entering media is not the only one. But I insert a media each time I insert an event that has to be documented.

I would like to have the foldernames to be sorted descending by the number of times they were used. I'm not used to read code to explain you how this worked in v1.7.16. 

But I suppose that each folder has a counter that is used to sort and present the foldernames in this manner.

And I don't understand the way that the list of folders is actually created. I see no order and it's never changing. see screenshot:
![media-folder](https://user-images.githubusercontent.com/14984533/76261899-51ac1700-625b-11ea-81ee-5e3c0b08606c.jpg)

**Comment by fisharebest** [comment]
Thanks for the screen dump.

I think your browser is adding its own suggestions **in front of** the webtrees suggestions.

I can recreate this behaviour.  In this screenshot, you can see the browser suggestions in front of the webtrees suggestions.

Note that the webtrees suggestions are sorted alphabetically

I can add some extra markup to disable the browser's auto-suggestion.

-----

<img width="389" alt="Screenshot 2020-03-14 at 16 48 45" src="https://user-images.githubusercontent.com/2306088/76686528-df995080-6613-11ea-9d9c-6ce1a3d90d63.png">

**Comment by AndreasRauhut** [comment]
Thank you for hiding in v2.0.3 the browsers suggestions. 

I see, when I type some characters of the foldername, that webtrees makes suggestions and shows me the existing folders containing the typed characters. That's fine. But it takes time to type the foldername and wait that webtrees shows it up.

But sorry, the previous behavior was more paractic.
