### ISSUE TITLE
V2 sidebar clumsy relationship naming convention

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3115]
See attached; in this instance William married both women (not together!) so If this is deliberate I don't like it - what was wrong with Husbands wife?

![dump](https://user-images.githubusercontent.com/104515/76641473-95e43380-6549-11ea-9108-f69d521d067d.jpg)

**Comment by t-karcher** [comment]
You didn't specify a marriage event for the second family, so the naming (correctly) implies they were never married. Add the marriage event (date is optional), add a divorce event with either the exact date or "BEF <second marriage date>", and the naming should change to "partner's ex-wife".

**Comment by ddrury** [comment]
Nope sorry, both marriage type specified

**Comment by fisharebest** [comment]
The code that creates relationship names only has access to the family record when there is a path-length of 1.

So, we can display the permutations of ex-wife, partner, husband, etc easily for immediate family.

But for longer paths, we only have structure of the relationship, which is just a list of path-components such as `partner`, `child`, `parent`, `sibling`.

So, it is not an easy fix.

There are other issues with the relationship-naming code - particularly the way it handles different relationships in different languages.  e.g. the meaning of "4th cousin" is different in English, Polish, Italian, etc.

This will get looked at as part of a larger change.

**Comment by ddrury** [comment]
Do you want to close this or leave it as a reminder?

**Comment by HRN65** [comment]
In my tree I se partner's partner instead of the correct partner's wife or partner's husband
