### ISSUE TITLE
The nickname '' or "" are missing in the chart and report selection boxes - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3117]
![image](https://user-images.githubusercontent.com/5202996/76700737-2abe6c80-66c3-11ea-9fde-609271faddd0.png)

**Comment by melizaa** [comment]
![image](https://user-images.githubusercontent.com/5202996/76700871-7f161c00-66c4-11ea-9b38-7a8d00c160ad.png)

**Comment by fisharebest** [comment]
The same is true for "starred" names.

`<select>` HTML elements do not allow formatted text, and so we lose the formatting for nicknames and prefered names.

**Comment by melizaa** [comment]
Also commas in names are lost.
We do not see ", ', underlines and commas in PDF and HTML reports.

We do not see Thai letter in PDF reports.
![image](https://user-images.githubusercontent.com/5202996/77160450-0215e880-6ab0-11ea-898e-a3991495d513.png)

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
