### ISSUE TITLE
No +/- boxes on v2.x - impossible to expand/collapse sources/notes by clicking on them

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3121]
While working fine in webtrees 1.7.16, there is a problem with the [+]/[-] boxes on v2.x:
- in Edge, IE, Palemoon and Waterfox: **no** +/- boxes on localhost and on [demo site](https://dev.webtrees.net/demo-dev/tree/demo/individual/i1/Queen-Elizabeth-II)
- in Firefox, Brave, Chrome and Vivaldi: **no** +/- boxes on localhost, **only** on [demo site](https://dev.webtrees.net/demo-dev/tree/demo/individual/i1/Queen-Elizabeth-II)

Without +/- boxes it's impossible to expand/collapse sources/notes by clicking on them.

Tested on two PCs with Win10 and on a VM with fresh installed Win 10.

**Comment by ddrury** [comment]
The comment in the forum discussion

> content is officially defined to work in ::before and ::after pseudo elements only

is not strictly true according to https://developer.mozilla.org/en-US/docs/Web/CSS/content scroll down to the "Element replacement" example

**Comment by fisharebest** [comment]
> according to https://developer.mozilla.org/en-US/docs/Web/CSS/content

Thanks.  I stopped reading when I got to the line

> Applies to ::before and ::after pseudo-elements

It seems that recent versions of Edge are OK.  It is just older version (and IE) that fail.

https://caniuse.com/#feat=mdn-css_properties_content_element_replacement

**Comment by TheDutchJewel** [comment]
> It seems that recent versions of Edge are OK. It is just older version (and IE) that fail.

If I open https://developer.mozilla.org/en-US/docs/Web/CSS/content#Element_replacement in Edge (latest version) I see **no** picture, just the text:
> Mozilla (replaced).
Same with IE and Waterfox.

In Palemoon I get this error:
> (Error code: SEC_ERROR_BAD_SIGNATURE)

In Firefox, Brave, Chrome and Vivaldi I see [the picture](https://mdn.mozillademos.org/files/12668/MDN.svg).

**Comment by fisharebest** [comment]
> Edge (latest version)

Which version number?

**Comment by TheDutchJewel** [comment]
44.18362.449.0

**Comment by ddrury** [comment]
Do you still have adguard installed? if so is it the app or just the browser extension? I have the app version 7.3 (build 3048, CL 1.5.163) installed which is working fine.
Do you have any other proxy installed
BTW My Edge is Version 80.0.361.69 (windows 10)

**Comment by fisharebest** [comment]
> 44.18362.449.0

The chart  at caniuse.com uses the internal (browser engine) version number.

This is Edge 18.  Since then, there is Edge 79 and Edge 80.

https://en.wikipedia.org/wiki/Microsoft_Edge

79 onwards should work.

**Comment by ddrury** [comment]
And caniuse.com doesn't list either Palemoon or Waterfox so if you plan on using either of them it may be worth checking with the developer that they support the content css property

**Comment by TheDutchJewel** [comment]
>Do you still have adguard installed? if so is it the app or just the browser extension? I have the app version 7.3 (build 3048, CL 1.5.163) installed which is working fine.

I use the same app, version 7.3.3048.0, which is working fine. At first I thought the problem was caused by AdGuard, but it wasn't.

>Do you have any other proxy installed

No.

>This is Edge 18. Since then, there is Edge 79 and Edge 80.

I used the default Windows 10 Edge with EdgeHTML engine. The one you mentioned is the new Edge with Blink engine. I installed this new Edge version and tried it with webtrees 2.0.3 and now the +/- boxes are visible and they work fine.

So here's the updated issue:
While working fine in webtrees 1.7.16, there is a problem with the +/- boxes on v2.x:
- in Edge with EdgeHTML engine, IE, Palemoon and Waterfox: **no** +/- boxes visible on localhost and on [demo site](https://dev.webtrees.net/demo-dev/tree/demo/individual/i1/Queen-Elizabeth-II)
- in Firefox, Brave, Chrome and Vivaldi: **no** +/- boxes visible on localhost, **only** on [demo site](https://dev.webtrees.net/demo-dev/tree/demo/individual/i1/Queen-Elizabeth-II)
- in Edge with Blink engine: +/- boxes visible on localhost and on [demo site](https://dev.webtrees.net/demo-dev/tree/demo/individual/i1/Queen-Elizabeth-II)

**Comment by fisharebest** [comment]
> And caniuse.com doesn't list either Palemoon or Waterfox

PaleMoon is a fork of Firefox 38-ESR (May 2015)
WaterFox is a fork of Firefox 52-ESR (March 2017)

Both have a market share of 0.005%

Since then there are two more ESR releases (60 and 68).

**Comment by TheDutchJewel** [comment]
What about Firefox, Brave, Chrome and Vivaldi?
**no +/- boxes visible on localhost**, only on [demo site](https://dev.webtrees.net/demo-dev/tree/demo/individual/i1/Queen-Elizabeth-II)

**Comment by fisharebest** [comment]
> no +/- boxes visible on localhost, only on demo site

I cannot reproduce this.

local/remote makes no difference for me.

**Comment by ddrury** [comment]
what is your local server setup

**Comment by fisharebest** [comment]
I am using VirtualBox to run a Windows virtual machine.  The virtual machine uses XAMPP.

**Comment by ddrury** [comment]
Sorry the question was aimed at @TheDutchJewel. Not that I can see how only some browsers could be affected!

**Comment by fisharebest** [comment]
I can understand old browsers not working.  caniuse.com matches exactly what we have observed.

I can't see a connection between rendering bugs and local/remote domains.

**Comment by TheDutchJewel** [comment]
I use webtrees v1.7.16 and 2.0.3 on XAMPP portable x64 v7.3.15.

**Comment by ddrury** [comment]
Don't know about Greg, but I'm clutching at straws, any error messages in ether the server or webtrees logs? If you look at the browser developer tools any error messages in the console tab or error responses in the network tab when loading the page?

I've attached an image of things to look at using the inspector tab. This image was produced using firefox on the demo site and the class you (hopefully) see could be either icon-plus or icon-minus
![demo](https://user-images.githubusercontent.com/104515/77246078-a6686e00-6c1b-11ea-88fa-9011736ea849.jpg)

**Comment by TheDutchJewel** [comment]
Problem solved: it seems that I have to login to webtrees in each browser to see the +/- boxes...
After login, webtrees shows the +/- boxes in Firefox, Brave, Chrome and Vivaldi.

**Comment by vytux-com** [comment]
That would be one of the privacy settings, to make notes / sources private to visitors

**Comment by TheDutchJewel** [comment]
Makes sense. Thank you!
