### ISSUE TITLE
We do not see titles or footers in the PDF reports - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3122]
![image](https://user-images.githubusercontent.com/5202996/77158739-941bf200-6aac-11ea-8779-09752c80e28e.png)

![image](https://user-images.githubusercontent.com/5202996/77158781-abf37600-6aac-11ea-8e1e-435dba77f64e.png)

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
