### ISSUE TITLE
Disable Custom Modules during upgrade? 

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#3123]
Shouldn't the upgrade tool disable custom modules, or at least give a warning that custom mudules could prevent the upgraded site to run?
Just upgraded from 2.02 to 2.03 with vesta modules installed. After upgrade I had a white screen without any obvious errors. Took me sometime to find out the cause.

**Comment by ric2016** [comment]
I think this would be useful in general.

Two things to note:
I expect further upgrades to be less critical in this regard, once the webtrees core code settles further. Optimally, we shouldn't have minor version changes in case of relevant changes in the core code. (In this case, my Vesta modules didn't follow the recommendations e.g. regarding module traits, so webtrees isn't to blame here)

It's always a good idea to check before upgrading if there are new versions of custom modules available, this check is integrated in the control panel. Maybe the mechanism could even be enhanced to indicate whether an upgrade of a custom module is _required_ for a specific webtrees version?

**Comment by fisharebest** [comment]
> Shouldn't the upgrade tool disable custom modules,

The upgrade script doesn't load any modules, so it should run sucessfully.
This problem happened *after* the upgrade.

> give a warning that custom mudules could prevent the upgraded site to run?

We already catch most errors in modules.
However, the more serious PHP errors cannot be caught.

> In this case, my Vesta modules didn't follow the recommendations e.g. regarding module traits, so webtrees isn't to blame here

The system of interfaces and traits was designed to allow module functionality
to be developed without breaking existing modules.
The documentation [modules_v4/README.md](https://github.com/fisharebest/webtrees/blob/master/modules_v4/README.md) makes this clear:

> For each module interface that you implement, you must also use the corresponding trait.
> If you don't do this, your module may break whenever the module interface is updated.

Finally,

> After upgrade I had a white screen without any obvious errors.

Your server is configured with the PHP setting `display_errors = Off`.
If this was set to `On`, you'd have seen an error message.

I think I can detect this case, and force the error to be displayed.
