### ISSUE TITLE
The website log shows:SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry

### ISSUE THREAD

**Issue by DaPoHou** [fisharebest/webtrees#3129]
This is an error recorded in the website log during browsing(not edit).

I have checked the pl_id field in the wt_placelocation table, and there is only one in 1880 and 1908.

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;1908&#039; for key &#039;PRIMARY&#039; (SQL: insert into `wt_placelocation` (`pl_id`, `pl_place`, `pl_parent_id`, `pl_level`, `pl_lati`, `pl_long`, `pl_icon`, `pl_zoom`) values (1908, 新洁村, 565, 2, , , , 2)) …/vendor/illuminate/database/Connection.php:664 #0 …/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection-&gt;runQueryCallback(&#039;insert into `wt...&#039;, Array, Object(Closure)) #1 …/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection-&gt;run(&#039;insert into `wt...&#039;, Array, Object(Closure)) #2 …/vendor/illuminate/database/Connection.php(411): Illuminate\Database\Connection-&gt;statement(&#039;insert into `wt...&#039;, Array) #3 …/vendor/illuminate/database/Query/Builder.php(2646): Illuminate\Database\Connection-&gt;insert(&#039;insert into `wt...&#039;, Array) #4 …/app/Location.php(97): Illuminate\Database\Query\Builder-&gt;insert(Array) #5 …/app/Cache.php(59): Fisharebest\Webtrees\Location-&gt;Fisharebest\Webtrees\{closure}() #6 …/vendor/symfony/cache/Adapter/ArrayAdapter.php(62): Fisharebest\Webtrees\Cache::Fisharebest\Webtrees\{closure}(Object(Symfony\Component\Cache\CacheItem), true) #7 …/app/Cache.php(60): Symfony\Component\Cache\Adapter\ArrayAdapter-&gt;get(&#039;e3673bc485ad36e...&#039;, Object(Closure)) #8 …/app/Location.php(102): Fisharebest\Webtrees\Cache-&gt;remember(&#039;location-\xE6\x96\xB0\xE6\xB4\x81...&#039;, Object(Closure)) #9 …/app/Location.php(77): Fisharebest\Webtrees\Location-&gt;id() #10 …/app/Cache.php(59): Fisharebest\Webtrees\Location-&gt;Fisharebest\Webtrees\{closure}() #11 …/vendor/symfony/cache/Adapter/ArrayAdapter.php(62):`

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;1880&#039; for key &#039;PRIMARY&#039; (SQL: insert into `wt_placelocation` (`pl_id`, `pl_place`, `pl_parent_id`, `pl_level`, `pl_lati`, `pl_long`, `pl_icon`, `pl_zoom`) values (1880, 大刘庄村, 478, 4, , , , 2)) …/vendor/illuminate/database/Connection.php:664 #0 …/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection-&gt;runQueryCallback(&#039;insert into `wt...&#039;, Array, Object(Closure)) #1 …/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection-&gt;run(&#039;insert into `wt...&#039;, Array, Object(Closure)) #2 …/vendor/illuminate/database/Connection.php(411): Illuminate\Database\Connection-&gt;statement(&#039;insert into `wt...&#039;, Array) #3 …/vendor/illuminate/database/Query/Builder.php(2646): Illuminate\Database\Connection-&gt;insert(&#039;insert into `wt...&#039;, Array) #4 …/app/Location.php(97): Illuminate\Database\Query\Builder-&gt;insert(Array) #5 …/app/Cache.php(59): Fisharebest\Webtrees\Location-&gt;Fisharebest\Webtrees\{closure}() #6 …/vendor/symfony/cache/Adapter/ArrayAdapter.php(62): Fisharebest\Webtrees\Cache::Fisharebest\Webtrees\{closure}(Object(Symfony\Component\Cache\CacheItem), true) #7 …/app/Cache.php(60): Symfony\Component\Cache\Adapter\ArrayAdapter-&gt;get(&#039;4cfcab0e55dac9b...&#039;, Object(Closure)) #8 …/app/Location.php(102): Fisharebest\Webtrees\Cache-&gt;remember(&#039;location-\xE5\xA4\xA7\xE5\x88\x98...&#039;, Object(Closure)) #9 …/app/Location.php(132): Fisharebest\Webtrees\Location-&gt;id() #10 …/app/Location.php(163): Fisharebest\Webtrees\Location-&gt;details() #11 …/app/Module/PlacesModule.php(172): Fisharebest\Webtrees\Location-&gt;latitude() #12 …/app/Module/PlacesModule.php(102): Fisharebest\Webtrees\Module\PlacesModule-&gt;getMapData(Object(Fisharebest\Webtrees\Individual)) #13 …/app/Http/RequestHandlers/IndividualPage.php(409): Fisharebest\Webtrees\Module\PlacesModule-&gt;hasTabContent(Object(Fisharebest\Webtrees\Individual)) #14 [internal function]: Fisharebest\Webtrees\Http\RequestHandlers\IndividualPage::Fisharebest\Webtrees\Http\RequestHandlers\{closure}(Object(Fisharebest\Webtrees\Module\PlacesModule), &#039;places&#039;) #15 …/vendor/illuminate/support/Arr.php(611): array_filter(Array, Object(Closure), 1) #16 …/vendor/illuminate/support/Collection.php(549): Illuminate\Support\Arr::where(Array, Object(Closure)) #17 …/app/Http/RequestHandlers/IndividualPage.php(410): Illuminate\Support\Collection-`

**Comment by fisharebest** [comment]
I think this is a timing error...

Two visitors view a page with a new placename at the same time.

Both try to create a new database entry for the place.  One wins.  One loses.

This should be a one-off error.  It is safe to ignore.
