### ISSUE TITLE
Baidu Spider Failed to Crawl to Website

### ISSUE THREAD

**Issue by DaPoHou** [fisharebest/webtrees#3131]
Error：
`HTTP/1.1 406 Not Acceptable`

https://github.com/fisharebest/webtrees/blob/c686c3e2a3929500fe120791452b1dd552698d0a/app/Http/Middleware/BadBotBlocker.php#L219

After debugging, there are only IP addresses and no host records.
` $host = gethostbyaddr($ip);`
Many spider IP in Baidu did not set host, so the above error occurred.
I think sogou has the same problem.

**Comment by fisharebest** [comment]
See https://help.baidu.com/question?prod_id=99&class=0&id=3001

> 5. How can I know the crawling is from Baiduspider?
> The hostname of Baiduspider is *.baidu.com or *.baidu.jp. Others are fake hostnames.

**Comment by DaPoHou** [comment]
In fact, Baidu has not fully complied with this standard.
Host only got the IP address, not host.
I also tested google and bing, which are normal.
