### ISSUE TITLE
In the Korean messege.po file of Webtrees, most of the parts used in Korea have been translated. However, it is not approved because there have been errors since the last version. I am not a programmer. I can't find what is the problem. If there is a wrong LOGIC, please help us fix it.

### ISSUE THREAD

**Issue by ramu98** [fisharebest/webtrees#3142]
In the Korean messege.po file of Webtrees, most of the parts used in Korea have been translated. However, it is not approved because there have been errors since the last version. I am not a programmer. I can't find what is the problem. If there is a wrong LOGIC, please help us fix it.

_Originally posted by @ramu98 in https://github.com/fisharebest/webtrees/pull/3141#issuecomment-604981121_

**Comment by fisharebest** [comment]
1) The updates in #3141 may be lost.

This is because there was a merge conflict on the translation server.

Please upload .PO files to https://translate.webtrees.net

2) The translations are stored in `messages.po`.  webtrees uses `messages.php`.

If you delete  `messages.php`, it will be re-created automatically (if PHP has write-permission to this folder).

**Comment by ramu98** [comment]
The messege.php file in use by the final modification is to find and fix the part that was difficult to find in the po file. It is difficult to find the edited part of the po file in the php file and edit it again, so a zip file containing the php translation file is attached. As of now, Korean translation files merged from translate.webtreees.com have some errors. The php file in the zip file I attached to the previous article is a more accurate translation.

**Comment by ramu98** [comment]
다시 한번 번역을 다시 한 php가 포함된 zip파일을 첨부합니다.
[ko.zip](https://github.com/fisharebest/webtrees/files/4413595/ko.zip)

**Comment by fisharebest** [comment]
See #3152

We can only accept translations
* at https://translate.webtrees.net
* updated .PO files.

Note: you can upload/download .PO files at https://translate.webtrees.net

We cannot use these .PHP files.
