### ISSUE TITLE
Display more meaningful hyperlink text when using @I0001@ shortcode

### ISSUE THREAD

**Issue by clivej** [fisharebest/webtrees#3144]
When I use the shortcode in a note, for example `@I0001@ `webtrees creates a hyperlink to that individual which is great, but it would be better/more useful to display the persons name or maybe even custom text.  For example:

`@Uncle John@I0010@` which would display the text Uncle John to the user, and link to record I0010

or

`@Smith Family@F0035@`

**Comment by fisharebest** [comment]
We currently show the name of the record as a tooltip.

<img width="506" alt="Screenshot 2020-03-28 at 14 15 15" src="https://user-images.githubusercontent.com/2306088/77825019-97dbf400-70fe-11ea-804c-1e2631cc4dad.png">

We could show the name of the record as the link text.
