### ISSUE TITLE
Language Korean Alternative fix

### ISSUE THREAD

**Issue by ramu98** [fisharebest/webtrees#3152]
As you informed me, I applied Korean to the server I run. I tried to fix the messy.po file or the awkward part of the translation from transerate.webtrees.org directly from messege.php.
A much more natural translation has been made.

Comparing what was understood in messege.po to what was applied
There were some misunderstandings and translations.

Korean translation of transerate.webtrees.org, which is not yet synchronized
This is a more incorrect translation than the file you are attaching now.

I don't know how to convert it to php-> po file.
I will attach Korean translation messege.php to the attached zip file.
[ko.zip](https://github.com/fisharebest/webtrees/files/4406919/ko.zip)

I hope the developer can apply it so that others can use it
Please.

**Comment by fisharebest** [comment]
> I don't know how to convert it to php-> po file.

This is not possible.

The translations are stored in the .PO file.

We use https://translate.webtrees.net to edit the .PO files.

We convert .PO to .PHP when we create a new version of webtrees.
