### ISSUE TITLE
Data fix - problem maybe not bug

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3153]
Add Married names.

Male born Smith, adopted by Jones when an infant. Therefore alway known as Jones.

After he's married, the data fix offers both Smith and Jones as married names for the wife. I don't really want to be offered Smith but I can't see a way to avoid it

Any ideas?

**Comment by fisharebest** [comment]
> I don't really want to be offered Smith but I can't see a way to avoid it

This data-fix is full of assumptions - most of which are wrong.

I don't really like it, I would never use it myself, and I would always advise against its use.

Maybe just remove it?

**Comment by ddrury** [comment]
> Maybe just remove it?

> I don't really like it, I would never use it myself, and I would always advise against its use.

That's a pretty good reason to remove it, however I wonder if removing it would cause complaints of "it worked for me - why remove it?"
Nevertheless I'd support removing it and maybe reintroduce a better version sometime in the future.

**Comment by fisharebest** [comment]
This data-fix was removed a while back.
