### ISSUE TITLE
Import custom thumbnails

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#3155]
Thanks a lot for the Data fixes. Converting _PRIM tags to GEDCOM 5.5.1 saved me from a lot of work!
Now I'm in the process of importing custom thumnails from 1.7, and is wondering:
Would it be possible to add checkboxes and bulk action to delete thumbnails that are not needed? I have more than 10000....
Alternatively, would it be safe to delete the data/media/thumbs folder on the server (after import of the few custom thumbs)?

**Comment by fisharebest** [comment]
Did you actually create any / many custom thumbnails for 1.7?

If not, just delete all the `/thumbs/` folders in your media folder.

**Comment by HRN65** [comment]
I have a few custom thumnails, like crops from family photos. 
Maybe I just browse through and import the few, before deleting the folder then.
