### ISSUE TITLE
Control Panel warning 'The PHP extension “gd” is not installed.'

### ISSUE THREAD

**Issue by kpine** [fisharebest/webtrees#3156]
I just switched from gd to ImageMagick after upgrading from 2.0.2 to 2.0.3 because of thumbnail generation errors. When going to the control panel I am now presented with a warning that gd is missing. (The thumbnails are working again).

![image](https://user-images.githubusercontent.com/791794/78326610-acb9ec80-752f-11ea-931c-224c3cbb7542.png)

According to the [FAQ](https://webtrees.net/faq/thumbnails/), one can install _either_ gd or ImageMagick. If that is correct, and I don't need gd, should a warning only be displayed when  neither are installed?

**Comment by fisharebest** [comment]
GD is required for the fanchart.

**Comment by kpine** [comment]
Indeed it is. If both are installed, will it use imagemagick for the thumbnails?

**Comment by fisharebest** [comment]
> If both are installed, will it use imagemagick for the thumbnails?

Yes.  The fanchart code can only use `GD`

**Comment by kpine** [comment]
Ok, I've got both installed now and everything looks good, thanks.
