### ISSUE TITLE
Errors in search/replace

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#3159]
![Bug1](https://user-images.githubusercontent.com/5910274/78456074-8f337280-7656-11ea-9cd6-1a56bb1f4fd1.jpg)
![Bug2](https://user-images.githubusercontent.com/5910274/78456093-99ee0780-7656-11ea-8b14-270e4b215feb.jpg)
I used search and replace several times (update all) with no problem, but then got the syntax error in the "bug1" image.  The image is not from the first error, which had the record type set to SOUR.
I changed the record type to INDI and got the type error in the "bug2" image.
Then I exited search/replace and clicked it again in the tree menu.
Pasted in the search string again (copied from a birth record in an INDI data page) and typed in the replace.  Clicked update all and got "bug1" again.

**Comment by WGroleau** [comment]
With "Canada, Charlevoix, Québec, Canada, Québec, Canada" and a long delay, the errors did not occur.  So I'm not sure how to reproduce.

**Comment by fisharebest** [comment]
Both these errors suggest an error in the XHR responses.

Can you follow these instructions, to see if you get a helpful error message?

https://webtrees.net/faq/xhr/

**Comment by WGroleau** [comment]
For reasons unknown, Firefox has been misbehaving on my MacBook for some time.
Don't have a Windows installation in my house currently.  Been considering switching an idle iMac to Linux.
Deleted Chrome and anything else offered by NSA's biggest competition.
I'll see whether I can figure out an equivalent method with Safari or Brave.
Was able to get the syntax error with "New York USA" as search string and "New York, USA" for replacement.

**Comment by WGroleau** [comment]
Couldn't find anything useful in Safari.

Updated to the latest version of Firefox, and then …

Instead of Safari's
SyntaxError: The string did not match the expected pattern.
Firefox displayed
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Request:
Request URL:https://unigen.us/admin/data-fix/HHH/fix-search-and-replace/update-all?search=New+York+USA&replace=New+York%2C+USA&method=exact&case=i&type=INDI
Request Method:POST
Remote Address:[2604:4f00::3:3:2795:1]:443
Status Code:
200
Version:HTTP/2
Referrer Policy:same-origin

Response:
Nothing to do.

**Comment by fisharebest** [comment]
> Instead of Safari's
> SyntaxError: The string did not match the expected pattern.
> Firefox displayed
> SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

There errors mean that the server response was not valid JSON format.

Which would happen if the server sent an error message instead.

If you can capture the error response using the developer tools, it would really help.

Without an error message, it is difficult to proceed.

**Comment by WGroleau** [comment]
I tried to get the details with `tcpdump -vv -s 500`, but I guess that's not the right way to get the payload.  I don't see how to get it with Safari.  Is it possible a comma in one of the strings needs to be escaped? 
![SyntaxError](https://user-images.githubusercontent.com/5910274/81584817-1d8ec880-9368-11ea-924c-935bb5d4f10e.jpg)

**Comment by fisharebest** [comment]
If you are using safari, go to Preferences, Advanced, and enable "Show develop menu".

Then use `CMD-OPTION-I` to enable them, and follow the instructions at https://webtrees.net/faq/xhr/

**Comment by fisharebest** [comment]
PS - I got your email with the account details, but they aren't working for me...

**Comment by WGroleau** [comment]
That's the page I looked at before.  It doesn't mention Safari.  I've always had the tools activated on both.  Firefox wouldn't do it before, but I just updated to the latest version and was able to do what it said—except for the last step, as nothing appeared to click on "response"
![No_XHR](https://user-images.githubusercontent.com/5910274/81888993-5e98ff80-9557-11ea-9a6f-4bd713107b39.jpg)

**Comment by fisharebest** [comment]
The line that shows "200 POST unigen.us" is a response.  click on it to see the details.

**Comment by WGroleau** [comment]
"Response" only said "Nothing to do"
![bug5](https://user-images.githubusercontent.com/5910274/81963039-6beed200-95c9-11ea-9868-b2747ba3ce26.jpg)

**Comment by fisharebest** [comment]
OK - I get it now.

I missed a couple of words at the end of your initial report.

The errors happens when you click "update all" - not when you click "search".

**Comment by fisharebest** [comment]
...and more specifically, it happens when you click update all - and there is nothing to update.

I had always assumed people would click search first, to see what would updated...
