### ISSUE TITLE
Using Baidu webmaster tool to simulate spider crawling, it always prompts failure of crawling, and 406 error appears.

### ISSUE THREAD

**Issue by kexuebin** [fisharebest/webtrees#3162]
Using Baidu webmaster tool to simulate spider crawling, it always prompts failure of crawling, and 406 error appears. This problem only appears in version 2.0.3.Baidu has been leading to a decline in the number of pages included.

**Comment by fisharebest** [comment]
Show me the 406 error message in the apache logs.

**Comment by kexuebin** [comment]
> 在apache日志中显示406错误消息。

After repair, baidu stationmaster tool, simulation spider crawls still 406.

**Comment by fisharebest** [comment]
Show me the apache logs.

**Comment by kexuebin** [comment]
> 
> 
> Show me the apache logs.

36.110.199.177 - - [11/Apr/2020:22:23:04 +0800] "GET / HTTP/1.1" 406 14 "-" "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)"
123.125.71.33 - - [11/Apr/2020:22:23:09 +0800] "GET / HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Linux;u;Android 4.2.2;zh-cn;) AppleWebKit/534.46 (KHTML,like Gecko) Version/5.1 Mobile Safari/10600.6.3 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html\xA3\xA9"
46.229.168.145 - - [11/Apr/2020:22:23:39 +0800] "GET /tree/ke/contact?to=%E7%AE%A1%E7%90%86%E5%91%98&url=https%3A%2F%2Fzisun.org%2Ftree%2Fke%2Fcontact%3Fto%3D%25E7%25AE%25A1%25E7%2590%2586%25E5%2591%2598%26url%3Dhttps%253A%252F%252Fyanhuang.zisun.org%252Ftree%252Fke%252Fcontact%253Fto%253D%2525E7%2525AE%2525A1%2525E7%252590%252586%2525E5%252591%252598%2526url%253Dhttps%25253A%25252F%25252Fyanhuang.zisun.org%25252Ftree%25252Fke%25252Fcontact%25253Fto%25253D%252525E6%2525259F%252525AF%252525E5%252525AD%252525A6%252525E5%25252585%252525B5%252526url%25253Dhttps%2525253A%2525252F%2525252Fyanhuang.zisun.org%2525252Ftree%2525252Fke%2525252Fcontact%2525253Fto%2525253D%25252525E6%252525259F%25252525AF%25252525E5%25252525AD%25252525A6%25252525E5%2525252585%25252525B5%25252526url%2525253Dhttps%252525253A%252525252F%252525252Fyanhuang.zisun.org%252525252Ftree%252525252Fke%252525252Fcontact%252525253Fto%252525253D%2525252525E6%25252525259F%2525252525AF%2525252525E5%2525252525AD%2525252525A6%2525252525E5%252525252585%2525252525B5%2525252526url%252525253Dhttps%25252525253A%25252525252F%25252525252Fwww.zisun.org%25252525252Fmodule%25252525252Fplaces_list%25252525252FList%25252525252Fke%25252525253Fparent%2525252525255B0%2525252525255D%25252525253D%252525252525E5%25252525252594%25252525252590%252525252525E6%25252525252598%252525252525AD%252525252525E5%252525252525AE%25252525252597%252525252525E5%252525252525A4%252525252525A9%252525252525E4%252525252525BD%25252525252591%252525252525E4%252525252525BA%2525252525258C%252525252525E5%252525252525B9%252525252525B4%252525252525E8%252525252525BF%25252525252581%252525252525E5%252525252525B1%25252525252585%252525252525E6%252525252525B0%252525252525B8%252525252525E6%25252525252598%252525252525A5%252525252525E5%2525252525258E%252525252525BF%252525252525E5%2525252525258D%25252525252593%252525252525E5%2525252525259F%25252525252594%252525252525E6%2525252525259F%252525252525AF%252525252525E7%252525252525BD%25252525252597%252525252525E6%2525252525259D%25252525252591 HTTP/1.1" 406 14 "-" "Mozilla/5.0 (compatible; SemrushBot/6~bl; +http://www.semrush.com/bot.html)"
46.229.168.138 - - [11/Apr/2020:22:23:51 +0800] "GET /tree/ke/contact?to=%E7%AE%A1%E7%90%86%E5%91%98&url=https%3A%2F%2Fzisun.org%2Ftree%2Fke%2Fcontact%3Fto%3D%25E6%259F%25AF%25E5%25AD%25A6%25E5%2585%25B5%26url%3Dhttps%253A%252F%252Fyanhuang.zisun.org%252Ftree%252Fke%252Fcontact%253Fto%253D%2525E6%25259F%2525AF%2525E5%2525AD%2525A6%2525E5%252585%2525B5%2526url%253Dhttps%25253A%25252F%25252Fyanhuang.zisun.org%25252Ftree%25252Fke%25252Fcontact%25253Fto%25253D%252525E6%2525259F%252525AF%252525E5%252525AD%252525A6%252525E5%25252585%252525B5%252526url%25253Dhttps%2525253A%2525252F%2525252Fwww.zisun.org%2525252Ftree%2525252Fke%2525252Fcontact%2525253Fto%2525253D%25252525E7%25252525AE%25252525A1%25252525E7%2525252590%2525252586%25252525E5%2525252591%2525252598%25252526url%2525253Dhttps%252525253A%252525252F%252525252Fwww.zisun.org%252525252Ftree%252525252Fke%252525252Fdescendants-tree-3%252525252FX500 HTTP/1.1" 406 14 "-" "Mozilla/5.0 (compatible; SemrushBot/6~bl; +http://www.semrush.com/bot.html)"
46.229.168.151 - - [11/Apr/2020:22:24:07 +0800] "GET /tree/ke/contact?to=%E7%AE%A1%E7%90%86%E5%91%98&url=http%3A%2F%2Fzisun.org%2Ftree%2Fke%2Fcontact%3Fto%3D%25E7%25AE%25A1%25E7%2590%2586%25E5%2591%2598%26url%3Dhttps%253A%252F%252Fyanhuang.zisun.org%252Ftree%252Fke%252Fcontact%253Fto%253D%2525E7%2525AE%2525A1%2525E7%252590%252586%2525E5%252591%252598%2526url%253Dhttps%25253A%25252F%25252Fyanhuang.zisun.org%25252Ftree%25252Fke%25252Fcontact%25253Fto%25253D%252525E7%252525AE%252525A1%252525E7%25252590%25252586%252525E5%25252591%25252598%252526url%25253Dhttps%2525253A%2525252F%2525252Fyanhuang.zisun.org%2525252Ftree%2525252Fke%2525252Findividual%2525252FX939%2525252F%25252525E6%252525259F%25252525AF%2525252520%25252525E5%25252525B5%25252525A9%25252525E5%2525252585%25252525AC HTTP/1.1" 406 14 "-" "Mozilla/5.0 (compatible; SemrushBot/6~bl; +http://www.semrush.com/bot.html)"

**Comment by fisharebest** [comment]
> `36.110.199.177 - - [11/Apr/2020:22:23:04 +0800] "GET / HTTP/1.1" 406 14 "-" "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)"`
> `123.125.71.33 - - [11/Apr/2020:22:23:09 +0800] "GET / HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Linux;u;Android 4.2.2;zh-cn;) AppleWebKit/534.46 (KHTML,like Gecko) Version/5.1 Mobile Safari/10600.6.3 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html\xA3\xA9"`

The first is blocked (406)
The second is allowed (302)

Test these IP addresses...

```
php > echo gethostbyaddr('36.110.199.177');
36.110.199.177
php > echo gethostbyaddr('123.125.71.33');
baiduspider-123-125-71-33.crawl.baidu.com
```

This tells us that the first is invalid, and the second is OK.

So, this is correct.  Invalid Baidu is blocked.  Valid Baidu is accepted.

**Comment by kexuebin** [comment]
Re clean test, a simulated computer Baidu spider crawling, a simulated mobile Baidu spider crawling, the results are as follows:
36.110.199.49 - - [11/Apr/2020:23:07:41 +0800] "GET / HTTP/1.1" 406 14 "-" "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)"
36.110.199.47 - - [11/Apr/2020:23:07:43 +0800] "GET / HTTP/1.1" 406 14 "-" "Mozilla/5.0 (Linux;u;Android 4.2.2;zh-cn;) AppleWebKit/534.46 (KHTML,like Gecko) Version/5.1 Mobile Safari/10600.6.3 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html\xA3\xA9"

**Comment by wkitty42** [comment]
On 4/11/20 11:10 AM, nuxiong wrote:
> Re clean test, a simulated computer Baidu spider crawling, a simulated mobile 
> Baidu spider crawling, the results are as follows:
> 36.110.199.49 - - [11/Apr/2020:23:07:41 +0800] "GET / HTTP/1.1" 406 14 "-" 
> "Mozilla/5.0 (compatible; Baiduspider/2.0; 
> +http://www.baidu.com/search/spider.html)"
> 36.110.199.47 - - [11/Apr/2020:23:07:43 +0800] "GET / HTTP/1.1" 406 14 "-" 
> "Mozilla/5.0 (Linux;u;Android 4.2.2;zh-cn;) AppleWebKit/534.46 (KHTML,like 
> Gecko) Version/5.1 Mobile Safari/10600.6.3 (compatible; Baiduspider/2.0; 
> +http://www.baidu.com/search/spider.html\xA3\xA9"

as greg wrote previously, 36.110.199.49 is not a valid baidu spider IP 
address... webtrees is blocking it because it blocks fake spiders and those 
pretending to be spiders... it would also block googlebot if it pretended to be 
the baidu spider...
