### ISSUE TITLE
Level 1 Media objects

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#3166]
Going from 1.7 to 2.0 i got a bit puzzled by the amount of individuals that had level 1 media objects attached to them.
I've alway added media to corresponding facts/events, and only added personal photos as level 1.
Looking closer, I find these media objects added as both level 1 AND level 2 media, and they are attached to facts/events that are typically copied from one indi to another.
I'm not able to reproduce this in 2.0, nor has it occurred in recent added individuals in 1.7, and checking the Last changes dates, the entries seem to be 5 to 10 years old.

I guess there have been changes to media handeling. Could it be in previous versions that copying facts/events with media objects attached to them, also added the media object as level 1?

**Comment by fisharebest** [comment]
If you selected the "keep media objects" option when you imported a GEDCOM file, then it would create these extra level 1 links.


This option is designed for a very specific use-case.

1) you edit your data offline in an application that does not support media (and will ignore/delete media in imported data)
2) you also add media objects in webtrees
3) you want to re-import your data (from the application that has deleted media) back into a tree in webtrees (where you also added media).
4) webtrees will then convert all existing media links into level 1 links, and merge them into the new tree.

My guess is that you selected this option accidently while importing.

**Comment by HRN65** [comment]
Thank you Greg!
Wouldn't "keep media objects" affect all objects? I found 100-200 out of thousands, and only one or two per affected individual. From what I could see, fact/event had been copied from one indi (father) to other family members (wife and children), and only wife and children had level 1 media objects.
Anyway, this is not a big issue, and I think I've found and deleted all erroneous level 1 objects.
I was jus curious, and always want to keep my gedcom "clean"

**Comment by fisharebest** [comment]
> Wouldn't "keep media objects" affect all objects?

Maybe this option was used in the past, when you had a much smaller tree?

That's the only thing in the code that might possible cause this problem.

If the problem was reproducable, then it can be fixed.  But trying to guess what may have happened in the past is harder.  Especially since an older version of the code would be used at the time.

If this happens again, raise another ticket and we can investigate.  But I don't think there is anything we can do for this one.
