### ISSUE TITLE
Duplicated 1 CHAN Records

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3168]
I have a few INDI records in my tree which have more than one "1 CHAN" records. Both "1 CHAN" records look ok, but it is not ok that a CHAN record is added if there is already one.

**Comment by fisharebest** [comment]
What are the timestamps in the two CHAN records?

**Comment by hartenthaler** [comment]
One was with 2 minutes distance, another one with several months between (for the first one: both CHAN records are from webtrees 2, for the second one : one was from webtrees 1.7 and the second one from webtrees 2).

**Comment by hartenthaler** [comment]
there was no error log entry and no message. I found the problem by using a GEDCOM validator.

**Comment by fisharebest** [comment]
Look in the changes log in the control panel.

Show me the old/new versions of the GEDCOM when the extra CHAN record was created.

**Comment by hartenthaler** [comment]
![Screenshot (62)](https://user-images.githubusercontent.com/6324175/78926880-2b69d900-7a9e-11ea-89f0-7de99ef40c55.png)
![Screenshot (63)](https://user-images.githubusercontent.com/6324175/78926886-2d339c80-7a9e-11ea-8510-673af8c34a36.png)

Now I found an example (it just happend some minutes ago). See screen shots.
- there was an old record (last changed 9 APR 2014)
- changed source
- changed _TODO
- deleted a SOUR record without accepting the pending changes before
- accepted the pending changes with the result that the last deleted SOUR record is there again and now there are two CHAN records
