### ISSUE TITLE
[Bug][v2] Weird weddings statistics

### ISSUE THREAD

**Issue by Salokyn** [fisharebest/webtrees#3170]
Hi,

Since v2.0. I get erroneous weddings statistics:

![image](https://user-images.githubusercontent.com/11018648/78978005-5b09f700-7b19-11ea-9c9a-83bdc4d69411.png)

**Comment by Salokyn** [comment]
Autres = Others
Mariage par siècle = Weddings by century
Nombre = Number

**Comment by fisharebest** [comment]
Thanks.  This has already been reported here: #3154
