### ISSUE TITLE
exif module is required, but not listed on control panel as missing php module

### ISSUE THREAD

**Issue by mvdw** [fisharebest/webtrees#3174]
Since release 2.0.3 (I guess), the php "exif" module is required, but not listed on the control panel as a missing php module (if it is missing) as some other modules are, such as gd and intl.

The effect of a missing exif module is that all thumbnails are shown as a red background with a "500" written on it.

**Comment by fisharebest** [comment]
This was fixed a few weeks ago, in 565f3f1786a59f78e87b1f8e299846a2e6499886

The EXIF library is optional.

If it exists, webtrees will auto-rotate images.
If not, images are not auto-rotated.
