### ISSUE TITLE
Feature request - user name visibility

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3179]
Whilst I don't mind being visible to other users, I would prefer that my user name isn't visible. For example in the "Who is Online" and "Send a message" blocks

**Comment by fisharebest** [comment]
You should be able to control both of these in your account settings.

What settings do you have for "Contact method" and "Visible online"?

**Comment by ddrury** [comment]
Contact method: Internal messaging with email
Visible online: Checked

BTW for the "Who is online" module the username is hard coded at \app\Statistics\Repository\UserRepository.php line 121

**Comment by fisharebest** [comment]
If you don't want to let people send you messages with in the messages block, you should set your account to "no contact".

If don't want to appear in the "who is online" block, uncheck the setting.

Are you saying that these two config options are not having an effect?

**Comment by ddrury** [comment]
No, I'm quite happy for users to see that "David Drury" is online. What I don't want to reveal is "David Drury - myuserid" is online

In fact thinking about it, when is revealing a userid useful/necessary on public facing pages?

**Comment by fisharebest** [comment]
Users can have the same name.  So, if David Drury senior and David Drury junior both have accounts, you wouldn't know which one was logged in.

(or maybe it doesn't matter that we don't know which one is logged in?)

**Comment by ddrury** [comment]
My family probably would thank God there's only one of me! But I think in that situation as administrator I'd ask the second user to pick a unique name during registration. But I wonder how offer it would be a problem in real life

On 14 April 2020, at 14:28, Greg Roach <notifications@github.com> wrote:

Users can have the same name. So, if David Drury senior and David Drury junior both have accounts, you wouldn't know which one was logged in.

(or maybe it doesn't matter that we don't know which one is logged in?)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/fisharebest/webtrees/issues/3179#issuecomment-613442289">https://github.com/fisharebest/webtrees/issues/3179#issuecomment-613442289</a>", "url": "<a href="https://github.com/fisharebest/webtrees/issues/3179#issuecomment-613442289">https://github.com/fisharebest/webtrees/issues/3179#issuecomment-613442289</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by fisharebest** [comment]
The block provides a link to message the logged-in user.

So, we probably do need to distinguish them...

...or remove the ability to send messages...

**Comment by ddrury** [comment]
Yeah, I understand that but all I'm saying is remove the visiblity, If a user wants to view the code in the browser inspector it'll still be there but then we do trust our users don't we? (and I realise that given that fact it's unlikely to be a hugh security risk nevertheless ...)

For the messaging block why not just change the option code 
from  `<option value=username>realname - username</option>`
to `<option value=username>realname</option>`

and do something similar for the logged in users block

**Comment by fisharebest** [comment]
> For the messaging block why not just change the option code

How would you know which user you were sending a message to?

For the "who is online" block, maybe we don't care which one is online.
But for sending a message, it's pretty essential.

**Comment by ddrury** [comment]
OK change username to email address

**Comment by fisharebest** [comment]
Ah...

We've been there before.  People do not want to share their email addresses.
It's why we have the various contact/messaging options.

> In fact thinking about it, when is revealing a userid useful/necessary on public facing pages?

We only show the names/usernames to people who are already logged in.

Visitors should just see a summary of "N signed-in users"

**Comment by ddrury** [comment]
I don't understand why people don't want to reveal their email address but are happy to reveal their userid, however I'm not going to win this one am I 👎

**Comment by fisharebest** [comment]
> I don't understand why people don't want to reveal their email address but are happy to reveal their userid

Isn't that just how most sites work?

e.g. the webtrees forum software shows people's username.
