### ISSUE TITLE
HTML Block #getAllTagsTable#

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3182]
I used in a new html block as content #getAllTagsTable# to show all possible Tags, but this results in an error when the block is shown:

`Function ReflectionType::__toString() is deprecated …/app/Statistics.php:237
#0 …/app/Statistics.php(237): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 [internal function]: Fisharebest\Webtrees\Statistics->getAllTagsTable()
#2 …/app/Statistics.php(2661): call_user_func()
#3 …/app/Statistics.php(284): Fisharebest\Webtrees\Statistics->getTags()
#4 …/app/Module/HtmlBlockModule.php(104): Fisharebest\Webtrees\Statistics->embedTags()
#5 …/resources/views/user-page-block.phtml(11): Fisharebest\Webtrees\Module\HtmlBlockModule->getBlock()
#6 …/app/View.php(186): include('/mnt/web312/a3/...')
#7 …/app/View.php(282): Fisharebest\Webtrees\View->render()
#8 …/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make()
#9 …/resources/views/user-page.phtml(15): view()
#10 …/app/View.php(186): include('/mnt/web312/a3/...')
#11 …/app/View.php(282): Fisharebest\Webtrees\View->render()
#12 …/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make()
#13 …/app/Http/ViewResponseTrait.php(51): view()
#14 …/app/Http/RequestHandlers/UserPage.php(91): Fisharebest\Webtrees\Http\RequestHandlers\UserPage->viewResponse()
#15 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\UserPage->handle()
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process()
#17 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle()
#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#19 …/modules_v4/faces/src/Modules/FacesModule.php(82): Middleland\Dispatcher->handle()
#20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process()
#21 …/app/Http/Middleware/AuthMember.php(57): Middleland\Dispatcher->handle()
#22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthMember->process()
#23 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle()
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#26 …/app/Http/Middleware/Router.php(134): Middleland\Dispatcher->dispatch()
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#28 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher->handle()
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#30 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle()
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#32 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#33 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#34 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#36 …/app/Http/Middleware/DoHousekeeping.php(81): Middleland\Dispatcher->handle()
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#38 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle()
#39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#40 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#42 …/app/Http/Middleware/UseLanguage.php(73): Middleland\Dispatcher->handle()
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#44 …/app/Http/Middleware/UseSession.php(73): Middleland\Dispatcher->handle()
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#46 …/app/Http/Middleware/UseFilesystem.php(58): Middleland\Dispatcher->handle()
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseFilesystem->process()
#48 …/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle()
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#50 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle()
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process()
#52 …/app/Http/Middleware/UseDatabase.php(106): Middleland\Dispatcher->handle()
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#54 …/app/Http/Middleware/BadBotBlocker.php(208): Middleland\Dispatcher->handle()
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#56 …/app/Http/Middleware/UseCache.php(74): Middleland\Dispatcher->handle()
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process()
#58 …/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle()
#59 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#60 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#61 …/app/Http/Middleware/HandleExceptions.php(76): Middleland\Dispatcher->handle()
#62 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#63 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle()
#64 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#65 …/app/Http/Middleware/ReadConfigIni.php(65): Middleland\Dispatcher->handle()
#66 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#67 …/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle()
#68 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#69 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#70 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#71 …/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle()
#72 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process()
#73 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#74 …/index.php(55): Middleland\Dispatcher->dispatch()
#75 {main}`

**Comment by fisharebest** [comment]
It seems that there has been a change in the latest version of PHP, which does not appear in the documentation.  https://www.php.net/reflectiontype
