### ISSUE TITLE
Signing out from FAQ page throws error

### ISSUE THREAD

**Issue by NaturePinks** [fisharebest/webtrees#3183]
Webtrees 2.0.3 on Debian 8
------------------------------------------
After sign in, go to FAQ page.
Click sign out.
The error 
`Argument 1 passed to Fisharebest\Webtrees\Module\FrequentlyAskedQuestionsModule::faqsForTree() must be an instance of Fisharebest\Webtrees\Tree, null given, called in …/app/Module/FrequentlyAskedQuestionsModule.php on line 398 …/app/Module/FrequentlyAskedQuestionsModule.php:415 `
is thrown on the resultant url: `example.com/index.php?route=%2Fmodule%2Ffaq%2FShow%2Ffamilytree`

Full error is attached.
Looks similar to #3020 and #2847 

[webtrees-bug.txt](https://github.com/fisharebest/webtrees/files/4489153/webtrees-bug.txt)

**Comment by ric2016** [comment]
Same issue as  #3171 - The problem occurs in all module routes that do not handle this specifically.

**Comment by fisharebest** [comment]
This was fixed in ea1011228b0ca5ef409caca1dcb0bdfb53b9feea

Signing out now redirects to the home page.

**Comment by ric2016** [comment]
This isn't only about redirecting after signing out.
If the respective url is entered (from a bookmark or any external link) when signed out, the error occurs.
