### ISSUE TITLE
Ability to create custom pages

### ISSUE THREAD

**Issue by mrqd9** [fisharebest/webtrees#3185]
Creating new pages are so tricky way as now, Can it be more easy to make new pages with a module?

**Comment by fisharebest** [comment]
There is already an example of this in the documentation.

See `function getFooBarAction()` in [modules_v4/README.md](https://github.com/fisharebest/webtrees/blob/2.0.3/modules_v4/README.md).

Put your page in the variable `$html`.

The URL of the page is `/module/<module_name>/FooBar/<tree>`.  Note that the `FooBar` part matches the name of the function.
