### ISSUE TITLE
Find living people from all persons list

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#3187]
Clicking on the button 'alive' above the individual list, should provide a list of all living persons (if logged in).

But it only show persons where the birth date is unknown, excluding many living individuals with a known birth date but without a death date or marked as death.

Whether the birth date is known or not should not matter.

**Comment by fisharebest** [comment]
I *think* this was fixed recently.

Compare the two demo sites: [demo-stable](https://dev.webtrees.net/demo-stable/index.php?route=%2Fdemo-stable%2Fmodule%2Findividual_list%2FList%2Fdemo&show=indi&show_marnm=no&show_all=yes) and [demo-dev](https://dev.webtrees.net/demo-dev/module/individual_list/List/demo?show=indi&show_marnm=no&show_all=yes)

**Comment by JustCarmen** [comment]
You are right. I encountered this at my own site which runs the stable version and then I've checked it by accident at the demo site against the stable version in stead of the dev version.

I can confirm this is fixed.
