### ISSUE TITLE
Type of Level 0 record changes to UNKNOWN

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3188]
When editing a SUBM record (edit raw GEDCOM) the type was changed to UNKNOWN (I cannot edit the Level 0 Line):
![Screenshot (66)](https://user-images.githubusercontent.com/6324175/79694088-97063000-826e-11ea-9479-17a6e3b9498f.png)

I had the same experience some time ago when editing _LOC records on level 0.

**Comment by fisharebest** [comment]
I cannot reproduce this.

Which version of webtrees?

**Comment by hartenthaler** [comment]
Is this a old version of this issue? I thought that you fixed it already.

**Comment by fisharebest** [comment]
I think the issue is fixed, and that the problems were created using the old code.

If it happens in the future, open a new issue.
