### ISSUE TITLE
Error when showing submitters at a tree

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3190]
In Control Panel / Family Trees / last column Submitters: when I click on the number of submitters in any tree the result is an error.
![Screenshot (67)](https://user-images.githubusercontent.com/6324175/79697857-68478400-8285-11ea-9327-38797587394a.png)

**Comment by fisharebest** [comment]
This is most likely a consequence of #3188.

Your `SUBN` records have changed to `UNKNOWN` records, which would cause the error.

**Comment by hartenthaler** [comment]
I don't think so. In the meantime, I repaired or deleted all the level 0 records which were changed to "UNKNOWN" (checking the database table wt_others). But maybe there is a unique point of failure behind both issues. I will concentrate on #3188 an come back to this issue if the other one is solved.
