### ISSUE TITLE
v2 -> v1 geographic data bug

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3193]
There is a problem importing a places csv file created in version 2 into version 1.7.
We properly quote strings in version 2 of the file
`2;Australia;"Western Australia";"Nedlands City";;E115.80572;S31.97992;10;`
however 1.7 expects 
`2;Australia;Western Australia;Nedlands City;;E115.80572;S31.97992;10;`
This results in the fields in the database being wrapped in quotes.

I don't know how you wish to handle this (probably rare) situation. 

It looks like a pain to change the 1.7 file reading code although it's a simple change to strip the quotes when assembling the parts into a full place.
We could remove the quotes from the 2.0 code but that doesn't seem right to me or just suggest using a text editor to remove the quotes in the csv before importing.

**Comment by ddrury** [comment]
There's another difference level 0 on 1.7 -> level 1 on 2.0 etc.

**Comment by fisharebest** [comment]
Two separate issues to consider - levels and CSV delimiters.

===LEVELS===

Levels aren't used in webtrees 2.0 - except to create the CSV files.  We read them in, and write them out.

Is it possible that someone will have a mix of zero-based and one-based levels in their database, depending on the history of their data?  (e.g. some created with webtrees 1.7, some created with webtrees 2.0).

If so, we probably shouldn't rely on the value in the database when generating the export.
Instead, we should probably generate them for each row by counting the number of parts in the place name and subtracting one!.

The code for processing the imports/exports seems unnecessarily complicated.  It is mostly copied directly from the original 1.7 code.  Perhaps now is the time to take a look at it...

===CSV DELIMITERS===

We now use the PHP `fputcsv()` function to create CSV files with proper delimiting and escaping.
This allows data to contain *both* the delimiter and the separator.

My test data contains place names such as `<script>alert("XSS");</script>`, and it is not inconcevable that someone could use a `"` or a `;` in place name.

So, I would be reluctant to simply strip quotes from CSV files.  It maybe better to update webtrees 1.7 to use `fgetcsv()`.

**Comment by fisharebest** [comment]
I've updated the export to count the place hierarchy parts (and subtract 1) - rather than assume anything in the `pl_level` column.

This column is now safe to delete.  

I'm thinking of storing the flags (as SVG data) in the place_location table.
To include these in the import/export, we would definitely need delimiters in the CSV file.

**Comment by ddrury** [comment]
OK, I'll close this, I've had a quick look at the 1.7 code 👎 but I'll see what I come up with - probably easiest to more or less replace with the 2.0 code

**Comment by fisharebest** [comment]
I've updated the 1.7 code to use the proper functions to read/write CSV files.

I didn't make any attempt to clean up the code - I wanted the change to be as simple/clear as possible to minimise the risk of adding bugs.

As far as I can tell, it works with files created by all versions...
