### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by Sobi007** [fisharebest/webtrees#3195]
System : Debian 10, nginx , PHP7.4.4 , PostgreSQL 9.6

After login shows "manage family trees" with error:
SQLSTATE[25P02]: In failed sql transaction: 7 BŁĄD: bieżąca transakcja została przerwana, polecenia ignorowane do końca bloku transakcji (SQL: insert into "wt_dates" ("d_day", "d_month", "d_mon", "d_year", "d_julianday1", "d_julianday2", "d_fact", "d_gid", "d_file", "d_type") values (12, JUL, 7, 1990, 2448085, 2448085, DEAT, I15, 2, @#DGREGORIAN@))

**Comment by fisharebest** [comment]
Error code `25P02` means that an error occured in the **previous** statement.

Looking through the code, the previous statement is probably this:

```
                try {
                    DB::table('placelinks')->insert([
                        'pl_p_id' => $place->id(),
                        'pl_gid'  => $xref,
                        'pl_file' => $tree->id(),
                    ]);
                } catch (PDOException $ex) {
                    // Already linked this place - so presumably also any parent places.
                    break;
                }
```

Here, we are inserting a record if it does not already exist.

It is quicker to insert it (and ignore the error if it is already there), than to query the database first to see if it exists.

But I guess that is what we will need to do.

We use the same construct in a few places.
