### ISSUE TITLE
2.0.3 - nick names in Descendants report: wrong order and missing quotation marks

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3204]
In the Descendants report of webtrees 1.7.16 the nick names are placed between the first name and last name.
Example: Willem 'Wim' Willemsen

In webtrees 2.0.3 the nicknames are placed after the surname, without quotes. 
Example: Willem Willemsen Wim
Can this be fixed?

**Comment by ddrury** [comment]
See https://github.com/fisharebest/webtrees/issues/1401

**Comment by fisharebest** [comment]
The change in behaviour of nick-names was intentional.  For reasons, see the link that @ddrury posted.

**Comment by TheDutchJewel** [comment]
That's not an answer on my question about the missing quotation marks.
Can this be fixed?
