### ISSUE TITLE
Installation with Cloudflare

### ISSUE THREAD

**Issue by Hauptstadt** [fisharebest/webtrees#3206]
Hi there,

A couple of notes for my attempt to install webtrees at https://www.fordrchris.com/familytree 

I continue to get 500 Internal Service Errors when I try to load the webpage to install.  I use Cloudflare and have "Automatic HTTPS Rewrites" and "Always use HTTPS" turned on, per other issues I found here.  Additionally, I have "SSL/TLS encryption mode = Full". Despite that, my issues remain:

I am using PHP 7.3 and meet all the other requirements.

 Per the help file in https://webtrees.net/install/cloudflare/ there is no file location "data/config.ini.php", within the data folder there is simply an index.php.  I've tried putting the trusted_headers="cf-connecting-ip" code in the index file but it still leads to errors.   
  
I've searched the zip file and located a config.ini.phtml file and tried putting the code slice in there but it also did not work there.  
  
I'm normally pretty technically adept but at this one I'm stumped.  Any ideas where I should be tinkering?

**Comment by fisharebest** [comment]
> Per the help file in https://webtrees.net/install/cloudflare/ there is no file location "data/config.ini.php",

This file is created during the setup/install process.

(and if it exists, webtrees assumes that the setup has been run, the database has been created, etc.)

So, you cannot enable cloudflare until after you have run the setup.

1) turn off cloudflare
2) delete data/config.ini.php that you created
3) run the setup script
4) enable cloudflare and add the trusted-header line to config.ini.php

**Comment by fisharebest** [comment]
Actually, you shouldn't need to turn off cloudflare.

The trusted-header line is just to ensure that you see the correct remote IP address in your logs.

**Comment by fisharebest** [comment]
> So, you cannot enable the cloudflare trusted-headers until after you have run the setup.

I have updated the documentation to make this clear.

> I continue to get 500 Internal Service Errors when I try to load the webpage to install.

This is most likely because webtrees thinks you have run the setup (since config.ini.php exists), when you haven't.

See https://webtrees.net/faq/500 for more info about 500 errors.

If you get other problems with the installation, please open a new issue.
