### ISSUE TITLE
Editing News Changes Date

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3208]
Every time I edit a News article, the date/time stamp is replaced with now.  This is screwing up all of my old News entries.

**Comment by miqrogroove** [comment]
Going to try this as a workaround.

`ALTER TABLE wt_news CHANGE updated updated timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;`

**Comment by fisharebest** [comment]
> `ALTER TABLE wt_news CHANGE updated updated timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`

Isn't that already the default?
```
MySQL> SHOW CREATE TABLE wt_news;

CREATE TABLE `wt_news` (
  `news_id` int NOT NULL AUTO_INCREMENT,
  `user_id` int DEFAULT NULL,
  `gedcom_id` int DEFAULT NULL,
  `subject` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `body` text COLLATE utf8_unicode_ci NOT NULL,
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`news_id`),
  KEY `wt_news_user_id_updated_index` (`user_id`,`updated`),
  KEY `wt_news_gedcom_id_updated_index` (`gedcom_id`,`updated`),
  CONSTRAINT `wt_news_gedcom_id_foreign` FOREIGN KEY (`gedcom_id`) REFERENCES `wt_gedcom` (`gedcom_id`) ON DELETE CASCADE,
  CONSTRAINT `wt_news_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `wt_user` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

**Comment by miqrogroove** [comment]
That's not what I had in my database.  Mine was 

```
`updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
```

**Comment by fisharebest** [comment]
Databases created by 1.x have `ON UPDATE CURRENT_TIMESTAMP`.
Databases created by 2.x do not.

We will need a database schema update to fix this.

**Comment by fisharebest** [comment]
> We will need a database schema update to fix this.

Alternatively, we could save the same date when we update the data.
