### ISSUE TITLE
Add support for Ethnic, Tribe and clan facts

### ISSUE THREAD

**Issue by agron2017** [fisharebest/webtrees#3209]
Can some one describe what needs to be done to add facts like Ethnicity, Tribe and Clan to Webtrees.
Do these facts need to be added in the database? Which table? Or in the source code? Which files? Or maybe in some text files? Which ones?

**Comment by fisharebest** [comment]
Gedcom 5.5.1 has a field `NATI` which would appear to be what you are looking for.

It is defined as follows:

> NATI {NATIONALITY}:=
> The national heritage of an individual.

You can view the full specification [here](https://webtrees.net/downloads/gedcom-551.pdf).

You would enable this field in: Control panel -> Family tree -> Preferences -> Individual facts -> Add "Nationality".

If none of the standard fields are applicable, you can use the "Custom fact" tag.
This should be enabled by default, but if not, you enable it the same way as above.

You would end up with data such as

1 FACT Wu-Tan
2 TYPE Clan

This would display as:

> Clan: Wu-Tan

**Comment by agron2017** [comment]
Thanks for the Nationality tip.

How can I make Tribe and Clan facts be permanently present or selectable for every new person? 
If I need to add them in the source code, where would I have to add it?

Thanks,
//Agron

**Comment by fisharebest** [comment]
The `NATI` tag is defined as "nationality or tribal origin".

This would seem to correctly cover all your cases (ethnicity, tribe, clan).

It is probably the best way to record these attributes, in terms of portability, correctness, etc.

If you don't like the label "Nationality" and would prefer "tribe/clan" or something else, you can change the text.

To provide a "custom translation", you need to create a simple module.  There is an example of this included in the code.

See https://github.com/fisharebest/webtrees/tree/master/modules_v4

**Comment by agron2017** [comment]
OK it looks like I need to go back and ask with an example because I am not getting it.
A person identifying as 3rd generation mexican in the USA, a US citizen, but he wants to be identified as mexican. How do I indicate in webtrees that him and all his family members are US citizens of mexican heritage? 
Furthermore, these people might belong to certain tribes, and within tribes they have clans. Tribes are a much larger group of related families spanning many regions and mountains, whereas a clan could be a group of families settled in a neighborhood or possibly a group of tipi's ( a tent in a western Indian culture) in a field. Sometimes they to the clan by the name of the oldest who sometimes even acted like a judge to settle clans problems.

**Comment by fisharebest** [comment]
webtrees is based around GEDCOM - a standard format for storing and exchanging genealogy data.

GEDCOM has a "Nationality" field, described as above.

You can use it to store all the facts you described.

It has no other similar fields.

Now, you can modify the code (quite easily) to create new fields - but the GEDCOM spec says that custom fields should be ignored by other applications that do not know about them.

So, while you *could* create custom fields for Clan, Tribe, etc. - I strongly recommend that you don't.  If/when you move to a different genealogy application, this data will be lost.

Just use the "Nationality" field.  It is defined as follows:

> NATIONAL_OR_TRIBAL_ORIGIN:={Size=1:120}The person's division of national origin or other folk, house, kindred, lineage, or tribal interest.Examples: Irish, Swede, Egyptian Coptic, Sioux Dakota Rosebud, Apache Chiricawa, Navajo BitterWater, Eastern Cherokee Taliwa Wolf, and so forth

**Comment by fisharebest** [comment]
To find out if other webtrees users have similar issues - or indeed have other suggestions, you could ask this question on the forum - <https://www.webtrees.net>
