### ISSUE TITLE
I need help in solving report issues - 2.0.3

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3211]
'There are several issues in reports, especially in the reports in rtl languages or for rtl data.

Who is ready to help me solve them?

Samples: 
#1484 - #1490, #1494, etc., #3122

**Comment by fisharebest** [comment]
The XML based reports are very difficult to maintain.

They are based on the TCPDF library, which has been abandoned (twice).  I was one of the developers who worked to fix the PHP 7.4 compatibility issues - and it took many months to get the patches accepted.  I very much doubt that it will work with PHP 8.0, which is due in December.

It is not possible to fix many of the issues.  Some simpler issues might be fixable - but require a disproportionate amount of time/effort.

It will be much quicker and easier to delete them all and start from scratch with a new design.

**Comment by melizaa** [comment]
Thanks for the update.
