### ISSUE TITLE
Advanced Search Sometimes Doesn't Work

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3213]
I have a surname in my family tree, MCLIN that, for some reason, if I do an advanced search for that exact phrase, gives me no search results.  But then if I empty the surname field and type in a given name, people start showing up.  What's going on here?

p.s. The same phrase in the General Search page gives me no troubles.

**Comment by fisharebest** [comment]
The "advanced search" will search the `wt_names` table.

The "general search" will search the `wt_individuals` table.

Can you look in the `wt_names` table to see if data exists in the `n_surn` column?

**Comment by miqrogroove** [comment]
Yes, it does not seem to a problem with the wt_name table...

```
mysql> SELECT COUNT(*) FROM wt_name;
+----------+
| COUNT(*) |
+----------+
|     7401 |
+----------+

mysql> SELECT COUNT(*) FROM wt_name WHERE n_surname='McLin';
+----------+
| COUNT(*) |
+----------+
|        3 |
+----------+
```

**Comment by miqrogroove** [comment]
Okay I just noticed something else.  The n_surname column shows `McLin` but the n_surn column shows `MacLin`  🤔

**Comment by miqrogroove** [comment]
Two more test results.  If I do an "Exact" search for "MacLin" it shows me people named "McLin".  And If I do a "Sounds like" search for "McLin" then I get good results as expected.  The problem is that it's not matching the right name on the "Exact" and "Begins with" conditions.

**Comment by fisharebest** [comment]
`n_surn` is a normalised version of the `SURN` tag.

`n_surname` is the surname extrated from the `NAME` tag.

Typically, `n_surname` is an inflected form "Wakovska" and `n_surn` is the base form `Wakovski`.

I guess that the advanced search is querying `n_surn`, when it should be querying`n_surname`.

**Comment by fisharebest** [comment]
> I guess that the advanced search is querying `n_surn`, when it should be querying `n_surname`.

It needs to search **both**.  Fixed.

**Comment by miqrogroove** [comment]
That https://github.com/fisharebest/webtrees/commit/fc6d23eeb6fc336a4e16e09a85369e2965a5bf63 doesn't look right.

**Comment by fisharebest** [comment]
Thanks - fixed.
