### ISSUE TITLE
Installation Error: Uncaught Error: Class 'Fisharebest\Webtrees\Webtrees' not found

### ISSUE THREAD

**Issue by Hauptstadt** [fisharebest/webtrees#3214]
Hi there,

Following up on[ my previous issue](https://github.com/fisharebest/webtrees/issues/3206), some more color, which doesn't seem to be Cloudflare related.

I have turned on display_errors and when I load my [URL to begin the setup process](https://www.fordrchris.com/familytree/), I get the following error:

Fatal error: Uncaught Error: Class 'Fisharebest\Webtrees\Webtrees' not found in /familytree/index.php:41 Stack trace: #0 {main} thrown in /familytree/index.php on line 41

For your information, my configuration is as follows:

Cloudflare is off
I am running PHP 7.3
I gave 777 permissions to the data folder and everything within it so that webtrees may write.  
I checked everything else in the 500 error FAQ and it seems to be none of those.  
I'm hosted by A2Hosting if it matters.
  
Any other ideas?  I appreciate the help and am really excited to use Webtrees, it looks amazing!

**Comment by fisharebest** [comment]
Does the file `/app/Webtrees.php` exist?

Does it look like this: https://github.com/fisharebest/webtrees/blob/2.0.3/app/Webtrees.php

Maybe you didn't copy all the files to your server?  If this one is missing or corrupt, then perhaps other are too?  If that's the case, try copying them all again.

**Comment by Hauptstadt** [comment]
Strange, I did fresh installs in two directories and both times the app folder had 3 php files in it instead of the 46, both times.  Either way, you nailed it, 100% user (or maybe I can blame the server :) ) error.  

Thank you so much!
