### ISSUE TITLE
Re-order Media

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3215]
When an individual has many photos attached, is there any shortcut for moving one object to the top of the list?  I find dragging these large rectangles rather awkward when I have to scroll the list.

**Comment by fisharebest** [comment]
Are you talking about the "Re-order media" option, on the individual page?

> I find dragging these large rectangles rather awkward

Can you describe the problem?

Are you using a mouse or a touch-screen?  Desktop, laptop, tablet or phone?  etc.

**Comment by miqrogroove** [comment]
Desktop.  Mouse.  Some individuals have 20 or 30 photos and when I add new media it goes to the bottom of the list.  If I want to make the new upload primary, I have to drag it all the way up the page.

**Comment by wkitty42** [comment]
On 5/7/20 7:03 AM, miqrogroove wrote:
> Desktop. Mouse. Some individuals have 20 or 30 photos and when I add new media 
> it goes to the bottom of the list. If I want to make the new upload primary, I 
> have to drag it all the way up the page.


does the page/list not scroll upwards automatically when you are dragging the 
media to the top and reach the top of the visible scrollable area?

the same should happen when dragging media down the list, too, i think...


-- 
  NOTE: No off-list assistance is given without prior approval.
        *Please keep mailing list traffic on the list unless*
        *a signed and pre-paid contract is in effect with us.*

**Comment by miqrogroove** [comment]
Scrolling is slow and awkward.  And the Save button is all the way at the bottom of the list.  That's 3 scrolls to accomplish something that should only require a single click.  Very inconvenient.

**Comment by wkitty42** [comment]
On 5/7/20 9:16 AM, miqrogroove wrote:
> Scrolling is slow and awkward.

i was speaking of autoscrolling the list... not manually... i see/use this all 
the time in other apps... for example, when i'm copying text from a text console 
that extends above or below the current text frame... i just move the mouse 
until the autoscroll is triggered and then hold it there until i reach the text 
i'm after...

> And the Save button is all the way at the bottom 
> of the list.

this is why i have buttons at the top and bottom in my UIs ;)

> That's 3 scrolls to accomplish something that should only require a 
> single click. Very inconvenient.

a single click to move an object from one place to another? interesting concept...

**Comment by fisharebest** [comment]
I guess that "move" buttons would also be useful for keyboard users.  first/up/down/last.

**Comment by miqrogroove** [comment]
Another idea: When I'm clicking through all of the other buttons and pages it takes to get an image uploaded, I could have one more option to make the new image primary.  Then I wouldn't even need to re-order in most situations.
