### ISSUE TITLE
Places Tab Sometimes Blank

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3216]
For some random individuals, I get a blank map and blank blue sidebar where the Places map should appear.

It seems to happen more often with individuals who have only one or two places in their fact list.  I haven't found the exact pattern yet.

**Comment by fisharebest** [comment]
How often?  If I visit your site and keep pressing F5, how long before I see it?

**Comment by miqrogroove** [comment]
It doesn't seem to be a refresh issue.  It's happening on specific individuals.

**Comment by ddrury** [comment]
Anything in the browser developer tools console or network tabs?

**Comment by miqrogroove** [comment]
Good idea...

```
DevTools failed to load SourceMap: Could not parse content for /public/js/vendor.min.js.map: Unexpected token < in JSON at position 1

VM83:81 Uncaught ReferenceError: geoJson_data is not defined
    at _buildMapData (<anonymous>:81:21)
    at <anonymous>:163:9
    at <anonymous>:166:7
    at b (vendor.min.js?v=2.0.3:2)
    at We (vendor.min.js?v=2.0.3:2)
    at w.fn.init.append (vendor.min.js?v=2.0.3:2)
    at w.fn.init.<anonymous> (vendor.min.js?v=2.0.3:2)
    at U (vendor.min.js?v=2.0.3:2)
    at w.fn.init.html (vendor.min.js?v=2.0.3:2)
    at Object.<anonymous> (vendor.min.js?v=2.0.3:2)

site.webmanifest:1 GET /public/site.webmanifest?v=2.0.3 401 (Unauthorized)

site.webmanifest:1 Manifest: Line: 1, column: 1, Syntax error.

DevTools failed to load SourceMap: Could not parse content for /public/js/vendor.min.js.map: Unexpected token < in JSON at position 1
```

**Comment by ddrury** [comment]
The only place that geoJson_data appears is on the Pedigree Map, can you confirm that is where the problem lies

**Comment by miqrogroove** [comment]
No it's /tree/tree1/individual/ 

Do you want me to try viewing the pedigree map page for the same person?

**Comment by ddrury** [comment]
Does  your version of `webtrees/resources/views/modules/places/tab.phtml` look like the one here
https://github.com/fisharebest/webtrees/blob/master/resources/views/modules/places/tab.phtml

**Comment by miqrogroove** [comment]
TortoiseMerge says line 106
```
-                    zoom = data.features[0].properties.zoom;
+                    zoom = geoJson_data.features[0].properties.zoom;
```

**Comment by miqrogroove** [comment]
https://github.com/fisharebest/webtrees/commit/ef9d8acc97201d390707f591d32fd32b3ee148d1

**Comment by ddrury** [comment]
Well that's the fix, I don't know off the top of my head whether that commit has got into a release or is destined for the next one.

**Comment by miqrogroove** [comment]
2.0.3 was March 17 so I'd say the bug is still valid for that milestone.

**Comment by ddrury** [comment]
OK
