### ISSUE TITLE
Unable to add repositories in 2.x?

### ISSUE THREAD

**Issue by Ziris85** [fisharebest/webtrees#3221]
Hello,

Usually in the 1.x version, if I needed to add a repository, I could do so while I was in the process of adding a source (or associate that source with an existing repository). In 2.x, it seems this feature is either missing or broken? All I get is a blank dropdown:
![image](https://user-images.githubusercontent.com/14392979/81454988-c6b4a380-915b-11ea-8ca2-ff7d19e6d6b5.png)
I've tested this with Firefox, Chromium, and Opera, on different internet connections, so I don't believe this is an environmental issue. Nothing in browser console from what I've been able to gather either.

Was this functionality changed and I'm just missing something? Appreciate your help!

**Comment by ric2016** [comment]
This is likely the same issue as #2935. It has been fixed (but not released yet).

**Comment by Ziris85** [comment]
Ah, dangit, you're absolutely right - complete with the delay. Thanks for pointing that out! I've actually seen this behavior in other places on my site (though can't recall atm where), though nothing a few page refreshes wouldn't eventually fix (being the lazy person that I am lol). However, before I close this issue, I'm going to explore my hosting env, since after upgrading to 2.x, I've noticed overall performance has dropped a bit, so I'm wondering if I need to make any changes there.

I'll follow up in here if I find anything.

**Comment by Ziris85** [comment]
So, after some tinkering with my Apache web server (temporarily unloading some hefty modules like modsecurity, mod_qos, etc), I was able to speed it up a little and start getting a functional drop-down sometimes. I was actually close enough to determine that ~400ms is the magic number - anything less than that and it would load, anything more and it wouldn't (if that's information anyone would care to know). In these two load attempts, the first one failed, and the second one succeeded:
![image](https://user-images.githubusercontent.com/14392979/81510035-ede6ae80-92dc-11ea-8daf-e57aa507683b.png)
However, I'm noticing that, even when the dropdown loads and gives me a search box to type in, I still don't have the option to create a new repository. So, before we close this one up, may I ask where I can accomplish this?

**Comment by fisharebest** [comment]
> I still don't have the option to create a new repository

You can't do it here.

We are creating a source in a pop-up / modal window.
You can select an existing repository, but not create a new one.
That would require a pop-up inside a pop-up.

I know webtrees 1.7 did this (you could have a stack of 5 or 6 pop-ups), but it is regarded as a poor UI design, and our CSS framework (bootstrap) does not allow it.

You'll need to create the new repository as a second step - either before or after.
