### ISSUE TITLE
Question: How to add Engagement fact to a couple before they get married

### ISSUE THREAD

**Issue by agron2017** [fisharebest/webtrees#3222]
I just need advice on how to use this fact.

Please tell me how to add Engagement fact to a couple before they get married.

Do I have to add this fact to both individuals? Or is it enough to add this fact to just one individual and they will both show up as connected on the relationship map?

**Comment by ric2016** [comment]
The forum is a better place to ask questions like this one.

Engagement is a family event, similar to marriage, so you add it on the family page. It will then show up for both individuals. 

(Note also that relationships are determined based on families; specific family events only change the type of relation, e.g. "wife" vs "ex-wife" vs "partner")

**Comment by agron2017** [comment]
Oh no, I didn't Engagement as an event like an engagement party. I meant Engagement as a fact which changes the relationship from a girlfriend or boyfriend to fiancé or fiancée.

I tried adding the Associate fact to the fiancé but there was no "fiancée" or "engaged to..." type of relationship. 
In other words, I still can't who is engaged to who.

**Comment by vytux-com** [comment]
I believe that this needs to be thought of in terms of genealogy... 

Family units would rarely get created before official formation by marriage or child birth. 

Some forms of engagement have been recorded in the past such as bahns however they would need to be added to a family unit. So you would need to join the couple to form a family first and that might be frowned upon / seen presumptuous by living relatives.

**Comment by ric2016** [comment]
> I tried adding the Associate fact to the fiancé

No, just use a family event, as suggested. In which way do you want the relationship status to be displayed anyway, if the respective individuals are married later?

**Comment by fisharebest** [comment]
As others are have said, you need to create a "Family" object (using the add wife/husband link).
You then add an engagement event to the family.

The link is labelled "add husband/wife", although you are actually adding a partner.

How the partner is labelled depends on their sex, and the family facts.

At present, we use

* ex-husband/ex-wife/ex-spouse (if a divorce event exists)
* husband/wife/spouse (if marriage event exists)
* partner (if no marriage event exists)

I will update the code to use fiancé/fiancé/fiancé(e) when an engagement event exists.

**Comment by agron2017** [comment]
I got it. 

NOTE: These instructions are good for Webtrees **version 2.0.3**
So here are the steps to do this (good for wiki):

### How to do an Engagement
1. Select the person that is engaged and click on the Families tab (half page down there are tabs like Places, Facts and Events, Families....)
2. Almost at the bottom of the page there is a text that says Add a Wife (or a Husband). You might think it is not clickable but it is. Click on it.
3. Just select the fiancé or fiancée and save it.
4. Then click on link that says Family with xxxx (the name of the fiancé or fiancée)
5. In the table Fact and Event table, On the row that says Fact and Event, click on Select and choose Engagement and click Add.
6. Enter all the info and click save.
7. If the couple is still engaged and not married yet, you can delete the Marriage fact. The Engagement fact will remain and it will show up in both partners family trees.
