### ISSUE TITLE
Wrong Date on Statistics Block

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3224]
When I looked in my tree site this morning, the Statistics block said, "This family tree was last updated on May 9, 2020."

I know I didn't make any updates yet today, so I checked the Changes Log, which correctly shows the most recent change on "2020-05-08 23:17:05".  That is the correct local time of the most recent update.

It seems like there is a bad date conversion happening somewhere.

**Comment by fisharebest** [comment]
This value does not come from the changes table.

It comes from the `DATE` field of the most recent `CHAN` record.

I have converted it to use the `wt_change` table instead.
