### ISSUE TITLE
The URL of the page from which a message was sent is not correct - 2.0.3

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3230]
I send a message from .../index.php?route=%2Ftest%2Ftree%2FGedcom.ged%2Findividual%2FI90%2FIlan-Amity.

At the bottom of the message I see "This message was sent while viewing the following URL" - ...?route=%2Ftest%2Ftree%2FGedcom.ged%2Findividual%2FI90%2FIlan-Amity

When I click on the URL in the message mail, I get: 
This page isn’t working
www.amitys.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

**Comment by fisharebest** [comment]
I just tried to send myself a message, and the URL worked OK.

Are you sending the message from:

(a) a logged in user
(b) a visitor

Are you reading the message:

(a) in your email
(b) in the messages block in webtrees

**Comment by melizaa** [comment]
Admin messages copies both of visitors and user mails show an erroneous URL.

I spoke of mails in G-Mail.
In the messages block I see the same erroneous URL in <>-s, not as a link.

I tried to send a message from a visitor in demo-dev from https://dev.webtrees.net/demo-stable/index.php?route=%2Fdemo-stable%2Ftree%2Fdemo. As expected, I did not get a copy.

**Comment by fisharebest** [comment]
I can't reproduce this at all.

When I use a test account to send a message to my main account, this is what the email looks like.

----------

<img width="614" alt="Screenshot 2020-05-11 at 12 43 21" src="https://user-images.githubusercontent.com/2306088/81558586-d8798f00-9385-11ea-8eb0-2ddf427b77bc.png">

**Comment by melizaa** [comment]
Greg,
Your above URL links to another page, not to the page of i3801.

I will try to see if I can find why my test sites omit index.php from the URL.  

Meliza

**Comment by melizaa** [comment]
After I send a message mail using the brave browser, I see in the future system
This page isn’t working
www.amitys.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

**Comment by melizaa** [comment]
Same error message and missing index.php also in Chrome.

**Comment by melizaa** [comment]
Where can I see the base-URL?

**Comment by melizaa** [comment]
The message URL is printed without the index.php. 
The page URLs have the index.php addition.

**Comment by melizaa** [comment]
How do you suggest that I test this?

**Comment by melizaa** [comment]
I see index.php on all the pages.
You do not have index.php in your URL.
Why?

**Comment by melizaa** [comment]
I do not have index.php in the message URL link.

**Comment by fisharebest** [comment]
I think I see the problem.

When you upgrade from 1.7 to 2.0, there are some manual steps.
See http://webtrees.net/upgrade/2.0/

The first (and most important) is that you need to specify the URL of your site in the file `data/config.ini.php`

So, you need to add this line to your config file:

base_url="https://www.amitys.com/future"

**Comment by melizaa** [comment]
Now the URL in the test mails is as expected. Thanks.

**Comment by melizaa** [comment]
and I do not see the message
This page isn’t working
www.amitys.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
