### ISSUE TITLE
Statcounter TM printed to the left on RTL pages - 2.0.3

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3232]
TM of Statcounter™ prints on rtl pages in Control panel - Modules - Website - analytics and /index.php?route=%2Ftest%2Fmodule%2Fstatcounter%2FAdmin anf titles to the left. It should print to the right.

**Comment by fisharebest** [comment]
There are 4 other cases like this, where the module title isn't translatable.

I will add these.

In the translation server, you can add non-printing directional characters.

Although `™` is created from latin characters, it is a non-directional character.

So, if you add a "LRM" (left-to-right mark) at the end of the translation string, you'll get

Statcounter™`lrm`

Now, the ™ is between two pieces of ltr text and will be rendered as a ltr character.
