### ISSUE TITLE
After code update I get error. 2.0.3

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3233]
I upgraded my test site to 6ccd7baf149..9b9349c6e2d  and I get error 
Aura\Router\Exception\RouteAlreadyExists: Fisharebest\Webtrees\Http\RequestHandlers\RedirectFamilyPhp in /home/amitys/test.amitys.com/vendor/aura/router/src/Map.php:134 Stack trace: #0 /home/amitys/test.amitys.com/vendor/aura/router/src/Map.php(177): Aura\Router\Map->addRoute(Object(Aura\Router\Route)) #1 /home/amitys/test.amitys.com/vendor/aura/router/src/Map.php(196): Aura\Router\Map->route('Fisharebest\\Web...', '/family.php', 'Fisharebest\\Web...') #2 /home/amitys/test.amitys.com/app/Module/RedirectLegacyUrlsModule.php(79): Aura\Router\Map->get('Fisharebest\\Web...', '/family.php', 'Fisharebest\\Web...') #3 /home/amitys/test.amitys.com/app/Services/ModuleService.php(841): Fisharebest\Webtrees\Module\RedirectLegacyUrlsModule->boot() #4 /home/amitys/test.amitys.com/app/Http/Middleware/BootModules.php(60): Fisharebest\Webtrees\Services\ModuleService->bootModules(Object(Fisharebest\Webtrees\Module\CloudsTheme)) #5 /home/amitys/test.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #6 /home/amitys/test.amitys.com/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #7 /home/amitys/test.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #8 /home/amitys/test.amitys.com/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #9 /home/amitys/test.amitys.com/vendor/illuminate/database/Concerns/ManagesTransactions.php(29):
etc.

Is it my mistake?

**Comment by melizaa** [comment]
Solved

**Comment by foscone** [comment]
How did you solve it?

**Comment by fisharebest** [comment]
A common cause of this error is to have two copies of the same module installed (with different names).
