### ISSUE TITLE
Error in Cousins tab

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#3234]
If clicking any cousin in Father's family, you are correctly taken to the cousin's indi page. Clicking a cousin in Mother's family results in reloading the initial indi page

**Comment by vytux-com** [comment]
I am going to assume it's on my custom module. https://github.com/vytux-com/vytux_cousins 

If this is the case, create an issue there and I'll have a look...

**Comment by fisharebest** [comment]
@vytux-com - agreed, it looks like one for you ;-)

**Comment by HRN65** [comment]
My bad. I forgot this was a custom module. I also see this is already fixed in master
