### ISSUE TITLE
Wrong Zoom Level in Places

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3235]
This is something we resolved in 1.7 with Google Maps a while back, but seems to be a problem again in 2.0 with OSM.

When an individual only has multiple events in the same place, but only one place, the map is using a default zoom level of maximum zoomed in, rather than the zoom level saved in the geo data.  For most places, this results in a blank or mostly blank map that must be zoomed out for context.

**Comment by miqrogroove** [comment]
For testing purposes, this bug is most easily replicated on individuals who died at a young age.  When birth and death were in the same place with no other places, the zoom level was always wrong.

**Comment by miqrogroove** [comment]
This remains a significant problem in 2.0.16.  There were too many changes since 2.0.11 to merge the hacks I was using to save the zoom levels.  Now I'm back to just seeing a random house or two in the middle of the city, and then I have to click the zoom out button multiple times.  Not a good experience.

**Comment by fisharebest** [comment]
Does your PR fix this issue?

If not, can you show me how to reproduce the problem?

**Comment by miqrogroove** [comment]
Not exactly fixed.  Remaining issues are discussed and duplicated in #3229 (you were planning a geojson schema to fix this some day)
