### ISSUE TITLE
Odd Behavior of Enter Key in Census Assistant

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3236]
Steps Taken:

1. Clicked the Census add fact link at the bottom of individual's Facts and events tab.
2. Picked United States 1860 from the date list.
3. Modified Census date to 6/23/1860.
4. Modified Census place to be more specific.
5. Under Source, picked my 1860 census source and added details and quality values.
6. Scrolled back to the top and clicked "Create a shared note using the census assistant"
7. Clicked on the Notes field, pasted some text, then pressed Enter.

Expected Result:

I thought maybe the Notes field could be multiline.

Actual Result:

Form submitted, and I ended up with not one but two identical Census facts attached to the individual.

**Comment by fisharebest** [comment]
> I thought maybe the Notes field could be multiline.

Are you saying

1) we should make it clear this is a single line field
2) you want to change this field into a multi-line field

> I ended up with not one but two identical Census facts

This is a separate issue.  If you can reproduce it, please create a new issue for it.  Thanks.

**Comment by miqrogroove** [comment]
Actually I was more interested in the duplicate census items.  I'm trying to work within the existing system so the single line input is fine, I just don't want things randomly duplicated.  I'll let you know if it's repeatable when I come back to that again.

**Comment by fisharebest** [comment]
Did you, perhaps, enter the person twice in the census data?

**Comment by miqrogroove** [comment]
I did some more testing and concluded that I hit the Enter key twice to try to insert a blank line.

I'm satisfied this is my user error.  I'll let you decide if it's worth changing anything in there.

**Comment by fisharebest** [comment]
We could change the field label from "Notes" to "Comments"?

This would emphasise the difference between it and the multi-line GEDOM "Note" fields that are also on the page.

**Comment by miqrogroove** [comment]
If I understand, this field just gets appended to the Shared Note after the census table.  I don't think the label matters.  I would either leave it as it is or adjust the script so that the Enter keypress will self-cancel.

**Comment by fisharebest** [comment]
> concluded that I hit the Enter key twice to try to insert a blank line in the Notes field.

I am unable to reproduce this.  Can you?

It is a standard HTML form with a POST method.  Your browser should not allow you to submit the form twice....

**Comment by miqrogroove** [comment]
Yes.  Chrome 81 for Windows 10.  Pressing Enter twice rapidly in the Notes field submits the form twice.  This is normal behavior for browsers, as far as I know.
