### ISSUE TITLE
2.0.3 - nick names in Descendants report: missing quotation marks

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3237]
In webtrees 2.0.3 the nicknames are placed without quotation marks. This is very confusing!
Example: Willem Willemsen Wim, which should be: Willem Willemsen 'Wim'
Can this be fixed?

Note: issue [#3204](https://github.com/fisharebest/webtrees/issues/3204) was closed without an answer on this question.

**Comment by fisharebest** [comment]
The XML reports will be replaced with PHPOffice reports.  See #3250.
