### ISSUE TITLE
Feature Request: Support streaming of audio/video

### ISSUE THREAD

**Issue by Ziris85** [fisharebest/webtrees#3240]
Hello! It would be nice to be able to stream audio and video files that are uploaded to my site, rather than just being prompted to download them. As a sysadmin by profession, I know that trying to support streaming media on sites can get pretty gnarly with things like ffmpeg, shoutcast servers, etc. However, I know HTML5 supports this natively, with something like:
```
<audio controls>
<source src="data/path/to/audio.ogg" type="audio/ogg" />
</audio>
```
I wish I knew enough about PHP development to offer a patch or module to do this, but since I don't I figured I would just throw the idea out there if it's something you/someone might consider adding. As far as design, I was thinking for audio it could just be an in-line player wherever the media is referenced, and for video it could be a pop-out modal like images are, with the player embedded in there.

Would something like this be practical? Just something like "If HTML5 supports streaming of media type, show player, else prompt download". I've started doing audio recordings of my relatives talking about people/places/experiences/etc, and it would be very nice to be able to listen to them straight from my tree site.

Thanks for your time and consideration :)

**Comment by fisharebest** [comment]
Embedding media players is pretty trivial.

Decided where to use them is harder.  For example, in a "chart box", it probably wouldn't make sense.  In the auto-complete results, it definitely wouldn't make sense.

The only place it might make sense to embed a media place is on the media-object page itself, where we list each of the media files.

**Comment by Ziris85** [comment]
Yes, that sounds exactly what I'm looking for! I was excited to see it in action, so I applied your diff patch to my site, but weirdly nothing appears to have changed - I still see no media player controls. I looked in both the individuals Media tab (which I figured you were referring to) and the "Media objects" List view, and in both places it's still just giving me a download-only option.

After reviewing your patch and doing some experimenting, I tweaked it slightly and that allowed the media player to pop up and allow me to play!
From
```
<?php if (explode('/', $media_file->mimeType())[0] === 'audio') : ?></php>
<audio controls>
<source src="<?= e($media_file->downloadUrl('inline')) ?>" type="<?= $media_file->mimeType() ?>"> 
```
To
```
<?php if (explode('/', $media_file->Type())[0] === 'audio') : ?></php>
<audio controls>
<source src="<?= e($media_file->downloadUrl('inline')) ?>" type="audio/<?= $media_file->Format() ?>">
```
Thoughts on this adjustment? Also, this only shows the player on the media objects page. Would it be possible to have this also show up in the Media tab as well, on the individuals page?

**Comment by fisharebest** [comment]
Here's a link to the demo site with the new code.

https://dev.webtrees.net/demo-dev/tree/demo/media/m57/Queen-Elizabeth-II-s-christmas-message-2011

Does this work for you?

> Thoughts on this adjustment?

I'd need to know what your data actually looks like.

You are presumably replacing the mime-type `audio/mpeg` with `audio/mp3` (not a valid mime type?)

See the docs at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio

**Comment by Ziris85** [comment]
Hmm, so it does (your demo site working). I think the reason yours worked is because your mp3 file was correctly detected as an audio file. The mimetype for my .ogg file is detected as `Format: application/octet-stream`, which I suppose means that it can't determine what type it is? Or thinks it's a binary file? On an interesting/funny point, I converted the file to mp3 and uploaded it to my site with my modified code and it still played, so at least in Firefox, it'll use `audio/mp3` lol.

I'm not sure why PHP is determining my ogg file to be a binary file:
```
[root@web familytree]# file data/media/my_audio.ogg 
data/media/my_audio.ogg: Ogg data, Vorbis audio, mono, 16000 Hz, ~64000 bps, created by: Xiph.Org libVorbis I
```

**Comment by fisharebest** [comment]
I guess we need a few more definitions in the list:
https://github.com/fisharebest/webtrees/blob/master/app/Mime.php

**Comment by fisharebest** [comment]
According to various online references, you should use `.oga` for ogg audio.

**Comment by Ziris85** [comment]
A-ha! OK, I mirrored those adjustments to my `app/MediaFile.php` file, and it now shows properly! And it looks like .oga files are for audio files with `FLAC, Ghost, and OggPCM` encoding, though ogg files are for those using Vorbis (as mine is), if I'm interpreting that documentation correctly.

But anyway, with that addition, the icon now shows with musical notes, and clicking on it gives me a player in a new page. This is great! Really excited to start uploading these things now.

My last request, if it would be possible, is to have the media player in-line in the Media tab, rather than going to a separate window? If that's not practical, I can live with this how it is, I just think having it play on the same page would flow better.
