### ISSUE TITLE
Latest beta send mail fails

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#3241]
I am using sendmail on my production site, and I recall it use to work.  Now, if I send a test message I get 
MailService: Unsupported sendmail command flags []. Must be one of "-bs" or "-t" but can include additional flags.

**Comment by fisharebest** [comment]
Which version of webtrees?  2.0.3 or latest dev.

There were some recent changes to sendmail.

Previously, we used the library's default (`/usr/sbin/sendmail -bs`).

Now we allow the user to specify their own command instead of the default.
http://webtrees.net/faq/email/

**Comment by makitso** [comment]
Sync'ed to git this morning.  If I change to SMTP I get:

MailService: Failed to authenticate on SMTP server with username "robert.peters@skatekey.net" using 2 possible authenticators. Authenticator LOGIN returned Expected response code 235 but got code "535", with message "535 5.7.8 Error: authentication failed: UGFzc3dvcmQ6 ". Authenticator PLAIN returned Expected response code 235 but got code "535", with message "535 5.7.8 Error: authentication failed: UGFzc3dvcmQ6 ".

**Comment by makitso** [comment]
OK, I had the password wrong for SMTP, it now works.  However, Sendmail still fails.

**Comment by makitso** [comment]
Yes, that fixed the problem, Sendmail now works.
