### ISSUE TITLE
Logs contain password

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#3242]
In Admin / Sending email, if I change the password and so a save the password shows up in the log file.

Site preference "SMTP_AUTH_PASS" set to "Sunshinexxxxxx"

**Comment by fisharebest** [comment]
This password is stored in plain text in the database (`wt_site_settings`) - but never displayed on screen.

So, the impact is when you have multiple admins on a site, and the password is private to just one of them.

**Comment by makitso** [comment]
OK.
