### ISSUE TITLE
Latest commit(s) break display

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3245]
For Colours & related themes.

see image from demo-dev

![demo](https://user-images.githubusercontent.com/104515/82039652-36b3b400-969d-11ea-827a-1470b7cb7472.jpg)

**Comment by ddrury** [comment]
I'm not entirely sure about this but I think it's bootstrap 4.5.0 thats the problem

**Comment by ddrury** [comment]
bootstrap 4.5.0 sets min-width to 0 for class col. Setting it to auto for class wt-secondary-navigation fixes the above problem but where else does this occur I wonder?

**Comment by fisharebest** [comment]
Changing the rule for `.secondary-navigation` from `flex: 0 0 0` to `flex: 0 0 content` seems to fix it.

**Comment by ddrury** [comment]
I intended to edit my last comment to say that changing the min-width setting proved that it was a bootstrap inititiated problem not as a "proper" fix.

But I forgot ;(

Your's is obviously the real solution

**Comment by fisharebest** [comment]
We need the same change on `.wt-site-title`.

Now seems to work the. same as previously.

**Comment by makitso** [comment]
The clouds these is fixed but colors is still bad -- on the demo site.

**Comment by fisharebest** [comment]
I assumed that colors would inherit this markup from clouds.

Running a diff on `clouds.css` and `colors.css`, it seems that there are lots of places where colors has repeated the definitions from clouds.  These ought to be removed.

I've copied the two changes over to colors.  I'll leave this issue open as a reminder to remove all the duplicates definitions.

**Comment by makitso** [comment]
Still not quite right  

![image](https://user-images.githubusercontent.com/5147603/82130923-9df86380-9784-11ea-94e3-3d298ad9eb67.png)

**Comment by makitso** [comment]
The problem gets worse.  The FAB and Minimal themes are also messed up.
With the latest patch, using Chrome and FF, I  reduced the size of the screen down to mobile size.
The secondary menu no longer collapses correctly.  If I do the same with the current 2.0 prod it works fine.

![image](https://user-images.githubusercontent.com/5147603/82131286-612e6b80-9788-11ea-82b9-6309ca0aba8d.png)

**Comment by ddrury** [comment]
The problem as mentioned by Rob above is also present in Edge (not surprising I suppose as it uses Chromium's rendering engine)

**Comment by ddrury** [comment]
Greg,
See https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis. Particularly Values - content
As suggested making the settings:
flex: 0 0 auto;
width: auto;
seems to work;

**Comment by ddrury** [comment]
And https://caniuse.com/#feat=mdn-css_properties_flex-basis_content

**Comment by fisharebest** [comment]
I've tried all the themes on mobile and desktop - and don't see anything obviously wrong...
