### ISSUE TITLE
after death not translated

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#3254]
![translation](https://user-images.githubusercontent.com/55854079/82127403-884e6280-97b3-11ea-86c9-6e3ce1477c3d.jpg)

**Comment by mpwt** [comment]
There are missing translations in different languages. See f.i. under https://translate.webtrees.net/projects/webtrees/webtrees/es/.

**Comment by fisharebest** [comment]
Previously, the `(` and `)` were part of the code, and only the text between them was a translatable string.

Now the `(` and `)` are part of the translated string - because some languages use different characters for these symbols.

So, this is a new/untranslated string.

As @mpwt says, we are just waiting for a Spanish translator to create a new translation.

**Comment by HRN65** [comment]
My bad. Was sure I had the latest language files (nn and nb). 
By the way, norwegian nn and nb are missing in demo Current and Latest

**Comment by fisharebest** [comment]
> Was sure I had the latest language files (nn and nb).

Your probably **do** have the latest files.

The issue is that nobody has translated these texts (yet).

**Comment by HRN65** [comment]
I translatet nb and nn about a week a go. They show 100% translated??

**Comment by fisharebest** [comment]
Your screendump looks like Spanish.

Spanish is not translated.

**Comment by HRN65** [comment]
Yes, I changed to spanish as there was no norwegian on Demo site. Both nb and nn are missing

**Comment by fisharebest** [comment]
Ah - you didn't mention that it was the demo site.

It needs manually updating to get the latest translation files.  I'll see if I can automate this....

**Comment by HRN65** [comment]
Appears my test site has the latest (100%) nb and nn language files. Not my live site. 
My bad (embarrassed)

**Comment by fisharebest** [comment]
OK - the demo site should now refresh its translation files every time it is updated (every hour).

**Comment by HRN65** [comment]
Thanx
