### ISSUE TITLE
Places Map Sometimes Doesn't Work

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3255]
When I hit an individual page for the first time during a session, the Places tab and map works normally.

If I switch to another tab, such as Album or Facts and events, and then refresh the page, the Places tab will not work correctly.  I get a blank map and have to refresh the page again with the Places tab active.

**Comment by ddrury** [comment]
I can't reproduce this at all, When you say "will not work correctly" what happens? Any errors anywhere?

**Comment by miqrogroove** [comment]
Every time I follow those steps, it looks like this:
![bug](https://user-images.githubusercontent.com/1371835/82148149-91c1e400-9820-11ea-8c52-1b698afa603f.png)

**Comment by ddrury** [comment]
A few things to try in order. Using the Browser developer tools

- On the network tab, anything unusual? any error statuses? you should see a number of images received from <letter>.tile.openstreetmap.org are they OK
- On the console tab, there should be a line XHR GET (current page). If you expand it and click on the response tab - Response payload, does the result look like` webtrees-2.0\resources\views\modules\places\tab.phtml`?

If these are both OK, insert the following at line 99 of tab.phtml (3rd line of _buildMapData) `console.log(data);` you should then see in the console tab `Object { type: "FeatureCollection", features: (x) […] }` where x is the number of events for this person.

**Comment by miqrogroove** [comment]
I'm still getting status 401 for `/public/site.webmanifest?v=2.0.3` in the Console and Network tabs.

Literally the only tile being loaded is `https://c.tile.openstreetmap.org/2/1/1.png` unless I refresh the page.

XHR GET is disabled by default for the Console tab.  After enabling that, I do see it fetched `/module/places/Tab/tree1?xref=...` and when expanded there are several mentions of `vendor.min.js?v=2.0.3:2`

**Comment by miqrogroove** [comment]
And sorry but I don't know how to find the file you mentioned.

https://github.com/fisharebest/webtrees/search?q=mapdata+filename%3Atab.phtml&unscoped_q=mapdata+filename%3Atab.phtml

**Comment by miqrogroove** [comment]
`{type: "FeatureCollection", features: Array(18)}`

I should point out that the blue sidebar is working in this situation.  It's only the map itself that's messed up.

**Comment by miqrogroove** [comment]
Also could not find any "response tab".  Still uncertain if my DevTools is configured the same as yours.

**Comment by ddrury** [comment]
Ah, I assumed from your snapshot above that only a portion of the page was being rendered, so are you getting the complete page but with parts of the map missing? I've seen this before when the openstreetmap site fails to return all the tiles in time. What's your network service like?

And refreshing the page does often help. If you're not seeing any error messages anywhere then this may be the problem.

I have a feeling I've seen somewhere that OSM can limit the number of requests made in a short time - I've just googled that but couldn't find anything.

**Comment by miqrogroove** [comment]
None of that sounds correct.  This problem is happening EVERY TIME the page is loaded with a tab other than Places being active.

**Comment by ddrury** [comment]
Whats the site url so we can have a look

**Comment by miqrogroove** [comment]
If you could contact me here, I will set that up privately https://www.miqrogroove.com/contact/

**Comment by ddrury** [comment]
Hi,
I completed the form but the response was 403 forbidden, so I don't know if the message was sent or not

**Comment by miqrogroove** [comment]
Probably not.  I'll put that on my to do list.  How about miqrogroove@gmail.com

**Comment by ddrury** [comment]
Thaks for the user details.

Bad news (for you) is that with Firefox, Chrome & Edge, it always works fine. All combinations of page refresh and changing tabs.

As far as I can see the only difference between us is that each user (me in this case) is fetching the map tiles from openstreetmap using their own broadband connection.

**Comment by miqrogroove** [comment]
According to DevTools my browser isn't trying to fetch any tiles.  That would be a significant difference.

**Comment by ddrury** [comment]
I really don't know what else to suggest. Image taken from Firefox
![demo](https://user-images.githubusercontent.com/104515/82347284-54f81780-99ef-11ea-9fde-68485c228a3f.jpg)

**Comment by miqrogroove** [comment]
Chrome before refresh
![screen1](https://user-images.githubusercontent.com/1371835/82347536-c15e2100-99c5-11ea-8601-aa6826b243e7.png)

Chrome after refresh
![screen2](https://user-images.githubusercontent.com/1371835/82347644-e6529400-99c5-11ea-8c07-91128d052e60.png)

I'm not very handy with Javascript so not sure how to debug this.

**Comment by ddrury** [comment]
I've had a look on Chrome and the map tiles are on your second image 92, 93, 94.png etc. If you hover the mouse over them you'll see something like https://c.tile.openstreetmap.org/n/nn/nn.png. The only difference I can see is that you're using the disk cache, I'm using memory.
I assume you've already cleared your browser cache?
Desperation suggestion ... Developer Tools - Network tab, on the next line Disable cache (while DevTools is open)

**Comment by miqrogroove** [comment]
I was able to replicate the same problem on my cell phone, but could not replicate it after momentarily switching off the Wi-Fi.  This leads me to wonder if the problem could be related to DNS caching.  If webtrees or OSM is doing a lookup on a shady hostname, there's a very small chance that it's blocked on my network.  But that doesn't explain why it works after refresh.

**Comment by miqrogroove** [comment]
I've also noticed that every time I switch back to the Wi-Fi, the Map tab is giving me two different zoom levels.  If I refresh with Places active, I get the expected zoom level.  If I refresh with a different tab and then switch to Places, I get the map fully zoomed out.

**Comment by miqrogroove** [comment]
I've eliminated any server issues by tethering my desktop to my cellphone and watching DevTools.  There is no difference whatsoever in the XHR and server responses.  The only difference is on the cell network the client script is requesting different images.

What I need here is a way to determine why the client script is requesting different images on different connections.  There is definitely a scripting bug here.

**Comment by ddrury** [comment]
` The only difference on the cell network is that the client script is requesting different images`
Probably due to screen size - smaller screen, smaller images.
All the mapping heavy lifting is done by leafet.js. See https://leafletjs.com/ and we are using 1.6.0

**Comment by miqrogroove** [comment]
> Probably due to screen size - smaller screen, smaller images.

You are not understanding this at all.  When I switch networks on my desktop computer, Chrome requests different images.  This has nothing to do with screen size.

**Comment by ddrury** [comment]
OK I give up - it works for me

**Comment by fisharebest** [comment]
I can't reproduce this either.

When I return to the map, I find that it loads much faster, as the tile images are already in my browser's cache.

@miqrogroove - does this happen on a public page on your site?  If not, can you create a public tree/page with some test data?

**Comment by miqrogroove** [comment]
I've established the bug is somehow sensitive to client network.  I don't know if the same bug would show up on a different server.  I will have to tinker more.  Is there already a demo site somewhere?

**Comment by miqrogroove** [comment]
Tried comparing local and remote servers on v2.0.4.  I can only reproduce the problem on the local server.  Something in that map script is not compatible with my network.

**Comment by miqrogroove** [comment]
Woah hold on... I just broke the map on the remote server while adjusting the control panel settings.

**Comment by miqrogroove** [comment]
So where I'm at now is the John DOE facts & events on one screen and DevTools on the other screen with Network tab and "Disable cache" ticked.

https://wp-test.miqrogroove.com/tree/tree1/individual/X1/John-DOE

If I set a timer for 10 seconds and then hit the Reload button in Chrome, followed by switching to the Places tab, this is giving me about a 50% fail rate.

On my local server, it's a 100% fail rate.

**Comment by miqrogroove** [comment]
Having some luck debugging this today.  I've eliminated almost all of the code in vendor.min.js as suspects, leaving me with just a couple more functions and the HTML to debug.  My goal is to either find the exact bug or point you to the line(s) of code that are misbehaving when I load the Places tab.

**Comment by fisharebest** [comment]
Thanks for the update.

**Comment by miqrogroove** [comment]
Thanks for the quick reply.  Since you're online I can tell you exactly how far I've traced this.  Nothing unusual happening at a low level with the map tiles.  Currently, when I trigger the bug vs. refresh without the bug, I am seeing identical inputs sent from `_buildMapData` into `fitBounds()`, but then inside of fitBounds the call to `this._getBoundsCenterZoom()` is returning different `zoom` values and passing them into `this.setView()`

I'm just now getting around to tracing _getBoundsCenterZoom to see if there is any obvious underlying relationship to the tab status.

**Comment by miqrogroove** [comment]
Here we go.

Before the getBounds code does its fancy math, it's checking two specific properties of the `osm-map` element that are not initialized with expected values.  You can search for them in vendor.min.js.

`this._container.clientWidth`
`this._container.clientHeight`

When I load the page with the Places tab in the background, the clientWidth and clientHeight properties are both set to zero.

I haven't gone any further to explain why this does not happen in every situation.  I'm hoping someone else can pick this up and run with it.

**Comment by miqrogroove** [comment]
For a basic next step, I found that I can type this in the DevTools Console:

`document.getElementById("osm-map").clientWidth`

Any time the Places tab is not in the foreground, that command returns zero.  So I'm thinking there's a timing issue with the map trying to load too early after a tab switch.

**Comment by miqrogroove** [comment]
Here is a workaround:

https://github.com/fisharebest/webtrees/blob/48b5fb7d0ea72448ce71d762405f74888f03b226/resources/views/modules/places/tab.phtml#L188

Replace with:
```
        if ( ! document.getElementById("osm-map").clientWidth ) {
                setTimeout(_buildMapData, 250);
        } else {
                _buildMapData();
        }
```

**Comment by ddrury** [comment]
Does this work for you?
in webtrees/resources/views/modules/places/tab.phtml, move lines 187/188
```
        _drawMap();
        _buildMapData();
```
up so they are within the function above so code looks like
```
        $(function() {
            sidebar
           etc ...
            .on('click', 'a', function(e) { // stop click on a person also opening the popup
                e.stopPropagation();
            });
          _drawMap();
          _buildMapData();
        });
```
```
The $(function{} {
}
```
stuff ensures code contained withing it doesn't run until the DOM is fully loaded.

**Comment by miqrogroove** [comment]
> stuff ensures code contained within it doesn't run until the DOM is fully loaded.

No, I tried that earlier.  Also consider if `osm-map` wasn't in the DOM I would get an error instead of zero size.  I tried 100 ms on the timer and that gave mixed results, which is why I increased it to 250.  So there is something happening with `osm-map` and `_drawMap()` that needs to finish properly before calling `_buildMapData()`.

**Comment by fisharebest** [comment]
Perhaps we need to call these functions in response to a leaflet event, such as `load` or something?

https://leafletjs.com/reference-1.6.0.html#map-event

**Comment by miqrogroove** [comment]
Maybe, but I suspect it checks the container before it fires the load event.  Could you point me in the direction of the tab logic file?

**Comment by miqrogroove** [comment]
Going to experiment with this next https://api.jquery.com/load/

I'm not familiar with it at all, but I can see the .load() call runs async and you haven't specified any callback for the tabs yet.

**Comment by miqrogroove** [comment]
That's not it either.  The callback runs right after _drawMap() when osm-map is still zero size.

**Comment by miqrogroove** [comment]
I can make it work with requestAnimationFrame instead of setTimeout but it's still waiting several frames and I don't know if that's the most efficient way to do this.

**Comment by miqrogroove** [comment]
```
        function waitforosm() {
                if ( ! document.getElementById("osm-map").clientWidth ) {
                        window.requestAnimationFrame(waitforosm);
                } else {
                        _buildMapData();
                }
        };

        _drawMap();
        waitforosm();
```

**Comment by miqrogroove** [comment]
I finally found your tab API.

**Comment by miqrogroove** [comment]
I finally found your tab API.

https://getbootstrap.com/docs/4.0/components/navs/#javascript-behavior

`fitBounds()` is called from the wrong event.  You're using `show.bs.tab` for everything but the `osm-map` doesn't render until `shown.bs.tab`

**Comment by miqrogroove** [comment]
```
        _drawMap();
        $('a[href="#places"]').on('shown.bs.tab', _buildMapData);
```

**Comment by miqrogroove** [comment]
Could we prioritize my Pull request before 2.0.6?  I'm happy to help with this one since I've done hours of debugging already.

**Comment by fisharebest** [comment]
Thanks for doing all the hard work on this one.  See my comments on the PR?

**Comment by miqrogroove** [comment]
And thanks for the revision.  Your JS skill is much better than mine.
