### ISSUE TITLE
FamilyCirles API

### ISSUE THREAD

**Issue by msmcgillis** [fisharebest/webtrees#3259]
This is more of an informational thing than an issue or bug. Feel free to close, just wanted to share if anyone is interested enough to experiment with code.

So I put together FamilyCircles https://fc.jenika.com some time ago but I use webtrees to store all my data. To use FamilyCircles I would do a gedcom export of webtrees then convert that to FamilyCircles API data and run a FamilyCircles service with that data to explore. But, I was never happy with maintaining that process and wanted FamilyCircles to be able to talk directly to webtrees to get data.

So I finally got some time to work through it this weekend. I took the 2.0.3 code and forked it then created an fc branch with everything I did. You can find it at:

https://github.com/msmcgillis/webtrees

In theory if you copy all the added/changed files from that to your webtrees you should be able to play with it.

In the tests directory is fctests.html this will let you validate that URL's to your server are generating json responses. For the tests you should see json similar to what is outlined on:

https://fc.jenika.com/api.shtml

If that is all working then you should be able to use:

`https://fc.jenika.com/code/current/explorer?service=http://<yourwebtreesserver>/index.php/fc/<yourtree>`

To begin exploring your data with the explorer.

Some things of note about what I did to webtrees.

1. Modified the ApiRoutes.php to support:
/fc/{tree}/object
/fc/{tree}/object/{id}
/fc/{tree}/config
2. Modified the composer autoloader so it would find FamilyCircles code in the FamilyCircles directory.
3. Modified the BaseUrl.php to support direct paths as well as the route param so either of these work:
http://<someserver>/index.php?route=/fc/xyz/config
http://<someserver>/index.php/fc/xyz/config
Don't really understand the choices around all this but hopefully what I did is transparent to webtrees (I haven't noticed any issues). This change allows explorer to work without customizations.
4. Added header (Access-Control-Allow-Origin) to MediaFileController to allow any browser so explorer is able to pull images and load them from webtrees in browsers. I did this just for my purposes. Probably not that best answer long term, but it is working for what I need. My webtrees server  is not internet accessible so I'm not concerned about images getting pulled.
5. I didn't spend time understanding exactly how access controls works, so for now, I just disabled/commented them out for this. Again not a good answer long term but works for my purposes, although on default I believe it is treating access as a guest so some limitations are still in place.

That is all I had to do for the most part other than including the actual FamilyCircles API code to support the new ApiRoutes but that is all new code that is in the FamilyCircles directory.

So far it is working fairly well for me. If anyone takes a look let me know what you think.

**Comment by hartenthaler** [comment]
Interesting GUI! But not possible to use it for a webtrees server on the public Internet. It should be a webtrees module without violating the security functions, but that's more than my programming skills allow.

**Comment by msmcgillis** [comment]
> It should be a webtrees module without violating the security functions, but that's more than my programming skills allow.

Agree on both points.

Unfortunately currently I was not able to find any module-level support for adding custom paths or services as outlined in the code I developed. I tried creating this initially as a report module but it didn't work. If the URL paths and services were modularized then a good chance this could be done through a module.

On the access side this I think should be relatively easy to resolve depending on requirements/assumptions about the relation between explorer and webtrees. But, I wanted to get something working for me over the weekend I had decided to try and work something out.

What I have is functional for anyone that is PHP technically inclined, if enough interest existed or dialog was generated with what I have shared I was going to decide from that how much more I would put into this. If no one else is interested at all no point in my doing any more than what works for me for now.

I can wait and see if other modules come along that make it easier to support in the future. This is more just a sharing exercise that may help guide the developers in supporting something like what I'm after someday, or not its all good.

I like webtrees as it is and plan to continue to use it and hope the developers find some value in what I have tried to share and demonstrate helps me.

**Comment by fisharebest** [comment]
>  I was not able to find any module-level support for adding custom paths

All modules have built-in support for mapping URLs to functions.

The function `route('module', ['module' => $module_name, 'action' => 'Xxxx', 'tree' => $tree_name]))` will generate a URL which will be routed to your module's `getXxxxAction()` or `postXxxxAction()` method - depending on which HTTP method was used.

The URL will be something like `/module/<module_name>/Xxxxx/<tree_name>`

You can add other parameters.

If you need something more specific, you can register your own custom URLs.  Look at the SiteMap module for an example of this.

**Comment by fisharebest** [comment]
If you need further information or help to create your module, you can ask on the forum or open another issue.
