### ISSUE TITLE
Layout issues on smaller screens

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#3263]
Some layout issues in Statistics block and Messages block on smaller screens 

![1](https://user-images.githubusercontent.com/55854079/82248045-c8464e80-9947-11ea-9e92-884cad36334e.jpg)
![2](https://user-images.githubusercontent.com/55854079/82248052-caa8a880-9947-11ea-8106-4591cd54dfc1.jpg)

**Comment by fisharebest** [comment]
Both these issues appear to be fixed in the latest code
