### ISSUE TITLE
No access to control pannel with pretty URL

### ISSUE THREAD

**Issue by luca74** [fisharebest/webtrees#3267]
Without pretty URL my home is:
https://www.vattovani.it/webtrees/index.php?route=%2Fwebtrees%2Ftree%2FAlbero%2Fmy-page
and the control panel is:
https://www.vattovani.it/webtrees/index.php?route=%2Fwebtrees%2Fadmin.

Enabling pretty URL they become:
https://www.vattovani.it/webtrees/tree/Albero/my-page (OK)
and 
https://www.vattovani.it/webtrees/admin (**error 404**).

I use .htaccess for apache how described in https://webtrees.net/faq/urls/

Thanks
Luca

**Comment by fisharebest** [comment]
Most likely a server configuration issue.

Maybe you have some sever-security software which is blocking `admin` URLs?

To test this, you could try changing `admin` so something else:

https://github.com/fisharebest/webtrees/blob/2.0.4/app/Http/Routes/WebRoutes.php#L197

**Comment by luca74** [comment]
I tried,
with pretty URL:  https://www.vattovani.it/webtrees/**aministra** not accessible
without https://www.vattovani.it/webtrees/index.php?route=%2Fwebtrees%2F**aministra** usable

**Comment by fisharebest** [comment]
> To test this, you could try changing `admin` so something else:

Perhaps `aministra` is a bad choice.  If you have security software that blocks URLs containing `admin`, then it will probably also block other langauges.

Choose a random word/letters.

**Comment by luca74** [comment]
Ok. Now it works.
Thank you

**Comment by luca74** [comment]
Today I try to access "Manage family trees" with pretty URL enabled and...
the link created report "admin" instead of alternative name
Control panel URL: https://www.vattovani.it/webtrees/pannello
but Manage tree URL: https://www.vattovani.it/webtrees/admin/trees/manage/Albero

**Comment by fisharebest** [comment]
`/admin` is also defined here:

https://github.com/fisharebest/webtrees/blob/2.0.4/app/Http/Routes/WebRoutes.php#L306

You must also change this line.

**Comment by luca74** [comment]
Ok. 
Done.
It works.
Thanks.

**Comment by luca74** [comment]
At each update I have to change again in order to make the site work.
I can propose to change "admin" to "admin-site" or something similar

**Comment by fisharebest** [comment]
This is an issue with the server configuration.

It is blocking URLs that are used by webtrees.

This is not a problem with the code.
