### ISSUE TITLE
Emoji-flags not correctly displayed in the "historic" modules.

### ISSUE THREAD

**Issue by ro-la** [fisharebest/webtrees#3268]
In the "historic" modules there  should be a flag icon (at least I think). Does not work (for me) in Firefox and Chrome. Tested on Windows 7. On android smartphone it works OK.

The page https://emojipedia.org/flag-austria/ is displyed in firefox correctly, in chrome (based) browsers (Chrome, Opera) not.

Screenshot from Firefox - also the icons in the bottom rows are missing.

Ladislav

![image](https://user-images.githubusercontent.com/60657963/82264530-5aa91b00-9965-11ea-80b2-a6a8670c22b0.png)

_Originally posted by @ro-la in https://github.com/fisharebest/webtrees/issues/3265#issuecomment-630463762_

**Comment by fisharebest** [comment]
> Tested on Windows 7.

Windows 7 has very little support for emoji.

There is nothing that we can do.

Note that for systems without emoji support, the flag emoji are designed to show as the country-code letters.  So, you will see `GB`, `AT`, etc.
