### ISSUE TITLE
Create (working) package (and update wiki) for CentOS

### ISSUE THREAD

**Issue by castedo** [fisharebest/webtrees#327]
RPM packages are currently built on https://build.opensuse.org/ for SUSE distros. I use the one for SLES 11 SP3. Installation instructions for this package are found at 
http://wiki.webtrees.net/en/Installation_using_RPM
The now closed enhancement #35 tracked that work.

This work item is to make a working package for CentOS 7 and update the wiki instructions for CentOS.

**Comment by castedo** [comment]
Here is some status on my progress so far on CentOS.

Some important discoveries:
1) ZendFramework version 1 does not appear to be in the CentOS 7 repositories (i.e. not base, not updates nor EPEL), only ZendFramework version 2 appears to be supported (and my understanding is the currently plan is for webtrees to not upgrade to ZendFramework2 which is not backwards compatible)
2) php-xml is a dependency, setup.php initially errorer out with DOMDocument not found when php-xml was not installed

I have built a package on CentOS and setup.php runs with SELinux NOT in enforcing mode. When SELinux enforcing mode is on then webtrees is getting permissions rejected. I'm still looking into this.

The package in progress is a fork on Open Build Service and is here:
https://build.opensuse.org/package/show/home:castedo:branches:server:php:applications/webtrees
The main things I needed to tweak was adding php-xml and using the subset of ZendFramework v1 that is inside the webtrees zip file (since ZF1 is not in the CentOS 7 distro).

**Comment by castedo** [comment]
For those curious on what SELinux is not permitting webtrees to do, it is this:
```
type=AVC msg=audit(1421360235.733:400): avc:  denied  { write } for  pid=11699 comm="httpd" name="cache" dev="xvda1" ino=26534589 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:httpd_sys_content_t:s0 tclass=dir
type=SYSCALL msg=audit(1421360235.733:400): arch=c000003e syscall=21 success=no exit=-13 a0=7f03f896e0b0 a1=2 a2=0 a3=1 items=0 ppid=11697 pid=11699 auid=4294967295 uid=48 gid=48 euid=48 suid=48 fsuid=48 egid=48 sgid=48 fsgid=48 tty=(none) ses=4294967295 comm="httpd" exe="/usr/sbin/httpd" subj=system_u:system_r:httpd_t:s0 key=(null)
```
I think this is because everything under /var/www gets the SELinux context httpd_sys_content_t and this does not permit writing (it is supposed to be static content).
But setup.php wants to write to /var/www/webtrees/data/cache/ and this is the denied write above.

**Comment by castedo** [comment]
I’m planning to switch my webtrees server from SLES to CentOS 7 this week and hopefully today commit a new webtrees package to my branch on Open Build Service.

By default SELinux is enabled on CentOS 7 and SELinux controls whether the httpd (Apache) process has write access to particular files, independent of the classic UNIX file permissions. 

The normal default setup on CentOS 7 appears to be to have files under `/var/www` as READ-ONLY to the httpd process (with the `httpd_sys_content_t` context type). In contrast, by default, the httpd process has write access to the directory `/var/lib`. I can go into details if anybody is interested.

With all this in mind, I am thinking that the proper thing to do with a webtrees package on CentOS is to do the following:

1. everything that goes into the webtrees “data” subdir goes into `/var/lib/webtrees`
2. everything else goes into `/var/www/webtrees` (what is `/srv/www/webtrees/static/` in SLES)
3. a symbolic link `/var/www/webtrees/data` to `/var/lib/webtrees` (instead of `../data` in SLES)

I’ve tested this today and this seems to work fine with SELinux enabled and enforcing.

There is some subtlety with the `var_lib_t` SElinux context type vs `http_var_lib_t` that I don’t fully understand, but so far this isn’t a problem. But I suspect the proper thing to do is to have an addition package with an SELinux policy that labels the `/var/lib/webtrees` directory with the `httpd_var_lib_t` context rather than the default `var_lib_t` context type.

Let me know if you guys have any insights or other ideas.

**Comment by castedo** [comment]
I have committed changes to Open Build Service, here is the diff with the semi-official server:server:php:application/webtrees:

https://build.opensuse.org/package/rdiff/home:castedo:branches:server:php:applications/webtrees?opackage=webtrees&oproject=server%3Aphp%3Aapplications&rev=5

@weberhofer, do you want me to submit a package request update on OBS?

**Comment by castedo** [comment]
On my production server I am now using the package created in home:castedo:branches:server:php:applications/webtrees

I also have also add the command:
"semanage fcontext -a -t httpd_var_lib_t /var/lib/webtrees"
to my personal setup script for configuring webtrees. Otherwise if a relabeling of SELinux file contexts happens in/var/lib/webtrees then existing files will no longer be writable. This doesn't appear to cause a major problem but it is definitely best to run semanage as part of the overall configuration and setup.

I should update the Wiki to reflect this and other steps taken to install on CentOS 7.

**Comment by fisharebest** [comment]
I have added a link to the package at https://webtrees.net/install/
