### ISSUE TITLE
Whitespace Not Preserved When Editing Source Text

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3270]
Edit: Noticed the editing does work.  It's the Sources tab where leading whitespace seems to be missing.

Would it be possible to display the text so that it looks more like it does on the editing page?

**Comment by fisharebest** [comment]
Can you give a specific example?

Do you enable "markdown" formatting on your site?

**Comment by miqrogroove** [comment]
Yes, markdown enabled.  I'm just indenting paragraphs with one or two spaces sometimes.

```
  Hello world.  This is formatted
for input.  So it looks nice.
```

Does markdown strip that out?

**Comment by fisharebest** [comment]
>  I'm just indenting paragraphs with one or two spaces

HTML collapses whitespace by default.
To indent paragraphs for presentation, perhaps use a non-breaking space?

> Does markdown strip that out?

I seem to remember that 2 (or 3? or 4?) spaces at the start of a line are signficant.  I will need to check the documentation to be certain.

**Comment by fisharebest** [comment]
4 leading spaces are used to select a fixed-width font.

**Comment by fisharebest** [comment]
> ```
>   Hello world.  This is formatted
> for input.  So it looks nice.
> ```

You also use two spaces after a `.`.

Trying to preserve whitespace is a battle against HTML - and I think we will lose...

If you want the first line of *all* paragraphs to be indented, then this is easier.
Add the following CSS in the control panel (CSS+JS module)

<style>
.markdown > p { text-indent: 1rem }
</style>

**Comment by miqrogroove** [comment]
I looked at the individual page source and it looks like all the leading spaces get stripped out.

```
  Hello world,
this should be
nicely formatted.
  And this would be
paragraph #2.
```

prints as

```
<div class="markdown" dir="auto"><p>Hello world,
this should be
nicely formatted.
And this would be
paragraph #2.</p>
</div>
```

**Comment by miqrogroove** [comment]
```
&nbsp;&nbsp;Hello world,
this should be
nicely formatted.
&nbsp;&nbsp;And this would be
paragraph #2.
```
prints as
```
<div class="markdown" dir="auto"><p>  Hello world,
this should be
nicely formatted.
  And this would be
paragraph #2.</p>
</div>
```
I guess I can use that as the workaround.
