### ISSUE TITLE
Big icons in index page blocks and in lists - 2.0.4 & 2.0.5-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3272]
I see huge gender icons and anniversary icons in the On this day. Upcoming events and Yahzeiten blocks of the home page and my page and in lists in the FAB and in the minimal themes. The icons on my test sites and in the demo sites are male, female and unknown gender icons and the anniversary bells.

![image](https://user-images.githubusercontent.com/5202996/82357172-63552c00-9a0d-11ea-8fff-6d2951050668.png)

**Comment by mrqd9** [comment]
An immediate upgrade is needed on this fix.

**Comment by fisharebest** [comment]
It has been reported

See #3265
