### ISSUE TITLE
I do not want religious fact icons on my site - 2.0.5-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3274]
The current xenea cemetery and death icons include crosses. Christian, muslim, buddhist, atheist, etc. icons are improper on my site.

![CEME](https://user-images.githubusercontent.com/5202996/82359331-6e5d8b80-9a10-11ea-9dcd-b81013fcf505.png)  ![DEAT](https://user-images.githubusercontent.com/5202996/82359344-71f11280-9a10-11ea-82fc-7d8ea5ee8c49.png)

**Comment by fisharebest** [comment]
You can disable all the fact icons in the control panel.  (Family tree -> Preferences -> Fact icons).

You can disable specific fact icons in the control panel.  (Modules -> CSS & JS -> Add to <head>)

```
<style>
.wt-fact-icon-BURI {content: none;}
.wt-fact-icon-DEAT {content: none;}
</style>
```

You can replace specific icons with your own.  Store them somewhere in the /public folder and use them like this:

```
<style>
.wt-fact-icon-BURI {content: url(/public/.../burial-icon.png);}
.wt-fact-icon-DEAT {content: url(/public/to/.../death-icon.png);}
</style>
```

**Comment by fisharebest** [comment]
I hope that one of these options will give you what you need.  If I can help further, just ask.
