### ISSUE TITLE
Visibility of information 

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3275]
Visitors can see [this person](http://ahnen.hartenthaler.eu/tree/ahnen/individual/I569/Gabriele-Margarete-Tschichholz-Gabi) because she is already in heaven. In Control Panel / Manage family trees / Privacy / Privacy restrictions of webtrees 2.0.4 there is a specification that for all records the Email address should be shown to members only. But it still visible for visitors.
![Screenshot (94)](https://user-images.githubusercontent.com/6324175/82376959-3449b500-9a23-11ea-8b2b-dd013da25299.png)
![Screenshot (93)](https://user-images.githubusercontent.com/6324175/82377055-5d6a4580-9a23-11ea-96af-84be43992ed1.png)

**Comment by fisharebest** [comment]
See the documentation page for privacy - https://webtrees.net/user/privacy/

Your data contains an attribute (i.e. level 2 GEDCOM data).

`0 INDI / 1 RESI / 2 EMAIL`

It is not possible to apply privacy to attributes.  (But see the documentation for a workaround).

What you have done is create a privacy rule for an "email fact".
e.g. `0 INDI / 1 EMAIL`.
Note that there is no such GEDCOM fact!  This is invalid GEDCOM - but some other programs create such data.

The same is true for phone and fax.  These are attributes - but some other programs will wrongly create them as facts.
