### ISSUE TITLE
Translation error (German language)

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3276]
on webtrees 2.0.4 "Control panel / User administration / Edit the user" there is a wrong translation: "Manager" should be "Verwalter".

![Screenshot (95)_LI](https://user-images.githubusercontent.com/6324175/82378846-2cd7db00-9a26-11ea-9162-39ed4eeded8c.jpg)

**Comment by fisharebest** [comment]
Translations are updated on the translation server - https://translate.webtrees.net

We will need a German translator to update this item.

https://translate.webtrees.net/translate/webtrees/webtrees/de/?q=+source%3Amanager+role+&type=all&ignored=False&checksum=&offset=

Perhaps you can do this?  Create an account on the translation server, and you can make updates directly.
