### ISSUE TITLE
Age bug in french translation

### ISSUE THREAD

**Issue by bombaata** [fisharebest/webtrees#3277]
Appeared on version 2.0.4, didn't show on 2.0.3.

The age sentences are incorrect.

🇫🇷 French translation :
![image](https://user-images.githubusercontent.com/65110137/82417252-9209eb80-9a7b-11ea-8eb7-5fdb2f448bb8.png)
Should be :
- (âgé de 1 jour)
- (âgé de 26 ans)

**Comment by fisharebest** [comment]
Translations are managed on the translation server - https://translate.webtrees.net

I think these are the incorrect translations (fr and fr_CA).

https://translate.webtrees.net/translate/webtrees/webtrees/fr/?q=%28aged&type=all&ignored=False&checksum=&offset=

https://translate.webtrees.net/translate/webtrees/webtrees/fr_CA/?q=(aged&type=all&ignored=False&checksum=&offset=

You can fix these yourself!

Create an account on the translation server and update them.

The changes will be added to the code automatically.

**Comment by bombaata** [comment]
other way, modify file resources/lang/fr/messages.php line 73 for :
`'(aged %s)' => '(âgé de %s)',`
instead of
`'(aged %s)' => '(âgé de %s ans)',`
