### ISSUE TITLE
allow for front-end->back-end reverse proxied configuration

### ISSUE THREAD

**Issue by wkitty42** [fisharebest/webtrees#328]
based on my posts here: http://www.webtrees.net/index.php/en/forum/help-for-ver-1-6-1/29923-can-t-login-redirected-to-internal-domain-name

the problem is that accessing webtrees via internal and external domain names from within the internal network causes problems with the generated URLs in webtrees and the domain stored in the session cookies which prevents logging into the webtrees site... the above link provides a quick fix for the two problems but needs something additional for more security...

**Comment by fisharebest** [comment]
Googling this suggests that it is unwise to blindly trust HTTP_X_FORWARDED_SERVER, and that you need to configure a list of trusted proxies.

Since you couldn't configure this without being logged in - and you can't login with configuring it, it might be difficult to implement ;-)

Perhaps we should assume that anyone capable of configuring a reverse-proxy is also capable of changing a line or two in the source code?

**Comment by wkitty42** [comment]
On 1/31/2015 4:27 PM, Greg Roach wrote:
> Googling this suggests that it is unwise to blindly trust
> HTTP_X_FORWARDED_SERVER, and that you need to configure a list of trusted proxies.
>
> Since you couldn't configure this without being logged in - and you can't login
> with configuring it, it might be difficult to implement ;-)
>
> Perhaps we should assume that anyone capable of configuring a reverse-proxy is
> also capable of changing a line or two in the source code?

i can easily agree with that since i'm one that has to use reverse-proxy for 
access to my webtrees ;)

i'm not sure where this is going but perhaps there can be a simple file in a 
protected admin directory or some such where we can define the ip of the 
authorized servers that must appear in the forwarded-for field?

-- 
NOTE: No off-list assistance is given without prior approval.
       Please keep mailing list traffic on the list unless
       private contact is specifically requested and granted.

**Comment by fisharebest** [comment]
Given the various ways in which proxies/servers can be configured, I think this would involve a disproportionate amout of testing for the benefit involved.  Sorry.

The current focus of development is re-factoring to allow us to use a PHP framework - maybe something symfony based such as Laraval.  When this happens, we can use their algorithm/configuration for this.
