### ISSUE TITLE
email "from name" is webtrees

### ISSUE THREAD

**Issue by marafa** [fisharebest/webtrees#3282]
i searched the wiki and the issue q and could not find an answer

when sending emails from webtrees the `from:` name is webtrees.

how do i change it to my site name? or other?

i do not see any field in the "website preference" to change the name. i intend to only have one family tree. if there is any additional family tree then there iwll be a main family tree until the other trees are merged into the main one.

site: [shagarat.com](https://shagarat.com)

**Comment by fisharebest** [comment]
> how do i change it to my site name? or other?

webtrees must be able to send email in circumstances where there is no tree.  For example, when registering on a private site.  Therefore we cannot use the tree name as the sender for system generated emails.

**Comment by marafa** [comment]
there is a tree
the tree has a name
the family tree title is set
the from email is set
the from name is "webtrees"
title header tag is set
description meta tag is set

from what you say this looks to be a bug as it doesnt use the tree name

**Comment by fisharebest** [comment]
> there is a tree

Not always.

If all trees are private, and a new user registers, there is no tree.

**Comment by ric2016** [comment]
Note: This is also discussed in the forum:
https://www.webtrees.net/index.php/en/forum/help-for-2-0/34502-newbie-change-email-address-from-name

We could still make the sender name configurable, independent of the tree name.

**Comment by Catreina** [comment]
> > how do i change it to my site name? or other?
> 
> webtrees must be able to send email in circumstances where there is no tree. For example, when registering on a private site. Therefore we cannot use the tree name as the sender for system generated emails.


Ah, but you COULD EASILY add in an option to have the SITE WIDE configuration (where emails are configured) to have a NAME for the emails generated (like you do with hard-coded "webtrees" in SiteUser.php). 

Pretty lazy to just throw aside customization of email from: names, and then to close a legitimate ticket for it.  It is stupid to have to hack core files to change such a legitimately requested option.
