### ISSUE TITLE
arabic sources

### ISSUE THREAD

**Issue by marafa** [fisharebest/webtrees#3283]
in the muslim / arabic world. inheritance follows strict divisions.
therefore (in egypt) the best source of family trees are the (paper) land deeds which will state who owns this plot of land. eg. a farm could have the children all listed by name if it was not divided 

how do i add this as a source considering that ancestry.com and all other large geneology sites concentrate on european and north american families?

**Comment by fisharebest** [comment]
TIP - for questions about how to use webtrees, it is better to ask on the forum at www.webtrees.net.  There are lots of people to help you, with lots of experience of different situations.  This issue tracker is for bugs/errors.
