### ISSUE TITLE
default block: move news to top

### ISSUE THREAD

**Issue by marafa** [fisharebest/webtrees#3284]
new user here so i may have missed this
i see i can move the "news" section to the very top for new trees before they are imported/generated.

how do i do this for already existing trees?

and in case i am asking the wrong question, i want to have a header section explaining about the site "this is me, this site is for my family, if you are a family member you can apply for an account blah blah blah" - is this the correct place to add that information?

**Comment by fisharebest** [comment]
> how do i do this for already existing trees?

You must navigate to the home page for the tree.
From the menu "My pages" choose "Customise this page"

> i want to have a header section explaining about the site "this is me, this site is for my family, if you are a family member you can apply for an account blah blah blah" - is this the correct place to add that information?

I would recommend that you add an HTML block (not use the news block).

**Comment by marafa** [comment]
that did the trick. thank you
