### ISSUE TITLE
faq + wiki outdated

### ISSUE THREAD

**Issue by marafa** [fisharebest/webtrees#3285]
it seems the faq and wiki are outdated

searching the forum isnt very intuitive and simple keywords like "mail" results in red herrings.

i do not have a solution to this as i am a new user. bringing it up so the more experienced users can contribute back to the wiki

**Comment by fisharebest** [comment]
> it seems the faq and wiki are outdated

The wiki is being replaced by a new project website https://webtrees.net

Creating documentation takes time, and I am working as fast as I can...

**Comment by fisharebest** [comment]
I guess it is time to turn the wiki server off.

**Comment by hartenthaler** [comment]
I agree! Maybe save a backup which can be accessed if there is a need.

I just updated in the old wiki the "access and privacy" page (in German only): [Zugang_und_Datenschutz](https://wiki.webtrees.net/de/Zugang_und_Datenschutz); your new page "[privacy](https://webtrees.net/user/privacy/)" is much better, but maybe the rewritten last chapter about  "RESN" can be reused at your new page.

**Comment by fisharebest** [comment]
The old wiki site has been deleted.

All the URLs should redirect to a appropriate page on the new documentation site.
e.g. https://wiki.webtrees.net/en/Frequently_Asked_Questions

I kept an offline backup.  I will check if any content can be re-used on the new site.

**Comment by mpfaff** [comment]
@fisharebest, I was finding the wiki to be quite useful, despite it being outdated, and was disappointed to find it gone. If I'm being honest, I've found the new documentation to be rather lacking aside from installation and hosting. Would you consider uploading the backup anywhere for those interested in its content?

**Comment by hartenthaler** [comment]
Do you know: [webtreesmanual.com](https://webtreesmanual.com/)?
I just found it, looks great for the first view.

**Comment by fisharebest** [comment]
@hartenthaler - Thanks!  I have not seen this.

@mpfaff - I can let you have a copy of the old wiki.  email me at greg@subaqua.co.uk
Perhaps you have time to read/review the pages, and see which ones might be useful to add on the new site?
