### ISSUE TITLE
An observation on css patches

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3288]
For https://github.com/fisharebest/webtrees/commit/7c45a75abda00d289352a0d81a6fd94fce7babe8 I notice you've added the patch to _core.css, wouldn't it be more appropriate to tack it onto the end of vendor.css or even create patch.css and add that to vendor.css.

However I appreciate this isn't likely to be a regular occurrence!

**Comment by fisharebest** [comment]
You are right.  It would be a good idea to have a separate `vendor-patches.css` file for this type of thing.

Hopefully, it will usually be empty...
