### ISSUE TITLE
Shared Note Anchor Disappears When Expanded

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3289]
When viewing shared notes attached to events, the note title is linked only when collapsed.  I'm more likely to look for the link after expanding and reading census data, for example.  It is not intuitive to collapse the note to find the link.

**Comment by fisharebest** [comment]
The note can consist of links (and only links).

When collapsed, we just show the note's "name" - the text of the first line (and we turn it into a link to the note record).

When expanded, we can't do this, as there is nothing to turn into a link.

So, we need another screen element to become the anchor...

**Comment by fisharebest** [comment]
I am sure there is already an open issue for this - but I cannot find it.

**Comment by fisharebest** [comment]
#3246
