### ISSUE TITLE
Place List Shows World Map When Children Have No Coodinates

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3291]
If you create a places such as Dallas, Texas, USA and Houston, Texas, USA and then specify coordinates for Texas, USA, when you then navigate to the Place List page for Texas, the map shows the entire world with no indication of where Texas is located.

**Comment by fisharebest** [comment]
> If you create a places such as Dallas, Texas, USA and Houston, Texas, USA and then specify coordinates for Texas, USA, when you then navigate to the Place List page for Texas, the map shows the entire world with no indication of where Texas is located.

I did this.  I have this data.

```
mysql> select * from wt_placelocation;
+-------+--------------+----------+---------------+---------+---------+---------+---------+
| pl_id | pl_parent_id | pl_level | pl_place      | pl_long | pl_lati | pl_zoom | pl_icon |
+-------+--------------+----------+---------------+---------+---------+---------+---------+
|     1 |            0 |        0 | United States |         |         |       2 |         |
|     2 |            1 |        1 | Texas         | W100    | N31     |       5 |         |
|     3 |            2 |        2 | Dallas        |         |         |       2 |         |
|     4 |            2 |        2 | Houston       |         |         |       2 |         |
+-------+--------------+----------+---------------+---------+---------+---------+---------+
4 rows in set (0.00 sec)
```

I see this:

<img width="1200" alt="Screenshot 2020-06-05 at 22 35 11" src="https://user-images.githubusercontent.com/2306088/83924563-d801c780-a77c-11ea-9494-90e09bdfc583.png">

The zoom level is set in the database.  If I edit the location and change the zoom level from 5 to 8, I see this:

<img width="1173" alt="Screenshot 2020-06-05 at 22 39 03" src="https://user-images.githubusercontent.com/2306088/83924808-69713980-a77d-11ea-9b3c-d97a9f3d005f.png">

How do I reproduce the problem?

**Comment by miqrogroove** [comment]
In that case, simply visit the Texas page instead of the United States page.  Its children have no coordinates and it won't even try to show you where Texas is located.

**Comment by fisharebest** [comment]
> visit the Texas page instead of the United States page

Sorry - I thought I was!

As you might guess, I didn't create this module, and rarely use it.

**Comment by miqrogroove** [comment]
In the situation where the current place has a zoom level saved, is it possible to use the saved zoom level instead guessing the "number of degrees"?

**Comment by fisharebest** [comment]
The zoom level is already ignored in most cases.

I think it is confusing to ask the user to choose a zoom level - and then ignore it.

I want to remove this setting.  I think there are better alternatives.

a) we can create a bounding-box of all child places.

b) we can store the true boundary of the place, instead of a point.  (The geojson format supports this).

**Comment by miqrogroove** [comment]
Bounding box of all child places is what we had before this patch.  It doesn't work.  You get situations where there is only one child, or there are only a few children in a small area and then the zoomed area is too small to be useful.

This patch is an improvement, but by ignoring the saved zoom levels it is frustratingly close to a better solution (actually using the data instead of ignoring it).

**Comment by miqrogroove** [comment]
I'm going to take a stab at moving around some of the lines in the patch.  Should I post my ideas here or a new issue?

**Comment by fisharebest** [comment]
> Bounding box of all child places is what we had before this patch. It doesn't work.

I meant bounding box if there are 2+ children (or grandchildren?) with co-ordinates,
and the current behaviour otherwise.

I started to code this, but I don't have enough (any) real-world data to work with.

**Comment by miqrogroove** [comment]
The pull request will basically eliminate the current behavior because:

1. As you said, the bounding box is better.
2. When there are zero children, we should use the saved view instead.
3. As we see in #3229 there are real problems with counting children when they might be far away from the "center" of the parent.
