### ISSUE TITLE
Question: Name of customer modules using special characters "_", "-" or " "

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3295]
There are two new webtrees modules:

- [GermanChancellorsAndPresidents](https://github.com/hartenthaler/german-chancellors-and-presidents/)

- [GermanWarsAndBattlesWorldwide](https://github.com/hartenthaler/german-wars-and-battles-worldwide)

I do not like to use the name "GermanChancellorsAndPresidents" and tried to name it "German Chancellors And Presidents". Or using "_" or "-" instead of " ", but whatever I tried had the result that webtrees don't found my module. How is the relation between the string in the title() function and the folder name of the module?

Sorry, I'm still a junior programmer. Do you have other recommendations for me? I'm just working on two additional moduls with historic data:
- pandemics and epidemics
- German kings and emperors (Holy Roman Empire).

**Comment by fisharebest** [comment]
The module names (i.e. folder names) must be 30 characters or less.
They also be valid PHP variable names.

https://github.com/fisharebest/webtrees/blob/2.0.4/app/Services/ModuleService.php#L612-L616

I recommend to use lower-case letters and hyphens.

**Comment by fisharebest** [comment]
See also https://github.com/fisharebest/webtrees/blob/2.0.4/modules_v4/README.md

> Note that module names (i.e. the folder names) must not contain spaces or the characters ., [ and ]. It must also have a maximum length of 30 characters.
