### ISSUE TITLE
Upgrade from 1.7.16 to 1.7.17 from Control panel: error occurred when unzipping the file

### ISSUE THREAD

**Issue by liegebe** [fisharebest/webtrees#3296]
Automated upgrade from the Control panel — Dashboard have been constantly working from v1.7.11 to 1.7.16, but now I am not able to upgrade to webtrees 1.7.17. When, clicking on 'Upgrade to webtrees 1.7.17.', I have got the following error:

`Check for pending changes…
    There are no pending changes.
    Check for custom modules…
    No custom modules are enabled.
    Check for custom themes…
    No custom themes are enabled.
    Export all the family trees to GEDCOM files…
    The family tree has been exported to /var/www/webtrees/data/ourtree-2020-05-23.ged.
    Download https://github.com/fisharebest/webtrees/releases/download/1.7.17/webtrees-1.7.17.zip…
    3 KB were downloaded in 0.05 seconds.
    Unzip webtrees-1.7.17.zip to a temporary folder…
    An error occurred when unzipping the file.
    PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature`
    
My config:
- webtrees 1.7.16
- CentOS Linux release 7.7
- mariadb-server-5.5.64
- nginx 1.16.1-1
- php7.1-1-1
- unzip-6.0-20
and I have 4G of empty space on the disk

Generally this error indicates that the .zip file is incomplete or corrupted, and indeed, if I download https://github.com/fisharebest/webtrees/releases/download/1.7.17/webtrees-1.7.17.zip directly, the file is really bigger than the one downloaded through the click on the Control panel.
The unzip seems to be immediate through the click on the Control panel, while the archive needs normally a few seconds to be downloaded.
I am still looking into debugging this issue, but I think it is useful for everyone to share.

**Comment by fisharebest** [comment]
This error has already been reported and fixed.

There was a change in the configuration of the github download server.

It now sends a `location` header instead of a `Location` header.  (Lower case).

The fix was here:

https://github.com/fisharebest/webtrees/commit/3bd4111244f5c168957c240a88cec8da69221538
