### ISSUE TITLE
Improve confirmation page after deletion of individuals

### ISSUE THREAD

**Issue by t-karcher** [fisharebest/webtrees#3298]
Currently, this is what you see after deleting a spouse of a family:

![image](https://user-images.githubusercontent.com/22897030/82803450-d7198d80-9e80-11ea-8003-383705394bcf.png)

While there's nothing wrong with it, I'd still like to suggest two improvements:
1) Don't route back to the deleted individual, but to the main page instead: We know it's deleted, so why go back there?
2) In the "link deleted" info message, it would be helpful to link the affected family, so I can immediately go back there and check the results / continue to work with it.

**Comment by mirono** [comment]
2nd this

**Comment by fisharebest** [comment]
> Currently, this is what you see after deleting a spouse of a family:

Only if you have "automatically accept changes" enabled on your account.

Regular users on your site will not usually have this enabled.
Instead, they will see the individual, with all the facts marked as deleted.

All the relationships are still shown, so there is a simple one-click link back to the area of interest.

> Don't route back to the deleted individual, but to the main page instead:

The home page is often slow, as it can contain many lists, statistics, etc.
Redirecting to a slow page would interrupt the user's workflow.

>  We know it's deleted, so why go back there?

It provides nice clear confirmation that the record is deleted.

----------

I understand what you are saying, but I'm not sure that navigating to the home page is a good solution.

**Comment by fisharebest** [comment]
> In the "link deleted" info message, it would be helpful to link the affected family, so I can immediately go back there and check the results / continue to work with it.

If these were links, then this page would be much more useful.  There would be links to all the records that linked to this individual.  One of them is probably the next page you would want to visit.
