### ISSUE TITLE
Word "year" appears twice in individuals age in some languages

### ISSUE THREAD

**Issue by Salokyn** [fisharebest/webtrees#3299]
Hi,

For some individuals, the word that stands for "year" in French and Spanish appears twice. Apparently it happens only for dead people :

In french 

---

![image](https://user-images.githubusercontent.com/11018648/82822028-65a00600-9ea5-11ea-8c1b-1cc1d5e33d19.png)

---

In spanish

---

![image](https://user-images.githubusercontent.com/11018648/82822101-823c3e00-9ea5-11ea-8a2b-b831a2f3036f.png)

---

**Comment by Salokyn** [comment]
Maybe linked to #3277

**Comment by jon48** [comment]
Hello,
I have already updated the translations on Weblate for both French/French (Canada) and Spanish (the only languages I could confidently identify the unnecessary 'years' word), and hopefully they will come down at the next Weblate merge.
If other languages displays the same issue, change the `'(aged %s)'` string (the `%s` placeholder is already a string containing the age qualifier).

**Comment by fisharebest** [comment]
Thanks @jon48

**Comment by Salokyn** [comment]
Ok, thanks!
