### ISSUE TITLE
1.6.2 - Bug in colors theme

### ISSUE THREAD

**Issue by HRN-webtrees** [fisharebest/webtrees#330]
Since 1.6.2 there seem to be a problem with colors theme. When adding a note like census transcript, the optionbox extends above it's limits, and disappears under the sidebar.
This was not a problem prior to 1.6.2. Removing the line white-space: nowrap; from descriptionbox (line 2037 in colors.css) seems to fix the problem, but I guess this is not the proper way to do it?

**Comment by fisharebest** [comment]
I presume from the comments that this is fixed...
