### ISSUE TITLE
Recent changes block shows empty data

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#3301]
Tested on the demo dev

![image](https://user-images.githubusercontent.com/5641963/82841431-4cfc1400-9ed6-11ea-937c-2cbe670245f2.png)

It always list a family record, even when changes are made to another type of record (individual, source etc.)

**Comment by fisharebest** [comment]
I think you tested on `demo-stable` (2.0.4) - not `demo-dev` (2.0.5-dev)

As far as I can tell, this was already fixed.

**Comment by JustCarmen** [comment]
I see what has happened. The link on webtrees.net that should go to demo-dev goes to demo-stable instead.

![image](https://user-images.githubusercontent.com/5641963/82861252-62942c80-9f1c-11ea-85d4-ac11a5e88e53.png)


So I thought I was on demo-dev when tested this.

**Comment by fisharebest** [comment]
> The link on webtrees.net that should go to demo-dev goes to demo-stable instead.

Oops!  Fixed!
