### ISSUE TITLE
Some thoughts on watermarks

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#3305]
Adding watermarks is both time and resource consuming, and in 2.0 it seems to be even more demanding. Having thousands of media files in my tree, most of them publicly available images from parish and census records etc, I guess more than 90% of the media objects could be displayed without watermarks. Actually, I would like to have only personal photos "protected" by watermarks.

Would it be technically possible to change the way watermarks are added, maybe per file or per folder? Perhaps by restrictions like "Add watermark" or "Show without watermark"?

**Comment by fisharebest** [comment]
> it seems to be even more demanding

We need to resize two images, and then merge them.

Previously, we only needed to resize one image.  So it probably takes 3 times as long.

Also, we can now generate thumbnails at lots of different sizes,  Devices with higher DPI screens will receive images with more pixels, etc.  So, there are more thumbnails to generate.

**Comment by fisharebest** [comment]
I've been looking at the JPEG compression ratio.  We use the default (90), but
I can't distinguish much difference between 30 and 90.

Note that we send images with high DPI values for high-resolution displays.

This image will be displayed at 100x130px in webtrees - about a quarter of the size shown here.
So any artefacts will be far less visible.

90: 73KB
![90](https://user-images.githubusercontent.com/2306088/82951598-64530400-9f9f-11ea-94de-7d1427a4feba.jpg)

80: 36KB
![80](https://user-images.githubusercontent.com/2306088/82951604-661cc780-9f9f-11ea-9762-2fc31709c6e9.jpg)

70: 28KB
![70](https://user-images.githubusercontent.com/2306088/82951605-66b55e00-9f9f-11ea-836c-28612438758f.jpg)

60: 23KB
![60](https://user-images.githubusercontent.com/2306088/82951606-674df480-9f9f-11ea-9136-af42f7ad3e21.jpg)

50: 19KB
![50](https://user-images.githubusercontent.com/2306088/82951608-67e68b00-9f9f-11ea-8fb3-847e1fdab940.jpg)

40: 16KB
![40](https://user-images.githubusercontent.com/2306088/82951610-67e68b00-9f9f-11ea-9ced-b7643e90dc0f.jpg)

30: 13KB
![30](https://user-images.githubusercontent.com/2306088/82951611-687f2180-9f9f-11ea-9a79-2c0c97ca08f5.jpg)

20: 10KB
![20](https://user-images.githubusercontent.com/2306088/82951612-6917b800-9f9f-11ea-8299-edd2c35e2bc3.jpg)

10: 6KB
![10](https://user-images.githubusercontent.com/2306088/82951595-6321d700-9f9f-11ea-877c-d9a5e7d21f3e.jpg)

Dropping the compression ratio helps the time to create them a little.  About 20% in some initial tests.  Smaller files will also transmit faster.

**Comment by HRN65** [comment]
Thank you Greg for elaborating on this. Looking at the compression, I agree there is not much difference between 30 and 90.

I ususally use 75 on my images of handwriting and printed text without seeing notable loss in quality. I also keep max dimension below 1500 - 2000 px, depending on image type.

Personal photos I usually reduce to about 800 x 600 px. Yes, I know many of my images are large, but this was never a problem in 1.7

As processing watermarked images now is more demanding, my concern is that many users, running sites on servers with only GD enabled, will face problems when upgrading to 2.0.

If you do a test at https://visitusinmaputo.com/webtree/tree/29082010.GED/individual/I159/Andreas-Pauli-Nilsen (GD only) you'll find that most images will fail, showing "This image failed to load."

(I have replaced the watermark.png with my own, but there is no difference in performance between the two)

I've also attached a file (1896 x 1536 px, 575 kB) if you kindly could test performance on your system.

Anyway, I will have Imagick installed on my server shortly, and hopefully this will ease the pain?

Though, my initial question still remains. Would it be possible, in the future, to have a system where you can choose which files should be protected with watermarks?

Less than 10% of my images would "need" watermarks, as most of them are public available anyway

![kb20050419010158](https://user-images.githubusercontent.com/55854079/83018130-0e28a400-a025-11ea-94ee-cb6e37aad7bb.jpg)

**Comment by fisharebest** [comment]
> Though, my initial question still remains. Would it be possible, in the future, to have a system where you can choose which files should be protected with watermarks?

Yes it would be possible.
But we need some logic that is simple enough to describe in one sentence.
Users need to understand easily which images get watermarks and which don't.

The current logic is "show watermarks if the user's role is less than XXX".

**Comment by HRN65** [comment]
Could this be a restriction set pr image? 
"Do not show watermark" (overriding general setting for watermarks)
"Show watermark" (overriding general setting for watermarks)

**Comment by JustCarmen** [comment]
This issue is related to this one: https://github.com/fisharebest/webtrees/issues/1436

**Comment by miqrogroove** [comment]
I see significant differences between 80 and 90 in the examples posted above.  Keep in mind, the smaller the image is, the more noticeable the compression effects will be.  On the 40 x 50 thumbnail images, only 90 should be used.  And on full size images, any extra compression must be optional/configurable.  I don't use the watermarks feature and I don't want my site to look bad for the sake performance.

**Comment by JustCarmen** [comment]
Me neither. Most of the time I use Photoshop to prepare my images for online usage in such way it gives me a good ratio between quality and size.  So the extra compression is not necessary at all and should definitely be optional. I don't have any performance issues so I don't need the extra compression.

**Comment by fisharebest** [comment]
6577bfc3111b4789852b83f46e19d92c9b59921c adds a new `ImageFactory` object.

This is responsible for

a) generating thumbnails
b) creating watermarks
c) adding watermarks
d) deciding which images require thumbnails
e) deciding which thumbnails require thumbnails

This makes it easy to override any part of the process:

* Create your own version of this object - `class MyImageFactory extends ImageFactory {...}`
* Register it in the `boot()` method of a module - `Factory::image(new MyImageFactory());`

Other changes include:

* We send the original full-size image, instead of a re-generated version (previously we re-generated it, to apply auto-rotation and remove EXIF data).
* We detect the original `q` value for jpeg images, and use this when creating thumbnails.
* We pre-calculate the transparancy for the watermark, to improve performance.
