### ISSUE TITLE
v2.0.4 When 'Automatically expand notes' is 'No', Shared Notes are displayed alongside media

### ISSUE THREAD

**Issue by sleebooth** [fisharebest/webtrees#3309]
When "Automatically expand notes" is set to "No" for a Family Tree, the Note div class is fact_NOTE rather than fact_SHARED_NOTE.

As a result the Shared Note is shown alongside media instead of below it.

Automatically expand notes is No:
![Automatically expand is No](https://user-images.githubusercontent.com/5928173/83053422-98363400-a048-11ea-84d8-ca24a8c19cff.png)

Automatically expand notes is Yes:
![Automatically expand is Yes](https://user-images.githubusercontent.com/5928173/83053855-522da000-a049-11ea-8f80-618d2ef4592d.png)

**Comment by fisharebest** [comment]
I think this is the same as #2502 which was fixed a few days ago.
