### ISSUE TITLE
GEDCOM validation error

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3310]
When exporting a GEDCOM, the code to split a long line can leave leading or trailing spaces.

For example

`n CONC  there are two spaces after the CONC here`

**Comment by fisharebest** [comment]
Erm - that looks right to me.

Page 10:
> If a concatenated line is broken at a space, then the space must be carried over to the next line.

Page 37:
> The requirement for usage is to either break the text line in the middle of a word, or if at the end of a word, to add a space to the first of the next CONC line.

**Comment by ddrury** [comment]
OK, It was no big deal but I recently installed a validator from Chronoplex software that flags it as having avoidable leading/trailing whitespace characters.
