### ISSUE TITLE
2.0.4 - option to maximize message box on MyPage

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3315]
In the message box on My Page, I can scroll sideways to read the entire message. But for long sentences and lines, this reads not handy.

Is it possible to add an option to maximize this window to make the text easier to read?

**Comment by TheDutchJewel** [comment]
Desktop

**Comment by fisharebest** [comment]
This is what my (laptop) screen looks like:

<img width="908" alt="Screenshot 2020-06-01 at 16 16 32" src="https://user-images.githubusercontent.com/2306088/83423723-4f54f580-a423-11ea-905a-b1541975f9dd.png">

What do you see?

**Comment by TheDutchJewel** [comment]
![afbeelding](https://user-images.githubusercontent.com/46184729/83428417-9eeeed80-a432-11ea-89ce-fd282a0321ca.png)

**Comment by fisharebest** [comment]
Messages from other users (not from visitors).

**Comment by TheDutchJewel** [comment]
In my case all visitors are members. So the messages are from members.

**Comment by fisharebest** [comment]
The issue is that these messages contain `----------------`.

We are using the markdown engine to convert URLs and XREFs into links.

But it is also converting `------------` into `<h2>` titles.
