### ISSUE TITLE
Re-Order Media Cursor Disagreement

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3317]
On the Re-Order Media page, the mouse cursor changes while hovering any `wt-sortable-item` however almost none of this area is drag-able.  I am only able to drag the media while hovering a `drag-handle`.

This disagreement between cursor appearance and purpose makes it more difficult to use.

webtrees 2.0.3 with Chrome 83 on Windows 10.

**Comment by fisharebest** [comment]
This was fixed in 2.0.4

You can see this on the demo site.

You can drag using all of the "card header"
