### ISSUE TITLE
Media & Album Tabs Have Different Sort Order

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3318]
After experimenting more with the Re-Order Media feature on an individual with 35 media objects, I've realized the Album tab remains semi-random and never respects the media order.  I have to go to the Media tab to see the correct order.

It would make more sense to have both of these tabs work with the media order feature.

**Comment by fisharebest** [comment]
Suppose you link a photograph of a church to `BAPM`, `MARR` and `BURI` events.
The media tab will show this three times - once for each event.
If you also linked the photograph to the `INDI` record, you would see it four times.

The album tab ignores the context, and shows a unique list of media objects.
So, it is not possible for these two tabs to show the *exact* same order, as they aren't
even showing the exact same number of things.

Also consider the case of the same media object linked to the individual more than once.  e.g.

```
1 OBJE @M1@
1 OBJE @M2@
1 OBJE @M1@
```

The media tab would show both links to M1 - to give you the opportunity to delete one of them.
The album tab would only show one link to M1.  Again, not possible to use the same order.

The media tab is aimed at editors.  The album tab is aimed at visitors.

**Comment by miqrogroove** [comment]
I get it.  Somewhat impractical showing duplicates and not being able to organize anything.  But we can close this if it's working as intended.

**Comment by miqrogroove** [comment]
And just to point things out, yes the Album tab absolutely does show multiple links to the same media object.  Maybe just under different circumstances.
