### ISSUE TITLE
Dialogs Cancel Unexpectedly

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3319]
The "Create a media object" box (and similar features) have the unfortunate behavior of disappearing if I click away from them, even after data entry.

One particularly nasty problem can be seen with the "Media type" drop down list.  This list extends below the bottom of the "Create a media object" box.  So I want to click on "Photo" but let's say I missed to the left of "Photo" by two pixels.  The result is that I've lost all of my data entry, including file selection and title.

**Comment by fisharebest** [comment]
There are two ways to close a modal dialog.

a) click the close button
b) click the background (outside the modal).

It is easy to disable (b).

The question is: will the change annoy more people than it will help?

**Comment by miqrogroove** [comment]
For me, it's not a problem when the dialog is open and unused.

Is there an easy way to disable the "background" click only when the dialog form is dirty?

**Comment by fisharebest** [comment]
Unfortunately, we must choose the behaviour when we create the dialog.
I do not think we can change it afterwards.

**Comment by fisharebest** [comment]
Is this a problem that you experience regularly - or just infrequently?

**Comment by miqrogroove** [comment]
I've experienced it enough that it discourages me from using the mouse.  I find myself trying to navigate the dialog using the keyboard more over time.

I haven't tested this version much on mobile yet.  Mostly desktop.

**Comment by miqrogroove** [comment]
Here's another scenario I've run into:

I'm typing out a shared note for a new fact citation.  I need to task switch so that I can copy and paste part of a transcript.  Even though Chrome does not have focus and is not even the top window on screen, when I click on it to switch back, my entire shared note is lost.
