### ISSUE TITLE
SQL Error when using Advanced Search for a Nickname

### ISSUE THREAD

**Issue by Norwegian-Sardines** [fisharebest/webtrees#3321]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'individual_name' in 'where clause' (SQL: select distinct `wtstable_individuals`.* from `wtstable_individuals` inner join `wtstable_name` as `wtstable_individual_name` on `wtstable_individual_name`.`n_file` = `wtstable_individuals`.`i_file` and `wtstable_individual_name`.`n_id` = `wtstable_individuals`.`i_id` where `i_file` in (1) and `individual_name` = NICK and `individual_name` LIKE %Honey%) …/vendor/illuminate/database/Connection.php:664

When Trying to search on a Nickname.

I did not enter an"individual_name just the selected NICK in other fields. The search was done on the Demo database, current release, Royal Family.

**Comment by Norwegian-Sardines** [comment]
This was by selecting an additional field called nickname.

**Comment by t-karcher** [comment]
Confirmed. Same for marriage name:
https://dev.webtrees.net/demo-dev/tree/demo/search-advanced?fields%5BNAME%3AGIVN%5D=&fields%5BNAME%3ASURN%5D=&fields%5BBIRT%3ADATE%5D=&fields%5BBIRT%3APLAC%5D=&fields%5BFAMS%3AMARR%3ADATE%5D=&fields%5BFAMS%3AMARR%3APLAC%5D=&fields%5BDEAT%3ADATE%5D=&fields%5BDEAT%3APLAC%5D=&fields%5BFAMC%3AHUSB%3ANAME%3AGIVN%5D=&fields%5BFAMC%3AHUSB%3ANAME%3ASURN%5D=&fields%5BFAMC%3AWIFE%3ANAME%3AGIVN%5D=&fields%5BFAMC%3AWIFE%3ANAME%3ASURN%5D=&fields%5BNAME%3A_MARNM%5D=Test&modifiers%5BNAME%3AGIVN%5D=EXACT&modifiers%5BNAME%3ASURN%5D=EXACT&modifiers%5BBIRT%3ADATE%5D=0&modifiers%5BFAMS%3AMARR%3ADATE%5D=0&modifiers%5BDEAT%3ADATE%5D=0&modifiers%5BFAMC%3AHUSB%3ANAME%3AGIVN%5D=EXACT&modifiers%5BFAMC%3AHUSB%3ANAME%3ASURN%5D=EXACT&modifiers%5BFAMC%3AWIFE%3ANAME%3AGIVN%5D=EXACT&modifiers%5BFAMC%3AWIFE%3ANAME%3ASURN%5D=EXACT
<pre>
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'individual_name' in 'where clause' (SQL: select distinct `wtsvn_individuals`.* from `wtsvn_individuals` inner join `wtsvn_name` as `wtsvn_individual_name` on `wtsvn_individual_name`.`n_file` = `wtsvn_individuals`.`i_file` and `wtsvn_individual_name`.`n_id` = `wtsvn_individuals`.`i_id` where `i_file` in (1) and `individual_name` = _MARNM and `individual_name` LIKE %Test%) …/vendor/illuminate/database/Connection.php:664
#0 …/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select distinct...', Array, Object(Closure))
#1 …/vendor/illuminate/database/Connection.php(333): Illuminate\Database\Connection->run('select distinct...', Array, Object(Closure))
#2 …/vendor/illuminate/database/Query/Builder.php(2130): Illuminate\Database\Connection->select('select distinct...', Array, true)
#3 …/vendor/illuminate/database/Query/Builder.php(2118): Illuminate\Database\Query\Builder->runSelect()
</pre>
