### ISSUE TITLE
Historic Data - TYPE should be more precise

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3322]
![Screenshot (107)](https://user-images.githubusercontent.com/6324175/83749138-84e82180-a663-11ea-885a-639a3bb211eb.png)

TYPE should be more precise:
- Prime Minister **of the United Kingdom**
- Bundespräsident **Österreich**

**Comment by fisharebest** [comment]
Do you think this is necessary?

It makes the text very long.  "Prime minister of the United Kingdom" requires 4 lines on a mobile display.

I guess these modules will only be used on English/Austrian sites.

I expect that the users will recognise the name of their historic leaders.

**Comment by hartenthaler** [comment]
My family is half German and half Austria. Ok, the elder relatives should know which Bundespräsident is from which country, but do the younger ones know all names? Maybe you can use abbreviations „UK“ and „A“ or „AUT“.

**Comment by fisharebest** [comment]
Fixed in #3437
