### ISSUE TITLE
Batch update search/replace single update returns in 501 error

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#3327]
Using the batch update feature. Trying to update 1 item from the list. Nothing happens. The list contains 15 items, I just want to update a few but updating a single item is impossible.

The chrome console shows a 501 error:
![image](https://user-images.githubusercontent.com/5641963/83962416-76854a00-a89d-11ea-96c1-26b74a7aca81.png)

**Comment by fisharebest** [comment]
Is this repeatable?

What search/replace options do you use?

Does the 501 appear immediately?  After a number of seconds?

**Comment by JustCarmen** [comment]
Yes it is repeatable. Just tried it again. This is my search query:

![image](https://user-images.githubusercontent.com/5641963/84187133-e2c89f00-aa91-11ea-858a-0d00851e7ce4.png)

The 501 error appears immediately after pushing the update button next to a search result. Can't show you the list itself due to privacy.

**Comment by fisharebest** [comment]
I cannot reproduce this, and cannot guess what might cause it.

**Comment by JustCarmen** [comment]
This error still exists. Every time when I want to do a datafix update of a single entry I get a 501 error. This only occurs on my live website. When performing the same operation on my local test site it works as expected.

A 501 status code is received when the web server does not support the facility required. But I have no idea which facility is missing. Do you have a clue or do you have an idea how I can find out?

**Comment by fisharebest** [comment]
I can't find anything in the code that would cause a [501 response](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501).

This is a `POST` request, and so it should only be sent if the server does not understand `POST`.

Can you could add some debug to see where the request fails?

**Comment by fisharebest** [comment]
I guess this is an issue with server configuration.

If you have more information that will help me to investigate, then please open a new issue.
