### ISSUE TITLE
Php error reporting is disabled in production

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#3328]
See Control Panel > Server Information:
"error_reporting" has a Local Value of 0.
This makes it impossible to analyze errors of users in production.

It is caused by an unintended value of ERROR_REPORTING in [Webtrees.php](https://github.com/fisharebest/webtrees/blob/7fe676e56205e9e90cf38847f31382635e0dc152/app/Webtrees.php#L89):

`E_ALL & !E_USER_DEPRECATED & !E_USER_DEPRECATED;`
This resolves to 0.

Apart from the fact that one of the E_USER_DEPRECATED is probably intended to be E_DEPRECATED? - The correct way to combine these levels is:

`E_ALL & ~E_USER_DEPRECATED`

**Comment by fisharebest** [comment]
Well spotted - I have used "binary not" instead of "bitwise not".

> Apart from the fact that one of the E_USER_DEPRECATED is probably intended to be E_DEPRECATED? 

In `dev` builds, we need `E_DEPRECATED` (for PHP notices) and `E_USER_DEPRECATED` (for webtrees notices).
