### ISSUE TITLE
example.disable

### ISSUE THREAD

**Issue by loudubewe** [fisharebest/webtrees#3329]
It seems that, due to the file 'example.disable/module.php', "Individual" appears as "Fish" (or "Poisson" in french) everywhere on our webtrees site. Is this a standard default behaviour and should I delete this file ?
Many thanks

**Comment by fisharebest** [comment]
Modules ending in `.disable` (or containing `.`) are ignored. Perhaps you also have a copy of this module?

**Comment by loudubewe** [comment]
You are right.
Thank you.
