### ISSUE TITLE
Redefining a Route Handler

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#3339]
When attempting to redefine a route via MiddlewareInterface, I came across this:

The final MiddlewareInterface instance added by the Router is the WrapHandler. It is constructed using the current route handler, [here](https://github.com/fisharebest/webtrees/blob/5bd13fbbb0904e682044d9a60b119ce8cb8d7138/app/Http/Middleware/Router.php#L104).

Therefore any attempt to update the route handler from custom modules implementing MiddlewareInterface, e.g. like this:

```
public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface {
    $route = $request->getAttribute('route');
    assert($route instanceof Route);
    if ($route->handler === EditFact::class) {
      $route->handler(EditFactAdjusted::class);
    }
    return $handler->handle($request);
}
```

has no effect. Is that by design? I would prefer MiddlewareInterface instances to be able to actually adjust the route handler (they can basically modify everything anyway in other ways).

This is easily achieved if WrapHandler uses the (perhaps adjusted) route handler from the request interface, instead of a route handler set via its constructor.

**Comment by fisharebest** [comment]
The request handler is created using the container.

So you can replace it easily like this:

```
boot() {
  app()->bind(EditFact::class, EditFactAdjusted::class);
}
```

**Comment by ric2016** [comment]
ok, that works (except for the Service Locator/ Dependency Injection confusion - so it's still ok to use the container for both?)

**Comment by fisharebest** [comment]
> (except for the Service Locator/ Dependency Injection confusion - so it's still ok to use the container for both?)

You are right that we need to clearly separate these two functions.

But not immediately.  There are many other priorities.
