### ISSUE TITLE
Media objects displayed on Facts and events tab

### ISSUE THREAD

**Issue by jpretired** [fisharebest/webtrees#3342]
2.0.5 Individual page bug:
**when** Control panel > Tabs > Media set to Show to members (and higher)
**then** for a visitor (not logged in) some media objects are displayed on Facts and events tab below the facts and events. Displayed media objects are those which are not connected to a fact or event.

**Comment by fisharebest** [comment]
This is working as intended.  See https://webtrees.net/upgrade/2.0

In webtrees 1.7, if you disable a tab, you also hide the data.

In webtrees 2.0, if you disable a tab (or sidebar), then the data is shown on the facts/events tab.

This allows you to create tabs for specific information.
e.g. If you create a tab to display censuses, then the censuses will only appears on that tab, and will not be duplicated on the facts/events tab.

**Comment by jpretired** [comment]
Sorry I acted rashly saying it is a bug, I didn't notice the paragraph in 'Difference in 2.0'.
Anyway imho the approach in 1.7 is closer to my logic: I don't want visitors to see media objects so I simply disable the tab Media (and Album). The only media they can see is the small portrait in place of silhouette.
Also - media object is not fact nor event, is it?

**Comment by SnarfW** [comment]
I fully I agree, the appraoch in 1.7 was fine for me and no need to change. (same behaviour is observed for notes). Because of this I have decided not to upgrade yet. Would it be possible to make this option configurable?
