### ISSUE TITLE
Comments/discussion on each page 

### ISSUE THREAD

**Issue by dobek** [fisharebest/webtrees#3344]
It would be more motivated for users to contribute if they could make comments under each person. The most knowledge about family is in a possession of older people who are non-technical. It would be easier for them just to write a comment like on blog pages.

These comments can be stored as notes with the username who wrote them.

**Comment by fisharebest** [comment]
> These comments can be stored as notes with the username who wrote them.

Users can already add notes.  Administrators can already see who added the notes.

How is this different?

Perhaps explain exactly what you want to see on the screen?
