### ISSUE TITLE
Customize Edit interface input field box

### ISSUE THREAD

**Issue by khatri22nukh** [fisharebest/webtrees#3349]
I want to customize form group or input field box, Please provide me location of that file .. thanks

**Comment by fisharebest** [comment]
In webtrees 2.0, it is complicated.  Which field?

In webtrees 2.1, it will be very easy.
Standard GEDCOM tags are defined [here](https://github.com/fisharebest/webtrees/blob/develop/app/Factories/GedcomElementFactory.php)
Custom tags are defined in modules, e.g. [here](https://github.com/fisharebest/webtrees/blob/develop/app/Module/CustomTagsFamilyTreeMaker.php)

Can you wait a few months for 2.1?

**Comment by khatri22nukh** [comment]
Thanks for your response. Actually i want to do some different style of input fields form by using some other bootstraps classes.

**Comment by khatri22nukh** [comment]
![IMG_20200617_004144](https://user-images.githubusercontent.com/56252635/84817920-5723b500-b033-11ea-862b-c140e5ade01e.jpg)

I need this form phtml file for customize this form

**Comment by fisharebest** [comment]
Editing names and new individuals is resources/views/edit/new-individual.phtml

Adding other facts resources/views/edit/add-fact.phtml
Editing other facts resources/views/edit/add-fact.phtml

But these files will disappear very soon.

**Comment by khatri22nukh** [comment]
Ok thankyou very much im waiting for that:)
