### ISSUE TITLE
Fan chart margin

### ISSUE THREAD

**Issue by khatri22nukh** [fisharebest/webtrees#3351]
![IMG_20200617_214538](https://user-images.githubusercontent.com/56252635/84922861-159f1280-b0e4-11ea-858a-3972e1eaf3c5.jpg)
How can i fix it?

**Comment by mpwt** [comment]
Take a look at <https://github.com/magicsunday/webtrees-fan-chart> and switch off the build-in fan chart. :)

**Comment by fisharebest** [comment]
This is  interesting.   I see the problem on the demo server - but not on my local development server.

Same code.  Same data.

Differences?  PHP 7.2 / 7.4

**Comment by fisharebest** [comment]
Perhaps this is a PHP bug?

I have checked, and we are passing the correct/same parameters to `imagefilledarc()`.

What version of PHP do you have?

**Comment by HRN65** [comment]
I see this on both 7.2.9 and 7.3.1

**Comment by fisharebest** [comment]
> I see this on both 7.2.9 and 7.3.1

Thanks.  Those are two more data-points.

So far, it seems that

7.1 - unknown
7.2 - fails
7.3 - fails
7.4 - works

**Comment by fisharebest** [comment]
I have reported this as a bug in PHP - https://bugs.php.net/bug.php?id=79763

Here is a test file.

On affected servers, setting `$radius` to an odd number causes the problem.  Setting it to an even number works OK.

So, on servers with the bug, you can draw an arc with a size of 274 or 276, but not 273, 275 or 277...

So, I guess our workaround is to ensure we only use a multiple of 2.

```
<?php
$image_size = 400;
$arc_size   = $_GET['r'] ?? 275;

$image = imagecreate($image_size, $image_size);

$c1 = imagecolorallocate($image, 255, 255, 255);
$c2 = imagecolorallocate($image, 0, 255, 0);
$c3 = imagecolorallocate($image, 0, 0, 255);

imagefilledrectangle($image, 0, 0, $image_size, $image_size, $c1);

imagefilledarc($image, $image_size/2, $image_size/2, $arc_size, $arc_size, 135, 270, $c3, IMG_ARC_PIE);
imagefilledarc($image, $image_size/2, $image_size/2, $arc_size, $arc_size, 270, 405, $c2, IMG_ARC_PIE);

header('Content-type: image/png');
imagepng($image);
imagedestroy($image);
```
