### ISSUE TITLE
I cannot add blocks to the Home page or the My page. 2.0.5-dev & demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3352]
I can remove blocks in Change the "Home/My page" blocks.

**Comment by fisharebest** [comment]
It seems to work OK for me.

I can add/remove blocks to home/my pages on the demo sites, my own site and my dev site.

Can you confirm the exact steps you are taking.
What goes wrong?
What browser?

**Comment by melizaa** [comment]
Sorry!

I did not try to drag the new blocks to the blocks 'tables', although I saw the arrow icons.
