### ISSUE TITLE
Cannot merge sources

### ISSUE THREAD

**Issue by ro-la** [fisharebest/webtrees#3361]
I will merge two sources - but it is not possilbe to choose  sources for merging. The text "Please enter 2 or more characters" does not appear. See picture:

![image](https://user-images.githubusercontent.com/60657963/85204062-2765fd00-b312-11ea-8d14-0c190020879f.png)

With other types it works.
![image](https://user-images.githubusercontent.com/60657963/85204102-511f2400-b312-11ea-9999-c76274ebdb68.png)

Is it possible that it is somhow related to this issue: https://github.com/fisharebest/webtrees/issues/2935 ?

webtrees 2.0.6.

Thanks 
Ladislav

**Comment by ric2016** [comment]
This is caused by the Vesta Research Suggestions custom module, see [here](https://github.com/vesta-webtrees-2-custom-modules/vesta_research_suggestions/issues/4).

Issue may be closed here.

**Comment by ro-la** [comment]
Thanks, i wanted just to report, that it is something with the Suggestion module :-) 

Ladislav
