### ISSUE TITLE
Feature: Option to show Tree Page after login

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3364]
One of the 2 code hacks that I have to merge with each new version is that I want my users to see the tree page instead of "my page" after login.

It would be nice if this was an option, or at least pluggable.

**Comment by fisharebest** [comment]
The user is only redirected to "My page" if they logged in from the "Tree page".

Otherwise, they remain on the same page - but with elevated credentials.

So, they would only be redirected if they have already seen the "Tree page".

> or at least pluggable.

This should be easy to implement as a module...

Create a boot method to register a replacement handler for the login action

```
public function boot() {
    app()->bind(LoginAction::class, MyLoginAction::class);
}
```

Your implementation of MyLoginAction exends the existing one, and its handle method looks like

```
{
  if (request>parameters[url] is MyPage) {
      request = request with parameter url = HomePage
  }
return parent::handle();
}
```

**Comment by miqrogroove** [comment]
I can work on that and probably publish the results too.  It would be a nice little module.

**Comment by miqrogroove** [comment]
> Perhaps you could explain your thinking, because the benefits aren't obvious to me.

Personal preference?

My users are not familiar with any of this stuff and they have trouble figuring out that the content they want is hidden under the "Family tree" button.

**Comment by miqrogroove** [comment]
I guess I'm not understanding how `bind()` works.  I want to extend or rebind `Fisharebest\Webtrees\Http\RequestHandlers\HomePage`

I'm including a new class file from my module file but my new class doesn't get used.  I tried a few different namespaces but nothing's happening.

**Comment by fisharebest** [comment]
Here is a module that gives you what you want:

```
<?php

declare(strict_types=1);

namespace MyCustomNamespace;

use Fisharebest\Webtrees\Http\RequestHandlers\LoginPage;
use Fisharebest\Webtrees\Module\AbstractModule;
use Fisharebest\Webtrees\Module\ModuleCustomInterface;
use Fisharebest\Webtrees\Module\ModuleCustomTrait;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

return new class extends AbstractModule implements ModuleCustomInterface, MiddlewareInterface {
    use ModuleCustomTrait;

    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        if ($request->getAttribute('route')->name === LoginPage::class) {
            $params = $request->getQueryParams();
            $url    = $params['url'] ?? '';
            if (substr_compare($url, '/my-page', -8) === 0) {
                $params['url'] = substr($url, 0, -8);
                $request       = $request->withQueryParams($params);
            }
        }

        return $handler->handle($request);
    }
};
```

**Comment by miqrogroove** [comment]
I'll try it.

Are there any working examples of the `bind()` idea?  If it were possible to customize any class just by changing bindings that would be very powerful.

**Comment by fisharebest** [comment]
> If it were possible to customize any class just by changing bindings that would be very powerful.

That is the idea behind it.

Although you can only affect things that are created *after* your code runs.

It is a feature of the container library we use (laravel), and isn't part of the PSR-11 container specification.  As such, I don't really like to rely on it or recommend it.

But other PSR-11 implementations all seem to offer similar features - just with a different syntax...

**Comment by miqrogroove** [comment]
> Although you can only affect things that are created _after_ your code runs.

Yeah I'm not clear on this part.  Is the boot method of an anonymous module providing the proper glue or do I need to do the binding somewhere else?

**Comment by fisharebest** [comment]
The boot method is just a convenient place to put this code.  It is called early in the execution sequence.  (There's a middleware called "BootModules").

When it runs, it can be certain that all other modules will exist - but not all will have been booted.

The sequence is
a) construct all modules
b) boot all modules
c) use modules

**Comment by miqrogroove** [comment]
I'm still struggling, but I've found what looks like `app()->getConcrete()` and some related functions that might make it possible to figure out what the heck is going on.

**Comment by fisharebest** [comment]
I think you are digging too deeply.

You don't need to know how the container class works.  Just how to use it.

**Comment by fisharebest** [comment]
The simplest use is `app(Foo::class)`.
This means: make me an object of type `Foo`.  If the constructor takes parameters, make those first.

That's it.  That is all that a container class is supposed to do.

The container implementation that we use has a few extra features.
Specifically

`app()->bind(Foo::class, Bar::class)`.

This means that next time someone asks for a `Foo`, give them a `Bar`.

**Comment by miqrogroove** [comment]
I think the missing piece for what I'm doing here is that the aura router isn't using the app container to resolve route handlers.  Or at least not in a way that makes any sense to me.  I can do what I need by changing the routes instead of changing the container binding.

**Comment by miqrogroove** [comment]
Solved!

https://github.com/miqrogroove/family-tree-home/
