### ISSUE TITLE
Thumbnails Extremely Compressed on Desktop

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3366]
After updating to v2.0.6, all of the Charts are showing extremely compressed thumbnail images for each individual.

If I right-click and download one of the thumbnails, it's showing a file size of 681 bytes 😢

When I look at the same charts on my phone, I still get the nice hi-dpi images.

**Comment by miqrogroove** [comment]
Changing this from 45 to 90 resolves the problem instantly:

https://github.com/fisharebest/webtrees/blob/e6149aa297b1e71a733ad947adf78db9d3f7c266/app/MediaFile.php#L263

**Comment by miqrogroove** [comment]
Media thumbnails are looking much better again too.  So this affects more than just the charts.

**Comment by fisharebest** [comment]
The jpeg quality/compression parameter was changed to improve performation - See #3305

Can you give an example of "extremely compressed"?

**Comment by miqrogroove** [comment]
I'd be happy to upload a celebrity photo and save the thumbnails for you, but I'll be surprised if we are seeing different results from the same code.

**Comment by miqrogroove** [comment]
Here is one example.  For this specific image, the impact to the individual page photo is undesirable but not severe, whereas the chart page shows major differences.

`q=90`
![q90-indi](https://user-images.githubusercontent.com/1371835/85207047-2920c800-b2f4-11ea-8853-f2c789e4f28c.png)

`q=45` with notable splotchy skintone
![q45-indi](https://user-images.githubusercontent.com/1371835/85207045-2920c800-b2f4-11ea-80fa-4178fa477165.png)

`q=90`
![q90-chart](https://user-images.githubusercontent.com/1371835/85207046-2920c800-b2f4-11ea-9ae8-89239c56f387.png)

`q=45` with horrible overall appearance
![q45-chart](https://user-images.githubusercontent.com/1371835/85207048-2920c800-b2f4-11ea-95ed-0c3bb84d51ae.png)

**Comment by JustCarmen** [comment]
I agree, this really looks terrible. I encounter the same issue on my own site.

**Comment by fisharebest** [comment]
> I'll be surprised if we are seeing different results from the same code.

Maybe you have better eyesight than me - or maybe  a better monitor?

I can't see a difference between these screenshots.
I just showed the larger ones to my girlfriend, who said the bottom one looked better (!)

**Comment by fisharebest** [comment]
> If I right-click and download one of the thumbnails, it's showing a file size of 681 bytes
> When I look at the same charts on my phone, I still get the nice hi-dpi images.

webtrees will send a different image to your desktop and your phone.

We use "media queries" to send a different sized image according to the DPI setting for your display.

So you may get an image with 100x150 pixels on your desktop, but 400x600 on your iPhone.

**Comment by fisharebest** [comment]
Also, the `q` value is not a standard parameter.

`q=75` will behave differently in Imagick and GD

**Comment by miqrogroove** [comment]
> Maybe you have better eyesight than me - or maybe a better monitor?

Apparently!

> I can't see a difference between these screenshots.
> I just showed the larger ones to my girlfriend, who said the bottom one looked better (!)

I can't argue with girlfriend-official results.  But I can at least complain about the need to hack this file as a result of severely degraded image quality.  Please stop forcing this subjective value on your users.

**Comment by miqrogroove** [comment]
Latest reference for anyone trying to fix this.

https://github.com/fisharebest/webtrees/blob/64c83a78b4caa4bdc810446739df37776e706d8d/app/MediaFile.php#L252

**Comment by fisharebest** [comment]
It would be good to have more data-points.

We have one that says that anything under 90 is unacceptable.
We have one that says that 45-90 are indistinguishable.

I suspect that the optimum value is somewhere in between.

Also, the `q` value is also different for `imagick` and `gd`...

**Comment by fisharebest** [comment]
Fixed in 6577bfc3111b4789852b83f46e19d92c9b59921c
