### ISSUE TITLE
Feature: Better css class name to refer to pages

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#3368]
I need to get rid of the default title on the login page, because I use my own. I know I have several options to achieve this, but I don't want to make a module and alter a view for something as simple as this.

In control panel I've put the custom title in the custom welcome text area with `<h2> `tags. But then I end up with two titles (the default one and my own) and that is not what I want.

So I enabled the custom CSS/JS module to solve this issue with just one line of css code.

But surprisingly this was not as easy as I thought it would be. 

The class .wt-page-title is used on multiple pages so I had to refine the rule so it will only effect the title on the login page. The only way I can think of is using the page class name which is a very long name:  `wt-route-Fisharebest\Webtrees\Http\RequestHandlers\LoginPage`

Unfortunately css won't eat it.  My css:
`<style>
  .wt-route-Fisharebest\Webtrees\Http\RequestHandlers\LoginPage .wt-page-title {
    display:none
  }
</style>`

didn't have any effect.

I am not sure if it is the length of the class name or the backslashes that causes the problem, but the fact is that it isn't working.

My solution which works:
`<style>
  [class*=LoginPage] .wt-page-title {
    display:none
  }
</style>`

Is this really the way it is meant to be? I think it should be easier to refer to a specific page. Why not use a simple class name like wt-route-loginpage? I can imagine a lot of users who know enough css to make some simple changes will have trouble with this.

**Comment by fisharebest** [comment]
Originally, the "route names" were simple strings.

But as the routing code was developed, they became class names.

You are right - this is not good.

Backslashes are valid, but need to be escaped (`\\\\`?) in CSS files.

We should use something like `basename($classname)`
