### ISSUE TITLE
Search does not display "Nickname" but does display "Also known as"

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#3374]
When one does a general search for "Andrew" which is a nickname, the list returned is correct but there is no display of the Nickname in the given name field, see image 1.
However, if you do a search for "Andrew" which is an "Also known as" field then the given names field shows the "Andrew" see image 2 below.

Image 1
![image1](https://user-images.githubusercontent.com/5147603/85314874-f3ecb500-b46e-11ea-8f7d-8f8d454bf829.png)

Image 2
![image2](https://user-images.githubusercontent.com/5147603/85314885-f64f0f00-b46e-11ea-8cd8-a23d0f34e0cb.png)

**Comment by fisharebest** [comment]
This is a full-text search.  You can search for text anywhere in the record.

If you searched for "farmer", you'd pick up everyone with `1 OCCU farmer` - but this wouldn't be shown in the results.

The results is just the standard name/birth/death details.

So, NICK (like OCCU) isn't a field in this view of the data, so I wouldn't expect it to be shown - unles, of course, it is also part of a name.

**Comment by makitso** [comment]
Your right of course.  However, it seems to be a bit of an inconsistency.  And, it would be helpful to casual users that say "I remember that someone had the nickname of "abc", they do a search and get 100 results with no visual indicator of the name.
