### ISSUE TITLE
HTML blocks will not allow display:flex statement.

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#3380]
If I create an html block and include the below, 

`<div style="display:flex">`

the code generated only has 

`<div>`

**Comment by fisharebest** [comment]
It seems that the HTML-Purifier library doesn't include `flex` in its list of allowable values:

https://github.com/fisharebest/webtrees/blob/master/vendor/ezyang/htmlpurifier/library/HTMLPurifier/CSSDefinition.php#L441-L458

**Comment by makitso** [comment]
Seems a bit narrow minded, it the library being supported?

**Comment by fisharebest** [comment]
It seems to be active / supported: https://github.com/ezyang/htmlpurifier

> I don't understand the list, I don't see margin or float in the list but they work.

That's a list of allowed values for `display: xxxx`

There is a simple workaround.  Since we are using bootstrap, all flex properties are available using classes.

e.g. `<div class="d-flex">`

**Comment by fisharebest** [comment]
https://getbootstrap.com/docs/4.1/utilities/flex/

**Comment by makitso** [comment]
OK
