### ISSUE TITLE
File not found in test and future test systems - 2.0.7-dev 

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3382]
I see for instance for urls
<https://www.amitys.com/test/index.php?route=%2Ftest%2Ftree%2FGedcom.ged%2Fpreferences>
<https://www.amitys.com/test/index.php?route=%2Ftest%2Ftree%2FGedcom.ged%2Ffan-chart-3-4-100%2FI1>

View file not found: …/app/../resources/views/components/select-number.phtml …/app/View.php:262
#0 …/app/View.php(186): Fisharebest\Webtrees\View->getFilenameForView('components/sele...')
#1 …/app/View.php(282): Fisharebest\Webtrees\View->render()
etc.
and 
View file not found: …/app/../resources/views/components/select-number.phtml …/app/View.php:262
#0 …/app/View.php(186): Fisharebest\Webtrees\View->getFilenameForView('components/sele...')
#1 …/app/View.php(282): Fisharebest\Webtrees\View->render()
etc.

For instance
<https://www.amitys.com/test/index.php?route=%2Ftest%2Ftree%2FGedcom.ged%2Fancestors-tree-4%2FI1>
and demo-dev work as expected.

How can I solve this?

**Comment by fisharebest** [comment]
> `resources/views/components/select-number.phtml`

This is a new file, that was added recently.

https://github.com/fisharebest/webtrees/blob/master/resources/views/components/select-number.phtml

I'm guessing this file did not get copied to the server when you updated.

**Comment by melizaa** [comment]
THANKS!

**Comment by melizaa** [comment]
I do not know how I missed it twice?
