### ISSUE TITLE
Missing full description of 'IN OR AFT' and 'IN OR BEF' dates

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3384]
If I add a fact date like `IN OR AFT` or `IN OR BEF`, webtrees shows only the `IN` date, not the full `IN OR AFT` or `IN OR BEF` date description.

Is it possible to display the full description?

**Comment by fisharebest** [comment]
`IN`?

This is not a valid GEDCOM keyword.

Can you give a full example of the date you are using?
Was it created by another application?  Which one?

**Comment by TheDutchJewel** [comment]
>Was it created by another application? Which one?

No, I just tried to add it in webtrees.

The last fact of a person was that she witnessed the baptism of her granddaughter in 1755. So she died in or after that year.

**Comment by fisharebest** [comment]
Just use `AFT 1755` (or the exact date, if you know it).
