### ISSUE TITLE
2.0.6 Christening fact missing in Quick individual facts on Facts and events page

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3385]
I've added both **Baptism** and **Christening** to the **Quick individual facts**, but on the **Facts and events** page only **Baptism** is visible, not **Christening**.

If this is a bug, can it be fixed?

**Comment by fisharebest** [comment]
You need to add christening to either the "all facts" or "unique facts" lists as well.

If a fact does not appear in the main list of facts to add, then it is not shown in the "quick facts".

The reason is so that we do not show unique facts that already exist.
