### ISSUE TITLE
Duplicate data in family chart box

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#3386]
The family chart box ( husband + wife) shows the birth year - death year after the person's name e.g. 1922 - 1978.
I do not see this same structure in any of the other charts.  

So my question is, what value does it provide when the birth and death dates are also shown?

**Comment by fisharebest** [comment]
It shouldn't be there.  See #3387 

The chart boxes contain lots of components, and we use CSS to hide them on specific charts/pages/etc.

This one was overlooked, and so shows everything.
