### ISSUE TITLE
URL switches when attempt to view new tree

### ISSUE THREAD

**Issue by marc1aj** [fisharebest/webtrees#3388]
I have multiple trees set up on my site and I recently upgraded to the latest version of Webtrees after I had to switch hosting companies. I do not have the option to select a tree to view because I want to keep them separate. I discovered recently that the URLs are not working as expected (once I figured out that they are taking a different format now). I will give you an example. If I try to visit https://genfamtrees.com/index.php?route=%2Ftree%2Fhercules, I am taken to https://genfamtrees.com/index.php?route=%2Ftree%2Fharvey instead and this happening with all my trees. I am not sure what is happening here. It may be some setting that I need to change but I need some guidance on what it could possibly be. Any assistance you can provide would be greatly appreciated,

Thanks,
Marcia

**Comment by t-karcher** [comment]
Maybe your other trees are set to private?

If you try to access https://familie-dohl.de/tree/this_tree_does_not_exist , you will be automatically forwarded to my default tree ("dohl"). But if you navigate to https://familie-dohl.de/tree/test , this should work fine. Same could be the case on your site: If "hercules" is not (publicly) available, you will be forwarded to your default tree.

**Comment by marc1aj** [comment]
Is this the setting where you show family tree under Privacy:

 Show the family tree - visitors members
Enabling this option will force all visitors to sign in before they can view any data on the website. 

I thought it would show the page and then you can log in to see further details. I tried changing another tree and now when I copy and paste, the URL remains constant. Thanks for the assistance.

Marcia
