### ISSUE TITLE
Name Field Sometimes Not Updated

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3389]
I'm confused about how name editing works sometimes.  If I have a person with a saved `NSFX` or `NPFX` then any changes I make to the Given Names are not saved into the Name field.  In all other situations, I simply edit the given names and it all just works without the fuss.

**Comment by fisharebest** [comment]
This code has been rewriten in the `develop` branch (will become 2.1.0), and is working there.

**Comment by fisharebest** [comment]
This fix has been merged into the main branch, and will be included in 2.1.0.
