### ISSUE TITLE
2.0.6 - 'Surname tradition patrilineal' does not add a surname

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3390]
If I use 'Surname tradition > **paternal** — Children take their father’s surname. Wives take their husband’s surname': the surname of the father is added.
But when I use 'Surname tradition > **patrilineal** — Children take their father’s surname': _no_ surname is added.

Can this be fixed?

**Comment by fisharebest** [comment]
The error is caused by a space character in the configuration settings.

After you have the updated code, you will need to re-select the surname tradition in the family tree preferences.

**Comment by TheDutchJewel** [comment]
I see same space character in line 87:
            `'matrilineal ' => /* I18N: A system where children take their mother’s surname */`
Does it also need to be corrected?
