### ISSUE TITLE
I do not manage to drag blocks in Change in the blocks - 2.0.7-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3391]
This used to work a short time ago both for the Home page and My page.

**Comment by melizaa** [comment]
Also clicking on the help icons does nothing.

**Comment by fisharebest** [comment]
Which of your sites has the problem?  I just tried on test, which worked OK.

Which browser are you using?

**Comment by fisharebest** [comment]
My guess is that there is a javascript error on the page, which prevents the other javascript functions from working.

Do you see an error in the browser's error console?

**Comment by melizaa** [comment]
Now I can drag the blocks.
I had problems both in the test and the future test systems.
I use mainly Google Chrome Version 84.0.4147.68 (Official Build) beta
(64-bit) on my windows 10 laptop.

I had the issue also in some other browsers.
Now I can also use Brave, Microsoft Edge, Firefox, etc.
Internet Explorer 11 Version 11.900.18362.0 (some blocks run and run after
I sign-in, several links do not work from the indi or family pages, the my
page sign-out block does not sign me out)), etc. - I tried now to update
the browser again. Got the same version and behavior.

The help ?-s return still nothing in Chrome.

I see now in the Chrome error console
Grammarly.js:2 [DEFAULT]: WARN : Using DEFAULT root logger
t.printToConsole @ Grammarly.js:2
Grammarly.js:2 [WARNING] Using default timeseries implementation.
e.getRootMetric @ Grammarly.js:2
DevTools failed to load SourceMap: Could not load content for
chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/content.map:
HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for
chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/iframe_handler.map:
HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for
https://www.amitys.com/test/public/js/vendor.min.js.map: HTTP error: status
code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

I can now still drag blocks.

Meliza

**Comment by fisharebest** [comment]
> I can now still drag blocks.

OK.  If the problem happens again, let me know and I will investigate.
