### ISSUE TITLE
Individual names in name accordion - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3393]
I do not like the surnames in slashes. If we need to highlight the surname, we could perhaps print it for instance with a bigger (or  upper-case) font. I would only remove the slashes. If I need to see the slashes, I can use raw-editing.

![image](https://user-images.githubusercontent.com/5202996/86471627-68b0d080-bd46-11ea-911e-37220f68193b.png)

**Comment by fisharebest** [comment]
We reformat the `NAME` record in the header panel - i.e. we remove `/` and underline given names that are followed by `*`.

If we also reformatted the `NAME` record in the details panel, then it will just be a duplicate of the header, and there would be no point in showing it at all.

Are you saying we should only show the level 2 fields (`GIVN`, `SURN`, etc.)?

We show the slashes when we edit the data, and we have help-text that explains how to use them correctly.

Surely showing them here, in the details panel, is a great way to educate our users?
They can see the formatting characters, `/` and `*`, and can see how it is displayed.

> if we need to highlight the surname, we could perhaps print it for instance with a bigger (or upper-case) font

FYI, you can use small-capitals for surnames using CSS - `.SURN {font-variant: small-caps}`

![Screenshot 2020-07-04 at 15 58 52](https://user-images.githubusercontent.com/2306088/86515277-a75e8d80-be0f-11ea-9e0c-3b74155fb868.png)

**Comment by melizaa** [comment]
I have still over 10,000 individuals on my site with only one NAME record that includes both the Latin and the Hebrew names.
I do not like how we see only the name in the page language orientation without the surname slashes.

Can we at least print on the LTR pages the 1 NAME and the 2 _HEB name and on the RTL pages the 2 _HEB and 1 NAME names without slashes and with underlines at the top of the name accordion?

![image](https://user-images.githubusercontent.com/5202996/87091968-45ed5300-c243-11ea-84ef-9626ee4e637a.png)

**Comment by melizaa** [comment]
On the Hebrew page
![image](https://user-images.githubusercontent.com/5202996/87092325-e8a5d180-c243-11ea-8777-f472346d2035.png)

**Comment by fisharebest** [comment]
webtrees can recognise two structures for name records.  One used by some desktop applications, and the GEDCOM standard.

```
1 NAME
2 _MARNM
```

to

```
1 NAME
1 NAME
2 TYPE married
```

By default, we have always created the first of these.  We inherited it from phpGedView.

But I want to change the default to create the GEDCOM standard structure.

This change will happen in 2.1.0.  The code for this is 90% complete.

> Can we at least print on the LTR pages the 1 NAME and the 2 _HEB name and on the RTL pages the 2 _HEB and 1 NAME names without slashes and with underlines at the top of the name accordion?

There is a new "data fix" utility.  "Convert NAME/_XXX to GEDCOM standard".

This will convert your data to the GEDCOM standard, with multiple NAME records.
All of these will be shown in the accordion.

**Comment by melizaa** [comment]
OK
