### ISSUE TITLE
Reports that include Notes

### ISSUE THREAD

**Issue by sevtor** [fisharebest/webtrees#3396]
The reports for Individual and Related families have a check box to include notes. This has no effect since the test in the files are incorrect: "if ($notes == 1) " should be "if ($notes =='on')".

The reports do not get proper headers and footers, it was ok in version 1.7.x. Changes needed in TcpdfWrapper.php and PdfRenderer.php. The contents in headers and footers is according to my preference. 

I have recently done some research on my family and added notes on individuals, families and source field for occupation. When i print a report on families I want all these notes to be included, they contain very interesting information. This is implemented by the changes in the xml files

I have patch files:
[reports.zip](https://github.com/fisharebest/webtrees/files/4875172/reports.zip)

**Comment by fisharebest** [comment]
Thanks for the patches.

I included many of them.
