### ISSUE TITLE
2.0.6 - Sorting Marriage bann and Marriage

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3398]
When I add a `Marriage bann` with date and a `Marriage` without date, the `Marriage bann` is sorted **after** the `Marriage` in the _Facts and events_ tab of the Individuals.
This does not make sense, because an `Marriage bann` always **precedes** a `Marriage`.

Can this be fixed?

**Comment by vytux-com** [comment]
Sure, Whan you add the marriage fact add a AFT date the same as the bann date entered

**Comment by TheDutchJewel** [comment]
@vytux-com Thanks for the workaround.

But I hope that the problem will be solved structurally, so that no more workaround is needed.

**Comment by vytux-com** [comment]
But is this a workaround? I though it was the solution as you are fixing the data according to your assumptions.

Maybe there was an elopement type marriage before the bann and then a church (re)marriage so it is feasible to have a marriage before and after a bank I would think.

Remember weirder things have happened in the history

**Comment by TheDutchJewel** [comment]
>But is this a workaround?

Yes, it is. I think a marriage should always come after a marriage bann, whether or not you fill in a marriage date.

It was a coincidence that I saw this case, I suspect there are more cases like this in my family tree. So as long as this problem is not solved in the basics, I will have to find and repair them manually.

**Comment by fisharebest** [comment]
We already have rules to sort `MARB` before `MARR`:

https://github.com/fisharebest/webtrees/blob/2.0.6/app/Fact.php#L72-L77

It works for me.

Can you provide a complete example of the problem.

**Comment by TheDutchJewel** [comment]
>Can you provide a complete example of the problem.

I tried, but I can't reproduce it either!

It was a person who was married twice. The problem was only visible at the first marriage.
But if I export a clipping chart of this person and his wives, and import it as a new tree, then the problem doesn't exist anymore.
Also if I put individual and familie XREFs of this person and his wives in a new gedcom file, and import it as a new tree, then the problem doesn't exist anymore.

So it seems to be an incident rather than a structural problem.
