### ISSUE TITLE
Changing the month in the daily calendar - Demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3401]
I look at the daily calendar and select to change the month. I am transferred to the monthly calendar. I want to remain in the daily calendar, as in pre wt 2.0.0.

**Comment by fisharebest** [comment]
Isn't the current behaviour more natural?

You click on a day to get a day view.
You click on a month to get a month view.

**Comment by melizaa** [comment]
Perhaps we should have an option to see the next day in the daily view or
to fill the full day that we want to see.
Now, on the last day of the month, I have to hit the next month and I am
transferred to the monthly view.

**Comment by melizaa** [comment]
I can change the day and month in the URL, without being moved to the monthly view.
