### ISSUE TITLE
Upcoming events module sort error

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3404]
Upcoming events with sort set to date, presentation style set to list, sort order is incorrect
See attached from latest demo
![demo](https://user-images.githubusercontent.com/104515/86927379-2ebb4200-c12b-11ea-885f-944b68a7d1a9.jpg)

**Comment by fisharebest** [comment]
That list looks correct to me - ascending order of upcoming anniversary.

12 July
14 July
15 July
16 July
17 July

**Comment by ddrury** [comment]
I have a feeling we've been here before but surely the year is part of the date and as such should be taken into account

**Comment by fisharebest** [comment]
> the year is part of the date and as such should be taken into account

We could use the year as a secondary sort?
But the primary (and only current) sort is on the anniversary date.

**Comment by ddrury** [comment]
I understand your reasoning for the current sort, therefore, I propose a third option "sort by age" which sorts by YYYYMMDD
> We could use the year as a secondary sort?

Do you mean if two events occur on the same day & month then also sort by year? I would have thought that that should happen anyway.

**Comment by fisharebest** [comment]
> "sort by age" which sorts by YYYYMMDD

I'm not sure this is particularly meaningful?
(But it is available in the "table" view of data - click in the column heading.)

What is your use-case, workflow, etc.
I can see *what* you want, but not *why* you want it (other than some sense of "completeness").

**Comment by ddrury** [comment]
Forget it, I'll do it myself
