### ISSUE TITLE
2.0.6 - Reports > Individual > Show notes: notes are not displayed

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3405]
I have individuals with notes in the Note tab.

When I select `Reports > Individual > Show notes > View/Download`, the notes are _not_ displayed.

Tested also on [live demo](https://dev.webtrees.net/demo-stable/index.php?route=%2Fdemo-stable%2Ftree%2Fdemo%2Freport-run%2Findividual_report&varnames%5B0%5D=pid&varnames%5B1%5D=sources&varnames%5B2%5D=notes&varnames%5B3%5D=photos&varnames%5B4%5D=pageSize&varnames%5B5%5D=colors&vars%5Bpid%5D=i1&vars%5Bsources%5D=on&vars%5Bnotes%5D=on&vars%5Bphotos%5D=highlighted&vars%5BpageSize%5D=A4&vars%5Bcolors%5D=on&format=HTML&destination=view).

Can this be fixed?

**Comment by fisharebest** [comment]
This was fixed a few days ago in #3396
