### ISSUE TITLE
Hebrew dates shown on wrong dates in the Calendar and in blocks - 2.0.7-dev 

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3406]
I have tested special Hebrew date birth/brit mila/marriage and   death/burial/yahrzeit cases in the calendar. 

Adar, Adar I and Adar II tested dates do not behave as expected. Also the 30 Heshvan deaths are not shown as expected in years where 30 Heshvan does not exist. 
See also #3097          

The same problems exist also in the Yahrzeiten and Upcoming events blocks.         

Attached my test gedcom & my test results spreadsheet.
[RtlDates.ged.zip](https://github.com/fisharebest/webtrees/files/4899069/RtlDates.ged.zip)
[HebrewDateIndis.xlsx](https://github.com/fisharebest/webtrees/files/4899075/HebrewDateIndis.xlsx)

**Comment by fisharebest** [comment]
Can we work through some of the examples in the spreadsheet, to help me understand the problem?

The first example - X5940 / "H Adar" - born 1 Adar (non-leap-year).

On a leap-year (e.g. 5779), the anniversary is shown in Adar II and not in Adar I.  (This is correct, yes?)

> We see in all the Adar II dates, except in 29 Adar II

I see several anniversaries in 29 Adar II.  What anniversaries are missing?

**Comment by melizaa** [comment]
H Adar - We should see the birth only on 1 Adar II 5779 and on 1 Adar 5780.
We see the birth also on 2-28 Adar II 5779 and on 2-28 Adar 5780 - this is
wrong. It is good that we do not see this birth on 29 Adar or 29 Adar II.

Meliza

**Comment by melizaa** [comment]
For instance the births of A Adar (X5933) and B Adar (X5932) should show in
29 Adar II 5779 - and they are correctly shown there.

We should not see J Adar (X5942) in 29 Adar II 5779, we should only see it
in 29 Adar I 5779.

Meliza

**Comment by fisharebest** [comment]
> We see the birth also on 2-28 Adar II 5779 and on 2-28 Adar 5780

OK - that one was easy to fix.

**Comment by fisharebest** [comment]
>We should not see J Adar (X5942) in 29 Adar II 5779, we should only see it in 29 Adar I 5779.

OK - the test for leap-years was reversed.  Fixed.

**Comment by fisharebest** [comment]
> Also the 30 Heshvan deaths are not shown as expected in years where 30 Heshvan does not exist.

I look at D Heshvan - born 30 Heshvan 5774.
I look at the year 5779 - Heshvan has only 29 days.
I see the anniversary for D Heshvan on 1 Kislev.
I think this is correct.

I look at A Heshvan - born 30 Heshvan 5684.
This day did not exist.  That month has only 29 days.
So, we see this individual in the "day not set" box - which is where we show all invalid dates.
I think this is correct.

**Comment by melizaa** [comment]
D Heshvan - 5778 and 5777 have only 29 days - We show on 1 Kislev which is correct. (5779 has 30 days)

I have now only looked at births after your correction, not yet at deaths.
I do not see the births of I Adar, S Adar or E Adar in 5780. 
C Adar should be in 30 Shevat 5780, not in 1 Nissan.   

A Heshvan,  died on 30 Heshvan 5684 and we see him correctly in the Day not set box.

**Comment by fisharebest** [comment]
> C Adar should be in 30 Shevat 5780, not in 1 Nissan.

I use the well-known reference book "Calendrical Calculations" to obtain my rules and forumae. It says:

> Someone born on the thirtieth day of Marcheshvan, Kislev, or Adar I has his birthday postponed until the first of the following month in years where that day does not occur.

So, C Adar (30 Adar 1) should be in 1 Nissan?

This is a regular anniversary (not a yahrzeit).  I think that yahrzeit would be on 30 Shevat.

https://www.hebcal.com/home/54/anniversaries-adar-cheshvan-kislev

**Comment by melizaa** [comment]
My husband searched again the definition of the Bar Mitzvah and Yahrzeiten date in a non leap year of an event that took place on 30 Adar I. The texts define it as 30 Shevat, the Rosh Hodesh (beginning of the month) of Adar.
<https://www.hidabroot.org/question/193220>
This is one of the definitions in Hebrew that he has found.
Your 1 Nissan is another possible option.
Perhaps we should fill the events of 30 Adar 1 twice in the calendar.
We speak of the birth of C Adar and the death of B Adar.

Now deaths.

Non leap year Adar deaths in a leap year.
Sephardim and Ashkenazim as a rule grieve the Yahzeiten of non leap-year Adar deaths either in Adar I or in Adar II or in both, we added in phpgedview the death (and other grievance) dates to the calendar in both the Adars in leap years. I would do the same in webtrees.
We should see the deaths of D Heshvan, O Adar, U Adar and A Adar in 5779 also in Adar I.

Should we somehow highlight that we have filled the above events twice to the calendar or would this just confuse the users?

I do not see in 5780 the Adar I deaths of G Adar, C Adar and the burial of P Adar and the Yahzeit of V Adar. 

A Heshvan died on 30 Cheshvan 5716 (a valid date). In 5777 and 5778 we should see the death on 1 Kislev, not in the Day not set box.

The definitions are complex, so people go to their Rabbi, who tells when the Bar Mitzvah and Yahrzeiten will fall. I have tried to define how to fill the events in the calendar without taking into account when the burial took place (normally it takes place on the day of death or the next day) and when the first Yahzeiten took place and if the user is a Sephardi, an Ashkenazi or some other Jew.

**Comment by melizaa** [comment]
I wrote wrong 5779 dates in the spreadsheet for S Adar and P Adar. They should be 2 Adar I and 11 Adar I.
Sorry!

**Comment by fisharebest** [comment]
> the definition of the Bar Mitzvah and Yahrzeiten date

I did not know there are also special rules for anniversaries of Bar Mitzvah...
We have a special block for Yahrzeiten.

The calendar page does not know the type of the event.  So it only shows "standard" anniversaries.

Continuing through the examples.  (Which are very helpful - thanks!)

* `R ADAR` - `02 ADR 5612` - missing
I see them on the calendar in Adar II in 5779 and in Adar in 5780.
(Note: the calendar defaults to BIRT/MARR/DEAT.  Did you forget to change the filter to "all"?)

* `X ADAR` - `02 ADR 5614` - missing
I see them on the calendar in Adar II in 5779 and in Adar in 5780.

* `I ADAR` - `01 ADR 5679` - shown twice
In 5779, I see them only in Adar I.
In 5780, I do not see them at all.

The code is checking if the event-year is a leap year.  It should check if the anniversary-year is a leap year.
e.g. if the anniversary year is not a leap year, then we include both months 6 and 7.
I will fix this next.

**Comment by fisharebest** [comment]
* `S ADAR` - `02 ADR 5611`
With the previous fix, I now see this OK.

* `J ADAR` - `29 ADR 5684`
With the previous fix, I now see this OK.

* `C ADAR` - `30 ADR 5679`.
We show invalid dates (e.g. `31 ADR`) on the last day of the month.
We should not do this for 30 ADR, because it will be shown on the next month.
I will fix this next.

**Comment by fisharebest** [comment]
* `E ADAR` - `ADR 5616`
I now see this in day-not-set for Adar and Adar I only.

* `K ADAR` - `01 ADS 5684`
I now see this only in Adar II and Adar.

* `T ADAR` - `02 ADS 5613`
I now see this only in Adar II and Adar.

**Comment by fisharebest** [comment]
* `D Heshvan` - ` 30 CSH 5774`
* `A Heshvan` - ` 30 CSH 5684` - This date did not exist - in 5684 there were only 29 days.

Since `A Heshvan` has an invalid date, it does not get picked up by the anniversary logic, and is instead shown on "day not set".

I think this is OK.  It makes it easier to see that the date is invalid.

**Comment by fisharebest** [comment]
I have been through all the issues in the spreadsheet, and think they are now all fixed.
