### ISSUE TITLE
Data Fix - Convert Name:_XXX tags stopped - 2.0.7-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3407]
I tried to Convert Name:_XXX tags. After more than 65%, I see
TypeError: Failed to fetch
The utility stopped after I4225.
I have approved only a few of the changes.
I have downloaded today's log if we need it.

If I run the utility again, will it run from I1 or from I4225??

**Comment by fisharebest** [comment]
We update 100 records at a time.

If a block of 100 updates fails (server timeout, network glitch, or other error), then it will stop.

> If I run the utility again, will it run from I1 or from I4225??

It depeneds if the changes are automatically accepted.

It searches the current *and* pending versions of each record.
So, it may start from the beginning, but it may not need to change many of the records.

I took a copy of your GEDCOM file, and ran it on my dev machine.

It took about 1 hour to complete.  But it completed without error.

My guess is that a network error or similar caused the process to stop.
There would be no loss of data, or inconsistency.
Running the process again would continue.

**Comment by fisharebest** [comment]
I have tested this (by temporarily stopping the database while the update is running).
I can re-run the update, and it continues from where it stopped.

We cannot prevent network errors, but we do work around them.

**Comment by melizaa** [comment]
I tried to re-run the utility. It stopped again. If I am not mistaken, it updated 1 individual.

**Comment by fisharebest** [comment]
Can you tell me which site, etc. so that I can see the problem?

**Comment by melizaa** [comment]
I have only tested in the test test system.

Now I changed my user's definition to automatically accept changes and the utility finished.
The pended previous changes are still pended.

**Comment by fisharebest** [comment]
I have tried many more times to reproduce this, but it works every time for me.

**Comment by melizaa** [comment]
Did you try to run if with a user whose changes are not approved automatically?

**Comment by arbor95** [comment]
please close
