### ISSUE TITLE
Data Fix _XXX Name tags - The order of the name records - 2.0.7-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3408]
I tested the _XXX name tag fix in the test system.    

I see now my Hebrew names before my Latin names.      
The input had two NAME records, one Latin and after it one Hebrew. 
For indis with only one NAME record, I see 1. Latin name 2. Hebrew name 3. Latin married name 4 Hebrew married name, in the order of the input from Pre 2.0.0. 
I want to show on Latin pages the Latin names before Hebrew, Arabic, Russian, Thai, etc. names. 

We should see the names after the ID and before the sex and birth data at the top of the GEDCOM record.
Pre 2.0.0 Webtrees has written name records at the bottom of the GEDCOM record.
I hope that the fix program will be able to write the names in the correct sequence at the top of the individuals data.

**Comment by fisharebest** [comment]
We show the `1 NAME` records in the order that they appear in the GEDCOM data.

GEDCOM says that when you have more than one of the same data (e.g. more than one name), you put the prefered one first.

The edit menu contains a "re-order" names option, so that users can change the order.

**Comment by melizaa** [comment]
Some samples of what i see after the Data Fix. 

1. In pre 2.0.0 we see
Name
Ossi Kotschack
Given names
Ossi
Surname
Kotschack
Also known as
Oskar Kotschack
אוסי קוטשאק

The Latin 1 NAME at the top and the Hebrew one at the bottom of the individual data.

After the utility we see
 Name אוסי קוטשאק
 Name אוסקר קוטשאק — also known as
 Name Ossi Kotschack
 Name Oskar Kotschack — also known as

All the 1 NAMEs are at the end of his data

This order is not what we have in wt pre 2.0.0 and I do not like it.

2. We have
Name
Rivka …
Given names
Rivka
Hebrew
רבקה
Married name
Rivka Kawaler
Married name
רבקה קולר

This name order was created by phpgedview or by wt.

After I accept the change I see

 Name Rivka …
 Name רבקה …
 Name Rivka Kawaler — married name
 Name רבקה קולר — married name

Not the name order that I like. I like the order Rivka ..., Rivka Kawaler, רבקה and then the Hebrew married name. 

3. In the test system I have
0 @I926@ INDI
1 NAME Judel /Pergament/
2 GIVN Judel
2 SURN Pergament
2 _HEB יודל /פרגמנט/
2 _AKA Jehuda Josel Josef Jutka /Pergament/
2 _AKA יוסף /פרגמנט/
2 _AKA יהודה /פערגאמענט/
2 _AKA John /Pergament/
and other data

I create for him in wt online two 1 NAME records. 

The updated 1 NAME Judel /Pergament/ remained as the 1st record after the ID. The new Hebrew name is added at the end of Judel’s data. I expect it to remain at the top of Judel’s data after the Latin 1 NAME.

4. My site has individuals with Russian names or Thai names, in addition to Latin and Hebrew names.
We should see them after the Latin and Hebrew names.

5. My site has almost 30,500 individuals, at least some 20,000 of whom have _XXX names. 
I cannot transfer so many names manually.
Could we have a utility that would re-order the names based on their language.

**Comment by melizaa** [comment]
The created 1 NAMEs do not have name pieces, only the married and aka (also known as) types.
Could this cause any issues?

**Comment by melizaa** [comment]
I see Lom in the test system as
 Name שלום לום בונרודכוי
 Name שלום לום יאנמו — married name
 Name หลอม บญรอดชวย
 Name หลอม จนทรโม — married name
 Name Shalom Lom Bunrodchoy
 Name Shalom Lom Janmo — married name
In prod she is
Name
Shalom ‘Lom’ Bunrodchoy
หลอม บญรอดชวย
שלום ‘לום’ בונרודכוי

We see Olga in the test as
 Name ольга Горигин
 Name ольга Аронштамм — married name
 Name Olga Gorigin
 Name אולגה גוריגין
 Name Olga Aronstamm — married name
 Name אולגה ארונסתם — married name

She has in prod two 1 NAMEs, one with her Latin and Hebrew names and the second with her Russian name.

**Comment by fisharebest** [comment]
Currently the datafix keeps the order of each *type* of name.
e.g. all `_MARNM` are in the same order, all `_AKA` are in the same order, etc.

I will update it so that *all* name fields are in the same order.

> The created 1 NAMEs do not have name pieces, only the married and aka (also known as) types.
> Could this cause any issues?

No.  webtrees already extracts GIVN/SURN from these name fields, and it will continue to do so.

**Comment by melizaa** [comment]
I tested now a couple of names in the future test system.
The names are not sorted.

On my site we should see the Latin names before Hebrew, Russian and/or Thai names, preferably after the ID or the SEX data.

The sequence of the names and their position in the individual GEDCOM record were created by wt as a   result of the name update form.

I cannot update the name sequences manually.

[wtNameConvert.xlsx](https://github.com/fisharebest/webtrees/files/4976579/wtNameConvert.xlsx)

**Comment by melizaa** [comment]
We have started to split manually the Latin and Hebrew names.  We speak of some 10,000 individuals.
I do not plan to use the wt Data Fix _XXX Name tags.
