### ISSUE TITLE
Googlemaps - showing inactive places throws the list of errors

### ISSUE THREAD

**Issue by wooc** [fisharebest/webtrees#341]
ERROR 2: asort() expects parameter 1 to be array, null given
0 Error occurred on in function asort
1 called from line 4305 of file module.php in function adminPlaces
2 called from line 104 of file module.php in function modAction
3 called from line 33 of file module.php

Warning: asort() expects parameter 1 to be array, null given in /modules_v3/googlemap/module.php on line 4305

ERROR 2: Invalid argument supplied for foreach()
0 Error occurred on line 4310 of file module.php in function adminPlaces
1 called from line 104 of file module.php in function modAction
2 called from line 33 of file module.php

Warning: Invalid argument supplied for foreach() in /modules_v3/googlemap/module.php on line 4310

ERROR 8: Undefined variable: fieldrec
0 Error occurred on line 4314 of file module.php in function adminPlaces
1 called from line 104 of file module.php in function modAction
2 called from line 33 of file module.php

Notice: Undefined variable: fieldrec in /modules_v3/googlemap/module.php on line 4314

ERROR 2: Invalid argument supplied for foreach()
0 Error occurred on line 4319 of file module.php in function adminPlaces
1 called from line 104 of file module.php in function modAction
2 called from line 33 of file module.php

Warning: Invalid argument supplied for foreach() in /modules_v3/googlemap/module.php on line 4319

**Comment by fisharebest** [comment]
This is fixed in the new 1.8 code.
