### ISSUE TITLE
Import gedcom error message

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3411]
When importing a gedcom file from the server, the message "This form has expired. Try again" is displayed when the progress bar is displaying "calculating" (probably towards the end of that phase)

Nevertheless, the import continues to a successful completion
![dump](https://user-images.githubusercontent.com/104515/87346449-9ddcd000-c549-11ea-88c1-7c7fb8f2cea2.jpg)

**Comment by fisharebest** [comment]
That message would have been created on a previous page/request - not the the page that displays it.

It could even have come from a different tab, and even an unrelated request.

I don't suppose you are able to reproduce this?

**Comment by ddrury** [comment]
I've discovered that it happens when xdebug is enabled and then it consistently produces that message. Xdebug slows things down significantly on my machine so maybe a timing problem?

With xdebug disabled all is fine
