### ISSUE TITLE
Modules titles and description not translated when disabled

### ISSUE THREAD

**Issue by jon48** [fisharebest/webtrees#3413]
If the modules provides the translations for their own title and description (which is very likely), those are not loaded in the module list (`/admin/modules`) when the module is disabled, so they appear not-translated.

Should be just add the `$include_disabled = true` parameter in the following line, or are you afraid if could bring some unstability? 
https://github.com/fisharebest/webtrees/blob/7b284074109540a9b0565c5e7ba90553c940acef/app/I18N.php#L315

![image](https://user-images.githubusercontent.com/5150782/87607273-de2c8180-c6f4-11ea-9dde-a68181828b06.png)

**Comment by fisharebest** [comment]
> Should be just add the $include_disabled = true parameter in the following line

There are modules that use translations to convert webtrees to use dog and horse pedigrees.  e.g.

* "Father" => "Sire"
* "Mother" => "Dam"
* "Child" => "Foal"

If a module is disabled, then its translations should not be applied.

So, to translate the title, we would need to apply **only** the translation for the module name/description.

I do not think there is an easy way to do this.

**Comment by ric2016** [comment]
In my custom modules, I use a special translator for module title and description, [see here](https://github.com/vesta-webtrees-2-custom-modules/vesta_common/blob/master/ModuleI18N.php).

It is used like this (not very elegant, but it has the intended effect):
```
public function title(): string {
    $title = I18N::translate('Vesta Common');
    if (!$this->isEnabled()) {
      $title = ModuleI18N::translate($this, $title);
    }
    return $this->vesta . ' ' . $title;
}
```

**Comment by ric2016** [comment]
I think the PR is problematic because

1. Disabled modules may still (e.g. accidentally) override base translations because they can define anything via customMetadataTranslations();
2. Custom modules now have to manage two translation files per language.

The respective methods (title/description) already provide translated strings. Therefore it seems more straightforward to let the disabled module translate those directly, as in my approch.

**Comment by jon48** [comment]
I hear your comments, and this is just a proposal trying to provide the functionality within the existing framework (with the limitations you highlight).

I believe it would be good to have a consistent approach we can stick to (I do not mind which one), rather than each custom module writer coming up with one's own implementation, or copying the same mechanism over and over (there are a couple of other topics around custom modules in that vein).

**Comment by ric2016** [comment]
I agree it's not necessary for each custom module to re-implement this. We could put it as a helper method somewhere, maybe into ModuleCustomTrait?

Something like
`public function translateInternally(): string`

**Comment by fisharebest** [comment]
AFAICT, there are only two places where we show titles/descriptions of disabled modules.

The list of all modules.
The list of module components (menus, tabs, etc.)

We can translate the title/description for disabled/custom modules with this:

``` 
$module instanceof ModuleCustomInterface ?
 $module->customTranslations(I18N::languageTag())[$module->title()] ?? $module->title() :
 $module->title()
```

So, we can fix this problem without requiring changes to custom modules.
