### ISSUE TITLE
Data Fix _XXX Name tags - Empty main name created - 2.0.7-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3415]
When the input is 1 NAME // 2 _MARNM /xxx/ the utility creates also an empty 1 NAME name fact. We should not create this name.

**Comment by fisharebest** [comment]
I think we must keep this empty name.

We use the first name record as the display name for the individual.

If we have `1 NAME //` `2 _MARNM /xxx/`, then we show the name as "Unknown".

If we have `1 NAME //` `1 NAME /xxx/` `2 TYPE married`, then we still show the name as "Unknown".

But if we remove the `1 NAME //`, then we will show the name as `xxx`.

Also, the individual will no longer appear in the "Unknown" category of the individual list.
