### ISSUE TITLE
Lat and Lon have same values when editing sub-location

### ISSUE THREAD

**Issue by RottenSod** [fisharebest/webtrees#3418]
When a location has sub-locations and the location has lat and lon values set, the sub-location (I assume) should honour those values. Instead, the lat and lon both take the lat value, although the pointer on the map is set correctly.

![wtbug1](https://user-images.githubusercontent.com/111339/87874951-c93a4180-c9c5-11ea-9154-e05c1b1fa23a.png)
![wtbug2](https://user-images.githubusercontent.com/111339/87874984-0272b180-c9c6-11ea-8991-79e4adadf685.png)

**Comment by fisharebest** [comment]
Already reported and fixed.  See #3403
