### ISSUE TITLE
all persons are duplicated when importing a GED file

### ISSUE THREAD

**Issue by dportabella** [fisharebest/webtrees#3419]
I import a GED file on webtrees and the process works successfully.
However, all persons are duplicated.
I verified the GED file, and there are no duplications at all.

I've tried with my current installation of webtrees 1.7.3.
I've also tried with a fresh installation of webtrees using the docker image dtjs48jkt/webtrees.

What can be the problem?

**Comment by fisharebest** [comment]
I have never seen this, and have no ideas.

What were the exact steps that you took?
Were there any anomalies during the import process?

Is the problem repeatable?  If you import the GEDCOM again, do you have the same problem?

**Comment by dportabella** [comment]
Yes, the problem is repeatable. I've tried once on my current installation and twice on a fresh webtrees installation.
Steps:
----------------------
http://mydomain.com/webtrees/
-> login
-> my page -> control panel
-> family trees -> manage my family trees
-> GEDCOM file -> import ->
-> A file on the server -> [select my .GED file]
-> continue
----------------------
No errors shown.

My GED file is created by the software "Brother's Keeper for Windows 6.6". 
Using this java library, I did a software myself to transform the GED file into a static html file showing the family tree, and there were no duplicates.
https://github.com/FamilySearch/Gedcom

**Comment by fisharebest** [comment]
> I've tried with my current installation of webtrees 1.7.3.

This is a very old version of webtrees.  Perhaps it was a bug that has already been fixed?

Can you upgrade to 1.7.17?

**Comment by dportabella** [comment]
I also tried with a fresh installation of webtrees using the docker image dtjs48jkt/webtrees.
v2.0.6

**Comment by fisharebest** [comment]
Can you share the GEDCOM file with me, so I can see if the problem occurs on my development system?

greg@subaqua.co.uk

**Comment by dportabella** [comment]
I cannot for legal reasons :(
But I'll try to trunk the GED file to a few records, see if the error still happens, and send it to you.
Thanks for your help!
