### ISSUE TITLE
Monthy calendat grid missing in minimal theme - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3423]
The minimal theme monthly calendar is not printed in a table. I   do not know if this issue exists also in some other pages.
--

![image](https://user-images.githubusercontent.com/5202996/88099704-386d8c80-cba4-11ea-8cda-1a62151960e2.png)

**Comment by melizaa** [comment]
I see still the same page as before.
What was changed?

**Comment by fisharebest** [comment]
The data (grid) is loaded in a second request to the server.  This was missing some parameters.  See 74aba44

**Comment by melizaa** [comment]
In pre 2.0.0 I see the monthly calendar in minimal theme
![image](https://user-images.githubusercontent.com/5202996/88558938-e1990480-d034-11ea-9dbc-22f8712bde23.png)

In 2.0.8-dev I see still the monthly minimal theme calendar without the lines and without the selected day and month in red (like for the other themes)
![image](https://user-images.githubusercontent.com/5202996/88559270-49e7e600-d035-11ea-8f35-8a3cf2376ebd.png)

**Comment by melizaa** [comment]
Please open this issue.
