### ISSUE TITLE
Option to suppress unused locations

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#3424]
Enhancement Request

Enhance **Control Panel / Geographic Data** to give the user the option to "hide unused place names", this would make the process of finding and correcting errors much more straightforward due to the size of these lists (the highest-level country list contains over 500 entries and very few of us are in AFG or ABW  :)  )

Ideally, the value of this field would be retained from session to session as a preference and not need to be re-entered.

**Comment by fisharebest** [comment]
Question - if you do not have any events in AFG, then why not delete this location?

**Comment by eric215** [comment]
I could delete most of them as it is unlikely I have ancestors there. I didn't recall loading the country information and assumed they were part of the base Webtrees install.

**Comment by eric215** [comment]
I do have US states where I found information on counties or place-names within counties and pre-loaded them into webtrees to save having to look up each new place as it was added.  

When the geographic data page only showed errors to be fixed it was a non-issue but now I may have to re-think the approach

**Comment by ro-la** [comment]
There are a lot of csv files with coordinates for all places in a country/region/county. So I think for some users it cann be helpful to have all places from a region in the table and the possibility to hide the unused places cann be a good chois. This is not my work flow, but somebody cann work this way.

**Comment by fisharebest** [comment]
I have done this, but I am not 100% happy with it.

It takes a complex database query to find out if a place is used or unused.

So, having 100s or 1000s of unused places will make the page slow.

We should encourage users to delete unused places, not to hide them.
