### ISSUE TITLE
Geographic Data page - Error handling Lat/Lon

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#3426]
When the _edit_ icon is selected on any line from the **Control Panel -> Geographical Data** page the Lat/Lon boxes are pre-filled but both fields always contain the Latitude, even when the prior page showed separate/correct values for Lat + Lon.

When the place being edited does **not** have a known Lat/Lon, the values displayed seem to come from the place's parent location

![Pic_a](https://user-images.githubusercontent.com/13973937/88245102-e55b0e80-cc63-11ea-8f69-12e990c48bb5.JPG)
![Pic_b](https://user-images.githubusercontent.com/13973937/88245109-e9872c00-cc63-11ea-8846-9fbda1b478e3.JPG)
![pic_c](https://user-images.githubusercontent.com/13973937/88245128-f9067500-cc63-11ea-9d3f-ccf5daa4ea85.JPG)
![pic_d](https://user-images.githubusercontent.com/13973937/88245134-fb68cf00-cc63-11ea-87c4-6b8df795b1d4.JPG)

**Comment by marku5** [comment]
Allready fixed: #3376
