### ISSUE TITLE
Tabs loaded twice on Individual Page

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#3429]
Tabs that return false for `canLoadAjax()` (such as the Facts & Events tab) are loaded twice, once directly and once via ajax (regardless of the return value of this method), apparently because the javascript in `individual-page.phtml` loads all tabs via ajax unconditionally.

I think there is a check missing wrt `canLoadAjax()`, e.g. [here](https://github.com/fisharebest/webtrees/blob/9ee82875dc514859cb0f28e95d21ce0ef0bb3568/resources/views/individual-page.phtml#L113) (data-href attribute should only be set if the tab may be loaded via ajax?).

(or I don't understand the point of the `canLoadAjax()` method - by the way: why is it set to false in `IndividualFactsTabModule.php` and other tabs anway?)

**Comment by fisharebest** [comment]
This looks like a regression introduced in 5675e46e95889fb28aff4062c093dba0f879e5f5

**Comment by fisharebest** [comment]
> I don't understand the point of the canLoadAjax() method - by the way

If the function returns false, then we generate the tab at the same time that we generate the page.

If the function returns true, then we generate an empty tab, and load it via AJAX when it is first used.

It is typically used on tabs that make other AJAX/HTTP requests (e.g. interactive tree, map).

**Comment by ric2016** [comment]
ok, I guess the name of the method is a bit misleading then - it's actually more like "preferablyLoadedViaAjax()". Not a big deal.

**Comment by fisharebest** [comment]
> I guess the name of the method is a bit misleading then

Agreed.  But it is now part of the API, so it is difficult to change.
