### ISSUE TITLE
I do not see some individuals in in the search by place or in the Place hierarchy - 2.0.7-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3430]
When I search for "San Miguel de Allende, Mexico" in my test or future test systems, the individual who has a residence in this town is not returned. 
I do neither see the individual in the test Place Hierarchy.

I do see the place in the Places map on the individual page. 

When I search the individual by her other residence town, she is returned.

If I search by "San Miguel Allende, Mexico", I see the individual.

**Comment by fisharebest** [comment]
We process each search term in turn.  After we process it, we remove it from the search string.

After we process "de", we remove it - which also removes it from `Allende,` - to give `Allen,` which does not exist in the data.
