### ISSUE TITLE
The Control panel - Map - Geographic data - Latitude and Longitude are missing for many places - 2.0.7-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3431]
In Control panel - Map - Geographic  data  I see yellow triangles with white ! Icons for the Latitude and Longitude of many countries and places. 
If I hit edit for the place, I see values in the Latitude and the Longitude.

I see these places in the individual maps and in the Place Hierarchy maps.

(I define the latitude and longitude manually.)

**Comment by fisharebest** [comment]
> If I hit edit for the place, I see values in the Latitude and the Longitude.

What values?  Zero?  Something else?

These are numeric fields.  I would expect the browser to be initialise them with zero.

**Comment by melizaa** [comment]
I see values of the Latitude and the Longitude that seem to be of the Country or State/Territory...

Sample: Faroe Islands on the Geographic data for countries.
![image](https://user-images.githubusercontent.com/5202996/88467111-0e85d400-cedc-11ea-9032-9b434f509833.png)

I click on Faroe Islands and see
![image](https://user-images.githubusercontent.com/5202996/88467210-43def180-cedd-11ea-9b98-9d89d7804ecf.png)

I edit it and see the rounded coordinates of Faroe Islands.
![image](https://user-images.githubusercontent.com/5202996/88467243-adf79680-cedd-11ea-90a5-2e104cc3ada9.png)

It is not yet clear to me why I see so many places with these missing coordinate icons.
I will try to look at this again.

**Comment by fisharebest** [comment]
When you add missing co-ordinates, the default value is the parent location.

So, when you create co-ordinates for Torshavn, the default co-ordinates are those of the Faroe Islands.

**Comment by melizaa** [comment]
I have not exported and imported the existing place coordinates to my test systems.
I will try to do it.

**Comment by melizaa** [comment]
I downloaded the places from pre 2.0.0 and imported the file to 2.0.8-dev. Now I see the missing places as expected.

I tried to look at the downloaded csv file.
I do not see the special letters as expected. The special characters are for instance ä, å, ö, ø, ü, א-ת.
I see that this is a known issue. Can we solve it?
<https://wordpress.org/support/topic/umlaute-special-characters-in-export-files/>
