### ISSUE TITLE
False focussing in merge XREF dialog

### ISSUE THREAD

**Issue by AndreasRauhut** [fisharebest/webtrees#3442]
The merging records dialog in the admin panel is working fine for all kind of records. 
- Sources
- Families
- Media Objects
- Repositories
- Notes
- Submitters

But when I choose to merge **Individuals** the first mouse click in one of  the fields "First record" or "Second record" sets the focus of the cursor a little bit under the new input field.  
The result of this:  the text I try to enter goes to the nirwana. 

I have  to place the cursor manually with a second click in the middle of the input field. Then I can type the name or the XREF.

**Comment by fisharebest** [comment]
I think this is caused by a bug in the select2 library: https://github.com/select2/select2/issues/5993

**Comment by fisharebest** [comment]
We have replaced `select2` with `tom-select`, and the problem appears to be fixed.
