### ISSUE TITLE
views\lists\datatables-attributes - a suggestion

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3445]
For the pagination control, translations are provided for "first" & "last" buttons, however these aren't used.

My suggestion is to provide an extra line to the file `data-paging-type="full_numbers"`, however I accept that in situations with a lot of pages this can result in an overly long control. I suppose rather than text the character equivalents of "<<",  "<", ">", ">>" could be used

![demo](https://user-images.githubusercontent.com/104515/88718233-93116600-d119-11ea-98bb-fc606b3165d1.jpg)

**Comment by fisharebest** [comment]
The existing pagination control shows the first and last page (by number) - `1` and `90` in this case.

So, they are not really needed here?

I think other pagination options don't include the end pages - and so first/last buttons may be useful in those cases.

**Comment by ddrury** [comment]
With my PR (https://github.com/fisharebest/webtrees/pull/3702) I made an executive decision and went with icons and full numbers. If, as I suspect, you're not going with the PR then stick with things as they are.
