### ISSUE TITLE
Case Sensitivity in Geographic Data 2.0.7

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3446]
The `/admin/map-data` pages have a new(?) problem in v2.0.7.

I have a place name standardized as "B'nai David" in my family tree records.  Within the Geographic data, however, it displays as "B'Nai David".  Starting in v2.0.7, the Geographic data screen shows a Delete icon and no facts link.

At the same time, the Place hierarchy list shows that there are still 8 individuals referencing this place.

I am able to edit the name in the Geographic data to match the "B'nai David" casing, and after doing so the facts link appears and the Delete icon disappears as expected.

**Comment by fisharebest** [comment]
MySQL uses a case-insensitive colation.

It is also insensitive to diacritics.  So, if you have both `Quebec` and `Québec` in your genealogy data, then the geographic data can only contain one of these - whichever was found first.

We extract a full list of which trees use which place using SQL.
We extact a full list of all locations using SQL.

But we compare them using PHP (which is case-sensitive).

To fix this, we'll probably need to use separate SQL queries for each location on the page, which could have a significant impact on performance.

**Comment by miqrogroove** [comment]
PHP can do case-insensitive comparisons and should be much faster than adding trips to the database.

**Comment by fisharebest** [comment]
We need locale-insensitive, rather than case-insensitive.  e.g. `e` = `é`, and `ß` = `SS`

**Comment by miqrogroove** [comment]
Yes, I'm seeing a similar problem where I used the Data Fix to rename Saint-Octave-de-Metis to Saint-Octave-de-Métis and now the Geographic Data page displays it as having no records, even though the facts and the geo name match perfectly.
