### ISSUE TITLE
Migrate code to a MVC framework

### ISSUE THREAD

**Issue by WorkingDevel** [fisharebest/webtrees#345]
Hello everyone,

I really like webtrees for managing my pedigree and as a professional PHP developer I wood like to contribute to the project, but I find it really hard with the current grown code base.

Is there any plan to base the code on any proven MVC framework? If, what framework did you consider? If not, would you consider to migrate to one? And which one would you like to prefer?

In all cases I would like to contribute or do the main efforts...

Best,
Christoph

**Comment by WorkingDevel** [comment]
Yeah, unfortunately most of the code seems impossible to be unit tested. But acceptance/regression testing with behat (http://behat,org) is maybe possible... I'll play a try a little bit with it

**Comment by bmhm** [comment]
Perhaps we can have integration testing, i.e. set up a some automation which will: login, create a family tree, import a gedcom file...
For java, there is maven and some surefire plugins. I excpect something similar to exist for php. Would that be helpful?

@WorkingDevel Why not start contributing modules or extracting the gedcom functionality to a module? Or writing documentation :-)

**Comment by WorkingDevel** [comment]
@bmhm I will not start doing something when it's not clear that it's needed or accepted.
First, I would say, we need a decision where we want to go, what can be done for that and what are the requirements that a PR will be accepted by @fisharebest 

Integration testing is in either way hard with this code as long as we have scripts that are executed at their include time. We should transform these scripts into classes (maybe by just wrapping it into a class with one public method that will be executed after including the script). Separation of output from control logic is also a big issue.

**Comment by fisharebest** [comment]
For the last year, I have been refactoring the code to follow the Laravel structure.  This will continue.

Once this is complete, the switch to Laravel should be straightforward.
