### ISSUE TITLE
Date input does not autocorrect in 2.0.7

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3451]
When entering as a date:
- 27 jan 2005
- 27.01.2005
- 27012005
this is not autocorrected to 27 JAN 2005. It is necessary to enter exactly 27 JAN 2005, This was more flexible in version 2.0.6.

**Comment by marku5** [comment]
Already discussed in #3439.

**Comment by TheDutchJewel** [comment]
>Already discussed in #3439.
fisharebest closed this 10 minutes ago

Yes, it's discussed, but the problem is **not** fixed yet.
