### ISSUE TITLE
Locations - Delete available when place is in use

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#3454]
I have two top-level entries showing for Netherlands, however the one with the option to delete also has a lower-level entry that is "in use" in the tree, so I should not be able to delete it.

ver 2.0.7

![image_a](https://user-images.githubusercontent.com/13973937/89092985-5f864400-d384-11ea-92ad-032f71d4b436.JPG)
![image_b](https://user-images.githubusercontent.com/13973937/89092986-601eda80-d384-11ea-9061-8229484dea94.JPG)
![image_c](https://user-images.githubusercontent.com/13973937/89092987-601eda80-d384-11ea-9049-bfdcb79289f4.JPG)

**Comment by fisharebest** [comment]
It should not be possible to have two places with the same name.

There is a unique index on the database table to prevent it.

Perhaps one of these contains a non-printing character in the name?

**Comment by eric215** [comment]
Yes, there is a 0x20 on one of the entries, and I will fix that; that extra character made it unique, should I be concerned that the PHP logic determined that entry was valid to delete even though it had an in-use child?

![img_a](https://user-images.githubusercontent.com/13973937/89106840-f5f54c80-d3fa-11ea-8fa2-03ebeecabbbe.JPG)

**Comment by eric215** [comment]
This is the structure of my place_location table, it does not have a "unique" constraint on the "place", is that an issue on my end or did you mean it was a software-controlled constraint?

![image_a](https://user-images.githubusercontent.com/13973937/89108997-58564900-d40b-11ea-8585-c509caeb840c.JPG)

**Comment by fisharebest** [comment]
The `pl_id` number for the row is very low (156).

I guess that the space was added by a very old version of the code.  That should not be possible now.

You need to delete the value with the space.
(Or delete 71193 and remove the space from 156.)

> it does not have a "unique" constraint on the "place"

It seems that webtrees 1.7 didn't create the index - but 2.0 does.

The program logic should ensure that duplicates aren't created - and the unique index enforces it.
Here is the structure created by the latest code.

If you wish, you can add the missing index.

```
CREATE TABLE `wt_placelocation` (
  `pl_id` int NOT NULL,
  `pl_parent_id` int NOT NULL,
  `pl_level` int NOT NULL,
  `pl_place` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `pl_long` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pl_lati` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pl_zoom` int DEFAULT NULL,
  `pl_icon` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`pl_id`),
  UNIQUE KEY `wt_placelocation_pl_parent_id_pl_place_unique` (`pl_parent_id`,`pl_place`),
  KEY `wt_placelocation_pl_place_index` (`pl_place`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

**Comment by eric215** [comment]
This can be closed out - I fixed the data
