### ISSUE TITLE
Notes Using Markup - Image not sized to fit within display space?

### ISSUE THREAD

**Issue by Norwegian-Sardines** [fisharebest/webtrees#3456]
I have use Notes to help readers learn about places in historical context, in particular where a group of family members once lived that no longer exist in modern times. The Note uses markup to display the content with headers, paragraphs and bolding. I also include a historical map showing the boundaries of the place in historic times.

The inclusion of the map (any photo would do this) causes the sizing of the space to use the actual size of the image rather than keeping the border consistent.

Without Image:
![Without Image](https://user-images.githubusercontent.com/66341154/89109906-386a5980-d3fa-11ea-99f4-30ff966b0da3.jpg)

With Image:
![With Image](https://user-images.githubusercontent.com/66341154/89109910-41f3c180-d3fa-11ea-856e-9762758d37a1.jpg)

**Comment by eric215** [comment]
(Assuming this is the same issue) It happens for me when a "Census" shared note is present without a picture/image

[(https://behunt.net/ft/tree/hunt.ged/individual/I32/Edward-Ebenezer-Fowler)]

![image a](https://user-images.githubusercontent.com/13973937/89140504-ce43d880-d50f-11ea-9714-6772351a2ebd.JPG)

**Comment by ro-la** [comment]
On the forum was this (or very similar) bug also reported 
here: https://www.webtrees.net/index.php/en/forum/help-for-2-0/34103-too-long-url-in-citation-breaks-the-layout
and here: https://www.webtrees.net/index.php/en/forum/help-for-2-0/34035-format-problem-with-shared-note-from-census-assist

And there is a second problem - on PC/notebook it is not possible to display the right margin of the blocks - you have to resize  the browser window, what cann be a problem  on a smaler display. On a smart device it is possible to move easily the display with the finger.
![image](https://user-images.githubusercontent.com/60657963/89168683-7e9bf600-d57d-11ea-854b-2f62b3dfe84e.png)

**Comment by fisharebest** [comment]
> And there is a second problem

1) PLEASE create a separate issue for each problem.

2) there is already an open issue forn this - #1427
