### ISSUE TITLE
Postgres 10 -  "No records to display" when records exist

### ISSUE THREAD

**Issue by wiljaxon** [fisharebest/webtrees#3459]
When List -> Individuals or List -> Families selected, a list of families or individuals are presented, but when selected "No records to display" when records known to 
![1](https://user-images.githubusercontent.com/3988661/89126555-514c3b00-d4de-11ea-961b-d8ace403482d.png)
![2](https://user-images.githubusercontent.com/3988661/89126556-51e4d180-d4de-11ea-947a-c71f35e16bcd.png)
![3](https://user-images.githubusercontent.com/3988661/89126558-527d6800-d4de-11ea-9cff-6e8152e0efd4.png)

exist. Attached screenshots 1 & 2 are PostgreSQL, the 3rd Webtrees using MySQL showing the expected records.

**Comment by fisharebest** [comment]
This is due to database collation rules.  In MySQL, `Smith` is the same as `SMITH`.  In Postgres, they are different.

The individual list relies on the case-insensitive matching...

**Comment by wiljaxon** [comment]
I've patched this file but I get the same result as before (in both Firefox & Chromium browsers), restarted Postgres and Apache. I must have overlooked something?

**Comment by fisharebest** [comment]
It isn't fixed yet.  The problem is harder than I first thought.

The only "cross-platform" solution I found does not use indexes, so may have performance issues on large sites.

**Comment by wiljaxon** [comment]
OK, I'd help if I could! Wonder how many Webtrees users rely on PostgreSQL, I became interested in it when I thought MySQL may get 'privatised' by Oracle.

**Comment by fisharebest** [comment]
According to the [Postgres 12 documentation](https://www.postgresql.org/docs/12/sql-createcollation.html), it should be possible to create collations in Postgres to match the ones used in MySQL.

But I have been unable to find any examples of this...
