### ISSUE TITLE
Dateless death records fix creates "grim reaper" impression.

### ISSUE THREAD

**Issue by photon-flip** [fisharebest/webtrees#3464]
To override the "private" designation of obviously dead individuals we use the workaround of manually added dateless death records and/or the "add missing death records" fix. 
Charts then become littered with many individuals with just their name and the word "Death" - a rather ominous sight - like the grim reaper has visited the tree.
Adding a second if() statement to the "Show DEAT or equivalent event" section of resources/views/chart-box.phtml to check if a death date is present fixes this to display only deaths that have a date to show. 

```
// Show DEAT or equivalent event   
            foreach (Gedcom::DEATH_EVENTS as $deattag) {             
                $event = $individual->facts([$deattag])->last();
                if ($event instanceof Fact  ) {
                    if($individual->getDeathYear()){
                    echo $event->summary();                  
                    if (in_array($deattag, $opt_tags, true)) {
                        unset($opt_tags[array_search($deattag, $opt_tags, true)]);
                    }
                    break;
                 }
                     
              }
        }
```

**Comment by fisharebest** [comment]
As genealogists, we are used to dealing with dead people (!), so I don't really get the "grim reaper" concern.

If you know that an individual is dead, then an empty death record is the standard way to record it.

BTW - your modification doesn't take into account deaths where the date is unknown, but the place is known.  e.g.

```
1 DEAT
2 PLAC London, England
```

Instead, you might want to use `$fact->value() === 'Y'`.

----------

Another option for you to consider is to add a privacy restriction "show to visitors", instead of a death record.  e.g.

```
1 RESN none
```

Now, webtrees will know that the individual is public, so will not need to run the living/dead calculations.

----------

Alternatively, if you want to follow the convention (of adding `1 DEAT Y`), but do not want your visitors to see the record, then you can add a "private" death record - again using a privacy restriction.

```
1 DEAT Y
2 RESN privacy
```

This record will be used for privacy calculations, but will not be shown to visitors.

**Comment by photon-flip** [comment]
I’d suggest that most people visiting Webtrees based family trees are not hardened genealogists but family members interested in their relatives and personal relationships. In my experience some can be a little “sensitive”. While my “grim reaper” remark was intended to be light hearted (I should have added a smiley) I seriously believe that for a lot of people, charts with many family names followed by nothing else but the word Death is not a good look.  

Even if for genealogists the empty death record is the standard way of recording an individual as dead, from a programming and UI/UX point of view displaying an event title with no content is surely not ideal or indeed intended and is an issue. 

The other options you mention might be fine for a few records but this issue came to light when using the data fix "add missing death records" to bulk fix over 500 individuals. Those options are just not practical for that and the bulk adding of 500 Death words is quite noticeable.

My fix for removing the death record with unknown date does unintentionally remove the known place as well – thanks for catching that - but the result of your code suggestion removes all death details and displays the Death title for empty deaths again. I’m not sure why it does that, the logic looks ok. One observation is that any death fact unsets 1 DEAT Y. An extra check step is needed to work as intended. 

I’m very disappointed that you have closed this issue. The discussion #34786 around missing death records on the Webtrees Help for version 2.0 Forum involved 21 replies and 331 views in 1 week.
Would it be more appropriate if I discussed this on the forum rather than as an issue here?

If you do still consider this issue closed, I do hope I can ask your advice on how to properly set up this fix in my custom Theme Module. I have it working but I’m sure not in the most efficient manner.

**Comment by photon-flip** [comment]
`$fact->value() === ''` works as the if statement.

**Comment by fisharebest** [comment]
> Would it be more appropriate if I discussed this on the forum rather than as an issue here?

Yes.

This issue tracker is the place to report bugs - and as far as I can tell, the code is working as designed.

You are proposing a change to the way webtrees has worked for very many years.

You would need to build a consensus for change in the webtrees community, and the place to do that is the forum.

Very few people look at the issue tracker.

> from a programming and UI/UX point of view displaying an event title with no content is surely not ideal or indeed intended and is an issue.

Previously, we showed events without date/place as "Death: yes" or "Divorce: yes", etc.

This fairly accurately represented the underlying data (`1 DEAT Y`, `1 DIV Y`, etc.)

But there was a discussion on the forum to remove the "yes".

**Comment by fisharebest** [comment]
> Previously, we showed events without date/place as "Death: yes" or "Divorce: yes", etc.
> This fairly accurately represented the underlying data (1 DEAT Y, 1 DIV Y, etc.)
> But there was a discussion on the forum to remove the "yes".

And a more recent one, which campaigned to bring it back.

https://www.webtrees.net/index.php/en/forum/2-open-discussion/34919-1-deat-y-output
