### ISSUE TITLE
Reduced image quality in 2.0.7

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#3465]
Since 2.0.7 I noticed images are displayed in bad quality, and zooming in on images of documents makes many of them barely readable. Could this be related to Pinch-zoom?
I do not have 2.0.6 running at the moment, but have images from 1.7.17 and 2.0.7 for comparison.

In 2.0.7 right clicking the image in viewer also allows downloading the original (higher) quality image, unlike in previous versions where you only get a 1x1 download.png

![wt207](https://user-images.githubusercontent.com/55854079/89320914-74175480-d682-11ea-82ab-c1d5e778003c.png)
![wt17](https://user-images.githubusercontent.com/55854079/89320918-75488180-d682-11ea-9dc3-1f84fa75a4d1.png)

**Comment by miqrogroove** [comment]
You may add your complaints to #3366 

I've posted a fix in there but it remains a serious problem.

**Comment by HRN65** [comment]
@miqrogroove 
I've already changed the 'q' value, but this only seems to affect the thumbnails.
It seems a low format image is sent to the viewer?

Try looking at this image file. Then right click and dowload to see original:
https://visitusinmaputo.com/webtree/tree/29082010.GED/media/M10428/Tingbok-1

**Comment by miqrogroove** [comment]
I'm seeing 1958x1536 resolution both inline and downloaded in Chrome for Windows.

Did you say the problem was specific to a mobile browser?

**Comment by HRN65** [comment]
Inline I see 728x559. Zooming makes it impossible to read the text
Actually, It appairs the image size is determined by the screen resolution.

![image](https://user-images.githubusercontent.com/55854079/89689488-cb2c5c00-d904-11ea-8c0a-981650f5382d.png)

**Comment by fisharebest** [comment]
> Try looking at this image file. Then right click and dowload to see original:
> https://visitusinmaputo.com/webtree/tree/29082010.GED/media/M10428/Tingbok-1

Have you modified the "watermark" file?
If a watermark is applied, then we must generate a new image, which uses the `q` value.
Thus we are sending a generated image.
It is only without the watermark that we send the original image.

> Actually, It appairs the image size is determined by the screen resolution/dpi.

For thumbnails, this is true.
We give the browser a choice of 4 images sizes (x1, x2, x3 and x4), and the browser will choose one according to the DPI of the display.

**Comment by HRN65** [comment]
Yes Greg, I have customised the watermark.png
However, even when logged in (no watermark) I see this behaviour, and image size will change with screen resolution.
Please see
https://visitusinmaputo.com/webtree/tree/29082010.GED/media/M10428/Tingbok-1

**Comment by HRN65** [comment]
Did a new install of 2.0.6 to compare, and here the images are fine. In 2.0.7 the images get blurry when zooming in.
Here you can see images from 2.0.6 and 2.0.7 when logged in (no watermark)


![206](https://user-images.githubusercontent.com/55854079/89934438-d89d5b00-dc10-11ea-94b2-70cc62824b92.png)
![207](https://user-images.githubusercontent.com/55854079/89934440-d9ce8800-dc10-11ea-8c80-05b4f7681a69.png)

**Comment by HRN65** [comment]
Innstalled latest JustLight theme for testing, and found using this theme the images are displayed in original quality!
See difference between fab and JustLight themes (2.0.7)

![207_fab](https://user-images.githubusercontent.com/55854079/91644959-577ff980-ea41-11ea-9462-d9c18f08f577.png)
![207_JustLight](https://user-images.githubusercontent.com/55854079/91644960-5949bd00-ea41-11ea-81d9-6da9e07c7af2.png)

**Comment by fisharebest** [comment]
Fixed in 6577bfc3111b4789852b83f46e19d92c9b59921c
