### ISSUE TITLE
all images appear as "500" in pink square after upgrade

### ISSUE THREAD

**Issue by chrisbeckstrom** [fisharebest/webtrees#3466]
I just upgraded from 1.7.0 to 2.0.7, manual upgrade. Everything seems to work fine - no errors or anything, but every image is appearing as a pink square with the number "500" inside it. This happens for existing images as well as new images I upload.

Browser: Chrome, running on Windows 10. Same behavior in Edge.

Media files live in what I think is the normal place, `webtrees/data/media/`

No webserver errors (apache). There is an error that appears in the browser console - 

```
DevTools failed to load SourceMap: Could not load content for https://familytree.chrisbeckstrom.com/public/js/vendor.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

...but this appears even when I'm trying to load a page with no images.

However, if I navigate to a media file's page, eg `https://familytree.chrisbeckstrom.com/index.php?route=%2Ftree%2Fbeckstrom-tuggle%2Fmedia%2FM19%2Fname-of-image-jpeg` and click "download file," I can successfully download the file and it will display perfectly on my local computer

I suspect there is something going on with thumbnails or caching, but I can't figure it out.

Any ideas? Please and thanks!

**Comment by fisharebest** [comment]
Did you see https://webtrees.net/faq/thumbnails/

**Comment by fisharebest** [comment]
It's good that you are using 2.0.7 - as this provides additional error information in the HTTP responses.

I see errors like this:

> Impossible  to create the root directory "data/thumbnail-cache/media/Becker,  Charles - Charles - Catharine - et al 1870 census.jpg

webtrees is trying to create a *folder* with this name (yes - the folder will end in `.jpg` - the actual thumbnails get stored in this folder).

Check file permissions?   Maybe delete data/thumbnail-cache (control panel, clean-up data directory), and let webtrees re-create it?

**Comment by chrisbeckstrom** [comment]
thanks for your help, @fisharebest !

I tried a variety of `chmod -R ... ... data` commands, and finally found one that worked - thumbnails are working now. I think my permissions are now much too open and I'll need to restrict them some more, but at least I've confirmed what was causing this.

Thanks so much, I love webtrees and the v2 is fantastic.
