### ISSUE TITLE
Webtrees deals differently with the TYPE of Marriage and Marriage banns

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3470]
Webtrees deals differently with the TYPE of `Marriage` and `Marriage banns`:

> 1 MARR
> 2 TYPE civil

-> Civil marriage

> 1 MARB
> 2 TYPE civil

-> Marriage banns, Type: civil

Why is that?
Is it possible to treat `Marriage banns` the same as `Marriage`?
If not, is it possible to translate the TYPE in case of `Marriage banns` by default? Because now it's untranslated.

**Comment by fisharebest** [comment]
Marriage banns are when you announce an upcoming wedding at a church.
Traditionally, you do this on three consecutive Sundays.

So, there is no such thing as "civil marriage banns"???
It is a religous event...

For marriages (`MARR`), we have special code that can recognise three `TYPE` keywords.
For these, we do not translate the `TYPE`.  Instead, we modify the event name.

`civil` => CIvil marriage
`religious` => Religious marrage
`partners` => Registered partnership

**Comment by TheDutchJewel** [comment]
In the 18th century, people who wanted to get married had to pay wedding money.
Look [here]( https://translate.google.com/translate?hl=&sl=auto&tl=en&u=https%3A%2F%2Fnl.wiktionary.org%2Fwiki%2Ftrouwgeld) for a Google translated article about it).
So it's civil.

This facts are registered in the GEDCOM file I got, as `1 MARB, 2 type civil`. Is this not correct for this facts?

**Comment by fisharebest** [comment]
So you must pay money for permission to marry?

I think this is a "Marriage licence".  GEDCOM = `MARL`

**Comment by TheDutchJewel** [comment]
Thanks.

I'll have to check all the about 300 `MARB` families to know if I've to change this events to `MARL` (wedding tax), or that I've to remove the `TYPE civil` for `MARB`.
