### ISSUE TITLE
2.0.7 - Ancestor Report: unnecessary space character after marriage date

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3472]
In the Ancestors Report (ahnentafel_report) there's an unnecessary space character after the year of the marriage date.

example:
`[...] married January 1, 1874 .`

**Comment by t-karcher** [comment]
This character was added deliberately for marriages without place data: 
https://github.com/fisharebest/webtrees/blob/3f9fe4dda0367a1808c06abe6d271a14c93182d1/resources/xml/reports/ahnentafel_report.xml#L278-L280

Removing line 279 would fix this issue, but I'm not sure why it was added in the first place? Some RTL issue maybe?

**Comment by fisharebest** [comment]
> but I'm not sure why it was added in the first place?

I don't think it is needed for anything.
