### ISSUE TITLE
French Translation issue for : aged

### ISSUE THREAD

**Issue by ckl67** [fisharebest/webtrees#3479]
Dans le cas d'une personne de sexe féminin, il faudrait mettre le terme "âgé" au féminin à savoir "âgée"

In case of a female person, the word aged : "âgé" should be translated  in "âgée"

I have checked on https://translate.webtrees.net/translate/webtrees/webtrees/fr/?q=aged&type=all&ignored=&checksum=&offset=1

But I didn't find how to have the option

Thanks

**Comment by ckl67** [comment]
One possibility would be to get the gender of the individual, and depending on it, to propose the correct translation
Style:

(if %... [-->man ] then agé %s else agée)

Is that possible ?

**Comment by fisharebest** [comment]
There are two similar translations:

`age %s` - present age of a living individual
`aged %s` - historic age of an individual at an event.

Do both translations need the male/female - or just `aged %s`

**Comment by ckl67** [comment]
Only the second one 
aged %s - historic age of an individual at an event.

**Comment by ckl67** [comment]
My proposal to fix this issue. 
To add a new properties $gender in class Age
Constructor by default: "M"
    public function __construct(Date $x, Date $y, $Gender="M")

Called in IndividualPage.php
$age = (new Age($bdate, $ddate,$individual->sex()))->ageAtEvent(false);

For that
It is needed to create a new entry in Weblate "agedF" corresponding to Femal
For France
aged ="agé"
agedF = "agée"

Fix in ageAtEvent(..)

        if ($this->gender === 'F') {
            /* I18N: The age of an individual at a given date for a femal individual */
            return I18N::translate('(agedF %s)', $age);
        } else {
            /* I18N: The age of an individual at a given date */
            return I18N::translate('(aged %s)', $age);
        }

Agreed ?

I'm not able to create an account on: https://translate.webtrees.net/projects/webtrees/
So I guess this is the only way to created this new entry : agedF

Can you unlock the situation ?

Same quest / translate to fix: #3476

**Comment by ckl67** [comment]
Fixed with
        if ($sex === 'M') {
            /* I18N: The age of an individual at a given date for a Male individual */          
            return I18N::translateContext('MALE', '(aged %s)', $age);
        } 
        if ($sex === 'F') {
            /* I18N: The age of an individual at a given date for a Female individual */          
            return I18N::translateContext('FEMALE', '(aged %s)', $age);
        }
