### ISSUE TITLE
invoking Javascript date-picker changes year

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#3480]
I had one of my wife's relatives with only the year for date of death and one with year and month.  When I found obituaries, I clicked the edit icon for those events, and then the calendar icon.  In both cases, it launched with the prior year in the picker and changed the text field to that year before I actually clicked on any date.

Version 2.0.7

**Comment by fisharebest** [comment]
I don't see anything like this.

If I have an incomplete date, the data-picker opens at 1st January of the same year.

It doesn't update the edit field unless I select a date.

**Comment by WGroleau** [comment]
Strange.  Could it be a Javascript bug relating to time zone?  Mine switches to December of the prior year.  I didn't notice what date was on the calendar, but it left the edit field as only a year but changed it to the prior year.  Currently, my webtrees time zone is UTC but the web server is in San Francisco and I am in Oregon.

**Comment by fisharebest** [comment]
>  Could it be a Javascript bug relating to time zone?

That will be it.

It seems that when you create a javascript `Date` object, it assumes you have given in UTC.
But when you extract the parts, it uses local time.
