### ISSUE TITLE
302 error when submitting the contact form

### ISSUE THREAD

**Issue by marc1aj** [fisharebest/webtrees#3485]
I was setting up email on my site and when I submit/send the message, I get this error:

The page isn’t redirecting properly

An error occurred during a connection to genfamtrees.com.

    This problem can sometimes be caused by disabling or refusing to accept cookies.

The resultant URL is https://genfamtrees.com/?route=%2Ftree%2Fameenoodeen/index.php?route=0 

Fortunately, the message itself is sent and received but it does not make for a good browsing experience if you think the site is broken. Does anyone know what can cause this particular to happen?

Thanks,
Marcia

**Comment by marc1aj** [comment]
Only the db information is in that file. There is no reference to base_url or rewrite_urls. Where is else is a config.ini file?

**Comment by fisharebest** [comment]
> Where is else is a config.ini file

http://webtrees.net/faq/config-ini-php/

> There is no reference to base_url or rewrite_urls

`base_url` is created when you install webtrees 2.0

If you installed webtrees 1.x and upgraded to 2.0, then you must add the entry yourself.
See http://webtrees.net/upgrade/2.0/

You would add an entry for `rewrite_urls` when you enable "pretty URLs".
See http://webtrees.net/faq/urls/

**Comment by marc1aj** [comment]
Thank you. That did the trick.
