### ISSUE TITLE
Lost many location coordinates

### ISSUE THREAD

**Issue by bombaata** [fisharebest/webtrees#3486]
Hi, using webtrees 2.0.7, I lost many location coordinates since last update (2.0.6 to 2.0.7).

In Geographic data list, the cities and coordinates are displayed correctly : 
![image](https://user-images.githubusercontent.com/65110137/90986487-931f4d00-e583-11ea-8db8-2bc85c903aad.png)

If I edit Montichiari (a city in Italy), its coordinates are now 0,0 :
![image](https://user-images.githubusercontent.com/65110137/90986527-e2657d80-e583-11ea-8e1a-fe9287a42f6c.png)

I have to manually modify each place again to get it saved.

I don't know what happened

**Comment by fisharebest** [comment]
This is already fixed.

The edit form starts again at 0,0 - instead of the co-ordinates.

So they will only be changed if you

1) click edit
2) do not select a new location
3) click save.
