### ISSUE TITLE
1 Deat Y not displayed correctly

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#3492]
In Gedcom: **1 DEAT Y**

wt-1.7:
![image](https://user-images.githubusercontent.com/5641963/91490179-5076b100-e8b2-11ea-8c35-8cde5ac95fe5.png)

same record in wt-2.0:
![image](https://user-images.githubusercontent.com/5641963/91490427-b9f6bf80-e8b2-11ea-9356-3cbd9017a953.png)

The word "Yes" is missing.

**Comment by fisharebest** [comment]
There was a forum discussion, where it was agreed to remove the "yes".

Many people said that it was not necessary.

Are you asking for the "yes" to return?

**Comment by JustCarmen** [comment]
Yes I do. I don't think visitors understand the meaning of the empty field. And frankly I don't like it either. If we know for sure that a person is death then it should be written down in my opinion.

**Comment by fisharebest** [comment]
Maybe this needs some discussion on the forum?

**Comment by JustCarmen** [comment]
https://www.webtrees.net/index.php/en/forum/2-open-discussion/34919-1-deat-y-output

**Comment by mpwt** [comment]
Is there a difference between 'Yes' and 'yes'?

The capitalized word is not translated. In the translation file there is only the lower case word.

**Comment by mpwt** [comment]
I think that was the original change in FunctionsPrint.php: https://github.com/fisharebest/webtrees/commit/89a24bfeb72ec9bb2e92ff6c90c6f57e06b85606#diff-8e9fb5ddeae40d5e74ace383de69d8e8
