### ISSUE TITLE
500 error after new update

### ISSUE THREAD

**Issue by mrqd9** [fisharebest/webtrees#3494]
`Warning: require(/home/xxxx/domains/xxx/public_html/vendor/composer/../symfony/polyfill-intl-normalizer/bootstrap.php): failed to open stream: No such file or directory in /home/xxxx/domains/xxx/public_html/vendor/composer/autoload_real.php on line 69

Fatal error: require(): Failed opening required '/home/xxxx/domains/xxx/public_html/vendor/composer/../symfony/polyfill-intl-normalizer/bootstrap.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/xxxx/domains/xxx/public_html/vendor/composer/autoload_real.php on line 69`

How to solve this

**Comment by fisharebest** [comment]
My guess is that you did not copy all the files to the server.

**Comment by mrqd9** [comment]
I have updated with Upgrade wizard, don't know which files are missed

**Comment by fisharebest** [comment]
The error message says that a [file](https://github.com/fisharebest/webtrees/blob/master/vendor/symfony/polyfill-intl-normalizer/bootstrap.php) is missing

I can only guess at the reason.  (FTP errors are common).

The solution will be to copy all the files to the server.

**Comment by fisharebest** [comment]
Did you copy the files to the server?
Did it fix the problem?

**Comment by mrqd9** [comment]
> Did you copy the files to the server?
> Did it fix the problem?

Yes. Copied all files with ftp and it's fixed now. 
Why Upgrade wizard missed these files? Is something to be fixed with it?

**Comment by fisharebest** [comment]
> Why Upgrade wizard missed these files?

I don't know.  Perhaps the script on the server did not complete?  (CPU time limit?)

**Comment by fisharebest** [comment]
Closing, as I don't think there is anything we can do to detect/correct this situation.
