### ISSUE TITLE
Missing Carriage Return in ADDR

### ISSUE THREAD

**Issue by ckl67** [fisharebest/webtrees#3495]
From the the GEDCOM 5.5.1 specifications:
CONT line implies that a new line should appear to preserve formatting.

The issue faces in WebTrees 2.0.7 is that :
 CONT does not result in a line break. Instead it does exactly the opposite. Example:
1 ADDR 31 Brigade Drive,
2 CONT Eagleby,
2 CONT Queensland,
2 CONT Australia

Thanks to fix

- https://www.webtrees.net/index.php/en/forum/2-open-discussion/34864-link-input-to-external-website?start=0#80262

**Comment by fisharebest** [comment]
The address is shown on one line to make best use of space.

Most users have lots of horizontal space.
There are frequent complaints that things take too much vertical space.

<img width="755" alt="Screenshot 2020-08-31 at 10 27 04" src="https://user-images.githubusercontent.com/2306088/91705347-b7c38800-eb74-11ea-905a-3fc85d21beb4.png">

Add the following CSS (via the control panel)

```<style> [class$=ADDR] > .field {display:block;white-space:pre-wrap;} </style>```

<img width="774" alt="Screenshot 2020-08-31 at 10 28 13" src="https://user-images.githubusercontent.com/2306088/91705341-b6925b00-eb74-11ea-851d-7a6133944290.png">

**Comment by fisharebest** [comment]
Perhaps the address could expand/collapse - same as sources/notes?

**Comment by ckl67** [comment]
You gave the trick ;-)
--> Perhaps the address could expand/collapse - same as sources/notes?

OK, understood, I can live with that .
Thanks
