### ISSUE TITLE
Save/cancel buttons on edit pages are hidden in Firefox on Android

### ISSUE THREAD

**Issue by SuperMasterPhoenix** [fisharebest/webtrees#3497]
The new version of Firefox on Android (version 79) allows to move the address bar to the bottom of the screen. Unfortunately the address bar then hides the save/cancel button on the edit pages. If I change the address bar to the top, everything looks fine (see pictures below for comparison). Because of that I am not really sure whether this is caused by Webtrees or Firefox itself - on the other hand I've never seen this issue on any other page until now.
Btw: I am using Webtrees 2.0.7

Address bar on bottom | Address bar on top (hidden because of scrolling)
------------ | -------------
![Address bar bottom](https://user-images.githubusercontent.com/20322801/91872528-40771c80-ec78-11ea-8325-db4f6d5ec132.jpg) | ![Address bar top](https://user-images.githubusercontent.com/20322801/91872617-5553b000-ec78-11ea-9f9e-3574a4e8c6c7.jpg)

**Comment by fisharebest** [comment]
When I use Firefox for android, the URL bar disappears when you scroll down to the bottom of the page - and reappears when you scroll up.

See https://dev.webtrees.net/3497.mp4

**Comment by SuperMasterPhoenix** [comment]
You are right, this really seems in issue with Android Mobile, sometimes it works on my phone, sometimes not 🤷‍♂️ 
I will close this issue. Thank you anyway.
