### ISSUE TITLE
Media upload of large files (size >20MB) fails with error (2.0.7)

### ISSUE THREAD

**Issue by t-karcher** [fisharebest/webtrees#3499]
After uploading a couple of files successfully yesterday I suddenly failed to upload a file (tried several times, always failed) and found the error shown below in the logs. I didn't analyze this any further yet. Any idea what might have caused this? Is this a known problem?

<pre>Undefined index: media-note …/app/Http/RequestHandlers/CreateMediaObjectAction.php:70 
#0 …/app/Http/RequestHandlers/CreateMediaObjectAction.php(70): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(8, &#039;Undefined index...&#039;, &#039;/data/web/1/000...&#039;, 70, Array) 
#1 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\CreateMediaObjectAction-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) 
#2 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#3 …/app/Http/Middleware/AuthEditor.php(57): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) 
#4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthEditor-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#5 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) 
#6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware
[...]
#54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#55 …/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) 
#56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) 
#58 …/index.php(57): Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest)) 
#59 {main}</pre>

**Comment by fisharebest** [comment]
Are these large images?

Does it work with small images?

**Comment by t-karcher** [comment]
Yes, and yes: It was a 30MB PDF file. Uploading PDFs up to 12 MB was no problem. Now I remember that I also had problems uploading videos in the past. I solved that by uploading them via FTP and adding them to the media object via administration afterwards. So the problems are caused by the file size?

**Comment by fisharebest** [comment]
I think that the upload is being truncated - probably a server limit.

The result is that input fields that occur towards the end (e.g. media notes) are missing, which causes the error message.

**Comment by t-karcher** [comment]
Looks like you're right: I just checked my server settings, and sure enough, there's a setting "upload_max_filesize" and a setting "post_max_size", both set to 20M. While I could change it on my server and/or just remember to upload all larger files via FTP, I think it would be better to add a warning to the upload dialog specifying this limit, and a proper error message in case the file is larger than this limit.

**Comment by t-karcher** [comment]
Ok, there *is* a warning in the upload dialog right below the file selection field! It's just pretty small and grey, so I never noticed it. 😮 I'd still prefer a better error handling in this case...
