### ISSUE TITLE
Error on a WiFi connection

### ISSUE THREAD

**Issue by mrqd9** [fisharebest/webtrees#3500]
I am unable to access site over a WiFi connection getting error "This site can’t be reached"

Working good with my Mobile Data

Where to allow IPs like this-(2405:204:93a9:9cca:8dba:3ac0:9641:a168)

**Comment by fisharebest** [comment]
This sounds like a problem with your network, not with webtrees.

For general help with setting up servers, it is better to ask on the forum at www.webtrees.net

> Where to allow IPs like this-(2405:204:93a9:9cca:8dba:3ac0:9641:a168)

webtrees allows connections from both IPv4 and IPv6.

There is no blocking or filtering.
