### ISSUE TITLE
Sharing individuals between family trees

### ISSUE THREAD

**Issue by unknownterritory** [fisharebest/webtrees#3502]
I am trying this software for the first time. I am wondering if it would be possible to link two family trees by sharing an individual record between them. I looked for this feature both in the manuals available online and also in the issues of this repository and didn't find this information.

Thanks in advance for any help.

**Comment by Lars1963** [comment]
+1

**Comment by fisharebest** [comment]
This isn't possible.

The system was designed around separate, isolated trees.

Creating links between trees has been tried before, but was too difficult.

* Each tree has different privacy and access settings.
* Lots of caching and optimisation assumes only one tree.
* Multiple links cause problems - you can get cycles of links from tree A to tree B and back again.
* Conflicting information in each tree.

There are no plans to add this.

**Comment by DaPoHou** [comment]
For example, X1 in tree A and X55 in tree B are the same person.
It is possible for an administrator to establish a correspondence between X1 in tree A and X55 in tree B in the control panel.
When a user accesses the X1 individual page in tree A, a button that links to X55 in tree B is highlighted next to X1's name.
Similarly, when a user accesses the X55 individual page in tree B, a button is highlighted next to X55's name that links to X1 in tree A. This may be a better solution.

This may be a better solution.
