### ISSUE TITLE
Editing users - if I edit a user it displays my Username instead of the user's username

### ISSUE THREAD

**Issue by ajswire** [fisharebest/webtrees#3504]
This may have been caused by me changing my own username previously, but now when I Edit _any_ user, the user's Real name and other data is correct, but the Username field displays _my_ username and the Password field displays _my_ password. The system prevents me from saving any user data, until I change the Username field back to the correct one and I erase the Password field.

**Comment by fisharebest** [comment]
Most likely, your browser is auto-filling the form.

The form has the attribute `autocomplete="off"`, but many browsers ignore this when they detect username/password fields.

**Comment by ajswire** [comment]
Thank you, @fisharebest! I agree with your analysis. I tried this in Safari rather than Chrome and that displayed the intended behavior. I just starting using webtrees for the first time over the weekend and it is a very impressive piece of software. Thanks. I will close this comment.
