### ISSUE TITLE
Media error on individual page - 2.0.8-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3507]
Call to a member function mediaFiles() on null …/resources/views/modules/lightbox/tab.phtml:4 in the E GEDCOM of my test systems for individual page of Fanny Jankeloff.

<https://www.amitys.com/test/index.php?route=%2Ftest%2Ftree%2FE.ged%2Findividual%2FX5900%2FFanny-Jankelow>

**Comment by melizaa** [comment]
I updated the E GEDCOM file and removed the Source and Media links.

I do no longer see the error.

**Comment by fisharebest** [comment]
I think this was fixed in 537671560f8b95d92974b107a3ac51b1f3ba7171
