### ISSUE TITLE
Error in individual or family list for NONE or ... surnames - 2.0.8-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3509]
Undefined offset: 0 …/app/GedcomRecord.php:512 for the list of individuals with no surname

<https://www.amitys.com/test/index.php?route=%2Ftest%2Ftree%2FGedcomTest.ged%2Findividual-list&alpha=%2C>

<https://www.amitys.com/test/index.php?route=%2Ftest%2Ftree%2FGedcomTest.ged%2Findividual-list&alpha=%40>

**Comment by fisharebest** [comment]
This seems to be caused by record `I27606` which has a completely empty `NAME` record.

```
0 @I27606@ INDI
1 NAME
1 SEX M
```

So it has a name - and does not have a name - at the same time ;-)

**Comment by melizaa** [comment]
I have a number of individuals whose names are not known.

I am in the middle of updating names on my production site.
Should I remove the empty 1 NAMEs?

**Comment by melizaa** [comment]
I have removed the empty 1 NAME // from my GEDCOM file.
I have left 
1 NAME //
2 _MARNM /Name/

I will soon import the GEDCOM.
Let's see what happens.

**Comment by melizaa** [comment]
There are still errors.

I will try to play with the E file inn test test.

**Comment by hartenthaler** [comment]
As far as I understand the GEDCOM standard, "1 NAME" and "1 NAME //" are both not allowed.
```
NAME_PERSONAL:= {Size=1:120}
[
 <NAME_TEXT> |
/<NAME_TEXT>/ |
 <NAME_TEXT> /<NAME_TEXT>/ |
/<NAME_TEXT>/ <NAME_TEXT> |
 <NAME_TEXT> /<NAME_TEXT>/ <NAME_TEXT>
]
```
<NAME_TEXT> cannot be empty. Reading it exactly, then even "1 NAME Fred //" is not allowed, but I think this is an error in the standard. If you don't know first name and surname you should not use a name record. In my opinion, there is a bug in webtrees: when you delete all name parts in a record, webtrees has still a record "1 NAME //", which is not allowed in my opinion.

**Comment by melizaa** [comment]
I created in E two individuals

X5967
1 NAME //
2 _MARNM /Cohen/

and her mother
X5969

1 NAME //
2 _MARNM //
I do not see the error either for the daughter or for the mother.

I changed the mother to 
1 NAME  //
No error.

I changed the mother to
1 NAME
I get an error even without approving the change.

**Comment by melizaa** [comment]
I removed the 1 NAME and I see an error.

**Comment by melizaa** [comment]
I have 6 individuals who have a given name, but no surname and no surname //.

How am I supposed to fill the name of individuals before surnames were added?

**Comment by melizaa** [comment]
1 NAME Ahven
2 GIVN Ahven

No problem

**Comment by melizaa** [comment]
I imported an updated GEDCOM fiile to the test test system. I do not see the error
