### ISSUE TITLE
Submenu names are cut on rtl pedigree pages - 2.0.8-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3510]
Names are cut in the rtl pedigree chart submenu of the previous arrow of the root person. I see this for the chart and for the block chart.

I see the full names on ltr pages.

![PedigreeHebrew](https://user-images.githubusercontent.com/5202996/93331189-8d3a2600-f828-11ea-913a-0392545b0e6b.jpg)

**Comment by fisharebest** [comment]
Your browser is drawing a solid scrollbar on top of the menu.

I cannot tell from your screenshot, but I guess that all the missing text is under the scrollbar.

My browsers either

1) draw a transparent scrollbar
2) draw a very thin scrollbar

Which browser are you using?  Which operating system?

**Comment by melizaa** [comment]
I use Google Chrome Version 85.0.4183.102 (Official Build) (64-bit) or Version 86.0.4240.42 (Official Build) beta (64-bit) on a Windows 10 machine.
I see the same behavior at least in Microsoft Edge Version 85.0.564.51 (Official build) (64-bit) and in Firefox.

**Comment by melizaa** [comment]
In demo-dev in the Hebrew pedigree the root person's arrow's LTR names are also cut

![image](https://user-images.githubusercontent.com/5202996/97095176-db7ee800-1664-11eb-9b55-6a1b832b2c06.png)

**Comment by fisharebest** [comment]
This has been fixed by the upgrade from Bootstrap 4 to Bootstrap 5.
