### ISSUE TITLE
V icon in report forms - 2.0.8-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3511]
I do not like the huge centered V icon in the report forms.          

See for instance the Individual report.

**Comment by fisharebest** [comment]
I'm not sure what you mean?

Can you add a screenshot?

**Comment by melizaa** [comment]
![image](https://user-images.githubusercontent.com/5202996/93332948-4b5eaf00-f82b-11ea-9d66-076df9b8c225.png)

**Comment by ddrury** [comment]
It's a chrome issue (OK on firefox) and BTW why are they centred
