### ISSUE TITLE
Control panel - Manage media

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3512]
V2.0.8 with commit https://github.com/fisharebest/webtrees/commit/1e9c29b270de6e44b7ea24e3dd37c4b17859fdc5
In the table, No image is shown in the Media column, and clicking on the placeholder results in 404 Not found "The requested URL was not found on this server", However clicking on the title in the Media Object column functions correctly

**Comment by fisharebest** [comment]
You mean this image here?

<img width="1063" alt="Screenshot 2020-09-17 at 09 05 25" src="https://user-images.githubusercontent.com/2306088/93438258-f4a5b380-f8c4-11ea-8bfe-fb92921f64be.png">

> No image is shown

Do you see an image with a broken URL - or no `<img>` at all?

**Comment by ddrury** [comment]
![demo](https://user-images.githubusercontent.com/104515/93438990-e86e2600-f8c5-11ea-88f8-1a3d716d8974.jpg)

BTW didn't there use to be a media-cache folder? All I have now is data/cache/

**Comment by ddrury** [comment]
If I disable pretty URLs it works and the URL on hover is `http://webtrees-2.0.test/index.php?route=%2Fadmin%2Fmedia-file%2Fmedia%252FDFH_Media-20031031-000001.jpg`

**Comment by ddrury** [comment]
.. And BTW, is there any point in having a link here? The resulting page is very basic (and ugly). I presume its purpose is to enable the file to be downloaded but that functionality is available by clicking on the media title in the Media Object column as well.

Having said that, in my LightGallery PR, I display the image in the lightbox

**Comment by ddrury** [comment]
... and with a brand new installation with freshly downloaded code and a new database, it's still not working. As far as I can see this is the only place where the thumbnail is missing

**Comment by fisharebest** [comment]
If you get the "broken image", then perhaps there was an unhandled exception when generating the image?

Look the the browser's dev tools for the response for that image.

Also, what is the URL of the (broken) image.  The URL you see on hover is the URL of the original file - not the thumbnail.

In firefox, rightclick and select "Copy image location" (Not "Copy link location").

**Comment by ddrury** [comment]
Copy image location gives` http://webtrees-2.0.test/admin/media-thumbnail/media%2FDFH_Media-20031031-000001.jpg`

![demo](https://user-images.githubusercontent.com/104515/93499134-897ed000-f90a-11ea-9272-0e1a701f2a80.jpg)

**Comment by HRN65** [comment]
I can confirm this error:
Image location: http://localhost/webtree/admin/media-thumbnail/media%2F001.jpg

**Comment by ddrury** [comment]
Greg,
(caveat - the routing stuff confuses the hell out of me!)

Looking at app\Http\Controllers\Admin\MediaController.php line 180 `$url = route(AdminMediaFileThumbnail::class, ['path' => $path]);` I'm assuming that should end up calling the handle function in app\Http\RequestHandlers\AdminMediaFileThumbnail.php, however it never arrives there. $url ends up with the value shown in the image location above.

**Comment by fisharebest** [comment]
Here is the HTML that I see for the screenshot I posted above.

```
<a href="https://webtrees.test/admin/media-file/media%2Froyals%2F1670_Anne_Sophie.jpg" type="image/jpeg" class="gallery">
  <img src="https://webtrees.test/admin/media-thumbnail/media%2Froyals%2F1670_Anne_Sophie.jpg">
</a>
```

The link target is `admin/media-file/{path_to_file}`
The image target is `admin/media-thumbnail/{path_to_file}`

Can you post the corresponding HTML from your screenshot?

**Comment by ddrury** [comment]
`<a href="http://webtrees-2.0.test/admin/media-file/media%2FDFH_Media-20031031-000001.jpg" type="image/jpeg" class="gallery">
  <img src="http://webtrees-2.0.test/admin/media-thumbnail/media%2FDFH_Media-20031031-000001.jpg">
</a>`

**Comment by fisharebest** [comment]
The URL is correct - `http://webtrees-2.0.test/admin/media-thumbnail/media%2FDFH_Media-20031031-000001.jpg`.

But your 404 seems to come from your webserver, not from webtrees.

What apache configuration are you using to rewrite your URLs?

My guess is that it is detecting the `.jpg` at the end of the path, and is trying to serve this as a file - rather than pass the request to webtrees.

**Comment by ddrury** [comment]
RewriteEngine On
#RewriteCond %{REQUEST_FILENAME} !-d
#RewriteCond %{REQUEST_FILENAME} !-f
#RewriteRule ^(.*)$ index.php [L]

If I make it like the webtrees.net FAQ the RewriteBase /webtrees-2.0/ line give me an internal server error, without it, no image

**Comment by fisharebest** [comment]
I'm pretty sure that the 404 error in your screenshot comes from your webserver, and not from webtrees, and that the request never makes it to webtrees.

The `.htaccess` file *adds* to any existing rules (defined in the apache config), and to any `.htaccess` files in higher-level folders.

**Comment by fisharebest** [comment]
> If I make it like the webtrees.net FAQ the RewriteBase /webtrees-2.0/ line give me an internal server error

The rewrite base is for when you have webtrees installed in a subfolder.  You have installed it in the root-folder of your domain, so it isn't needed (or can be set to `/`).

**Comment by ddrury** [comment]
I'm now at a complete loss, I've installed a brand new server (Xampp instead of Wamp), new code, new database, rewrite as per webtrees.net FAQ and it still fails

**Comment by fisharebest** [comment]
Does it only fail with URL rewriting?

**Comment by ddrury** [comment]
Yes

**Comment by fisharebest** [comment]
Can you edit the routes file, and change two lines.

https://github.com/fisharebest/webtrees/blob/fd30738620ed1bd71f926c9c64253ff30909ca72/app/Http/Routes/WebRoutes.php#L297-L298

Replace `{path}` with `{path}/xxx`

This is just adding some extra characters to the URL, so that it won't end in `.jpg`.

**Comment by ddrury** [comment]
no change

**Comment by ddrury** [comment]
I'm going to be busy today but I was thinking of putting a break point on the last line of index.php and looking at all the variables for both pretty & ugly urls to see what the differences are.

What do you think?

**Comment by fisharebest** [comment]
I'm pretty sure the request isn't reaching PHP.

**Comment by ddrury** [comment]
Adding `AllowEncodedSlashes On` to the apache config fixes it. See http://httpd.apache.org/docs/current/mod/core.html#allowencodedslashes

But I wonder if this is a real solution. Would shared hosting providers allow that?

**Comment by ddrury** [comment]
I checked with my hosting provider and they **wouldn't** be prepared to change this value

**Comment by fisharebest** [comment]
Thanks for investigating this.

The apache documentation is here.

http://httpd.apache.org/docs/current/mod/core.html#allowencodedslashes

When the requested URL contains the string %2F, the request is refused with a 404 (Not found) error.

This would affect any value that is encoded as a URL segment.
e.g. slash characters are valid in XREFs - although I have never seen one in the wild.

> Setting AllowEncodedSlashes to On or NoDecode in the apache config fixes it.

By "apache config", do you mean the `.htaccess` file, or do you mean the system config files in `/etc/apache2/...`

**Comment by ddrury** [comment]
It can't go in htaccess, it must be in either httpd.conf or the vhosts config

**Comment by makitso** [comment]
I have two webtrees installs that have this issue, both Apache.  One is my production (hosted) site and the other my local Dev system.  On the Dev machine I only have the Pretty URLs rewrite in the .htaccess file.

**Comment by makitso** [comment]
It's kind of strange that all other thumbnail links are correct, only the one in Manage media is wrong??

**Comment by fisharebest** [comment]
The "genealogy" thumbnail links use a system of signed URL parameters, to prevent malicious users sending requests for images in thousands of different sizes.

The admin thumbnail has no configuration options, and is only accessible to admins.
