### ISSUE TITLE
1.7.17 - List of individuals not sorted

### ISSUE THREAD

**Issue by jpretired** [fisharebest/webtrees#3514]
List > Individuals
An example - with language set to English, surnames are sorted:

![Výběr_076](https://user-images.githubusercontent.com/350656/93508981-6579b980-f91f-11ea-80d8-b1e9256bf34e.jpg)

The same example - with language set to Czech (Polish, Slovak etc.), surnames in random order:

![Výběr_077](https://user-images.githubusercontent.com/350656/93509198-af629f80-f91f-11ea-857c-2dc52848f64a.jpg)

The same issue is with List > Families.
The random order makes it hard to find a name in the list.

**Comment by fisharebest** [comment]
As far as I can tell, this is working OK in webtrees 2.0

webtrees 1.7 is only getting fixes for major/security issues.
There are no resources available to fix minor issues like this.
Sorry.

**Comment by jpretired** [comment]
Yes, it is a minor issue.
Yes, in 2.0 it is working OK.
