### ISSUE TITLE
Beta - media files have wrong address

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#3517]
Latest beta.  On the Manage media page, all the media links for .jpg files appears to be wrong i.e. have admin/media-file??
https://skatekey.net/admin/media-file/media%2FPeters-Family-picture.jpg

![image](https://user-images.githubusercontent.com/5147603/93669199-33637700-fa47-11ea-8f87-f4c5adcb09af.png)

**Comment by fisharebest** [comment]
> appears to be wrong

The URL looks OK to me.

The route to the original file is defined as: `/admin/media-file/{path}`.
(The route for the thumbnail is similar: `/admin/media-thumbnail/{path}`.

The path of the file is `media/Peters-Family-picture.jpg`.

It gets URL-encoded, giving `media%2FPeters-Family-picture.jpg`.

Substituting the placeholder and adding the base URL gives `https://skatekey.net/admin/media-file/media%2FPeters-Family-picture.jpg`.

**Comment by makitso** [comment]
Then why am I getting this

![image](https://user-images.githubusercontent.com/5147603/93669665-9a365f80-fa4a-11ea-97bc-99dcf225c422.png)

**Comment by fisharebest** [comment]
> Then why am I getting this when I click on the media object?

With the following in your .htaccess, any file that does not exist should get passed to `index.php`.


```
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /webtrees/
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^ index.php [L]
</IfModule>
```

But as I said in #3512, this doesn't appear to be happening for you.
Apache is trying to serve a file that does not exist - and giving a 404.
This 404 response comes from Apache - not from webtrees.

My guess is that there is some other apache config/rules on your server that is taking precedence over your `.htaccess` file.

This is why I suggested modifying the two URLs (e.g. adding `/xxx`).

Perhaps try replacing `{path}` with `{path}xxx`?
Perhaps try replacing `/admin` with `/yyy`?

**Comment by makitso** [comment]
I had rewrite_urls="1" set in my config file.  Removing it fixed the problem.

**Comment by makitso** [comment]
I can not make this problem go away if I configure my site -- skatekey.net -- with pretty URLs

I have this in my .htaccess file
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^ index.php [L]
</IfModule>

I have this in my config.ini.php file:
base_url="https://skatekey.net"
rewrite_urls="1"

**Comment by ddrury** [comment]
Hi Rob,
Don't know if you're following https://github.com/fisharebest/webtrees/issues/3512, but I've found a solution to the problem which entails a change to apache's configuration. Unfortunately my hosting provider isn't prepared to make that change so I guess it's up to Greg to sort it out properly.

**Comment by makitso** [comment]
Looks like issue #3512 is the same issue.

**Comment by makitso** [comment]
Greg,

Can you reopen this issue?

I suspect that the demo site uses Nginx not Apache?  If so, then this issue 
probably only happens on Apache.
Since Apache has about 50% market share and probably is most popular on 
with hosting companies, IMHO, this issue needs attention.

Rob

**Comment by fisharebest** [comment]
> Can you reopen this issue?

#3512 was never closed - I just tagged it to note that I have been unable to reproduce the issue.

**Comment by makitso** [comment]
Like Dan, I can reproduce this issue on two Apache based webtrees installs, 
my production system (hosted) and my Dev machine.
