### ISSUE TITLE
Error in test file - 2.0.8-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3518]
I imported the old E GEDCOM file again to the test test system. The file contains the previously removed not existing media links and the source links and I see errors

Argument 1 passed to Fisharebest\Webtrees\GedcomRecord::Fisharebest\Webtrees\{closure}() must be an instance of Fisharebest\Webtrees\GedcomRecord, null given …/app/GedcomRecord.php:132 for 
<https://www.amitys.com/test/index.php?route=%2Ftest%2Ftree%2FE.ged%2Findividual%2FX5900>
and for his spouse

I see the error also in the future test system's E file

See #3507 and #3508

**Comment by fisharebest** [comment]
This is caused by a link to a non-existing media object in the record of X5900.
