### ISSUE TITLE
Improve Sourcelist Performance by Ignoring Privacy rules for counts

### ISSUE THREAD

**Issue by KosherJava** [fisharebest/webtrees#352]
See the following thread
As Greg stated:
> If we ignore privacy, we can perform the count entirely in SQL, which is very fast, and uses no memory. e.g.

>SELECT l_to, COUNT(i_id) FROM wt_individuals JOIN wt_link ON (l_file = i_file AND l_from = i_id) WHERE i_file = 3 AND l_type='SOUR' GROUP BY l_to 

http://www.webtrees.net/index.php/en/forum/help-for-ver-1-6-2/29762-list-of-sources

**Comment by fisharebest** [comment]
I'm still not entirely sure we should bypass privacy, given that we enforce it assiduously everywhere else.

**Comment by KosherJava** [comment]
Thank you. A great performance improvement (from close to 30 seconds to about 3). My 1,400 sources are a lot, but now the page renders. I am curious why the page still takes 57 queries (56 for the 3 sources at https://dev.webtrees.net/demo-dev/sourcelist.php?ged=demo ), but I see that a simple page like search.php takes over 30 queries (https://dev.webtrees.net/demo-dev/search.php?ged=demo takes "only" 28 queries). It does seem excessive.

**Comment by fisharebest** [comment]
> It does seem excessive.

Look at the number of tables, and think about which ones might be needed on a page...

If you are curious, get a copy of 1.6.2, and edit session.php to change `DEBUG_SQL` to `true`.
