### ISSUE TITLE
Using ampersand in a story title

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#3520]
When using an ampersand (&) in a story title it outputs as `&amp;`
The output is correct in a story text.

See: https://wijzijnfamilie.nl/tree/wijzijnfamilie/individual/I2749/Johann-Christoph-Honig#tab-stories

The title is wrong but note the first sentence in the last paragraph where the '&' outputs correctly.
The story is in Dutch but I think you will understand the issue.

**Comment by fisharebest** [comment]
This bug has caused `&amp;` to be stored in the database, instead of `&`.

After you update the code, you will need to edit the story title.

**Comment by JustCarmen** [comment]
> After you update the code, you will need to edit the story title.

Thanks. Done that. It works correct now.
