### ISSUE TITLE
Uncaught Type Error

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#3524]
I receive the following error on every individual that I have looked at

> Uncaught TypeError: t is null
     persistentToggle   https://behunt.net/ft/public/js/webtrees.min.js?v=2.0.7:1
    <anonymous>       https://behunt.net/ft/tree/hunt.ged/individual/I1222/Samuel-Fowler#tab-tree:4068

The code appears to be:
`webtrees.persistentToggle('show-historical-facts');`

I do not have any "historical facts" set up on my tree.

This does not seem to be causing any issues, simply a finding.

Ver: 2.0.7
PHP: 7.4.10
MySQL: 5.7.23-23

**Comment by fisharebest** [comment]
Thanks for reporting this.  It was already fixed in #3441
