### ISSUE TITLE
Security issue. Private data is visible when not logged in (latest dev)

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#3526]
I noticed today that when I am not logged in on my testsite I see private data of living people.

I removed all cache and session cookies and disabled all custom modules, but that doesn't make any difference. I even tried another browser with the same result.

**Comment by fisharebest** [comment]
Can you email me the details of your test site?
If possible, include an admin account so I can look at the privacy settings.

**Comment by JustCarmen** [comment]
Sorry to bother you. Problem solved. Something wrong with my own privacy settings. Don't know exactly when it has been changed but the age above which a person is considered dead was set to '1'....

**Comment by fisharebest** [comment]
No problem at all - glad you found the problem.
