### ISSUE TITLE
ReflectionException (latest dev)

### ISSUE THREAD

**Issue by jpretired** [fisharebest/webtrees#3527]
Today Sep 26 I downloaded and installed the latest dev (webtrees-master.zip).
Here is the error dump:
[20200926-wtdev-error.txt](https://github.com/fisharebest/webtrees/files/5286525/20200926-wtdev-error.txt)

**Comment by fisharebest** [comment]
Thanks.  I have already written a fix for this, but have not yet uploaded it to github.

I'll do it later today.

(Temporarily, you can disable the vesta modules which will make the problem disappear).

**Comment by fisharebest** [comment]
Done.

**Comment by jpretired** [comment]
Solved, thank you.
