### ISSUE TITLE
Filters not working in ancestors / individuals lists

### ISSUE THREAD

**Issue by toweosp** [fisharebest/webtrees#3528]
Webtrees: 2.0.7
Firefox: 80.0.1

In the ancestors as well as the individuals list the filters at the top of the table/list (sex, alive, dead..., roots, leaves) are not working. If the filters are selected they are highlighted but nothing happens to the data.

In contrast the buttons "show parents" and "show statistics charts" below the lists/tables are working correctly.

**Comment by fisharebest** [comment]
This has already been reported and fixed.

You can see it working at https://dev.webtrees.net/demo-dev/tree/demo
