### ISSUE TITLE
Version 2.0.8 missing webtrees-2.0.8.zip

### ISSUE THREAD

**Issue by NathanVaughn** [fisharebest/webtrees#3533]
On the [version 2.0.8 release](https://github.com/fisharebest/webtrees/releases/tag/2.0.8), there is no `webtrees-2.0.8.zip` file included, like usual. The Docker image I make for webtrees [uses this file](https://github.com/NathanVaughn/webtrees-docker/blob/b94e320b04ec2a14f2f432ac48aa8b1e75013d27/Dockerfile#L11) as it includes extra translations not present in the base source code zip files. I see that someone else [on the forums](https://www.webtrees.net/index.php/en/forum/help-for-2-0/35013-missing-messages-php-after-update-to-2-0-8) has also noticed this.

**Comment by fisharebest** [comment]
See the forum.  The release was pulled due to a bug.

**Comment by NathanVaughn** [comment]
Ah, didn't see that. Thanks!
