### ISSUE TITLE
weblate certificate issue

### ISSUE THREAD

**Issue by ro-la** [fisharebest/webtrees#3534]
When attempting to go to https://weblate.iet.open.ac.uk/ I receive a message saying that the certificate is invalid NET::ERR_CERT_DATE_INVALID

Ladislav

**Comment by fisharebest** [comment]
Thanks.  The certificate had been updated automatically, but the webserver had not been restarted.  It is working now.

PS - this server has several URLs.  You should use https://translate.webtrees.net/
