### ISSUE TITLE
Erroneously getting "This user account does not have access to any tree."

### ISSUE THREAD

**Issue by zblesk** [fisharebest/webtrees#3535]
I'm new to Webtrees and running it in docker. I've created and edited a tree, everything seems to work well. 
Then I went to add a new user and added it to the existing tree. 

![image](https://user-images.githubusercontent.com/4245227/95323211-17146680-089e-11eb-863b-5af5a9c6bd5e.png)

However, if I select any Role different from "Manager", the user doesn't see the tree. 
When he logs in, he only gets the "This user account does not have access to any tree." message. When I change the role to Manager, the tree shows up normally; if I select anything else, he loses access again. It doesn't seem to depend on any of the other fields in the row, either.

I've tried looking for additional security access options and searching for answers, but haven't found anything. What am I doing wrong?

Thank you.

**Comment by zblesk** [comment]
![image](https://user-images.githubusercontent.com/4245227/95334626-a88bd480-08ae-11eb-85ef-5a6e11e85208.png)

**Comment by fisharebest** [comment]
Next, can you run

`select count(*) from wt_gedcom_chunk where imported=0;`

**Comment by zblesk** [comment]
here 

![image](https://user-images.githubusercontent.com/4245227/95335606-e76e5a00-08af-11eb-887f-170201d8ae11.png)

**Comment by fisharebest** [comment]
OK - something has gone wrong when you imported the GEDCOM file (or created a new/empty tree).

It seems that all the data was imported (because there is no data to import in `wt_gedcom_chunk`.
But the status of the tree is still "no imported".

Perhaps an error in the final part of the GEDCOM file?
Perhaps there was a system/database error at this time?

I do not know how the database image is created in docker.  Perhaps it was incomplete?

Since the tree is "not imported', it is only visible to managers and administrators (who can complete the import).

So, it is temporarily unavailable to members/editors/moderators.

> I've created and edited a tree,

If you imported you data from a GEDCOM file, then import it again.

If you started with an empty tree in webtrees, then use the export option (to create a GEDCOM file), and import that.

**Comment by zblesk** [comment]
Yes, I imported a file (exported from MyHeritage). It did display some error, but all the entries seemed to work OK so I disregarded that message. 

It's not a docker problem, I think: it just bundles up the app. Webtrees still normally asks for a DB connection and does all the initialization itself. And the app just otherwise worked normally, as well. 

Since I've added modifications and media after the upload, and the interface says importing anew would just drop my existing data, I can't re-upload the same file. I tried exporting from Webtrees and importing that, whilst checking the option to keep media. (I'd literally just exported and then re-imported, so it could have worked, I figured.) 

That deleted all of my existing data, and then the import failed with this error: 

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-X3' for key 'PRIMARY' (SQL: insert into `wt_media` (`m_id`, `m_file`, `m_gedcom`) values (X3, 1, 0 @X3@ OBJE 1 FILE D:/OneDrive/Db/MyHeritage Family Tree_Photos/P3_2448_3264.jpeg 2 FORM jpeg 2 TITL priska 1 _PHOTO_RIN MH:P3 1 _FILESIZE 2073955))
```

And it imported nothing. 

Next I did a few minutes of panicking, then shut down Webrtrees to restore from the database dump I'd taken just before the attempted fix. 
That also threw some SQL errors, but after trying twice, they seem to be mostly resolved. When I turned webtrees back on, it seems I'm where I was at the beginning. Hopefully. Here's to hoping nothing's broken in a more subtle, invisible way. 

So, if the issue is the tree being marked as 'not imported', is there a way to manually override/overwrite that? 

And thank you for your help!

**Comment by fisharebest** [comment]
> Yes, I imported a file (exported from MyHeritage). It did display some error, but all the entries seemed to work OK so I disregarded that message.

If there was an error, then the import will be incomplete.  Hence your original error.

> whilst checking the option to keep media

Do not use this option.  It will merge your existing media objects with the imported data.
It assumes your imported data does not contain media.
If it does contain media, you will get the SQL error that you see.

> So, if the issue is the tree being marked as 'not imported', is there a way to manually override/overwrite that?

You could overwrite the entry in `wt_site_setting`.  But I would not recommend it.  If there was an error during import, then there is likely to be missing data.

**Comment by zblesk** [comment]
Regarding the media import: 

I did it like this: 

![image](https://user-images.githubusercontent.com/4245227/95433249-f9073e80-094f-11eb-8a0d-0d8399209b22.png)

I.e. I didn't check the Media (or anything else), and just downloaded a GED file. 
Then tried to import it back. 
What _should_ I have done to omit all media references? 

>  If there was an error during import, then there is likely to be missing data.
I don't really care that much, really. By the numbers, I see the number of people at least is correct. And I have neither any idea how to fix a ged file exported by MyHeritage, nor time to learn how.  
Good to know there might be missing data, so I can check them manually. I suspect that might still be faster than trying to fix the file. :D

**Comment by fisharebest** [comment]
> I.e. I didn't check the Media (or anything else), and just downloaded a GED file.

It is an option on the IMPORT.
It is a checkbox.  Make sure it is not checked.

There are desktop programs that do not support media.

If you use one of these programs to edit your data, and you also use webtrees to display your data, and you also add media in webtrees, then you can use this option.

> I suspect that might still be faster than trying to fix the file. :D

Maybe not.  What was the error?

**Comment by zblesk** [comment]
Oh! That worked. (And it didn't delete my media, which I thought it would do.) 
Now everything works and the issue is resolved, thanks! 

(Going forward I only want to use webtrees. Glad to ditch MyHeritage.)
