### ISSUE TITLE
v2.0.8 Place Hierarchy map problem

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3536]
If when drilling down a place hierarchy, a child place has the co-ordinates (0,0) then the map rather that displaying the place reverts to the global view.

Example, I have the hierarchy England, Wiltshire, Fovant (Fovant has co-ords 0,0 - don't know how that happened - maybe an import problem?) Click England gives map of England, Click Wiltshire, map reverts to world view. Add proper co-ordinates for Fovant and all is OK

**Comment by ddrury** [comment]
Co-ords 0,0 solved. Webtrees 1.7 sees E0, N0 as valid and exports it as such.

**Comment by ric2016** [comment]
E0, N0 **are** valid coordinates. [There is actually something at that location ;-) ](https://www.ndbc.noaa.gov/station_page.php?station=13010)

I think it is not optimal to use these valid coordinates as a marker to indicate 'coordinates unknown', null would be more appropriate.

**Comment by ddrury** [comment]
Agreed

**Comment by ddrury** [comment]
The problem is in Placelocation::boundingRectangle() line 249. If any child place has co-ords [0,0] then they are returned as the min values. I can see a couple of ways to fix it.

- Amend the filter when getting latitudes & longitudes to remove 'E0', 'W0' etc.
- Filter the results before line 249

Either of these options could potentially unbalance the lat/long arrays (ie if you have a place with co-ords something like [0, 1] . I don't think this would be a problem but leave it up to you to resolve

**Comment by ddrury** [comment]
See new issue https://github.com/fisharebest/webtrees/issues/3638
