### ISSUE TITLE
pdf report i18n

### ISSUE THREAD

**Issue by jzfan** [fisharebest/webtrees#3544]
1. PDF report 中文 乱码
![图片](https://user-images.githubusercontent.com/13995797/95807862-c7221d80-0d3d-11eb-839a-8fe0bb69ae20.png)

2. How to change the pdf report styles ?

**Comment by fisharebest** [comment]
> PDF report 中文 乱码

This is a known problem.  See #1479

> How to change the pdf report styles ?

The styles and fonts are defined in the .XML files - `/resources/xml/reports/*.xml`
