### ISSUE TITLE
Fix: #2494 show block ID on 'customise this page' doesn't work in V2.0.9

### ISSUE THREAD

**Issue by ungeahnt** [fisharebest/webtrees#3545]
> Please make this block-Id in any manner visible

The block ID is shown if you hover your mouse over the block.

<img width="230" alt="Screen Shot 2019-08-16 at 20 10 00" src="https://user-images.githubusercontent.com/2306088/63192102-27e29700-c062-11e9-80df-fe81419b0347.png">

see also #2494

_Originally posted by @fisharebest in https://github.com/fisharebest/webtrees/issue_comments/522120605_

**Comment by fisharebest** [comment]
Remind me why the block-id is required?

**Comment by ungeahnt** [comment]
No problem, we all becomes older ;)

https://www.webtrees.net/index.php/en/forum/9-request-for-new-feature/33421-customize-page-html-blocks-with-id-or-similar

**Comment by ungeahnt** [comment]
In V2.0.10 the block-id is visible (e.g. 'Change the “My page” blocks').  Problem is solved.

It seems that nothing has been changed in the code. So I must have made a mistake.
