### ISSUE TITLE
Empty emails being sent

### ISSUE THREAD

**Issue by mpaluchowski** [fisharebest/webtrees#3548]
My 2.0.9 installation is sending out truncated, essentially empty emails. I've set the mechanism to `sendmail` and just tried to request a password reset. This is the _whole_ email that was sent:

```
X-uid: nethut
mta96: /home/nethut/public_html/genealogy.nethut.pl/./
```

These headers are probably getting added by sendmail, and there's nothing contributed by Webtrees. For comparison, Wordpress emails work fine.

This might be related to #3547

**Comment by fisharebest** [comment]
Do you know what parameters are required by sendmail on your server?

webtrees uses `/usr/sbin/sendmail -bs` by default.

You can change this by adding a line to config.ini.php

`sendmail_command="/usr/sbin/sendmail -x -y -z ..."`

**Comment by mpaluchowski** [comment]
Hmm, I'm not sure how to test that.

I created a file named `msg.txt` with the contents (and _actual_ email addresses):

```
From: <from email>
To: <my email>
Subject: Testing sendmail
This is a sendmail test.
```

And I ran `/usr/sbin/sendmail sendmail -bs < msg.txt` which worked fine. The email was sent and delivered.

**Comment by mpaluchowski** [comment]
OK, I think that was that after all. I changed the config to:

```
sendmail_command="/usr/sbin/sendmail -t"
```

I see you're using SwiftMailer, which says the only other supported mode is `-t`. Now the emails send fine.

Is there a way to handle this better? Ie. display an error and suggest changing the configuration string? With the default `-bs` mode using any mail-sending feature was causing an endless page load and only because of server logging did I find that any emails were being sent.

**Comment by fisharebest** [comment]
> Is there a way to handle this better?

I don't know.

I have very little experience with sendmail.  I just followed the documentation.

**Comment by fisharebest** [comment]
FYI, this is already mentioned in the FAQ - http://webtrees.net/faq/email/

**Comment by mpaluchowski** [comment]
> FYI, this is already mentioned in the FAQ - http://webtrees.net/faq/email/

Yes, but the instruction is not very precise. [SwiftMailer's code](https://github.com/fisharebest/webtrees/blob/8b04670a78742b3f7e8852b5533a6c5e1d47dd73/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/SendmailTransport.php) says, that the _only_ supported commands are:

```
sendmail -bs
sendmail -t
```

so the FAQ could say something like "if the default `sendmail -bs` doesn't work on your system, try `sendmail -t` or switch to SMTP".

**Comment by fisharebest** [comment]
The FAQ has been updated.
