### ISSUE TITLE
Display Notes attached to a Name element

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#3549]
*Enhancement Request*

When "Automatically expand notes" is set to "yes" it would be consistent to display any notes which are attached to the "Name" element similar to how Notes are expanded for facts/events.   As an example 

`1 NAME Hannah /Perrine/`
`2 GIVN Hannah`
`2 SURN Perrine`
`2 NOTE Person 640 in "Daniel Perrin <<The Huguenot>>..."`
`3 CONT Person 3931 in "The Van Voorhees Family in America"`

[https://behunt.net/ft/tree/hunt/individual/I1572/Hannah-Perrine](url)

**Comment by fisharebest** [comment]
In the latest 2.1 code, the INDI:NAME:NOTE is displayed the same as INDI:XXXX:NOTE.

Both will obey the "automatically expand notes" option.
