### ISSUE TITLE
Display Married Name + "AKA Names" Always

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#3550]
*Enhancement Request*

When an individual has a Nickname, Married Name or AKA name, it would be helpful if those were displayed *always* when the individual is shown.
![Capture](https://user-images.githubusercontent.com/13973937/96059055-e95d8d80-0e5a-11eb-9bcb-19259b716201.JPG)

There is currently no indication that any of these elements **might** exist for an individual, so an editor or casual viewer would not know to expand the field, yet these other names may be of high importance to a viewer.

**Comment by vytux-com** [comment]
You should be converting all of those to the correct standards by adding these additional names with the correct type rather than hiding them as a sub tag of another name

**Comment by eric215** [comment]
Agreed, closing this out.

Vy_tux -->   You are very active in webtrees development and know the capabilities quite well.  As a user, I was not aware that capability had been added to perform this mass edit. Yes, I know there has been discussion for some times about the use of custom tags, but I often have only a little time to stay current with what is happening here, and I generally trust webtrees to create the right tags so I rarely spend much attention on some of the GEDcom discussions..
