### ISSUE TITLE
The edit boxes print to the left outside the RTL pages - 2.0.10-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3552]
The individual, family, source, shared note, media edit boxes print to the left outside the RTL pages.

On the LTR pages we see, as expected
![image](https://user-images.githubusercontent.com/5202996/96259949-fd260280-0fc6-11eb-81c9-f5f45ab2f64c.png)

On the RTL pages we see
![image](https://user-images.githubusercontent.com/5202996/96259853-da93e980-0fc6-11eb-8277-461653d80289.png)

The RTL page should be a mirror image to the LTR page.

**Comment by fisharebest** [comment]
This has been fixed by the upgrade from Bootstrap 4 to Bootstrap 5.
