### ISSUE TITLE
The page header in FAB does not print across the page width - 2.0.10-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3558]
The headers in all the other themes print across the page.

The issue was highlighted after I added to my future test system Makitso's custom.css and JustCarmen's FancyImagebar.

FAB
![image](https://user-images.githubusercontent.com/5202996/96369074-7f95fa00-1160-11eb-95af-c4c2aa87c5bf.png)

Other themes
![image](https://user-images.githubusercontent.com/5202996/96369113-bc61f100-1160-11eb-8abb-61052ab392fa.png)

![image](https://user-images.githubusercontent.com/5202996/96369145-fb904200-1160-11eb-8c8e-b25921786a25.png)

With custom.css and FancyImagebar

FAB
![image](https://user-images.githubusercontent.com/5202996/96369236-6fcae580-1161-11eb-9c5a-3776b8356885.png)

Other themes
![image](https://user-images.githubusercontent.com/5202996/96369279-a1dc4780-1161-11eb-8155-5eeb23f3e786.png)

![image](https://user-images.githubusercontent.com/5202996/96369333-f384d200-1161-11eb-8cfd-150b73889d46.png)

**Comment by fisharebest** [comment]
This design was intentional. The themes are supposed to be different.
