### ISSUE TITLE
Reports Family format PDF view error

### ISSUE THREAD

**Issue by jpretired** [fisharebest/webtrees#3562]
wt 2.0.9
There is an issue, not with every family:
`Trying to access array offset on value of type float …/app/Report/ReportPdfTextBox.php:181
#0 …/app/Report/ReportPdfTextBox.php(181): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 …/app/Report/PdfRenderer.php(123): Fisharebest\Webtrees\Report\ReportPdfTextBox->render()
#2 …/app/Report/PdfRenderer.php(519): Fisharebest\Webtrees\Report\PdfRenderer->body()
#3 …/app/Report/ReportParserGenerate.php(429): Fisharebest\Webtrees\Report\PdfRenderer->run()
#4 …/app/Report/ReportParserGenerate.php(266): Fisharebest\Webtrees\Report\ReportParserGenerate->docEndHandler()
#5 …/app/Report/ReportParserBase.php(74): Fisharebest\Webtrees\Report\ReportParserGenerate->endElement()
`
Full error listing:
[20201019-report-family-error.txt](https://github.com/fisharebest/webtrees/files/5403143/20201019-report-family-error.txt)

Family GEDCOM:
[Edit the raw GEDCOM - Rajmund Špunda + Anežka Nevrlá – webtrees.pdf](https://github.com/fisharebest/webtrees/files/5403147/Edit.the.raw.GEDCOM.-.Rajmund.Spunda.%2B.Anezka.Nevrla.webtrees.pdf)

**Comment by fisharebest** [comment]
This bug was fixed recently.
