### ISSUE TITLE
User defined welcome text does not work.

### ISSUE THREAD

**Issue by BertKoor** [fisharebest/webtrees#3569]
This bug was reported in the forum: https://www.webtrees.net/index.php/en/forum/help-for-2-0/35066-sign-in-options

Control Panel - Sign-in and Registration - select No text or User defined welcome text and type it in the box. 
Save and log out, then go to login page. It will show the predefined text which states all visitors can request an account. So the selection of welcome text does not work for these two options.

**Comment by hartenthaler** [comment]
For me the user defined text is working. But the option 1 (no predefined text) and option 2 (... all users can ...) are resulting in the same welcome text. The option text 3 (... admin will decide ...) does not fit with the resulting welcome text.

**Comment by fisharebest** [comment]
It works for  me:

<img width="716" alt="Screenshot 2020-10-24 at 19 44 07" src="https://user-images.githubusercontent.com/2306088/97091126-59290080-1631-11eb-8498-740a230a3e8e.png">
<img width="712" alt="Screenshot 2020-10-24 at 19 44 25" src="https://user-images.githubusercontent.com/2306088/97091127-5c23f100-1631-11eb-83ad-6df630e45dab.png">

NOTE: this option is dependent on the language.
If you site runs in several languages, you must change language and select new text for each one.

**Comment by McBilll** [comment]
Interesting that it works for some and not others. I've reduced languages to just one and still the user defined text doesn't work.

**Comment by fisharebest** [comment]
I can't reproduce this, and cannot find anything obvious in the code that might cause it.

If you can reproduce it, create a new issue with as much information as you have.
