### ISSUE TITLE
Trying to access array offset on value of type null in plugins/elementor/includes/base/controls-stack.php on line 1430

### ISSUE THREAD

**Issue by nkoerner93** [fisharebest/webtrees#3570]
Hey, with PHP 7.4 we're currently running into the stated issue.

The website in question is one of our staging websites: http://www.xseed.works.osaka.iway.ch/

You can see the issue on the frontpage in the first section after the slider.

Anyone knows how to ressolve this issue until it gets fixed?

**Comment by fisharebest** [comment]
Have you posted this issue to the correct repository?

webtrees does not contain any files called `controls-stack.php`.

**Comment by nkoerner93** [comment]
Hey Fisharebest,

I'm sorry, this was supposed to be listed in the elementor repository :).

I'll edit the issue.

Best Regards

**Comment by nkoerner93** [comment]
Wrong repository, was supposed to be listed in the Elementor Repo.

Resolved.
