### ISSUE TITLE
Autocomplete with special characters

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#3577]
If a slash is used in autocomplete inputs, it is used unescaped as part of the request url, leading to an unintended redirect (see also https://github.com/fisharebest/webtrees/issues/3561#issuecomment-719919842).

This is an issue at least for media, where a slash may be used in the input to indicate a sub-folder hierarchy, and for places, where the placename may actually contain slashes.

In the case of media, searching for "foo/bar" leads to a request url ending in "/autocomplete/folder/foo/bar", which returnes a 302 response. Using '%2F' instead leads to a 404 response (url ends with "/autocomplete/folder/foo%2Fbar").

Should the router handle these cases differently, or do we have to escape slashes (and maybe other characters as well) differently? Sub-folder autocompletion may have to be handled separately in AutoCompleteFolder.php in any case.

**Comment by ric2016** [comment]
There are actually three aspects, only the first of which turns out to be an actual webtrees issue:

1. When entering an autocomplete input in the client, this input must be url encoded, in particular in order to handle slashes properly.

2. An url with encoded slashes must be accepted by the server. I had to add `AllowEncodedSlashes NoDecode` to my Apache configuration to achieve this. Otherwise, 404 was returned directly by the web server (didn't even reach webtrees).

3. On the server side, the request handler has to interpret the respective query properly. This turns out to be already the case in AutoCompleteFolder.php: A pretty url ending with 'autocomplete/folder/foo%2Fbar' is handled as expected (bar is treated as a sub-folder).

So apparently just 1. has to be fixed in webtrees, but I'm not sure how. I would have expected `webtrees.autocomplete` in webtrees.js to uri encode the query string, but that is apparently not the case. If you manually enter 'foo%2Fbar' in the search field, e.g. for the folder part of 'Filename on server' in the 'Create a media object' dialog, this works (bar is treated as a sub-folder) - but isn't very user-friendly.

**Comment by FrankWarius** [comment]
I did a little resaerch on Places. I using IIS on Windows 2019 Server, mariaDB, WT 2.10, PHP 7.4
Güstrow is a city in Mecklenburg, If you enter in place edit dialog
"g" you get a response of 10 places, mb_detect_encoding returns ASCII
"gü" you get no response, mb_detect_encoding returns ""

I fixed it (on IIS) with adding a line in AutoCompletePlaces.php after
   $query = $request->getAttribute('query');
   **$query = utf8_encode($query);**

I cann't test this on Apache

**Comment by FrankWarius** [comment]
We see different behavior base on option rewrite_urls. If rewrite_urls=“0“ and “URL rewrite“ is off then $query contains already an UTF-8 string. In this the case utf8_encod() result is corrupt.
If rewrite_urls=“1“ and “URL rewrite” is on $query contains an ASCII string and utf8_encode() works right.

This code works in both cases (on Windows Server 2019 and IIS)

$debugMsg1=$query . " " . bin2hex($query) . " " . mb_detect_encoding($query);
if (mb_detect_encoding($query) !== 'UTF-8') {$query = utf8_encode($query);}
$debugMsg2=$query . " " . bin2hex($query) . " " . mb_detect_encoding($query);

**Comment by ric2016** [comment]
@FrankWarius I cannot reproduce this with Apache and php 7.3.
mb_detect_encoding() returns 'UTF-8' with or without pretty urls enabled, for a query with an umlaut, and there are place result in either case without your adjustments.

**Comment by fisharebest** [comment]
A google search reveals many issues with IIS/fastcgi not recognising UTF8 characters in URLs.

https://support.microsoft.com/en-gb/help/2277918/fix-a-php-application-that-depends-on-the-request-uri-server-variable
