### ISSUE TITLE
Sporadic Errors: Undefined index: xref …/app/Http/RequestHandlers/MediaFileThumbnail.php

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3578]
I found in my log file sporadic error entries (all from 17.58.99.197):
`Undefined index: xref …/app/Http/RequestHandlers/MediaFileThumbnail.php:54 #0 …/app/Http/RequestHandlers/MediaFileThumbnail.php(54): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(8, &#039;Undefined index...&#039;, &#039;/mnt/web312/a3/...&#039;, 54, Array) #1 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\MediaFileThumbnail-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #2 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) <b>#3 …/modules_v4/vesta_classic_look_and_feel/ClassicLAFModule.php(151): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))</b> #4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ClassicLAF\ClassicLAFModule-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) <b>#5 …/modules_v4/faces/src/Modules/FacesModule.php(93): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))</b> #6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) <b>#7 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(212): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))</b> #8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #9 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #11 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #13 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #14 …/app/Http/Middleware/Router.php(166): Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest)) #15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):``
...`

**Comment by fisharebest** [comment]
My guess is that these are caused by a search-engine or robot that is making a bad request.

Can you find the webserver (e.g. apache) logs for this request?
TIP - look at the timestamp of the error message and the timestamp in the logs.

**Comment by hartenthaler** [comment]
There are some errors in my webserver logfile, but none of them is related to the relevant timestamps. Maybe this error is not so important, so you can close it. when I will find much more of these entries in the future, I can open it again.
