### ISSUE TITLE
Support for Google Analytics gtag

### ISSUE THREAD

**Issue by terrymgray** [fisharebest/webtrees#3580]
Google updated their analytics script to include a new reporting snippet, referred to as [gtag.js](https://developers.google.com/analytics/devguides/collection/gtagjs) . The script is similar to the existing Universal Analytics script but includes additional data collection capabilities, including improved data collection across devices (e.g. user engagement across mobile + desktop).

While it is possible to manually add the GA script via the custom javascript module, this option does not allow custom dimensions to be dynamically inserted in to the code (e.g. `ga("send", "pageview", {"dimension1":"FamilyName","dimension2":0});` ).

Format of the gtag.js (GA4) code snippet:
`<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-34567890-1');
</script>`

The new GA code snippet is a straight slot-in replacement for the old Universal Analytics code snippet. However, as Google have introduced a new Analytics layout for use with gtag.js some users may prefer not to upgrade to the new view, and instead stick with Universal Analytics. 

A code enhancement for the webtrees Google Analytics module is required. One option is to include a new standalone module (you can run both gtag.js and Universal Analytics alongside each other - both will collect data). However, a preferred option would be to update the webtrees Google Analytics module to include a checkbox to the effect '_Do you wish to use the new Google Analytics gtag.js code?_'  If the checkbox is selected, the gtag.js code would be generated. Otherwise, the existing Univeral Analytics code would be generated in the HTML header.

The current code snippet generates custom dimensions. Details on creating [custom dimensions with gtag.js](https://developers.google.com/analytics/devguides/collection/gtagjs/custom-dims-mets) are described here. Universal Analytics will be phased out eventually as Google only displays the gtag.js tracking code, so webtrees needs to be able to give users the option to update their tracking code snippet.

**Comment by fisharebest** [comment]
> However, a preferred option would be to update the webtrees Google Analytics module to include a checkbox to the effect 'Do you wish to use the new Google Analytics gtag.js code?'

If the new script is fully backwards compatible, then I don't understand why we would need this option?

**Comment by terrymgray** [comment]
> If the new script is fully backwards compatible, then I don't understand why we would need this option?

More to meet user expectations, than for any technical reason as the new script is backwards compatible. Some users unfamiliar with the new script may ask why the analytics snippet has changed.

**Comment by fisharebest** [comment]
@terrymgray - are you able to provide a snippet/template which includes the custom dimensions?

(I don't currently have access to a google-analytics account, so am unable to test).

**Comment by terrymgray** [comment]
@fisharebest the custom dimension takes the following format:

`gtag('event', 'page_view', { 'dimension1': familyName });`
where familyName is the name of the Family Tree (eg. 'Roach')

As GA 4 allows you to add custom parameters it would be more descriptive to replace the current 'dimension1' key with  'FamilyTree' or 'FamilyName'.  I don't recall what 'dimension2' represents but same comments apply so the format would be 

`gtag('event', 'page_view', { 'dimension1': familyName, 'dimension2': value });`

I'll email a custom snippet.
