### ISSUE TITLE
Place missing from Place Hierarchy

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#3581]
Ver 2.0.10

This individual was last edited in June 2014; he has 2 BIRT records.

The 1st location (Alabama, United States) is only partially appearing in Lists --> Place Hierarchy.

- For Alabama there is an entry for the place, but 0 individuals + 0 Families

- In Illinois there IS an entry with both BIRT locations.

Showing both BIRT locations is OK, but not including him in the Alabama listing is an issue.

It IS showing up in the Geographic Data page

[https://behunt.net/ft/tree/hunt/individual/I1492/Levi-Bird-Willett](url)
`1 BIRT
2 PLAC Alabama, United States
2 SOUR @S155@
.......

1 BIRT
2 DATE JAN 1864
2 PLAC Illinois, United States
2 SOUR @S8@
`
**Alabama Entry**
![Capture](https://user-images.githubusercontent.com/13973937/97921111-7b550980-1d28-11eb-817c-494483625ea3.JPG)

**Illinois entry**
![Capture](https://user-images.githubusercontent.com/13973937/97921754-6af15e80-1d29-11eb-889e-ad5a11f9d210.JPG)

**Geographic Data page**
![Capture](https://user-images.githubusercontent.com/13973937/97921844-88bec380-1d29-11eb-8ec3-5b2803bfa469.JPG)

**Comment by fisharebest** [comment]
I can't reproduce this.  If I create an individual with two birthplaces, then they appear twice in the place-hierarchy, as expected.

If you edit this individual and accept the changes, it will re-create the links between places and individuals.

Does this make a difference on your site?

**Comment by eric215** [comment]
Removing the PLAC, saving, then re-adding worked.  I had waited to touch it in case you wanted to see underlying data..  It concerned me that the link was broken since this individual had not been changed in several years.

Is there any way for me to validate all of the links rather than poking around one-at-a-time?

I have also tried to duplicate this with a different individual and everything worked as expected.

**Comment by fisharebest** [comment]
The links between individuals and places are updated whenever you edit or import data.

If the link was missing, it could have been caused by an earlier bug.

> Is there any way for me to validate all of the links rather than poking around one-at-a-time?

You can force webtrees to re-create all the links by exporting to a GEDCOM file, and then re-importing it.
