### ISSUE TITLE
Thumbnail Cleanup

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3582]
Since updating from the 1.x branch, I've noticed my server has collected thousands of new thumbnail files, and I suspect many of them are not necessary.

data/media/thumbs has 1,353 files and none have been modified in the past 6 months.
data/thumbnail-cache/media has 1,794 subdirs each containing between 3 and 7 files. (6,077 files total)
data/thumbnail-cache/62[...]f0 has 1,223 subdirs, all empty.  Some of these were created in the past week or two.

Should I manually delete any of this?

Should webtrees offer a tool for this?

**Comment by fisharebest** [comment]
`thumbnail-cache` was used internally by our old thumbnail library (https://glide.thephpleague.com)

webtrees has some housekeeping code to delete these files after 90 days.  See https://github.com/fisharebest/webtrees/blob/2.0.10/app/Http/Middleware/DoHousekeeping.php#L95

`data/media/thumbs` can was originally for internal use only, but several users discovered that they could create custom thumbnails here (e.g. crop one individual face from a group photo).  So, we cannot delete it automatically.

If you did not create custom thumbnails, then you can safely delete it.
But if you did create custom thumbnails, then the control panel contains a tool to review/import/delete these custom thumbnails.

**Comment by miqrogroove** [comment]
I like the housekeeping code.

I will delete media/thumbs manually.

Thank you.
