### ISSUE TITLE
MS SQL Server driver issue

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [fisharebest/webtrees#3591]
When trying to access the MS SQL Server from Weiteres I'm getting the error that the driver is not supported.

How can I solve this issue?

**Comment by fisharebest** [comment]
Can you give the exact error message?  Where do you see it?

**Comment by mariomurrent-softwaresolutions** [comment]
This occurs when I try to install WebTrees with using a MS SQL Server. So this occurs during the installation wizard. And I only get the error that the driver is not support - there is no more information :(

**Comment by vytux-com** [comment]
I thought only MySQL and MariaDB were supported

**Comment by mariomurrent-softwaresolutions** [comment]
> I thought only MySQL and MariaDB were supported

MS SQL is in the beta phase - at least it is mentioned in the docs

**Comment by fisharebest** [comment]
Do you still see this error with the latest code?

Do you have the driver for PHP SQL-Server (`pdo-sqlsrv`) installed on your server?

**Comment by mariomurrent-softwaresolutions** [comment]
> Do you still see this error with the latest code?
> 
> 
> 
> Do you have the driver for PHP SQL-Server (`pdo-sqlsrv`) installed on your server?

Haven't tried it yet

**Comment by fisharebest** [comment]
The error message indicates a missing PHP library.
