### ISSUE TITLE
Error：'utf8_unicode_ci' is not valid for CHARACTER SET 'utf8mb4'

### ISSUE THREAD

**Issue by DaPoHou** [fisharebest/webtrees#3602]
I changed the database sorting rule from utf8_unicode_ci to utf8mb4_unicode_ci

```
MariaDB -10.4.17
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
```
Does not seem to work with utf8mb4.

Open Place list page:
`SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'utf8_unicode_ci' is not valid for CHARACTER SET 'utf8mb4' (SQL: select `p_place` from `wt_places` where `p_file` = 2 and `p_parent_id` = 0 order by p_place /*! COLLATE utf8_unicode_ci */ asc) …/vendor/illuminate/database/Connection.php:664
#0 …/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback()
#1 …/vendor/illuminate/database/Connection.php(333): Illuminate\Database\Connection->run()
#2 …/vendor/illuminate/database/Query/Builder.php(2130): Illuminate\Database\Connection->select()
#3 …/vendor/illuminate/database/Query/Builder.php(2324): Illuminate\Database\Query\Builder->runSelect()
#4 …/vendor/illuminate/database/Query/Builder.php(2604): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 …/vendor/illuminate/database/Query/Builder.php(2326): Illuminate\Database\Query\Builder->onceWithColumns()
#6 …/app/Place.php(193): Illuminate\Database\Query\Builder->pluck()
#7 …/app/Module/PlaceHierarchyListModule.php(284): Fisharebest\Webtrees\Place->getChildPlaces()
#8 …/app/Module/PlaceHierarchyListModule.php(219): Fisharebest\Webtrees\Module\PlaceHierarchyListModule->getHierarchy()
#9 …/app/Http/Middleware/WrapHandler.php(66): Fisharebest\Webtrees\Module\PlaceHierarchyListModule->handle()
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process()
#11 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#13 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
`
After Administrator Login, Website Log：
`SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION &#039;utf8_bin&#039; is not valid for CHARACTER SET &#039;utf8mb4&#039; (SQL: select n_surname /*! COLLATE utf8_bin */ AS surname, count(*) AS total from `wt_name` where `n_file` = 2 and n_surn /*! COLLATE utf8_bin */ = 印 group by `surname`) …/vendor/illuminate/database/Connection.php:664 #0 …/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection-&gt;runQueryCallback() #1 …/vendor/illuminate/database/Connection.php(333): Illuminate\Database\Connection-&gt;run() #2 …/vendor/illuminate/database/Query/Builder.php(2130): Illuminate\Database\Connection-&gt;select() #3 …/vendor/illuminate/database/Query/Builder.php(2324): Illuminate\Database\Query\Builder-&gt;runSelect() #4 …/vendor/illuminate/database/Query/Builder.php(2604): Illuminate\Database\
`

**Comment by fisharebest** [comment]
> Does not seem to work with utf8mb4.

Correct.  This issue is already known.  See #2950

**Comment by DaPoHou** [comment]
Mariadb is support utf8mb4_general_ci.
https://mariadb.com/kb/en/supported-character-sets-and-collations/
I backed up the database and re-imported it by changing the VARCHAR(255) in the SQL file to VARCHAR(191). Is it possible to support utf8mb4_general_ci
