### ISSUE TITLE
Names not shown on change name dialog

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#3606]
When changing a name, in some cases the family name and surname is not displayed. For some persons it works, for other not.
Can reproduce it on dev.webtrees.net

Here a screenshot:

![wt-change-names](https://user-images.githubusercontent.com/16715040/100207280-b56c9200-2f07-11eb-80dc-b45324d06a4d.jpg)

**Comment by HonkXL** [comment]
or here from "my" real system

![wt-change-names2](https://user-images.githubusercontent.com/16715040/100207480-ebaa1180-2f07-11eb-8255-876ba6ed55ae.jpg)

**Comment by ric2016** [comment]
The name parts are not extracted from the "1 NAME" gedcom tag (the first editable row in the name edit dialog), but from the gedcom name subtags (see "Edit the raw GEDCOM").

In the case of "Augstus the Younger" on the demo server, there are no subtags (perhaps intentionally). In your GEDCOM, there are probably none either. You'll have to detremine the cause for this - Have you imported the tree from another application, or have you created the respective person within webtrees?

Note that webtrees updates the value of the "1 NAME" automatically (when the first row is 'locked'), by using the subtag values you enter in the other fields when editing a name, but not the other way around: You can override the "1 NAME" value by editing this value directly (after unlocking it). This value is not parsed into subtags.

**Comment by fisharebest** [comment]
I think this is working as designed.

By default, you enter `GIVN`, `SURN`, etc. fields - and webtrees creates/updates the `NAME` field.

For most names, the `NAME` can be simply created from the other fields - but not all.

If the `NAME` *does* follow the standard pattern, then it will be automatically updated.
If it does not, then you must update it manually.

All the examples you show are where the `NAME` is not simply `GIVN /SURN/`.

**Comment by HonkXL** [comment]
Seems to be ok. I think this issue can be closed.
