### ISSUE TITLE
New theme code suggestion

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#361]
How about including a theme javascript object. Off the top of my head the base object could include for example the various edit windows dimensions but custom themes could add/extend as necessary

**Comment by fisharebest** [comment]
Currently, there is BaseTheme::hookFooterExtraJavascript()

This and a few other bits of the BaseTheme class need tidying up, but were written as they are to assist the migration from the old theme code.

**Comment by fisharebest** [comment]
This sounds like it should be a good idea.  I just haven't worked out how we might use it!

**Comment by fisharebest** [comment]
Themes have the ability to insert javascript (or any other content) at almost any point on the page.  I think satisfies the request.
