### ISSUE TITLE
After merge, two options for next page

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#3613]
If we pick "check for duplicates," we get a list of possible duplicates with each having a merge option.

If the merge is selected and saved, it should go back to the list of possible duplicates.

Instead it goes to the page for selecting two records to be merged.

**Comment by fisharebest** [comment]
There are two possible paths to the merge function.

Manage trees -> Find duplicates -> Merge records
Manage trees -> Merge records

So after merging, the place to return is presumably "Manage trees"?
