### ISSUE TITLE
Suggestion: Consider adding a “skip to main content” link

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3615]
See https://webplatform.news/issues/2020-05-26 - seems like a good idea

**Comment by fisharebest** [comment]
We already have this - it's the first item in the header.

```
<a class="sr-only sr-only-focusable btn btn-info btn-sm" href="#content">
    Skip to content
</a>
```

If I open a page and press tab, this link appears.

Admittedly, it is visually obscured by a logo - but it is there and functional.
It works with text-to-speech too.

<img width="380" alt="Screenshot 2020-12-10 at 16 30 54" src="https://user-images.githubusercontent.com/2306088/101800374-1e0d5e80-3b05-11eb-954a-16151f3288a3.png">

What environment do you use?  I know that MacOS disables this by default, but you can re-enable it in the settings:
https://www.scottohara.me/blog/2014/10/03/link-tabbing-firefox-osx.html

**Comment by ddrury** [comment]
Ooops.
