### ISSUE TITLE
Sorting of recent changes

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#3616]
I have the recent changes block set to sort by date, newest first.  But it is sorting by name.

And I set the limit to seven days, but three individuals added today are not shown. made today are not shown.

**Comment by WGroleau** [comment]
Puzzled.  I did not change the settings, but about a half-hour after entering this, I went to it again, and the sorting was by date and time—but the times were wrong.  Changes I made yesterday are shown as occurring one minute earlier than the three I made today.

**Comment by WGroleau** [comment]
Another half-hour, logged into tree again and changes are alphabetic again

**Comment by mrqd9** [comment]
Did you checked [This](https://www.webtrees.net/index.php/en/forum/help-for-2-0/35039-on-this-day-using-utc-time-instead-of-local-time) ?

**Comment by fisharebest** [comment]
The config option sets the default sorting.

If you change the order (by clicking on a column header), then the new order is saved in your browser storage.

This local setting in your browser storage will override the default sorting.

I just checked this, and it works as designed.

If I use the developer tools in my browser (CTRL-SHIFT-I, Storage, Local Storage) to delete all the entries for "DataTables", then I see the default order again.

<img width="1377" alt="Screenshot 2021-01-22 at 08 17 52" src="https://user-images.githubusercontent.com/2306088/105465063-62565780-5c8a-11eb-833e-58e217787535.png">

This config option is, perhaps, more useful on the tree page (for visitors) than on the user page.

Feel free to suggest some alternative logic, but at the moment it is working as intended.
