### ISSUE TITLE
Gzip compression on Apache blocked in webtrees 2.0.10

### ISSUE THREAD

**Issue by jpretired** [fisharebest/webtrees#3619]
Gzip compression on Apache is not working with wt 2.0.10.
My webtrees website is https://test.jprodina.cz/tree/nase-rodina.
The issue is described on webtrees forum post https://www.webtrees.net/index.php/en/forum/help-for-2-0/35150-gzip-compression#81786
Hosting server runs on Apache version 2.4.43, PHP 7.4.13.
The code handling response headers is in /app/Helpers/functions.php, line 116+:

`function response($content = '', $code = StatusCodeInterface::STATUS_OK, $headers = []): ResponseInterface
{
    if ($content === '' && $code === StatusCodeInterface::STATUS_OK) {
        $code = StatusCodeInterface::STATUS_NO_CONTENT;
    }

    if ($headers === []) {
        if (is_string($content)) {
            $headers = [
                'Content-Type'   => 'text/html; charset=utf-8',
                'Content-Length' => (string) strlen($content),
            ];
        } else {
`

Commenting the line

`// 'Content-Length' => (string) strlen($content),`

solves the issue, gzip compression is working OK.
May I suggest to comment or delete the mentioned line of code.
Thank you.
Btw the same issue is described at https://stackoverflow.com/questions/53314451/apache-output-compression-doesnt-work-when-content-length-is-set

**Comment by ddrury** [comment]
This is old but still gives an insight into what's going on
https://serverfault.com/questions/183843/content-length-not-sent-when-gzip-compression-enabled-in-apache

**Comment by fisharebest** [comment]
I guess we could do the compression in PHP.

**Comment by fisharebest** [comment]
There are nice packages to do this, [middlewares/encoder](https://github.com/middlewares/encoder) and [content-length](https://github.com/middlewares/content-length), but these require PHP 7.2 and we are still supporting PHP 7.1
