### ISSUE TITLE
2.0.10 doesn't load properly in older browser

### ISSUE THREAD

**Issue by lordofthemoon** [fisharebest/webtrees#3620]
Hi, I upgraded my 1.7.17 instance to 2.0.10 today and although it works as expected in the current releases of Firefox and Chrome, when I try to open the homepage in my default browser (SeaMonkey 2.53.5.1), I see a set of spinners on the homepage and nothing else.  The error console shows the messages:

ReferenceError: customElements is not defined  vendor.min.js:2:1017022
ReferenceError: $ is not defined  webtrees.min.js:1:25720
ReferenceError: $ is not defined  index.php:862:13

SeaMonkey is what Firefox is based on and the current version is roughly equivalent to Firefox 60.  I don't understand the first error, but it looks like JQuery isn't being properly loaded for the second.

**Comment by fisharebest** [comment]
> SeaMonkey is what Firefox is based on and the current version is roughly equivalent to Firefox 60

According to https://caniuse.com/?search=customelements, in this version of firefox, you need to enable support for customElements via the config settings:

> Can be enabled by setting `dom.webcomponents.customelements.enabled` to `true`.

**Comment by lordofthemoon** [comment]
Thanks, that solves that issue, but it still seems to leave me with various permissions problems.  When I try to load the 'interactive tree' for many pages, it just shows up as 'you don't have permission' (I'm admin on my installation).  I think I might just have to use a different browser for this.

**Comment by fisharebest** [comment]
> but it still seems to leave me with various permissions problems

It is difficult to manage issues when multiple problems are combined into one.

Perhaps you could create a new issue for this.  Please include things like the full/exact error message, whether you are using the interactive tree full-page/tab/chart, etc.

**Comment by lordofthemoon** [comment]
Yeah, good point.  I'll open a separate issue for the permissions issue
