### ISSUE TITLE
List "Place hierarchy" shows not existing entries for this tree

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3623]
For my main tree the list "Place hierarchy" shows not existing entries for this tree. There is always an entry "England" and sometimes an entry "Belgium". But there are no events for these locations in this tree. I'm always using "England, GBR" and "BEL". Searching for "Belgium" in my tree results in no hit. Deactivating the Vesta-modules and using the standard modules doesn't change this erroneous behavior.

![Screenshot (39)_LI](https://user-images.githubusercontent.com/6324175/101687175-64fa4600-3a6a-11eb-91aa-9b5087910d70.jpg)

**Comment by fisharebest** [comment]
If you use the search/replace to update place names, then the index tables are not updated.

This can leave "orphan" entries, such as these.

The only solution is to export/import your data.
