### ISSUE TITLE
Exported gedcom bad XREF format

### ISSUE THREAD

**Issue by makksi** [fisharebest/webtrees#3626]
I'm referring to 2.0 version

The exported Gedcom file contains this bad format:

0 OBJE @X175@
1 FILE /P500671_525_700.jpg
2 FORM jpg

instead of:
0 @X175@ OBJE
1 FILE /P500671_525_700.jpg
2 FORM jpg

so whe I try to import the exported gedcom file the following message appears:

Record GEDCOM non valido
0 OBJE @X175@
1 FILE /P500671_525_700.jpg
2 FORM jpg

**Comment by ddrury** [comment]
See @fisharebest's comment (Entry no 9) in your own forum topic !
https://www.webtrees.net/index.php/en/forum/help-for-2-0/35196-export-import-error-on-media-files

**Comment by fisharebest** [comment]
This was fixed in commit https://github.com/fisharebest/webtrees/commit/b77f2e9399d0c7e5a5dfcef91d84237029afb7d6
