### ISSUE TITLE
"On this day" using wrong time zone.

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#3632]
I noticed that the "on this day" block was on the wrong date, so I checked the preferences and saw that the time zone was set to UTC.  I changed it to America/Los Angeles, but several days and several logins later, the block is still changing dates too early.

**Comment by fisharebest** [comment]
This works OK for me.

I am currently in UTC, and see events for today (21 December).

If I change my timezone (in my account settings) to something further east (e.g. Australia/Sydney), I see events for tomorrow (22 December).

1) There are timezone settings for both users and trees (for members and visitors).  Are you sure you haven't mixed up the two.

2) Is the system clock correct on your server?

**Comment by WGroleau** [comment]
I did not know the users could set a time zone.
Mine is now also set to "America/Los Angeles"
Logged in on the server and `date` shows the same as my local clock.
