### ISSUE TITLE
Message "choose option" when adding a new child is not visible on iPad

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#3633]
When you add a new child and forget to select the sex, you will get a message "choose option"
On Safari for Mac this message is dipslayed over the browser tab and I haven't seen this the first time.
On iPad the message is displayed to much on the top of screen. You see only the lower part of the message, but not the text.

See screenshots:

Mac:
<img width="724" alt="missing-option-mac" src="https://user-images.githubusercontent.com/16715040/102724083-318ea580-430d-11eb-8ccd-5e99181236fd.png">

iPad:
![IMG_0292](https://user-images.githubusercontent.com/16715040/102724089-394e4a00-430d-11eb-8a64-cf92f94bebfd.jpeg)

Solution: make the message better visible.

**Comment by fisharebest** [comment]
When you submit a form, and there are validation errors, **some** browsers will helpfully scroll the page to the first error.

This is a browser feature.  I guess the browser on your iPad doesn't have this feature.

**Comment by HonkXL** [comment]
I understand. But if I scroll up on iPad, the message disappears. So I can not see the message and I am wondering, why it is not working.
Expected behaviour: Error message should be visible. If scrolling to the message is not working, Show the message in an other way.

**Comment by fisharebest** [comment]
This appears to be a well-known bug in iOS.

Here is one of many posts that describe it.

https://blog.teknkl.com/auto-scroll-to-first-error-ios-focus/

**Comment by HonkXL** [comment]
Bugreport sent to Apple.

**Comment by fisharebest** [comment]
Closing, as there's nothing we can do.
