### ISSUE TITLE
On-screen-keyboard broken in Firefox & Chrome

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#3635]
I just used the on-screen-keyboard for a first time.
It is broken in Firefox 84.0 (latest version).

![on-screen-keyboard-firefox](https://user-images.githubusercontent.com/16715040/102899439-2c476d00-446b-11eb-9635-b95b073e6b85.png)

**Comment by HonkXL** [comment]
Looks the same in Google Chrome.

**Comment by fisharebest** [comment]
Works for me in Firefox 85, Safari 14 and Chrome 89.

<img width="1202" alt="Screenshot 2020-12-22 at 17 46 02" src="https://user-images.githubusercontent.com/2306088/102917993-12fbec00-447e-11eb-919e-080c73876956.png">

Are you using any browser plugins or anything that might trigger this?

**Comment by fisharebest** [comment]
Also works OK in Firefox Mobile

**Comment by jpretired** [comment]
I have the same issue with Firefox 84 as HonkXL.
Btw the buttons marked with arrow work OK:

![Buttons](https://user-images.githubusercontent.com/350656/103089305-e535b500-45ed-11eb-8f62-b9d40f35f8df.jpg)

**Comment by ric2016** [comment]
Will be fixed in next Vesta release, thanks @jpretired for tracking this down!
