### ISSUE TITLE
Advanced Search by place of marriage showing no result

### ISSUE THREAD

**Issue by cdewaele** [fisharebest/webtrees#3641]
In the demo instance, there are at least 3 marriages who take place in "City of Westminster"

![image](https://user-images.githubusercontent.com/65779755/103153710-c91f4880-4792-11eb-98f9-16243b4ac575.png)

When whe try to find this records by advanced search whith place of marriage, there is not result :

![image](https://user-images.githubusercontent.com/65779755/103153754-0aaff380-4793-11eb-90a4-cce106a06e0b.png)

Maybe replacing 'Continue 2' by 'Continue 3' line 859 of SearchService.php should solve the problem ?

https://github.com/fisharebest/webtrees/blob/3d64aab23a9e354ec29ceaabc7c91293be5745aa/app/Services/SearchService.php#L859

**Comment by fisharebest** [comment]
Thanks for this fix!
