### ISSUE TITLE
Source publication URLs are not printed in the Source list as a link. wt 2.0.11-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3642]
![image](https://user-images.githubusercontent.com/5202996/103153851-54e9a280-479c-11eb-815a-03683bc946ec.png)
Sample JDC Archives - S1172

They print on the source page as a link.
![image](https://user-images.githubusercontent.com/5202996/103153868-7ba7d900-479c-11eb-86e4-f3f8be7a367d.png)

**Comment by fisharebest** [comment]
Fixed in 1197bb9cb49467b99c3a10f99876cf6c5b3b37ff
