### ISSUE TITLE
Feature Request: support webp images

### ISSUE THREAD

**Issue by Ziris85** [fisharebest/webtrees#3647]
Hello! As the title suggests, just looking to put in a feature request to support webp images in the same way as other formats are, with thumbnails and pop-out displays and such. Right now they work but display on a separate page. There's also no thumbnail preview (top image is jpeg, bottom is webp):
![Screenshot_20201231_131953](https://user-images.githubusercontent.com/14392979/103421641-73201b80-4b6b-11eb-9851-2f217d867b61.jpg)
Webp, at least in some cases, offers better image compression and smaller sizes, so would be a boon in archival software such as this.

Thanks!

**Comment by Ziris85** [comment]
Thanks for the update! This allows the popout to display the image correctly, but it doesn't appear to be able to generate a thumbnail:
![Screenshot_20210106_133155](https://user-images.githubusercontent.com/14392979/103807005-cab6ff00-5023-11eb-80f2-1dbf9f8c9ec2.png)
I tried re-uploading the image, thinking the thumbnail was only generated on image upload, but it remained this way. Does webtrees have the capacity to generate thumbnails for this media type?

**Comment by fisharebest** [comment]
> Does webtrees have the capacity to generate thumbnails for this media type?

Yes.

<img width="323" alt="Screenshot 2021-01-07 at 12 26 57" src="https://user-images.githubusercontent.com/2306088/103892536-aa4e7980-50e3-11eb-9712-6cec38f08064.png">

Look at the HTTP response headers for the thumbnail image (i.e. the red square), and you should see an error message.

It probably says that your graphics library (either `GD` or `ImageMagick`) does not support webp.

You can probably confirm this by looking at the `phpinfo()` page (Control panel -> Server information), where you can see which image formats are supported by your server.

**Comment by Ziris85** [comment]
Ah, good catch! Turns out my imagemagick install didn't support it by default. I tried compiling it in but all that resulted in was a transparent/blank thumbnail. Uninstalling the PHP ext and relying on GD allowed the thumbnail to render properly.

Thanks for the help!
