### ISSUE TITLE
Error in Block with pedigree chart if "chart pedigree" is disabled

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3650]
I disabled the standard chart "pedigree" after installing the custom module "webtrees-pedigree-chart" from magicsunday. But this results in an error in a pedigree chart in a block on "my page":
```
Call to a member function chartTitle() on null …/app/Module/ChartsBlockModule.php:108
#0 …/app/Http/RequestHandlers/UserPageBlock.php(72): Fisharebest\Webtrees\Module\ChartsBlockModule->getBlock(Object(Fisharebest\Webtrees\Tree), 39, 'user')
#1 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\UserPageBlock->handle(Object(Nyholm\Psr7\ServerRequest))
#2 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#3 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(212): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#5 …/modules_v4/faces/src/Modules/FacesModule.php(93): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
```

I would prefer an empty block instead of an error message or even better that the new pedigree chart from magicsunday can be used in this chart block.

after disabling standard pedigree chart:
![Screenshot (79)](https://user-images.githubusercontent.com/6324175/103461196-d604e480-4d1c-11eb-9e42-ca0a3f45e14c.png)
before:
![Screenshot (82)](https://user-images.githubusercontent.com/6324175/103461198-dbfac580-4d1c-11eb-8d75-e643bdaea682.png)

**Comment by ric2016** [comment]
> even better that the new pedigree chart from magicsunday can be used in this chart block.

That's not a fix to be made in webtrees - The custom module will have to be adjusted for this. Any chart that extends PedigreeChartModule will be loaded in the block. Note that the respective custom module should also provide a separate view for the block (the actual chart without the chart parameter input fields).

**Comment by magicsunday** [comment]
This is not a bug in my module. As the error message refers to a module called `vesta_research_suggestions`. If I disable the default pedigree chart module in my installation (which contains only my two custom modules) I get the following message "`The module “Pedigree” has been disabled.` but not exception is thrown.

**Comment by magicsunday** [comment]
@fisharebest Oh you already fixed this 👍 Didn't realized this.
