### ISSUE TITLE
Postgres - General search would be better if case insensitive

### ISSUE THREAD

**Issue by kalafut** [fisharebest/webtrees#3651]
It seems that the General Search function is case sensitive, but I feel it would be more convenient if it wasn't. It would be nice to quickly type "laura" and have "Laura" records to show up. More of an issue was when I was searching for "Joann" and thought there was no record, when in fact the correct spelling of the name was "JoAnn" and the record did exist.

Thanks for Webtrees! Great to find a rebooted PHPGedView which I used years ago.

**Comment by fisharebest** [comment]
What database do you use? (e.g. MySQL or Postgres)

**Comment by kalafut** [comment]
I'm using Postgres.

**Comment by fisharebest** [comment]
The webtrees setup page shows the warning "Support for PostgreSQL is experimental."

MySQL provides collation-aware searching (i.e. case-insensitive).

Postgres doesnt seem to provide this by default. 
Collations can be [created](https://www.postgresql.org/docs/12/sql-createcollation.html), but there is little online documentation/examples and it seems to be dependant on the collations available in the operating system - and there is no way to detect these.

**Comment by kalafut** [comment]
That’s fine, and useful to know. As I role this out to some others I might just revert to MySQL to get past some of the sharp edges. Everything else I’m storing (other apps) is in Postgres so I’m glad to see there is work on supporting it.

**Comment by mpfaff** [comment]
> Postgres doesnt seem to provide this by default.

Postgres provides `ILIKE`, a case-insensitive version of `LIKE`. Is that what's needed for this?
