### ISSUE TITLE
Allowed memory size exhausted makes Check for errors impossible

### ISSUE THREAD

**Issue by ghezibde** [fisharebest/webtrees#3654]
since v2 was first installed, "Check for errors" impossible on one big gedcom, ok on others.

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /home/(..////).net/genealogie/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 158

**Comment by wkitty42** [comment]
On 1/5/21 1:00 PM, ghezibde wrote:
> since v2 was first installed, "Check for errors" impossible on one big gedcom, 
> ok on others.
> 
> Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 
> 20480 bytes) in 
> /home/(..////).net/genealogie/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php 
> on line 158
your configured allowable php memory size is too small... that's only 500Meg... 
you need to increase it... maybe try doubling the value currently set in your 
php configuration... it may be set in the web server's conf, too... where ever 
it is, find it and try doubling it... that should help with this and your other 
memory related error (issue #3656)...

FWIW: i've had a few setups that required a Gig or more of RAM to be allocated 
per process to hold all the data they were working with... it'll only grow as 
more and more data is added...

**Comment by fisharebest** [comment]
The current logic loads all records into memory.

It needs to be redesigned to that it only processes a small number records in each HTTP request.

**Comment by magicsunday** [comment]
> one big gedcom
What is big?

**Comment by ghezibde** [comment]
@magicsunday 
you're right, excuses for this assertion but this error seems related to the size of the tree/gedcom.
Otherwise this tree has right now 346 096 indis / 133 945 families/ and 12 764 media objects.


,
