### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character on Add missing death records

### ISSUE THREAD

**Issue by ghezibde** [fisharebest/webtrees#3655]
The error SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data occurs when launching Data fixes / Add missing death records . Update All

**Comment by fisharebest** [comment]
@ghezibde - to investigate this, I would like to run the data-fix on your tree and examine the results.
Can I do this on your site?  Which tree?

**Comment by ghezibde** [comment]
It happens on main tree and after a while .
this message is followed, several minutes later by a error "TypeError: progressbar is null"
