### ISSUE TITLE
allowed memory size exhausted when exporting with privacy settings 

### ISSUE THREAD

**Issue by ghezibde** [fisharebest/webtrees#3656]
Since V2 install, no way to export gedcom file when applying privacy settings :
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) in /home/vdlynden/www.ghezibde.net/genealogie/vendor/symfony/cache/Adapter/ArrayAdapter.php on line 40

**Comment by ghezibde** [comment]
still occurs with 2.0.19

**Comment by ghezibde** [comment]
possible on hosting.webtrees.net ?

**Comment by ghezibde** [comment]
On our test server working on a dump of ghezibde database, we upgraded the server memory to 8 GB and visitor export now works.
During the process of export with privacy settings for visitors, available memory goes down to 1.8 GB.
The memory need to export our 175MB gedcom file is  6-8GB (3-4 for PHP, 1.3 for MySql and about 1 for system)
Does that confirm the chart you posted ?

**Comment by ghezibde** [comment]
On our test server working on a dump of ghezibde database, we upgraded the server memory to 8 GB and visitor export now works.
During the process of export with privacy settings for visitors, available memory goes down to 1.8 GB.
The memory need to export our 175MB gedcom file is  6-8GB (3-4 for PHP, 1.3 for MySql and about 1 for system)
Does that confirm the chart you posted ?
If yes, could we test export with 4 GB available for PHP ?
(this place is perhaps not the right place to talk about our hosting)

**Comment by fisharebest** [comment]
This is the same issue as #4839
