### ISSUE TITLE
Some emojis in name prefix brings error

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#3658]
I am organizing my genealogy using emojis in the prefix, to get an quick overview over important things.

This works fine with emojis like:
⚙️ < for me this means need to be checked
⚠️ < for me this means not sure - something wrong

But with this it is not working:
🧬 🧪
This are emojis from Unicode 11.0 while the other two are from around Unicode 4.

I think using emojis in this place is a very common suggestion and a lot of people are doing so.

Here the error message I get when I try to add the DNA-Symbol - verified on the webtrees demo:

`SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\xA7\xAC P...' for column 'new_gedcom' at row 1 (SQL: insert into `wtstable_change` (`gedcom_id`, `xref`, `old_gedcom`, `new_gedcom`, `user_id`) values (1, i23, 0 @i23@ INDI
1 NAME Isla Elizabeth /Phillips/
2 GIVN Isla Elizabeth
2 SURN Phillips
1 SEX F
1 FAMC @f7@
1 CHAN
2 DATE 25 MAY 2012
3 TIME 19:25:07
2 _WT_USER greg
1 BIRT
2 DATE 29 MAR 2012
2 SOUR @s1@
3 PAGE https://en.wikipedia.org/wiki/Autumn_Phillips, 0 @i23@ INDI
1 NAME Isla Elizabeth /🧬 Phillips/
2 GIVN Isla Elizabeth
2 SPFX 🧬
2 SURN Phillips
1 SEX F
1 FAMC @f7@
1 BIRT
2 DATE 29 MAR 2012
2 SOUR @s1@
3 PAGE https://en.wikipedia.org/wiki/Autumn_Phillips
1 CHAN
2 DATE 07 JAN 2021
3 TIME 10:18:49
2 _WT_USER moderator, 5)) …/vendor/illuminate/database/Connection.php:664
#0 …/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback()
#1 …/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection->run()
#2 …/vendor/illuminate/database/Connection.php(411): Illuminate\Database\Connection->statement()
#3 …/vendor/illuminate/database/Query/Builder.php(2646): Illuminate\Database\Connection->insert()
#4 …/app/GedcomRecord.php(999): Illuminate\Database\Query\Builder->insert()
#5 …/app/Http/RequestHandlers/EditFactAction.php(148): Fisharebest\Webtrees\GedcomRecord->updateFact()
#6 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\EditFactAction->handle()
#7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process()
#8 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle()
#9 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#10 …/app/Http/Middleware/AuthEditor.php(57): Middleland\Dispatcher->handle()
#11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthEditor->process()
#12 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle()
#13 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#15 …/app/Http/Middleware/Router.php(166): Middleland\Dispatcher->dispatch()
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#17 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher->handle()
#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#19 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle()
#20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#21 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#22 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#23 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#25 …/app/Http/Middleware/DoHousekeeping.php(74): Middleland\Dispatcher->handle()
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#27 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle()
#28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#29 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#31 …/app/Http/Middleware/UseLanguage.php(70): Middleland\Dispatcher->handle()
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#33 …/app/Http/Middleware/UseSession.php(71): Middleland\Dispatcher->handle()
#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#35 …/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle()
#36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#37 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle()
#38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process()
#39 …/app/Http/Middleware/UseDatabase.php(117): Middleland\Dispatcher->handle()
#40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#41 …/app/Http/Middleware/BadBotBlocker.php(212): Middleland\Dispatcher->handle()
#42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#43 …/app/Http/Middleware/RegisterFactories.php(72): Middleland\Dispatcher->handle()
#44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterFactories->process()
#45 …/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle()
#46 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#48 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#50 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle()
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#52 …/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher->handle()
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#54 …/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle()
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#56 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#58 …/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle()
#59 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process()
#60 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#61 …/index.php(57): Middleland\Dispatcher->dispatch()
#62 {main}`

**Comment by vytux-com** [comment]
I believe this is same as #2950

**Comment by fisharebest** [comment]
> I believe this is same as #2950

Yes.  It is the same issue.  Please continue the discussion there.  Thanks.
