### ISSUE TITLE
Tree Privacy Disrupts Login Redirection

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3660]
I've done some debugging with v2.0.10 and think I've found the culprit of a login issue.

If I have "Show the family tree" set to "Show to visitors", then a guest may be shown an error message when using a deep link.  Then the guest may click "Sign in" and be redirected to the deep link.

If I have "Show the family tree" set to "Show to members", then a guest is redirected to the HomePage before LoginPage, causing the 'url' param to reset to '/'.  After sign in, the guest always lands on their home page instead of the desired deep link.  The problem is after matching the deep link in the Router, the "missing mandatory parameter" condition is met before leaving the Router because the tree service never listed the tree for the logged out user.  It then calls NoRouteFound.php and destroys the url.

Do I need to customize this, or is it a "bug"?

I'm considering whether the best workaround is to use external redirection to force guests to visit the log in page with the correct url param.

Alternatively, I might figure out how to make a module that forces all guests to log in.  I have no desire to get into the weeds of whether or not the error messages are appropriate for guests.  I want everyone to log in, and then test the route for errors only when logged in.

**Comment by miqrogroove** [comment]
Workaround in NoRouteFound.php

```
        if ( $request->getAttribute('user') instanceof Fisharebest\Webtrees\User ) {
                return redirect(route(HomePage::class));
        } else {
                $url = (string) $request->getUri();
                return redirect(route(LoginPage::class, [ 'url' => $url ] ));
        }
 ```

**Comment by fisharebest** [comment]
When a tree is private (show to members), we do not allow visitors to know that it exists.

In fact, the tree privacy filtering happens at a very low level, and so the application code cannot distinguish between "tree does not exist" and "tree exists but is private".

So, when the visitor follows a link for a private tree, we have to treat it the same as if we had followed a link to a non-existant tree.  For this, the response is to redirect to the home page.

**Comment by miqrogroove** [comment]
I will keep it custom then.  Thank you for reading.
