### ISSUE TITLE
Problem with thumbnails after migrating to new webserver

### ISSUE THREAD

**Issue by MiloBeenhakker** [fisharebest/webtrees#3662]
Hello,

We are in the process of migrating our domain to a new web server. Part of that is our family genealogy for which I use Webtrees. I have made a backup of both the database and the Webtrees (2.0.10) files from the old server. After I placed the old files and the database on the new web server, I got a message that a new version was out, I installed this immediately. We got a message that some PHP modules were missing (exif, gd, intl and zip). Meanwhile all required PHP modules have been installed and I don't get any error messages in the Control Panel.
The data / thumbnail-cache folder was lost when installing Webtrees. All thumbnails generated on the old server are missing. After some searching I understood that if thumbnails do not exist, they should be automatically recreated. In our case, however, nothing happened. I have recreated the folder in question and chmod it to 777, files chmod 666. I have linked a new photo to a person, no thumbnail here, but the large photo visible. The paths to the media files are correct in the database. Everything in webtrees works fine only the thumbnails are missing, any idea how I can fix this?

Thanks in advance for your reply!

**Comment by fisharebest** [comment]
The folder `thumbnail-cache` was created/used by webtrees version 1.7

It is not used/needed by webtrees version 2.0

What exactly do you mean by "no thumbnail"?  Can you post a URL where I can see this?

**Comment by MiloBeenhakker** [comment]
Hi,

Thanks for the reply.
What I mean by no thumbnail: the reduced image (preview) of each image is not visible. Instead, a red box is shown with the extension of the file in question.
Non-graphic files such as a PDF file are displayed correctly.
Check it out at: [http://family.beenhakker.org/](url)
At the bottom of the favorites section I have placed a few files that clearly show what is happening.

**Comment by MiloBeenhakker** [comment]
Hi Greg,
Thanks for the reply.
What I mean by no thumbnail: the reduced image (preview) of each image is not visible. Instead, a red box is shown with the extension of the file in question.
Non-graphic files such as a PDF file are displayed correctly.

Check it out at: [http://family.beenhakker.org/index.php?route=%2Ftree%2Fbeenhakker](url)
At the bottom of the favorites section I have placed a few files that clearly show what is happening.

**Comment by fisharebest** [comment]
Did you check out the [FAQ](https://webtrees.net/faq/thumbnails/)?

I guess your server is unable to manipulate images due to missing drivers, etc.

**Comment by MiloBeenhakker** [comment]
Hi Greg,

The problem is solved. Apparently .jpg suppoort was not turned on in GD, so no thumbnails of the images were created. Case closed! thx Milo
