### ISSUE TITLE
#commonSurnamesTotals# and similar keywords don't work as expected

### ISSUE THREAD

**Issue by reteP-riS** [fisharebest/webtrees#3664]
With webtrees 1.7.x I used 

1. Top 10 family names: #commonSurnamesTotals:1:10:**r**count#
2. Top 10 male given names: #commonGivenMale**Totals**:1:10:rcount#
3. Top 10 female given names: #commonGivenFemale**Totals**:1:10:rcount#

To achieve the same result with webtrees 2.0.11 I have to use

1. Top 10 family names: #commonSurnamesTotals:1:10:count#
2. Top 10 male given names: #commonGivenMale:1:10:rcount#
3. Top 10 female given names: #commonGivenFemale:1:10:rcount#

Explanation:
For the surnames I have to replace "rcount" with "count" in order to list the surnames beginning with the highest number.
For the given names I have to remove "Totals" from the keywords in order to get the totals.

All three issues exist with both php 7.3.25 and php 7.4.13.

**Comment by fisharebest** [comment]
IMHO, `count` for descending and `rcount` for ascending seems more logical.  If we were showing *all* results, then maybe it would be the other way around, but since we are only showing the highest values, then high-to-low seems "natural".

So, I would regard this as a bug in 1.7 that was fixed in 2.0.

**Comment by reteP-riS** [comment]
Thanks for looking into this, Greg.

I can follow your logic and I can see that some changes have been applied to the respective code. Therefore I copied below updated files to my server and made a few tests. Some errors seem to have been corrected, but the results are not consistent.

- app/Functions/FunctionsPrintLists.php
- app/Statistics.php
- app/Statistics/Repository/IndividualRepository.php

Inconsistencies:
1. The defaults (without number interval, count or rcount) seem to work consistently and as expected (following your logic) except for #commonSurnames# and #commonSurnamesList# which are both sorted alphabetically while all others are ordered by totals in descending order.
2. When using #...:1:10:count# the results are as expected.
3. Reversing the sort order by using #...:1:10:rcount# does NOT work as expected at all except for #commonSurnames#, #commonSurnamesList#, #commonSurnamesListTotals# and #commonSurnamesTotals#. For all the others there is no difference between #...count# and #...rcount#.

**Comment by fisharebest** [comment]
> For all the others

Can you give one example?

**Comment by reteP-riS** [comment]
Sure. These - taken from https://dev.webtrees.net/demo-dev/tree/demo/my-page - are all sorted by totals and descending:

- commonGiven# Duke, Princess, Elizabeth, Count, Albert, I,, George, Sophie, Louise, Frederick
- commonGiven:1:10:count# Duke, Princess, Elizabeth, Count, Albert, I,, George, Sophie, Louise, Frederick
- commonGiven:1:10:rcount# Duke, Princess, Elizabeth, Count, Albert, I,, George, Sophie, Louise, Frederick 
- commonGivenTotals# Duke (19), Princess (12), Elizabeth (10), Count (9), Albert (8), I, (8), George (8), Sophie (8), Louise (7), Frederick (7) 
- commonGivenTotals:1:10:count# Duke (19), Princess (12), Elizabeth (10), Count (9), Albert (8), I, (8), George (8), Sophie (8), Louise (7), Frederick (7) 
- commonGivenTotals:1:10:rcount# Duke (19), Princess (12), Elizabeth (10), Count (9), Albert (8), I, (8), George (8), Sophie (8), Louise (7), Frederick (7)

**Comment by fisharebest** [comment]
These functions do not accept a "sort" parameter.  Just threshold and limit.

https://github.com/fisharebest/webtrees/blob/2.0.11/app/Statistics.php#L2254

**Comment by reteP-riS** [comment]
Not what I expected, but obviously a deliberate design decision. Thanks for looking into this!
