### ISSUE TITLE
Errors in test system Control Panels - wt 2.0.12-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3668]
I have sent a mail to Greg.

**Comment by fisharebest** [comment]
The error message indicates a file-mismatch.

I just re-installed b43e8d2bb2c and the error no longer occurs.

**Comment by melizaa** [comment]
Thanks!

**Comment by melizaa** [comment]
But why would this affect the future test system?

**Comment by melizaa** [comment]
The error is still in the future test system.
Please do not re-install it. There might exist some local program changes.

**Comment by fisharebest** [comment]
Is it the exact same error message?

**Comment by melizaa** [comment]
I have not compared automatically the 2 messages.
As far as I see they seem to be the same messages.

I'll compare them tomorrow.

**Comment by fisharebest** [comment]
The file app/Http/Routes/WebRoutes.php does not contain the latest code.

The file resources/views/admin/control-panel.phtml does contain the latest code.

This mismatch causes the error.

There may also be other outdated files.

**Comment by melizaa** [comment]
Thanks!
I did not transfer a few days ago to the test system on the server the file app/Http/Routes/WebRoutes.php.
Now the future test system works and I can transfer there the latest changes. 

I see that you removed the tests directory.
Should I remove it from all my systems on the server?

**Comment by melizaa** [comment]
The errors were the same except for the site URLs.

**Comment by melizaa** [comment]
You replaced the test test system files.
Now all of them are last modified on 12/1/2021 and the files are a little smaller than the files on my Windows local computer and the parallel files on the future test system. Some files do no longer exist on the server.
The files that no longer exist in the root directory are:
package-lock.json
php.ini
webpack.mix.js
package.json
phpstan.neon.dist
phpunit.xml.dist
the directory tests

Is it possible that when I will update the files on the server from my local Windows machine with the slightly bigger files, this may cause any problems? Is it possible that the filesizes are different because of different file endings in Windows and in Unix?
Is it possible that the missing files may cause any problems?

Meliza

**Comment by fisharebest** [comment]
> The files that no longer exist in the root directory are:

These files are only used for local development.  They are not included in the webtrees releases.

> Is it possible that when I will update the files on the server from my local Windows machine with the slightly bigger files, this may cause any problems? Is it possible that the filesizes are different because of different file endings in Windows and in Unix?

Some FTP programs will automatically convert between unix and windows line-endings when you transfer files.

You can usually disable this setting (by selecting "binary" mode instead of "text" mode).

The line endings on some files ARE important.  For example, the email template files should have windows line endings.

**Comment by melizaa** [comment]
Thanks!
