### ISSUE TITLE
duplicate records

### ISSUE THREAD

**Issue by ghezibde** [fisharebest/webtrees#3669]
Checking errors on an GEDCOM export because of issue #3654, i find out some annoying errors, mainly duplicate records. 

**- duplicate: `0 @F12510@ FAM`** (seems an old one)
```
    0 @F12510@ FAM
    0 @F12510@ FAM
```
first is empty, second contains a real record

**- duplicate: `0 @X111@`** (with detailed content)
```
    0 @X111@ INDI
    1 NAME Jacqueline /DELISQUE/
    2 GIVN Jacqueline
    2 SURN DELISQUE
    1 SEX F
    1 CHR
    2 DATE 30 SEP 1629
    2 PLAC Lynde (59173), Nord (59), Nord-Pas-de-Calais, France
    1 FAMC @X81@
    1 CHAN
    2 DATE 06 OCT 2020
    3 TIME 18:49:57
    2 _WT_USER carnel59
```
and
```
    0 @X111@ FAM
    1 CHIL @X109@
    1 HUSB @X112@
    1 WIFE @X114@
    1 MARR Y
    1 CHAN
    2 DATE 06 OCT 2020
    3 TIME 21:07:46
    2 _WT_USER vdLynden
```

**- duplicate `0 @X1204@`**
`    0 @X1204@ NOTE Archives d'état de Mons arrondissement Charleroi`
and
`    0 @X1204@ INDI`

**- duplicate `0 @X1697@`**
`    0 @X1697@ INDI`
and
`    0 @X1697@ FAM`

**- duplicate `0 @X3195@`**
`    0 @X3195@ INDI`
and
`    0 @X3195@ FAM`

I did not control wether whose errors where all in the database or if those errors where generated by the export script.

**Comment by cdewaele** [comment]
F12510 : only one row in the wt_families table, but whith a duplicate line in the  f_gedcom column :
select * from wt_families where f_id = 'F12510' and f_file = 9;

![image](https://user-images.githubusercontent.com/65779755/104512412-7517bf00-55ee-11eb-81a8-ca2f958b9b98.png)

0 @F12510@ FAM
0 @F12510@ FAM
1 HUSB @I35557@
1 WIFE @I33923@
1 CHAN
2 DATE 07 JAN 2009
3 TIME 06:41:18
2 _WT_USER xxxxxxx
1 CHIL @I35558@
1 CHIL @I35562@
1 CHIL @I35565@

The error was already in the database before webtrees V2 upgrading

X111, X1697 and X3195 seems to be real duplicates in the database : 
select * from wt_families, wt_individuals where i_id = f_id

![image](https://user-images.githubusercontent.com/65779755/104513125-73023000-55ef-11eb-82d9-0e2c183187dc.png)

Maybe something to do with #3611 ?

**Comment by fisharebest** [comment]
To fix the problem with `F12510`, use 'Edit raw GEDCOM` and click save.
I just did this for you.

> Maybe something to do with #3611 ?

Possible.  I will investigate...

**Comment by fisharebest** [comment]
#3611 occurs when two users edit the same *existing* record at the same time.
One of the edits will overwrite the other.
The solution was to lock the row in the database

This problem occurs when two users create *new* records at the same time.

Looking at `X3194` and `X3195`, there are two edits that create a new family and a new individual together.

User `b…` edited `X3161` to add a new parent family `X3194` and a new parent `X3195`.

User `d…` edited `I122223` to add a new husband `X3194` and a new family `X3195`.

**Comment by fisharebest** [comment]
To fix the existing data, try the following procedure...

(Make a copy of each GEDCOM record first!)

1) Create a new family using the same husband/wife as the existing family.  To do this, you can use the option "add a husband/wife using an existing individual".

2) In the control panel, merge these two family records (new record first, old record second).

This will copy all the facts to a new family record with a new XREF.

3) Edit the indivdual record.  e.g. add a fact and delete it.

4) Edit the new family record. e.g. add a fact and delete it.

This will re-create the search indexes.

**Comment by ghezibde** [comment]
> To fix the existing data, try the following procedure...
> (Make a copy of each GEDCOM record first!)
>     1. Create a new family using the same husband/wife as the existing family.  To do this, you can use the option "add a husband/wife using an existing individual".
>     2. In the control panel, merge these two family records (new record first, old record second).
> This will copy all the facts to a new family record with a new XREF.
>     1. Edit the indivdual record.  e.g. add a fact and delete it.
>     2. Edit the new family record. e.g. add a fact and delete it.

> This will re-create the search indexes.

I just made it.
To get this case in order, i had also to fix individual X3195 and re-create his family with X3116 and then relink his seven existing children to the new family (X14190).

**Comment by ghezibde** [comment]
I finally got rid of those duplicates ... not so easy cause concerned families where broken and i had to look for unlinked individuals to link them or unlinked spouses to delete them.
Hope nothing remains.
Guess move to 2.0.11 is highly recommended ?

**Comment by fisharebest** [comment]
> Guess move to 2.0.11 is highly recommended ?

Yes.  You should be able to use the automatic upgrade.
Or I can do it for you - if you prefer.

I have a possible solution for this issue.  But it is difficult to test.
When it is working, I will create 2.0.12.

**Comment by ghezibde** [comment]
Well, not ready for the automatic update; i'd prefer you did the update (hope we're ready for next release)

**Comment by ghezibde** [comment]
still occurs in 2.0.11
![webtrees mixed indis-v2011](https://user-images.githubusercontent.com/75539399/105522337-66f82b80-5cdd-11eb-8911-0565a1aa1c5b.png)

**Comment by ghezibde** [comment]
not able to apply the correction describet in https://github.com/fisharebest/webtrees/issues/3669#issuecomment-760164357 :

- i created family X14946 with the same husband wife than in X14937
- when i try to merge the two families X14946 and X14937 (merge-step1?xref1=X14946&xref2=X14937), merge who go to step 2

**Comment by ghezibde** [comment]
Other examples in 2.0.11
the family X14946 is included as child in family F17336
`**0 @X14946@ FAM**
1 HUSB @X14938@
1 WIFE @X14939@
1 MARR Y
1 CHIL @X14935@
1 CHIL @X14941@
1 CHIL @X14940@
1 CHAN
2 DATE 22 JAN 2021
3 TIME 17:25:09`
and 
`0 @F17336@ FAM
1 WIFE @I48722@
1 HUSB @I48721@
1 MARR
2 DATE 07 JAN 1772
2 PLAC Zuytpeene (59670), Nord (59), Nord-Pas-de-Calais, France
1 CHIL @I48727@
1 CHIL @I48731@
1 CHIL @I48726@
1 CHIL @I6374@
1 CHIL @I48733@
**1 CHIL @X14946@**
1 CHIL @X14944@
1 CHIL @I187185@
1 MARC
2 DATE ABT 07 JAN 1772
2 NOTE Notaire :  DEHANDSCHOEWERKER à Cassel
2 SOUR @S343@
3 PAGE Dépouillements Michel Moulin > version 2020-04
1 CHAN
2 DATE 22 JAN 2021
3 TIME 17:25:06`

can't guess what was lost during update ?

**Comment by ghezibde** [comment]
Other scaring example in 2.0.11
the family F42271 is included as child in family F178911 on 28 JAN 2021 21:26:12

0 @F178911@ FAM
1 HUSB @I448872@
1 WIFE @I448870@
1 MARR
2 DATE 27 JUN 1893
2 PLAC Proven, West-Vlaanderen, Vlaanderen, België
1 CHIL @X15696@
**1 CHIL @F42271@**
1 CHAN
2 DATE 28 JAN 2021
3 TIME 21:26:12

**Comment by fisharebest** [comment]
The changes that will fix this are currently in the 2.1 branch of the code.

This code is not ready for release.  But I am working on it as fast as I can.

**Comment by ghezibde** [comment]
Great !
Waiting for that release and yet knowing day last only 24h - Thanks

**Comment by ghezibde** [comment]
still present in 2.0.15, as expected

**Comment by fisharebest** [comment]
These changes are now in the `main` branch of the code.

**Comment by ghezibde** [comment]
Problems still unsolved in 2.1.13
Today 
an X153233 was inserted in family X14236 and at the same time, a X153233 with different content was added as husband in family X153234 (both action made by two different editors as you can imagine)
![image](https://user-images.githubusercontent.com/75539399/211624142-965c7580-3231-400b-820f-065debde2b25.png)

**Comment by ghezibde** [comment]
with 2.1.13, i've no way to control with  Check for errors . I want to keep gedcom _tags listed for the moment i'll check those.
This control fails most of the time for timeouts i can manage it nor use it. I wish those gedcom tags related controls were listed in another check tool or could be switched off/on before lauching control.

**Comment by fisharebest** [comment]
I have increased some limits and timeouts.
The error check worked for me just now.

Greg
--
Greg Roach, Stony Stratford, Bucks, England, ***@***.***
"Don't eat animals - it's not good for them and they don't like it"

------- Original Message -------
