### ISSUE TITLE
The dropdown menu of Family trees does not print under the icon in Clouds and Colors themes - RTL - wt 2.0.12-dev 

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3673]
The dropdown menus of Family trees, Charts, Lists, Calendars, Reports, Search, Clipping cart, etc. on LTR pages print under the texts or icons. 

On RTL pages the dropdown menu of Family trees does not print under the icon in the Clouds and Colors themes.

![image](https://user-images.githubusercontent.com/5202996/104773359-9e1a8a00-577d-11eb-81f1-76772a825e32.png)

Is this similar to #3552?

**Comment by fisharebest** [comment]
It works OK on my site and also on the demo server:

<img width="516" alt="Screenshot 2021-01-16 at 08 47 56" src="https://user-images.githubusercontent.com/2306088/104807536-9ab3ec80-57d7-11eb-8351-44eccdfe8704.png">

**Comment by melizaa** [comment]
Depending on the window size [and the page zoom (CTRL +)], I see
![image](https://user-images.githubusercontent.com/5202996/104813718-95749300-5813-11eb-88f0-7d51d2f82836.png)
and
![image](https://user-images.githubusercontent.com/5202996/104813786-02882880-5814-11eb-966f-c90ae87669cc.png)

On the LTR pages the dropdown window prints exactly under the icon border.
![image](https://user-images.githubusercontent.com/5202996/104813942-eb960600-5814-11eb-8f8a-3922ac188481.png)

This is not the most important issue.
I posted it only because it might explain what causes the RTL edit dropdown windows to print outside the page.

**Comment by fisharebest** [comment]
The 5 .0 release of bootstrap promises RTL support.

Here is the announcement in the 5.0-beta1 release notes: https://getbootstrap.com/docs/5.0/migration/#v500-beta1

**Comment by makitso** [comment]
Appears to be a problem with custom.css, will look at it.

**Comment by makitso** [comment]
Nope, its not custom.css.  On a RTL page, if one clicks on the home icon the dropdown is positioned correctly, but the second click results in an offset.

**Comment by melizaa** [comment]
I see the behavior both in my test and future test systems. 

I do not use custom-css in my test test system.
