### ISSUE TITLE
Advanced search filters for individuals/families without sources

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3674]
To complete my tree I need to add sources to the facts. But the more individuals have resources, the harder it is to find individuals without sources.

Is it possible to enhance the advanced search function with an option to filter on individuals/families without sources per selected fact?

Examples for filtering:
1. list of all individuals **born** in 1920 without **BIRT** source
2. list of all families **married** in 1945 without **MARR** source
3. list of all individuals **died** in 1970 without **DEAT** source

**Comment by fisharebest** [comment]
This is very hard to do.

We have database tables/indexes that allow us to find links between records (or the absence of a link)l

We do not have any tables/indexes that allow us to find links between facts/events.

So, this type of search would require loading *all* records into memory, extracting the facts, and then processing.

webtrees avoids operations that need to process all records, as the CPU/memory requirements will generally exceed the server limits.

The missing data report provides this functionality - but for the reason given above, it only operates on a subset of the data, such as ancestors of a given individual.

**Comment by TheDutchJewel** [comment]
If it is possible to do this with SQL queries, could you please provide an example?

**Comment by fisharebest** [comment]
It is not possible to do this with SQL queries - and this is why it is not possible to implement this feature.

**Comment by TheDutchJewel** [comment]
>list of all individuals born in 1920 without BIRT source
>It is not possible to do this with SQL queries 

Is it possible to do with regex?

With this expression all **BIRT** info can be find:
`1 BIRT.*(?:\n[2-9].*)+`

See demo at [regex101.com](https://regex101.com/r/LSqcz8/1/)

But what's the correct expression to match both conditions:
1. must contain **1920**
2. must _not_ contain **SOUR**.

**Comment by fisharebest** [comment]
> It is not possible to do this with SQL queries

Try this:

Use `SUBSTRING_INDEX()` to identify text after `\n1 BIRT`.
Then use `SUBSTRING_INDEX()` to identify text before `\n1`.
Then use `LIKE %1920%` to identify text containing the year.
Then use `NOT LIKE %\n2 SOUR%` to identify text without source links.

**Comment by TheDutchJewel** [comment]
I don't understand how to get that working.

Can you give an example how to do that?

**Comment by fisharebest** [comment]
Something very approximately like this:

```
select * from wt_individuals
where substring_index(substring_index(i_gedcom, '\n1 BIRT`, 2), '\n',1) like '%1920%'
and substring_index(substring_index(i_gedcom, '\n1 BIRT`, 2), '\n',1) not like '%\n2 SOUR%'
```

**Comment by TheDutchJewel** [comment]
```

select * from wt_individuals
where substring_index(substring_index(i_gedcom, '\n1 BIRT', 2), '\n',1) like '%1920%'
and substring_index(substring_index(i_gedcom, '\n1 BIRT', 2), '\n',1) not like '%\n2 SOUR%';

```
That selects not **DATEs** with 1920, but **IDs** with 1920 (@I1920@, @I19200@, @I19202@, @I21920@ etc):

```
0 @I1920@ INDI
1 NAME Xxxxx /Xxxx/
1 SEX M
1 BIRT
2 DATE 19 OCT 1857
2 PLAC Xxxxx
1 DEAT
2 DATE 24 JAN 1889
2 PLAC Xxxxx
1 FAMC @F549@

0 @I19200@ INDI
1 NAME Xxxxx /Xxxx/
1 SEX F
1 FAMS @F19201@

0 @I19202@ INDI
1 NAME Xxxxx /Xxxx/
1 SEX F
1 FAMC @F19201@
1 FAMS @F19206@
1 CHAN
2 DATE 26 Jan 2021
3 TIME 18:29:35
2 _WT_USER Xxxx

0 @I21920@ INDI
1 NAME Xxxxx /Xxxx/
1 SEX M
1 FAMC @F21915@
1 FAMS @F21928@
```
How to fix it?

**Comment by fisharebest** [comment]
Join on the table `wt_dates`, with `d_year = 1920` and `d_fact = BIRT`

**Comment by TheDutchJewel** [comment]
```
select * from wt_individuals
join wt_dates on d_year = 1920 and d_fact = BIRT
where substring_index(substring_index(i_gedcom, '\n1 BIRT', 2), '\n',1) like '%1920%'
and substring_index(substring_index(i_gedcom, '\n1 BIRT', 2), '\n',1) not like '%\n2 SOUR%';
```
This ends with a MySQL error:
`#1054 - Unknown column 'BIRT' in on clause`

**Comment by fisharebest** [comment]
Sorry - I assumed you know the basics of SQL.

This isn't a verbatim/tested SQL statement.  It is just thoughts expressed in SQL syntax.

BIRT is a text string.  So put it in quotes.`'BIRT'`

You'll also need to expand the `join`.

**Comment by TheDutchJewel** [comment]
> I assumed you know the basics of SQL.
I have no SQL knowledge, so I have to rely on good examples, which I can adapt to my needs.

```
select * from  wt_individuals
join wt_dates on d_year = 1920 and d_fact = 'BIRT'
where substring_index(substring_index(i_gedcom, '\n1 BIRT', 2), '\n',1) like '%1920%'
and substring_index(substring_index(i_gedcom, '\n1 BIRT', 2), '\n',1) not like '%\n2 SOUR%';``
```

This gives a long list of 5508 records with d_year = 1920 and d_fact = 'BIRT'
But all records of the first column have the same i_id (I19200), and the list is not filtered on 'without SOUR'.

**Comment by TheDutchJewel** [comment]
The long list of 5508 records was caused by multiple sample trees with same gedcom content  for testing in one webtrees database...

After removing this sample trees , there are now only **204** records with 1920 and BIRT:

```
select * from wt_dates 
where (d_year = 1920) and (d_fact = 'BIRT')
```

But this query:
```
select * from  wt_individuals
join wt_dates on d_year = 1920 and d_fact = 'BIRT'
where substring_index(substring_index(i_gedcom, '\n1 BIRT', 2), '\n',1) like '%1920%'
and substring_index(substring_index(i_gedcom, '\n1 BIRT', 2), '\n',1) not like '%\n2 SOUR%';
```
- still gives **612** records with d_year = 1920 and d_fact = 'BIRT',
- all records of the first column have the same i_id (I19200)
- the list is 

Any ideas how to fix this?

**Comment by fisharebest** [comment]
Your `join` clause needs to actually join the two tables.

select * from table1 join table2 on table1.col = table2.col and table1.col = table2.col

Here, you need to join on the i_file/d_file and i_id/d_gid columns.

**Comment by TheDutchJewel** [comment]
With:
```
select * from  wt_individuals
join wt_dates on i_file = d_file and i_id = d_gid
where substring_index(substring_index(i_gedcom, '\n1 BIRT', 2), '\n',1) like '%1920%'
and substring_index(substring_index(i_gedcom, '\n1 BIRT', 2), '\n',1) not like '%\n2 SOUR%';
```
Now I get 9 records, with as d_fact and d_gid:
1 x BIRT (I1920)
1 x DEAT (I1920)
7 x CHAN (I1920, I19202, I19203, I19205, I19207, I19209, I21920)
So still only but IDs with 1920.

**Comment by fisharebest** [comment]
Now that you have joined the dates table, you can match dates using that table

> Join on the table wt_dates, with d_year = 1920 and d_fact = BIRT

Then you won't need to match is by searching the gedom text.

**Comment by TheDutchJewel** [comment]
```
select * from  wt_individuals
join wt_dates on i_file = d_file and i_id = d_gid
join wt_dates on d_year = 1920 and d_fact = 'BIRT'
```
MySQL reports:
#1066 - Not unique value table/alias: 'wt_dates'

**Comment by fisharebest** [comment]
Replace the second `join wt_dates on` with `where`.

The `join` line joins the two tables.

Then you start filtering with a `where`

**Comment by TheDutchJewel** [comment]
```
select * from wt_individuals
join wt_dates on i_file = d_file and i_id = d_gid
where d_year = 1920 and d_fact = 'BIRT'
```
Clear. Now I get **68** records with `d_year` 1920 and `d_fact` BIRT.

**Question 1**
Why is this different from the following query which gives **204** records?
```
select * from wt_dates 
where (d_year = 1920) and (d_fact = 'BIRT')
```
**Question 2**
How to filter out the ones without `SOUR`, or even without a specific `SOUR`?

**Comment by fisharebest** [comment]
As I said at the beginning:

> This is very hard to do.

What are you trying to achieve?

If you are looking for a 100% / generic solution, then I'll stop here.

If you just want a one-off query to assist a manual edit, then use it and accept it is not perfect.

> Why is this different from the following query which gives 204 records?

This is a search index - not structured data.

If you have `1 BIRT / 2 DATE BET JAN 1920 AND MAR 1920`, then it will create two entries in the table.

> How to filter out the ones without SOUR, or even without a specific SOUR?

`WHERE <substring extract from i_gedcom> NOT LIKE `%\n2 SOUR%`


`WHERE <substring extract from i_gedcom> NOT LIKE `%\n2 SOUR @X123@%`

**Comment by TheDutchJewel** [comment]
> What are you trying to achieve?
> If you are looking for a 100% / generic solution, then I'll stop here.
> If you just want a one-off query to assist a manual edit, then use it and accept it is not perfect.

I understand that a generic solution is not possible, so a one-off query to assist a manual edit is fine.

Let me try to explain what I am looking for.
I would like to add sources that lead directly to a birth/death/marriage certificate from a given year when the certificates become available (birth after 100 years, marriage after 75 years, death after 50 years).
Sometimes a BIRT has a SOUR that does not lead directly to the birth certificate, but a SOUR from another family tree or from a newspaper. What I want to know then is:
- which BIRT fact of a given year has **no** specific SOURces (any source leading directly to birth certificate).

The BIRT facts from a given year **with** those specific sources I don't want to see then. I just want to add the missing specific sources.

Anyway, there's no difference in output between:
```
select * from wt_individuals
join wt_dates on i_file = d_file and i_id = d_gid
where d_year = 1920 and d_fact = 'BIRT'
```
and:
```
select * from wt_individuals
join wt_dates on i_file = d_file and i_id = d_gid
where d_year = 1920 and d_fact = 'BIRT'
and substring_index(substring_index(i_gedcom, '\n1 BIRT', 2), '\n',1) not like '%\n2 SOUR @S18876@%';
```
In both cases, the specific source has not been filtered out.

So how to get a list of individuals with:
- a BIRT fact of a given year (e.g. 1920) that has no specific SOURces (e.g, S18875 or S18876).

**Comment by fisharebest** [comment]
The outer call to substring_index is wrong.

You want to find the start of the next fact `\n1` - not the start of the next line `\n`.

**Comment by TheDutchJewel** [comment]
Thanks for the correction.

```
select * from wt_individuals
join wt_dates on i_file = d_file and i_id = d_gid
where d_year = 1920 and d_fact = 'BIRT'
and substring_index(substring_index(i_gedcom, '\n1 BIRT', 2), '\n1',1) not like '%\n2 SOUR @S18876@%';
```

But same result:  the specific source has not been filtered out.

**Comment by fisharebest** [comment]
Try selecting the substring expression, so you can see what is in it.

It might not be selecting the text you think it is...

**Comment by TheDutchJewel** [comment]
How to do that?

Because:
```
select * from wt_individuals
where substring_index(substring_index(i_gedcom, '\n1 BIRT', 2), '\n1',1)
```
gives this error:
`Warning: #1292 Truncated incorrect INTEGER value: '0 @I1@ INDI'`

And:
```
select substring (i_gedcom, '\n1 BIRT', 2);
```
gives this error:
`#1630 - FUNCTION webtrees.substring does not exist. Check the 'Function Name Parsing and Resolution' section in the Reference Manual`

**Comment by fisharebest** [comment]
The query starts `SELECT <list of things to select>`.

The `*` is a shortcut for a list of all columns in all tables.

You could specify all the columns in one table `wt_individuals.*` or just a list of columns `i_id, i_file, i_gedcom`.

Add the substring expression to the list of selected columns.

**Comment by TheDutchJewel** [comment]
> Add the substring expression to the list of selected columns.

What's the correct syntax for add the substring expression to the list of selected columns?

**Comment by fisharebest** [comment]
copy/paste the substring expression into the list of columns to select.

**Comment by TheDutchJewel** [comment]
`select substring_index(i_gedcom, '\n1 BIRT', 2) from wt_individuals`
This gives a list of all Individuals...

Same with:
`select substring_index(substring_index(i_gedcom, '\n1 BIRT', 2), '\n1',1) from wt_individuals`

**Comment by TheDutchJewel** [comment]
`select substring(i_gedcom, '\n1 BIRT', 2) from wt_individuals`
24632 records with value 0

`select substring(i_gedcom, 1, 100) from wt_individuals`
24632 records with the first 100 characters of the gedcom content of the individuals

Or do I have to use another substring?

**Comment by fisharebest** [comment]
We are not using the function `substring`.  We are using the function `substring_index`.

https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_substring-index

**Comment by TheDutchJewel** [comment]
`select substring_index(i_gedcom, 1, 2) from wt_individuals`
24632 records with only the 0 line (like `0 @I1@ INDI`).

`select substring_index(i_gedcom, '\n1 BIRT', 2) from wt_individuals`
24632 records with **complete** gedcom content (from first 0 line to last CHAN rows, with all facts between).
So it seems to me that `'\n1 BIRT'` doesn't do anything here.

**Comment by TheDutchJewel** [comment]
When I change the count from 2 to `1`:
`select substring_index(i_gedcom, '\n1 BIRT', 1) from wt_individuals`
I get all gedcom content down to the delimeter `'\n1 BIRT'`, like this one:

```
0 @I1@ INDI
1 NAME xxxxxxx /xxxxxxxx/
2 NICK x
1 SEX M
1 BURI
2 DATE 20 JAN 1960
2 PLAC xxxxxxxxxxx
2 SOUR @S18874@
3 PAGE xxxxx://xxx.xxxxxx-xxxxxxxxxxxxxxx.xx/xxxx/xxxxxxx
3 DATA
4 TEXT xxxx xx-xxxxxx: xxxxxxx
5 CONT xxxxxxxxxxxxxxx.: xxxx
1 OCCU xxxxxxxxxx, xxxxxxxxxx
1 FAMS @F2@
1 FAMC @F5@
1 DEAT
2 DATE 17 JAN 1960
3 TIME 21:45
2 PLAC xxxxxxxxxx
2 SOUR @S5@
3 PAGE xxxxx://xxx.xxxxxx.xxx/xx.xxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
3 DATA
4 TEXT xx.xxx-x-xxxx xxxxxxxxxx xxxxxxxxxxxxxxxx xxxxxxxxxxx xxxxx
2 SOUR @S4@
3 PAGE xxxxx://xxxxxxxxxxxxxxxxxx.xx/xxxxx/xxx/xxxx-xx-xx/xxxxxxx/x/xxxx/xx?xxxxx=xxxxxxx
```

When I change the count from 1 to `2`:
`select substring_index(i_gedcom, '\n1 BIRT', 2) from wt_individuals`
I get all gedcom content, from first to last line, like this:

```
0 @I1@ INDI
1 NAME xxxxxxx /xxxxxxxx/
2 NICK x
1 SEX M
1 BURI
2 DATE 20 JAN 1960
2 PLAC xxxxxxxxxxx
2 SOUR @S18874@
3 PAGE xxxxx://xxx.xxxxxx-xxxxxxxxxxxxxxx.xx/xxxx/xxxxxxx
3 DATA
4 TEXT xxxx xx-xxxxxx: xxxxxxx
5 CONT xxxxxxxxxxxxxxx.: xxxx
1 OCCU xxxxxxxxxx, xxxxxxxxxx
1 FAMS @F2@
1 FAMC @F5@
1 DEAT
2 DATE 17 JAN 1960
3 TIME 21:45
2 PLAC xxxxxxxxxx
2 SOUR @S5@
3 PAGE xxxxx://xxx.xxxxxx.xxx/xx.xxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
3 DATA
4 TEXT xx.xxx-x-xxxx xxxxxxxxxx xxxxxxxxxxxxxxxx xxxxxxxxxxx xxxxx
2 SOUR @S4@
3 PAGE xxxxx://xxxxxxxxxxxxxxxxxx.xx/xxxxx/xxx/xxxx-xx-xx/xxxxxxx/x/xxxx/xx?xxxxx=xxxxxxx
1 BIRT
2 DATE 10 JUN 1900
3 TIME 06:00
2 PLAC xxxxxxxxxxx
2 SOUR @S1@
3 PAGE xxxxx://xxx.xxxxxx.xxx/xx.xxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
3 DATA
4 TEXT xx.xxx-x-xxxx xxxxxxxxxxx xxxxxxxxxxxxx xxxxxxxxxxx xxxxx
5 CONT xxxxxxxxxxxx xxxxxxx xxxxxxxx, xx-xx-xxxx
1 CHAN
2 DATE 16 JAN 2021
3 TIME 14:37:47
2 _WT_USER xxxxx
```

What's the right `substring_index` expression to get only the `BIRT `part?
```
1 BIRT
2 DATE 10 JUN 1900
3 TIME 06:00
2 PLAC xxxxxxxxxxx
2 SOUR @S1@
3 PAGE xxxxx://xxx.xxxxxx.xxx/xx.xxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
3 DATA
4 TEXT xx.xxx-x-xxxx xxxxxxxxxxx xxxxxxxxxxxxx xxxxxxxxxxx xxxxx
5 CONT xxxxxxxxxxxx xxxxxxx xxxxxxxx, xx-xx-xxxx
```

**Comment by fisharebest** [comment]
OK - I mis-remembered the substring_index function.

I thought that the third parameter meant that it extracted that substring.
It seems it extracts text up to the Nth substring.

Maybe use LOCATE and SUBSTR functions instead.

You are trying to extract the substring that contains the birth record.
