### ISSUE TITLE
Add option to mass-delete unused locations

### ISSUE THREAD

**Issue by t-karcher** [fisharebest/webtrees#3676]
Follow-up to #3337:

I'm still not happy with all the rubbish piling up in my location data every time I import test / temporary trees: While I can hide them in the web interface (which breaks the alternate row colors but works otherwise fine), they're still included in the table itself and in the CSV / geoJSON export.

If preventing the automatic import is not an option, could we at least add a "Delete all unused locations" button somewhere in the admin interface?

**Comment by fisharebest** [comment]
NOTE: these comments apply to the latest dev code - which is not yet on github...

> they're still included in the table itself and in the CSV / geoJSON export

Places without co-ordinates are not included in the exports.

> Delete all unused locations

You can achieve this by

1) exporting all your location data to CSV/GEOJSON
2) importing this file - and selecting "delete all" and "update existing"
