### ISSUE TITLE
2.0.11 - regex problem with number of characters in note field

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3683]
To better sort the GEDCOM file I build a few regex commands. 

After comparing the result of regex commands in Notepad++ and webtrees, I notice that webtrees does not find all cases when the (?ms) regex modifier is used:

**Search text/pattern**
`(2 SOUR.*)(\R3 DATA.*)(\R4 TEXT.*\R5 (?ms)((?!\n[1-4]).)*?)(\R3 PAGE.*)`

**Replacement text**
`\1\5\2\3`

**GEDCOM text**
```
1 CHR
2 DATE 01 JAN 1700
2 PLAC Place
2 SOUR @S19258@
3 DATA
4 TEXT xxxx
5 CONT xxxxxxx xxx xx xxxx xxxxx xxxx.
5 CONT xxxxxxx xxx xx xxxx xxxxx.
5 CONT xxxxxxx xxx xx xxxxx xxxx.
5 CONT xxxxxxx xxx xx xxxx xxxx.
5 CONT
5 CONT "xxxxxxxxxxx, xxxxxxx xxxxxxxx, xxxxxx xxxxxxx, xxxx-xxxx," xxxxxx, xxxxxxxxxxxx (xxxxx://xxxxxxxxxxxx.xxx/xxx:/xxxxx/x:x:xxxx-xxxx-xxxx : xx xxx xxxx), xxxxxxxxxx xxxxxxxx > xxxxxxxxxx > xxxxx xxxx-xxxx xxxxxxx xxxx-xxxx xxxxxxxx xxxx-xxxx xxxxxxxx xxxx-xxxx, xxxx-xxxx > xxxxx xx xx xxx; xxxxxxxxxx xxxxxxxxxxxxxxxxxx, xxx xxxx (xxxxxxxxxxx xxxxxxxx xxxxxxxx, xxx xxxxx).
3 PAGE https://xxxxxxxxxxxx.xxx/xxx:/xxxxx/x:x:xxxx-xxxx-xxxx
```

**Result in https://regex101.com/**
![image](https://user-images.githubusercontent.com/46184729/105528580-6fecfb00-5ce5-11eb-8e36-3c5277c62ee9.png)

**Result in webtrees**
![image](https://user-images.githubusercontent.com/46184729/105528397-416f2000-5ce5-11eb-97d7-7ed867d75eb6.png)

But if I remove a (random) character from one of the '5 CONT' rows, webtrees does find the record.
Therefore, I suspect that there is a restriction set up somewhere that prevents the command from working properly.

**Comment by fisharebest** [comment]
The example above works for me.

<img width="823" alt="Screenshot 2021-01-23 at 10 41 54" src="https://user-images.githubusercontent.com/2306088/105575989-abc8a480-5d67-11eb-820a-d05158e1e342.png">

What version of MySQL are you using?  Old versions only have partial support for regular expressions.

**Comment by TheDutchJewel** [comment]
I use XAMPP v7.3.26-0, which includes MySQL v15.1

```
mysql -V
mysql  Ver 15.1 Distrib 10.4.17-MariaDB, for Win64 (AMD64), source revision 5fbfdae130950d0a5a07d4b909f3bf1ff0498d34
```

**Comment by fisharebest** [comment]
Have you tried using the regular expression directly in MariaDB?

**Comment by TheDutchJewel** [comment]
Just tested also with XAMPP v7.4.14-0 (which contains the same MySQl version):

```
mysql -V
mysql  Ver 15.1 Distrib 10.4.17-MariaDB, for Win64 (AMD64), source revision 5fbfdae130950d0a5a07d4b909f3bf1ff0498d34
```

Same problem.

Does it also work for you with more characters?
For example:
```
1 CHR
2 DATE 01 JAN 1700
2 PLAC Place
2 SOUR @S19258@
3 DATA
4 TEXT xxxx
5 CONT xxxxxxx xxx xx xxxx xxxxx xxxx.
5 CONT xxxxxxx xxx xx xxxx xxxxx.
5 CONT xxxxxxx xxx xx xxxxx xxxx.
5 CONT xxxxxxx xxx xx xxxx xxxx.
5 CONT xxxxxxx xxx xx xxxx xxxxx xxxx.
5 CONT xxxxxxx xxx xx xxxx xxxxx.
5 CONT xxxxxxx xxx xx xxxxx xxxx.
5 CONT xxxxxxx xxx xx xxxx xxxx.
5 CONT xxxxxxx xxx xx xxxx xxxxx xxxx.
5 CONT xxxxxxx xxx xx xxxx xxxxx.
5 CONT xxxxxxx xxx xx xxxxx xxxx.
5 CONT xxxxxxx xxx xx xxxx xxxx.
5 CONT xxxxxxx xxx xx xxxx xxxxx xxxx.
5 CONT xxxxxxx xxx xx xxxx xxxxx.
5 CONT xxxxxxx xxx xx xxxxx xxxx.
5 CONT xxxxxxx xxx xx xxxx xxxx.
5 CONT
5 CONT "xxxxxxxxxxx, xxxxxxx xxxxxxxx, xxxxxx xxxxxxx, xxxx-xxxx," xxxxxx, xxxxxxxxxxxx (xxxxx://xxxxxxxxxxxx.xxx/xxx:/xxxxx/x:x:xxxx-xxxx-xxxx : xx xxx xxxx), xxxxxxxxxx xxxxxxxx > xxxxxxxxxx > xxxxx xxxx-xxxx xxxxxxx xxxx-xxxx xxxxxxxx xxxx-xxxx xxxxxxxx xxxx-xxxx, xxxx-xxxx > xxxxx xx xx xxx; xxxxxxxxxx xxxxxxxxxxxxxxxxxx, xxx xxxx (xxxxxxxxxxx xxxxxxxx xxxxxxxx, xxx xxxxx).
3 PAGE https://xxxxxxxxxxxx.xxx/xxx:/xxxxx/x:x:xxxx-xxxx-xxxx
```

**Comment by TheDutchJewel** [comment]
>Have you tried using the regular expression directly in MariaDB?

No. How does that work?

**Comment by fisharebest** [comment]
Run the SQL statement

```
SELECT * FROM wt_individuals WHERE i_gedcom REGEXP '.....';
```

**Comment by TheDutchJewel** [comment]
First I got (with all commands) as a result 0 rows.

After I changed `\R` into `\n` it worked better, but now I get this error:

`Warning: #1139 Error 'pcre_exec: recursion limit of 533 exceeded' received from regexp`

**Comment by fisharebest** [comment]
Slightly off-topic, but isn't there an error in your regex?  If you have two source-citations in the same record, and the first does not have `3 PAGE`, then I think it will match the first citation and the `3 PAGE` from the second citation...

IIRC, negative assertions in regular expressions, are expensive functions, and require recursion to implement.
It looks like you hit the recursion limit for MariaDB.

I'm not sure you even need it.  A much simpler solution is:

Search: `z(2 SOUR.*)((?:\n[3-9].*)+)(\n3 PAGE.*)`
Replace `\1\3\2`

**Comment by fisharebest** [comment]
PS - the latest code in the `develop` branch will automatically re-order data like this whenever you edit it.

It will be added to the 2.1 branch in due course...

**Comment by TheDutchJewel** [comment]
>Slightly off-topic, but isn't there an error in your regex? If you have two source-citations in the same record, and the first does not have 3 PAGE, then I think it will match the first citation and the 3 PAGE from the second citation...

No, it works fine:
![image](https://user-images.githubusercontent.com/46184729/105609648-ffa8ad00-5daa-11eb-9e2a-787dd79cc2bf.png)

But your solution is better: it is simpler and works fine in webtrees!
![image](https://user-images.githubusercontent.com/46184729/105609750-a725df80-5dab-11eb-97f7-6fcd958f1e85.png)

Thanks for the solution and explanation!
