### ISSUE TITLE
Search results not fitting on mobile screen

### ISSUE THREAD

**Issue by mrqd9** [fisharebest/webtrees#3686]
Hello.. Take a look 
![20210123_192519](https://user-images.githubusercontent.com/56225476/105580210-09351380-5db1-11eb-855a-9e0179dfc00f.jpg)

I fixed it by adding `<style>.wt-search-results{width:100%; overflow-x:scroll}
</style>`

**Comment by mrqd9** [comment]
> I fixed it by adding `<style>.wt-search-results{width:100%; overflow-x:scroll} </style>`

Disclaimer: I don't think it's a fix.

**Comment by fisharebest** [comment]
This works OK on my phone.

What device?
What browser?

**Comment by mrqd9** [comment]
> What device?
Android - checked with multiple devices 
> What browser?
Chrome, Edge and Internet (samsung) 

Result No different

**Comment by mrqd9** [comment]
Not only search results, Facts table also.
![Screenshot_20210124-021745_Edge](https://user-images.githubusercontent.com/56225476/105613766-b4ae8a00-5dea-11eb-8756-10458058ba23.jpg)

**Comment by fisharebest** [comment]
It works OK with my Samsung S20 ...

![Screenshot_20210124-082832_Firefox Nightly](https://user-images.githubusercontent.com/2306088/105625155-1688e700-5e1f-11eb-8834-f3b3d1436ebd.jpg)

**Comment by mrqd9** [comment]
Screenshot from iPhone 7 plus

![IMG-20210124-WA0003](https://user-images.githubusercontent.com/56225476/105625853-16560f00-5e52-11eb-8d1c-95840df4d236.jpg)

Same with Samsung M30s, M31, Redmi Note 8, Note 7.

**Comment by sleebooth** [comment]
Not on my Samsung Note 9 (portrait but ok landscape); ok on my Samsung Galaxy S6 tablet (portrait or landscape)Chrome BrowserRegards JohnLancaster, UKResearching BOOTH, COCKING, COOK, HITCHCOX, PACK, SIMPSON, SLEE and many more.In process of transferring data to WikiTree
-------- Original message --------From: Greg Roach <notifications@github.com> Date: 24/01/2021  08:44  (GMT+00:00) To: fisharebest/webtrees <webtrees@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [fisharebest/webtrees] Search results not fitting on mobile screen (#3686) 
It works OK with my Samsung S20 ...
