### ISSUE TITLE
Some dead individuals are marked as living

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3691]
As described in the issue [squatteur/webtrees-branch-statistics/issues/1](https://github.com/squatteur/webtrees-branch-statistics/issues/1) the webtrees function [isDead()](https://github.com/fisharebest/webtrees/blob/master/app/Individual.php) does not recognize that people are dead, if their record looks like
```
1 DEAT
2 SOUR @S723@
2 AGE 55y
```

because this function tests only:  "1 DEAT Y" or "1 DEAT/2 DATE" or "1 DEAT/2 PLAC".

In my case I do not know when these persons are born, I do not know when they died; I have only the information that they died in the age of xx years.

**Comment by fisharebest** [comment]
This is correct.

According to the GEDCOM standard, to indicate than an event acutally occuredm it must have `Y` or a date or a place.

![Screenshot_20210124-082832_Firefox Nightly](https://user-images.githubusercontent.com/2306088/105644586-27bd0c80-5e8e-11eb-8233-906623aacfb3.jpg)

**Comment by hartenthaler** [comment]
Correct cited! But in the first sentence, it says "unless the line contains subordinate GEDCOM lines". So in my example, there are subordinate lines and therefore the record starts with "1 DEAT" and not with "1 DEAT Y". The standard is (as in many other cases) wrong in the example given:  "i.e. 1 DEAT Y should be used to imply a death known to have happened but date and place are unknown, not 1 DEAT". This example assumes that there are no other subordinate GEDCOM lines other than DATE and PLAC, which is wrong.

**Comment by fisharebest** [comment]
Another quotation from the GEDCOM specification.  Page 34.

<img width="854" alt="Screenshot 2021-01-25 at 13 41 58" src="https://user-images.githubusercontent.com/2306088/105713632-49140c00-5f13-11eb-89f1-0dc036be8047.png">

**Comment by fisharebest** [comment]
I think this is clear.
