### ISSUE TITLE
Problems with saving Placelocation

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3694]
A few issues with app\Http\RequestHandlers\MapDataSave.php.

Saving at the global level fails (see 1 below)

1. Line 48 `$place_id `can return an empty string so I think the line should be `$place_id  = $params['place_id'] ?: null;` 
2. Lines 63 - 66 I thought you wanted to remove this test
3. It seems to be possible that we can attempt a database query If $latitude and $longitude are both set to null which seems pointless

**Comment by fisharebest** [comment]
1. Fix incoming...
2. This restriction is OK (only allow `0,0` at top level).  I didn't like the restriction that `0,0` cannot have child places with co-ordinates.
3. If you enter `"New Place", 0, 0`, it gets saved as `"New place", null, null`.  Better than not saving at all?  Also, when support for flags is added, we will need to be able to add places with flags but no co-ordinates.
