### ISSUE TITLE
Beta - Marriage location in Places shows no records

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#3700]
I have two people married in Hessen, Germany.  Under Places I select Germany then select Hessen and no records show.

**Comment by fisharebest** [comment]
Is the problem fixed by rebuilding the search indexes? (e.g. export to a GEDCOM file and re-import)

**Comment by makitso** [comment]
Tried exporting/importing with same results.  So, are you saying that marriage locations should show up in places and when selected that the two individual records should be listed?

**Comment by fisharebest** [comment]
Yes.

Here on the demo site, if you visit the page for "London, England", you'll get a  list of people born/married/died there.

https://dev.webtrees.net/demo-dev/tree/demo/place-list?action2=hierarchy-e&place_id=612

**Comment by makitso** [comment]
How about a place that is only referenced by marriage i.e. no birth or death at that location?

**Comment by makitso** [comment]
I see my error, sorry.
