### ISSUE TITLE
A query with SearchService::searchPlaces()

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3705]
If I seach for Rome which doesn't exist in my data, the search service returns Frome, Somerset which does exist.
Is this intended behaviour?

**Comment by fisharebest** [comment]
Yes.  It is used for the auto-complete lookup.

**Comment by ddrury** [comment]
> Yes. It is used for the auto-complete lookup.

I realise that; it just seems strange the it would match something in the 'middle' of a placename. Afterall I'm not likely to start typing a place from the middle out

**Comment by fisharebest** [comment]
I use it all the time.  I have lots of ancestors from Peterborough.

To get a unique response from autocomplete, I just need to type `rb`.

If I start from the beginning, I need to type `peterb`.

**Comment by ddrury** [comment]
Hm, ok
