### ISSUE TITLE
Migration44.php: PDOException: Integrity constraint violation Duplicate entry for key 'wt2_place_location_parent_id_place_unique' 

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#3711]
I got an untraped PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1860-' for key 'wt2_place_location_parent_id_place_unique'  DEV.

Cause is a triple entry in places table (extract from places-global.csv). I guess,I added these entries ~10 years before.
```
Stufe	Place0	Place1	Place2	Place3	Place4	Place5	Longitude	Latitude	Zoom	Icon
1	USA	Iowa					W93.1	N41.9	13	places/USA/flags/IA.png
2	USA	Iowa					W93.58	N41.62	8	
2	USA	Iowa					W93.6	N41.63	7	
2	USA	Iowa	Des Moines				W93.61	N41.60	13	
2	USA	Iowa	Des Moines				W93.61	N41.60	13	
2	USA	Iowa	Des Moines				W93.61	N41.60	13	
2	USA	Iowa	Polk County				W93.50	N41.63	10	

```
the placelocation table is

```
ID | parent_id | level | place | long | lati | zomm | flag
1972 | 1860 | 2 | Polk County | W93.50 | N41.63 | 10 |  
1973 | 1860 | 2 |   | W93.58 | N41.62 | 8 |  
1974 | 1860 | 2 |   | W93.6 | N41.63 | 7 |  
1975 | 1860 | 2 | Des Moines | W93.61 | N41.60 | 13 |  
1976 | 1860 | 2 | Des Moines | W93.61 | N41.60 | 13 |  
1977 | 1860 | 2 | Des Moines | W93.61 | N41.60 | 13 |  

```
quick Fix: After native deleting 2 entries in the database for Des Moines I got another error on Groß Poserin

```
ID | parent_id | level | place | long | lati | zomm | flag
1396 | 848 | 4 | Gross Poserin | E12.183 | N53.549 | 15 |  
1397 | 848 | 4 | Kressin | E12.135 | N53.535 | 14 |  
2762 | 848 | 4 | GroÃŸ Poserin | E12.1816 | N53.5496 | 17 |  
2856 | 848 | 4 | Klein Wangelin | \N | \N | 2 |  
```

after deleting the GroÃŸ (=Groß) Poserin entry, the migration finished sucessfully

**Comment by fisharebest** [comment]
Newer versions of webtrees use database constraints to ensure data is unique.

Older versions of webtrees used PHP to ensure data is unique.  I guess there was a bug in the old code which allowed duplicates.

**Comment by FrankWarius** [comment]
a simple export to a temporary Places-Global(.csv) from old and import to new table seems to fix the problem.
Just tested with export from 2.0.10 and import in 2.0.11 Dev, with option delete old places.
There is one row for ‘Des Moines’ but 2 rows for Gross / Groß Poserin in table place_location
