### ISSUE TITLE
How can I replace the default logo ?

### ISSUE THREAD

**Issue by aravindnc** [fisharebest/webtrees#3712]
I tried to change it in the webtrees.min.css but the change is not reflecting. I've cleared the browser cache as well as cache folder still not luck.

**Comment by aravindnc** [comment]
Worked automatically after sometime. Not sure what happened.

**Comment by fisharebest** [comment]
> I tried to change it in the webtrees.min.css

If you do this, you will need to apply patches after every upgrade.

Instead, use the "CSS and JS" module in the control panel to add your own CSS to every page, with a reference to a file in your /public folder.  e.g.

```.wt-site-logo::after { content:url(/path/to/public/my-logo.png) }```

**Comment by aravindnc** [comment]
@fisharebest  Yes I did it with CSS and JS module. Thanks for the help.
