### ISSUE TITLE
Display change of the search form

### ISSUE THREAD

**Issue by mpwt** [fisharebest/webtrees#3713]
All search forms have display problems when the number of family trees is higher. Then the selection window becomes too long to see the search results at the bottom. See screenshot. On smaller screens, the search result is not visible at all!

<img width="1136" alt="Bildschirmfoto 2021-02-07 um 11 45 57" src="https://user-images.githubusercontent.com/16311627/107144265-5cbf6980-693a-11eb-95b7-eabbbb91a599.png">

Can the selection window be displayed again as a tab next to persons, families etc. after submitting the form? This was better solved in v1.7.

<img width="1197" alt="Bildschirmfoto 2021-02-07 um 11 53 40" src="https://user-images.githubusercontent.com/16311627/107144384-23d3c480-693b-11eb-8207-5588ac88eefb.png">

**Comment by fisharebest** [comment]
This is the only page in webtrees that allows a user to access more than one tree at the same time.

All other searches/lists/etc. function with just one tree.

Maybe we should search the current tree by default, with a link/option to search the others.

This way, the list of trees would be hidden until it is requested.

**Comment by mpwt** [comment]
> This way, the list of trees would be hidden until it is requested.

Thanks for the feedback. I like the overall view when calling up the search as a list of all family trees, but the selection list should be displayed as a separate tab (as in v1.7) after submitting and a result display, so that the results of the search are visible at the top of the page. Or, if there are many family trees, there is a multi-column selection of the same, f.i. with a pagination after 10-15 family trees.

Currently, the results list is not visible on smaller monitors without scrolling. Some users don't even notice that there are results. Not everyone has a 27" monitor with 5K ...

**Comment by fisharebest** [comment]
The phonetic search page also allows multiple trees to be searched.

Other pages have a consistent structure:

* page options at the top
* page data underneath

If we combine these two as tabs, it makes the page very different.
I think the inconsistency will be confusing for users.

Instead, I can collapse all the unused options.

**Comment by mpwt** [comment]
Thank you. Currently I can't test the fix on my test installation with the dev version because I didn't create enough pedigrees. Will there be a version 2.0.12 in the near future?

When using general or phonetic search, search results have tabs for individuals and families. Why not also for the search input, as it was solved in v1.7? This would actually not be a layout break compared to other pages (my opinion).
