### ISSUE TITLE
Auto-completion helper is TOO helpful

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#3717]
This has happened with both names and places.

I have an INDI named Vincenzo Dominic Mistico.

I go to add his father, who happens to be named Vincenzo Mistico with no known middle name.

When I type Vincenzo, the helper code fills in Dominic.  If I erase it, it is immediately filled in again.  The only way I know of to fix it is to save, go to the record, and then edit.  Similar with places: when I try to enter _Springfield, Lane Co., Oregon, USA_, I have to accept _Springfield, Greene Co., Missouri, USA_ and then edit.

**Comment by fisharebest** [comment]
Can you give me steps to reproduce this.

Which field (NAME, GIVN, SURN, etc.) contains `Vincenzo Dominic Mistico`?
Do you already have `Vincenzo Mistico` in the database?

**Comment by WGroleau** [comment]
As stated, Vincenzo Dominic Mistico was already in the database.
When I type "Vincenzo" in the given names field, auto-complete adds "Dominic" and highlights (selects) it.
When I tap the delete key, the highlighted part vanishes but immediately re-appears.  This happened many times, and has also happened when entering places.
ODDLY, on **one** occasion, right **after** entering this report, delete worked and it didn't come back!

`1 NAME Vincenzo Dominic /Mistico/` was in the DB, but as always, I had already deleted the unnecessary clutter of GIVN and SURN

**Comment by fisharebest** [comment]
There is no autocomplete on the `NAME` field.

Perhaps your browser provides an "autofill" function?

**Comment by WGroleau** [comment]
Yes.  And irritatingly, the default is on, including credit card information.  GBRRR!  Pretty stupid of Apple.  I would never have expected it to remember things like this, though.
