### ISSUE TITLE
We should see a Hebrew Source and Repository Title in the new and edit title forms. 2.0.12-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3720]
We should have an option to add a preference for Hebrew titles of sources and repositories in a similar way as for place names. They should not be defined by the Advanced name facts.
Now we need to use Raw editing to add the Hebrew titles.          

We do no longer fill 2 _HEB names and we do not show the Hebrew names in the forms.
We use now a separate 1 NAME for Hebrew person names.

**Comment by fisharebest** [comment]
The code that will allow this is nearly ready.  I should have an answer for you in the next week.

**Comment by fisharebest** [comment]
Definitions for custom tags are now added using the `boot()` function in a module.

Here you can see how we add support for` _TODO` tasks in the research tasks module.

https://github.com/fisharebest/webtrees/blob/d3e191dc13df4ee95fa867758ce98ec063566485/app/Module/ResearchTaskModule.php

For each new custom tag, you need to specify the type of data, the label, and (optionally), the required subtags.

You can the full list in https://github.com/fisharebest/webtrees/blob/d3e191dc13df4ee95fa867758ce98ec063566485/app/Factories/ElementFactory.php

To add support for `SOUR:TITL:_HEB` tags, you would need to redefine `TITL` to have a subtag, and add the definition for it.

Remember to import `use` the classes at the top of the file.

```
use Fisharebest\Webtrees\Elements\DescriptiveTitle;
use Fisharebest\Webtrees\Elements\NameOfRepository;
use Fisharebest\Webtrees\Elements\CustomElement;

…

public function boot(): void 
 { 
     Registry::elementFactory()->register([ 
        'SOUR:TITL'      => new DescriptiveTitle(I18N::translate('Title'), ['_HEB' => '0:1']),
        'SOUR:TITL:_HEB' => new DescriptiveTitle(I18N::translate('Hebrew name')),

        'REPO:NAME'      => new NameOfRepository(I18N::translateContext('Repository', 'Name'), ['_HEB' => '0:1']),
        'REPO:NAME:_HEB' => new NameOfRepository(I18N::translate('Hebrew name')),

        'INDI:_MTNG' => new CustomElement(I18N::translate('Mother tongue')),
    ]);
}
```

Be aware that this code is still under development, and may change slightly before the next stable release.
