### ISSUE TITLE
Bug in AutoCompleteCitation

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#3724]
Spaces are not handled properly: 

[In this line](https://github.com/fisharebest/webtrees/blob/ae0043b720d44ad147874b2a3afe4e7a347c314a/app/Http/RequestHandlers/AutoCompleteCitation.php#L50), spaces are replaced by special regex characters (for some reason), which are then quoted.

Therefore, searching for "Page 5" results in a `$regex_query` with the value `Page\.\+5`.

Fix is to swap the functions like this:
`$regex_query = strtr(preg_quote($query, '/'), [' ' => '.+']);`

**Comment by fisharebest** [comment]
> (for some reason)

This is so that you search for `1877 5` and find `Year: 1877, Volume: 5`.

> Fix is to swap the functions like this:

Thanks
