### ISSUE TITLE
In the RTL Pedigree chart Right and Left selections are wrong - 2.0.12-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3730]
In RTL Right we see the root person to the right and in Left the root person to the left.
On LTR pages Right prints the root person to the left. We should have the same behavior on RTL pages. 

Instead of the Right and Left icons in the RTL selections, we see the Down icon.

![image](https://user-images.githubusercontent.com/5202996/108088862-9b170000-7081-11eb-89e6-90ac617aca30.png)

**Comment by fisharebest** [comment]
The rotated icons are created using CSS transformations.
The RTL reflection is created using CSS transformations.

These transformations do not combine.  So, we are seeing an RTL flip of the original image - not an RTL flip of the rotated image.
