### ISSUE TITLE
Statistics chart - texts cut - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3732]
Statistics chart - Own charts - Month of birth/death - the date period texts "between YYYY and YYYY" are cut. 
We see the full text in wt 1.8-dev.

![image](https://user-images.githubusercontent.com/5202996/108116427-39b45880-70a4-11eb-8d8b-95131230a94f.png)

**Comment by fisharebest** [comment]
We use Google-Charts to create these.

I cannot find any formatting options to adjust the width of the legend.

Many people are unhappy that we use Google due to privacy concerns - so I would like to rewrite all the charts using a different charting package.

**Comment by melizaa** [comment]
Could we print "1700-1749" instead of "between 1700 and 1749", etc. ?
Would we see the full texts?

**Comment by fisharebest** [comment]
A simpler solution ;-)
