### ISSUE TITLE
Sideshow and statistics get pinwheels when used in pretty URLs.

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#3740]
I use pretty URLs for my production site skatekey.net.
In my config.ini.php it contains these values:
`base_url="https://skatekey.net"
rewrite_urls="1"`

Now, if I access my site as https://skatekey.net all works well.
However, if I access my site as https://www.skatekey.net the site displays but get pinwheels for sideshow and statistics.

Now I can fix this by adding this to my .htaccess file but is this a bug or what?

RewriteEngine On
RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
RewriteRule ^ %{REQUEST_SCHEME}://%1%{REQUEST_URI} [R=301,L]

**Comment by fisharebest** [comment]
> Now I can fix this by adding this to my .htaccess file but is this a bug or what?

This is likely to be normal.  I guess that your browser was probably complaining of cross-origin errors when sending an AJAX request.  Check the browser's error console?

It would be easier to give a definitive answer if I could visit the site while it was showing the error.

**Comment by makitso** [comment]
Using Chrome, go to https://skatekey.net
Once the site is loaded place  your cursor in the URL at the top and add www. in front of skatekey.

**Comment by fisharebest** [comment]
Chrome is preventing a page at www.skatekey.net from making a request to skatekey.net.

<img width="357" alt="Screenshot 2021-02-23 at 13 40 55" src="https://user-images.githubusercontent.com/2306088/108906163-7ccc7980-7618-11eb-9859-5e3bf572734a.png">

**Comment by makitso** [comment]
I take it that the CORS is a hosting issue.  Easier to add the Rewriterule back in to remove the www

**Comment by makitso** [comment]
Interesting, on my localhost dev system, if I change the URL to http://www.localhost/index.php?route=%2Ftree%2Fpeters.ged
I get the same errors.

**Comment by makitso** [comment]
Greg,  I am going to reopen this issue. If I use my localhost system, with the base_url="http://localhost" it works fine if I use localhost.com  However, if I use base_url="http://www.localhost" it fails with any browser.

**Comment by fisharebest** [comment]
Are you trying to make your site available at TWO different URLs, or redirect from one to the other?

The former isn't going to work, and isn't recommended.

**Comment by makitso** [comment]
IMHO, webtrees should treat www.domain.com and domain.com the same way.  I will close this issue
