### ISSUE TITLE
Theme class suggestion

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#375]
For function bodyHeaderPopupWindow() consider adding a class to body to aid in styling, eg

    return
        '<body class="simple">' .
        '<main id="content" role="main">' .
        $this->flashMessagesContainer(WT_FlashMessages::getMessages());

**Comment by fisharebest** [comment]
...although it would be good to eliminate popup windows.

The concepts of "popup" and "window" do not exist on many devices, such as tablets.
