### ISSUE TITLE
Swedish language file missing - 2.0.12-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3750]
I do not see the file in
<https://translate.webtrees.net/projects/webtrees/webtrees/sv/>

**Comment by fisharebest** [comment]
I see it there.

Maybe a temporary glitch on the translation server?

**Comment by melizaa** [comment]
Perhaps.

On the Dutch page I see
![image](https://user-images.githubusercontent.com/5202996/109426956-c93cfe00-79f8-11eb-9ff2-a1719644342e.png)

On the Swedish page I see
![image](https://user-images.githubusercontent.com/5202996/109427005-07d2b880-79f9-11eb-94d8-21813d014a88.png)

**Comment by fisharebest** [comment]
The `.PO` file was corrupt - caused by a git-merge error.
