### ISSUE TITLE
no auto upgrade to 2.0.12

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#3759]
no auto upgrade is offered in WT 2.0 (e.g. 2.0.10 or 2.0.11)
UPDATE_URL points to 
    'https://dev.webtrees.net/build/latest-version.txt' 
and here we find a hint for 1.4.6 but no entry for 2.0
    1.4.6|1.0.0|https://github.com/fisharebest/webtrees/releases/download/1.4.6/webtrees-1.4.6.zip

**Comment by fisharebest** [comment]
> no auto upgrade is offered in WT 2.0 (e.g. 2.0.10 or 2.0.11)

What version do you use now?

**Comment by FrankWarius** [comment]
currently 2.0.11. Same problem with 2.0.10. I started a manual upgrade in both cases.

**Comment by fisharebest** [comment]
> currently 2.0.11

webtrees will only check for updates every 24 hours.

Try again tomorrow?

**Comment by FrankWarius** [comment]
I changed the update check intervall to 60 sec - and same issue with 2.0.10

**Comment by fisharebest** [comment]
What entries do you have in the table wt_site_setting for: `LATEST_WT_VERSION` and `LATEST_WT_VERSION_TIMESTAMP`.

e.g. run this query in MySQL.

`select * from wt_site_setting where setting_name like 'LATEST_WT_%';`

**Comment by FrankWarius** [comment]
LATEST_WT_VERSION = '' (empty)
LATEST_WT_VERSION_TIMESTAMP = 1

**Comment by FrankWarius** [comment]
no errors or other events in the log file

**Comment by fisharebest** [comment]
Edit this file, and add the line `throw $ex;` at the highlighted line.

https://github.com/fisharebest/webtrees/blob/2.0.12/app/Services/UpgradeService.php#L296-L297

Now, when webtrees cannot connect, it should give an error message.

**Comment by FrankWarius** [comment]
it's a catched certificate error
[13-Mar-2021 14:11:23 UTC] PHP Warning:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://dev.webtrees.net/build/latest-version.txt?w=2.1.0-dev&p=7.4.16&o=w in D:\Web\WTMain\webtrees\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:211
Stack trace:
#0 D:\Web\WTMain\webtrees\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 D:\Web\WTMain\webtrees\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 D:\Web\WTMain\webtrees\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactor in D:\Web\WTMain\webtrees\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 211

**Comment by fisharebest** [comment]
Perhaps your server (or PHP configuration) does not have a root-certificate file?

This file is required for HTTPS / SSL network connections.

More info here:

https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate/34883260#34883260

**Comment by FrankWarius** [comment]
I followed your hint and https://www.php.net/manual/de/curl.configuration.php#ini.curl.cainfo :
1.	Download ‘cacert.pem’ from https://curl.haxx.se/docs/caextract.html to C:\PHPTools . It’s a list off more than 100 CA root certificates in PEM format (not a self-signed certificate).
2.	Add `curl.cainfo=C:\PHPTools\cacert.pem` to php.ini

This fixes the issue on 2.0.12 and 2.1.0 dev.
We should add a hint in https://webtrees.net/install/iis/
I did some research on backups. The last successful access to update server was on November 8 2020 before I migrated from Win Srv 2016 WT 1.7 to new out of the box Win Srv 2019 installation and WT 2.0
```
('LATEST_WT_VERSION', '1.7.17|1.0.0|https://github.com/fisharebest/webtrees/releases/download/1.7.17/webtrees-1.7.17.zip'),
('LATEST_WT_VERSION_TIMESTAMP', '1604926620'),
```

**Comment by fisharebest** [comment]
I have updated https://webtrees.net/install/iis/

**Comment by unown294** [comment]
For anyone who comes across this in the future. I was using Version 2.1.16 and ran into this issue with a path defined in both capath and updated certificate in the extra\ssl\ folder for PHP

Solution that worked for me was to use the following steps found here:
> Perhaps your server (or PHP configuration) does not have a root-certificate file?
> 
> This file is required for HTTPS / SSL network connections.
> 
> More info here:
> 
> https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate/34883260#34883260

 and enable the openSSL extension along with its cafile path (which for me was still off while running into this issue). Once defining the folder path within php.ini for the following the error went away and was able to check for a latest version:

- openssl.cafile=
- curl.cainfo=

Once defined and the extensions were enabled the issue went away. Hope this helps anyone in the future that may encounter this issue

**Again Solution was as followed:

1. verify cacert.perm was up-to-date
2. define in the php.ini where to find the cacert.perm file for the following
- openssl.cafile=
- curl.cainfo=
3. If not already enable the extensions for both openssl and curl**
