### ISSUE TITLE
I try to pull code changes and get error - wt 2.0.12-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3761]
I get
git.exe pull --progress -v --no-rebase "origin" master
fatal: Couldn't find remote ref master

git did not exit cleanly (exit code 1) (2016 ms @ 11/03/2021 21:58:39)

**Comment by fisharebest** [comment]
When you visited the webtrees repository on github, did you see a message like this:

<img width="584" alt="Screenshot 2021-03-11 at 07 38 43" src="https://user-images.githubusercontent.com/2306088/110851180-9de3ca00-82a8-11eb-9c25-df24247429a7.png">

You will need to follow those instructions.

There were two changes to the github repository today.  See here for more info:

https://www.webtrees.net/index.php/en/forum/2-open-discussion/35250-git-users

**Comment by melizaa** [comment]
<https://github.com/fisharebest/webtrees/commits/master> gives as expected error 
404 This is not the web page you are looking for.

After I remove 'master', I see the commits.

I use TortoiseGit.

**Comment by vytux-com** [comment]
You need to change master to main

**Comment by melizaa** [comment]
thanks

**Comment by melizaa** [comment]
Worked 
5980 files changed, 2763 insertions(+), 565883 deletions(-)

I do not see the green V for the root

**Comment by fisharebest** [comment]
@melizaa - don't forget that you need to run the `composer` script to install (or update) the library files in `/vendor`.

**Comment by melizaa** [comment]
Now I see the green V.
Thanks!
