### ISSUE TITLE
Source citation no longer a link

### ISSUE THREAD

**Issue by vonarezen** [fisharebest/webtrees#3763]
In facts/events I used in sources the "citation details"-field for URLs with links to the concrete page of a source with this fact/event.

Now (2.0.12) it is no longer a link like it was before (2.0.11).

---
For example two sources in a event of my database:

**Source:** Gams: Bürgerregister Band I | 1785-1886
**Citation details:** www.staatsarchiv-sg.ch/index.php?id=&bid..._01_03Tx_033-034.jpg
**Text:**
#33

**Source:** Gams: Bürgerregister Band I | 1785-1886
**Citation details:** www.staatsarchiv-sg.ch/index.php?bid=226..._01_03Tx_585-586.jpg
**Text:**
#598

**Comment by jpretired** [comment]
Please Greg, can this bug be fixed as soon as possible?
