### ISSUE TITLE
2.0.12 - new added images no longer linked to person

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#3765]
When I add a new image to a person, it is now just uploaded, but no longer linked to the person. So the new created media object is not visible in the multimedia tab.
On next step I have to link it manually. This works, but it's to complicated.

In 2.0.11 and earlier it was linked automatically.

**Comment by fisharebest** [comment]
I just tried this, and it works OK.

Any error messages in the logs?  Any other information that might help me understand what is happening on your site?

**Comment by fisharebest** [comment]
Ignore the above - wrong number in commit message...

**Comment by HonkXL** [comment]
Maybe it's a compatibility issue with the vesta addons. I will test this later. Changing the order of media files brings up a error message now...

**Comment by HonkXL** [comment]
Works after updating to the latest version of Vesta tool! After this, all bad links to media files has to be changed from @@M123@@ to @M123@

**Comment by HonkXL** [comment]
Can be closed, was a bug in vesta tools. Is fixed now.
