### ISSUE TITLE
2.0.12 Cannot add favorite

### ISSUE THREAD

**Issue by jpretired** [fisharebest/webtrees#3767]
![image](https://user-images.githubusercontent.com/350656/110935877-4e48e100-8330-11eb-9620-a24273bd7aa1.png)

**Comment by gmarcon** [comment]
Just upgraded to 2.0.12, same issue.
The dropdown selector works in other sections (like link-spouse-to-individual), only when adding a favourite does not work.
No error is shown in the javascript console.

**Comment by fisharebest** [comment]
This was caused by the upgrade from jQuery 3.5.1 to 3.6.0

I will downgrade until we can identify the problem.
