### ISSUE TITLE
Upgrade in version 2.0.12 : Erreur Data too long for column 'place' in table place_location

### ISSUE THREAD

**Issue by sibador** [fisharebest/webtrees#3769]
Hello

I have do upgrade webtrees in version 2.0.12

I have this error 
`SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column &#039;place&#039; at row 35966 (SQL: insert into `wt_place_location` (`id`, `parent_id`, `place`, `latitude`, `longitude`) select `pl_id`, CASE pl_parent_id WHEN 0 THEN NULL ELSE pl_parent_id END, `pl_place`, REPLACE(REPLACE(pl_lati, &#039;S&#039;, &#039;-&#039;), &#039;N&#039;, &#039;&#039;), REPLACE(REPLACE(pl_long, &#039;W&#039;, &#039;-&#039;), &#039;E&#039;, &#039;&#039;) from `wt_placelocation` left join `wt_place_location` on `id` = `pl_id` where `id` is null order by `pl_id` asc) …/vendor/illuminate/database/Connection.php:664 #0 …/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection-&gt;runQueryCallback(&#039;insert into `wt...&#039;, Array, Object(Closure)) #1 …/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection-&gt;run(&#039;insert into `wt...&#039;, Array, Object(Closure)) #2 …/vendor/illuminate/database/Connection.php(411): Illuminate\Database\Connection-&gt;statement(&#039;insert into `wt...&#039;, Array) #3 …/vendor/illuminate/database/Query/Builder.php(2706): Illuminate\Database\Connection-&gt;insert(&#039;insert into `wt...&#039;, Array) #4 …/app/Schema/Migration44.php(140): Illuminate\Database\Query\Builder-&gt;insertUsing(Array, Object(Illuminate\Database\Query\Builder)) #5 …/app/Services/MigrationService.php(71): Fisharebest\Webtrees\Schema\Migration44-&gt;upgrade() #6 …/app/Http/Middleware/UpdateDatabaseSchema.php(56): Fisharebest\Webtrees\Services\MigrationService-&gt;updateSchema(&#039;\\Fisharebest\\We...&#039;, &#039;WT_SCHEMA_VERSI...&#039;, 45) #7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
`

The error comes from the webtrees/app/Schema/Migration44.php file.

This migration creates a new table "place_location" and with a "place" field of 120 characters long.
This field is filled in from the "place" field of the "placelocation" table. But this field is 250 characters long.

In my database, I have 2 lines with a length greater than 120 characters.

I increased the size of the "place" field of the "place_location" table with a length of 250 characters. So I have no more mistakes.

But I think this is not the best solution.

Can you take care of this problem?

**Comment by WGroleau** [comment]
Possibly related: After upgrade, when I clicked "Continue," I got three errors.  Similar (probably the same) errors for any URI on the site.  Stack traces were very long, so I've attached an abbreviated version.  Can provide the whole thing if needed.  

Restored previous site from backup.

[PDO_errors.txt](https://github.com/fisharebest/webtrees/files/6134336/PDO_errors.txt)

**Comment by fisharebest** [comment]
In the new table, we only store the first 120 characters of a place-name (the maximum allowed in GEDCOM 5.5.1).

Note - this is just a "search index".  Your actual data is not truncated.

A fix has already been written, which will be released this weekend.

Essentially, it runs this SQL command before the migration.

You could run it yourself, now.

`UPDATE wt_placelocation SET pl_place = SUBSTR(pl_place, 1, 120);`
