### ISSUE TITLE
raw GEDCOM edit not possible for illegal record structure

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3770]
I just exported my tree and found an illegal record on level 2:
```
0 @I8585@ INDI
2 NOTE hieß er mit Nachnamen Müller und war er mit Susanna x verheiratet?
```
Why is it not possible to delete the illegal line "2 NOTE ..." using raw GEDCOM editing? This line is not displayed. It is not possible to delete this line by Search/Replace, too. This line is not shown in this case, too. Do I have to edit the database itself or is there another trick?

![Screenshot (213)_LI](https://user-images.githubusercontent.com/6324175/110984700-c7195e80-836b-11eb-9b46-168af1f716e1.jpg)

How happened this illegal structure? I deleted about 300  "1 NAME //" records just before. It was my fault replacing "\n1 NAME //\n" by "\n" instead of replacing only "\n1 NAME //\n1" by "\n1".

**Comment by fisharebest** [comment]
I guess it would be better to deleting these names by replacing `\n1 NAME //\n1` with `\n1`.

This would only match emtpy name records that did not have sub-records.

I do not think you can fix this using webtrees.
You should be able to export your tree to a GEDCOM file, edit the file, and then import it.

**Comment by fisharebest** [comment]
If this text exists only one, perhaps you can use the search/replace datafix to replace

`\n2 NOTE hieß er mit Nachnamen Müller und war er mit Susanna x verheiratet?`

with

`\n1 NAME //\n2 NOTE hieß er mit Nachnamen Müller und war er mit Susanna x verheiratet?`
