### ISSUE TITLE
2.0.12 reorder media files is not working

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#3771]
On my webtrees installation and my test-installation of 2.0.12 the function "reorder media files" is no longer working - it brings up an error. I tried it with your test installation, but there it worked. Maybe it depends on PHP version? I use 7.4.

Here the message I got:

Call to a member function fullName() on null …/resources/views/edit/reorder-media.phtml:25
#0 …/app/View.php(189): include()
#1 …/app/View.php(286): Fisharebest\Webtrees\View->render()
#2 …/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make()
#3 …/app/Http/ViewResponseTrait.php(51): view()
#4 …/app/Http/RequestHandlers/ReorderMediaPage.php(62): Fisharebest\Webtrees\Http\RequestHandlers\ReorderMediaPage->viewResponse()
#5 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\ReorderMediaPage->handle()
#6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process()
#7 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle()
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#9 …/app/Http/Middleware/AuthEditor.php(57): Middleland\Dispatcher->handle()
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthEditor->process()
#11 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#13 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#14 …/app/Http/Middleware/Router.php(166): Middleland\Dispatcher->dispatch()
#15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#16 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher->handle()
#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#18 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle()
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#20 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#21 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#22 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#24 …/app/Http/Middleware/DoHousekeeping.php(74): Middleland\Dispatcher->handle()
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#26 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle()
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#28 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#30 …/app/Http/Middleware/UseLanguage.php(70): Middleland\Dispatcher->handle()
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#32 …/app/Http/Middleware/UseSession.php(71): Middleland\Dispatcher->handle()
#33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#34 …/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle()
#35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#36 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle()
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process()
#38 …/app/Http/Middleware/UseDatabase.php(117): Middleland\Dispatcher->handle()
#39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#40 …/app/Http/Middleware/BadBotBlocker.php(217): Middleland\Dispatcher->handle()
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#42 …/app/Http/Middleware/CompressResponse.php(75): Middleland\Dispatcher->handle()
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#44 …/app/Http/Middleware/RegisterFactories.php(74): Middleland\Dispatcher->handle()
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterFactories->process()
#46 …/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle()
#47 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#48 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#49 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#51 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle()
#52 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#53 …/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher->handle()
#54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#55 …/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle()
#56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#57 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#58 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#59 …/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle()
#60 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process()
#61 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#62 …/index.php(57): Middleland\Dispatcher->dispatch()
#63 {main}

**Comment by fisharebest** [comment]
The error suggests that one of the "facts" (`1 FILE ...`) is not linked to the individual record from which it came.

Are there any pending additions/deletions?
Does the "Check for errors" in the contol panel find anything?

**Comment by HonkXL** [comment]
It shows no errors.
No pending changes.
This tree was created in webtrees and edited in webtrees. Itwas never changed outside, was never imported or manipulated in the DB.
How can I fix this?

**Comment by fisharebest** [comment]
The situation you describe should not be possible.  I cannot think how this is happening, so I have no suggestions.

I would need to understand the situation on your server.  There must be something unusual/different about this record.

Can you give me access to your site so I can examine it?

**Comment by ric2016** [comment]
This is caused by invalid entries (see 'Edit the raw GEDCOM') such as

```
1 OBJE @@M5144@@
```

caused by #3765 (actually https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/issues/61).
You'll have to remove (or fix) these links manually.

**Comment by HonkXL** [comment]
Great. This works!

#3765 seems to be related to this. You can close both issues. It's a problem with vesta shared places, I think.

**Comment by HonkXL** [comment]
This was a bug in vesta plugins. Has been fixed and works fine in latest versions.
