### ISSUE TITLE
Location Icon

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#3772]
[Shouldn't the icon of the Location record](https://github.com/fisharebest/webtrees/blob/90288370403060744b506537895bce97ce70617c/resources/views/icons/record.phtml#L32) (used e.g. when listing a location in the clippings cart) be `icons/location` rather than `icons/map`? (or a new separate icon, if we want to distinguish between Locations and Placelocations?)

What are the plans regarding support of Location records anyway? There is now a list of locations - I guess this is mainly intended for GEDCOM files imported from other applications?

**Comment by fisharebest** [comment]
> What are the plans regarding support of Location records anyway?

With the new code for GEDCOM elements, it is easy to support custom GEDCOM structures.

I added (very basic) support for Locations because it was now easy to do so.

I expect that support will improve over time.

> There is now a list of locations - I guess this is mainly intended for GEDCOM files imported from other applications?

Correct.
