### ISSUE TITLE
'aged' is not translated

### ISSUE THREAD

**Issue by jpretired** [fisharebest/webtrees#3774]
wt 2.0.12
The word 'aged' behind an individual's name is not translated:
![image](https://user-images.githubusercontent.com/350656/111043343-585b0480-8442-11eb-8800-b33ef603ae68.png)

despite the fact that in /lang/cs/messages.php there is a translation string '(aged %s)' => '(ve věku %s)'.

**Comment by fisharebest** [comment]
> despite the fact that in /lang/cs/messages.php there is a translation string '(aged %s)' => '(ve věku %s)'.

Some languages (e.g. french) require different translations for male/female/unknown.

The existing translation is now used for unknown sex.
We now have two new translations for MALE/FEMALE.

You can see the three translations here

https://translate.webtrees.net/translate/webtrees/webtrees/cs/?q=source%3Aaged+&type=all&ignored=False&checksum=&offset=

We are currently still waiting for the translations to be updated.

**Comment by jpretired** [comment]
The Czech translation has been completed.
