### ISSUE TITLE
I have sent 2 mails to Greg

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3776]
on the vendor directory and on old Hebrew issues that prevent me to upgrade my site to the main code.

**Comment by fisharebest** [comment]
I guess you run `git pull` locally, and then use SFTP to copy the updated files to the server...

After you run `git pull`, you also need to run `php composer.phar install --no-dev`.
This will fetch (locally) the latest vendor files.
You can then upload them to the server, with the other updated webtrees files.

-----

The vendor files are different for each branch.  So, the `2.0` branch will have different vendor files from the `main` branch.

In particular, we use different versions of `flysystem`.  The `2.0` branch uses flysystem v1 - which is compatible with older versions of PHP.  The `main` branch uses flysystem v2 - which is compatible with newer versions of PHP.

-----

After an upgrade, old files will be left behind.  These should be harmless.

The automatic upgrade will remove most of these old files.  But if you want to clean them out when you are upgrading manually, then a simple solution is to delete the `app`, `vendor`, and `resources` on the server before you upload the new files.

-----

You have made changes to some of the vendor files.  They look like they apply to older versions of the code, and I do not think they are still needed.  If you think they are, then perhaps create an issue on github for each of them?

**Comment by melizaa** [comment]
I do not have php on my local windows machine.
When I try to 'run php composer.phar install --no-dev' from the root of C I see
'php' is not recognized as an internal or external command, operable program or batch file.

Thanks for the other points.

**Comment by melizaa** [comment]
Can PuTTY help?

**Comment by fisharebest** [comment]
> I do not have php on my local windows machine.

Option 1 (simplest)

Install XAMPP from https://www.apachefriends.org/download.html

Then you can run PHP by typing `c:\xampp\php`.

So, the command becomes `c:\xampp\php composer.phar install --no-dev`.

TIP: instead of typing this command every time, you can create a windows batch/command file (e.g. `update.cmd`) that will run both scripts for you.

```
git pull --rebase
c:\xampp\php composer.phar install --no-dev
```

Option 2

Install cygwin https://www.cygwin.com/

This gives you access to lots of unix-style command line tools - including PHP and RSYNC

RSYNC will synchronise files between your local computer and a remote server.

You can then have an update script which does 3 things

1) git pull
2) composer install
3) rsync local files to the server

Option 3

I can set up your site to work the same as the demo site - it is updated automatically from git every hour or day.

You will still be able to make modifications to the code, but if they cause any conflicts with updates in the core code, you will probably need to ask me to resolve them.

**Comment by melizaa** [comment]
My son suggested today that he can prepare a local Linux test machine for me.
He asks, how he/we can communicate with you to finalize the set-up?

**Comment by fisharebest** [comment]
I guess it will be simplest if he emails me directly.

**Comment by melizaa** [comment]
How will we know that vendor files have changed?
Based on the past, how often do the files change?

**Comment by fisharebest** [comment]
> How will we know that vendor files have changed?

The file `composer.lock` will change.

> Based on the past, how often do the files change?

Approximately every 2 weeks.

```
$ git log --format="%h %ci %s" composer.lock
0819b6fe7 2021-03-12 11:27:00 +0000 Update vendor dependencies
f7cf8a155 2021-03-11 10:22:29 +0000 Remove vendor dir, add support for PHP 8.0, drop support for PHP 7.1 and 7.2
ac6993c3f 2021-02-18 17:36:31 +0000 Update vendor dependencies
bfaab54a7 2021-02-07 08:26:22 +0000 Upgrade vendor dependencies
b4669828e 2021-01-25 09:54:14 +0000 Update vendor code
708e66987 2020-12-27 20:48:18 +0000 Remove old dependency - league/glide
6b7955575 2020-12-19 21:37:39 +0000 Update vendor dependencies
da4213fc4 2020-11-30 17:31:29 +0000 Update vendor dependencies
7d2ca7cb2 2020-11-10 18:41:43 +0000 Update vendor dependencies
4aa632fc7 2020-10-06 12:17:15 +0100 Update vendor dependencies
1e6d05306 2020-09-19 10:27:37 +0100 Update vendor dependencies
6577bfc31 2020-09-15 07:43:50 +0100 Remove league/glide.  Use intervention/image directly.
2dce7b68a 2020-09-13 08:36:08 +0100 Update vendor dependencies
f2daa95ba 2020-09-03 19:04:24 +0100 Update vendor dependencies
d3744fc76 2020-08-05 23:48:14 +0100 Update vendor dependencies
e2cad6467 2020-07-27 11:03:26 +0100 Update vendor dependencies
e2b536aae 2020-07-21 14:16:43 +0100 Update vendor dependencies
ce785c6bf 2020-07-08 14:15:53 +0100 Update vendor dependencies
dec352c1d 2020-07-04 09:51:06 +0100 Use new PHP functions - str_starts_with(), str_ends_with() and str_contains()
deed60b3f 2020-06-29 21:27:38 +0100 Update vendor dependencies
bd0ff478d 2020-06-27 11:39:49 +0100 Update vendor dependencies
e6149aa29 2020-06-20 14:15:38 +0100 Update vendor dependencies
666268ebd 2020-06-08 00:20:27 +0100 Update vendor dependencies
8e8a90084 2020-06-01 14:14:55 +0100 Update vendor dependencies
ee843e2ef 2020-05-14 19:58:32 +0100 Update vendor dependencies
bcb233581 2020-05-07 21:53:07 +0100 Update vendor dependencies
d6acaa74d 2020-05-01 09:15:47 +0100 Update vendor dependencies
e5b0797c4 2020-04-05 18:03:28 +0100 Update dependencies
e496404fe 2020-03-28 13:58:57 +0000 Update vendor dependencies
e82ac1bc6 2020-03-02 16:16:18 +0000 Update vendor dependencies
1c7feab28 2020-02-23 19:27:07 +0000 Update vendor dependencies
089dadac9 2020-02-17 15:16:43 +0000 Check for bad robots
7d4806103 2020-02-14 12:59:52 +0000 Update vendor dependencies
228ba97d1 2020-02-12 17:14:42 +0000 #2777 - 7.4 compatibility patch has been accepted into TCPDF
600daa5d4 2020-02-11 12:06:32 +0000 Update vendor code - Update markdown handler to use new CommonMark library
26c0efaa5 2020-01-14 13:54:08 +0000 Update vendor dependencies
```

**Comment by melizaa** [comment]
My test sites' vendor directories work again.
