### ISSUE TITLE
Extra media requests Question

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#3777]
Using this as an example
https://dev.webtrees.net/demo-dev/tree/demo/individual/i177/Louise-Hilda-Agnes-d-039-Aubert

The html seems to generated  a thumbnail request for her mother that is not needed on this page.

> <div class="wt-chart-box wt-chart-box-f   overflow-hidden" data-xref="i174" data-tree="demo">
            <div class="wt-chart-box-thumbnail float-left mr-1">
            <a class="gallery" type="image/jpeg" href="https://dev.webtrees.net/demo-dev/tree/demo/media-download?xref=m90&amp;fact_id=7e4125592f70f124e49b72eaae66b22d&amp;disposition=inline&amp;mark=1" data-title="Portrait of Princess Juliane of Saxe-Coburg-Saalfeld (1795-1796)"><img class="wt-chart-box-thumbnail" dir="auto" src="https://dev.webtrees.net/demo-dev/tree/demo/media-thumbnail?xref=m90&amp;fact_id=7e4125592f70f124e49b72eaae66b22d&amp;w=40&amp;h=50&amp;fit=crop&amp;mark=1&amp;s=4fb3e8324f722d22e00b0a0ad7460b24" srcset="https://dev.webtrees.net/demo-dev/tree/demo/media-thumbnail?xref=m90&amp;fact_id=7e4125592f70f124e49b72eaae66b22d&amp;w=80&amp;h=100&amp;fit=crop&amp;mark=1&amp;s=cdfb92229da7335e61a806a19ef442e1 2x,https://dev.webtrees.net/demo-dev/tree/demo/media-thumbnail?xref=m90&amp;fact_id=7e4125592f70f124e49b72eaae66b22d&amp;w=120&amp;h=150&amp;fit=crop&amp;mark=1&amp;s=16efb7ee52456992218e923fff4c82d4 3x,https://dev.webtrees.net/demo-dev/tree/demo/media-thumbnail?xref=m90&amp;fact_id=7e4125592f70f124e49b72eaae66b22d&amp;w=160&amp;h=200&amp;fit=crop&amp;mark=1&amp;s=1305ee4899b82ab9e9cbfec6a9e70de1 4x" alt="Portrait of Princess Juliane of Saxe-Coburg-Saalfeld (1795-1796)"></a>       

</div>

**Comment by fisharebest** [comment]
Her mother - and her photo - is shown on the "Families" tab.
