### ISSUE TITLE
Request: Add custom fields to the registration form

### ISSUE THREAD

**Issue by mrqd9** [fisharebest/webtrees#3779]
Add option to create more custom input fields in register page.

**Comment by fisharebest** [comment]
Can you provide more details about what you want?

We could add extra fields.  The data would be stored in the database.

Then how is this data used?

**Comment by mrqd9** [comment]
Hello... Thank you for reply. 

Now I try to explain my aim,

Note: I am aware of that not every webtrees admin need this, I want to say that the registration page should be customizable. For example we do drag and drop blocks in "Customize this page" 

These extra fields will help an administrator to track an existing or create a new individual record of the **New User**. Fields like:  `Surname`  `Father's name`  `Mother's name`  `Grand father`  `Grand mother`  `Date of birth` etc.

All fields above are duplicate of genealogy data so don't store them in the database separately, just use them to notify administrator.
