### ISSUE TITLE
CONTRIBUTING.md - wrong link to wiki

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#3781]
In CONTRIBUTING.md there is this text:

Please refer to the guide from the official wiki.

This linkt to: https://webtrees.net/en/Category:Translation_Guidelines
but this page does not exists.

**Comment by alexschnapper** [comment]
What would be the correct link? Or should the link be removed?

**Comment by HonkXL** [comment]
I don't know where the wiki is now, after the redesign of the homepage.
