### ISSUE TITLE
Feature Request: add search for "shared locations"

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3786]
In "General search" you can search in all types of records, but not in _LOC-records. It would be nice to have this possibility, too. I don't know if this should be done in webtrees core or in a Vesta module.
![Screenshot (220)_LI](https://user-images.githubusercontent.com/6324175/111386904-33b69500-86ad-11eb-9b30-56da1e3a837c.jpg)

**Comment by ric2016** [comment]
I'm not sure either whether this should be part of the 'basic location support' within webtrees - It would show up in the search dialog for all users, even if they don't have any _LOC records (if implemented in the same way as the searches for other top-level records).

@fisharebest Let us know what you think - I could implement this either in Vesta or as a PR for webtrees itself.

**Comment by fisharebest** [comment]
> It would show up in the search dialog for all users, even if they don't have any _LOC records

For the lists menu, we only show the menu item if there are objects.

For example, we only show the submitter list when there are submitter records.

We need a location list.  It should work the same way.

The general search should also make this check.

**Comment by fisharebest** [comment]
> The general search should also make this check.

Perhaps not.  Maybe the records exist (from an import), but the user does not want to use/display them...

**Comment by ric2016** [comment]
> Perhaps not. Maybe the records exist (from an import), but the user does not want to use/display them...

The checkbox should be initially deselected anyway, just like the others for repository etc, so that wouldn't be a problem?

**Comment by reteP-riS** [comment]
The general search offers to search for shared notes even if the shared notes module is deactivated and regardless of whether shared notes exist or not.
To handle shared notes and locations consistently I suggest to only show these search options if the respective modules have been activated AND shared notes or locations exist.

**Comment by ric2016** [comment]
There is no single module which activates/deativates Shared Notes overall (and similar for other top-level records). There are only modules providing functonality for specific areas (lists etc).

In general I think it may be more confusing than useful to hide records that are contained in the respective GEDCOM. It doesn't seem very intrusive to have a deselected checkbox in the search for these record types.

**Comment by fisharebest** [comment]
I think that linking this visibility to the "lists menu" would be confusing.

We should show the option, only if the records exist.

> The checkbox should be initially deselected anyway, just like the others for repository etc, so that wouldn't be a problem?

Agreed.

**Comment by reteP-riS** [comment]
> There is no single module which activates/deativates Shared Notes overall (and similar for other top-level records). There are only modules providing functonality for specific areas (lists etc).

This is correct - thanks.

> We should show the option, only if the records exist.

I suggest to extend this to "We should show the option, only if the records exist OR the shared places module has been activated."

**Comment by ric2016** [comment]
This is now implemented in the latest Vesta release, because there is no progress here.
