### ISSUE TITLE
PHP8 issue

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3788]
At 2.1-dev   41e3e3663ef7f15489d74cf9a5ea751685c5e7e8

If this is on the list of know issues then I apologize, but on the geographic data page, attempting to import a file from the server list results in the following:

`Fatal error: Uncaught ValueError: Path cannot be empty in D:\Server\html\webtrees-2.0\vendor\nyholm\psr7\src\Factory\Psr17Factory.php:40 Stack trace: #0 D:\Server\html\webtrees-2.0\vendor\nyholm\psr7\src\Factory\Psr17Factory.php(40): fopen('', 'r') #1 D:\Server\html\webtrees-2.0\vendor\nyholm\psr7-server\src\ServerRequestCreator.php(216): Nyholm\Psr7\Factory\Psr17Factory->createStreamFromFile('') #2 D:\Server\html\webtrees-2.0\vendor\nyholm\psr7-server\src\ServerRequestCreator.php(188): Nyholm\Psr7Server\ServerRequestCreator->createUploadedFileFromSpec(Array) #3 D:\Server\html\webtrees-2.0\vendor\nyholm\psr7-server\src\ServerRequestCreator.php(98): Nyholm\Psr7Server\ServerRequestCreator->normalizeFiles(Array) #4 D:\Server\html\webtrees-2.0\vendor\nyholm\psr7-server\src\ServerRequestCreator.php(71): Nyholm\Psr7Server\ServerRequestCreator->fromArrays(Array, Array, Array, Array, Array, Array, Resource id #4) #5 D:\Server\html\webtrees-2.0\index.php(55): Nyholm\Psr7Server\ServerRequestCreator->fromGlobals() #6 {main} thrown in D:\Server\html\webtrees-2.0\vendor\nyholm\psr7\src\Factory\Psr17Factory.php on line 40`

**Comment by fisharebest** [comment]
I can't reproduce this.

What are your exact steps to trigger the error?

**Comment by ddrury** [comment]
/data/places has file places.csv. Go to control panel - geographic data - import file.  - Select file places.csv from the drop down for "A file on the server" and select continue.

Works on php 7.4.1 fails on php 8.0.3 - This is on a windows machine

**Comment by fisharebest** [comment]
https://github.com/Nyholm/psr7-server/issues/42

**Comment by ddrury** [comment]
Greg,

I notice the issue you've raised mentions an empty  filename - but we have selected a file - haven't we?

**Comment by fisharebest** [comment]
The HTML form contains two input elements. An `<input type="file">` and a `<select>`.

Only one is used.  So, if you use the `<select>`, the upload is empty - which triggers the error.

**Comment by fisharebest** [comment]
Since webtrees is built around the various PSR standards, we can easily swap to a different PSR-7 implementation - there are lots to choose from.

I chose the nyholm one because it was fairly fast/lightweight.

I'll give them some time to fix it before swapping out to another implementation.

**Comment by ddrury** [comment]
> The HTML form contains two input elements. An <input type="file"> and a <select>.

Silly me - senior moment (becoming more prevalent recently!)

**Comment by ddrury** [comment]
> The HTML form contains two input elements. An <input type="file"> and a <select>.

Silly me - senior moment (becoming more prevalent recently!)

**Comment by ddrury** [comment]
> The HTML form contains two input elements. An <input type="file"> and a <select>

Silly me - senior moment (becoming more prevalent recently!)

**Comment by ddrury** [comment]
> The HTML form contains two input elements. An <input type="file"> and a <select>
Silly me - senior moment (becoming more prevalent recently!)
