### ISSUE TITLE
A plea for help

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3791]
I've just about finished writing the code to allow live switching of map providers (see attached images) but I nead to write tests for the RequestHandlers and I'm struggling. 

Can you point me to a dummies guide to phpunit pretty please.
![demo1](https://user-images.githubusercontent.com/104515/111663045-5ad5a980-8808-11eb-9ed2-6a9e941b93af.jpg)
![demo2](https://user-images.githubusercontent.com/104515/111663055-5c9f6d00-8808-11eb-8469-16a38acd1228.jpg)

**Comment by fisharebest** [comment]
A simple test script will

1) create the request handler object
2) create a request
3) call the handler, to get a response
4) check that the response has the correct status (200, 301, etc.)

Look at the tests for LoginPage for an example

https://github.com/fisharebest/webtrees/blob/main/tests/app/Http/RequestHandlers/LoginPageTest.php

Here we have two tests, one gives a 200, the other gives a 301.

**Comment by ddrury** [comment]
OK,

Here's one to test you out. In one of the queries I use concat (see below), Sqlite uses || instead of concat so the test fails. I've taken the easy way out and abandoned that test.

```
$inner = DB::table(function ($qry) {
    $qry->selectRaw('*, concat(key_name, \'-enabled\') as enabled')
        ->from('map_names');
});
```
This is used to check a site setting (eg googlemaps-enabled) I realize that I could change the setting name but the context would be lost, so any suggestions?

**Comment by fisharebest** [comment]
`||` is the standard SQL syntax.

By default, MySQL uses it as a boolean.  But we enable "standard" behaviour in our connection settings, so you can use `||` as concat in all database engines.

**Comment by ddrury** [comment]
Easy when you know how - thanks
