### ISSUE TITLE
Website mentions a 2.1.0 version?

### ISSUE THREAD

**Issue by cburschka** [fisharebest/webtrees#3792]
The webtrees.net page mentions a version 2.1.0 in multiple places, eg on the compatibility table - 
![image](https://user-images.githubusercontent.com/1448001/111747934-32918d80-8890-11eb-923d-a38e1cbd4047.png)

on the downloads page, and in a blog entry dating its release to March 10: https://webtrees.net/blog/2021/03/10/new-webtrees-release-2-1-0.html

But there seemingly is no release and no tag (or even a branch) for it on Github, so the download link doesn't work... does this version exist yet?

**Comment by fisharebest** [comment]
> Creating a release takes a couple of hours.  There are lots of things to update.

I found a few issues just before I uploaded it.

Be patient.

**Comment by mrqd9** [comment]
Look at this. 
webtrees.net / navigation bar / demo

![Screenshot_20210319-212725_Chrome](https://user-images.githubusercontent.com/56225476/111808406-fb57c680-88f9-11eb-98d3-c6c54d81ebda.jpg)

**Comment by fisharebest** [comment]
I have updated https://webtrees.net/install/ to say "coming soon"
