### ISSUE TITLE
Adding new place to Geographic data

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#3793]
When adding a new place to Geographic data, the map will correctly display parent location and reasonable zoom level.
However, if i zoom in/out before moving the marker, the map will jump to coordinates 0,0, forcing me travel the world, zooming and dragging back to correct location. Quite annoying.

**Comment by fisharebest** [comment]
To be sure that I understand the problem:

The marker is originally placed at the parent location (or 0,0 if there is no parent location).

After you zoom, the map is redrawn to include the marker location.

If this didn't happen, the marker would be off-screen - and you wouldn't be able to drag it.

So, it seems that preventing the redraw will prevent you from seeing/moving the marker...

**Comment by HRN65** [comment]
If you want to add a new sublocation, say Woodstock, Oxfordshire, England, you go to Oxfordshire and press "add place".
The map will open and display previously set location of Oxfordshire. From here you can drag the marker to any location, zoom in or out, if necessary. 
However, if you zoom in or out (even just touch the scroll wheel) before moving the marker, the map will "jump" to South Atlantic Ocean, putting the marker at 0,0, and you will have to find your way back to Oxfordshire.
This did not happen in previous versions, there you could zoom in/out before moving the marker. It would stick to the set location for Oxfordshire.

**Comment by ddrury** [comment]
Greg,

The problem is with this bit of code about line 200 of resources/admin/location-edit.phtml
```
.on('zoomend', function () {
   $('.editable').trigger('change');
});
```
the bit of code that is triggered gets the lat/long from the form fields which of course with a new location are empty. maybe rather than triggering this bit of code we need to get the current co-ordinates and re-centre the map based on them.
