### ISSUE TITLE
Missing texts - 2.1.0-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3795]
I miss texts that did exist till now. I do not know if additional texts are also missing.

1. I would like to have some utility that would highlight all the missing texts.

2. The missing texts that I have seen so far for two of my production GEDCOMS are
INDI:ADDR:ADR1
INDI:ADDR:CITY
INDI:ADDR:POST
INDI:BURI:CEME
INDI:DATA:TEXT
INDI:DATA:EVEN
INDI:DATA:EVEN:DATE
INDI:PHON

3. I see also
INDI:MARR:HUSB
INDI:MARR:HUSB:AGE
INDI:MARR:WIFE
INDI:MARR:WIFE:AGE
and in the family record I see
**Husband:
Husband’s age: 21y
Wife:
Wife’s age: 22y**
but I do not understand why we need them, the data is already printed in the individual and family records,
**for the wife and the husband we see in addition**
Spouse's name — View this family
18 December 1910 (aged 20 years) Husband: 21 years Wife: 22 years
Westchester, NY, USA
**and for the family we see**
18 December 1910 Husband: 21 years Wife: 22 years
Westchester, NY, USA

**Comment by fisharebest** [comment]
The repeated ages for husband/wife ages have been removed.

Since 2.0.12, we define GEDCOM tags in their correct context.
We now have a definition for `FAM:MARR` instead of just `MARR`.
This means that we won't recognise tags that are used incorrectly - such as `INDI:MARR`.

**Comment by melizaa** [comment]
As we move to stricter GEDCOM tags, it is important to have a utility that will highlight past incorrect use of tags.

**Comment by fisharebest** [comment]
> it is important to have a utility that will highlight past incorrect use of tags.

Agreed.  And with the new code, it is extremely easy to write such a utility.

The difficulty is that it must be written to work on very large gedcoms and very small servers.

The logic for jobs that must be split into lots of smaller jobs is not easy.  We have something similar for importing GEDCOM files, and performing data-fixes.

I am currently working on a more generic solution to this problem.  When I have this, I can create such a tool.

**Comment by melizaa** [comment]
Greg,

When do you think that we can use the new utility that will highlight the past incorrect tags?

**Comment by melizaa** [comment]
I see for instance among my site's unrecognized GEDCOM Codes
SOUR:TITL:_HEB and
REPO:NAME:_HEB.

Should we add them to wt or should we allow a second 
1 SOUR:TITL and
1 REPO:NAME?

I can now add them using raw editing.

**Comment by fisharebest** [comment]
Adding custom tags and subtags is covered by #4008
