### ISSUE TITLE
Error - wt 2.1.0-dev 

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3800]
I uploaded the changed code files on 21/03/2021 to the test sites.
No vendor files changed although I see composer.lock in the changed file list.

When I enter the sites, I get in both of my test systems the following error:
(demo-dev does not give the error)

ParseError: syntax error, unexpected '=' in /home/amitys/test.amitys.com/app/GedcomRecord.php:406 Stack trace: 
#0 /home/amitys/test.amitys.com/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/home/amitys/te...') 
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Fisharebest\\Web...') 
#2 /home/amitys/test.amitys.com/app/Family.php(30): spl_autoload_call('Fisharebest\\Web...') 
#3 /home/amitys/test.amitys.com/vendor/composer/ClassLoader.php(480): include('/home/amitys/te...') #4 /home/amitys/test.amitys.com/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/home/amitys/te...')
etc.

I updated the code 70dafbb4965..51f91c3c9c5  .

**Comment by fisharebest** [comment]
Your site uses PHP 7.3 - which is the highest version supported by webtrees 1.7.

But the 2.1/dev code requires PHP 7.4.

So, let me see if I can configure different versions of PHP on different parts of your site...

**Comment by melizaa** [comment]
When do you think we will have a solution?

**Comment by melizaa** [comment]
My son suggests that perhaps we can use docker container.

**Comment by melizaa** [comment]
With the updated code I get now
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.27-9+ubuntu18.04.1+deb.sury.org+1. in .../test.amitys.com/vendor/composer/platform_check.php on line 24

**Comment by melizaa** [comment]
I was carrying out the last tests on the test test system in March before I planned to upgrade the code of the tree prod system to wt 2.

**Comment by melizaa** [comment]
I intended to update language files, but I do not have a system to test the texts.

**Comment by fisharebest** [comment]
This has been resolved.
