### ISSUE TITLE
_ASSO Relation

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#3801]
When adding an ASSO to Engagement event, none of the relations are translated.
Related to recent changes in fam-related events?

**Comment by fisharebest** [comment]
Just to be clear, are you adding an `ASSO` or an `_ASSO` ?

**Comment by HRN65** [comment]
1 ENGA
2 DATE 08 JUN 1778
2 PLAC xxxxxxc
2 OBJE @Mxxxx@
2 _ASSO @I5785@
3 RELA best_man
