### ISSUE TITLE
Thumbnails caching

### ISSUE THREAD

**Issue by slavkoja** [fisharebest/webtrees#3805]
Hi,

the docs is clean about caching of `/public` directory content, including versioning info. But please, can you clarify how it is with thumbnails? I am able to add some caching headers into my nginx config, based on '/media-thumbnail' URI, but is it safe?

I mean safe in situation, when image and thus thumbnail changes, to not use deprecated thumbnail... IMO most images/thumbnails will not be changed often, thus are ideal to cache, but from time to time it can happen.

**Comment by fisharebest** [comment]
Sorry for closing - clicked accidently!

Thumbnail files are cached for 100 days.

The cache "key" includes the filename and the last-modified time.

https://github.com/fisharebest/webtrees/blob/2.0.13/app/Factories/ImageFactory.php#L217

So, if you update the file on disk, a new thumbnail will be created.

> I am able to add some caching headers into my nginx config, based on '/media-thumbnail' URI, but is it safe?

I thought we added cache headers in webtrees?

Let me check...

**Comment by slavkoja** [comment]
Yes, cache headers are there, they was overwritten by my global cache settings. sorry for noise
