### ISSUE TITLE
Setting 'Unique individual facts' not evaluated correctly

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#3807]
In case of individual facts displayed e.g. in the sidebar (via IndividualMetadataModule), if the respective type is marked as 'unique individual fact', it is still always available as a new fact to be added, even if already set.

Cause: The respective check for existing unique facts ([Functionsprint::checkFactUnique](https://github.com/fisharebest/webtrees/blob/71e227692690e458be82e7cd21735966867d33e6/app/Functions/FunctionsPrint.php#L493) via [tab.phtml](https://github.com/fisharebest/webtrees/blob/71e227692690e458be82e7cd21735966867d33e6/resources/views/modules/personal_facts/tab.phtml#L54)) is based on the facts displayed by the tab itself only ([IndividualFactsTabModule::getTabContent](https://github.com/fisharebest/webtrees/blob/71e227692690e458be82e7cd21735966867d33e6/app/Module/IndividualFactsTabModule.php#L133)), with sidebar facts filtered out.

Fix: Pass the full list of used facts as an additional variable to tab.phtml and use that list for Functionsprint::checkFactUnique.

E.g. like this in IndividualFactsTabModule::getTabContent:

```
    $excludedindifacts = $individual->facts()
            ->filter(static function (Fact $fact) use ($exclude_facts): bool {
      return $exclude_facts->contains($fact->getTag());
    });

    $usedfacts = $indifacts->merge($excludedindifacts);

    return view('modules/personal_facts/tab', [
            'can_edit'             => $individual->canEdit(),
            'clipboard_facts'      => $this->clipboard_service->pastableFacts($individual, new Collection()),
            'has_historical_facts' => $historical_facts !== [],
            'individual'           => $individual,
            'facts'                => $indifacts,
            'usedfacts'            => $usedfacts,
        ]);
```

**Comment by ric2016** [comment]
On second thought, we should probably just use

```
$usedFacts = $individual->facts();
```

for the uniqueness check - this is simpler and safer: We don't have to evaluate the other displayed facts (historical facts etc) anyway for the check.

**Comment by ric2016** [comment]
This should be a simple fix - Do you need additional information?

**Comment by fisharebest** [comment]
The list of available subtags (e.g. facts and events) now comes from the GEDCOM definitions - not from the user-preferences.

So, the "Unique individual facts" preference no longer exists.

There is now a hard-coded list of "unique" facts (e.g. BIRT, DEAT), which is applied to the "quick facts" setting only.

**Comment by fisharebest** [comment]
I think this is now working with the current code/logic.

We have a hard-coded list of "unique" facts (birth, death, etc.) which are removed from the list of "quick facts"
