### ISSUE TITLE
Privacy restrictions can not be assigned to certain records

### ISSUE THREAD

**Issue by Jefferson49** [fisharebest/webtrees#3808]
When adding a new privacy restriction (in Control panel / Manage family trees / tree  - Privacy) and choosing a certain record category (e.g. "Source" or "Media object") webtrees won't take the category after saving. 

If a certain "fact or event" category was chosen, webtrees will save the privacy restriction with "All records" (instead of the chosen record):
"All records / [Fact or Event] / Show to xyz"

If no "fact or event" category was chosen, webtrees will not save the privacy restriction at all.

Issue was identified in webtrees 2.0.13

**Comment by fisharebest** [comment]
The first column allows you to select either

a) one specific record
b) all records

It does not allow you to select a "type" of record.

If you want to add a privacy restriction to all sources, select "Source" in the second column.

By default, new trees have entries in this column to make sources private.

**Comment by Jefferson49** [comment]
Thanks for the feedback. I guess, my description with "type" was some kind of misleading.

I try to rephrase:

Regarding "one specific record" or a)
If I select one specific record (in the first column) and a certain "fact or event" category (in the second column), webtrees will save the privacy restriction with "All records" (instead of the chosen specific record). The result will be:
"All records / [chosen fact or event] / Show to xyz"

Regarding "all records" or b)
If no "fact or event" category was chosen (in the second column), webtrees will not save the privacy restriction at all, regardless of the selected record (in the first column). The result will be: no new entry at all

**Comment by fisharebest** [comment]
Either I do not understand the problem or I cannot reproduce it...

> If I select one specific record (in the first column) and a certain "fact or event" category (in the second column), webtrees will save the privacy restriction with "All records" (instead of the chosen specific record)

Here, I added an entry for an individual and a fact:

![Screenshot 2021-03-29 at 12 57 28](https://user-images.githubusercontent.com/2306088/112833295-72c1ee80-908e-11eb-8ced-37e860f23361.png)

After I saved the form, I see this:

![Screenshot 2021-03-29 at 12 57 38](https://user-images.githubusercontent.com/2306088/112833313-7786a280-908e-11eb-81d8-58fd7bd5b850.png)

**Comment by Jefferson49** [comment]
Thank you very much for the screenshot! It really helped. "The Queen" opened my eyes for the additional text field, which is used to choose specific records. If ignoring this text field, the described behavior can be observed.

I have to confess that I have not recognized this text field at all, although I tried to add new privacy restrictions multiple times. My interpretation of the menu was that clicking on one of the entries in the drop down menu would choose all records of a certain type, e.g. all source records. This made a lot of sense to me. Therefore, I misunderstood the whole concept.

After understanding the menu and diving deeper into the details, it still confuses me a little bit that some objects (e.g. sources or media objects) can be chosen as "Record" in the first column, but also as "Fact or event" in the second column. I will spent  some more time for testing to gain a better understanding.

For the moment, the issue ticket can be closed, because the menu itself seems to work fine.

**Comment by fisharebest** [comment]
Certain types of "fact" are actually links.  So, "Source" is a link to a source, "Media" is a link to a media object, etc.

When you hide links to a type of object, we implicitly also hide the objects themselves.

You are right that it isn't entirely obvious.  But it has been like that for 20 years - which makes it difficult to change.

As someone who is new to the system, then if you have any suggestions on how to improve the GUI to make it more "obvious", then these would be welcome.

**Comment by Jefferson49** [comment]
> As someone who is new to the system, then if you have any suggestions on how to improve the GUI to make it more "obvious", then these would be welcome.


Maybe, an easy improvement would just address the pop up box when choosing a specific record:
a) Immediately open up the full menu structure, e.g. to choose specific records, see first screenshot
b) Show some text while opening the menu, e.g. "choose specific record", see second screenshot

![Menu with text field](https://user-images.githubusercontent.com/81484983/113348092-77103500-9336-11eb-88e1-bde4ca9e74b5.jpg)
![Menu with text field 2](https://user-images.githubusercontent.com/81484983/113348304-b63e8600-9336-11eb-86b7-7fbd46fd039b.jpg)
