### ISSUE TITLE
A few (minor) issues

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#381]
Greg, first of all I would like to say that I really like the new theme system!
I am almost done with the conversion of both of my themes without any problems.

A few things to mention though:
- The favicon is missing in the headcontents function of the BaseTheme.
- In the parameters functions several images are listed which aren't referenced anywhere in the code. I think they could be removed. This counts for the following images:
image-add, image-button_family, image-remove, image-search, image-default_image_F, image-default_image_M, image-default_image_U.
The only place the equivalent images are called is from css as background-image. I can't find them anywhere else.
- The version number is no longer set on the logo. I don't know if this is a deliberate change or not.

**Comment by fisharebest** [comment]
> The favicon is missing in the headcontents function of the BaseTheme.

OK, I'll look at this.

> In the parameters functions several images are listed which aren't referenced anywhere in the code. 

I want to replace all of these "parameters" with CSS icons, API functions, etc.
The current code is just a temporary placeholder to help me migrate the code.

> The version number is no longer set on the logo. I don't know if this is a deliberate change or not.

It's in the HTML source (CTRL-U), along with the execution statistics.

**Comment by fisharebest** [comment]
> I am almost done with the conversion of both of my themes without any problems.

If you have any suggestions for improvement, now is the time for them!

Also, the exact functions may change a little before the release.

Also, I want to change all the classnames to use namespaces.  This will be a major change that will break every custom module/theme/etc. :-(  If there is time, I will do it for 1.7.0.  If not, then 1.8.0

**Comment by fisharebest** [comment]
Also, I want to replace jQueryUI with bootstrap...

**Comment by makitso** [comment]
On 01/21/2015 01:28 PM, Greg Roach wrote:
> It's in the HTML source (CTRL-U), along with the execution statistics.
I will take a look at it.

**Comment by fisharebest** [comment]
@makitso - I mean I have deliberately moved it to the HTML source.  The execution stats, etc., are after the closing `</html>`, in a `<!--` `-->` comment.

**Comment by makitso** [comment]
Yes, I see that.  So, there is nothing I should do.

**Comment by fisharebest** [comment]
These stats are of interest to developers and site owners.  But of no interest to site visitors.  They really don't care, and it is just clutter on an already busy page.

Having them hidden in the source means everybody wins ;-)

**Comment by JustCarmen** [comment]
>>Having them hidden in the source means everybody wins ;-)

Found it. Fine solution.

>>Also, I want to replace jQueryUI with bootstrap...

Yes, I know. I already used the menu->bootstrap function in my JustLight theme. Works great.

>>Also, the exact functions may change a little before the release.
>>Also, I want to change all the classnames to use namespaces. This will be a major change that will break every custom module/theme/etc.

I know the code is still in development but It is easier for me to keep up with the changes if the main conversion of the themes is done and it gives me the time and the opportunity to test things out.

>>If you have any suggestions for improvement, now is the time for them!

Is there a possibility to have the functions hookHeaderExtraContent and hookFooterExtraJavascript or something similar, available within modules? That would be very helpful.

**Comment by fisharebest** [comment]
> Is there a possibility to have the functions hookHeaderExtraContent and hookFooterExtraJavascript or something similar, available within modules? That would be very helpful.

I agree.  The current module interface was started under PGV (and never used?), then finished in a hurry for webtrees 1.0.0.  Most of the APIs were a guess.

This change should be part of a complete review of the module API.
