### ISSUE TITLE
Multi media format is set to "jpeg" rather than "jpg"

### ISSUE THREAD

**Issue by Jefferson49** [fisharebest/webtrees#3810]
When uploading photos in *.jpg format as media objects, webtrees will set the media format to "jpeg" rather than "jpg". However, the GEDOM specifications only supports "bmp | gif | jpg | ole | pcx | tif | wav". As a consequence, some tools (e.g. GedTool) throw error messages during GEDCOM import. 

Usually, importing tools don't mind, because there is a lot of variation in today's file formats. On the other hand, a deviation of the standard should not be used if a reasonable standard attribute is available.

Example from webtrees GEDCOM:
0 @X1@ OBJE
1 FILE Foto.jpg
2 FORM jpeg
3 TYPE photo
2 TITL Foto 

Identified with webtrees version 2.0.13

**Comment by slavkoja** [comment]
IMO, `jpeg` is right MIME type, not `jpg`, AFAIK it is changed (corrected) in GEDCOM 5.5.5.

**Comment by Jefferson49** [comment]
Thanks for the hint! After rechecking, I agree that jpeg was introduced in 5.5.5.
Sorry, I had checked GEDCOM 5.5.1 standard only.

In 5.5.5, the following is specified:
"GEDCOM 5.5 uses the values JPEG and TIFF, GEDCOM 5.5.1 uses JPG and TIF instead. GEDCOM 5.5.5 uses the values JPEG and TIFF, not JPG and TIF. The JPG and TIF values are supported, but deprecated."

Therefore, it depends on the GEDCOM strategy of webtrees. 
If the webtrees GEDCOM export is based on 5.5.5, this issue can be closed.

**Comment by fisharebest** [comment]
We already had code for this - but it was wired backwards (e.g. jpg => jpeg instead of jpeg => jpg).
