### ISSUE TITLE
Webtrees one person registered twice

### ISSUE THREAD

**Issue by Sjonar** [fisharebest/webtrees#3811]
Hello! I have a problem with Webtrees.
I have registered a person as a child in one family with his parents and sisters and brothers. Then I found that this child was the same person who was registered as a husband in another family. 
**The same person was registered two times.** 
To make this right I deleted him as a child in family 1 and as a husband in family 2. 
Then I tried to register him as a husband in family 2 again. 
The result was that the system made a new family with him and his wife, but his wife  kept the first family with all the children. 
I would be very happy if someone could help me with this problem.

**Comment by fisharebest** [comment]
> I have registered a person as a child in one family with his parents and sisters and brothers. Then I found that this child was the same person who was registered as a husband in another family.

If you created the same person twice, then the best solution is to merge the two records

Control panel -> Family tree -> Merge records

> The result was that the system made a new family with him and his wife

You can merge these two families.

**Comment by Sjonar** [comment]
Thank you for your quick response. I will try the solution you gave me. I
am using Webtrees and I am very satisfied with the program. I like the
reports, diagrams and lists. I have donated 20 GBP to Webtrees.

man. 29. mar. 2021 kl. 11:20 skrev Greg Roach ***@***.***>:

**Comment by fisharebest** [comment]
Thanks!
