### ISSUE TITLE
Auto complete in SOUR:PAGE

### ISSUE THREAD

**Issue by tronsmit** [fisharebest/webtrees#3815]
I miss the auto-complete functionality when entering the PAGE information for a source.

Many of PAGE citations are complex because of the URL in them, and I use the descriptive information at the beginning to make sure that I correctly cite the information (often there are many persons identified in one source) across different records.

In previous versions I was able to put only part of the surname and some extra information like a year to get to the correct citation (I think the new autocomplete logic in other entry fields requires the phrase to be exact, and not for example as in the 1.7 logic separated by other text).

**Comment by fisharebest** [comment]
It works for me.  Here is an example from the demo site.

![Screenshot 2021-03-30 at 20 48 05](https://user-images.githubusercontent.com/2306088/113047505-51015e00-9199-11eb-9a40-bed1c12f3205.png)

It shows the autocomplete suggesting three existing citations - based on typing `erd`.

**Comment by mpwt** [comment]
Is there a limit of 10 selection terms for auto-complete? This disturbs e.g. in the location selection a bit, if the desired location is not displayed and also cannot be scrolled.

**Comment by tronsmit** [comment]
> That is strange On demo site with android tablet logged in as editor and chrome browser I see same behaviour as on my laptop. For the source entry I get prompted for at least two characters, but not for the citation entry and no autocomplete suggestions ![Screenshot_2021-03-30-22-06-33-1](https://user-images.githubusercontent.com/10382564/113051199-01755f00-91a6-11eb-9428-4033f02b4886.png)

Update: deleted vendor folder on my site and rolled back to 2.0.13. Now the autocomplete (chrome browser) works on my site for PAGE entries, but still not on the demo site (<meta name="generator" content="webtrees 2.0.14">). using a different tab, but the same borwser instance.  

I'll check again once the version with updated email libraries get rolled out

**Comment by FrankWarius** [comment]
This is a bug in webtrees.min.js.
The behavior depends on pretty urls or normal urls.
The suggestion for the citiation depends on the source and is transfered in the "extra" parameter.
With normal urls we get 
`index.php?route=xxx?extra=src `
which is wrong and should be correct
`index.php?route=xxx&extra=src`
The fix in webtrees.min.js near line 528 could look like this: 
```
                 if (t.indexOf("?") > 0) {
                    extra = "&extra=";
                  } else {
                    extra = "?extra=";
                  }
                  return (
                    t.replace(/(%7B|{)query(%7D|})/, a) +
                    extra +
                    encodeURIComponent(o)
                  ); 
```
