### ISSUE TITLE
"Lineage-Linked" should be written in upper case in GEDCOM header 1 GEDC 2 FORM

### ISSUE THREAD

**Issue by Jefferson49** [fisharebest/webtrees#3816]
webtrees 2.0.13 exports GEDCOM form in GEDCOM header as follows: 
1 GEDC
2 VERS 5.5.1
2 FORM Lineage-Linked

The tool "GEDCOM Validator" throws the following warning:
"Use ALL-CAPS for the <GEDCOM_FORM> 'Lineage-Linked' for increased compatibility."

Specification found in GEDCOM 5.5.1:
"GEDCOM_FORM:=        {Size=14:20}
[ LINEAGE-LINKED ]
The GEDCOM form used to construct this transmission. There maybe other forms used such as
CommSoft's "EVENT_LINEAGE_LINKED" but these specifications define only the LINEAGELINKED
Form. Systems will use this value to specify GEDCOM compatible with these
specifications."

**Comment by fisharebest** [comment]
The GEDCOM 5.5.1 specification says that these values are not case-sensitive:

![Screenshot 2021-04-03 at 08 33 43](https://user-images.githubusercontent.com/2306088/113471892-5db2da00-9457-11eb-9a0e-a42eb39f312d.png)

IMHO, this is a bug in the validation tool...
