### ISSUE TITLE
Field for "Call number" is not shown when editing a repository

### ISSUE THREAD

**Issue by Jefferson49** [fisharebest/webtrees#3818]
When adding a new repository to a source, a field for entering the "Call number" is shown and can be filled (screenshot 1).

When editing an existing repository for a source (screenshot 2), the "Call number" field is not shown (screenshot 3). However, the field should also be shown during editing.

Remark: if a "Call number" has already been entered for a repository assigned to a source, it will also be shown during editing. The behavior above only shows up if no "Call number" is assigned to a repository of a source.

Observed with webtrees 2.0.15

### Screenshot 1:
![Screenshot New Repository](https://user-images.githubusercontent.com/81484983/113421177-e6cfff80-93ca-11eb-8f2c-708d088fb71b.jpg)

### Screenshot 2:
![Screenshot Edit Repository for Source](https://user-images.githubusercontent.com/81484983/113468665-d14ceb00-9447-11eb-94d8-36a243e3dcab.jpg)

### Screenshot 3:
![Screenshot Edit Repository](https://user-images.githubusercontent.com/81484983/113421186-ec2d4a00-93ca-11eb-9aad-17baa5a2b8c3.jpg)

**Comment by fisharebest** [comment]
This has already been fixed in the `develop` branch of the code.

**Comment by fisharebest** [comment]
I added this to the 2.1 milestone.  However, we will need a new minor release for PHP 8.0 compatibility, so this probably become the 2.2 release instead.

**Comment by fisharebest** [comment]
This fix has been merged into the main branch, and will be included in 2.1.0.
