### ISSUE TITLE
Another (minor) theme class suggestion

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#382]
Consider renaming function cssUrl() to something more generic as it's also useful as a base for loading js also provide a default value, something like

    public function baseUrl() {
        // return the directory containing the theme
        return WT_THEMES_DIR . basename(dirname(__FILE__)) . '/';
    }

**Comment by fisharebest** [comment]
In most (all?) frameworks, "base url" refers to URI for the application.  In webtrees' case, this would be `WT_SERVER_NAME . WT_SCRIPT_PATH`.

`assetsUrl()` would be a much better name, as this is the generic term for CSS+JS+PNG+etc.

However, it **really** ought to be a private function.  Nothing outside the theme needs to refer to it.

Currently, the lightbox module uses it (badly).  It ought to generate markup (e.g. an icon class?), which the theme should choose how to render.
