### ISSUE TITLE
Burial Errors

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#3824]
Using 2.1 dev.
Started getting errors on Burial:
![image](https://user-images.githubusercontent.com/5147603/113493665-53fc9700-9496-11eb-82a4-f50437ea2559.png)

Gedcom is:
![image](https://user-images.githubusercontent.com/5147603/113493668-5eb72c00-9496-11eb-8fc3-f7e79c90c2b6.png)

**Comment by makitso** [comment]
I understand that the CEME tag is no longer in GEDCOM 5.5.  However, if I check the tree for errors it finds none??

**Comment by makitso** [comment]
I used the Data fixes and the "Convert CEME tags to GEDCOM 5.5.1" to the Address tag.

**Comment by fisharebest** [comment]
We should be able to support commonly used custom tags.  I must have forgotten this one...
