### ISSUE TITLE
Re-import of exported geographic datas CSV does not import LATI and LONG figures, when "Delete all exisiting..." is set

### ISSUE THREAD

**Issue by github-bryld** [fisharebest/webtrees#3825]
As I was testing them by doing a data round-trip, I noticed, that the import wouldn't accept its own export for the LATI and LONG figures.

If _"Delete all existing geographic data before importing the file."_ is set to **"Yes"**, no LATI or LONG figures are imported.

On the other hand the script seems agnostic about whether commas or dots are used in the CSV

This has been tested on a database with existing place names from just one GEDCOM with the setting _Only update existing records_ and after emptying the MySQL table **_place_location_** first.

**Comment by fisharebest** [comment]
I am not sure this option is particularly useful.

It may be better to have a "delete unused locations" function.
