### ISSUE TITLE
calendar urls contain unescaped ampersand

### ISSUE THREAD

**Issue by tronsmit** [fisharebest/webtrees#3829]
ampersands are not replaced, for example, see in a fact record display
`<span class="date"><a href="https://dev.webtrees.net/demo-stable/index.php?route=%2Fdemo-stable%2Ftree%2Fdemo%2Fcalendar%2Fday&cal=%40%23DGREGORIAN%40&year=1895&month=DEC&day=14"`

**Comment by fisharebest** [comment]
I can't find this.

What is the URL of the page where you see this link?

**Comment by tronsmit** [comment]
Any fact page on the demo site that has a date field that is a link, eg.

https://dev.webtrees.net/demo-stable/index.php?route=%2Fdemo-stable%2Ftree%2Fdemo%2Findividual%2FI10014%2FHeinrich-XXIV-Count-Reuss-of-Ebersdorf

in page source view I see

![calendarUrl](https://user-images.githubusercontent.com/10382564/113581371-59d5b200-9627-11eb-93c6-e17b89f310ce.jpg)

Firefox highlights them in bold red, it seems to be from the year parameter to the end

**Comment by fisharebest** [comment]
Sorry - I was looking on the calendar page itself, not links to it.
