### ISSUE TITLE
baseTheme validation error

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#383]
(I know I mentioned this in an email to you but thought it should be recorded here)

functions menuChart.... (Ancestors, Descendants etc) add ids to the top level "li" element but they can be used multiple times on a page (popup menus in a chart box) so trigger validation errors

**Comment by fisharebest** [comment]
This has been a problem for a long time, and one I have been quietly ignoring ;-)

The menu objects already use classes for the "makeMenu" menus.  Once these have been eliminated, we can rename the "id" parameter to a "class" parameter.

There are a couple of calls to `$menu->setClass('active');` which are used for the current menu/theme.

I would have thought that the calling logic can easily be changed to supply "menu-language-fr active" in the constructor.

**Comment by fisharebest** [comment]
I've removed the offending menus from admin_media.

Still need to do the family-navigator and album modules.
