### ISSUE TITLE
Proposal: Have events to which a person is associated shown directly, not as "close relatives" events.

### ISSUE THREAD

**Issue by github-bryld** [fisharebest/webtrees#3831]
Reason:

1) People may well be associated with events entirely unrelated to their own close relatives, but those events will still show up in the "close relatives" area as things are right now (2.0.15).

2) When using the "close relatives view", a large number of close relatives events may bury the events to which the main person is actually associated.

Use case:

Many of my own ancestors served in farm households of more distant relatives. They would in census events appear as associated with these families, but their presence is likewise of interest as their own personal events (That's were they were at the time).

If having many siblings and using the "close relatives" view, their "timeline" on the Events tab gets blurry, while with "close relatives" filtered away  their "timeline" presents incompletely.

**Comment by ric2016** [comment]
I agree that these events don't belong in the 'Events of close relatives' category. I think a better solution is to have a separate checkbox for these type of events ([anyway that's how I implemented this in the extended tab](https://github.com/vesta-webtrees-2-custom-modules/vesta_personal_facts)).

**Comment by fisharebest** [comment]
I don't think we should show associated events the same as individual events.

I think it will be confusing to see several baptisms, marriages, etc. when these are events of other people.

So, I think we should keep the distinct styling (faded text).

But I agree that we should create a separate category/checkbox for these.

**Comment by github-bryld** [comment]
If associated events could be separated from "close relatives' events" by their own checkbox filter, that would also achieve, what I suggest in a satisfactory manner.
I'm unaware of proper GitHub etiquette, so not sure if this issue should be closed now or later (on implementation). Please close, if that's the thing to do now.
