### ISSUE TITLE
hightlight registered member's own branches on branches lists

### ISSUE THREAD

**Issue by ghezibde** [fisharebest/webtrees#3833]
As admin of the gedcom on my website, i daily gedt use of branches lists.
My own ancestors are highlighted in yellow so it's easy to remark my own branches.
Today i logged in with my two children accounts, registered as editors, and i discovered their branches (which are also mine) were not highlighted.I remember this worked fine some versions ahead.
I guess this should work the same for them and for me ?

**Comment by fisharebest** [comment]
Have you set the correct "Individual record" in their user accounts?

This is used to identify ancestors in the branches list.

**Comment by ghezibde** [comment]
In fact yes, first thing i checked when i discovered this. 
I checked the raw gedcom for his record (I2073) and everything's ok
I checked the raw gedcom for his FAMC (my FAMS) and everythings OK
BUT when i log in with his account and i go to his indi record, nothing even appears in his Families TAB (proposed to add father and mother). If i log in with my own account and go to his indi record / Families tab ... everythings ok
but he can find my record and i have no family shown in family tab but he can add a new spouse for me and he can see my sisters children (his cousins) linked to their famil.y
His accounts has no restrictions to immediate family.
I didn't edit my family for year until those days.
Real strange

**Comment by fisharebest** [comment]
Can you email me with the account names and I will investigate...

**Comment by ghezibde** [comment]
I found out why this occured.
I did set a restriction "1 RESN Confidential" to my children's mother/my wife ... and my children only have an editor status. I works as it should. This issue can be closed ... but i'd have a suggestion about this issue.
Thanks
