### ISSUE TITLE
Use sessionStorage?

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#384]
Just a thought - now we're into html5 how about using sessionStorage instead of cookies. It would save loading an aditional library (although I realise jQuery.cookie is tiny) and it seems the browser coverage is very good

**Comment by fisharebest** [comment]
I've never used sessionStorage.

We only use javascript-created cookies to remember the tab/sidebar states on the individual page.

Is there anything else that would benefit from this?

**Comment by ddrury** [comment]
It was the individual page I played with - seemed to work fine. I guess another possible use would be the pastefield stuff but I had a quick look and couldn't figure out what it was doing

**Comment by fisharebest** [comment]
> We only use javascript-created cookies to remember the tab/sidebar states on the individual page.

We also need to access these on the server, so I don't think session storage would work here.
