### ISSUE TITLE
Disable SSL check option in email service settings

### ISSUE THREAD

**Issue by conichonhaa** [fisharebest/webtrees#3842]
Is it possible to had an option to disable SSL certificate check in email settings

I successfully disable it in my EmailService.php file but erased on every update

`$transport->setStreamOptions(array('ssl' => array('allow_self_signed' => true, 'verify_peer' => false)));`

**Comment by fisharebest** [comment]
I am not sure it is a good idea to add a "disable security checks" feature.  Too many people will enable it at their first config problem.

Can't you add this certificate to the root-certificate store on your server?

e.g. search for: `add certificate to root [YOUR-OPERATING-SYSTEM-NAME]`

**Comment by conichonhaa** [comment]
You're right. It's just going to be difficult, I'm behind a reverse proxy and certificates are stored on this vm, I proxy_pass them to my different locations (mail server, sms server, webtrees...) on several ip.
I could export the certificate to the mail server and include it in trusted certificates but I don't know how to automate it every 90 days.....

**Comment by fisharebest** [comment]
There are docs available for creating modules.

You could add one with this method:

```php
public function boot(): void
{
    app()->bind(EmailService::class, MyEmailService::class);
}
```

Now, when webtrees asks for an `EmailService`, it gets a `MyEmailService`.

You'd then define `MyEmailService` something like this:

```php
class MyEmailService extends EmailService
{
    protected function transport(): Swift_Transport
    {
        $transport = parent::transport();
        $transport->setStreamOptions(array('ssl' => array('allow_self_signed' => true, 'verify_peer' => false)));

        return $transport;
    }
```

Note - for this to work, the `EmailService::transport()` would need to change from `private` to `protected`,  but this is a reasonable change to make in the core code.

**Comment by conichonhaa** [comment]
Does the minimum settings for a module as you described is enough ?
`use Fisharebest\Webtrees\Module\AbstractModule;`
`use Fisharebest\Webtrees\Module\ModuleCustomInterface;`
`use Fisharebest\Webtrees\Module\ModuleCustomTrait;`

Or do I need to call other modules

**Comment by fisharebest** [comment]
That should be enough.

If you get stuck, put your module in a public git repo, and I'll take a look.

**Comment by conichonhaa** [comment]
Thanks a lot

I tried something but not sure without errors :)))
[https://github.com/conichonhaa/ExtendedEmailService](url)

**Comment by fisharebest** [comment]
You module should:

* define the new service, based on the original
* define a module, which registers the new service as a replacement for the original
* create a module object, and return it

(Note, many examples combine steps 2 and 3).

Something more like this:

```
// Create a modified version of EmailService
class MyEmailService extends EmailService {
    function transport() {
        $transport = parent::transport();
        $transport->setStreamOptions(array('ssl' => array('allow_self_signed' => true, 'verify_peer' => false)));

        return $transport;    }
}

// Create a custom module
class MyClass extends AbstractModule implements ModuleCustomInterface {
    use ModuleCustomTrait;

    public function boot(): void {
        app()->bind(EmailService::class, MyEmailService::class);
    }

    // The other module functions go here (name, title, description, author, version, etc.).
}

// Create and return a module object.
return new MyClass();
```

PS - do not forget to change `private` to `protected` in the core code.  This change will be included in the next release.

**Comment by conichonhaa** [comment]
Thanks I'll try
Do I have to change private to protected on every occurence or one specific ?
![Screenshot_20210411_165331_com android chrome](https://user-images.githubusercontent.com/16390706/114309178-a5380680-9ae6-11eb-87f6-15277a3f56c5.jpg)

**Comment by slavkoja** [comment]
> PS - do not forget to change `private` to `protected` in the core code. This change will be included in the next release.
Please, can you separate the message creation and send methods too? To one can only override the message creation. I meet this in reminder module, where i want to add the List-Unsubscribe header...

**Comment by fisharebest** [comment]
> Do I have to change private to protected on every occurence or one specific ?

Just once - `EmailService::transport()`

> Please, can you separate the message creation and send methods too? To one can only override the message creation. I meet this in reminder module, where i want to add the List-Unsubscribe header...

Please create a new issue for this.

It becomes confusing and difficult to manage when many different things are added to one issue.

**Comment by conichonhaa** [comment]
I made the modification you make in EmailService.php and switched between private to protected
Do i have to restart something for changes ?
Because i wrote this
`<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Module\AbstractModule;
use Fisharebest\Webtrees\Module\ModuleCustomInterface;
use Fisharebest\Webtrees\Module\ModuleCustomTrait;
use Fisharebest\Webtrees\Services\EmailService;

// Create a modified version of EmailService
class MyEmailService extends EmailService {
    function transport() {
        $transport = parent::transport();
        $transport->setStreamOptions(array('ssl' => array('allow_self_signed' => true, 'verify_peer' => false)));

        return $transport;    }
}

// Create a custom module
class MyClass extends AbstractModule implements ModuleCustomInterface {
    use ModuleCustomTrait;

    public function boot(): void {
        app()->bind(EmailService::class, MyEmailService::class);
    }

    // The other module functions go here (name, title, description, author, version, etc.).
/**
     * How should this module be labelled on tabs, menus, etc.?
     *
     * @return string
     */
    public function title(): string
    {
        return 'EmailService disable';
    }
    
    /**
     * A sentence describing what this module does.
     *
     * @return string
     */
    public function description(): string
    {
        return 'This module disable EmailService SSL check';
    }
	
	public function customModuleAuthorName(): string
    {
        return 'Conichonhaa';
    }
}

// Create and return a module object.
return new MyClass();`

And then i got this error

`Fatal error: Declaration of MyEmailService::transport() must be compatible with Fisharebest\Webtrees\Services\EmailService::transport(): Swift_Transport in /var/www/html/modules_v4/ExtendedEmailService/module.php on line 12`

My line 12 is `function transport() {` in `// Create a modified version of EmailService
class MyEmailService extends EmailService {
    function transport() {
        $transport = parent::transport();
        $transport->setStreamOptions(array('ssl' => array('allow_self_signed' => true, 'verify_peer' => false)));

        return $transport;    }
}
`

**Comment by fisharebest** [comment]
The function declaration must match exactly.

Instead of `protected function transport() { ... }`
use `protected function transport(): Swift_Transport { ... }`

**Comment by conichonhaa** [comment]
Do you know what !!!! It works thanks a lot :)))) I uploaded changes to github

**Comment by conichonhaa** [comment]
> The function declaration must match exactly.
> 
> Instead of `protected function transport() { ... }`
> use `protected function transport(): Swift_Transport { ... }`

That's still `private function transport(): Swift_Transport ` and not `protected` about 1 year later

I change code manually after every update, just a bit annoying
