### ISSUE TITLE
Separate the message creation and send methods

### ISSUE THREAD

**Issue by slavkoja** [fisharebest/webtrees#3844]
Please, can you separate the email message creation and send methods, to one can only override the message creation or use it to get message and then customize values and use built-in send (and transport).

I meet this in reminder module, where i want to add the List-Unsubscribe header...

**Comment by fisharebest** [comment]
You want to add the header to all emails - or just some emails?

**Comment by slavkoja** [comment]
For all messages, i didn't play with it, it is only idea yet.

My PHP knowledge/skill are limited, but on quick look into send() method i see, that for now i need to do whole send() method by own, if i need to modify message. My idea is, that separating them i can choose to create whole message by own, or use webtree's method and modify the result only (add header), and then send it by built-in way.

**Comment by fisharebest** [comment]
What action do you take when you receive the unsubscribe link?

Update the user's account to change the "contact method" to stop sending mail?

**Comment by slavkoja** [comment]
No one-click unsubscribe, only link to webtrees's
