### ISSUE TITLE
v2.0.15: ASSO:RELA custom relationship is no longer translated

### ISSUE THREAD

**Issue by mpwt** [fisharebest/webtrees#3848]
In the current version, a custom relationship in ASSO:RELA is no longer translated.

<img width="740" alt="ASSO_RELA" src="https://user-images.githubusercontent.com/16311627/115115234-8c6e9b80-9f93-11eb-9a97-e6296e07e2dd.png">

**Comment by fisharebest** [comment]
How can webtrees translate custom text?  You could write anything in the `RELA` field.

**Comment by mpwt** [comment]
This issue was resolved years ago.: https://github.com/fisharebest/webtrees/issues/1144.

Up to v2.0.13, the custom translation of own designations worked under RELA. At least since v2.0.15 this suddenly no longer works.

At the moment I use the following additional RELA designations and translate them with a custom modul: 'earliest known ancestor', 'first known descendant', 'same person?', 'heir' and 'heiress'.

**Comment by mpwt** [comment]
I have added the additional RELA designations to GedcomCodeRela.php as a test and can also select them in the translation when I create a new one:

1 ASSO @I3073@
2 RELA same person? 

<img width="1142" alt="rela1" src="https://user-images.githubusercontent.com/16311627/117578063-d9561580-b0ec-11eb-93b9-60a86dd5c912.png">

However, after saving, no translation is displayed for the additional designations, although they are available.

<img width="926" alt="rela2" src="https://user-images.githubusercontent.com/16311627/117578073-e5da6e00-b0ec-11eb-8d69-26b56a247c2c.png">

**Comment by fisharebest** [comment]
> I have added the additional RELA designations to GedcomCodeRela.php

This is old code that is no longer used.

In 2.1, there will be an official way to modify these things.

Until then, you would modify https://github.com/fisharebest/webtrees/blob/main/app/Elements/RelationIsDescriptor.php

**Comment by mpwt** [comment]
Thank you. I tried it out and found the following:

It works for
2 _ASSO @I3073@
3 RELA same_person?

It doesn't work for
1 ASSO @I3073@
2 RELA same_person?

<img width="917" alt="rela3" src="https://user-images.githubusercontent.com/16311627/117584406-0aded900-b10d-11eb-81c2-d6915bc74f63.png">

The addition of GedcomCodeRela.php is used in the dropdown menu for RELA. Without the entry there, the additional relations are not displayed.

<img width="1142" alt="rela1" src="https://user-images.githubusercontent.com/16311627/117584466-83de3080-b10d-11eb-9984-5f7b0b3eb3cc.png">

**Comment by mpwt** [comment]
After changing the two files, the problem seems to be solved with the fix for https://github.com/fisharebest/webtrees/issues/3877. 

The earlier possible use of a free text under RELA and a custom translation I have to look at again now.

**Comment by TheDutchJewel** [comment]
> In 2.1, there will be an official way to modify these things.

What's the official way in 2.1 to modify these things?

**Comment by fisharebest** [comment]
You would create your own version of the `RelationIsDescriptor` class, with your own version of the `values()` function.

e.g. something like this

```
class MyRelationIsDescriptor extends RelationIsDescriptor {
  public function values(string $sex = 'U'): array {
     return parent::values($sex) + [
        'new-value-1' => I18N::translate('New value one'),
        'new-value-2' => I18N::translate('New value two'),
        'new-value-3' => I18N::translate('New value three'),
    ];
  }
}
```

Then create a module - there are plenty of examples and templates.

In your module's `boot()` method, you'd register it in all the same places that it is registered in `Gedcom.php`.

Look at `app/Modules/ResearchTaskModule.php` for an example of a module that registers tags.

**Comment by fisharebest** [comment]
There is already an example module for custom tags.
https://github.com/webtrees/example-module-custom-tags

Just add your `MyRelationIsDescriptor` class to it, and put your own content in the functions `customTags()`, `customSubTags()` and `customTranslations()`

**Comment by TheDutchJewel** [comment]
Thanks for the directions and tips.

I added the following line to the `use `section of `ExtendedRelationIsDescriptor.php`:
`use Fisharebest\Webtrees\Elements\RelationIsDescriptor;`

Then I added this code at the bottom of the file:

```
class MyRelationIsDescriptor extends RelationIsDescriptor {
    public function values(string $sex = 'U'): array {
        return parent::values($sex) + [
            'minister'    => I18N::translate('Minister'),
            'twin'        => I18N::translate('Twin'),
            'triplet'     => I18N::translate('Triplet'),
        ];
    }
    public function boot(): void
    {
        Registry::elementFactory()->registerTags([
            'INDI:ASSO:RELA'     => new RelationIsDescriptor(I18N::translate('Relationship')),
            'INDI:*:ASSO:RELA'   => new RelationIsDescriptor(I18N::translate('Relationship')),
            'INDI:*:_ASSO:RELA'  => new RelationIsDescriptor(I18N::translate('Relationship')),
            'FAM:*:_ASSO:RELA'   => new RelationIsDescriptor(I18N::translate('Relationship')),
        ]);
    }
    public function values(string $sex = 'U'): array {
        return parent::values($sex) + [
            'minister'    => I18N::translate('Minister'),
            'twin'        => I18N::translate('Twin'),
            'triplet'     => I18N::translate('Triplet'),
        ];
    }
}
```
But now I get this error:
`Fatal error: Cannot redeclare ExampleNamespace\MyRelationIsDescriptor::values() in D:\xampp\htdocs\webtrees-test\modules_v4\example-module-custom-tags\ExampleModuleCustomTags.php on line 177`

So I added a new namespace above the added class:
`namespace MyRelationIsDescriptorNamespace;`
but that doesn't solve the problem.

Any ideas how to solve this problem?

**Comment by fisharebest** [comment]
Your class has three functions.  The first and third are duplicates `values()`.

Delete one of these.

**Comment by TheDutchJewel** [comment]
Thank you! That solved the fatal error.

Now I have:
```
class MyRelationIsDescriptor extends RelationIsDescriptor {
    public function values(string $sex = 'U'): array {
        return parent::values($sex) + [
            'minister'    => I18N::translate('Minister'),
            'twin'        => I18N::translate('Twin'),
            'triplet'     => I18N::translate('Triplet'),
        ];
    }
    public function boot(): void
    {
        Registry::elementFactory()->registerTags([
            'INDI:ASSO:RELA'     => new RelationIsDescriptor(I18N::translate('Relationship')),
            'INDI:*:ASSO:RELA'   => new RelationIsDescriptor(I18N::translate('Relationship')),
            'INDI:*:_ASSO:RELA'  => new RelationIsDescriptor(I18N::translate('Relationship')),
            'FAM:*:_ASSO:RELA'   => new RelationIsDescriptor(I18N::translate('Relationship')),
        ]);
    }
}
```

But the new values are still not available in the associates drop-down menu...

**Comment by fisharebest** [comment]
You need two classes: MyRelationIsDescriptor and your module class.

The boot function needs to be in the module class, not the RelationIsDescriptor.

Now, when your module boots, it will register your custom tags.

**Comment by TheDutchJewel** [comment]
The [ExampleModuleCustomTags](https://github.com/webtrees/example-module-custom-tags) contains the file `ExampleModuleCustomTags.php`.

I modified the file as follows: :

Step 1. adding this code to the use section:
`use Fisharebest\Webtrees\Elements\RelationIsDescriptor;`

Step 2. changing the module class:
a. replacing the `customTags` function by this code:
```
    protected function customTags(): array
    {
        return [
            'INDI:ASSO:RELA'     => new RelationIsDescriptor(I18N::translate('Relationship')),
            'INDI:*:ASSO:RELA'   => new RelationIsDescriptor(I18N::translate('Relationship')),
            'INDI:*:_ASSO:RELA'  => new RelationIsDescriptor(I18N::translate('Relationship')),
            'FAM:*:_ASSO:RELA'   => new RelationIsDescriptor(I18N::translate('Relationship')),
        ];
    }
```
b.  replacing the `customTranslations` function by this code:

```
    public function customTranslations(string $language): array
    {
        switch ($language) {
            case 'nl':
                return [
                    'Minister' => 'Predikant',
                    'Triplet' => 'Drieling',
                    'Twin' => 'Tweeling',
                ];

            default:
                return [];
        }
    }
```
Step 3. adding this code at the bottom to create a new class:
```
class MyRelationIsDescriptor extends RelationIsDescriptor {
    public function values(string $sex = 'U'): array {
        return parent::values($sex) + [
            'minister'    => I18N::translate('Minister'),
            'twin'        => I18N::translate('Twin'),
            'triplet'     => I18N::translate('Triplet'),
        ];
    }
}
```
Everything seems to be correct with the instructions, but the new values are still not available in the associates drop-down menu.

What is wrong?

**Comment by TheDutchJewel** [comment]
Thank you very much!

Now it works fine.

I have learned a lot.

**Comment by TheDutchJewel** [comment]
Now the new values are not inserted alphabetically, but added at the bottom of the list.

How can this be sorted alphabetically?
