### ISSUE TITLE
Github - google bot error in log file

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#3861]
Class &#039;Sabre\VObject\Component\VCalendar&#039; not found …/app/Module/ShareAnniversaryModule.php:157 #0 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Module\ShareAnniversaryModule-&gt;handle() #1 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler-&gt;process() #2 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher-&gt;handle() #3 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process() #4

**Comment by fisharebest** [comment]
You probably need to update your `/vendor/` folder by running `composer install --no-dev`.

**Comment by makitso** [comment]
I am confused.  The process I follow is to do a pull from github, do testing on my dev machine and then rsync up to my production system, a shared host environment.  Several weeks ago I ran composer to get the dev environment to work.  Are you saying that I need to do this every time I do a pull from github, or are you saying I need to do this on my production system?

**Comment by fisharebest** [comment]
> Are you saying that I need to do this every time I do a pull from github

You need to run `composer install --no-dev` whenever there has been a change in the file `composer.lock`.

**Comment by makitso** [comment]
OK, did not know that, thanks

**Comment by makitso** [comment]
composer.lock date is 4/30/21 and composer install --no-dev has been run.  Still getting error

The supplied iCalendar datetime value is incorrect: 1798 …/vendor/sabre/vobject/lib/DateTimeParser.php:40 #0 …/vendor/sabre/vobject/lib/DateTimeParser.php(205): Sabre\VObject\DateTimeParser::parseDateTime() #1 …/vendor/sabre/vobject/lib/Property/ICalendar/DateTime.php(167): Sabre\VObject\DateTimeParser::parse() #2 …/vendor/sabre/vobject/lib/Property/ICalendar/DateTime.php(311): Sabre\VObject\Property\ICalendar\DateTime-&gt;getDateTimes() #3 …/app/Module/ShareAnniversaryModule.php(160): Sabre\VObject\Property\ICalendar\DateTime-&gt;offsetSet() #4 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Module\ShareAnniversaryModule-&gt;handle() #5 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler-&gt;process() #6 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher-&gt;handle() #7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process() #8 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #9 …/app/Http/Middleware/Router.php(151): Middleland\Dispatcher-&gt;dispatch() #10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router-&gt;process() #11 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher-&gt;handle() #12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules-&gt;process() #13 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher-&gt;handle() #14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes-&gt;process() #15 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher-&gt;handle() #16 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}() #17 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection-&gt;transaction() #18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process() #19 …/app/Http/Middleware/DoHousekeeping.php(74): Middleland\Dispatcher-&gt;handle() #20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process() #21 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher-&gt;handle() #22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process() #23 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher-&gt;handle() #24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process() #25 …/app/Http/Middleware/UseLanguage.php(70): Middleland\Dispatcher-&gt;handle() #26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process() #27 …/app/Http/Middleware/UseSession.php(71): Middleland\Dispatcher-&gt;handle() #28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process() #29 …/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher-&gt;handle() #30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process() #31 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher-&gt;handle() #32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar-&gt;process() #33 …/app/Http/Middleware/UseDatabase.php(117): Middleland\Dispatcher-&gt;handle() #34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process() #35 …/app/Http/Middleware/BadBotBlocker.php(222): Middleland\Dispatcher-&gt;handle() #36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process() #37 …/app/Http/Middleware/CompressResponse.php(75): Middleland\Dispatcher-&gt;handle() #38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process() #39 …/app/Http/Middleware/RegisterFactories.php(76): Middleland\Dispatcher-&gt;handle() #40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterFactories-&gt;process() #41 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher-&gt;handle() #42 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp-&gt;process() #43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process() #44 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher-&gt;handle() #45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process() #46 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher-&gt;handle() #47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process() #48 …/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher-&gt;handle() #49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process() #50 …/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher-&gt;handle() #51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process() #52 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher-&gt;handle() #53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process() #54 …/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher-&gt;handle() #55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment-&gt;process() #56 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #57 …/index.php(57): Middleland\Dispatcher-&gt;dispatch() #58 {main}

**Comment by makitso** [comment]
I looked through the log and some requests, from where I don't know, completed correctly and some generated a 500 error.
For example:
`66.249.79.109 - - [03/May/2021:00:44:12 -0700] "GET /tree/johannsen/anniversary-ics/X1190/4a9db8d931ec10ee863a49d93d53753c HTTP/1.1" 500 52154 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.84 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.79.111 - - [03/May/2021:02:13:01 -0700] "GET /tree/peters/anniversary-ics/I1505/4e014cf6fdacb8c4830612d693b49416 HTTP/1.1" 200 6988 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.84 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.79.111 - - [03/May/2021:02:31:37 -0700] "GET /tree/peters/anniversary-ics/I540/8dbf9e28242d0b38fdc7c0a581548bd3 HTTP/1.1" 500 52290 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.84 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.79.111 - - [03/May/2021:02:47:18 -0700] "GET /tree/johannsen/anniversary-ics/I1427/3326ed2e878285bbfff29b1f8fd267f5 HTTP/1.1" 200 6984 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.84 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
`
