### ISSUE TITLE
Control panel layout issue

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3866]
![demo](https://user-images.githubusercontent.com/104515/116438460-5f00d800-a846-11eb-8094-e83755670dc4.jpg)

**Comment by fisharebest** [comment]
I cannot reproduce this.  Can you look at the HTML and see what is happening?

**Comment by ddrury** [comment]
Ah, it only happens when the sitemaps module is disabled.

**Comment by ddrury** [comment]
views/admin/control panel

`<span class="fa-li"><?= view('icons/module') ?>` at lines 747/752 needs removing
