### ISSUE TITLE
Control panel / Geographic data and _LOC support

### ISSUE THREAD

**Issue by ro-la** [fisharebest/webtrees#3867]
I am using the Vesta Modules and the _LOC records for locations/shared places. But webtress (without Vesta modules) also gives some support for _LOC-tag. 

I was tidying up my place hierarchy and changed some of them in creating new places for the fact. When I looked in Control Panel/Geographic data i couldnt delete the places, which I changed before. After clicking on the tree in column "Facts and events" I  saw, that no person or family is conected to this place. I could delete these places only after export/import the GEDCOM. Later I realised, that I have also some "Locations" (or "Shared places" in the language of the Vesta modules). After deleting this locations (_LOC records) the red icon for deleting place in the Geographic data was displayed.

I am not sure, whether disallowing to delete a place, when a location with the same exists correct is. When yes, after export/import of GEDCOM it should behave in the same way. 

So my proposal is - on the place hierarhy display not only Individuals and Families, but also Locations. 
Or indicate in some way on the Geographic data, that a Location with this name exists.

Ladislav

**Comment by fisharebest** [comment]
> I am not sure, whether disallowing to delete a place, when a location with the same exists correct is

This is working correctly.  If you have a GEDCOM record with a `PLAC` that matches this location, then you cannot delete the location.
