### ISSUE TITLE
Administration theme layout query

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3874]
In resources/views/layouts/administration.phtml line 71 is  `<div id="content"></div>` and line 82 is `<?= $content ?>`

Shouldn't these be merged to be 
```
<div id="content">
  <?= $content ?>
</div>
```

**Comment by fisharebest** [comment]
The empty `<div>` is just the target for the "skip to content" link (for keyboard-only users).

e.g. press the tab key, and the link appears, press enter, and you'll navigate past the menus.

![Screenshot 2021-05-02 at 17 32 52](https://user-images.githubusercontent.com/2306088/116820346-6ee12a80-ab6c-11eb-8e88-1002d79a7797.png)
