### ISSUE TITLE
2.0.15 - Notes to associates are not displayed

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3876]
For marriages it is possible to add a note to the associates, but this note will not be displayed.

Is this a bug?

If not, where does that note appear?

**Comment by ro-la** [comment]
This is a very old feature/bug/enhancement request - there are at least this two open issues regarding this (or a very similar issue)
https://github.com/fisharebest/webtrees/issues/3074
https://github.com/fisharebest/webtrees/issues/1284

**Comment by fisharebest** [comment]
This is a duplicate of #1284
