### ISSUE TITLE
Individual with Associate does not show translation

### ISSUE THREAD

**Issue by PeBueGo** [fisharebest/webtrees#3877]
Individual with Associate does not show translation
Version 2.0.16 
php PHP Version 7.3.27-1~deb10u1

**Comment by fisharebest** [comment]
Works OK for me.  Here I add a witness, and then select another language (French).

1 OCCU Farmer
2 _ASSO @X1041@
3 RELA witness

![Screenshot 2021-05-04 at 19 58 28](https://user-images.githubusercontent.com/2306088/117055482-1ac47a80-ad13-11eb-82e6-7749d60ffa4e.png)

**Comment by PeBueGo** [comment]
I used 

associate - godchild
Verbundene Person - Patenkind

![Bildschirmfoto zu 2021-05-05 12-43-40](https://user-images.githubusercontent.com/16778457/117130241-13977e00-ada0-11eb-9312-8b7d33da3e49.png)

1 ASSO @I138@
2 RELA godchild
2 DATE MAR 1824

**Comment by wkitty42** [comment]
On 5/5/21 6:48 AM, PeBueGo wrote:
> 1 ASSO @i138@
> 2 RELA godchild
> 2 DATE MAR 1824

i note that greg's entry uses _ASSO whereas yours is using ASSO... perhaps this 
is the difference?
