### ISSUE TITLE
2.0.15 no autoupgrade to 2.0.16 on WinServer and PHP 8.0.5

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#3878]
I just migrated to PHP 8.0. autoupgrade to 2.0.15 with PHP 7.4 works fine but not with PHP 8.0.

https://dev.webtrees.net/build/latest-version.txt?w=2.0.15&p=8.0.5&o=w returns
  1.4.6|1.0.0|https://github.com/fisharebest/webtrees/releases/download/1.4.6/webtrees-1.4.6.zip

https://dev.webtrees.net/build/latest-version.txt?w=2.0.15&p=7.4.16&o=w returns
  2.0.16|2.0.0|https://github.com/fisharebest/webtrees/releases/download/2.0.16/webtrees-2.0.16.zip

**Comment by fisharebest** [comment]
PHP 8.0 requires webtrees 2.1.0 - but webtrees 2.1.0 not yet been released.

See the issue tracker for PHP8 issues.

If you can use `git` and `composer`, then you can checkout the `main` (2.1.0-dev) branch, and install the dependencies using `composer install --no-dev`.

**Comment by FrankWarius** [comment]
I have a 2. develop installation, which run on PHP 8.0 since 3 month.

My porduction envoirement runs stable under 8.0

**Comment by fisharebest** [comment]
For PHP8.0, you may now use [`webtrees-2.1.0-alpha.1`](https://github.com/fisharebest/webtrees/releases/tag/2.1.0-alpha.1)
