### ISSUE TITLE
Cannot edit "Media file" on a media objectt

### ISSUE THREAD

**Issue by ro-la** [fisharebest/webtrees#3880]
I cannot edit the "Media file"-fact of a media object - after clicking there is displayed a pop-up window for editing, but the whole page is greyed out and I cannot perform the edit
![obrázok_2021-05-06_170440](https://user-images.githubusercontent.com/60657963/117321111-250a8400-ae8d-11eb-993b-f405d64ddf1b.png)

On the demo it works OK.
![obrázok_2021-05-06_171013](https://user-images.githubusercontent.com/60657963/117322020-eb864880-ae8d-11eb-97a3-7acbda745836.png)

Is it possible that it is something similar to this: https://github.com/fisharebest/webtrees/issues/2935 ?

I cann edit "Media file" only using raw-gedcom edit. 

A second question - why editing Media file brings an "pop-up" window and all other edits looks like a normal window? I see no reason why this edit should look/work in other way than all other edits.

**Comment by fisharebest** [comment]
Look in your browser's error console for error messages?

**Comment by btreb** [comment]
I just ran into the same problem after updating to the latest release. The problem is seemingly not restricted to "Media file", but to all modal dialogs. At least for me, no errors are shown in the browser console.

**Comment by ro-la** [comment]
> I just ran into the same problem after updating to the latest release. The problem is seemingly not restricted to "Media file", but to all modal dialogs. At least for me, no errors are shown in the browser console.

Do you use also the Vesta Modules, or other custom modules? It is possible that my problem is caused by these modules. I will investigate more.

**Comment by ro-la** [comment]
It seems to be a problem related to the module ⚶ Vesta Classic Look & Feel.

**Comment by btreb** [comment]
> It seems to be a problem related to the module ⚶ Vesta Classic Look & Feel.

I can confirm that disabling the Vesta Classic Look & Feel Module resolves the issue.

**Comment by ric2016** [comment]
Fixed in latest Vesta release 2.0.16.0.3.

Remember to always check your custom modules first when reporting issues ;-)

**Comment by ro-la** [comment]
> Remember to always check your custom modules first when reporting issues ;-)

Sorry, I realised only later it would be good to try it without custom  modules :-)
