### ISSUE TITLE
Statistics bug: oldest mother is a man

### ISSUE THREAD

**Issue by BertKoor** [fisharebest/webtrees#3885]
Reported on behalf of forum user jvdmeer in forum thread 
https://www.webtrees.net/index.php/en/forum/help-for-2-0/35749-according-to-statitics-oldest-mother-is-an-man

The statistics page of the tree shows the oldest mother is a man.
Checked the data, it seems correct. Reimported the GEDCOM and it's still there.
So this could be a bug in the code. Example GEDCOM file is attached in the forum post.

**Comment by fisharebest** [comment]
[vdmeer-test2.zip](https://github.com/fisharebest/webtrees/files/6465772/vdmeer-test2.zip)

**Comment by fisharebest** [comment]
The GEDCOM file contains the following family record:

```
0 @F1586@ FAM
1 WIFE @I79@
1 CHIL @I4418@
```

This should say 

```
1 HUSB @I79@
```

You should edit or re-create family `F1586`

**Comment by fisharebest** [comment]
@BertKoor - thanks for investigate this.
