### ISSUE TITLE
Return value of Fisharebest\Webtrees\Services\RelationshipService::legacyNameAlgorithm() must be of the type string, null returned

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#3886]
I did some "Renumber" and "Check for errors" afterwards and got the following message "INDI X2992 has a FAMS link to X2259. X2259 does not have a link back to X2992." When I clicked on the first link I got the following error:

`Return value of Fisharebest\Webtrees\Services\RelationshipService::legacyNameAlgorithm() must be of the type string, null returned …/app/Services/RelationshipService.php:2146`

Under some circumstances it seems possible the method "legacyNameAlgorithm" could return "null" which is not defined as return type of the method.

**Comment by magicsunday** [comment]
I'm not able to access the individual anymore to change the raw gedcom data in anyway.

**Comment by magicsunday** [comment]
Some of my individuals are now three times in the database.

**Comment by magicsunday** [comment]
This commit only resolves rendering the fatal error. With this the individuals are accessible again, but it does not prevent the "Renumber" method from creating duplicates.

**Comment by fisharebest** [comment]
> By the way "Renumber" seems not to process the whole database, as I expected, just a part of the records

It renumbers any record which shares the same XREF in another tree.

**Comment by magicsunday** [comment]
I only have one tree. 😕

**Comment by magicsunday** [comment]
Is there a way to renumber the whole tree? Now I have some xref staring with X, some are still starting with F or I.

**Comment by vytux-com** [comment]
Export to gedcom, create a duplicate tree by importing the same gedcom. Then you should be able to do the export again from the second tree. 

Delete the second tree and import the second gedcom over the first tree.

That should work in theory and I think that was how I did that a while back.

**Comment by fisharebest** [comment]
FYI, I just fixed a bug which caused the "find duplicate XREFs" logic to find XREFs that were not used in other trees.
