### ISSUE TITLE
PHP 8.0.6 gedcom import failure

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3889]
webtrees 2.1 after https://github.com/fisharebest/webtrees/commit/2cc54ff867fb4801c90268da273ce9c42c85dd8f

Attempting to import a gedcom from the server results in error as attached (works with php 7.4)

![dump](https://user-images.githubusercontent.com/104515/118137635-54753f80-b3fd-11eb-8dd7-5d7dc21f9c84.jpg)

**Comment by fisharebest** [comment]
Did you update your `/vendor` folder with `composer install --no-dev`?

**Comment by ddrury** [comment]
Bugger - forgot. Sorry

**Comment by fisharebest** [comment]
FYI, the commit message for these changes always includes the word "vendor".
e.g. "Update vendor libraries".
