### ISSUE TITLE
Media Note URLs are not links - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3893]
In the media list
![image](https://user-images.githubusercontent.com/5202996/118399511-2e060d00-b666-11eb-9e16-5bf0e79daf72.png)

On media pages
![image](https://user-images.githubusercontent.com/5202996/118399542-57bf3400-b666-11eb-9d4d-58ea5cdaa2ff.png)
and
![image](https://user-images.githubusercontent.com/5202996/118399569-78878980-b666-11eb-94dc-384bac8a62f9.png)

Perhaps this is similar to #3642

**Comment by fisharebest** [comment]
This is a duplicate of #2600
