### ISSUE TITLE
Webclip and PWA shortcuts support

### ISSUE THREAD

**Issue by Tuetenk0pp** [fisharebest/webtrees#3902]
I recently tried to add a safatri shortcut on my iphone and I noticed that although it works, it has a black background instead of the (expected) white background and some shadows of the logo are cut off.

I would like to try and fix this myself using the https://realfavicongenerator.net/ but I have never done a PR before so we'll see how that goes 🙃 

I have tow questions:

1. Were can I find a webtrees logo with no cut off shadows with 260x260px or more? PNG, SVG, JPG are all fine.
2. In which .html file would the header information have to go?

**Comment by Tuetenk0pp** [comment]
Well it seems that this was already fixed with  #1123 and 52bcc40297e06e51c5cc74d5ddd66c750aefef51 ... so what now? Is it maybe theme-related?

**Comment by fisharebest** [comment]
> Were can I find a webtrees logo with no cut off shadows with 260x260px or more? PNG, SVG, JPG are all fine.

The original logo was only 192x192.  No larger version is available.

https://webtrees.net/resources/w-192x192.png

If you have photoshop or similar, the font is 

> In which .html file would the header information have to go?

Depending on the favicon, you can either just put a file with the right name in the root folder, or add a meta link to it in `resources/views/layouts/default.phtml`.  However, this file will shortly be re-factored into smaller files.

**Comment by fisharebest** [comment]
From the archives...

The logo "w" was created using:

* Font: "Anja Eliane"
* Base color: #2694e8
* Border 1px black
* Texture: smooth inner bevel, with highlights from left(270°), at a 35° elevation using color #c8bebf
* Drop shadow, gray, positioned down and to the right.

**Comment by Tuetenk0pp** [comment]
thanks!

**Comment by fisharebest** [comment]
This might not be fixed.

I have just borrowed an iPad - but it cannot connect to my development server, so I must commit the fix to the live site and test there...

**Comment by fisharebest** [comment]
OK - working now.
