### ISSUE TITLE
2.0.16 Untranslated string 'Count' in Find duplicates

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3906]
In **Control panel > Manage family trees > Find duplicates** there is an untranslated string **Count**.

Can this be added to the translations?

**Comment by fisharebest** [comment]
I cannot find this string.  Show me a screenshot.

**Comment by TheDutchJewel** [comment]
![afbeelding](https://user-images.githubusercontent.com/46184729/119469810-fffc8900-bd47-11eb-9807-0c001bb6209b.png)

**Comment by fisharebest** [comment]
This is how they are displayed on my site.

![Screenshot 2021-05-25 at 10 02 21](https://user-images.githubusercontent.com/2306088/119470501-4fd75200-bd40-11eb-95a6-22a15a07cf58.png)

Have you installed any custom modules?
Does the problem disappear if you disable these modules?

**Comment by TheDutchJewel** [comment]
You are right: the problem is caused by a custom module: 
[H&Hwt MultTreeView module](https://github.com/huhwt/huhwt-mtv).

There is a Dutch translation file missing, so I am going to add that.
