### ISSUE TITLE
Beta - Menu dropdown truncated on mobile devices

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#3908]
On mobile devices the main menu dropdown, on the left side, is truncated.  For RTL display it appears ok.

![image](https://user-images.githubusercontent.com/5147603/119679096-ef561c80-bdf4-11eb-9bd0-dcb4a1e73689.png)

![image](https://user-images.githubusercontent.com/5147603/119679023-e2392d80-bdf4-11eb-9d07-2d8073f2bb98.png)

**Comment by fisharebest** [comment]
Which device is this?  Which browser?

I only have access to a Samsung S20, which works OK - but my screen is wide enough for 4 icons on the top row, so my "search" menu is further to the left...

**Comment by makitso** [comment]
Greg, I have a Google pixel 4a and see the problem with Chrome and Firefox. But, not Brave which displays icons in 4 and 2 grid whereas the others are 3 and 3 grid.

**Comment by fisharebest** [comment]
This is an issue with bootstrap4.  It works fine in bootstrap5.

**Comment by fisharebest** [comment]
Bootstrap has just been upgraded from v4 to v5, and the problem is fixed.
