### ISSUE TITLE
"Pedigree" describes two different things

### ISSUE THREAD

**Issue by ro-la** [fisharebest/webtrees#3909]
Pedigree is used in two different ways, which cannot be translated with a single translation.
One meaning is  a name of a report and the second is for relationship to parents.

See also: https://bugs.launchpad.net/webtrees/+bug/971823

and current discussion 
https://www.webtrees.net/index.php/en/forum/8-translation/34168-an-other-string-for-pedigree 
https://www.webtrees.net/index.php/en/forum/8-translation/35790-menu-ahnentafel-falsche-uebersetzung-menu-pedigree-wrong-translation

**Comment by ro-la** [comment]
It seems that this is a duplicate issue to https://github.com/fisharebest/webtrees/issues/3839

**Comment by fisharebest** [comment]
The label for `INDI:FAMC:PEDI` was changed to "Relationship to parents" in #3839.
