### ISSUE TITLE
select box after name of husband and wife, when editing a marriage event

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3912]
When editing a marriage event there are checkboxes after the name of husband and wife. What is the function of these boxes? There is no hint available. And is it possible to have a bit more space between the name and the box, if the box is necessary?
![Screenshot (335)_LI](https://user-images.githubusercontent.com/6324175/120112731-4ce0c500-c177-11eb-800f-b0197a10a2b9.jpg)

**Comment by fisharebest** [comment]
This is fixed in 2.1 - but in 2.1 we do not display the husband/wife names.  This should be fixed.
