### ISSUE TITLE
External images are not used as portrait photos

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3913]
Images are not used as portrait photos if they are external. The media object is linked as INDI.OBJE on level 1.

![Screenshot (344)_LI](https://user-images.githubusercontent.com/6324175/120120532-1f5b4200-c19e-11eb-9887-5c40f7f653f7.jpg)

![Screenshot (343)](https://user-images.githubusercontent.com/6324175/120120534-22eec900-c19e-11eb-84db-956b975fd382.png)

**Comment by fisharebest** [comment]
The "primary" photo, which is used in chart-boxes and on the individual page needs to be cropped to a "portrait" aspect ratio.

We can't crop URLs - only local images.

We cannot even know that a URL points to an image.  It might point to some other sort of document.

So, the logic for choosing the primary image is to select the first local image file.

**Comment by fisharebest** [comment]
This is working as designed.
