### ISSUE TITLE
Request: Add current individual record to view/interface context

### ISSUE THREAD

**Issue by jon48** [fisharebest/webtrees#3915]
This is not a bug report, just a selfish request to expand slightly a couple of module/view interfaces.

In my custom modules, I have detected 2 interfaces where I could benefit from the current individual record being passed down, so that it is readily available for modules / views.
I completely acknowledge that it would not have any benefit for the core code (at least as it stands today), but provide slightly more flexibility for the custom modules, so just opening the discussion.

For both cases, I can use a workaround, retrieving that record from xref param of the request object, but this is rather bloated, whereas the relevant record is at arm's length.

- View `individual-page-names`:  
I am quite happy that the `individual-page` view has been recently broken down into different sub-views, so that we can amend a specific one. However, whereas the other views (`individual-page-menu`, `individual-page-images`, `individual-page-tabs`, `individual-page-sidebars`) are passed down the current `$record` object, the `individual-page-names` is the only one that is not. In my use case, I am overriding the view to add another section to the accordion (below the names and sex one), but need the current record for that new section.  
It should be a pretty harmless change here, inserting `'record' => $record,` : 
 https://github.com/fisharebest/webtrees/blob/50220ae3e3b73dff030c71ed5ac8c1e17c6437e9/resources/views/individual-page.phtml#L44

- Interface `ModuleSidebarInterface`  
Maybe a slightly more debatable one is adding the Individual to the `sidebarTitle` method in the ModuleSidebarInterface. That would allow to control a bit more the title for the current individual (for instance sex-contextualising the title, or display a different title based on some attributes of the individual - my use case), the same way the individual is passed to the `getSidebarContent` or `hasSidebarContent`. I say "more debatable" simply because it means a breaking change of the interface signature: not an issue for the core modules which all use the `ModuleSidebarTrait` trait (easily corrected), but could be for custom modules overriding that method.

**Comment by fisharebest** [comment]
> It should be a pretty harmless change here, inserting 'record' => $record, :

That is a sensible change.  It made me remember that I missed a bit of the refactoring.

The other parameters (`name_records`, `sex_records`) are actually views.
We should let `individual-page-names` fetch them - not generate them in code and pass them in.

> it means a breaking change of the interface signature

Instinctively, I want to avoid changing the signature.  But there are

* many breaking changes (mostly removing deprecated code) from 2.0 to 2.1
* few modules that use this interface

so perhaps it will be OK.

**Comment by jon48** [comment]
Thank you Greg for the changes, much appreciated.
