### ISSUE TITLE
“On this day” block repeats entries

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#3918]
Went to UniGen.us without logging in, on 1 June 2021.
Clicked “show more” at the bottom of the On This Day block.
Attached partial image of results.
Verified that the database has only one Marcus King and only one Frank Carter.
Verified that each of these has only one BIRT record.
![AA13E792-C8D6-435E-8F1E-2C8DAE9411E6](https://user-images.githubusercontent.com/5910274/120354390-3c376880-c2b7-11eb-8fc9-aa698db5d815.jpeg)

**Comment by WGroleau** [comment]
Perhaps related to the fact the dates are a range, not specific.

**Comment by fisharebest** [comment]
> Perhaps related to the fact the dates are a range, not specific.

Both ends of a date range are considered separately - so you get June twice.

Probably just need a `DISTINCT` on a SELECT query.

**Comment by fisharebest** [comment]
This is featuring twice, because there are two different dates that match.

Therefore these are unique combinations of individual/date.

I think this is therefore working as designed.
