### ISSUE TITLE
2.0.16 - Login page shows untranslated Show button for password

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3920]
My login page is in Dutch, but on the right side of the password field is a button with an untranslated text: Show.

![image](https://user-images.githubusercontent.com/46184729/121166196-272b7e00-c851-11eb-90c0-56432b663c7b.png)

Can that text be added to the translations?

**Comment by vytux-com** [comment]
That looks like a browser button rather than webtrees is your browser language also in Dutch or English?

**Comment by TheDutchJewel** [comment]
My browser are only in Dutch.

Tested with Edge and Firefox (latest versions).

**Comment by fisharebest** [comment]
This is the `hideshowpassword` library.  I will need to check whether it supports localisation.

**Comment by TheDutchJewel** [comment]
Thank you for the info.

Because the text is apparently not part of webtrees, this topic can be closed

**Comment by jon48** [comment]
Looking at the options of the `hideShowPassword` function, there is actually a way to translate those labels, through the `states.shown.toggle.content` / `.attr.title` and `states.hidden.toggle.content` / `.attr.title` attributes (not very well documented I reckon).

So, for instance, changing in the `login-page.phtml` view, that can be achieved by :

```js
$("#password").hideShowPassword({show: "infer", innerToggle: true, states: {
    shown: { toggle: { content:  '<?= e(I18N::translate('Hide')) ?>', attr: { title: '<?= e(I18N::translate('Hide password')) ?>'}}},
    hidden : { toggle: { content:  '<?= e(I18N::translate('Show')) ?>', attr: { title: '<?= e(I18N::translate('Show password')) ?>'}}} 
}});
```
There are several instances of that chunk of code, so there may be some refactoring possible. 

The defaults could also be overridden instead through the below, but I don't know where it would be best placed, as it would need the I18N context (which `webtrees.js` does not have).

```js
$.extend(true, $.fn.hideShowPassword.defaults, {
  states: { 
        shown: { toggle: { content:  '<?= e(I18N::translate('Hide')) ?>', attr: { title: '<?= e(I18N::translate('Hide password')) ?>'}}},
        hidden : { toggle: { content:  '<?= e(I18N::translate('Show')) ?>', attr: { title: '<?= e(I18N::translate('Show password')) ?>'}}} 
  }
});
```

**Comment by fisharebest** [comment]
@jon48 - could we pick up the text from `data-hide="…" data-show="…"` attributes on the `<input>` element?

This is the technique we use for other JS libraries - e.g. datatables.

**Comment by fisharebest** [comment]
...or simpler still, could we use unicode symbols instead of text?

There must be ones for the standard "eye" and "eye with a slash"...

**Comment by jon48** [comment]
> could we pick up the text from data-hide="…" data-show="…" attributes on the <input> element?

Yes, that is completely possible. We could add the following in `webtrees.js`:
```js
$('input[type=password]').each(function() {
  $(this).hideShowPassword("infer", true, {
    states: { 
          shown: { toggle : { content: this.dataset.hideText, attr: { title: this.dataset.hideTitle, 'aria-label' : this.dataset.hideTitle }  } },
          hidden: { toggle : {  content: this.dataset.showText, attr: { title: this.dataset.showTitle, 'aria-label' : this.dataset.showTitle } }}
    }
  });
});
```
And then each password `input` would be : 

```html
<input ... type="password" data-show-text="<?= e(I18N::translate('Show')) ?>" data-show-title="<?= e(I18N::translate('Show password')) ?>" data-hide-text="<?= e(I18N::translate('Hide')) ?>" data-hide-title="<?= e(I18N::translate('Hide password')) ?>">
```

> could we use unicode symbols instead of text?

I like that idea. I found a character for the open eye (U+1F441 &#128065; ), but could not find one for the "eye with a slash".
I tried to play as well with the FontAwesome icons (`fa-eye` and `fa-eye-slash`), but it introduces a misalignment which I could not figure out...
Those "symbol" solutions are fine for the visual aspect, however they do not offer a solution for translating the `title` and `aria-label` attributes, which are still probably required for complying with accessibility requirements.

**Comment by fisharebest** [comment]
I have tried this.  It works well for the text in the button.  But I can't get it to change the text in the `title`.  e.g.

![Screenshot 2021-07-17 at 14 51 44](https://user-images.githubusercontent.com/2306088/126039794-a7d43764-78ee-4a86-b053-a51bb6058c07.png)

**Comment by jon48** [comment]
Just to rule out the obvious, have you added the relevant translations entries to the German language file (assuming this was your testing locale)?

The following ones do not currently exist in the main code: 

```
'Hide' => 'Cacher',
'Show password' => 'Afficher le mot de passe',
'Hide password' => 'Masquer le mot de passe',
```

When added, I have the expected behaviour (in French, and German - tentative translations - below):

![image](https://user-images.githubusercontent.com/5150782/126045919-dba0b32f-38a7-4843-abe2-e330597329e2.png)

![image](https://user-images.githubusercontent.com/5150782/126046095-bb97fd26-7363-4c14-9da1-44b3f369418f.png)

**Comment by jon48** [comment]
I have pushed the code which is working for me on the `hotfox/password-translate` branch of my fork, if that can provide any useful comparison : https://github.com/jon48/webtrees/commit/e5c8dad37c9158234d6a718de3b4380acd1cbbfd

**Comment by fisharebest** [comment]
Thanks Jon.  I must have mis-typed something...
