### ISSUE TITLE
Question to Historic Events

### ISSUE THREAD

**Issue by Lars1963** [fisharebest/webtrees#3922]
@fisharebest I'm working on some new core historic events modules (German and Worldwide) . I've two questions for you:

1. How do I code the small flags in the title? I haven't figured that one out.

2. I'd like to rename the existing Modules for better oversight/grouping. Just like you e. g. did with `LanguageName`. I'm not sure, whether to start the names with `Events`, `Historic` or `Timelists`? I think `HistoricEvents` results in too long names. What do you suggest? 

THX Lars

**Comment by fisharebest** [comment]
1: The flags are emoji (unicode icons).  You can copy/paste them from https://emojipedia.org/flags/

2: I used the prefix `LanguageName` to avoid potential conflicts in the future.  e.g. "Spanish language" and "Spanish surname tradition".  I don't think we have the same risk with "PresidentsOfTheUnitedStates:, etc.

**Comment by Lars1963** [comment]
THX

As I said, renaming only should have the purpose of better oversight in the folder. I like structur, maybe I'm a little autistic 🥴
