### ISSUE TITLE
Documentation suggested change

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3923]
Webtrees.net home page, latest releases section says 

> webtrees 2.1, when it is released, will support PHP 8.

However the development code is using functions that only php 8 supports so I suggest the line should read

> webtrees 2.1, when it is released, will **require** PHP 8.

**Comment by fisharebest** [comment]
Which functions?  AFAICT, we are only using ones supported by https://github.com/symfony/polyfill-php80

**Comment by ddrury** [comment]
missed that - sorry
