### ISSUE TITLE
Editing a media object that is external

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3925]
After creating a media object that has a URL instead of a local filename and then attempting to edit it, the edit page thinks the URL is a filename (see attached)
![demo](https://user-images.githubusercontent.com/104515/122018934-38c5d600-cdbb-11eb-9031-4ccae0c351cf.jpg)

**Comment by fisharebest** [comment]
Showing two entries for the file is a bug, which I've fixed.

I can't reproduce the "missing file" warning.  It should only be shown for local files - i.e. not containing `://` in the name.

**Comment by ddrury** [comment]
The "missing file" warning was down to me!
