### ISSUE TITLE
Make history modules selectable by users

### ISSUE THREAD

**Issue by Lars1963** [fisharebest/webtrees#3927]
_Originally posted by @hartenthaler in https://github.com/fisharebest/webtrees/issues/3924#issuecomment-863614426_

As discussed, it might be a good idea to make the history modules selectable by the user

`Maybe a special menu in the control panel would help the admin to manage more and more historic data files. But there is a deeper question behind: who decides about which historic data is of interest for the users. At the moment the admin selects the historic data files he thinks are of interest for his tree, but maybe a user from China knows Chinese history very well and likes to see Chinese history events even if all events in the tree are located in Europe because he likes to compare what happened in China at the time the events in the tree happened. Maybe the users should be able to select the history files, but the normal user will not find and use this possibility, so we should not make it too flexible.`

**Comment by fisharebest** [comment]
I'm not sure this is necessarily a good idea.

Korean events are only likely to be of interest to Korean speakers, and only included on Korean sites.
Translating these into 60 other languages is a lot of effort.

For some events (perhaps in countries with multiple official languages), then it may make sense for the module to supply a version for each language - but not as translatable strings.

**Comment by magicsunday** [comment]
I would be more in favor of making these special history modules available as separately installable extensions and removing them completely from the Webtrees core.

**Comment by fisharebest** [comment]
Historic events are now shown only for the current language.

i.e. events in French are only shown when the current language is French.

Where applicable (countries with multiple official languages), the module can provide separate events for each language.

**Comment by fisharebest** [comment]
> As discussed, it might be a good idea to make the history modules selectable by the user

I think the selection of *all* modules (including history modules) should be a matter for the site-admin, not for users.
