### ISSUE TITLE
beta release -- log errors

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#3929]
Not sure if their related but:
Apache Log file: [Sat Jun 19 04:13:13.407651 2021] [fcgid:warn] [pid 31014:tid 139911516485376] [host skatekey.net] [client 194.153.113.223:61894] PHP Fatal error: Uncaught ErrorException: Trying to get property 'name' of non-object in /var/www/html/sk/skatekey.net/resources/views/layouts/default.phtml:69

webtrees log:

`syntax error, unexpected &#039;version&#039; (T_STRING) …/resources/views/browserconfig-xml.phtml:1 #0 …/app/View.php(286): Fisharebest\Webtrees\View-&gt;render() #1 …/app/Http/RequestHandlers/BrowserconfigXml.php(41): Fisharebest\Webtrees\View::make() #2 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\BrowserconfigXml-&gt;handle() #3 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler-&gt;process() #4 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher-&gt;handle() #5 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process() #6 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #7 …/app/Webtrees.php(237): Middleland\Dispatcher-&gt;dispatch() #8 …/app/Http/Middleware/Router.php(149): Fisharebest\Webtrees\Webtrees::dispatch() #9 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router-&gt;process() #10 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher-&gt;handle() #11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules-&gt;process() #12 …/app/Http/Middleware/LoadRoutes.php(74): Middleland\Dispatcher-&gt;handle() #13 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes-&gt;process() #14 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher-&gt;handle() #15 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}() #16 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection-&gt;transaction() #17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process() #18 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher-&gt;handle() #19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process() #20 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher-&gt;handle() #21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process() #22 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher-&gt;handle() #23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process() #24 …/app/Http/Middleware/UseLanguage.php(69): Middleland\Dispatcher-&gt;handle() #25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process() #26 …/app/Http/Middleware/UseSession.php(75): Middleland\Dispatcher-&gt;handle() #27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process() #28 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher-&gt;handle() #29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process() #30 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher-&gt;handle() #31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar-&gt;process() #32 …/app/Http/Middleware/UseDatabase.php(117): Middleland\Dispatcher-&gt;handle() #33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process() #34 …/app/Http/Middleware/BadBotBlocker.php(223): Middleland\Dispatcher-&gt;handle() #35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process() #36 …/app/Http/Middleware/CompressResponse.php(74): Middleland\Dispatcher-&gt;handle() #37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process() #38 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher-&gt;handle() #39 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp-&gt;process() #40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process() #41 …/app/Http/Middleware/HandleExceptions.php(89): Middleland\Dispatcher-&gt;handle() #42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process() #43 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher-&gt;handle() #44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process() #45 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher-&gt;handle() #46 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process() #47 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher-&gt;handle() #48 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process() #49 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher-&gt;handle() #50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process() #51 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #52 …/app/Webtrees.php(237): Middleland\Dispatcher-&gt;dispatch() #53 …/app/Webtrees.php(224): Fisharebest\Webtrees\Webtrees::dispatch() #54 …/index.php(44): Fisharebest\Webtrees\Webtrees-&gt;httpRequest() #55 {main}`

**Comment by fisharebest** [comment]
Does your server have `short_open_tags` enabled in php.ini?

**Comment by makitso** [comment]
Yes,
![image](https://user-images.githubusercontent.com/5147603/122646566-a08a6280-d0d4-11eb-9bea-dd854d926536.png)
