### ISSUE TITLE
Enhancement: ask for review

### ISSUE THREAD

**Issue by Lars1963** [fisharebest/webtrees#3931]
@fisharebest 
Greg, is it possible to add the possibilty to your repo to ask for review by specific persons on PR's?

**Comment by fisharebest** [comment]
I thought this was enabled automatically.

If not, then I can't see how/where to enable it.

**Comment by Lars1963** [comment]
Nope, its not possible for me. I now also why:
` Note: Pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository.  `

see: 11 https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review

**Comment by fisharebest** [comment]
I guess just add a comment saying that the PR is ready for review, etc.

I get notifications for all the comments.

**Comment by Lars1963** [comment]
Yeah, that's seems sadly to be only way
