### ISSUE TITLE
Name leak of private INDI

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#3934]
I selected a cousin who is still living, saved a clipping of ancestors, and set privacy to visitors.

In my settings, this should hide all information about the person.

And, indeed, for that person, the NAME line was not included in the clipping.ged.

But it did include 
```
1 SOUR @WEBTREES@
2 PAGE https://UniGen.us/tree/HHH/individual/P966/**name-of-living-person**

```
If the name is omitted from the URI, the P966 still gets the person (**IF** logged in and related) to the person.

It also included the gender—not sure whether that should be hidden

**Comment by fisharebest** [comment]
When we create an export from the clippings cart, we include a source linking back to the original site.

This feature was inherited from phpGedView.  I'm not sure that it is particularly needed or useful.

Perhaps we should just remove it...

**Comment by WGroleau** [comment]
Linking back to the site is useful (in my opinion).
But if NAME Given /Surname/ is private, then the name should also be omitted from the URI, especially since the link works without it.

**Comment by HonkXL** [comment]
I never understood the reason for showing the name in die URI. It was easier in webtrees 1.x to habe only the INDI in the URI.

**Comment by wkitty42** [comment]
On 6/22/21 5:49 AM, Thomas Weiland wrote:
> I never understood the reason for showing the name in die URI. It was easier in 
> webtrees 1.x to habe only the INDI in the URI.

IIRC, because they might get renumbered or the ID prefix letter changed... names 
generally don't get changed...

**Comment by slavkoja** [comment]
> ... names generally don't get changed...

Are you sure? My name changed (including birth certificate) two times yet...

Or consider simple mistake/typo, when creating record...

**Comment by HonkXL** [comment]
I rename individuals very often: sometimes they have double names but I have only a single family name. Or it was written wrong, or I have different writings of a name in different documents. The only thing that does not change is the ID. And: the ID does not contain any sensitive data, so it is no problem to use just the ID in a public link that should not become public. But it's a problem to leak the name in the link.

**Comment by fisharebest** [comment]
> I never understood the reason for showing the name in die URI

URLs that contain the search term are believed to feature higher in google's search results.

The name part of the URL is not important for webtrees.
If the name changes, the URL will be updated, and the old URL will redirect to the new URL.

> But it's a problem to leak the name in the link.

The code which generates the URL has the same access as the current user - so it will only show the name if you have permission to see it.

This bug exists because YOU have permission to see the name, but you are creating a file for somebody who does not have permission to see it.

**Comment by wkitty42** [comment]
On 6/22/21 10:36 AM, Slavko wrote:
>     ... names generally don't get changed...
> 
> Are you sure? My name changed (including birth certificate) two times yet...
> 
> Or consider simple mistake/typo, when creating record...

both of these are examples of why i specifically included the term "generally" ;)
