### ISSUE TITLE
Tree MEDIA_DIRECTORY preference issue on new install

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3943]
The default value for the MEDIA_DIRECTORY is 'media/', however it is not saved to the database,
Control Panel - Manage media seems to read this value from the database and as it doesn't exist neither the media directory or media are shown

By setting the tree preference to anything (xxxx for example) and then changing it back to media forces the value to be saved to the database. Control Panel - Manage media then works.

**Comment by fisharebest** [comment]
If we call `$tree->getPreference()`, and a value isn't set, then a default is used.
https://github.com/fisharebest/webtrees/blob/main/app/Tree.php#L223
So, each tree will function correctly.

But the control panel isn't aware of this default.
