### ISSUE TITLE
My page meta data

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3944]
`app\Http\RequestHandlers\TreePage.php` passes parameters `meta_robots & meta_description` to `resources\views\tree-page.phtml`, however these values are not used in this view.

**Comment by fisharebest** [comment]
The template `tree-page.phtml` doesn't use them.  But we don't call `view('tree-page', [...])` directly.

We call `ViewResponseTrait::viewResponse('tree-page', [...]')` - which passes all the parameters to the "layout" template `views/layouts/default.phtml` (as well as passing them to 'tree-page').

This will then add them to the `<head></head>`.

See https://github.com/fisharebest/webtrees/blob/2.0.16/app/Http/ViewResponseTrait.php#L47-L48
