### ISSUE TITLE
Custom module help text

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#395]
Any suggestions as to how custom modules should provide help text now that the facility has been removed from help-text.php?

**Comment by JustCarmen** [comment]
You should switch to inline help-text. You can use the p-tag for that:
< p class="small text-muted" >

**Comment by JustCarmen** [comment]
I have several of my modules already converted to the new admin theme.

Look in the repo's for an example: https://github.com/JustCarmen?tab=repositories

**Comment by fisharebest** [comment]
The plan is to remove **all** popup help text, not just modules.  I've completed the admin pages, and will do the others soon. [*]

Nobody ever finds or reads the help text.  You can tell from the questions that are asked on the forums.  As a result, the help text is neglected, and frequently out-of-date.

I think the family-tree privacy page is a good example of the sort of thing we should do.  All the explanations are shown in the form, so they can be seen together.

A lot of the text needs to be rewritten for clarity and consistency, but I can do this later.

[*] We *may* need a few help pages for things like date and place formats.

**Comment by alvin101** [comment]
There is a system called frontaccounting that uses a help button that shows on all pages.  When the button is pushed you get a popup just for that page. If you have edit or admin rights you can edit this popup page like a wiki.  This makes it very handy when you want to tell your staff how to do something or add and keep notes, etc. for that page.

Of all the help page systems that I know of I like this one the best.

Just a thought.  A user edit help system.

**Comment by fisharebest** [comment]
The usability experts where I work tell me that if a system needs help text, then it is badly designed.  The solution should be to improve the desgin, not to add more help text.

**Comment by alvin101** [comment]
Well, you are correct, however I think that a user customization, (help/text) is a good design in any system where you work with other users.  As an admin I like to tell our users how we do things in our system.

I think that any user customization in any system is a good design.
