### ISSUE TITLE
Control panel - Family tree - Privacy error

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3950]
Under privacy restrictions click add. Error listing under All facts and events

![demo](https://user-images.githubusercontent.com/104515/124955836-4adc1280-e00f-11eb-8fee-cc9988aeb945.jpg)

**Comment by fisharebest** [comment]
I've fixed this - but it is part of a larger change, which isn't finished just yet.

**Comment by fisharebest** [comment]
Should be fixed in the latest code.
