### ISSUE TITLE
Census Czech Republik 1921 

### ISSUE THREAD

**Issue by ro-la** [fisharebest/webtrees#3953]
Based on the online released Census sheets fromm MZA Brno (for example [here](https://www.mza.cz/scitacioperaty/digisada/detail/849?image=226203010-000001-000003-001229-000445-02-BO1146-02800.jp2)) I propose to change the file https://github.com/fisharebest/webtrees/blob/main/app/Census/CensusOfCzechRepublic1921.php as follows:

```
    public function columns(): array
    {
        return [
            new CensusColumnNull($this, 'Ř.č.', 'Řadové číslo'),
            new CensusColumnSurname($this, 'Příjmení', 'jméno rodinné'),
            new CensusColumnGivenNames($this, 'Jméno', 'Jméno (křestni)'),
            new CensusColumnRelationToHead($this, 'Vztah', ''),
            new CensusColumnSexMZ($this, 'Pohlaví', ''),
            new CensusColumnNull($this, 'Stav', 'Rodinný stav'),
            new CensusColumnBirthDayDotMonthYear($this, 'Narození', 'Datum narození'),
            new CensusColumnBirthPlace($this, 'Rodiště', 'Rodná obec, Soudní okres, Země'),
            new CensusColumnNull($this, 'Bydlí od', 'Od kdy bydlí zapsána osoba v obci?'),
            new CensusColumnNull($this, 'Přísluší', 'Domovské právo'),
            new CensusColumnNull($this, 'Národnost', 'Mateřský jazyk'),
            new CensusColumnReligion($this, 'Vyznání', ''),
            new CensusColumnNull($this, 'Gramotnost', 'Znalost čtení a psaní'),
            new CensusColumnOccupation($this, 'Povolání', 'Druh povolání'),
            new CensusColumnNull($this, 'Postavení', 'Postavení v zaměstnání'),
            new CensusColumnNull($this, 'Podnik', ''),
            new CensusColumnNull($this, 'Měl povolání 1914', ''),
            new CensusColumnNull($this, 'Povolání 1914', 'Druh povolání dne 16. července 1914'),
            new CensusColumnNull($this, 'Postavení 1914', 'Postavení v zaměstnání dne 16. července 1914'),
            new CensusColumnNull($this, 'Poznámka', ''),
        ];
    }

```

I dont know who the author of this Census definition was (@jpretired ?) and perhaps in other parts of Czechoslovakia were used other sheets. 
So my question - is it OK to change the definition or is it better to create a new census definition (something like CensusOfCzechRepublic1921Moravia.php)?

Ladislav

**Comment by jpretired** [comment]
I am the author of the Czech 1921 Census definition. I made it on the basis of the same census sheet layout as @ro-la mentions. I only left out the less important items as (in my opinion) there has been little space for displaying the resulting markdown table row of corresponding shared note in individual's census fact.
I do not object to the proposed changes.
