### ISSUE TITLE
Search has stopped working for visitors on my production site - wt 1.8.0 dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3955]
Top search **for visirors** gives
/home/amitys/www.amitys.com/webtrees/includes/session.php:204 /home/amitys/www.amitys.com/webtrees/app/Individual.php:1116 Trying to access array offset on value of type null #0 /app/Individual.php:1116 ErrorException("/home/amitys/www.amitys.com/webtrees/app/Individual.php:1116 Trying to access array offset on value of type null") #1 /app/GedcomRecord.php:611 addName() #2 /app/Family.php:334 getAllNames() #3 /app/GedcomRecord.php:732 getAllNames() #4 /app/Functions/FunctionsDb.php:453 getFullName() #5 unknown:unknown Fisharebest\Webtrees\Functions\{closure}() #6 /app/Functions/FunctionsDb.php:461 array_filter() #7 /app/Controller/SearchController.php:247 searchFamilyNames() #8 /app/Controller/SearchController.php:187 generalSearch() #9 /search.php:24 __construct()

Phonetic and Anvanced search give
/home/amitys/www.amitys.com/webtrees/includes/session.php:204 /home/amitys/www.amitys.com/webtrees/app/Individual.php:1116 Trying to access array offset on value of type null #0 /app/Individual.php:1116 ErrorException("/home/amitys/www.amitys.com/webtrees/app/Individual.php:1116 Trying to access array offset on value of type null") #1 /app/GedcomRecord.php:611 addName() #2 /app/GedcomRecord.php:643 getAllNames() #3 /app/Individual.php:1054 getPrimaryName() #4 /app/Functions/FunctionsPrintLists.php:366 getPrimaryParentsNames() #5 /app/Controller/SearchController.php:530 individualTable() #6 /search.php:308 printResults()

The General search by a visitor and searces by users seem to work.

**Comment by fisharebest** [comment]
This is caused by running webtrees 1.7 using PHP 7.4.
It only works with PHP 5.6 - 7.3

I have tried to set up your site using different versions of PHP for different folders.  Maybe this isn't working correctly.  Let me look again.

**Comment by fisharebest** [comment]
OK - should be working now.
