### ISSUE TITLE
Error when I selected theme justright - wt 2.1.0-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3958]
I get the following error when I selected in my future test system theme justlight.

How can I sign out?

ErrorException: filemtime(): stat failed for /home/amitys/future.amitys.com/app/../public/favicon-196.png in /home/amitys/future.amitys.com/app/Helpers/functions.php:62 Stack trace: #0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}() #1 /home/amitys/future.amitys.com/app/Helpers/functions.php(62): filemtime() #2 /home/amitys/future.amitys.com/modules_v4/jc-theme-justlight/resources/views/layouts/head/favicons.phtml(6): asset() #3 /home/amitys/future.amitys.com/app/View.php(189): include('/home/amitys/fu...') #4 /home/amitys/future.amitys.com/app/View.php(286): Fisharebest\Webtrees\View->render() #5 /home/amitys/future.amitys.com/app/Helpers/functions.php(202): Fisharebest\Webtrees\View::make() #6 /home/amitys/future.amitys.com/modules_v4/jc-theme-justlight/resources/views/layouts/default.phtml(37): view() #7 /home/amitys/future.amitys.com/app/View.php(189): include('/home/amitys/fu...') #8 /home/amitys/future.amitys.com/app/View.php(286): Fisharebest\Webtrees\View->render() #9 /home/amitys/future.amitys.com/app/Helpers/functions.php(202): Fisharebest\Webtrees\View::make() #10 /home/amitys/future.amitys.com/app/Http/ViewResponseTrait.php(54): view() #11 /home/amitys/future.amitys.com/app/Http/RequestHandlers/UserPage.php(90): Fisharebest\Webtrees\Http\RequestHandlers\UserPage->viewResponse() #12 /home/amitys/future.amitys.com/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\UserPage->handle() #13 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process() #14 /home/amitys/future.amitys.com/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle() #15 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process() #16 /home/amitys/future.amitys.com/app/Http/Middleware/AuthLoggedIn.php(50): Middleland\Dispatcher->handle() #17 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthLoggedIn->process() #18 /home/amitys/future.amitys.com/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle() #19 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process() #20 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #21 /home/amitys/future.amitys.com/app/Webtrees.php(239): Middleland\Dispatcher->dispatch() #22 /home/amitys/future.amitys.com/app/Http/Middleware/Router.php(149): Fisharebest\Webtrees\Webtrees::dispatch() #23 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process() #24 /home/amitys/future.amitys.com/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle() #25 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process() #26 /home/amitys/future.amitys.com/app/Http/Middleware/LoadRoutes.php(74): Middleland\Dispatcher->handle() #27 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process() #28 /home/amitys/future.amitys.com/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle() #29 /home/amitys/future.amitys.com/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}() #30 /home/amitys/future.amitys.com/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction() #31 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process() #32 /home/amitys/future.amitys.com/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle() #33 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process() #34 /home/amitys/future.amitys.com/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle() #35 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process() #36 /home/amitys/future.amitys.com/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle() #37 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process() #38 /home/amitys/future.amitys.com/app/Http/Middleware/UseLanguage.php(69): Middleland\Dispatcher->handle() #39 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process() #40 /home/amitys/future.amitys.com/app/Http/Middleware/UseSession.php(75): Middleland\Dispatcher->handle() #41 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process() #42 /home/amitys/future.amitys.com/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle() #43 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process() #44 /home/amitys/future.amitys.com/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle() #45 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process() #46 /home/amitys/future.amitys.com/app/Http/Middleware/UseDatabase.php(117): Middleland\Dispatcher->handle() #47 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process() #48 /home/amitys/future.amitys.com/app/Http/Middleware/BadBotBlocker.php(223): Middleland\Dispatcher->handle() #49 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process() #50 /home/amitys/future.amitys.com/app/Http/Middleware/CompressResponse.php(74): Middleland\Dispatcher->handle() #51 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process() #52 /home/amitys/future.amitys.com/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle() #53 /home/amitys/future.amitys.com/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process() #54 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process() #55 /home/amitys/future.amitys.com/app/Http/Middleware/HandleExceptions.php(89): Middleland\Dispatcher->handle() #56 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process() #57 /home/amitys/future.amitys.com/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle() #58 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process() #59 /home/amitys/future.amitys.com/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle() #60 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process() #61 /home/amitys/future.amitys.com/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle() #62 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process() #63 /home/amitys/future.amitys.com/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle() #64 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process() #65 /home/amitys/future.amitys.com/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #66 /home/amitys/future.amitys.com/app/Webtrees.php(239): Middleland\Dispatcher->dispatch() #67 /home/amitys/future.amitys.com/app/Webtrees.php(226): Fisharebest\Webtrees\Webtrees::dispatch() #68 /home/amitys/future.amitys.com/index.php(44): Fisharebest\Webtrees\Webtrees->httpRequest() #69 {main}

**Comment by jon48** [comment]
The `ErrorException: filemtime(): stat failed for` message typically occurs when the file does not exist, and indeed the `public/favicon-196.png` has been removed in the 2.1-dev code (commit 571594c0), but the JustLight theme has not integrated that change yet, and [still references it](https://github.com/JustCarmen/webtrees-theme-justlight/blob/27fc2c582e9c1d2fe1f08a1f4a51ece24605d7f5/resources/views/layouts/head/favicons.phtml#L6).

Nothing much to fix in webtrees itself, and I would disable the theme for the time being, until it has been made compatible with the 2.1 branch. 

More generally, I would be careful with enabling custom modules on different minor versions (2.x to 2.y) than the ones they have been "certified" against, unless the developer has explicitly encouraged it or has created a matching development branch, as those upgrades are usually used to introduce breaking changes.

**Comment by melizaa** [comment]
I did manage to inactivate the justlight theme.

**Comment by fisharebest** [comment]
This is an error in the JustLight theme.

It will only cause a problem if you are using it with a dev version of webtrees.

(Stable versions do not check file-modification times).
