### ISSUE TITLE
Put another field to verify when the password will be changed

### ISSUE THREAD

**Issue by yako1984** [fisharebest/webtrees#3959]
Put another field "Repeat password", to verify when the password will be changed.

![Screenshot_2](https://user-images.githubusercontent.com/67491705/126069172-23ea0431-5397-498b-83bd-de4fe30c8512.jpg)

**Comment by fisharebest** [comment]
We had this previously.

We replaced it with the "hide/show" password feature.

Most (all?) user experience experts prefer this approach.

https://www.nngroup.com/articles/stop-password-masking/
https://www.nngroup.com/articles/checklist-registration-login/

**Comment by yako1984** [comment]
OK, thank you!
