### ISSUE TITLE
Suggestion re modules_v4

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3963]
Now the modules have been moved to their own repository, remove modules_v4 from .gitignore file

**Comment by jon48** [comment]
:thinking:

Are you sure this is what we want to do?
IMHO, it makes sense for the whole folder to be git-ignored, now that the example modules have been moved away. 
With the latest commit, any custom module copied in the folder will show as git untracked files, which is a bit confusing (and potentially lead to unwanted committed files) when testing/troubleshooting the core code with some custom modules/themes enabled.

I would expect the `modules_v4` folder to be treated in a similar way as the `data` one, i.e. a "user folder", which content is entirely ignored by the version control.

**Comment by fisharebest** [comment]
@jon48 - you're right.  I'll revert this.
