### ISSUE TITLE
N’th cousins calculations are wrong for Italian

### ISSUE THREAD

**Issue by AlexKalopsia** [fisharebest/webtrees#3964]
Hi, 

today I was investigating an issue with WebTrees where the N’th cousins calculation is seemingly wrong. I initially thought this was a translation issue, but then in `Functions.php` I found:

```
/* I18N: Note that for Italian and Polish, “N’th cousins” are different from English “N’th cousins”, and the software has already generated the correct “N” for your language. You only need to translate - you do not need to convert. For other languages, if your cousin rules are different from English, please contact the developers. */
```

This custom Italian solution is just wrong (and confirmation can be found in [this](https://www.webtrees.net/index.php/en/forum/8-translation/32098-traduzioni-in-italiano#66929) forum post from 3 years ago.

From [Wikipedia](https://it.wikipedia.org/wiki/Cugino):

> Traditionally, in Italy people define their "degree" of N’th cousins in relation to their descendance from the uncles:
> 
> The 1st cousin is the child of an uncle.
> The "procugino" is the child of a great-uncle or, alternatively, the child of a cousin.
> The 2nd cousin is the child of a cousin's child or, alternatively, the child of a great-uncle's child. In other words, the child of a 1st cousin.
> The 3rd cousin is the child of a 2nd cousin or, alternatively, the child of a great-great-uncle's child.
 
With this in mind, here is what the current calculation is doing:

![cDvWIpW](https://user-images.githubusercontent.com/2306088/126605962-42101e5e-a7c8-436c-aa6b-acfe02884305.png)

Note how clearly wrong it is, adding an extra generation makes the graph go from 3rd to 2nd, and not the other way around.

I am a bit surprised that the rest of the italian webtrees community accepted this, but it would really be great if this could be rectified. I can contribute to the code myself, if that is deemed necessary. 

_Note that I created a similar post on the forum, but only realized now that it might have been better to create an issue here._

**Comment by fisharebest** [comment]
The current logic was created by an Italian who is also a well-known open-source developer.
So, it would be good to get more feedback from other Italian users.

----------

We have a new system for generating relationships.  Instead of translations, each language defines its own relationships.

See some code here:
https://github.com/fisharebest/webtrees/blob/main/app/Module/LanguageEnglishUnitedStates.php
https://github.com/fisharebest/webtrees/blob/main/app/Module/LanguageFrench.php

See the test scripts here:
https://github.com/fisharebest/webtrees/blob/main/tests/feature/RelationshipNamesTest.php

We should migrate the Italian relationships to the new system.

**Comment by AlexKalopsia** [comment]
Hi, I am wondering if there is any update on this and, even better, if I can meaningfully contribute to fix this. If so, how would you advice to proceed_

Thanks

**Comment by AlexKalopsia** [comment]
So, after ivnestigating, I am certain the original problem underlined in the first post is the result of a translation copy-paste mistake. 

```
#: app/Services/RelationshipService.php:1223
msgctxt "grandfather’s sibling’s granddaughter"
msgid "second cousin"
msgstr "cugina di 2° grado"

#: app/Services/RelationshipService.php:1227
msgctxt "grandfather’s sibling’s grandson"
msgid "second cousin"
msgstr "cugino di 3° grado"

#: app/Services/RelationshipService.php:1219
msgctxt "grandfather’s sister’s grandchild"
msgid "second cousin"
msgstr "cugino/a di 3° grado"

#: app/Services/RelationshipService.php:1211
msgctxt "grandfather’s sister’s granddaughter"
msgid "second cousin"
msgstr "cugina di 3° grado"

#: app/Services/RelationshipService.php:1215
msgctxt "grandfather’s sister’s grandson"
msgid "second cousin"
msgstr "cugino di 3° grado"

...
```

As you can see, "grandfather’s sibling’s **granddaughter**" was translated correctly as "cugina di 2° grado", but "grandfather’s sibling’s **grandson**" (no difference from the male counterpart) was translated as "cugino di 3° grado". 

After this mistake, all the other relationships of second cousins also mistakenly got translated to 3° grado. 

I initially thought of creating a PR, but I've seen that the translation is handled on Weblate. I have fixed these lines and also translated an extra 100ish missing lines to bring Italian to 100%. 

I don't know if there is anything else I should do other than waiting for the new translation to get pulled automatically.

**Comment by fisharebest** [comment]
> I initially thought of creating a PR, but I've seen that the translation is handled on Weblate. I have fixed these lines and also translated an extra 100ish missing lines to bring Italian to 100%.

Thanks!

> I don't know if there is anything else I should do other than waiting for the new translation to get pulled automatically.

The translations get pulled automatically, every day (approximately).

I have just manually synchronised things.  Your changes are now in the source code:

https://github.com/fisharebest/webtrees/commit/bd518d4bf2158ccf9baec7e8d90687c30fe0862e

> I guess I will start working on LanguageItalian.php and then create a PR for review.

That would be great!  If you need help, please ask.
