### ISSUE TITLE
Custom tag on Individual Facts and Events tab

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3965]
The previously used custom tag _MILI appears as INDI:_MILI in red on the facts tab. (Have solved by using custom fact) but I suppose this is a bug.

UPDATE: This applies to all custom tags

**Comment by fisharebest** [comment]
Control panel -> Modules -> Custom GEDCOM tags

The tag `_MILI` was created by the phpGedView project.  I can't find evidence of it being used by other applications.

Other applications (Brothers Keeper and Family Tree Maker) provide `_MILT` (Military Service).

If it isn't already, then perhaps this module ought to be enabled by default.

**Comment by ddrury** [comment]
> perhaps this module ought to be enabled by default.

Probably not. I can't remember what software I was using when I created the records. I guess that as people find the tags in red It'll become more obvious which should be enabled by default.

**Comment by fisharebest** [comment]
Actually, it isn't enabled.  To reduce upgrade issues, I will enable it.
