### ISSUE TITLE
Latest dev code causes 500 error on thumbnails

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#3969]
Loaded a clean database with 2.0.16.  Standard no pretty URL.

I added an image to John Doe and it work correctly, e.g. Slideshow showed thumbnail and individual page showed thumbnail.

I then updated to the latest dev branch on github. I then updated the Vendor folder via composer.
Now, the Slideshow and individual page both show red box with 500 number.
Apache Error.log has no entries.
Apache Access.log shows:
::1 - - [25/Jul/2021:13:26:50 -0700] "GET /index.php?route=%2Ftree%2Ftree1%2Findividual%2FX1%2FJohn-DOE HTTP/1.1" 200 9802 "http://localhost/index.php?route=%2Ftree%2Ftree1%2Findividual%2FX1%2FJohn-DOE" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36"
::1 - - [25/Jul/2021:13:26:50 -0700] "GET /public/favicon-32.png?v=1615472259 HTTP/1.1" 200 2003 "http://localhost/index.php?route=%2Ftree%2Ftree1%2Findividual%2FX1%2FJohn-DOE" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36"
Chrome browser console shows:
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.

**Comment by makitso** [comment]
For whats its worth,
For the standard 2.0.16 release gives a thumbnail address of:
http://localhost/index.php?route=%2Ftree%2Ftree1%2Fmedia-download&xref=X2&fact_id=db469b680c72814a947b7f2798df90a7&disposition=inline**&mark=0**
The latest dev code gives:
http://localhost/index.php?route=%2Ftree%2Ftree1%2Fmedia-download&xref=X2&fact_id=db469b680c72814a947b7f2798df90a7&disposition=inline**&mark=1**

**Comment by makitso** [comment]
Interesting:  The latest dev code does show the thumbnail after logging in, both on the individual page and the Slideshow.  However, not for guests.

**Comment by wkitty42** [comment]
On 7/25/21 4:52 PM, Rob Peters wrote:
> Interesting: The latest dev code does show the thumbnail after logging in, both 
> on the individual page and the Slideshow. However, not for guests.

is your john doe test user alive? ;)

**Comment by makitso** [comment]
> is your john doe test user alive? ;)
The John Doe is the default provided by the webtrees install, born in 1860.

**Comment by fisharebest** [comment]
With the 500 thumbnail, there will be some HTTP headers with extra info.

Use your browser dev tools to see them.

e.g. 'x-thumbnail-exception'

**Comment by ddrury** [comment]
I had this problem as well see https://github.com/guzzle/guzzle/issues/2824#issuecomment-883971577.

We need the following versions
```
    "guzzlehttp/guzzle": "^7.3.0",
    "intervention/image": "^2.6",
```

composer.json has the following line:  `"intervention/image": "^2.5",`

but because of the caret (I think) composer.lock causes the correct version to be installed

I don't know why by running composer update a second time fixed it.
