### ISSUE TITLE
webtrees 2.1 Robots.txt?

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3972]
For webtrees 2.1 is a robots.txt still necessary, if so is there an example?

**Comment by fisharebest** [comment]
If you use "pretty URLs", then a `robots.txt` will be generated automatically.

If not, then visit `<yoursite>/index.php?route=robots.txt` and copy/paste the contents into an actual file called `robots.txt`.

**Comment by ddrury** [comment]
`<yoursite>/index.php?route=robots.txt` redirects to "My Page"
