### ISSUE TITLE
Update url returns wrong version

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3976]
`https://dev.webtrees.net/build/latest-version.txt` is returning

`1.4.6|1.0.0|https://github.com/fisharebest/webtrees/releases/download/1.4.6/webtrees-1.4.6.zip`

**Comment by fisharebest** [comment]
This URL takes additional parameters, and will return different versions of webtrees as required.

Your request didn't include a PHP version, so you get the oldest known webtrees version.
With newer versions of PHP, you'll get 1.7.x or 2.0.x (and soon 2.1.x)

**Comment by ddrury** [comment]
This is with 2.1-dev

**Comment by fisharebest** [comment]
> `https://dev.webtrees.net/build/latest-version.txt` is returning

This is the expected response from that URL.
But webtrees never requests that URL.  It will request something like

`https://dev.webtrees.net/build/latest-version.txt?w=2.0.14&p=7.4.0`

which gives the response

`2.0.16|2.0.0|https://github.com/fisharebest/webtrees/releases/download/2.0.16/webtrees-2.0.16.zip`.

If you are setting `p=8.0` or `p=8.1` then there is not yet a supported version for that version of PHP.

**Comment by ddrury** [comment]
Oh, of course 2.1 is not yet released!!

**Comment by fisharebest** [comment]
> Oh, of course 2.1 is not yet released!!

Exactly.  See #3878
