### ISSUE TITLE
No date field on birth edit form

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#3979]
Birth on INDI page had no date.  Clicked edit and the form had no field to enter the date.
GEDCOM was 
```
1 BIRT
2 PLAC Quincy, Adams Co., Illinois, USA
3 _LOC @X912@
2 SOUR @S14@
3 PAGE http://UniGen.us/?itemid=91
```
webtrees 2.0.16

**Comment by fisharebest** [comment]
I see the `DATE` field, but it is near the bottom of the form.

In 2.1, the fields are sorted, so date and place are at the top.

**Comment by fisharebest** [comment]
I can' reproduce this, and it is working on a number of sites - including the demo site.

If you can reproduce this, please create a new issue with details.
