### ISSUE TITLE
Create tree ignores Tree Name

### ISSUE THREAD

**Issue by vytux-com** [fisharebest/webtrees#398]
When creating a new tree the value specified in tree name is ignored and the default value of "My Family Tree" is always used.

**Comment by fisharebest** [comment]
Are you using the lastest code.  I thought this was fixed last night.

https://github.com/fisharebest/webtrees/commit/482ad87b1148ff1fe94f3d41d74336018af6edd0

**Comment by vytux-com** [comment]
Yes just updated again with the two new commits and it's still doing this. Editing the name after creation is OK
