### ISSUE TITLE
URI in SOUR:PAGE 

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#3980]
If GEDCOM for an INDI contains 
```
2 SOUR @S70@
3 PAGE 348 - http://books.google.com/books?id=E0gDAAAAYAAJ&printsec=titlepage#PPA348
```
the href generated is in the form
`https://unigen.us/tree/HHH/individual/P1748/348%20-%20http://books.google.com/books?id=E0gDAAAAYAAJ&printsec=titlepage#PPA348`

**Comment by FrankWarius** [comment]
fixe in DEV (https://github.com/fisharebest/webtrees/issues/3973(
