### ISSUE TITLE
Batch updating media filename doesn't update the filename on the server

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#3981]
It is possible with the search & replace function to batch update media filenames 1 FILE *.jpg

But that is a pretty useless action since the filename on the server doesn't get updated.

Shouldn't that be part of the batch update function when renaming files?

**Comment by fisharebest** [comment]
The search/replace works on the entire GEDCOM record, using `preg_replace()` or `str_replace()`.

It does not consider the context or details of what it is changing.

It is also impossible to know if we are editing filenames to make the correct.

To implement this, we would need a dedicated module to edit filenames.  (We already have a dedicated module for renaming place names).

**Comment by fisharebest** [comment]
I think there are too many difficult problems.

This is not an interactive process, so we cannot stop at every record to ask "What should we do here".

For example, what if we need to rename a file, but the destination filename already exists.

**Comment by fisharebest** [comment]
I don't think this will be possible.

Suppose you have a batch-update which changes this

```
0 @X123@ OBJE
1 FILE foo.jpeg
1 FILE bar.jpeg
```

into this

```
0 @X123@ OBJE
1 FILE bar.jpeg
1 FILE foo.jpeg
```

We cannot know if we are re-ordering the media, or renaming `foo.jpeg` to `bar.jpeg`
