### ISSUE TITLE
Title of popup window is wrong: "Edit a media file"

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3982]
This window should be titled: "Edit a media object and file".

![Screenshot (438)_LI](https://user-images.githubusercontent.com/6324175/128625322-18d02316-cba2-4d4d-a0d9-47cad36fa6d3.jpg)

**Comment by fisharebest** [comment]
A media object (`0 OBJE`...) can contain many media files (`1 FILE` ...).

Here, we are editing just one file within a media object.

So, the title seems correct to me...

**Comment by hartenthaler** [comment]
No, it is not about one or more files. Here, we are editing a media file and a media object in one window. The folder and filename are related to the file. Title and type are related to the object. So the title of this window should give a reference not only to "edit a media file". The reason for this issue was a discussion with a webtrees user showing that for him it was not clear that media files and media objects are different things. So I suggest being here more precise.

**Comment by fisharebest** [comment]
>  The folder and filename are related to the file. Title and type are related to the object.

No they are not.

Each file has its own title and type.  These can be different.  e.g.

```
0 @m1@ OBJE
1 FILE interview.mp4
2 TITL Interview with Greg Roach
2 FORM mp4
1 FILE interview.text
2 TITL Transcript of interview
2 FORM txt
```

**Comment by hartenthaler** [comment]
All these elements in your last post are related to the media object defined as "0 @m1@ OBJE": FILE, TITL, FORM, So if you are editing those elements in webtrees, this is "Edit a media object" and not "Edit a media file". So the title of the window is wrong - at least for me.

There is another thing at the server, I call this "file". You are editing the file using a program like Photoshop. You cannot use webtrees for this task. You can edit the name of the file using Filezilla or webtrees. You can select the folder name in the directory of your server using webtrees. But you cannot delete a folder using webtrees. So the editing of a file by using webtrees is limited. Therefore I think that it is important to be precise: "editing a media object" (GEDCOM) is different from "editing a media file" (server). In the window which is shown in the screenshot, both are possible: editing the file name and selecting the folder is related to the file on the server, editing the title and media type (and filename) is related to the media object.

I hope this does not look like quibbling from your sight. For you and me there is no doubt about how these things are working, but another user may think that "editing a file" will allow him not only to change a filename but also to delete directory folders or do other file manipulations, but webtrees is not designed to edit files.

**Comment by fisharebest** [comment]
A media object contains

* one or more media files
* notes
* sources
* privacy restriction
* last-change info 

This edit form is just editing the fields for one of the media files.

> I hope this does not look like quibbling from your sight.

Of course not.

Maybe we are editing "media file details", not a "media file"?

**Comment by hartenthaler** [comment]
Ok, "Edit media file details" is a good idea. "Editing media object" would be wrong, too. Because it is only about editing some of the media object information fields. To be more precise it is "Editing media file related details of a media object", but this is too long and still not perfect because editing the file name is both object and file related. So "Edit media file details" is good because it is short and vague enough..

**Comment by fisharebest** [comment]
This request is to change the title from "Edit media file" => "Edit media file details".

But if we do that, we should change "media file" to "media file details" everywhere else.

<img width="980" alt="Screenshot 2022-04-09 at 10 16 44" src="https://user-images.githubusercontent.com/2306088/162565162-de6f89fc-cb00-4e8f-9b44-77fa9d9f41cc.png">

I think this adds unnecessary words.

I will keep this as it is.
