### ISSUE TITLE
Question: use of filter options in a tab (user modul "extended family")

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3984]
I was asked to add a filter possibility for my module "[extended family](https://github.com/hartenthaler/hh_extended_family)" (see [issue](https://github.com/hartenthaler/hh_extended_family/issues/18)). Since the last release of this module, it is possible for the admin to select/filter "only male/female and/or dead/alive persons" using a control panel option. But the idea behind the filter options is that a user (and not the admin) should be able to set the filter options (similar it is offered in the general search function of webtrees).

![Screenshot (438)_LI](https://user-images.githubusercontent.com/6324175/129101272-db2d7aa2-b912-4952-b0d5-7519162b5f43.jpg)

I have not found the webtrees code which is related to the filter function of the general search menu; so I cannot use this as an example. I don't know how to bring the filter buttons into operation, so I need hints or help.

My idea is that if a user clicks on one of the filter buttons a function of my module is called and I can trigger a reload of the tab based on the filtered results. I assume that the filter possibilities in the general search menu are working differently (all information is already there and is made visible or invisible only).

- Is my idea ok? Which function is necessary so that a filter button calls a function of my module and how do I trigger a reload of the tab with actualized information? Or should I provide always all possible combinations of filtered information and a click on a filter button makes some information visible and other information invisible?
- Following my idea I see the need to store the information which filter combination was set by the user. But how? Options selected by the admin in the control panel are stored in the database, but how to store transient information for a user? Using cookies?

Maybe you can push me in the right direction? I'm willing to learn but bringing the filter bar for my module into life is beyond my possibilities at the moment.

**Comment by jon48** [comment]
The logic for filtering in the general search tables (or tables in general) is contained in the respective `resources/views/list/**-table.phtml`, for instance for individual tables, [this is the code](https://github.com/fisharebest/webtrees/blob/d1da5ba430762bd82a5d57bc40552492431d11ee/resources/views/lists/individuals-table.phtml#L85-L99), however you cannot reuse it the same way as it is linked to the underlying datatables.

In your case, given that generating the whole tab or the filtered tab will probably not make a huge differences in terms of performance, I would not bother reloading the tab, but only use Javascript to show/hide the relevant data.

There are several ways to implement, but for instance, keeping the inspiration of using the `data-` attribute to have a generic JS code, you can for instance, define your buttons with (the important part being the addition of  `hh-extended-filter-button` class, the `data-filter-type` and `data-filter-value` attributes on the `input`)

```html
<th>
    <div class="btn-group btn-group-toggle btn-group-sm" data-toggle="buttons">
        <label class="btn btn-outline-secondary" title="<?= I18N::translate("show only male persons") ?>">
            <input class="hh-extended-filter-button" type="checkbox" autocomplete="off" data-filter-type="sex" data-filter-value="M">
            <span class="wt-icon-sex wt-icon-sex-m"><i class="fas fa-mars fa-fw" aria-hidden="true"></i></span>
        </label>
        <label class="btn btn-outline-secondary" title="<?= I18N::translate("show only female persons") ?>">
            <input class="hh-extended-filter-button" type="checkbox" autocomplete="off" data-filter-type="sex" data-filter-value="F">
            <span class="wt-icon-sex wt-icon-sex-f"><i class="fas fa-venus fa-fw" aria-hidden="true"></i></span>
        </label>
        <label class="btn btn-outline-secondary" title="<?= I18N::translate("show only persons of unknown gender") ?>">
            <input class="hh-extended-filter-button" type="checkbox" autocomplete="off" data-filter-type="sex" data-filter-value="U">
            <span class="wt-icon-sex wt-icon-sex-u"><i class="fas fa-genderless fa-fw" aria-hidden="true"></i></span>
        </label>
    </div>
</th>
<th>&nbsp;</th>
<th>
    <div class="btn-group btn-group-toggle btn-group-sm" data-toggle="buttons">
        <label class="btn btn-outline-secondary" title="<?= I18N::translate("show only alive persons") ?>">
            <input class="hh-extended-filter-button" type="checkbox" autocomplete="off" data-filter-type="alive" data-filter-value="Y">
            <?= I18N::translate("alive") ?>
        </label>
        <label class="btn btn-outline-secondary" title="<?= I18N::translate("show only dead persons") ?>">
            <input class="hh-extended-filter-button" type="checkbox" autocomplete="off" data-filter-type="alive" data-filter-value="N">
            <?= I18N::translate("dead") ?>
        </label>
    </div>
</div>
</th>
```
Then augment your chartbox with data (the name of the `data-filter-value-**` is defined by the `data-filter-type` set in the buttons: 

```html
<div class="wt-chart-box-<?= strtolower($indi->sex()) ?> hh-extended-filter" data-filter-value-sex="<?= $indi->sex() ?>" data-filter-value-alive="<?= $indi->isDead() ? 'N' : 'Y' ?>">
```

And finally, the javascript could be: (it is making use of the Bootstrap `d-none` class which should be available, there are other more native JS way of showing/hiding a div)

```javascript
$(".hh-extended-filter-button").click(function() {
  let checkbox = $(this);
  let siblings = checkbox.parent().siblings();

  // Deselect other options
  siblings.children().prop("checked", false).removeAttr("checked");
  siblings.removeClass('active');

  // Apply (or clear) this filter
  let filterType = checkbox.data("filter-type");
  if(checkbox.prop("checked")) {
      let filterValue  = checkbox.data("filter-value");
      $(".hh-extended-filter[data-filter-value-" + filterType + "]").addClass('d-none');
      $(".hh-extended-filter[data-filter-value-" + filterType + "='" + filterValue + "']").removeClass('d-none');
  }
  else {
      $(".hh-extended-filter[data-filter-value-" + filterType + "]").removeClass('d-none');
  }
  
})
```

This is pretty rough, but that can give you and idea of a working solution.

I am assuming that with javascript you do not need to store the filter combination (that can still be done, but I think this is less relevant). There are several choices if you want to implement it, but you would probably look at the sessionStorage if using javascript, and probably more at cookies indeed if you want to keep session information with the server.

**Comment by hartenthaler** [comment]
Thanks a lot! This will help me to go in the right direction! I will find a solution now!

**Comment by hartenthaler** [comment]
I found a solution based on your very appreciated help! There are still two minor bugs, but the filter option for users will be part of the next release of my module. Thank you!
