### ISSUE TITLE
Latest beta - Search fails to return results

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#3987]
Search for name e.g. Peters, return no results on any search option.

**Comment by makitso** [comment]
Actually, the results are returned but not displayed. If one selects the family tab then families show.  Then going back to the individual tab the search results are now shown -- can reproduce on webtrees beta demo.

**Comment by fisharebest** [comment]
In bootstrap 5, the code for activating tabs is different.  I guess I missed these tabs...
