### ISSUE TITLE
Colors theme - text color

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3990]
All palettes. Lots of text has turned blue - Not sure but I think it's related to this piece of css being imported from clouds.css and not being over-ridden.
```
a, .nav-link {
    color: #039;
    text-decoration: none;
}
```

BTW, if this is a work in progress let me know and I'll stop reporting

**Comment by fisharebest** [comment]
This will be a consequence of the Bootstrap upgrade.  There are probably others, so please report any more that you find.

In BS4, navigation items are coloured as text.
In BS5, navigation items are coloured as links.
