### ISSUE TITLE
Control panel - list of family trees style (opinion)

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3995]
The table containing the list of family trees has the following css applied to the th & td elements. In my opinion this is too obtrusive and the table looks better with it removed

```
[dir] .table > :not(:last-child) > :last-child > * {
    border-bottom-color: currentColor;
}
```

**Comment by jon48** [comment]
This is something I noted as well, trying to upgrade my theme to Bootstrap 5.

This has been added [in the Bootstrap framework](https://github.com/twbs/bootstrap/blob/fd985d3732f170f4d55f93800bf82bb3137836e3/scss/_tables.scss#L42-L44), but I share your opinion, I find it a bit too opinionated, as it takes over any style you may have applied to the table, and I haven't found a neat way of revert it to the initial border colour (whatever it would be), other than overriding the specific `.table > :not(:last-child) > :last-child > *` rule with the explicit colour I need (in as many context as needed). I would be happy to hear about any trick that would "unset" the last property assignment (I have tried the `unset`, `revert`, `inherit`... values, but they do not achieve the expected result)

This issue will be exhibited on the standard themes as well for any lists when PR #3997 have been merged.

**Comment by fisharebest** [comment]
> I haven't found a neat way of revert it to the initial border colour

Adding the bootstrap class `table-bordered` replaces the thicker/black lines with thinner/grey ones.

But it does also add vertical lines, which (IMHO) is unnecessary visual clutter.

**Comment by ddrury** [comment]
Actually this isn't as bad as I first thought. Bootstrap styles a table the same as you'd draw one on a piece of paper - Line under the column titles and line before the footer with lighter lines between each content line.

The problem I mentioned above is an edge case where there is only one content line, hence the heavy lines above and below.

From my point of view therefore, I'd be prepared to close this
