### ISSUE TITLE
Theme colour changes

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3996]
See https://github.com/fisharebest/webtrees/issues/3990

Also applies to Clouds, F.A.B, Minimal & Xenia.

**Comment by fisharebest** [comment]
Can you give a specific example?

**Comment by ddrury** [comment]
https://dev.webtrees.net/demo-dev/tree/demo/individual/I10034/Augustus-the-Younger-Duke-of-Brunswick-Luneburg

**Comment by fisharebest** [comment]
OK, here is the old/new sites with xenea theme.

What aren't I seeing?

<img width="1374" alt="Screenshot 2021-08-21 at 10 17 49" src="https://user-images.githubusercontent.com/2306088/130317188-848f383f-13fc-45e5-8d5c-c17a797d64a4.png">
<img width="1193" alt="Screenshot 2021-08-21 at 10 17 43" src="https://user-images.githubusercontent.com/2306088/130317189-d1f2d217-83ac-48c1-a369-1bc1b2b35a24.png">

**Comment by ddrury** [comment]
Try the minimal theme

**Comment by jon48** [comment]
It can be seen below (comparison on minimal - individuals' name).

In addition, the links are now underlined by default (as documented in the [migration notes](https://getbootstrap.com/docs/5.0/migration/#content-reboot-etc)), as highlighted below on the number of children links between blocks: 
![image](https://user-images.githubusercontent.com/5150782/130321452-b9f07041-950a-4a8f-a723-9205ac9e0598.png)

This probably needs to be added to `_base.css`, to keep the same display:

```css
a, .btn-link, .nav-link {
    text-decoration: none;
}
```

**Comment by fisharebest** [comment]
I've moved the link color/decoration defintions to CSS variables.

I've kept the underscores on the minimal theme.  Although "unstylish", they can be beneficial for some users (e.g. colorblind).

**Comment by ddrury** [comment]
Are you leaving the minimal theme text colour as blue instead of black deliberately?

**Comment by fisharebest** [comment]
Yes.  I'm thinking that it might help with accessibility on this theme.

Might review the decision in the future.
