### ISSUE TITLE
Tag FAM:_SEPR displayed in Individual facts

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3999]
See https://dev.webtrees.net/demo-dev/tree/demo/individual/X9211/Princess-Alice-of-Battenberg#

**Comment by fisharebest** [comment]
The GEDCOM file contains a non-standard tag, and the site hasn't enabled any modules that support it.

So, the code is working as expected.

I guess `1 _SEPR` ought to be replaced with `1 EVEN Separation` - although it might be useful to keep it as an illustration of how custom tags are handled.
