### ISSUE TITLE
eg Family tab dropdown menu sizing

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4005]
See example

When the number of items causes the length to exceed the set length the scroll bar obscures some of the entries (I suspect this code is a candidate for updating to bootstrap 5)

![demo](https://user-images.githubusercontent.com/104515/130368882-4880729c-6ced-470f-8cbd-d1509ec60462.jpg)

**Comment by fisharebest** [comment]
It is impossible(?) to style scrollbars with CSS, and I think this is probably working as bootstrap/popper intended.

On some browsers, they are semi-transparent so you can see the content beneath them.
On others, they are only shown when you move your pointer over them.
On Firefox, they fade away after a few seconds.

**Comment by ddrury** [comment]
what about increasing the width then?
