### ISSUE TITLE
Hebrew Repository name and Source title in wt 2.1.0-dev code 

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#4008]
How can I add a Hebrew Repository name and a Hebrew Source title?
In pre wt 2.0 I used level 2 _HEB values.
A second 1 NAME and 1 TITLE could also work.

**Comment by fisharebest** [comment]
> In pre wt 2.0 I used level 2 _HEB values.

In 2.1, you will need to create a module which defines these custom tags.

It will be straightforward to create such a module.  When I have finished a little more of the core code, I will create a module for you.

**Comment by fisharebest** [comment]
I created an example module here:

https://github.com/webtrees/example-module-custom-tags

I am still happy to create a module for you, with all your customisations.  Just ask.
