### ISSUE TITLE
Github Beta - _UID tag missing from Privacy restriction

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#4010]
Control Panel, Privacy restriction.  When trying to add a restriction, the dropdown of all the tags is missing the _UID tag.

**Comment by fisharebest** [comment]
No custom tags are currently available.

The "Custom tag" modules need to specify two things.

1) how to understand tags in the existing data. This is largely done, so `_UID` is displayed correctly.

2) how to add new custom tags.  This is still being developed.

As a temporary workaround, you can add a row directly to the `wt_default_resn` table.

**Comment by fisharebest** [comment]
To use `_UID` fields, you must now enable a "custom tags module" that supports it.

Currently, this includes legacy, paf, reunion, roots magic and webtrees.

The definitions for these other applications still needs more work/research.
