### ISSUE TITLE
Timeline - zoom icons don't work

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#4016]
At the timeline click at the magnifier to zoom the page in or out. It doesn't work. The page refreshes but that's all.

Confirmed in demo dev.

**Comment by JustCarmen** [comment]
I don't get a 'zoom' parameter in the URL at all. And no errors in console or website log.

Tested in both demo-dev and stable-dev. In Chrome and Edge.

See: https://dev.webtrees.net/demo-dev/tree/demo/timeline-16?xrefs%5B0%5D=i1&xrefs%5B1%5D=I10030

**Comment by fisharebest** [comment]
On the demo site, the default timeline chart URL is this:

https://dev.webtrees.net/demo-dev/tree/demo/timeline-10?xrefs%5B0%5D=i1

If zoom in, the URL becomes:

https://dev.webtrees.net/demo-dev/tree/demo/timeline-13?xrefs%5B0%5D=i1
https://dev.webtrees.net/demo-dev/tree/demo/timeline-16?xrefs%5B0%5D=i1
https://dev.webtrees.net/demo-dev/tree/demo/timeline-20?xrefs%5B0%5D=i1
https://dev.webtrees.net/demo-dev/tree/demo/timeline-25?xrefs%5B0%5D=i1
https://dev.webtrees.net/demo-dev/tree/demo/timeline-31?xrefs%5B0%5D=i1
https://dev.webtrees.net/demo-dev/tree/demo/timeline-38?xrefs%5B0%5D=i1

With each zoom, the scale is changed.

Perhaps it needs a bigger change with each zoom.

10 -> 20 -> 30 -> 40, etc.

**Comment by JustCarmen** [comment]
Greg, I am so sorry but I totally misunderstood the zoom function of this page. I have never used the timeline function much so it is my inexperience with this part that made me think the zoom function was to zoom the page.... I couldn't read the small text very well so I tried zooming in a bit and nothing happened.... Until now I hadn't noticed that the zoom function was only for the timeline itself (in case there is too much data to show in a certain period). And you're right, this works correctly.

Next time I will use the zoom function of the browser if I have trouble reading the text.

But I think your suggestion to expand the zoom steps is a good one. I don't think the small steps help much if there is too much data to see.

**Comment by fisharebest** [comment]
I've increased the change in zoom with each click.
