### ISSUE TITLE
2.1-Dev Adding/Editing facts

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4017]
I know I've seen this somewhere before but can't find an issue relating to it so feel it should be recorded here and added to the 2.1 milestone.

The introduction of the tag element management has (in my view) made fact adding/editing almost unuseable in it's current form. In particular for facts with lots of possible elements (e.g census) the edit form extends beyond a resonable page length making it almost impossible to work out where an element sits in the hierarchy as once the page is scrolled the indented relationship is lost.

This is on a desktop system - I wouldn't even attempt it on a touch screen device

**Comment by fisharebest** [comment]
> I know I've seen this somewhere before but can't find an issue relating to it

Probably #3027

**Comment by ddrury** [comment]
Agreed - duplicate

**Comment by fisharebest** [comment]
What are your thoughts on https://getbootstrap.com/docs/5.1/forms/floating-labels/

By combining the labels, we get more flexibility to alter the layout - e.g. indentation to indicate hierarchy, collapsable children, etc.

**Comment by ddrury** [comment]
Like them, I'd also prefer collapsible children otherwise I think the indentation would have to be greater than currently to more clearly define the hierarchy.

**Comment by fisharebest** [comment]
Closed in favour of #3027 - it's part of the same problem.
