### ISSUE TITLE
Media and Album Tabs not respecting privacy for OBJE level > 1

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4022]
Example: image attached to source citation. Current privacy level prohibits display of source. Image is nevertheless shown on the media tab.

**Comment by fisharebest** [comment]
We don't have an entity "source citation" in the database.

Links are between records.  The privacy logic for media objects has always been "links to private records" - not "links to private substructures of records".  https://webtrees.net/user/privacy/

Given the current database structure, it's not practical to change this.
