### ISSUE TITLE
An error occurs when some characters are entered in the name

### ISSUE THREAD

**Issue by DaPoHou** [fisharebest/webtrees#4024]
When I change a person's name and enter the Chinese character 𡐤 , the following error occurs when I save it.

> SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\xA1\x90\xA4\x0A2...' for column `webtrees`.`wt_change`.`new_gedcom` at row 1 (SQL: insert into `wt_change` (`gedcom_id`, `xref`, `old_gedcom`, `new_gedcom`, `user_id`) values (2, I33497, 0 @I33497@ INDI

https://www.fileformat.info/info/unicode/char/21424/index.htm

**Comment by fisharebest** [comment]
This is the same as #2950
