### ISSUE TITLE
Tests: failure on `$family instanceof Family` assertion

### ISSUE THREAD

**Issue by jon48** [fisharebest/webtrees#4026]
Now that most of the HTML parsing failures are dealt with, there is still an error on the test suite. 
```console
TypeError: Fisharebest\Webtrees\Factories\FamilyFactory::Fisharebest\Webtrees\Factories\{closure}(): Return value must be of type Fisharebest\Webtrees\Family, null returned
```

I don't know if you had any chance to troubleshoot that one, but this is quite a sneaky one...

According to my testing, the family of interest is `@f29@` from the `demo.ged` (there are probably more, but they would probably appear after).
When debugging `EmbeddedVariablesTest`, it appears indeed that the Cache contains a `null` value for family record `@f29@` when displaying all tags, through.

`Statistics::getAllTagsTable`
`Statistics::ageBetweenSpousesFM`
`FamilyRepository::ageBetweenSpousesFM`
`FamilyRepository::ageBetweenSpousesQuery` l.1293
`FamilyFactory::mapper`

I could not understand where that null value was coming from, until I realised that it must have been set during the tree import.
And indeed.

- The import is done without the user being an administrator (because PHPUnit is running from the CLI, and in the test, no user has been authenticated yet)
- When importing, it first imports individual record `@X1031`, which `FAMC` is `f29`. Note that at this point, the family has not been imported yet
- As part of the individual import, in `FunctionsImport::importRecord`, the process is calling `FunctionsImport::updateNames` (l. 347).
- `FunctionsImport::updateNames` itself calls `Individual::getAllNames()` (l. 682)
- And here the problem is going to start: before extracting the names, the method `getAllNames` check if the names can be shown. Remember that the running user is not an administrator.
- `Individual::canShow` is subsequently called, and there are the successive checks of whether the individual can be shown. As an administrator, those checks are bypassed fairly early in the stack, but here, the user being anonymous, it needs to go through all the checks, and in particular the following chain:
  `Individual::canShowRecord` (l.1329) / `Individual::canShowByType` (l.101) / `Individual::isDead` (l.285) / `Individual::childFamilies`
- At this points, because the individual is linked to `@f29` through `FAMC`, it tries to load the family
- **BUT** the family has not been imported yet, so when executed the first time, the closure in FamilyFactory::make returns a `null` value and it is stored in the Cache against the `@f29@` family
- Any subsequent call to the cache for that family therefore returns `null`, in particular in the use case above when displaying `getAllTagsTable`

This can be fixed by changing a bit the sequence of the test, and authenticating first as an admin, then import, and run the first test as a member, then logout and running the test as a visitor (see below).
The same issue could however happen everywhere `TestCase::importTree` is used before having logged in as an administrator. Maybe we could move a similar logic within the `TestCase::importTree` method itself, checking if the current user is an admin and make sure the import runs as an admin.

Thinking a bit more out of the box, I am wondering whether this is a good practice that the cache stores `null` values. I reckon `null` can be a valid result, but it can be as well the default value when something went wrong (like in the `GedcomRecordFactory::make` example). Maybe the `remember` method could by default not store in cache when null values are returned by the closure, and rather take an additional parameter when `null` values are allowed. I have done a small test in that direction ([available in my fork](https://github.com/jon48/webtrees/blob/hotfix/phpunit-cache/app/Cache.php)), but requires to move the `Cache` class from Symfony interfaces to PSR-6 ones (not a big issue because Symfony classes implements the PSR-6 classes as well), because we need slightly more methods than Symfony offers to implement the logic.

**Working test**
```php
    public function testAllEmbeddedVariables(): void
    {
        $user = (new UserService())->create('user', 'User', 'user@example.com', 'secret');
        $user->setPreference(UserInterface::PREF_IS_ADMINISTRATOR, '1');
        Auth::login($user);
        
        $tree       = $this->importTree('demo.ged');
        // Required as contactWebmaster uses the current request
        app()->instance(ServerRequestInterface::class, self::createRequest()->withAttribute('tree', $tree));
        
        $statistics = new Statistics(new ModuleService(), $tree, new UserService());

        // As member
        $text = $statistics->embedTags('#getAllTagsTable#');
        self::assertNotEquals('#getAllTagsTable#', $text);

        // As visitor
        Auth::logout();
        $text = $statistics->embedTags('#getAllTagsTable#');
        self::assertNotEquals('#getAllTagsTable#', $text);
    } 
```

**Comment by fisharebest** [comment]
Thanks for this.  The issue was already raised as #3939 (I'll close that one) and I'd gotten as far as finding that the null was set during import.

> Maybe we could move a similar logic within the TestCase::importTree method itself, checking if the current user is an admin and make sure the import runs as an admin.

Since import only ever happens as admin/manager, then this makes perfect sense.
Add something like `self::assertTrue(Auth::isManager($tree));`?

**Comment by fisharebest** [comment]
> I am wondering whether this is a good practice that the cache stores null values.

There are times when `null` is a valid result, and you would want it to be stored.
For example, fetching a non-existing record such as `@f29@`.
You would not want to query the database every time.

Although logging-in as an administrator will fix this particular test failure, the `Statistics` class pulls in lots of "global" variables such as the request, which are awkward to mock.

**Comment by jon48** [comment]
> There are times when `null` is a valid result, and you would want it to be stored. For example, fetching a non-existing record such as `@f29@`.

True, I did not considered the case where the record is really non existing. Forget the idea...

> Add something like `self::assertTrue(Auth::isManager($tree));`?

We can have 2 approaches:

- Either leaving the responsibility of running as an appropriate user to the initial test, and indeed we could just add a check in `importTree`.
  We can use your suggestion with `assertTrue`, but as this is not really testing anything in the application, but rather a check that the test itself has been correctly written to reach an expected state, maybe we could mark it as incomplete instead. I do not have a strong opinion on either to be honest.  For info, there would be 13 tests failing because of this check (including the current `testAllEmbeddedVariables`)
  ```php
  if(!Auth::isManager($tree)) {
      self::markTestIncomplete('The tree cannot be imported: current user is not a manager');
  }
  ```
- Or make it transparent to the initial test, and login as Administrator if necessary within `importTree` (so roughly `if not a manager then create an admin user and login, run the import, logout`). However, the logic needs to  be a bit more complex, as we need to cater for a potential non-manager user already logged in, and need to be logged in again after the import. I am afraid that would create a too complex method.

**Comment by fisharebest** [comment]
The `importTree()` function actually creates a tree as well as importing it.  So it needs to be an admin - not a manager.

Maybe we can
* create a helper function `function createAdminUser()`
* pass an admin user to the `importTree()` function as a second parameter.
