### ISSUE TITLE
I tried to update the vendor files and get errors 

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#4031]
I get the following errors in both my test systems.

Warning: require(/home/amitys/future.amitys.com/vendor/composer/../symfony/polyfill-iconv/bootstrap.php): failed to open stream: No such file or directory in /home/amitys/future.amitys.com/vendor/composer/autoload_real.php on line 71

Fatal error: require(): Failed opening required '/home/amitys/future.amitys.com/vendor/composer/../symfony/polyfill-iconv/bootstrap.php' (include_path='.') in /home/amitys/future.amitys.com/vendor/composer/autoload_real.php on line 71

**Comment by melizaa** [comment]
As far as I understand symfony/polyfill-iconv was removed.
Removing symfony/polyfill-iconv (v1.23.0)

**Comment by fisharebest** [comment]
I have updated the `/vendor` folder for you on both these systems.
They now appear to be working OK.

**Comment by melizaa** [comment]
I see that you have added and updates many vendor files.

I update vendor files on my windows computer using "php composer.phar install", and upload then the changed files to my test systems.

Suppose I download to my local windows computer the vendor files that you added. 
Should "php composer.phar install" update the files in the future?

Meliza

**Comment by fisharebest** [comment]
You should use `php composer.phar install --no-dev`.

(without the `--no-dev` option, it will also install things that are only needed during local development, such as test scripts.)

I ran this command locally on your site.

> Should "php composer.phar install" update the files in the future?

It does not matter what files currently exist in the `/vendor` folder.
The `composer install` will delete any old files that are no longer needed.

**Comment by melizaa** [comment]
Yes, I use the --no-dev option.

**Comment by melizaa** [comment]
Do we still need vendor package sebastian?

**Comment by fisharebest** [comment]
These are part of the test tools.

You don't need them.

They are installed if you run `composer install` (without `--no-dev`).

If you run `composer install --no-dev`, they should be deleted.
