### ISSUE TITLE
Usage of OBJE:_DATE

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#4034]
When I imported photos from FTB, I had records like this:

```
0 @X200@ OBJE
1 _DATE 1922
```

So I always added `_DATE` in addition to `DATE` in the `GedcomTag.php` tag switch block of older versions.  But by v2.0 this has been baked in.  (Thank you!)

When I updated to 2.0.16, instead of getting the word "Date" in the left column of a media details screen, I now get, "A date associated with a multimedia object, usually a picture or video (under an OBJE block)."

So something changed and is not right with this.  Is this a new bug?

![screen](https://user-images.githubusercontent.com/1371835/133322639-0833be99-aff1-428c-86e3-453daa441993.png)

see also https://github.com/fisharebest/webtrees/blob/31adf47427d752f5d7e48e6e93cfd4b474027f1c/app/Factories/ElementFactory.php#L1271

There's a similar, possibly related problem with `_PHOTO_RIN` which is defined in `GedcomTag.php` as `I18N::translate('Record ID number')` but in v2.0.16 it's literally described as "Photo" instead.  This is confusing because the ID is not a photo.  The ID is an ID, and it needs to be labeled correctly.

see also https://github.com/fisharebest/webtrees/blob/31adf47427d752f5d7e48e6e93cfd4b474027f1c/app/Factories/ElementFactory.php#L811

Are these two separate bugs?

**Comment by fisharebest** [comment]
I think you are looking at old code.

Support custom tags is now in a separate module.
For example, FamilyTreeBuilder custom tags are defined here:

https://github.com/fisharebest/webtrees/blob/main/app/Module/CustomTagsFamilyTreeBuilder.php

`OBJE:_DATE` looks OK.

The others are probably just place-holders - I still need to do more research to find out what tags are created by FTB.  

If you use this software, then perhaps you can help?

**Comment by miqrogroove** [comment]
Sure.  If I'm understanding, this was partially fixed in the trunk where "Date" is now correct, but the RIN fields are still badly tagged as "Photo".

The other problems still exist on the 2.0 branch.  Is the 2.0 branch still supported, and do you need separate pulls for the branch and trunk?

**Comment by fisharebest** [comment]
As I said, I am still trying to track down a copy (or documentation) of FTB to find out what custom tags it uses.

There are probably many others that I don't know about.

Just create a PR for `main`.

**Comment by fisharebest** [comment]
In the absence of other informaion, I've assumed that `OBJE:_PHOTO_RIN` is the same as `OBJE:RIN`...
