### ISSUE TITLE
beta - contact throws error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#4035]
Undefined index: body …/app/Http/RequestHandlers/ContactAction.php:91 #0 …/app/Http/RequestHandlers/ContactAction.php(91): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}() #1 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\ContactAction-&gt;handle() #2 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler-&gt;process() #3 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher-&gt;handle() #4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process() #5 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #6 …/app/Webtrees.php(241): Middleland\Dispatcher-&gt;dispatch() #7 …/app/Http/Middleware/Router.php(149): Fisharebest\Webtrees\Webtrees::dispatch() #8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router-&gt;process() #9 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher-&gt;handle() #10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules-&gt;process() #11 …/app/Http/Middleware/LoadRoutes.php(74): Middleland\Dispatcher-&gt;handle() #12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes-&gt;process() #13 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher-&gt;handle() #14 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}() #15 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection-&gt;transaction() #16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process() #17 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher-&gt;handle() #18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process() #19 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher-&gt;handle() #20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process() #21 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher-&gt;handle() #22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process() #23 …/app/Http/Middleware/UseLanguage.php(69): Middleland\Dispatcher-&gt;handle() #24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process() #25 …/app/Http/Middleware/UseSession.php(75): Middleland\Dispatcher-&gt;handle() #26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process() #27 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher-&gt;handle() #28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process() #29 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher-&gt;handle() #30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar-&gt;process() #31 …/app/Http/Middleware/UseDatabase.php(132): Middleland\Dispatcher-&gt;handle() #32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process() #33 …/app/Http/Middleware/BadBotBlocker.php(223): Middleland\Dispatcher-&gt;handle() #34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process() #35 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher-&gt;handle() #36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process() #37 …/app/Http/Middleware/ContentLength.php(52): Middleland\Dispatcher-&gt;handle() #38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength-&gt;process() #39 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher-&gt;handle() #40 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp-&gt;process() #41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process() #42 …/app/Http/Middleware/HandleExceptions.php(89): Middleland\Dispatcher-&gt;handle() #43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process() #44 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher-&gt;handle() #45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process() #46 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher-&gt;handle() #47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process() #48 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher-&gt;handle() #49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process() #50 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher-&gt;handle() #51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process() #52 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #53 …/app/Webtrees.php(241): Middleland\Dispatcher-&gt;dispatch() #54 …/app/Webtrees.php(228): Fisharebest\Webtrees\Webtrees::dispatch() #55 …/index.php(44): Fisharebest\Webtrees\Webtrees-&gt;httpRequest() #56 {main}

**Comment by fisharebest** [comment]
Is this something that you can trigger - or did you just find this in the logs?

**Comment by makitso** [comment]
I found it in the logs.  About the same time I received an email from someone looking at my web site.

**Comment by makitso** [comment]
I happen to see this again yesterday.  The http logs show
212.102.33.191 - - [28/Sep/2021:04:46:41 -0700] "GET /tree/peters.ged/contact?to=makitso&url=https%3A%2F%2Fskatekey.net%2Ftree%2Fpeters.ged HTTP/1.1" 301 7116 "https://skatekey.net" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
212.102.33.191 - - [28/Sep/2021:04:46:41 -0700] "GET /tree/peters/contact?to=makitso&url=https%3A%2F%2Fskatekey.net%2Ftree%2Fpeters.ged HTTP/1.1" 200 12335 "https://skatekey.net" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
212.102.33.191 - - [28/Sep/2021:04:46:43 -0700] "GET /tree/peters/contact?to=makitso&url=https%3A%2F%2Fskatekey.net%2Ftree%2Fpeters.ged HTTP/1.1" 200 12219 "https://skatekey.net" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
212.102.33.191 - - [28/Sep/2021:04:46:45 -0700] "POST /tree/peters/contact HTTP/1.1" 500 51490 "https://skatekey.net" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"

**Comment by fisharebest** [comment]
Fixed in 8d9c2b6
