### ISSUE TITLE
Statistics.php chart errors

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#404]
Visible on latest beta demo but ok on 1.6.2 demo

Individuals tab Total Individuals (top chart) generates "NetworkError: 400 Bad Request" for both male/female and living/dead

Later
the chart dimensions are blank but at the moment I can't see why

**Comment by ddrury** [comment]
I think for \WT\Stats\chartMortality() & \WT\Stats\chartSex the globals

    $WT_STATS_S_CHART_X, $WT_STATS_S_CHART_Y; 

need replacing by

    $WT_STATS_S_CHART_X    = Theme::theme()->parameter('stats-small-chart-x');
    $WT_STATS_S_CHART_Y    = Theme::theme()->parameter('stats-small-chart-y');

**Comment by fisharebest** [comment]
Thanks
