### ISSUE TITLE
Gedcom Export Data Loss

### ISSUE THREAD

**Issue by andrewgoz** [fisharebest/webtrees#4043]
It is possible for webtrees to produce an incomplete exported Gedcom file when resource constrained. When this occurs, there is no indication to the user that there is any problem - there is silent data loss.

My understanding is that the return code from fwrite() is not checked. All writes during export should be confirmed error-free and a message shown to the user if there is a problem. If the export is successful it may also be useful to confirm that to the user.

This issue was originally noticed on a system with a small (64MB) /tmp filesystem and the exported Gedcom approached that size. It occurred when using the "export to file on the server", and also the "export to compressed file on your PC". The "export uncompressed file to your PC" failed to produce any data.

**Comment by fisharebest** [comment]
Fixed in 783b32e3a5ee549486e64373d0161e7a55b5a7c0
