### ISSUE TITLE
MINOR formatting issue with expanding sub record

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#4048]
When I open or close the source citation in the images, the display geometry changes horizontally.  Not very important, but visually jarring
![closed](https://user-images.githubusercontent.com/5910274/134289520-07433448-1b35-4ca1-9da9-e5ee492ed6bd.gif)
g
![open](https://user-images.githubusercontent.com/5910274/134289545-0d7c36d4-6536-4f27-ba44-4c74b2dc8ceb.gif)
.

**Comment by fisharebest** [comment]
This change was made a few weeks ago.  You can see it on the demo site.
