### ISSUE TITLE
V2.1-dev Add a person

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4055]
When adding a person, a 2nd name block is present in the edit form which I can't see how to suppress, this potentially results in an empty name being saved.

**Comment by fisharebest** [comment]
This depends on the surname tradition.

If the new individual would have a married name, the second name block is for TYPE=married.

**Comment by fisharebest** [comment]
AFAICT, this is working as designed.

Feel free to re-open or raise another issue if you think otherwise...
