### ISSUE TITLE
Issue with Production PDF reports - 1.8.0-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#4059]
**How can I correct the errors?
I tried to use the latest tcpdf files. I see in webtrees the same issues as I see in the test systems on Hebrew pages and for Hebrew names (RTL).
I need ASAP a solution for my webtrees production site.
Is it possible not to enable PDF reports in my webtrees production site till this issue is solved? How?**

In my **webtrees** site 
**I got error:**
/xxx/webtrees/includes/session.php:204 /xxx/webtrees/vendor/tecnickcom/tcpdf/tcpdf.php:17787 "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? #0 /vendor/composer/ClassLoader.php:440 ErrorException("/xxx/webtrees/vendor/tecnickcom/tcpdf/tcpdf.php:17787 "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?") #1 /vendor/composer/ClassLoader.php:440 include() #2 /vendor/composer/ClassLoader.php:322 Composer\Autoload\includeFile('/xxx/we…') #3 unknown:unknown loadClass('TCPDF') #4 /app/Report/ReportTcpdf.php:25 spl_autoload_call('TCPDF') #5 /vendor/composer/ClassLoader.php:440 include('/xxx/we…') #6 /vendor/composer/ClassLoader.php:322 Composer\Autoload\includeFile('/xxx/we…') #7 unknown:unknown loadClass('Fisharebest\\Webtrees\\Report\\Re…') #8 /app/Report/ReportPdf.php:64 spl_autoload_call('Fisharebest\\Webtrees\\Report\\Re…') #9 /app/Report/ReportParserGenerate.php:324 setup() #10 /app/Report/ReportParserGenerate.php:157 docStartHandler([array]) #11 unknown:unknown startElement([resource], 'Doc', [array]) #12 /app/Report/ReportParserBase.php:43 xml_parse([resource], 'geSize="$pageSize" >

In the **tree** site
**After I update the tcpdf files I see the reports as expected, because there is no RTL data!!**
**I got the error**
/xxx/includes/session.php:193 /xxx/vendor/tecnickcom/tcpdf/tcpdf.php:16901 Array and string offset access syntax with curly braces is deprecated #0 /vendor/composer/ClassLoader.php:440 ErrorException("/xxx/vendor/tecnickcom/tcpdf/tcpdf.php:16901 Array and string offset access syntax with curly braces is deprecated") #1 /vendor/composer/ClassLoader.php:440 include() #2 /vendor/composer/ClassLoader.php:322 Composer\Autoload\includeFile() #3 unknown:unknown loadClass() #4 /app/Report/ReportTcpdf.php:25 spl_autoload_call() #5 /vendor/composer/ClassLoader.php:440 include('/xxx/a…') #6 /vendor/composer/ClassLoader.php:322 Composer\Autoload\includeFile() #7 unknown:unknown loadClass() #8 /app/Report/ReportPdf.php:64 spl_autoload_call() #9 /app/Report/ReportParserGenerate.php:324 setup() #10 /app/Report/ReportParserGenerate.php:157 docStartHandler() #11 unknown:unknown startElement() #12 /app/Report/ReportParserBase.php:43 xml_parse() #13 /app/Report/ReportParserGenerate.php:128 __construct() #14 /reportengine.php:282 __construct()

**Comment by fisharebest** [comment]
This was a bug in an old version of TCPDF.

I guess you have replaced the latest version of `tcpdf.php` with a modified copy of the old version.

**Comment by melizaa** [comment]
I used the old 2018 version of TCPDF on my live sites till August 11, 2021.
That is when I started to use version 6.4.2 that I use in my two test systems.
I have the same RTL errors in the live system and in the test systems.

Should I try the not yet stable TCPDF version 8.0.6 in my test system?

**Comment by melizaa** [comment]
version 6.4.2 can be found in wt composer.json.

**Comment by fisharebest** [comment]
TCPDF versions 6.3 and 6.4 just contain compatibility fixes for newer versions of PHP.

So, you should be able to do a comparison of your modified version and 6.4.2 - e.g. using a side-by-side difference program.

You can then merge your changes into the 6.4.2 file.

**Comment by melizaa** [comment]
Thanks for reminding me of my local changes to the reports and to TCPDF.

The change that I had in the old TCPDF was only in the tcpdf.php file
//@@	mb_internal_encoding('ASCII');
 		mb_internal_encoding('UTF-8'); //@@

The new file does not have "mb_internal_encoding('ASCII');".

I prefer as soon as possible to **try to** remove the PDF option at least from some of the Hebrew reports on my live webtrees site.
I will add the pdf reports back as soon as they work as expected in my test system.
See for instance the Hebrew individual and related families pdf reports of I269, the Hebrew family pdf report of the family F68 in my webtrees production site without signing in (or the future test system site after signing in).
(The pictures under the text, the texts on texts, the adjustment of relatives' data after the father's data)

For instance, the birth report is now OK in the test system but not OK on my production site.
The pdf ahnentafel and descendants reports print still texts on texts in the test system.

The related individuals pdf and html ltr and rtl reports print still the marriage day between the spouse's Latin and Hebrew names.

The rtl pdf changes report prints LTR usernames immediately next to the time and then the -.

Unknown ltr and rtl names are printed in ltr and rtl HTML and PDF reports with the ... on the same side of the known name.

etc.

I need to carry out thorough tests to see when I could start to use the latest development code in my live sites.

**Comment by fisharebest** [comment]
> In my production site with it's 1.8.0-dev code in the Control panel - Module administration I do not see any CSS option.

My mistake.  Custom CSS is a feature in 2.0.

Your edit is probably the easiest solution to the problem.
