### ISSUE TITLE
Reported a security issue at HUNTR

### ISSUE THREAD

**Issue by B3EF** [fisharebest/webtrees#4062]
https://huntr.dev/bounties/ff3c3869-27df-4dc6-9663-34013a71b76c

**Comment by fisharebest** [comment]
Hi @B3EF - there is no need to post this here.  As the project owner, I recieve alerts directly from <https://huntr.dev>.

Also, see the [security policy](https://github.com/fisharebest/webtrees/blob/main/SECURITY.md).

**Comment by B3EF** [comment]
Sorry for posting it here , thanks for your response
