### ISSUE TITLE
My account is now modify : very dangerous

### ISSUE THREAD

**Issue by Fa10175** [fisharebest/webtrees#407]
when a person is connected, he can access to "My account" and can modify all field without be an administrator. this could be dangerous. The only modification that i accept is the password. all other should be done only by the true administrator.

**Comment by vytux-com** [comment]
The only field that I believe should not be modifiable would be the Individual Record, which is read-only (correct).

What other fields would be a problem?

**Comment by Fa10175** [comment]
I think all should be not modify by somebody are not administrator (except password may be the address (but this person can write something not good without control))
example a person change how send message after that the mail address disappear even the administrator can enter something after . I should go to database to correct it.
if he change name how the administrator recognizance him. he should not modify how he can see people in the tree.
the access to my account should be define by the administrator.

**Comment by JustCarmen** [comment]
I don't see what is different here with previous versions. The 'my account' menu has been part of the 'my page' menu for ages. Users were always able to change their personal account information. I don't see any problems with that. A user must be able to change for example his e-mail address or contact method by himself.

I agree with Vytux the only part of the user information a user should not change is the individual record link.

**Comment by Fa10175** [comment]
on 1.6.2 an user can't modify is account access
![select-my page 1-6-2](https://cloud.githubusercontent.com/assets/10681601/5992108/0781cb52-aa19-11e4-888e-46a52daca298.jpg)
now 1.7.0-devit is possible to change everything (same user)
![select-my page 1-7-0](https://cloud.githubusercontent.com/assets/10681601/5992140/60d483b4-aa1b-11e4-9e7b-7156bfb556b3.jpg)
with selected my account he can modify everything without any control and verification by administrator
![my account](https://cloud.githubusercontent.com/assets/10681601/5992147/b5d69c8a-aa1b-11e4-921b-fab90a0a931f.jpg)
this user is just member

**Comment by Fa10175** [comment]
I test a little more in 1.6.2 and i found something it possible to say this user can modify his account or not.
the user that as show you before cannot modify his account and now in 1.7.0 he can
If in 1.6.2 i set this user can modify his account we can access and modify everything also.

but for me some are dangerous it 's for that i set all users except me  (administrator) to do not modify his own account.
![allow-to-edit-own-account](https://cloud.githubusercontent.com/assets/10681601/5992209/7486698c-aa1f-11e4-9982-0d1113edba9f.JPG)

**Comment by JustCarmen** [comment]
In version 1.6.2 there is an option in the user administration: "allow this user to edit his account information". I set it to 'yes'. Apparently you have set it to 'no'.

This option doesn't exist anymore in wt 1.7.0. At least I can't find it.

**Comment by JustCarmen** [comment]
Sorry double post

**Comment by fisharebest** [comment]
>  In version 1.6.2 there is an option in the user administration: "allow this user to edit his account information". I set it to 'yes'. Apparently you have set it to 'no'.  This option doesn't exist anymore in wt 1.7.0. At least I can't find it.

The help text for this option said (approximately):

"You can have one account that is shared between lots of users.  This prevents one of them changing the username.  This is not recommended."

We should not encourage (or allow!) people to use shared accounts.

@Fa10175 - all users can now change:

1) their language
2) whether to receive emails from other users
3) the default person for charts
4) if they are visible to other users
5) theme (if the site allows themes to be changed)
6) email
7) username
8) real name
9) password
Since 1.7.0, they can also delete their account.

What problems does this cause?

**Comment by Fa10175** [comment]
i want just also to keep the possibility as before to do not authorize  to change.
like that for me i keep the control to the users account

**Comment by Art4** [comment]
@fisharebest I have a read only shared account for multiple people. Why is it not encouraged to do this anymore? I'm using 1.6.2 yet.

**Comment by fisharebest** [comment]
> Why is it not encouraged to do this anymore?

All users will have the same language.
It breaks the password reset/reminder function.
Users cannot set their "default individual".
It breaks the "who is logged on now" function.
etc.

**Comment by Art4** [comment]
These are no problems for me. These are features for me. :smile:

I have an user called "visitor", who can read only a tree. I share the password with family members, who are only interested in read the tree a few times, not to modify it. They all talk the same language (german). The visitor is not bind to an individual. If someone forget the password they will ask me or other family members.

**Comment by vytux-com** [comment]
For the visitor account if you trust your 'visitor' users with private information you should be able to trust them not to mess with the options.

However if one of them (mistakenly or on purpose) discloses the login details you will be giving away access to private information and:
1) won't know who was responsible for this
2) will also make it difficult to detect any unauthorised use, if 1 individual accesses the site from two different locations (even countries) you won't know if that is OK or not as it could be two or more different users, but with individual accounts that would not be a problem
3) if you are ok with the above why not just make the information public in the first place?

**Comment by Art4** [comment]
We are working with 6 users on a tree with 2500+ individuals. Sometimes we got requests from family members who wants to read the tree, eg. in case of someones death. So we can give them the visitors password.

We are changing the password sometimes and we trust them they won't change the options. I think we can do it this way in 1.7 too but I was wondering why it is not encouraged to do this.

**Comment by StarJackie** [comment]
Hello,
It is part of the « Loi sur la vie privée » in Quebec to have the right to modify and/or delete a membership/account on a website. Therefore, no website administrator (from Quebec) can block that right.
I don't know if this is valid in other countries.

**Comment by StarJackie** [comment]
It seems that even in Europe a law already exists about that.
Sorry for the link in French :+1: 
http://www.barreau.qc.ca/pdf/journal/vol29/no20/viepriveeprotegee.html
go down in the page and see the section : « L'action à l'européenne »

**Comment by StarJackie** [comment]
FA10175 said above
"i want just also to keep the possibility as before to do not authorize to change.
like that for me i keep the control to the users account"
You, as admin, have always the control on your users accounts.
If you are not confident in your users and/or if they don't behave according to your rules (I assume that you approved their accounts based on some rules), then, simply delete their account. They don't deserve it. 
Why would you pull your hair for that?
Voilà !

**Comment by bmhm** [comment]
@Fa10175 
In most countries you may not deny the change of their account information. e. g. the german Bundesdatenschutzgesetzt (federal data privacy law, BDSG) says that noone may store more information than needed to provide a service[1]. If the user wants to anonymize his name, it's his right to do so. If he can't, he may start a lawsuit, because you are storing information you don't need to store.
In fact, you'd need to clear all the logs where his former name was included (or at least also change them) [2]. If a person is deceased, you can publish (almost) any information [3].

[1] http://www.gesetze-im-internet.de/bdsg_1990/__14.html
   => which means: don't store more than username and password, if the user doesn't want to.
[2] http://www.gesetze-im-internet.de/bdsg_1990/__20.html
[3] http://www2.genealogy.net/vereine/ArGeWe/datenschutz.htm

**Comment by fisharebest** [comment]
Shared accounts may be convenient - but I think that the new behaviour is correct.

The new theme system makes it easy to modify most behaviour.  It would be simple to create a theme which removes the "Edit account" menu.

You'd need a theme containing just the following

```php
	/**
	 * A link to allow users to edit their account settings (edituser.php).
	 *
	 * @return Menu|null
	 */
	protected function menuMyAccount() {
		if (Auth::id() !== 123) { // 123 is the user ID of your visitor account.
			return parent::menuMyAccount();
		} else {
			return null;
		}
	}
```
