### ISSUE TITLE
SOUR:REPO:CALN:MEDI data not shown

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#4071]
One of the tests at https://www.gedcomassessment.com/ uses
```
0 @I243@ INDI
1 NAME 02-Full /Repository/
1 SEX M
1 BIRT
2 DATE 1912
2 SOUR @243@
0 @243@ SOUR
1 TITL Birth Registers, 1912
1 AUTH Boston (Mass.) City Registrar
1 PUBL Salt Lake City, UT: Gen. Soc. of Utah, 1970
1 REPO @R243@
2 NOTE Note value for R243 reference
2 CALN US/CAN 740463
3 MEDI film
0 @R243@ REPO
1 NAME Family History Library (Full)
(and every other REPO field the spec mentions)

```
I marked this test as fully supported because it asks whether all the REPO fields are shown and they are. However, I cannot see any rendering of the **3 MEDI film** except in raw GEDCOM.

Not sure subordinate to the call number makes sense for this, but that's where the spec puts it (5.5.1 p. 40)

**Comment by fisharebest** [comment]
<img width="578" alt="Screenshot 2021-10-17 at 13 09 31" src="https://user-images.githubusercontent.com/2306088/137626693-3cba7e42-1bdc-4f70-b0c4-768891fd9c04.png">

It's shown in the 2.1-dev code.

But the field isn't available to add for new record.  I'll fix this.
