### ISSUE TITLE
FAM:CENS:AGE and FAM:EVEN:AGE and more unrequiered infos shown on edit family page

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#4074]
On the edit screen of a family there are lot of unneeded infos and two red entries: FAM:CENS:AGE and FAM:EVEN:AGE in 2.0.17.
This looked much better in 2.0.16.

![grafik](https://user-images.githubusercontent.com/16715040/137341780-dfa0dc90-55e1-4a4c-be2f-20ecbc7fe711.png)

**Comment by fisharebest** [comment]
How do you get to this screen?

**Comment by fisharebest** [comment]
What is the URL of the page?

**Comment by HonkXL** [comment]
https://wt.genealogie-weiland.de/tree/ofb-hoegyesz/record/F1513
(but this page is not public accessible)

**Comment by HonkXL** [comment]
And the edit window I get is
https://wt.genealogie-weiland.de/tree/ofb-hoegyesz/edit-record/F1513

**Comment by fisharebest** [comment]
I've fixed the issue with `FAM:CENS:AGE` - for family census records, we would want `FAM:CENS:HUSB:AGE` and `FAM:CENS:WIFE:AGE`.

**Comment by fisharebest** [comment]
> https://wt.genealogie-weiland.de/tree/ofb-hoegyesz/record/F1513

This URL should redirect to the corresponding family page - https://wt.genealogie-weiland.de/tree/ofb-hoegyesz/family/F1513

If it doesn't, then perhaps webtrees is failing to detect the record somehow.

What is the GEDCOM data for this record in

* The table `wt_families`
* The tabel `wt_change`

**Comment by HonkXL** [comment]
When I go to the edit RAW gedcom and then click "Cancel", I am forwarded to the "right" family screen:
https://wt.genealogie-weiland.de/tree/ofb-hoegyesz/family/F1513/Paul-Weber-Anna-Maria-Tillmann-F1513#
Here I do not have "Edit/Edit" - here is it possible to change family members or to edit the raw GEDCOM again.

The wrong screen is only displayed, when I come from the "Check for errors" screen.

Here is a video of my workflow and the problem. The last screen should be the right one.

https://nc.weiland-cloud.de/index.php/s/AWbzN4smE5gMM98

**Comment by HonkXL** [comment]
wt_families:

f_id = F1513
f_file = 3
f_husb = I4175
f_wife = I4176
f_gedcom =
0 @F1513@ FAM
1 HUSB @I4175@
1 WIFE @I4176@
1 MARR
2 DATE 02 MAY 1871
2 PLAC Diósberény, Tolnau, Ungarn
2 _ASSO @Konrad Weber@
3 RELA witness
2 _ASSO @Johann Kremer@
3 RELA witness
1 CHIL @I4506@
1 CHIL @I4174@
1 CHIL @I27089@
1 CHAN
2 DATE 21 FEB 2020
3 TIME 06:38:27
2 _WT_USER Beáta Farkas

f_numchil = 3

wt_change shows no entry for SELECT * FROM `wt_change` WHERE xref = 'F1513';

**Comment by fisharebest** [comment]
There are two issues here.

One was fixed (wrong definition for `FAM:CENS`).

I cannot reproduce the other (family record not redirecting).  If you can reproduce it, and can provide more details, please open another issue.
