### ISSUE TITLE
Enhancement: edit the raw GEDCOM in the edit-menu

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#4075]
I have a tree with some GEDCOM-errors. Workflow is:
open the error view in the control panel, click the error, the individual or family view opens, then edit / Edit, then scroll to the bottom and click "edit the raw GEDCOM". This are too many clicks for this simple action.

Better: bring the edit raw gedcom to the edit menu.

![grafik](https://user-images.githubusercontent.com/16715040/137342308-93b0c180-95ca-4a6a-8863-7c3d2efde6d4.png)

**Comment by fisharebest** [comment]
In 2.1:

* We should now be able to add/edit/delete every valid GEDCOM tag.
* We also have dedicated edit pages for all record types (submission, header, etc.)
* Subtags are now sorted into a standard order (e.g .TYPE/DATE/PLAC/ADDR).

So, we should have far less need for editing raw GEDCOM data.

Can I ask why you need it?  What could you not do without it?

**Comment by HonkXL** [comment]
I have a lot of entries like this:

2 _ASSO @konrad Weber@
3 RELA witness
2 _ASSO @johann Kremer@
3 RELA witness

And I change them to
2 NOTE Witness Konrad Weber
3 CONT Witness Johann Kremer

I found no good solution to do this in the web frontend.
Sometimes this entries are more complex and have notes that shows city or occupation. I just create notes of them.

This entries came from import of other software and an user that wrote new entries in this way. I don't know how much there are, but many (>1000)
