### ISSUE TITLE
Missing icon/link in Interactive tree

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#4077]
When expanding an indi-box In the Interactive tree, the icon/link to the individual's interactive tree is missing in fab and minimal themes.
See https://www.webtrees.net/index.php/en/forum/help-for-2-0/36138-loss-of-the-small-character-in-the-interactive-tree

**Comment by jon48** [comment]
I got caught in the Rural theme on that one, so an easy one to spot 😃 

There is no content defined for the `.wt-icon-individual` class, so no icon to display.
However, the F.A.B. and minimal are rather icon-less themes, so I will leave it to Greg if the best way forward is to have an icon (as it used to in 1.7), or any other way through FontAwesome or some text (for info, there is a "standing person" character in Unicode U+1F9CD &#x1F9CD;)
