### ISSUE TITLE
Places from historic events appear in the geographic data list

### ISSUE THREAD

**Issue by reteP-riS** [fisharebest/webtrees#4080]
Please see https://www.webtrees.net/index.php/en/forum/help-for-2-0/36170-non-existing-deleted-place-keeps-resurrecting-in-control-panel

**Comment by reteP-riS** [comment]
I checked ALL database tables including the Vesta wt_gov_... tables, even exporting the complete database, but the place in question is not there. Only after this mysterious resurrection it appears in wt_place_location and wt_places, but not in wt_placelinks. That place is not included in the 2 GEDCOM files I import on a regular base. It's not included if I export these 2 family trees to GEDCOM files either. BTW I have no open changes either.

Greg, I know this sounds weird. I'd therefor be happy to setup a screen sharing session for the two of us or provide more information upon your request.

**Comment by ric2016** [comment]
Do you use Vesta shared places?
If you do, it is possible that the place is created from a shared place hierarchy with the respective 'partial' place names. Can you rule this out as well?

**Comment by ric2016** [comment]
Vesta Shared Places only uses standard tables so we can rule it out in this case.

**Comment by reteP-riS** [comment]
The zombie place resurrected once more, but I finally found its origin! It's included in a custom module for historic events https://github.com/reteP-riS/HistoricEvents-Germany/blob/7a88b6a7c67a0156e97b89fb77041e82db9efbf6/module.php#L210 and the webtrees _Control Panel > Geographic Data_ page seeems to link the zombie PLACe to the first tree.

To reproduce this issue either install this module or add a similar EVENt to one of your own historic events modules including PLACe details for a PLACe that doesn't exist in any of your trees.

Now that the mystery is resolved I can see two ways to deal with this issue:

1. either don't add PLACes from custom historic events modules to the database and don't show them on the _Control Panel > Geographic Data_ page at all or
2. make a better use of these PLACes and refer the user/administrator to the historic event (instead of pointing to non-existing events for individuals or families).

Clicking on the PLACe of the historic event on the individual's page both the standard webtrees _Pedigree Map_ module and the _⚶ Vesta Places and Pedigree Map_ module open a world map with the _Individuals 0_ and _Families 0_ tabs and _No results found_ below. Maybe a third tab _Historic Events_ could be added on the map page to show this PLAC.

**Comment by hartenthaler** [comment]
Some time ago I thought about adding PLAC to historic events, too. But finally decided to not use this. Historic event modules can be used by many users and these users all have their own place hierarchy style. Your "2 PLAC Westerplatte, Neufahrwasser, Stadtkreis Danzig, Freie Stadt Danzig" does not make sense for my location hierarchy style, because it uses German location names for a location which is today located in Poland and doesn't follow my style "city, county, state, country". I think records in historic event modules should be restricted to  EVEN, TYPE, DATE, NOTE, and SOUR.
