### ISSUE TITLE
OpenRouteServiceAutocomplete quirk

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4083]
With the current code the results from an autocomplete search can return something like 

> Dover, Kent, Kent, England

(county and region both contain same data) which admittedly isn't the biggest problem in the world - it's simple to edit, however I've changed line 154 of app\Module\OpenRouteServiceAutocomplete.php to
`$places[] = implode(Gedcom::PLACE_SEPARATOR, array_unique(array_filter($parts))) ?: $result->properties->label;`
this works for uk places but I'm not clear on how it would work for hierarchies in other countries.

I suppose an alternative would be to set region to null in the test for "United Kingdom"

**Comment by fisharebest** [comment]
I'm not certain that `array_unique()` preserves the order.  So you might end up with "Dover, England, Kent"

There were changes to the array-sort functions in PHP 8 to retain the original order of equally-sorting values (aka "stable sort").  I'd need to check if this applies to `array_unique()` as well.

> I suppose an alternative would be to set region to null in the test for "United Kingdom"

We would probably end up with special rules for every country.

Not necessarily a bad thing - but possibly a lot of work.
