### ISSUE TITLE
Error with display of notes

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4084]
Markdown ignores the "\n" line ending character which causes the display of a shared note to look like the first image whereas it should look like the 2nd image
![dump](https://user-images.githubusercontent.com/104515/138353264-f517e4ea-936c-417d-bd88-1f330f2ccd6e.jpg)
![dump2](https://user-images.githubusercontent.com/104515/138353467-80c57224-fd97-42e3-8615-8f850888c2c7.jpg)

Adding two spaces to the end of a line indicates to markdown that a linebreak is required.

In app\Note.php, I've changed line 52 to  `return preg_replace("/\n1 CONT ?/", "  \n", $match[1]);` i.e added two spaces to the replace element which fixes it and as far as I can see doesn't affect note display when markdown is disabled but I'm not convinced I've covered every eventuality.

**Comment by fisharebest** [comment]
> Markdown ignores the "\n" line ending character which causes the display of a shared note to look like the first image 

Yes - this is part of the markdown specification

> whereas it should look like the 2nd image

Should?  The markdown spec says that consecutive lines should be joined into a paragraph.

So, I guess we could add a blank line (i.e. to force a new paragraph) between the first line (the title) and the second line (the address).

https://github.com/fisharebest/webtrees/blob/2.0.17/app/Module/CensusAssistantModule.php#L178
