### ISSUE TITLE
Pending changes link

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#409]
With this commit https://github.com/fisharebest/webtrees/commit/33670914cbb4a46ff63690df64f6cba2487c9b10 support for pending changes link is removed.

Reason: bad ui design when placed in the footer.

But I used it within the JustLight theme in the header as an html alert. I don't want to add it to the menu because it doesn't look nice in this theme.

![1-2-2015 9-23-53](https://cloud.githubusercontent.com/assets/5641963/5991540/25824bbe-a9f5-11e4-9615-29bca41fcd61.jpg)
I only changed a part of the formatPendingChangesLink function with the part below and retrieved the rest from the BaseTheme:
>>return $this->htmlAlert($this->pendingChangesLink(), 'info', true);

I now have moved all the needed code to the theme class file. But I hope you reconsider the removal of the functions pendingChangesLink and pendingChangesLinkText from the BaseTheme.

**Comment by JustCarmen** [comment]
Wow, you are quick :)

**Comment by fisharebest** [comment]
It doesn't take long to type `git revert 3367091`, `git push` ;-)
