### ISSUE TITLE
NPM run production error

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4091]
On `npm run production`, I get [webpack-cli] Error: Cannot find module 'autoprefixer'. To ensure it was a real error, I cleared out the node_modules folder and ran `npm install` afresh. Still got error

adding  `"autoprefixer": "^10.3.7"`, to the dependencies section of package.json fixed it

**Comment by fisharebest** [comment]
I guess it used to be included as a dependency of a dependency - and now we need to include it explicitly.
