### ISSUE TITLE
Github search position

### ISSUE THREAD

**Issue by slavkoja** [fisharebest/webtrees#4095]
I do not know what happen, but recently i need to find this repo, and it was bot in first 100 search results. Then i noticed, that here is only one star and zero forks. At the first position of search results is this one repo https://github.com/jon48/webtrees

What happens? Is it intended/expected?

**Comment by jon48** [comment]
Great! They restored it very quickly indeed.
Interestingly enough, I still see jon48/webtrees with 242 forks (up from 240 yesterday), but all the forks refer correctly to fisharebest/webtrees as their parent. The 2 repositories may have been "symlinked" in some ways from the forks perspective, so hopefully that will not cause any issue in the future.

@slavkoja : That was my initial intention to add a link in the description, but it appears to be a plain text field, where neither Markdown or HTML tabs work.

**Comment by fisharebest** [comment]
> I still see jon48/webtrees with 242 forks 

I saw that - but it shows the same network/tree for *everyone* - not just you.
