### ISSUE TITLE
When "citation details" or "text" added to sources then the grouping doesn't work

### ISSUE THREAD

**Issue by ungeahnt** [fisharebest/webtrees#4097]
related to #3027 

Look at wt demo-dev (e.g. [David Armstrong-Jones, Viscount Linley - Birth](https://dev.webtrees.net/demo-dev/tree/demo/individual/I10115/David-Armstrong-Jones-Viscount-Linley#)) and you see (red markings):

![grafik](https://user-images.githubusercontent.com/28572767/139523395-abd49693-a3bb-45dc-b11e-09eaa5816a14.png)

**Comment by ungeahnt** [comment]
same with associate and its sources

Before (=no text filled in):

![grafik](https://user-images.githubusercontent.com/28572767/139523890-93b44ee0-6012-4f5f-83e6-803e81c8ec82.png)

After filling in text, no more grouping and you see additional items (like 'Text', 'source citation' and 'Associate') :
![grafik](https://user-images.githubusercontent.com/28572767/139523969-a706ae31-c8ca-44ad-bd1a-55bf619c23d6.png)

**Comment by ungeahnt** [comment]
Btw: the grouping looks nice!

**Comment by ungeahnt** [comment]
Related to 'Associate':  in wt 2.0 it was possible to add a media object directly to the 'Associate'. In the current dev version I don't find this option anymore. Is this intentional?

**Comment by fisharebest** [comment]
> After filling in text, no more grouping 

The edit form collapses certain GEDCOM structures - but only when they are empty.

> and you see additional items (like 'Text', 'source citation' and 'Associate')

The GEDCOM specification allows you to have multiple `TEXT` fields in a source-citation.

<img width="758" alt="Screenshot 2021-10-30 at 10 46 37" src="https://user-images.githubusercontent.com/2306088/139528162-4c3bddac-cc74-4238-8beb-c14becdabb1b.png">

> Related to 'Associate': in wt 2.0 it was possible to add a media object directly to the 'Associate'. In the current dev version I don't find this option anymore. Is this intentional?

In webtrees 2.1, we follow the GEDCOM specification much more closely.  You are not allowed to add media to an association.  (But you can add media to a source-citation, and add the source-citation to the association.)

<img width="760" alt="Screenshot 2021-10-30 at 10 44 13" src="https://user-images.githubusercontent.com/2306088/139528091-beabe9fd-9122-4d2f-af67-c2acb9766745.png">

**Comment by ungeahnt** [comment]
> 
> The edit form collapses certain GEDCOM structures - but only when they are empty.

You mean it is only grouped when editing an empty field for the first time and not after that? Is this intentional and should it remain?

That would mean if I want to edit an existing entry (like the 2nd image in https://github.com/fisharebest/webtrees/issues/4097#issuecomment-955163868) , then I have again only a long listing of all possible items without grouping and I can't distinguish again what belongs where?

Why not show the grouping permanently?

> > and you see additional items (like 'Text', 'source citation' and 'Associate')
> 
> The GEDCOM specification allows you to have multiple `TEXT` fields in a source-citation.

see https://github.com/fisharebest/webtrees/issues/4098#issuecomment-955187022

**Comment by fisharebest** [comment]
> You mean it is only grouped when editing an empty field for the first time and not after that? Is this intentional and should it remain?

It is only **collapsed** when it is empty.

If any of the fields have data, then it is expanded

**Comment by ungeahnt** [comment]
Thanks!
