### ISSUE TITLE
Empty "Media objects" / "source citation" not necessary when items exists (-> + button)

### ISSUE THREAD

**Issue by ungeahnt** [fisharebest/webtrees#4098]
related to #3027 

Look at wt demo-dev (e.g. [David Armstrong-Jones, Viscount Linley - Birth](https://dev.webtrees.net/demo-dev/tree/demo/individual/I10115/David-Armstrong-Jones-Viscount-Linley#)) and you see (blue markings):

![grafik](https://user-images.githubusercontent.com/28572767/139523395-abd49693-a3bb-45dc-b11e-09eaa5816a14.png)

**Comment by fisharebest** [comment]
You have one existing source-citation (wikipedia).

There are also empty fields to enter a second source-citation.

How else can you add an additional source-citation?

**Comment by ungeahnt** [comment]
> You have one existing source-citation (wikipedia).
> There are also empty fields to enter a second source-citation.

I've thought that when I click on the + button I will add one additional item. I must have been wrong

> How else can you add an additional source-citation?

However, I find it confusing to display (multiple) empty boxes that I don't need for now. Couldn't these be grouped together and then displayed in a drop-down menu (similar to 'add a fact' on the INDI page)?

This would help a lot for clarity.

**Comment by fisharebest** [comment]
> I've thought that when I click on the + button I will add one additional item. I must have been wrong

The plus button creates a completely new source (which you can then use in the source-citation).

> However, I find it confusing to display (multiple) empty boxes that I don't need for now.

The multiple boxes are only visible because you expanded the second (empty) source-citation.

They are collapsed by default.

**Comment by ungeahnt** [comment]
> The plus button creates a completely new source (which you can then use in the source-citation).

Your are absolutely right, of course. 
 
> > However, I find it confusing to display (multiple) empty boxes that I don't need for now.
> 
> The multiple boxes are only visible because you expanded the second (empty) source-citation.
> They are collapsed by default.

That's correct only for the first edit. Afterwards you will see all boxes again (see https://github.com/fisharebest/webtrees/issues/4097#issuecomment-955163868). That's very confusing (at least for me). Why not use permanently the grouping and folding function?
Futhermore the 'add boxes' looks identical with 'existing boxes' and you have a mix of it in a long list. Therefore my suggestion/question:

_Couldn't these be grouped together and then displayed in a drop-down menu (similar to 'add a fact' on the INDI page)? This would help a lot for clarity._

... or set the 'add-boxes' otherwise in the background, e.g. with gray/smaller font or by a text addition (e.g. "Add a source citation" instead of just "source citation")

For me is this issue connected with #4097. If wt groups the items permanently, then these multiple boxes are not so annoying, but if (after the first edit) you have everything in one long list again (without grouping), then it would be helpful if these 'add-boxes' are at least visually different somehow.

**Comment by fisharebest** [comment]
> Why not use permanently the grouping and folding function?

Because you do not want to hide fields that contain data.

We only hide GEDCOM structures that are empty.  e.g.

* new source citations
* new associates
* etc.

**Comment by ungeahnt** [comment]
Thanks!
