### ISSUE TITLE
Request: add map provider - osMap

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#4099]
[osMap](https://wiki.openstreetmap.org/wiki/OsMap) is a group of OSM Carto-style world maps **in one language**. Unlike osm.org, where the map is in the local language of the country or region. It serves ten different versions with name displays in Czech, Danish, Dutch, English, French, German, Italian, Polish, Portuguese and Spanish. Transliteration and fallbacks are used if no name:xx tag is available in the said language.

**Maps**
Czech: [https://www.osmapa.cz](https://www.osmapa.cz)
Danish: [https://www.osmap.dk](https://www.osmap.dk)
Dutch: [https://www.osmap.nl](https://www.osmap.nl)
English: [https://www.osmap.uk](https://www.osmap.uk)
French: [https://www.osmap.fr](https://www.osmap.fr)
German: [https://www.osmap.de](https://www.osmap.de)
Italian: [https://www.osmappa.it](https://www.osmappa.it)
Polish: [https://www.osmap.pl](https://www.osmap.pl)
Portuguese: [https://www.osmap.pt](https://www.osmap.pt)
Spanish: [https://www.osmap.es](https://www.osmap.es)

**Comment by fisharebest** [comment]
I do not think that osmap would allow other projects to use their tileservers.

According to the only documentation on the site - https://www.osmap.uk/contact.html - they ask other projects to use a commercial map-tile service:

> If you want to use the tiles used at osMap for your own projects, please visit MapTiles API.
