### ISSUE TITLE
background color of cradle icon in Locations tab: blue for boys, pink for girls

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#4101]
In the Locations tab, the birthplace icon is displayed with a white cradle on a pink background.

Can this be changed to a blue background for boys and a pink background for girls?

**Comment by fisharebest** [comment]
Note - the original author of this module was British, and UK birth/marriage/death certificates are pink/green/black.

Hence events related to birth (BIRT, BAPM, CHR) are pink, etc.

Just changing birth to blue would be inconsistent.  Plus we'd need a third colour for unknown.

So, we'd need definitions for each combination of event-type and gender.

The existing defintions are here: https://github.com/fisharebest/webtrees/blob/main/app/Module/PlacesModule.php#L41-L56

Also, would you distinguish between birth of the individual, and the birth of their children?

**Comment by TheDutchJewel** [comment]
> Plus we'd need a third colour for unknown.

Gray is fine for unknown.


>Also, would you distinguish between birth of the individual, and the birth of their children?

Based on the use of color in webtrees (blue for men, pink for women), it doesn't make sense.


But thanks for the clarification.

I was not aware that the colors were related to English deeds. Let's leave it at that.
