### ISSUE TITLE
edit and collapse: indention jumps to the leftmost edge of the screen

### ISSUE THREAD

**Issue by ungeahnt** [fisharebest/webtrees#4102]
related to https://github.com/fisharebest/webtrees/commit/aa936b04932cfc43da6708c7f93a6da0fffe6c40 ... and thanks a lot for the fix!

But when adding a second (sub)collapse, the indention jumps to the leftmost edge of the screen and breaks the uniformity (see picture below -> Associate)

![grafik](https://user-images.githubusercontent.com/28572767/139592258-d02ae1d8-b25e-4352-be9b-2c00e3313627.png)

**Comment by fisharebest** [comment]
Thanks for the feedback and testing.
