### ISSUE TITLE
Differences between Add & Edit Media object

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#4107]
When you Add a new media object the option to add a source or shared note is missing, but there is an extra menu to set editing restriction. When you Edit an existing media object then you can add a source or shared note, but you only have one drop-down box to set a restriction (combined for privacy & editing).

Shouldn’t the Add & Edit menu have the same possibilities (add source, shared note) and have the same look (one or two dropdown boxes for restrictions)?

**Comment by fisharebest** [comment]
The GEDCOM specification only allows one RESN tag on each record/fact.

webtrees can work with two RESN tags, but I guess we should not create non-standard data.

I will combine these two fields

**Comment by SnarfW** [comment]
Thanks for your response on the RESN.
But still the option to add a source or shared note is missing when you add a new media event. Shouldn’t this be possible?

**Comment by fisharebest** [comment]
Please only raise one thing in each issue.  It is difficult to manage issues that contain multiple things.

See #1448
