### ISSUE TITLE
Bugs in the production tree system's Babo site. 1.8.0-dev 

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#4110]
Greg,

In the 1.8.0-dev production tree site, I get errors for the Babo data Birth, and Vital records reports (without filling any surname for the reports), and in the unknown and all individuals and families lists. I see the reports and lists as expected in the 2.1.0-dev test system, in the Glück tree, and for specific surnames in both systems.

I exported the Babo Gedcom file.
The Gedcom file looks OK.

I looked one by one at the Babo tree individuals who have an unknown surname and detected errors for
I278, I79, and their family F115. Additional errors may also exist.

Should I import the file to the test system and if it looks OK import it again to the tree production site?

Meliza

The errors that I see are:
I278
1 NAME Lars //
2 GIVN Lars
/home/amitys/tree.amitys.com/includes/session.php:193 /home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null #0 /app/Individual.php:1116 ErrorException("/home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null") #1 /app/GedcomRecord.php:608 addName() #2 /app/GedcomRecord.php:732 getAllNames() #3 /app/Module/FamilyNavigatorModule.php:186 getFullName() #4 /app/Module/FamilyNavigatorModule.php:248 getHTML() #5 /app/Module/FamilyNavigatorModule.php:153 getFamily() #6 /app/Module/FamilyNavigatorModule.php:85 drawFamily() #7 /app/Controller/IndividualController.php:376 getSidebarContent() #8 /individual.php:48 getSideBarContent()

I279
1 NAME Erland /Kafle/
2 GIVN Erland
2 SURN Kafle
1 SEX M
1 BIRT Y
1 FAMS @F155@
/home/amitys/tree.amitys.com/includes/session.php:193 /home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null #0 /app/Individual.php:1116 ErrorException("/home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null") #1 /app/GedcomRecord.php:608 addName() #2 /app/GedcomRecord.php:732 getAllNames() #3 /app/Module/FamilyNavigatorModule.php:186 getFullName() #4 /app/Module/FamilyNavigatorModule.php:248 getHTML() #5 /app/Module/FamilyNavigatorModule.php:153 getFamily() #6 /app/Module/FamilyNavigatorModule.php:93 drawFamily() #7 /app/Controller/IndividualController.php:376 getSidebarContent() #8 /individual.php:48 getSideBarContent()

F155
/home/amitys/tree.amitys.com/includes/session.php:193 /home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null #0 /app/Individual.php:1116 ErrorException("/home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null") #1 /app/GedcomRecord.php:608 addName() #2 /app/GedcomRecord.php:732 getAllNames() #3 /app/Theme/AbstractTheme.php:998 getFullName() #4 /app/Theme/AbstractTheme.php:955 individualBoxMenuFamilyLinks() #5 /app/Theme/AbstractTheme.php:759 individualBoxMenu() #6 /app/Functions/FunctionsPrint.php:57 individualBox() #7 /app/Functions/FunctionsCharts.php:341 printPedigreePerson() #8 /family.php:77 printFamilyChildren()

Individual list of Undefined names
/home/amitys/tree.amitys.com/includes/session.php:193 /home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null #0 /app/Individual.php:1116 ErrorException("/home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null") #1 /app/GedcomRecord.php:608 addName() #2 /app/Query/QueryName.php:495 getAllNames() #3 /indilist.php:261 individuals()

All individuals list gives
/home/amitys/tree.amitys.com/includes/session.php:193 /home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null #0 /app/Individual.php:1116 ErrorException("/home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null") #1 /app/GedcomRecord.php:608 addName() #2 /app/GedcomRecord.php:643 getAllNames() #3 /app/Individual.php:1065 getPrimaryName() #4 /app/Functions/FunctionsPrintLists.php:353 getPrimaryParentsNames() #5 /indilist.php:261 individualTable()

Family list of Kafle
/home/amitys/tree.amitys.com/includes/session.php:193 /home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null #0 /app/Individual.php:1116 ErrorException("/home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null") #1 /app/GedcomRecord.php:608 addName() #2 /app/Functions/FunctionsPrintLists.php:54 getAllNames() #3 /app/Functions/FunctionsPrintLists.php:823 sortableNames() #4 /famlist.php:261 familyTable()

Birth report
/home/amitys/tree.amitys.com/includes/session.php:193 /home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null #0 /app/Individual.php:1116 ErrorException("/home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null") #1 /app/GedcomRecord.php:608 addName() #2 /app/GedcomRecord.php:732 getAllNames() #3 /app/Report/ReportParserGenerate.php:848 getFullName() #4 /app/Report/ReportParserGenerate.php:157 getPersonNameStartHandler() #5 unknown:unknown startElement() #6 /app/Report/ReportParserGenerate.php:2267 xml_parse() #7 /app/Report/ReportParserGenerate.php:178 listEndHandler() #8 unknown:unknown endElement() #9 /app/Report/ReportParserBase.php:43 xml_parse() #10 /app/Report/ReportParserGenerate.php:128 __construct() #11 /reportengine.php:282 __construct()

Vital records report
/home/amitys/tree.amitys.com/includes/session.php:193 /home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null #0 /app/Individual.php:1116 ErrorException("/home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null") #1 /app/GedcomRecord.php:608 addName() #2 /app/GedcomRecord.php:732 getAllNames() #3 /app/Report/ReportParserGenerate.php:848 getFullName() #4 /app/Report/ReportParserGenerate.php:157 getPersonNameStartHandler() #5 unknown:unknown startElement() #6 /app/Report/ReportParserGenerate.php:1091 xml_parse() #7 /app/Report/ReportParserGenerate.php:178 repeatTagEndHandler() #8 unknown:unknown endElement() #9 /app/Report/ReportParserGenerate.php:2267 xml_parse() #10 /app/Report/ReportParserGenerate.php:178 listEndHandler() #11 unknown:unknown endElement() #12 /app/Report/ReportParserBase.php:43 xml_parse() #13 /app/Report/ReportParserGenerate.php:128 __construct() #14 /reportengine.php:282 __construct()

**Comment by melizaa** [comment]
I tried to import the file copy renamed baboProdNew.ged from my Laptop to BaboProdNew.
0% has been processed and I see
/home/amitys/tree.amitys.com/includes/session.php:193 /home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null #0 /app/Individual.php:1116 ErrorException("/home/amitys/tree.amitys.com/app/Individual.php:1116 Trying to access array offset on value of type null") #1 /app/GedcomRecord.php:608 addName() #2 /app/Functions/FunctionsImport.php:936 getAllNames() #3 /app/Functions/FunctionsImport.php:657 updateNames() #4 /import.php:214 importRecord()

I see now that I intended to import it to the tree production system and not to the test system.

How can I stop this process?

**Comment by fisharebest** [comment]
> Trying to access array offset on value of type null

This error usually indicates that you are using webtrees 1.7 with PHP 7.4.

> How can I stop this process?

You can abort this process by deleting all the rows in the table `wt_gedcom_chunk`

**Comment by melizaa** [comment]
Yes, my tree production site with (QMF tables wtt) should be defined the same way as the production webtrees site (QMF tables w) is defined, with webtrees 1.8-DEV and the old PHP (5.6-7.3).

The future test site (QMF tables wt) and the test test site (QMF tables wtb) should use webtrees 2.1.0-dev and PHP 7.4.

Perhaps the tree folder uses PHP 7.4? Please correct this.

I emptied the future test wt_gedcom_chunk. I see still the error on the manage family trees of the tree production system (QMF wtt). Should I also delete all the rows of the table wtt_gedcom_chunk in order to abort the process?

**Comment by melizaa** [comment]
I imported the Babo production GEDCOM file to the test test system and I see all the data as expected.

In the production tree site, I emptied the Babo's production tree wtt_gedcom_chunk and deleted the Babo production GEDDCOM file copy. Now the two remaining trees are working, but the Babo site gives still the errors probably because of **webtrees 1.8-dev and PHP 7.4.**

**Comment by melizaa** [comment]
I see that my webtrees production site uses PHP Version 7.3.31-2+ubuntu18.04.1+deb.sury.org+1.
The tree production site uses still PHP Version 7.4.25.

**Comment by melizaa** [comment]
Greg, 
Let's wait a day or two with the PHP downgrade in the tree production site.

I will test the behaviour of Babo and Glück data in 2.1.0.
Perhaps I should upgrade the code.

**Comment by fisharebest** [comment]
I always need to spend a lot of time working out the different parts of your site.

So, I think we have this:

| URL | PHP | database | webtrees |
| - | - | - | - |
| `www.amitys.com/webtrees` | 7.3 | `w_` | 1.7 |
| `www.amitys.com/test` | 7.4 | `wtb_` | `2.1` |
| `www.amitys.com/future` | 7.4 |`wt_` | `2.1` |
| `tree.amitys.com`| 7.4 | `wtt_` | `1.7` |

The only inconsistency is the last row - this should be PHP 7.3.  I have now changed this.  The reported errors now disappear.

**Comment by melizaa** [comment]
Many thanks!
