### ISSUE TITLE
Incorrect identification of media type

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4112]
Function MediaFile::isImage() returns true based on the file extension, however it is possible to have images that are scans of documents and these shouldn't really be shown on the individual page main photo.

I suggest that the media type should also be considered

**Comment by fisharebest** [comment]
I have lots of non-photo images that I want to be used as the primary/default image for an individual.

e.g. coat-of arms, statue, gravestone, etc.

**Comment by ddrury** [comment]
What about those you don't want to display?

**Comment by fisharebest** [comment]
> What about those you don't want to display?

webtrees only looks for images attached to the individual - not to images attached to facts/events.

> images that are scans of documents

I can't think of a case where I would have such a media file, and would not have a fact/event/source to which it would be attached.


Birth certificate - attach to the BIRT event.
Will - attach to a WILL event.
etc.
