### ISSUE TITLE
Markdown Links Are Broken 😢

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#4114]
I use markdown links extensively throughout my tree within source text, event text, and shared notes.  After upgrade to 2.0.17, there are major problems.

I'm not seeing any trouble with the shared notes Details tab.

But then on individual's Sources tab all of my `[description](https://address)` markdown is being rendered as `<a href="[description](https://address)">[description](https://address)</a>`

It also looks like some links separated by newlines are being concatenated.

```
[description1](https://address1)
[description2](https://address2)
```

now renders as

```
<a href="[description1](https://address1) [description2](https://address2)">[description1](https://address1) [description2](https://address2)</a>
```

😭

**Comment by miqrogroove** [comment]
In one instance I see a full obituary, followed by two new lines, followed by a markdown link, and the entire text of the obituary is appearing inside the link text now.

**Comment by miqrogroove** [comment]
As seen on dev site...

![markdown-fail](https://user-images.githubusercontent.com/1371835/140769476-364942fc-405e-4d5d-bb8c-8f9348f48739.png)

**Comment by miqrogroove** [comment]
Also, in these same text fields where markdown links are broken, markdown tables are also broken and seem to render as plain text with newlines stripped.

**Comment by fisharebest** [comment]
```
[description1](https://address1)
[description2](https://address2)
```

I just pasted this into the SOUR:TEXT field on the demo server.

The links render as expected

<img width="597" alt="Screenshot 2021-11-12 at 16 33 11" src="https://user-images.githubusercontent.com/2306088/141501422-cc744ee3-7774-4930-a4f1-9c2ec04187fd.png">


However, these should be on one line (according to markdown definitions).  This is caused by CSS, which should probably be removed.

<img width="354" alt="Screenshot 2021-11-12 at 16 36 24" src="https://user-images.githubusercontent.com/2306088/141501875-29572c52-7957-4a08-a63e-4acd0fc694bb.png">

**Comment by miqrogroove** [comment]
So why is your screenshot different from mine?  Is it fixed already?

**Comment by fisharebest** [comment]
I took that screenshot from the demo site.

Which version are you using - 2.0.17 or 2.1.0-dev

**Comment by miqrogroove** [comment]
We are still missing ALL line breaks from every note and every markdown on the entire site.  Can we fix this or should I restore my database for v2.0.16?  😥

**Comment by miqrogroove** [comment]
Notes that were beautifully formatted in every version before 2.0.17 are now ugly and difficult to read.

![webtrees-screen](https://user-images.githubusercontent.com/1371835/145214002-18799b66-8af1-4b09-94d1-a49f19b00047.png)
