### ISSUE TITLE
Create one combined historic events module

### ISSUE THREAD

**Issue by Lars1963** [fisharebest/webtrees#4121]
As discussed here: https://www.webtrees.net/index.php/en/forum/help-for-2-0/36271-historic-facts-place#88216

How about combining all historic events into one file, enhanced with translation and "PLAC" and maybe a tag for original language? If desired more events can then be added by pull requests.

As Alternative to #3927

**Comment by fisharebest** [comment]
Modules can already provide different translations, if needed.

I have updated the code to make this clearer.

We don't need to translate every event into every language.  e.g. nobody outside Korea will be interested in Korean events.

I have updated the code to only show events that match the current language.
