### ISSUE TITLE
Markdown formatting

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4123]
Here are a few comments based on this thread in the forum https://www.webtrees.net/index.php/en/forum/help-for-2-0/36162-v2-0-17-things-that-no-longer-work-after-update#88276, commit https://github.com/fisharebest/webtrees/commit/b6b785a1da4d8c051f96d8525d89e5f6e3d6e201 and pull request https://github.com/fisharebest/webtrees/pull/4115

- It is clear that formatting for markdown encoded text containing line/paragraph breaks goes further than just shared notes.
- The commit mentioned above only addressed the first line break in each census assistant part. My pull request fixes that insofar as each line break is considered a paragraph and is changed to a `<li>` element, nevertheless it is simple to adapt should the change to unordered lists be considered unnecessary.
- Only notes created after the above mentioned code changes are affected. A data fix is needed to apply the formatting changes to existing plain text content that contains line/paragraph breaks where that text needs to be interpreted as markdown.

**Comment by ddrury** [comment]
Thinking further why not do all the processing on display and only do sufficient on creation (ie just add as many newlines as necessary to indicate whats required)

**Comment by fisharebest** [comment]
> only addressed the first line break in each

Can you give any specific examples of what isn't currently working?

**Comment by ddrury** [comment]
Specifically:
Add more than one paragraph to any of the census assistant fields, only the first paragraph gets the double space added to the `\n`. Practically this only really applies to the comments section, but for completeness should target each field.

Other things that don't work are formatting for notes attached to sources or media.

Blowing my own trumpet, all these "problems" are addressed in https://github.com/fisharebest/webtrees/pull/4128

**Comment by fisharebest** [comment]
67721f6fe545e33878bd31b73a960fe472601f42 adds a new config option - "markdown with line breaks"
