### ISSUE TITLE
Fix for cell content exceeding width of container table

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4129]
(Not the most elegant fix)

For tables with class wt-fact-table set table-layout to fixed and add a Colgroup to set the colum widths

**Comment by ddrury** [comment]
Actually don't need to set table-layout, just add colgroup

**Comment by fisharebest** [comment]
I tried this, and couldn't make it work.

**Comment by ddrury** [comment]
resources/views/modules/personal_facts/tab.phtml starting at line 22

```
<div class="wt-tab-facts py-4">
    <table class="table wt-facts-table">
      <colgroup>
        <col style="width:20%">
      </colgroup>
        <tbody>
         etc...
```

css

```
.wt-tab-facts .wt-facts-table {
    table-layout: fixed;
}
```
