### ISSUE TITLE
v2.0.19 - multi-line level 2 notes (2 NOTE / 3 CONT) are displayed without line breaks

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#4130]
In version 2.0.19 with enabled markdown for text and notes, multi-line level 2 notes (`2 NOTE / 3 CONT`) are displayed without line breaks.

Tested also on the demo server:
![afbeelding](https://user-images.githubusercontent.com/46184729/144722700-b2a3852c-bfb8-4e22-ac51-b8d3828c1055.png)

**Comment by Norwegian-Sardines** [comment]
It works on the demo server, when you follow each line with two (2) spaces as indicated in the markdown documentation.

Line Breaks
To create a line break (<br>), end a line with two or more spaces, and then type return.

**Comment by TheDutchJewel** [comment]
It's good to follow the markdown rules.

But that doesn't mean that support for GEDCOM linebreaks should be dropped.

Thanks to [ric2015](https://www.webtrees.net/index.php/en/forum/help-for-2-0/36316-note-cont-missing-line-breaks-2-0-19#88495) this is fortunately supported again, but it would be even better if this was also supported by webtrees itself.

**Comment by Norwegian-Sardines** [comment]
Yes I agree that something should change at the core so that the GEDCOM can remain without changes, but this then becomes a design change to the original design implementation of markdown for webtrees.  The problem always is that users who have embraced webtrees/markdown by the book, may have some unwanted outcomes as well or made changes long ago to support the design.

The use of markdown in future releases of webtrees may need to be reviewed when GEDCOM v7 is embraced!  One of the features of the “text” type in v7 is the use of HTML in the body of the text.  The use of HTML formatting in NOTEs is already used by many programs (which I was against) and has been incorporated into v7.  This may be the way to format text in the future since incoming GEDCOM files will already have it, and we should preserve as much of the GEDCOM as possible, in particular for those people who don’t use webtrees exclusively.

I’ve become tired of all of this and will now back away unless asked for more comment!

**Comment by SnarfW** [comment]
When I enter this in a note field:

![afbeelding](https://user-images.githubusercontent.com/25879600/144752932-c6eb8148-7dcb-43eb-8b82-20def9e31b06.png)

Then I am expecting that the note appears like this on the website. It would be very helpfull when Webtrees could check whether the 2 spaces, required by markdown, are added, and when need would automatically add them.

**Comment by Norwegian-Sardines** [comment]
Some areas work correctly while others do not.  See this issue [https://www.webtrees.net/index.php/en/forum/help-for-2-0/36316-note-cont-missing-line-breaks-2-0-19?start=20#88569](url)

**Comment by miqrogroove** [comment]
See also #4114  This was a regression in v2.0.17 and makes me a little angry.  I literally can't read some of my notes anymore unless I open the fact editor.

**Comment by fisharebest** [comment]
67721f6fe545e33878bd31b73a960fe472601f42 adds a new config option - "markdown with line breaks"

**Comment by Norwegian-Sardines** [comment]
I don’t think this fixes the problem outline here. https://www.webtrees.net/index.php/en/forum/help-for-2-0/36316-note-cont-missing-line-breaks-2-0-19?start=20#88569

**Comment by fisharebest** [comment]
Please give an example of what is not working.

<img width="739" alt="Screenshot 2021-12-20 at 08 08 30" src="https://user-images.githubusercontent.com/2306088/146733703-7f3c0a8c-72d1-40d6-9523-5083221a861a.png">
<img width="332" alt="Screenshot 2021-12-20 at 08 08 12" src="https://user-images.githubusercontent.com/2306088/146733710-58124b0c-b0b4-4c49-af7b-365b519d7d53.png">
<img width="225" alt="Screenshot 2021-12-20 at 08 07 41" src="https://user-images.githubusercontent.com/2306088/146733713-e4688944-2ec3-428b-84db-23d7ee688097.png">

**Comment by fisharebest** [comment]
And with markdown, we have line breaks and a paragraph break

<img width="191" alt="Screenshot 2021-12-20 at 08 10 43" src="https://user-images.githubusercontent.com/2306088/146733988-bf2ecbee-7120-4b5d-bab8-3189d5cb10f6.png">
<img width="755" alt="Screenshot 2021-12-20 at 08 10 21" src="https://user-images.githubusercontent.com/2306088/146733989-cde43162-9bf5-4c3a-9b07-e495a998e84e.png">

**Comment by fisharebest** [comment]
And with standard markdown:

<img width="274" alt="Screenshot 2021-12-20 at 08 12 05" src="https://user-images.githubusercontent.com/2306088/146734123-060e2dd6-de82-4c82-b951-0b103d6a0565.png">
<img width="738" alt="Screenshot 2021-12-20 at 08 11 53" src="https://user-images.githubusercontent.com/2306088/146734125-e0a3b90f-b854-4ad7-8378-01c52de81fe2.png">

**Comment by Norwegian-Sardines** [comment]
I'd love to test your changes, but I would have no idea how to download the files from Git without a release.  

I only had issues with "Plain Text" line breaks on Fact Citation Display Notes, Fact Display Notes and Shared Notes Text.  So if these areas were also addressed with this fix then we are good!
