### ISSUE TITLE
v2.0.19 - Proxy not available in associates drop-down menu

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#4131]
'Proxy' is not available in the associates drop-down menu, even though it is in [appElementsRelationIsDescriptor.php](https://github.com/fisharebest/webtrees/blob/cc4c83a826365b2c6c1f20f9c23ab588f402f280/app/Elements/RelationIsDescriptor.php#L119):
![afbeelding](https://user-images.githubusercontent.com/46184729/144737887-1ed426f8-1a92-4a5c-bf84-181e86247199.png)

**Comment by fisharebest** [comment]
This relationship type was added to the 2.1 branch of the code, and will be included in the 2.1.0 release.
