### ISSUE TITLE
GEDCOM-L custom GEDCOM tags in webtrees 2.1

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#4134]
In the webtrees 2.1 module, which implements the GEDCOM-L tags, these tags are defined, but it is not defined how often each tag can be used. For example, there is a definition in the GEDCOM-L Addendum under _LOC:
` _MAIDENHEAD <MAIDENHEAD_LOCATOR> {0:1}`
But webtrees offers to add more than one tag of this type. But this makes no sense for a maidenhead locator.

Would it be helpful when I provide a function customSubTags() for this module?

**Comment by fisharebest** [comment]
> but it is not defined how often each tag can be used

It is defined here:

https://github.com/fisharebest/webtrees/blob/ae0043b720d44ad147874b2a3afe4e7a347c314a/app/Elements/LocationRecord.php#L33

> But webtrees offers to add more than one tag of this type.

Does it?  If I create a `_LOC` record, I can only add one maidenhead locator.

Can you provide the exact steps to reproduce this issue?

**Comment by hartenthaler** [comment]
I was not able to reproduce it, too. I have seen it when using "Edit"/"Edit with all GEDCOM tags". There was a line with an existing maidenhead locator and a new line for the same tag offering to add a new one. But now everything works as expected.
