### ISSUE TITLE
Version 2.1.0-alpha.1 and PHP 8.1

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#4137]
Using PHP 8.0 is ok, but when using PHP 8.1 I get the following error when opening any page
`During inheritance of SessionHandlerInterface: Uncaught ErrorException: Return type of Fisharebest\Webtrees\SessionDatabaseHandler::gc($max_lifetime): bool should either be compatible with SessionHandlerInterface::gc(int $max_lifetime): int|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/app/SessionDatabaseHandler.php:148 Stack trace: #0 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/app/SessionDatabaseHandler.php(29): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}() #1 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/vendor/composer/ClassLoader.php(571): include('...') #2 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile() #3 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/app/Session.php(64): Composer\Autoload\ClassLoader->loadClass() #4`

**Comment by fisharebest** [comment]
This is an issue in the aura.router library.

I have already submitted a fix - https://github.com/auraphp/Aura.Router/pull/176

Just waiting for it to be accepted.

**Comment by fisharebest** [comment]
See #4141

**Comment by fisharebest** [comment]
My PR was accepted.  It's not yet been released, but we can use the `4.x-dev` branch.

2.1.0-alpha.2 is now released, with all (known) PHP 8.1 issues fixed.
