### ISSUE TITLE
Level 1 Media Objects (INDI and FAM pages) ignor RESN "none" when global restriction is set to "show to members"

### ISSUE THREAD

**Issue by Norwegian-Sardines** [fisharebest/webtrees#4139]
See https://www.webtrees.net/index.php/en/forum/help-for-2-0/36349-media-permissions-question#88718

Basically, if I set Media Object at the Tree Level to Show to Members, then set specific Media Objects to Show to Visitors,  The LEVEL 1 OBJE do not honor the RESN none setting, but LEVEL 2 OBJE tags do honor the RESN none setting.

**Comment by fisharebest** [comment]
Interesting...

We have one setting that is used for both level 0 and level 1 records.

> if I set Media Object at the Tree Level to Show to Members

With these settings, we now have a conflict.

We are checking the level 1 record (which is private, according to privacy rules).
We are not checking the linked level 0 record (which is public, according to restriction).

Simple to fix.  A little surprised nobody noticed before, as this logic hasn't changed for a very long time...
