### ISSUE TITLE
Aura Router appears to be abandoned - need a replacement

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#4141]
[Aura Router](https://github.com/auraphp/Aura.Router) hasn't been updated for a long time.

A [pull request](https://github.com/auraphp/Aura.Router/pull/176) to add compatibility with PHP 8.1 hasn't been acknowledged.

The [contributing guide](https://github.com/auraphp/Aura.Router/blob/3.x/CONTRIBUTING.md) warns there may be no immediate feedback - however we need support for PHP8.1 before we can release webtrees 2.1.

Our options are to find a replacement (symfony?) or write our own replacement.

**Comment by Lars1963** [comment]
IMHO the simpliest solution for now is to fork `Aura Router`, add your PR on it and use this fork. You the have time to find a better replacement for 2.1.x (or 2.2?) and you can solve the remaning php8.1 issues for the upcoming 2.1 Release first.

**Comment by harikt** [comment]
Hey, 

I am one of the members of the core team. If the PR fixes 8.1 issue we will happily merge it. I somehow missed to see this. I will not blame you guys for forking and releasing your own as you need.

Note : One of our teammate has been working on 8.x release : https://github.com/auraphp/Aura.Router/pull/177.

No one is paid, so it is when we get some time we are doing it.

Again thanks for your patience.
