### ISSUE TITLE
Missing bits of markdown-br

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4142]
`resources/views/note-page-details.phtml` ~ line 36

Control panel - Manage media (`app/Http/RequestHandlers/ManageMediaData::mediaObjectInfo()`) ~line 279

**Comment by ddrury** [comment]
BTW, when is the plain markdown option useful?

**Comment by Norwegian-Sardines** [comment]
Dave,  Are you referring to the CONT issue when markdown is turned off?  I'm not a "Git" person so I can't test fixes until they are released!

**Comment by ddrury** [comment]
@Norwegian-Sardines 

>  Are you referring to the CONT issue 

Sort of. Commit https://github.com/fisharebest/webtrees/commit/67721f6fe545e33878bd31b73a960fe472601f42 by Greg introduces a new tree option for text preferences. Where previously the options were "plain text" and "markdown" we now have a 3rd option "markdown with line-breaks" which solves the CONT problem, however, the two areas I've mentioned above still exhibit the problem.

**Comment by Norwegian-Sardines** [comment]
I’m assuming then that, with plain text only, the CONT tags are still not honored.  This is what I outlined in my entry, I’m not concerned at all about the new third option.  I’ll wait for a release (.20) then create a new instance of webtrees with markdown turned off and check SOUR.TEXT and FACT.NOTE and other level 3 NOTE, 3 TEXT behavior.
