### ISSUE TITLE
Possibly duplicate css

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4144]
Assuming all markdown tables are wrapped in `<div class="table-responsive"></div>` who's css contains `overflow-x: auto;` then that css is not necessary for class markdown.

**Comment by fisharebest** [comment]
`table-responsive` will scroll the table independently of the surrounding text.

`.markdown { overflow-x: auto; }` will scroll the entire block of markdown.  For example, if there is a very long word with no spaces.

An alternative might be `overflow-wrap: break-word;`.
