### ISSUE TITLE
Call number can not be entered if repository has already already been assigned before without call number

### ISSUE THREAD

**Issue by Jefferson49** [fisharebest/webtrees#4146]
Observed with webtrees 2.0.19
If a repository is assigned to a source without a call number and the repository is opened again for editing, there is no entry line shown for the call number. Therefore, a call number can not be added any more. 

![Source with repository but without call number](https://user-images.githubusercontent.com/81484983/147401866-d38556e9-3a53-48e0-a36f-7eb4eac1e7b7.JPG)
![No entry field for call number shown](https://user-images.githubusercontent.com/81484983/147401870-c7e8c2bf-fb95-4c28-a1c2-f157742f13f8.JPG)

**Comment by fisharebest** [comment]
Already fixed for 2.1 - see #381
<img width="1040" alt="Screenshot 2021-12-27 at 08 46 42" src="https://user-images.githubusercontent.com/2306088/147453620-87beb9b6-2718-4bf1-8488-d5b82b27ea5c.png">
8
