### ISSUE TITLE
Changing language when historic events are enabled

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4147]
Initial settings
Language: english
Historic events: enabled

With the above settings (and the english events module enabled) english historic events are displayed, now change language to something where no historic events exist and then switch back to english.

The historic events checkbox shows a flash of checked and then becomes unchecked, however the historic events are displayed. Refreshing the page restores the correct state

**Comment by magicsunday** [comment]
This also happens if you tick the checkbox "Events of close relatives" and change the language. The events are displayed but the checkbox is not checked anymore.

**Comment by ddrury** [comment]
Further investigation reveal that any checkbox on the Facts and events tab when checked alternates between checked/unchecked on each page refresh.
