### ISSUE TITLE
Manually add new user - skip user approved email

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#4148]
See: https://www.webtrees.net/index.php/en/forum/help-for-2-0/36364-manually-add-new-user-skip-user-approved-email

When a user is added manually by the administrator, the system should not automatically send an email to let the user know that his request has been approved and he can log in. This is because at that point the administrator is not yet been able to inform the user that an account has been created for him and which login details he needs. Moreover, the text in the email is incorrect because it assumes that the user has requested an account himself.

**Comment by fisharebest** [comment]
I guess the simplest solution is to create the account with "approved = yes".

Then, the admin will not need to select this, and the email will not be sent.
