### ISSUE TITLE
Purpose of "dummy"?

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#4151]
resources/views/modules/interactive-tree/chart.phtml

What is "dummy => "dummy" used for? ;-)
 
`<div id="<?= $name ?>_out" class="tv_out" data-url-details="<?= e(route('module', ['module' => $module, 'action' => 'Details', 'tree' => $tree->name(), 'dummy' => 'dummy'])) ?>" data-url-individuals="<?= e(route('module', ['module' => $module, 'action' => 'Individuals', 'tree' => $tree->name(), 'dummy' => 'dummy'])) ?>">`

**Comment by fisharebest** [comment]
It allows javascript to easily add parameters to this base-URL - with and without pretty URLs.

New parameters are always `&x=y`.

Without this, the code would need to choose between `&x=y` and `?x=y`.

**Comment by magicsunday** [comment]
👍🏻
