### ISSUE TITLE
Error in top 10 pageviews

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#416]
`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''10'' at line 1' in C:\xampp\htdocs\webtrees_build\library\WT\DBStatement.php:83 Stack trace: #0 C:\xampp\htdocs\webtrees_build\library\WT\DBStatement.php(83): PDOStatement->execute() #1 C:\xampp\htdocs\webtrees_build\modules_v3\top10_pageviews\module.php(74): WT_DBStatement->execute(Array) #2 C:\xampp\htdocs\webtrees_build\index.php(70): top10_pageviews_WT_Module->getBlock(344) #3 {main} thrown in C:\xampp\htdocs\webtrees_build\library\WT\DBStatement.php on line 83`

**Comment by fisharebest** [comment]
Same as https://bugs.launchpad.net/webtrees/+bug/1417286
