### ISSUE TITLE
DataTables warning: table id=DataTables_Table_0 - Ajax error

### ISSUE THREAD

**Issue by MvdB1982** [fisharebest/webtrees#4169]
I run into the following error when opening the user administration panel:

DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

Fetch/XHR gives: "403 Forbidden"

System specs running:
Webtrees 2.0.19
PHP Version 7.4.9

Tried (resulting in the same error)
- Upgrade to Webtrees 2.1 (alpha)
- Upgrade to PHP 8
- Fresh install webtrees

I've been running webtrees for the past two years without any problems.  Do you guys have any suggestions?

**Comment by fisharebest** [comment]
See https://webtrees.net/faq/xhr/

This should help you see the error message.

**Comment by MvdB1982** [comment]
Thnx, but all ready went through this steps. See result (403 forbidden) in my first post

**Comment by fisharebest** [comment]
> Thnx, but all ready went through this steps. See result (403 forbidden) in my first post

It wasn't clear what you'd done in the first post.  You might have just used `wget` or `curl` to fetch the URL - which would have given a 403...

**Comment by fisharebest** [comment]
> Fetch/XHR gives: "403 Forbidden"

Was there any body to the HTML response?
And what other headers?

**Comment by MvdB1982** [comment]
I took the following steps:
1. Egde - Developer tools
2. Network - Fetch/XHR
Then 'Response' gives the following output:

```<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

**Comment by fisharebest** [comment]
This looks like a 403 page generated by your webserver, not by webtrees.

Do you have any PHP coding skills?  If so, you can add some simple debug to verify this.

**Comment by MvdB1982** [comment]
_I have never tried that before, so I think I should definitely be able to do that_

If you can give me some guidance (or a good reference), I will look into that..

**Comment by fisharebest** [comment]
What webserver do you use?  If it is IIS, did you read https://webtrees.net/install/iis/

**Comment by MvdB1982** [comment]
Based on the tab 'server information'  it's an Apache webserver.

**Comment by fisharebest** [comment]
Find `app/Http/RequestHandlers/UserListData.php`

Add this line at the start of the `handle()` function.

Do you still get the 403, or do you get a 500?

If 403, then it is almost certain that the response is being generated by your webserver, and the request isn't being passed to webtrees.

**Comment by MvdB1982** [comment]
Still 403...

**Comment by fisharebest** [comment]
Then you need to look at your webserver (e.g. apache) configuration.

Perhaps your server has installed some type of security application that is blocking these requests?

**Comment by MvdB1982** [comment]
Moved the side to another hosting provided. Issue is gone
