### ISSUE TITLE
Bug - census assistant module

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4173]
Following change to Tom Select, a page refresh leaves the census selector (element `id="census-assistant-title") populated with the previously selected census, it is then necessary to select any other census to re-enable proper functioning of the census selector.

**Comment by fisharebest** [comment]
> Following change to Tom Select

This is not new.  It has been a firefox feature(!) for decades.  It affects countless sites.

If you reload a page (with F5), firefox will auto-fill form fields from the previous page.
However, it won't trigger a `change` event on it.

So, the code generates HTML for a select with no value selected, and firefox silently changes it to be selected.

There are bug-reports on firefox for this going back decades - all marked as "won't fix".

If you want a clean page in firefox, use CTRL-F5.

**Comment by ddrury** [comment]
You live and learn!

**Comment by fisharebest** [comment]
Here's a bug report from 22 years ago - https://bugzilla.mozilla.org/show_bug.cgi?id=46845

Googling suggests that `autocomplete="off"` may disable this.

Reopening until I can test this.
