### ISSUE TITLE
A query on browser support

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4174]
Following on from the work I've recently done with the map stuff I decided to start working on removing jQuery code from the map views. As a first step I thought I'd remove the scrollTo function which is repeated for each view and I decided to use the native scrollIntoView method. (the change is trivial), however I'm currently using the option `{behavior: "smooth"}` which it seems Safari doesn't currently support, however the latest desktop version has support in a technical preview so I guess it's on the way.

See https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView.

Any views?

**Comment by fisharebest** [comment]
For something like this (cosmetic rather than functional, not a major browser, will be fixed upstream), I would just use the native function.

**Comment by ddrury** [comment]
Glad you said that as I'd already done it this way !

Thanks
