### ISSUE TITLE
Possible bug with Filter::expandUrls()

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#419]
If I call Filter::formatText() with the FORMAT_TEXT preference set to nothing (ie not markdown) with some text containing embedded html I get something like the following.

    <div dir="auto" style="white-space: pre-wrap;"><strong>Section 1.10.32 of "de Finibus Bonorum et 
    Malorum", written by Cicero in 45 BC</strong> Sed ut **perspiciatis** unde omnis iste natus error sit
    voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo ... etc.
    </div>

Which looks ok but unfortuntely the triangular braces around the strong keyword are escaped and converted into lt & gt which stops them being interpreted as html

**Comment by fisharebest** [comment]
> with some text containing embedded html

Text from where, exactly?  If it is user-supplied, then we most certainly do want to escape it...

`1 NOTE <script>do_evil();</script>`;

**Comment by ddrury** [comment]
yeah see what you mean,

You may recall some time ago I submitted a PR with a replacement News module & a lightweight html/markdown editor but you were making changes so fast I couldn't keep up! so I withdrew it. I just had another go at it and discovered this problem.

It's no big deal, I'll only call Filter::formatText() if markdown is enabled otherwise I'll handle the output myself

**Comment by fisharebest** [comment]
I saw the PR, but I'm afraid I didn't get the time to give it a full look.  As you noticed, I was in the middle of some other changes (the refactoring took several weeks before it was committed).

My initial thoughts were perhaps to include the markdown and html editors in the core code.

We'll need to change the module API for the next release (modules_v4), and this is the only way we can actually retire/delete old modules (such as cke).

**Comment by ddrury** [comment]
OK,
I'll continue tinkering and at a suitable point I'll shove something up to you
