### ISSUE TITLE
2.0.19 Statistics / Families - truncated slanted x-axis labels

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#4205]
In some non-English languages, the labels for the x-axis of charts on the Statistics / Families tab are tilted.

This happens with the second chart (Number of families without children) in the "Children in Family" section.

But the slanted texts are truncated.

Tested with African/Dutch/German/Italian languages.

Example in Dutch:

![afbeelding](https://user-images.githubusercontent.com/46184729/152530294-79470ba5-6c72-4990-996a-979d84cf2a3e.png)

**Comment by fisharebest** [comment]
The right-hand chart has an extra column "Unknown".

This is google chart's attempt to fit the labels.

They are now too wide, so they are slanted.
They are still too wide, so they are truncated.

I can disable the "slanted" feature, but then it only displays every 2nd or 3rd label.

I can't find any other configuration options in the documentation: https://developers.google.com/chart/interactive/docs/gallery/columnchart

See also #3883

**Comment by JustCarmen** [comment]
I think you should take a look at the hAxis.showTextEvery option.

I've tested it by setting the value to 1: $chart_options['hAxis']['showTextEvery'] = 1;

This is the result:

![image](https://user-images.githubusercontent.com/5641963/152612397-62200c99-cfbe-4b62-8621-1e24c68b9482.png)

The word 'Onbekend' (Unknown) is still truncated but it looks better than in the current situation.

**Comment by fisharebest** [comment]
Thanks Carmen!
