### ISSUE TITLE
2.1: IndividualMetadataModule and ElementInterface

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4207]
Modules such as CustomTagsFamilySearch will allow the easy addition of custom tags. Some of these (such as FamilySearchFamilyTreeId in this case) would like to be displayed in the sidebar, via IndividualMetadataModule.

IndividualMetadataModule currently has a static list of handled facts. If these facts would be determined dynamically instead (via a new method `isNonGenealogyInformation` or similar in ElementInterface), the sidebar could adjust automatically to custom tags.

Does this make sense? Or is it something that's too specific for ElementInterface?

**Comment by fisharebest** [comment]
If someone wanted to customize the list of tags that appear here, they could do it by creating a modified version of `IndividualMetadataModule`.

> via a new method `isNonGenealogyInformation` or similar in ElementInterface

If we did this, then you would need to modify the GEDCOM definitions to make a change - which is more work, and is more likely to conflict with other modules.

So, I think it is best to simply add `_FSFTID` to the list of `HANDLED_FACTS`.

Also, this is the only place that we use this information.  If we needed it somewhere else, then I think I would agree that we should move the definition to the element.

I'm happy to reconsider this, if you disagree.

**Comment by ric2016** [comment]
> If we did this, then you would need to modify the GEDCOM definitions to make a change

No, you could still create a custom IndividualMetadataModule with a static list of handled facts.

Your solution works for _FSFTID, but not for other custom tags - But this may be a quite theoretical case. I guess the solution i ok for now.
