### ISSUE TITLE
2.0.19 - website log: filter 'type' -> 'error' and 'media' doesn't work

### ISSUE THREAD

**Issue by ungeahnt** [fisharebest/webtrees#4216]
I've tried to fix it with pull request #4215, but there was check errors and I've closed the PR.

It's probably not as simple as I thought ;)

**Comment by fisharebest** [comment]
What exactly do you mean by "doesn't work"?

**Comment by ungeahnt** [comment]
the result is "No records to display"

**Comment by ungeahnt** [comment]
I've checked it again. 
When I set the filter on 'error', the result 'No records to display" and the text "Showing 42 to 6 of 6" is displayed. 

'42'? ... the answer to everything ;)

Then I've clicked on the button 'next' (to view the next page) and afterwards it shows all correctly and the problem disappeared (it's no longer reproducable).

I think there is no point in looking further here and I would close the issue if there are no objection.
