### ISSUE TITLE
Duplicate CSS

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4219]
Both webtrees.css and each theme.css import _base.css which results in a great deal of duplication

**Comment by fisharebest** [comment]
Not sure I follow this.

Each of the six themes imports `_base.css`.

Surely this reduces duplication, as the common formatting is only defined once...?

**Comment by ddrury** [comment]
I'm a dipstick, brain was in script mode, I was assuming webtrees.css got loaded alongside the theme!

Sorry
