### ISSUE TITLE
2.1: Display of other fact attributes

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4242]
The view 'fact.phtml' has a block for 'other attributes', but this doesn't seem to work correctly (or I do not understand it):
The value of the attribute isn't used anywhere ([and not part of the regex here](https://github.com/fisharebest/webtrees/blob/6612c384f7d79aa0f86b473c59e91988d6adbf5d/resources/views/fact.phtml#L141)), and therefore the attribute apparently isn't displayed.

Example the '2 RELI' e.g. in a 'INDI:CHR:RELI' (by the way, the entire 'INDI:*:RELI' doesn't appear in 'Gedcom tags' and can only be added via raw GEDCOM):

```
1 CHR
2 DATE 23 JUL 1822
2 RELI luth
```

This may also be the reason why SOUR:DATA:EVEN isn't displayed (cf #4239).

```
1 DATA
2 EVEN BIRT
3 DATE FROM 1800
3 PLAC England
```

**Comment by ric2016** [comment]
Thanks - Should I create a separate issue for this:

> the entire 'INDI:*:RELI' doesn't appear in 'Gedcom tags' and can only be added via raw GEDCOM

**Comment by fisharebest** [comment]
> Should I create a separate issue for this:

Yes please.
