### ISSUE TITLE
2.1: Missing Event Structure subtags

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4243]
The entire `INDI:*:RELI` doesn't appear in 'Gedcom tags' and can only be added via raw GEDCOM.
Probably also affects `FAM:*:RELI`, and perhaps other `INDI:*`/`FAM:*`

I think it would make sense to allow to enable those one-by-one in the preferences (instead of having a single checkbox for all INDI:*:RELI), RELI is a useful subtag for religious events (BAPM/CHR), not so much for most others.

**Comment by fisharebest** [comment]
GEDCOM allows `:INDI` subtags to be added to *all* facts and events (including `INDI:RELI`!).

Should we add them

(a) everywhere
(b) only in places where it is sensible.

**Comment by fisharebest** [comment]
`AGNC` is similar.  Do we add it everywhere, or only where it is meaningful.

**Comment by ric2016** [comment]
I think there should be a way to add them everywhere, in order to be GEDCOM-compliant.

In the preferences for the Gedcom Tags, maybe use one section per subtag (i.e. one for RELI, one for AGNC, others if required), in the same format as 'Facts for new individuals' in the tree preferences, labeled 'Facts with non-hidden subtag RELI' etc. This can then be pre-filled with a meaningful selection, and most users won't ever have to adjust it:

<img width="833" alt="prefs" src="https://user-images.githubusercontent.com/18174787/156233649-05e62cd1-0a80-4429-be7c-847ff1aea9a1.PNG">

**Comment by Norwegian-Sardines** [comment]
I thought that one of the enhancements to webtrees via v2.1 would be that it supported various dialects of GEDCOM.  For example a user would have the ability to have a dialect that had non-GEDCOM tags, or include GEDCOM tags is odd places or ways.  One “dialect” of GEDCOM is GEDCOM! All standard GEDCOM tags should be available in the correct places as a selectable option, along side a reduced/common tags option.  I use a lot of the GEDCOM tags and sub tags and have become accustomed to using the raw entry but I’d like to have better coverage of less used subtags!

**Comment by Norwegian-Sardines** [comment]
Adding dialects would allow for add GEDCOM v7.0 later on!

**Comment by Norwegian-Sardines** [comment]
My hope was that the admin would have some easy control over the tags and subtags available for their use of GEDCOM.  For example: I would not want ADDR subtags available because I want to use the PLAC tag to have the street addresses.  And yes for “number of marriages” those are useless tags, but will everyone need to build a module to support their desired data entry needs?  Or can some configuration generation script be created were, for example, a php file is built with all of the correct hooks that defines a custom implementation of the base GEDCOM dialect?

**Comment by Norwegian-Sardines** [comment]
I don’t use AGNC, RELI, or CAUS very much anyway so for me I would eliminate them from all facts!

**Comment by ric2016** [comment]
> My hope was that the admin would have some easy control over the tags and subtags available for their use of GEDCOM.

As I understand it, that's what the section 'Gedcom Tags' in the preferences is for. In my opinion, everything from standard GEDCOM should be configurable there (see my comment above as to how), even 'meaningless' tags such as INDI:NMR:AGNC.

**Comment by Norwegian-Sardines** [comment]
So the question becomes, should webtrees provide all tags and subtags as possibilities. Have a basic “best practice” tag set, But also have some form of selecting/deselecting tags and subtags that make sense for the particular installation (and admin preference)?  GEDCOM suggests not using ADDR:STAE/CTRY/POST/CITY so some may want to eliminate those to prevent confusion too!  And other tag combinations are only in the document to support backward compatibility or are rarely used but useful if used properly like PLAC:FORM.  I realize much of this comes from a person that uses RAW entry a lot and changes a lot of entries made by others to conform to my desires for reporting consistencies.

**Comment by fisharebest** [comment]
All valid subtags are available by clicking the "show all" button.  If any are missing, then this is a bug.

(Should the "show all" button should be an admin-only feature?)

The issue is how to configure which are shown/hidden by default.

> GEDCOM suggests not using ADDR:STAE/CTRY/POST/CITY so some may want to eliminate those to prevent confusion too!

This is a good example of something that should be hidden by default.

> everything from standard GEDCOM should be configurable there (see my comment above as to how)

The problem here is that you'll get 1000's of configuration options, which will be overwhelming for the average user.

**Comment by ric2016** [comment]
> The problem here is that you'll get 1000's of configuration options, which will be overwhelming for the average user.

This is why I suggested to group them, as in the example above. Do you see any alternative?

**Comment by fisharebest** [comment]
All valid subtags are available by clicking the "show all" button.  If any more are missing, then this is a bug.

I have updated the tag-definitions and configuration slightly.

Tags may be hidden for 2 reasons.

1) they are valid, but do not make sense - e.g. `INDI:NCHI:RELI`

2) they have been hidden using the settings in the control panel.

To discuss these, or suggest changes, please create new issue.

**Comment by ric2016** [comment]
> they have been hidden using the settings in the control panel.

I don't understand this - Where is the setting to hide e.g. INDI:BAPM:RELI?

**Comment by fisharebest** [comment]
> I don't understand this - Where is the setting to hide e.g. INDI:BAPM:RELI?

The issue was that these tags were not available.

The fix was to make them available everywhere that GEDCOM permits.

(Also, new logic was added to allow modules to decide what tags are initially hidden.)

> Where is the setting to hide e.g. INDI:BAPM:RELI?

Deciding which configuration options to have is a different issue.

**Comment by ric2016** [comment]
ok, first part of this issue (which was "The entire INDI:*:RELI doesn't appear in 'Gedcom tags'") re-opened in #4243. I'll try to make separate issues right away next time.
