### ISSUE TITLE
Not all gedcom tags configurable via preferences

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4244]
This continues #4243. As stated there:

> The entire INDI:*:RELI doesn't appear in 'Gedcom tags'

See the discussion in #4243 - To summarize, it isn't clear whether offering configuration options for all tags is a good idea.

In my opinion, everything should be configurable. Otherwise we'll just end up spending a lot of time discussing all kinds of special cases in the forum. As pointed out, we'll have a lot of options, but the average webtrees administrator will not have to touch most of them.

**Comment by fisharebest** [comment]
`RELI` subtags should now be available pretty much everywhere.
