### ISSUE TITLE
[Feature request] Bulk add research tasks

### ISSUE THREAD

**Issue by Neriderc** [fisharebest/webtrees#4245]
Can we get a way to bulk add research tasks? Maybe someone can suggest another way to get the outcome I'm looking for.

I have imported a GEDCOM from someone else. I want to add research tasks to every individual, that I will clear as I review them myself.

Research tasks seem like the best we to do this, particularly as you can list research tasks on your home page.

I don't believe there is a way to add research tasks in bulk currently. Maybe there is a better way of doing what I'm trying to do?

**Comment by fisharebest** [comment]
You could use the search/replace (data-fix) function.

Use the regular-expression search.

Search for `$` (matches end of the record)
Replace with `\n1 _TODO\n2 DATE 04 MAR 2021`

The date is important.  webtrees uses the data indexes to find these records.

**Comment by Neriderc** [comment]
Thanks this seems to work, except it added two research tasks to every individual.

I used search method regular expression, case insensitive - no, records Individuals. I didn't press the button twice or anything like that. I tested a few times and each time it added 2 new records.

**Comment by fisharebest** [comment]
It worked fine when I tested it on my local machine.

Hard to guess what you might have done differently to me.

**Comment by Neriderc** [comment]
Yeah it seemed to me there wasn't much opportunity to deviate. It was 100% reproducible, I added several research tasks (separate ones for "Confirm birth date", "Confirm death date", etc). If it worked for you then chances are there's something weird in my setup.

**Comment by fisharebest** [comment]
Here are 3 screenshots.

1) the search/replace settings
2) a preview of one of the changes
3) the result of the change.

Maybe you clicked "update all" twice?

----------

<img width="1368" alt="Screenshot 2022-03-06 at 09 01 55" src="https://user-images.githubusercontent.com/2306088/156916346-4ef701e8-797f-4bc4-af8e-3122edd2cba7.png">

----------

<img width="1305" alt="Screenshot 2022-03-06 at 09 02 07" src="https://user-images.githubusercontent.com/2306088/156916340-81e6393c-16f6-4754-8448-06bb03bcfed8.png">

----------

<img width="954" alt="Screenshot 2022-03-06 at 09 02 25" src="https://user-images.githubusercontent.com/2306088/156916337-9f74ec36-8ecc-4343-8b40-cb6aa480d147.png">
