### ISSUE TITLE
Support for linked Locations?

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4250]
Top-level Locations are now partially supported in webtrees (e.g. in the general search, see #3786).

They are not integrated everywhere, e.g. not in [record-page-links.phtml](https://github.com/fisharebest/webtrees/blob/main/resources/views/record-page-links.phtml).

Do we want them there? I would provide the respective PRs, but I'm not sure about this: For users not using _LOC at all, there would always be an empty tab 'Locations 0'. Or [add a check as in the search](https://github.com/fisharebest/webtrees/blob/718572693f6a54a91ebf59f26621acfb21b425d3/app/Http/RequestHandlers/SearchGeneralPage.php#L95) and only show this tab if there are any locations at all? Or keep this out of webtrees core for now?

**Comment by fisharebest** [comment]
> Or keep this out of webtrees core for now?

We should add support for this.

We are also missing several other links.  For example repositories and submitters.

The various `GedcomRecord::linkedXxxx()` functions do not really belong in this class.  They are nothing to do with the implementation/representation of the record.  They need to be in their own business-logic class.  Perhaps  `LinkedRecordService`.

**Comment by ric2016** [comment]
> For users not using _LOC at all, there would always be an empty tab 'Locations 0'.

This is considered to be acceptable? Personally I don't mind, but it seems somewhat questionable as _LOC isn't standard gedcom.

**Comment by fisharebest** [comment]
Where we don't want to show an empty tab, we convert the empty `Collection` to `null`.

So, you will find this code everywhere:

`'linked_locations'     => $linked_locations->isEmpty() ? null : $linked_locations,`

This hides the empty tab.

The only place we should show a tab with `Locations 0` is on the page of another location.

**Comment by ric2016** [comment]
Thanks for the explanation - I missed that part.
