### ISSUE TITLE
Custom Gedcom Tags and ElementInterface

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4251]
Three are custom subtags for PLAC in [CustomTagsGedcomL](https://github.com/fisharebest/webtrees/blob/718572693f6a54a91ebf59f26621acfb21b425d3/app/Module/CustomTagsGedcomL.php#L163).

These are not available when editing, because the respective element PlaceName [doesn't have them as subtags](https://github.com/fisharebest/webtrees/blob/718572693f6a54a91ebf59f26621acfb21b425d3/app/Elements/PlaceName.php#L38) (which is ok, they don't belong there).

How should this be handled - Should the module (CustomTagsGedcomL in this case) replace all PLAC definitions like this
`'INDI:BAPM:PLAC'           => new ExtendedPlaceName(I18N::translate('Place of baptism')),`

(potentially problematic in case of additions via separate modules)

Isn't the subtag definition somewhat redundant anyway (apart from the cardinality), since the subtags have to registered with the ElementFactory anyway? If we pull the subtag defintions out of the ElementInterface and handle it directly via the ElementFactory definitions, custom tag additions would be easier.

We'd probably have to move the cardinality definitions in general though, e.g. like this:
`'INDI:BAPM'           => new ZeroOrMany(new Baptism(I18N::translate('Baptism'))),`

**Comment by fisharebest** [comment]
> How should this be handled

There are two choices.

1) Each element has default subtags.  But you can override these when you register it.  For example:
`'INDI:BAPM:PLAC' => new PlaceName(I18N::translate('Place of baptism'), ['_LOC' => '0:1', ...])`.
This will *replace* the default subtags, not *add* to them.  For just a few tags, it may be easiest to do this.

2) Create a new element type, e.g. `class GedcomLPlaceName extends PlaceName`.

I guess that if we use (2), then we may be able to have a custom edit control, which links the `PLAC` to the `PLAC:_GOVID`.

I think (2) is probably the better option.  Let me think a little.

> Isn't the subtag definition somewhat redundant anyway (apart from the cardinality), since the subtags have to registered with the ElementFactory anyway?

The definitions have the appearance of a formal grammar.
But they are not.  They are more pragmatic.

Registering tags allows us to *display existing fields*.  This is an improvement on the old logic, as we can easily distinguish context.  But it also has false-positives.  e.g. the registration of `'INDI:*:PLAC'` will match invalid tags such as `INDI:SEX:PLAC`.

The subtag definitions are used to *edit/create new fields*.  But we treat `0:M` and `1:M` the same - both allow us to create a new field.  We also use `2:M` to show a minimum of two edit fields (for witnesses at `MARR`). and `3:3` to show 3 language fields for a submitter.

I would like to have a formal grammar.  I see the current code as a stepping-stone to that.
But first I want to learn how the current code works in the "real world".

**Comment by ric2016** [comment]
> There are two choices.

Either way, if all subtags are replaced and not added to, how is this supposed to work if there are multiple modules that add to the same tag?

We have this e.g. in CustomTagsFamilySearch (INDI:_FSFTID) and CustomTagsFamilyTreeMaker (INDI:_CIRC and several others). None of these currently work because IndividualRecord doesn't have these subtags, but if each modules replaces the definition, only one of them can win.

So perhaps the subtags should always be added, and never replaced? Or is there a use case where we need to replace?

**Comment by fisharebest** [comment]
There are two different things here.

1) The default subtags for an element type.  There are only a few of these.  For example

```
'INDI:FAMC'  => new XrefFamily(I18N::translate('Family as a child'), ['NOTE' => '0:1', 'PEDI' => '0:1', 'STAT' => '0:1']),
```

It doesn't matter that the subtags are a *replacing* the default subtags for `XrefFamily` - we are also *replacing* any existing entry for `INDI:FAMC`.

2) `Module::customSubTags()` which registers subtags.  This allows you to add/edit/remove subtags from existing tags.  These can add/change/remove.

Looking at the code, I see a some confusion as to whether you use `0:0` or an empty string to indicate removal.  I'll clear this up.  `0:0` is probably clearer.

**Comment by ric2016** [comment]
I was mainly confused because I didn't see `customSubTags()` initially (and you didn't mention it either). Can you confirm that these customSubTags definitions are missing in CustomTagsGedcomL, CustomTagsFamilySearch, and several other places?

**Comment by fisharebest** [comment]
> Edit: For example, CustomTagsFamilySearch should have this?

If you want to be able to *add* these tags (as well as display them), then yes.

Since these IDs will only come from a FamilySearch GEDCOM export, I don't know if it is meaningful to add them manually.

**Comment by ric2016** [comment]
> Since these IDs will only come from a FamilySearch GEDCOM export

No, of course it makes sense to add them manually! It's just a different type of link that's not available in standard GEDCOM.

Apparently this is a fundamental misunderstanding on my part of what the CustomTagsXyz is supposed to achieve. I thought it would allow users to use these additional tags as regular tags, not only display them correctly in case they appear in an imported GEDCOM file.

So the selection in the respective module preferences "Hide/show GEDCOM tags in the edit forms" is informational only - I thought this would allow the user to configure this further, as in the main 'GEDCOM tags' preferences, and just wasn't finished yet.

**Comment by fisharebest** [comment]
> So the selection in the respective module preferences "Hide/show GEDCOM tags in the edit forms" is informational only - I thought this would allow the user to configure this further, as in the main 'GEDCOM tags' preferences, and just wasn't finished yet.

I had forgotten about that page!

I originally intended to allow these modules to configure which custom tags to show / edit.

But I never finished it.

**Comment by ric2016** [comment]
[See related forum discussion here](https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/36626-some-of-the-custom-gedcom-tags-that-you-continue-to-use-cannot-be-used-help-me#90027). I expect more of this kind, if the custom tags aren't made available for editing (ideally configurable).

**Comment by fisharebest** [comment]
In the latest code, all custom tags are available for display/edit.

For *new* custom tags (facts and events), there is a configuration page in the control panel.

For the `PLAC` subtags, these are enabled by selecting the "GEDCOM-L" option.
