### ISSUE TITLE
2.0.19-When uploading photos from phone camera, the display is rotated.

### ISSUE THREAD

**Issue by DaPoHou** [fisharebest/webtrees#4252]
When I use the mobile browser to create new multimedia, click Choose File, and take photos with the camera, the thumbnail displayed after uploading is rotated (90 degrees counterclockwise).
The original file stored in the media folder is normal. Only all thumbnails are rotated.

How to fix it?

**Comment by DaPoHou** [comment]
https://github.com/Intervention/image/issues/461
Is this the cause of the error?

**Comment by fisharebest** [comment]
> How to fix it?

What exactly is broken.

* webtrees rotates the image - but it should not be rotated
* webtrees does not rotate the image - but it should be rotated

Does your server have the PHP `exif` library installed?
Control panel -> Server information ->
<img width="1389" alt="Screenshot 2022-03-07 at 09 26 31" src="https://user-images.githubusercontent.com/2306088/157003905-ae502503-151e-4b59-996a-bd3e5213c93c.png">

**Comment by DaPoHou** [comment]
yes,exif is enable.
![Uploading 微信截图_20220307173400.png…]()

**Comment by fisharebest** [comment]
For thumbnails, we must rotate the image ourselves.  (Using the EXIF data).

For original images, the browser will rotate the image.  (Also using EXIF data).

If the thumbnail image is not rotated, then the there is a problem with the image library on your server.

The code is here.

https://github.com/fisharebest/webtrees/blob/2.0.19/app/Factories/ImageFactory.php#L374-L383

Perhaps replace `return $image;` with `throw $ex;`.

If there is an error, perhaps you will see it.

**Comment by DaPoHou** [comment]
> 

I tried this method without getting any errors.
Preview images and thumbnails are still incorrectly rotated.

**Comment by DaPoHou** [comment]
![Screenshot_20220307-195348_Chrome](https://user-images.githubusercontent.com/26761596/157029785-e410fdf5-91ed-41ce-af2b-da2d269615f8.jpg)

**Comment by fisharebest** [comment]
Can you provide the original image

**Comment by DaPoHou** [comment]
> Can you provide the original image
Attached is the original image in the media folder on the server.
[16466539500334113853255912621296.zip](https://github.com/fisharebest/webtrees/files/8197491/16466539500334113853255912621296.zip)

**Comment by fisharebest** [comment]
`Orientation: 6`.

This means that the right edge of the photo is the "top".
So, the image must be rotated -90 degrees.

The image library in webtrees is doing exactly this.

I think the code is working correctly.

Your image contains the wrong EXIF data for orientation.

**Comment by DaPoHou** [comment]
> 
My device is Samsung S21, the latest last year.
It shouldn't be a problem with my device, I have also tested on other devices, I have the same problem on ipad ios 12.5.

**Comment by DaPoHou** [comment]
https://github.com/Intervention/image/issues/392#issuecomment-825201230
I wonder if this method can fix the bug?

**Comment by DaPoHou** [comment]
https://github.com/fisharebest/webtrees/blob/22a7fa5553122caa0b259cf025de6010b8992ba0/app/Factories/ImageFactory.php#L218
After my repeated tests, the $image in this line of code did not get any information. 

![微信截图_20220308105343](https://user-images.githubusercontent.com/26761596/157160545-0512d50f-0515-4ff6-b571-3f1e2acbeacb.png)

So there is no way to judge the orientation of the image here
https://github.com/Intervention/image/blob/b734a4988b2148e7d10364b0609978a88d277536/src/Intervention/Image/Commands/OrientateCommand.php#L15

**Comment by DaPoHou** [comment]
I've spent a lot of time debugging this issue, this is simply too hard for my non-developer.
Hard work pays off, I think I've figured out where the problem is.
Images in webtrees:
1. If you use the gd engine, the exif data will be lost.
2. If you use Imagick engine, exif  will be reserved.
Why was it obtained by mistake? Because in Intervention/image the following statement is used to get the value of  `Orientation` . 

https://github.com/Intervention/image/blob/b734a4988b2148e7d10364b0609978a88d277536/src/Intervention/Image/Commands/ExifCommand.php#L44

But in Webtrees, images have two `Orientation` values. As shown below. 

![error_orientation](https://user-images.githubusercontent.com/26761596/157828619-efda237e-c78e-4c99-a2e8-b350e97b701b.JPG)

The real value is in the subarray `THUMBNAIL`.  Therefore, according to the statement in Intervention/image, only the wrong `Orientation` value can be obtained.

**Comment by fisharebest** [comment]
> But in Webtrees, images have two Orientation values. One is 0 and the other is the real value. As shown below.

Are you certain?  I see `6` for both the main image and the thumbnail.

```
php > var_export(exif_read_data('16466539500334113853255912621296.jpg'));
array (
  'FileName' => '16466539500334113853255912621296.jpg',
  'FileDateTime' => 1646682786,
  'FileSize' => 1595997,
  'FileType' => 2,
  'MimeType' => 'image/jpeg',
  'SectionsFound' => 'ANY_TAG, IFD0, THUMBNAIL, EXIF, GPS, INTEROP',
  'COMPUTED' => 
  array (
    'html' => 'width="4032" height="1816"',
    'Height' => 1816,
    'Width' => 4032,
    'IsColor' => 1,
    'ByteOrderMotorola' => 1,
    'ApertureFNumber' => 'f/1.8',
    'Thumbnail.FileType' => 2,
    'Thumbnail.MimeType' => 'image/jpeg',
    'Thumbnail.Height' => 144,
    'Thumbnail.Width' => 320,
  ),
  'ImageWidth' => 4032,
  'ImageLength' => 1816,
  'Make' => 'samsung',
  'Model' => 'SM-G9910',
  'Orientation' => 6,
  'XResolution' => '72/1',
  'YResolution' => '72/1',
  'ResolutionUnit' => 2,
  'DateTime' => '2022:03:07 19:52:55',
  'YCbCrPositioning' => 1,
  'Exif_IFD_Pointer' => 212,
  'GPS_IFD_Pointer' => 776,
  'THUMBNAIL' => 
  array (
    'ExifImageWidth' => 320,
    'ExifImageLength' => 144,
    'Compression' => 6,
    'Orientation' => 6,
    'XResolution' => '72/1',
    'YResolution' => '72/1',
    'ResolutionUnit' => 2,
    'JPEGInterchangeFormat' => 1052,
    'JPEGInterchangeFormatLength' => 15326,
  ),
  'ExposureTime' => '2497831/125000000',
  'FNumber' => '180/100',
  'ExposureProgram' => 2,
  'ISOSpeedRatings' => 320,
  'ExifVersion' => '0220',
  'DateTimeOriginal' => '2022:03:07 19:52:55',
  'DateTimeDigitized' => '2022:03:07 19:52:55',
  'UndefinedTag:0x9010' => '+08:00',
  'UndefinedTag:0x9011' => '+08:00',
  'ComponentsConfiguration' => '' . "\0" . '',
  'ShutterSpeedValue' => '5645/1000',
  'ApertureValue' => '169/100',
  'BrightnessValue' => '64/100',
  'ExposureBiasValue' => '0/10',
  'MaxApertureValue' => '169/100',
  'MeteringMode' => 2,
  'Flash' => 0,
  'FocalLength' => '5400/1000',
  'SubSecTime' => '808446',
  'SubSecTimeOriginal' => '808446',
  'SubSecTimeDigitized' => '808446',
  'FlashPixVersion' => '0100',
  'ColorSpace' => 1,
  'InteroperabilityOffset' => 745,
  'SensingMethod' => 1,
  'SceneType' => '',
  'ExposureMode' => 0,
  'WhiteBalance' => 0,
  'FocalLengthIn35mmFilm' => 26,
  'SceneCaptureType' => 0,
  'GPSLongitudeRef' => 'E',
  'GPSLongitude' => 
  array (
    0 => '0/1',
    1 => '0/1',
    2 => '0/10000',
  ),
  'GPSAltitudeRef' => '' . "\0" . '',
  'GPSAltitude' => '0/1000',
  'GPSTimeStamp' => 
  array (
    0 => '0/1',
    1 => '0/1',
    2 => '0/1',
  ),
  'GPSDateStamp' => '1970:01:01',
  'InterOperabilityIndex' => 'R98',
  'InterOperabilityVersion' => '0100',
)
```

**Comment by DaPoHou** [comment]
Of course, The first xx value in the image coding process is wrong.

When I use the following code, the picture is rotated correctly.

`$data = array_key_exists($key, $data['THUMBNAIL']) ? $data$data['THUMBNAIL'][$key] : false;`

**Comment by yann64** [comment]
Same issue (only the thumbnail has wrong rotation) : https://genealogie.histoiredeserignan.fr/index.php?route=%2Ftree%2Fh2s%2Findividual%2FX13695%2FEdmond-Paul-Maury
Photo taken from Sony XPeria.

**Comment by fisharebest** [comment]
Your site adds watermarks to images.  Therefore I cannot see the original image.  Can you attach it here?

**Comment by yann64** [comment]
As requested:
![Edmond-Maury](https://user-images.githubusercontent.com/2534680/172012811-b735941d-3f29-455d-b8c1-62461eca8bc1.jpg)

**Comment by fisharebest** [comment]
I think this is a problem with the image library.

There are several other error reports saying that `orientate()` is not working.

**Comment by DaPoHou** [comment]
It should be that there is something wrong with the thumbnail generated by webtrees when processing photo.
The location where the value of orientation exists in the generated thumbnail changes.
Image library cannot get the value of orientation from the generated thumbnail.

Can the value of orientation in the original photo be used to judge the rotation direction?

**Comment by fisharebest** [comment]
The bug is in the image library.  I have submitted a fix.  Waiting for it to be accepted.

Closing this issue, for this one: #4592
