### ISSUE TITLE
Incorrect GEDCOM not handled well.

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#4255]
GEDCOM spec and probably most genealogy programs do not allow a FAM to have more than two spouses.

As a test to "see what happens," I created the attached GEDCOM.  webtrees imported it with no error messages.  And check for errors found nothing.  The site then shows only one family, with the partners being the first HUSB and WIFE in the FAM—Alex and Mimi

Unfortunately, however, the navigator shows "Family with Alex and Mimi" for ALL other individuals, no mater the INDI's NAME and SEX.  

The tree has been made non-private, if you want to view it: https://UniGen.us/tree/TT

I believe that anything considered illegal or which cannot be reasonably handled should at least get error messages and perhaps even refused
[TT.ged.zip](https://github.com/fisharebest/webtrees/files/8211924/TT.ged.zip)
.

**Comment by WGroleau** [comment]
I  still secretly wish for a way to handle this: https://www.webtrees.net/index.php/en/forum/2-open-discussion/36590-polygamy

**Comment by fisharebest** [comment]
The GEDCOM spec says to ignore unrecognised/invalid tags.

By ignoring multiple occurrence of `HUSB` and `WIFE` tags, webtrees is doing exactly this.

The "name" of a family record is composed from the names of the individuals in the (first) HUSB/WIFE links.

I'm not sure what else we could do.

> I still secretly wish for a way to handle this

The GEDCOM 7 committee said that they considered polygamous/polyandrous/etc. relationships, but decided not to implement them for GEDCOM 7.0.  This may  be reconsidered in a future version.

Until that happens, I think the best you can do is use `ASSO` tags to link the individuals.

**Comment by WGroleau** [comment]
I think that silently ignoring a tag was a bad decision on their part.  I think there should be (at least) a warning in the "check for errors" report.  As for the name, I see no reasonable alternative for that part, as long as group marriages are not supported.  If/when they are, I would change the "family name" to just "group marriage."  Currently, I don't have any and hope I never do.  I just did it as a test after seeing a forum post about it.
