### ISSUE TITLE
Custom welcome text

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#426]
The field for the custom welcome text should be a textbox in stead of a one line input field. Now the text can only hold 255 characters which is by far not enough in most cases.

All predefined welcome texts have more than 255 characters, so it is not very logic to keep the custom text limited.

**Comment by fisharebest** [comment]
The welcome text is (currently) an attribute of the tree.

The tree attributes are stored in the table `wt_gedcom_setting`.

This is limited to 255 characters, because MySQL cannot index columns longer than this - and this column must be indexed.

**Comment by wodka** [comment]
@fisharebest the welcome text is stored in site_settings, but for both tables the value not used in the index - why would you want to index the value?

<img width="770" alt="screen shot 2015-10-25 at 21 23 48" src="https://cloud.githubusercontent.com/assets/385731/10717659/e5efaf28-7b5e-11e5-86ff-5a47ca8d7510.png">


I just changed the value type to text and added a much longer text for the welcome message :) - this is working if I only change the values through phpmyadmin.

**Comment by wodka** [comment]
I have not tried this with my installation, but it should work: https://github.com/fisharebest/webtrees/pull/756

**Comment by fisharebest** [comment]
> welcome text is stored in site_settings

My mistake.  I thought that this setting was different for each tree.

**Comment by fisharebest** [comment]
Fixed via PR #756
