### ISSUE TITLE
Validator Error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#4260]
I am seeing lots of these errors in my Apache log

[Wed Mar 09 16:56:36.234621 2022] [fcgid:warn] [pid 29390:tid 140192010647296] [host skatekey.net] [client 34.245.89.123:48810] PHP Fatal error: Uncaught Fisharebest\\Webtrees\\Http\\Exceptions\\HttpBadRequestException: The parameter \xe2\x80\x9croute\xe2\x80\x9d is missing. in /var/www/html/sk/skatekey.net/app/Validator.php:311

**Comment by makitso** [comment]
Does this help, if not I will have to wait until tomorrow to get the access logs

[Wed Mar 09 16:56:36.234621 2022] [fcgid:warn] [pid 29390:tid 140192010647296] [host skatekey.net] [client 34.245.89.123:48810] PHP Fatal error: Uncaught Fisharebest\\Webtrees\\Http\\Exceptions\\HttpBadRequestException: The parameter \xe2\x80\x9croute\xe2\x80\x9d is missing. in /var/www/html/sk/skatekey.net/app/Validator.php:311

[Wed Mar 09 16:56:36.185872 2022] [fcgid:warn] [pid 29390:tid 140192136537856] [host skatekey.net] [client 34.245.89.123:48812] #2 /var/www/html/sk/skatekey.net/app/View.php(278): Fisharebest\\Webtrees\\View->render()

[Wed Mar 09 16:56:36.185861 2022] [fcgid:warn] [pid 29390:tid 140192136537856] [host skatekey.net] [client 34.245.89.123:48812] #1 /var/www/html/sk/skatekey.net/app/View.php(183): include('...')

[Wed Mar 09 16:56:36.185849 2022] [fcgid:warn] [pid 29390:tid 140192136537856] [host skatekey.net] [client 34.245.89.123:48812] #0 /var/www/html/sk/skatekey.net/resources/views/layouts/default.phtml(67): Fisharebest\\Webtrees\\Validator->route()

[Wed Mar 09 16:56:36.185838 2022] [fcgid:warn] [pid 29390:tid 140192136537856] [host skatekey.net] [client 34.245.89.123:48812] Stack trace:

**Comment by fisharebest** [comment]
As previously, this is most likely an error in the error-handler.

You could comment out this line in `app/Webtrees.php`.

https://github.com/fisharebest/webtrees/blob/43b889820012e1a743b36eaea0462bf3c7b1ee33/app/Webtrees.php#L184

Now, when an error occurs, you should hopefully get the original error in your logs.

**Comment by makitso** [comment]
Greg, here is the Apache log for the error:
34.245.89.123 - - [09/Mar/2022:16:56:33 -0800] "HEAD /ads.txt HTTP/1.1" 500 7397 "-" "TprAdsTxtCrawler/1.1"
34.245.89.123 - - [09/Mar/2022:16:56:33 -0800] "HEAD /app-ads.txt HTTP/1.1" 500 7398 "-" "TprAdsTxtCrawler/1.1"
34.245.89.123 - - [09/Mar/2022:16:56:36 -0800] "HEAD /ads.txt HTTP/1.1" 500 415 "-" "TprAdsTxtCrawler/1.1"
34.245.89.123 - - [09/Mar/2022:16:56:36 -0800] "HEAD /app-ads.txt HTTP/1.1" 500 416 "-" "TprAdsTxtCrawler/1.1"


Error log:
[Wed Mar 09 16:56:36.234621 2022] [fcgid:warn] [pid 29390:tid 140192010647296] [host skatekey.net] [client 34.245.89.123:48810] PHP Fatal error: Uncaught Fisharebest\Webtrees\Http\Exceptions\HttpBadRequestException: The parameter \xe2\x80\x9croute\xe2\x80\x9d is missing. in /var/www/html/sk/skatekey.net/app/Validator.php:311

**Comment by fisharebest** [comment]
If you fetch this url yourself (`/ads.txt`), what do you see on screen?

**Comment by makitso** [comment]
Don't have a file with that name.

**Comment by fisharebest** [comment]
So, you get a 404 page?  An error message?

If I fetch it on my own site, I get redirected to the home page.
On your site, you get an error in the logs, or something else....?

**Comment by makitso** [comment]
Sorry, I do not get a 404, I get a redirect to my home page as well.
Noting in the log.

**Comment by fisharebest** [comment]
So, to be clear, if this robot fetches the URL`/ads.txt`, then you get an error in the logs, but if you fetch the same URL, you are redirected to your home page (which is the expected behaviour).

SInce `ads.txt` and `app-ads.txt` are semi-standard files (like `robots.txt`), then perhaps we should adopt the same logic - i.e. generate a resonse, unless the file exists.
