### ISSUE TITLE
2.1

### ISSUE THREAD

**Issue by ol810** [fisharebest/webtrees#4266]
Мастер установки webtrees

Возникла неожиданная ошибка в базе данных.

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'wt_gedcom' already exists (SQL: create table `wt_gedcom` (`gedcom_id` int not null auto_increment primary key, `gedcom_name` varchar(255) not null, `sort_order` int not null default '0') default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB)

**Comment by fisharebest** [comment]
This error indicates that you are trying to install webtrees, and have specified an existing database.

If this database exists, and is complete webtrees will start using it.
If the database is incomplete/empty, webtrees will give this error.

If the database is empty, try deleting all the tables and trying again.
