### ISSUE TITLE
2.1 B1  Legacy URLs Redirect results to access error

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4271]
WT 1 Urls like https://wbt.warius.info/individual.php?pid=I2197&ged=Warius.ged results in
"This individual does not exist or you do not have permission to view it." but
https://wbt.warius.info/tree/Warius/individual/I2197/Wilhelm-Ravenstein not

**Comment by fisharebest** [comment]
You have changed the name of your tree, from `Warius.ged` to `Warius`.

If you visit https://wbt.warius.info/individual.php?pid=I2197&ged=Warius (without the `.ged`), then you are correctly redirected to https://wbt.warius.info/tree/Warius/individual/I2197/Wilhelm-Ravenstein

**Comment by FrankWarius** [comment]
Thanks Greg, you are right
But not me but google search is using warius.ged and now has a lot of 404 errors.
I haven't changed the tree name, just migrated to 2.1 B1 in Prod

**Comment by fisharebest** [comment]
Perhaps you changed the tree name a long time ago, and google has been searching for both `Warius` and `Warius.ged`.

Google must have seen `Warius.ged` somewhere.  This would be the default name for the tree, if it was created with an older version of webtrees/phpGedView.

If google is searching both URLs, then just ignore these 404s.
They will stop eventually, and google will only see the new URL.

The code is working as designed (redirect old URLs -> new URLs).
It was not designed to redirect old tree names -> new tree names.

**Comment by fisharebest** [comment]
This module is not for google.  google will quickly find new URLs and forget old URLs.

This module is for real users who have bookmarked pages in their browser.
