### ISSUE TITLE
If only one language module is activated, there is no menu shown for users

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#4278]
1. If I deselect all language modules: the browser language is used and no menu is shown to users: ok
2. if I select only one language module: no menu is shown to users: not ok (I expect that the selected language is offered in a menu)
3. if I select two or more languages: they are offered in the menu: ok

It is a bug that there is no menu visible for users if the admin has selected only one language module. For example, I would like to have only the German language as an option for users available. If the user has "English" in his browser as the preferred language he will see many elements of my page in English, but some elements are only available in German, so he should be able to manually select "German" in the webtrees language menu.

**Comment by hartenthaler** [comment]
Strange observation: if there is only one language module selected, there is no language menu on webtrees main page, but there is a language menu on the admin page.

**Comment by fisharebest** [comment]
> but some elements are only available in German,

Do you mean HTML-blocks (and similar)?

You could make these available for all languages instead of German.

**Comment by hartenthaler** [comment]
Yes, there are some HTML blocks that are available in two translated versions
- in German and
- written in English and available for all other languages.
But that's not a problem, it works as it should.

The problem is that there is no menu if only one language is activated. If there are two or more languages active, then there is a menu.

1. only language "cestina" activated - no menu to select that language in the top right corner (bug)
![Screenshot (105)](https://user-images.githubusercontent.com/6324175/161563268-f75626d3-27e6-4a02-9ad0-d991d05cfc69.png)

2. two languages activated - menu to select a language in the top right corner is visible (ok)
![Screenshot (106)](https://user-images.githubusercontent.com/6324175/161563331-66721495-3200-47dc-9838-00b19a645b92.png)

**Comment by fisharebest** [comment]
The code is working as it was designed.  It uses the same logic as the themes menu.

I think that many people would consider it a bug to show a language menu with only one option.

Also, I think that many people will have selected just one language - and will be confused if the menu suddenly appears.

So, I am reluctant to change this.

**Comment by hartenthaler** [comment]
For the "theme menu" the code is ok; if there is only one theme, then a menu makes no sense. But for the "language" it is different because even if there is only one language selected by the admin, you have as a user the choice to use the language which is defined in your browser or to use the only one language that was selected by the admin.
So the code to show/not to show the menu is the same for "theme" and "language", but the code to decide what should be used is different for "theme" and "language". In my opinion, it would be correct to change the code for the "language" menu.
But you are right that for users that have selected just one language at the moment it could be disturbing. So I can follow your decision.

The reason behind this: we (four people including Sir Peter) are just writing a manual for webtrees in German (see http://www.genwiki.de/Webtrees_Handbuch). When describing the selection of language I found the problem that there was no menu when I expected it to be there.

**Comment by fisharebest** [comment]
> writing a manual for webtrees in German

When you are ready, we can add a link to it here.

https://webtrees.net/user/
