### ISSUE TITLE
2.1: Multi-line formatting still broken

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4281]
Reproducible on the demo server (latest beta):
Add a multi-line inline note to an event:
```
2 NOTE a
3 CONT b
3 CONT c
```

The note is displayed as "a b c".
It should be displayed in three lines (regardless of whether markdown is enabled or not).
Same for TEXT under SOUR, see e.g. [this birth event](https://dev.webtrees.net/demo-dev/tree/demo/individual/i1/Queen-Elizabeth-II).

See e.g. [this older forum post](https://www.webtrees.net/index.php/en/forum/help-for-2-0/36316-note-cont-missing-line-breaks-2-0-19?start=20#88569) for what things to check when fixing this.

**Comment by fisharebest** [comment]
Hopefully.

I created a test for both formatting options ("markdown" and "autolink"):

https://github.com/fisharebest/webtrees/blob/main/tests/app/Factories/MarkdownFactoryTest.php#L127

**Comment by TheDutchJewel** [comment]
@fisharebest closed this in [fisharebest/webtrees@db3f036](https://github.com/fisharebest/webtrees/commit/db3f03687778a9ca480e61247e532d65feca63b1), but is there also a fix for the 2.0.x version? 

Because in v2.0.23 this problem still exists. 

The latest version without this problem is 2.0.19.
