### ISSUE TITLE
2.1: Question about a custom edit control

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4283]
In 2.0, I have a custom edit control for _LOC:MAP which provides a map as an alternative way to set the coordinates, like this:

<img width="463" alt="MAP" src="https://user-images.githubusercontent.com/18174787/160669647-0d636f3c-bb3b-4fb1-a09a-1e22c721031c.PNG">

(i.e. adapted from Control panel / Geographic data / Some Place / Edit)

I'm wondering whether there is a 'supported' way to have something like this in 2.1. Adding the map either to the coordinates element (currently an EmptyElement), or to LATI or LONG is visually not optimal because it isn't displayed full-width. Doing this properly would perhaps require a new method additionalEditControl() on AbstractElement, to be called [from around here](https://github.com/fisharebest/webtrees/blob/9212740242555a3293ede021c65afcdf1dbfabaa/resources/views/edit/edit-gedcom-fields.phtml#L58).

Are there any other edit controls that would benefit from something like this, or is there a better way?

**Comment by fisharebest** [comment]
The HTML for these edit controls is hierarchical.

The `MAP` element can easily find its child `LATI` / `LONG` using javascript (and vice-versa).

We currently use this in the auto-complete for `SOUR:PAGE`.

For `MAP`, I was planning to use a bootstrap modal, but your inline approach should also work.

> s visually not optimal because it isn't displayed full-width.

Can you use CSS for this (`position` / `size`)?
