### ISSUE TITLE
2.1: Broken select control in Relationships chart

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4286]
Reproducible on demo server ([e.g. via this](https://dev.webtrees.net/demo-dev/tree/demo/relationships-0-99/i1)):
Cannot select a second individual. Requests to 'https://dev.webtrees.net/demo-dev/tree/demo/tom-select-individual?&query=xyz' fail (response code 400) with "The parameter “at” is missing."

**Comment by fisharebest** [comment]
This is a regression caused by the fix to #4280
