### ISSUE TITLE
2.1 B2 (new) It is no longer possible to download only the Gedcom zipped without media files

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4288]
![grafik](https://user-images.githubusercontent.com/16499744/161703732-cebf603c-2270-4797-b92e-5cf8393e4d17.png)

**Comment by fisharebest** [comment]
This was a deliberate change.

I do not see the need for it.

Historically, it was done to make the download faster.  But now we compress the HTTP responses, so this is not necessary.

**Comment by FrankWarius** [comment]
it's a question of  space - even on Onedirve (with windows, the entire folder is compressed)
actual Gedcom uncompressed 5.2 MB / 2022-03-19 compressed 1 MB 
I have monthly backups back to 2007

**Comment by Lars1963** [comment]
I would like to have the ZIP-Download back also. Is saves me the trouble of compressing the GEDCOM **after** the download, as my cloudspace is limited.

**Comment by hartenthaler** [comment]
Does GEDCOM 7.0 allow a zipped GEDCOM without media files? Then I would prefer to have it available again.
