### ISSUE TITLE
2.1 B2 (new) Website logs are empty - Undefined array key &quot;tree&quot; …\app\Services\SiteLogsService.php:43

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4289]

**Comment by fisharebest** [comment]
I cannot reproduce this.

Where do you see this error?

* on screen
* in the logs

**Comment by FrankWarius** [comment]
in the SQL log table; screen remains empty 
Undefined array key &quot;tree&quot; …\app\Services\SiteLogsService.php:43
#0 …\app\Services\SiteLogsService.php(43): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(2, &#039;Undefined array...&#039;, &#039;D:\\Web\\WT2\\app\\...&#039;, 43)
#1 …\app\Http\RequestHandlers\SiteLogsData.php(59): Fisharebest\Webtrees\Services\SiteLogsService-&gt;logsQuery(Array)
#2 …\app\Http\Middleware\RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\SiteLogsData-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#3 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#4 …\app\Module\HitCountFooterModule.php(157): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#5 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#6 …\app\Http\Middleware\AuthAdministrator.php(53): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#7 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthAdministrator-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#8 …\app\Http\Middleware\CheckCsrf.php(76): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#9 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#10 …\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#11 …\app\Webtrees.php(265): Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest))
#12 …\app\Http\Middleware\Router.php(150): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array)
#13 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#14 …\app\Http\Middleware\BootModules.php(60): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#15 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#16 …\app\Http\Middleware\RegisterGedcomTags.php(56): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#17 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#18 …\app\Http\Middleware\LoadRoutes.php(75): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#19 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#20 …\app\Http\Middleware\UseTransaction.php(45): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#21 …\vendor\illuminate\database\Concerns\ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#22 …\app\Http\Middleware\UseTransaction.php(46): Illuminate\Database\Connection-&gt;transaction(Object(Closure), 3)
#23 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#24 …\app\Http\Middleware\DoHousekeeping.php(73): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#25 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#26 …\app\Http\Middleware\UseTheme.php(69): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#27 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#28 …\app\Http\Middleware\CheckForMaintenanceMode.php(51): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#29 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#30 …\app\Http\Middleware\UseLanguage.php(71): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#31 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#32 …\app\Http\Middleware\UseSession.php(78): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#33 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#34 …\app\Http\Middleware\UpdateDatabaseSchema.php(57): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#35 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#36 …\app\Http\Middleware\UseDatabase.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#37 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#38 …\app\Http\Middleware\BadBotBlocker.php(233): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#39 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#40 …\app\Http\Middleware\CompressResponse.php(73): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#41 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#42 …\app\Http\Middleware\ContentLength.php(40): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#43 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#44 …\vendor\middlewares\client-ip\src\ClientIp.php(65): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#45 …\app\Http\Middleware\ClientIp.php(47): Middlewares\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#46 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#47 …\app\Http\Middleware\HandleExceptions.php(90): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#48 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#49 …\app\Http\Middleware\BaseUrl.php(78): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#50 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#51 …\app\Http\Middleware\ReadConfigIni.php(68): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#52 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#53 …\app\Http\Middleware\SecurityHeaders.php(48): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#54 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#55 …\app\Http\Middleware\EmitResponse.php(57): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#56 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#57 …\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#58 …\app\Webtrees.php(265): Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest))
#59 …\app\Webtrees.php(252): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array)
#60 …\index.php(51): Fisharebest\Webtrees\Webtrees-&gt;httpRequest()
#61 {main}

**Comment by FrankWarius** [comment]
![grafik](https://user-images.githubusercontent.com/16499744/161746176-f3b06419-2777-4dcb-95ff-b502fd5ad6d5.png)

**Comment by fisharebest** [comment]
What URL are you viewing when you see the error?

**Comment by fisharebest** [comment]
Do you use any custom modules?  Do you also see the error if you disable the modules?

**Comment by fisharebest** [comment]
This is the same cause as #4286 and #4287.
