### ISSUE TITLE
problem to display fan chart in french ok english

### ISSUE THREAD

**Issue by Fa10175** [fisharebest/webtrees#429]
( ! ) Notice: Array to string conversion in C:\wamp\www\webtrees\app\I18N.php on line 447
Call Stack
#	Time	Memory	Function	Location
1	0.0200	140096	{main}( )	..\fanchart.php:0
2	25.6615	12030192	Fisharebest\Webtrees\FanchartController->generateFanChart( )	..\fanchart.php:124
3	26.7729	13432432	Fisharebest\Webtrees\I18N::translate( )	..\FanchartController.php:384
4	26.7729	13432680	call_user_func_array ( )	..\I18N.php:447

**Comment by fisharebest** [comment]
Are you using the latest versions of the language files?

You can download them from the demo server:

dev.webtrees.net/demo-dev/language/fr.mo

**Comment by Fa10175** [comment]
i update with this file and it's ok
