### ISSUE TITLE
2.1: I18N source string with html code

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4290]
[This doesn't look good](https://github.com/fisharebest/webtrees/blob/2839cc24da7b441a9751a07cf82606fbefad22b4/resources/views/fact-association-structure.phtml#L97) (same string a few lines further down). Is the markup actually supposed/required to be 'translated'?

I suggest to do it like this, if the full flexibility of formatting is actually required:

```
$part1 = /* I18N: relationship description, label part */I18N::translate('%1$s:', $label);
$part2 = /* I18N: relationship description, separator part */I18N::translate(' ');
$part3 = /* I18N: relationship description, value part */I18N::translate('%1$s', $value);
        
$asso  = /* I18N: relationship description, consisting of label, separator, and value */I18N::translate(
                '%1$s%2$s%3$s', 
                '<span class="field" dir="label">' . $part1 . '</span>', 
                $part2,
                '<span class="field" dir="auto">' . $part3 . '</span>');
```

In any case this should be documented for translators?

**Comment by fisharebest** [comment]
This translation exists for French users, who need a half-width space before the colon.

Most of these had already been updated to use `I18N::translate('%1$s: %2$s', $label, $value);`

**Comment by fisharebest** [comment]
On a related note, I plan to create a class for all user-generated text.

This will be simpler than adding `dir="auto"` everywhere.
