### ISSUE TITLE
2.1 how to hide an _UID tag of FAM from an INDI display

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4294]
In my webtrees installation, _UID tags are also generated for new FAMs. These are displayed on the INDI display.

![grafik](https://user-images.githubusercontent.com/16499744/162389860-c4567c29-5e8b-48af-a354-5e869443f1af.png)
In https://wbt.warius.info/admin/tags I can't enter _UID

**Comment by fisharebest** [comment]
Privacy rules - "hide from everybody"

**Comment by FrankWarius** [comment]
this not the intention.
I need the _UID of the family in the FAM display but not in the INDI display.
It's not possible to enter _UID in /admin/tag to select hide

**Comment by FrankWarius** [comment]
I think it's a bug or a feature request.
The FAM information is sometimes repeated twice on the INDI side
![Screenshot 2022-04-13 111048](https://user-images.githubusercontent.com/16499744/163145403-dd614656-53b7-4556-8cc7-cb111c222ddd.jpg)
![Screenshot 2022-04-13 112238](https://user-images.githubusercontent.com/16499744/163145419-6a40c5be-aa22-4279-a25b-7e2266ec356c.png)
.
