### ISSUE TITLE
Layout Favourites module

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#4297]
![chartbox](https://user-images.githubusercontent.com/55854079/162568299-4128876c-aacd-483c-8411-927315b99531.jpg)
In the Favourites module, there is missing space between the chart-boxes in all themes.
Not sure this would be the correct solution: 

```
[dir] .wt-chart-box {
    padding: 2px;
    margin: 4px;
}

```
(Personally, in FAB and colours themes I would prefer border-color #ccc on both male and female boxes)

![fab](https://user-images.githubusercontent.com/55854079/162568351-dccf99f9-7a25-42f2-9e82-4408c72a83fe.jpg)

**Comment by fisharebest** [comment]
Padding is the responsibility of the thing that uses the chart-box - not the chart-box itself.

(Otherwise charts with lines would not join up.)

So we need to make a change to the favorites block.
