### ISSUE TITLE
Error in privacy settings

### ISSUE THREAD

**Issue by HRN-webtrees** [fisharebest/webtrees#430]
In Manage family trees -> Preferences,  "Images without watermarks" set to "Show to visitors" does not take action.
Even worse, when doing this, all settings in Manage family trees -> Privacy are reset to "Show to visitors", age at which to assume dead is set to 100, and Extended privacy to dead individuals is reset to 0,0

**Comment by HRN-webtrees** [comment]
Still, Privacy settings are reset when doing changes to Preferences!

**Comment by fisharebest** [comment]
OK - I see it now.  Fixed
