### ISSUE TITLE
Media objects listed twice

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#4301]
In 2.1, I noticed quite a lot of my media objects for some reason supposedly were linked to two individuals, but were actually linked twice to the same indidual.
It appairs all these media objects have some "old" 1 _WT_OBJE_SORT tags, and deleting these tags solves the issue. 
I have 7k individuals and more than 14k media objects, so a quick fix (regex) to clean out these tags from the GED file, would be highly appreciated :) 

![200056](https://user-images.githubusercontent.com/55854079/162587217-c1251834-7052-4bb4-a697-42c571e43d38.jpg)

**Comment by fisharebest** [comment]
There is a "data-fix" available in the control panel.

It will re-order your media objects according to the _WT_OBJE_SORT tags - and then delete the tags.

**Comment by fisharebest** [comment]
I cannot reproduce this.

I created two links from an individual to the media object, using both `OBJE` and `WT_OBJE_SORT` tags.

<img width="335" alt="Screenshot 2022-04-09 at 20 06 20" src="https://user-images.githubusercontent.com/2306088/162588235-190f3bcd-87f5-4e6e-8ddc-940b384635ba.png">

I only see the individual once on the media page.

If you can still reproduce this, can you provide an example GEDCOM.

**Comment by HRN65** [comment]
Look at M498
[clippings.zip](https://github.com/fisharebest/webtrees/files/8457639/clippings.zip)

**Comment by fisharebest** [comment]
Which media object in the clippings file?

**Comment by HRN65** [comment]
Try M23, or any that has a INDI:_WT_OBJE_SORT

**Comment by fisharebest** [comment]
M23 shows only 1 individual.

<img width="795" alt="Screenshot 2022-04-09 at 22 18 23" src="https://user-images.githubusercontent.com/2306088/162591967-b5f220b4-7f21-4e43-8d69-ddb05d2f1315.png">

**Comment by HRN65** [comment]
Strange. This is what I see
![232024](https://user-images.githubusercontent.com/55854079/162592015-aa920c58-2951-4a10-808f-889b8fbe5e94.jpg)

**Comment by fisharebest** [comment]
Which version *exactly*?

2.1.0-beta.2?
latest code from github?

**Comment by fisharebest** [comment]
There was a bug introduced in 3793e425c2785d459ca4db6202cc4a6b01e4a322 (after the 2.1.0-beta.2 release) which prevents links from being recorded correctly.  This is why I cannot see your duplicate.

Fixing this bug and re-importing the clippings cart means that I can now see 2 individuals.

**Comment by HRN65** [comment]
I'm on 2.1.0-beta.2

**Comment by HRN65** [comment]
Thank you!
