### ISSUE TITLE
2.1: Gedcom.php: Inconsistent and missing translations

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4303]
Several custom elements have labels without translations, is this intentional?

[E.g. here](https://github.com/fisharebest/webtrees/blob/86070f864cdeaaac8a3c643b8e44b4d3097298ab/app/Gedcom.php#L895), and in the following lines - there are many others.

Others, which are repeated in different methods, are [translated sometimes](https://github.com/fisharebest/webtrees/blob/86070f864cdeaaac8a3c643b8e44b4d3097298ab/app/Gedcom.php#L1401), but [not always](https://github.com/fisharebest/webtrees/blob/86070f864cdeaaac8a3c643b8e44b4d3097298ab/app/Gedcom.php#L1115) - at least this should be done consistently. It currently has the effect that e.g. an existing German translation is not applied, if the final definition doesn't have the I18N method.

**Comment by fisharebest** [comment]
> Several custom elements have labels without translations, is this intentional?

Yes.  These are tags for which I have no good documentation or examples.
I'm not even sure where they belong.  e.g. `INDI:_INDG` or `INDI:NAME:_INDG`.

> Others, which are repeated in different methods, are [translated sometimes] - at least this should be done consistently.

For `_NAME` => "Name of addressee", this is an error, and should be fixed.
