### ISSUE TITLE
Minimal theme colour differences v2.0 -> v2.1

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4306]
![v2](https://user-images.githubusercontent.com/104515/163140727-28048281-b25a-49a5-8790-b432f05db333.jpg)
![v2 1](https://user-images.githubusercontent.com/104515/163140738-d4217a6d-5f9b-4a4f-873f-6c5631478299.jpg)

**Comment by fisharebest** [comment]
The change was intentional.  I think the theme is easier to use when the links are visible.
