### ISSUE TITLE
No access as visitor

### ISSUE THREAD

**Issue by HRN-webtrees** [fisharebest/webtrees#431]
As visitor I have no access to my family tree (Set to "Show to visitors") but are taken to login.php?url=index.php%3F
Trying different urls, I can access through madialist.php -> Family trees

**Comment by KosherJava** [comment]
Probably related to http://www.webtrees.net/index.php/en/forum/3-help-for-beta-and-github-versions/30098-tree-stuck-at-calculating 
I have the same issue. Somehow the tree that had been imported is lost, and I can't reimport. the redirect to login at index.php%3F is something I see for non-logged in users.

**Comment by KosherJava** [comment]
After the latest git checkin, i re-imported and save the gedcom privacy config (with no changes), and things started working.

**Comment by HRN-webtrees** [comment]
Still not working. When logging out, I'm taken to login.php?url=index.php%3F

**Comment by fisharebest** [comment]
Are you still having problems?

If visitors cannot log in, it often indicates that none of the (public) trees are imported.

Since we are not seeing this problem on other sites, I guess it is just you.  What further information can you give that might help identify what it is (and why it only affects you).

**Comment by HRN-webtrees** [comment]
Wiped everything and reinstalled 1.6.2 and all is fine. 
Again upgraded to latest dev, and problem is back:

Family tree is set to "Show to visitors"

When entering the site (http://localhost/webtrees/), I'm redirected to http://localhost/webtrees/login.php?url=index.php%3F
Logging in as member reloads http://localhost/webtrees/login.php?url=index.php%3F, but "My pages" appears in upper right corner indicating I'm logged in. (see img)
Clicking "My page" takes me to http://localhost/webtrees/login.php?url=index.php%3Fctype%3Duser%26 and
clicking "My account" takes me to http://localhost/webtrees/login.php?url=edituser.php%3F, both displaying the login page.

Logging in as administrator takes me to http://localhost/webtrees/admin_trees_manage.php. Her, all links (except the one to my family tree) will just reload the page.

Clicking my family tree under "Manage family trees" expands the menu, and clicking "Preferences" takes me to http://localhost/webtrees/admin_trees_config.php?action=general&ged=29082010.GED
From here everything seems to work fine. Clicking "Control panel" takes me to http://localhost/webtrees/admin.php, and all links are working. I can now access my tree through "My page"

Now all looks fine until I log out, and is back to http://localhost/webtrees/login.php?url=index.php%3F
![img1](https://cloud.githubusercontent.com/assets/7372415/6147578/2e930820-b20a-11e4-9e0f-b00a63a2e5df.jpg)

**Comment by fisharebest** [comment]
> Logging in as member reloads 

Have you set your trees to private (require visitor authentication), and then tried to log in as a member who does not actually have any access to any trees?

> Her, all links (except the one to my family tree) will just reload the page.

Any javascript errors on the page?

Are the trees all fully imported?

**Comment by makitso** [comment]
You know, I had this same problem a few days ago, that is going to the login page instead of going to index.php.  IMMS, I fixed it by changing the url to /index.php?ctype=gedcom&ged=Peters Genealogy.  That got me to the home page and the problem never came back.

**Comment by HRN-webtrees** [comment]
Yes, using full url takes me to index.php, and all seems fine. Though, logging in and out again takes me to login.php?url=index.php%3F (At least, now I can use browsers back button to get to index.php)

Tree is not private and fully imported
I see no javascript errors
Tested in Chrome, IE and FF

**Comment by fisharebest** [comment]
Have you set either SERVER_URL or LOGIN_URL in your site settings?

**Comment by makitso** [comment]
Probably a dumb question but, are all your folders the same as on git?  The reason for this statement is that about the same time, I failed to copy one of the folders to my dev system and that may have been the problem.

**Comment by HRN-webtrees** [comment]
Both SERVER_URL and LOGIN_URL are blank

**Comment by KosherJava** [comment]
What I had to do to solve this (mentioned above) was to save the family settings from the admin UI (without any change). Something must have changed to cause the tree to appear private in the new Git that was fixed with a re-save.

**Comment by KosherJava** [comment]
Latest Git update and the issue returned, and I feel that it is unrelated to what I stated before. Historically my users have gone to http://mydomain.com/wt/ . Going to this results in a redirect to http://mydomain.com/wt/login.php?url=index.php%3F forcing a login.
However if the user goes to http://mydomain.com/wt/index.php?ctype=gedcom&ged=myfam.ged he will get in properly, and then goes to http://mydomain.com/wt/ he will get right in. It almost seems as if there is a cookie that is storing the gedcom, and if that was never there the default URL will not work.

**Comment by fisharebest** [comment]
If you are being redirected to the login page, then webtrees thinks you do not have access to the current (or any?) tree.

Check the permissions very carefully.

**Comment by KosherJava** [comment]
There is only 1 tree and access is open to the public, but if I do not pass the GEDCOM ID in the first request I am being redirected to the login page. Once I pass the gedcom once I seem to be good for that session.

**Comment by KosherJava** [comment]
Thanks Greg. The "random" tree fix works perfectly in my case where there is only 1 tree.

**Comment by HRN-webtrees** [comment]
Thank you. It's working fine now.
