### ISSUE TITLE
Additional GEDCOM tags does not work in every case

### ISSUE THREAD

**Issue by webtrees-pesz** [fisharebest/webtrees#4319]
When I check the Fax, Phone, and URL tags in the list of GEDCOM tags in the control panel, they do not appear when I edit facts, such as residence.
They also do not appear when I select "Edit with all GEDCOM tags".

**Comment by fisharebest** [comment]
This was fixed in 302fdb8d52cb4f4341c6cc9dc09d1eb0794caab6
