### ISSUE TITLE
Bug if block module is deleted from disk

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#432]
Occurs in 1.6.2+ and probably earlier

I realise this is fairly obscure.

Noticed when changing the git branch on the development setup. If module.php for an active block is deleted from the disk then an error of the form below is raised

    Fatal error: Class 'Fisharebest\Webtrees\some_WT_Module' not found in <path to>index.php on line 105

**Comment by fisharebest** [comment]
Is this for a core module or  a custom module?

**Comment by ddrury** [comment]
either

**Comment by fisharebest** [comment]
In 1.7.0, this shouldn't happen as we autoload all the (core) modules. I'd need to check what happens with custome modules.

**Comment by ddrury** [comment]
On a core module you also get an error message of the form

Warning: include(<path>modules_v3/<module folder>/module.php): failed to open stream: No such file or directory in <path>\vendor\composer\ClassLoader.php on line 412

**Comment by fisharebest** [comment]
I think this is now fixed.  Re-open or raise another issue if you find otherwise...
