### ISSUE TITLE
Prohibited signs

### ISSUE THREAD

**Issue by webtrees-pesz** [fisharebest/webtrees#4320]
On the individual page, the Prohibited signs appear in the section of the extra information when I use a tree with GEDCOM 7.0 (maximal70.ged). [https://gedcom.io/testfiles/gedcom70/maximal70.ged](url)
The same signs appear "oversized" at the bottom of the page.

What does this sign mean?

**Comment by fisharebest** [comment]
I see the issue in 2.1.0

I cannot reproduce it in the latest code.

Presumably it has been fixed by some other change.
