### ISSUE TITLE
2.1.0 / 2.1.1Dev Cleanup Data Folder: Error The parameter “dbtype” is missing.

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4324]
I think that was still OK in 2.1.0 B1.
Calling Control panel/Clean-up data folder (http://dev.warius.info/index.php?route=%2Fadmin%2Fclean) results

The parameter “dbtype” is missing.

No entries in any log.

**Comment by FrankWarius** [comment]
this works with dbtype="mysql" 
But I use MariaDB, what ist he correct entry?

**Comment by fisharebest** [comment]
this is correct.

mariadb and mysql both use the same driver

**Comment by fisharebest** [comment]
Was fixed in de7806433751628aac0849317c07c2ed20d673ff
