### ISSUE TITLE
Running 2.1.0 released on 4-20-2022 get Fatal PHP error I18N::$translator must not be accessed before initialization

### ISSUE THREAD

**Issue by Commando677** [fisharebest/webtrees#4328]
When trying to run the new release or doing an upgrade from 2.0 I get the following PHP error on a server running with PHP 8.0.11.

PHP Fatal error:  Uncaught Error: Typed static property Fisharebest\Webtrees\I18N::$translator must not be accessed before initialization in \webtrees\app\I18N.php:361

**Comment by fisharebest** [comment]
Do you just get this one line error, or is there a full stack-trace?

**Comment by Commando677** [comment]
I did get a full trace here you go.
Stack trace:
#0 \webtrees\app\Validator.php(334): Fisharebest\Webtrees\I18N::translate()
#1 \webtrees\app\Http\Middleware\BaseUrl.php(54): Fisharebest\Webtrees\Validator->string()
#2 \webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#3 \webtrees\app\Http\Middleware\ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#4 \webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#5 \webtrees\app\Http\Middleware\SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#6 \webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#7 \webtrees\app\Http\Middleware\EmitResponse.php(57): Middleland\Dispatcher->handle()
#8 \webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#9 \webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher->handle()
#10 \webtrees\app\Webtrees.php(265): Middleland\Dispatcher->dispatch()
#11 \webtrees\app\Webtrees.php(252): Fisharebest\Webtrees\Webtrees::dispatch()
#12 \webtrees\index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#13 {main}

**Comment by fisharebest** [comment]
Do you have an entry for `base_url` in the file `data/config.ini.php`

https://webtrees.net/faq/config-ini-php/

**Comment by Commando677** [comment]
No I do not have an entry for that. Just the following.

; <?php exit; ?> DO NOT DELETE THIS LINE
dbhost="localhost"
dbport="3306"
dbuser="someuser"
dbpass="somepassword"
dbname="webtrees"
tblpfx="wt_"

**Comment by Commando677** [comment]
That was it, I updated my config to match the default config with the base url and rewrite info and now it works. Thanks for the quick response.
