### ISSUE TITLE
Views/Icons: query or bug

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4329]
Some (if not all) of the icons end with <?php, for example
`resources/views/icons/add.phtml`

Is this a bug or doing something clever?

**Comment by fisharebest** [comment]
These icon files should not have any trailing whitespace - as it breaks some of the layouts.

We could save the files without a final newline.  But that would break the PSR coding standards.  Most editors will add them back again.

So, the PHP open tag actually consists of `<?php` plus an optional newline character.

So, this open tag is there to "eat" the final newline.

> doing something clever

Yes :-)
