### ISSUE TITLE
Name boxes in charts are too small - demo-dev and my test systems

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#4333]
I would print 2-3 name lines and birth and death lines. Now the last line prints partially outside the box and data is missing.

**Samples**

**Small boxes**
Family book
Hourglass chart
Pedigree
Relationships
![image](https://user-images.githubusercontent.com/5202996/164549845-25762612-ba5b-4f6e-8a9e-51295b379f1a.png)
We do neither see birth nor death data.

![MorduchSmall1](https://user-images.githubusercontent.com/5202996/164549309-2b7181ba-1e31-458d-8148-19bd9bcc0a24.jpg)
We see partial birth data, but no death data

**Bigger boxes**
Ancestors
Descendants
Family page

![ancestors-demo](https://user-images.githubusercontent.com/5202996/164549300-1a7ff4cd-ee67-43e7-8cf4-f9cdf4ad0cf0.jpg)
We see partial birth data, but no death data

![image](https://user-images.githubusercontent.com/5202996/164550415-ea1c0e4a-1bf9-44ae-aa2a-251418a2f385.png)
We see partial death data. We do not see the country.

**Comment by fisharebest** [comment]
See also #4323

**Comment by melizaa** [comment]
On my production site the boxes are

![image](https://user-images.githubusercontent.com/5202996/165135599-aedb2b29-108f-4d68-ae31-e5fb542d6b77.png)

and

![image](https://user-images.githubusercontent.com/5202996/165135977-103a2a65-fbe2-4034-bdfc-d0098746c3a2.png)

I tried to shorten the main names to fit on one row.

**Comment by fisharebest** [comment]
I think this is the same issue as #4323 so I will continue the discussion there.
