### ISSUE TITLE
Error 500 after upgrade

### ISSUE THREAD

**Issue by mr2017x** [fisharebest/webtrees#4337]
Hi,

after upgrading (internal automatic) from either 1.7.9 (went back) or 2.0.3 to 2.1.0 error 500 came up. Is there a known error?

Uncaught Error: Typed static property Fisharebest\Webtrees\I18N::$translator must not be accessed before initialization in /var/www//app/I18N.php:361
Stack trace:
#0 /var/www//app/Validator.php(334): Fisharebest\Webtrees\I18N::translate()
#1 /var/www//app/Http/Middleware/BaseUrl.php(54): Fisharebest\Webtrees\Validator->string()
#2 /var/www//vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#3 /var/www//app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#4 /var/www//vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#5 /var/www//app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()

**Comment by Lars1963** [comment]
You have to set the base_url in your config. As of 2.1 this mandatory.

See [webtrees.net/faq/config-ini-php/](https://webtrees.net/faq/config-ini-php/)

**Comment by mr2017x** [comment]
> You have to set the **base_url** in your config. As of 2.1 this is mandatory. So you didn't read https://webtrees.net/upgrade/2.0/
> 
> Also see [webtrees.net/faq/config-ini-php/](https://webtrees.net/faq/config-ini-php/)
> 
> A sort of fix now in [d5ee013](https://github.com/fisharebest/webtrees/commit/d5ee013a23e7982599a97a61594ede84e5f8244f)

great, i was already on 2.0.x but it wasn't running smooth. but now i handled it somehow. but maybe this could be implemented in further deployments as also it get asked for outdated modules? :)

**Comment by mr2017x** [comment]
But now i get errors when trying to get an Fhourglass diagramm in a specific way - setting to e.g. 4th level - 500error, setting to 4th level with spouse - working fine?

**Comment by Lars1963** [comment]
> > You have to set the **base_url** in your config. As of 2.1 this is mandatory. So you didn't read https://webtrees.net/upgrade/2.0/
> > Also see [webtrees.net/faq/config-ini-php/](https://webtrees.net/faq/config-ini-php/)
> > A sort of fix now in [d5ee013](https://github.com/fisharebest/webtrees/commit/d5ee013a23e7982599a97a61594ede84e5f8244f)
> 
> great, i was already on 2.0.x but it wasn't running smooth. but now i handled it somehow. but maybe this could be implemented in further deployments as also it get asked for outdated modules? :)
Allready in https://github.com/fisharebest/webtrees/commit/d5ee013a23e7982599a97a61594ede84e5f8244f

**Comment by fisharebest** [comment]
`base_url` issue fixed in #4328

> But now i get errors when trying to get an Fhourglass diagramm in a specific way - setting to e.g. 4th level - 500error, setting to 4th level with spouse

Please create a separate issue for each problem.  You will also need to provide more information.  e.g. what errors?
