### ISSUE TITLE
Show private relationships

### ISSUE THREAD

**Issue by HRN-webtrees** [fisharebest/webtrees#434]
Control panel -> Manage family trees -> Privacy -> Show private relationships

Visual feedback does not correspond to choises.
Show to visitors is missing from the menu. 
Or should this be Y/N?

**Comment by fisharebest** [comment]
It is implemented internally as a boolean, but I wanted to use the same format for all the options.

The label in the drop down may need chaning to "show to visitors" / "hide from everyone"
