### ISSUE TITLE
Class form-check-label is replaced with form-label in bootstrap 5

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#4340]
The class form-check-label doesn't exist in bootstrap 5. It is replaced by form-label.

See: https://getbootstrap.com/docs/5.0/migration/

Used in views/components/checkbox and maybe in other places too.

It provides a small bottom margin so the checkbox items are not too close together.

**Comment by JustCarmen** [comment]
It is confusing, because here it seems the class does exists: https://getbootstrap.com/docs/5.0/forms/checks-radios/ but it appears to do nothing and there is no css rule attached to it.

**Comment by fisharebest** [comment]
Good question.  I copied the markup from the documentation.

Is there anywhere that this causes a problem with the layout?

**Comment by JustCarmen** [comment]
I noticed it on the configuration page of the module Fancy Research Links where I have a list of checkboxes using the default checkbox view. Those elements were placed to close together.  I am not near my laptop now to look for other places with the same issue but it should be everywhere this view is used.

But it is not a big deal. I solved it by adding a margin class to the parent div.

**Comment by fisharebest** [comment]
> I solved it by adding a margin class to the parent div.

This was a documented change in bootstrap 5

Edit controls no longer have any vertical margins - so you need to add a margin to the parent.
In webtrees, all the edit controls now have `mb-3` on the parent `div`.

**Comment by JustCarmen** [comment]
Clear. I assume this issue is solved then.
