### ISSUE TITLE
"Edit the raw GEDCOM" is missing for some record types

### ISSUE THREAD

**Issue by webtrees-pesz** [fisharebest/webtrees#4341]
For individuals and families, there is an "Edit the raw GEDCOM" entry in the Edit button substructure.
For sources, repositories, media objects, shared notes and submitters, this entry is missing.

**Comment by FrankWarius** [comment]
there is an indirect way:
e.g. Source
press "edit" / "edit" and at the bottom of the page press "edit the raw gedcom"

**Comment by fisharebest** [comment]
This change was intentional.

For these other record types, we now have an "edit record" page which includes all the facts.
(Previously, you could only edit one fact at a time).

So, these records have less need for "edit raw".  This is why the link was moved to the "edit record" page.

**Comment by webtrees-pesz** [comment]
Thanks to both. i knew the way via the „edit record“ page. But applying the old habit, I missed the entry in the edit button.
