### ISSUE TITLE
Note Formatting Broken in v2.0.23

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#4344]
This is a new duplicate of #4136 which I understand was closed since v2.0.17 but from my perspective there is still a major problem preventing me from using any newer version.

Version 2.0.23 does not correctly display any linefeeds in any notes unless they are double linefeeds or unordered lists, making notes ugly and very difficult to read. This is a significant regression for my website.  This was previously reported against versions 2.0.17 through 2.0.19.

**INPUT STEPS**

The test object, as previously reported, is as follows:
```
Draft Registration Cards - Bernard Fitzstephens - WWI (test)

Name in full: Bernard J. Fitzstephens
Age in yrs: 24
Home address: 305 E Court, Caro, Mich
Date of birth: July 28th 1892
Citizenship: Natural born
Where were you born: North Branch Mich U.S.
Present trade, occupation, or office: Electrician
By whom employed: Michigan Sugar Co.
Where employed: Caro Mich
Dependents: Wife / Child 2 1/2 yrs old
Race: White
Do you claim exemption: No
Tall, medium, or short: Tall
Slender, medium, or stout: Slender
Color of eyes: Blue
Color of hair: D Brown
Bald: No
```

1. Navigate to the individual named Bernard Fitzstephens.
2. Edit the Birth fact on the "Facts and events" tab.
3. Click "Source" to add a new citation.
4. After selecting a source name, click the "+" next to Note to create a shared note.
5. Paste the test object into the "Create a shared note" dialog.
6. Click "Save".
7. Click "Save".

**Expected Result - As Seen in v2.0.16**
![screen-2-0-16](https://user-images.githubusercontent.com/1371835/165172510-ff0a901f-0fbf-426c-844c-a80070d7a1e0.png)

**Actual Result - As Seen in v2.0.23**
![screen-2-0-23](https://user-images.githubusercontent.com/1371835/165172555-1794c7ed-9f41-4f59-82b3-6d6a3ccffb94.png)

**Additional Info**
The exact steps above were used in both versions, to demonstrate that the problem is not limited to stored data, but also affects the current I/O.

Items requested by fisharebest:

Line-breaks between paragraphs -- Yes, working, if I manually add two linefeeds instead of one.

Trailing double-spaces -- Yes, working, if I manually add two trailing spaces before each linefeed.

Markdown is enabled and used extensively in notes and text fields.

For testing purposes, I disabled markdown and there was no change in output.  v2.0.16 gives the expected result in both modes, and v2.0.23 strips all single linefeeds in both modes.

**Comment by ddrury** [comment]
The census assistant is still broken in 2.1.0. To make it work two spaces need to be added to function createNoteText as follows (This may be a sticking plaster and not the _real_ solution)
```
        if ($ca_citation !== '') {
            $text .= "  \n" . $ca_citation;
        }

        if ($ca_place !== '') {
            $text .= "  \n" . $ca_place;
        }
```

**Comment by fisharebest** [comment]
I think this is working in the current code.
