### ISSUE TITLE
OBJE File FORM tag produces error/warrning when check for errors is run

### ISSUE THREAD

**Issue by Norwegian-Sardines** [fisharebest/webtrees#4347]
I'm setting this a place holder for additional findings.

The "Check for errors" routine puts out messages (blue warnings?) that say indicate something that should be changed in the GEDCOM:

Media object: M12 — Line number: 6 — 2 FORM jpg
“jpg” should be “JPG”.

1) can't change the FILE:FORM tag can't be changed on the EDIT screen to correct the warning.
2) the FILE:FORM tag is defaulted to lowercase jpg when a new image is added to an OBJE record, thus the error/warning is created
3) Changing the FILE:FORM using MYPHPADMIN will cause errors at runtime, so not an option (not sure what the code does) with the tag!

I'm still trying to understand the issue so this could all be a simple misunderstanding on my part!

**Comment by Norwegian-Sardines** [comment]
We should be ignoring these errors!
![YellowError](https://user-images.githubusercontent.com/66341154/165365306-40685cbd-7881-4798-8dc7-d872a860b785.jpg)

If I set the FILE:FORM to JPG I get that message.

**Comment by fisharebest** [comment]
The `FORM` tag is generated automatically from the file name.

This code converts to lower case.
It should convert to upper case.

**Comment by Norwegian-Sardines** [comment]
The AGE units should remain lower case, but for the “text” CHILD = INFANT = STILLBORN  they should be uppercase for v5.5.1.  I don’t see this as a big deal, so the code can remain the same.  When v7.0.x is implemented these “phrases” should be moved to the appropriate tag, and the AGE tag always use lowercase units.
