### ISSUE TITLE
Error in logic in `longlifeQuery`?

### ISSUE THREAD

**Issue by laryn** [fisharebest/webtrees#4348]
Could it be that `longlifeQuery` only counts people who have died? I was trying to troubleshoot why someone wasn't showing up as the "Individual who lived the longest" on the landing page of the family tree. I found my way over to `longlifeQuery` in `app/Statistics/Repository/IndividualRepository.php` and adjusted it to return two values instead of just one, which showed that the person I was expecting was not shown in the top two. This got me thinking that the issue could be that the person who should be listed in my case is still alive, so perhaps the query is assuming a death date. I couldn't figure out how to insert the current date for people who are still alive.

**Comment by fisharebest** [comment]
There are two separate statistics.

#topTenOldest# - individuals with a birth-date **and** a death-date
#topTenOldestAlive# - individuals with a birth-date and **no** death-date

**Comment by fisharebest** [comment]
> Or is part of the issue that it could start showing people as hundreds of years old if the data regarding deaths isn't updated?

Exactly that.
