### ISSUE TITLE
Events of close relatives

### ISSUE THREAD

**Issue by HRN-webtrees** [fisharebest/webtrees#435]
When displaying Events of close relatives on INDI pages, christening/baptism and burials of close relatives are displayed.
In Manage family trees -> Preferences only Birth, Marriage and Death can be chosen.
Should we have christening/baptism and burials removed for consistency?

**Comment by fisharebest** [comment]
This is intentional.

For "birth", we also show baptism, christening, adoption, etc.
For "death", we also show burial, cremation, etc.

This to allow for cases when we only have christening/burial - e.g. old records from church registers.

**Comment by HRN-webtrees** [comment]
OK. Makes sense
