### ISSUE TITLE
Broken system after upgrade to 2.1

### ISSUE THREAD

**Issue by davidtessier** [fisharebest/webtrees#4351]
Hey there!

I upgraded Webtrees yesterday to 2.1 from 2.0.x - I don't remember the exact number, but I think it was the previous release because I do keep this up to date. The application is unusable and broke after the update :( 

I used the automated updater built into the app as I normally do. It showed a bunch of successful messages as it went throug the process, but then when it came time to re-load after the update, the following error is shown. 

Do you have any idea what I can do? I don't see anything in my `/var/log/apache/error.log`

I'm running a LAMP stack with PHP 7.4.3 on Ubuntu 20.04.4 LTS
I've never had issues like this before and I've been using Webtrees for a couple of years (love your product by the way!)

`
Error: Class 'Fisharebest\Webtrees\Http\Controllers\Admin\AbstractAdminController' not found in /var/www/webtrees/modules_v4/reminder/src/Http/Controllers/AdminController.php:17 Stack trace: #0 /var/www/webtrees/vendor/composer/ClassLoader.php(571): include() #1 /var/www/webtrees/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile() #2 [internal function]: Composer\Autoload\ClassLoader->loadClass() #3 /var/www/webtrees/modules_v4/reminder/src/Modules/ReminderModule.php(57): spl_autoload_call() #4 /var/www/webtrees/app/Services/ModuleService.php(906): UksusoFF\WebtreesModules\Reminder\Modules\ReminderModule->boot() #5 /var/www/webtrees/app/Http/Middleware/BootModules.php(58): Fisharebest\Webtrees\Services\ModuleService->bootModules() #6 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process() #7 /var/www/webtrees/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle() #8 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process() #9 /var/www/webtrees/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle() #10 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process() #11 /var/www/webtrees/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle() #12 /var/www/webtrees/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}() #13 /var/www/webtrees/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction() #14 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process() #15 /var/www/webtrees/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle() #16 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process() #17 /var/www/webtrees/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle() #18 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process() #19 /var/www/webtrees/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle() #20 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process() #21 /var/www/webtrees/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle() #22 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process() #23 /var/www/webtrees/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle() #24 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process() #25 /var/www/webtrees/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle() #26 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process() #27 /var/www/webtrees/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle() #28 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process() #29 /var/www/webtrees/app/Http/Middleware/BadBotBlocker.php(233): Middleland\Dispatcher->handle() #30 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process() #31 /var/www/webtrees/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle() #32 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process() #33 /var/www/webtrees/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle() #34 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process() #35 /var/www/webtrees/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle() #36 /var/www/webtrees/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process() #37 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process() #38 /var/www/webtrees/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle() #39 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process() #40 /var/www/webtrees/app/Http/Middleware/BaseUrl.php(78): Middleland\Dispatcher->handle() #41 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process() #42 /var/www/webtrees/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle() #43 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process() #44 /var/www/webtrees/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle() #45 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process() #46 /var/www/webtrees/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle() #47 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process() #48 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #49 /var/www/webtrees/app/Webtrees.php(265): Middleland\Dispatcher->dispatch() #50 /var/www/webtrees/app/Webtrees.php(252): Fisharebest\Webtrees\Webtrees::dispatch() #51 /var/www/webtrees/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest() #52 {main}
`

**Comment by Lars1963** [comment]
You have to set the base_url in your config. As of 2.1 this is mandatory. So you didn't read https://webtrees.net/upgrade/2.0/

Also see [webtrees.net/faq/config-ini-php/](https://webtrees.net/faq/config-ini-php/

**Comment by Lars1963** [comment]
> Thanks for the tip but I do have the base_url set in the config.

Can you Show me the exact entry?

**Comment by Lars1963** [comment]
Try `base_url="https://x.xxxx.ca/webtrees`"

**Comment by davidtessier** [comment]
That's a great find! Thank you. 
I got it working after the following steps since I couldn't access the UI to remove it. 

- Remove the reminder module from the modules_v4 folder `sudo rm -rf /var/www/webtrees/modules_v4/reminder/` 
- Removed the reminder row from the **wt_module_setting** table (had to do this before the next step).
```sql
DELETE FROM `wt_module_setting`
WHERE `module_name` = '_reminder_' ;
```
- Remoevd the reminder row from the **wt_module** table 
```sql
DELETE FROM `wt_module`
WHERE `module_name` = '_reminder_';
```

Thank you very much for your support with this! 

Keep up the amazing work on this product. <3
