### ISSUE TITLE
v2.1 - Feature request - PLAC for research tasks

### ISSUE THREAD

**Issue by mpwt** [fisharebest/webtrees#4355]
In addition to the date, could a location input (PLAC) be integrated for research tasks? 

Since v1.7 I use this for example to specify the archive. The simple solution via app/config.php is gone with v2.1. Am I the only one ... what files would I need to customize to be able to enter a location?

**Comment by fisharebest** [comment]
If you do this, it would affect the place-hierarchy functions.

For example, if you enter the location of a place you want to visit to check some records, the individual would be linked to that place - even if they never went near it.

So, I don't think I want to include such a change in the core code.

> what files would I need to customize to be able to enter a location?

Create a module!  Just copy the example one and delete the bits you don't need.

Add a `boot()` function.  It would need one line.

```
Registry::elementFactory()->make('INDI:_TODO')->subtag('PLAC', '0:1');
```
