### ISSUE TITLE
2.1.1 - Fatal error in Example module

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#4356]
When I save the [example module](https://github.com/webtrees/example-module) into the `modules_v4\example_module` folder, I get this error when opening tree in the browser.

![afbeelding](https://user-images.githubusercontent.com/46184729/165946725-5fa28008-dea5-442e-b266-869e7e8597af.png)

All other modules are disabled.

**Comment by fisharebest** [comment]
Works for me with 2.1.1

<img width="380" alt="Screenshot 2022-04-29 at 19 42 52" src="https://user-images.githubusercontent.com/2306088/166006736-8edb134e-3948-4b75-9e55-4634ac025336.png">

Can you double check that you installed the right example-module in the right folder?

The error message suggests that webtrees was trying to load a non-module file

**Comment by TheDutchJewel** [comment]
I used only the file `ExampleModule.php` and renamed it to `module.php`.

It seems I need both the `module.php` and` ExampleModule.php`.
