### ISSUE TITLE
Problem with restrictions (2.1.1)

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#4357]
Event with restriction "Show to members" has a media object also with restriction "Show to members"
Event is not correctly displayed when logged in as administrator. Media object displayed as expected.
[clippings.zip](https://github.com/fisharebest/webtrees/files/8593071/clippings.zip)
![restriction](https://user-images.githubusercontent.com/55854079/166024156-b77af2da-f5bb-46e5-bfea-9535b952bd7b.jpg)

**Comment by JustCarmen** [comment]
I ran into another problem with restrictions. Tested on the demo-dev site:

![image](https://user-images.githubusercontent.com/5641963/166097705-4b02abbc-cdb2-4db9-8b00-b8f7b9d9c7d0.png)

Restriction set on the media object results in 3 icons (1 should be enough I guess). I set 'show to members' as restriction,. It doesn't make any difference if I use 'show to members - only managers can edit'. In both cases, logged in as moderator, I am not able to edit the restriction itself. But I can edit the other entries.
