### ISSUE TITLE
Missing edit raw GEDCOM for media objects

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#4361]
In #4341 it is explained why the "edit raw GEDCOM" option is moved and not directly available anymore on the Edit button. For the media objects I failed to find the moved link. Currently it seems impossible to see/edit the raw decom of media objects. Could this be made available again?

(The updated check for errors routine indicated some errors, which with seeing the raw gedcom were difficult to understand/correct)

**Comment by fisharebest** [comment]
We don't have "Edit raw" for media objects.

The "edit media file" pages are a special case.

If you edit the filename, webtrees will rename the file.

This option also ignores the "pending change" - because we must ensure the filename matches the value in the GEDCOM.

So, this is a deliberate design decision.

**Comment by SnarfW** [comment]
I will probable going the mis the option to see the raw gedcom. As mentioned the check for errors routine indicates on which line the error is reported. Without the possibility to see the raw gedcom it is not always easy to find and correct the error...

**Comment by fisharebest** [comment]
> Without the possibility to see the raw gedcom it is not always easy to find and correct the error...

Just click the edit link for the media-file, and then click save.

This will save the data with the prefered capitalisation.

Or just ignore it for the time being.

In the future, we will probably "fix" this data automatically during import.
