### ISSUE TITLE
Multi line census notes, link to expand the note incorrectly created

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4363]
![demo](https://user-images.githubusercontent.com/104515/166140028-e4e4bce0-8470-49fe-9538-073dabce2604.jpg)

**Comment by ddrury** [comment]
Function `Note::extractNames` needs to obtain the first line by using` "<br>"` as well as `"\n"` as the split characters.

**Comment by miqrogroove** [comment]
I believe multi-line notes are always required to have two linefeeds after the title.  And I doubt this has changed in a long time.  Have you tried that?

**Comment by ddrury** [comment]
Yeah, I've found the problem but there are a number of ways to skin this particular cat so I'll let Greg decide on what to do (see my second comment above)

**Comment by fisharebest** [comment]
The common mark library uses `<br />` for "hard breaks", and a configurable value for soft breaks.
We've been using `<br>`.

Changing our config to `<br />` will simplify the processing.
