### ISSUE TITLE
NAME:RESN causes screen display problems

### ISSUE THREAD

**Issue by Norwegian-Sardines** [fisharebest/webtrees#4370]
I’m not sure if you saw this issue in the forum!

https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/36803-name-resn-causes-screen-display-problems#91191

1) I migrated my production GEDCOM over to webtrees v2.1.1 and saw this issue. The display was correct when I removed the RESN tag. "confidential" and "locked" do not have this issue!

2) I don't see a way on the edit screen to change the restriction.

1 NAME Given /Surname/
2 TYPE BIRTH
2 GIVN Given
2 SURN Surname
2 RESN privacy

**Comment by fisharebest** [comment]
This was reported and fixed in #4357 

I'll create a new release fairly soon.

But if you cannot wait, it is a simple one-line change.

https://github.com/fisharebest/webtrees/commit/f99bbb61d5fc19ed8cfdc1e238f679695462c8af

**Comment by Norwegian-Sardines** [comment]
Thanks Code change worked.  I appreciate the update.
