### ISSUE TITLE
V2 Shared Shared notes in source record are not dispalyed correctly

### ISSUE THREAD

**Issue by ro-la** [fisharebest/webtrees#4371]
In 2.1 in a level 0 source record with a shared note (1 NOTE @n1@) will display only the first line of the note and there is no possibility to display the whole note.

![obrÃ¡zok_2022-05-02_091620488](https://user-images.githubusercontent.com/60657963/166267114-e1681258-b46a-48f0-99c7-bd9b6720fbc4.png)

https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/36812-shared-notes-in-source-record-not-dispalyed-correctly

**Comment by JustCarmen** [comment]
I have found a similar issue with objects and shared notes as described here:

https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/37015-shared-notes-attached-to-media-not-visible-on-the-individual-and-media-page#92596

**Comment by ro-la** [comment]
It is possible that this issue is the same as reported here,
https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/37112-notes-shown-as-links
