### ISSUE TITLE
Block "recent changes": description and headline missing

### ISSUE THREAD

**Issue by ungeahnt** [fisharebest/webtrees#4373]
With commit 501bc70 you have the possibility to switch between 'webtrees database' and 'gedcom database'.

1) What is the difference between both settings?
-> It would be good to describe the diffrences in more detail at the options menu (e.g. text below the menu).

2) The configured block does not show which option is selected in the end. In both cases the headline is only "Changes in the last x days".
-> It would be good to add the selected option ('webtrees db' / 'GEDCOM') to the headline.

**Comment by fisharebest** [comment]
I don't think visitors to a site would need to know the difference.

**Comment by ungeahnt** [comment]
Maybe I'm wrong with the commit?! Actually, I wanted to address this here:

![grafik](https://user-images.githubusercontent.com/28572767/166811557-cb7d5761-1a13-42ee-b33d-dedee8252647.png)

Depending on the selected 'changes-set' (webtrees / genealogy data) I see different content.

**Comment by fisharebest** [comment]
> Maybe I'm wrong with the commit?! Actually, I wanted to address this here:

You have the correct commit.  This is the option.

> Depending on the selected 'changes-set' (webtrees / genealogy data) I see different content.

This is normal/expected.

Suppose you import a GEDCOM file containing this:

```
1 CHAN
2 DATE 01 MAY 2022
```

Now you use the edit-raw function and change this to

```
1 CHAN
2 DATE 02 MAY 2022
```

We now have two different change times.

We know that the edit was made today (5th May)
But the CHAN record says 02 MAY 2022.

So, in the list of recent changes, do we show this as today (`05 MAY 2022`) or `02 MAY 2022`?

**Comment by ungeahnt** [comment]
> So, in the list of recent changes, do we show this as today (05 MAY 2022) or 02 MAY 2022?

Depending on what you want to achieve, the two options make sense. 

But the difference is not only that you have two different change times. 

The 'webtrees' option includes additional items. So I see recent changes on media-objects, which I could not see with the 'genealogy' option (because they are not part of the raw GEDCOM, or?). With the 'webtrees' option I see much more changes in my tree and I think that option 'genealogy' is a subset of option 'webtrees' (but with different timestamps). Am I correct? 

> I don't think visitors to a site would need to know the difference.

Visitors certainly not, but as an admin. I wanted to have a way to trace  **all** the latest changes of my pedigree. However, it's not so easy to see which of the two options is suitable for this. 

If my assumption with the subset is correct, then I will now choose the 'webtrees' option.

However, I still think that the selected option should also be displayed with the block and a description of the function would certainly be helpful.

btw: Thanks a lot for the new Version!

**Comment by fisharebest** [comment]
> The 'webtrees' option includes additional items. So I see recent changes on media-objects, which I could not see with the 'genealogy' option (because they are not part of the raw GEDCOM, or?). With the 'webtrees' option I see much more changes in my tree and I think that option 'genealogy' is a subset of option 'webtrees' (but with different timestamps). Am I correct?

Yes.   A record can have a `CHAN` fact when it was imported - but it has never been edited in webtrees.

You can also edit a record to remove the `CHAN` facts - but it will have an edit-time in the database.

> I wanted to have a way to trace all the latest changes of my pedigree.

If these changes are made in webtrees, then choose the "webtrees" option.
If these changes are made in another application, then choose the "CHAN record" option.

**Comment by ungeahnt** [comment]
> You could use raw GEDCOM editing to remove the CHAN field.

I think I don't want to lose this information. What advantage would it give?

> All combinations are possible

If the information in the two databases can be different for one record, why not combine both information in one table?: 
`'Record' | 'mysql timestamp'- 'editor1' | 'GEDCOM CHAN' - 'editor2'`?

> Yes. A record can have a CHAN fact when it was imported - but it has never been edited in webtrees

GEDCOM-import means deleting the old family tree. This is then like a reset of the 'last changes', isn't it?
Are there other cases - besides the import - where no db-timestamps are set? Probably not and therefore the 'webtrees' option will include almost all changes to the family tree (but unfortunately only the last change per record). Am I right about that?

>  But IMHO, it makes more sense to use only the last edit - not all of them.

It depends on what you are aiming for. I thought 'recent changes' is a 'genealogical summary' of the website-log. I thought I can put the block on MyPage and then see a history of all changes and can go directly to the record with one click (which is not possible in the website-log).
That multiple changes to the same record are not listed is IMHO not so nice.  If I have to restore a db-backup, for example, then I need the information about all changes. It would also be nice to see by whom and when a record was changed. But this is only my opinion, others may want to see only the last change.

**Comment by fisharebest** [comment]
> If the information in the two databases can be different for one record, why not combine both information in one table?:
'Record' | 'mysql timestamp'- 'editor1' | 'GEDCOM CHAN' - 'editor2'?

CHAN records do not have timezones.
The database change records have timezones.

So, it is possible that every change would be shown twice - perhaps one or two hours apart....

----------

It is possible to have a CHAN record in the GEDCOM, a change record in the wt_change table in the database, both or neither.  Both timestamps may be different.

----------

Simple advice - if you edit offline and just use webtrees for display, choose the CHAN records.
If you edit in webtrees, use the database.  It is faster and supports time-zones.

**Comment by ungeahnt** [comment]
Forget the fusion of both options in one table. Due to the different time stamps, one cannot guarantee an exact assignment. In a table this would only lead to wrong assumptions.

However, I still think that the 'webtrees' option should actually contain more of the changes made. 

Regardless of functional changes, my main concern in this issue was that the differences between the two variants are described somewhere (e.g. in the options-menu) and that you can see in the block which option was chosen. 

Is this feasible?

**Comment by fisharebest** [comment]
I do not want to display this information in the block.

This block exists so that visitors to your site can see recent activity.
I don't think they would care about the algorithm used to select it.

Also, I guess that most site visitors do not understand either GEDCOM or databases.

**Comment by ungeahnt** [comment]
> This block exists so that visitors to your site can see recent activity.

I suppose that most wt users are not aware of this limited scope.
Ok, for admins there is the pedigree/changes-log in control-panel.
