### ISSUE TITLE
Editing census shared note produces errors - see attached images

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4376]
![demo1](https://user-images.githubusercontent.com/104515/166904726-df2cf2e1-677f-4324-8efd-b10d1467ad27.jpg)
![demo 2](https://user-images.githubusercontent.com/104515/166904736-738e07fb-0832-4a28-88d0-97b375d4e82c.jpg)

**Comment by fisharebest** [comment]
I'm not seeing this.  Can you share the raw GEDCOM for this?  You may need to export your tree, and use a text editor...

**Comment by ddrury** [comment]
This is on the demo - latest beta

Queen Elizabeth - 1939 English census

**Comment by ddrury** [comment]
Solved with latest commits
