### ISSUE TITLE
Pedigree Map issue

### ISSUE THREAD

**Issue by StarJackie** [fisharebest/webtrees#438]
Hi, ticking the checkbox of "Hide flags" makes no difference. Is that normal? Consequently, the help text is useless.
« Hide the flags that are configured in the googlemap module. Usually these are for countries and states. This serves as a visual cue that the markers around the flag are from the general area, and not the specific spot. »
See for yourself on the Demo page
https://dev.webtrees.net/demo-stable/module.php?ged=demo&mod=googlemap&mod_action=pedigree_map&rootid=i1&PEDIGREE_GENERATIONS=4&hideflags=1

**Comment by fisharebest** [comment]
The demo site doesn't have any flags installed, so hiding them will make no difference ;-)

I will need to install some flags and see what happens....

PS - There is a related bug report at https://bugs.launchpad.net/webtrees/+bug/1421614

Are these options useful?  Would we ever want to hide the lines?  (Or show flags?)
