### ISSUE TITLE
2.1 Featuere Request hide _UID and Source from FAM on INDI Page

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4381]
I think it's a bug or a feature request.
The FAM information is sometimes repeated twice on the INDI side
![Screenshot 2022-04-13 111048](https://user-images.githubusercontent.com/16499744/163145403-dd614656-53b7-4556-8cc7-cb111c222ddd.jpg)
![Screenshot 2022-04-13 112238](https://user-images.githubusercontent.com/16499744/163145419-6a40c5be-aa22-4279-a25b-7e2266ec356c.png)
.

_Originally posted by @FrankWarius in https://github.com/fisharebest/webtrees/issues/4294#issuecomment-1097793823_

**Comment by fisharebest** [comment]
Which version of webtrees?

Family _UID values were removed from the indivdiual facts/events tab in 2.1.2

See https://webtrees.net/blog/2022/05/04/new-webtrees-release-2-1.2.html

**Comment by FrankWarius** [comment]
You are right _UID fixed in 2.1.2 
But Source from FAM still there and irritating

![grafik](https://user-images.githubusercontent.com/16499744/167107412-a5ced9bc-d70e-4887-ad65-a31a29f05e72.png)

I think it should show up with the other sources or just only in the FAM display

**Comment by fisharebest** [comment]
A source citation on a family event would presumably apply to both spouses.
So I think it is correct to show it on the individual page.
