### ISSUE TITLE
EVEN tag does not allow a value

### ISSUE THREAD

**Issue by MarkyJ1** [fisharebest/webtrees#4387]
A value for an EVEN tag cannot be entered when creating a family or individual event. Only a value of 'Y' is allowed via the checkbox - it's occurred but the details aren't known.

The GEDCOM 5.5.1 spec does not explicitly state that this should be allowed for an individual but the example used in the event descriptor is that of an individual.

The GEDCOM 7 spec does allow it.

**Comment by fisharebest** [comment]
This is fixed in the latest development code.  The fix will be included in the next release.
