### ISSUE TITLE
Number of input variables in edit requests is potentially problematic

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4389]
This issue has been revealed by accidentally using the generic edit form for an individual ([see here](https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/issues/79)), but it is actually a potential general problem:

The edit forms send a potentially large number of input variables ([level, tags, and values e.g. here](https://github.com/fisharebest/webtrees/blob/e820a2a4359ba8c938798bfe7bd0430398d3ec2a/app/Http/RequestHandlers/EditFactAction.php#L72)).
If this number exceeds the configured value, php emits a warning "PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini." and truncates the inputs, leading to errors of the kind 

> assert(count($tags) === $count) …\app\Services\GedcomEditService.php:126

This is reproducible by e.g. adding a large number of source citations (like 50 - depending on the actual value of max_input_vars) to an individual fact, and saving from the edit fact dialog after enabling "Edit with all GEDCOM tags".

In practice this is probably largely theoretic, as facts are usually far smaller. I guess there won't be an easy fix either, as all inputs from various sub-views would have to be collected differently.

**Comment by fisharebest** [comment]
Thanks for investigating this.  I was looking for a logic error in the form.

I guess we can detect this condition, and give a more helpful error message.

**Comment by fisharebest** [comment]
> This is reproducible by e.g. adding a large number of source citations 

I am trying to reproduce this.  I create a form with more than 1000 fields (lots of citations fields).

If `display_startup_errors` is set to `On`, then I see the message:
"PHP Warning: Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini."

If `display_startup_errors` is set to `Off`, then I see that both `$_GET` and `$_POST` are empty.
The documentation says they should be truncated after the 1000th variable.

I was hoping to add this to `Validator::_construct()`:

```
        $count_get           = count($request->getQueryParams());
        $count_post          = count((array)$request->getParsedBody());
        $count_cookie        = count($request->getCookieParams());
        $max_input_variables = (int) ini_get('max_input_vars');

        if ($count_get + $count_post + $count_cookie >= $max_input_variables) {
            throw new HttpBadRequestException(I18N::translate('Too many parameters.  Increase the PHP setting: max_input_variables.'));
        }
```

**Comment by fisharebest** [comment]
Another solution might be to move the CSRF token to the end of the form.

If this is missing (and we assume all webtrees forms contain one), then it becomes likely the the input was truncated.

This would also catch another error case (not sure if there is an issue for it), where the POST body is truncated by NGINX, and some fields are then missing.
