### ISSUE TITLE
Relationship to ASSO

### ISSUE THREAD

**Issue by HRN-webtrees** [fisharebest/webtrees#439]
When adding an ASSO to an event like baptism, there will be links to both individual and to relationship.
However, when visiting the ASSO's INDI page, the relationship link will show the initial individual's relationship to self.

**Comment by fisharebest** [comment]
Can you give a specific example of this?

**Comment by HRN-webtrees** [comment]
See Christening
http://www.visitusinmaputo.com/webtree/individual.php?pid=I85
Go to Godmother's INDI page and scroll down....

**Comment by fisharebest** [comment]
> Should this event be displayed on the ASSO's INDI page at all?

It is a genealogy event, where an individual was present.

Why wouldn't you include it?

**Comment by HRN-webtrees** [comment]
I like the idea of displaying the events on the ASSO's INDI page, but shouldn't we then include all ASSOs?
If you take a look at the example given above, the event is not displayed on the Godfather's INDI page (maybe because of too distant relationship?)

Originally using 1 ASSO only, I guess I'm a bit confused regarding the display of 2 ASSO
