### ISSUE TITLE
Notes and Shared Notes in Research tasks

### ISSUE THREAD

**Issue by Manja-S** [fisharebest/webtrees#4391]
Up until now, I organised my research tasks in [the record of a person](https://www.schledorn.nl/webtrees/tree/Schledorn/individual/I31/Marie-van-der-Heiden) by 
- adding a fixed set of Shared notes for every individual to one instance of Research tasks (to keep track of a fixed set of information I'd like to find for everybody) and 
- adding Notes to another instance of Research tasks (to keep track of other things that I want or need to research later)

After my upgrade to version 2.1.2 the GEDCOM code of my Research tasks hasn't changed, but the output on screen has:

(part of) fixed set of **Shared notes:**
1 _TODO [I] Algemene onderzoekstaken
2 DATE 01 FEB 2021
2 _WT_USER maschle
2 NOTE @N405@
2 NOTE @N406@
2 NOTE @N411@
2 NOTE @N52@
2 NOTE @N409@

Output on screen in previous versions
** Opzoeken: (scan van) geboorte-akte - Search for: (scan of) birth certificate
** Opzoeken: bronvermelding geboorte - Search for: source for birth
** Uitzoeken: doop - Research: baptism
** Uitzoeken: ouders - Research: parents
**** Opzoeken: (scan van) overlijdensakte - Search for: (scan of) death certificate

Output in version 2.1.2:
**The problem:**
** Opzoeken: (scan van) geboorte-akte - Search for: (scan of) birth certificate

**The problem:**
** Opzoeken: bronvermelding geboorte - Search for: source for birth

**The problem:**
** Uitzoeken: doop - Research: baptism

**The problem:**
** Uitzoeken: ouders - Research: parents

**The problem:**
**** Opzoeken: (scan van) overlijdensakte - Search for: (scan of) death certificate

So, my old, compact list has expanded into something space consuming and full of redundancy (every instance of **The problem:** )
When I want to edit this list, I can no longer see the descriptions of the shared notes (** Opzoeken: (scan van) geboorte-akte - Search for: (scan of) birth certificate), I only get to see the code (@N405@). I can't add a shared note in the edit-window either, I have to edit the raw GEDCOM to do so.

I've got the same kind of problem with the **Notes**

Here the GEDCOM code hasn't changed either:

(part of)  **Notes:**
1 _TODO [I] Specifieke onderzoekstaken
2 DATE 12 FEB 2013
2 _WT_USER maschle
2 NOTE North Dakota Obituary and Death Notice Archive - Page 189: http://www.genlookups.com/nd/webbbs_config.pl/noframes/read/189
3 CONT
3 CONT Marie Schledorn
3 CONT
3 CONT EDMORE, N.D. -- Marie Schledorn, 94, Edmore, died Saturday, Dec. 5, 1998, in Lakota (N.D.) Good Samaritan Center.
3 CONT
3 CONT Marie Vander-Heiden was born Jan. 20, 1904, the daughter of Albert and Sarah (Van Dyke) Vander-Heiden, in Pella, Iowa. She moved with her family to Edmore, where she attended school. She married Frank Schledorn on Nov. 12, 1921, in Devils Lake. They farmed in Lawton, N.D., and Edmore until retiring in 1971. Frank Schledorn died Sept. 22, 1976. She continued to live in Edmore until moving to Devils Lake. She became a resident of Lakota Good Samaritan in January 1998.
2 NOTE Irene van der Heiden (zus van Marie)
3 CONT
3 CONT https://familysearch.org/ark:/61903/1:1:MC8D-4K2
3 CONT
3 CONT Later Irene Collins: https://familysearch.org/ark:/61903/1:1:QV5W-PV71
3 CONT
3 CONT De Geneanet-gegevens van 'Hammelvater': http://gw.geneanet.org/hammelvater?lang=nl&m=N&v=Schledorn&t=A
3 CONT
3 CONT https://www.ussearch.com/search/people/~/~/schledorn/~/~/~/1

But the output on screen has: 
Notes are set to collapse in my configuration, so I had a nice, compact list of collapsed notes (with the visible line indicating the subject) where I could expand the note I had chosen to work on. Now, with version 2.1.2 I've got a whole lot of text, interspersed with **The problem:** I've got to scroll through.  I can't add a note in the edit-window either, I have to edit the raw GEDCOM to do so.

I do realise that my way of using Research tasks may seem a bit eccentric, but it used to work very well for me. So I hope the output and edit screen can be fixed to reflect the actual GEDCOM code again.

**Comment by fisharebest** [comment]
I have read this several times, and still do not understand the issue.

Are you saying that the label "Note:" has changed to "The problem"?

This was taken from another application that used `INDI:_TODO:NOTE` in this way.

I am happy to change it back - if this is what you are asking.

**Comment by Manja-S** [comment]
Hi Greg,

The label "Note:" has indeed changed to "The problem", which is apparently now followed by a line break instead of a space. This means the layout is less compact. I preferred the compact layout, but I won't die if it is abandoned.

However, that's not the only thing that has changed. The behaviour in the edit-screen has changed as well. 
- It's no longer possible to add a Note or a Shared Note to an existing Research task. 
- Existing Shared Notes are shown in the edit-screen as a common note field, containing the code for the shared note, and not as a shared note field containing the description of the note.

It seems that the option to control whether or not to automatically display content of a Note record on the Individual page is broken as well. My setting for 'Automatically expand notes' in https://www.schledorn.nl/webtrees/tree/Schledorn/preferences is 'NO'.

I created a (temporary) [Jane Doe](https://www.schledorn.nl/webtrees/tree/Schledorn/individual/I1442/Jane-Doe) in my tree to show my problems, I hope that will clarify things a bit. Please let me know if things still aren't clear.

**Comment by fisharebest** [comment]
Please - only 1 issue at a time.  It is difficult to manage issues that contain many different things.

For example, they are closed automatically when I submit a code change that references it.

The issue with single-line notes showing as block-text is already known.
