### ISSUE TITLE
2.1.2 FAM:SOUR Records Displayed as Individual Events??

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#4392]
After upgrading from 2.0.16 to 2.1.2, I observed FAM:SOUR entries displayed in too many places!

Family page - GOOD
Individual sources tab - GOOD
Individual facts and events tab - BAD - Why is it showing up in two tabs at the same time?  🤔

p.s. This is also happening with FAM:RIN but not with FAM:_UID so it looks like there is more than one item affected.

**Comment by FrankWarius** [comment]
it's fixed in Dev
#4381
