### ISSUE TITLE
2.1.2 Shared Note Titles Showing First 3 Lines Concatenated

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#4393]
After upgrading from 2.0.16 to 2.1.2, I observed shared note titles are displayed differently.

If my note begins with:

1

2
3
4

Then the title should be "1" but now is displayed as "1 2"

**Comment by ddrury** [comment]
@miqrogroove I agree with you. I think you mentioned this in an earlier issue, the problem now is the extra line break after the first line - remove that and the problem is solved (I'm not suggesting this as the "fix" just pointing out the cause) - over to @fisharebest

**Comment by fisharebest** [comment]
We need to apply markdown (which creates HTML), and then extract the first line from the HTML.

We do this by stripping tags (except `<br>`), and taking everything before the first `<br>`.

The HTML is

```
div class="markdown" dir="auto"><p>1</p>
<p>2<br />3<br />4</p>
</div>
```

I guess we also need to convert `</p><p>` to `<br>` before doing this.
