### ISSUE TITLE
The labels "Note" and "Shared Note" have been changed to "The problem" in Research tasks

### ISSUE THREAD

**Issue by Manja-S** [fisharebest/webtrees#4398]
The labels "Note" and "Shared Note" have been changed to "The problem" in Research tasks. This doesn't reflect the labels in the raw GEDCOM. To me this change is more confusing than clarifying, I'd like to have it reversed.

(first mentioned in #4391)

**Comment by fisharebest** [comment]
This was already fixed in 0ef2a2ca22f80f065ac958080787dbb225517026
