### ISSUE TITLE
First line of note: problematic cutoff

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4402]
Apparently the first line of a non-expanded note cuts off at a fixed position, sometimes in the middle of a html entity such as '\&quot;'.

Reproducible on the demo server: Add the following note to a fact

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.
"A quote"
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.
```

First line is displayed as 

```
Note: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.
&quo…
```

In general, the whole area of note formatting remains a mess unfortunately. Overall it feels like a regression, we had a better solution in earlier versions (do not repeat the first line if possible etc). Are there any improvements planned at all? Otherwise I'll handle this in Vesta.

**Comment by ro-la** [comment]
In 2.1.2 the "first line" is displaying not only the first line - it display the first x characters of the whole note. This should be changed so it displays only first x characters from the first line.

![obrázok_2022-05-13_123001744](https://user-images.githubusercontent.com/60657963/168265602-4dd1cc6c-5991-494a-9196-fa394e944e8b.png)

**Comment by fisharebest** [comment]
> Are there any improvements planned at all?

Yes.  The system was rewritten to use a new Markdown library - the old one doesn't support newer versions of PHP (and vice-versa).

The old code used CSS for formatting, which relied on implementation details of the markdown library.

The new code uses HTML formatting, which should be more predictable / deterministic.

We now have test scripts for this.  So, as bugs are reported/fixed, there should be no regressions.

**Comment by ddrury** [comment]
Greg,
As far as I can ascertain the following code in Note::extractNames solves the problems above and I can't make it fail elsewhere, however people here may find differently

```
    public function extractNames(): void
    {
        $html = Registry::markdownFactory()->autolink($this->getNote());

        // Take the first line
        [$html] = explode(MarkdownFactory::BREAK, html_entity_decode(strip_tags(trim($html), ['br'])));

        if ($html !== '') {
            $html = htmlspecialchars_decode($html, ENT_QUOTES);
            $this->addName('NOTE', Str::limit($html, 100, I18N::translate('…')), $this->gedcom());
        }
    }
```
