### ISSUE TITLE
User's login ID displayed on her INDI page.

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#4403]
Only close relatives can see it, but sometimes close relatives don't get along.  And sometimes (often) people create easy-to-guess passwords.  In this case, the user had put her e-mail address in as user name.

I would prefer that not be displayed anywhere except in the user administration panel..

At the top of her INDI page was

   Given I. Surname, birth year — (age ## years) —
            username@domain.tld

When I changed the user ID to GSurname, that appeared instead of the e-mail.  I looked at the code for Individual.php and didn't see a fix.

**Comment by fisharebest** [comment]
The link is to an admin page, so we should only show it to admins (who already know everyone's email address).

**Comment by WGroleau** [comment]
Oh, that makes sense.  I'd still prefer it not on the INDI page, but maybe other admins feel different?  If so, perhaps as an option?

**Comment by fisharebest** [comment]
> but maybe other admins feel different?

The feature was requested by several users - so I guess so.

This is easy to customise.  It is a simple template - https://github.com/fisharebest/webtrees/blob/main/resources/views/individual-page-title.phtml - and there is an example module showing how to provide custom versions of templates.
