### ISSUE TITLE
Validator::integer does not accept string-typed negative integers

### ISSUE THREAD

**Issue by jon48** [fisharebest/webtrees#4408]
As I was introducing Validators in my custom module, I introduced a "regression" due to the method Validator::integer not accepting negative integers as string (as they usually are interpreted in POST body).

This is because ctype_digit does not recognise a string representing a negative integer as an integer (the character `-` not being an integer).  
https://github.com/fisharebest/webtrees/blob/b9a9ffe24ec25ddfa5b1788a9c1b82b5c37a22c5/app/Validator.php#L279

I was wondering whether this was the intended design (so accept only positive integer), or a bug.
In my opinion, negative integers are integers, and because the Validator would accept an int-type negative integer, I feel that the same way we should accept string-type negative integer, as the amended test below.

```php
public function testRequiredIntegerParameter(): void
{
    $request    = $this->createStub(ServerRequestInterface::class);
    $parameters = [
        'int_type_positive' => 42,
        'int_type_negative' => -42,
        'string_type_positive' => '42',
        'string_type_negative' => '-42',
        'invalid' => 'not_int'
    ];
    $validator  = new Validator($parameters, $request);

    self::assertSame(42, $validator->integer('int_type_positive')); // PASS
    self::assertSame(-42, $validator->integer('int_type_negative')); // PASS
    self::assertSame(42, $validator->integer('string_type_positive')); // PASS
    self::assertSame(-42, $validator->integer('string_type_negative')); // FAIL - raise an exception 'The parameter “string_type_negative” is missing'

    $this->expectException(HttpBadRequestException::class);
    $validator->integer('invalid');
}
```
If this is considered a bug, we cannot use `is_numeric` either, as it would accept both positive and negative integer, but float as well.
I would suggest replacing L.279-283 by the following, but maybe you have some some reservations about the filter functions.
```php
 $value = filter_var($value, FILTER_VALIDATE_INT);
if($value === false) {
    $value = null;
}
```

**Comment by fisharebest** [comment]
> I was wondering whether this was the intended design (so accept only positive integer), or a bug.

Perhaps just an oversight.  I don't think anything in the core code uses negative parameters...
