### ISSUE TITLE
Style Missing on Create Shared Note Restriction Selector

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#4412]
The "Create a shared note" dialog is missing some of the new styling for v2.1.  PR coming shortly.

**Comment by miqrogroove** [comment]
See #4413

**Comment by fisharebest** [comment]
TIP:  include "Fixes #nnn" in the title of the PR.  It will link the two items, and will automatically close the issue when the PR is merged.  See https://docs.github.com/en/enterprise-server@3.5/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by miqrogroove** [comment]
Yah.  I forgot.  Also wouldn't it be easier to just CSS all the select elements instead of renaming them?
