### ISSUE TITLE
A query re note formatting (sorry!)

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4415]
Following commits  https://github.com/fisharebest/webtrees/commit/63a2c22b53010174339c850ccde339d45092dcf2 & https://github.com/fisharebest/webtrees/commit/2de327da270463ab61ba59007eb29d982f430db0, why is the handling of long single paragraph inline notes treated differently. i.e. not split into first line followed by all text in a drop down panel?

**Comment by fisharebest** [comment]
Single-line inline notes are shown inline, with no toggle.

Multi-line inline notes toggle between first-line (with `overflow:hidden` using CSS) / all lines.

Trying to toggle a single-line note means that we need to know if it fits on screen.
This is hard to do, and choosing a fixed number of characters (e.g. 100) doesn't look good on wide-screens, or when you have multiple notes as they all use slightly different numbers of pixels.
