### ISSUE TITLE
Problematic regex in Fact::attribute()

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4417]
The method attribute() in Fact.php is called in various places, e.g. with argument 'PLAC'.

[Due to the optional space in the regex after the tag name (' ?')](https://github.com/fisharebest/webtrees/blob/aab1cd2de4c0191332a694d2472838afe1e7a050/app/Fact.php#L267), this matches any tag starting with PLAC. If a GEDCOM file has a custom tag PLACXYZ, this is parsed as a place.

Example (tested on the demo server via edit raw GEDCOM):

`2 PLACXYZ Mayfair, London, England`
results in a Place "XYZ Mayfair, London, England", but at the same time a warning wrt an unrecognized tag 'INDI:BIRT:PLACXYZ'.

Possible solutions? Either change the regex (was there a specific reason for the ' ?') or call the method with 'PLAC ' etc?

**Comment by fisharebest** [comment]
IIRC, ` ?` is there to match these cases

```
2 ADDR some text
3 CONT with two lines
```
```
2 ADDR
3 CONT some text starting with a blank line
```
