### ISSUE TITLE
hard coded background in relationship.php

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#443]
In relationships.php there now is a hard coded (inline style) white background behind the relationship name. I hope you can reconsider this because this white background is very ugly on a dark background like in the JustBlack theme.

I don't see an easy way to overwrite the background in the theme css because this area doesn't have an id or a class.

![19-2-2015 16-44-17](https://cloud.githubusercontent.com/assets/5641963/6269932/c9629a9e-b856-11e4-87f4-3d9245021ce7.jpg)

**Comment by fisharebest** [comment]
The markup for this page is still being developed.

When it is finished, it will get moved to the theme.

**Comment by JustCarmen** [comment]
Oh thats great. Thanks.
