### ISSUE TITLE
2.1.4 FAM:SOUR Records Displayed as Individual Events

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#4430]
The fix for #4392 must have failed because I still get family source records on the individual events tab.  They are showing up in duplicate being on the events tab and sources tab at the same time.

Edit: Also seeing FAM:NOTE on individual events tab rather than the notes tab where they belong.

**Comment by FrankWarius** [comment]
I can't confirm that in my 2.1.4 installation.
https://wbt.warius.info/tree/Warius/individual/I3034/Henriette-Warias
do you have examples

**Comment by mpwt** [comment]
Not only sources, but also notes (1 NOTE) for families are displayed on the person page.

**Comment by miqrogroove** [comment]
I was going to mention that too but then I couldn't remember uf notes are supposed to be on the notes tab.  The current behavior foes seem abnormal.

**Comment by mpwt** [comment]
I seem to remember that the sources and notes in the family tab were then displayed on the individual tab when the sources and notes tabs were hidden. Now they are displayed even though the tabs are active.

**Comment by mpwt** [comment]
With the current changes, FAM:CHAN is now displayed in the Facts and Events tab.

**Comment by miqrogroove** [comment]
I noticed that too but it didn't bother me.  Maybe it needs to be a new issue.

**Comment by fisharebest** [comment]
>  Maybe it needs to be a new issue.

Please create one.
