### ISSUE TITLE
open the error checker for DATE:TIME

### ISSUE THREAD

**Issue by Bogiegit** [fisharebest/webtrees#4433]
With GEDCOM 5.5.1 rigid checks got into the game which will be softend again in furture GEDCOM 7.0.
Hence could you enable the following time tags and thereby reduce the number of errors.
INDI:BIRT:DATE:TIME
INDI:DEAT:DATE:TIME
FAM:MARR:DATE:TIME
Thanks

**Comment by fisharebest** [comment]
There is now the option to dismiss these errors with a one click.
