### ISSUE TITLE
FAQ on statistics page not correct any longer

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#4438]
At https://dev.webtrees.net/statistics.html the FAQ part has to be rewritten. For example "Now, by looking at the build-server access logs, we can count the number of unique IP addresses that have requested this file." and all the following FAQ topics.

This is not a webtrees issue, but I did not find the correct issue list.

**Comment by fisharebest** [comment]
I updated the script.  It will run again tomorrow morning.
