### ISSUE TITLE
New custom GEDCOM-L tag _LOC:EVEN:PLAC:_LOC

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#4454]
In the _LOC record, there is a possibility to add events for that location (for example a "location founding" event). These events can happen at a place (as it is for all events). After some discussion in the GEDCOM-L group, we agreed that if there is no PLAC in an event the semantic is that it is assumed that the event happened at the location of that place itself. But in general, it would be possible to add events at another location (for example a town twinning founding event). Now it should be possible to add a _LOC to that PLAC as it is used in INDI:PLAC or FAM:PLAC.

So my request is to add a line at https://github.com/fisharebest/webtrees/blob/81aa9d168e84a93cdd1208f7500841e1a664caaa/app/Gedcom.php#L1103

`_LOC:EVEN:PLAC:_LOC => new XrefLocation(I18N::translate('Location')),`

**Comment by fisharebest** [comment]
> After some discussion in the GEDCOM-L group, we agreed

Is this discussion available online?  If so, can you post a link to it here.

**Comment by hartenthaler** [comment]
No it is not online, as far as I know. Here my initial post and the most important answer.
`Message: 2
Date: Wed, 4 May 2022 13:14:26 +0200 (CEST)
From: Hermann Hartenthaler <[hermann@hartenthaler.de](mailto:hermann@hartenthaler.de)>
Subject: [Gedcom-L] EVEN in einem Ortsdatensatz (_LOC.EVEN.PLAC._LOC)
To: [gedcom-l@genealogy.net](mailto:gedcom-l@genealogy.net)



Ich habe noch eine andere Frage:

Die Definition eines Ortsdatensatzes nach GEDCOM-L-Addendum sieht als ein Element ein Ereignis (EVEN) vor:
0 @<XREF:_LOC>@ _LOC {1:1}
1 NAME <PLACE_NAME> {1:M}
2 DATE <DATE_VALUE> {0:1}
...
1 EVEN [<EVENT_DESCRIPTOR>|<NULL>] {0:M}
2 <<EVENT_DETAIL>> {0:1}
...

In den Details zum Ereignis kommt dann wieder PLAC und sicherlich auch wieder ein zugehöriger Verweis mit _LOC vor.

Das nutze ich in einem Ortsdatensatz @X168@ zur Stadt Freiburg etwa so:

(1) Mit einem erneutem Verweis auf den eigenen Datensatz:
1 EVEN
2 TYPE Stadtgründung
2 DATE 1120
2 PLAC Freiburg
3 _LOC @X168@

(2) Ohne erneuten Ortsverweis in der Annahme, dass es klar ist, wenn man nicht auf einen Ort verweist, dass dann der Ort gemeint ist, in dem sich das EVEN befindet:
1 EVEN
2 TYPE Stadtgründung
2 DATE 1120

(3) Bei einem anderen Ereignistyp vollständig ausgeführt:
1 EVEN
2 TYPE Städtepartnerschaft
2 DATE 06 JUN 1959
2 PLAC Besançon, Frankreich
3 _GOV BESNONJN37AF
3 _LOC @L50@

webtrees unterstützt alle drei Varianten. Neu ist in einem Vesta-Erweiterungsmodul von webtrees eine Funktion, die zu einem Ort die gesamte Historie als Auflistung präsentiert, also wann hat sich in der GOV-Hierarchie des Ortes etwas geändert, wann hat jemand dort gewohnt oder dort einen Beruf ausgeübt, etc. Nun kam es zu Fragen, ob und wie die oben beschriebenen Ereignisse, die im Ortsdatensatz selbst definiert werden, angezeigt werden sollen. Etwa ob bei der Historie des Ortes Besançon das Ereignis "Städtepartnerschaft" aus dem Eintrag beim Ortsdatensatz zu Freiburg zitiert werden soll.

Meine konkreten Fragen:
- Ist es im GEDCOM-L-Addendum gewollt, dass es für Ortsdatensätze _LOC eine Struktur wie _LOC.EVEN.PLAC._LOC gibt?

- Würdet ihr bei einem fehlenden _LOC.EVEN.PLAC und einem fehlenden _LOC.EVEN.PLAC._LOC das auch so interpretieren, dass sich das Ereignis an dem Ort des Ortsdatensatzes abgespielt hat oder würdet ihr eine fehlende Angabe zu PLAC so interpretieren, dass der Ort des Ereignisses unbekannt ist?

- Würdet ihr die obigen Beispiele genau so importieren und wieder exportieren und so interpretieren, wie ich es tue?

Viele Grüße 
Hermann

PS: was ich bei den Festlegungen zu _LOC vermisse, sind die folgenden Möglichkeiten für Angaben im Ortsdatensatz:
- Angabe einer Adresse (sinnvoll, wenn es sich bei dem Ort etwa um einen Bauernhof oder ein Schloss handelt); auf die derzeit mögliche Angabe von _POST könnte man dann verzichten.
- Angabe von mit dem Ort verbundenen Personen (ASSO), etwa um eine Liste der Bürgermeister des Ortes oder der Pfarrer einer Kirchengemeinde zu erstellen.`

`Message: 3
Date: Fri, 6 May 2022 02:04:10 +0200
