### ISSUE TITLE
Delete fact confirmation dialog formatting

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4456]
... should be improved: The parents' ages shouldn't be included, anyway not with linebreaks. See screenshot from demo server.

<img width="612" alt="delete" src="https://user-images.githubusercontent.com/18174787/171722832-6d1e22bb-534b-46c4-b02c-d8dd3eac9011.PNG">

**Comment by FrankWarius** [comment]
Duplicate to #4282

**Comment by ric2016** [comment]
Sorry, didn't check that far down in the issues list - This should be easy to fix though?
