### ISSUE TITLE
conversion error for multimedia link

### ISSUE THREAD

**Issue by arbor95** [fisharebest/webtrees#4457]
see https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/36973-gedcom-tags the last posts from Herman:
What you have in your source GEDCOM file is a MULTIMEDIA_LINK. GEDCOM standard 5.5.1 says about that
n OBJE
+1 FILE <MULTIMEDIA_FILE_REFN> {1:M}
+2 FORM <MULTIMEDIA_FORMAT> {1:1}
+3 MEDI <SOURCE_MEDIA_TYPE> {0:1} 
+1 TITL <DESCRIPTIVE_TITLE> {0:1}
So your input is ok.

To convert such Multimedia-Links to Media-Objects (MULTIMEDIA_RECORD) during import by webtrees is ok for me.
GEDCOM 5.5.1 says about Media-Objects:
MULTIMEDIA_RECORD:=
n @XREF:OBJE@ OBJE {1:1}
+1 FILE <MULTIMEDIA_FILE_REFN> {1:M}
+2 FORM <MULTIMEDIA_FORMAT> {1:1}
+3 TYPE <SOURCE_MEDIA_TYPE> {0:1}
+2 TITL <DESCRIPTIVE_TITLE> {0:1}
...

So the result should be
0 @XobjectNumber@ OBJE
1 FILE path+name.jpg
2 FORM JPG
2 TITL
as you have said. I have not used the import of multimedia links for a long time. Are you sure that webtrees converted this to "3 TITL"?

No: If I'm using your example with empty "2 TITL", then webtrees deletes this empty TITL during the import and the resulting GEDCOM is correct.
Yes: If there is for example "2 TITL xxx", the result is a media object record with "3 TITL xxx". This is a bug. Raise an issue, please.

Done

**Comment by fisharebest** [comment]
Fixed in 8a45bdde3e585c8cd758249b4a548b89089a19ab
