### ISSUE TITLE
beta - media scrolls past person 

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#4458]
My site: https://skatekey.net/tree/peters/individual/I0282/Norris-Kent-Dalton#tab-relatives

click on the picture of Norris
bottom left arrows - second click of next shows obituary of Arthur Peters obituary
The issues is that only two pictures should be visible not three.

**Comment by fisharebest** [comment]
The "colorbox" plugin displays all images found in the page.

The same image is shown several times - so it is shown several times.

Colorbox is abandonded.  We should find a replacement.

**Comment by makitso** [comment]
Arthur L Peters is the maternal grandfather of Norris.  To me it is strange that the source for the page has more data than is displayed to the viewer.  And, displaying the obituary for the maternal grandfather is, in my opinion, confusing to the person viewing the media for Norris.

**Comment by fisharebest** [comment]
Perhaps I misunderstand what you mean by "scrolls past".

**Comment by makitso** [comment]
Select the picture, it opens in a color box window.  Do next, next, next an it shows a picture of the obituary of Donald l Peters

**Comment by fisharebest** [comment]
If you select the "Events of close relatives", and look at "Death of a maternal grandmother", you'll see the obituary there.
