### ISSUE TITLE
Fact Editor Doesn't Provide FAM:*:SOUR:NOTE

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#4464]
When adding or editing a Census or a Death in 2.1.4 it is easy to add an inline or shared note under a new Source citation.  However, the same screen for other things such as Marriage or Family Residence will not show any Note option for a new Source.  Is this configurable, or hard-coded?

I have full citations enabled.

**Comment by miqrogroove** [comment]
It appears to be disabled on the demo server.  None of the citations show a note field.

**Comment by fisharebest** [comment]
Sorry, I misread this as SOUR, NOTE, not SOUR:NOTE.  (Some forms *were* missing SOUR and NOTE).

Control panel -> GEDCOM tags -> Source citations -> Note -> hide/show

**Comment by miqrogroove** [comment]
Do I need to unhide SOUR:DATA:NOTE to fix this?

**Comment by fisharebest** [comment]
Please clarify where you are trying to add a note.

To a source citation? (:SOUR:NOTE)
To a source record? (SOUR:NOTE)
To the data of a source record? (SOUR:DATA:NOTE)

**Comment by miqrogroove** [comment]
I believe it's the :SOUR:NOTE when adding or editing FAM events.  I can double check if it's missing in any INDI items but seems to be family related.

**Comment by miqrogroove** [comment]
Confirmed, this bug doesn't affect INDI:* but the problem is found with all FAM:*:SOUR:NOTE
