### ISSUE TITLE
Datatables broken in latest version for some regions

### ISSUE THREAD

**Issue by vitorsemeano** [fisharebest/webtrees#4469]
Hi,

I am using the latest version, 2.1.5, and anything related with the datatables component is broken. Further investigation on the console panel, indicates a problem with datatables and locales.

A fix already exists in the version 1.12.1 of datatables (source: https://datatables.net/forums/discussion/72749/error-initialization-datatable). 

Supposedly the dependency that this project uses, datatables.net-bs5, already is in the latest version, but in package-lock, datatables is still in version 1.12.0.

This needs to be upgraded to version 1.12.1 (at least) for this problem to be fixed in some regions.

**Comment by fisharebest** [comment]
> but in package-lock, datatables is still in version 1.12.0.

Are you sure?

https://github.com/fisharebest/webtrees/blob/2.1.5/package-lock.json#L15

> for some regions

It would be helpful if you said which region(s) was not working?

**Comment by vitorsemeano** [comment]
> > but in package-lock, datatables is still in version 1.12.0.
> 
> Are you sure?

Yes, datatables.net-bs5  is in the latest version, but this brings the dependency of datatables.net, and that version is 1.12.0. It should be in version 1.12.1 (the one that contains the fix).

https://github.com/fisharebest/webtrees/blob/535e8ffe43368f8e13f52893c2b4369c75eabcd9/package-lock.json#L15309

> > for some regions
> 
> It would be helpful if you said which region(s) was not working?

For my region is not working (Portugal). Any location referred in the link previously provided should not work also.

Try making a fresh npm install, and should bring the latest datatables.net version, or update that version manually in package-lock.
