### ISSUE TITLE
2.1.5 Security Issue on Place Admin

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4471]
from Website logs; 2022-06-10 01:59:44 | error | 138.201.11.237 | none | none

no no more Website logs entries for 138.201.11.237 but IIS log entries. No user was logiged n at this time

how could this happen?

IIS Log Error
2022-06-09 23:59:44 85.214.164.127 GET /index.php - 443 - 138.201.11.237 Mozilla/5.0+(X11;+Linux+x86_64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/87.0.4280.67+Safari/537.36 - 500 0 0 2815

Website logs error:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;23643-2-Ahrensbök&#039; for key &#039;ux1&#039; (SQL: insert into `wt2_places` (`p_file`, `p_place`, `p_parent_id`, `p_std_soundex`, `p_dm_soundex`) values (2, Ahrensbök, 23643, A652, 059647:096475)) …\vendor\illuminate\database\Connection.php:712 #0 …\vendor\illuminate\database\Connection.php(672): Illuminate\Database\Connection-&gt;runQueryCallback(&#039;insert into `wt...&#039;, Array, Object(Closure)) #1 …\vendor\illuminate\database\Connection.php(502): Illuminate\Database\Connection-&gt;run(&#039;insert into `wt...&#039;, Array, Object(Closure)) #2 …\vendor\illuminate\database\Connection.php(454): Illuminate\Database\Connection-&gt;statement(&#039;insert into `wt...&#039;, Array) #3 …\vendor\illuminate\database\Query\Builder.php(2980): Illuminate\Database\Connection-&gt;insert(&#039;insert into `wt...&#039;, Array) #4 …\app\Place.php(141): Illuminate\Database\Query\Builder-&gt;insert(Array) #5 …\app\Cache.php(60): Fisharebest\Webtrees\Place-&gt;Fisharebest\Webtrees\{closure}() #6 …\vendor\symfony\cache\Adapter\ArrayAdapter.php(84): Fisharebest\Webtrees\Cache::Fisharebest\Webtrees\{closure}(Object(Symfony\Component\Cache\CacheItem), true) #7 …\app\Cache.php(61): Symfony\Component\Cache\Adapter\ArrayAdapter-&gt;get(&#039;07582e21abab4d6...&#039;, Object(Closure)) #8 …\app\Place.php(148): Fisharebest\Webtrees\Cache-&gt;remember(&#039;place-Ahrensb\xC3\xB6...&#039;, Object(Closure)) #9 …\app\Place.php(223): Fisharebest\Webtrees\Place-&gt;id() #10 …\app\Place.php(300): Fisharebest\Webtrees\Place-&gt;url() #11 …\resources\views\lists\individuals-table.phtml(328): Fisharebest\Webtrees\Place-&gt;shortName(true) #12 …\app\View.php(183): include(&#039;D:\\Web\\WT21 Pro...&#039;) #13 …\app\View.php(278): Fisharebest\Webtrees\View-&gt;render() #14 …\app\Helpers\functions.php(145): Fisharebest\Webtrees\View::make(&#039;lists/individua...&#039;, Array) #15 …\resources\views\record-page-links.phtml(117): view(&#039;lists/individua...&#039;, Array) #16 …\app\View.php(183): include(&#039;D:\\Web\\WT21 Pro...&#039;) #17 …\app\View.php(278): Fisharebest\Webtrees\View-&gt;render() #18 …\app\Helpers\functions.php(145): Fisharebest\Webtrees\View::make(&#039;record-page-lin...&#039;, Array) #19 …\resources\views\record-page.phtml(55): view(&#039;record-page-lin...&#039;, Array) #20 …\app\View.php(183): include(&#039;D:\\Web\\WT21 Pro...&#039;) #21 …\app\View.php(278): Fisharebest\Webtrees\View-&gt;render() #22 …\app\Helpers\functions.php(145): Fisharebest\Webtrees\View::make(&#039;record-page&#039;, Array) #23 …\app\Http\ViewResponseTrait.php(50): view(&#039;record-page&#039;, Array) #24 …\app\Http\RequestHandlers\SourcePage.php(90): Fisharebest\Webtrees\Http\RequestHandlers\SourcePage-&gt;viewResponse(&#039;record-page&#039;, Array) #25 …\app\Http\Middleware\RequestHandler.php(54): Fisharebest\Webtrees\Http\RequestHandlers\SourcePage-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #26 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #27 …\app\Module\HitCountFooterModule.php(154): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #28 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #29 …\app\Module\CheckForNewVersion.php(115): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #30 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #31 …\app\Http\Middleware\CheckCsrf.php(80): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #32 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #33 …\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #34 …\app\Webtrees.php(275): Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest)) #35 …\app\Http\Middleware\Router.php(153): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array) #36 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #37 …\app\Http\Middleware\BootModules.php(60): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #38 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #39 …\app\Http\Middleware\RegisterGedcomTags.php(54): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #40 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #41 …\app\Http\Middleware\LoadRoutes.php(75): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #42 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #43 …\app\Http\Middleware\CheckForNewVersion.php(65): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #44 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #45 …\app\Http\Middleware\UseTransaction.php(45): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #46 …\vendor\illuminate\database\Concerns\ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection)) #47 …\app\Http\Middleware\UseTransaction.php(46): Illuminate\Database\Connection-&gt;transaction(Object(Closure), 3) #48 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #49 …\app\Http\Middleware\DoHousekeeping.php(73): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #50 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #51 …\app\Http\Middleware\UseTheme.php(69): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #52 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #53 …\app\Http\Middleware\CheckForMaintenanceMode.php(51): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #54 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #55 …\app\Http\Middleware\UseLanguage.php(71): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #56 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #57 …\app\Http\Middleware\UseSession.php(78): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #58 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #59 …\app\Http\Middleware\UpdateDatabaseSchema.php(57): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #60 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #61 …\app\Http\Middleware\UseDatabase.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #62 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #63 …\app\Http\Middleware\BadBotBlocker.php(233): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #64 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #65 …\app\Http\Middleware\CompressResponse.php(73): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #66 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #67 …\app\Http\Middleware\ContentLength.php(40): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #68 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #69 …\vendor\middlewares\client-ip\src\ClientIp.php(65): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #70 …\app\Http\Middleware\ClientIp.php(47): Middlewares\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #71 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #72 …\app\Http\Middleware\HandleExceptions.php(90): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #73 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #74 …\app\Http\Middleware\BaseUrl.php(79): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #75 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #76 …\app\Http\Middleware\ReadConfigIni.php(68): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #77 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #78 …\app\Http\Middleware\SecurityHeaders.php(48): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #79 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #80 …\app\Http\Middleware\EmitResponse.php(57): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #81 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #82 …\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #83 …\app\Webtrees.php(275): Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest)) #84 …\app\Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array) #85 …\index.php(51): Fisharebest\Webtrees\Webtrees-&gt;httpRequest() #86 {main}

**Comment by FrankWarius** [comment]
the database itself seems to be ok:
![grafik](https://user-images.githubusercontent.com/16499744/173154542-42d6cd56-8539-43e4-9cb7-bb10d8b7ae2f.png)

**Comment by fisharebest** [comment]
Does your data contain both `Ahrensbök` and `Ahrensbok`?

**Comment by FrankWarius** [comment]
no. See the above screenshot of the DB

**Comment by FrankWarius** [comment]
As you can see, both places have the same Soundex value. Ahrenshoop is in Western Pomerania, Ahrensbök in Schleswig-Holstein.
I think we had problems with umlauts / code pages about 5 years ago. Some 1.x stuff we solved.

Why I'm afraid it's a security issue:

- Place entries in _places are created when an INDI or FAM tag is created or edited. You need update rights for this.
- Place entries are changed or deleted using the Admin\Place function. You need admin rights for this
- The session from the IP address 138.201.11.237 was not logged in and therefore only had visitor rights without admin or update rights.

Should there now be other code paths that insert into the _places table, that would be OK for me and not a security issue.

**Comment by fisharebest** [comment]
Entries in this table are created when they are first used.

This one was created while viewing the individual list.

> Does your data contain both `Ahrensbök` and `Ahrensbok`?

You didn't answer this question.

Due to collation rules, only one of these can be stored.  If you have both, the second will fail with the error above....

**Comment by FrankWarius** [comment]
**0 enties for Ahrensbok**

![grafik](https://user-images.githubusercontent.com/16499744/173225159-5540f207-5e15-45aa-8c31-7220826cc3ec.png)

**1 entry for Ahrensbök,** 

![grafik](https://user-images.githubusercontent.com/16499744/173225478-986e587e-51c6-472f-af74-5a296ef97afd.png)

last changed before the incident in 2015 (the log entry is from the next day)

**Comment by FrankWarius** [comment]
in the last place Export / Backup 2022-05-23 Places Global.csv there is no Ahrensb%k entry.

**Comment by FrankWarius** [comment]
I think the case is understandable and it's not a security issue.

- About 5 years ago a Webtree 1.x Release DB migration crashed several times. The reason was places with umlauts. The workaround was to delete these incorrect ones from the _places table and to restart the migration.
- If this place is later called up for display, the corresponding entry in the _places table is inserted, regardless of whether it is called up by a guest or a logged-in user.

I just successfully tested this with Eckernförde.

The question remains why the insert was made twice and led to an error entry in the log. From my point of view there are more urgent problems and **we can close this issue**.
