### ISSUE TITLE
Sorting Individual list in "List style" is wrong in some cases

### ISSUE THREAD

**Issue by ro-la** [fisharebest/webtrees#4477]
Following name is in Individual list (Surname list style set to "list") sorted as "von Dernath" and not as "Dernath"

```
1 NAME gr. Paulina /von Dernath/
2 NPFX gr.
2 GIVN Paulina
2 SPFX von
2 SURN Dernath
```
When the Surname list style is set to "table" the sorting is OK

See also the discussion forum
https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/37047-sorting-individual-list-is-different-in-table-list-list-style

**Comment by fisharebest** [comment]
The discussion forum is very long, and contains many different issues.

In my system, `Denarth` and `von Denarth` are both sorted together.  See this screenshot.
<img width="442" alt="Screenshot 2022-09-19 at 11 17 38" src="https://user-images.githubusercontent.com/2306088/190996789-017adda5-6af1-4191-b0fc-1b9a65d34c14.png">

This is correct?  `von Denarth` is sorted before `Roach`.

Can you create a simple GEDCOM file that demonstrates the issue?
