### ISSUE TITLE
Indviduals with no surname should be sorted/displayed according to the SURN-tag

### ISSUE THREAD

**Issue by ro-la** [fisharebest/webtrees#4479]
In Individual list individuals with no surname part in the tag NAME and a value in the SURN subtag are handled differently in "List style" and "Table style". 
The surname from SURN-tag should be dispalyed also in "List style".

See also the discussion forum
https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/37047-sorting-individual-list-is-different-in-table-list-list-style

**Comment by fisharebest** [comment]
The SURN tag is used internally for sorting/grouping.  It is not designed for display.

Suppose we have the following `SURN` tags in different name records

* `2 SURN ROACH`
* `2 SURN Roach`
* `2 SURN RoaCh`

We upper-case this column, so that we can group them together.

e.g. `SELECT all surnames FROM names WHERE UPPER(surn) = 'ROACH';`

**Comment by ro-la** [comment]
The problem is not uppercase of the name.
The problem is when there is no name displayed, only the count of this name.

It should work in the "List layout" in the same way as in "Table layout"

**Comment by fisharebest** [comment]
> The surname from SURN-tag should be dispalyed also in "List style".

No it should not.  This value is only used for sorting/grouping.

We say many times that `NAME` is used for display, and `GIVN` / `SURN` are only used for sorting/searching.

If the individual has no surname, we show them in a category "No surname".

Therefore we should display "No surname" instead of empty text.

**Comment by fisharebest** [comment]
The individual list has A-Z and two other options: no surname / all surnames.

I think the problem is that we are showing a name with no surnames in the "all surnames" list, rather than the "no surnames" list.

**Comment by ro-la** [comment]
I am very sorry, but the fix https://github.com/fisharebest/webtrees/commit/214be48c32e57df34e154cd8ec7bc3bf7fa4615a is quite the opposite of what I wonted to achieve. :-(

And it seems you will completly remove a very good feature - grouping individuals using the field SURN which have worked for years. It is realy such a big thing to display the reason why "No surname" is listed in letter "W" - perhaps something like "No surname (Windsor)"? 

For example I have some individuals with no surname in NAME and a surname in SURN. And a lot of individuals with the same surname in NAME. Will be this family be splitted in the future?

**Comment by Norwegian-Sardines** [comment]
I agree with ro-la this “no surname” title for individuals without a surname in the NAME tag but a value in the SURN tag, breaks a long time use I had of webtrees.  This would render my use of webtrees v2.1 a no-go!

**Comment by fisharebest** [comment]
It is a difficult situation when there are users who rely on a bug.

See also the recent comments on https://github.com/FamilySearch/GEDCOM/issues/169

We have said for a long time that the `SURN` field is only used for sorting and searching, not for display.  

This needs some careful thinking

**Comment by Norwegian-Sardines** [comment]
An alternative would be for the software to incorporate other INDI tags that lend themselves to building a sorted and grouped list such as the INDI:NATI tag.  Using this tag in this way would be similar to the NAME tag process.

Obviously this tag would require an extensive and thought out update to each GEDCOM to add information to that tag, as well as a new database record, index and code to build the index and display its content.

Every instance of an INDIvidual could participate in multiple “House”, “clan”, or Nationality groupings (Half Swede and Half Norwegian) or showing the intersection of two “houses”.

**Comment by Norwegian-Sardines** [comment]
The GEDCOM 7.0 Committee has affirmed that the INDI:NATI tag will continue to have the following definition:

>An individual's national heritage or origin, or other folk, house, kindred, lineage, or tribal interest.
>
