### ISSUE TITLE
Add media - align problem

### ISSUE THREAD

**Issue by enes73** [fisharebest/webtrees#4482]
Like you can see in ScreenShots - when I try to add media file, some of blocks and text not where it should be.

text "Choose File" and text "No file chosen" are merged, even we have gray background for button "Choose File" and white space for text "No file chosen" or media name "eg. test-picture.jpg"

Also, below we have option "Filename on server" and some selection witch we cannot read... if we have any text below "folder" box... See attach. It seems that we have some text below... :)

![Screenshot 2022-06-14 114238](https://user-images.githubusercontent.com/6985394/174075480-3f085982-4354-4420-8411-8a48b2ca8fad.png)

![Screenshot 2022-06-14 114543](https://user-images.githubusercontent.com/6985394/174075510-5b5f6aaa-ff66-40e2-86fb-9d534694d959.png)

**Comment by fisharebest** [comment]
I've been looking at this on-and-off for a long time.

The HTML markup is trivial, and AFAICT matches the [documentation](https://getbootstrap.com/docs/5.1/forms/form-control/#file-input).

`<input class="form-control" id="file" name="file" type="file">`

It's the same in Control panel -> Media -> Upload, which is a much simpler page.

Suggestions welcome...

**Comment by reteP-riS** [comment]
I understand @enes73 mentioned 2 issues here:

1. The text "Choose file" is partly overwritten by the text "No file chosen" or the filename.
2. The button which enables the Folder selection box is partly overwritten by the Folder selection box.

As far as I can tell only the 2nd issue has been resolved. The 1st issue seems to persist and unforunately it exists on other forms as well, e. g. when selecting a GEDCOM file for import or when selecting a file to import geographic data. There may be more places where this issue occurs.

**Comment by fisharebest** [comment]
> I understand @enes73 mentioned 2 issues here:

This is always a problem :-(

An issue can only be "open" or "closed".  It cannot be "half open".

> As far as I can tell only the 2nd issue has been resolved. 

If you create two issues, then fixing the first one will automatically close the issue...

BUT - I think this other problem is now fixed.  I just upgraded from Bootstrap 5.1 to Bootstrap 5.2, and it is now working for me.
