### ISSUE TITLE
Update from 2.1.5 to 2.1.6 from admin panel not working

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#4485]
2.1.5 says in admin panel that 2.1.6 is available. Update from there ends with:

Client error: `GET https://github.com/fisharebest/webtrees/releases/download/2.1.6/webtrees-2.1.6.zip` resulted in a `404 Not Found` response:
Not Found

**Comment by FrankWarius** [comment]
I just tested the link https://github.com/fisharebest/webtrees/releases/download/2.1.6/webtrees-2.1.6.zip direct over Windows. It works.

**Comment by fisharebest** [comment]
This was a problem with the github release system.

For more info, see my support ticket: https://github.community/t/new-limit-of-25mb-for-release-binaries/257508
