### ISSUE TITLE
Problematic whitespace after expand/collapse icons

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4489]
This occurs for the expand/collapse icons of notes (perhaps also elsewhere) due to subsequent newline characters.
Ugly effect: Visible whitespace, underlined due to the enclosing 'a'-tag. See e.g. minimal theme with latest beta.

<img width="362" alt="whitespace" src="https://user-images.githubusercontent.com/18174787/175106657-9d6fade4-a840-44a7-8a78-80d83698ef7a.PNG">

The icon views themselves are ok, they avoid newlines [as explained here](https://github.com/fisharebest/webtrees/issues/4329).
But the parent view adds newlines after all, [here](https://github.com/fisharebest/webtrees/blob/8993d39a30118703a27ea366e6319289e28c1cd0/resources/views/fact-gedcom-fields.phtml#L60). 

If this line and the following are replaced by a single line

`<?= view('icons/expand') ?><?= view('icons/collapse') ?></a>`

the unwanted whitespace disappears.

**Comment by fisharebest** [comment]
I guess the parent element should be a `<button>`, rather than a `<a>`.

We use `<button>` in most other places.

**Comment by fisharebest** [comment]
Does the whitespace cause a problem?

Does the whitespace before/after the icons also cause a problem?

**Comment by ric2016** [comment]
Never mind, the switch to 'button' gets rid of the whitespace anyway (apparently via `class="btn"`).
