### ISSUE TITLE
Control Panel > GEDCOM Tags: Cannot hide Email address 

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4490]
<img width="665" alt="gedcom_tags" src="https://user-images.githubusercontent.com/18174787/175123190-8e299094-0e83-43a2-b675-6593e746285f.PNG">

... due to [typo here](https://github.com/fisharebest/webtrees/blob/8993d39a30118703a27ea366e6319289e28c1cd0/resources/views/admin/tags.phtml#L315) (at the end of line), should be

`<?= view('components/checkbox-inline', ['name' => 'HIDE_ADDR_EMAIL', 'label' => I18N::translate('hide'), 'checked' => (bool) Site::getPreference('HIDE_ADDR_EMAIL')]) ?>`

(Also the header 'Addresses' is somewhat confusing, as this only affects RESI facts)

**Comment by fisharebest** [comment]
> Also the header 'Addresses' is somewhat confusing, as this only affects RESI facts

Are you sure?  I just tried it (editing a SUBM record), and it worked there.

**Comment by ric2016** [comment]
> Also the header 'Addresses' is somewhat confusing, as this only affects RESI facts

I seem to have misinterpreted this, because the label is created via 'INDI:RESI:EMAIL'.
(Still, these fields are separate from actual Address fields. Not a big deal.)
