### ISSUE TITLE
Edit NAME- FONE/ROMN: PERSONAL_NAME_PIECES are missing

### ISSUE THREAD

**Issue by ungeahnt** [fisharebest/webtrees#4492]
According https://gedcom.io/specifications/ged551.pdf (p. 38) FONE and ROMN have _PERSONAL_NAME_PIECES_ (like GIVN, SURN, ...). The corresponding entries are missing in the wt edit form.

```
PERSONAL_NAME_STRUCTURE:=
n NAME <NAME_PERSONAL> {1:1} p.54
+1 TYPE <NAME_TYPE> {0:1} p.56
+1 <<PERSONAL_NAME_PIECES>> {0:1} p.37
+1 FONE <NAME_PHONETIC_VARIATION> {0:M} p.55
+2 TYPE <PHONETIC_TYPE> {1:1} p.57
+2 <<PERSONAL_NAME_PIECES>> {0:1} p.37
+1 ROMN <NAME_ROMANIZED_VARIATION> {0:M} p.56
+2 TYPE <ROMANIZED_TYPE> {1:1} p.61
+2 <<PERSONAL_NAME_PIECES>> {0:1} p.37
```

If these entries are added, then it would also be good if the subtags of the ROMN/FONE blocks are also indented. At the moment the TYPE-tag is not indented.

btw: in GEDCOM 7 the newly added ROMN and FONE tags are replaced by TRAN (Translation). Based on the discussion from #4455, I am currently testing the use of ROMN/FONE for my pedigree. ~~However, it is not yet clear to me how to transfer FONE to GEDCOM 7 / TRAN in the future. Are there already suggestions for this?~~
[edit]: I have only now seen that the BCP47-payload (= LANG) also includes phonetic alphabets and transliterations (e.g. fonipa, alalc97, ...).

**Comment by ric2016** [comment]
These tags are available via "Edit with all GEDCOM tags".
You can show them directly via `Control panel > GEDCOM tags`.

**Comment by ungeahnt** [comment]
> These tags are available via "Edit with all GEDCOM tags". You can show them directly via `Control panel > GEDCOM tags`.

I know, but you can only activate the NAME.FONE/ROMN and NAME.FONE/ROMN.TYPE, but not NAME.FONE/ROMN.GIVN/SURN .... 

like:

```
PERSONAL_NAME_PIECES:=
n NPFX <NAME_PIECE_PREFIX> {0:1} p.55
n GIVN <NAME_PIECE_GIVEN> {0:1} p.55
n NICK <NAME_PIECE_NICKNAME> {0:1} p.55
n SPFX <NAME_PIECE_SURNAME_PREFIX {0:1} p.56
n SURN <NAME_PIECE_SURNAME> {0:1} p.55
n NSFX <NAME_PIECE_SUFFIX> {0:1} p.55
n <<NOTE_STRUCTURE>> {0:M} p.37
n <<SOURCE_CITATION>> {0:M} p.39

```

Or did I miss something?

**Comment by ric2016** [comment]
No, you're right, these are actually missing.

**Comment by fisharebest** [comment]
These were suppressed intentionally, as the old edit interface couldn't handle them.

https://github.com/fisharebest/webtrees/blob/2.1.6/app/Gedcom.php#L1940-L1941

The new edit interface might work.
