### ISSUE TITLE
Raw gedcom edit delete source

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4496]
After raw editing a fact and removing a source it isn't possible to save the result
![demo](https://user-images.githubusercontent.com/104515/175977263-c5ebad91-ca4d-40d8-8a26-88ef019e6499.jpg)
.

**Comment by fisharebest** [comment]
Have you left blank lines at the end of the GEDCOM?

**Comment by ddrury** [comment]
I now see that there must be no CR/LF after the text - do you not think this situation is too restrictive and for the uninitiated (i.e me!) not intuitive?
