### ISSUE TITLE
Edit name: different appearance/behavior of FONE/ROMN

### ISSUE THREAD

**Issue by ungeahnt** [fisharebest/webtrees#4503]
In regard to 03c5559 (#4492), I have copied only the three modified files to my wt V2.1.6 installation (I hope this is sufficient). While testing, I see the following different appearance/behavior of FONE/ROMN:

a) The values from the subtags (SURN/GIVN) are not automatically passed to FONE or ROMN (as is the case with NAME).

b) For ROMN the edit button and the keyboard button are missing:
![grafik](https://user-images.githubusercontent.com/28572767/177320213-37139de0-331b-45ae-816b-e3a0e47c2c6a.png)

c) When opening the edit dialog, FONE is automatically displayed with a `//`. This happens also if you want to edit e.g. only NAME (and not FONE). After saving, FONE is then displayed with this 'empty string' in the INDI view, although you did not want to use FONE at all. This should not happen.

I put the items all in one issue, because I think they belong together. If needed, I can also create separate issues.

**Comment by ungeahnt** [comment]
Update to V2.1.7: all three issues still existing

**Comment by fisharebest** [comment]
> If needed, I can also create separate issues.

Please do this.

Some of these issues are easier to fix than others.
