### ISSUE TITLE
Fact/event type field max length restriction

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#4505]
When entering a new fact or event, the field for type is restricted to 15 positions. Which is far too low.

Trying to use the type 'Military service' which won't fit in.

I don't recall encountering this limitation before, so it must be something added in one of the latest versions.

According to the Gedcom 5.5.1 standard the number of characters allowed is 90.

**Comment by FrankWarius** [comment]
The Gedcom FACT structure is:
1 EVEN {1:90}
2 TYPE {1:15}
The edit-fact form only seems to support
1 EVENT <not supported, not shown by Webtrees>
2 TYPE <any text max 15 char>

A workaround is to enter the text in length 15 and then enter the full text via "Edit the raw GEDCOM".
