### ISSUE TITLE
Shared note edit

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4507]
Fields are shown for adding a note (add a note to a note?) fortunately contents are not saved.

![demo](https://user-images.githubusercontent.com/104515/178942859-870ae692-b36e-478a-a0cf-41487388157e.jpg)

**Comment by fisharebest** [comment]
This is adding a note to `CHAN` record.

0 NOTE
1 CHAN
2 NOTE

If you expand the source-citation, you will see another note.

I agree it is confusing.  We cannot collapse them, as it is on the same level as `CHAN:DATE`.

Suggestions?  It should probably be hidden initially.

We could change the labels for these notes.  Perhaps:

Notes about last change
Notes about citation

Notes on last change
Notes on citation

**Comment by fisharebest** [comment]
Or perhaps "Note on last change" (singular) for consistency...

**Comment by ddrury** [comment]
Is it really needed at all?

**Comment by fisharebest** [comment]
Is what needed?  The renamed label?

**Comment by ungeahnt** [comment]
> Suggestions? It should probably be hidden initially.

Is it possible to create an additional "section" CHAN and collapse 'Date/Time/Note/Author of last change' together? Or group all four parts in another way. Hidding is no solution


> Or perhaps "Note on last change" (singular) for consistency...

singular is better


>  ... fortunately contents are not saved.

I can reproduce this.

**Comment by fisharebest** [comment]
> The ability to add a note to a change record

Well, it is part of the standard - people would complain if we couldn't add it.

However, the entire CHAN fact is replaced when we edit a record - thus removing any `NOTE`.
This ought to be fixed as well...

**Comment by ddrury** [comment]
Hm,
It may be legal, but is it useful? Anyway given that you're doing it can you at least make it hidden by default
