### ISSUE TITLE
API change starting with wt2.1.6; Exception is not cought

### ISSUE THREAD

**Issue by bmarwell** [fisharebest/webtrees#4508]
Hi!

## To reproduce:

* I had a not-so-recent version of vesta modules installed.
* webtrees 2.1.5 or earlier
* PHP 8.1

Then upgrade to wt 2.1.6

## Behaviour

The whole site 500s with these errors all over the place:

```
[14-Jul-2022 19:44:08] WARNING: [pool www] child 27462 said into stderr: "[14-Jul-2022 17:44:08 UTC] PHP Fatal error:  Declaration of Cissee\Webtrees\Module\PersonalFacts\IndividualFactsTabModuleExtended::sidebarTitle(): string must be compatible with Fisharebest\Webtrees\Module\ModuleSidebarInterface::sidebarTitle(Fisharebest\Webtrees\Individual $individual): string in /var/www/html/modules_v4/vesta_personal_facts/IndividualFactsTabModuleExtended.php on line 455"
```

## Analysis

The method which changed is:

```
  /**
   * How should this module be identified in the control panel, etc.?
   *
   * @return string
   */
  public function sidebarTitle(): string
  {
      /* I18N: Name of a module/sidebar */
      return $this->getSidebarTitle(MoreI18N::xlate('Extra information'));
  }
```

The new method from the most recent vesta version is:

Gone. The closes I could find:

```
vesta_personal_facts/IndividualFactsTabModuleTrait.php:    protected function getMainTitle() {
```

## Proposed Solution

* Re-add the method `sidebarTitle(): string` with a default to not unnecessarily break old modules.
* When both are available, call the latter (sidebarTitle(Individual $individual): string`.

But more importantly:
* Catch such errors so the whole site does not 500 (if possible).

**Comment by fisharebest** [comment]
The change was #3915 in June 2021.  Because it was a breaking change, it was made during the 2.0 -> 2.1 upgrade.

So, I'm not sure that it would have worked with 2.1.5 (or any version of 2.1).

The module code exists to work around #3413 which was also fixed.
So, this function in the module is no longer needed.

> Catch such errors so the whole site does not 500 (if possible).

This is a fatal PHP error.  It cannot be caught.

**Comment by bmarwell** [comment]
Alright. Too bad. Thanks for the clarification though.
