### ISSUE TITLE
./pedigree-map/events.phtml missing a CSS class when displaying images

### ISSUE THREAD

**Issue by reteP-riS** [fisharebest/webtrees#4512]
I initially created this issue https://github.com/vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map/issues/29 for the respective Vesta module, but it seems that the respective code is part of the webtrees core:

https://github.com/fisharebest/webtrees/blob/0e5421932b835c4221b828a21fd7609d7230b452/resources/views/modules/pedigree-map/events.phtml#L39

It would be great if you could add a CCS class to the resulting HTML
`<img dir="auto" src="https://webtrees.example.com/tree/myTree/media-thumbnail ...`
with something like this:
`<img class="wt-chart-box-thumbnail" dir="auto" src="https://webtrees.example.com/tree/myTree/media-thumbnail ...`

**Comment by fisharebest** [comment]
> `wt-chart-box-thumbnail`

Probably best not to re-use this class, as it may have unintended consequences for people who expect it only to be used in chart-boxes..  I have added `wt-pedigree-map-thumbnail` instead.
