### ISSUE TITLE
Missing support and translation for 1 _NMAR Y

### ISSUE THREAD

**Issue by mpwt** [fisharebest/webtrees#4514]
In v1 and v2.0 it was possible to add 1 _NMAR Y to the person who was never married. "Y" was translated as "yes". In v2.1 the selection of this tag is no longer possible and the translation of existing "Y" is missing. For 1 _NMR Y for families it works as expected.

To replace the custom tag with 1 FACT Y 2 TYPE never married, a translation should be possible there.

**Comment by fisharebest** [comment]
FYI, you can use the standard `1 NMR 0`(number of marriages = 0) here instead

**Comment by mpwt** [comment]
Thank you for the quick reply. Since the tag was offered and used in the past webtrees versions, it should continue to be supported in v2.1. I find the display of "Never married - yes" better than "Number of marriages - 0", especially since church records more often state that the person was not married.

**Comment by fisharebest** [comment]
> should continue to be supported

Sure. But I'm away from home for a few days with no laptop.  Will fix this next week.

**Comment by mpwt** [comment]
Enjoy it (without a laptop)!

**Comment by mpwt** [comment]
Almost. Now the tag can be selected and used. Thank you very much.

However, the input field is not a checkbox as with 1 _NMR, so that a "Y" is automatically saved
<img width="414" alt="Bildschirmfoto 2022-07-25 um 19 30 47" src="https://user-images.githubusercontent.com/16311627/180839181-5217479f-3649-4549-b0af-bf7916dd6f6b.png">

and a manually entered "Y" is not translated as "yes".
<img width="856" alt="Bildschirmfoto 2022-07-25 um 19 29 46" src="https://user-images.githubusercontent.com/16311627/180839161-59b7cfd2-1089-4ef5-9df4-7b239ca51770.png">
