### ISSUE TITLE
The indipage Facts and events picture keeps scrolling - Webtrees 2.1.7-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#4516]
I want still to show the primary picture.
How do I get rid of the changing individual pictures?

**Comment by fisharebest** [comment]
> How do I get rid of the changing individual pictures?

The only changing pictures in webtrees are in the slideshow block on the home page.

I don't know which pictures you are talking about...

**Comment by melizaa** [comment]
Greg, see for instance <https://dev.webtrees.net/demo-dev/tree/demo/individual/i1>

**Comment by fisharebest** [comment]
This looks like a consequence of the upgrade from bootstrap 5.1 to 5.2.

**Comment by fisharebest** [comment]
https://github.com/twbs/bootstrap/issues/36526
