### ISSUE TITLE
Documentation of release date for 2.1.7

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#4519]
At https://webtrees.net/blog/ there it is written:
```
webtrees 2.1.7 released
20 June 2022
```

The release date is wrong (copy paste error).

**Comment by hartenthaler** [comment]
additionally: at https://www.webtrees.net/index.php/en/ the block "Latest releases" is outdated.

**Comment by fisharebest** [comment]
FYI, the source code for the webtrees.net site is available at https://github.com/webtrees/webtrees.github.io

You can raise issues (or create pull requests) there.

**Comment by hartenthaler** [comment]
Ah! Yes. Thanks!
