### ISSUE TITLE
HTML block which includes gedcom_stats block

### ISSUE THREAD

**Issue by wooc** [fisharebest/webtrees#452]
On my home page I've set the HTML block. That block includes gedcom_stats block inside.
I see the following error:
Fatal error: Class 'gedcom_stats_WT_Module' not found in /app/Stats.php on line 5948

**Comment by fisharebest** [comment]
The modules are not (currently) loaded using the autoloader.

We will probably change to a system similar to way themes are created.

**Comment by fisharebest** [comment]
This should now be fixed.

Can you test and confirm.
