### ISSUE TITLE
new graduation event TYPE is missing

### ISSUE THREAD

**Issue by Bogiegit** [fisharebest/webtrees#4526]
When entering a new graduation the tag TYPE is not shown by default. You have to click on "Edit with all GEDCOM tags".
Furthermore there is no possibility to activate it under Control panel -> GEDCOM tags -> Facts and events.

**Comment by fisharebest** [comment]
> When entering a new graduation the tag TYPE is not shown by default. You have to click on "Edit with all GEDCOM tags".

Infrequently used tags are hidden by default - and only shown when the "show all" option is selected.

I have approximately 2000 GEDCOM files downloaded from the internet.  INDI:GRAD:TYPE occurs zero times.  It is therefore an infrequently used tag.

So, this is working as designed.

> Furthermore there is no possibility to activate it under Control panel -> GEDCOM tags -> Facts and events.

I believe that Richard Cissee has created a module which allows every possible tag/subtag combination to be configured individually.

**Comment by Bogiegit** [comment]
Ok, got you, I can live with that.

In my eyes the Vesta modules modify too many functions of webtrees and have side effects which I don't want to have in my installation. Thus I intend to stay close to the standard and use some smaller customizations only.

**Comment by ric2016** [comment]
> In my eyes the Vesta modules modify too many functions of webtrees and have side effects which I don't want to have in my installation.

You should be able to only those parts of Vesta that are relevant for you - Which side effects in particular are problematic? I.e. it should be possible to use any part of Vesta as 'smaller customization'. But this should perhaps be discussed elsewhere.

**Comment by ric2016** [comment]
> I believe that Richard Cissee has created a module which allows every possible tag/subtag combination to be configured individually.

For future reference: This in indeed available via the Vesta module '⚶ Vesta Classic Look & Feel'.
