### ISSUE TITLE
View statistics as graphs / Most common surnames Display Issue with Shorter Right Column

### ISSUE THREAD

**Issue by KosherJava** [fisharebest/webtrees#453]
By default the right column in the statistics block is longer than the left one. If some items in the right column are removed (via config) and the right column is shorter, the View statistics as graphs / Most common surnames section is cramped into a single narrow column.

**Comment by fisharebest** [comment]
This is not what I see.

The common surnames list goes across the entire block.

URL?

**Comment by makitso** [comment]
I see the problem.... let me look at it.
