### ISSUE TITLE
The expressions with  variable %S, will not be translated into Persian

### ISSUE THREAD

**Issue by borjian** [fisharebest/webtrees#4532]
Hello
I completed the translation of Webtrees in Persian offline and at https://translate.webtrees.net/projects/webtrees/webtrees/fa/
I uploaded Now, according to the initial translation, there are two problems when change to Persian language.
1. The expressions with variable %S, will not be translated into Persian in messages.php, for example
"This page has been viewed %s time."
2. In abbreviating the lists, both Persian and English alphabet letters are seen together
Now, in order to correct the translation of some phrases, I need to see the full translation of the site
my site : borjtree.ir
Best regards
bijan borjian
![1](https://user-images.githubusercontent.com/6689759/183498172-e0ae5fbd-b319-41ff-a8ac-fee642dcc7c0.JPG)
![2](https://user-images.githubusercontent.com/6689759/183498225-5fc53477-689b-4592-ae82-2ed45816ee4b.JPG)

**Comment by fisharebest** [comment]
Wrong plural rule for `fa` in [fisharebest/localization](https://github.com/fisharebest/localization) 1.16.0

**Comment by fisharebest** [comment]
> there is still a problem in the second issue

Please create a separate issue for this.

It is difficult to manage issues that contain more than one issue.

Thanks!
