### ISSUE TITLE
error in Latest Beta Demo

### ISSUE THREAD

**Issue by zhoueysun** [fisharebest/webtrees#4533]
When clicking from the main website http://dev.webtrees.net/demo-dev/ I get this error message.

_Error: Class "Fisharebest\Localization\Locale\LocaleAf" not found in /home/webtrees/dev.webtrees.net/demo-dev/app/Module/LanguageAfrikaans.php:37 Stack trace: #0 /home/webtrees/dev.webtrees.net/demo-dev/app/Http/Middleware/UseLanguage.php(96): Fisharebest\Webtrees\Module\LanguageAfrikaans->locale() #1 [internal function]: Fisharebest\Webtrees\Http\Middleware\UseLanguage::Fisharebest\Webtrees\Http\Middleware\{closure}() #2 /home/webtrees/dev.webtrees.net/demo-dev/vendor/illuminate/collections/Collection.php(695): array_map() #3 /home/webtrees/dev.webtrees.net/demo-dev/app/Http/Middleware/UseLanguage.php(97): Illuminate\Support\Collection->map() #4 /home/webtrees/dev.webtrees.net/demo-dev/app/Http/Middleware/UseLanguage.php(63): Fisharebest\Webtrees\Http\Middleware\UseLanguage->languages() #5 /home/webtrees/dev.webtrees.net/demo-dev/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process() #6 /home/webtrees/dev.webtrees.net/demo-dev/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle() #7 /home/webtrees/dev.webtrees.net/demo-dev/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process() #8 /home/webtrees/dev.webtrees.net/demo-dev/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle() #9 /home/webtrees/dev.webtrees.net/demo-dev/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process() #10 /home/webtrees/dev.webtrees.net/demo-dev/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle() #11 /home/webtrees/dev.webtrees.net/demo-dev/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process() #12 /home/webtrees/dev.webtrees.net/demo-dev/app/Http/Middleware/BadBotBlocker.php(233): Middleland\Dispatcher->handle() #13 /home/webtrees/dev.webtrees.net/demo-dev/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process() #14 /home/webtrees/dev.webtrees.net/demo-dev/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle() #15 /home/webtrees/dev.webtrees.net/demo-dev/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process() #16 /home/webtrees/dev.webtrees.net/demo-dev/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle() #17 /home/webtrees/dev.webtrees.net/demo-dev/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process() #18 /home/webtrees/dev.webtrees.net/demo-dev/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle() #19 /home/webtrees/dev.webtrees.net/demo-dev/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process() #20 /home/webtrees/dev.webtrees.net/demo-dev/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process() #21 /home/webtrees/dev.webtrees.net/demo-dev/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle() #22 /home/webtrees/dev.webtrees.net/demo-dev/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process() #23 /home/webtrees/dev.webtrees.net/demo-dev/app/Http/Middleware/BaseUrl.php(79): Middleland\Dispatcher->handle() #24 /home/webtrees/dev.webtrees.net/demo-dev/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process() #25 /home/webtrees/dev.webtrees.net/demo-dev/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle() #26 /home/webtrees/dev.webtrees.net/demo-dev/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process() #27 /home/webtrees/dev.webtrees.net/demo-dev/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle() #28 /home/webtrees/dev.webtrees.net/demo-dev/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process() #29 /home/webtrees/dev.webtrees.net/demo-dev/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle() #30 /home/webtrees/dev.webtrees.net/demo-dev/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process() #31 /home/webtrees/dev.webtrees.net/demo-dev/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #32 /home/webtrees/dev.webtrees.net/demo-dev/app/Webtrees.php(275): Middleland\Dispatcher->dispatch() #33 /home/webtrees/dev.webtrees.net/demo-dev/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch() #34 /home/webtrees/dev.webtrees.net/demo-dev/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest() #35 {main}_

**Comment by fisharebest** [comment]
Github keeps demanding authentication tokens before it will allow command-line access.

I've fed it a new token...
