### ISSUE TITLE
Shared notes/markdown

### ISSUE THREAD

**Issue by HRN-webtrees** [fisharebest/webtrees#454]
If adding text/img in addition to markdown table in a Shared note, there is no space between table and text/img. May I suggest adding margin-bottom: 8px; to .markdown table in all themes?

**Comment by fisharebest** [comment]
I give up.  I've spent 20 minutes trying to create a table in markdown.

Cut/paste some markdown here that will reproduce your problem.

**Comment by HRN-webtrees** [comment]
If you add this table and an image to a shared note, you'll see there is no space between them.
I suggest adding margin-bottom: 8px; to .markdown table in all themes

Markdown table:

AAA|BBB|CCC|DDD|EEE|FFF|GGG|HHH|III
-|-|-|-|-|-|-|-|-
aaaaaaaa|bb|cccccccccc|ddd|eeeeeee|fff|g|hhhh|iiiiiiiiiiii
aaaaaaaa|bb|cccccccccc|ddd|eeeeeee|fff|g|hhhh|iiiiiiiiiiii
aaaaaaaa|bb|cccccccccc|ddd|eeeeeee|fff|g|hhhh|iiiiiiiiiiii
![sharednote](https://cloud.githubusercontent.com/assets/7372415/7086885/9fe78cec-df8e-11e4-847d-f74edbe2eb22.jpg)
