### ISSUE TITLE
Problem with edit media algorithm-both Demo and Latest Beta

### ISSUE THREAD

**Issue by zhoueysun** [fisharebest/webtrees#4542]
When you open the Media tab=>Media object=>Edit (pencil), you get the Add a Media Object screen instead of Edit Media Object screen. The Edit Media screen occurs correctly when you click on the Title.

**Comment by fisharebest** [comment]
From the media tab, clicking the edit link allows me to edit the link to the media object.  This is the same as other links, such as source/note/repo links.

I'm not sure what you are seeing/doing.  Maybe add some screenshots?

**Comment by zhoueysun** [comment]
Everything is on the **Latest Demo**.
From, the **Media Tab**, when I click the pencil to **edit a media file**:
![edit-media-file-1](https://user-images.githubusercontent.com/14076780/187475869-ebfd3c88-4672-4c92-a96e-aba812b982bc.png)

I get the **add new media page**:
![edit-media-file-1a](https://user-images.githubusercontent.com/14076780/187476292-8dc3e844-632e-4c04-8aeb-5e389e7df20b.png)

Of course, when I click on the **file name** from the **Media Tab**:
![edit-media-file-2](https://user-images.githubusercontent.com/14076780/187476579-ae3bb77f-80eb-4113-8d62-d45501408e22.png)

I can then **edit the media object**: 
![edit-media-file-2a](https://user-images.githubusercontent.com/14076780/187476791-685a480c-ae6f-4eca-bbed-8966bf633e95.png)

I think this is a change from the prior algorithm

**Comment by fisharebest** [comment]
> I think this is a change from the prior algorithm

I don't think it is.

The current logic is consistent.  The "edit" icon edits the **link**.  You need to follow the link to edit the linked object.
