### ISSUE TITLE
v2.1.7 - Privacy settings for shared notes do not work

### ISSUE THREAD

**Issue by mpwt** [fisharebest/webtrees#4544]
<img width="1133" alt="privacy_restrictions" src="https://user-images.githubusercontent.com/16311627/184805171-99fc9ee7-b9f4-4e7b-975a-8b3b50f80b48.png">

The privacy setting for shared notes is still from the previous versions. If I delete the setting, it cannot be added again from the selection menu.

<img width="944" alt="facts_events" src="https://user-images.githubusercontent.com/16311627/184805202-70591591-4bb2-4e5b-9abb-e50594680c61.png">

Despite specifying that shared notes should only be visible to members, they are displayed and can be expanded.

**Comment by fisharebest** [comment]
Already reported and fixed.

See #4521
