### ISSUE TITLE
Error with recent commit

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4550]
Since https://github.com/fisharebest/webtrees/commit/10e0649788c8d7d4974d81c048ca2b225df8f22e am getting the following error:
Fisharebest\Webtrees\I18N::number(): Argument #1 ($n) must be of type float, string given, called in …\resources\views\lists\surnames-compact-list.phtml on line 24 …\app\I18N.php:402
#0 …\resources\views\lists\surnames-compact-list.phtml(24): Fisharebest\Webtrees\I18N::number('726')

**Comment by fisharebest** [comment]
I think that one was fixed in b7c04225f29dcd7a44d33dd14370434ae68454b5

I added `declare(strict_types=1);` to all our PHTML templates.  It's now picking up some type mismatches.
