### ISSUE TITLE
strict type error ... maybe?

### ISSUE THREAD

**Issue by ungeahnt** [fisharebest/webtrees#4552]
Thanks.  I suspect there may be a few more of these...

_Originally posted by @fisharebest in https://github.com/fisharebest/webtrees/issues/4551#issuecomment-1239468516_

maybe also here:
https://github.com/fisharebest/webtrees/blob/5442f1410722fe1fa32ec3696d7ab3565043b847/resources/views/lists/families-table.phtml#L507

and here

https://github.com/fisharebest/webtrees/blob/5442f1410722fe1fa32ec3696d7ab3565043b847/resources/views/lists/families-table.phtml#L514

?

'Age' is INT and round returns float, or?

**Comment by fisharebest** [comment]
> round returns float

Correct - even if you ask for zero decimal places (i.e. "integers").

I think these two are OK.  The second parameter `1` says we want 1 decimal place.  So these are expected to be floating point numbers.

In the other case, we were expecting integers.

**Comment by fisharebest** [comment]
I've searched through the code, and cannot find any more of these.

**Comment by ungeahnt** [comment]
I thought that the first parameter of marriageAgeData[] is an object of class 'Age' and therefore must be from the type integer. I thought therefore the float return value of round would lead to an error. 

I guess I am wrong and this first parameter can apparently be of any type. 

Sorry for the inconvenience.

**Comment by fisharebest** [comment]
> Sorry for the inconvenience.

Please do not apologise!

Extra eyes on the code are always good.
