### ISSUE TITLE
Official docker support

### ISSUE THREAD

**Issue by webysther** [fisharebest/webtrees#4554]
I want to suggest putting in Readme or another docs section docker support to make it easy to deploy and update/upgrade.

A great find is this project https://github.com/NathanVaughn/webtrees-docker from @NathanVaughn, maybe fork inside the webtrees or point to this project.

**Comment by fisharebest** [comment]
There's already a link to another docker installation in the [installation documentation](https://webtrees.net/install/).

Is this one better/different to the existing one?

(I have never used docker).

Perhaps you could compare the two, and either add/replace this one?  The docs page has an edit link at the bottom...

**Comment by webysther** [comment]
Nice, thanks, I started using the webtrees now, I will make the comparison.

**Comment by webysther** [comment]
Yes, there a few options make the another one better, maybe consider suggest both:
- One is more for using docker --link strategy and another use docker-compose, make easy to up the all services at same time.

May I will suggest a merge of this two projects or move the creation of one by [lsi](https://www.linuxserver.io/) community
