### ISSUE TITLE
Face lift ideias and discussions

### ISSUE THREAD

**Issue by webysther** [fisharebest/webtrees#4555]
There's someplace to discuss UX/UI upgrades?

I have a few suggestions and want to know if is ok send PR to have a chance to be accepted:

- New SVG icons: https://www.toools.design/free-open-source-icon-libraries
  - My picks: [Google](https://github.com/google/material-design-icons), [Apple](https://developer.apple.com/sf-symbols/), [Remix](https://remixicon.com/) and [Hero](https://heroicons.com/)
- Start using a better font: [public sans](https://github.com/uswds/public-sans) or another.
- Start using a UI: [MUI](https://mui.com) or [HTML5 Boilerplate](https://github.com/h5bp/html5-boilerplate)

Maybe this [starts the possibility of changing the license to another one](4556), like MIT.

**Comment by fisharebest** [comment]
> There's someplace to discuss UX/UI upgrades?

Yes.  There is a [discussion forum](https://www.webtrees.net/index.php/en/forum/2-open-discussion) for this.

Note that the appearance is controlled by themes, and themes are free to override fonts, styles, icons, etc.

By default, webtrees uses [FontAwesome icons](https://fontawesome.com/) and the [Bootstrap native font stack](https://getbootstrap.com/docs/5.2/content/reboot/#native-font-stack).

An important consideration for fonts is support for non-latin characters.  e.g. hebrew, arabic, greek, cyrillic, CJK, etc.
