### ISSUE TITLE
Consider re license to Apache/MIT

### ISSUE THREAD

**Issue by webysther** [fisharebest/webtrees#4556]
If the project doesn't have another GPL project inside, consider changing the license to another more permissive one.

Q/A

[Can I relicense my own GPL code into Apache/MIT?](https://opensource.stackexchange.com/questions/7533/can-i-relicense-my-own-gpl-code-into-apache-mit)
[MIT vs GPL license](https://stackoverflow.com/questions/3902754/mit-vs-gpl-license)

**Comment by fisharebest** [comment]
I am very happy with the GPL licence.  All existing contributions were made under GPL.  This includes the translations.

For libraries, I agree that MIT is a good licence.  I have written many libraries and packages that are released under MIT.

But for a project like this, I think GPL is the better licence.
