### ISSUE TITLE
Unable to switch language or theme

### ISSUE THREAD

**Issue by Manja-S** [fisharebest/webtrees#4558]
I just switched my hosting provider, and now I'm unable to switch my language or theme using the items in the top bar of my Webtrees. I can't change the language at my Control Panel (top right) either. I've tried both with and without custom modules enabled. Is there any other setting I can try?

My tree: https://webtrees.schledorn.nl

**Comment by fisharebest** [comment]
When you click these links, an HTTP `POST` request is sent to the server.

Your server is responding with a `501 - Not Implemented` response.

I don't think this response comes from webtrees - we have no code that generates this response.

My guess is that this response is being generated by your webserver - and that the request isn't actually passed to the webtrees code.

**Comment by Manja-S** [comment]
I'll ask my provider.

**Comment by Manja-S** [comment]
My hosting provider has solved the issue. They said this was a mod_security issue for which exceptions were made.
