### ISSUE TITLE
"There are pending changes for you to moderate"

### ISSUE THREAD

**Issue by HRN-webtrees** [fisharebest/webtrees#456]
Even with no pending changes I get this message on the index page.
Clicking the link will open/close a popup window, and index page is reloaded.

**Comment by fisharebest** [comment]
I haven't seen this.  Are there steps that will reproduce it, or is it an intermittent/random issue?

**Comment by HRN-webtrees** [comment]
I see this all the time

Only me as Administrator (changes automatically approved)
Users are all set to "Member"

**Comment by HRN-webtrees** [comment]
You can also see this in demo dev when logged in as moderator

**Comment by JustCarmen** [comment]
It is the 'pending changes block' which causes this error. If you have set this block on the homepage or mypage it will always output the message, even if there are no pending changes.
