### ISSUE TITLE
fresh install on Devuan Chimaera, first visit to localhost/webtrees yields blank page

### ISSUE THREAD

**Issue by wfdudley** [fisharebest/webtrees#4564]
Fresh install on Devuan Chimaera machine (which is Debian without systemd).
Fresh Install of php74 (this is the dpkg listing):
`
ii  libapache2-mod-php7.4                  7.4.30-1+deb11u1                   amd64
ii  php                                    2:7.4+76                           all
ii  php-common                             2:76                               all
ii  php7.4                                 7.4.30-1+deb11u1                   all
ii  php7.4-cli                             7.4.30-1+deb11u1                   amd64
ii  php7.4-common                          7.4.30-1+deb11u1                   amd64
ii  php7.4-json                            7.4.30-1+deb11u1                   amd64
ii  php7.4-readline                        7.4.30-1+deb11u1                   amd64

`
Apache version is `2.4.54-1~deb11u1`

and then:

`apachectl restart`.

Result: blank page when visiting localhost/webtrees

I got the SAME RESULT with a fresh install on FreeBSD 12.3, but I attributed that to FreeBSD having PHP81 installed.
That's when I did the install on the Devuan machine.

I've been running a web server for many years, I have other PHP applications running, so I have confidence in my "install".
I looked for a FAQ page or content in "Discussions" or "Wiki" and found naught.

I see in "webtrees/index.php" this line:
`require __DIR__ . '/vendor/autoload.php';`

There is no file called autoload.php in the distribution, and there isn't one on (either) machine.

**Comment by fisharebest** [comment]
> I looked for a FAQ page

Try this https://webtrees.net/faq/500/

**Comment by fisharebest** [comment]
> There is no file called autoload.php in the distribution, and there isn't one on (either) machine.

"In the distribution"?  What exactly did you install?

It is included in the versioned releases.  See https://github.com/fisharebest/webtrees/releases

But if you simply did a `git clone`, you'll need to install all the dependencies yourself using `composer install --no-dev`.  See https://github.com/fisharebest/webtrees#building-and-developing

**Comment by wfdudley** [comment]
Thanks for the quick reply.  I didn't understand the difference between using git clone
and downloading a "release", though I should have.  Perhaps a sentence in README.md
could gently point people to "releases".  Change this:
1. Download the .ZIP file for latest stable version from [github.com](https://github.com/fisharebest/webtrees/releases/latest).

To this:
1. Download the .ZIP file for latest stable version from [github.com/fisharebest/webtrees/releases](https://github.com/fisharebest/webtrees/releases/latest).

That would have gently pointed me in the right direction.

As far as the FAQ; I have no excuse for not finding it.

Thanks,
Bill Dudley
