### ISSUE TITLE
Cannot fetch latest webtrees version

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#4565]
Since the last update, I see an error message that occurs only on localhost:

`Cannot fetch latest webtrees version. cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://dev.webtrees.net/build/latest-version.txt?w=2.1.8-dev&p=8.1.5&s=6234e2f3-07fe-438c-9003-657399bc51fb&d=mysql`

I haven't changed anything to my local environment. I am not sure if this is something I should fix or is this error caused by webtrees?

**Comment by fisharebest** [comment]
1) I have just checked a few sites, and all are fetching this file OK.

2) The SSL cert at dev.webtrees.net seems OK.

<img width="848" alt="Screenshot 2022-09-30 at 10 03 32" src="https://user-images.githubusercontent.com/2306088/193234778-abf36125-caa0-4189-bfaf-eeceb0c47d11.png">

It could be that the root-certificate store on your server is outdated?
Is this your local dev machine, or a web-host?

**Comment by JustCarmen** [comment]
> Is this your local dev machine, or a web-host?

This is my local dev machine running on Wampserver. 

> It could be that the root-certificate store on your server is outdated?

I don't use https on my local server because I don't know how to get that done. Does that have anything to do with this error?

**Comment by fisharebest** [comment]
Try this link: https://bobcares.com/blog/curl-error-60-in-wamp-server/

Or, if you are not using the latest version of WAMP, then perhaps upgrade it?

**Comment by ddrury** [comment]
If you're using the latest version of wamp and have decided to use fcgi rather than the windows module to access PHP then be aware that each version of PHP has it's own ini file and you have to add the pointer to cacert.pem to each version that you use

**Comment by FrankWarius** [comment]
it's the same problem as in #3759.

You have to download cacert.perm and link the file in php.ini 
curl.cainfo = “[pathtofile]cacert.pem”

see https://medium.com/@narendravaghela/how-to-fix-curl-error-60-ssl-certificate-problem-80e7dafafa57

**Comment by fisharebest** [comment]
@FrankWarius - thanks for the link.

**Comment by JustCarmen** [comment]
> You have to download cacert.perm and link the file in php.ini
curl.cainfo = “[pathtofile]cacert.pem”

Thanks. Problem solved.

> be aware that each version of PHP has it's own ini file and you have to add the pointer to cacert.pem to each version that you use

Thanks for the hint.
