### ISSUE TITLE
2.1.dev SqlSrv: Mirgration44 (168): SQLSTATE[23000]

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4571]
I startet setup with a fresh DB prefix(without debugging) and got 2 exception, which i could bypass with Edge reload.

SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Index "wt10_media_m_ext_m_type_index" ist von Spalte "m_ext" abhängig. (SQL: DECLARE @sql NVARCHAR(MAX) = '';SELECT @sql += 'ALTER TABLE [dbo].[wt10_media] DROP CONSTRAINT ' + OBJECT_NAME([default_object_id]) + ';' FROM sys.columns WHERE [object_id] = OBJECT_ID('[dbo].[wt10_media]') AND [name] in ('m_ext') AND [default_object_id] <> 0;EXEC(@sql);alter table "wt10_media" drop column "m_ext")
#5 D:\web\WT21Dev\webtrees\app\Schema\Migration37.php(89): Illuminate\Database\Schema\Builder->table('media', Object(Closure))

SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Das Einführen der FOREIGN KEY-Einschränkung "wt10_place_location_parent_id_foreign" für die wt10_place_location-Tabelle kann Schleifen oder mehrere Kaskadepfade verursachen. Geben Sie ON DELETE NO ACTION oder ON UPDATE NO ACTION an, oder ändern Sie andere FOREIGN KEY-Einschränkungen. (SQL: alter table "wt10_place_location" add constraint "wt10_place_location_parent_id_foreign" foreign key ("parent_id") references "wt10_place_location" ("id") on delete CASCADE on update CASCADE)
#5 D:\web\WT21Dev\webtrees\app\Schema\Migration44.php(62): Illuminate\Database\Schema\Builder->table('place_location', Object(Closure))

than one, which I couldn't skip

SQLSTATE[23000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Ein expliziter Wert für die Identitätsspalte kann nicht in der wt10_place_location-Tabelle eingefügt werden, wenn IDENTITY_INSERT auf OFF festgelegt ist. (SQL: insert into [wt10_place_location] ([id], [parent_id], [place], [latitude], [longitude]) select [pl_id], CASE pl_parent_id WHEN 0 THEN NULL ELSE pl_parent_id END, [pl_place], REPLACE(REPLACE(pl_lati, 'S', '-'), 'N', ''), REPLACE(REPLACE(pl_long, 'W', '-'), 'E', '') from [wt10_placelocation] left join [wt10_place_location] on [id] = [pl_id] where [id] is null order by [pl_level] asc, [pl_id] asc)
#3 D:\web\WT21Dev\webtrees\app\Schema\Migration44.php(168): Illuminate\Database\Query\Builder->insertUsing(Array, Object(Illuminate\Database\Query\Builder))

**Comment by fisharebest** [comment]
Which version of SQL-Server?

**Comment by FrankWarius** [comment]
lastest 
Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Express Edition (64-bit) on Windows Server 2022 Datacenter 10.0 <X64> (Build 20348: ) (Hypervisor)

**Comment by fisharebest** [comment]
Three different errors here.

It is always difficult to manage issues that contain many different errors.

1) Don't know yet.  We drop columns individually (required by SQLite) - but may need to drop two columns together for SQL-Server.

2) SQL-Server doesn't support `ON DELETE CASCADE` for self-referential foreign keys.

3) Need special code for SQL-Server.
