### ISSUE TITLE
SOUR:TITL, SOUR:PUBL and SOUR:AUTH can contain multi-line data

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#4580]
These three fields are currently defined as "single-line" fields

To comply with the 5.5.1 specification, these should be changed to multi-line fields.

However, we need to look at how we use/display these.

For example, we use the title as the "name", and in contexts where multi-line data is not appropriate.  Should we just use the first line, or collapse the whitespace?

**Comment by Norwegian-Sardines** [comment]
- For the “Source List Table” I would collapse them into one line.

- For display on the “Source Detail Page” I would display them as entered, multi-line.  Some books, articles, and other sources have 2 titles, primary and secondary, multiple authors, and a publisher line that is easier to read if on multiple lines.

- For the link title on the INDI or FAM page to the Source_Record, I would again collapse the title to one line.

The Source detail page is the best place to show the multi line data for readability.

If webtrees ever gets an updated reporting add-on, we would need to discuss in better detail how citation and bibliography writing should better use these tags and maybe by GEDCOM v7.1 they will have nailed down citation based tags.
