### ISSUE TITLE
Formatting issue in Clouds theme

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#4582]
![temp](https://user-images.githubusercontent.com/5910274/196878368-914b4102-d00b-4e6c-b558-d9ee459cb810.jpg)
comes from GEDCOM:
```
1 OCCU Pastor
2 AGNC Lighthouse Spirit of God Church
2 ADDR 1657 Mable Avenue
3 CONT Flint, Michigan
```

**Comment by fisharebest** [comment]
This is a bug in Safari / IOS - and is already reported at #4353

There is probably a workaround for the bug.

**Comment by WGroleau** [comment]
Bug reported to Apple as FB11707784.  Unfortunately, Apple does not allow anyone to see a bug report except a few employees and the individual who reported it.

**Comment by WGroleau** [comment]
I forgot I had seen it before and even commented on the earlier issue!
