### ISSUE TITLE
Feature Request: Slightly more granular privacy controls

### ISSUE THREAD

**Issue by pganssle** [fisharebest/webtrees#4583]
I am looking to make my family tree more public, but the controls available in the privacy panel are not quite granular enough. Right now I can set it so that individuals are hidden to visitors if they are alive or dead, and I can specify that certain pieces of information are private (for everyone).

However, I would like it if the controls were more granular on two dimensions. One, I'd like to be able to specify privacy restrictions based on whether an individual is alive or dead. Right now, it seems I can only specify "everyone" or specific families/branches/etc, but I'd like to be able to say "Show someone's birth event if they are alive, but if they are dead hide it". So maybe add "Living individuals" and "Dead individuals" to this list:

![image](https://user-images.githubusercontent.com/1377457/196983161-ac2a17fd-8e8f-42f8-b01e-7dfec171afb2.png)

It would also be nice to be able to change the default access level for all facts and information. Right now it seems like all facts are visible to anyone who can see the person in the tree unless otherwise specified, but I'd rather it go the other way, where I specify that everything is hidden unless otherwise specified.

**Comment by fisharebest** [comment]
> "Show someone's birth event if they are alive, but if they are dead hide it".

I don't think it makes sense to give more privacy to dead individuals, than to living ones.

Can you explain your reasoning or use-case for such a feature?

**Comment by pganssle** [comment]
>  I don't think it makes sense to give more privacy to dead individuals, than to living ones.

I meant to say it the other way around, but I assume that if you add ways to select people by "living status" that end users would be able to configure it however they like. That said, I am mainly concerned with providing additional privacy to living people.

**Comment by pganssle** [comment]
> In which case, that functionality already exists...

> By default, living individuals are hidden completely.

> To hide the birth (or some other) event from dead individuals, set up a rule "All records, Death, Show to members"

Sorry, I think I may not have explained correctly. I would like to be able to make the names and relationships of people in my family public, because I don't think "Paul and Chris are cousins" is particularly sensitive information, but some things like birthday and residence information seems like it could be used for identity theft, which is not a concern for people who have been dead for a while (often this information is published in obituaries anyway).

So ideally I'd want to specify a rule like, "Living people are visible but their birthday, residence, religion and notes about them are available only to members. All that information is available for dead people."

**Comment by fisharebest** [comment]
> I would like to be able to make the names and relationships of people in my family public

OK - there are already options for this.

In the privacy settings page are two options:

Show private names
Show private relationships

With these enables, visitors will be able to see charts, etc. which show that "Paul and Chris are cousins".
But they won't be able to see any details of Paul or Chris.

**Comment by pganssle** [comment]
Yes, that is a reasonable workaround, but won't it override restrictions set at an individual level? If I want to keep specific people's names private (e.g. some people are sensitive about having any details about their children made public) while achieving the general goal of "all names public, some additional information public for dead people", I don't think your workaround will work.

Stepping back from specific use cases, I think the fact that the living (+ recently dead) / dead dichotomy already exists in the privacy settings (and in fact the two categories have different default settings!) is a sign that this is a natural way to delineate individuals for privacy purposes. It seems natural to make that a first-class concept in the granular privacy settings, since it is likely that people will have different levels of tolerance about what is public between the two groups. Unless you think that it is particularly difficult to implement or maintain, or you think that having that kind of selector will lead people to accidentally do something they don't mean to, it seems like it would be a nice addition to the privacy controls.

By the way, I'd like to take a moment to thank you for the back-and-forth on this. It's helped me to clarify my thinking on the matter, and given me some good tips on how to use the privacy settings.

**Comment by fisharebest** [comment]
>  If I want to keep specific people's names private (e.g. some people are sensitive about having any details about their children made public) while achieving the general goal of "all names public, some additional information public for dead people", I don't think your workaround will work.

Yup - there is support for this, and it is described in the documentation that I linked.

Adding a RESN tag (Restriction) to a record or fact overrides any logic or processing.

So, adding`2 RESN privacy` to a `1 NAME` record will make that name private - even if you set the logic for "Show private names: show to visitors".


```
1 NAME Anthony /Burgess/
2 RESN privacy
2 NOTE Anthony asked that his name not be shown in the tree
```

Remember, webtrees privacy logic only applies to records that do not have an explicity RESN tag.

> Stepping back from specific use cases, I think the fact that the living (+ recently dead) / dead dichotomy already exists in the privacy settings (and in fact the two categories have different default settings!) is a sign that this is a natural way to delineate individuals for privacy purposes.

If an individual is living their record is private - so it doesn't really make sense to add a rule for "Birth records for living individuals" - the record is private, and the birth record is already hidden.  You cannot make it "more hidden".

The only exception to the "living individuals are completely private" rule are the two options:

* Show private relationships
* Show private names

The latter only applies to names without a RESN.

**Comment by fisharebest** [comment]
I think I have addressed all the concerns in this issue, so will close it.

Please feel free to open a new issue if you have any new/related concerns.
