### ISSUE TITLE
2.1: Private Persons not shown on Family View 

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4584]
I'm not sure if that's correct:

Show private relationships is set to "Show to visitors"

e.g. at https://wbt.warius.info/tree/Warius/individual/I13/Ernst-Gustav-Warias#

in family navigator one sees his 2nd marriages with wife and children as "private" and himself with his name
![grafik](https://user-images.githubusercontent.com/16499744/197157153-528010a7-4f14-499d-9dc1-4050382376c1.png)
When you call FAM, you only see "This family does not exist or you do not have permission to view it." 
Shouldn't this display also be like in the family navigator?

**Comment by fisharebest** [comment]
Originally, we did display the family page for these records.

It had a message saying "All the details of this family are private".

All this information is available on individual pages, so this page adds nothing new.
It is also a little unfriendly.

So, it was decided to remove it.

**Comment by FrankWarius** [comment]
this case is quite different

husband: visible 
wife: private 
children: some private, some visible

so some details can shown, including wedding details

**Comment by fisharebest** [comment]
> so some details can shown, including wedding details

No. If one family member is private, we hide ALL family facts and events.

**Comment by FrankWarius** [comment]
Vou are right, especially since we create a FAM event with reference to the church register entry for illegitimate birth of a child.

how about:
If one of the family members is private, we show the family view with all members (private or visible) but without any event.

**Comment by FrankWarius** [comment]
> We already show this family structure on the family-navigator and the families-tab on the individual page. 

This was the origin of the discussion: inconsistency between family navigator and family view

> Search engines will see thousands of identical pages showing just "Private + private. Private. Private. Private."

Maybe I wasn't precise enough: If only at least **one** family member is not private we should  show the family view but without events! All private and all visible remains unchanged.
This doesn't result in "thousands" of identical views as that one member makes it unique.

>  I think the users will be very disappointed. The page will show them less information than the previous page.

The people who contribute information about their next of kin to my website are disappointed that they cannot see their family since they are alive themselves

**Comment by fisharebest** [comment]
Here is a page with private family members.

<img width="989" alt="Screenshot 2022-11-02 at 21 09 50" src="https://user-images.githubusercontent.com/2306088/199603221-7d2c02fc-b457-4078-91e7-186481a8f3e3.png">

The title of the family "Max MUSTERMANN with Private" is not clickable - because the family is private.

You want the link to be clickable, were we can see a family page like this:

<img width="1139" alt="Screenshot 2022-11-02 at 21 10 37" src="https://user-images.githubusercontent.com/2306088/199603418-a6d8fe7b-ab61-49bc-8edc-4f47645bc467.png">

But the family page will contain less information than the original page.
I do not understand why you think this is useful....

**Comment by FrankWarius** [comment]
-  Your example is constructed. This is a practical example (more people visible)

![Screenshot 2022-11-03 083039](https://user-images.githubusercontent.com/16499744/199667496-b0a7e3d7-6291-4b9a-bc60-812c8c479e0c.png)

- A normal use case is to click up to Great Grandfather and then down through Cousins. Why should this end on an error page and not on a FAM view as a "dead end"
