### ISSUE TITLE
2 FONE // is added if editing and saving an individual's name with "Edit with all GEDCOM tags"

### ISSUE THREAD

**Issue by Jefferson49** [fisharebest/webtrees#4588]
observed with webtrees 2.1.7

If editing the data of an individual's name and choosing the "Edit with all GEDCOM tags" option, webtrees will save an empty phonetic name, even if no entry was made for the phonetic name. 

Example for resulting GEDCOM:
1 NAME Wilhelm Theodor Bernhard /Dobber/
2 TYPE BIRTH
2 SOUR @S8808@
3 PAGE page 336
2 FONE //

See also attached screenshot

![2 FONE](https://user-images.githubusercontent.com/81484983/199833842-bd19d488-6da0-4263-bd7a-3972f8575a51.JPG)

**Comment by fisharebest** [comment]
Already fixed: See #4539
