### ISSUE TITLE
Additional data if editing FAM:NCHI

### ISSUE THREAD

**Issue by Jefferson49** [fisharebest/webtrees#4589]
Observed with webtrees 2.1.7

If editing the "Number of children" for a family (see screenshot), webtrees 2.1.7 allows me to enter additional data for a date, note, media object, or source citation. The resulting GEDCOM might look like this:
```
1 NCHI 2
2 SOUR @S8810@
```

If validating the resulting GEDCOM file with Gedcom Validator, I get an error message that it is not allowed to use 2 SOUR under 1 NCHI

From the GEDCOM 5.5.1 spec, it seems that FAM:NCHI does not allow a sub structure.

![FAM-NCHI](https://user-images.githubusercontent.com/81484983/199842304-be479461-6a4e-494f-95a0-f603086fd474.JPG)

**Comment by fisharebest** [comment]
Now, you must enable this option in: Control panel -> GEDCOM tags -> GEDCOM 7
