### ISSUE TITLE
 improving check for errors

### ISSUE THREAD

**Issue by Bogiegit** [fisharebest/webtrees#4593]
When using 'Check for errors' I suggest to add some more validations.

Date entries should be valid in terms of
- month names according to GEDCOM spec. pages 52/53 (i.e. MAY, OCT, VEND, BRUM, TSH, CSH)
- approximated dates according to GEDCOM spec. page 45 (i.e. ABT, AFT, BET, CAL, INT)
- date values (i.e. switching days, short and long forms)
- no additional text allowed

Tags BIRT, DEAT and MARR should be checked in terms of
- lines followed by any subordinate tags must not use value 'Y'
- lines without any subordinate tags must use value 'Y'

Tag 'CAUS' may only appear 1 times under tag 'DEAT'
Tag 'DATE' may only appear 1 times under tag 'BIRT', 'DEAT', 'MARR'
Tag 'NICK' may only appear 1 times under tag 'NAME'
Tag 'PLAC' may only appear 1 times under tag 'OCCU'
Tag 'TYPE' may only appear 1 times under tag 'EVEN', 'MARR', 'NAME'

The given examples may be not complete.

**Comment by hartenthaler** [comment]
Regarding "DEAT Y" there was a discussion in the GEDCOM-L group some time ago. The consent was - as I remember - that the GEDCOM standard 5.5.1 says: "Y" if there is no date and no location. So it should be "Y" if there is only a source or a media object under DEAT. So the following three records are all correct:

> 1 DEAT Y

> 1 DEAT Y
> 2 SOUR @S1@

> 1 DEAT
> 2 DATE 1 JAN 1900

**Comment by fisharebest** [comment]
This is three separate issues:

* validation of `DATE` elements
* validation of minimum/maximum number of subtags
* validation of `Y`

It is difficult to manage issues that contain lots of smaller issues.

**Comment by Bogiegit** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}Thank you, Greg! Looking forward to that feature.
Regards,
 
Bogie

https://ourtree.thespiegels.com

Greg Roach schrieb am 25.11.2022 12:53 (GMT +01:00):

This is three separate issues:

validation of DATE elements
validation of minimum/maximum number of subtags
validation of Y

It is difficult to manage issues that contain lots of smaller issues.

**Comment by Bogiegit** [comment]
validation issues have been seperated in to #4620, #4621, #4622
