### ISSUE TITLE
Incorrect duplicate in 2.1.7

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#4603]
Find duplicates showed 
George Erson Giffin (P3383) — P3383 — P3385 — Merge
but P3385's name is John Gossett

Looked at the GEDCOM for both and didn't see any errors.

**Comment by fisharebest** [comment]
Are you still able to reproduce this?  If yes, can we look in your database.

What entries do you have in the tables `wt_name` and `wt_dates` for these two individuals.

**Comment by WGroleau** [comment]
The one reported does not happen today.  I don't recall changing anything on either of them.  Today I have
```
Mollie Greer (P3403) — P3403 — P3411 — P3412
Mollie Greer (P3403) — P3403 — P3412 — Merge

```
details attached.
I see that P3403 does not have the complete married name.  But that would not have been the case with P3383 & P3385 .
I can tell that these records were not created by import because the sub records are not in my preferred order and FONE is there.  I also know that I have not edited raw GEDCOM on them or my perfectionism would have "corrected" those two "flaws".
[ug_dates.csv](https://github.com/fisharebest/webtrees/files/10042963/ug_dates.csv)
[HHH.ged.notes.txt](https://github.com/fisharebest/webtrees/files/10042965/HHH.ged.notes.txt)
[ug_name.csv](https://github.com/fisharebest/webtrees/files/10042966/ug_name.csv)

**Comment by fisharebest** [comment]
They both have the same full name - `@P.N. Davidson` - (@P.N. is an internal code for unknown given name).

They both have the same death date - `1955`.

These two criteria are how we determine duplicates.

**Comment by WGroleau** [comment]
I would suggest also looking at FAMS and BIRT if present.
I don't know why the first two happened once and then didn't when neither of them were changed.  
They have different names but the same BIRT:DATE and no DEAT:DATE
But since it didn't repeat, mystery.

**Comment by fisharebest** [comment]
> I would suggest also looking at FAMS and BIRT if present.

It is a common mistake to add the same fact (e.g. `DEAT`) to both a father and a son with the same name.

So I feel it is useful to include these in the check.

**Comment by fisharebest** [comment]
As far as I can tell, the code is working as designed.

We don't find *duplicates*.  We find *potential* duplicates.  It is for the user to determine if the individuals are the same.

All the examples I looked at contained two individuals with the same name and the same birth/baptism/death/burial event on the same date.

If you want to discuss a better algorithm, then perhaps start a thread on the forum.
