### ISSUE TITLE
Error message on GEDCOM import if media files cannot be read

### ISSUE THREAD

**Issue by mathiasbockwoldt** [fisharebest/webtrees#4604]
I tried for some time to import a GEDCOM file with connected media.
I uploaded the media to `data/media` and let webtrees modify the paths in the ged file, but to no avail. Finally, I got the idea of updating the file permissions. And then it worked.
It would be great if the importer could issue a warning for files that cannot be read instead of silently ignoring such problems. This would make the import much more smooth.

**Comment by fisharebest** [comment]
The GEDCOM importer does not read the media files.  So, I do not understand this error.

Did the error occur during the import?  After the import?
What error message did you see?

**Comment by mathiasbockwoldt** [comment]
Ah, sorry, I wasn't clear on this! There is no error message at all. But when I install webtrees on my server and upload media files to `data/media` and import a gedcom file that has links to the media files, I can still get red 404 messages instead of pictures. This can be due to wrong permissions.

For me, it would have been great, if webtrees would have checked if it can find the linked media and if they were readable. This is not done now, but would help people transitioning from other software a lot, I think.

So, there is no error message, but I think it would be good if there were an error message.

**Comment by fisharebest** [comment]
When we can't show an image, we show a "replacement image" - the number in a red square.

These numbers are HTTP status codes.  For most errors, we include an error message in the HTTP headers.

But not for `404` (not found) errors.  It was thought that these error messages might contain sensitive information such as filenames.

However, this has already been changed, and the next release **will** include error messages in `404` errors as well.
