### ISSUE TITLE
2.1 Incomplete link / URL leads to inconsistent redirect result

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4609]
using an incomplete URL leads to different results

| http status | link / URL | resulting page | result |
| ------------- | ------------- | ------------- | ---------- |
| 200 | https://dev.webtrees.net/demo-dev/tree/demo/individual/I10089/King-George-VI | Indi-Page I10089 | ok |
| 301 / 200  | https://dev.webtrees.net/demo-dev/tree/demo/individual/I10089 | Indi-Page I10089 | ok |
| **302 / 302 / 200** | https://dev.webtrees.net/demo-dev/tree/demo/individual/I10089/ | **HomePage** | **wrong** |
| 301 / 200 | https://dev.webtrees.net/demo-dev/tree/demo/individual/I10089/QEII | Indi-Page I10089 | ok |

an incomplete / wrong link leads to at least one redirect

**Comment by fisharebest** [comment]
The [URL matching library](https://github.com/auraphp/Aura.Router) does not allow parts of the URL to be empty.

So, the URL is not recognised.  Unrecognised URLs are re-directed to the home page.

I will check to see if it is possible to change this behaviour.
