### ISSUE TITLE
Date qualifications

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#461]
Greg, I'm stuck here.

In the Fancy Treeview module I need to determine if a date has a date qualification, because the output text depends on it.

I only need to set a prefix if the date has no date qualifications but  I can't access qual1 and qual2 in the date object anymore.

Fatal error: Cannot access private property Fisharebest\Webtrees\Date::$qual1 in C:\xampp\htdocs\webtrees_build\modules_v3\fancy_treeview\fancytreeview.php on line 900

Do you have a solution for this?

**Comment by fisharebest** [comment]
If possible, I would prefer to keep the implementation details of the Date objects private.

I haven't used this module, but I guess you are trying to create a sentence like this:

> [Person] was born on [date] in [place]

I presume you start with a fact.  e.g. `$fact = $individual->getFirstFact('BIRT')`.

You can access the original GEDCOM version of the date with `$gedcom_date = $fact->getAttribute('DATE')`.

You can test it with `if (preg_match('/^(ABT|BET|FROM|...)/', $gedcom_date) {}`

**Comment by JustCarmen** [comment]
Thanks for the explanation. I got it working.
