### ISSUE TITLE
Interactive tree, webtrees 2.1.8

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#4615]
The Interactive tree does not expand when dragging in fullscreen

**Comment by mpwt** [comment]
It seems that it is the same behavior with fullscreen on maps. It does not work.

**Comment by ddrury** [comment]
For use with Safari see https://caniuse.com/fullscreen. It seems the you need Safari ver 16.1 released on Oct 24 2022 and even then a note says "Partial support refers to supporting only iPad, not iPhone. Shows an overlay button which can not be disabled"

**Comment by ddrury** [comment]
For the interactive tree the problem is in resources\js\treeview\getSize (about line 142), changing the trigger element to .tv_out's parent (.wt-tab-tree) allows the resizing to work but only half the screen is filled - the vertical resize button can be used to drag down to fill the fullscreen (not very satisfactory) and I haven't found a proper solution. 

Over to you Greg (although I'll keep looking)

**Comment by HRN65** [comment]
Fullscreen or not, I find the Interactive tree difficult to navigate, as it expands "endlessly in all directins".
Would it be possible to add a zoom functin, like in magicsunday's pedigree-, descendants- and fancharts? These charts also have the option to export to png, which is very nice.
I guess adding a zoom function would require the whole tree to be loaded initially? Any thoughts?

magicsunday's charts used on my [site](https://visitusinmaputo.com/webtree/tree/familie/webtrees-descendants-chart/I1843?generations=8&layout=down)

**Comment by huhwt** [comment]
@HRN65
The two tools rely on different techniques ... "Interactive Treeview" uses the good old tables under the hood, the "Magic Sunday" modules work with SVG elements. For tables there is simply no zoom option.
Maybe an alternative would be https://github.com/huhwt/huhwt-xtv, a Treeview variant which allows to selectively show and hide single branches ... I would be thrilled if you would give it a try and send me some feedback.

**Comment by photon-flip** [comment]
The original issue raised here is: "The Interactive tree does not expand when dragging in fullscreen".
There is a separate issue of links not working on mobile devices.
The first issue relates to the new fullscreen functionality in 2.1.8
The mobile issue is much older. 
I'd like to suggest that they be treated separately or at least please indicate which one is being commented on.
