### ISSUE TITLE
Journal at "My page" cannot be updated

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#4617]
When I try to save an updated journal on "my page" (Add/edit a journal/news entry), there is an error message
`The parameter “subject” is missing.`

But the subject is there and was not changed.

**Comment by hartenthaler** [comment]
see [Forum](https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/37478-journal-entry-add-edit#95705)

**Comment by fisharebest** [comment]
This was fixed in 6623e4dbe95e0812a13790cb48942b4a088a1bcc
