### ISSUE TITLE
SyntaxError 2.1.8

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#4619]
When trying to add a shared note to an event, I get : SyntaxError: Unexpected token '<', "
Tested on Demo Current Release with same result.

**Comment by fisharebest** [comment]
Blast.  Didn't see this until after I created the 2.1.9 release.

We actually need to add `''` to the list of allowable values - not remove the check.

It is currently requiring a privacy restriction, as you cannot leave it blank.

I'll create a new release tomorrow.
