### ISSUE TITLE
Update from 2.1.8 to 2.1.9 does not work

### ISSUE THREAD

**Issue by sgrossberndt** [fisharebest/webtrees#4624]
After running the upgrade wizard /webtrees/index.php?route=%2Fwebtrees%2Fadmin%2Fupgrade&continue=1 which says the process worked without issues:
![Screenshot 2022-12-01 at 13-30-54 Aktualisierungsassistent](https://user-images.githubusercontent.com/3786510/205053738-8c519f63-494c-42ca-9b15-61cda7a5894f.png)
when I click on "Weiter"/"Continue" I am redirected back to the management page which says I have 2.1.8 and offers the 2.1.9 update again:
![Screenshot 2022-12-01 at 13-33-37 Verwaltung](https://user-images.githubusercontent.com/3786510/205054197-2386450b-d805-401f-be0f-5c3fff4a1e99.png)

**Comment by fisharebest** [comment]
This has already been reported and fixed.

Unfortunately, you will need to replace one file manually before you can use the online upgrade.

See https://webtrees.net/upgrade/

**Comment by fisharebest** [comment]
Also, I have temporarily withdrawn the 2.1.9 release.  I do not want more people installing it.

I will create 2.1.10 soon.

**Comment by sgrossberndt** [comment]
Great, thanks for the fast reply. I will wait for the 2.1.10 update then and replace the mentioned file before updating.
