### ISSUE TITLE
Media files doubled!

### ISSUE THREAD

**Issue by enes73** [fisharebest/webtrees#4625]
When I import GEDCOM file, I suddenly get DOUBLED media files?!

![image](https://user-images.githubusercontent.com/6985394/205075433-db70d92e-0b3a-4f81-8b6a-402d24a6e5a2.png)

When I open RAW GEDCOM, I see doubled media object.

![image](https://user-images.githubusercontent.com/6985394/205075914-084f312d-b708-4fc6-ac04-9351329d4747.png)

In exported GEDCOM file, I don't have doubled gedcom tag... it's OK....

Maybe problem with latest versions???

**Comment by fisharebest** [comment]
When you imported the GEDCOM file, did you select the "Keep media objects" link.

This will cause your media objects to be doubled.

This option has a very specific use.  It does not apply to you.

**Comment by enes73** [comment]
Yes, this option is been preselected.... I inport file again and I don't have a problem with doubled media files!!!

THANKS for quick reply!!!

Issue resolveed - not exist :) Close...
