### ISSUE TITLE
Version 2.1.9: Error Language

### ISSUE THREAD

**Issue by heiler** [fisharebest/webtrees#4627]
Same as Issue #4618. Sorry, but again I have a lot of entries in the log from stupid bots. The access is f. e.:
GET /webtrees/tree/heiler/family-list?surname=schr%C3%B6ders HTTP/1.1.

**Comment by fisharebest** [comment]
Managed to add some debug to one of these requests.  Here are the HTTP headers.

```
array (
  'Host' => array ( 0 => 'fisharebest.webtrees.net', 1 => 'fisharebest.webtrees.net', ),
  'Connection' => array ( 0 => 'Keep-Alive', ), 'Accept-Encoding' => array ( 0 => 'br,gzip', ),
  'Accept-Language' => array ( 0 => 'en-US,en;q=0.5', ),
  'Accept' => array ( 0 => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', ),
  'User-Agent' => array ( 0 => 'CCBot/2.0 (https://commoncrawl.org/faq/)', ),
  'Content-Length' => array ( 0 => '', ),
  'Content-Type' => array ( 0 => '', ),
)
```

Nothing obviously wrong...

**Comment by fisharebest** [comment]
Using some more debug, I have found the cause of this - but have been unable to set up a test-case to reproduce it.

1) Web-crawler selects a language using the HTTP `Accept-Language` header - but this this language is not currently enabled.  This is allowed.  Visitors can use any language.
2) Web-crawler visits a page that needs language features.  (All these pages have meta tags to tell robots not to follow or index).
3) The internationalisation code doesn't allow disabled languages to be initialised - hence the error.

Simple fix - but frustrating that I cannot set up a local test case.

**Comment by heiler** [comment]
I updated the I18N.php, let's see what happens.
