### ISSUE TITLE
Control panel / All modules / Menus is not updated after access level is changed in modal 

### ISSUE THREAD

**Issue by Jefferson49** [fisharebest/webtrees#4630]
observed with webtrees 2.1.9

If the access level for menu items is changed for a module in the control panel (Control panel / All modules / Menus), the page is not updated after closing the modal. Therefore, the newly chosen value for the access level is not visible until the "save" button is pressed for the overall Menue page.

I do not know, if there are restrictions when using modals and how difficult it is to implement. However, if possible, it would be more intuitive to see the change after closing the modal.

![update Access level](https://user-images.githubusercontent.com/81484983/205361385-363d138d-d539-4dcf-a916-60d65288689f.JPG)

**Comment by fisharebest** [comment]
I think this is the same issue as #2932
