### ISSUE TITLE
Agressive Bot

### ISSUE THREAD

**Issue by LarsRabe** [fisharebest/webtrees#4634]
serpstatbot is crawling my site with a massive load an therefore slowing it down. Can you please add it to the badbotblocker?

thx

**Comment by fisharebest** [comment]
What is the exact user-agent string?  SerpStatBot, SertstatBot, Serpstatbot, etc.?  Upper/lower case is important

**Comment by fisharebest** [comment]
Fixed in f4b154857f4c2ada57a839292c889a5c376c1625
