### ISSUE TITLE
Search results and privacy

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#464]
Situation: masquerade as a user who is a member in one tree (tree 1) and just has visitor rights in a second tree (tree 2). In tree 1 he has the right to see living persons in his area, in tree 2 he has not.

Search a living person from tree 1 that only exists in tree 2. The person will be listed in the search results table. Clicking on the person's name in the table however gives a privacy message. So webtrees knows this member may not see this person, but this person is listed with all details in the search results table.

When entering tree 2 and do a search for the same person, the user will not find this person which is correct.

So searching for a private person from another tree gives false results.

I hope I made the situation clear. If not please ask.

**Comment by fisharebest** [comment]
Is this 1.6.2 or 1.7.0?

This has been a problem for 10 years ;-)  The privacy for one tree was used for all trees.

I thought it was finally fixed in 1.7.0.

Does your user have permission to see the *names* of living people in tree 2?

**Comment by JustCarmen** [comment]
Greg, I thought this was what your trying to fix with the recent commit 8d6ded4dd6f9668b0671275231e78d609e36f8f1. That's why I mentioned it. I know it is a long lasting problem.

But to answer your question. The user doesn't have the permission to see the names of living people in tree 2. The option 'Show names of private individuals' is set to 'show to managers'.

I hope you will able to fix this privacy leak.

**Comment by fisharebest** [comment]
I was a bit ahead of myself.  I had made all the necessary changes to trees - but not to individuals.

I now have it working.  I need to tidy up before I commit it.

**Comment by fisharebest** [comment]
It should be working now.

**Comment by JustCarmen** [comment]
No it isn't. Just tested the same situation as described above and I'm getting the same results.

But I also don't see a commit that would have fixed this, or am I missing something?

**Comment by fisharebest** [comment]
> But I also don't see a commit that would have fixed this, or am I missing something?

The commit was called "Remove constants, to improve multi-tree handling".  I think I made it to the wrong branch, and then deleted the branch.  Let me see if I can recover it....

**Comment by fisharebest** [comment]
`git reflog` and `git cherry-pick` are your friends ;-)

**Comment by JustCarmen** [comment]
Thats why I love git :).

But I have tested it again and now it works. I tried it with different users and different roles and everything looks fine now. No more private records are shown in the search results. Thanks a lot!
