### ISSUE TITLE
HTTP-Header 'REDIRECT_GEOIP_...': How to get information about it?

### ISSUE THREAD

**Issue by ungeahnt** [fisharebest/webtrees#4644]
according to 

_Originally posted by @fisharebest in https://github.com/fisharebest/webtrees/issues/4637#issuecomment-1336987659_

Can someone tell me how to display the values of the HTTP header? I have tried with the Firefox developer tools, but I can't find any information about 'REDIRECT_GEOIP'.

**Comment by fisharebest** [comment]
Control panel -> Server information.

Bottom of the page will show HTTP headers.

**Comment by ungeahnt** [comment]
Thanks a lot Greg.

Server information shows me:

<html><body>


REDIRECT_GEOIP_CONTINENT_CODE | EU
-- | --
REDIRECT_GEOIP_COUNTRY_CODE | DE
REDIRECT_GEOIP_COUNTRY_NAME | Germany
REDIRECT_GEOIP_REGION | 13
REDIRECT_GEOIP_REGION_NAME | Sachsen
REDIRECT_GEOIP_CITY |  
REDIRECT_GEOIP_DMA_CODE | 0
REDIRECT_GEOIP_METRO_CODE | 0
REDIRECT_GEOIP_AREA_CODE | 0
REDIRECT_GEOIP_LATITUDE | 51.200001
REDIRECT_GEOIP_LONGITUDE | 12.383300
REDIRECT_GEOIP_POSTAL_CODE | 04564


</body>
</html>


`REDIRECT_GEOIP_CITY` is empty. Is it possible that the string 'Böhlen' is already filtered (because it is invalid non-ASCII) and I do not see the string that was actually transmitted?

If so, is it possible to display the raw data somehow? 

My hoster would like to have more detailed information.

And once again a big thank you for your tireless efforts. There are not many software projects that are kept up to date at this level!

**Comment by fisharebest** [comment]
> If so, is it possible to display the raw data somehow?

Create a script (e.g. `info.php`) containing the following:

```
<?php var_dump($_SERVER);
```

**Comment by ungeahnt** [comment]
Thanks! 

The var_dump shows me `["GEOIP_CITY"]=> string(6) "B�hlen" ` 
It looks like non-ASCII characters are being sent ;). 

But there is no `REDIRECT_GEOIP_CITY` listed. I would like to know more about this `REDIRECT_GEOIP.... ` but I can't find any information about it anywhere. It also doesn't seem to be a fix PHP function/variable. 
Do you know where I can find information about 'REDIRECT_GEOIP_...'?

I am still waiting for feedback from my hoster and will leave the issue open until then.

**Comment by fisharebest** [comment]
Your original error messages showed `REDIRECT_GEOIP_...`.
Long strings are truncated in error messages.

I **guessed** that this was `REDIRECT_GEOIP_CITY`.  But it could be anything.  `STATE`, `REGION`, PLANET`, etc.

> But there is no REDIRECT_GEOIP_CITY listed

I see it in your post.  It is empty.  But it is there.

**Comment by ungeahnt** [comment]
Sorry, I did not make myself clear. 

> Do you know where I can find information about 'REDIRECT_GEOIP_...'?

I asked only for my personal understanding.  I don't know the difference between `GEOIP_...` and `REDIRECT_GEOIP_...` and I can't find any literature/info about it. The question was of a general nature and not directly related to wt.

btw: 
> I guessed that this was REDIRECT_GEOIP_CITY.

Don't worry, as always you were very accurate and never mentioned CITY before. It was me who guessed. ;)

**Comment by fisharebest** [comment]
It will be a plugin/module for your webserver - apache/nginx/iis.

It may be created by your webhost.

**Comment by ungeahnt** [comment]
For completeness only: my hoster didn't give any feedback, but apparently changed something. The GEOIPs have been sent without umlauts for a few days now.
