### ISSUE TITLE
V2.1.12 - Control panel / Tree / Privacy restrictions: New entries cannot be saved

### ISSUE THREAD

**Issue by ungeahnt** [fisharebest/webtrees#4645]
Control panel / Manage family trees / Privacy restrictions: 

It's possible to add a new entry but you can't save it. When you click on 'save' nothing happens.

**Comment by fisharebest** [comment]
I think the existing bug is harmless, so try reverting the fix.

**Comment by motherboard1999** [comment]
Thank you so much! With this workaround I can set the restriction.
