### ISSUE TITLE
[Bug] List Families - No result for names with ü/ä/ö - Redirects url to ue/ae/oe

### ISSUE THREAD

**Issue by Pilzinsel64** [fisharebest/webtrees#4647]
When navigating to "Lists"->"Families", click a letter does list all names correctly.

When you now click on a name it should list some persons. As soon as a name has ü/ä/ö in the name, the link url (bottom left in picture) points to a not working URL.
![grafik](https://user-images.githubusercontent.com/23138465/205876678-a06853e7-6b6c-411b-854f-1c4265505f1d.png)

This is the result when clicking on this name with "ü":
![grafik](https://user-images.githubusercontent.com/23138465/205876749-55a6ccc5-a5c6-48ee-882a-7cf16ece5ba7.png)

When you change the "UE" in the url to "Ü", then it shows the correct results.

The person can still be found fine via the search. It's just this the "List Families" feature as it seems.

**Comment by ungeahnt** [comment]
It looks like that the URL depends on the selected language:

https://proavitus.de/tree/proavitus/family-list?alpha=B#
When I select
1) 'British English' the URL is:  `https://proavitus.de/tree/proavitus/family-list?surname=B%C3%9CHLER`   (=`BÜHLER`) 
2) 'German' the URL is: `https://proavitus.de/tree/proavitus/family-list?surname=BUEHLER` (=`BUEHLER`)

When "English" is selected I see the families. With "German" not.

**Comment by Pilzinsel64** [comment]
Very strange, it only affects the German language. I've tested it on my instance too, it's the same.

Additional infos:
- Webtrees v2.1.12
- PHP 8.0.26
- Apache 2.4.54-1
- Ubuntu Server 22.04 LTS

**Comment by fisharebest** [comment]
There is some recent code which helps to match equivalent letters in some languages.  For example, `Ü` = `UE` in German.

I guess there is a bug in it somewhere...

**Comment by mpwt** [comment]
Can [this commit](https://github.com/fisharebest/webtrees/commit/dff81305056ece421b7a0cf2d2cfc5e08717a262) have caused the change?

**Comment by mpwt** [comment]
Hi Greg, will there be a backport of this fix for v2.1? With v2.1.12 the search and display of names with german umlauts as described here does not work correctly.

**Comment by fisharebest** [comment]
There already is!

It is included in 2.1.13

**Comment by mpwt** [comment]
Are you sure? I can't find the fix in the change log.

**Comment by fisharebest** [comment]
Development is on the `main` (`2.2`) branch.

Where possible, fixes are back-ported to the `2.1` branch.

I remember merging this commit into `2.1`.
I'll look at the logs...

**Comment by fisharebest** [comment]
I see the history in one of my console windows.

But I think I may have reset it in a different window.

I've merged it now.  It will be in the next release.

**Comment by Pilzinsel64** [comment]
Thank you very much for your work! Will update the customers site soon.

**Comment by Pilzinsel64** [comment]
Alright, now with v2.1.14 it's fixed, thank you!
