### ISSUE TITLE
Endless upgrade loop  from 2.1.8 to 2.1.12

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#4649]
In the admin screen it shows me that 2.1.8 is installed and 2.1.12 is available.
When I perform the update to 2.1.12 everything runs without errors, but it still shows the update as available and 2.1.8 as installed version.
I can perform the update again, without error, but without any chance.

**Comment by fisharebest** [comment]
You need to patch one of the files.  See https://webtrees.net/upgrade/ for more info.
