### ISSUE TITLE
Interactive tree query unused code

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4652]
I have a feeling that function `app\Module\InteractiveTreeModule.::getChartAction()` is never used - at least the html in resources\views\modules\\interactive-tree\page.phtml never seems to appear anywhere.

As a simple test I've commented out `app\Module\InteractiveTreeModule.::getChartAction()` and no errors are generated and the chart displays OK

**Comment by fisharebest** [comment]
For modules, functions with the name `getXxxxAction` and `postXxxxAction` are called in response to URLs containing:
module=ModuleName&action=Xxxx`

For the interactive tree, this is used to load the chart on the full-screen chart, not the tab-version.

**Comment by fisharebest** [comment]
<img width="777" alt="Screenshot 2022-12-07 at 18 02 52" src="https://user-images.githubusercontent.com/2306088/206260770-ffa264f1-f0df-4aa5-a718-bf649a7317b1.png">
