### ISSUE TITLE
2.0.12 - Collapsing and unfolding citation details

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#4654]
When collapsing and unfolding citation details from, say, BIRT, this also works into the events CHR/CREM/BURI.

But not for DEAT, which works separately.

Tested by adding an unlinked individual on the [live demo](https://dev.webtrees.net/demo-dev/tree/demo/add-unlinked-individual).

Is that intentional, or is it a bug?

**Comment by fisharebest** [comment]
Not sure what you are seeing.  Expand/collapse of `DEAT:SOUR` is working for me.

<img width="510" alt="Screenshot 2022-12-13 at 13 46 44" src="https://user-images.githubusercontent.com/2306088/207343572-6a1e39db-967c-4349-b4b4-14c1a124fccb.png">
<img width="635" alt="Screenshot 2022-12-13 at 13 46 53" src="https://user-images.githubusercontent.com/2306088/207343608-6bd5e32a-1a11-4803-878c-da5cc814a4d7.png">

**Comment by ungeahnt** [comment]
> When collapsing and unfolding citation details from, say, BIRT, this also works into the events CHR/CREM/BURI.
> But not for DEAT, which works separately.

This effect occurs also with CHR/CREM/BURI.

You have to enter text in the TEXT or NOTE field and when you save, afterwards the folding functionality is gone.

**Comment by TheDutchJewel** [comment]
> Expand/collapse of `DEAT:SOUR` is working for me.

For me too, that's not the problem. 

> When collapsing and unfolding citation details from, say, BIRT, this also works into the events CHR/CREM/BURI.
> 
> But not for DEAT, which works separately.

The question is why when collapsing and unfolding citation data from `BIRT`, for example, the source data also collapses and unfolds events `CHR`/`CREM`/`BURI`, but not on `DEAT` (which works separately).

**Comment by ric2016** [comment]
As noted in the original ticket, this is caused by multiple elements in the DOM with the same id attribute (e.g. 'collapse-15'), which should generally be avoided.

**Comment by ungeahnt** [comment]
Sorry, I misunderstood

**Comment by TheDutchJewel** [comment]
> Not sure what you are seeing. Expand/collapse of `DEAT:SOUR` is working for me.
> 
> <img alt="Screenshot 2022-12-13 at 13 46 44" width="510" src="https://user-images.githubusercontent.com/2306088/207343572-6a1e39db-967c-4349-b4b4-14c1a124fccb.png">

**Before** unfolding citation data from `BIRT`:
![afbeelding](https://user-images.githubusercontent.com/46184729/207850709-8f70fa44-9105-453b-9735-2a97f01411c8.png)

**After** unfolding citation data from `BIRT`:
![afbeelding](https://user-images.githubusercontent.com/46184729/207850895-874684f2-a45f-4e3a-9f0a-691353de7f2c.png)

**Comment by ric2016** [comment]
Is this still unclear? (because it still has the 'cannot reproduce' label)
As noted above, the cause are multiple elements with the same id attribute in the DOM.

**Comment by fisharebest** [comment]
> Is this still unclear?

Yes.

I add a new individual.

I open the panels for birth and death.

Both panels have a (collapsed) source-citation.

I click to expand BIRT:SOUR. It expands.
I click to expand DEAT:SOUR.  It expands.
I click to collapse BIRT:SOUR.  It collapses.
I click to collapse DEAT:SOUR.  It collapses.

**Comment by fisharebest** [comment]
> As noted above, the cause are multiple elements with the same id attribute in the DOM.

I don't see any duplicates.

All the IDs (`#collapse-XXX`) are unique.

**Comment by ric2016** [comment]
To summarize [this comment](https://github.com/fisharebest/webtrees/issues/4654#issuecomment-1352941544):

Create a new individual on the demo server.
https://dev.webtrees.net/demo-stable/index.php?route=%2Fdemo-stable%2Ftree%2Fdemo%2Fadd-child-to-individual%2Fi1&sex=U

click to expand BIRT:SOUR. (one of its elements has "collapse-15") -> BURI:SOUR expands **_also_** - this is the effect this is about. (it probably also expands because one of its elements has the same "collapse-15")

**Comment by fisharebest** [comment]
Thanks.  It depends on which subtags are enabled.

I guess that I was "lucky", and the collapse elements in each fact/event had different positions in my data...

We are using `$key`.  We should probably be using `$id[$key]` .
