### ISSUE TITLE
2.0.12 - Family residence with input field for Residence - Why?

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#4655]
The normal `Residence` dialog does **not** have an input field for `Residence`:

![afbeelding](https://user-images.githubusercontent.com/46184729/206924749-e748b52b-320f-4bf3-802a-ebb5b81db91d.png)
See also the [live demo](https://dev.webtrees.net/demo-stable/index.php?route=%2Fdemo-stable%2Ftree%2Fdemo%2Fadd-fact%2Fi1%2FRESI).

 

But the `Family residence` dialog **does** have an input field for `Residence`.

![afbeelding](https://user-images.githubusercontent.com/46184729/206924913-6e99ad9d-992b-4e61-970d-ad4222f80015.png)

Why is that?

**Comment by photon-flip** [comment]
I notice that Family Residence has to be added manually in Control Panel and then "Edit with all Gedcom tags" to add Place etc. so it's quite a different dialogue set up than the general Facts tab edit.
In The Family - Family Residence Edit section the Input field is just a Title not the active link to the place. The link has to be added with the Place field. 
Too me, the Family Residence input for a title seems superfluous. If that was removed it would make the two dialogues consistent.
Either that or add a Residence title input field to the general Facts Residence dialogue.
 
Personally I don't find the current setup a problem. 

There could however be significance to the Gedcom tags. The general Facts Residence adds a RESI tag with no value but the Family edit dialogue can add the RESI with the Residence title - is one or both of these gedcom compliant?

I also note that the Family Residence appears in the General Facts once it's added to the Family Facts via control panel and data entered. - probably a good thing right?

**Comment by TheDutchJewel** [comment]
> Personally I don't find the current setup a problem.

I do think it is a problem because it's confusing. Since it's an input field for a residence, I entered a place name here and wondered why the autocomplete didn't work...

> I also note that the Family Residence appears in the General Facts once it's added to the Family Facts via control panel and data entered. - probably a good thing right?

That is indeed good, and that is also how it was in 2.0.x

**Comment by photon-flip** [comment]
> I do think it is a problem because it's confusing. Since it's an input field for a residence, I entered a place name here and wondered why the autocomplete didn't work...

Fair comment. 

I'd be interested to hear what the gedcom specialists say about RESI with and without a value added. In my mind Residence is a type of place but there is sure to be another way of looking at that. And that would determine what a fix for the dialogues would look like.

**Comment by hartenthaler** [comment]
INDI:RESI and FAM:RESI both do not have a payload following GEDCOM 5.5.1. So the family residence dialogue is wrong.

**Comment by photon-flip** [comment]
Thank you Hermann.
It looks like if a fix was to be made it would be to remove the input field for the Family Residence dialogue.

**Comment by fisharebest** [comment]
This is a mismatch between GEDCOM 7 (which allows a value) and GEDCOM 5.5.1 (which does not).

See also https://github.com/FamilySearch/GEDCOM/issues/33

`INDI:RESI` uses the GEDCOM 5.5.1 version
`INDI:RESI` uses the GEDCOM 7.0 version

**Comment by fisharebest** [comment]
As with other GEDCOM 7 features, this one is now opt-in.

The default behaviour is GEDCOM 5.5.1

**Comment by photon-flip** [comment]
> As with other GEDCOM 7 features, this one is now opt-in.
The default behaviour is GEDCOM 5.5.1

I'm sure this is a good fix for GEDCOM handling but I'm not sure it addresses the initial issue of the inconsistency between the two dialogues.

**Comment by photon-flip** [comment]
Hi Greg,

I looked through the code changes and couldn’t see where the Residence or Family residence input field was added or removed from either of the edit dialogues, assuming that would be the fix for the original issue.

I only know enough PHP to get me into trouble and glaze over at more than 10 lines of code so I may vey well have missed it.

 

Murray
