### ISSUE TITLE
Place hierarchy does not come to an end

### ISSUE THREAD

**Issue by webtrees-pesz** [fisharebest/webtrees#4662]
The list of locations shows 4550 entries. Any ideas for the behavior? 

Current version: 2.1.12 - Vesta modules disabled

Best regards, Peter

**Comment by fisharebest** [comment]
> The list of locations shows 4550 entries. Any ideas for the behavior?

You have 4550 top-level locations?

You can list them using: `SELECT * FROMwt_place_location WHERE parent_id IS NULL;`

Web-browsers are frequently slow when displaying large tables.

If find that this page is created (by webtrees) in one or two seconds - but it can take firefox a minute to format the page.

**Comment by webtrees-pesz** [comment]
Hello Greg,

the wt_place_location list contains 5035 entries, 44 of them are top-level locations with parent_id = NULL.
When I start the location hierarchy, after 30 minutes there is still no result.
I checked wt_place_location for a possible loop, but I didn't find any. Do you want to get the list by mail?

Best regards, Peter

**Comment by fisharebest** [comment]
Can you send a `mysqldump` of this table?

**Comment by fisharebest** [comment]
This data works OK for me.

Exactly what do you mean by "does not come to an end".

**Comment by webtrees-pesz** [comment]
The transaction runs more than 30 minutes without any result. I created an user for you and send username and password to your private mail.

**Comment by fisharebest** [comment]
Thanks for the login details.  It is always much easier to investigate a problem when you can see it.

The javascript error console in the browser showed a message saying "Missing API key for Bing Maps".

The "Bing maps" module was enabled - but no key was supplied.

Perhaps we could detect this and give a more helpful error message?
