### ISSUE TITLE
Census assistant bug

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4666]
At commit https://github.com/fisharebest/webtrees/commit/843973cef733731fddd2fd35e8767920a4d9824d Tested on demo using QE2

Select census and create a shared note using the census assistant.

Click the plus on the individual field without selecting a person to enter a blank line in the results table gives 400 bad request error. The parameter “xref” is missing.

**Comment by fisharebest** [comment]
Fixed in 5465075226
