### ISSUE TITLE
2.2 Dev Sqlsrv Session.php: SQLSTATE[42000] implicit conversion from nvarchar data type to varbinary(max) is not allowed

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4669]
SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Die implizite Konvertierung vom nvarchar-Datentyp in varbinary(max) ist nicht zulässig. Verwenden Sie die CONVERT-Funktion, um diese Abfrage auszuführen. (SQL: insert into [wt_session] ([session_id], [session_time], [user_id], [ip_address], [session_data]) values (r12cqpbo56d7cvssdj8t3mpbsd, 2022-12-16 22:47:04, 0, 127.0.0.1, initiated|b:1;))

0 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(720): Illuminate\Database\Connection->runQueryCallback('insert into [wt...', Array, Object(Closure))
1 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(546): Illuminate\Database\Connection->run('insert into [wt...', Array, Object(Closure))
2 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(498): Illuminate\Database\Connection->statement('insert into [wt...', Array)
3 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Query\Builder.php(3218): Illuminate\Database\Connection->insert('insert into [wt...', Array)
4 D:\GitRepos\fisharebest\webtrees\app\SessionDatabaseHandler.php(100): Illuminate\Database\Query\Builder->insert(Array)
5 [internal function]: Fisharebest\Webtrees\SessionDatabaseHandler->write('r12cqpbo56d7cvs...', 'initiated|b:1;')
6 D:\GitRepos\fisharebest\webtrees\app\Session.php(146): session_regenerate_id(false)

**Comment by FrankWarius** [comment]
After config.ini.php is successfully created we can't insert anything in the session table - so nothing works
relvant stack during setup:
#5 [internal function]: Fisharebest\Webtrees\SessionDatabaseHandler->write('df3mobeh37om9uk...', 'initiated|b:1;')
#6 D:\GitRepos\fisharebest\webtrees\app\Session.php(146): session_regenerate_id(false)
#7 D:\GitRepos\fisharebest\webtrees\app\Auth.php(189): Fisharebest\Webtrees\Session::regenerate()
#8 D:\GitRepos\fisharebest\webtrees\app\Http\RequestHandlers\SetupWizard.php(429): Fisharebest\Webtrees\Auth::login(Object(Fisharebest\Webtrees\User))
#9 D:\GitRepos\fisharebest\webtrees\app\Http\RequestHandlers\SetupWizard.php(357): Fisharebest\Webtrees\Http\RequestHandlers\SetupWizard->createConfigFile(Array)
#10 D:\GitRepos\fisharebest\webtrees\app\Http\RequestHandlers\SetupWizard.php(193): Fisharebest\Webtrees\Http\RequestHandlers\SetupWizard->step6Install(Array)

**Comment by FrankWarius** [comment]
if You call webtrees again You get 2 errors:
PDOException: SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Die implizite Konvertierung vom nvarchar-Datentyp in varbinary(max) ist nicht zulässig. Verwenden Sie die CONVERT-Funktion, um diese Abfrage auszuführen. in D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php:545 
Stack trace: 
#0 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(545): PDOStatement->execute() 
#1 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(753): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into [wt...', Array) 
#2 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(720): Illuminate\Database\Connection->runQueryCallback('insert into [wt...', Array, Object(Closure)) 
#3 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(546): Illuminate\Database\Connection->run('insert into [wt...', Array, Object(Closure)) 
#4 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(498): Illuminate\Database\Connection->statement('insert into [wt...', Array) 
#5 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Query\Builder.php(3218): Illuminate\Database\Connection->insert('insert into [wt...', Array) 
#6 D:\GitRepos\fisharebest\webtrees\app\SessionDatabaseHandler.php(100): Illuminate\Database\Query\Builder->insert(Array) 
#7 [internal function]: Fisharebest\Webtrees\SessionDatabaseHandler->write('2qffenk3q0fvcba...', 'initiated|b:1;_...') 
#8 D:\GitRepos\fisharebest\webtrees\app\Session.php(100): session_write_close() 
#9 D:\GitRepos\fisharebest\webtrees\app\Http\Middleware\UseSession.php(80): Fisharebest\Webtrees\Session::save()

and
#38 {main} Next Illuminate\Database\QueryException: 
SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Die implizite Konvertierung vom nvarchar-Datentyp in varbinary(max) ist nicht zulässig. Verwenden Sie die CONVERT-Funktion, um diese Abfrage auszuführen. (SQL: insert into [wt_session] ([session_id], [session_time], [user_id], [ip_address], [session_data]) values (2qffenk3q0fvcba1s23ctivvih, 2022-12-21 08:52:09, 0, 127.0.0.1, initiated|b:1;_GUEST_sessiontime|s:10:"1671612726";language|s:2:"de";theme|s:8:"webtrees";)) in D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php:760 Stack trace: 

#0 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(720): Illuminate\Database\Connection->runQueryCallback('insert into [wt...', Array, Object(Closure)) 
#1 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(546): Illuminate\Database\Connection->run('insert into [wt...', Array, Object(Closure)) 
#2 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(498): Illuminate\Database\Connection->statement('insert into [wt...', Array) 
#3 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Query\Builder.php(3218): Illuminate\Database\Connection->insert('insert into [wt...', Array) 
#4 D:\GitRepos\fisharebest\webtrees\app\SessionDatabaseHandler.php(100): Illuminate\Database\Query\Builder->insert(Array) 
#5 [internal function]: Fisharebest\Webtrees\SessionDatabaseHandler->write('2qffenk3q0fvcba...', 'initiated|b:1;_...') 
#6 D:\GitRepos\fisharebest\webtrees\app\Session.php(100): session_write_close() 
#7 D:\GitRepos\fisharebest\webtrees\app\Http\Middleware\UseSession.php(80): Fisharebest\Webtrees\Session::save()

**Comment by fisharebest** [comment]
I think we can change this column from `blob/varbinary` to `text/varchar`.

There are other columns with this type.  I will need to review them.

`wt_gedcom_chunk`.  This is no longer required, as we now convert to UTF8 before we insert the data.

**Comment by FrankWarius** [comment]
Be careful, this leads to an other error. I'll post it after lunch

**Comment by FrankWarius** [comment]
After Changing to nvarchar(max):
PDOException: SQLSTATE[22007]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Bei der Konvertierung eines nvarchar-Datentyps in einen datetime-Datentyp liegt der Wert außerhalb des gültigen Bereichs. in D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php:545 Stack trace: 
#0 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(545): PDOStatement->execute() 
#1 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(753): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into [wt...', Array) 
#2 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(720): Illuminate\Database\Connection->runQueryCallback('insert into [wt...', Array, Object(Closure)) 
#3 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(546): Illuminate\Database\Connection->run('insert into [wt...', Array, Object(Closure)) 
#4 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(498): Illuminate\Database\Connection->statement('insert into [wt...', Array) 
#5 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Query\Builder.php(3218): Illuminate\Database\Connection->insert('insert into [wt...', Array) 
#6 D:\GitRepos\fisharebest\webtrees\app\SessionDatabaseHandler.php(100): Illuminate\Database\Query\Builder->insert(Array) 
#7 [internal function]: Fisharebest\Webtrees\SessionDatabaseHandler->write('3eb401lrd3dvje5...', 'initiated|b:1;_...') 
#8 D:\GitRepos\fisharebest\webtrees\app\Session.php(100): session_write_close() 
#9 D:\GitRepos\fisharebest\webtrees\app\Http\Middleware\UseSession.php(80): Fisharebest\Webtrees\Session::save() 

session data = 
`initiated|b:1;_GUEST_sessiontime|s:10:"1671620087";language|s:2:"de";theme|s:8:"webtrees";`

**Comment by fisharebest** [comment]
Type of `session_data` and `chunk_data` both changed from `BLOB` to `TEXT` in 736b8b72ed0af202b700901a7965eb77c180581f

Please create a new issue for the date/time columns.
