### ISSUE TITLE
2.1 Branch individual list (8be64285b2100556621e9aa3cb7bfb479aa06040) must be of type string, null given

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4670]
Fisharebest\Webtrees\Module\LanguageGerman::normalize(): Argument #1 ($text) must be of type string, null given, called in …\app\Module\IndividualListModule.php on line 637 …\app\Module\ModuleLanguageTrait.php:203
#0 …\app\Module\IndividualListModule.php(637): Fisharebest\Webtrees\Module\LanguageGerman->normalize(NULL)
#1 …\app\Module\IndividualListModule.php(224): Fisharebest\Webtrees\Module\IndividualListModule->allSurnames(Object(Fisharebest\Webtrees\Tree), false, false)
#2 …\app\Module\IndividualListModule.php(174): Fisharebest\Webtrees\Module\IndividualListModule->createResponse(Object(Fisharebest\Webtrees\Tree), Object(Fisharebest\Webtrees\GuestUser), Array, false)

**Comment by fisharebest** [comment]
This is SQL Server?

The error message sugggests that you have null values in `wt_name.n_surn`?

webtrees does not store nulls in this column.

Can you look in this table and tell me about your data.

**Comment by FrankWarius** [comment]
no Production MySql 8.0. on Branch 2.1 (MS SQL doesn't work at all)
I now revoke the 3 Commits ahead Tag 2.1.13 and it is working again

15:10:32	SELECT * FROM wtprod.wt21_name where n_surname is null 	757 row(s) returned	0.000 sec / 0.000 sec

all sources, repos, objects with ID S*, R*, M* but no X*

**Comment by fisharebest** [comment]
> all sources, repos, objects

Thanks.

This is all old data.

The table `wt_name` is now only used for individual names.

We need to ignore/delete this data.

**Comment by fisharebest** [comment]
Until I write a fix, you can delete all the rows where `n_surn` is null or `n_surname` is null.

**Comment by FrankWarius** [comment]
From my side, the issue is closed - I'm waiting for the next release.
(I'm still struggling with Github and didn't want to use the whole branch 2.1 but just tag 2.1.13. - Github is much more complex than Panvalet https://en.wikipedia.org/wiki/Panvalet (:- )
