### ISSUE TITLE
Change family members broken

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4674]
Removing any child via ChangeFamilyMembersPage/ChangeFamilyMembersAction results in the family having no children left at all.
Tested on demo server.

Cause: Either the request array is malformed (contains empty entries, i.e. the removed children), example:

```
[CHIL] => Array
                        (
                            [0] => I6647
                            [1] => I6648
                            [2] => I6649
                            [3] => I6650
                            [4] => I6651
                            [5] => 
                            [6] => I17063
                        )
````

or it isn't validated corectly [here](https://github.com/fisharebest/webtrees/blob/f4e80bda8ea3ef43d745d58768708703dafd2eee/app/Http/RequestHandlers/ChangeFamilyMembersAction.php#L52) (empty value should probably just be skipped in array, currently the Validator returns null in that case).

**Comment by fisharebest** [comment]
> or it isn't validated correctly

The `isXref()` validator expects an array of valid xrefs - so this is the wrong validation to use here.
