### ISSUE TITLE
2.1 Dev MS SQL SQLSTATE[42000] when entring control panel after setup (with or without loaded GEDCOM)

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4679]
SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Column 'wt1222_user.user_name' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause. (SQL: select [wt1222_user].* from [wt1222_user] inner join [wt1222_user_gedcom_setting] on [wt1222_user_gedcom_setting].[user_id] = [wt1222_user].[user_id] where [wt1222_user_gedcom_setting].[setting_name] = canedit and [wt1222_user_gedcom_setting].[setting_value] = admin and [wt1222_user].[user_id] > 0 group by [wt1222_user].[user_id] order by [real_name] asc) …\vendor\illuminate\database\Connection.php:760
#0 …\vendor\illuminate\database\Connection.php(720): Illuminate\Database\Connection->runQueryCallback('select [wt1222_...', Array, Object(Closure))
#1 …\vendor\illuminate\database\Connection.php(422): Illuminate\Database\Connection->run('select [wt1222_...', Array, Object(Closure))
#2 …\vendor\illuminate\database\Query\Builder.php(2650): Illuminate\Database\Connection->select('select [wt1222_...', Array, true)
#3 …\vendor\illuminate\database\Query\Builder.php(2638): Illuminate\Database\Query\Builder->runSelect()
#4 …\vendor\illuminate\database\Query\Builder.php(3174): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 …\vendor\illuminate\database\Query\Builder.php(2639): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#6 …\app\Services\UserService.php(234): Illuminate\Database\Query\Builder->get()
#7 …\app\Http\RequestHandlers\ControlPanel.php(156): Fisharebest\Webtrees\Services\UserService->managers()

**Comment by fisharebest** [comment]
In standard SQL, you only need to `GROUP BY` the primary key.  All other columns depend on the key, and so there is no ambiguity.

Looking through the code, I can see other places where we use

```
SELECT <other column>
GROUP BY <primary key>
```

We can probably rewrite these using subqueries.

**Comment by fisharebest** [comment]
In all of these cases, we do not use any aggregate functions (`COUNT()`, `SUM()`, etc.).

So, `SELECT DISTINCT x.*` would be logically equivalent to `SELECT x.* GROUP BY x.primary_key`.

There might be some peformance considerations.
