### ISSUE TITLE
2.2 dev sqlsrv: GROUP_CONCAT' is not a recognized built-in function name.

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4683]
SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]'GROUP_CONCAT' is not a recognized built-in function name. (SQL: select GROUP_CONCAT(s_id) AS xrefs from [wt1224_sources] where [s_file] = 1 group by [s_name] having COUNT(s_id) > 1 order by [xrefs] asc) …\vendor\illuminate\database\Connection.php:760
#0 …\vendor\illuminate\database\Connection.php(720): Illuminate\Database\Connection->runQueryCallback('select GROUP_CO...', Array, Object(Closure))
#1 …\vendor\illuminate\database\Connection.php(422): Illuminate\Database\Connection->run('select GROUP_CO...', Array, Object(Closure))
#2 …\vendor\illuminate\database\Query\Builder.php(2650): Illuminate\Database\Connection->select('select GROUP_CO...', Array, true)
#3 …\vendor\illuminate\database\Query\Builder.php(2864): Illuminate\Database\Query\Builder->runSelect()
#4 …\vendor\illuminate\database\Query\Builder.php(3174): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 …\vendor\illuminate\database\Query\Builder.php(2866): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#6 …\app\Services\AdminService.php(122): Illuminate\Database\Query\Builder->pluck('xrefs')
#7 …\app\Http\RequestHandlers\FindDuplicateRecords.php(60): Fisharebest\Webtrees\Services\AdminService->duplicateRecords(Object(Fisharebest\Webtrees\Tree))

**Comment by fisharebest** [comment]
It appears that SQL-Server calls this function `STRING_AGG()`

https://database.guide/the-sql-server-equivalent-to-group_concat/

**Comment by fisharebest** [comment]
...`STRING_AGG()` does not support `DISTINCT`.

**Comment by FrankWarius** [comment]
sorry, I'm lost (this was not part of IBM's DB2 in 1985)

Did You seem this https://www.codeproject.com/Articles/691102/String-Aggregation-in-the-World-of-SQL-Server?

**Comment by FrankWarius** [comment]
still exists
