### ISSUE TITLE
Error in webtrees test admin page

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#4686]
I updated today my test test system code.

/test/index.php?route=%2Ftest%2Fadmin
shows error 
Class "?" not found …/vendor/symfony/cache/CacheItem.php:172
#0 …/vendor/symfony/cache/Adapter/AbstractAdapter.php(75): Symfony\Component\Cache\CacheItem->pack()
etc.

Meliza

**Comment by melizaa** [comment]
I see the page without any error in the future test system, so this must be my error.

**Comment by fisharebest** [comment]
In the `main` branch, we have updated all the `/vendor/` files.

This includes the symfony/cache library.

I guess you need to update these files.

Locally, run `php composer.phar install`, and then copy the `/vendor/` folder.

Or ask, and I can do this for you.

**Comment by melizaa** [comment]
I have not yet figured out what causes the error.
As far as I see, I uploaded all the changed files.

I will continue to try to figure out why the program searches Class ?.

**Comment by fisharebest** [comment]
Try deleting the folder data/cache

**Comment by melizaa** [comment]
I removed data/cache.
I see still the same error as before.

I see

**Comment by melizaa** [comment]
Solved.
I did not replace the composer changes.
