### ISSUE TITLE
404 error after using direct link to control panel

### ISSUE THREAD

**Issue by Jefferson49** [fisharebest/webtrees#4688]
Observed with webtrees 2.1.15

For a fast access to the control panel, I am using a browser bookmark:
MY_SITE/webtrees/index.php?route=%2Fwebtrees%2Fadmin

After opening the link, webtrees shows the login page. However, after logging in, webtrees shows an 404 error.

I have used the link for a long time. The 404 error seems to be new; maybe since webtrees 2.1.13. Currently it is reproducable with 2.1.15.

With some testing, I could identify a workaround. After the 404 error occurs, I re-call the mentioned URL. After this, the control panel is shown and everything seems to be fine.

**Comment by Jefferson49** [comment]
After further usage of webtrees 2.1.15, I recognized that the described issue also occurs in other situations if the user does not log in from the main login page.

An example:
- User not logged in
- User opens a certain view (e.g. list of sources)
- Login of user (after list of sources is shown)
- After the login, the page is redirected and a 404 error is shown

**Comment by Jefferson49** [comment]
With a [hint in the forum](https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/37578-v2-1-15-after-accepting-changes-the-weiter-button-leads-to-404-page#96594), I could resolve the issue: 

So, **adding the default .htaccess file**, which is [proposed in the webtrees FAQs](https://webtrees.net/faq/urls/), solves the issue (for both of the described scenarios above).

**Comment by Jefferson49** [comment]
Well, it is still a question how to handle this issue. Since not every user installs the .htaccess file, some users could run into this issue. For my case, I have been using webtrees for almost 20 years without the .htaccess files. It is the first time, I need it.

Maybe, a warning or hint could be shown in the Control Panel, if the .htaccess file is missing. Then, the admin can decide.

**Comment by Jefferson49** [comment]
Additional information: I did not activate activate "pretty URLs". My data/config.ini.php files do not contain a rewrite_urls="1" line.

**Comment by fisharebest** [comment]
There was a recent change to redirect "ugly" URLs onto "pretty" ones.

This error only affects "ugly" URLs, and may be related to this change.
