### ISSUE TITLE
Error after update to 2.1.15

### ISSUE THREAD

**Issue by rookelaar** [fisharebest/webtrees#4692]
I updated successfully app to 2.1.15 and then after going to main page I'm getting stacktrace:

`Error: Class "Fisharebest\Webtrees\Elements\FamilyResidence" not found in /var/www/html/app/Gedcom.php:476 Stack trace: #0 /var/www/html/app/Gedcom.php(1117): Fisharebest\Webtrees\Gedcom->gedcom551Tags() #1 /var/www/html/app/Http/Middleware/RegisterGedcomTags.php(52): Fisharebest\Webtrees\Gedcom->registerTags() #2 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process() #3 /var/www/html/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle() #4 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process() #5 /var/www/html/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher->handle() #6 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process() #7 /var/www/html/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle() #8 /var/www/html/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}() #9 /var/www/html/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction() #10 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process() #11 /var/www/html/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle() #12 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process() #13 /var/www/html/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle() #14 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process() #15 /var/www/html/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle() #16 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process() #17 /var/www/html/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle() #18 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process() #19 /var/www/html/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle() #20 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process() #21 /var/www/html/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle() #22 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process() #23 /var/www/html/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle() #24 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process() #25 /var/www/html/app/Http/Middleware/BadBotBlocker.php(245): Middleland\Dispatcher->handle() #26 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process() #27 /var/www/html/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle() #28 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process() #29 /var/www/html/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle() #30 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process() #31 /var/www/html/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle() #32 /var/www/html/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process() #33 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process() #34 /var/www/html/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle() #35 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process() #36 /var/www/html/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle() #37 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process() #38 /var/www/html/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle() #39 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process() #40 /var/www/html/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle() #41 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process() #42 /var/www/html/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle() #43 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process() #44 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #45 /var/www/html/app/Webtrees.php(275): Middleland\Dispatcher->dispatch() #46 /var/www/html/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch() #47 /var/www/html/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest() #48 {main}`

**Comment by fisharebest** [comment]
At your last upgrade, one file did not get copied.

This has affected a few users, but we haven't isentified a pattern. (All ysing German web host?)

Do a manual upgrade to fix this.

**Comment by fisharebest** [comment]
Instructions here: https://webtrees.net/upgrade/manual/

**Comment by photon-flip** [comment]
`All using German web host?` maybe not.
When I had the same problem I was using a Bulgarian? host, Siteground on their Singapore server.
Was easily fixed with the manual reload.

**Comment by fisharebest** [comment]
> When I had the same problem I was using a Bulgarian? host

OK.  That has debunked that idea :-)
Now I have no idea why this happens for some people.

**Comment by photon-flip** [comment]
Oops, just realized, it was with my local XAMPP setup on Windows 10 not my online site. Still not a German host though.
Could it be a timestamp "thing"? 
Has anyone tried just overwriting the GEDCOM.php or where there other files not updated as well?
Hard to reproduce the problem at will to test.

**Comment by rookelaar** [comment]
Works after manual upgrade 👍
I'm using my own hard disk as a hosting since I've got public IP.

**Comment by photon-flip** [comment]
If I intentionally use an old 2.1.5 Gedcom.php in 2.1.13 or 2.1.15 I do get the `Error: Class "Fisharebest\Webtrees\Elements\FamilyResidence" not found`.
Not a very "scientific" simulation I know but maybe an indication that it is only that file that's not updated. 
I've done half a dozen test automatic upgrades on my local environment without the problem so still a mystery.
