### ISSUE TITLE
Wrong alphabetic order in Place hierarchy (2.1.15)

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#4694]
In Place hierarchy, the Scandinavian letters Ææ Øø Åå are not correctly listed (should be last in the alphabet)

**Comment by pezball** [comment]
For Swedish, the corresponding letters are Ää Öö Åå, but they correctly appear at the end of the alphabet.

However the order is not correct, currently they are listad as Ää Åå Öö, when Swedish should have them in order Åå Ää Öö.   That may differ from other Scandinavian languages.

The people and family lists are sorted in the correct way.  So the problem must be that place hierarchy uses a separate (and incorrect) language settings module.


________________________________
Från: HRN65 ***@***.***>
Skickat: den 29 december 2022 18:41
Till: fisharebest/webtrees ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: [fisharebest/webtrees] Wrong alphabetic order in Place hierarchy (2.1.15) (Issue #4694)


In Place hierarchy, the Scandinavian letters Ææ Øø Åå are not correctly listed (should be last in the alphabet)

**Comment by fisharebest** [comment]
> However the order is not correct, currently they are listad as Ää Åå Öö, when Swedish should have them in order Åå Ää Öö.

The definition appears to be correct:

https://github.com/fisharebest/webtrees/blob/0fd8983e1a1376eaa4bddf23ee5d2a545a24f151/app/Module/LanguageSwedish.php#L68-L70

I see this order on the demo site:

<img width="757" alt="Screenshot 2022-12-29 at 18 33 45" src="https://user-images.githubusercontent.com/2306088/209994755-6e7dbe57-79dd-4965-ac10-507df8f8b2ca.png">

Which version of webtrees are you using?  Can you post the URL of your site?

**Comment by fisharebest** [comment]
Sorry - ignore me.  I missed that you were talking about the place hierarchy - not the individual list.
