### ISSUE TITLE
Pending changes continue button leads to 404

### ISSUE THREAD

**Issue by bombaata** [fisharebest/webtrees#4697]
Hi, using webtrees 2.1.15; when I approve a modification of a user, the "continue" button redirects to a 404 url (adds "/tree/" in the address, ie https://mydomain.com/tree/mytree/edit-fact/X11435/6c99fd31a25948ac87edd4caa5296ad1?route=%2Ftree%mytree%2Fedit-fact%2FX11435%2F6c99fd31a25948ac87edd4caa5296ad1).

**Comment by fisharebest** [comment]
I think this is the same issue as #4688
