### ISSUE TITLE
Error during GEDCOM Import

### ISSUE THREAD

**Issue by webtrees-pesz** [fisharebest/webtrees#4698]
I get following Error:

SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x87\xAB\xF0\x9F...' for column 'chunk_data' at row 1 (SQL: insert into `wt_gedcom_chunk` (`gedcom_id`, `chunk_data`) values (1, 0 @I5138@ INDI
1 NAME Elisabeth /GALLINGER/
2 SOUR @S75@
3 OBJE @M4024@
2 SOUR @S273@
3 OBJE @M4169@
1 SEX F
....

How to find out the wrong character?

In Notepad ++ everything looks fine.

![image](https://user-images.githubusercontent.com/13770346/210092289-bb6c8ae7-a167-40ab-b604-4420d79fea54.png)

**Comment by fisharebest** [comment]
This will be a 4-byte UTF8 sequence. Typically an emoji.

Already reported as #2950

I hope to fix this in 2.2.0

> How to find out the wrong character?

It could be a flag?

**Comment by webtrees-pesz** [comment]
How to find out, which record or better which line is affected?
When I delete the mentioned record, then the error will start with the next one.

**Comment by webtrees-pesz** [comment]
I found it with the help of GEDCOM Validator from Chronoplex.

![image](https://user-images.githubusercontent.com/13770346/210099115-2398992f-4dc5-4914-ba13-2ed2ea145733.png)

![image](https://user-images.githubusercontent.com/13770346/210099292-ebe7570e-20f2-4ad2-b77d-89ff548b166a.png)
