### ISSUE TITLE
inconsistencies in Dutch translation

### ISSUE THREAD

**Issue by Joppla** [fisharebest/webtrees#4709]
Hello,

I found some inconsistencies in the Dutch translation, for example:
Add a son -> Voeg een zoon toe
Add a daughter -> Een dochter toevoegen

(but there are more)

It looks not nice if you see it in one view. 

I tried to edit it in `/resources/lang/nl/messages.po`  but it seems me that I do not have permission for it. Or it has to be another file?

Thanks for reaction,

Jop

**Comment by LarsRabe** [comment]
Translations are solely done using
https://translate.webtrees.net/projects/webtrees/

**Comment by Joppla** [comment]
Oke, Thanks, How to get an overview of the translations? Or search to the inconsistent translation?

**Comment by fisharebest** [comment]
The translation server has a "search" function.

You can search on source-text, translated text, and more

**Comment by fisharebest** [comment]
> Is this enough for the future versions of Webtrees? Or have I to do other thinks?

The different versions (1.7, 2.0, 2.1 and 2.2) are all linked.

If you update one version, then the other versions will also be updated.

The translation server has many "error checks".  It will tell you if you have the same string with different translations in different versions.

**Comment by Joppla** [comment]
Thanks for explanation Greg!
