### ISSUE TITLE
Class "Fisharebest\Webtrees\Elements\FamilyResidence" not found after upgrading to 2.1.15

### ISSUE THREAD

**Issue by gmarcon** [fisharebest/webtrees#4711]
I just upgraded from 2.1.14 to 2.1.15. After the upgrade Webtrees does not work anymore, any page shows the following error/stack trace:
Error: Class "Fisharebest\Webtrees\Elements\FamilyResidence" not found in /var/www/webtrees/app/Gedcom.php:476
Stack trace:
0 /var/www/webtrees/app/Gedcom.php(1117): Fisharebest\Webtrees\Gedcom->gedcom551Tags()
1 /var/www/webtrees/app/Http/Middleware/RegisterGedcomTags.php(52): Fisharebest\Webtrees\Gedcom->registerTags()
2 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
3 /var/www/webtrees/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
4 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
5 /var/www/webtrees/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher->handle()
6 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
7 /var/www/webtrees/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
8 /var/www/webtrees/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
9 /var/www/webtrees/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
10 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
11 /var/www/webtrees/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
12 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
13 /var/www/webtrees/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
14 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
15 /var/www/webtrees/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
16 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
17 /var/www/webtrees/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
18 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
19 /var/www/webtrees/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
20 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
21 /var/www/webtrees/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
22 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
23 /var/www/webtrees/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle()
24 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
25 /var/www/webtrees/app/Http/Middleware/BadBotBlocker.php(245): Middleland\Dispatcher->handle()
26 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
27 /var/www/webtrees/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
28 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
29 /var/www/webtrees/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
30 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
31 /var/www/webtrees/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
32 /var/www/webtrees/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
33 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
34 /var/www/webtrees/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
35 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
36 /var/www/webtrees/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle()
37 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
38 /var/www/webtrees/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
39 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
40 /var/www/webtrees/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
41 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
42 /var/www/webtrees/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
43 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
44 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
45 /var/www/webtrees/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
46 /var/www/webtrees/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
47 /var/www/webtrees/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
48 {main}

**Comment by fisharebest** [comment]
`FamilyResidence` was removed in version 2.1.13

https://github.com/fisharebest/webtrees/blob/2.1.12/app/Gedcom.php#L102
https://github.com/fisharebest/webtrees/blob/2.1.13/app/Gedcom.php#L102

You still have the old version of this file, from 2.1.12 or earlier.

Perform a [manual upgrade](https://webtrees.net/upgrade/manual/), being careful that all files are copied to the server.

Note that several people have reported this.  It seems that one file (and possibly others) is not copied - but only on some servers.

**Comment by ungeahnt** [comment]
There is a problem with one file, that is not copied correctly. The reason is unknown. 

The solution is a manual upgrade.
