### ISSUE TITLE
"My site" One block has a type mismatch

### ISSUE THREAD

**Issue by WeT-Klb** [fisharebest/webtrees#4714]
When I go to "My Site" in 2.1.15 on bottom i can choose the blocks to be shown.

There it is on block named "Yahrzeiten" - should be Jahrzeiten.
I am using german language.

![Webtrees](https://user-images.githubusercontent.com/20600342/211278832-c7ba25ba-85a1-40fc-bb78-8bc6c5de2069.jpg)

**Comment by mpwt** [comment]
Take a look at: https://www.webtrees.net/index.php/fr/forum/8-translation/18039-description-of-the-yahrzeiten-module

I18N: Name of a module. Yahrzeiten (the plural of Yahrzeit) are special anniversaries of deaths in the Hebrew faith/calendar.

**Comment by fisharebest** [comment]
Is this a translation issue?

https://translate.webtrees.net/translate/webtrees/webtrees-22/de/?q=+source%3Ayahrzeit+&sort_by=-priority%2Cposition&offset=1

**Comment by WeT-Klb** [comment]
mpwt is right. Do I need to do something?

**Comment by fisharebest** [comment]
You can update the translation!

Use your github account to log into the translation server...

**Comment by WeT-Klb** [comment]
I am not sure if the german word "Jahreszeit" is the right match because "Jahreszeit" means season.
I never read nor heared that judish word Yahrzeit before.

**Comment by mpwt** [comment]
I have changed the german translation to Jahrzeit and Jahrzeiten. You can close this issue here.
