### ISSUE TITLE
more bad bots

### ISSUE THREAD

**Issue by LarsRabe** [fisharebest/webtrees#4718]
Please add following bots to the BadBotBlocker. Thank you.

```
Yandex
MegaIndex Bot
```
https://yandex.com/support/webmaster/robot-workings/user-agent.html
https://user-agents.net/string/mozilla-5-0-compatible-megaindex-ru-2-0-http-megaindex-com-crawler

**Comment by fisharebest** [comment]
Yandex is the Russian equivalent of Google.

I do not think it qualifies as a "bad bot".

**Comment by FrankWarius** [comment]
Compared to Google and Bing, Yandex is no more aggressive

request per Month  | Okt | Sep | Dez | Jan 
-- | -- | -- | -- | --
bing | 1.824 | 8.531 | 40.548 | 14.077
google | 4.901 | 6.022 | 5.315 | 1.702
yandex | 3.141 | 3.750 | 10.254 | 6.912

megaindex found my site on 19.11. at 5:30. I blocked it in the firewall after making 7,600 requests in 6 hours (out of a total of 9,000 of all bots that entire day)

**Comment by fisharebest** [comment]
> megaindex found my site on 19.11. at 5:30. I blocked it in the firewall after making 7,600 requests in 6 hours (out of a total of 9,000 of all bots that entire day)

Same here :-)

```
sudo ufw deny from 144.76.27.118   comment "MegaIndex.ru"
sudo ufw deny from 144.76.60.98    comment "MegaIndex.ru"
sudo ufw deny from 176.9.117.99    comment "MegaIndex.ru"
sudo ufw deny from 176.9.137.17    comment "MegaIndex.ru"
sudo ufw deny from 176.9.139.229   comment "MegaIndex.ru"
sudo ufw deny from 176.9.146.74    comment "MegaIndex.ru"
sudo ufw deny from 176.9.41.28     comment "MegaIndex.ru"
sudo ufw deny from 176.9.58.227    comment "MegaIndex.ru"
sudo ufw deny from 46.4.100.132    comment "MegaIndex.ru"
sudo ufw deny from 46.4.72.213     comment "MegaIndex.ru"
sudo ufw deny from 5.9.98.178      comment "MegaIndex.ru"
sudo ufw deny from 78.46.161.81    comment "MegaIndex.ru"
sudo ufw deny from 78.46.174.55    comment "MegaIndex.ru"
sudo ufw deny from 88.198.158.233  comment "MegaIndex.ru"
sudo ufw deny from 88.198.25.244   comment "MegaIndex.ru"
sudo ufw deny from 95.216.33.150   comment "MegaIndex.ru"
```

**Comment by LarsRabe** [comment]
Hmmm, as I'm on a shared host I cannot alter the firewall. So for now I added it to the `robots.txt`. Any suggestion what I can do else (besides asking my hoster)?

**Comment by fisharebest** [comment]
> So for now I added it to the robots.txt.

Does "it" mean yandex or megaindex.

Yandex probably obeys robots.txt.
Megaindex probably does not.

**Comment by LarsRabe** [comment]
I added both

**Comment by FrankWarius** [comment]
I guess You use Apache (which i don't know).

I use MS IIS 10 and added the following rule to IIS URL Rewrite (that seems to be similar to htaccess)

`              <rule name="Block Bad Bots" stopProcessing="true">`
`                    <match url=".*" />`
`                    <conditions logicalGrouping="MatchAny" trackAllCaptures="false">`
`                        <add input="{HTTP_USER_AGENT}" pattern=".*seokicks.*" />
`                        <add input="{HTTP_USER_AGENT}" pattern=".*petalsearch.*" />
`                        <add input="{HTTP_USER_AGENT}" pattern=".*SeekportBot.*" />
`                    </conditions>
`                    <action type="CustomResponse" statusCode="403" statusReason="Forbidden: Access is denied." statusDescription="You do not have permission to view this directory or page using the credentials that you supplied." />`
`                </rule>`

**Comment by fisharebest** [comment]
> <add input="{HTTP_USER_AGENT}" pattern=".*SeekportBot.*" />

I had always assumed that SeekPort was valid.  www.seekport.de looks like a real search engine.

But it is either broken or a fake - it does not return any search results...

**Comment by FrankWarius** [comment]
It's not a real search engine, it's a service:

"search engine optimization
Up with SISTRIX: better rankings and more visitors from Google.
Optimize your website with the most used SEO software, discover the secrets of success of the competitors and get more visitors from Google."

I blocked it 19.12 on its first visit having 12.500 requests in 7 h from one IP-adress

**Comment by fisharebest** [comment]
Thanks.  I'll add it to the list.

**Comment by LarsRabe** [comment]
Are you sure `MegaIndex.ru`is the correct name for the bot? 

In the link I provided the name `MegaIndex Bot` was mentioned. My logs show that entry works.

**Comment by fisharebest** [comment]
> Are you sure MegaIndex.ru is the correct name for the bot?

This is an entry from my own logs.  It shows `MegaIndex.ru`.

```
46.4.64.197 - - [30/Dec/2022:01:13:04 +0000] "GET /running HTTP/1.1" 301 194 "-" "Mozilla/5.0 (compatible; MegaIndex.ru/2.0; +http://megaindex.com/crawler)"
```

**Comment by FrankWarius** [comment]
I confirm
cs(User_Agent: Mozilla/5.0+(compatible;+MegaIndex.ru/2.0;++http://megaindex.com/crawler)

**Comment by LarsRabe** [comment]
I did see the same entries also, but after I added `MegaIndex Bot` to my `robots.txt` they disappeared. Maybe both works?
