### ISSUE TITLE
Turning off watermark on thumbnail does not work

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#472]
Selected Yes for adding watermarks to thumbnails, could see watermarked thumbnails.
Then selected No for adding watermarks to thumbnails but still see watermarks.
![watermark](https://cloud.githubusercontent.com/assets/5147603/6564229/024d9a12-c675-11e4-8448-9699882f1414.png)

**Comment by makitso** [comment]
Turning off watermarks on the full size image fails as well.  FWIW, the database is being updated.

**Comment by HRN-webtrees** [comment]
I only see this behaviour in "Favorites" block
After setting watermarks on thumbnails to No, watermarks are not displyed after clearing cache.
However, the higlighted images for individuals added to my Favorites block still display watermarks.
These thumbnails do not display watermarks after setting "Images without watermarks" to "Show to visitors".

**Comment by makitso** [comment]
Drat :-( refreshed the page several times but did not clear the cache.  So, my issue does not exist.

**Comment by fisharebest** [comment]
> So, my issue does not exist.

Does this mean we can close the issue, or is there still something to investigate?

**Comment by makitso** [comment]
My issue was resolved.  But, I thought HRN-webtrees had a different issue:
> However, the higlighted images for individuals added to my Favorites block still display watermarks.

**Comment by fisharebest** [comment]
> I thought HRN-webtrees had a different issue:

He hasn't commented.  If he still has a problem, he needs to raise a separate bug report.
