### ISSUE TITLE
Fatal error in demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#4726]
Warning: require(/home/webtrees/dev.webtrees.net/demo-dev/vendor/composer/../symfony/polyfill-php81/bootstrap.php): Failed to open stream: No such file or directory in /home/webtrees/dev.webtrees.net/demo-dev/vendor/composer/autoload_real.php on line 41

Fatal error: Uncaught Error: Failed opening required '/home/webtrees/dev.webtrees.net/demo-dev/vendor/composer/../symfony/polyfill-php81/bootstrap.php' (include_path='.') in /home/webtrees/dev.webtrees.net/demo-dev/vendor/composer/autoload_real.php:41 Stack trace: #0 /home/webtrees/dev.webtrees.net/demo-dev/vendor/composer/autoload_real.php(45): ComposerAutoloaderInit05316846783bb0b0f98c19b5fb8e3c16::{closure}() #1 /home/webtrees/dev.webtrees.net/demo-dev/vendor/autoload.php(25): ComposerAutoloaderInit05316846783bb0b0f98c19b5fb8e3c16::getLoader() #2 /home/webtrees/dev.webtrees.net/demo-dev/index.php(29): require('...') #3 {main} thrown in /home/webtrees/dev.webtrees.net/demo-dev/vendor/composer/autoload_real.php on line 41

**Comment by fisharebest** [comment]
Thanks.  Fixed.
