### ISSUE TITLE
Why do we use version on favicon? Google regularly checks favicon versions back to 2.0.10

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4734]
It's a minor problem - and you can close it immediately. But my daily quota of Google crawling requests is currently 150 per day, of which about 5 are redundant favicon request.

time | request
-- | --
15.01.23   03:41 | https://wbt.warius.info/public/favicon-192.png?v=2.0.11
15.01.23   03:41 | https://wbt.warius.info/public/favicon-32.png?v=2.0.11
15.01.23 03:41 | https://wbt.warius.info/public/favicon-152.png?v=2.0.11
15.01.23   03:41 | https://wbt.warius.info/public/favicon-128.png?v=2.0.11
15.01.23 03:41 | https://wbt.warius.info/public/favicon-180.png?v=2.0.11
15.01.23   03:41 | https://wbt.warius.info/public/favicon-196.png?v=2.0.11
15.01.23 04:54 | https://wbt.warius.info/public/favicon-32.png?v=2.1.7

Statistics of the last 90 days

Vers | Okt   2022 | Nov   2022 | Dez   2022 | Jan   2023 | Summe
-- | -- | -- | -- | -- | --
2.0.10 |   | 6 | 13 |   | 19
2.0.11 | 1 |   |   | 6 | 7
2.0.13 |   | 6 | 3 |   | 9
2.0.16 |   | 13 |   |   | 13
2.0.17 | 1 |   |   |   | 1
2.0.19 | 1 | 1 |   | 10 | 12
2.1.10 |   |   | 2 |   | 2
2.1.12 |   |   | 12 | 1 | 13
2.1.13 |   |   | 6 |   | 6
2.1.14 |   |   | 4 |   | 4
2.1.15 |   |   | 8 | 7 | 15
2.1.2 |   | 4 |   |   | 4
2.1.4 |   |   | 1 | 2 | 3
2.1.5 | 2 |   |   |   | 2
2.1.6 |   | 2 |   |   | 2
2.1.7 | 1 | 8 | 12 | 2 | 23
2.1.8 |   | 4 |   |   | 4
2.1.9 |   | 4 | 10 |   | 14
Summe | 6 | 48 | 71 | 28 | 153

**Comment by fisharebest** [comment]
All static files (/public/...) have a version parameter.

* For stable releases, this is the webtrees version.
* For dev releases, this is the timestamp of the file.

This allows the site owner to add long cache lifetimes to these files - which helps performance.

It would require special code to exclude the version string from favicon.ico.
I don't think it would change google's behaviour?
If you wish to experiment, the code is here:
https://github.com/fisharebest/webtrees/blob/7f657e2ddb4d0e724ae03063fd8b1b90664dc594/app/Helpers/functions.php#L54-L70

> But my daily quota of Google crawling requests is currently 150 per day

Recently, I have noticed that I see very few Google crawlers, and many Bing crawlers.

Yesterday was 6000 Google, and 50000 Bing.
Last year, these numbers were reversed.

**Comment by FrankWarius** [comment]
It was more a question than a request for change. favicon is static and it's better to treat all static content the same.

>Yesterday was 6000 Google, and 50000 Bing.

Are You sure that is the daily rate and not the monthly total, Our booth side have approximately 9,000 records (so bing visited every of Yours record 5 times on a daily base). 

May daily average is

 |  | Oct | Nov | Dec | Jan
-- | -- | -- | -- | --
bing | 59 | 284 | 1.308 | 1.295
google | 158 | 201 | 171 | 162

My monthly total

 |  | Oct | Nov | Dec | Jan
-- | -- | -- | -- | --
bing | 1.824 | 8.531 | 40.548
google | 4.901 | 6.022 | 5.315

Do You use pretty or ugly URLs

**Comment by fisharebest** [comment]
> Are You sure that is the daily rate and not the monthly total

Yes - but this is for all the webtrees sites on my server.

> Do You use pretty or ugly URLs

Always pretty URLs.

**Comment by FrankWarius** [comment]
Thanks
