### ISSUE TITLE
add media count to tag #totalRecords#

### ISSUE THREAD

**Issue by Bogiegit** [fisharebest/webtrees#4740]
I would think the block tag #totalRecords# should include the media count, too.
That would be much more obvious than notes and repositories from table wt_other.

**Comment by hartenthaler** [comment]
... and add the count for shared location records (_LOC), please.

**Comment by Bogiegit** [comment]
Which of the standard webtrees tables hold the _LOC records?

**Comment by Bogiegit** [comment]
I have added the media to the #totalRecords# in file IndividualRepository.php, tested it on my installation and created a pull request.
