### ISSUE TITLE
Why we use http 302 "Moved Temporarily" instead of 301 "Moved Permanently".

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4744]
I am still fighting with Google :-). After I deployed the fix #4712 locally Google is reporting 302 redirects again. This causes Google to keep crawling these pages.

date | url | code
-- | -- | --
27.01.23, 08:14 | https://wbt.warius.info/tree/Warius/family-list?surname=Mandel | Vorübergehend verschoben (302)
24.01.23, 07:20 | https://wbt.warius.info/tree/Warius/family-list?surname=Kreszties | Vorübergehend verschoben (302)
23.01.23, 14:46 | https://wbt.warius.info/tree/Warius/family-list?surname=Kreszties | Vorübergehend verschoben (302)
23.01.23, 06:46 | https://wbt.warius.info/tree/Warius/family-list?surname=Kreszties | Vorübergehend verschoben (302)
22.01.23, 19:38 | https://wbt.warius.info/tree/Warius/family-list?surname=Kreszties | Vorübergehend verschoben (302)
18.01.23, 07:42 | https://wbt.warius.info/tree/Warius/individual-list?surname=Ziemann | Vorübergehend verschoben (302)
16.01.23, 17:46 | https://wbt.warius.info/tree/Warius/family-list?surname=Kramer | Vorübergehend verschoben (302)
12.01.23, 16:56 | https://wbt.warius.info/tree/Warius/family-list?surname=Kreszties | Vorübergehend verschoben (302)
10.01.23, 21:56 | https://wbt.warius.info/tree/Warius/family-list?surname=Kreszties | Vorübergehend verschoben (302)
30.12.22, 03:31 | https://wbt.warius.info/tree/Warius/family-list?surname=Heydebreck | Vorübergehend verschoben (302)

The reason is that we use StatusCodeInterface::STATUS_FOUND = 302. But Wiki https://en.wikipedia.org/wiki/HTTP_302 and Google interpret 302 as 

> phrase "Moved Temporarily" rather than "Found".  https://en.wikipedia.org/wiki/HTTP_302 

You can find ::STATUS_FOUND in about 20 modules as default. It should be replaced by ::STATUS_MOVED_PERMANENTLY. See e.g. https://github.com/fisharebest/webtrees/commit/7520bc14ead30c4fe7c342e8513052cbf66656a7

**Comment by fisharebest** [comment]
> It should be replaced by ::STATUS_MOVED_PERMANENTLY. See e.g. https://github.com/fisharebest/webtrees/commit/7520bc14ead30c4fe7c342e8513052cbf66656a7

After a `POST` request, the response should be `302`.  So we should not change this function.

Instead we should specify the code when we call `Registry::responseFactory()->redirectUrl()`.
