### ISSUE TITLE
PHP error if removing data while working in Gedcom 7 context

### ISSUE THREAD

**Issue by Jefferson49** [fisharebest/webtrees#4753]
Observed with webtrees 2.1.16

If I import an individual, which contains a CHR:ASSO structure, with Gedcom 7 and remove the ASSO structure, I get a PHP error. 

Steps to reproduce:
- Import the attached Gedcom 7 file
- Open INDI view
- CHR:ASSO @ VOID @ is shown as error. This issue is already know at #4695
- Edit the christening and removing the ASSO data (either in the browser or by "Edit the raw GEDCOM")
- Press "save" button

**Error texts:**
SQLSTATE[HY000]: General error: 1364 Field 'change_id' doesn't have a default value (SQL: insert into `wt_change` (`gedcom_id`, `xref`, `old_gedcom`, `new_gedcom`, `user_id`) values (19, I802, 

Fisharebest\Webtrees\GedcomRecord->updateFact('NOT A VALID FAC...', '1 CHR\n2 DATE 11...', true)

**Gedcom file:**
[Anton Huber Gedcom7 error.ged.txt](https://github.com/fisharebest/webtrees/files/10712985/Anton.Huber.Gedcom7.error.ged.txt)

**Full PHP error text:**
[webtrees Gedcom 7 error - Not a valid fact.txt](https://github.com/fisharebest/webtrees/files/10712986/webtrees.Gedcom.7.error.-.Not.a.valid.fact.txt)

**Screenshots:**
![VOID ASSO pointer](https://user-images.githubusercontent.com/81484983/218249493-24e31566-4959-4b78-854b-230772e9953d.JPG)
![Editing ASSO](https://user-images.githubusercontent.com/81484983/218249502-4248a9c5-947c-47c0-ac0d-33eecff9bfcd.JPG)

**Comment by Jefferson49** [comment]
Further testing showed that the same PHP error also occurs if other data is changed, e.g. the birth date.

Furthermore, it is not possible to delete EVENTS/FACTS for this individual. If pressing the delete icon, nothing happens. However, no error occurs.

**Comment by Jefferson49** [comment]
If a new individual is added to the tree in the control panel, the error also occurs. 

Therefore, the error seems to be more general and not related to the CHR:ASSO structure. The error also occurs with my full Gedcom 7 tree.

**Comment by fisharebest** [comment]
> SQLSTATE[HY000]: General error: 1364 Field 'change_id' doesn't have a default value

`change_id` is an `autoincrement` field.  By definition, it has a default value.

Perhaps your database has an inssue?  The table `wt_change` should look like this:

```
SHOW CREATE TABLE wt_change;

wt_change | CREATE TABLE `wt_change` (
  `change_id` int NOT NULL AUTO_INCREMENT,
  `change_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` enum('accepted','pending','rejected') COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT 'pending',
  `gedcom_id` int NOT NULL,
  `xref` varchar(20) COLLATE utf8mb3_unicode_ci NOT NULL,
  `old_gedcom` longtext COLLATE utf8mb3_unicode_ci NOT NULL,
  `new_gedcom` longtext COLLATE utf8mb3_unicode_ci NOT NULL,
  `user_id` int NOT NULL,
  PRIMARY KEY (`change_id`),
  KEY `wt_change_gedcom_id_status_xref_index` (`gedcom_id`,`status`,`xref`),
  KEY `wt_change_user_id_index` (`user_id`),
  CONSTRAINT `wt_change_gedcom_id_foreign` FOREIGN KEY (`gedcom_id`) REFERENCES `wt_gedcom` (`gedcom_id`),
  CONSTRAINT `wt_change_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `wt_user` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci ```

**Comment by Jefferson49** [comment]
Thank you very much for analyzing the issue. Your analysis seems to lead to the right point. The `wt_change`  table is different from your data and the autoincrement for  `change_id` is really missing.

This is a specific webtrees installation for testing purposes only. I copy my main database there every once in a while. I will start a new copy now.

CREATE TABLE `wt_change` (
  `change_id` int(11) NOT NULL,
  `change_time` timestamp NOT NULL DEFAULT current_timestamp(),
  `status` enum('accepted','pending','rejected') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'pending',
  `gedcom_id` int(11) NOT NULL,
  `xref` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `old_gedcom` longtext COLLATE utf8_unicode_ci NOT NULL,
  `new_gedcom` longtext COLLATE utf8_unicode_ci NOT NULL,
  `user_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
COMMIT;

**Comment by Jefferson49** [comment]
Please excuse me taking your time with my faulty installation. After deleting the faulty database and re-importing a backup from my main database, everything seems to be fine.

The autoincrement confuses me a little bit, because it seems to be missing in my main database also. It seems that it is not included in the SQL dump and was also not imported from the backup. However, after re-importing, everything is working fine. Maybe, the autoincrement was not the root cause but some other database issue caused the problems.

**Comment by fisharebest** [comment]
> because it seems to be missing in my main database also

Without it, you might find it difficult to make any edits.

The only way I can think that this could happen is if you use phpMyAdmin to do a backup/restore, and choose one of the (many) options that doesn't include the full database structure.

FYI, I'm working on a change to the database-update script.  Instead of making incremental changes, we'll have a "repair" script that updates the existing structure to match the desired structure.  When it's ready, this will fix issues like yours.

**Comment by Jefferson49** [comment]
I dived a little bit more into this issue. The autoincrement (for `change_id`  in `wt_change`) seems to exist in my databases, although it is not included in the (phpMyAdmin) exports:

![change_id_autoincrement](https://user-images.githubusercontent.com/81484983/218295356-d95c0fc1-ac09-4600-9f13-8d9f8adcf861.JPG)

Maybe, phpMyAdmin does not include the autoincrement for primary keys, because it assumes that they are autoincrement by default.

In phpMyAdmin, I use the standard export ("quick export") without any additional settings/changes.

![quick_export](https://user-images.githubusercontent.com/81484983/218295433-ed26dd61-6b2d-4d17-8bb4-222209a01ac2.JPG)
