### ISSUE TITLE
Admin theme inconsistency

### ISSUE THREAD

**Issue by vytux-com** [fisharebest/webtrees#476]
I just noticed that Server Information page has different formatting for the "My page" "Language" "Logout" menu bar.

This seems to be caused by:
ob_start();
phpinfo(INFO_ALL & ~INFO_CREDITS & ~INFO_LICENSE);
preg_match('%<style type="text/css">(.*?)</style>.*?(<body>.*</body>)%s', ob_get_clean(), $matches);
$style = $matches[1];
$html  = $matches[2];

and then echoing $style which includes this line: a:link {color: #009; text-decoration: none; background-color: #fff;}

**Comment by fisharebest** [comment]
The code uses `<style scoped></style>' so it should only apply the style to that block.

I do not see any difference.  Which browser are you using?

**Comment by vytux-com** [comment]
Chrome on windows. I will do some more testing on other browsers later today/tomorrow

**Comment by fisharebest** [comment]
Can you explain exactly 

> has different formatting

Perhaps I have the same problem, but cannot see it?

**Comment by vytux-com** [comment]
Just checked and indeed it does seem to be a Chrome issue, as in Firefox it seems OK.

Here are the screenshots of the affected area.

![webtrees admin - server info](https://cloud.githubusercontent.com/assets/5370583/6654833/9e752e38-cb33-11e4-94ea-8b74b8a9beab.png)
![webtrees admin - all others](https://cloud.githubusercontent.com/assets/5370583/6654834/a46b8260-cb33-11e4-88cc-2ae6a92a453a.png)

**Comment by vytux-com** [comment]
On further research it seems that scoped CSS is a Firefox only feature: http://caniuse.com/#feat=style-scoped
