### ISSUE TITLE
Error found in webtrees log file

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#4761]
The error occurred several times when nobody is logged in (no user, no tree, IP=52.167.144.79).

It was first discussed at
https://github.com/vesta-webtrees-2-custom-modules/vesta_extended_relationships/issues/99
but is not related to the Vesta modules.

**Comment by fisharebest** [comment]
Is the same issue as #4548

**Comment by ric2016** [comment]
Not sure this issue should be closed - The related issue is closed without fix, apparently.

**Comment by fisharebest** [comment]
This was the fix:

https://github.com/fisharebest/webtrees/commit/65905dc446ba24b6b706b2394d6cc0b3e72c8618

**Comment by ric2016** [comment]
Sorry, I missed that.
