### ISSUE TITLE
pedigree map: links

### ISSUE THREAD

**Issue by arbor95** [fisharebest/webtrees#4762]
![explanation](https://user-images.githubusercontent.com/6124739/220985777-60c43b82-5a68-4308-b4a4-284fd1e344c6.jpg)

**Comment by arbor95** [comment]
not completely solved
![Headline-link](https://user-images.githubusercontent.com/6124739/221144221-3912a27d-579b-4525-a04f-f99c7f26db1e.jpg)
not completely solved

**Comment by fisharebest** [comment]
If you click on the "location icons" (the red links), the map scrolls to show that location.

**Comment by arbor95** [comment]
That function is not obvious (intuitive) (for me) cause normally all locations are shown (if not zoomed).
Perhaps scrolling and showing the bubble (popup) is more intuitive.
Perhaps a Split into two links: one for the Icon and one for the relation (I would rather like it)

Cause webtrees has no context help, that seems more intuitive for me.
