### ISSUE TITLE
rate-limit-registration

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4764]
Got this message in the log last night, at the same time as someone requested to register (only one request). What's it all about?

>  Site preference "rate-limit-registration" set to "1643718286,1655417926,1671032997,1677186524"

**Comment by fisharebest** [comment]
We apply limits to certain actions - password reset, registration, contact messages, etc.

Otherwise an attacker could trigger 1000s of requests that would cause 1000s of emails to be sent.

Some limits are per site.
Others are per user.

Search the code for `RateLimitService`
