### ISSUE TITLE
Sitemap link for Bing/Yahoo result in http error 410

### ISSUE THREAD

**Issue by LarsRabe** [fisharebest/webtrees#4772]
When clicking on the Bing/Yahoo link for the sitemap it results in a `HTTP ERROR 410`
![sitemap](https://user-images.githubusercontent.com/119816325/221410939-3ef72166-ef61-4e35-9e4e-6b909c01f435.jpg)

**Comment by fisharebest** [comment]
It seems that bing has retired this feature.

Now you can only submit sitemaps via their webmaster-tools site.

**Comment by LarsRabe** [comment]
Then this should be retired or link to the webmaster-tools site.

**Comment by LarsRabe** [comment]
Bump 🫣
See https://www.webtrees.net/index.php/forum/help-for-2-0/39347-sitemaps

**Comment by LarsRabe** [comment]
solved with commit 94582e9
