### ISSUE TITLE
Surnames with umlauts (ä, ö, ü)

### ISSUE THREAD

**Issue by arbor95** [fisharebest/webtrees#4776]
Names with umlauts (ä, ö, ü) are not shown in individuals and families lists if language is set to "Deutsch". I did not test other language settings.

When I search for persons with umlauts in the lists of individuals and families, and subdivide them according to first names, the letters A to Z are greyed out (see attachment: individuals list "Böhm" = 312 persons). 

This only applies if the language is set to "German". 
In English, all letters are displayed correctly.

or look at Struth: https://familienbuch-eichsfeld.de/index.php?route=%2Ftree%2FStruth
and then Köthe: 
search in EN: https://familienbuch-eichsfeld.de/index.php?route=%2Ftree%2FStruth%2Findividual-list&surname=KOTHE
search in DE: https://familienbuch-eichsfeld.de/index.php?route=%2Ftree%2FStruth%2Findividual-list&surname=KOETHE

**Comment by Morph3us2** [comment]
I'm using webtrees 2.1.16 just in German but can't reproduce the failure, even though we have the "ü" in our surname.

**Comment by arbor95** [comment]
> I'm using webtrees 2.1.16 just in German but can't reproduce the failure, even though we have the "ü" in our surname.

So you did not use the example above: proof yours (at least with a site - info, and usage)

**Comment by fisharebest** [comment]
> but can't reproduce the failure

I can reproduce it - and have just submitted a fix
