### ISSUE TITLE
I updated today my test sites' webtrees and vendor files. They included: Removing symfony/polyfill-ctype (v1.27.0) 

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#4777]
Now I get in the test and future sites fatal error:
"Warning: require(/home/amitys/future.amitys.com/vendor/composer/../symfony/polyfill-ctype/bootstrap.php): Failed to open stream: No such file or directory in /home/amitys/future.amitys.com/vendor/composer/autoload_real.php on line 71

Fatal error: Uncaught Error: Failed opening required '/home/amitys/future.amitys.com/vendor/composer/../symfony/polyfill-ctype/bootstrap.php' (include_path='.') in /home/amitys/future.amitys.com/vendor/composer/autoload_real.php:71 Stack trace: #0 /home/amitys/future.amitys.com/vendor/composer/autoload_real.php(61): composerRequiree4af25206f6291f0450638b36aceb78d() #1 /home/amitys/future.amitys.com/vendor/autoload.php(7): ComposerAutoloaderInite4af25206f6291f0450638b36aceb78d::getLoader() #2 /home/amitys/future.amitys.com/index.php(29): require('...') #3 {main} thrown in /home/amitys/future.amitys.com/vendor/composer/autoload_real.php on line 71"

**Comment by fisharebest** [comment]
I think that some of the files were not uploaded correctly.

I just copied the vendor files to your site, and it is now working.

**Comment by melizaa** [comment]
Thanks a lot!
