### ISSUE TITLE
[embedding html file] Unexpected token

### ISSUE THREAD

**Issue by andriej** [fisharebest/webtrees#4785]
I like to take copies of whole html websites with images embedded using `SingleFile` browser extension.
Often when I try to embed such file, I get error as below:
`SyntaxError: Unexpected token '<', "`

I guess it's parsing the preview of file or anyhow interact with it's contens.
Multiple retries of uploading the file always ends up the same - I'm removing all non-characted chars from file or auto generating one.

**Comment by fisharebest** [comment]
This error usually indicates that a JSON response was expected but an HTML response was received.

This almost always happens when some rype of wrb security/firewall app has blocked the request.  e.g. apache/mod-security

**Comment by andriej** [comment]
Thank you, will check with lower/disabled security settings.

**Comment by andriej** [comment]
You were right, it was WAF setting on website.
I'd like to keep it at highest level possible to have traffic filtered, but lowered it one level and it works.
