### ISSUE TITLE
Pedigree map: bottom text

### ISSUE THREAD

**Issue by arbor95** [fisharebest/webtrees#4789]
Bottom text is not at bottom on small devices (here with minimal theme)
![Screenshot_20230318-115247_Chrome](https://user-images.githubusercontent.com/6124739/226101252-f360b3fa-e3fa-4aaf-b357-91e1c0e228ed.jpg)

**Comment by ddrury** [comment]
Also visible on place hierarchy

**Comment by ddrury** [comment]
Fix submitted. In the meantime as a temporary measure add the following css to the css and js module in the control panel

```
.wt-pedigree-map-map, .wt-pedigree-map-sidebar,
.wt-place-hierarchy-map, .wt-place-hierarchy-sidebar,
.wt-places-tab-map, .wt-places-tab-sidebar {
	height: 70vh;
}

.wt-pedigree-map-wrapper, .wt-place-hierarchy-wrapper, .wt-places-tab-wrapper {
	height: auto;
}
```

**Comment by ungeahnt** [comment]
This issue is similar (or equal) to #3568. Is this then also fixed?

**Comment by ddrury** [comment]
I believe so, I don't speak German (sorry!) but as it stands the fix forces all the standard footer modules to the bottom. If impressum... is one of those then yes it will work.

Why not try temporarily adding the css mentioned above which achieves the same result as the fix albeit in a slightly more verbose manner

**Comment by ungeahnt** [comment]
> I don't speak German (sorry!)

nobody is perfect ;)

> Why not try temporarily adding the css ...
my post is more or less a 'link' between both issues ... only to keep in mind. I will test the fix with the next release
