### ISSUE TITLE
michelf markdown bug or feature?

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#479]
I've been playing with some new modules and came up with the following:

suppose I enter the following markdown'ed text (which renders as the 2nd line)

```
### Welcome to webtrees #WebtreesVersion#
Welcome to webtrees #WebtreesVersion
```

OK, escape the hashes 

```
### Welcome to webtrees \#WebtreesVersion\#
Welcome to webtrees #WebtreesVersion\
```

So add a final hash (the space before it is important)

```
### Welcome to webtrees \#WebtreesVersion\# #
Welcome to webtrees 1.7.0-dev
```

It seems to me that the michelf implementation is doing some sort of reverse scan to find the end of the header and is ignoring the escaping of the hashes. Would you agree this is a bug?

**Comment by fisharebest** [comment]
Yes, it looks like a bug in the library.

BTW - One of the reasons for choosing this particular library was PHP5.3 support.  I also considered http://commonmark.thephpleague.com but it requires PHP5.4.  It follows a clearly defined specification, which says:

> The optional closing sequence of #s must be preceded by a space

I think this library may be a better long-term solution, once we drop support for PHP5.3
