### ISSUE TITLE
Statistics - Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by MarkyJ1** [fisharebest/webtrees#4803]
Noticed this error today on my site in a few of the stats. Checked both current and beta releases and the problem occurs on both.

![stats_error](https://user-images.githubusercontent.com/105113537/229892009-29ba16a9-3a58-49b1-97e9-cf4f8a82091b.jpg)

**Comment by fisharebest** [comment]
Is there a URL where I can see this?

**Comment by MarkyJ1** [comment]
The screenshot was taken from the current release demo site.

Tried using different browsers and had the same issue although the message was slightly different.

Today it all works fine so maybe the problem was at my end - Windows 10.

I think this one can be closed.
