### ISSUE TITLE
Error in English text?

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#481]
I have no idea what the word "prepended" means in this sentence:

>>%s will be prepended to media filenames.

Neither Google translate knows the word nor the Cambridge dictionary.

I am not sure what you are trying to say here, so if this is an existing word, could you please explain the meaning.

**Comment by vytux-com** [comment]
means that text in %s will be added before the rest of the text, so in this case if %s contained "C:\test\" then this would be added to the front of all media filenames.

**Comment by fisharebest** [comment]
I asked several English speakers, who all know the meaning (opposite of "append").

Perhaps this is a new word, created by computer programmers.  e.g.  http://api.jquery.com/prepend/

But it does not exist in any of my dictionaries, so we should find a simpler word.

**Comment by fisharebest** [comment]
> Media filenames will be prefixed by %s.

**Comment by JustCarmen** [comment]
Clear. Thanks.

**Comment by wkitty42** [comment]
On 3/13/2015 7:33 PM, JustCarmen wrote:
> I have no idea what the word "prepended" means in this sentence:
>
>         %s will be prepended to media filenames.
>
> Neither Google translate knows the word nor the Cambridge dictionary.

prepended: added before

like appended is added after...
