### ISSUE TITLE
Use of ::backdrop css pseudo element

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4810]
Whilst fixing incorrect use of wt-global class (https://github.com/fisharebest/webtrees/pull/4808/commits/6c77a7e9b28e3a4ecfc5e8c276f2b3692c3f72f0) I discovered the ::backdrop css pseudo element and I wonder if we should apply it to all the standard themes like so

```
::backdrop, wt-global {
 ....
}
```
to ensure that the proper background is always applied on fullscreen (I can't see any problems at the moment so this would only be for futureproofing any new fullscreen implementations

(See https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop)

**Comment by fisharebest** [comment]
Thanks - I wasn't aware of `::backdrop`.  Sounds perfect.
You want to update the PR to use it?

Also, can you rename `wt-sidebar` to `wt-map-sidebar`?
The individual page has a sidebar which probably ought to have a class for styling - which probably ought to be called `wt-sidebar`.

**Comment by ddrury** [comment]
Ok, bear with me

**Comment by ddrury** [comment]
See https://github.com/fisharebest/webtrees/pull/4808
