### ISSUE TITLE
GEDCOM-L tags missing in input form

### ISSUE THREAD

**Issue by webtrees-pesz** [fisharebest/webtrees#4812]
If GEDCOM-L is enabled under 'Control Center - GEDCOM Tags', these custom tags will not be displayed in the input forms. The only way to insert new tags is to use the raw GEDCOM form. Is this a bug or a missing feature?

Best regards, Peter

**Comment by fisharebest** [comment]
Works for me.

If I enable GEDCOM-L, I see the tags on the edit forms.

e.g. when editing/adding a baptism, I see WITN, GODP, PLAC:_LOC, etc.

**Comment by webtrees-pesz** [comment]
Hello Greg,

the _GOV tag (GOV identifier) as a subtag of PLAC ist missing.

Best regards, Peter

**Comment by webtrees-pesz** [comment]
Thanks for your fast support.

Best regards, Peter
