### ISSUE TITLE
Address formatting

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#4822]
Less than ideal formatting seen in three different themes, shown in image attached.
![temp](https://github.com/fisharebest/webtrees/assets/5910274/56f9db35-119f-4309-b59c-3338a9ecd2a9)

**Comment by HonkXL** [comment]
Is this a duplicate of #4353 ?

**Comment by WGroleau** [comment]
Yes, its is.  I didn't remember seeing it and commenting.
