### ISSUE TITLE
Contradictory dates

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#4827]
In search results, I have a "J. L. Patison" with birth date estimated as 1898
But if I click on the name, the facts tab has an explicit birth date of 1880.

https://UniGen.us/tree/HHH/search-general?query=1880%20census&search_families=1&search_individuals=1&search_locations=0&search_notes=0&search_repositories=0&search_sources=1&search_trees%5B0%5D=HHH

https://UniGen.us/tree/HHH/individual/X185/J-L-Patison-X185

**Comment by MarkyJ1** [comment]
Is '1880' an actual birth date? If it is then I'd expect it to be clickable.

**Comment by WGroleau** [comment]
Hmmm.  Well, if it weren't an "actual birthdate," why would it be displayed on the INDI page as if it were?  It comes from
```
1 BIRT 1880
2 PLAC Elkhart Twp., Bates Co., Missouri, USA

```

**Comment by fisharebest** [comment]
Is the date valid?

If it was invalid (but looked visually like "1880"), then webtrees would calculate an estimated date for the list.

Hidden/non-printing characters?

Perhaps you could use the clippings cart to extract this individual and his immediate family?

**Comment by WGroleau** [comment]
I see the problem:
```
1 BIRT 1880
2 PLAC Elkhart Twp., Bates Co., Missouri, USA

```should be
```
1 BIRT
2 DATE 1880
2 PLAC Elkhart Twp., Bates Co., Missouri, USA

```

**Comment by fisharebest** [comment]
Ah! Obvious when you see it! :-)
