### ISSUE TITLE
Can't access family members

### ISSUE THREAD

**Issue by tintin7b** [fisharebest/webtrees#4835]
Hi,

Webtrees 2.1.16
havrebakken7.dk/anetavle

Webtrees has worked perfectly for me until yesterday where I added some new family members.
Nothing happens when clicking on any of my family members and the browser tab with webtrees is blocked for several minutes when I try.

Apparently i made a mistake. It seems that I added a family member twice  as mother and daughter (see snippet).
My problem is that I can't access the "daughter" so I can delete her again.
I don't know if that is the reason, but the issue happend after adding that family member and her husbond.
Can someone help me?

![image](https://github.com/fisharebest/webtrees/assets/135065861/ccff3de6-68aa-4af1-a4d3-622ce32da7e0)

Best Regards,
Torben Ingemann Nielsen

**Comment by FrankWarius** [comment]
I guess you need to delete the family between the two Betina's.
You can find the family entry in the change log

**Comment by tintin7b** [comment]
Thanks a lot, FrankWarius
Your trick did it 👍
