### ISSUE TITLE
Import of GEDCOM file without HEAD.CHAR

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#4838]
When generating GEDCOM files using ChatGPT there is sometimes no "1 CHAR UTF-8" in the HEAD. When importing such a file with webtrees the coding is not correct: Umlaute in the text are not recognized correctly: [Kleinm��nchen 123](https://ahnen.hartenthaler.eu/tree/bio_neu/)

I would expect that UTF-8 is the default when importing a GEDCOM without HEAD.CHAR.

The file was generated by Notepad++ after copy/paste from ChatGPT.
0 HEAD
1 SOUR OpenAI
2 NAME ChatGPT
2 VERS 4.0
1 DATE 19 JUN 2023
1 FILE hartenthaler.ged
1 GEDC
2 VERS 5.5
2 FORM LINEAGE-LINKED
0 @I1@ INDI
1 NAME Rudolf /Hartenthaler/
1 SEX M
1 BIRT
2 DATE 23 FEB 1907
2 PLAC Kleinmünchen 123
1 FAMC @F1@
0 @I2@ INDI
1 NAME Unbekannter /Vater/
1 SEX M
1 OCCU Arbeiter in einer Zementwarenfabrik
1 FAMS @F1@
0 @I3@ INDI
1 NAME Unbekannte /Mutter/
1 SEX F
1 OCCU Maurerhelferin und Hilfskraft in Fabriken
1 FAMS @F1@
1 FAMC @F2@
0 @I4@ INDI
1 NAME Franz /Unbekannt/
1 SEX M
1 BIRT
2 DATE EST 1900
1 FAMC @F2@
0 @I5@ INDI
1 NAME Maria /Hartenthaler/
1 SEX F
1 FAMC @F1@
0 @I6@ INDI
1 NAME Josef /Hartenthaler/
1 SEX M
1 FAMC @F1@
0 @F1@ FAM
1 HUSB @I2@
1 WIFE @I3@
1 CHIL @I1@
1 CHIL @I5@
1 CHIL @I6@
0 @F2@ FAM
1 CHIL @I4@
1 CHIL @I3@
0 TRLR

**Comment by hartenthaler** [comment]
[haitenthaler.ged.txt](https://github.com/fisharebest/webtrees/files/11853955/haitenthaler.ged.txt)

I tried it again with another file (attached - please remove ".txt" at the end of the filename). Generated by ChatGPT. Copy/paste to Notepad++. The Umlaut in "Oberösterreich" looks ok in Notepad++. Saved it on my Windows 11 PC and attached this file here. Tested it with the validator ShowMeGedcom - the error message appears that there is no CHAR in the HEAD which is ok; the umlaut in Oberösterreich is corrupted. Import this file to webtrees 2.1.16 and the umlaut is corrupted there, too.

But maybe this is an error in Notepad++. When I open the file in WordPad the line is corrupted, too.

> 2 PLAC Frankenmarkt, OberÃ¶sterreich, Austria

So it seems that Notepad++ is able to display this line correct, but it is stored already incorrect. I assume that the missing CHAR in HEAD is irrelevant. But I was able to transfer GEDCOM code generated by ChatGPT with umlauts without any problems following the same steps using Notepad++.

**Comment by hartenthaler** [comment]
When I open the file in the old fashioned "Editor" - it looks ok!

**Comment by fisharebest** [comment]
I can't reproduce this - because it was already fixed in #4738 ;-)
