### ISSUE TITLE
matomo integration: custom tracking code

### ISSUE THREAD

**Issue by HB9HIL** [fisharebest/webtrees#4842]
Hello guys

Would it be possible to let the administrator edit the matomo/piwik tracking manually? In the settings for the matomo plugin the tracking code is auto-generated but in case of some custom options it would be nice to give the admin a option to edit the tracking code manually. 

Thanks for discussing this.

Cheers

**Comment by HB9HIL** [comment]
I mean a)

some more configuration options. 

<img width="1078" alt="image" src="https://github.com/fisharebest/webtrees/assets/80885850/a3d9bfda-532d-4970-8547-a1d264d5459b">

As I mentioned, for example the possibility to use a custom tracking code of more configuration options. Why? Because the automatic generated tracking code uses "piwik.php" for the tracking engine after the main URL. The newer version of Matomo uses 'matomo.php'.

This is why the tracking in my case doesn't work.

**Comment by fisharebest** [comment]
> the automatic generated tracking code uses "piwik.php" 

I don't see `piwik.php` anywhere.

Perhaps show me the exact changes you've made / want to make?

**Comment by HB9HIL** [comment]
<img width="1136" alt="image" src="https://github.com/fisharebest/webtrees/assets/80885850/6543b79b-54a8-4c4f-a95b-59d9d4a71c2c">

The Tracking code generated by webtrees doesn't work like that.

**Comment by HB9HIL** [comment]
> I don't see `piwik.php` anywhere.

See Line 9

And there are some more differences

**Comment by HB9HIL** [comment]
> Perhaps show me the exact changes you've made / want to make?

The easiest solution would be to don't generate the matomo code automatically. Instead let the user paste in the tracking code generated by matomo.

**Comment by SunsetGolfer** [comment]
> > Perhaps show me the exact changes you've made / want to make?
> 
> The easiest solution would be to don't generate the matomo code automatically. Instead let the user paste in the tracking code generated by matomo.

Is this possible now? Would be really nice...

**Comment by HB9HIL** [comment]
> > Perhaps show me the exact changes you've made / want to make?
> 
> The easiest solution would be to don't generate the matomo code automatically. Instead let the user paste in the tracking code generated by matomo.

@fisharebest Any Update on that? 



@SunsetGolfer Unfortunaltely not.. Matomo does not work

**Comment by HB9HIL** [comment]
@SunsetGolfer 

A workaround for you

Go to file `resources/views/modules/matomo-analytics/snippet.phtml`

comment out (or delete) the script from `Line 12 to Line 24`

Copy your matomo tracking code from Matomo into that script. 

For me it works. I can't understand why the script is hardcoded and generated by webtrees. This is really bad.

**Comment by HB9HIL** [comment]
@SunsetGolfer 

<img width="749" alt="new matomo tracking code" src="https://github.com/fisharebest/webtrees/assets/80885850/68492d5f-543f-406d-9864-35d81a798623">

**Comment by SunsetGolfer** [comment]
@HB9HIL Thanks, will try that tomorrow...

**Comment by fisharebest** [comment]
> For me it works. I can't understand why the script is hardcoded and generated by webtrees. This is really bad.

webtrees provides two modules:

1) "CSS and JS".  This allows you to insert your snippet on every page.   You can insert content into both the `<head>` and `<body>` elements.

2) "Matomo/Piwik analytics" which generates the snippet automatically.  This module is designed for users who want it to "just work", and are not confident to edit javascript.  The JS snippet was created using the documentation from Matomo.

You said that you didn't want to use the standard snippet, because you wanted to customise it with additional tracking parameters.  The "CSS and JS" module is perfect for you!

**Comment by fisharebest** [comment]
> And I said the automatic generated tracking does not work with the latest version of matomo😉

I missed that bit.  A consequence of discussing two things in the same issue...

**Comment by HB9HIL** [comment]
> @SunsetGolfer
> 
> A workaround for you
> 
> Go to file `resources/views/modules/matomo-analytics/snippet.phtml`
> 
> comment out (or delete) the script from `Line 12 to Line 24`
> 
> Copy your matomo tracking code from Matomo into that file.
> 
> For me it works. I can't understand why the script is hardcoded and generated by webtrees. This is really bad.

Nevermind I found a workaround
