### ISSUE TITLE
Legend of Places tab on iPhone not visible

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#4844]
The legend of the "Places" tab is on an iPhone not visible. Only the first line "Birth" can be seen. All the other information is hidden behind the side menu.

![IMG_3335](https://github.com/fisharebest/webtrees/assets/6324175/8ad334cc-0ed9-4973-b5d5-2f4a18c5d300)

On a laptop everything looks ok. The error is there in the Vesta Places tab and the standard Places tab. This error was first discussed at https://github.com/JesseWebDotCom/webtrees-theme-modern/issues/25#issuecomment-1625900034
![Screenshot (372)](https://github.com/fisharebest/webtrees/assets/6324175/fbbd1ae4-798e-4a4f-a992-269dd5ba9f14)

**Comment by arbor95** [comment]
Hallo Hermann,
as far as I know the following css helps with this bug:
.wt-pedigree-map-map, .wt-pedigree-map-sidebar,
.wt-place-hierarchy-map, .wt-place-hierarchy-sidebar,
.wt-places-tab-map, .wt-places-tab-sidebar { height: 70vh; }
.wt-pedigree-map-wrapper, .wt-place-hierarchy-wrapper, .wt-places-tab-wrapper {	height: auto; }

You can test at freris.de .

**Comment by ddrury** [comment]
@arbor95 the css you list is a temporary fix. This [PR](https://github.com/fisharebest/webtrees/pull/4799) is the proper fix and will be available in the next webtrees release, however, from the description of the problem above I'm not entirely sure this is the solution (I hope I'm wrong!)

**Comment by hartenthaler** [comment]
In the meantime, I installed webtrees 2.1.17. The problem described here disappeared in that version (I can see now the map and the map legend just below the map - ok).

But the user interface of the iPhone is now much worse than before. As you can see the sidebar is now at the side and not below everything else. This looks very bad.

![IMG_3359](https://github.com/fisharebest/webtrees/assets/6324175/231e75be-2712-4926-8d9c-57eeef1ba0c6)

**Comment by hartenthaler** [comment]
I removed all custom CSS in the CSS&JS module, but the behaviour is still the same. But it is only the test system and it is only on the iPhone in portrait mode. If you like you can close this issue.
