### ISSUE TITLE
2.1.17: hamburger-menu on mobile doesn't work anymore

### ISSUE THREAD

**Issue by imc67** [fisharebest/webtrees#4846]
Since the last update to 2.1.17 the hamburger-menu isn't clickable.

Steps to reproduce:

1. open Webtrees in your mobile browser or make your desktop browser window small
2. click on the hamburger-menu
3. result: nothing happens

**Comment by arbor95** [comment]
That is for JustLight thema:
https://github.com/JustCarmen/webtrees-theme-justlight/issues/146

I already reported there.

**Comment by zhoueysun** [comment]
Thank you both. It’s good to know who that is specific to a particular theme.


Sent from Yahoo Mail for iPhone


On Sunday, July 16, 2023, 08:26, Franz Frese ***@***.***> wrote:




That is for JustLight thema:
JustCarmen/webtrees-theme-justlight#146

I already reported there.

**Comment by JustCarmen** [comment]
Fixed in https://github.com/JustCarmen/webtrees-theme-justlight/issues/146
