### ISSUE TITLE
SOUR:DATA:EVEN:PLAC:_GOV is shown as unknown Gedcom structure

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4849]
Subtag definition [here](https://github.com/fisharebest/webtrees/blob/d5a67ecc93b0e0a2a173314356281c2abacf8f4b/app/Gedcom.php#L1100) is not aligned with subtags defined [here and in the following lines](https://github.com/fisharebest/webtrees/blob/d5a67ecc93b0e0a2a173314356281c2abacf8f4b/app/CustomTags/GedcomL.php#L211) (_GOV is missing).

**Comment by Jefferson49** [comment]
Screenshot from webtrees 2.1.17: 
SOUR:DATA:EVEN:PLAC:_GOV is shown in red as an unknown structure, even if no data was entered.

![SOUR-DATA-EVEN-PLAC-_GOV](https://github.com/fisharebest/webtrees/assets/81484983/3d7a8a9b-16d1-494f-b8f7-95cdea83013b)
