### ISSUE TITLE
Searching across multiple trees is no longer possible

### ISSUE THREAD

**Issue by martingeusen** [fisharebest/webtrees#4851]
Your not able to choose other trees at this position with 2.1.17
![grafik](https://github.com/fisharebest/webtrees/assets/80057858/ba946f98-b969-40b7-8c2e-e53ba9e06b79)

**Comment by fisharebest** [comment]
This works for me. See the demo site - https://dev.webtrees.net/demo-stable/index.php?route=%2Fdemo-stable%2Ftree%2Fdemo%2Fsearch-general

Can you provide more details, or is there a URL where I can see this?

**Comment by martingeusen** [comment]
It happens if you have more than three trees. At that point webtrees starts to display a vertical list instead of a horizontal list like on the demo-site.
Please check https://webtree-test.geusen.de/index.php?route=%2Ftree%2FOEV5%2Fsearch-general&query=peter%20rhein
it happens also on my two other instances of webtrees and with several browsers
there is no visible php-error, and no matching entry in log-files

**Comment by fisharebest** [comment]
Looks like a javascript error, that prevents the "show more" dropdown list from expanding.

**Comment by luenissla** [comment]
The same problem here: [Datenpool](https://datenpool.bvff.de/tree/Datenpool/search-general# )

**Comment by fisharebest** [comment]
This is caused by the upgrade from bootstrap 5.2 to 5.3.

https://github.com/twbs/bootstrap/issues/38974

**Comment by fisharebest** [comment]
This has now been fixed in [bootstrap 5.3.2](https://github.com/twbs/bootstrap/releases/tag/v5.3.2)

**Comment by mpwt** [comment]
I'm not sure it's fixed with the update to v2.1.18. The pedigree selection button still does not work.

On my page https://ffp.bauschaffen.de I have five family trees and it is always searched only in the currently selected one. The selection of all does not work.
