### ISSUE TITLE
Bug: personal facts module

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4853]
If the historic facts module has content and is enabled and an individual has no personal facts recorded then the message "There are no facts for this individual." should be displayed.

This doesn't happen because the historic events are included in the personal facts collection. 

See [this commit](https://github.com/fisharebest/webtrees/pull/4861/commits/d218cc45523e80f5c6421267a2e7594d7cbfa893)

**Comment by fisharebest** [comment]
Presumably, the same is true of events of relatives/associates.

**Comment by ddrury** [comment]
No, they are never merged with anything else, it's only the individual facts that get the others merged
```
        $individual_facts = $individual_facts
            ->merge($family_facts)
            ->merge($relative_facts)
            ->merge($associate_facts)
            ->merge($historic_facts);
```
I've made a simple fix in https://github.com/fisharebest/webtrees/pull/4854, just add this line before the merge 
` $has_individual_facts = $individual_facts->isNotEmpty()`;
then include it in the call to the view and test for it in the view

**Comment by ddrury** [comment]
BTW maybe a good idea to merge into a more appropriate name ($all_facts?)

**Comment by arbor95** [comment]
Has this been done or is it obsolete?

**Comment by fisharebest** [comment]
The purpose of this text is simply to prevent a completely empty tab - which could be confusing.

> If the historic facts module has content and is enabled and an individual has no personal facts recorded

We only show historic events that occur between the first and last personal event with a date.

So there should never be historic events and no personal events.

If this is happening, then it should be a separate bug report.
