### ISSUE TITLE
Problems displaying media - image failed to load

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4858]
We have problems displaying some documents, e.g. https://wbt.warius.info/tree/Warius/media/X1679/1873-11-30-Backer-Hermann-Otto-Willy-Taufe.

If you click on the thumbnail without being logged in, "image failed to load" appears. If you are logged in, the image is loaded normally. Hypothesis: it could be due to the generation of the watermark.

This concerns newer images, older ones load (unregistered) without problems (cache?).

 I became aware of the problem through Google Bot:
https://wbt.warius.info/tree/Warius/media-download?xref=X1679&fact_id=0b35e7d5af2cef9b193d0e46f1fbb323&disposition=inline&mark=1
leads to
Allowed memory size of 268435456 bytes exhausted (tried to allocate 97377425 bytes)
D:\web\WT21Git\webtrees\vendor\intervention\image\src\Intervention\Image\Gd\Commands\ResizeCommand.php: 58 
Workaround: Blocking media-download in robots-txt

**Comment by arbor95** [comment]
So you can close this issue?
