### ISSUE TITLE
Custom tags for TNG

### ISSUE THREAD

**Issue by webtrees-pesz** [fisharebest/webtrees#4862]
Please support following custom tags for TNG:
- _PLAC.CONT
- _PLAC.MAP
- _PLAC.MAP.LATI
- _PLAC.MAP.LONG
- _PLAC.NOTE
- _PLAC._GOV
- INDI.NAME.OBJE
- INDI.NAME.SOUR.QUAY
- INDI._LIVING
- FAM._FREL
- FAM._MREL
- OBJE.FORM
- OBJE.TITL
- OBJE.TYPE
- *.NOTE.SOUR

**Comment by fisharebest** [comment]
Is `_PLAC` a top-level object?

`INDI.NAME.SOUR.QUAY` - I think this is standard GEDCOM.

* `INDI:_LIVING`
* `FAM:_FREL`
* `FAM:_MREL`

What values do we see in these tags?  Keywords?  Free text?  Links?

**Comment by webtrees-pesz** [comment]
Hello Greg,

I found following in the TNG_Wiki:

Processing by TNG
Here are some specific considerations that apply to TNG's handling of GEDCOM files.

Proprietary Tags
Any proprietary event tag (e.g. _MILT for military events) can be treated as an event in TNG.

Other proprietary tags that are typically treated as "Pure Attributes" include:

_MREL and _FREL, which characterize the relationship (Natural, Adoptive, Foster, etc.) between a child and a parent.
_PRIM means "Primary Multimedia Object", and is expected to be a level 2 tag that is subordinate to a level 1 Multimedia Object reference in an Individual record. It is used to designate one Multimedia Object as the primary photo for an Individual.
_PHOTO is an alternate way to identify the primary photo for an Individual, and is not understood by TNG. _PHOTO tags needs to be converted to _PRIM tags.
_LIVING designates an individual as living
_PRIVATE designates an individual or family as private.
See [Desktop gotchas](https://www.tng.lythgoes.net/wiki/index.php/Desktop_gotchas) to read about GEDCOM quirks in some PC software packages, and the need to convert some GEDCOM files before they can be imported into TNG.

_PLAC is a top-level object like _LOC

**Comment by fisharebest** [comment]
> _PLAC is a top-level object like _LOC

According to my notes, TNG `_PLAC` tags do not have an XREF, and so we cannot import them as records.

Instead, we just import the `LAT`/`LONG` into the the `wt_place_location` table.

I think we should be able to support the others.

**Comment by arbor95** [comment]
Do we want an export for TNG and others?

**Comment by fisharebest** [comment]
We shouldn't **export** `_PLAC` records without an XREF, as this would be invalid GEDCOM.

But we should be able to recognise/display other custom tags.  I will add definitions for the ones listed above.
