### ISSUE TITLE
Deaths report consider _MARNM instead of NAME.TYPE=married

### ISSUE THREAD

**Issue by webtrees-pesz** [fisharebest/webtrees#4864]
_MARNM is no longer supported by webtrees. However, it is still used in the Deaths report. On the other hand, NAME.TYPE=married is not supported in the report.

**Comment by reteP-riS** [comment]
> _MARNM is no longer supported by webtrees.

This is not correct. Although webtrees does no longer offer forms that create _MARNM and _AKA records, you could add these custom tags as raw GEDCOM and - what may be more important - when importing GEDCOM files webtrees will accept these custom tags. The respective data fix is optional.

Nevertheless I agree that NAME.TYPE=married should be added as a search criteria or filter criteria to the respective reports in addition to _MARNM.

**Comment by fisharebest** [comment]
I have never noticed this option before :-)
