### ISSUE TITLE
Lists / Families

### ISSUE THREAD

**Issue by arbor95** [fisharebest/webtrees#4865]
once clicked "All" and then clicked a shown family (for example Armstrong-Jones) I expect only the 5 Armstrong-Jones families are shown, but I get all the families.

all - link:
https://dev.webtrees.net/demo-stable/index.php?route=%2Fdemo-stable%2Ftree%2Fdemo%2Ffamily-list&show_all=yes&show_marnm=
Armstrong - link:
https://dev.webtrees.net/demo-stable/index.php?route=%2Fdemo-stable%2Ftree%2Fdemo%2Ffamily-list&surname=Armstrong-Jones&show=indi&show_all=yes&show_marnm=
result:
https://dev.webtrees.net/demo-stable/index.php?route=%2Fdemo-stable%2Ftree%2Fdemo%2Ffamily-list&alpha=&falpha=&show=indi&show_all=yes&show_all_firstnames=&show_marnm=&surname=ARMSTRONG-JONES

**Comment by arbor95** [comment]
perhaps the solution can be like:
                            echo view('lists/surnames-table', [
                                'families' => $this->families,
                                'module'   => $this,
                                'order'    => [[0, 'asc']],
                                'params'   => ['show' => 'indi'] + ['show_all' => ''] + $params,
                                'surnames' => $surns,
                                'tree'     => $tree,
                            ]);
in the IndividualListModule.php

**Comment by webtrees-pesz** [comment]
I have a similar problem:
when I click 'All', then I see all family names. If I select one of them, then I get only 1 person, which does not fit with this name.
The same when I click "Show the list of individuals".

It seems to be a bug.

**Comment by arbor95** [comment]
without a link to that case in your site, we can only guess. And we should know which list you called ( indi or family ). 
If its family it may be the name of the spouse.

**Comment by fisharebest** [comment]
> perhaps the solution can be like

Thanks.  This is the solution.

**Comment by webtrees-pesz** [comment]
After loading the fixed module IndividualListModule.php I get following error:
all to undefined method Fisharebest\Webtrees\Registry::container() …/app/Module/IndividualListModule.php:123
#0 …/app/Module/ModuleListTrait.php(59): Fisharebest\Webtrees\Module\IndividualListModule->listUrl()
#1 …/app/Module/ListsMenuModule.php(90): Fisharebest\Webtrees\Module\IndividualListModule->listMenu()
#2 [internal function]: Fisharebest\Webtrees\Module\ListsMenuModule::Fisharebest\Webtrees\Module\{closure}()
#3 …/vendor/illuminate/collections/Collection.php(695): array_map()
#4 …/app/Module/ListsMenuModule.php(91): Illuminate\Support\Collection->map()
#5 …/app/Module/ModuleThemeTrait.php(495): Fisharebest\Webtrees\Module\ListsMenuModule->getMenu()
#6 [internal function]: Fisharebest\Webtrees\Module\CloudsTheme::Fisharebest\Webtrees\Module\{closure}()
#7 …/vendor/illuminate/collections/Collection.php(695): array_map()
#8 …/app/Module/ModuleThemeTrait.php(495): Illuminate\Support\Collection->map()
#9 …/app/Module/CloudsTheme.php(55): Fisharebest\Webtrees\Module\CloudsTheme->baseGenealogyMenu()
#10 …/modules_v4/vesta_classic_look_and_feel/resources/views/layouts/default.phtml(127): Fisharebest\Webtrees\Module\CloudsTheme->genealogyMenu()
#11 …/app/View.php(183): include('...')
#12 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#13 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#14 …/app/Http/ViewResponseTrait.php(54): view()
#15 …/app/Http/RequestHandlers/LoginPage.php(110): Fisharebest\Webtrees\Http\RequestHandlers\LoginPage->viewResponse()
#16 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\LoginPage->handle()
#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#18 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(277): Middleland\Dispatcher->handle()
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule->process()
#20 …/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher->handle()
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#22 …/app/Module/CheckForNewVersion.php(122): Middleland\Dispatcher->handle()
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process()
#24 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle()
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#27 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#28 …/app/Http/Middleware/Router.php(163): Fisharebest\Webtrees\Webtrees::dispatch()
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#30 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#32 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#34 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
#35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#36 …/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher->handle()
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
#38 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#39 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#40 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#42 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#44 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#46 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#48 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#50 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#52 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#54 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle()
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#56 …/app/Http/Middleware/BadBotBlocker.php(287): Middleland\Dispatcher->handle()
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#58 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#59 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#60 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#61 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#62 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#63 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#64 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#65 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#66 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#67 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle()
#68 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#69 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#70 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#71 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#72 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#73 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#74 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#75 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#76 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#77 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#78 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#79 {main}

**Comment by webtrees-pesz** [comment]
> without a link to that case in your site, we can only guess. And we should know which list you called ( indi or family ). If its family it may be the name of the spouse.

https://mustermann.genonline.de/tree/Mustermann/individual-list?show_all=yes&show_marnm=#

**Comment by fisharebest** [comment]
> After loading the fixed module IndividualListModule.php I get following error:

I guess you used the version from the `main` branch, instead of the `2.1` branch.

**Comment by webtrees-pesz** [comment]
Thx, Greg. You are right - wrong branch.

But now, when I click 'All', then I see all family names. When I click "Show the list of individuals" in the next step, I see only one person instead of all. 
See https://mustermann.genonline.de/tree/Mustermann/individual-list?show_all=yes&show_marnm=#

**Comment by BertKoor** [comment]
Seems like this also fixes issue #4700

**Comment by reteP-riS** [comment]
It seems that the query always returns only those individuals which have one name record (regular, _AKA, _MARNM) without a surname surrounded by slashes!

**Comment by arbor95** [comment]
#4700 is not fixed with the above:

"All" in list/individuals does not show the individuals
and
"All" in list/families does not show the spouses (families)
