### ISSUE TITLE
Lists for Families or Individuals for subselection "All"

### ISSUE THREAD

**Issue by arbor95** [fisharebest/webtrees#4870]
since version 2.1.14
"All" in list/individuals does not show all the individuals
and
"All" in list/families does not show all the spouses (families)

**Comment by arbor95** [comment]
I suppose this problem can be solved, if you surround line 703 to 708
        if ($surnames === []) {
            // SURN, with no surname
            $query->where('n_surn', '=', $surname);
        } else {
            $query->whereIn($this->binaryColumn('n_surname'), $surnames);
        }
with
if ($surname !== '') {
}
I did not check $surname beeing empty on calling, but should be easy to do for selection of "All".

**Comment by Export33** [comment]
And even if you select a family in the list, the result still shows zero results.

**Comment by JustCarmen** [comment]
This is the same issue as https://github.com/fisharebest/webtrees/issues/4700

**Comment by JustCarmen** [comment]
I've found a workaround that might work for you too:

https://github.com/fisharebest/webtrees/issues/4700#issuecomment-1722539139
