### ISSUE TITLE
Lists for Families or Individuals with "Surname prefix" included within /<name>/

### ISSUE THREAD

**Issue by arbor95** [fisharebest/webtrees#4872]
have a look at in "live demo dev". You see following Indi:

![Screenshot_20230901-234442_Chrome](https://github.com/fisharebest/webtrees/assets/6124739/0165a019-7ec2-42fb-a17d-be340e15942d)

clicking the List for Individual you can see her surname to select (as de Marteaux) under First Letter "M"

![Screenshot_20230901-234536_Chrome](https://github.com/fisharebest/webtrees/assets/6124739/72578c78-1d09-4392-a463-01d9986deb30)

But clicking onto the surname changes the selection to First Letter of surname to "D" without result.

![Screenshot_20230901-234601_Chrome](https://github.com/fisharebest/webtrees/assets/6124739/955ae67f-c2a6-4596-b831-07edc33fd55a)

**Comment by JustCarmen** [comment]
I can confirm this issue. In the Netherlands surnames with prefixes are very common. For example this list containing surnames starting with the letter 'G': https://wijzijnfamilie.nl/tree/wijzijnfamilie/individual-list?alpha=G&show_marnm=
It contains a lot of surnames with prefixes starting with 'Van'. Clicking on the link opens the alphabet under the letter 'V' (instead of 'G') and then shows an empty table without any results.

**Comment by arbor95** [comment]
I could solve this problem by changing surnames-table.phtml in resources/views/lists line 63
from
`<a href="<?= e($module->listUrl($tree, ['surname' => $surname] + $params)) ?>" class="ut"><?= e($surname) ?></a>`
to
`<a href="<?= e($module->listUrl($tree, ['surname' => $surn] + $params)) ?>" class="ut"><?= e($surname) ?></a>`

This will change the links query-parameter surname from the cases-sensitive surname variant to the uppercase one.

**Comment by JustCarmen** [comment]
> I could solve this problem by changing surnames-table.phtml in resources/views/lists line 63
> from
> <a href="<?= e($module->listUrl($tree, ['surname' => $surname] + $params)) ?>" class="ut"><?= e($surname) ?></a>
> to
> <a href="<?= e($module->listUrl($tree, ['surname' => $surn] + $params)) ?>" class="ut"><?= e($surname) ?></a>
> 
> This will change the links query-parameter surname from the cases-sensitive surname variant to the uppercase one:
> 
> "de Marteaux" to "MARTEAUX"

Thanks. This works.

**Comment by fisharebest** [comment]
@arbor95 - thanks for the fix.
