### ISSUE TITLE
Individual lists showing incorrect results

### ISSUE THREAD

**Issue by andrewgoz** [fisharebest/webtrees#4879]
This is using webtrees 2.1.17

On my webtrees, selecting "M" individuals shows a large selection:

http://mncp.scss.dyndns.info/tree/mncp.ged/individual-list?show=surn&show_marnm=yes&alpha=M

If I click on "McARTHUR (19)" instead of getting the expected list of 19 results I get no results and the heading indicates the search was for "MCARTHUR" (uppercase 'C').

http://mncp.scss.dyndns.info/tree/mncp.ged/individual-list?alpha=M&falpha=&show=indi&show_all=&show_all_firstnames=&show_marnm=yes&surname=MCARTHUR

If instead of "McARTHUR (19)" I click on "MACARTHUR (1)" immediately above it, I don't get the expected single "MACARTHUR" result, instead I get a combined list of "MACARTHUR" (1 result) and "McARTHUR" (19 results - the ones I wanted previously) for a total of 20 results.

http://mncp.scss.dyndns.info/tree/mncp.ged/individual-list?surname=MACARTHUR&show=indi&alpha=M&show_marnm=yes

I expect webtrees to show 1 result when clicking on "MACARTHUR (1)" and 19 results when clicking on "McARTHUR (19)".

Edit: I have Administrator access to this site, and the results do not change whether I am logged in or not.

**Comment by JustCarmen** [comment]
I think this is related to #4872. This was fixed earlier this week and will be in the next release. You could try to load the 5 files from [this commit](https://github.com/fisharebest/webtrees/commit/236826542d96a386a0e11fece6262b42cb7d4cdd) to see if it makes any difference.

**Comment by andrewgoz** [comment]
I believe #4872 relates to surname prefixes (SPFX), which are not present in any of the names in my report.

I had thought the issue might be some sort of case sensitivity after noting that the results page for "McARTHUR" was actually headed "MCARTHUR", but after adding a test individual with an all-caps "MCARTHUR", clicking on the new "MCARTHUR (1)" produces an empty result list (same as "McARTHUR (19)"), while clicking on "MACARTHUR (1)" now produces a list with 21 results and has a heading "MACARTHUR/MCARTHUR/McARTHUR".

**Comment by andrewgoz** [comment]
One more comment. I remembered I had a test webtrees 2.1.16 active and checked its behaviour. Both "MACARTHUR" and "McARTHUR" produce the exact same combined results page for "MACARTHUR/McARTHUR".

That is much better. My preference would be to not combine names, but at least the "McARTHUR" page showed something.

**Comment by fisharebest** [comment]
There are several issues with the logic on this page.

Originally, we used MySQL collation rules to match letters with accents, upper/lower case.

However, this doesn't work for other databases (and not all languages).  So, the logic was rewritten to work in PHP.

I've rewritten it.  But before submitting the fix, I need to add lots more test-scripts to make sure we don't introduce any regressions during future updates.
