### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by HRN-webtrees** [fisharebest/webtrees#488]
In Control panel -> Website -> Languages there are no languages to choose from.
I can only see Save button and horizontal scroll bar

**Comment by fisharebest** [comment]
The list comes from the `*.mo` files in the `/languages/` folder.

I see them all on my dev server and the demo server.

Do you have any `.mo` files?

**Comment by HRN-webtrees** [comment]
Yes, I have all .mo files in place

**Comment by HRN-webtrees** [comment]
Seems to be a Chrome issue. Looks fine in FF and IE

**Comment by vytux-com** [comment]
I can confirm that this is an issue in Chrome and also if disable this line in css (via developer tools it's OK) 

-webkit-columns: 4 150px;
