### ISSUE TITLE
Error in Manage media -> Unused files

### ISSUE THREAD

**Issue by gregoiregentil** [fisharebest/webtrees#4881]
I'm on 2.1.17. In Manage media, if I select "Unused files", I get the following error. Any idea what's wrong?

DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by fisharebest** [comment]
See https://webtrees.net/faq/xhr for how to find the underlying error.

**Comment by gregoiregentil** [comment]
It was a problem of memory size allocation in php. I increase the limit. Thank you.
