### ISSUE TITLE
Individuals — All and Families — All do not show all Individuals respective Families

### ISSUE THREAD

**Issue by arbor95** [fisharebest/webtrees#4888]
using the current github code (an issue for this has been opened, but it seems to be closed now, cause I cant find to reopen):
Individuals — All and Families — All do not show all Individuals respective Families.

the subselection (list of all surnames (groups)) of familynames is shown (all should not mean all surnames, but all Individuals / families)
So I will never see all Individuals / Families (but I expect that).

**Comment by fisharebest** [comment]
"All" means "All surnames".  It excludes "No surname" and "Unknown surname".

This is the logic that was inherited from PhpGedView.  It has been like this for 20 years.

**Comment by arbor95** [comment]
For this logic you do not need a subselection (as I do understand, and that has recently been discussed in the forum).
There is no additional functionality showing the list of surnames (written in full), you get the same results, if only the first letters are shown.
Following your understanding, I extend:
"Individuals — All and Families — All do not show all Individuals respective Families", that have a surname (possibly extendable by those excluded).

**Comment by arbor95** [comment]
So remove All from selection
