### ISSUE TITLE
Linked Records

### ISSUE THREAD

**Issue by oddityoverseer13** [fisharebest/webtrees#489]
I'm not sure if this feature already exists, so if it does, please let me know.

I was just messing with webtree's ability to have multiple family trees. I was wondering what would happen if they had someone in common. For example, I have just been in contact with someone who is very distantly related to me. Our common ancestory is my 10x great grandfather. This other person has done his own research and has his own GEDCOM data. What I would like is to have that common ancestor appear in both trees, (as well as any further ancestors that we discover), but the descendants be in separate trees.

Is this available/possible/feasible?

**Comment by oddityoverseer13** [comment]
As a test, I tried the "merge records" function in the admin interface, and found out that's not what I want. That simply merged a person from one tree into another, removing the person from the first tree. I'm curious if that's what it's supposed to do, because it replaced the ID of the person in the first tree, with the ID from the second tree, which screwed up my data. (eg: Person A has ID "P316" in Tree A. I merged Person A into Tree B. In the GEDCOM, I now I have Person A in Tree B, with ID "I1", and in Tree A, all instances of "P316" got replaced with "I1", which is actually a different person.)

**Comment by fisharebest** [comment]
> Is this available/possible/feasible?

Internally, webtrees only has one set of data for privacy, etc.  Therefore any code that attempted to use records from different trees ran into problems, as the privacy rules from the wrong tree were used.

The next release has a complete rewrite of this, and it will be able to do this.  Currently, the search pages are the only place we need to show records from different trees on the same page.

This fixes the main obstacle in linking records from different trees.  However, a few others remain.

I doubt it will ever be possible to seamlessly link between trees.  For example, the privacy settings for one tree (e.g. can see living people within X steps - and this takes you into another tree) may conflict with privacy settings in the other tree.

> As a test, I tried the "merge records" function in the admin interface,

That's already been "fixed" for the next release.  It only allows you to merge records from the same tree.
