### ISSUE TITLE
Error message during export of a GEDCOM file

### ISSUE THREAD

**Issue by webtrees-pesz** [fisharebest/webtrees#4891]
I get the following error message when I try to export a GEDCOM file to my computer:
Allowed memory size of 134217728 bytes exhausted (tried to allocate 39995728 bytes)
/var/www/vhosts/.../httpdocs/webtrees/app/Http/Middleware/CompressResponse.php: 86

The tree contains approximately 61,500 individuals. When I download the tree to the server, the export ends without error. The file on the server has 32 MB. The maximum memory size on the server is 128 MB.

Is this a bug?

**Comment by fisharebest** [comment]
I guess this is the same issue as #4839
