### ISSUE TITLE
Surname filter ignores names like McDonald - second capital

### ISSUE THREAD

**Issue by krmcelhinney** [fisharebest/webtrees#4892]
The family or individual list does not show details of names with second capital eg McDonald, McDowel, McElhinney, McInerny, McEnzie. When you select from menu 'list>family' all the names appear with their record count, however, when you click one of the names above - no records appear. All the names without the second capital work fine. 
This can be seen in my webtrees site from following link.

http://family.mcelhinney.net.au/index.php?route=%2Ftree%2Fmcelhinney%2Ffamily-list&alpha=M&show_marnm=

Regards
Ken

**Comment by fisharebest** [comment]
This was fixed as part of #4700.  You should be able to test this at https://dev.webtrees.net/demo-dev

The fix will be included in the next release.
