### ISSUE TITLE
Place Hierarchy layout issue

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#4893]
The webtrees dropdown menu elements do not stack properly with respect to certain leaflet map elements.
See attached screenshot from demo server.
Setting a z-index of 1001 on the entire header tag fixes the issue (until some content with an even higher z-index comes along ...), but ther may be a more robust way of fixing this?

<img width="716" alt="dropdown" src="https://github.com/fisharebest/webtrees/assets/18174787/1e7bdd25-d786-4216-a375-eafea34fdd00">

**Comment by fisharebest** [comment]
The vendor CSS for the leaflet (map) library sets a `z-index` on this control (and the one on the left) at `1000`.

I can't see why this is needed.  If I remove it, then it still seems to work.

But to be safe, I'll override it at `999`.
