### ISSUE TITLE
Log Errors

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#4898]
I see lots of these errors in the wt log

Undefined array key &quot;MCLVER&quot; …/app/Module/IndividualListModule.php:455 #0 …/app/Module/IndividualListModule.php(455): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}() #1 …/app/Http/Middleware/RequestHandler.php(52): Fisharebest\Webtrees\Module\IndividualListModule-&gt;handle() #2 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler-&gt;process() #3 …/app/Module/CheckForNewVersion.php(122): Middleland\Dispatcher-&gt;handle() #4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion-&gt;process() #5 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher-&gt;handle() #6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process() #7 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #8 …/app/Http/Middleware/Router.php(166): Middleland\Dispatcher-&gt;dispatch() #9 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router-&gt;process() #10 …/app/Http/Middleware/BootModules.php(58): Middleland\Dispatcher-&gt;handle() #11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules-&gt;process() #12 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher-&gt;handle() #13 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags-&gt;process() #14 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher-&gt;handle() #15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes-&gt;process() #16 …/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher-&gt;handle() #17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion-&gt;process() #18 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher-&gt;handle() #19 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(30): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}() #20 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection-&gt;transaction() #21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process() #22 …/app/Http/Middleware/DoHousekeeping.php(71): Middleland\Dispatcher-&gt;handle() #23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process() #24 …/app/Http/Middleware/UseTheme.php(66): Middleland\Dispatcher-&gt;handle() #25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process() #26 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher-&gt;handle() #27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process() #28 …/app/Http/Middleware/UseLanguage.php(69): Middleland\Dispatcher-&gt;handle() #29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process() #30 …/app/Http/Middleware/UseSession.php(79): Middleland\Dispatcher-&gt;handle() #31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process() #32 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher-&gt;handle() #33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process() #34 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher-&gt;handle() #35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process() #36 …/app/Http/Middleware/BadBotBlocker.php(289): Middleland\Dispatcher-&gt;handle() #37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process() #38 …/app/Http/Middleware/CompressResponse.php(71): Middleland\Dispatcher-&gt;handle() #39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process() #40 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher-&gt;handle() #41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength-&gt;process() #42 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher-&gt;handle() #43 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp-&gt;process() #44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process() #45 …/app/Http/Middleware/PublicFiles.php(62): Middleland\Dispatcher-&gt;handle() #46 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PublicFiles-&gt;process() #47 …/app/Http/Middleware/HandleExceptions.php(89): Middleland\Dispatcher-&gt;handle() #48 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process() #49 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher-&gt;handle() #50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process() #51 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher-&gt;handle() #52 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process() #53 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher-&gt;handle() #54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process() #55 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher-&gt;handle() #56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process() #57 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #58 …/app/Webtrees.php(284): Middleland\Dispatcher-&gt;dispatch() #59 …/app/Webtrees.php(252): Fisharebest\Webtrees\Webtrees-&gt;httpRequest() #60 …/index.php(32): Fisharebest\Webtrees\Webtrees-&gt;run() #61 {main}

**Comment by heiler** [comment]
I also see theses errors, version 2.1.18.

**Comment by fisharebest** [comment]
Are you able to correlate the times of these errors with your HTTP access logs?

Do the requests come from interactive users or from search engines?

**Comment by makitso** [comment]
Sorry Greg, I should have provided this information at the time I saw the errors.  IIRC,  there were no errors in my HTTP server logs.  As for access logs, not sure of what date I saw these and the "Two weeks ago" notation is not very exact.

**Comment by heiler** [comment]
I checked two entries: one referred to bingbot, the other to antbot.
