### ISSUE TITLE
content for meta description is missing in 2.1.18, if logged-in

### ISSUE THREAD

**Issue by arbor95** [fisharebest/webtrees#4902]
if logged-in:
Although the desired content is set in Control panel, Manage family trees, Preferences, Website, Description META tag
the content result in webpage is empty:
`<meta name="description" content="">`

**Comment by fisharebest** [comment]
This information is included the tree's home-page - but not the individual/family/chart/etc. pages.

**Comment by fisharebest** [comment]
(The individual/family pages have their own meta-description).

**Comment by arbor95** [comment]
Thx for your info.
