### ISSUE TITLE
Error with individual and Family lists

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4904]
Have just updated my test system to the latest code (https://github.com/fisharebest/webtrees/commit/6e8002182a6bbfa2316898120b7075a4beb047ff) and I now get the following messages for both the Individual & Family list pages

_Firefox has detected that the server is redirecting the request for this address in a way that will never complete._

and if I go back to the previous page I see a number of messages: _There are no individuals with the surname ““_ (I guess each message corresponds to a redirect attempt)

UPDATE: Seems to only fail when called from "My page" If called from an individuals page then it works

**Comment by fisharebest** [comment]
Dang.  I know what I've done, without looking at the code.

**Comment by fisharebest** [comment]
Actually no - I can't reproduce this.  What is the link that you are following from "My page"?

**Comment by ddrury** [comment]
![demo](https://github.com/fisharebest/webtrees/assets/104515/69793c81-9874-421b-87ea-d17db5ecae0b)

**Comment by ddrury** [comment]
Changing line 219 of app\Module\IndividualListModule.php to   `if ($surname !== '' && !array_key_exists($surname, $all_surns)) {` seems to solve the problem

**Comment by fisharebest** [comment]
That was the fix I had in mind for my first comment.  But couldn't reproduce the error.  Will have another look later.

**Comment by ddrury** [comment]
I think my solution above is back to front in that you need to fail when there is no surname parameter, maybe valid urls within webtrees should always have a surname parameter of some sort

**Comment by fisharebest** [comment]
All my test trees contain at least one individual without a surname.  Hence the `array_key_exist` check always passed, even when `$surname === ''`
