### ISSUE TITLE
General logout after 30 minutes

### ISSUE THREAD

**Issue by webtrees-pesz** [fisharebest/webtrees#4906]
After 30 minutes of logging in, you are automatically logged out, even if there has been activity during this time. This is particularly unpleasant if the data entered is lost shortly before an update. webtrees runs with version 2.1.18 and PHP 8.2.

**Comment by mathiasbockwoldt** [comment]
Probably the same as #4869

**Comment by webtrees-pesz** [comment]
Yes, it seems to be the same problem. Thanks for the hint. But there has been no progress on #4869 for more than 10 weeks.
