### ISSUE TITLE
All button text should start with capital letter

### ISSUE THREAD

**Issue by durangod** [fisharebest/webtrees#4910]
Hi,  please use PHP ucwords() on all button text.  All button text first letters should be capitalized.

Thanks :)

**Comment by fisharebest** [comment]
I like lower case :-)

It is why the project is called `webtrees` and not `Webtrees`.

Go to the control panel, and enable the module "CSS and JS".

Now add the following to the `<head>` section:

```
<style>
.btn { text-transform: capitalize; }
btn span { display: inline-block; text-transform: capitalize; }
</style>
```

This should give you the effect you are after.

**Comment by fisharebest** [comment]
That second line should probably have been `.btn` rather than `btn`.  There are a few cases where we use `<a class="btn"...`

**Comment by durangod** [comment]
Yeah i caught it...  :)   thanks for catching it though as well..   :)
