### ISSUE TITLE
Inconsistent Name Display When GIVN Missing

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#4918]
The first problem is just a data entry issue.  The arrangement of the NPFX field before the GIVN field sometimes leads me to put the name in the wrong place.  That's not so bad.

Unfortunately, when NPFX is supplied without GIVN, webtrees never displays the missing name placeholder.

Example:

1 NAME Karen /Smith/
2 NPFX Karen
2 SURN Smith

Expected Display:

Karen ... Smith

Actual Display:

Karen Smith

This leaves no indication that the GIVN is missing.  Is it possible to change this so it's more obvious?

**Comment by arbor95** [comment]
Do you want a Baron ... Kennedy instead of Baron Kennedy: I think no.

**Comment by miqrogroove** [comment]
Is Baron the GIVN?  Is Kennedy the GIVN?  Is GIVN missing?  Without some display consistency I can only guess how the name was entered.

**Comment by arbor95** [comment]
Baron is surely always NPFX.
If it was GIVN there are never ... in the presentation.

**Comment by arbor95** [comment]
but sure you can never concluse the name parts from the NAME.

**Comment by miqrogroove** [comment]
For me, the answer is yes, I would want

1 NAME Baron /Kennedy/
2 NPFX Baron
2 SURN Kennedy

Expected Display:

Baron ... Kennedy

This indicates to me that the given name is missing.  But for every family tree in the world, I'm unsure of the implications.

**Comment by Norwegian-Sardines** [comment]
The NAME tag does not have to be equal to the subtags!  For example:

1 NAME Jon Erik /Andersen/
2 GIVN Jon, Erik
2 SURN Andersen

1 NAME Maria /Zawadzka/
2 GIVN Maria
2 SURN Zawadzk

1 NAME Johan /von Trapp/
2 SURN Trapp

For many people they want their simple names to be equal, but in more complicated situation they can be different.

The NAME tag (without the slashes) issued for display, the Name_Pieces are used for indexing.

**Comment by miqrogroove** [comment]
I've never tried to customize the NAME value so I wasn't aware it was being treated as separate from the parts.  I will have to consider this more.
