### ISSUE TITLE
Internal Server Error when accessing user management interface or website logs

### ISSUE THREAD

**Issue by RonMcKay** [fisharebest/webtrees#4930]
Hi everyone,

I am struggling accessing the user management interface. I get the following when trying to open it:

```
DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7
```

When looking at the response in the chrome developer console it says

```html
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>openresty</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

The error occurs in `vendor.min.js?v=2.1.18` at `a.send(t.hasContent && t.data || null)`. The same error also occurs when I try to access the website logs in the control panel (`/admin/logs`).

I am running version 2.1.18 with [docker-compose](https://github.com/NathanVaughn/webtrees-docker/blob/main/docker-compose.yml) using the `ghcr.io/nathanvaughn/webtrees:latest` image. My instance is running behind an NGINX reverse proxy (which supplies SSL) with [Authelia](https://github.com/authelia/authelia) in front.

**Comment by fisharebest** [comment]
OK - the code that generates the table-contents is causing a fatal error.

Most errors will be caught, and an error message should appear.

Since you get a web-server generated response, I'm guessing that you have either a fatal/uncatchable error in PHP or (more likely?) a server configuration error.

The requests can generate some pretty long URLs.  Maybe your webserver doesn't like them?

**Comment by RonMcKay** [comment]
@fisharebest You were on the right track with the long URLs. My Authelia instance had problems with them and after increasing the buffer sizes everything works fine.
Thank you very much for the support. 🙂
