### ISSUE TITLE
Subtle change to language tag names

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#495]
I notice that with the change to fisharebest/localisation some language tags have changed for example en_GB to en-GB. Is this deliberate?

**Comment by fisharebest** [comment]
Yes.  Previously, we used the codes as prefered by the old launchpad translation server.  These were a bit ad hoc.

The new filenames are based on the IETF language tags, which gives us a predictable way to find the file for a language, and the language for a file.

**Comment by ddrury** [comment]
That being the case, shouldn't the code at lines 160-164 in I18N::init be removed

**Comment by ddrury** [comment]
And also provide an update script for whereever the tag is stored in the database; for example 

    UPDATE `wt_block_setting` SET `setting_value` = REPLACE(`setting_value`, '_', '-') WHERE `setting_name` = 'languages'

**Comment by fisharebest** [comment]
> That being the case, shouldn't the code at lines 160-164 in I18N::init be removed

Internet standards say that browsers should use IETF language tags (with hyphens),

Microsoft browsers (bless them), send locales, with underscores.

So this code is for IE.

Once finished, it should work like this:

IE sends `de_DE`.  We create a locale for it, which generates a language tag `de`, which corresponds to our file `de.mo`.

**Comment by fisharebest** [comment]
The block/module/tree/user/etc. settings are updated in db_schema_29_30, although this won't be run (yet) in dev builds.  The DB schema version (session.php) will be updated before the next release.
