### ISSUE TITLE
Reports Descendants without result

### ISSUE THREAD

**Issue by arbor95** [fisharebest/webtrees#4952]
Reports Descendants without result
I tried for Queen Elizabeth II, 1926–2022 at [dev.webtrees](https://dev.webtrees.net/demo-stable/index.php?route=%2Fdemo-stable%2Ftree%2Fdemo%2Freport%2Fdescendancy_report&xref=i1)

**Comment by ddrury** [comment]
Have you seen  [this forum post](https://www.webtrees.net/index.php/forum/2-open-discussion/37839-reports#98395)

**Comment by fisharebest** [comment]
All the descendants of QE2 are living/private - hence the empty report.

If you are logged in, you get the report that you expect.

**Comment by arbor95** [comment]
Why is the King Charles III, living son of QE2 shown in Descendants of Queen Elizabeth II (https://dev.webtrees.net/demo-dev/tree/demo/descendants-tree-3/i1#) and his INDI page (https://dev.webtrees.net/demo-dev/tree/demo/individual/I10084/King-Charles-III).

**Comment by fisharebest** [comment]
> Why is the King Charles III, living son of QE2 shown

Because his record has `1 RESN none`.  i.e. it is explicitly public, even though he is living.

This is done on the demo site to demonstrate this feature.

**Comment by arbor95** [comment]
so, KCIII should be shown in Reports Descendants (of QEII)?

**Comment by fisharebest** [comment]
> so, KCIII should be shown in Reports Descendants (of QEII)?

No - because we hide families where any individual is public.

So visitors can see KCIII (because of the RESN tag), but cannot see the family containing his private/living siblings.
