### ISSUE TITLE
Update place names - missing places

### ISSUE THREAD

**Issue by mirono** [fisharebest/webtrees#4959]
I used the Lists -> Place Hierarchy and found Iowa:
![image](https://github.com/fisharebest/webtrees/assets/6016445/a0d32c32-921a-4300-8a81-27cad345ee4a)
So I wanted to change it to Iowa, USA.
I went into the control panel -> Data Fixes -> Update place names. Searched for Iowa, nothing found:
![image](https://github.com/fisharebest/webtrees/assets/6016445/18e6777e-7f87-4993-b454-c6183bfb5345)

**Comment by fisharebest** [comment]
I can't reproduce this.

Maybe something odd in your data.  Perhaps a non-breaking space or some other unprintable character in your data?

If you can let me have a copy of your database, I can investigate.  Otherwise, I'm not sure I can help.

**Comment by fisharebest** [comment]
OK - I can reproduce this.

The search doesn't run until you have entered text into both fields.  Type something into the replace box (e.g. Iowa, USA), and it should work as you expect.

**Comment by mirono** [comment]
Yes, that worked so it's not a bug. If it can print a message to the screen that both fields should be filled that would be great.

**Comment by mirono** [comment]
Closing as it works as expected.
