### ISSUE TITLE
untraanslated string vendor.min.js

### ISSUE THREAD

**Issue by HerzScheisse** [fisharebest/webtrees#4963]
Hi,

i found a untranslated string when using some input field like sources, or shared places... i guess it comes from `public/js/vendor.min.js`

dont know if its even possible to translate this inside the js file... not a big problem if not, but wanted to mention it here...

![no result error](https://github.com/fisharebest/webtrees/assets/146635896/3b2df5cf-5031-402d-b94e-c653ce3574e7)

**Comment by fisharebest** [comment]
We need to store the translated text in `data-*` attributes, and then use them in the initialisation for the TomSelect objects in `webtrees.initializeTomSelect()`.

**Comment by fisharebest** [comment]
https://tom-select.js.org/examples/i18n/#internationalization

**Comment by fisharebest** [comment]
The code has been updated.  The text should be available for translation at translate.webtrees.net in the next 24 hours.

**Comment by HerzScheisse** [comment]
wow that was fast... didnt expected that. thank you...

for the translation, what about using the already existing string of `I18N::translate('No results found.')` instead of `I18N::translate('No results found')` (note the dot at the end of the line) in the resources/views/components/ files?

**Comment by fisharebest** [comment]
> what about using the already existing string

I only saw that one after I rebuilt all the translation files.  I prefer the translation without the `.`.

If you have spare time, perhaps you could visit the translation server, and copy/paste the existing translations and remove the `.`?

**Comment by HerzScheisse** [comment]
yeah i can do that... do i need to wait for the changes to arrive on the language server and than fix that?

I took a quick look and can use search and replace there... to remove the dot...
And then i update the translation files, where the newly added translation string are used, right?

**Comment by fisharebest** [comment]
The translations should be available now.

We need to create new translations (rather than edit the existing ones) as old versions of the code (2.0) still use the old strings with the `.`.

Editing the translation files directly often causes merge conflicts, which are time-consuming to resolve.
