### ISSUE TITLE
Datatables v2 breaks table layouts

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4964]
At commit e124422,

Cell borders missing and cell alignment is wrong (visible on latest demo)

**Comment by ddrury** [comment]
This is caused by commit https://github.com/fisharebest/webtrees/commit/d11b6d871f0ef4a835494c1d71b139bb6dc3209d updating datatables.net-bs5 to version 2.0.2

**Comment by fisharebest** [comment]
Oops - that's not good.

**Comment by fisharebest** [comment]
I think it's related to https://github.com/DataTables/Dist-DataTables-Bootstrap5/issues/11

**Comment by ddrury** [comment]
There are at least another couple of things that need attention,

1. resources/views/lists/datatables-attributes.phtml will need significant work (in particular the new layout attribute)
2. something I've not fully figured out yet, take the Individual surname list (resources/views/lists/surnames-table.phtml), the first column is right justified and examining the html it gets the class dt-type-numeric. Changing it in the html does correct the alignment but changing the code has no effect so I guess it's added as a default by datatables - does this mean we have to define all columns for every table?

**Comment by fisharebest** [comment]
I have downgraded to datatables 1.x until the upstream issue is fixed.

Keep this issue open until we can work with 2.x.

**Comment by miqrogroove** [comment]
I thought it was intentional.  I like the wider name fields.  Maybe just row borders should come back.
