### ISSUE TITLE
Import of location data not working

### ISSUE THREAD

**Issue by SunsetGolfer** [fisharebest/webtrees#4967]
I used the following format:

Level;Place0;Longitude;Latitude;Zoom;Icon
0;"Alt-Schwerin bei Plau";E53.51;N12.35;;
0;"Aschersleben";E51.76;N11.46;;
0;"Belgien";E50.50;N4.47;;
0;"Berlin-Siemensstadt";E52.54;N13.26;;

This format is what the export gives me as well.

And none of the locations is imported..

Am I doing anything wrong?

Cheers
Jörg

**Comment by fisharebest** [comment]
I saved this text into a file.
I imported it.
webtrees reported 4 places imported
The data was imported - I see the co-ordinates.

So it seems to work fine.

> Am I doing anything wrong?

Hard to tell.  What did you do exactly?  What happened, exactly?

**Comment by SunsetGolfer** [comment]
@fisharebest thanks for the fast response.

There are  63 entries in my list and I do not get an error, but rather this...
![grafik](https://github.com/fisharebest/webtrees/assets/11488056/c1904a24-226d-43d6-8009-e3bd654ebd23)

**Comment by fisharebest** [comment]
And what options do you select for the import?

**Comment by SunsetGolfer** [comment]
"Replace only"

There seems to be a problem with my Umlauten...
![grafik](https://github.com/fisharebest/webtrees/assets/11488056/a26f7295-f85e-47fd-bbcf-9f2a4e0d7972)

**Comment by fisharebest** [comment]
Is your file saved using UTF8 encoding?

**Comment by SunsetGolfer** [comment]
Not sure. How can I check?

![grafik](https://github.com/fisharebest/webtrees/assets/11488056/50d4a5c1-8822-45e4-bfbe-ff5ba98dea99)

**Comment by SunsetGolfer** [comment]
It was not, so converting to UTF8 and importing again did the job.

Thanks for your support.

kr Jörg

**Comment by fisharebest** [comment]
Add the file here as an attachment or email it to me

**Comment by SunsetGolfer** [comment]
[Webtrees Locations_UTF8.CSV](https://github.com/fisharebest/webtrees/files/14715161/Webtrees.Locations_UTF8.CSV)

But somehow the map is odd...
![grafik](https://github.com/fisharebest/webtrees/assets/11488056/b603c2c0-4783-4a79-adc3-111f71089a2d)

**Comment by fisharebest** [comment]
You have the co-ordinate columns in the wrong order.

It should be Longitude first, Latitude second.

**Comment by SunsetGolfer** [comment]
Ok, it´s been a long day...

But still this looks wrong

![grafik](https://github.com/fisharebest/webtrees/assets/11488056/6b802393-2655-4c4b-b613-f4fb49eee7a8)

ie geographischen Koordinaten von Dortmund, einer Stadt in Deutschland, sind etwa:

    Breitengrad (Latitude): 51,5139° N
    Längengrad (Longitude): 7,4653° O

**Comment by SunsetGolfer** [comment]
Ok, so there is a problem with the translation.

1. Longitude = Längengrad
2. Latitude = Breitengrad

but

![grafik](https://github.com/fisharebest/webtrees/assets/11488056/a160d907-5c10-48f3-8b0f-54a9bd207b67)

**Comment by SunsetGolfer** [comment]
[Webtrees Locations_UTF8.CSV](https://github.com/fisharebest/webtrees/files/14720062/Webtrees.Locations_UTF8.CSV)

This should be ok, but when trying to upload - however I try - it does not recognize the changes.

**Comment by SunsetGolfer** [comment]
Still the same problem. What can i do to fix it?

Any hints welcome...
