### ISSUE TITLE
Empty control in Privacy Restrictions prevents anything but "All records"

### ISSUE THREAD

**Issue by TonyGravagno** [fisharebest/webtrees#4970]
v2.1.19 Control panel > Manage family trees > name — Privacy

+Add a new restriction. Select any record type other than "All records". In addition to the type selected, another empty dropdown list control is added. It's empty.  
We're directed to "Please select an item im the list." But the list is empty.  
Therefore, in this release, it looks like we cannot create a restriction for any record type other than "All records".

![image](https://github.com/fisharebest/webtrees/assets/499473/1b00ab9d-4486-442b-b1d8-c0791e66bb3d)

**Comment by kiwi3685** [comment]
That empty box is actually a search field. It lets you choose a specific individual if you want to. 

Just type a couple letters from the name of the person you want. This is a common tool throughout the system. 

![image](https://github.com/fisharebest/webtrees/assets/1231773/0448e539-e463-4b1d-a9d5-cd2c6dd11ac2)

**Comment by fisharebest** [comment]
This option was designed for users who (a) maintain their data elsewhere (b) using software that does not support privacy restrictions and (c) use webtrees for display only.

In general, you should add a privacy restriction to the record itself.  i.e. store the privacy restriction as an attribute of the record.  e.g `1 RESN confidential`.

But if (a), (b) and (c) apply, then this function allows you to "merge at runtime" a dynamically-created privacy restriction to a record with a given ID (`XREF`).  `XREF`s are ephemeral and should not be used as permanent identifiers.

Same outcome, but less efficient and will break if/when the `XREF` changes.

**Comment by TonyGravagno** [comment]
I will look closer to understand the functionality where this is occuring. But my point was that the dropdown itself is a required field that doesn't contain data. If we need to select an individual, and there are no individuals, we're left with a control that says we Must do something that cannot be done. This is a UX issue, whatever the reasoning in the application.
