### ISSUE TITLE
"No records to display" in "Changes log" except for the last listed tree

### ISSUE THREAD

**Issue by tronsmit** [fisharebest/webtrees#4976]
Actions: Control panel - Manage family trees - Changes log - (select tree) - search
Result: "No records to display" except when the last listed tree is selected

Recently upgraded to 2.1.19
I have several trees
Tree names are displayed alphabetically
date span is from first install to current date, no other filters
Confirmed the behaviour persists after disabling all custom modules

"Changes in the last 7 days"  block, seems to work fine, i.e. I can see the changes there, they just won't list in the control panel.
Have not checked the database, but because the recent changes block seems to work, I think all is good there

**Comment by BertKoor** [comment]
Reported in the [forum](https://www.webtrees.net/index.php/forum/help-for-release-2-1-x/38844-no-protocol-of-changes#105065) : 
````
After upgrading from webtrees 2.1.18 to 2,1,19 Changes Log is showing only first 10 changes data.
````

**Comment by krm911** [comment]
After upgrading from webtrees 2.1.18 to 2,1,19 Changes Log is showing only first 10 changes data..

What I checked and did:
I checked mariaDB table "wt_changes", it contains ALL up-to-date last minute changes data of each and every family trees.

So I installed another copy of webtrees 2.1.18 in a sub folder to get "Changes Log" working for now until developers provide solution to this issue.

More info and WorkAround I've posted in [forum](https://www.webtrees.net/index.php/forum/help-for-release-2-1-x/38844-no-protocol-of-changes#105065)

**Comment by hartenthaler** [comment]
#4977 solves the problem (for me). Thank you!

**Comment by fisharebest** [comment]
Thanks for the fix.
