### ISSUE TITLE
Can't detect third party module on webtrees 2.1.20

### ISSUE THREAD

**Issue by abdullahaaf** [fisharebest/webtrees#4983]
I install webtrees `2.1.20` on my local windows machine and use Laragon. When I add third party module on `modules_v4` directory, this external module isn't displayed on webtress `All modules` menu. Do I need to add additional config when install webtrees on windows machine?

**Comment by fisharebest** [comment]
Does your module have a valid folder name?  Just alphanumerics, <=30 chars.  Not `.`, etc.

**Comment by abdullahaaf** [comment]
module name is `webtrees-descendants-chart`, I named it like that as refer to module installation suggestion.

is that name correct?

**Comment by fisharebest** [comment]
OK, hard to guess what you've done without seeing it.

**Comment by abdullahaaf** [comment]
Hm, sorry for the unclear information.

So, I just install webtrees on my windows machine and I'm using Laragon as my dev server.
I plan to add external module named `webtrees-descendants-chart` from this repository (https://github.com/magicsunday/webtrees-descendants-chart).

As installation steps mentioned on those repository, I download `zip` version of this module and extract on `modules_v4` directory and rename the module name to `webtrees-descendants-chart`. So `modules_v4` contain subdirectory named `webtrees-descendants-chart`.

As mentioned on installation steps, this module should listed on `All modules` menu on my webtrees, but when I check this module still disappear. I already tried with other module like https://github.com/Jefferson49/ChangeLanguageWithURL and the result still same.

**Comment by reteP-riS** [comment]
See https://github.com/magicsunday/webtrees-descendants-chart/issues/59#issuecomment-2089009477

**Comment by abdullahaaf** [comment]
@ddrury yes but the module isn't listed either on `All modules` or `All module/Charts` menu

**Comment by ddrury** [comment]
@abdullahaaf ah sorry, I thought you meant on the main page

**Comment by abdullahaaf** [comment]
I try to re-install webtrees from https://github.com/fisharebest/webtrees/releases and external module listed. Thanks for the help
