### ISSUE TITLE
Base table or view already exists on fresh db

### ISSUE THREAD

**Issue by abdullahaaf** [fisharebest/webtrees#4984]
I just deploy `webtrees 2.1.20` on https://www.koyeb.com/ and use my hosting as database provider. When initial setup I got error message like below picture :
<img width="740" alt="image" src="https://github.com/fisharebest/webtrees/assets/16618535/5b3c80e5-c0d1-4c04-a11d-dfea69e547e3">

I already did some check that database that I use is completely fresh (no table created before)

does anyone ever face similar problem when setup webtrees on the first time?

Thanks before for the help.

**Comment by fisharebest** [comment]
What tables do you have in the DB?

**Comment by abdullahaaf** [comment]
<img width="593" alt="image" src="https://github.com/fisharebest/webtrees/assets/16618535/ee405446-eb63-456f-ac9a-bee2b5380693">

currently after error raised, those tables exist on my DB

**Comment by fisharebest** [comment]
These are the first 4 tables that are created.  I guess that the installation failed or was interrupted at this point, and the subsequent tables were not created.

The code assumes that all ~30 tables will be created together.

Delete (`DROP`) these four tables and try again.  If the same occurs, then it suggests an error creating the next table (`wt_user_setting`).  Look closely in case any error messages are displayed.
