### ISSUE TITLE
 Error in lists of individuals and families

### ISSUE THREAD

**Issue by luenissla** [fisharebest/webtrees#5000]
I refer to this thread in the [Forum](https://www.webtrees.net/index.php/forum/help-for-release-2-1-x/39058-error-in-lists-of-individuals-and-families ).
The error only occurs when the German language is set. If there are names in the file with a circulation in the first position, the list contains an additional entry, for example "UE". 

![Personenliste_deutsch_06-21-2024_01](https://github.com/fisharebest/webtrees/assets/11136971/f4e8f9c2-5f10-411b-bd5f-6b2addd5786a)

A click on the link shows that there is no name with "UE"!  

![Personenliste_deutsch_06-21-2024_02](https://github.com/fisharebest/webtrees/assets/11136971/c23a6d1b-b00e-460d-9fe6-9a6e286b6a4d)

If the name cloud is set for the display, the program terminates. 

[Error_Indi-list_cloud.txt](https://github.com/user-attachments/files/15936209/Error_Indi-list_cloud.txt)

**Comment by arbor95** [comment]
Same with the other umlauts. Example
https://familienbuch-eichsfeld.de/index.php?route=%2Ftree%2FFuhrbach%2Findividual-list&alpha=OE&show_marnm=

For O respective Ö

**Comment by luenissla** [comment]
Hi Greg,
thanks for the quick repair. 
Best regards
Hans-Joachim

**Comment by WeT-Klb** [comment]
On my installation there is only a /app/Module/AbstractModule.php - no AbstractIndividuallistModule.php.
I even downloaded the latest release from here again:
https://github.com/fisharebest/webtrees/releases/download/2.1.20/webtrees-2.1.20.zip
But even in there there isn#t that php-file!?

**Comment by fisharebest** [comment]
@WeT-Klb - this module has already been modified since the 2.1.20 release.
So the fix is only applicable on the latest development code, and not the last release.
I hope to make a new release soon.

**Comment by WeT-Klb** [comment]
Thanks to make it clear :-)

**Comment by arbor95** [comment]
**but there is still a little bug:**
The Indis of given names, beginning  with Umlauts, do not show under the corresponding letter. (Test by Select A or B or ALL given names)

you can see the test at [dfrese](https://dfrese.de/webtrees/tree/ahnen/individual-list?surname=MILLER&show=indi&alpha=M&show_marnm=no)  .

good/ok Ä no longer in selection, but
clicking A: result: no indis shown (HOver says 2), B-> one indi, All: 3 indis

![bug](https://github.com/fisharebest/webtrees/assets/6124739/e8de95ab-5425-48b2-817f-6e08ef97f362)
