### ISSUE TITLE
missing slashes in NAME

### ISSUE THREAD

**Issue by mariannevanharten** [fisharebest/webtrees#5005]
When I add a new person from who I only know his/her NICK, the name is incomplete stored and displayed.
Because there is no known GIVN or SURN, the name should be
1 NAME //
but the stored data is
1 NAME
The consequence of this is: there is no NICK shown on the person page.
i.e.
1 NAME
2 NICK Marianne

**Comment by Norwegian-Sardines** [comment]
I would have entered this as:

1 NAME “Marianne” //
2 NICK Marianne

Normally I don’t like including the nickname in the NAME tag, but this is a special case!

**Comment by mariannevanharten** [comment]
The case of this comment:
webtrees should at least add the two slashes after 
1 NAME

**Comment by fisharebest** [comment]
We have the convention that `//` indicates an unknown surname.

So if we automatically added `//`, then it would imply that the individual DID HAVE a surname.

It may be the case that this individual is from a culture that does not use surnames.

webtrees uses the `NAME` field for display.  If you want the nickname used in the display name, then it should be included here.

I would use the solution suggested by @Norwegian-Sardines (with or without the `//`)

**Comment by arbor95** [comment]
Hallo Marianne,
would you please answer or close this issue.

**Comment by hartenthaler** [comment]
I think that the solution of @Norwegian-Sardines is a good solution. If a name piece like the nickname is set it should be part of the NAME, even if given and/or last name are not set.
