### ISSUE TITLE
Family Book Security.

### ISSUE THREAD

**Issue by elysch** [fisharebest/webtrees#5007]
Hello.

I've just discovered there is a problem where a manager generates a Family Book Chart that contains a media object that only managers can see and edit, and if you click on the image, it just opens it without any restrictions.

How to reproduce it?

a) login to the tree as manager
b) Go to an individual. 
c) Click on the text below his/her media object to open it. (I tested it in someone who only has only one picture)
d) Edit the media object to add a restriction so only managers can see and edit it.
e) Generate a Family book chart that contains that person.
f) print to pdf the chart.
g) logout from your webtrees installation 
h) open the Family Book pdf and click on the image you have just hide.
i) the browser opens and show the image and it shouldn't.

I found the petition goes via `app/Http/RequestHandlers/RedirectFamilyBookPhp.php` file. 

I coudn't find a way to use the `canShow` function.

Hope it helps.

Ely.

**Comment by elysch** [comment]
P.S: I also tested it logging in as an editor user, copying and pasting the link from the pdf, and it also showed the picture without complaining, when it shouldn't have.

**Comment by arbor95** [comment]
A generated pdf can never be controlled by webtrees and restrictions defined there.

**Comment by elysch** [comment]
Hello.

Never said webtrees should control a pdf... what I said was that app/Http/RequestHandlers/RedirectFamilyBookPhp.php should not allow giving away information without applying security restrictions. 

That's all.

**Comment by elysch** [comment]
Just to be sure, I tested it again and it is not giving away information without applying security restrictions now. Not sure what was wrong in my previous tests (obviously I was authenticated after logging out, or there where some cache data, who knows).

I'm receiving now something similar to "this was not found or you don't have permissions".

I'm closing this one. 
Thanks anyway.
