### ISSUE TITLE
Research tasks table too wide

### ISSUE THREAD

**Issue by ekdahl** [fisharebest/webtrees#5010]
The table within research tasks extends beyond the width of the parent box. This happens with all supplied themes, when the browser window is not very wide.
![image](https://github.com/user-attachments/assets/41d7d5af-ac20-49eb-8b0d-b8126ed5da10)

**Comment by arbor95** [comment]
can not reproduce:

![rt](https://github.com/user-attachments/assets/90442607-5eb6-4803-87a5-40136fca5443)

**Comment by ekdahl** [comment]
Looking a bit closer, it looks like it is a long URL that decides the minimum width of the table.
![image](https://github.com/user-attachments/assets/9cc982a7-a178-4f52-9d61-72eddb89bfe2)

**Comment by arbor95** [comment]
Problem is not the url. A very long word does the same. the word is not split, but you can
write the link into a note of the research task. more advantage: you can use markdown and so click the url direct. Try
AbrownquickfoxjumpsoverthelazydogAbrownquickfoxjumpsoverthelazydog

**Comment by ekdahl** [comment]
> Problem is not the url. A very long word does the same. the word is not split, but you can write the link into a note of the research task. more advantage: you can use markdown and so click the url direct. Try AbrownquickfoxjumpsoverthelazydogAbrownquickfoxjumpsoverthelazydog
Yes, that was what I meant. An URL is essentially like a long word.

The issue is fixed by applying a style rule like this (but I don't know if it has unwanted consequences in other parts of the web site):
`[dir] td {
    word-break: break-word;
}`

**Comment by fisharebest** [comment]
webtrees has a class for this - `ut` (user text).  But in tables, `word-break: break-word` only works with `table-layout: fixed`.  So we need some column-width formatting.
