### ISSUE TITLE
Calendar display counts events, but displays under heading "individuals"

### ISSUE THREAD

**Issue by kiwi3685** [fisharebest/webtrees#5017]
As shown in image, for the day or year view, if any individual or family has multiple events in the same period they are counted multiple times. The image is a simple, one individual with two events on the same day. But I have examples of families and individuals with multiple events , for either days or years making the heading count substantial inaccurate.

I would have thought a list headed as "x individuals" should show that number of unique individuals.
I'm not sure if it's better to change the heading ("x individual's events" ??), or group the events before displaying the list.

I do see that events are grouped by individual on the "month" view, so puzzled it's not done for the other two periods.

<img width="1369" alt="Screenshot 2024-08-06 at 5 13 46 PM" src="https://github.com/user-attachments/assets/4053f9f7-99a9-4a2a-970f-b68a2a09b9ec">

<img width="1360" alt="Screenshot 2024-08-06 at 5 25 44 PM" src="https://github.com/user-attachments/assets/0c9b5197-7b44-43b9-a646-b9d9ed6405ba">

**Comment by fisharebest** [comment]
Do you have a suggestion?

* Change the title to "N indivdiual events" / "N family events"
* Change the title to "Individuals" / "Families"
* Change the count to the number of unique indivdiuals/families
* Something else?

**Comment by kiwi3685** [comment]
Change the count to the number of unique indivdiuals/families
