### ISSUE TITLE
Move link changes blocks to the footer area

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#502]
Is it possible to move the link changes blocks and the hitcounter to the footer area? Then it could be accessed from the theme file.

**Comment by fisharebest** [comment]
These links only appear on the `index.php` page.  Would it make sense to include them in the footer?

From questions on the forum, I see that many users cannot find the "change the blocks" link.  Where else can we put it?

**Comment by JustCarmen** [comment]
Another option would be to place it under the 'my pages' menu. I think this would be the most elegant solution.

The reason I asked this is because I moved this link to the footer in one of my themes, but this has to be done on the client side and I rather do it on the server side. Best way to illustrate is with some images:
![21-3-2015 23-18-37](https://cloud.githubusercontent.com/assets/5641963/6767097/5be29072-d021-11e4-838e-cfe623b728a2.png)
![21-3-2015 23-20-33](https://cloud.githubusercontent.com/assets/5641963/6767099/612931a8-d021-11e4-9b15-2371a9ec6a6c.png)
It is a matter of taste, but I don't like the default location of the link because it looks so messy.

But moving the change block link to the 'my pages' menu would even be better. 

But that doesn't count for the pageview text inside.  I would rather have that one in the footer area so it is stylable and can be placed anywhere. Looking at the screenshot of my theme I could place it above the grey block, below or inside. And as a theme developer, I like to have that choice.

**Comment by fisharebest** [comment]
> Another option would be to place it under the 'my pages' menu. I think this would be the most elegant solution.

That could work.  I will try this.

>  I would rather have that one in the footer area so it is stylable and can be placed anywhere.

We collect "hit counts" on families/sources/repositories/etc. as well as individuals.  But we do not display this.

I need to refactor `includes/hitcount.php` into a class, so I will look at this.

The hard part (for me!) is deciding how to style this for the existing 6 themes...

**Comment by makitso** [comment]
>The hard part (for me!) is deciding how to style this for the existing 6 themes...

Need help?

**Comment by ddrury** [comment]
>Another option would be to place it under the 'my pages' menu. I think this would be the most elegant solution.

I'd support this and suggest changing name to something like "Customize my page"

**Comment by fisharebest** [comment]
> Need help?

I've just added them centrally at the bottom of the footer.  If you want to reposition them, go ahead.

> I'd support this and suggest changing name to something like "Customize my page"

Good idea.  I went for "this" page, rather than "my" page.  Seemed clearer.

**Comment by fisharebest** [comment]
PS - I added hit counters to the charts pages as well, since it was easy to do.

We could add them to other pages (lists, calendar, ...), but these wouldn't be "per individual".
