### ISSUE TITLE
Dates prior to 1901 fail on 32-bit systems ("On this day" feature - anniversaries-list.phtml)

### ISSUE THREAD

**Issue by raaspt** [fisharebest/webtrees#5022]
Hi,
The "On this day" feature (anniversaries-list.phtml) breaks on 32-bit systems for dates prior to 1901 when "show only events of living individuals" is set to "no".
I know there have been some comments on issues regarding this limitation, but I couldn't find anything regarding this specific feature.

In such cases, "$this->carbon->subYears($years)" in "app/Timestamp.php:183" returns "bool(false)" instead of "int(...)" causing the error:

Argument 1 passed to Fisharebest\Webtrees\Timestamp::__construct() must be of the type int, bool given, called in …/app/Timestamp.php on line 185 …/app/Timestamp.php:35
#0 …/app/Timestamp.php(188): Fisharebest\Webtrees\Timestamp->__construct(false, 'Europe/Lisbon', 'pt_PT')
#1 …/resources/views/lists/anniversaries-list.phtml(52): Fisharebest\Webtrees\Timestamp->subtractYears(130)

Any solution or workaround?
Thanks.

**Comment by magicsunday** [comment]
PHP version?

**Comment by raaspt** [comment]
PHP 7.4.30 running on my old Synology NAS which I can't upgrade.

**Comment by fisharebest** [comment]
Elsewhere (e.g. the individual/family lists), we use `->subtractYears(100)`.  Presumably you don't see an error here.

Your error message says `->subtractYears(130)`, which suggests that you have set "Age at which to assume dead" to 130.

Since 130 causes the overflow, and 100 does not, I wonder if using a lower number for this setting would be an effective work-around.

**Comment by raaspt** [comment]
I only see the error in "anniversaries-list.phtml", and I have not changed the default value of "Age at which to assume dead" (which I don't think has anything to do here).

I have added a couple of `var_dump`s to the beginning of the `Timestamp.php->substractYears(int)` function.

There's an individual that was born on this day in 1718, so 306 years ago, and I get the following:
`var_dump($years)` = `306`
`var_dump($this->carbon->subYears($years)->getTimestamp())` = `bool(false)`

And as mentioned this throws an exception on 32-bit systems.
