### ISSUE TITLE
images previews showing in the wrong orientation

### ISSUE THREAD

**Issue by Jeefongithub** [fisharebest/webtrees#5023]
In multiple sections of the UI I've noticed some images previews are showing as horizontal however when selected the image corrects to the vertical orientation. I've noticed this in the Slideshow and on a users album page of a user

Here is example from the Slideshow section. First image is the preview and the second is showing once selected
![image](https://github.com/user-attachments/assets/0eca7b4a-88c7-42db-b70c-4ca5763a7333)
![image](https://github.com/user-attachments/assets/99c99a4e-d7f8-478c-802e-7309107d9c7a)

The next image is showing from the album view of that user
![image](https://github.com/user-attachments/assets/b215d270-eda0-4b23-9917-2571e2eb4574)

**Comment by kiwi3685** [comment]
See forum post: 

https://www.webtrees.net/index.php/forum/help-for-release-2-1-x/39023-images-changing-orientation#105795
