### ISSUE TITLE
Add support for FTM's `_PHOTO` tag to mark a media object as the individual's "profile picture"

### ISSUE THREAD

**Issue by alexhauser** [fisharebest/webtrees#5031]
While investigating switching from `Family Tree Maker` to Webtrees, we ran into the issue that in FTM you can mark one media file as the individual's "profile image". This image will always be displayed first on an individual if more than one media objects are assigned.

In the gedcom export, FTB uses the 1st level tag `_PHOTO` to encode that information, xref'ing to an existing OBJE record:

```
0 @I1936@ INDI
1 NAME John /Doe/
1 _PHOTO @M6903@
1 OBJE @M833@
1 OBJE @M5425@
1 OBJE @M5426@
1 OBJE @M5427@
1 OBJE @M6903@
1 OBJE @M6904@
```
Currently, webtrees doesn't seem to support this tag, so most of the individuals get displayed using the wrong image (the first one that happens to appear in the gedcom file for that individual).

I have already looked into how to implement this in webtrees, and it seems to be rather straigthforward.
But I wanted to ask first, if a PR for such an addition would be appreciated?

Thanks for your terrific work and all the best!

**Comment by Norwegian-Sardines** [comment]
In the example above, change the _photo to OBJE and it will be displayed.  The _photo tag is not Standard GEDCOM.

**Comment by fisharebest** [comment]
> webtrees doesn't seem to support this tag

It doesn't - I have not come across it before.

At the simplest level, we could add support by adding this line to the defintions in `FamilyTreeMaker.php`:

```php
'INDI:_PHOTO'  => new XrefMedia(I18N::translate('Primary photo')),
```

This would display the photo with a sensible label.

But webtrees wouldn't understand the meaning of this - it would just be a label, and it wouldn't be shown on the media tab.

To actually treat it as the primary photo, we'd need to reformat the GEDCOM using valid 5.5.1 - which means re-ording the `OBJE` links to have the primary one first.

As a general rule, we try to avoid automatically "fixing" invalid data.  We let the user do that using tools.  You'll see a few data-fix modules that "Convert XXX to GEDCOM 5.5.1".

However, there are quite a few fixes that we do silently.

So, webtrees could add a data-fix for this...

...or webtrees could become a little more "opinionated", and always convert non-standard inputs to standard/valid GEDCOM.

**Comment by LarsRabe** [comment]
`...or webtrees could become a little more "opinionated", and always convert non-standard inputs to standard/valid GEDCOM.
`
That seems to be the right way. I think it should be the future standard for webtrees to handle this Kind of situations.

**Comment by kiwi3685** [comment]
> > ...or webtrees could become a little more "opinionated", and always convert non-standard inputs to standard/valid GEDCOM.
> 
> 
> 
> That seems to be the right way. I think it should be the future standard for webtrees to handle this kind of situations. 
> 
> 

Sorry, I couldn't disagree more. Webtrees has an excellent reputation  for adhering to Gedcom standards, **_while still allowing users to control such decisions for themselves_**. 
It would be a very negative step to lose that flexibility.

**Comment by alexhauser** [comment]
Thanks for all the great feedback and discussion.

I'm aware that the `_PHOTO` tag is not standard GEDCOM and that everything can be solved by modifying the GEDCOM file before importing.

The "_use a tool to fix the GEDCOM_"-approach is fine with me per se, I've actually written a tool to consolidate and rename media files from FTM's GEDCOM file, so adding the reordering of the `OBJE` records is no big deal. But that obviously doesn't help the next user that wants to switch from FTM to Webtrees.

So this issue for me is more about the question:
"Do we want to improve the out-of-the-box experience for new users coming from FTM?" 

I understand that there are different approaches when it comes to dealing with proprietary or invalid GEDCOM data, and as someone new coming to this project, I am definitely not taking any sides or making any demands here. :)

Personally, I would find it a sensible approach to "fix" this silently during import by reordering the `OBJE` records.
As for "_allowing the user to control such decisions for themselves_", this could be accomplished by making the data fixes (de)selectable using a checkbox on import.

**Comment by alexhauser** [comment]
Oh and by the way, adding the definition for the tag in `FamilyTreeMaker.php` would of course also be appreciated, if only for for aesthetic reasons. Thank you!

```php
'INDI:_PHOTO'  => new XrefMedia(I18N::translate('Primary photo')),
```

**Comment by fisharebest** [comment]
I think, perhaps, an import option might be the right place for this - and maybe some of the other "data fixes".
