### ISSUE TITLE
wt-icon-sex-f foreground color in minimal theme

### ISSUE THREAD

**Issue by ekdahl** [fisharebest/webtrees#5036]
This line should probably use --sex-f-fg instead of --sex-m-fg
https://github.com/fisharebest/webtrees/blob/main/resources/css/minimal.css#L769
Similar for this line
https://github.com/fisharebest/webtrees/blob/main/resources/css/minimal.css#L781

This is noticeable when basing themes on minimal theme and setting different colors for male and female.

**Comment by fisharebest** [comment]
> Did you see the mention of this line?

Oops!

I'll fix that now.
