### ISSUE TITLE
Blank alert on "onclick" events

### ISSUE THREAD

**Issue by kiwi3685** [fisharebest/webtrees#5046]
Anywhere I find an element like the following, two alert pop-ups are produced.

`<button type="submit" class="btn btn-link" data-wt-confirm="Are you sure you want to remove this item from your list of favourites?" onclick="return confirm(this.dataset.confirm);">`

The first empty box appears on clicking the element, and the second on clicking the "cancel" text on the first. See these two consecutive images as example (from Demo site, clicking on the "Remove" text in the favorites block).

<img width="890" alt="Screenshot 1" src="https://github.com/user-attachments/assets/c4e44800-2e09-4135-af38-6fdfc31d1ab6">
<img width="884" alt="Screenshot 2" src="https://github.com/user-attachments/assets/c3489e79-fe6f-4358-bebf-b96893c0ee6c">

I have checked it on my site, the demo site, multiple browsers, and themes (including standard and custom themes). It affects all elements with similar code structure.

I can't find a solution to stop the first (empty) alert appearing. Hoping someone else can.

**Comment by fisharebest** [comment]
This seems to be a chrome issue.  I don't see it with Firefox.
