### ISSUE TITLE
Admin Network errors

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#505]
admin_site_change throws following errors

    NetworkError: 404 Not Found - <path>/packages/bootstrap-3.3.4/fonts/glyphicons-halflings-regular.woff
    NetworkError: 404 Not Found - <path>/packages/bootstrap-3.3.4/fonts/glyphicons-halflings-regular.ttf

**Comment by fisharebest** [comment]
I didn't think we were using any of the glyphicons - just font-awesome.

I'll take a look...
