### ISSUE TITLE
Error al introducir datos en el formulario de búsqueda avanzada

### ISSUE THREAD

**Issue by BernatBanyuls** [fisharebest/webtrees#5054]
Al intentar ingresar datos en la opción "lugar de residencia" (en la búsqueda avanzada), los datos no se registran y la búsqueda no arroja resultados. Posteriormente, la opción "lugar de residencia" aparece en "opciones predeterminadas" y entonces funciona correctamente.

**Comment by fisharebest** [comment]
"When I try to enter data in the "place of residence" option (in the advanced search), the data is not recorded and the search does not return any results. Later, the "place of residence" option appears in "default options" and then works correctly."

**Comment by fisharebest** [comment]
We cannot add the search-value on the first page.  We do not know which type of edit control (date/place/value) to create until after the field is selected.

So, it is still a two-step process (add field, add value), but we no longer require a value on the first page.
