### ISSUE TITLE
Add Rel=Nofollow to private links - Enhancement

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#5057]
Add Rel=Nofollow to all generated links that are "private" to discourage search engines from trying to index pages they can't reach.

Example, this is the link currently generated on the family drop down of an Individual's page:

`<a class="dropdown-header wt-family-navigator-dropdown-heading" href="https://behunt.net/ft/tree/hunt/family/F135/Private-Private">               Family                                    </a>`

Search engines (Google at least) will follow the link then complain about the 403-Forbidden error

**Comment by fisharebest** [comment]
We shouldn't be showing these links at all...
