### ISSUE TITLE
Statistics block & Most common surnames

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#5059]
In the most common surnames section on the statistics block, the link leads to the family list. Shouldn’t this be the individual list?

See for instance royal family on demo site: select “Armstrong-Jones” in the most common surnames, opens the family list.

**Comment by kiwi3685** [comment]
Already raised and fixed 

https://github.com/fisharebest/webtrees/issues/4989

It is included in latest release 2.1.21

**Comment by SnarfW** [comment]
I missed issue 4989.
I haven't upgrade my site yet, but the demo server apperently is upgrade to 2.2.0. On this page the issue still does excist.

**Comment by kiwi3685** [comment]
You're right. Don't know the reason for that. 

The change is definitely in the upgrade to 2.1.21.
