### ISSUE TITLE
New translation library. How to use it with custom modules?

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#506]
In my modules I have this piece of code:

>>I18N::addTranslation(
new Zend_Translate('gettext', $this->module . '/language/' . WT_LOCALE . '.mo', WT_LOCALE)
);

How do I change this so it will work with the new localization library?

**Comment by fisharebest** [comment]
At present, these language files should be loaded automatically.

In future, I want to combine themes and modules.  Then, we will probably have a `ModuleTranslationInterface`, which will allow each module to identify which translations it uses.  This should be more efficient than scanning all the folders.

**Comment by JustCarmen** [comment]
Ok, thanks that make sense.

Because I got errors with the modules I needed to solve that first, before I could get in my (develop) site again. So I did, but then I noticed the site isn't been translated at all anymore. I switched off all custom modules and themes, clear the cache, updated al the mo.files. But nothing helps.

I doesn't matter which language I choose, it always stays in English.

But with some languages (not all) I get an error message:

>> #0 \vendor\fisharebest\localization\src\Translate\Translation.php:33 ErrorException("Undefined offset: 1") #1 \app\I18N.php:182 __construct('C:\\xampp\\htdocs\\webtrees_build…') #2 \includes\session.php:450 init() #3 \admin.php:28 require('C:\\xampp\\htdocs\\webtrees_build…').

I didn't get this message when choosing Dutch, but I did when choosing German or French.

**Comment by JustCarmen** [comment]
Ok, the error message is gone when I removed my custom data/language folder. I used some simple csv tranlations and that doesn't seem to work.

But the pages are still only in English, none of the other languages can be activated.

**Comment by fisharebest** [comment]
> But with some languages (not all) I get an error message:

The error says your CSV file is invalid.  Are you using the correct format?  http://wiki.webtrees.net/en/Custom_Translation#CSV_format

> I switched off all custom modules and themes, clear the cache, updated al the mo.files. But nothing helps.

At present, all translation files are loaded for all modules.  As mentioned previously, we need to ask each module to provide its translations, using a new API.

**Comment by JustCarmen** [comment]
Ok, maybe I didn't make myself clear. I started this message with a question about modules and translations, but later I found out the translations haven't been working at all since the change to the new library. Maybe I should have made a new topic for this.

But the problem is that also the default webtrees texts from the core are only visible in English. I can switch to whatever language but they simply don't work. Not in the control panel and not in the front.

**Comment by fisharebest** [comment]
I create the file `data/language/nl.php`, containing `<?php return array('Individuals' => 'Fish');`

I visit the page `indilist.php` and select Dutch.  I see all the text in Dutch, except the title, which is now translated as "Fish".

>  found out the translations haven't been working at all

You mean everything is in English, whatever language you select?

**Comment by JustCarmen** [comment]
>> You mean everything is in English, whatever language you select?
Yes, that is exactly what I mean.

**Comment by fisharebest** [comment]
Do you see a file `data/cache/language-nl-cache.php`?

Is it about 380KB?
Does it contain a PHP array of Dutch translations?

**Comment by JustCarmen** [comment]
I see the file but it is only containing this:

>> <?php return array (
);

It doesn't contain any translations.

**Comment by fisharebest** [comment]
OK, delete it - and see if it is recreated.

**Comment by JustCarmen** [comment]
I have deleted it, and it is indeed recreated but still empty (except for the php tag with the empty array)

I don't know if it is important but I am running this development version locally on a xampp installation.

**Comment by fisharebest** [comment]
If it still does not work, can you debug I18N.php, line ~170

``` php
		// Load the translation file(s)
		// Note that glob() returns false instead of an empty array when open_basedir_restriction
		// is in force and no files are found.  See PHP bug #47358.
		$translation_files = array_merge(
			array(WT_ROOT . 'language/' . self::$locale->languageTag() . '.mo'),
			glob(WT_MODULES_DIR . '*/language/' . self::$locale->languageTag() . '.{csv,php,mo}', GLOB_BRACE) ?: array(),
			glob(WT_DATA_DIR . 'language/' . self::$locale->languageTag() . '.{csv,php,mo}', GLOB_BRACE) ?: array()
		);

		$rebuild_cache = false;
		foreach ($translation_files as $translation_file) {
			if (filemtime($translation_file) > $filemtime) {
				$rebuild_cache = true;
				break;
			}
		}

		if ($rebuild_cache) {
			$translations = array();
			foreach ($translation_files as $translation_file) {
				$translation = new Translation($translation_file);
				$translations = array_merge($translations, $translation->asArray());
			}
			file_put_contents($cache_file, '<' . '?php return ' . var_export($translations, true) . ';');
		} else {
			$translations = include $cache_file;
		}
```

**Comment by JustCarmen** [comment]
Ok, it goes wrong in the section where the cache is rebuild. Starting with "if ($rebuild_cache)"

a var_dump of $translation_files is giving this output:

>>string(45) "C:\xampp\htdocs\webtrees_build\language/nl.mo" string(40) "modules_v3/fancy_branches/language/nl.mo" string(38) "modules_v3/fancy_gendex/language/nl.mo" string(40) "modules_v3/fancy_imagebar/language/nl.mo" string(44) "modules_v3/fancy_privacy_list/language/nl.mo" string(46) "modules_v3/fancy_research_links/language/nl.mo" string(43) "modules_v3/fancy_source_list/language/nl.mo" string(40) "modules_v3/fancy_treeview/language/nl.mo" string(49) "modules_v3/justblack_theme_options/language/nl.mo" string(49) "modules_v3/justlight_theme_options/language/nl.mo" string(50) "C:\xampp\htdocs\webtrees_build\data\language/nl.mo" 

But a var_dump of $translation is giving this output:
>> object(Fisharebest\Localization\Translation)#26 (1) { ["translations":"Fisharebest\Localization\Translation":private]=> array(0) { } } object(Fisharebest\Localization\Translation)#24 (1) { ["translations":"Fisharebest\Localization\Translation":private]=> array(0) { } } object(Fisharebest\Localization\Translation)#26 (1) { ["translations":"Fisharebest\Localization\Translation":private]=> array(0) { } } object(Fisharebest\Localization\Translation)#24 (1) { ["translations":"Fisharebest\Localization\Translation":private]=> array(0) { } } object(Fisharebest\Localization\Translation)#26 (1) { ["translations":"Fisharebest\Localization\Translation":private]=> array(0) { } } object(Fisharebest\Localization\Translation)#24 (1) { ["translations":"Fisharebest\Localization\Translation":private]=> array(0) { } } object(Fisharebest\Localization\Translation)#26 (1) { ["translations":"Fisharebest\Localization\Translation":private]=> array(0) { } } object(Fisharebest\Localization\Translation)#24 (1) { ["translations":"Fisharebest\Localization\Translation":private]=> array(0) { } } object(Fisharebest\Localization\Translation)#26 (1) { ["translations":"Fisharebest\Localization\Translation":private]=> array(0) { } } object(Fisharebest\Localization\Translation)#24 (1) { ["translations":"Fisharebest\Localization\Translation":private]=> array(0) { } } object(Fisharebest\Localization\Translation)#26 (1) { ["translations":"Fisharebest\Localization\Translation":private]=> array(0) { } } 

And finally a var_dump of $translations is giving me this output:
>> array(0) { } array(0) { } array(0) { } array(0) { } array(0) { } array(0) { } array(0) { } array(0) { } array(0) { } array(0) { } array(0) { } 

For your information I have disabled all modules from the control panel. But since the code is looking for language files in the folder module_v3 they are still found.

So I also have done the same test with the modules enabled, but it leads to the same result (an empty array at the end).

**Comment by fisharebest** [comment]
> But a var_dump of $translation is giving this output:

What about `var_dump($translation->asArray())`?

**Comment by JustCarmen** [comment]
Same result:

>> array(0) { } array(0) { } array(0) { } array(0) { } array(0) { } array(0) { } array(0) { } array(0) { } array(0) { } array(0) { } array(0) { }

**Comment by fisharebest** [comment]
Can you look in `vendor/fisharebest/localization/src/Translate/Translation.php`?

Is `$number_of_strings` being set to the number of translations in the file?

**Comment by JustCarmen** [comment]
Sorry I don't understand what you mean.

Looking in that file I see the variable $number_of_strings only in this part of the code:

>>// Read the lookup tables
		list(, $number_of_strings, $offset_original, $offset_translated) = $this->readMoWords($fp, 8, 3, $pack);
		$lookup_original   = $this->readMoWords($fp, $offset_original, $number_of_strings * 2, $pack);
		$lookup_translated = $this->readMoWords($fp, $offset_translated, $number_of_strings * 2, $pack);

		// Read the strings
		for ($n = 1; $n < $number_of_strings; ++$n) {
			fseek($fp, $lookup_original[$n * 2 + 2]);
			$original = fread($fp, $lookup_original[$n * 2 + 1]);
			fseek($fp, $lookup_translated[$n * 2 + 2]);
			$translated = fread($fp, $lookup_translated[$n * 2 + 1]);
			$this->translations[$original] = $translated;
		}

I don't know how I can see if it set to the right value.

**Comment by fisharebest** [comment]
`var_dump($number_of_strings);`

**Comment by Amgine0** [comment]
Synchronous channel?

**Comment by JustCarmen** [comment]
O I am sorry I misunderstood.

But a var_dump of $number_of_strings doesn't output anything.
I tried to echo the word 'test' from that point but that doesn't work either. So I suspect this code can't be reached.

I then echoed the word 'test' from the top of the function 'readMoFile' and that does work. So the function is called.

Then I put the word test1, test2 and test3 in the switch to see which one is called and it turned out that the function breaks at

>>default:
				// Not a valid .MO file.
				return;

I make my mo files always in batch with the GetTextTool:

>> cd C:\Program Files (x86)\Poedit\GettextTools\bin
msgfmt C:\xampp\htdocs\webtrees_build\language\nl.po --output-file C:\xampp\htdocs\webtrees_build\language\nl.mo

Is this the problem??? Because it has always worked.

**Comment by fisharebest** [comment]
Can you send me the file?

**Comment by JustCarmen** [comment]
I will send you the file in a moment.

**Comment by ddrury** [comment]
Greg,
I think this is the problem causing #511. I've compiled the files using both poedit & betterpoedit and both times readMoFile fails on the switch statement (hits the default option)

**Comment by fisharebest** [comment]
Your file works fine for me.  What output do you get for this:

``` php
		// How is the numeric data packed in the .MO file?
		$magic = $this->readMoWords($fp, 0, 1, self::PACK_LITTLE_ENDIAN);
		var_dump(dechex($magic[1]));
```

**Comment by ddrury** [comment]
I get 950412de for en-GB

**Comment by ddrury** [comment]
Its a string not a number

**Comment by fisharebest** [comment]
@ddrury 

> Its a string not a number

What exactly is a string?  The function `readMoWords()` should return an array of integers, and the constant `PACK_LITTLE_ENDIAN` is also an integer.

The switch statement **should** match them up.....

**Comment by JustCarmen** [comment]
I'm getting this output:

>> string(8) "950412de" string(8) "950412de" string(8) "950412de" string(8) "950412de" string(8) "950412de" string(8) "950412de" string(8) "950412de" string(8) "950412de" string(8) "950412de" string(8) "950412de" string(8) "950412de"

**Comment by fisharebest** [comment]
Intel CPUs are little-endian, so I would expect almost all .MO files to be encoded in this format.

The "magic constant" is the one I would expect.

Try `var_dump(self::MO_MAGIC_LITTLE_ENDIAN, $magic[1]);`

**Comment by ddrury** [comment]
var_dump($magic[1], self::MO_MAGIC_LITTLE_ENDIAN, dechex($magic[1]), dechex(self::MO_MAGIC_LITTLE_ENDIAN));
produces
int -1794895138
float 2500072158
string '950412de' (length=8)
string '950412de' (length=8)

**Comment by JustCarmen** [comment]
I am getting the same output (only repeated for each nl.mo file I have)

**Comment by fisharebest** [comment]
`var_dump(PHP_INT_SIZE);`

I'm guessing this will give 4 (i.e. 32 bit builds of PHP).

All my machines have 64 bit builds....

**Comment by ddrury** [comment]
Yep gives 4 (but this is a 64bit build)

**Comment by JustCarmen** [comment]
Indeed 4

I have a 64bit PC but Xampp is only available in 32bit
Is that the problem?

**Comment by fisharebest** [comment]
Thanks both for your help.

I'll need to update the fisharebest/localization package....

**Comment by JustCarmen** [comment]
Your welcome. I am glad we got this far.

**Comment by JustCarmen** [comment]
Thanks, I can confirm it is working now!
