### ISSUE TITLE
Shared Notes not opened in events (webtrees 2.1.21)

### ISSUE THREAD

**Issue by sleebooth** [fisharebest/webtrees#5060]
In Version 2.1.21, Shared Notes are not displayed automatically in Census events, despite the arrow to the left of "Shared Note" pointing upwards.

**Comment by HRN65** [comment]
Also applies to 2.2.0

**Comment by fisharebest** [comment]
This only happens when you have selected the "automatically expand notes" option.

**Comment by fisharebest** [comment]
Fixed in be7b921bc7dbb3fd634004ac8684ab4b3e7671c3
