### ISSUE TITLE
Bug in 2.1.21 - wrong private GEDCOM exports

### ISSUE THREAD

**Issue by webtrees-pesz** [fisharebest/webtrees#5061]
The new function for avoiding empty data records in private GEDCOM exports causes an incorrect GEDCOM structure.

INDI record in 2.1.20:
1 DEAT
2 PLAC Culm, West Prussia, Germany
2 SOUR @S145@
3 DATA
4 DATE 18 APR 1906
4 TEXT abc
5 CONC def
5 CONC ghi
3 QUAY 2
1 FAMC @F291@
...
0 @S145@ SOUR
0 @S146@ SOUR
...

INDI record in 2.1.21:
1 DEAT
2 PLAC Culm, West Prussia, Germany
3 DATA
4 DATE 18 APR 1906
4 TEXT abc
5 CONC def
5 CONC ghi
3 QUAY 2
1 FAMC @F291@
...

The problem occurs whenever a link to an empty record is followed by a substructure (e.g. ASSO, FAMC, FAMC, SOUR, ...).

**Comment by webtrees-pesz** [comment]
Perhaps the following code could be helpful in solving this problem:
https://github.com/Jefferson49/ExtendedImportExport/blob/main/resources/filter/RemoveEmptyRecordsGedcomFilter.php

**Comment by fisharebest** [comment]
The code searches for private links, and their subtags.

It then deletes them

BUT, the order of matches can cause a problem.

For example, suppose we match these two strings

```
2 SOUR @X1@
```

```
2 SOUR @X1@
3 OBJE @X2@
```

If we delete the first one, then it will also delete the first part of the second.
