### ISSUE TITLE
No update form the field updated in tab wt_news

### ISSUE THREAD

**Issue by luenissla** [fisharebest/webtrees#5068]
In the news box (table wt_news), the date of the change (updated) is __not updated__ when a change is made. The old date remains. (In the example for the issue, I changed the date manually in the database).  
![Update_News_Zwischenablage_12-04-2024_02](https://github.com/user-attachments/assets/c33c1055-9298-41f3-9ee5-0119a59fdaec)

**Comment by fisharebest** [comment]
See #3208

I guess this needs a checkbox or similar...

**Comment by fisharebest** [comment]
Or maybe we should allow the user to edit the date/time?

**Comment by fisharebest** [comment]
<img width="729" alt="Screenshot 2024-12-09 at 09 36 44" src="https://github.com/user-attachments/assets/f2433699-8dc1-42f4-b6c0-bc761c0a8070">

You can now

* keep the existing timestamp
* edit the existing timestam
* use the current date/time

**Comment by mpwt** [comment]
Please test the changes in v2.2.2-dev. You will receive an error message when saving a new journal or news entry.
