### ISSUE TITLE
2.2.1: Individuals table wrong sort order birth and death date

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#5069]
The sort result of the event date is incorrect for both ascending and descending sort orders. (Last Change is sorted correctly)

1705, 1864, 1891, 1911, **1839**, 1807, 1843,1870, 1742
![Screenshot 2024-12-04 163853](https://github.com/user-attachments/assets/81e86abd-619d-48d7-8a65-d2904d353a48)

1843, 1859, **1848**, 1850, 1862, 1891, 1893, 1832, 1824, 1798 
![Screenshot 2024-12-04 163910](https://github.com/user-attachments/assets/3886faeb-873b-41f0-9dda-17aaf945db49)

see https://wbt.warius.info/tree/Warius/individual-list?show=indi&show_marnm=yes&surname=KLINGBERG&falpha=

**Comment by fisharebest** [comment]
Duplicte of #5067?  This is already fixed.
