### ISSUE TITLE
Thumbnail profile pictures with errors

### ISSUE THREAD

**Issue by HerzScheisse** [fisharebest/webtrees#5073]
Hi,

I successfully upgraded to webtrees 2.2.1 (on php 8.3) and all the modules today... but now i noticed a strange error which i cant resolve...

on my site i created a profile picture for each individual, which is stored in the subfolder /data/profil/I12345.jpg

while checking for errors after the upgrades... i noticed that almost all thumbnails of these profil pictures have errors (white dots or also white lines) and its only the thumbnail which is not generated correctly... if i click the picture to enlarge... the image is display correctly without those image errors...

So my guess is, it has something to to with the thumbnail creation... 

I deleted the website and browsercache multiple times... but the erros still exists...

Any ideas?

**Comment by fisharebest** [comment]
Can you give me details?  e.g. a copy of the corrupted image?  Hard to guess what you are seeing.

**Comment by HerzScheisse** [comment]
hey Greg,
I've send you a email with login details for my site... so you can test this live on my page...

**Comment by FrankWarius** [comment]
its seems to be a dup of #5042

**Comment by HerzScheisse** [comment]
Hey @FrankWarius thanks for your comment... i guess its not related to your lined issue... the image is not truncated... it just hast to original size... but with picture errors...

f.e.
![image error](https://github.com/user-attachments/assets/df8db50a-8b2e-4f1e-ac52-2266ab36dd71)

**Comment by HerzScheisse** [comment]
hey @fisharebest  and others,
I have good news... the error ist gone now...
Because of some performance issues i've spoken with my hoster and they transfered my site to a newer server last night...
After some testing today, i noticed that the error is gone now...

so maybe the thumbnail issues and their creation may be related to the bad/slow server performance...
