### ISSUE TITLE
Link Place -> Place list not correct for visitor

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#5074]
See demo site (current release):
For instance on [page ](https://dev.webtrees.net/demo-stable/index.php?route=%2Fdemo-stable%2Ftree%2Fdemo%2Findividual%2Fi1%2FQueen-Elizabeth-II)of Queen Elizabeth II

When I click on het birth place (Mayfair) the behaviour is different for a visitor and member.
The link for a member is "https://dev.webtrees.net/demo-stable/index.php?route=%2Fdemo-stable%2Ftree%2Fdemo%2Fplace-list%2F1054" and the map opens
But for a visitor the link is different, and your are redirected to the same page: "https://dev.webtrees.net/demo-stable/index.php?route=%2Fdemo-stable%2Ftree%2Fdemo%2Findividual%2Fi1%2FQueen-Elizabeth-II#"

Is this the intended behaviour, or is this a bug?

**Comment by fisharebest** [comment]
There's a few locations in the code that assume all `Place` objects will have a URL - to the places-list.

But if you do not have permission to see the places-list module, we use `#` as the URL - which disables the link.

So, this is the intended behaviour.

We can probably tidy this up, so it doesn't display the link at all.

**Comment by SnarfW** [comment]
Thanks for the explanation. I agree it would be better to not show a link when is not allowed to see the link.
Personally, I feel that the location of a place is not a secret. I want to give visitors access. How can I do this? I tried Control Panel > Lists > Locations, access level ‘show to visitors’, but this did not give visitors access.

**Comment by kiwi3685** [comment]
You want "Control panel > Lists > Place hierarchy" not Locations.

**Comment by fisharebest** [comment]
> Personally, I feel that the location of a place is not a secret

Many people include the address in the place.  e.g.

```
1 BIRT
2 PLAC 3 The Green, Ambridge, Borsetshire, England
```

This allows them to be placed on a map.  It may not be a good idea to show these.
