### ISSUE TITLE
Edit raw GEDCOM adds a superfluous space character to empty NOTE lines

### ISSUE THREAD

**Issue by Bogiegit** [fisharebest/webtrees#5075]
Given a record has a fact structure as follows.

1 FACT fact description
2 TYPE fact type
2 NOTE
3 CONT line 1
3 CONT line 2

! Line NOTE is deliberately left empty.

When menu item "edit the raw GEDCOM" is used webtrees automatically adds a space character at the end of the NOTE line. That prevents the GEDCOM to be saved and will highlight the section with a red frame. The GEDCOM only can be saved when the space character is removed manually. That has to be repeated every time the GEDCOM is edited again.

**Comment by fisharebest** [comment]
The space is being added here:

https://github.com/fisharebest/webtrees/blob/0d41e7de2cd76eae3d8c3b669b54cf29df693705/app/Services/GedcomImportService.php#L202

Looks obviously wrong, but seems intentional.  I'd like to take another at it before changing it.

**Comment by fisharebest** [comment]
Looks like the logic was left around after a previous re-factor.

**Comment by Bogiegit** [comment]
Using webtrees 2.2.3 shows the issue is still unresolved.

**Comment by fisharebest** [comment]
Reopening, as the fix was reverted due to #5193
