### ISSUE TITLE
Notes not totalled in Statistics Chart nor Control Panel

### ISSUE THREAD

**Issue by RAMINCNZ** [fisharebest/webtrees#5078]
Pretty much as the Title suggests I have found that Notes are not totalled in Stats Chart nor on the Tree Module in the Control Panel.

![Notes-1](https://github.com/user-attachments/assets/8d384655-5168-4408-9cad-1563d77f9f04)

![Notes-2](https://github.com/user-attachments/assets/1d0a9d04-740a-42df-afd6-1df6925f3b8d)

Minor issue for sure

Rick M
New Zealand - Nu Tirani

**Comment by fisharebest** [comment]
This is a count of records - i.e. "shared notes".  Not inline notes.

Works for me...
<img width="864" alt="Screenshot 2024-12-12 at 10 19 59" src="https://github.com/user-attachments/assets/4c845184-4244-4472-8aad-a534d3496f16" />

**Comment by RAMINCNZ** [comment]
Ok its not that intuitive, thanks for the explanation.

Rick M
New Zealand - Nu Tirani
