### ISSUE TITLE
Error in custom module with webtrees 2.2.1

### ISSUE THREAD

**Issue by jpretired** [fisharebest/webtrees#5080]
With my own custom module I get an error with webtrees 2.2.1, php 8.3.
This is my custom module for Privacy policy:
[module-php.zip](https://github.com/user-attachments/files/18142192/module-php.zip)

This is the error:
[error-cust-module.txt](https://github.com/user-attachments/files/18142169/error-cust-module.txt)
Please help!

**Comment by fisharebest** [comment]
The function `app(...)` no longer exists in webtrees 2.2

Instead, use `Registry::container()->get(...)`
