### ISSUE TITLE
Suggestion: Cache result of BadBotBloker 

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#5084]
I've been playing around with Xdebug and Q/KCacheGrind recently to optimise my IIS / PHP installation, and I've noticed along the way that BadBotBloker seems to be one of the more time-consuming WT functions.

Since each IP address is checked for all negative bots, for a positive IP address the full path is traversed with each click.

It should be easy to cache the result for each IP address, whether positive or negative, to minimise the processing time.

**Comment by fisharebest** [comment]
I'm not seeing this.  Here's a screenshot of qcachegrind on my dev machine, and `BatBotBlocker` is almost undetectable.

Can you share your findings?

<img width="633" alt="Screenshot 2024-12-20 at 15 29 01" src="https://github.com/user-attachments/assets/31ab64ac-f2fb-43aa-bb20-45646bc5340e" />

**Comment by FrankWarius** [comment]
this is a snapshot of a Indi call
![image](https://github.com/user-attachments/assets/efaafcd9-c664-4045-9346-4a67342ab389)

**Comment by fisharebest** [comment]
OK, odd.  Can you see a breakdown of what's happening inside the function?

**Comment by FrankWarius** [comment]
fhe folder is in the source-list but
![image](https://github.com/user-attachments/assets/58941b46-817b-4537-8cc3-2a6e44fcfa64)

I'll will check the config tomorrow

**Comment by FrankWarius** [comment]
There is a cachegrind bug that appears under non-linux filesystems. I had to change grind output to relative path (https://stackoverflow.com/questions/21022365/qcachegrind-source-code-path-wrong)

now we get
85.59 1 call(s) to <cycle 5> via Middleland\Dispatcher -> handle
85.59 / 86.04 = 99,5%
the rest seems normal (no need for caching?)

Maybe it's a XDebug/Windows artefact. The average response time of the website (Prod) is 500 ms. 

![image](https://github.com/user-attachments/assets/ea8cf16a-269d-48d6-960d-8b2e430d77d6)
