### ISSUE TITLE
Cannot create new citation source

### ISSUE THREAD

**Issue by kpouget** [fisharebest/webtrees#5086]
Hello, 

I'm a long time user of Webtrees, but since a "recent" update (maybe >1y), I cannot create new citation source :/ 

![image](https://github.com/user-attachments/assets/d8c3adb6-f15e-4c4e-82e8-bddd1a2be390)

See this screenshot, where I wrote `nothing` ...nothing works :/ 
When I want to save, it says `Please select an item from the list` ... but the list is empty and I don't know how to populate it :| 
The field name contains `INDI-BIRT-SOUR-_ACT-city`, that's an indicator of what's expected, but I don't know where to fill it ...

I'm using https://github.com/fisharebest/webtrees fork, so I don't know if my issue is related to the main repo or Fisharebest. Asking here first, I'll ask there if not part of the main repo.
Currently using `v2.1.22`.

*EDIT:* using this fork: https://github.com/jon48/webtrees-geneajaubart

Thanks for any help :)

**Comment by fisharebest** [comment]
FYI, this is the main repository.  @fisharebest is the author of webtrees...

I am confused.  When webtrees creates new citations, it does not create the `_ACT` field.

It will recognise *existing* `_ACT` fields, but only when they are directly within a fact/event.  e.g. INDI:BIRT:_ACT.

Have you modified your code to add `_ACT` in other places?  Are you using a third-party module that does this?

**Comment by kpouget** [comment]
sorry @fisharebest 😅 I confused the names 😅 😅 
it's this fork I'm using: https://github.com/jon48/webtrees-geneajaubart

> Have you modified your code to add _ACT in other places? Are you using a third-party module that does this?

when I started using WebTrees years ago, this fork had some Birth/Marriage/Death badges that where very useful for genealogy research work.

It's totally possible that my issue is specific to this fork ....

**Comment by fisharebest** [comment]
OK, I'm guessing that this issue is specific to @jon48's fork.  Try raising an issue there.
