### ISSUE TITLE
Webtrees theme secondary menu error

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#511]
For secondary menus (My pages, favourites, themes etc.) the vertical dividing lines are incorrectly positioned on RTL languages and on Firefox 36.0.4 (and possibly earlier - didn't check) for RTL languages the menus jump all over the place on hover (only webtrees theme)

**Comment by fisharebest** [comment]
I'm using FF 36.0.1, and don't see anything unexpected.  Can you post a screenshot?

**Comment by ddrury** [comment]
First image just demonstrates bar placement (also seen on chrome) no bar between My pages & favorites, extra bar at right hand end)
![demo0](https://cloud.githubusercontent.com/assets/104515/6790391/20d7ba78-d19f-11e4-9166-9e8014bfffa4.jpg)

Second image shows what happens when I hover on language (but the menus change as I move across the word)
![demo1](https://cloud.githubusercontent.com/assets/104515/6790394/237d768c-d19f-11e4-9714-ff6e5c115d76.jpg)

**Comment by fisharebest** [comment]
You have RTL layout, but don't have translation into a RTL language?

I think this is because the CSS `:after` is confused by the LTR text.

Does the problem go away when you have RTL text?

**Comment by makitso** [comment]
Tried this on Win8 and FF 36.04 and could not see it.  However, for RTL testing I use Hebrew

**Comment by ddrury** [comment]
91b81fd2c363c400276c2a073e6d57ec924b31f8 fixes this
