### ISSUE TITLE
Uncaught exception 'Zend_Locale_Exception'

### ISSUE THREAD

**Issue by Amgine0** [fisharebest/webtrees#515]
<br />
<b>Fatal error</b>:  Uncaught exception 'Zend_Locale_Exception' with message 'Unknown script 'latin'. Use 'Latn' for digits 0,1,2,3,4,5,6,7,8,9.' in /var/www/webtrees/library/bombayworks/zendframework1/library/Zend/Locale/Format.php:216
Stack trace:
#0 /var/www/webtrees/library/WT/I18N.php(415): Zend_Locale_Format::convertNumerals('856', 'latn', 'latin')
#1 /var/www/webtrees/library/WT/I18N.php(400): WT_I18N::digits('856')
#2 /var/www/webtrees/includes/hitcount.php(94): WT_I18N::number('856')
#3 /var/www/webtrees/includes/session.php(651): require('/var/www/webtre...')
#4 /var/www/webtrees/index.php(30): require('/var/www/webtre...')
#5 {main}
  thrown in <b>/var/www/webtrees/library/bombayworks/zendframework1/library/Zend/Locale/Format.php</b> on line <b>216</b><br />

**Comment by Amgine0** [comment]
Note: happened whilst editing in the tree remotely - no server changes or anything I can see. Ran apt-get immediately when I got home, then added debugging to index.php and got this.

**Comment by fisharebest** [comment]
Which version of the code?

Zend_Locale was removed a few weeks ago.

**Comment by Amgine0** [comment]
1.6.2

**Comment by fisharebest** [comment]
Are you switching between different versions of webtrees (dev / 1.6.2)?

I have only seen this when I have an active login session with one version, and then replace the code with another version

**Comment by Amgine0** [comment]
No, strictly working with the one site and tree. The issue was resolved when I next managed to get internet, so I assumed it was something to do with the session/cookies. Unfortunately, I no longer remember what I was working with at the time.

**Comment by fisharebest** [comment]
Since the error is in code that no longer exists, it is presumably fixed for the next release.
