### ISSUE TITLE
Error to access Admnistration / Modules 

### ISSUE THREAD

**Issue by Fa10175** [fisharebest/webtrees#520]
Download 2015/03/28
I have this error when i try to access Admnistration / Modules for all options
Fatal error: Class 'WT_Module' not found in .... / webtrees-master/modules_v3/pedigree_report-add/module.php on line 31

**Comment by fisharebest** [comment]
This is a custom module.

It will need to be updated for webtrees 1.7

Where did you get this module?  Who is the author?

**Comment by Fa10175** [comment]
inside this file i saw:
// $Id: module.php 12993 2011-12-05 18:13:17Z greg $
inside class_pedigree.php
 * $Id: class_pedigree.xml 11124 2011-03-15 20:20:18Z lukasz $ 
inside report.xml


I hope that help you

**Comment by fisharebest** [comment]
Once the 1.7.0 release is complete, I may have time to help upgrade custom modules.

But this file is not part of webtrees, and I have never seen/used it.
