### ISSUE TITLE
Icons need to be to the right on rtl pages

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#522]
Website - webtrees/admin_site_clean.php – Clean-up data folder
We need to print the trash and danger icons to the right of the check-boxes and the file names

Family trees – admin_trees_manage.php – Manage family trees
The options under the titles Family tree, Genealogy data, Add unlinked records and GEDCOM file, should print with the icon to the right and then the text.

**Comment by fisharebest** [comment]
I discussed this last year on the font-awesome project

https://github.com/FortAwesome/Font-Awesome/issues/3505

**Comment by fisharebest** [comment]
Fixed
