### ISSUE TITLE
ltr admin URL and file data on rtl pages should print as on ltr pages

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#523]
Family trees – admin_trees_manage.php – Manage family trees
Create new family tree
URL – we should swap the columns and print them ltr.
= is on the wrong side of the text & the file name should print to the right of =.
The boxes should be as on ltr pages.

Family trees – Family tree – webtrees/ admin_trees_config.php
action=general – Preferences - General
URL – we should swap the columns and print them ltr.
= is on the wrong side of the text. 
The boxes should print as on ltr pages.

Family trees – Family tree – webtrees/ admin_trees_config.php
action=general – Preferences - Media - Media folders
Media folder - we should swap the columns and print them ltr. 
The boxes should print as on ltr pages.

Family trees - GEDCOM file - Import
Select a GEDCOM file to import - A file on the server
We should print the file name to the right of the directory,
The boxes should print as on ltr pages

**Comment by melizaa** [comment]
I can change the code to print the data in correct sequence, but I do not know how print the boxes as expected.I think that we need to use bootstrap instead of bootstrap-rtl.

**Comment by melizaa** [comment]
Also
Website - webtrees/admin_site_config.php
action=tracking - Tracking and analytics
Piwik URL – trailing / printed to the left

**Comment by fisharebest** [comment]
There doesn't seem to be an easy way to combine LTR and RTL bootstrap markup.

**Comment by fisharebest** [comment]
The bootstrap-rtl project (https://github.com/morteza/bootstrap-rtl) doesn't currently support bootstrap4.  There are no indications that it plans to do so.

Investigate https://github.com/mmdsharifi/Bootstrap4-RTL
