### ISSUE TITLE
Missing verical lines on rtl admin pages

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#525]
Website - webtrees/admin_site_logs.php?action=show – Website logs
In the table, the vertical line between the User and the Family tree is missing. 

Website – webtrees/admin_site_access.php – Website access rules
We do not see the data table vertical line between the rule and the comment. 

Family trees – Family tree – webtrees/ admin_trees_config.php
action=privacy – Privacy
In the table, the vertical line between Access level and the +Add column is missing. 

webtrees/admin_site_change.php?action=show – Changes
In the table, the vertical line between the User and the Family tree is missing. 

Users - admin_users.php – User administration
action=edit – Edit user
In the table, the vertical line between the Individual record and Restricted to immediate family is missing.

Users - admin_users.php – User administration
action=edit – Add a new user
The vertical line between the Individual record and Restricted to immediate family is missing.

Media - webtrees/admin_media.php
Vertical line is missing between Media and Media object.

Modules - webtrees/admin_modules.php – Module administration
Google Maps - module.php?mod=googlemap
mod_action=admin_place
The vertical line is missing between Edit and Delete.

Modules - webtrees/admin_modules.php – Module administration
Google Maps - module.php?mod=googlemap
mod_action=admin_placecheck
The table vertical lines between level 5 Latitude and Longitude and to the left of the Longitude are missing

**Comment by fisharebest** [comment]
https://github.com/DataTables/Plugins/issues/177
