### ISSUE TITLE
Trailing special character in user's real name

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#528]
Control panel - webtrees/admin.php – Users on the page
ltr user with a trailing special character like ). The ) is printed to the left as ( on the rtl page
rtl user with trailing (surname) is printed on the ltr pages with the (surname) to the right 
rtl user with trailing special character is printed on the ltr pages with the special character to the right

**Comment by melizaa** [comment]
rtl user with trailing special character is still printed on the rtl & the ltr pages with the special character to the right

The user shows OK on the admin_user.php pages and on his My page

**Comment by fisharebest** [comment]
It seems OK everywhere I look.

Can you give an example?

**Comment by melizaa** [comment]
Sample:
In the Dashboard list of users for the last user in the list of user types I see [like here]: יעל בר (נהר) 
In User administration and in Edit user I see as user's real name : (יעל בר (נהר 

Meliza

**Comment by fisharebest** [comment]
Which browser?

This is what I see

![untitled](https://cloud.githubusercontent.com/assets/2306088/7102444/3624b596-e079-11e4-8ca5-bc5740de80dd.png)

**Comment by melizaa** [comment]
What do you see In User administration and in Edit user?
I see it in Chrome.

In IE and Firefox I see it OK on the rtl and ltr Dashboard and User administration.

**Comment by melizaa** [comment]
I defined your user. I see the name in Chrome OK in the Edit user page.
This is what I see in the Dashboard
![huserspecchar](https://cloud.githubusercontent.com/assets/5202996/7102712/fc97fee6-e091-11e4-83a1-c3ce8062aa95.jpg)

**Comment by fisharebest** [comment]
This looks like a problem with chrome.

The markup is correct (<span dir="auto"></span>), but it
does not work as expected.

Greg

On 11 April 2015 at 19:30, melizaa <notifications@github.com> wrote:

> I defined your user. I see the name in Chrome OK in the Edit user page.
> This is what I see in the Dashboard
> [image: huserspecchar]
> <https://cloud.githubusercontent.com/assets/5202996/7102712/fc97fee6-e091-11e4-83a1-c3ce8062aa95.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fisharebest/webtrees/issues/528#issuecomment-91896266>
> .
>



-- 
Greg Roach, Stony Stratford, Bucks, England, greg@subaqua.co.uk
"Don't eat animals - it's not good for them and they don't like it"

**Comment by melizaa** [comment]
If I change the code I see the ltr and rtl users' real names as expected in chrome.
I see them also OK in IE and FF.

From
<a href="admin_users.php?action=edit&user_id=<?php echo $user->user_id; ?>" dir="auto">
	<?php echo Filter::escapeHtml($user->real_name); ?>
To
<a href="admin_users.php?action=edit&user_id=<?php echo $user->user_id; ?>">
	<?php echo '<span dir="auto">' . Filter::escapeHtml($user->real_name) . '</span>'; ?>

**Comment by melizaa** [comment]
![dashboardusers](https://cloud.githubusercontent.com/assets/5202996/7104868/63edba5e-e105-11e4-987a-76f6f1976849.jpg)
