### ISSUE TITLE
What does the following mean in Website access rules?

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#530]
Website – webtrees/admin_site_access.php – Website access rules

What does it mean to see that the table is sorted (as a default) by the Edit icons?

I see “Showing 1 to 10 of 13 (filtered from 8 total entries)”. What does the 8 mean?

**Comment by fisharebest** [comment]
This would be unusual.  I would expect the "8" to be larger than the "13".

It means that the table would normally contain "8" entries, but you have typed something into the search/filter box, and are only seeing 13 of these 8 entries.

**Comment by melizaa** [comment]
In future I see 1 to 10 of 10 (filtered from 8 total entries).
I do not filter anything.
The last 2 have unknown rules.

In build I see Showing 1 to 10 of 13 (filtered from 8 total entries) without any filtering.
The 5 last ones have unknown rules.

 

Meliza

**Comment by fisharebest** [comment]
OK - in 1.7.0, we combined the two tables.
But we are still generating the total count from the old "top" table.
Fixed!
