### ISSUE TITLE
BranchesController.php : gedcomid or rootid ?

### ISSUE THREAD

**Issue by Gustine** [fisharebest/webtrees#534]
On line 54 of BranchesController.php, getUserPreference calls gedcomid instead of rootid (called on lines 207 and 243). Error or not ?
http://www.webtrees.net/index.php/en/forum/3-help-for-beta-and-github-versions/30199-lists-of-branches-sosas-and-generations#52474

**Comment by fisharebest** [comment]
These should be gedcomid.  We want to show the relationship for the SOSA that we just displayed.

Nobody else commented on the forum.  I guess everyone is happy that we calculate SOSA for the individual record...
