### ISSUE TITLE
Civil & Religious wedding

### ISSUE THREAD

**Issue by Feandil** [fisharebest/webtrees#537]
It's possible to set a wedding to be either Civil or religous, but I didn't see any way of having both.
Did I miss soemthing?

**Comment by fisharebest** [comment]
...or just leave the type empty?

I would normally use the types "civil" and "religious" when the two events are different.  For example, in some countries, you have a civil marriage at a government office, followed by a religious ceremony elsewhere.

It may be better to ask this question on the forum at www.webtrees.net.  Hundreds of people read the forums.  Very few read the bug reports....
