### ISSUE TITLE
Create new family tree

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#540]
Family trees – admin_trees_manage.php – Manage family trees - Create new family tree

Should the text “Avoid spaces and punctuation. A family name might be a good choice.” print under the Family tree title?

**Comment by vytux-com** [comment]
Yes. They are help texts, this should be closed as it's working as designed

**Comment by melizaa** [comment]
The text prints now under the URL, not under the Family tree title.

**Comment by fisharebest** [comment]
To create a tree, we need two things:

1) The descriptive name/title - shown at the top of each page
2) The URL / GEDCOM name - used to create files, URLs, etc.

This is the help text for (2).

If you found this confusing (and you know the system!), then perhaps we also need help text for (1).

Or perhaps we need different labels for the two fields.

**Comment by fisharebest** [comment]
I've removed the default text from the "family tree title" option.  We want the user to enter a real title.

I can't think of any useful help text for this field.
