### ISSUE TITLE
Can't inherit abstract function Fisharebest\Localization\Locale\LocaleInterface::endonym()

### ISSUE THREAD

**Issue by wooc** [fisharebest/webtrees#543]
When I try to view page with the recent git code.

Fatal error: Can't inherit abstract function Fisharebest\Localization\Locale\LocaleInterface::endonym() (previously declared abstract in Fisharebest\Localization\Locale\AbstractLocale) in \vendor\fisharebest\localization\src\Locale\LocaleEn.php on line 12

**Comment by wooc** [comment]
My browser is set to Polish language.

**Comment by fisharebest** [comment]
Which version of PHP do you use?

I think this is a problem with PHP 5.3.0 -> 5.3.8

**Comment by wooc** [comment]
5.3.8

**Comment by fisharebest** [comment]
The file `./vendor/fisharebest/localization/src/Locale/AbstractLocale.php` contains two abstrct functions `endonym()` and `language()`.

What happens if you delete these two functions?

**Comment by wooc** [comment]
Fatal error: Can't inherit abstract function Fisharebest\Localization\Script\ScriptInterface::code() (previously declared abstract in Fisharebest\Localization\Script\AbstractScript) in \vendor\fisharebest\localization\src\Script\ScriptLatn.php on line 10

**Comment by fisharebest** [comment]
OK, delete the abstract functions `code()` and `number()` from `./vendor/fisharebest/localization/src/Script/AbstractScript.php`

**Comment by wooc** [comment]
Fatal error: Can't inherit abstract function Fisharebest\Localization\Territory\TerritoryInterface::code() (previously declared abstract in Fisharebest\Localization\Territory\AbstractTerritory) in \vendor\fisharebest\localization\src\Territory\TerritoryPl.php on line 10

**Comment by magicsunday** [comment]
Same here. Also PHP 5.3.8

Fatal error: Can't inherit abstract function Fisharebest\Localization\Locale\LocaleInterface::endonym() (previously declared abstract in Fisharebest\Localization\Locale\AbstractLocale) in C:\Projekte\webtrees\vendor\fisharebest\localization\src\Locale\LocaleEn.php on line 12

    class LocaleEn extends AbstractLocale implements LocaleInterface

Both AbstractLocale and LocaleInterface implement the method "endomym"! The abtract class AbstractLocale should implement the LocaleInterface and the class LocaleEn should only implement the AbstractLocale and not the Interface (not necessary here) so no duplicate methods will exists.

**Comment by fisharebest** [comment]
> there is no need to declare it twice in the abstract and interface class.

There is no need for it, but it helps development-environments (e.g. PhpStorm) to understand the code - and it is valid in PHP5.3.9 onwards.

**Comment by magicsunday** [comment]
Now it works for my PHP 5.3.8 but using PHP 5.3.29 it results in:

Fatal error: Call to undefined method Fisharebest\Localization\Locale\LocaleDe:: �x0ETag() in /share/MD0_DATA/Web/webtrees/app/I18N.php on line 398

sometimes in:

Fatal error: Call to undefined function () in /share/MD0_DATA/Web/webtrees/app/I18N.php on line 398

**Comment by fisharebest** [comment]
The unit tests for this ran OK on PHP5.3.29
https://travis-ci.org/fisharebest/localization/jobs/57346980

At line 398, the code should be calling Locale::languageTag().

Do you have any corrupt files?

**Comment by magicsunday** [comment]
No corrupt files. I did a

    git reset --hard origin/master

to completly overwrite all files.

Here is another error I got:

Fatal error: Call to undefined function ks/zendframework1/library/zend/exception.php0xb666f3a() in /share/MD0_DATA/Web/webtrees/app/I18N.php on line 397

**Comment by fisharebest** [comment]
`zend exception` ???

The I18N class no longer uses and Zend libraries.
