### ISSUE TITLE
Translate user language automatically from xx_yy to xx-yy

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#551]
I have on my production site over 350 user whose language is en_GB or en_US. We should automatically transfer them to en-GB and en-US. 

Now, if the user is edited the language is changed by webtrees 1.7.0-dev to the 1st defined language, in my test site Afrikaans.

**Comment by fisharebest** [comment]
There is already an upgrade script for this (and some other changes).  See includes/db_schema/db_schema_29_30.php

It will be run automatically when you upgrade to 1.7.0.

You are currently using 1.7.0-dev, (which comes between 1.6.2 and 1.7.0).
