### ISSUE TITLE
Request for new password

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#561]
When a user requests a new password (login page) and enters an email address, there is no system check to determine if it's a valid email address.  Shouldn't this check be made?

**Comment by fisharebest** [comment]
We used to have validation, but I think it was removed because it failed with things such as `user@localhost` or `user+xxx@example.com`.

If you can find a suitable rule for matching email addresses, then go ahead and add it.

**Comment by makitso** [comment]
Also, the lots password text block says "Username or email address" but does not validate a username.

**Comment by makitso** [comment]
Not having a validation check would allow a spammer to create bogus emails to valid email addresses.

**Comment by makitso** [comment]
The email validation does work correctly on the "Request new user account" screen.

**Comment by fisharebest** [comment]
> Not having a validation check would allow a spammer to create bogus emails to valid email addresses.

Emails are only sent if the supplied value is a known username/email.  The message "A new password has been created and e-mailed to foo@bar." is always displayed - even if no message is actually sent.

The idea is to prevent people from using this page to guess at value usernames/emails.

I suppose it is, perhaps, unnecessarily defensive, and we could instead display "Nobody here by that name" or similar.

> The email validation does work correctly on the "Request new user account" screen.

When we register, we supply two values - username and email.  We can validate the email.

In the "forgot password" page, the supplied value can be either an email or a username - which can be arbitrary text.  So, we cannot validate it.

BTW - I recently updated the code to remove the restriction on characters in a username.  It is now possible to have a username like `><(((('>` if you really want!



But I see the validation (`WT_REGEX_USERNAME`) is still used.  I should remove this.
