### ISSUE TITLE
Fatal error during registration

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#563]
[Sat Apr 18 16:17:56.399392 2015] [:error] [pid 1303] [client 127.0.0.1:54341] PHP Fatal error:  Call to undefined method Fisharebest\\Webtrees\\Tree::title() in /home/rob/www/login.php on line 326, referer: http://localhost/login.php?action=register
-------------
My guess is that $WT_TREE->title should be $WT_TREE->getTitleHtml()  but am not sure.

**Comment by fisharebest** [comment]
Since this is to go in an email subject, we don't want any HTML markup.

We just need `getTitle()` instead of `title()`.
