### ISSUE TITLE
Not all labels available for translation.

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#564]
For instance, I can not find "Find duplicates" or "No duplicates have been found." (admin_trees_duplicates.php) inside the german or english language files.

**Comment by fisharebest** [comment]
The .PO files are only updated every few weeks (or if there are very many changes).

Even small changes to text can create very large increases in the repository size - as the line numbers all change.

Also, it takes approx 1hr of CPU to import the new .PO files into the translation server.

The latest files are currently being imported.
