### ISSUE TITLE
Remarried couple not recognized

### ISSUE THREAD

**Issue by oogoofeo** [fisharebest/webtrees#567]
Hi!

If a couple is married, divorced and remarried, WT still considers them ex-husband/wife.

**Comment by fisharebest** [comment]
The logic is this:

If a `DIV` record exists, then describe them as "ex-husband/wife".
If a `MARR` record exists, then describe them as "husband/wife".
Otherwise, describe them as "partners".

I'm not sure what else we could do.  We need to be able to work without dates (as data is often incomplete), so we can't just look at the latest `MARR` or `DIV` record.

It is also common in many countries to have two marriage records (one religious, one legal/civil) - so we can't simply count the number of marriages and divorces.

I can't think of a solution that wouldn't cause more problems than it fixes.  I think we may have to accept this anomaly when a couple divorces and re-marries.

**Comment by wkitty42** [comment]
is there no way to handle this by the dates of the activities? i know that there are and have been times that i've had to go back into the GED and order some things how they really happened to have them display oldest to newest... this should allow us to see that they were married, then divorced and now married again and display them as a simple married couple... unless you want to try something like a married ex-couple but i don't think that's really necessary ;)

**Comment by fisharebest** [comment]
> is there no way to handle this by the dates of the activities?

No, because we don't always know the dates.

e.g.

```
1 MARR
2 DATE 20 JAN 2000
2 TYPE religious
1 MARR
2 DATE 25 JAN 2000
2 TYPE civil
1 DIV Y
```

We cannot tell if this is a couple who remarried, or divorced couple.

**Comment by wkitty42** [comment]
true on the lack of dates possibility... in those cases, i tried especially hard to ensure that the activities were listed in chronological order... i guess maybe that's really what i was suggesting... use the listing order if dates do not exist... folks can still edit the order of the actions in the GED, right? that carries over to the ordering in the database, doesn't it?

**Comment by fisharebest** [comment]
The number of couples who remarry after divorcing is quite small.

I'm pretty sure than any "fix" will cause more problems than it solves.

> folks can still edit the order of the actions in the GED, right?

The GEDCOM spec says that multiple versions of the same event (e.g. conflicting data) should be stored in the order of preference.  It says nothing about storing events in chronological order.

**Comment by wkitty42** [comment]
> The GEDCOM spec says that multiple versions of the same event (e.g. conflicting data) should be stored in the order of preference. It says nothing about storing events in chronological order.

makes sense... for us, "order of preference == chronological order (oldest to newest)" :wink: :smile_cat:

**Comment by fisharebest** [comment]
I will leave this issue open for a while, in case anyone else has any ideas for a reliable algorithm.

But if not, I think we will need to accept this anomaly.

**Comment by bmhm** [comment]
I think there might be a solution as long as if there are enough dates. If not, fall back to the current solution. I'd like to see this resolved, too. Please don't close it too soon.

**Comment by oogoofeo** [comment]
Hi,

fisharebest wrote:
> We need to be able to work without dates (as data is often incomplete),
> so we can't just look at the latest MARR or DIV record.

OK, what about considering this records only if they contain a date? IF [DIV] contains date AND [MARR] with later date is present, consider them as married, ELSE treat it as always.

**Comment by Amgine0** [comment]
++oogoofeo, although the additional complexity is meh.

Common-law relationships are somewhat more prone to periodic separation/re-establishment.  [Long essay about low genealogic relevance of some GED fields and the effort put into divorce/marriage religious/civil/common data deleted.] If possible, simplify what is tracked.
