### ISSUE TITLE
unable to change session parameters 

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#573]
app/Session.php function start

changed line 42 to 

    var_dump($key, ini_set($key, $value));

and all keys return false apart from session.use_cookies which returns 1 (default value anyway)

Tried with various php versions all on win7 x64 - no log entries and no disabled functions

**Comment by ddrury** [comment]
I think all the parameters have to start with session; so "session.name" etc. This is why session.use_cookies is the only option that works

**Comment by fisharebest** [comment]
Aha.  Well spotted.

I had based this code on `Zend_Session::setOptions()`, but missed this.

**Comment by ddrury** [comment]
Yeah - I saw the entries in the PHP docs but it was a case of can't see 
for looking.

Regards
David

Please consider the environment before printing this e-mail



------ Original Message ------
