### ISSUE TITLE
Problem with Session::put() & Session::get()

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#574]
The easiest way to demonstrate the problem is to use lifespan.php.
1. Hit the clear button to empty the chart
2. "Add another individual to the chart" - uncheck the "Include the individual’s immediate family?" checkbox - that person should be displayed and the xref stored in the session
3. Repeat No 2 (above) with different people and each iteration should add the new person to the chart

On my system sometimes the person is added, other times the previous entry is over-written, or the entire list is deleted. I tried json encoding/decoding the variable but it made no difference. If I put a few strategically place var_dump()s around, things change - A timing issue?

I thought the recent Session variable fix may have solved it but no luck!

**Comment by fisharebest** [comment]
> The easiest way to demonstrate the problem is to use lifespan.php.

I tried this.  I added 10 individuals (i1 ... i10).  I now have a chart with the the 10 individuals I selected.

Do you have any local code changes?  For example, any `var_dump()` before the page header is written, which would close the session and prevent further updates from being persisted?

**Comment by ddrury** [comment]
I had a horrible feeling this would be the case. No code changes, maybe a windows problem? but I haven't the foggiest where to start

**Comment by ddrury** [comment]
Withdrwn as I have the same problem with 1.6.2 code
