### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#579]
It would be convenient if app/Date/CalendarDate.php provided access to the fisharebest/ext-calendar CalendarInterface.php jdStart & jdEnd variables, e.g.

    	public function jdStart() {
            return $this->calendar->jdStart();
        }

    	public function jdEnd() {
            return $this->calendar->jdEnd();
        }

**Comment by fisharebest** [comment]
Out of curiosity, what is the use case for this?

**Comment by ddrury** [comment]
My revised lifespan chart code offers the opportunity to filter results by a date range. If the start year is omitted I'd like to offer "year one" from the selected calendar - I appreciate that this could be calculated by other means but as I use CalendarDate anyway this would make it trivial.

**Comment by fisharebest** [comment]
Firstly, you can always create one of the calendar objects directly.  e.g.

$cal = new Fisharebest\ExtCalendar\GregorianCalendar;
$cal->jdStart()

Secondly, "year 1" for the gregorian and julian calendars is around 4712 BC - which may not be especially useful.

Alternatively, just use "year 1" of a GEDCOM date.  e.g.

$date = new Date('"@#DFRENCH R@ 1");
