### ISSUE TITLE
URLs in Notes no longer links

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#582]
I have URLs in notes. They used to be links. Now they are plain text.

Some samples: 
http://www.amitys.com/webtrees/mediaviewer.php?mid=M18&ged=Gedcom.ged
and its
http://www.amitys.com/webtrees/mediaviewer.php?mid=M7062&ged=Gedcom.ged
and
http://www.amitys.com/webtrees/mediaviewer.php?mid=M7061&ged=Gedcom.ged#

And:
http://www.amitys.com/webtrees/individual.php?pid=I4611&ged=Gedcom.ged
and
http://www.youtube.com/watch?v=zH33cb3TXoA
http://yle.fi/aihe/artikkeli/2006/12/08/ida-ekman-largo
https://archive.org/details/ida_ekman
etc.

**Comment by fisharebest** [comment]
When using markdown, you must explicitly mark links.

It's in the markdown specification.

**Comment by melizaa** [comment]
note markdowns do not work as expected in reports.

links do not work in PUBL or TEXT fields of sources.
