### ISSUE TITLE
Markdowns do not work in reports

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#589]
Note markdowns do not work in reports.

**Comment by melizaa** [comment]
In order to make my URLs as links in notes I need to fill 
[http://www.stepup.fi/show/6pack.htm](http://www.stepup.fi/show/6pack.htm)

In reports I see
[http://www.stepup.fi/show/6pack.htm](http://www.stepup.fi/show/6pack.htm)
instead of http://www.stepup.fi/show/6pack.htm

Same for titles (###Revision List) and other markdown syntax.

Meliza

**Comment by melizaa** [comment]
I need to fill the url in [] and then in ().

**Comment by fisharebest** [comment]
The reports expect the notes to be inline text.  They are dispayed as footnotes, etc.

What can we do with markdown that contains tables, images, etc.  The report engine can only cope with plain text in this context.

**Comment by melizaa** [comment]
Can we solve text markups?

**Comment by melizaa** [comment]
I have over 3 thousand individuals with URL links that used to work as expected in the past.

Now I add manually markdowns to the URLs of these individuals.
I am not happy to see that the reports do not show the URLs correctly.
