### ISSUE TITLE
Charts and compact mode

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#593]
When (trying) to view some charts in compact mode it is not always working well:
* Ancestors chart: untick the 'show details' button then click the view button -> the chart automatically switches back to full mode.
* Descendants chart and Pedigree chart: when viewing in compact mode, clicking on an arrow automatically brings you back to full mode. It should stay in compact mode. This does work as expected in the hourglass chart.

**Comment by JustCarmen** [comment]
Another one:
In the control panel you can define the maximum pedigree generations to show. Default value is 10. But when choosing a number higher then 8 on the pedigree page, the number switches back to 8. It is not possible to set a higher value even if it is in the list.

**Comment by fisharebest** [comment]
The pedigree chart has a limit of 8 generations - because it uses an HTML canvas, which has a limit of 65536 pixels.

We could display more individuals - but not the connecting lines.

**Comment by ddrury** [comment]
I've create a pull request to fix the problems with the Ancestry & descendancy charts - at some point the show_full parameter has gone missing, however before I submit it, in FunctionsEdit::twoStateCheckbox a second check box is created to handle the onclick event and the name attribute is set to $name . '-GUI-ONLY" so on submission you see two parameters on the command line $name for the first checkbox and $name . '-GUI-ONLY" for the second checkbox . I don't think this second checkbox needs a name attribute

**Comment by ddrury** [comment]
Further to the above, I noticed that in e.g descendancy.php. show_full has morphed into

    <?php echo FunctionsEdit::twoStateCheckbox('show_full', $controller->showFull()); ?>

This function doesn't exist, but I wonder if the intention was to determine the show_full state via this function rather than access a public class variable

**Comment by fisharebest** [comment]
I have discussed the "show full" option with a few others.

On a regular page, it makes very little difference to the display - just a few pixels smaller.  It doesn't allow any more generations to be shown, etc.

The use of `$show_full` is painful to folow.  It is passed as globals to functions which overwrite it, call other functions using it as a parameter, etc.  I started to clean it up at one point, and remove all the global uses.

I'm not sure it makes much sense to include charts in home-page blocks.  There isn't really enough room.  If we do want charts here, then maybe this block should have dedicated code to produce a compact chart with limited generations and a fixed layout?

**Comment by fisharebest** [comment]
The "two state checkbox" is designed to cope with the need for three states:

1) selected
2) deselected
3) neither selected/deselected, and thus takes the default (which can be selected or deselected)

**Comment by ddrury** [comment]
1. The pull request I mentioned above which more or less restored the earlier behaviour is clearly not what you intended and I'll not submit it.
2. I entirely agree about not putting charts in home page blocks
3.If the compact view is abandoned then there is some javascript specific to that facility (I think) that could be at worst simplified, at best removed

**Comment by fisharebest** [comment]
> maybe this block should have dedicated code to produce a compact chart

Actually, I see that it does.

> If the compact view is abandoned 

I'm thinking that we should always generate the full view, but perhaps allow CSS/JS to compact it.

You could then toggle between the two without re-loading the page.

It would be good to know if (m)any people want/use it.  I don't think I've ever seen anyone have it selected by default on their site.

**Comment by JustCarmen** [comment]
> It would be good to know if (m)any people want/use it. I don't think I've ever seen anyone have it selected by default on their site.

I have made a template for the pedigree chart in compact view (only for 'oldest at top' and 'oldest at bottom'). I like this layout because you can have more boxes inside the viewport this way and it gives you a quick overview of the pedigree.

I don't use compactview by default, but I don't think it should be abandoned. It is nice to have that option. This template couldn't be made in full view.

![15-6-2015 7-08-58](https://cloud.githubusercontent.com/assets/5641963/8153430/2564cef2-132e-11e5-9d9b-af86db107e82.jpg)

**Comment by JustCarmen** [comment]
> The pedigree chart has a limit of 8 generations - because it uses an HTML canvas, which has a limit of 65536 pixels.

But why is the default then set to 10?
See: tree.php: $tree->setPreference('MAX_PEDIGREE_GENERATIONS', '10');

**Comment by ddrury** [comment]
> But why is the default then set to 10?
> See: tree.php: $tree->setPreference('MAX_PEDIGREE_GENERATIONS', '10');

>It even is allowed to set this value to a higher number in de control panel.

I seem to remember discussing this with Greg when I submitted the revised code for the pedigree chart but I can't remember his reasoning for keeping things as they are - hopefully he can

**Comment by fisharebest** [comment]
> I can't remember his reasoning for keeping things as they are

This setting is used for lots of things, other than the number of generations in pedigree charts.

Is this a useful setting?  I'm not sure why we have it.

**Comment by wkitty42** [comment]
@fisharebest it was probably used to limit the amount of data transferred or pulled out of the database... is this a carry over from the original project's code before your fork??

**Comment by fisharebest** [comment]
> it was probably used to limit the amount of data transferred or pulled out of the database

You could be right.

People don't like change, and since rewriting to be mobile friendly will be a big change, I figured it would be easier to do it all at once...
