### ISSUE TITLE
Create hooks for php-header, html-head and html-footer

### ISSUE THREAD

**Issue by bmhm** [fisharebest/webtrees#597]
As a module dev, I'd like to intercept the whole page generation on certain events. I cannot do this right now.

Use case:

``` php
if ($_Server['HTTP_ACCEPT'] === "application/ld+json") {
    // create a useful reply
    header("Content-Type: application/ld+json");
    // send requested content
    echo '{ "@type": "Person", "@context": "http://schema.org/" }';
    // prevent sending unrequested content
    exit 0; // or die to prevent further (normal) page loading
}
```

I found something similar in wordpress: http://codex.wordpress.org/Plugin_API/Action_Reference/send_headers

Similar for html-head-section and html footer (template).

**Comment by fisharebest** [comment]
Which code are you looking at?  1.6.2 or master?

I'm pretty sure the latest code will let you do this.

**Comment by bmhm** [comment]
Didn't find anything which fits my needs in https://github.com/fisharebest/webtrees/blob/master/app/Module/AbstractModule.php or in https://github.com/fisharebest/webtrees/blob/master/app/Module/ModuleThemeInterface.php.

So… can you give me a hint?

**Comment by fisharebest** [comment]
`BaseTheme::hook*()`

Set the header in `hookAfterInit()`?
Add your content anywhere.

You can detect the current script using WT_SCRIPT_NAME (although this might disappear)

**Comment by fisharebest** [comment]
Kind of ignore that.  I'm confusing modules and themes.

I've started to convert themes into modules, but keep forgetting that this isn't finished/live yet

**Comment by bmhm** [comment]
You can tag this for 1.8 or any later version (laravel).

**Comment by bmhm** [comment]
Tag 2.0 please, Label Enhancement.

**Comment by fisharebest** [comment]
The latest code allows modules to act as "middleware".

i.e. the request/response cycle gets passed through them, allowing them to intercept the request, modify the response, etc.

To enable this, the module simply needs to implement `MiddlewareInterface`, which is one function `next()`

You'll have access to the request object, so can easily decide whether or not to send the default response or your own response.
