### ISSUE TITLE
SSL Logout

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#601]
Have set up site for using SSL.  Login works correctly.  However, upon logout, the URL is points to the base domain site but still on SSL, eg.  https://domain.com.    Shouldn't a logout put you back on the Login screen or at to the base URL with standard http?

**Comment by fisharebest** [comment]
If you have configured HTTPS, why wouldn't you want to use it all the time?

It prevents things such as malicious wifi hotspots from injecting adverts into pages.

**Comment by makitso** [comment]
Greg,  www.webtrees.net should now be using SSL for everything.  The
configuration is a bit strange, its not set up exactly the way Joomla
says.  But, I think it will work.

**Comment by Amgine0** [comment]
<blinks> How would I go about setting up a malicious wifi hotspot to do that? bet I could make some coffee money off the leechers and have fewer script kiddies busting the router...

**Comment by fisharebest** [comment]
> How would I go about setting up a malicious wifi hotspot to do that?

Technically, this is very easy, and very common.  I've done this myself, using off-the-shelf software.

You set up a wifi hotspot.  You interecept the first HTTP request, and replace the page content with a login, asking for name/email/etc.  You now give free wifi in exchange for the marketing info.

You can also match the credentials against MAC addresses, so you'll know when the customer returns to your store, even if they do not use your wifi the next time.

However, such a hotspot could do **anything** to the pages that pass through it.  For example, insert Javascript to pop up adverts, steal other credentials, etc.

**Comment by makitso** [comment]
Back to the original issue:  when a user logs out, they are redirected to https://domain.com.  I have tried a lot of sites and most redirect back to the login page.

**Comment by bmhm** [comment]
@makitso Shouldn't the login page be the same? What do you expect instead? You mean to /login.php instead of just '/'?

**Comment by makitso** [comment]
@bmhm  Currently, after logout, the redirect is to https://domain.com.  I would think it should be to https://domain.com/login.php

**Comment by fisharebest** [comment]
Every site I've looked at seems to have a login form on the home page, so the home page is **also** the login page.

I have no strong views.  I think we should do whatever is most common/conventional - home page or login page.

>  I have tried a lot of sites and most redirect back to the login page. 

After a few minutes trying various sites, I can't find any that do this.  Paypal goes to the home page.

(FYI, this would be a one-line change.  `WT_BASE_URL` becomes `WT_LOGIN_URL` in `logout.php`)

**Comment by bmhm** [comment]
I'd vote to redirect to the home page. If you do log out, it's almost only on public machines and the probability that some else wants to login right after you is very tiny. I'd rather expect someone else would want to see the public tree. Therefore: :-1:

**Comment by fisharebest** [comment]
What is important is that the user gets positive confirmation that they are no longer logged in.

A login form is one way to do this.

Either way, I think a confirmation message is also helpful - so I have just added a "You have logged out" message.

**Comment by Amgine0** [comment]
"You are logged out" will be easier for translation.

**Comment by fisharebest** [comment]
> "You are logged out" will be easier for translation.

Done
