### ISSUE TITLE
Remove language parameter from URL 

### ISSUE THREAD

**Issue by bmhm** [fisharebest/webtrees#605]
Due to double content indecing and cluttered URLs and laravel on the way, I'd like to propose a new system on how to determine the displayed language. 

1. Read a cookie, if language had been set before. 
2. Try to parse preferred language with Locale::acceptFromHttp(). 
3. If still empty, try some basic geolocation (ip database like piwik?). 
4. fallback language Set in admin
5. English

This would eliminate the need of &lang= and would play more nicely with laravel.

**Comment by bmhm** [comment]
The lang parameter (staying or not)  should cause a 301 redirect to the site without user setting parameters. http://googlewebmastercentral.blogspot.de/2007/09/google-duplicate-content-caused-by-url.html?m=1
Add a re=canonical link https://yoast.com/articles/duplicate-content/#rel-canonical

I'll look into this soon. Same for theme parameter.

**Comment by fisharebest** [comment]
See https://github.com/mcamara/laravel-localization

**Comment by bmhm** [comment]
How much time would I have left to implement a 301 redirection to the same url with lang= stripped?
