### ISSUE TITLE
Private should give 403 instead of 404

### ISSUE THREAD

**Issue by bmhm** [fisharebest/webtrees#607]
If an individuals' record is private, you get a 404 as if it didn't exist. This is a problem because there may be links to it. So Google will see that you habe broken links (link to 404 = broken). 

403 Forbidden would be better, because the link is not considered broken anymore. It is a small fix in session.php, pull request comming in a few hours.

**Comment by bmhm** [comment]
Sorry, I should now always create a new branch. =)

**Comment by fisharebest** [comment]
I thought I already commented, but I can't find my comments...

Originally, we had this behaviour.  Two different error pages "Not found (404)" and "Not allowed (403)".  By popular demand, these were combined into a single error "Not found or not allowed (404)".

Although this change may be technically correct - I am not sure it will be welcomed.

As far as I know, search engines, etc., treat all 4xx errors the same.  Are there any benefits to end-users of this change?

**Comment by bmhm** [comment]
Yes you did already comment on this, I think on one of your commits.

I'd vote to be able to chose from 403 or 404. Reason: A missing individual id (number) can be a hint or a clue, but could never be evidence for existing persons. Also, I would not want to have dead links on my domain.
So if you could chose from those two options, everyone would be satisfied.

Or you could also link it to the "links to private individuals" settings. As soon as it is enabled, use 403 instead of 404. Problem solved in an elegant way.

**Comment by fisharebest** [comment]
http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

> 10.4.4 403 Forbidden
> --------------------------
> If the request method was not HEAD and the server wishes to make public why the request has not been fulfilled, it SHOULD describe the reason for the refusal in the entity. If the server does not wish to make this information available to the client, the status code 404 (Not Found) can be used instead. 

Since we do not wish to give a reason, then it is valid to send a 404 response.

Google should not see links to private records, because we do not generate them.  If there are links to private records, then this is probably a (different) bug.
