### ISSUE TITLE
Error in Lists when certain letters are clicked in tag cloud style

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#611]
the Individual list
In the test system with the latest code I see for top letters ?, Thai letters, Ø, etc.:
#0 /app/Functions/FunctionsPrintLists.php:1627 ErrorException("Division by zero") #1 /indilist.php:197 surnameTagCloud([array], 'indilist.php', true, [Tree])

I have a similar issue in my prod site with older 1.7.0 code
#0 /includes/functions/functions_print_lists.php:1621 ErrorException("Division by zero") #1 /indilist.php:195 Fisharebest\Webtrees\format_surname_tagcloud([array], 'indilist.php', true, [Tree])

the family list
For the latest code I see for the top letters ?, Thai letters, Ø, etc.:
#0 /app/Functions/FunctionsPrintLists.php:1627 ErrorException("Division by zero") #1 /famlist.php:196 surnameTagCloud([array], 'famlist.php', true, [Tree])

I do not know why these letters give the errors. I used to see the lists of all the top letters without errors in the past.

Meliza

**Comment by fisharebest** [comment]
Without access to the data, it is difficult to investigate.

It would appear that a surname is found - but no individuals are found.  Perhaps you could add some debug to identify the name, and then examine the name.

**Comment by melizaa** [comment]
The error happens when lists are shown in tag cloud style.
