### ISSUE TITLE
Text "was born" not translated

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#612]
I see English text "was born" in the Ancestors and the Descendants reports in all the languages. I do not see the text in the webtrees language translation site.

The problem exists also on my production site with older 1.7.0 code.

Meliza

**Comment by fisharebest** [comment]
The translation system is designed to extract text from .PHP files.

For the .XML files, we need to use some "clever tweaks".  I guess these weren't quite clever enough...

**Comment by fisharebest** [comment]
These messages will not appear until I next rebuild the .PO files.
