### ISSUE TITLE
Undefined $spid error in ancestors report

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#613]
Undefined variable $spid in the I1 report in the new 1.7.0 code.

I do not see the error on my prod site with older 1.7.0 code.

Meliza

**Comment by makitso** [comment]
Can't reproduce on demo site -- how are you getting this?

**Comment by melizaa** [comment]
I see the error in Website logs both for PDF and for HTML reports in Chrome and in IE (I have not tested in other browsers). I see a report. I do not see the error on the webtrees page nor in the error_log. I do not know what causes it and I am sorry, but I cannot analyze what causes it in the near future.

I see the error for I1 (me), for I90 (my husband) and for I269 (my grandfather). These are the only individuals for whom I have tried to create the report.

I show 3 generations and sources. My site defines mostly record sources, not fact sources.

**Comment by makitso** [comment]
Can you reproduce the error on the demo site and if so what parameters are you using?

**Comment by melizaa** [comment]
I do not know about the demo-dev site, I do not see the Website logs.

I just tested the report on the demo-future site "JG test one" for default I00001. I see the error message in Website logs.
![ancestorswebsitelog](https://cloud.githubusercontent.com/assets/5202996/8150641/2d66c3be-12fa-11e5-99ad-007ec9b1751e.jpg)

**Comment by makitso** [comment]
OK, I thought the error was in the apache log.  I can see it in the
webtrees log.

**Comment by fisharebest** [comment]
This is a bug in the design of the XML reports.

These report errors have always been suppressed.

I enabled the display of them, so that they can be found/fixed.  But there were too many errors, so I suppressed them again.  Hence you may no longer see errors that you found in the logs.

> demo-future site

This site was not intended for public access.  I have now removed it.

**Comment by melizaa** [comment]
The errors are created to the Website logs using the latest GitHub code.

Meliza

**Comment by fisharebest** [comment]
This error has always existed.

Only now it is being recorded.

This is a low priority - and you can safely ignore it.
