### ISSUE TITLE
Error when using Arial font

### ISSUE THREAD

**Issue by vytux-com** [fisharebest/webtrees#617]
When using Arial font and PDF output I get the following error: TCPDF ERROR: Could not include font definition file: arialunicid0

Some of the text does include non Latin chars like ė

**Comment by fisharebest** [comment]
I think that arial was removed from the TCPDF library a long time ago.

Is this a useful option?  Perhaps there should be only one font, which is set in the theme?

**Comment by vytux-com** [comment]
It would need to be UTF8 compatible as so far only 1 option out of the 3 work OK with international letters. That being DejaVu
