### ISSUE TITLE
Error by using batch update fixed name slashes and spaces

### ISSUE THREAD

**Issue by mikejpr** [fisharebest/webtrees#618]
I received an error message each time by using batch update for fixed name slashes and spaces.
Following error message appears.

#0 /app/Statement.php:82 PDOException("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2128I-1' for key 'PRIMARY'") #1 /app/Functions/FunctionsImport.php:652 execute([array]) #2 /app/Functions/FunctionsImport.php:1158 importRecord('0 @2128I@ INDI 1 NAME Marie /M…', [Tree], true) #3 /app/Functions/FunctionsImport.php:1073 updateRecord('0 @2128I@ INDI 1 NAME Marie /M…', 1, false) #4 /app/GedcomRecord.php:1293 acceptAllChanges('10001I', 1) #5 /app/Module/BatchUpdateModule.php:155 updateRecord('0 @2128I@ INDI 1 NAME Marie /M…', false) #6 /app/Module/BatchUpdateModule.php:104 main() #7 /module.php:26 modAction('admin_batch_update') 

I see also that when this message appear webtrees show me some "Pending changes" about some very strange modification he want to do.

I tried this also with the version 1.6.2 but do not received error messages.

**Comment by fisharebest** [comment]
> Integrity constraint violation: 1062 Duplicate entry '2128I-1' for key 'PRIMARY'"

This should not be possible.  It is trying to insert two records with the same ID `2128I`.  But, we delete the existing record before we insert the new one.

> I see also that when this message appear webtrees show me some "Pending changes" about some very strange modification he want to do.

If you think these are relevant, then can you give more details?

**Comment by mikejpr** [comment]
OK if we delete the record before inserting the new one, then I suppose that my server is maybe to slow. 
Is there a difference between 1.6.2 and 1.7.0? 
I can reproduce each time the error only with 1.7.0, with 1.6.2 it works fine.

Corcerning the Pending change I think this will be caused because the deleting was not done before inserting the new file, and so we have this conflict.

Here the result of my import from tonight.

#0 /app/Statement.php:82 PDOException("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2241I-1' for key 'PRIMARY'") #1 /app/Functions/FunctionsImport.php:652 execute([array]) #2 /app/Functions/FunctionsImport.php:1158 importRecord('0 @2241I@ INDI 1 NAME Bernard …', [Tree], true) #3 /app/Functions/FunctionsImport.php:1073 updateRecord('0 @2241I@ INDI 1 NAME Bernard …', 1, false) #4 /app/GedcomRecord.php:1293 acceptAllChanges('10001I', 1) #5 /app/Module/BatchUpdateModule.php:155 updateRecord('0 @2241I@ INDI 1 NAME Bernard …', false) #6 /app/Module/BatchUpdateModule.php:104 main() #7 /module.php:26 modAction('admin_batch_update')

**Comment by fisharebest** [comment]
This logic has not changed between 1.6.2 and 1.7.0.
It has not changed for a very long time.

I would investigate `FunctionsImport::updateRecord()`.  It deletes the existing record from the table `wt_individuals` before it loads the new record.

Perhaps you could add debugging code here to see what is happening?

**Comment by fisharebest** [comment]
PS - Have you updated the database directly? e.g. using PhpMyAdmin.

**Comment by mikejpr** [comment]
No I didn't use directly phpmyadmin or an other programm. I use the interface of webtrees. 

Could you tell me how I can activate the debug mode. I didn't find it in the control panel.
Thx.

**Comment by fisharebest** [comment]
There is no debug mode.

From previous comments, I thought you know some PHP programming...

**Comment by mikejpr** [comment]
Sorry I'm not a programmer, but I work as ecommerce manager so that I have some technical backgrounds. 
Maybe the following information helps you to isolate the error.

I make different test and I can communicate you following informations:
- On a synology diskstation it works
- On my webspace (OVH) with 1.6.2 it works
- On my webspace (OVH) with 1.7-dev I had the errors show above. 
 - I change from PHP 5.6 to PHP 5.5 but the errors can be reproduced
 - I load another GEDCOM file found in the net. Same problem
 - I modify the .ovhconfig in the development mode, so that PHP Log error should appears on the site (https://www.ovh.co.uk/g1175.optimisation-php-fpm-hebergement-mutualise-ovh), but I see nothing.
 - I had also used the extention FirePHP, but no error message.
 - I found in the french help pages that with this code in the PHP-page it will display the error `ini_set('display_errors',1);` (https://www.ovh.com/fr/g1562.diagnostiquer-corriger-page-blanche-site-web). But if I put them on the page as recommended directly in the line behind `<?php` then I have really an error message that he need first the Namespace. When I put them behind the namespace I don't see any error message.Here ends my PHP knowledge. I don't know if the line behind the namespace is still okay to put this code  `ini_set('display_errors',1);`.

This can be a sign that it doesn't be a php error or that my PHP knowledge is to bad :smile: 

One information more. From OVH I can see the server error logs, maybe this help you.

>[Sun Jun 14 11:37:37 2015] [error] [client xx.xx.xx.xx] [host www.DOMAIN.com] (104)Connection reset by peer: FastCGI: comm with server "/DOMAIN/www/webtrees/relationship.php" aborted: read failed, referer: http://DOMAIN/webtrees/relationship.php?pid1=1370I&ged=ged=tree1
[Sun Jun 14 11:37:37 2015] [error] [client 82.83.61.74] [host DOMAIN] Handler for fastcgi-script returned invalid result code 1, referer: http://DOMAIN/webtrees/relationship.php?pid1=1370I&ged=ged=tree1

In the fact I can only suppose that this has something to do with the deleting and inserting of the record and that maybe the delay between both is for this server to short.
What do you mean?

Thx.

**Comment by fisharebest** [comment]
> something to do with the deleting and inserting of the record and that maybe the delay between both is for this server to short

Databases are not allowed to process instructions out-of-sequence.  If it is doing this, it is fundamentally broken.  This should not be possible.

> I load another GEDCOM file found in the net. Same problem

Nobody else has this problem.  It appears to be just your server.

I have no more ideas.

**Comment by fisharebest** [comment]
This is the same error that you also reported on the forum.

Did you find the cause?  Has it stopped happening?

**Comment by fisharebest** [comment]
Unable to reproduce problem.

If it happens again, please create a new bug report.
