### ISSUE TITLE
Error message in translate.webtrees.net - The French republican calendar

### ISSUE THREAD

**Issue by mikejpr** [fisharebest/webtrees#619]
Two comments.

First - it's only written "French" for the following entry.

#. I18N: The French calendar
#: app/Date.php:212 help_text.php:199
msgid "French"
msgstr "Républicain français"

I think it would be better if it's written "French republican calendar" or only "French republican", because it's confusing if only the word "French" written. 

Second - I tried to correct this entry in German with "Französischer Revolutionskalender" but I had only the following error message:

Server Error

The server had serious problems while serving your request. We've just sent our trained monkeys to fix the issue.

 Maybe you can checked it. Thx.

**Comment by Amgine0** [comment]
OT: I now have a terrible mental image of a script monkey wearing a fisharebest t-shirt...

**Comment by fisharebest** [comment]
> Second - I tried to correct this entry in German with "Französischer Revolutionskalender" but I had only the following error message:

This problem should be fixed.  There was a file with the wrong permission/ownership on the server.

**Comment by mikejpr** [comment]
Yes it works. Thx I could make the modifications in German.

I had two other questions concerning the translation.
Where can I translate the "languages"-selektor? (left-side from "logout")
I would modify in French from "Langage" to "Langues" and -this is more a little think- but "Français" should be also better with a capital letter at the beginning. But I can found it in the translation files. Are this topic not editable?

The second remark what I have is that on the "fact and events"-page some word don't show I translation. I found the translation in the german or french files so that I suppose that the I18n-Key is missed in the code page.
This was the case for the word "other", "godparent"

**Comment by fisharebest** [comment]
> Where can I translate the "languages"-selektor?

These are in a library of language data.  It is not editable.

> but "Français" should be also better with a capital letter at the beginning

The French do not use capital letters for languages.  Perhaps we should use lowercase everywhere ("deutsch", "english", ...)

So, we use the capitalisation rules for each language.

If you must change this, you can create your own theme, and use CSS (`text-transform: capitalize`).

> The second remark what I have is that on the "fact and events"-page some word don't show I translation.

They are translated on the demo site: https://dev.webtrees.net/demo-dev/individual.php?pid=i1&ged=demo

What is the GEDCOM data for this fact.

PS - Please put only one bug in each bug report.  There is only one title and one status.  These two questions are nothing to do with "French Republican calendar".

You can open lots of bug reports.  There is no cost!

**Comment by mikejpr** [comment]
Your right. I create new issues.
