### ISSUE TITLE
Missing translation under "facts and events" 

### ISSUE THREAD

**Issue by mikejpr** [fisharebest/webtrees#620]
The second remark what I have is that on the "fact and events"-page some word don't show I translation. I found the translation in the german or french files so that I suppose that the I18n-Key is missed in the code page.
This was the case for the word "other", "godparent" 

YOUR ANSWER
They are translated on the demo site: https://dev.webtrees.net/demo-dev/individual.php?pid=i1&ged=demo

What is the GEDCOM data for this fact.

**Comment by mikejpr** [comment]
My GEDCOM delivery for Godparent

3 TYPE INDI
3 RELA Godparent
3 TITL Parrain

 and for other

3 TYPE INDI
3 RELA Other
3 TITL Témoin
3 NOTE frère

**Comment by fisharebest** [comment]
For the "RELA" data, webtrees can only translate **exact** text.

It has a translation for "godparent".  It does not have a translation for "Godparent".

Change this to lower case.

**Comment by fisharebest** [comment]
> 3 RELA Other
> 3 TITL Témoin

Use `3 RELA witness`.

Firstly, this will be translated into all other languages.

Secondly, these have automatic translations for male/female.  For example, in French, `3 RELA friend` will show as "Ami" for males and "Amie" for females.

**Comment by mikejpr** [comment]
>It has a translation for "godparent". It does not have a translation for "Godparent".
>
>Change this to lower case.

But if I show in the translation file I found only "Godparent" and not "godparent"

#. I18N: gedcom tag _GODP
#: app/Gedcom/GedcomCodeRela.php:142 app/Gedcom/GedcomTag.php:1510
msgid "Godparent"
msgstr "Parrain/marraine"

Or did I misunderstood how the programm works?

**Comment by fisharebest** [comment]
> Or did I misunderstood how the programm works?

A little.

In the GEDCOM file are "code words".

webtrees converts these "code words" to text, and translates the text.

So, it finds the "godparent".  It looks for the sex of the person.  It then displays a translation of either "Godfather" or "Godmother". (Or, if the sex is unknown, "Godparent").

If the codeword is not recognised, then it is displayed unchanged.

A simpler example is the record for sex.  e.g. `1 SEX F`.  Here, webtrees finds the codeword "F", and displays the translation of "female" (not the translation of "F").

**Comment by mikejpr** [comment]
Thx a lot fisharebest. I modifiy my GEDCOM with "godparent" and "witness" and it works. With the relation "other" he has still his problem it doesn't translate it anyway.

For godparent the record for male/female doesn't works with my GEDCOM even though he recognized a maternal grandfather
![godparent](https://cloud.githubusercontent.com/assets/11269935/8240412/b1404c86-1602-11e5-8437-e59015cb828e.png)
