### ISSUE TITLE
Translation of the Language Data

### ISSUE THREAD

**Issue by mikejpr** [fisharebest/webtrees#621]
Where can I translate the "languages"-selektor? (left-side from "logout")
I would modify in French from "Langage" to "Langues" and -this is more a little think- but "Français" should be also better with a capital letter at the beginning. But I can found it in the translation files. Are this topic not editable?

```
YOUR COMMENT
```

  Where can I translate the "languages"-selektor?

> These are in a library of language data. It is not editable.

 but "Français" should be also better with a capital letter at the beginning

> The French do not use capital letters for languages. Perhaps we should use lowercase everywhere ("deutsch", "english", ...)
> So, we use the capitalisation rules for each language.
> If you must change this, you can create your own theme, and use CSS (text-transform: capitalize).

**Comment by mikejpr** [comment]
> These are in a library of language data. It is not editable.

Can you please modify "Language" in "Langues" in the French version - see also your portal with Joomla https://www.webtrees.net/index.php/fr/ they use there also "Langues"

>The French do not use capital letters for languages. Perhaps we should use lowercase everywhere ("deutsch", "english", ...)

In the fact it doesn't matter but I prefer if we are consistent. If you want to use lowercase everywhere it is be also fine. Personaly for the usability it should be consistent on lowercase or with a capital letter at the beginning

**Comment by JustCarmen** [comment]
> If you want to use lowercase everywhere it is be also fine.

I don't think so. The language names are not translated and kept in the original language. In that case you can't be consistent. In Dutch we write 'Nederlands' with a capital, not with a lower case.

**Comment by fisharebest** [comment]
The language names (and uppercase/lowercase letters) are from an official standard - http://cldr.unicode.org

> but I prefer if we are consistent

We consistently use the capitalisation that each language prefers :-)

**Comment by Amgine0** [comment]
Just a comment, as this is an area I have a little knowledge about... unicode is not a linguistic authority. They're a digital characters authority - that is, computer geeks not language geeks. The largest translingual authority is also not language geeks, but a Christian missionary group. Few languages have central authorities like French who claim to have the 'right' way for spelling and grammar. It makes it difficult to decide which standard to use, since you are guaranteed to have edge cases.

You have chosen a good standard, so apply it consistently and refer the arguments to the authority.

(And a smaller note, français is the language, Français/Française is a person of French nationality.)

**Comment by mikejpr** [comment]
I understand our the point of view, but the official standard notice only tell how we should write the language in French but not, that this will be always written with lowercase.
The first word is always capitalized. (http://french.about.com/library/writing/bl-capitalizationoftitles.htm)
So we write "Le français est une langue..." corresponding to the official standard. But if you write only "Français" at the beginning it should be capitalized. 
Look at other websites: facebook, google, microsoft, geneanet.org etc. all write "Français" with a capitalized letter at the beginning. 

@Amgine0 : All depends if we use it as a name then we capitalize, but for an adjective we use lowercase. For exemple: "C'est un Français et il est français".

**Comment by Amgine0** [comment]
Oui, mais lui n'est pas « je parle en peu Français, » qui était la question.

**Comment by mikejpr** [comment]
Maybe a grafik is better then words :smiley: 
![langues](https://cloud.githubusercontent.com/assets/11269935/8239662/97955d1c-15fd-11e5-9f1d-80b83f18065d.png)

**Comment by vytux-com** [comment]
You said first word is always capitalised, however that is only true to sentences and only to most of them not all.

Menu items are not sentences so should not be capitalised by default especialy in some languages, like Lithuanian and it seems French.  Also webtrees is a trademark name so it is always written in lowercase even when at the start of a sentence, so there goes your rule of first word is always capitalised.

**Comment by bxbroze** [comment]
Hello,
Thanks to the initiator and all the contributors of this project. This is my first post here:)
I agree with mikejpr: "Francais" in a language selection menu, "francais" inside a sentence.
So the question for me is: is the language name used somewhere inside a sentence or only for te language selection?
So I did a commit to my local branch to change this and will check if I find occurences of "Francais" inside a setence. (https://github.com/bxbroze/webtrees/commit/97f9eee9e1670d2b3720a441187656890e8075cc)

Regards,
BXB

**Comment by fisharebest** [comment]
Many years ago (as part of the PhpGedView project), all the translators had a very long discussion about this.

The conclusion was that each language should be capitalised by its own rules.

This is also the conclusion of the CLDR.

If you want intial capitals, then there is a (very simple!) code change that will achieve this.  (Add a `text-tranform` rule to the CSS - perhaps in a custom theme).

I do not intend to make this change.  Sorry.
