### ISSUE TITLE
RTL names do not work as expected

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#632]
I fill a rtl name.
I see #0 /edit_interface.php:487 Exception("Invalid GEDCOM data passed to GedcomRecord::updateFact(2 GIVN רות 2 SURN הלפביין)")

I fill a rtl married surname to a person who has a rtl _HEB name, The married name is not updated.

Meliza

**Comment by melizaa** [comment]
Same issue with the married name, if the person has a rtl 1 NAME.

**Comment by melizaa** [comment]
It does not yet work.
Please reopen the issue.

I have individual with names
1 NAME Eva /Pergament/
2 GIVN Eva
2 SURN Pergament
2 _MARNM Eva /Mendels/

1. I try to add a new rtl 1 NAME. 
I fill
2 GIVN אוה
2 SURN פרגמנט
and I expect webtrees to create the 1 NAME.
<b>It remains blank.</b>
(I can only create it using raw edit.) 

Adding a rtl married surname causes the creation of a rtl 2 _MARNM.

2. Instead of adding a new 1 NAME, I add 2 _HEB to the existing NAME. 
I try then to fill the rtl married surname מנדלס.
<b>The rtl 2 _MARNM is not created.</b>

Meliza

**Comment by fisharebest** [comment]
Your original problem was that when there was an empty "1 NAME" with a non-empty "2 GIVN/SURN/etc.", then this created invalid GEDCOM

> I see #0 /edit_interface.php:487 Exception("Invalid GEDCOM data passed to GedcomRecord::updateFact(2 GIVN רות 2 SURN הלפביין)")

The fix failed to initialise the `1 NAME` to `1 NAME //`, which caused the NAME record not to be automatically generated from the GIVN/SUN.

This should now be fixed.

**Comment by melizaa** [comment]
When I fill a Latin or a rtl Given name and a Surname, but no 1 NAME, I expect the 1 NAME to be automatically created from the Given name and the Surname. We should not create a 1 NAME // in this case. 

It should also be possible to fill the 1 NAME with different information.

**Comment by melizaa** [comment]
Let me see if it works now as expected.

**Comment by melizaa** [comment]
A new 1 NAME is now created as expected and so is it's 2 _MARNM.

Adding a rtl married surname to an individual with a rtl 2 _HEB name does not create the 2 _MARNM.
Any existing rtl 2 _MARNM is as well deleted.

Meliza
