### ISSUE TITLE
I cannot delete News or Journal entries on the Home page and My page

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#634]
I click on Delete under the entry and to question "Are you sure that you want to delete this xxxx entry". Nothing is removed.

Meliza

**Comment by melizaa** [comment]
I click on OK

**Comment by melizaa** [comment]
I deleted a news item from the wt_news table using cpanel mysql. 
Should I also delete anything else?

**Comment by fisharebest** [comment]
> Should I also delete anything else?

No.  That is all.
