### ISSUE TITLE
Weblate wraps long lines

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#635]
Is there a way to prevent this? It is hard to see the changes when long lines are wrapped.

**Comment by fisharebest** [comment]
I did add a "pre-commit hook" to reformat the files.

See https://github.com/nijel/weblate/issues/365

I guess it isn't working.

**Comment by fisharebest** [comment]
I've just upgraded weblate to the latest version.  Next time weblate commits some of your changes, can you check if it now working?  Thanks.

**Comment by JustCarmen** [comment]
There was not much to change right now, but I did a tiny change in a long line (removed an extra space after the dot). I expected to see the line unwrapped now but that's not the case.

See: https://github.com/fisharebest/webtrees/commit/84eb1431e20b0152031678393611673865175124

**Comment by fisharebest** [comment]
This is now fixed.  There was a change to weblate, and it now requires a full path to the pre-commit hook.
