### ISSUE TITLE
Translation Connexion not done depending the configuration

### ISSUE THREAD

**Issue by Fa10175** [fisharebest/webtrees#639]
if i configure the Manage Family trees / privacy / Show visitor to the family
-show to visitor
the connection block is translated to language selector
-show to member
the connection block is not translated to language selector

**Comment by Fa10175** [comment]
May be is the selector language not working?

**Comment by fisharebest** [comment]
Can you add a screendump to show exactly what is not translated?

**Comment by Fa10175** [comment]
![connexion translation](https://cloud.githubusercontent.com/assets/10681601/8670564/733bb8aa-2a1e-11e5-95c4-8a375119085b.png)

**Comment by Fa10175** [comment]
just info i test the modification it works after to do a refresh after to have selected the language.

**Comment by Fa10175** [comment]
but if i logout the first time it's ok
