### ISSUE TITLE
Update error: execute() called twice

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#648]
Using the automatic update function (from 1.7.0 to 1.7.1) the following error occurs during the export of trees:
---
Aktualisierungsassistent
Die Aktualisierung kann mehrere Minuten benötigen. Bitte haben Sie Geduld.

Überprüfe auf ausstehende Änderungen…
Es gibt keine ausstehende Änderungen.
Überprüfe auf benutzerdefinierte Module…
Es sind keine benutzerdefinierten Module aktiviert.
Überprüfe auf benutzerdefinierte Themen…
Es sind keine benutzerdefinierten Themen aktiviert.
Exportiere alle Familienbäume in GEDCOM Dateien…
Stammbaum wurde in /volume1/web/webtrees_17/data/alecia-2015-07-16.ged exportiert.#0 /app/Tree.php:599 Exception("Statement::execute() called twice.")
#1 /admin_site_upgrade.php:290 exportGedcom()
---
There are several ged trees, the first one was exported correctly, but then the error occurs.

**Comment by fisharebest** [comment]
Already fixed.

A simple code change is needed.  See:

https://github.com/fisharebest/webtrees/commit/195d09d8958a83dd9691b4af3225af8c9a5ece13
