### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#652]
I see in the webtrees error log
[15-Jul-2015 10:42:15 UTC] PHP Fatal error:  Class 'Patchwork\Utf8\Bootup' not found in /home/meliza/public_html/webtrees/includes/session.php on line 185

Meliza

**Comment by fisharebest** [comment]
Not sure how this could have happened.  Patchwork\Utf8 is loaded by autoload.php, a few lines earlier.

If there was a problem, it would affect all classes.

Could it have happened while you were uploading / updating files, and had a temporarily incomplete / inconsistent installation.

**Comment by melizaa** [comment]
Perhaps that is what happened.

**Comment by fisharebest** [comment]
If this happens again, or you discover futher information, please open another issue.
