### ISSUE TITLE
GedcomCodeRela.php

### ISSUE THREAD

**Issue by mikejpr** [fisharebest/webtrees#655]
How can the Relation "Godparent" be adapt by gender that the right translation should appear.
Original Code
```
		case 'godparent':
		// no sex implied
		return I18N::translate('Godparent');
```
Here I get "Godparent" or the right translation in another language, i.e. "Parrain/marraine" in french

Based on "friend" I thought I should only adapt it like this:
```
		case 'godparent':
			switch ($sex) {
			case 'M':
				return I18N::translateContext('MALE', 'Godfather');
			case 'F':
				return I18N::translateContext('FEMALE', 'Godmother');
			default:
				return I18N::translate('Godparent');
			}
```

I got the right relation. For the male it show "Godfather" and for the female "Godmother", the only problem that persits was that it show it only in english. No more translation in another language are shown.

**Comment by Amgine0** [comment]
In languages where the default is male (as I believe is the case in French) you can do this:
```php
      case 'godparent':
            switch ($sex) {
            case 'F':
                return I18N::translateContext('FEMALE', 'Godmother');
           case 'M':
           default:
                return I18N::translateContext('MALE', 'Godfather');
            }
```

**Comment by fisharebest** [comment]
We do not need to use a context-sensitive translation for "Godmother", because it is **always** female.  There are no male godmothers!

**Comment by mikejpr** [comment]
Thx but this are not the answer to my question. If this are not clear describe I can try to send screenshot next time.

**Comment by wooc** [comment]
case 'godparent':
            switch ($sex) {
            case 'M':
                return I18N::translate('Godfather');
            case 'F':
                return I18N::translate('Godmother');
            default:
                return I18N::translate('Godparent');
}

but you already have
case 'godfather':
		// always male
		return I18N::translate('Godfather');
case 'godmother':
		// always female
		return I18N::translate('Godmother');

**Comment by fisharebest** [comment]
I think that @mikejpr wants us to auto-correct the data.

If you enter "godfather", it will display godfather.
If you enter "godmother", it will display modfather.

But if you enter "godparent", it will display godfather or godmother or godparent automatically.

There are two questions.

1) should we also auto-correct the others.  Perhaps you enter "godfather" for a woman.  Should we display "godmother" here?

2) autocorrect is nice - but it hides the errors.  Do we want this?

**Comment by mikejpr** [comment]
>1) should we also auto-correct the others. Perhaps you enter "godfather" for a woman. Should we display I18N::translate('Godmother') here?

No I don't want to correct the others cases, because the gender was selected and like you say this should hides errors.

>2) autocorrect is nice - but it hides the errors. Do we want this? Or perhaps this is not an error. Perhaps "godparent" is the correct data?

My GEDCOM delivery for each Gender only `3 RELA Godparent`. So that I want to display the corresponding translation. I think that in the most case when in the GEDCOM the relationship is not Godfather or Godmother and only Godparent, this should be an "error" of the other program. But in the most case the gender is known and we can show the right state. If we don't have a gender "godparent" should still works. 

In the default code version I have the following result in French:
`Parrain/Marraine: John DOE`
`Parrain/Marraine: Jane DOE`
which is in english:
`Godparent: John DOE`
`Godparent: Jane DOE`

When I use the code from above, the gender has been recognized but not the translation. I got the following result:
`Godfather: John DOE`
`Godmother: Jane DOE`

but I want to have them also traduzed in my case in french:
`Parrain: John DOE`
`Marraine: Jane DOE`

And the last point doesn't work as desired.
