### ISSUE TITLE
Parent and childthemes in theme selector

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#658]
Say I make a custom (child) theme from one of the standard (parent) themes with just a few modifications that will fit my needs.

In my childtheme I can add a function to hide the parent theme in the theme selector. Because I've made modifications to this theme I don't want people to see the original parent theme, but let them select the child theme instead.

But this doesn't work if I use multiple themes. As soon as I select one of the other themes, both themes (parent and child) will be visible again in the theme selector. 

I think that a parent theme always should be hidden in the theme selector when this parent has a child theme. It doesn't make sense to show both.

**Comment by vytux-com** [comment]
I would suggest the best way to handle this would be similar to how we handle languages. Have a list of available themes, and then have an option to disable ones you don't need.

One would want to automatically disable "parent" theme as that could mean any theme based on let's say webtrees would disable that.

**Comment by fisharebest** [comment]
> I think that a parent theme always should be hidden in the theme selector when this parent has a child theme. It doesn't make sense to show both.

The colours theme is a child of the clouds theme.

**Comment by JustCarmen** [comment]
> The colours theme is a child of the clouds theme.
Ok, I didn't realize that. But then could the suggestion of Vytux be considered? If you give people the opportunity to personalize their website I think It should be possible to hide one or more themes from the theme selector without removing them from the server. Because removal isn't an option anymore since you need the parents theme class and functions.

At the moment it is all or nothing. You can hide the theme selector and just present one theme to your users or enable the theme selector to show them all.

**Comment by makitso** [comment]
> The colours theme is a child of the clouds theme
Actually, on webtrees, clouds was based on colors ;-)

**Comment by fisharebest** [comment]
Another option is to remove the ability for users to specify their own themes.  i.e. remove the option "Allow users to select their own theme", and make it always "no".

I can't think of any other application that does this.  It is always the administrator / site-owner who selects the theme.

**Comment by Amgine0** [comment]
In most open source cms this is an admin option. Mediawiki, Drupal, Tiki for sure. Not all make it easily discovered; most hide it in user settings.

**Comment by fisharebest** [comment]
In 2.0, themes are now implemented as modules.

As with other modules, you can enable/disable unwanted themes.

If only one theme is enabled, the theme menu disappears.
