### ISSUE TITLE
Import a tree as manager

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#663]
A user with the role of Manager is allowed to import a new Gedcom in the tree he is Manager in.

But the process fails if this Manager has this role in one tree only. Somewhere during the import process the old Gedcom is removed and at that point the Manager is immediately kicked out of the Control Panel because at that tiny moment there is no tree he has Manager rights in!

The import process continues as soon as the Administrator logs in to the Control Panel and select 'manage family trees'.

But a Manager is unable to complete the import process by himself..

**Comment by fisharebest** [comment]
Should a manager be able to import/export trees?
