### ISSUE TITLE
Untranslated punctuation

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#669]
![source](https://cloud.githubusercontent.com/assets/2306088/9017085/607444b4-37cd-11e5-9202-cdae1fd84f79.PNG)

"Source:" should be "Source :" in French.

Perhaps omit the colon?

**Comment by JustCarmen** [comment]
Why can't we just make the translatable string include the colon? Then the French could use a space in their translation. Without the colon the sentence looks strange. In Dutch a colon is needed before a description like this.

**Comment by fisharebest** [comment]
> Why can't we just make the translatable string include the colon?

This would require two translations of every fact.

Instead we have a translation for (approximately) `<b>%1$s</b>: %$2s`.  I guess we are not using it here.

**Comment by JustCarmen** [comment]
> This would require two translations of every fact.

Yeah, you're right. Not a good idea ;)
