### ISSUE TITLE
Menu "Family trees" : grammar & logic

### ISSUE THREAD

**Issue by SodanWT** [fisharebest/webtrees#671]
In app/Theme/AbstractTheme.php function menuHomePage()

1) **Grammar : plural / singular**
``` php
if (count($submenus) > 1) {
                        $label = I18N::translate('Family trees');
                } else {
                        $label = I18N::translate('Family trees'); // --> should be "Family tree" (singular)
                }
```

2) **Submenu always present**
As a result of 
``` php
foreach (Tree::getAll() as $tree) {
                                if ($tree == $this->tree || $ALLOW_CHANGE_GEDCOM) {
```
there always is a submenu under "Family trees", even if there is only 1 tree even if $ALLOW_CHANGE_GEDCOM=false.

3) **Improvement**
Once the second point is solved, I suggest  to change the label for the menu "Family tree" if there is no submenu. Indeed, if there are several submenus, clicking on the menu "Family trees" will propose us several trees. But if there is only 1 tree, clicking on it will bring us to the Home Page, not to a "Family tree". So I suggest something like that : 
``` php
if (count($submenus) > 1) {
                        $label = I18N::translate('Family trees');
                } else {
                        $label = I18N::translate('Home page');
                }
```

**Comment by fisharebest** [comment]
Issues containing multiple problems are difficult to manage.  If you have 3 issues, it helps to create 3 separate issues on the tracker...

1) You suggest that the menu is renamed "Family tree" when there is only one tree.
3) You suggest that the menu is renamed "Home page" when there is only one tree.

> clicking on it will bring us to the Home Page, not to a "Family tree"

The link is to the famliy tree's home page.

**Comment by SodanWT** [comment]
You're right.
We can keep this bug 671 for the second item.
I'll create another one for the label.

So from now, here the content of this bug :

As a result of

```php
foreach (Tree::getAll() as $tree) {
                                if ($tree == $this->tree || $ALLOW_CHANGE_GEDCOM) {
```
there always is a submenu under "Family trees", even if there is only 1 tree even if $ALLOW_CHANGE_GEDCOM=false. I think there should be no submenu in this case.
