### ISSUE TITLE
[Reports] Missing facts report crashes with a fatal error "cannot access private property"

### ISSUE THREAD

**Issue by Schoaf** [fisharebest/webtrees#673]
I was trying to create a report of the missing facts with version 1.7.1 but ran into the following error:

Fatal error: Cannot access private property Fisharebest\Webtrees\Report\ReportParserGenerate::$vars in /home/.sites/145/site786/web/stammbaum/app/Report/ReportParserGenerate.php on line 2802

Thats the whole URL with all of the settings for the report:
reportengine.php?action=run&report=modules_v3%2Fmissing_facts_report%2Freport.xml&varnames[]=pid&vars[pid]=I3&type[pid]=INDI&varnames[]=relatives&vars[relatives]=ancestors&type[relatives]=&varnames[]=maxgen&vars[maxgen]=*&type[maxgen]=&varnames[]=pageSize&vars[pageSize]=A4&type[pageSize]=&varnames[]=fsour&type[fsour]=&varnames[]=fbirt&vars[fbirt]=1&type[fbirt]=&varnames[]=fbapm&type[fbapm]=&varnames[]=fbarm&type[fbarm]=&varnames[]=fbasm&type[fbasm]=&varnames[]=fconf&type[fconf]=&varnames[]=fenga&type[fenga]=&varnames[]=ffcom&type[ffcom]=&varnames[]=fmarb&type[fmarb]=&varnames[]=fmarr&type[fmarr]=&varnames[]=fdeat&vars[fdeat]=1&type[fdeat]=&varnames[]=fburi&type[fburi]=&varnames[]=freli&type[freli]=&output=PDF

**Comment by Schoaf** [comment]
Actually that same error occurs for each and every report.

I just upgraded to version 1.7.1 and using PHP version 5.3.29.

**Comment by fisharebest** [comment]
Already fixed.

https://github.com/fisharebest/webtrees/commit/aa22a75ef1cb7faaeb6d3b029ed97a3d1f41fc89

It's a one-line code change, if you can't wait for the next release.

**Comment by Schoaf** [comment]
awesome! thanks!
<3
