### ISSUE TITLE
Problemconfiguration acces when you are several trees

### ISSUE THREAD

**Issue by Fa10175** [fisharebest/webtrees#675]
I configured in webtrees with 2 trees, one of which is by default (No. 1).
Access to these trees is private. (Login required, only members can view the data).

When I create a user who is in every tree, it can access to each of the two (it is said in the member 2). OK.

If I declare it as a visitor in a tree, he has access to the tree or it is a member. OK.

If a user is not in a tree (No. 1), if I declare it as a visitor without reference into the shaft No. 1 which is true.
For the tree No. 2, it is declared as a member and is referenced.
When it connects, webtrees displays nothing (normal visitor no access to that person in the shaft No. 1 which is the default.
webtrees does not switch on the tree # 2. No OK.

If the default tree was the No. 2, he could have seen the tree data No. 2 without access to the shaft # 1. OK

By cons, if the same user I declare it as a visitor with a fake link in the shaft # 1.
When it connects, webtrees displays information of the tree No. 2 and does not provide access to the shaft # 1. OK

Thank you to note this problem and tell me whether to make a bug report or tell me a method to solve this problem.
Knowing that I have in each tree of people who are not in the other (I can not change the default tree).

**Comment by Fa10175** [comment]
I try to test i create a user visitor for the first tree (default) nobody defined and member for the second with his identifier and i  have this message
Fatal error: Call to a member function getUserPreference() on null in /opt/lampp/htdocs/webtrees-master/app/Theme/AbstractTheme.php on line 1536

**Comment by Fa10175** [comment]
I tested with the master download today

**Comment by fisharebest** [comment]
>  i have this message

When does the error message appear?

**Comment by Fa10175** [comment]
When i try to connect to webtrees with this user Id and password

All the users should be connected to enter on trees (1 or 2)
I have 2 trees
Tree 1 is declare as default for webtrees
this user is declare for tree 1 as visitor and no id on tree 1
this user is declare for tree 2 as member and has an id on tree 2
So as soon as i try to connect to this user, I have this message instead to display this page.

**Comment by fisharebest** [comment]
I cannot reproduce this error on my own server.

I created two trees.
I set them both to "Show to members"
I created a new user.  Visitor in tree1, Member (with linked individual) in tree2.
I set tree1 to be default.
I logout as administrator.
I login as the user.
I see tree2 as expected.

**Comment by Fa10175** [comment]
I check again and i see the problem
i have declare this user member to the tree 2
but i don't know what append when i check again he set as visitor
so for me it 's ok and it works fine
sorry for your lost time
so this message appear only 
when the trees are set them both to "Show to members"
when a new user. is Visitor in tree1and  visitor in tree2.
 This case should be not exist.
Thanks
