### ISSUE TITLE
Unable to add new administrator account

### ISSUE THREAD

**Issue by exxamalte** [fisharebest/webtrees#678]
The administrator flag has been partially renamed with the following effects:
* The user detail form for an existing administrator (created with webtrees 1.6.x) does not show the `Administrator` checkbox checked.
* Newly created administrator user (created in webtrees 1.7.x) does not actually have admin rights in the system.

It appears that the `canadmin` setting has been renamed to `admin` at some point in time in some code instances.

In my webtrees 1.7.1 instance's database table `wt_user_setting` the admin has a setting `canadmin` set to `1`. And this is apparently what `app/Auth.php#isAdmin` checks for. However, in `admin_users.php` when rendering the checkbox for the user detail form the code looks for a setting `admin` (this setting name has been introduced in https://github.com/fisharebest/webtrees/commit/07b70ae14d34ec3d428f7482e6df3ea0b1e7ef47). 
And when you add a new user with the `Administrator` checkbox checked, this user ends up with a `admin` setting set to `1`, but no `canadmin` setting.

Here the original discussion in the forum: https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-x/30550-administrator-account-s

**Comment by fisharebest** [comment]
You are right.  The correct setting is `canadmin`.

If you have time to create a pull-request, that would be good.

**Comment by exxamalte** [comment]
No worries, I'll take a look.
