### ISSUE TITLE
Editing FAQ, HTML block or History tab - no WYSIWYG form

### ISSUE THREAD

**Issue by wooc** [fisharebest/webtrees#681]
CKEditor is enabled.

https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-x/30555-editing-faq-item-no-wysiwig-form

**Comment by fisharebest** [comment]
I have fixed the FAQ edit page.

The HTML block works OK for me.
The stories module works OK for me.
Perhaps I do not understand the problem?

**Comment by wooc** [comment]
[2015-08-12 15:13:26] JavaScript - http://localhost/xampp/wt-git/module.php?mod=faq&mod_action=admin_edit
Inline script thread
Uncaught exception: Error: The environment is incompatible.
Error thrown at line 5, column 722 in <anonymous function: ckeditor>(g, d) in http://localhost/xampp/wt-git/packages/ckeditor-4.4.7-custom/adapters/jquery.js:
    throw Error("The environment is incompatible.");
called from line 83, column 2 in http://localhost/xampp/wt-git/module.php?mod=faq&mod_action=admin_edit:
    jQuery(".html-edit").ckeditor(function(){}, {
Error created at line 5, column 722 in <anonymous function: ckeditor>(g, d) in http://localhost/xampp/wt-git/packages/ckeditor-4.4.7-custom/adapters/jquery.js:
    throw Error("The environment is incompatible.");
called from line 83, column 2 in http://localhost/xampp/wt-git/module.php?mod=faq&mod_action=admin_edit:
    jQuery(".html-edit").ckeditor(function(){}, {

**Comment by wooc** [comment]
Possible solution:
http://stackoverflow.com/questions/25640576/ckeditor-error-the-environment-is-incompatible

**Comment by fisharebest** [comment]
Which browser are you using?

**Comment by wooc** [comment]
Opera Mobile. In Chorme there is OK.

**Comment by fisharebest** [comment]
Fixed.
