### ISSUE TITLE
Delete menu option under Media is not working

### ISSUE THREAD

**Issue by DJAlik** [fisharebest/webtrees#683]
When I click on Edit-> Delete for a media object, nothing is happening.

**Comment by fisharebest** [comment]
1) What version of webtrees?

2) What language are you using?  Do you see the same problem with English?

**Comment by DJAlik** [comment]
1.7.1 English

**Comment by fisharebest** [comment]
> nothing is happening.

There should be a confirmation dialog.  Then the media object is deleted.  I presume you do not see the confirmation dialog.

Do you see any messages in your browsers JavaScript error log?
Does the problem affect all images, or just certain images?

**Comment by DJAlik** [comment]
Like I said when I click on the link there is no confirmation dialog there are no errors. Right clicking the Delete just brings you back to the same page

http://djalik.x10host.com/webtrees/mediaviewer.php?mid=M2612&ged=Family

**Comment by DJAlik** [comment]
Same for other media objects.

I did "Inspect Element" in chrome and here's the HTML code behind the
Delete link

<a href="#" onlcick="return delete_media(&quot;Are you sure you want to
delete “xaq29xib_medium.jpg”?&quot;, &quot;M2612&quot;);">Delete</a>

On Thu, Aug 13, 2015 at 2:51 PM, Greg Roach <notifications@github.com>
wrote:

> nothing is happening.
>
> There should be a confirmation dialog. Then the media object is deleted. I
> presume you do not see the confirmation dialog.
>
> Do you see any messages in your browsers JavaScript error log?
> Does the problem affect all images, or just certain images?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fisharebest/webtrees/issues/683#issuecomment-130819642>
> .
>



-- 
<http://www.facebook.com/djalik>  <http://twitter.com/#!/DJAlik>
<http://www.linkedin.com/in/alexrusinov>
<http://plus.google.com/114580313768137070684>
<http://www.mixcloud.com/djalik/>
<http://psnprofiles.com/DJAlik>

**Comment by fisharebest** [comment]
If nothing happens when you click this, there must be a javascript error.

Open the JavaScript console in Chrome, then reload the page, then select the delete option.

This should give you an error message

**Comment by DJAlik** [comment]
Nothing comes up on the console when I click on Edit->Delete. All other
options under the Edit menu work fine with windows coming up. It's just the
Delete that's not working.

On Thu, Aug 13, 2015 at 4:31 PM, Greg Roach <notifications@github.com>
wrote:

> If nothing happens when you click this, there must be a javascript error.
>
> Open the JavaScript console in Chrome, then reload the page, then select
> the delete option.
>
> This should give you an error message
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fisharebest/webtrees/issues/683#issuecomment-130850286>
> .
>



-- 
<http://www.facebook.com/djalik>  <http://twitter.com/#!/DJAlik>
<http://www.linkedin.com/in/alexrusinov>
<http://plus.google.com/114580313768137070684>
<http://www.mixcloud.com/djalik/>
<http://psnprofiles.com/DJAlik>

**Comment by DJAlik** [comment]
Seems to be working in 1.7.2

On Fri, Aug 14, 2015 at 9:22 AM, Alex Rusinov <djalik@gmail.com> wrote:

> Nothing comes up on the console when I click on Edit->Delete. All other
> options under the Edit menu work fine with windows coming up. It's just the
> Delete that's not working.
>
> On Thu, Aug 13, 2015 at 4:31 PM, Greg Roach <notifications@github.com>
> wrote:
>
>> If nothing happens when you click this, there must be a javascript error.
>>
>> Open the JavaScript console in Chrome, then reload the page, then select
>> the delete option.
>>
>> This should give you an error message
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fisharebest/webtrees/issues/683#issuecomment-130850286>
>> .
>>
>
>
>
> --
> <http://www.facebook.com/djalik>  <http://twitter.com/#!/DJAlik>
> <http://www.linkedin.com/in/alexrusinov>
> <http://plus.google.com/114580313768137070684>
> <http://www.mixcloud.com/djalik/>
> <http://psnprofiles.com/DJAlik>
>



-- 
<http://www.facebook.com/djalik>  <http://twitter.com/#!/DJAlik>
<http://www.linkedin.com/in/alexrusinov>
<http://plus.google.com/114580313768137070684>
<http://www.mixcloud.com/djalik/>
<http://psnprofiles.com/DJAlik>
