### ISSUE TITLE
Adjustment of GEDCOM code: HEAD.GEDC.FORM

### ISSUE THREAD

**Issue by webtrees-pesz** [fisharebest/webtrees#684]
"Lineage-Linked” instead of “LINEAGE-LINKED”

**Comment by fisharebest** [comment]
The sample GEDCOM on page 74 of the specification says `Lineage-Linked`:

> 2 FORM Lineage-Linked

The GEDCOM tag definition on page 50 of the specification says `LINEAGE-LINKED`:

>GEDCOM_FORM:= {Size=14:20}
> [ LINEAGE-LINKED ]
> The GEDCOM form used to construct this transmission. There maybe other forms used such as CommSoft's "EVENT_LINEAGE_LINKED" but these specifications define only the LINEAGE- LINKED Form. Systems will use this value to specify GEDCOM compatible with these specifications.

Page 21 of the specification says it does not matter if you use uppercase or lowercase:
> All controlled line_value choices should be considered as case insensitive.


...but I think we already use `Lineage-Linked`.  See https://github.com/fisharebest/webtrees/blob/master/app/Functions/FunctionsExport.php#L101

**Comment by webtrees-pesz** [comment]
Hello Greg,

 

you are right. The deciding sentence is: All controlled line_value choices should be considered as case insensitive

 

I will send you an updated version of GedTool, which consider this rule.

 

Best regards

Peter

 

Von: Greg Roach [mailto:notifications@github.com] 
Gesendet: Donnerstag, 13. August 2015 02:20
An: fisharebest/webtrees
Cc: webtrees-pesz
Betreff: Re: [webtrees] Adjustment of GEDCOM code: HEAD.GEDC.FORM (#684)

 

The sample GEDCOM on page 74 of the specification says Lineage-Linked:

2 FORM Lineage-Linked

The GEDCOM tag definition on page 50 of the specification says LINEAGE-LINKED:

GEDCOM_FORM:= {Size=14:20}
[ LINEAGE-LINKED ]
The GEDCOM form used to construct this transmission. There maybe other forms used such as CommSoft's "EVENT_LINEAGE_LINKED" but these specifications define only the LINEAGE- LINKED Form. Systems will use this value to specify GEDCOM compatible with these specifications.

Page 21 of the specification says it does not matter if you use uppercase or lowercase:

All controlled line_value choices should be considered as case insensitive.

...but I think we already use Lineage-Linked. See https://github.com/fisharebest/webtrees/blob/master/app/Functions/FunctionsExport.php#L101
