### ISSUE TITLE
Mediafirewall Error.

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#686]
Version 1.7.2 beta, PHP 5.6.11, Memory Limit 496M

In testing with a very large image file, if I am not logged in and select Media Objects, Search and then click on a thumbnail, I get the colobox error "The image file failed to load."  The webtrees log shows the error below.  However, if I log on to my webtrees account and do the same thing the image loads correctly.

#0 unknown:unknown ErrorException("imagejpeg(/home/rob/www/data/media/watermark/Peters Genealogy/alice-peters-1898.jpg): failed to open stream: Permission denied") #1 /mediafirewall.php:392 imagejpeg([resource], '/home/rob/www/data/media/water…') 
![alice-peters-1898](https://cloud.githubusercontent.com/assets/5147603/9282049/44767486-428f-11e5-9b13-785247005ded.jpg)

**Comment by makitso** [comment]
So, you can't see the image (of a person b: 1898, d: 1945 yet when I log in I can.  Its interesting that the URLs are different for the same media object:

 guest   http://localhost/mediafirewall.php?mid=M48&ged=Peters%20Genealogy&cb=991c332d
 registerhttp://localhost/mediafirewall.php?mid=M48&ged=Peters%20Genealogy&cb=ab2a51af

**Comment by fisharebest** [comment]
> Its interesting that the URLs are different for the same media object:

The reason for the different "cb" parameter to to prevent caching.  If you log out, you may need to see the image with the watermark.  Without it, the browser may show the cached image.

Perhaps this is a PHP error - failing to add the watermark to the image?

**Comment by makitso** [comment]
Actually, I am curious as to why the image failed to load for a visitor but loads correctly when the visitor logs in.
