### ISSUE TITLE
Upgrade 1.7.1 to 1.7.2 - exception Statement::execute() called twice.

### ISSUE THREAD

**Issue by narcissusjwl3** [fisharebest/webtrees#693]
/app/Tree.php:596 Exception("Statement::execute() called twice.")
#1 /admin_site_upgrade.php:290 exportGedcom()

It looks like it creates a backup of the first tree but breaks on the next one.

**Comment by fisharebest** [comment]
Already fixed.  See: https://github.com/fisharebest/webtrees/commit/195d09d8958a83dd9691b4af3225af8c9a5ece13

**Comment by narcissusjwl3** [comment]
Thanks for the update. To clarify, I would have to manually update (ie. download and unzip) to get the newest version?

**Comment by fisharebest** [comment]
Yes - or just make the one-line change I linked to.
