### ISSUE TITLE
Alphabetical order - Norwegian (nn and nb)

### ISSUE THREAD

**Issue by HRN-webtrees** [fisharebest/webtrees#694]
In placelist, famlist and indilist the names and places are no longer listed in correct alphabetical order.
AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZzÆæØøÅå

**Comment by fisharebest** [comment]
An omission in the localisation library.

https://github.com/fisharebest/localization/issues/1
