### ISSUE TITLE
Private tree creates Apache error after new user logs on.

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#696]
Steps to create:
1) Created a new private tree, i.e. under privacy set everything to show members except private relationships is set to Hide from everyone.  
2) Create new user.
3.  When new user logs on they get a blank screen and this Apache error:
[Sun Aug 23 12:18:44.738248 2015] [:error] [pid 21068] [client 127.0.0.1:51846] PHP Fatal error:  Call to a member function getUserPreference() on null in /home/rob/www/app/Theme/AbstractTheme.php on line 1536, referer: http://localhost/login.php?url=index.php%3F

**Comment by makitso** [comment]
This error is serious.  Once the above situation happens, the web site can not be accessed by the administrator unless one clears the browser cache and cookies.

**Comment by fisharebest** [comment]
I'm guessing that when you created the user, you did not give them access to any tree, and there is also no public tree on the site.

I'm guessing that you logged in as the user from the same machine (masquerade or logout / login).

You are then able to use the site as a visitor - because of this error, and you are unable to log in as adminsistrator, since you are unable to log out as the user.

**Comment by fisharebest** [comment]
Perhaps we should reject the login in this situation?  After all, this user has no access to any page except the login page.

**Comment by makitso** [comment]
You are absolutely correct, giving them member access to the one tree fixed the problem.
> Perhaps we should reject the login in this situation?
The current situation leaves the site in an unusable state, something that should not happen.  Perhaps a message saying that the user is not authorized to view any tree?

**Comment by makitso** [comment]
So, if I have a one tree that is public and I create a user, the user defaults to visitor role for that tree.  So, then when the user logs on they have access to the tree.  This only fails when the tree is marked private.  So why isn't the system smart enough that when there is only one tree and you are creating a new user, that the user is given the default role of member?

**Comment by fisharebest** [comment]
> This only fails when the tree is marked private. 

It only fails when **all** trees are marked private.

Hence, from the user's perspective, there is no difference between
1) there are no trees to which you have access
2) there are no trees at all

Note that (2) could also occur temporarily if there is only one tree, and it is in the middle of being re-imported.  So, I think that denying access (with a suitable message) is probably the right course of action.

> So why isn't the system smart enough that when there is only one tree and you are creating a new user, that the user is given the default role of member?

The admin always needs to choose between member/editor (or higher).  Whatever we choose will be wrong.  Perhaps make it clearer to the admin that they need to choose a role?

**Comment by makitso** [comment]
Maybe if they have not picked a role, the save fails.......

**Comment by fisharebest** [comment]
We could achieve the same situation in a different order.  Create the user, then make the tree private.

**Comment by makitso** [comment]
I am not sure I follow you.  But, I like things simple and straight forward :-)

Seems to me that requiring someone to intentionally pick a role when adding a user is easy to understand.  And, most people would probably pick member without really understanding the implications.  A private tree and the role of visitor is Incongruous at best.

**Comment by fisharebest** [comment]
>  Perhaps make it clearer to the admin that they need to choose a role?

See also #710
