### ISSUE TITLE
v1.7.2 Android 5.1.1 Exception Error

### ISSUE THREAD

**Issue by DaveWalt** [fisharebest/webtrees#698]
Samsung S6 G920F
Android 5.1.1
Default browser
KSWEB - lighttpd/MySQL/PHP5.6.10
webtrees v1.7.2
No internet connection - localhost:8080/webtrees

Flagging an unknown exception error on a few individuals. The error is, conversion from 'UTF-8' to 'UTF-16BE' is not allowed. Tracked this down to individuals with the NICK tag. Remove the nickname and the individual is displayed correctly.

A temporary fix
Commented out line 72 in webtrees/app/Filter.php i.e. // return sprintf('\\u%04s', strtoupper(bin2hex(iconv('UTF-8', 'UTF-16BE', $x[0]))));

**Comment by fisharebest** [comment]
This line is converting UTF8 characters into JavaScript escaped encoding.

e.g. the open quote `“` becomes `\u201C`

Commenting out this line will cause problems for you if your data contains certain "special" characters.

**Comment by DaveWalt** [comment]
Noted - so far no problems with special characters and the fix is better than dropping all NICK tags.
