### ISSUE TITLE
Android 5.1.1 Change Blocks Fails

### ISSUE THREAD

**Issue by DaveWalt** [fisharebest/webtrees#702]
Samsung S6 G920F
Android 5.1.1
Default browser
KSWEB - lighttpd/MySQL/PHP5.6.10
webtrees v1.7.2
No internet connection - localhost:8080/webtrees

Change the blocks… fails but the default will always work even though change the blocks… appears to be empty.

**Comment by vytux-com** [comment]
That is because the system is designed to re-add the default blocks of no blocks are present. No point in having an empty page is there?

**Comment by DaveWalt** [comment]
Hence my comment above - empty dropdowns but a complement of blocks present and working. On the Android smartphone block editing is displayed differently to that on a PC. I found a way to get the block editor working but it requires the user to remember where they move the blocks. The downside is that you can have multiple entries for a given block which then need to be moved back to the pick list.
