### ISSUE TITLE
Android 5.1.1 Media Scroll

### ISSUE THREAD

**Issue by DaveWalt** [fisharebest/webtrees#703]
Samsung S6 G920F
Android 5.1.1
Default browser
KSWEB - lighttpd/MySQL/PHP5.6.10
webtrees v1.7.2
No internet connection - localhost:8080/webtrees

Media viewer will display thumbnails and allow pinch to zoom but scrolling fails in the media window.

Fix
Long press the thumbnail, click on Open in the context menu. This fix with the default browser but it does not work in the Chrome browser.

**Comment by fisharebest** [comment]
We use third-party modules for the image zoom/scroll functions (https://github.com/jackmoore/colorbox and https://github.com/jackmoore/wheelzoom).

I see that updated versions are available.  However, we can't use them directly as we use a patched version.

**Comment by DaveWalt** [comment]
Thanks for this information. Using the context menu in the default browser to open media is OK. I like Chrome and, following my change to nginx + KSWEB updates, clicking on a thumbnail/magnify now allows horizontal scrolling but limits vertical scrolling. Chrome with webtrees is limited for viewing media (by clicking on thumbnails) and the Android default browser does the job.
To view media in the Android Chrome browser - Using the Chrome context menu requires tab navigation and clicking on the apparently empty new tab before the media opens in that new tab. You then have pinch to zoom and full scrolling access. Return back through tab navigation to the individual's tab.

**Comment by fisharebest** [comment]
These libraries have been updated.

I cannot test this.

But even if it is not fixed, I think there is little we can do.
