### ISSUE TITLE
Googlemaps preferences - label and helptext don't match

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#706]
![fireshot screen capture 064](https://cloud.githubusercontent.com/assets/5641963/9486645/4126b432-4bca-11e5-87cd-40beb79c8df9.jpg)

But I am not sure if it is only the wrong help text or the label and radio buttons belonging to this help text are missing.

**Comment by fisharebest** [comment]
The original help text for this entry was

> Here you can choose between two types of displaying places names in hierarchy.  If set Yes the place has short name or actual level name, if No - full name.<br><b>Examples:<br>Full name: </b>Chicago, Illinois, USA<br><b>Short name: </b>Chicago<br><b>Full name: </b>Illinois, USA<br><b>Short name: </b>Illinois

This help text belonged to an old config option `PEDIGREE_MAP_hideflags`.  It needs deleting.

We already have a per-tree setting for abbreviating place names.  Does the GM module need its own one?

**Comment by JustCarmen** [comment]
>> We already have a per-tree setting for abbreviating place names. Does the GM module need its own one?

You are right. This seems to be a superfluous setting. IMHO it could be removed.

**Comment by fisharebest** [comment]
This setting is only used on the place hierarchy.

On these pages, the parent place (e.g."London, England") is shown in the header.  So, we do not need to show the full placename "Westminster, London, England" in the map window, just the "Westminster" part.
