### ISSUE TITLE
incorrect order for given name and surname when translating to Chinese

### ISSUE THREAD

**Issue by waylonwang** [fisharebest/webtrees#708]
A standard sinitic full name has two parts—a surname and given name. Surname and given name are written together, and the surname is before the given name. The two names don't separate by a space or comma.

For example:

the surname of 'Yao Ming' is 姚(Yao), and given name is 明(Ming), His full name is 姚明 when translating to Chinese, the following translation is incorrected: 明 姚(given name is before the surname) or 姚 明(separated by a space between two names).

the surname of 'Deng Xiaoping' is 邓(Deng), and given name is 小平(Xiaoping), His full name is 邓小平 when translating to Chinese, the following translation is incorrected: 小平 邓(given name is before the surname) or 邓 小平(separated by a space between two names).

![surname](https://cloud.githubusercontent.com/assets/7424276/9568332/091324a6-4f79-11e5-8405-3a2bbd7828ae.png)

**Comment by fisharebest** [comment]
This works for me.

I set the language to Chinese.
I add a new name to an individual.
I enter given names and a family name.
The full name is created automatically in the correct format: family name (no space) given name.

How can I reproduce the problem?

**Comment by waylonwang** [comment]
I have tried again,the full name has fixed order(given name[space]surname) at write to database ,and Individual.php show the full name with same order.

change name:
![changename](https://cloud.githubusercontent.com/assets/7424276/9579518/e695acf2-5025-11e5-9db0-15e3b790a43d.png)

result:
![newname](https://cloud.githubusercontent.com/assets/7424276/9579530/f7ecf00a-5025-11e5-8a0c-b56edddc2b09.png)

database:
![database](https://cloud.githubusercontent.com/assets/7424276/9579539/ff703288-5025-11e5-9315-28a76acb5ea9.png)

html code:
![html-1](https://cloud.githubusercontent.com/assets/7424276/9579544/099f1684-5026-11e5-8493-27f54817437a.png)

source code:
![individual php](https://cloud.githubusercontent.com/assets/7424276/9579548/1152936a-5026-11e5-885f-06caaf554214.png)

**Comment by waylonwang** [comment]
I think that to take care of different national habits, increasing an option of full name order is a better solution, just like "Surname tradition" option.

**Comment by waylonwang** [comment]
It really is a big trouble! When I find individual by name, I can not go to a query by the Chinese full name, because already in the database is based on the English habit of saving a full name, the code directly to a query by the this full name

find by Chinese full name order,can not find individual 
![find1](https://cloud.githubusercontent.com/assets/7424276/9594923/7fd1d53a-5094-11e5-8a17-790b83518d37.png)

find by English full name order,can find it
![find2](https://cloud.githubusercontent.com/assets/7424276/9594928/8a6f0a08-5094-11e5-9061-445c47ecda2e.png)

SQL String
![find3](https://cloud.githubusercontent.com/assets/7424276/9594930/9138791e-5094-11e5-999c-4ae84d102cc8.png)

**Comment by fisharebest** [comment]
> I think that to take care of different national habits, increasing an option of full name order is a better solution

This already exists.  If you set your lanuage to English, names will be created as `Given /Family/`.  If you set it to Hungarian, names will be created as `/Family/ Given` and if you set it to Chinese, names will be created as `/Family/Given`.

Note that name structure is not dynamic.  It is set once only, when you enter the name.  It does not change later.

The name-order options only take effect when you **create** a name.

Are you seeing the wrong order when you **create** names?

**Comment by waylonwang** [comment]
Is that option include in version 1.7.2? I can't find different rule of create full name when I switch the language.

My download path is 'https://launchpadlibrarian.net/214692666/webtrees-1.7.2.zip', is this a latest install package?

**Comment by fisharebest** [comment]
> Is that option include in version 1.7.2?

This logic has existed since 1.0.0.

> I can't find different rule of create full name when I switch the language

Are you following the **exact** same steps that I listed in my first post.

**Comment by fisharebest** [comment]
@waylongwang -

If I set the language to English, and enter surname `邓` and given name `小平` then I get `小平 /邓/` (English name structure).

If I set the language to Chinese, and enter surname `邓` and given name `小平` then I get `/邓/小平` (Chinese name structure).

If you do not see this behaviour, then you will need to demonstrate it on your site.  Perhaps create a new tree, and give me an account with edit permission.
