### ISSUE TITLE
incorrect display of date format when translating to Chinese

### ISSUE THREAD

**Issue by waylonwang** [fisharebest/webtrees#709]
The date format was wrong when changed language to zh-Hans,'1 January 1850' should be translated to '1850年 01月 01日',but it has been translated to '1850年 01月 %s日' now,all date of webtrees has found this bug,please fix it,thanks!

![dateformat](https://cloud.githubusercontent.com/assets/7424276/9568344/409666fe-4f79-11e5-86da-9d027fbf916a.png)

**Comment by waylonwang** [comment]
I have checked the line 190 of .po file was wrong,the path is '/language/zh-Hans.po'.

#. I18N: This is the format string for full dates.  See http://php.net/date for codes
#: app/I18N.php:160
msgid "%j %F %Y"
msgstr "%Y年 %m月 %s日"

msgstr  must be replaced to  "%Y年 %m月 %d日"

**Comment by fisharebest** [comment]
The placeholders `%m` and `%d` have leading zeros.  See [php.net/date](http://php.net/manual/en/function.date.php) for the documentation

Is this correct? [Wikipedia](https://en.wikipedia.org/wiki/Date_format_by_country) says we should **not** use leading zeros.  The equivalent placeholders without leading zeros are `%n` and `%j`.

Updates to the translation strings need to be made vie [translate.webtrees.net](http://translate.webtrees.net).

**Comment by waylonwang** [comment]
I try to change dateFormat function for test

public static function dateFormat() {
		return '%Y年 %n月 %j日';
}

result is correct,and this is the better solution:)

**Comment by wooc** [comment]
The better solution is update to the translation string via translate.webtrees.net as mentioned by Greg.

**Comment by waylonwang** [comment]
Yes, I mean the use of '%Y年 %n月 %j日' as translation strings is a better solution.

**Comment by fisharebest** [comment]
Somebody needs to update the translation at http://translate.webtrees.net
Preferably someone who understands Chinese.  Can you do this?

**Comment by waylonwang** [comment]
I have download Poedit this afternoon, it's a great tool. I try to edit zh-Hans.po and make zh-Hans.mo, it's worked very well.

I can help you to update some resource translation to Chinese, and I can replenish some untranslated resource if I have time.

**Comment by waylonwang** [comment]
I have changed the '%Y年 %m月 %s日' to '%Y年 %n月 %j日' at http://translate.webtrees.net.

Online translation is indeed more convenient than edit the po file, I will do my best to reduce untranslated resources.
