### ISSUE TITLE
problem with name display when using only surname with name suffix

### ISSUE THREAD

**Issue by zhoueysun** [fisharebest/webtrees#711]
In Chinese genealogy, the elder married woman will be called by her birth surname and then the name suffix Shee (氏). It is the same as the French term née, but the term is actually added to the nomenclature.

The current webtrees 1.7.2 repeats the suffix if a space is removed between the suffix and the surname. See example:

![double name without space](https://cloud.githubusercontent.com/assets/14076780/9635408/3105613a-514b-11e5-9124-caad5355f607.JPG)

If I don't modify the name and leave a space between the suffix and surname, then the result is as below:

![no double name with space](https://cloud.githubusercontent.com/assets/14076780/9635478/844c31fc-514b-11e5-8517-8db1d511c3b3.JPG)

BTW: is this site in lieu of https://bugs.launchpad.net/webtrees

**Comment by waylonwang** [comment]
I think use the 'married surname' is the better way.

I don't know what ‘her birth surname’ means, meaning that her husband‘s surname or her father's surname? The ancients correct surname should be the husband's surname,but now woman have not so styled.

**Comment by waylonwang** [comment]
zhoueysun, Do you have troubled with style name(字) and pseudonym(号) of ancestors? It is to add a new name or use a nickname or prefix/suffix to solve?

**Comment by zhoueysun** [comment]
waylonwang,

By birthname, I meant the wife's father's surname. See example. Most Chinese text will not have a space between the two characters.

![sou shee](https://cloud.githubusercontent.com/assets/14076780/9641548/19ceb5fe-516c-11e5-8b6d-a934248225a7.JPG)

I don't have problems with the style or any other names, since fisharebest showed me how to modify the code so I can pick the correct name type. A future request: since the name type is user defined text, when I modify the name, it will erase my user defined text I had entered previously. See example: 

![joe hip](https://cloud.githubusercontent.com/assets/14076780/9641665/c4c775f4-516c-11e5-892e-9de8a15d06ec.JPG)

**Comment by fisharebest** [comment]
webtrees has always modified the NAME field (internally) to include NICK, NPFX and NSFX fields that are not present in the NAME.

I do not agree with this logic - but it was inherited from PhpGedView.  If I remember correctly, this logic is an attempt to work around a deficiency in an old desktop program.

If we change the logic, we will have a small problem.

The generated "full name" is stored in the database.  When we fetch data for the individual list, we need to match individuals against this name.  If we have a different algorithm for calculating it, we won't match.

For example, if we have stored "joemd md" in the database, it won't match "joemd".

Before making any change, I need to work out the impact of the change.

**Comment by fisharebest** [comment]
When entering names in Chinese, we **do not** include a space between the SURN and GIVN.

But we **do** include a space between the NPFX, SPFX and NSFX.  I guess this is wrong.

**Comment by zhoueysun** [comment]
To clarify, I was not using the Chinese language module. I would manually modify the name tag by removing the space. This is the same technique I used via the English language module when entering Chinese characters. I would <select><cut> and <paste> the given name and move it behind the /surname/ without spaces. I understand that the database thinks there is a given name.

Rather than spend time on this relatively minor 'bug' rewriting the algorithm, may I recommend that space not be allowed to be removed manually if there is no given name and the display is only 'joe md'?

Then when other languages have issues, the algorithm can be re-configured. I understand you (usually) have a full plate.
