### ISSUE TITLE
Tracking URL gets converted wrongly

### ISSUE THREAD

**Issue by bmhm** [fisharebest/webtrees#714]
Hi,

I entered `https://sub.domain.invalid/` as my tracking site.

Javascript console in my browsre says: `GET https://https//sub.domain.invalid//piwik.js `

So there seems to be some kind of conversion? Also, I'd like the fields to have a description. At first I thought I'd hat to enter my auth key, but it is just the site number.

**Comment by bmhm** [comment]
Perhaps it's the description. It says "enter URL", which is what I did. But just the domain is being  requested. So I'd propose:

 1. Either change the description to "domain" instead of "URL" (or domain with path without trailing slash).
 2. Be more generous about what was entered
 3. Use the Piwik API instead and let the user chose from a dropdown box - like WP-Piwik implements this feature.

**Comment by fisharebest** [comment]
> 2 Be more generous about what was entered

This seems the most flexible option.

> Also, I'd like the fields to have a description. At first I thought I'd hat to enter my auth key, but it is just the site number.

The piwik documentation calls it a "Site ID" or "Site ID code", so I think our label is correct.  Unless you have a suggestion?

**Comment by bmhm** [comment]
Site ID will do, you are correct. Shall I post a PR tomorrow? It is
probably not urgent anyway.

On Fri, 4 Sep 2015 16:12 Greg Roach <notifications@github.com> wrote:

> 2 Be more generous about what was entered
>
> This seems the most flexible option.
>
> Also, I'd like the fields to have a description. At first I thought I'd
> hat to enter my auth key, but it is just the site number.
>
> The piwik documentation calls it a "Site ID" or "Site ID code", so I think
> our label is correct. Unless you have a suggestion?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fisharebest/webtrees/issues/714#issuecomment-137747332>
> .
>
-- 
Mit freundlichen Grüßen,
      Benjamin Marwell

      Jöhrensstraße 3
      30559 Hannover

      Telefon: +49 (5 11) 47 41 69 50
      Mobil  : +49 ( 1 70) 7 13 93 17
      E-Mail: E-Post@bmarwell.de
      PGP-Key: FD58 0CC0

**Comment by fisharebest** [comment]
Already fixed: 9c4e4339d16c44a8631dd70d96a756194efba24a
