### ISSUE TITLE
Tracking: Exclude roles or users

### ISSUE THREAD

**Issue by bmhm** [fisharebest/webtrees#715]
Feature request: Specific users or roles (like managers) should be excludable from tracking.

**Comment by fisharebest** [comment]
With Google Analytics, we can add the user ID to the tracking.

https://developers.google.com/analytics/devguides/collection/analyticsjs/user-id

**Comment by fisharebest** [comment]
Piwik can also does this.

**Comment by fisharebest** [comment]
Before we implement this, we need to allow visitors to opt out of tracking - http://www.cookielaw.org/the-cookie-law

**Comment by bmhm** [comment]
:+1:

**Comment by fisharebest** [comment]
I have added some extra "dimensions" to google analytics, one of which is the user's access level.  You can filter/report on this separately.
