### ISSUE TITLE
Canonical URL

### ISSUE THREAD

**Issue by bmhm** [fisharebest/webtrees#716]
We could implement a canonical URL until laravel, which would be a good thing anyway.

https://support.google.com/webmasters/answer/139066?hl=en

http://googlewebmastercentral.blogspot.de/2013/04/5-common-mistakes-with-relcanonical.html

**Comment by fisharebest** [comment]
We used a canonical URL when we used URL parameters to change theme/language (e.g. `...?lang=de`).

But we replaced these with `onclick()` events and `POST` requests.

We also fixed some other cases that were generating the same content at multiple URLs.  e.g. `index.php` and `index.php?ged=DEFAULT&ctype=gedcom`.

As far as I can tell, there are no longer any cases where we can generate the same content at multiple URLs, so therefore we should not need to specifiy a canonical URL.

**Comment by bmhm** [comment]
Still, I'd like to see a head link tag with rel=canonical. Does it hurt?

On Fri, 4 Sep 2015 16:17 Greg Roach <notifications@github.com> wrote:

> We used a canonical URL when we used URL parameters to change
> theme/language (e.g. ...?lang=de).
>
> But we replaced these with onclick() events and POST requests.
>
> We also fixed some other cases that were generating the same content at
> multiple URLs. e.g. index.php and index.php?ged=DEFAULT&ctype=gedcom.
>
> As far as I can tell, there are no longer any cases where we can generate
> the same content at multiple URLs, so therefore we should not need to
> specifiy a canonical URL.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fisharebest/webtrees/issues/716#issuecomment-137748206>
> .
>
-- 
Mit freundlichen Grüßen,
      Benjamin Marwell

      Jöhrensstraße 3
      30559 Hannover

      Telefon: +49 (5 11) 47 41 69 50
      Mobil  : +49 ( 1 70) 7 13 93 17
      E-Mail: E-Post@bmarwell.de
      PGP-Key: FD58 0CC0

**Comment by fisharebest** [comment]
> Still, I'd like to see a head link tag with rel=canonical. Does it hurt?

Suppose a site is available at two URLs:

* `http://www.example.com/my-family`
* `http://my-family.example.com/`

It is not possible for a PHP script to know which is the canonical URL, or even if another URL exists.

**Comment by bmhm** [comment]
Only via configuration - like wordpress does. If the new plugin system provides a way to modify the html head section, I'd do it as a plugin.

**Comment by fisharebest** [comment]
> If the new plugin system provides a way to modify the html head section

If you just want this for your own site, then a custom theme allows you to inject your own content into the `<head>` using the `hookHeaderExtraContent()` function.

Just extend and existing theme, and implement this function.

**Comment by bmhm** [comment]
I'd want this for every theme, same goes with my jsonld-plugin (which should respond to special requests). It doesn't feel right to implement this into a theme, since this is sth which should be theme-independent and doesn't have much to do with design.

By the way, did you receive my mails from ~2 weeks ago?

**Comment by fisharebest** [comment]
>  If the new plugin system provides a way to modify the html head section, I'd do it as a plugin.

The module system in 2.0 now allows this, through [ModuleGlobalInterface](https://github.com/fisharebest/webtrees/blob/master/app/Module/ModuleGlobalInterface.php)

There is also a built-in module "Custom CSS and JS" which allows you to do this from the control panel.
