### ISSUE TITLE
Website Logs - From + To Dates Reset each time page displayed

### ISSUE THREAD

**Issue by eric215** [fisharebest/webtrees#718]
*This seems to be new behavior with 1.7.1; I'm unable to easily go back and check prior versions.*

*To me it is a low-priority item, more something to have to remember than anything else*
 
The Website Logs page places today's date into the **From** and **To** date fields **each time** the page is displayed, even when other filters are being used, making it more difficult to perform maintenance.

Found this as I was trying to delete log entries.  It can be done but have to clear out the date fields after the desired entries are displayed and before selecting "delete"

Screen shots below - first - I cleared out all fields and was about to select "filter". 

![weblogs_before](https://cloud.githubusercontent.com/assets/13973937/9699447/55a498cc-53b1-11e5-8722-51b4399fb966.jpg)

 Second shot is the resulting display - note dates have changed again.

![weblogs_display](https://cloud.githubusercontent.com/assets/13973937/9699449/6202c9a4-53b1-11e5-8544-5599181bed37.jpg)

As an example To remove all log entries from my own IP address (because I don't care about those)

1. Paste the IP address in the filter field, clear out dates
2. Select "filter"
3. Results are displayed
4. Clear out date fields
5. Select "delete" & accept confirmation dialogue

**Comment by fisharebest** [comment]
> The Website Logs page places today's date into the From and To date fields

If these fields are empty, they are set to the earliest and latest dates of **any** logs in the database.

> 4 Clear out date fields

I don't understand why you do this.  It should have no effect.  The default dates cover all data in the database.  If you delete them, they will be set back to the earliest/latest dates.

**Comment by eric215** [comment]
I believe what you describe is how it used to work, but is not how it is behaving for me with 1.7.2.   The From & To dates are being replaced with today's date *every* time, and that prevents any deletion or search from working until the From date is cleared out.

**Comment by fisharebest** [comment]
> The From & To dates are being replaced with today's date every time

I can't see how this would happen - unless your logs only contained data from today.

The code is very simple, and easy to follow - even if you are not a programmer.

```
$earliest = Database::prepare("SELECT DATE(MIN(log_time)) FROM `##log`")->execute(array())->fetchOne();
$latest   = Database::prepare("SELECT DATE(MAX(log_time)) FROM `##log`")->execute(array())->fetchOne();
$from   = Filter::get('from', '\d\d\d\d-\d\d-\d\d', $earliest);
$to     = Filter::get('to', '\d\d\d\d-\d\d-\d\d', $latest);
```

The from/to dates are the dates you specified - or if you do not specify them, the earlist/latest date from the database.

**Comment by eric215** [comment]
No longer reproducible.   I'm going to consider this a Firefox Forms/cache issue for now. It did happen consistently enough that I noticed it and was able to capture multiple screen shots, however  FF cache/history/etc have been cleared and it is no longer occurring
