### ISSUE TITLE
Error in website logs

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#723]
In the error logs on my live site I've found a whole bunch of entries with this message:

>>#0 /app/Statement.php:82 PDOException("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '773052951-773052951--unknown' for key 'wt_site_access_rule_ix1'") #1 /includes/session.php:362 execute([array]) #2 /index.php:31 require('/var/www/qb103200/data/www/wij…') 

I've scrolled through the pages to see when this message first appears and that was mid July. That's around the time wt 7.0 was released.

This error doesn't exist on my local site.

As far as I can see this bug isn't reported yet but it is mentioned in the forum:
https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-2/30610-error-found-in-website-logs#55139

**Comment by fisharebest** [comment]
Are you able to look at your webserver access logs, and find the user-agent string that accompanied this request?

You can use the timestamp of the error to find it.

The IP address (773052951) would be 46.19.218.23

**Comment by JustCarmen** [comment]
46.19.218.23 - - [09/Sep/2015:03:55:02 +0200] "GET /index.php?ctype=gedcom&ged=knegt HTTP/1.0" 200 251 "-" "-"

There are multiple of these entries in my access logs only the timestamp differs but none of them gives more information.

I've searched this IP-number and it seems to be a shared IP-number from the Netherlands:
http://www.iptodomain.com/ip-46-19-218-23.php. I don't know if that is important to know.

**Comment by fisharebest** [comment]
> 46.19.218.23 - - [09/Sep/2015:03:55:02 +0200] "GET /index.php?ctype=gedcom&ged=knegt HTTP/1.0" 200 251 "-" "-"

This shows that the visitor did not provide a user-agent string or a HTTP-REFERER.
It also used HTTP/1.0 instead of 1.1.

This is almost certainly a robot/crawler.

I guess the empty user-agent-string is not matching any searches, but already exists in the DB.  Hence we don't find it, but try to insert it.
