### ISSUE TITLE
1.7.2 upgrade issue - OpenStreetMap module

### ISSUE THREAD

**Issue by Amgine0** [fisharebest/webtrees#724]
Self-update output:

```
Check for custom modules…
Fatal error: Class 'WT_Module' not found in /var/www/webtrees/modules_v3/openstreetmap/module.php on line 11
```

**Comment by fisharebest** [comment]
The OpenStreetMap module is not part of webtrees.

**Comment by Amgine0** [comment]
Understood, however it apparently interrupted the upgrade rendering the site broken. e.g. [Jean Cartier](https://saewyc.ca/l/23 "Genealogy entry")

**Comment by fisharebest** [comment]
> Understood, however it apparently interrupted the upgrade rendering the site broken. e.g. Jean Cartier

This error (Error 28 from storage engine) means that you have run out of disk space.

**Comment by fisharebest** [comment]
> Fatal error: Class 'WT_Module' not found

We cannot detect fatal errors in other people's code until PHP7.0

With PHP7.0, these errors should be managed correctly.

**Comment by Amgine0** [comment]
Hmm. I traced *that* issue back to the /tmp being on a ram disk. That part is (temporarily) resolved.

Here is a method to capture fatal errors, [on StackOverflow](https://stackoverflow.com/questions/277224/how-do-i-catch-a-php-fatal-error), php 5.2+. Here is a cap of where the upgrade script stops; I will unload the module to actually do the upgrade later.

![upgrade](https://cloud.githubusercontent.com/assets/1359795/9838476/10e480d2-5a4e-11e5-8e35-fbddf01a9654.jpg)
