### ISSUE TITLE
I add a markdown URL to an individual source text, I see the URL with the markdown in reports 

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#728]
I create and individual level 1 source and fill for instance [Geni](http://www.geni.com) with markdown in the text field.
The source is created in webtrees as
1 SOUR
2 DATA
3 TEXT
I expect to see the URL in the level 3 text field the same way as in the level 2 note, which today is that no URL data is shown.

**Comment by melizaa** [comment]
I fill 
<pre lang="no-highlight"> 
<code>
[Geni](http://www.geni.com)
</code>
</pre>

**Comment by melizaa** [comment]
The real question is, why do I need to write the URL as above in order to see it as a link in webtrees?

According for instance to the page https://guides.github.com/features/mastering-markdown/:
"Automatic linking for URLs
Any URL (like http://www.github.com/) will be automatically converted into a clickable link."

Why does webtrees no longer show the simple URLs (like http://www.geni.com) as links?
(Webtrees reports do show them as links.)

I have still 2500 individual with URL links that are not as above.
It takes very long to manually change them to the above format, and this should be unnecessary.

In the past, webtrees used to print these simple URLs as links.

**Comment by webtrees** [comment]
I think the problem is that there is currently no markdown processing for the TEXT of a SOURCE citation. (See for instance issue #712  " Convert markdown-generated url's in the form of an @xref@ to webtrees url's")

**Comment by fisharebest** [comment]
> I think the problem is that there is currently no markdown processing for the TEXT of a SOURCE citation.

Are you sure?  I just tried adding markdown to a citation (TEXT) field, and the formatting was applied.
