### ISSUE TITLE
Error last download 2015/09/27

### ISSUE THREAD

**Issue by Fa10175** [fisharebest/webtrees#733]
Warning: require(/.../vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php): failed to open stream: Aucun fichier ou dossier de ce type in /...r/vendor/composer/autoload_real.php on line 58

Fatal error: require(): Failed opening required '/.../vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php' (include_path='/.../vendor/bombayworks/zendframework1/library:.:/opt/lampp/lib/php') in /.../vendor/composer/autoload_real.php on line 58

**Comment by fisharebest** [comment]
Quick answer - install the missing dependencies using `composer` (http://getcomposer.org).

Run `composer install`.

Long answer - wait for a day or two, or roll-back to an earlier release (perhaps Friday?).
