### ISSUE TITLE
EU cookie law - tracking opt-out

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#739]
Since webtrees can now load google analytics automatically, we need to implement a tracking opt-out, to comply with [EU cookie law](http://www.cookielaw.org/the-cookie-law)

See also #715

**Comment by fisharebest** [comment]
webtrees now honours the DNT header, if set by the user.

**Comment by fisharebest** [comment]
We still need to create a page with a cookie policy.

**Comment by makitso** [comment]
A long time ago I created the base cookie policy for USBank.  It's been
updated since but......

https://www.usbank.com/privacy/security.html

**Comment by fisharebest** [comment]
On reflection, I don't think we can do this.  We know what cookies **we** have added (e.g. google analytics), but we don't know what other cookies users may have added themselves - e.g. custom modules/themes or embedding webtrees in another application.

We have a dismissable warning when analytics cookies are used.  I think this is the best we can do.
