### ISSUE TITLE
Merging individuals with only the same surname, deletes the data of the target individual

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#740]
I had a wife and her husband’s family on my site and I had her father and his ancestors.
In order to create a family for the father and his daughter I created a one parent family with a child and I merged the wife and the child.
The wife’s existing data was removed by the action.

I have a married woman (I3600) (Woman B1) and I want to link her to her existing father. (Husband is Husband B2).
I add to the father (Father B1) a one parent child (with only a name, without sex)(I3608) (aa B1) and merge the woman with the child.

I see on the Merge page “No matching facts found” for
The following facts and events were found in both records.
The following facts and events were only found in the record of WomanB1.
The following facts and events were only found in the record of aa B1.

I click save

I see
The link from “Father B1 + … …” to “aa B1” has been updated.
The records “Woman B1” and “aa B1” have been merged.

After I approve the changes:
I3600’s data is deleted. Also the link to the family record with her husband is deleted and the link to her father does not exist.
Father and Husband are linked to I3600, as expected. 
I3608 is deleted, as expected.

When I define the child with sex F (C individuals), the merge works as expected. 

I will send my TestMerge.ged file to Greg.

**Comment by FrankWarius** [comment]
same issuee when merging sources which have no matching data:

old:
0 @S239@ SOUR
1 TITL Ossian Mesterton
1 WWW http://www.mesterton.net
1 CHAN
2 DATE 29 JAN 2012
3 TIME 13:29:22
2 _WT_USER FrankW
1 _UID 5C44D7C9A147F4E43DE2C1E8646220134CCF

new:
0 @S239@ SOUR
1 CHAN
2 DATE 31 Dec 2015
3 TIME 10:42:10
2 _WT_USER FrankW

record merged:
0 @S601@ SOUR 
1 TITL Släkten Spalding 
1 WWW http://koti.phnet.fi/ossian/spalding.htm 
1 CHAN 
2 DATE 25 JUN 2007 
3 TIME 18:02:18 
2 _WT_USER FrankW 
1 _UID 3E595B149FCD48D4C10ED65949387F6148A5

the linked records where updated correct

regards
Frank
