### ISSUE TITLE
Android chrome browser touch events fail for single menu items

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#747]
For Android devices ( tablet or mobile),  touch events fail on webtrees primary menu items that contain no submenus.  For example if you only have one gedcom tree defined or if you have stories enabled, the generated code would look like this:

`<li class="menu-tree">`
	 `<a href="index.php?ctype=gedcom&ged=FamilyTree">Family tree</a>`
`</li>`
`<li class="menu-story">`
	`<a href="module.php?mod=stories&mod_action=show_list">Stories</a>`
`</li>`

Android browser's do allow for the option to “Request desktop site.”  By default, this is not enabled.  

The problem is that when an Android user touches the primary menu icon for Stories or Home (with only one tree defined), nothing happens.  If the user has selected the “Request desktop site” then selecting any primary icon fires the first item in the sub menu – an undesirable experience.

For comparison purposes only,  the www.webtrees.net web site has three primary icons that do not have submenus; Home Page, Forum and Add-ons.  The code generated has this general structure:

`<li class="item-149 current active deeper parent">`
	`<a class="hash" href="/index.php/en/">`
		`<img alt="Home page" src="/templates/webtrees/images/home.png">`
		`<span class="image-title">Home page</span>`
	`</a>`
	`<ul class="nav- unstyled small">`
		`<li class="item-272">`
			`<a href="/index.php/en/home-en/home-page">`
				`<img alt="Home page" src="/templates/webtrees/images/home-16.png">`
				`<span class="image-title">Home page</span>`
			`</a>`
		`</li>`
	`</ul>`
`</li>`

Android devices work correctly with this configuration.

**Comment by fisharebest** [comment]
we need to eliminate hover menus.  it's a problem of user resistance more than anything else

**Comment by makitso** [comment]
IMO, hover menus are not the villian since webtrees.net uses them and they work correctly and I believe they worked OK with version 1.6.2 -- if my memory serves me.   I suspect that it would be much simpler, and easier to support, if we structured the menus like what I see in Carmen's JustLight theme.

**Comment by makitso** [comment]
Yea, I just spun up a 1.6.2 version and a single tree  has this structure and it works with Android

`<li id="menu-tree">`
`<a href="index.php?ctype=gedcom&ged=Peters">Home page</a>`
`<ul>`
`<li id="menu-tree-1">`
`<a href="index.php?ctype=gedcom&ged=Peters">`
`<span dir="auto">My family tree</span>`
`</a`>
</li>
</ul>
</li>

**Comment by fisharebest** [comment]
www.webtrees.net does have hover menus - but it does not have *empty* hover menus.

The "Home page" menu has a submenu "Home page", etc.

AFAICT, the problem is that the browser is detecting "hover menu markup", and implementing special logic so that a tap causes the submenu to toggle on/off.

Since our sub-menu is empty, and clicking in the main menu link is being "hijacked" by the browser, we are stuck.

In 1.6.2, all menus had at least 1 submenu.

In the current code (by popular demand), these "one-entry" submenus were removed.

> if we structured the menus like what I see in Carmen's JustLight theme

IIRC JustLight uses bootstrap (google can't find me a site to check this) - which does not use hover menus.

**Comment by fisharebest** [comment]
> (google can't find me a site to check this)

OK - I found one.  No hover menus.

**Comment by fisharebest** [comment]
Suggestion:

1) short term: re-introduce submenus for all menus.

2) long term: replace CSS/hover menus (and jQueryUI tabs, etc. ??) with Bootstrap.

**Comment by fisharebest** [comment]
OK - I found the problem.  We have the following code:

```
		// Temporary fix for access to main menu hover elements on android/blackberry touch devices
		$this->addInlineJavascript('
			if(navigator.userAgent.match(/Android|PlayBook/i)) {
				jQuery(".primary-menu > li > a").attr("href", "#");
			}
		');
```

It disables *all* top-level menus, not just those with children.
