### ISSUE TITLE
Norwegian Census - column definitions

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#750]
[Norwegian Census info - Ark 1.pdf](https://github.com/fisharebest/webtrees/files/18668/Norwegian.Census.info.-.Ark.1.pdf)

More info at http://www.rhd.uit.no/

**Comment by HRN-webtrees** [comment]
1 Feb 1801

31 Dec 1865

31 Dec 1875 (actually 3 Jan 1876)

31 Dec 1885 (cities only)

1 Jan 1891

3 Dec 1900

1 Dec 1910


column definitions:

Person no|Household no|Name|Age/born|Place of birth|Family position|Martial status|Occupation|Residential status

Example:
http://digitalarkivet.arkivverket.no/en-gb/ft/person/pf01036754000048

http://www.arkivverket.no/eng/content/view/full/629

**Comment by fisharebest** [comment]
This will need a Norwegian speaker/volunteer.
