### ISSUE TITLE
Need to add Windows Phone 8.1 devices to site access rules

### ISSUE THREAD

**Issue by yann64** [fisharebest/webtrees#752]
Windows Phone 8.1 are currently not allowed by webtress site access rules and need to be added manualy by allowing the following user agent:
```
Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft; %) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537
```
Windows Phone 10 user agent will also have to be added once officially released (December this year?).

**Comment by yann64** [comment]
Windows Phone 10 uses Microsoft Edge that is already allowed by site access rules, so this modification will be only for older 8.1 phones that cannot get migrated to 10.

**Comment by fisharebest** [comment]
It is a little amusing that Microsoft create a user-agent string that contains identifiers from almost every other browser - but still it is not recognised ;-)

**Comment by yann64** [comment]
Indeed, and I find the part stating that the compability is like what you can expect on an IOS 7 is very questionable...
Thanks for fixing this!
