### ISSUE TITLE
Make User Approval easier

### ISSUE THREAD

**Issue by ftrojahn** [fisharebest/webtrees#753]
In our project, we have more than 3000 users and get new user requests several times a week.

Before at least Webtrees version 1.7.2 it was really easy to approve a user: 
 * go to /admin_users.php list, 
 * sort "approved" column, 
 * click "no"
 * select "yes" 
 * save. 
Repeatedly for multiple users.

Now ... edit user, click "Approved by administrator", go to end of page, save ... back to list, same again for every user. Or we don't know how to do it more quickly.

I have two ideas how this could be done really easy:

* in the list, list box to the left with edit symbol, have an extra entry "approve"

* in /admin.php, "Users" panel, beneath each "not approved by an administrator" user, have an approval-icon if the user has verified it's email address.

What do you think? We'd try to provide a pull request for this.

**Comment by fisharebest** [comment]
Just trying to understand your workflow...

> go to end of page, save

Don't you also need to set the access permissions, and link the user account to an individual record?

This is what happens on (almost?) all other sites.

**Comment by ftrojahn** [comment]
Well ... no. There are only about 280 gedcoms and >3000 users, only few have individual record. Permissions have configured defaults.

It's even worse - just noticed this: when coming back to the users list after saving the user record, the sorting is back to standard (means: sorting is not saved in e.g. cookie) so another regression IMHO.

**Comment by fisharebest** [comment]
> Permissions have configured defaults.

So, if I understand correctly; when you approve a user, you do not grant them membership of any tree.  They remain "visitor" on all trees?

> Or we don't know how to do it more quickly.

On my browser (firefox), after clicking the "approved by admin" checkbox, I can just press "enter" to submit the form.

> when coming back to the users list after saving the user record, the sorting is back to standard

Fixed.
