### ISSUE TITLE
Media Download

### ISSUE THREAD

**Issue by wodka** [fisharebest/webtrees#755]
is there a way to enable media to be downloadable?

**Comment by fisharebest** [comment]
It is downloadable?
Right-click on a thumbnail, save link as

Or do you want a button marked "download media"?

**Comment by wodka** [comment]
For the images I only get a inline representation like: data:image/png;base64,... 
sadly that does not work (at least not in chrome)

meaning a "download media" button would be perfect.

**Comment by fisharebest** [comment]
> For the images I only get a inline representation like: data:image/png;base64,... 

Really?

We only use inline images in Control Panel / Manage media / Unused media.

Elsewhere we use links, and these work for me.

> meaning a "download media" button would be perfect.

In the past, we had a download link on each media page.  This was removed by popular request.  Most site admins do not want to make it easy for people to take their content.

**Comment by wodka** [comment]
Ah :) I only have the inline thing if I go to "Multimedia -> Click on Image -> in Overlay right Click"

If I right click directly inside the multimedia tab it works.



Would it be ok to add a setting for the media? ala "show download link yes/no"

**Comment by JustCarmen** [comment]
>> Would it be ok to add a setting for the media? ala "show download link yes/no"

This already exists in the tree preferences options in control panel (under media)

![25-10-2015 23-56-48](https://cloud.githubusercontent.com/assets/5641963/10718501/bf73b0ea-7b74-11e5-90aa-f6fccd67e54c.jpg)

**Comment by wodka** [comment]
I had this already activated - took me a while now to find the generated link...

it is then only available in the mediaviewer
![image](https://cloud.githubusercontent.com/assets/385731/10727549/fa42ad6e-7bda-11e5-8fa6-5a3e405ef629.png)

whereas in the media tab of the user there is no link
![image](https://cloud.githubusercontent.com/assets/385731/10727568/29ba3ee0-7bdb-11e5-836b-3943cff76f45.png)

also not in the overlay - there I would expect the download link
![image](https://cloud.githubusercontent.com/assets/385731/10727604/62079860-7bdb-11e5-893f-16a0c41890be.png)

**Comment by fisharebest** [comment]
> it is then only available in the mediaviewer

The option is called "Show download link in mediaviewer" ;-)

> whereas in the media tab of the user there is no link

Click on the image - open in overlay
Click on title - go to media viewer
IMHO, a third link (for download) would be confusing and crowded.

From this tab, a download requires only 2 clicks.  One to get to the media viewer page.  One to download the file.

**Comment by fisharebest** [comment]
> a download requires only 2 clicks

I think this is OK.
