### ISSUE TITLE
site-offline.php won't work with PHP5.3

### ISSUE THREAD

**Issue by BertKoor** [fisharebest/webtrees#758]
I've just upgraded to wt 1.7.2 while still on PHP5.3 (working on that) but site-offline.php gave a server error 500. Line 22 of site-offline.php refers to WT_ROOT which is defined a couple of lines below. Moving that define some lines up made that page work again.
Please include that fix in the next release? Thnx...

**Comment by fisharebest** [comment]
Fixed last month...

https://github.com/fisharebest/webtrees/commit/c2eb1bb185cf8696f593922c0424eac85328e3a5
