### ISSUE TITLE
Googlemap tab/link is present for search engine bots but page returns 403

### ISSUE THREAD

**Issue by arpiun** [fisharebest/webtrees#762]
- The Google Maps tab on an individual.php page is present when browsing the site as a robot ;

- When clicking on the provided link behind this tab (i.e. /individual.php?pid=I[0-9]+&ged=$gedtree&action=ajax&module=googlemap) then webtrees detects that the agent is a search engine robot and returns 403 Forbidden (normal behavior) ;

This tab on individual.php may not be presented to search engine robots.

This results in errors being reported in Google Webmaster Tools :
![screen-capture](https://cloud.githubusercontent.com/assets/15666506/10962352/c1866ec4-8397-11e5-91cf-2c8fb7e1ce10.png)

**Comment by fisharebest** [comment]
This was fixed in #720 and the fix will be included in 1.7.3
