### ISSUE TITLE
Import Gedcom Bug

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#768]
A Gedcom file created in v1.6.2 has lines similar to this

> 2 NOTE bla bla bla long line ... other records show him as being from Gl
> 3 CONC oucestershire or Cheshire. 

On importing that gedcom into v1.7.2 the import routine leaves a space at the line break like so
> Gl oucestershire

**Comment by fisharebest** [comment]
When you import the GEDCOM, there's an option to "Add spaces where long lines were wrapped ".

Did you select it by mistake?

**Comment by ddrury** [comment]
Yep, apologies
