### ISSUE TITLE
Fact editor bug?

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#769]
Initially created a fact without a date like so

> 1 BIRT
> 2 PLAC Gloucestershire, England
> 2 SOUR @S26@
> 3 PAGE Piece: 2237, Folio: 421, Page: 60
> 3 QUAY 2

On re-editing that fact to enter a date, the field is not show neccessitating the use of the raw gedcom editor

**Comment by fisharebest** [comment]
Do you have "Show full source fields" enabled?  Does the problem disappear if you disable it?

i.e. the option that gives you "date of entry in original source".

Perhaps the code is seeing that date, and confusing it with the event date...

**Comment by ddrury** [comment]
"Show full source fields" wasn't enabled. Enabling it makes no difference

**Comment by ddrury** [comment]
Hm, By enabling and then disabling "Show full source fields" the date field is now showing albeit not in it's usual place. It's at the bottom of the form adjacent to the source fields. I'm absolutely sure it wasn't there before. I'm going out now but I'll re-import the Gedcom and start from scratch when I get back

**Comment by fisharebest** [comment]
> not in it's usual place. It's at the bottom

This is the same when adding any missing field - they are put at the bottom.

**Comment by ddrury** [comment]
I must have had a really bad day. It of course is there - I'll book an appointment with the optician
