### ISSUE TITLE
datetimepicker problem in admin_site_change.php

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#771]
Occurs in 1.7.3 master branch. 

On entering this script the "from" & "to" datetimepickers should be initialised with the earliest and latest dates found in the database but here they are both initialised with the latest date. Adding option "useCurrent: false" restores the correct working and there is some reference in the example code here: http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers, however I can't find issue #1075.

This is made all the more strange by the fact that admin_site_logs.php uses virtually the same code and it works without this option.

This is occurring on a windows 10 installation and I tried with firefox, chrome & edge!!

**Comment by fisharebest** [comment]
> but here they are both initialised with the latest date

I don't see this.   I see the earliest/latest dates as expected.  (Firefox and Chrome).

Does the original/raw HTML have the correct dates?  (i.e. is it the browser that is modifying them, or is the server sending the wrong dates?)

**Comment by ddrury** [comment]
Ho Hum, I don't see it now either - be aware that if you're using the current code then the recent PR for admin_site_change.php that you accepted from me includes the "useCurrent: false" option, however the code still functions properly with it removed.

I've just upgraded from php 7.0.0 to 7.0.1 can't see why but maybe that affected things - may as well close this!
