### ISSUE TITLE
Minor bug in gedcom import

### ISSUE THREAD

**Issue by MikeT2** [fisharebest/webtrees#774]
I've come across a minor bug that occurs when importing a gedcom that contains media objects that are linked to several different records (e.g. a scan of a census or parish register). In previous versions of webtrees only one media object would be created, and all the individual or family records that referred to it would be linked to that one object. When you used the **Lists -> Media objects** feature of webtrees, each media object would be shown once, and all the individuals or families that referred to it would be listed under it.

In webtrees version 1.7.2 that's no longer the case if media objects don't have a title (TITL) set. In that case a separate media object is created for each reference, so a census scan that shows four individuals in a tree will be created as four separate, but identical media objects, and will be listed four times in a media objects list.

I'm not sure exactly which version of webtrees introduced this bug, but it's certainly there in 1.7.2 and definitely wasn't there in 1.6.2.

I've done some poking around and the problem occurs in app/Functions/FunctionImport.php in the **createMediaObject()** function which starts at line 1011. One of the first things that function does is check whether the media object reference that's being imported has a title attribute that isn't blank. If a non-blank title attribute isn't found, then the variable $titl is set equal to variable $file. The function then goes on to check whether a matching media object has already been created, but that check always fails because previously created records of that same media object all have blank title attributes in the database.

I compared **createMediaObject()** in 1.7.2's app/Functions/FunctionImport.php with **create_media_object()** in 1.6.2's includes/functions/functions_import.php but couldn't find any significant difference. So I poked around a bit further and compared the **__construct()** function of the **Media** class in 1.7.2's app/Media.php with the **__construct()** function of the **WT_Media** class in 1.6.2's library/WT/Media.php. And there I found a significant difference.

In 1.6.2's library/WT/Media.php lines 43 to 52 look like this:

if (preg_match('/\n1 FILE (.+)/', $gedcom . $pending, $match)) {
			$this->file = $match[1];
		} else {
			$this->file = '';
		}
		if (preg_match('/\n\d TITL (.+)/', $gedcom . $pending, $match)) {
			$this->title = $match[1];
		} else {
			$this->title = $this->file;
		}

but in 1.7.2's app/Media.php lines 46 to 51 are these:

if (preg_match('/\n1 FILE (.+)/', $gedcom . $pending, $match)) {
			$this->file = $match[1];
		}
		if (preg_match('/\n\d TITL (.+)/', $gedcom . $pending, $match)) {
			$this->title = $match[1];
		}

So in 1.6.2 that's where blank title attributes are set equal to file attributes before new media objects are created in the database. Those lines are missing in the equivalent 1.7.2 code so the title attribute remains blank in the database.

I was able to fix this bug by adding the extra lines from 1.6.2's library/WT/Media.php into 1.7.2's app/Media.php, but I'm not sure what other implications that change will have.
### This section added to my WT forum post ###
It seems to me that, in version 1.7.2, the code at the start of the **createMediaObject()** function in app/Functions/FunctionImport.php (lines 1012 to 1022) must be the same as the code in the **__construct()** function of the **Media** class in app/Media.php (lines 46 to 51). Whether or not that code sets a blank title attribute equal to file will depend on implications elsewehere in WebTrees that I'm not aware of.

I'm attaching a sample gedcom that demonstrates this bug (I've had to change the extension to txt as GitHub wouldn't accept ged).

[test.txt](https://github.com/fisharebest/webtrees/files/52807/test.txt)

I hope that helps,

Mike

**Comment by fisharebest** [comment]
> It seems to me that, in version 1.7.2, the code at the start of the createMediaObject() function in app/Functions/FunctionImport.php (lines 1012 to 1022) must be the same as the code in the __construct() function of the Media class in app/Media.php (lines 46 to 51).

I'd agree with this analysis.  

> Whether or not that code sets a blank title attribute equal to file will depend on implications elsewehere in WebTrees that I'm not aware of.

There was a reason for not using the filename - but I forget what it was....

**Comment by MikeT2** [comment]
Thanks Greg!

Mike
