### ISSUE TITLE
Masquerade as another user but don't update last login time

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#776]
When using the masquerade function to test some user settings I've noticed that the last login time is getting updated with the time I as admin has logged in myself as the other user.

I would rather see the last login time remains unchanged at the last time the real user was logged in. This will provide more useful information.

**Comment by fisharebest** [comment]
FYI, It is not really a "last login" time.  It does not record logins.

It is a "last active" time. It is updated every time you view a page (with a maximum of once per minute).

It is used to provide the "who is logged on now" function.

**Comment by JustCarmen** [comment]
Ok that maybe true, but that doesn't change my request. When looking in the user administration in control panel I can see the last 'active' time of users in the column with the header 'last logged in'.

When I masquerade as one of this users to test some (privacy) settings this time changes. From then on it gives false information. It doesn't give me the time this user was last active on the website but it gives the time I masquerade as this user, which is not right in my opinion.
