### ISSUE TITLE
Installation step 3

### ISSUE THREAD

**Issue by nigelhorne** [fisharebest/webtrees#777]
When I tried step 3 I got this output.  Presumably something needs to be configured on Apache but I don't know what and I couldn't work out from your installation guide:

. */ namespace Fisharebest\Webtrees; /** * Defined in session.php * * @global Tree $WT_TREE */ global $WT_TREE; use Fisharebest\Webtrees\Controller\AjaxController; use Fisharebest\Webtrees\Controller\PageController; use Fisharebest\Webtrees\Functions\Functions; use Fisharebest\Webtrees\Functions\FunctionsDb; define('WT_SCRIPT_NAME', 'index.php'); require './includes/session.php'; // The only option for action is "ajax" $action = Filter::get('action'); // The default view depends on whether we are logged in if (Auth::check()) { $ctype = Filter::get('ctype', 'gedcom|user', 'user'); } else { $ctype = 'gedcom'; } // Get the blocks list if ($ctype === 'user') { $blocks = FunctionsDb::getUserBlocks(Auth::id()); } else { $blocks = FunctionsDb::getTreeBlocks($WT_TREE->getTreeId()); } $active_blocks = Module::getActiveBlocks($WT_TREE); // The latest version is shown on the administration page. This updates it every day. Functions::fetchLatestVersion(); // We generate individual blocks using AJAX if ($action === 'ajax') { $controller = new AjaxController; $controller->pageHeader(); // Check weâ€™re displaying an allowable block. $block_id = Filter::getInteger('block_id'); if (array_key_exists($block_id, $blocks['main'])) { $module_name = $blocks['main'][$block_id]; } elseif (array_key_exists($block_id, $blocks['side'])) { $module_name = $blocks['side'][$block_id]; } else { return; } if (array_key_exists($module_name, $active_blocks)) { echo $active_blocks[$module_name]->getBlock($block_id); } return; } // Redirect search engines to the full URL if (Filter::get('ctype') !== $ctype || Filter::get('ged') !== $WT_TREE->getName()) { header('Location: ' . WT_BASE_URL . 'index.php?ctype=' . $ctype . '&ged=' . $WT_TREE->getName()); return; } $controller = new PageController; if ($ctype === 'user') { $controller->restrictAccess(Auth::check()); } $controller ->setPageTitle($ctype === 'user' ? I18N::translate('My page') : $WT_TREE->getTitle()) ->setMetaRobots('index,follow') ->pageHeader() // By default jQuery modifies AJAX URLs to disable caching, causing JS libraries to be loaded many times. ->addInlineJavascript('jQuery.ajaxSetup({cache:true});'); if ($ctype === 'user') { echo '
'; echo '
', I18N::translate('My page'), '
'; } else { echo '
'; } if ($blocks['main']) { if ($blocks['side']) { echo '
'; } else { echo '
'; } foreach ($blocks['main'] as $block_id => $module_name) { if (array_key_exists($module_name, $active_blocks)) { if (Auth::isSearchEngine() || !$active_blocks[$module_name]->loadAjax()) { // Load the block directly echo $active_blocks[$module_name]->getBlock($block_id); } else { // Load the block asynchronously echo '
 
'; $controller->addInlineJavascript( 'jQuery("#block_' . $block_id . '").load("index.php?ctype=' . $ctype . '&action=ajax&block_id=' . $block_id . '");' ); } } } echo '
'; } if ($blocks['side']) { if ($blocks['main']) { echo '
'; } else { echo '
'; } foreach ($blocks['side'] as $block_id => $module_name) { if (array_key_exists($module_name, $active_blocks)) { if (Auth::isSearchEngine() || !$active_blocks[$module_name]->loadAjax()) { // Load the block directly echo $active_blocks[$module_name]->getBlock($block_id); } else { // Load the block asynchronously echo '
 
'; $controller->addInlineJavascript( 'jQuery("#block_' . $block_id . '").load("index.php?ctype=' . $ctype . '&action=ajax&block_id=' . $block_id . '");' ); } } } echo '
'; } echo '
';

**Comment by nigelhorne** [comment]
OK, what was missing is the need to run "apt-get install libapache2-mod-php5".

Now I get:

'PHP extension “pdo_mysql” is disabled. You cannot install webtrees until this is enabled. Please ask your server’s administrator to enable it.

PHP extension “gd” is disabled. Without it, the following features will not work: creating thumbnails of images. Please ask your server’s administrator to enable it.'

Again I can't fathom that from the installation guide.

**Comment by nigelhorne** [comment]
Found the missing step:

apt-get install php5-gd php5-mysql

Would you please consider adding these to your installation guideline?  Thank you.

**Comment by fisharebest** [comment]
> need to run "apt-get install libapache2-mod-php5".

Only if you want ot run PHP as an apache module.  You could alternativly run apache and PHP via FCGI.

In the "old days", FCGI implementations were much slower than mod_php, hence there is (still) lots of online advice to use it.  But these days, there's no real difference, and FCGI gives lots of advantages, such as isolating websites/users from each other.

Given a choice, I always use php-fcgi with nginx.

> apt-get install php5-gd php5-mysql

Actually, you'd have been better off just running this: (The circumflex at the end is important).

sudo apt-get install lamp-server^

This is a meta-package, and would have installed a fully working Apache/MySQL/PHP, with all necessary dependencies, such as php5-mysql, libapache2-mod-php5, etc.

If you're installing Ubuntu Server from scratch, there's a tick-box in one of the final pages "LAMP server", which would install the same thing.

**Comment by fisharebest** [comment]
I think it's probably out of scope to give server setup instructions for various operatings systems and distributions.  There's plenty of (better) documentation available for this.
