### ISSUE TITLE
Bad advice on creating directory

### ISSUE THREAD

**Issue by nigelhorne** [fisharebest/webtrees#778]
"Setup wizard for webtrees
/var/www...../data

Oops! webtrees was unable to create files in this folder.

This usually means that you need to change the folder permissions to 777."

No, no and thrice no.  Do not change folder(sic) permissions to 777.  Always use chown to get the ownership correct.  In this case www-data.

**Comment by fisharebest** [comment]
Well, 99% of users won't have root access, and therefore won't be able to run chown.

So, "..usually means that you need to..." is pretty accurate.

**Comment by fisharebest** [comment]
The error message says that webtrees couldn't create files.  There could be many reasons for this.

Given that most of our users are not server administrators, and will be using a server provided by their ISP, the advice to `chmod` is probably the right one for them.

It's what the majority of web applications do.

The only alternative strategy is to ask the user for their SFTP/FTP credentials, and write to the file using phpleague/flysystem (or similar).  However, all decent SFTP libraries won't run on old versions of PHP.

There are lots of things that would be done differently if we controlled the server as well as the appliction, but alas we must work to the lowest common denominator.
