### ISSUE TITLE
General form user-defined GEDCOM records (creating, changing, and displaying)

### ISSUE THREAD

**Issue by webtrees-pesz** [fisharebest/webtrees#781]
Not all existing GEDCOM records (e.g. SUBM) are supported by a record specific form in the user Interface (UI). In addition the GEDOM Standard is on hold since more than 15 years and new requirements can only be implemented based on user-defined tags and/or records (e.g. _LOC).

Therefore a general UI form make sense, which is able to support unassisted records and structures.

Based on a new table in the settings (Administration) user-defined records/tags can be enriched by tag specific labels, comments, help texts, format descriptions (text, date, flag, xref, ...) and so on.

**Comment by webtrees-pesz** [comment]
Hello Greg,

 

thanks for realization. Is there a possibility to see an example in the beta demo version?

 

Best regards

Peter

 

Von: Greg Roach [mailto:notifications@github.com] 
Gesendet: Freitag, 18. Dezember 2015 23:08
An: fisharebest/webtrees
Cc: webtrees-pesz
Betreff: Re: [webtrees] General form user-defined GEDCOM records (creating, changing, and displaying) (#781)

 

Closed #781 <https://github.com/fisharebest/webtrees/issues/781>  via  <https://github.com/fisharebest/webtrees/commit/e096e2aee647cb779de456a0eb938e33b7cc8774> e096e2a.

**Comment by Amgine0** [comment]
@webtrees-pesz: You may also wish to be aware of [GedComX](https://github.com/FamilySearch/gedcomx "GitHub repository for GedComX standard"), which continues to be actively developed.
