### ISSUE TITLE
Feature request: handling and gedcom export of place informations

### ISSUE THREAD

**Issue by mpwt** [fisharebest/webtrees#782]
I miss the way to record notes / shared notes (NOTE_STRUCTURE) in accordance with the gedcom standard:
(https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-2/30854-plac-and-notes)

> Gedcom 5.5.1
> PLACE_STRUCTURE:=
> n PLAC <PLACE_NAME>
> ...
> +1 MAP
> +2 LATI <PLACE_LATITUDE>
> +2 LONG <PLACE_LONGITUDE>
> +1 <<NOTE_STRUCTURE>>

Otherwise webtrees does not export LATI/LONG informations via gedcom. Why?

There exist two ways to do it:
1. in accordance with the gedcom standard 5.5.1 (see above) with each place

or
1. to avoid redundant rows in the ged file with a link _LOC @Lxxx@ -> 0 @Lxxx@ _LOC
   (see at http://wiki-de.genealogy.net/GEDCOM/PLAC-Tag#Vereinbarungen_zu_PLAC or
   in english http://wiki-en.genealogy.net/GEDCOM/PLAC-Tag -> there are a lot of custom tags they are not so important for the whole user community of webtrees or very specially, f.i. FOKO - it is an db of research contacts - will in future no longer continued)

it might look simplified as follows:

1 BIRT
2 DATE 7 AUG 1840
2 PLAC Neu-Dierkow, MV, DEU
3 _LOC @L143@

0 @L143@ _LOC
1 NAME Neu-Dierkow, MV, DEU
1 MAP
2 LATI N54.1234
2 LONG E12.1565
(1 _GOV <GOV_IDENTIFIER> {0:1} )
1 NOTE @Nxxx@
(1 OBJE @Oxxx@) nice-to-have

_GOV (see here http://gov.genealogy.net/search/index) would be nice-to-have but if exist the possibillity to record shared notes it can be stored there.

Thanks, Martin

**Comment by fisharebest** [comment]
> Otherwise webtrees does not export LATI/LONG informations via gedcom. Why?

Yes it does?

![screenshot](https://cloud.githubusercontent.com/assets/2306088/11826647/a4cccaec-a37e-11e5-936f-763d89776d6c.png)

**Comment by mpwt** [comment]
Thanks, I saw this possibilliy but for what I import geo informations in the database table "placelocation" when I have to insert LATI and LONG again on every place citation for the complete gedcom export of them. The information exists but it is not connected right to the place citations.

Therefore I wrote this issue. :)

**Comment by ric2016** [comment]
> enhancement 1 - shared notes for places

This is now available via the custom module 'Shared Places'.

**Comment by fisharebest** [comment]
The latest dev code allows you to add `NOTE` to `PLAC`.
