### ISSUE TITLE
Page "User administration" : blank pop-up on email link

### ISSUE THREAD

**Issue by SodanWT** [fisharebest/webtrees#786]
Firefox 42/Linux

On page "User administration" after clicking on a user e-mail, there is just a blank pop-up.
Seems related to the "span" tag in the javascript link, as when removing it the pop-up loads properly.
```html
<a href="#" onclick="return message('<span dir=&quot;auto&quot;>test</span>', '', '');">email@example.com</a>
```

**Comment by fisharebest** [comment]
Duplicate of #734 and already fixed ;-)

**Comment by SodanWT** [comment]
I searched issues with "mail" keyword, not "email"...
Sorry.

**Comment by fisharebest** [comment]
No problem!
