### ISSUE TITLE
error in GitHub 8d33d34

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#791]
I see in demo-dev:
Warning: require(/home/webtrees/public_html/demo-dev/vendor/jakeasmith/http_build_url/src/http_build_url.php): failed to open stream: No such file or directory in /home/webtrees/public_html/demo-dev/vendor/composer/autoload_real.php on line 59

Fatal error: require(): Failed opening required '/home/webtrees/public_html/demo-dev/vendor/jakeasmith/http_build_url/src/http_build_url.php' (include_path='/home/webtrees/public_html/demo-dev/vendor/bombayworks/zendframework1/library:.') in /home/webtrees/public_html/demo-dev/vendor/composer/autoload_real.php on line 59

I do not see the jakeasmith package in the webtrees code?

Meliza

**Comment by fisharebest** [comment]
Fixed
