### ISSUE TITLE
Error handling different with PHP 7

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#792]
During coding, if I make some sort of coding error (for example spelling a classname incorrectly) the following message is generated which makes it difficult to track down the real problem    

    <br />
    <b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to Fisharebest\Webtrees\{closure}() must be  an instance of Exception, instance of Error given in <path>\includes\session.php :210
    Stack trace:
    #0 [internal function]: Fisharebest\Webtrees\{closure}(Object(Error))
    #1 {main}
    thrown in <b><path>\includes\session.php</b> on line <b>210</b><br />

**Comment by fisharebest** [comment]
I don't think I've seen this error.  Can you give me a specific example of a coding error that will trigger it.

**Comment by ddrury** [comment]
Index.php comment out line 28 "use Fisharebest\Webtrees\Functions\FunctionsDb;"

**Comment by fisharebest** [comment]
I just get

Fatal error: Class 'Fisharebest\Webtrees\FunctionsDb' not found in /home/greg/public_html/webtrees/index.php on line 45

**Comment by ddrury** [comment]
Aha, this seems to be a php 7 problem, on php 5.6 I get the error you mention above

**Comment by fisharebest** [comment]
This was fixed with #821 
http://php.net/manual/en/migration70.incompatible.php
