### ISSUE TITLE
For Information: xdebug issue fixed

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#793]
You may remember when I was redoing the lifescan chart I had a problem with erratic writes to a session variable. This was tracked down to a problem (on windows) where xdebug was installed in any php version that was compiled using the Visual Studio® 2012 (VC11) libraries.

I'm happy to report that this issue has been fixed in xdebug2.4.0 RC3

**Comment by fisharebest** [comment]
> (on windows)

That explains why I never saw the problem ;-)
