### ISSUE TITLE
Events of close relatives

### ISSUE THREAD

**Issue by HRN-webtrees** [fisharebest/webtrees#796]
When you tick "Events of close relatives", burials of siblings, children and grandchildren are displayed.
Should this be regarded a bug, as displaying burials are not even an option in the settings?

**Comment by fisharebest** [comment]
Death includes burial and cremation.
Birth includes baptism and christening.

This is by design.

The description of the options just says "birth" and "death" to keep the text short.

There is no convenient term for "start of life events" and "end of life events".

**Comment by HRN-webtrees** [comment]
Ok. Thanks for the explanation
