### ISSUE TITLE
webtrees function "relationship" is broken after update to 1.7.3

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#798]
After updating to 1.7.3 for all my trees the chart "relationship" does not work anymore. It shows always "No link between the two individuals could be found."

**Comment by fisharebest** [comment]
Is your webhost strato.de?  If so, there is a fault in your host's implementation of PHP.  See #697

**Comment by hartenthaler** [comment]
Oh yes! They still have this error. I had to replace in line 109 of vendor/fisharebest/algorithm/src/Dijkstra.php 'INF' with '1000000'. And now it works again! Thanks!
