### ISSUE TITLE
Census Asst: no married name; Add blank line with data - data lost on save

### ISSUE THREAD

**Issue by sleebooth** [fisharebest/webtrees#800]
Error encountered on my website using webtrees 1.7.3 and repeatable on Demo (See screen dump.)
Using new Census Assistant:
1) Selected husband and wife - wife's maiden name used rather than married surname.
2) added 3rd line using "Add/insert a Blank Row" and entered date: name, relation, condition, ageM. On Save, the data has been lost, though the 3rd line is present with blank data fields - (see screen dump)
![census assistant blank last line](https://cloud.githubusercontent.com/assets/5928173/12236037/79ce8a1e-b86f-11e5-8bd1-6771c365dcd2.jpg)

![census assistant married name and last line](https://cloud.githubusercontent.com/assets/5928173/12235768/cf6d559c-b86d-11e5-9262-6f7802c80333.jpg)

**Comment by jpretired** [comment]
I encountered the same issue.

**Comment by sleebooth** [comment]
Checking on the Demo-Dev, the data seems to be saved now, but the wife's 
maiden name is still used on a date after a marriage - it should pick up 
her married surname
John

**Comment by fisharebest** [comment]
It is always best to raise one issue at a time.  An issue can only ever have one status (complete, etc.) or be assigned to one person.
