### ISSUE TITLE
Please add URL data type to the Missing Data Report - Enhancement

### ISSUE THREAD

**Issue by sleebooth** [fisharebest/webtrees#807]
In the Missing Data Report, data types list: "Sources to the Events, Birth, .....Burial, Religion", can you add URL please. I want to be able to cross-reference with another tree and check for incomplete data.

**Comment by fisharebest** [comment]
As far as I understand the gedcom specification, the only way to store a URL against a fact/event is like this:

```
1 OCCU systems analyst
2 AGNC IBM
2 ADDR
2 WWW http://www.ibm.com
```

i.e. a `WWW` (not `URL`)  must follow `ADDR` - which is subordinate to a fact or event.

Are you using `URL` the same as `BIRT`, `OCCU`, `DEAT`, etc.

**Comment by sleebooth** [comment]
Yes - e.g.http://www.sleebooth.co.uk/individual.php?pid=I5114&ged=sleebooth.ged

**Comment by fisharebest** [comment]
A more valid construct might be to create a source for wikitree.net, and put the URL in the citation.  e.g.

```
0 @I1@ INDI
1 SOUR @S12345@
2 PAGE http://www.wikitree.net/yyyyy
```

I'm not sure it's wise to add functionality that might encourage people to create invalid GEDCOM.

But if you want to find these records, then a simple SQL query would do it.

```sql
SELECT * FROM wt_individuals WHERE i_gedcom NOT LIKE '%\n1 URL http://www.wikitree.com/%'
```

**Comment by sleebooth** [comment]
I take your point. If I went with your suggestion of using a Source, would the following find individuals without a wikitree link?:

SELECT * FROM wt_individuals WHERE i_gedcom NOT LIKE '%\n1 PAGE http://www.wikitree.com/%'

**Comment by fisharebest** [comment]
> `SELECT * FROM wt_individuals WHERE i_gedcom NOT LIKE '%\n1 PAGE http://www.wikitree.com/%' `

Not quite - PAGE is level 3.

> Is there any easy way to globally change the existing URL facts into Source and Citation entries?

If the batch update can't do it, any reasonable text editor will be able to.
