### ISSUE TITLE
does not use the right date format for unapproved changes

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#812]
On the screen of unapproved changes the date-format is not date format I use in webtrees.

The date shows 2016-01-17 instead of 07.01.2016. I am not sure, but I think that it was different in earlier versions?

**Comment by fisharebest** [comment]
I think most of the admin pages use the default (MySQL) format YYYY-MM-DD.

All the admin pages were rewritten for 1.7.0, so it may have been different before then.

**Comment by HonkXL** [comment]
I think it is ok for admin-only pages like the log. But in the unapproved changes screen it looks bad.

**Comment by fisharebest** [comment]
First, we must fix #865
