### ISSUE TITLE
[wishlist] Define order for place hierarchy

### ISSUE THREAD

**Issue by mikejpr** [fisharebest/webtrees#817]
Normaly the GEDCOM should shows the jurisdictional entities that are named in a sequence from the lowest to the highest jurisdiction. But not all genealogy programs will due it in the export.
For exemple I use Heredis and the programm save the following structure for the PLAC Tag "Town, ZIP code, County, Region, Country, Subdivision".
After importing in webtrees the data are pretty messed up for exemple subdivision as country, country as state, etc.

I would like that we can defined (during the import or afterwards in the module configuration) what value has to been imported and select the correct position so that we can merged them in the correct order.

In my exemple I want to map Position 6 to Subdivision, Position 1 to Town, ignore Position 2 (zip code), Postion 3 to County, Position 4 to Region, Position 5 to Country.

This would be a great feature.

Thx

**Comment by fisharebest** [comment]
> For exemple I use Heredis and the programm save the following structure for the PLAC Tag "Town, ZIP code, County, Region, Country, Subdivision".

You can already fix this using the "Batch update" module.

With a search/replace type of "regular expression", you could search for

```^2 PLAC ([^,\n]+), ([^,\n]+), ([^,\n]+)$``` and replace with ```2 PLAC $3, $2, $1```

which would replace "England, London, Westminster" with "Westminster, London, England".

You may also find the "Manage family trees" -> "Update place names" option useful.
