### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'username' for key 'wt_user_ix1'

### ISSUE THREAD

**Issue by Akhenaton** [fisharebest/webtrees#818]
Fresh install 1.7.3
Trying to restor an existing wt database, i got this error and can't start anything....

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'username' for key 'wt_user_ix1'

"username is my admin name i had.

**Comment by fisharebest** [comment]
> Trying to restor an existing wt database

How are you doing this?  `mysqldump`?

**Comment by Akhenaton** [comment]
Hi, i messed up the update 1.7.2 => 1.7.3 

So i installed from scratch 1.7.3 and now wt wants again make me start with the wizard but i have already my previous wt database...  it's not really a "restore", i indicate simply my database with my credentials.... (i think i erased something in the data directory.....)

**Comment by fisharebest** [comment]
> So i installed from scratch 1.7.3 and now wt wants again make me start with the wizard

If the file data/config.ini.php does not exist, webtrees will run the setup wizard.

> but i have already my previous wt database

So, the setup fails, because it cannot create the new user.  (This is good.  It is not overwriting your old user).

> (i think i erased something in the data directory.....)

Yup config.ini.php.  It should look like this

```
; <?php exit; ?> DO NOT DELETE THIS LINE
dbhost="127.0.0.1"
dbport="3306"
dbuser="XXX"
dbpass="XXX"
dbname="webtrees"
tblpfx="wt_"
```

Create this file, and everything should be good again

**Comment by Akhenaton** [comment]
You are a ...... genious !   :smiley:
Thank you so much ! Everything back to normal !
