### ISSUE TITLE
Media management - deleting more than one item not possible

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#820]
For a user that has to approve all changes, it is only possible to delete one media file. Then this is set to the list of unapproved changes. Before approving them, a further deletion will not be accepted by webtrees.

**Comment by fisharebest** [comment]
I don't understand what you are saying.

Can you provide a sequence of steps that will reproduce the issue?

**Comment by HonkXL** [comment]
I tried it again. It seemed to be a problem, maybe with my browser, because now it works. Sorry - please close this issue.
