### ISSUE TITLE
Surnames list inconsistant capitalization

### ISSUE THREAD

**Issue by ArchPrime** [fisharebest/webtrees#825]
In my website landing page kingfamily.prime.net.nz , featured families' names listed are capitalized (or not) inconsistently.

It appears that for an example family with capitilized surname in this list, no members of that family have their surname capitalized or in the wrong field when each is viewed in the 'Edit Name' dialog for those individuals.  Running version 1.7.3, though issue has been noted in earlier versions

**Comment by fisharebest** [comment]
Can you give a specific example?

**Comment by ArchPrime** [comment]
Hi Greg.  As a suggested workaround from someone in the webtrees forum, I recently tried exporting & reimporting the GED file, which seems to have un-capitalized the names that were capitalized, solving my problem.

 

Not sure how some came to be capitalized in the first place – perhaps something introduced and migrated through from my earlier PhpGEDview version of the GED file.

 

Cheers

Paul

**Comment by fisharebest** [comment]
OK thanks.  I'll close this one.  If it happens again to anybody, we can investigate then.
