### ISSUE TITLE
Error when wt_change table is empty

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#828]
If you remove all changes from the changes log via control panel a javascript error occurs after refreshing the page (admin_site_change.php):

![2016-02-06 15_13_30](https://cloud.githubusercontent.com/assets/5641963/12867101/01059ed0-cce5-11e5-8b04-7b6c1da6ecc5.png)
When the database table is empty the script can't find a date.

**Comment by fisharebest** [comment]
Fixed by ddrury in PR #829
