### ISSUE TITLE
Prevent switching to HTTPS if not configured.

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#834]
The protocol of the webtrees installation is always forced to be https if the server configuration did not contain a `HTTPS` entry, e.g. is empty.

The result of `Filter::server('HTTPS', null, 'off')`is an empty string and not `off`. So I think it would be better to test if the result is empty or `off` and keep the protocol at `http`.

**Comment by fisharebest** [comment]
I want to use the same logic as Symfony/HttpFoundation - so that we can replace our own code with the library.

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L1189

I think the symfony code ignores 'OFF' as well as 'off'.

**Comment by fisharebest** [comment]
Added `strtolower()` ...
