### ISSUE TITLE
Undefined index in admin_trees_check.php

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#840]
While executing `Control panel => Manage family trees => Check for errors`

It shows me following:

```
GEDCOM errors
/includes/session.php:193 
/admin_trees_check.php:158 
Undefined index: i385 #0 /admin_trees_check.php:158 ErrorException("/admin_trees_check.php:158 Undefined index: i385") 
```

**Comment by magicsunday** [comment]
The index is in lowercase i385 which should be I385. If I add an `$xref2 = strtoupper($xref2);` the error disappears.

**Comment by magicsunday** [comment]
It was a wrong assignment in a `BAPM` record. The baptism details were displayed correctly, only the error check was throwing failure.

**Comment by fisharebest** [comment]
Line 158 has an `@` - to ignore this exact error.  (We look for upper/lower case mismatches later.)

IIRC, `@` was used because it was faster than `array_key_exists()`.

But we should avoid `@`, so I'll remove this.
