### ISSUE TITLE
Obsolete HTML Markup - a suggestion

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#842]
Whilst you're in the mood :-) Picky suggestion

I hate` <br>` characters! so how about changing line 521 of CensusAssistantModule.php to
`		echo '<tr><td colspan="3"></td></tr>';`
As that stands it saves a bit of vertical space but IMHO still looks OK but you could add a class if needed.
Used in the 'Create a new shared note using assistant' popup

**Comment by fisharebest** [comment]
> I hate `<br>` characters!

Me too.  I also hate `&nbsp;` being used for horizontal padding ;-)

> how about changing line 521

Or perhaps

`<tr><td colspan="3" style="height:1em;"></td></tr>` ...

**Comment by ddrury** [comment]
More than one way to skin a cat!
