### ISSUE TITLE
Ancestors booklet chart - line connecting to 2nd spouse misplaced - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#846]
Ancestors booklet of children with more than one spouse. Vertical line connecting the second, etc. spouse is printed too much to the left and not high enough.
See https://dev.webtrees.net/demo-dev/ancestry.php?ged=demo&rootid=i100&chart_style=1&show_cousins=0&PEDIGREE_GENERATIONS=4&show_full=1&show_full-GUI-ONLY=1

**Comment by fisharebest** [comment]
Fixed.  Thanks for reporting!
