### ISSUE TITLE
Interactive tree - children not one under the other - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#847]
Interactive tree – Individual page and stand-alone

https://dev.webtrees.net/demo-dev/individual.php?pid=i1&ged=demo

https://dev.webtrees.net/demo-dev/module.php?mod=tree&mod_action=treeview&ged=demo&rootid=i1

Queen Elisabeth’s children do not print in the same ‘column’ one under the other.
Same issue for her grandchildren.

**Comment by fisharebest** [comment]
According to the docs `<td align="right">` should be the same as `<td style="text-align:right;">`, but it isn't...
