### ISSUE TITLE
French Censuses

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#849]
In the course of my tinkering recently, I've noticed that none of the French censuses have column definitions (well they have - 'XXXX'). Should they be released in this state? - and my french is almost non-existent so don't ask me :-(

**Comment by fisharebest** [comment]
The old census code provided dates for French censuses, but no column details.

The new code provides both together or neither.

I was hoping one of the French users would see the "XXX" and submit the correct details ;-)

I have been unable to find any online scans of French censuses to see the columns.

**Comment by ddrury** [comment]
Should I raise this in the forum to give better visibility?

Regards
David
Please consider the environment before printing this e-mail



------ Original Message ------

**Comment by Amgine0** [comment]
I have some French, but I would need something to work from.

**Comment by mikejpr** [comment]
I could translate it? But where should I do this? 
I don't found XXXX under https://translate.webtrees.net

**Comment by mikejpr** [comment]
Ok I found them in the source code!
