### ISSUE TITLE
Ancestors booklet with cousins - children's spouse vertical lines not correct - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#850]
The vertical lines to children's spouses are not correct when there is more than one spouse. Parts of the lines are missing when at least one of the spouses has more than one child.  

https://dev.webtrees.net/demo-dev/ancestry.php?ged=demo&rootid=i100&chart_style=1&show_cousins=1&show_cousins-GUI-ONLY=1&PEDIGREE_GENERATIONS=4&show_full=1&show_full-GUI-ONLY=1
Look at the too long line from Ernest Frederick, Duke of Saxe-Coburg-Saalfeld + Princess Sophie Antoinette of Brunswick-Wolfenbüttel's child Francis, Duke of Saxe-Coburg-Saalfeld

https://dev.webtrees.net/demo-dev/ancestry.php?ged=mythology&rootid=i93&chart_style=1&show_cousins=1&show_cousins-GUI-ONLY=1&PEDIGREE_GENERATIONS=4&show_full=1&show_full-GUI-ONLY=1

Look in the Cronus + Rhea family at the line from Zeus to his wives and from Hera to her husbands. 
1. The line is too short when a couple has more than 1 child.
2. The line prints too low for the last spouse.
Meliza

Greg has told me:
The logic for this line is here:
https://github.com/fisharebest/webtrees/blob/master/app/Functions/FunctionsCharts.php#L355

**Comment by makitso** [comment]
This chart uses HTML tables for positioning etc.  I am not aware of any way to fix this without a complete redesign.

**Comment by fisharebest** [comment]
The booklet views have been removed.  They were inconsistent with the rest of the charts and provide little benefit.

**Comment by makitso** [comment]
So now we can get rid of all the spacing stuff in the theme .css files?
linea1 - linea6
lined1 - lined5
line3
line4
pvline
spacer

**Comment by fisharebest** [comment]
> So now we can get rid of all the spacing stuff in the theme .css files?

Done
