### ISSUE TITLE
Search Tool Does not look for REFN (Reference Number) in records

### ISSUE THREAD

**Issue by NorwegianSardines** [fisharebest/webtrees#852]
Tried to use the Advanced Search (or any search tool) to look for a specific REFN value.  REFN is not one of the search fields in the "Advanced Search" drop down.  A general search does not return a record with the REFN value.

**Comment by fisharebest** [comment]
The general search code excludes a list of "non genealogy" fields `_UID|_WT_USER|FILE|FORM|TYPE|CHAN|REFN|RESN`.

It is not clear if you are asking for this to be changed, or simply stating that there is none of the search options allow a search on RESN.

The advanced search now includes REFN

**Comment by NorwegianSardines** [comment]
Because I use REFN heavily to identify unique people, sources and objects (the same way others may use XREF)  I need to be able to find these record instances directly by REFN.  You may recall REFN with a TYPE of Accession is used to uniquely ID all things as they are added to the database.  If a searching user can enter XREF as a search value and get a returned record REFN should have the same result.

**Comment by NorwegianSardines** [comment]
Advanced search works now with the added Reference Number option.  

The main search field at the top of the screen will not find a REFN value but I'm good with using advance only at this time,  unless the fix is easy to add REFN here as well and it does not bring back too many records for the common user.  Don't know how others use REFN, or if they even do use REFN.

**Comment by fisharebest** [comment]
> unless the fix is easy to add REFN here

The fix is trivial.  Code has been written to explicitly ignore REFN in general searches.

IIRC, the problem was that reference numbers and UIDs were creating false hits for some people.

I guess we can change it, and see if it other people report problems...
