### ISSUE TITLE
Whilst I'm in census mode - a suggestion

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#855]
Rather than using the current

```
.start_formatted_area.
census lines
.end_formatted_area.
```

formatting for shared census notes why not use markdown format instead (in fact as an experiment I did it - it's simple). I'm aware that existing notes would need converting (schema update?) and I've not looked at that but I assume we could split the existing note using the regex from function formatCensusNote and then reassemble it (or could we use mysql stored procedures - do we still support mysql 4?)

**Comment by fisharebest** [comment]
>  I'm aware that existing notes would need converting (schema update?)

I considered this originally, but wimped out.  ;-)

Another problem is that tables are not part of the official markdown specification - http://commonmark.org/

By sticking to the official spec, we can get to use more tools, such as Javascript based editors with live previews, etc.

The "gold standard" PHP library is http://commonmark.thephpleague.com/ but it requires PHP 5.5.

It's a real shame that we were forced to use the MichelF library, (which adds non-standard extensions such as tables), but it was the best option for PHP 5.3.  However, we're probably stuck with it forever :-(

> or could we use mysql stored procedures - do we still support mysql 4?

Until MySQL 5.5, stored procedures required admin privileges on the server, which most users won't have.  Even in 5.5, I guess many users still won't have "create/execute" procedure privs.  So, I don't think this will fly.

**Comment by ddrury** [comment]
commonmark does have a community addon to provide table support so it's not a complete dead end (a quick glance seems to indicate it uses the same format as the michelf library)

> By sticking to the official spec, we can get to use more tools, such as Javascript based editors with live previews, etc.

In fact I've produced a couple of modules one is a revised news & journal module which uses the other which implements  the https://github.com/NextStepWebs/simplemde-markdown-editor which is very nice but it and the underlying editor (codemirror) don't really like anything but en-US and certainly don't play well with RTL languages

**Comment by fisharebest** [comment]
https://github.com/webuni/commonmark-table-extension

**Comment by fisharebest** [comment]
Fixed in 01cf285
