### ISSUE TITLE
Level 2 _UID fields

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#858]
When I tried to register from https://www.webtrees.net/index.php/en/login-en?view=registration the only response was a blank page that said "Invalid Token".

I was hoping to start a thread about GUIDs.  When I installed webtrees and imported my GEDCOM, the "Facts and events" tab for every individual shows a GUID with each event, which is highly distracting, ugly, and difficult to read.

**Comment by fisharebest** [comment]
The "invalid token" error usually means something like:

(a) your session timed-out while you were completing the form.
(b) you didn't follow a link from another page on the site.
(c) your browser does not allow cookies.

You should contact Rob Peters (makitso@gmail.com) who operates the forum and its server.

As for the GUIDs.  I guess these are here because your previous genealogy software created/added them.  What tag *exactly* is it using. e.g. something like "_UID"...

**Comment by miqrogroove** [comment]
More like

`1781
Scotland
Globally unique identifier: 1F4E3B21-BE76-434B-AFD8-740B8820FCFC`

So the GUIDs are overwhelming the useful content.

**Comment by fisharebest** [comment]
OK, but I need to know exactly how this is being represented internally.  You can see this by clicking the "Edit raw GEDCOM link".

I'm *guessing* that the above data will be stored as follows, but I need you to confirm whether the tag is "_UID" or something else.

2 DATE 1781
2 PLAC Scotland
2 _UID 1F4E3B21-BE76-434B-AFD8-740B8820FCFC

**Comment by miqrogroove** [comment]
```1 BIRT
2 _UID 816843B8-E4A0-481A-9569-7EB27D28E921
2 RIN MH:IF6795
2 DATE 1767
2 PLAC Scotland```

**Comment by miqrogroove** [comment]
Is it easy to turn this off, or would it require some new settings to be created?

**Comment by makitso** [comment]
>When I tried to register from https://www.webtrees.net/index.php/en/login-en?view=registration the only response was a blank page that said "Invalid Token".

I just did a test registration and everything works correctly.  I would agree with Greg's assessment of the potential reasons your failed.

**Comment by miqrogroove** [comment]
I tried adding the Privacy setting for Globally unique identifier, set hide from everyone, but that had no effect.

**Comment by fisharebest** [comment]
The privacy rules apply to records (level 0) and facts (level 1).  They do not apply to attributes (level 2).
