### ISSUE TITLE
Make copied fact clipboard available to families

### ISSUE THREAD

**Issue by lindonb** [fisharebest/webtrees#860]
Enhancement request: is it possible to make a fact copied on an individual page available for a family page? I often find that I've added a fact for an individual that I realize would be better added for the family.

**Comment by sleebooth** [comment]
I second this request.

On 29/02/2016 00:26, lindonb wrote:
>
> Enhancement request: is it possible to make a fact copied on an 
> individual page available for a family page? I often find that I've 
> added a fact for an individual that I realize would be better added 
> for the family.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/fisharebest/webtrees/issues/860>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by fisharebest** [comment]
Which facts?  You shouldn't copy BIRT to a family or MARR to an individual, etc.

**Comment by vytux-com** [comment]
The only one I can think of would be residence, but I find that that works much better as an individual fact rather than family.

**Comment by lindonb** [comment]
Yes, I was thinking about Residence. Census is another one. Perhaps making only the copied facts available that would also be appropriate for families.

**Comment by fisharebest** [comment]
Also sources.  See #1224

**Comment by melizaa** [comment]
I do not yet see in the individual sources tab sources that exist in the clipboard.
