### ISSUE TITLE
note.php - needs colgroup...

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#864]
... and appropriate class.

Not submitting PR 'cos can't figure out how to submit without sending all the dev stuff

**Comment by wkitty42** [comment]
On 03/01/2016 04:40 PM, David Drury wrote:
> ... and appropriate class.
>
> Not submitting PR 'cos can't figure out how to submit without sending all the
> dev stuff

don't use "git add *" or "git add ." at the git command line... specifically add 
only those files that you want in the commit...

eg: $ git add README hello.rb


-- 
  NOTE: No off-list assistance is given without prior approval.
        *Please keep mailing list traffic on the list* unless
        private contact is specifically requested and granted.

**Comment by fisharebest** [comment]
Fixed via #867
