### ISSUE TITLE
travis-ci failing with error msg (as of 03/03/2016)

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#868]
Your github oauth token for github.com contains invalid characters: ""

**Comment by fisharebest** [comment]
I created a new one.  Same problem.

I toggled the option "Make this variable visible in the logs" - and it started working.
I toggled the option off, and it stopped working.

It needs to be off, as it's linked to my account.

Without the access token, the github API limit kicks in, and we can't download our dependencies.

**Comment by fisharebest** [comment]
It seems to have started working again.
I didn't change anything ;-)
