### ISSUE TITLE
Wrong level for CALN

### ISSUE THREAD

**Issue by mpwt** [fisharebest/webtrees#869]
I think the level of CALN is saved wrong. The problem occurs if you create a new source and connect it in the same step to a repository with a call number (CALN). See screenshot [here](https://www.webtrees.net/media/kunena/attachments/7061/Bildschirmfoto2016-03-04um19.37.18.png).

But it should like this:

SOURCE_REPOSITORY_CITATION:=
n REPO [ @XREF:REPO@ | <NULL>]
+1 CALN <SOURCE_CALL_NUMBER>

I think the error is in edit_interface.php - line 1318: \n1 CALN shold be \n2 CALN

```
$REPO = Filter::post('REPO', WT_REGEX_XREF);
	if ($REPO) {
		$newgedrec .= "\n1 REPO @" . $REPO . '@';
		$CALN = Filter::post('CALN');
		if ($CALN) {
			$newgedrec .= "\n1 CALN " . $CALN;
		}
```

**Comment by NorwegianSardines** [comment]
This error occurs when adding a new Source and Repository combination.  Not when connecting a SOUR to an already existing REPO.
