### ISSUE TITLE
Census Assistant: Marital Status wrongly set as "Wid"

### ISSUE THREAD

**Issue by sleebooth** [fisharebest/webtrees#871]
When I use the Census Assistant, the Marital Status is set to Wid rather than Mar ....in certain cases, when the spouse's death has not been specified. I tried to work out why, by replicating the case I came across on my own site on the Demo site, but it showed as Mar there.
I have managed to replicate it on my test Tree though - the Privacy - Bloggs family tree. I emailed Greg the username and password on 21/1/2015. Let me know if you need them again.
If you create an 1871 England Census entry for Richard Cocking Ninnis - http://www.sleebooth.co.uk/individual.php?pid=I6127&ged=Privacy - and use the Census Assistant, you should see what I mean:
![1871 rc ninnis](https://cloud.githubusercontent.com/assets/5928173/13578034/81cceab8-e48d-11e5-977b-703f610204c5.JPG)
If I add a Death event to his spouse - say 1872 - his status is correctly specified as Mar.
I'm running webtrees 1.7.4

**Comment by ddrury** [comment]
I **think** AbstractCensusColumnCondition function isDead() should use getEstimatedDeathDate() and not getDeathDate()

**Comment by fisharebest** [comment]
> I think AbstractCensusColumnCondition function isDead() should use getEstimatedDeathDate() and not getDeathDate()

I think `getEstimatedDeathDate()` would have the same problem - if there is no information, it returns a "null" date.
