### ISSUE TITLE
Census Record - amending Shared Note loses census fact changes

### ISSUE THREAD

**Issue by sleebooth** [fisharebest/webtrees#880]
1. Open a census fact for an individual for edit.
2. Edit one or more of the fields e.g. Source, Text, Source Citation.
3. Edit the Shared Note and save that edit.
4. The changes made in step 2 are lost.
   i.e. we need to save those changes before editing the shared note.

Tested and repeatable in the Demo Site

**Comment by fisharebest** [comment]
Fixed in the recent rewrite of this module
