### ISSUE TITLE
Level 2 RIN fields

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#881]
Same as #858 but I think there should also be a "case 'RIN'" so that the Record ID number I'm seeing under every single fact will be hidden unless editing.

**Comment by NorwegianSardines** [comment]
FACT tags should not have a RIN tag subordinate to them.  Where do these get added?  Just to be sure, you are seeing a raw GEDCOM like:

1 FACT 
2 RIN

.???

**Comment by miqrogroove** [comment]
Yes, I already explained this in the previous ticket.  They are imported from FTB.
