### ISSUE TITLE
Linking individual from different tree

### ISSUE THREAD

**Issue by imskriaz** [fisharebest/webtrees#883]
Is it possible to implement below features,

1. Admin can assign manager for specific tree/ access of the tree creator bound to his own tree
2. Webtrees can suggest common member by query facts, names and admin can link common individual from different tree

**Comment by fisharebest** [comment]
1) Yes.  There is a user-role "manager".  Control panel -> Users -> User administration -> Edit -> Role

2) webtrees works with data in the GEDCOM format.  GEDCOM does not support links between different trees.
