### ISSUE TITLE
bad "Upload geographic data" under French language

### ISSUE THREAD

**Issue by loudubewe** [fisharebest/webtrees#888]
The same 'places.csv' file is correctly uploaded with the English interface but badly uploaded with the French one.
In my csv file, country names are standard 3 letters names.
The problem (with French) is that during uploading, the word 'USA' is automatically translated into "Etats Unis d'Amérique" and the correspondence with the places in the my gedcom file is lost. When English language is selected, 'USA' is correctly uploaded as 'USA' and I can then switch back to French.

**Comment by wooc** [comment]
This is intentional. All the 3 letters names are translated into Country name in language which is currently used during the import. If you want USA instead of Etats Unis d'Amérique you can always change the name after importing.

**Comment by fisharebest** [comment]
Country codes are converted into the "common name" of the country, and then translated.

> `ENG` => `England`.  This is translated as Inglaterra (it), Angelterre (fr), etc.
> `FRA` => `France`.  This is translated as Francia (it), France (fr), etc.

For USA, we have

> `USA` => `USA`.  This is translated as Stati Uniti d’America (it), États-Unis d’Amérique (fr), etc.

IMHO this is wrong.  The common name is not "USA".  It is  "United States".  We should have

> `USA` => `United States`.  This should be translated as Stati Uniti (it), États-Unis (fr), etc.

I will need to update the code to fix this.  Until then, there is a simple solution.  Create a [custom translation](https://wiki.webtrees.net/en/Custom_Translation) for "USA" in French.  e.g.

data/languages/fr.php
```
<?php return array(
  'USA' => 'États-Unis',
);
```

**Comment by vytux-com** [comment]
Shouldn't this translation happen on display of the data and not on import? That way data stored in PLAC tag would also be translatable to the current language....
