### ISSUE TITLE
Feature request: WebAPI and application

### ISSUE THREAD

**Issue by ChristianLJ** [fisharebest/webtrees#891]
I would like to make an mobile application for webtrees. 
Does webtrees provide a webAPI?

**Comment by fisharebest** [comment]
There is no API at the moment, but it would be straightforward to add one.

It wouldn't necessarily need to be part of the core code - it could be implemented as a module.

The hardest part will be defining the requirements / interface.

**Comment by ChristianLJ** [comment]
I will look into this.

**Comment by bmhm** [comment]
Milestone 2.0 => I'll start adding one

**Comment by fisharebest** [comment]
Closed in favour of #1665 (duplicate)
