### ISSUE TITLE
Error on searching own name

### ISSUE THREAD

**Issue by AlGoore** [fisharebest/webtrees#894]
I have webtrees 1.7.4 installed on Ubuntu server 14.04 with Apache2, PHP 5.6 and MySQL 5.5 matching the system requirements for webtrees.

My own user named 'laurenz' is linked to my individual in the database.
If I try to search my name (there are more than one Laurenz in the database) this error occurs:

```
/var/www/webtrees/includes/session.php:193
/var/www/webtrees/app/Functions/FunctionsDb.php:187 Argument 1 passed to Fisharebest\Webtrees\Functions\FunctionsDb::Fisharebest\Webtrees\Functions\{closure}() must be an instance of Fisharebest\Webtrees\Individual, instance of Fisharebest\Webtrees\GedcomRecord given
#0 /app/Functions/FunctionsDb.php:187 ErrorException("/var/www/webtrees/app/Functions/FunctionsDb.php:187 Argument 1 passed to Fisharebest\Webtrees\Functions\FunctionsDb::Fisharebest\Webtrees\Functions\{closure}() must be an instance of Fisharebest\Webtrees\Individual, instance of Fisharebest\Webtrees\GedcomRecord given")
#1 unknown:unknown Fisharebest\Webtrees\Functions\{closure}([GedcomRecord I123@1])
#2 /app/Functions/FunctionsDb.php:187 array_filter([array], [Closure])
#3 /app/Controller/SearchController.php:242 searchIndividuals([array], [array])
#4 /app/Controller/SearchController.php:193 generalSearch() #5 /search.php:24 __construct()
```

I'm not sure...
Is it a little bug in webtrees, or just a misconfiguration or incompatibility of my setup?
Can anyone confirm this behaviour?

Thanks in advance!

Laurenz

**Comment by fisharebest** [comment]
One possibility is that you might have two records with the same XREF `I123`.
One is an individual and would be another type of record. (Submitter, custom record, etc.)

Perhaps you could export your data to a GEDCOM file, and search it for lines beginning `0 @I123@`.

**Comment by AlGoore** [comment]
Thank you for your answer!
I did not see the hint with record I123...

So I exported the GEDCOM file and I was wondering that the data of record I123 had no new lines (`\n`).
I added them and the search works fine now.
