### ISSUE TITLE
Regnerate thumbnails after GEDCOM file is imported

### ISSUE THREAD

**Issue by ChristianLJ** [fisharebest/webtrees#904]
Hi!
I have imported a GEDCOM file from MyHeritage. The imported images does not have any thumbnail associated with them after the import. Is it possible to regenerate thumbnails for these images?

When i click on an image it shows up so the images are not missing from the server.

**Comment by ChristianLJ** [comment]
I investegated this further. It seems that the images doesn't get imported. 
The images all link to MyHeritage. Somehow there still exists a base64 string of the image.

`<img class="cboxPhoto" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==" style="width: 290px; height: 387px; float: none; background-image: url(&quot;http://website.com/mediafirewall.php?mid=M8&amp;ged=lj&amp;cb=&quot;); background-size: 290px 387px; background-position: 0px 0px; background-repeat: no-repeat;" width="290" height="387">`

The URL: http://website.com/mediafirewall.php?mid=M8&amp;ged=lj&amp;cb=&quot; resolves to https://www.myheritageimages.com/P/storage/site68144981/files/00/00/14/000014_817367ad2dci0cv3350904.jpg

Is this standard behaviour or am i missing something?

**Comment by fisharebest** [comment]
> Is this standard behaviour

Possibly.  You do not give enough information.

If this is the "Unused files" section of the control panel, then yes.
If this is an external file, then possibly.
If this is a local file, then probably no.

**Comment by fisharebest** [comment]
We don't have enough information to understand this issue.  If you still have problems, please open another issue with more detail.

FYI, thumbnails are generated when they are first needed - except for files without associated media objects (e.g. unused files in the admin page), which are sent as inline base64.
