### ISSUE TITLE
Birth/Death/Marriage Reports and source records

### ISSUE THREAD

**Issue by BertKoor** [fisharebest/webtrees#906]
Note: this is a security vulnerablilty.
On trees where visitors are not allowed to see source records, visitors can access the text content of sources through a backdoor in some reports, namely birth, marriage and death reports.
See https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-4/31265-source-information-showing-on-reports-a-bug#58931

**Comment by fisharebest** [comment]
Fixed in a900710214851af825c3bf82f9de1c36e334dcf1
