### ISSUE TITLE
Error after upgrade from 1.7.3 to 1.7.4

### ISSUE THREAD

**Issue by jhnpldng** [fisharebest/webtrees#908]
Running php 7.0 on Litespeed webserver. After auto upgrade, I'm getting the following

`#0 /app/Controller/IndividualController.php:49 ErrorException("Missing argument 1 for Fisharebest\Webtrees\Controller\IndividualController::__construct(), called in /home/pauldingtree/public_html/genealogy/individual.php on line 31 and defined")
#1 /individual.php:31 __construct()`

**Comment by fisharebest** [comment]
The error message suggests that you have `individual.php` from webtrees 1.7.2 (or earlier).

Perhaps your server ran out of CPU time while making the upgrade, and you still have some old files?

I suggest you manually upload all the 1.7.4 files again, using FTP.

**Comment by jhnpldng** [comment]
I just noticed that myself. I uploaded the newer individual.php and it 
seems good but I'll go ahead and use ftp to compare/upload the rest. 
Probably was a timeout. I'll have to see what it's set at.

Thanks for getting back to me and I'll go close the issue or you can.

On 04/17/2016 10:14 AM, Greg Roach wrote:
>
> The error message suggests that you have |individual.php| from 
> webtrees 1.7.2 (or earlier).
>
> Perhaps your server ran out of CPU time while making the upgrade, and 
> you still have some old files?
>
> I suggest you manually upload all the 1.7.4 files again, using FTP.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/fisharebest/webtrees/issues/908#issuecomment-211042700>
>

-- 
ozarkswebdesign <http://ozarkswebdesign.com>

**Comment by jhnpldng** [comment]
Pretty sure we had 1.7.3
