### ISSUE TITLE
French months changed

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#911]
Why were the accented letters removed from the French calendar months on April 19, 2016? Should I make the same changes in my translation files?

Meliza

**Comment by fisharebest** [comment]
The source-texts are written in US english.

US english does not use accents on loan words - except where they are necessary for disambiguation. For example, in the French word résumé (which would be confused with resume), they only retain the final accent (resumé).

In other, unambiguous, words (such as French calendar names), they are lost.

I updated the **source** texts, but left the **translated** texts unchanged.  e.g. we now have this:

```
msgid "Ventose"
msgstr "Ventôse"
```

This keeps the accents for non en-US texts.

So, unless I made a mistake somewhere, your translations should still have accented letters.
