### ISSUE TITLE
Text cut off on relationship-chart / language German

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#912]
When I set language to German, the text "Zwillingsbruder" is messed up with the chart boxes. In English the text is "twin brother" and is displayed in two lines.

See screenshot.

![webtrees-relationship-formatting](https://cloud.githubusercontent.com/assets/16715040/14757280/1b54c222-08f2-11e6-8643-3d60d9f24963.png)

**Comment by makitso** [comment]
Could you please provide a URL so I can take a look at the?

**Comment by HonkXL** [comment]
sure: https://webtrees.weiland24.de - I hope you will see it, because I have some privacy settings. If it does not work, please write back.

**Comment by HonkXL** [comment]
direct Link: https://webtrees.weiland24.de/relationship.php?pid1=I111&pid2=I3714&ged=ged=Weiland

**Comment by makitso** [comment]
OK, looks like it's the same with all themes.  I will look at this tomorrow.
