### ISSUE TITLE
Photo Title Editing Bug

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#914]
After importing a GEDCOM with photos, the photo titles are displayed correctly, but I can't edit them.  When I click Edit Details, the title box is always blank, so if I save any changes the title is deleted.  Under edit raw, the unedited photo looks like:

0 @M14607@ OBJE
1 FORM jpg
1 TITL Ben

If I manually copy and paste the title into the empty title box and save it, then under edit raw the photo looks like:

0 @M14607@ OBJE
1 FILE P1577_879_1443.jpg
2 FORM
3 TYPE photo
2 TITL Ben

**Comment by fisharebest** [comment]
What was the original GEDCOM - before it was imported into webtrees?

(During import, webtrees converts inline media references into media objects.  I want to know if this media object was created by the other genealogy application, or by the inline->object conversion.)

**Comment by miqrogroove** [comment]
```
1 OBJE
2 FORM jpg
2 TITL Ben
2 FILE P1577_879_1443.jpg
```

From what I can see, it is attached under two individuals:

`0 @I38@ INDI`
and
`0 @I117@ INDI`

**Comment by fisharebest** [comment]
This error occurs during the import of the original GEDCOM.

The fix only applies to the import.  To see the change, you will need to import the FTB (?) GEDCOM file again.

**Comment by miqrogroove** [comment]
I will test the patch this weekend.  FTB adds many custom fields to the photos so I will make sure the regex is compatible.  Thank you.

**Comment by miqrogroove** [comment]
It works!  Thanks again.
