### ISSUE TITLE
imprint and data privacy statement visible on all pages

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#920]
In Germany in some cases it is requiered to have a imprint and a data privacy statement visible on all pages. Best place for this is good visible on the menu on top. It is not ok to link only from the start page - it has to be on all pages.
Some users did this with other plugins to add a special menu, but the cleaner and better way would be to add this to Webtrees without any plugin/addon.

It would be a ideal situation to have this page and the content of this pages is configurable for differnt languages.

**Comment by fisharebest** [comment]
> pages is configurable

> configurable for different languages.

I asked on the forum if there was a "template" that we could configure.  Perhaps by inserting names and email addresses.

I was told this was not possible.

How do you think such a system will work?

**Comment by HonkXL** [comment]
I think it is not possible with a template, because there are to many different details to care of. You have to put in other text for private or business pages or if you use tracking tools or anything else.

I think the best and easiest way would be:
Create two new items on top menu (near the login text). Make then configurable, so users can enable them if requiered. In the backend add simple HTML-editfields for both pages for the different languages. If a language is not configured, it sould link to the page in a configurable default language.

I think this would be the easiest way for you and the simplest way for the user. I think it is no good idea to suggest any text for this, because maybe someone makes you liable if there is any mistake in this text. And thats not good.

**Comment by HonkXL** [comment]
Here is a (good) example:
https://ffp.bauschaffen.de/index.php?ctype=gedcom&ged=Pannier

Scroll down - on bottom of the page there are two links "Impressum" and "Datenschutzerklärung". This is done using vytux menu. The problem here is, that the same page is displayed in all languages.

But it's a good idea to put this two links to bottom.

**Comment by mpwt** [comment]
:) Thanks. 
My solution based on VytuxPages (menu item "Info") and the module Custom JavaScript for the footer part. The menu item I can translate with a custom language file in data/language/de.mo, but not the footer part.

It would be great to have an optional menu for an Imprint and a Privacy policy and a direct link from the footer. The content could be a html block where the admin can insert what he wants.

**Comment by HonkXL** [comment]
Yesterday I installed MediaWiki on my server. In a fresh installed MediaWiki there are this links on the buttom of the page:
"privacy" - "About this Wiki" and "Imprint".
They are linked to pages without any content. Maybe it could be solved in this way in Webtrees?

**Comment by HonkXL** [comment]
Are there any plans to implement this in a future update?

**Comment by fisharebest** [comment]
If you want a "standard" privacy policy, so that an admin can simply tick a box to enable it - then yes, this is easy.  Someone needs to write this "standard" privacy policy.

If you want a general purpose system that allows users to create custom HTML pages (like a wiki) and add links to them from menus, footers, headers, etc., then I fear this will become an difficult-to-maintain mess.  I don't want to end up implementing a wiki within webtrees.  That's not its job.

**Comment by Amgine0** [comment]
The "Imprint" (Impressum, Imprimateur, masthead, etc.) is a legal requirement to appear on every page in certain countries - it declares who owns the site and how to contact them. Which means it probably needs to be configurable.

I would be happy to write a 'standard' privacy policy page text. I have some familiarity with Canadian, French, German, and US privacy requirements, and could probably pull together something very generic.

These pages could be implemented as .md text files? Better than a menu item like the FAQ imo, easily sanitized.

**Comment by mpwt** [comment]
I don't think there is a standard privacy policy text. Different countries different law. IMO an imprint and privacy policy page should be a simple html block to insert the correct text. F.i. in Germany does exist  some imprint generators to create the right text.

**Comment by Amgine0** [comment]
```markdown
#Webtrees Privacy Policy#

The software running this site collects some information about all visitors, primarily to improve the presentation of the site's content and the user's experience. Interacting with this software involves the use of cookies to temporarily store information on your device; use of the site implies acknowledgement and acceptance of these cookies. The software does not communicate this information with any third parties. Logs may be kept to assess website performance. 

Some sites using this software may implement audience assessing tools, which may gather further data about users and their interactions with the website. It is beyond the scope of this policy statement to address each unique installation.

#Genealogical data privacy#

The collection and collation of genealogical data for publication via the web is inherently an act of publication of personal and private data, and as such may be governed the privacy laws of the jurisdiction of this website. This software has the ability to conform to privacy laws, selectively limiting publication of the stored, collaboratively-developed genealogical content.

#Owner, access, and correction#

This site's contact and management are documented at the [Imprint](/link/to/imprint "$sitename: Imprint"). Please use the information there to request access or correction to the data presented within the site.
```

**Comment by fisharebest** [comment]
678a16c4e adds an example footer module which does this.

It contains a footer with a link to a page of information.
