### ISSUE TITLE
Editing the SUBM tag

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#921]
Somethimes I need to edit the SUBM tag of the GEDCOM. It would be great to be able to do this in the settings of the family tree. I alsways have to change it in the mySQL database :-(

Feature request: make a small editor for this tag in the settings of the family tree. Would be a great feature.

**Comment by fisharebest** [comment]
You can do this already.  Log in to the demo site as editor/editor and visit the page:

https://dev.webtrees.net/demo-dev/gedrecord.php?pid=SUBM

(Tip - you can find this page by typing the XREF of the submitter record into the quick search box at the top of the page)

Admittedly, the editor only lets you edit existing fields - not add new ones.  However, it gives the option to edit the GEDCOM data.

**Comment by fisharebest** [comment]
Tip: you can edit the `HEAD` record in the same way.
