### ISSUE TITLE
German translation for the values in QUAY tag

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#922]
In the QUAY tag (inside the sources) the German translations are correct, but not very clear how to use them.

Genealogy.net recomends this values:

0 = angenommen, geschätzt
1 = fragwürdig, fraglich
2 = abgeleitet, Sekundärquelle
3 = sicher, Primärquelle

The complete text for this is here:
http://wiki-de.genealogy.net/GEDCOM/QUAY-Tag

This texts would be more useful, because they are easier to understand.

**Comment by fisharebest** [comment]
Translations are managed at https://translate.webtrees.net

You can update all of the German translations there.

**Comment by mpwt** [comment]
Done. I have changed the german translation.
