### ISSUE TITLE
Most common surnames block is not showing correctly

### ISSUE THREAD

**Issue by mirono** [fisharebest/webtrees#923]
All the names are displayed with the width of the 3ed column of the table above it. See attached.
Version 1.7.4 on both Chrome and Firefox.
![capture](https://cloud.githubusercontent.com/assets/6016445/15067822/dd19c6bc-137b-11e6-9d36-5403b368b3ca.PNG)

**Comment by wooc** [comment]
Already fixed. Search forum.

**Comment by fisharebest** [comment]
This was the fix:

https://github.com/fisharebest/webtrees/commit/28941e3c677f7739a8b5dc01eb297ca0c5ad75a1

...or just wait for the next release :-)

**Comment by mirono** [comment]
Thanks (should have searched the closed issues as well, sorry)!
