### ISSUE TITLE
Googlemaps module bug

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#929]
With streetview enabled and setting the longitude for the centre of England as W1 which is returned as -1, when saving the streetview parameters something similar to the following error is generated (this one refers to sv_bearing but depending upon the edited values other fields can be in error)

> <path>\app\Statement.php:82 SQLSTATE[01000]: Warning: 1265 Data truncated for column 'sv_bearing' at row 1 #0 \app\Statement.php:82 PDOException("SQLSTATE[01000]: Warning: 1265 Data truncated for column 'sv_bearing' at row 1") #1 \app\Module\GoogleMapsModule.php:3282 execute([array]) #2 \app\Module\GoogleMapsModule.php:108 placesEdit() #3 \module.php:26 modAction('places_edit')

**Comment by fisharebest** [comment]
As per your earlier comment, the `slice(0,-1)` look bogus, and I don't know why they were added.

**Comment by ddrury** [comment]
Thanks for this, I removed the comment because the slice(0, -1) looked 
so flaky that I thought there must be something devious going on!

Regards
David
Please consider the environment before printing this e-mail



------ Original Message ------

**Comment by fisharebest** [comment]
Maybe at one time there were degree signs at the end of the lat/long which needed removing?

**Comment by ddrury** [comment]
Yeah - good idea.

BTW I've noticed we're not up to date with the latest maps api (the 
latest seems to require a key again) and I get lots of 404 errors on 
loading a map  - don't know if they're related.

When I get some time I'll have a look if you like.

Regards
David
Please consider the environment before printing this e-mail



------ Original Message ------
