### ISSUE TITLE
Feature Request: Mouse hover over delete icon in Shared Notes list

### ISSUE THREAD

**Issue by splitpoint** [fisharebest/webtrees#933]
When I hover the mouse over the delete-icon in the list of shared notes (/notelist.php), the cursor is still an arrow.

I think it would be more appropriate that it change to a link-cursor.

I use the default webtrees-theme.

**Comment by fisharebest** [comment]
Same applies to `repolist.php` and `sourcelist.php`.

I guess we need to change the `<div>` to either `<a>` or (preferably?) `<button>`.
