### ISSUE TITLE
Feature Request: Include INDI-number in "Individual"-report

### ISSUE THREAD

**Issue by splitpoint** [fisharebest/webtrees#934]
I hereby suggest to include INDI-number in the "Individual"-report (IndividualReportModule), so line 102 in "report.xml":
`<Text style="pageheader"><GetPersonName id=""/> </Text>`
... would look like this:
`<Text style="pageheader"><GetPersonName id=""/> </Text> <Text style="text">(ID: <GedcomValue tag="@id"/>)</Text>`
or similar

**Comment by fisharebest** [comment]
Not showing the XREF is a deliberate design decision.  See the [FAQ](https://wiki.webtrees.net/en/Frequently_Asked_Questions#How_can_I_show_the_GEDCOM_IDs_.28XREFs.29_in_webtrees.3F).

So, this change won't happen - sorry.

However, as you've seen, it is straightforward to modify the code yourself.
