### ISSUE TITLE
Feature Request: Individual report for all individuals

### ISSUE THREAD

**Issue by splitpoint** [fisharebest/webtrees#935]
It would be awesome to have a report that creates an "Individual"-page for all individuals in the current tree in the same report.

**Comment by fisharebest** [comment]
A tree with 1000 individuals would be considered small.
I know trees with 500,000 individuals.

Anything that does "all individuals" will be unusable on a tree of any reasonably size.

**Comment by splitpoint** [comment]
I see - that makes sense.
