### ISSUE TITLE
Misinterpreted translation in ClippingsCartModule.php

### ISSUE THREAD

**Issue by mpwt** [fisharebest/webtrees#937]
In ClippingsCartModule.php a translation string will not translated well: 

```
	public function getDescription() {
		return /* I18N: Description of the “Clippings cart” module */
			I18N::translate('Select records from your family tree and save them as a GEDCOM file.');
	}
```
It looks like a SQL command in English or German and is not translated (although a german translation exists):

![clippingscart_translation](https://cloud.githubusercontent.com/assets/16311627/15295743/36d7cfd2-1b92-11e6-8f42-8bcd9409f930.jpg)

**Comment by fisharebest** [comment]
Do you have the latest code?

A few weeks ago, my software development tools "auto-corrected" this for me - and I changed it back a few days later.

**Comment by mpwt** [comment]
No, I'm using 1.7.4. On your development demo I couldn't test it - there are no admin rights available. :)
I will try to test the latest dev on a local installation ... but there the german translation works only partially.

**Comment by fisharebest** [comment]
If you use the development code, you will need to either

* download the .MO file from the translation server
* create the .MO file using the command line `msgfmt -o language/de.mo language/de.po`

**Comment by mpwt** [comment]
Thanks. I found your changes on 16 April. Now I have changed the code of ClippingsCardModule.php in my webtrees installation **and insert the missing translation part to the de.mo of 1.7.4**. Now it works.
