### ISSUE TITLE
Convert a GEDCOM age string to localized text

### ISSUE THREAD

**Issue by mpwt** [fisharebest/webtrees#940]
Why this function doesn't works well for ages when only a year value is inserted (f.i. 66y)? In this case webtrees shows only "66" instead of "66 years". When I insert "66y 3m" it shows "66 years 3 months".

I think, the following function in FunctionsDate.php regulates this:

			function ($match) use ($age_string, $show_years) {
					switch ($match[2]) {
					case 'y':
					if ($show_years || preg_match('/[dm]/', $age_string)) {
					return I18N::plural('%s year', '%s years', $match[1], I18N::digits($match[1]));
					} else {
					return I18N::digits($match[1]);
					}
					case 'm':
					return I18N::plural('%s month', '%s months', $match[1], I18N::digits($match[1]));
					case 'w':
					return I18N::plural('%s week', '%s weeks', $match[1], I18N::digits($match[1]));
					case 'd':
					return I18N::plural('%s day', '%s days', $match[1], I18N::digits($match[1]));
					}
					},
					$age_string
				);

Is the if ... elso ... part in case 'y': too much?

**Comment by fisharebest** [comment]
This was the design.

If someone says their age is 54, then you know this means 54 years.

You would not (in English**), say "John died, aged 54 years".  You would say, "John died, aged 54".

It is only necessary to say years/months/days when the age is not years.

-----
** The may be different for other languages.  What language(s) do you use?

**Comment by mpwt** [comment]
Thanks. My prefered language is german.
![age_at_event](https://cloud.githubusercontent.com/assets/16311627/15439198/1934f888-1ed0-11e6-8172-ed5eb4b88dbe.png)
I understand what is the intention of the behaviour but 2 AGE is f.i. a data entry from a source and in my opinion it should look exactly like an age with years, months and days to see the diffence between age at event and a calculated age.

Could I use
```
case 'y':
return I18N::plural('%s year', '%s years', $match[1], I18N::digits($match[1]));
```
instead of
```
case 'y':
if ($show_years || preg_match('/[dm]/', $age_string)) {
return I18N::plural('%s year', '%s years', $match[1], I18N::digits($match[1]));
} else {
return I18N::digits($match[1]);
}
```
to display "year" or "years"?

**Comment by Amgine0** [comment]
When reading obituaries it is a common English practice to say "John died, aged 54 years," and often the number of months and days as well although the practice is changing, particularly so since about 2000. In my anecdotal experience the fully precise years, months, days seems to have peaked in upper-midwestern newspapers just prior to WWII, declined slowly until the 1980s when it became years only, and now they often skip reporting the age altogether.
