### ISSUE TITLE
Edit_interface.php/action=edit adds and move unintended gedcom rows

### ISSUE THREAD

**Issue by mpwt** [fisharebest/webtrees#941]
I was playing a little bit with a gedcom validator and found strange things (sometimes errors) in source citations inside my gedcom export. But I know that I have corrected some of this before I have imported last time. Problems I had with double 3 DATA parts inside the same source citation there after I had edited this event.

Now I have tested to reproduce them and discover at existing source citations (they I made with another program before I use webtrees) that when I edit an event entry with "edit_interface.php/action=edit" (click on pencil symbol) the raw gedcom have one row (3 QUAY after 2 SOUR) more and the 3 DATA is moved after 4 DATE:
before edit:
![before_edit](https://cloud.githubusercontent.com/assets/16311627/15450077/f05aae2c-1f91-11e6-9913-ec9650454508.png)
 after edit:
![after_edit](https://cloud.githubusercontent.com/assets/16311627/15450079/fcd8b2ac-1f91-11e6-92ce-7e350e62a3ae.png)

When I edit the same event with the raw gedcom editor (edit_inteface.php/action=editrawfact) the additional rows aren't there. I believe I found some code for this behaviour inside FunctionsEdit.php but I don't understand it at the moment ...

**Comment by fisharebest** [comment]
Can you post the original GEDCOM for this record, so I can try to reproduce your problem?
(I cannot copy/paste from a screenshot...)

**Comment by fisharebest** [comment]
I can confirm the problem.  It only happens when you enable "Use full source citations"

**Comment by mpwt** [comment]
> It only happens when you enable "Use full source citations"
Thats true. Sorry, I forgot to inform you about. 

But I want to see all possible field when I add a source citation and I use the DATE field every time but never QUAY. Actually when I select "no" I don't have a date field if I want to add a new source citation. Therefore (for me) I would need more options for this setting like "no", "quality", "date" and "both" instead of "no" and "yes" only. 

Next problem with the actually behaviour is that webtrees expects 3 DATA before 4 TEXT. If I have an old source citation from previous genealogical software with 3 DATA 4 DATE 4 TEXT and I edit the event and click save then webtrees change the order to 4 DATE 3 DATA 4 TEXT (see screenshots above) or insert a second 3 DATA before 4 TEXT. Last one is a gedcom error because the citation have too much DATA parts.

**Comment by fisharebest** [comment]
I'm pretty sure this fix is OK.  Can you test it for me.  Thanks.

**Comment by mpwt** [comment]
Great, it looks like it works. I tested it with the two possible source settings (no or yes) and an empty edit changes nothing now. Thanks a lot.

It would be great if webtrees could edit the order of gedcom rows from a source citation if someone edits the event like the blank "Add a source citation":
![addsourcecitation](https://cloud.githubusercontent.com/assets/16311627/15456219/d3ef23d4-2069-11e6-9914-c2878f528162.png)
The editor would see every times the same order of input fields. At the moment the input fields are ordered by the order of gedcom rows.

**Comment by mpwt** [comment]
The problem does not occure if I edit a source citation ... but if I add a new source citation now webtrees does insert the 4 DATE only without the 3 DATA row:
```
2 SOUR @S29@
3 PAGE (XXX)
4 DATE 06 JUN 2009 
```
instead of
```
2 SOUR @S29@
3 PAGE (XXX)
3 DATA
4 DATE 06 JUN 2009
```
