### ISSUE TITLE
Used language after signing out

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#943]
How can I set the language what webtrees uses after signing out? Where it shows up if I set the language in Control panel > Family trees > Manage family trees > Preferences > General > Language? As I see the used language after signing out is always English regardless of this setting. Am I wrong?

**Comment by fisharebest** [comment]
> How can I set the language what webtrees uses after signing out?

You can't.  It is different for every user.  webtrees chooses the language from the browser configuration.

If you set the browser to prefer Hungarian, then webtrees will show Hungarian.

> Where it shows up if I set the language in Control panel > Family trees > Manage family trees > Preferences > General > Language?

This is only used when the client does not choose a language.  Normally, this only applies to search engines.  

> As I see the used language after signing out is always English regardless of this setting. Am I wrong?

I guess your browser is configured to prefer English??

**Comment by tunandras** [comment]
Yes, you are absolutely right. The preferred language in my browser is English.
I just tried to set language used by webtrees for other members of my family. This means I can't. It depends on their browser's settings.
Thanks for your quick answer.
