### ISSUE TITLE
Inconsistency in alignment of webtrees messages

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#948]
Some of webtrees messages are left aligned others are centered. It would be better if they would be consistent in alignment. I prefer centered as "You have signed out." looks like.
If you agree please center the left aligned messages like "This individual does not exist or you do not have permission to view it." or "This individual has been edited. You should review the changes and then accept or reject them.", etc. (or align left the centered ones if you like that alignment better).

**Comment by tunandras** [comment]
I was very pleased in sight of fixing the inconsistency in alignment of messages and saw that they are all centered.

Thanks a lot! :-)

But there were some new behaviors...

I found--when changing a fact of or deleting an individual--the message and options to accept or reject changes migrated from **Individual's page** to **Home page** and **Pending change** window. 

Accepting or rejecting command is accomplished

- on **Home page**--and webtrees confirmed on the same page;
- in **Pending change** window--without confirmation.

Is that what you intended?

**Comment by fisharebest** [comment]
> But there were some new behaviors...

It is good to create a new issue for new problems.

If you add comments to issues that have been closed, it is unlikely that anyone will see them.

**Comment by tunandras** [comment]
All right, I understand. Thank you.

I repeated the comment in a new issue...
