### ISSUE TITLE
Bold links in a message

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#949]
It would be better if links would be exceptionally bold in "This individual has been edited. You should review the changes and then [**accept**](#) or **[reject](#)** them." webtrees message--just to better understand what administrator can do. (It was bold in Hungarian translation before--and I kept it.) If you discourage it, I'll make normal in Hungarian translation too. (The linked words are black in webtrees.)

**Comment by makitso** [comment]
Is this what you mean?
![selection_014](https://cloud.githubusercontent.com/assets/5147603/15651598/6fa94bee-2635-11e6-800c-21ade85956b7.png)

**Comment by tunandras** [comment]
Absolutely! Do you like it? Do the rules permit that?

Did you increase the font size too?

**Comment by makitso** [comment]
The theme .css files would need to be changed to bold the accept  and reject words and increase the font size.

.ui-state-highlight a {font-size: 16px; font-weight: bold;}

**Comment by fisharebest** [comment]
IMHO, 
Bold text - yes
Larger text - no

**Comment by makitso** [comment]
That's  kind of what I thought,  will commit the changes later today.

**Comment by tunandras** [comment]
Hi Greg & Rob,

Is it regular to say thanks in webtrees practice?
That was exactly what I thought. Thank you very much.

Sorry, if it's not allowed to leave a comment after an issue is closed.

András

**Comment by fisharebest** [comment]
> Is it regular to say thanks in webtrees practice?

Of course it is allowed.  We are a friendly project!

> if it's not allowed to leave a comment after an issue is closed.

Yes, this is also allowed.

Sometimes a fix is incomplete, and we must re-open an issue.
