### ISSUE TITLE
Suggestion to change "Minimum number..." field's explanation string

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#950]
According to the last module changes--on **Family trees > Manage family trees > Preferences** page in **Names** block's **Minimum number of occurrences to be a “common surname”** field's explanation instead of
This is the number of times that a surname must occur before it shows up in the Common Surname list on the “Home page”.
would be better something like this:
This is the number of times that a surname must occur before it shows up in the “Most common surnames” list at the bottom of Statistics on “Home page” or on “My page”—if showing of Statistics block is set by administrator or user.

**Comment by fisharebest** [comment]
This logic has been changed.

There is now a simple option - "Number of surnames".

...actually, it is not completely simple...

If a surname has variants, then all the variants are shown.  Therefore you can ask for 10 names, but see 12.  This is the same logic that is used for the top-surnames block.

**Comment by tunandras** [comment]
> There is now a simple option - "Number of surnames".

Yes, I see it in the "Configure -- Top surnames" window. I agree, that's all right.

But I'm sorry to lose all name setting options in preferences window because they affected the number of surnames in "Most common surnames" in Statistics module. Is the number of names there always 10 from now? Since you can't set it. Or can you? When I wrote this suggestion, I thought you just wanted to separate "Top surnames" block's settings from "Most common surnames" block's settings. Maybe I was wrong...

**Comment by fisharebest** [comment]
>  Is the number of names there always 10 from now? Since you can't set it. Or can you?

Yes - you can set the number!

In the configuration for the block, there is a setting "Number of surnames".

I moved this to the end because the surname list is shown at the end.

**Comment by tunandras** [comment]
Oh yes, thank you very much, I found it now! :) You worked hard on it and I didn't think to look for it in "Configure -- Statistics" window. I was searching in its old place... :(

**Comment by tunandras** [comment]
The field for "Number of surnames" label in "Configure -- Statistics" window has a feature. It is automatically validated by HTML5. If you leave it empty and click the "save" button, it says in English: "Please fill out this field.". It doesn't help, if you choose your own (e.g. Hungarian) language for displaying pages in the browser, the error message remains in English. Now I see two options to handle this problem:

1. You can specify not to validate with attribute [novalidate](https://www.w3.org/TR/html5/forms.html#attr-fs-formnovalidate) and [formnovalidate](https://www.w3.org/TR/html5/forms.html#attr-fs-formnovalidate).
2. The message can be overwritten with jQuery (here is a Turkey [example](http://jsfiddle.net/zpkKv/2/) -- found at a [community forum](http://www.silverstripe.org/community/forums/form-questions/show/36191#post332675)).

What are you planning? Do you want to deal with it?

**Comment by fisharebest** [comment]
The is a browser error message.

You are using the English version of Firefox.
If I install the Hungarian version of Firefox, I see the messages in Hungarian.

**Comment by tunandras** [comment]
That's true--I didn't install that, and seems it doesn't help to choose a preferred language. Sorry and thank you very much.
