### ISSUE TITLE
Nickname in the name

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#953]
In my installation if I add a nickname:
![nickname_in_nickname_input](https://cloud.githubusercontent.com/assets/15856891/15646900/9f9935fa-2660-11e6-865e-25b18839b9f2.png)

the individual's name starts with it within a quotation mark pair (and the "Nickname" row correctly appears):
![with_nickname](https://cloud.githubusercontent.com/assets/15856891/15646991/4166ca82-2661-11e6-8bd2-7a92b60e9f01.png)
however, it is not the most important name. I'm really inexperienced. Is that behavior the expected? The correct location of a nickname is really in the front of a name?

In my opinion it would be better to put it to the end--separated by a comma. If I do so (by editing the "Name" field):
![nickname_in_name_input](https://cloud.githubusercontent.com/assets/15856891/15647170/471b7706-2662-11e6-954d-f382633b183f.png)

the result name will contain the nickname as I preferred, but incorrect way--that is the nickname row disappears and for example if I change the language, the quotation mark remains (does not changes to that which belongs to the selected language):
![without_nickname](https://cloud.githubusercontent.com/assets/15856891/15648223/57f967e8-2669-11e6-9faf-a95fac8abdd7.png)

Let's take another example. The world uses Clinton's name with his nickname this way: Bill Clinton. It follows the general rule for names but if we would show his name in webtrees, his name would be William Jefferson Clinton, “Bill”. Isn't it true? Or am I wrong?

**Comment by fisharebest** [comment]
1) The nickname is added between the given names and surname.  e.g.

William Jefferson "Bill" Clinton

I guess this conflicts with the Hungarian surname-first rule.

2) I do not like this automatic behaviour.  If the user wants "Bill" in the name, they should add it.  They can then choose between

William Jefferson "Bill" Clinton
William "Bill" Jefferson Clinton
William Jefferson Clinton "Bill"
etc.

**Comment by tunandras** [comment]
> I do not like this automatic behaviour. If the user wants "Bill" in the name, they should add it.

I agree. That is what I tried to do. But this method has the shown unwanted consequences:

![without_nickname](https://cloud.githubusercontent.com/assets/15856891/15649171/c72804c0-266f-11e6-91ee-0ab51f10a5bd.png)

the "Nickname" row disappears (that is not too big problem) and the Hungarian style quotation mark remains though the English language is selected (this is not so nice) but of course I can live with them... :)

**Comment by fisharebest** [comment]
GEDCOM 5.5 introduced the `NICK` tag, and said that the nickname should also be included in the `NAME` tag in double quotes.

GEDCOM 5.5.1 changed this, so that the nickname should NOT be included in the `NAME` tag.

IMHO, we should follow the latest specification.

If we are going to remove this "auto-magic" feature, we should do it at a major version change, such as 2.0.0

**Comment by fisharebest** [comment]
The nickname is now always added to the end of the name - if it is not present.

e.g. `aaa /bbb/ ccc` becomes `aaa /bbb/ ccc "nickname"`

This should work with all name traditions.
