### ISSUE TITLE
Messages when an individual is deleted

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#954]
If I delete an individual--using **Edit menu > Delete** menu item--the next messages appear:

![after_deletion1](https://cloud.githubusercontent.com/assets/15856891/15669521/ff3daf7a-2720-11e6-8398-84f9af68adce.png)

All three messages (1. pending changes, 2. link has been deleted, 3. you should accept or reject) are correct by their content (I don't mention alignment now). Please note, the third message says: the individual has been deleted.

If then I **accept** the deletion (that is, approve all changes) the next messages appear:

![after_deletion2](https://cloud.githubusercontent.com/assets/15856891/15669540/10638ac2-2721-11e6-98c3-09ccbb4d23ec.png)

​In my opinion to show №1 and №3 messages in this phase is not needed.
№1: I approved all changes in wain, some pending changes still remained, though I think, there could not be pending changes any more (just because of this deletion; if there were no other changes).
№3: The administrator probably knows that the (just deleted) individual does not exist. It's not necessary to warn him. (Further problem [for me] that the warning remains after refreshing the page.)

№2: Since we know that the action was deletion (see third message on upper image) the text of this message could be
"The deletion of “Kiss Béla” have been accepted."
I think this message makes more sense. (I wouldn't call the delete operation "changes" to the individual.)
​
What do you think? Is that right? Or, is №2 a general message--used after other actions too--and it's not so important to create an own acknowledgement message for deletion?

**Comment by fisharebest** [comment]
There are two types of message:

(1) Messages that are shown once.  For example, a confirmation that a record was deleted.
(2) Messages that are shown every time you visit the page.  For example, a message that a record has pending changes.

FYI - these are created in different parts of the code.  This explains why (1) are centred and (2) are left-aligned (see #948).

Note that the "Pending changes link" and the "You should review the changes" links are only shown to users who have the role moderator/manager/administrator.  Users with the role editor will not see them, as they cannot accept/reject the changes.

> №1: I approved all changes in wain, some pending changes still remained, though I think, there could not be pending changes any more (just because of this deletion; if there were no other changes).

You approved all changes to this record.  But there are other records with pending changes.

> №3: The administrator probably knows that the (just deleted) individual does not exist. It's not necessary to warn him. (Further problem [for me] that the warning remains after refreshing the page.)

After we delete a record, we have two options.

(1) stay on the same page - with a message that the record has been deleted.
(2) show a different page.

Currently, we choose (1).  For (2), we must choose a  page.  But which one?

> №2: Since we know that the action was deletion (see third message on upper image) the text of this message could be "The deletion of “Kiss Béla” have been accepted." I think this message makes more sense. (I wouldn't call the delete operation "changes" to the individual.)

I agree.  It would be clearer to say something like "Kiss Béla has been deleted".

**Comment by tunandras** [comment]
> After we delete a record, we have two options.

> (1) stay on the same page - with a message that the record has been deleted.
> (2) show a different page.
> 
> Currently, we choose (1). For (2), we must choose a page. But which one?

That's a good question. I was wondering when I wrote my comments. I think "My page" with a message that the record has been deleted would be appropriate--as it happens when user logs (signs) out: they get to "Home page" with "You have signed out." message.
