### ISSUE TITLE
Is there some inconsistency in "Pending changes" window?

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#955]
On individuals' web pages for changes we use phrases "accept" and "reject". In my opinion, if we want to be consistent, we should use the same words in "Pending changes" window as well. But if we decide to use there different ones (namely "approve" and "undo") don't we have to use them consistently? In that case do the word "accept" appropriate in this window?

![pending_changes_window](https://cloud.githubusercontent.com/assets/15856891/15670925/36178848-2728-11e6-9cc6-a1c1fcfd9fc0.png)

Do I misunderstand something? Or if we say yes to all changes at once, that is approving, and we accept, if we say yes to changes one after one? Is it a question of interpretation--what is unknown for me?

Correction: this and [#954](https://github.com/fisharebest/webtrees/issues/954) suggestion came up when I tried out how bold links look like (I believe bold helps a lot) and as my last questions show I think some of my remarks are because of my poor English: sorry, I'm sure I don't feel enough the finesse of the language.

**Comment by fisharebest** [comment]
>  if we want to be consistent, we should use the same words

I agree.  We should be consistent.
These should be "accept" and "reject".

**Comment by fisharebest** [comment]
It seems that there are many other references to "approve" and "undo".

**Comment by tunandras** [comment]
Yes, you are right... however not too much, mostly "Not approved by an administrator", "Approve all changes"; and as I see just `edit_changes.php` for "undo".
Sorry, I didn't check it. :(
