### ISSUE TITLE
Check for errors - ASSO link to HUSB/WIFE not recognised

### ISSUE THREAD

**Issue by thomas52** [fisharebest/webtrees#957]
A check for errors @ www.adkins.ws shows among others:
INDI I5978 has a FAMS link to F2324. F2324 does not have a link back to I5978.
This "error" appears to result from an ASSO in the MARR record
1 MARR
2 ASSO @I5978@
3 RELA Mary Ann "Polly" Tankersley is the first cousin of John Roy Tankersley
I would like a means to "flag" or hide this error (unless there is in fact an error that requires correction with advice on how to correct.)
[gedcom-error.zip](https://github.com/fisharebest/webtrees/files/298161/gedcom-error.zip)

**Comment by mpwt** [comment]
All person link exists in your ged file:
0 @F2324@ FAM
1 WIFE @I5978@
1 HUSB @I5977@
1 MARR
2 DATE 10 SEP 1801
2 PLAC Port Royal, Caroline, Virginia, USA
2 ASSO @I5978@
3 RELA Mary Ann "Polly" Tankersley is the first cousin of John Roy Tankersley

But the ASSO tag is not allowed here. I believe that is not a webtrees error than a incorrect use of this tag. Where did you insert this tag?

Try to use it within individual part:
0 @I5978@
...
1 ASSO @I5977@
2 RELA Mary Ann "Polly" Tankersley is the first cousin of John Roy Tankersley

and the same for @I5977@ ith ASSO @I5978@

**Comment by fisharebest** [comment]
> But the ASSO tag is not allowed here. I believe that this is not a webtrees error than an incorrect use of this tag. Where did you insert this tag?

Other applications (and old versions of webtrees) create "2 ASSO" tags.

New versions of webtrees create "2 _ASSO" tags.  See http://wiki-de.genealogy.net/GEDCOM/ASSO-Tag

**Comment by thomas52** [comment]
As shown: in the MARR record.  I wanted to shown an individual married a
1st cousin to explain the name similarity.
If the ASSO tag is not allowed here, then that would certainly explain why
it is shown as an error.
My understanding was it is acceptable.
A2 Extension to Family Records

For the description of relations from a family to an individual (e.g.
witness of marriage) the tag _ASSO is used. Beside the assignment to the
family record for _ASSO apply the same rules from the standard as for ASSO.
For programs with fixed data fields for such relations it is recommended to
use following text behind RELA:

2 RELA Witness_of_Marriage
2 RELA Witness_of_Civil_Marriage
2 RELA Witness_of_Religious_Marriage

*Source: http://wiki-en.genealogy.net
<http://wiki-en.genealogy.net>**/GEDCOM/ASSO-Tag*


​Should I have used "_ASSO"?​

*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*"If you would not be forgotten, as soon as you are dead and rotten;
 Either write things worthy of reading, or do things worthy of writing."
 -- Benjamin Franklin, May 1738*

*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Comment by mpwt** [comment]
> Should I have used "_ASSO"?
Yes, please test it (or use an inline NOTE to store this additional information). After you can check for errors again.

**Comment by thomas52** [comment]
No joy.
"1 MARR
2 DATE ABT 1841
2 PLAC Plattsburgh, Clinton, New York, USA
2 _ASSO @I1151@
3 RELA William Ross Banker is the first cousin (1x removed ascending) of
Ruth Banker"
...returns:
INDI I1151 <http://www.adkins.ws/gedrecord.php?pid=I1151> has a FAMS link
to F409 <http://www.adkins.ws/gedrecord.php?pid=F409>. F409
<http://www.adkins.ws/gedrecord.php?pid=F409> does not have a link back to
I1151 <http://www.adkins.ws/gedrecord.php?pid=I1151>.

*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*"If you would not be forgotten, as soon as you are dead and rotten;
 Either write things worthy of reading, or do things worthy of writing."
 -- Benjamin Franklin, May 1738*

*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Comment by fisharebest** [comment]
`2 ASSO` / `2 _ASSO` shouldn't make a difference here.

The underscore version is prefered at level 2, but both should work equally.

**Comment by fisharebest** [comment]
I have found the bug.  The error checking code assumes there will only be one type of link between any two records.

You have two types of link between the family and the individual. WIFE and ASSO.
Only the final one is being considered.

It's not a quick/easy fix, so it won't happen before the next release.

As a temporary workaround, edit the family using the raw GEDCOM editor, and move (drag/drop) the MARR record before the HUSB/WIFE records.

**Comment by thomas52** [comment]
Not a problem for me, as long as you are aware.

**Comment by mpwt** [comment]
I don't think this is abug of webtrees. Every assoziation have two directions: from the first person / marriage to another person and from the another person back. In the example above the wife is the first cousin of her husband but also the husband is the first cousin of his wife. This link back is missing. Therefore the ASSO link have to insert at this persons twice. Please test to insert the back assoziation and check for errors again.

For the example above I would use the ASSO tag between the persons and not between the marriage an one of this persons. I believe that webtrees than check automatically for the back link. Otherwise this is a assoziation between persons ... A assoziation between a marriage and other persion are whitnesses of the marriage (civil or religious).

**Comment by fisharebest** [comment]
> I don't think this is a bug of webtrees

It is a bug.  The code that checks links only stores one link between each pair of records.

So, it can see either the WIFE or the ASSO - but not both.
Therefore it thinks the WIFE does not exist, and reports an error.

**Comment by mpwt** [comment]
Ok, I have tested it. The gedcom error message exists only if a partner of the marriage is assoziated. When I assoziate another person (f.i. as witness) no error is shown. It is not relevant if _ASSO is on level 1 or 2 (beside individual or below an event).

Interesting is that if I use_ASSO on level 2 below the marriage the text shows the relationship of the person to the spouses. When I use it on level 1 webtrees shows nothing (not the RELA information like witness nor the familiar relationship).

Thanks for patience. :)
