### ISSUE TITLE
Duplicate "Add a new associate" entry on edit family event

### ISSUE THREAD

**Issue by mpwt** [fisharebest/webtrees#959]
When I edit a family event like marriage I found a duplicate entry for "Add a new associate". Both links does the same and adds 2 _ASSO. Is this right? When I edit a individual event I see this entry only once.

![add_a_new_associate](https://cloud.githubusercontent.com/assets/16311627/15806479/8a2c95de-2b44-11e6-87a8-712e0304cad3.png)

**Comment by fisharebest** [comment]
This is because there are traditionally two witnesses at a marriage.

**Comment by mpwt** [comment]
Ah. Thanks. But ... :) ... I have to insert it one by one and can use the same link again. It is similar to notes, shared notes and so on - I can add more than one and I have to use the add link again and again.

(Otherwise I am missing the possibility to add the reverse link from the associate to the person or event automatically. For instance the associate is a witness of a marriage - I have a link from the marriage to this person but from this associated person back to the event I haven't a link.)
