### ISSUE TITLE
Issues with chart blocks

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#963]
I've set up a pedigree chart block on the homepage, but encounter some issues.

Loading of the initial pedigree goes well, but clicking on one of the arrows to get the next generation gives strange results.

Instead of one new generation, you always get 3 generations at once, despite of the fact the ajax call asks for 1 (the querystring in the ajax get request: 
../hourglass_ajax.php?rootid=I3613&**generations=1**&type=asc&show_full=1&show_spouse=0)

I think this is caused by the fact in the HourglassController the minimum value of generations is set to 2. When calling 1 it gives the default value of 3 instead:

`$this->generations = Filter::getInteger('generations', 2, $WT_TREE->getPreference('MAX_DESCENDANCY_GENERATIONS'), 3);`

A second issue:
In the block configuration I've set 'show details' to 'no' (which is the default I think). The data-parms attribute in the anchor tag shows the correct value: asc-0-0. Despite of that the ajax get request sets the show_full parameter to 1 (see above).

The request is generated from the setupJavascript function in the HourglassController. The current code shows: `jQuery('#td_'+id).load('hourglass_ajax.php?rootid='+ id +'&generations=1&type='+parms[0]+'&show_full='+(parms[1] ? 1:0) +'&show_spouse='+(parms[3] ? 1:0)`.

When changing the part `&show_full='+(parms[1] ? 1:0)` to `&show_full='+(parms[1] === 1 ? 1:0)` the parameter is formed correctly, but I can't figure out why because the original code seems ok (but I bet you can ;)).

I've tested the above in the demo with the same results.

**Comment by JustCarmen** [comment]
Just found another issue. No lines before empty blocks:

![6-6-2016 09-48-30](https://cloud.githubusercontent.com/assets/5641963/15815262/5245a218-2bcc-11e6-84d2-47784d0bf38c.jpg)

**Comment by fisharebest** [comment]
> A second issue:

> Just found another issue.

It is easier to manage issues when each github issue contains only one problem...

**Comment by fisharebest** [comment]
> When changing the part `&show_full='+(parms[1] ? 1:0)` to `&show_full='+(parms[1] === 1 ? 1:0)` the parameter is formed correctly, but I can't figure out why because the original code seems ok (but I bet you can ;)).

`parms[1]` is a string.
`parms[1] === 1` is always `false`
`parms[1] === 1 ? 1:0` is always `0`

`show_full` is a checkbox - and has two values: checked or not sent.

We need three values: checked, unchecked and not-sent.

For this reason, we use some (untidy) code "3 state checkbox" which includes an extra "GUI-only" field.  I guess this URL should also set that.

**Comment by JustCarmen** [comment]
`It is easier to manage issues when each github issue contains only one problem...`

Sorry, it was the same chart block ;). But since you've have given an answer regarding the second issue I've split off the first and the third to two new issues.

**Comment by fisharebest** [comment]
I guess we can close this one now...

**Comment by JustCarmen** [comment]
> I guess we can close this one now...

I'm afraid not. This thread is somewhat confusing because it contains multiple issues (my mistake). I'd split up this thread afterwards with one remaining issue in this thread, which is the issue regarding the 'show details' option.

In the block configuration panel when you set the 'show details' option to 'no', the pedigree starts correctly in compact mode, but as soon as you click on one of the arrows the next generation comes in in full mode which is not correct. The next generation should open in compact mode as well.

**Comment by fisharebest** [comment]
Can you create a new issue for this?  Thanks.
