### ISSUE TITLE
Possible problem with Fix #876 - chartcontroller

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#964]
With option "show private relationships" set to hide from everyone - I can't see (for example) my own pedigree

**Comment by fisharebest** [comment]
Isn't this to be expected?  You are living/private.  If you hide your relationships, then we cannot see your parents.

**Comment by ddrury** [comment]
I understand that logic but isn't it going to extremes when I can't see my own stuff

**Comment by wkitty42** [comment]
i think agree with @ddrury in that you should always be able to see your pedigree... direct descendants as well if they are also currently blocked...

**Comment by fisharebest** [comment]
OK - I really don't understand the problem.

You want to do two things:

a) hide private relationships
b) show a chart that includes private relationships.

If you want to a chart to include private relationships, you must enable them...

Perhaps give an example.

**Comment by fisharebest** [comment]
> Perhaps give an example.

bump - @ddrury 

I don't know what behaviour you are seeing, what configuration you have, etc.

AFAICT, you have configured webtrees to hide private relationships, then you log out, and can no longer see private relationships - which is how things are designed...

**Comment by ddrury** [comment]
I'm logged in (as Admin), option set to hide private relationships, attempt to view my pedigree (where I'm the only living person) and get 'This individual does not exist or you do not have permission to view it'

**Comment by fisharebest** [comment]
Drat - it would have been good to have fixed this before yesterday's release :-(

**Comment by ddrury** [comment]
Sorry - should have responded sooner ;-(
