### ISSUE TITLE
Layout changes in different areas

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#965]
Please remove the dashes on the end of text lines (where the place names are missing) in Families tab and on the top in main area between the year of birth and the individual's age, if the individual is alive on individual's page, in Interactive tree's boxes, in boxes on family representations, etc. (as you did in changes in GitHub [Family tree statistics - layout](https://github.com/fisharebest/webtrees/tree/d93f11b54705fec36138c6e97eb7d00c55354c23)).

Some examples:

**Individual's page Families tab**
![individual](https://cloud.githubusercontent.com/assets/15856891/15849286/09f17f8e-2c92-11e6-989c-36b6bd55b2c2.png)

**Year of birth**
![year_of_birth](https://cloud.githubusercontent.com/assets/15856891/15849324/3264905a-2c92-11e6-91a6-5b130097c651.png)

**Interactive tree**
![interactive_tree](https://cloud.githubusercontent.com/assets/15856891/15849341/421854f0-2c92-11e6-8c8e-ee133e5ed1f7.png)

**Family representation**
![family](https://cloud.githubusercontent.com/assets/15856891/15849354/4ecd88fa-2c92-11e6-906b-d707183947e1.png)

**Comment by tunandras** [comment]
Sorry, the last one is a bad example. This would be better:

![family](https://cloud.githubusercontent.com/assets/15856891/15858999/7b73c802-2cc3-11e6-95ca-bec106af0716.png)

**Comment by tunandras** [comment]
Yesterday evening you were working very hard. I couldn't imagine for example how could you amend the translations in languages seem like Burmese...

But sorry, there remained some areas where the text lines still ends with dashes.

The individual's page looks much better, but unfortunately there are in Families tab in facts' lines as in the sidebar (what sorry, I didn't notice earlier), and in the main line between the year of birth and the individual's age.

![individual_page](https://cloud.githubusercontent.com/assets/15856891/15982768/84ca742a-2f91-11e6-8e2e-4ed3d626ea80.png)

As Wikipedia don't use dashes after year of birth (true, they write the word "born"...)

![year_of_birth](https://cloud.githubusercontent.com/assets/15856891/15982822/f4075c3a-2f92-11e6-9853-78578c7f0474.png)

but look at this strange example:

![not_born](https://cloud.githubusercontent.com/assets/15856891/15982827/0ded788c-2f93-11e6-9d6e-f2c4228e4ed8.png)

and some remained in the interactive tree too:

![interactive_tree](https://cloud.githubusercontent.com/assets/15856891/15982860/3b7e3056-2f94-11e6-87c7-024a1a05ec5a.png)

If it's possible, please handle these too.

**Comment by fisharebest** [comment]
We use the dashes for many things.

The code I fixed was the dash between the attributes for a fact: value, date, place.  e.g.
> Occupation: Farmer - 1920 - Berlin

We also use them to indicate a date range.  For example, "1910-1970".  If only one date is known, then we must keep the dash.  For example, "-1910" means died in 1910 and "1910-" means born in 1910.
