### ISSUE TITLE
Suggestion to change source phrase “My page”

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#968]
I suggest to change **“My page”** to **“My pages”** in [#309](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=cf3d03fb2bd243417622a587e92723ef) Weblate source string, since that is the correct name of the menu.

Otherwise I don't understand why we enclose phrases "Home page", "My page", "Request a new user account", etc. in quotation marks, while some are without them (and there are differences in spelling). These are for instance:
control panel [#2939](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=e99162f669d64f9a57cd4edcffe3c607)
favorite pages [#999](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=7f64aa84380c26a75ec12869516c601e), [#1000](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=9e731e9d7591cbf662db65c54aeb231f)
administration page [#1424](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=3c2cb09cc0ca44573b5489473ec27909)
Individual pages [#2427](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=3403aa024e554166a2cf9c69f9c7775f)
individual page [#2464](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=9c0ccd090862afc25af66409f377aadc)
Details page [#2631](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=14a5b1eaec3695aff2262bb3b7d9a652)
Individual page [#2820](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=ef3f560f84f204eeba1368c748a5490e), [#2821](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=588050fd02bcdb998a8f3149baf315b1), [#2822](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=75be219a0a035fac0578ac24d8365cf4)
individual’s page [#3011](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=06d9ea556df4b4a6a558ba95de70506c)
sign-in page [#3084](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=ed77e7d44fb501ab6435c3f252aded3e)

The [#2427](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=3403aa024e554166a2cf9c69f9c7775f) is the most extreme string. It is in English: "Show hit counters on Portal and Individual pages." and in Hungarian: "Látogatószámláló feltüntetése a „Honlapon” és a Személyoldalakon."
One is between quotation marks while the other is not. In the translation I replaced the word "Portal" with phrase "Home page" and to be consistent, I enclosed it in quotation marks.

**Comment by fisharebest** [comment]
Thanks for all of these reports.

It is easy for a native speaker to become "blind" to these errors.

I will probably wait until after the 1.7.5 release.  This will give translators time to update them before 1.7.6

**Comment by tunandras** [comment]
You are welcome. :-) Of course I promise, I will inform you later, if I meet something more.

**Comment by fisharebest** [comment]
> I don't understand why we enclose phrases ... in quotation marks

We use quotation marks when we are talking about the word, rather than the concept.

> Cheese comes from milk.
> "Cheese" comes from the latin word caseus.

We also use them for the names of things when a sentence would be ambigous.

> This is shown on my page.
> This is shown on "my page".

**Comment by tunandras** [comment]
> We use quotation marks when we are talking about the word, rather than the concept.

Yes, that's clear but I think when we use capitalized text in webtrees (not at the beginning of a sentence) that is not ambiguous any more. And as I see there are object names enclosed in quotation marks while others not. Or is it just my bad memory?

**Comment by fisharebest** [comment]
I wonder if italic text would be more helpful.  e.g.

> This is shown on the _facts and events_ tab on the _individual_ page.

We would need to use **emphasis**, rather than **italic**, and not all languages use italic.  e.g. chinese, arabic, etc.

`This is shown on the <em>facts and events</em> tab on the <em>individual</em> page.`

**Comment by tunandras** [comment]
That's true. Bold is preferably used.

Although recently we started to use bold to emphasize invisible links (I'm trying it on one page too just now).

**Comment by fisharebest** [comment]
There are lots of separate issues here.  The final one is now #1041
