### ISSUE TITLE
A lot of occurrence of word "new" in translations

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#971]
Why do I see so many occurrences of word "new" in the translations where the English text contains "add"--while there is no "new" in the source? Not just in Hungarian translation ("új"); I see it in French ("nouvel/nouvelle") and in Russian ("новый/новая/новое") too. Here are some examples:

"Add a media object"
"Ajouter un nouvel objet média"

"Add a mother"
"Új anya felvétele"

"Add a name"
"Добавить новое имя"

"Add a restriction"
"Ajouter une nouvelle restriction"
"Új korlátozás felvétele"
"Добавить новое ограничение"

"Add a son or daughter"
"Ajouter un nouveau fils ou nouvelle fille"
"Új gyermek felvétele"
"Добавить нового сына или дочь"

and so on, and so on to infinity... Nowhere "new" in the English strings and nearly all of the translations contains it (not consistently)... Is it because of the history of webtrees? Did originally the source strings contain the word "new" when adding something or somebody, and later--after removing them--the translators didn't perform these changes? Shall I take out that plenty "new"? A lot of them are not necessary.

**Comment by fisharebest** [comment]
> Is it because of the history of webtrees? Did originally the source strings contain the word "new"

Correct.

If the English text is changed, the translation is lost.  `Create a XXX` and `Create a new XXX` are different messages.

So, when the English text recieves a very minor change that does not affect the meaning, I will sometimes copy the old translations to the new text.

**Comment by vytux-com** [comment]
Wouldn't the correct procedure in that case would be to also set the string as fuzzy so that the translators can verify and update if needed?

**Comment by fisharebest** [comment]
> Wouldn't the correct procedure in that case would be to also set the string as fuzzy

You are right.

Next time...
