### ISSUE TITLE
Suggestion to replace phrase "Lost password request"

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#974]
If you click on "Forgot password?" link in the "Sign in" block the form opens and the outdated string "Lost password request" ([#1616](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=cf2b0d81a8700ea5cce5dc37fe4b570a)) appears (recently we don't lose passwords--we forget). It would be better instead something "Forgotten password request" or simply the much better "Password request" title. (Or you use the--forget and lose--phrases as synonyms?)

If you think there is something to explain (I think), you could put there a clickable circled question mark ![question_mark](https://cloud.githubusercontent.com/assets/15856891/15918113/a6e384f0-2e03-11e6-83eb-847ae2f91c6b.png) and help user in a small description to know what is this about, when it used, what happens step by step etc.

**Comment by fisharebest** [comment]
I think we should keep "Lost password request" as the subject for the email that is sent.

**Comment by makitso** [comment]
I  would agree with keeping the existing language.
