### ISSUE TITLE
Showing flags

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#975]
Would you like to show flags--set in Google Maps™ Geographic data window--on individual's page in Facts and Events tab beside country and state names or in the Google Maps™ tab on the map?

![no_flag_in_map](https://cloud.githubusercontent.com/assets/15856891/15918329/f575f6b4-2e05-11e6-9f25-255a383e67d2.png)
Events in two countries--without flags...

Are the flags just for administrator? 

![flag_in_geographic_data_window](https://cloud.githubusercontent.com/assets/15856891/15918337/0c12cf6e-2e06-11e6-9c55-40f819c8c7f4.png)

Or are they shown somewhere else not just in Google Maps™ Geographic data window that I can't see in my installation?

**Comment by ddrury** [comment]
It already works - see attached. But be aware that there can be no subordinate place elements below the element for which the flag is set. So in the attached image the place is Westmorland, England for which a flag is assigned, however if the place was for example Whitehaven, Westmorland, England then the default marker will be shown as no flag is set for that place.

![googlemaps_flags](https://cloud.githubusercontent.com/assets/104515/15946597/6cf813aa-2e8f-11e6-870b-93512ab7a3cf.png)

**Comment by tunandras** [comment]
> But be aware that there can be no subordinate place elements below the element for which the flag is set.

Thank you very much for your help. Yes, indeed. That was my mistake.

![with_flag_in_map](https://cloud.githubusercontent.com/assets/15856891/15951983/539cebbe-2ebd-11e6-9742-24ebf679eecc.png)
The flags belong to a higher level.

This means you have to make a compromise, because (smaller) cities usually doesn't have flags...

**Comment by tunandras** [comment]
> But be aware that there can be no subordinate place elements below the element for which the flag is set.

Thank you very much for your help. Yes, indeed. That was my mistake.

![with_flag_in_map](https://cloud.githubusercontent.com/assets/15856891/15952429/fdf26b9a-2ec0-11e6-9972-84932ec94f53.png)
The flags belong to a higher level.

This means you have to make a compromise, because (smaller) cities usually don't have flags...
