### ISSUE TITLE
The "Sign out" name would be better

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#976]
If a user selects "Customize this page" item in "My pages" menu on "My page" window, they can set "Sign in" block in the "Change the “My page” blocks" three pane window. As a result it appears on "My page" but turned to "Sign out".

Since "My page" is seen only after signing in, that block is really a "Sign out" block. Although the description of it "An alternative way to sign in and sign out.", actually the user never meets it as "Sign in" block. (Just an administrator can set "Sign in" block--and only from "Home page" window in the "Change the “Home page” blocks".)

The suggestion: the name of the block in "Change the “My page” blocks" as on "My page" might be better "Sign out" with the description "An alternative way to sign out." and, in "Change the “Home page” blocks" it would be for example "Sign in/Sign out" or "Sign in/out" (I like second better but that doesn't matter) with the original description "An alternative way to sign in and sign out.".

**Comment by fisharebest** [comment]
This block is normally used on the home page - and was designed for sites that do not have the standard header.  For example, sites with custom themes or sites that are embedded in other sites.

Here, it really is the sign-in block:

The name is shown as "sign in" if you are signed out.
The name is shown as "sign out" if you are signed in.

**Comment by tunandras** [comment]
> The name is shown as "sign in" if you are signed out.
> The name is shown as "sign out" if you are signed in.

Yes, of course, you are right. Not that was my problem. Sorry, I couldn't explain with my poor English. Anyway, sometimes a picture says more than thousand words. I tried to speak about this window, and the emphasized phrases in it:

![change_my_page_block](https://cloud.githubusercontent.com/assets/15856891/15983289/9e3efd3e-2fa2-11e6-9807-f311f5c71a7f.png)

This block appears  on "My page"--only after signing in--and there it can't be other than "Sign out"... so, that's why I wrote: the name of the block in "Change the “My page” blocks" (just in this window) would be better "Sign out" with the description "An alternative way to sign out."...

**Comment by tunandras** [comment]
Sorry, I forgot to write about the other window.

The block (though physically it could be the same but, from the viewpoint of the user another block) what you can set here 

![change_home_page_block](https://cloud.githubusercontent.com/assets/15856891/15983503/d74aa4b4-2fa9-11e6-85ea-88313aa50fa5.png)

could be on the home page alternatively "Sign in" or "Sign out". That is why I suggested its name in "Change the “Home page” blocks" (just in this window) "Sign in/out", and said the original description is OK.

**Comment by fisharebest** [comment]
The name of the block "Sign in" is used in:

* Control panel -> Manage modules
* Change the "My page" blocks.
* Change the "Home page" blocks

> (just in this window)

It needs to be the same everywhere.  The block does not know how it is being used.

Since we can only have one name, I prefer the simple "Sign in"
