### ISSUE TITLE
Undefined index in new Google Maps code

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#983]
I'm seeing lots of "undefined index: events" errors in line 2039 of the GM module.

$unique_places[$index]['events'] .= $evtStr;

~~Possibly~~ triggered by an individual with no place location data...

**Comment by fisharebest** [comment]
@ddrury - can you take a look at this one?

**Comment by ddrury** [comment]
Ok

**Comment by fisharebest** [comment]
This fixes the bug - but I think I see two issues.

1) places without co-ordinates get a flag a 0N 0W.

2) where an individual has more than one event in the same place, but the events have specific co-ordinates, then the last co-ordinate overwites the first. e.g. a person born and buried in the same village, with exact co-ords for the birth and burial will only get one flag - at the place of burial.
