### ISSUE TITLE
Chart block - too many next generations at once

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#987]
This is a split off of issue #963 

I've set up a pedigree chart block on the homepage.

Loading of the initial pedigree goes well, but clicking on one of the arrows to get the next generation gives strange results.

Instead of one new generation, you always get 3 generations at once, despite of the fact the ajax call asks for 1 (the querystring in the ajax get request:
../hourglass_ajax.php?rootid=I3613&generations=1&type=asc&show_full=1&show_spouse=0)

I think this is caused by the fact in the HourglassController the minimum value of generations is set to 2. When calling 1 it gives the default value of 3 instead:

$this->generations = Filter::getInteger('generations', 2, $WT_TREE->getPreference('MAX_DESCENDANCY_GENERATIONS'), 3);

**Comment by fisharebest** [comment]
I think this was fixed in e4e04c02309230014cd901dd776f1a08e31af91d

**Comment by JustCarmen** [comment]
Sorry missed it. But you are right, this is fixed. Thanks.
