### ISSUE TITLE
Chart block - no lines before empty blocks

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#988]
This is a split off of #963 

![6-6-2016 09-48-30](https://cloud.githubusercontent.com/assets/5641963/15815262/5245a218-2bcc-11e6-84d2-47784d0bf38c.jpg)

This only occurs when placing the chart in a block (homepage/my page). It doesn't happen with the full charts.

**Comment by fisharebest** [comment]
> It doesn't happen with the full charts.

Yes it does.

This chart uses half of the hourglass chart - which has the same layout errors.
