### ISSUE TITLE
Helping translators and users to understand "self"

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#989]
The word "self" appears when hovering the yellow check marks on individual's page in families tab and in sidebar.

![selfs](https://cloud.githubusercontent.com/assets/15856891/15998708/cbe0f5b8-3140-11e6-8a6a-5a59769d53cc.png)

In my opinion something longer phrase in the images' title attribute would be much more informative. Maybe taking into account gender--"himself/herself" could help (or something like that as "lui/elle" is for instance in the French translation) but, in my opinion there would be a bit more understandable for example "the individual himself/herself". Possibly it would mean the most if--since the individual's gender is mostly known--this string would vary depending on their gender: it would be either "the individual himself" or "the individual herself" (and if the gender is unknown, it could be "the individual himself/herself").

Is it possible to expand this phrase somehow? I don't know what would be the best because my English is too week. The only thing I know: it took a long time for me to guess what does "self" means in this context when I met it. Or is it just my problem? Is it my fault? What is your opinion? (A longer explanation sent in private...)

**Comment by tunandras** [comment]
My English is so weak that I didn't know the difference between week and weak... :D

**Comment by fisharebest** [comment]
> My English is so weak that I didn't know the difference between week and weak... :D

:-)

**Comment by fisharebest** [comment]
We could replace "self" with

"himself", "herself" and "themself".

**Comment by tunandras** [comment]
Sorry, how do you mean exactly? You can replace "self" with "himself" and "herself", if the gender known, and you would use "themself", if gender is unknown? Is the third known widely? I mean, the plural variant in this context... I'm learning it recently from you.

Note: my spelling checker in Firefox suggests "them self" or "themselves" instead of "themself".

**Comment by fisharebest** [comment]
> Is the third known widely?

It is in wikipedia :-)
https://en.wikipedia.org/wiki/Singular_they

> Themself was common from the 14th to 16th centuries and its use has increased since about the 1970s or 1980s

My 1983 dictionary lists "himself", "herself", "itself" and "them self" (2 words).
My 2007 dictionary lists "themself" as an alternative to "themselves".

**Comment by tunandras** [comment]
> It is in wikipedia :-)

All right. :-) My English is very poor... as I said...



> We could replace "self" with
> 
> "himself", "herself" and "themself".

Anyway, I like your suggestion. In my opinion it is better than "self". Am I the only one, who is interested in this?

Note: And, since I know personally Németh László (who is developing Hunspell--the spell checker used in Firefox and in LibreOffice) and, usually I send him yearly bug collections, next time I'll send him this too. Exceptionally an English word.  :-)

**Comment by JustCarmen** [comment]
Is it really necessary to have a tooltip with whatever text on the icon? I think it is obvious that the check-mark icon indicates the current individual.

**Comment by tunandras** [comment]
Hi JustCarmen,

> it is obvious that the check-mark icon indicates the current individual.

No doubt, that's my fault, that I didn't start to think, when I met it. I just wanted to guess the translation--what was there already, because I didn't understand. It was "own" in English. That means the translators had no idea.

And when I tried to guess (again: perhaps that would have been better to interpret the graph) I visited other translations and found, that I'm not the only one who doesn't understand. The word "self" in some of the translations (e.g. in some Slavonic languages or Italian) is "I" or "me" in English and the French translation is for example "he/she"--if I understand them well...

That is why I wrote this comment. :-)

**Comment by fisharebest** [comment]
I dislike tooltips.  They do not work with touch-screens and assistive-technology.

IMHO, here we should show the tick icon AND the text.

**Comment by tunandras** [comment]
> IMHO, here we should show the tick icon AND the text.

I agree. The tooltip didn't help. It rather confused me...

**Comment by fisharebest** [comment]
FYI, the new translations will not appear in weblate for a week or two.

**Comment by tunandras** [comment]
> `Fix #989 self - himself/herself/themself`

I like it very much. (Especially after translation...) It's much more than I thought. :-)
