### ISSUE TITLE
"sign-in" versus "sign in"

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#991]
Unfortunately I found a new suspicious phrase what you will probably want to replace: **sign-in** ([in 3 files](https://github.com/fisharebest/webtrees/search?utf8=%E2%9C%93&q=sign-in) and 6 strings [in Weblate](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?q=sign-in&search=substring&source=on&target=on&type=all&ignored=False)) vs. **sign in** (in 10 files and 18 strings [in Weblate](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?q=sign+in&search=substring&source=on&target=on&type=all&ignored=False)).

There is no **sign-out** in either GitHub repository or Weblate.

(I suppose you don't have to worry about `.fa-sign-in` and `.fa-sign-out` css selectors [in font-awesome.min.css file](https://github.com/fisharebest/webtrees/blob/master/packages/font-awesome-4.4.0/css/font-awesome.min.css).)

**Comment by fisharebest** [comment]
"Sign in" is a verb.  e.g. "After you sign in you can edit data"
"Sign-in" is a noun.  e.g. "There was a new sign-in on your account"

http://english.stackexchange.com/questions/49850/sign-in-signin-or-sign-in

**Comment by tunandras** [comment]
Thank you, that is good news... :)
Sorry for my ignorance. I have very much to learn.
