### ISSUE TITLE
Googlemaps unused config item

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#993]
On my recent forays through the googlemaps module, I've noticed that the GM_XSIZE configuration option is not used anywhere - should it be removed?

**Comment by fisharebest** [comment]
...or perhaps we **should** use it???

**Comment by fisharebest** [comment]
...or perhaps we **shouldn't** use the YSIZE???

Do you know the reason for having these?  Originally, I thought they were to allow the maps to fit different themes, but I guess not.

**Comment by ddrury** [comment]
The map div has to have a pixel size either inherited or explicitly set. 
They could be set in the css file but then the admin wouldn't be easily 
able to alter them (does anyone ever do so?). I guess a better solution 
is to make it fully scalable but off the top of my head I can't see how 
to do that without using some javascript.

Regards
David
Please consider the environment before printing this e-mail



------ Original Message ------

**Comment by fisharebest** [comment]
> off the top of my head I can't see how to do that without using some javascript

I think I have a CSS-only solution for this...
