### ISSUE TITLE
Googlemap does not appear

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#994]
Sorry, I can't follow your frequent dialogues so, I can't decide: have you seen that--since the improvement of two affected files in [merge](https://github.com/fisharebest/webtrees/commit/84d33e751b65b41866d26f1a62e1644d2c06e417) #962--the map on Google Maps™ tab doesn't appear on your individual's [demo pages](https://dev.webtrees.net/demo-dev/individual.php?pid=i35&ged=demo)?

**Comment by fisharebest** [comment]
I think you simply need to clear your browser's cache.  e.g. CTRL-F5.

Once these changes are complete, I will rename the file.  This will prevent any users from having this file.

**Comment by tunandras** [comment]
Thanks a lot, I had to clear the cache using "Clear Recent History..." window.
