### ISSUE TITLE
iCalendar/CalDav support for Android/iOS and other 3rd party calendar apps

### ISSUE THREAD

**Issue by DmitrySandalov** [fisharebest/webtrees#995]
iCalendar format is designed to transmit calendar-based data. It is supported by a large number of products, including Google Calendar, Apple Calendar, etc. 

iCalendar support in webtrees would allow us to see events from third party calendar apps.

More about iCalendar here: https://en.wikipedia.org/wiki/ICalendar

iCal was supported in PhpGedView, but it was not working correctly:
https://github.com/fisharebest/webtrees/blob/5bc7b36708d272081ffd2df5658ddf12275447dd/ical.php
https://bugs.launchpad.net/webtrees/+bug/589568
http://phpgedview.sourceforge.net/devdocs/api/PhpGedView/Export/_ical.php.html

It could be a dedicated iCal page where the user selects which data she wants to see. Or we can add a link to iCal to the calendar.php ("On this day") page:
- The user opens calendar.php
- Adjusts the filters (e.g. living individuals, vital records)
- Saves a link to the query to her calendar

In Android third party calendars can be added with this app:
https://play.google.com/store/apps/details?id=org.gege.caldavsyncadapter

More on CalDav:
https://www.webtrees.net/index.php/en/forum/9-request-for-new-feature/19978-caldav-carddav

**Comment by Amgine0** [comment]
Another Android 3rd party calendar app is [DAVdroid](https://play.google.com/store/apps/details?id=at.bitfire.davdroid "At Google Play Store") (also available via [F-droid](https://f-droid.org/repository/browse/?fdfilter=DAVdroid&fdid=at.bitfire.davdroid "F-droid store")) which is [open source](https://gitlab.com/bitfireAT/davdroid "GPL3") and has spun out some interesting libraries for android.

[eluceo/ical](https://packagist.org/packages/eluceo/ical) and [sabre/vobject](https://packagist.org/packages/sabre/vobject) on packagist.

**Comment by fisharebest** [comment]
I don't understand what you want to achieve.

I don't understand why I would want to add historic events to the calendar on my phone.

**Comment by Amgine0** [comment]
A birthday or an anniversary is a historic event, yet it is observed annually ever after.

While I don't get it myself, I have had family members ask if they can get a dump of all the birthdays and anniversaries for their branch from my family tree. I suspect that is what Dmitry is asking for.

**Comment by DmitrySandalov** [comment]
Exactly. This feature can be used as annual reminders of some historic dates: birthdays, anniversaries, maybe deaths for close relatives.

**Comment by Draky50110** [comment]
Suscribing as I'm interested in ICS export, mainly for birthdays purpose :P

**Comment by UksusoFF** [comment]
This feature can be added by module. But anonymous user can't have access to tree data. Because in session.php Webtrees redirect all anonymous to login page.
I want create module which send daily email digest with birthdays but can't because same trouble.

**Comment by UksusoFF** [comment]
Perhaps we can do this after api will be implemented:
https://github.com/fisharebest/webtrees/issues/1665
https://github.com/fisharebest/webtrees/issues/891
