### ISSUE TITLE
Displaying an undefined place causes a GoogleMapsModule error

### ISSUE THREAD

**Issue by Gustine** [fisharebest/webtrees#996]
On my test site, running webtrees 1.7.5, several places are undefined. 
When I attempt to display such a place (Cimetière has no coordinates), the upper level is displayed (Bihorel has) ; that's OK : 
http://gustine.eu/wt3/placelist.php?parent[]=France&parent[]=Normandie&parent[]=Seine-Maritime&parent[]=Bihorel&parent[]=Cimeti%C3%A8re&ged=Riviere-LeDu3

But when I attempt to access the upper level (Bihorel), I get an error : 
http://gustine.eu/wt3/placelist.php?parent[]=France&parent[]=Normandie&parent[]=Seine-Maritime&parent[]=Bihorel&ged=Riviere-LeDu3

/home/gustine/wt3/app/Statement.php:82 SQLSTATE[42000]: Syntax error or access violation: 1064 
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1 #0 /app/Statement.php:82 PDOException("SQLSTATE[42000]: Syntax error or access violation: 1064 
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1") #1 /app/Module/GoogleMapsModule.php:2770 execute([array]) #2 /placelist.php:215 mapScripts(2, 4, [array], '&parent[0]=France&pare…', [array])

**Comment by Gustine** [comment]
I am once again surprised by your reactivity!

**Comment by fisharebest** [comment]
I do my best!
