### ISSUE TITLE
Listing drop-down menu items in alphabetic order

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#997]
Do you want to list drop-down menu items in alphabetic order?

For example in charts' preferences window:

![chart_pref_type_order](https://cloud.githubusercontent.com/assets/15856891/16153467/c072567c-34a6-11e6-8786-aee95f5ca254.png)

or in upcoming events' preferences window:

![upcoming_events_sort_order](https://cloud.githubusercontent.com/assets/15856891/16153481/ccb7c368-34a6-11e6-9c98-c8711035643a.png)

**Comment by fisharebest** [comment]
The list of charts - yes these should be sorted.  (The same as the menu)

For lists of values (e.g. landscape/portrait, yes/no, sort order, etc.), I think the fixed order is more natural and predictable.
