### ISSUE TITLE
Which one do you prefer?

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#999]
There are two appearances of phrase "media viewer": a lower-case in the subtitle and a capitalized in the Help text. Do you want to be one of them?

![media_viewer](https://cloud.githubusercontent.com/assets/15856891/16153708/c747b266-34a7-11e6-9b70-a2513d30afc0.png)

File: [admin trees config.php](https://github.com/fisharebest/webtrees/blob/master/admin_trees_config.php), on line 1047 and line 1052
Weblate: [#2397](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=0e4b0cbe5b9edb8ad3dc966ca46a6d93) and [#2619](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=2e89f050d370c1b7c03d8e6d48fe4b00)

**Comment by fisharebest** [comment]
I prefer lower case.

**Comment by tunandras** [comment]
Thank you very much for your quick answer. I will change it in the translation...
